### ISSUE TITLE
How to extract the last time steps from two or more LSTM networks and add several density layers to form a computational graph?

### ISSUE THREAD

**Issue by cqiaoYc** [deeplearning4j/deeplearning4j#10020]
I want to use 2-3 LSTM networks as feature selectors, extract the last time steps of LSTM networks as the input layer, and then add several density layers to build a computation graph. How can I use a computation graph to build it?

**Comment by agibsonccc** [comment]
@cqiaoYc  please post on the forums. You know this by now. Thanks!
