### ISSUE TITLE
Please ensure that you have an nd4j backend on your classpath. Please see: https://deeplearning4j.konduit.ai/nd4j/backend

### ISSUE THREAD

**Issue by lqscr88** [deeplearning4j/deeplearning4j#10047]
Issue Description
Why are errors still reported when cuda versions are consistent

Version Information
Please indicate relevant versions, including, if relevant:
Deeplearning4j version： 1.0.0-M2.1
Platform information ： windows

the java code：
 public static void main(String[] args) throws Exception {
        // Gets Path to Text file
        String filePath = new ClassPathResource("raw_sentences.txt").getFile().getAbsolutePath();

        log.info("Load & Vectorize Sentences....");
        // Strip white space before and after for each line
        SentenceIterator iter = new BasicLineIterator(filePath);
        // Split on white spaces in the line to get words
        TokenizerFactory t = new DefaultTokenizerFactory();

        /*
            CommonPreprocessor will apply the following regex to each token: [\d\.:,"'\(\)\[\]|/?!;]+
            So, effectively all numbers, punctuation symbols and some special symbols are stripped off.
            Additionally it forces lower case for all tokens.
         */
        t.setTokenPreProcessor(new CommonPreprocessor());

        log.info("Building model....");
        Word2Vec vec = new Word2Vec.Builder()
                //是一个词在语料中必须出现的最少次数。本例中出现不到五次的词都不予学习。
                .minWordFrequency(5)
                //是网络在处理一批数据时允许更新系数的次数。迭代次数太少，网络可能来不及学习所有能学到的信息；迭代次数太多则会导致网络定型时间变长。
                .iterations(1)
                //指定词向量中的特征数量，与特征空间的维度数量相等。以500个特征值表示的词会成为一个500维空间中的点。
                .layerSize(100)
                .seed(42)
                .windowSize(5)
                //告知网络当前定型的是哪一批数据集
                .iterate(iter)
                //将当前一批的词输入网络
                .tokenizerFactory(t)
                .build();

        log.info("Fitting Word2Vec model....");
        vec.fit();

        log.info("Writing word vectors to text file....");

        // Prints out the closest 10 words to "day". An example on what to do with these Word Vectors.
        log.info("Closest Words:");
        Collection<String> lst = vec.wordsNearestSum("day", 10);
        //Collection<String> lst = vec.wordsNearest(Arrays.asList("king", "woman"), Arrays.asList("queen"), 10);
        log.info("10 Words closest to 'day': {}", lst);
    }
![2EB42FB9-9EB1-4cbe-8CB7-38CF2FA42D36](https://github.com/deeplearning4j/deeplearning4j/assets/62920348/e34ddd41-f80b-48d0-98a2-e23ed2d571cd)
![Dingtalk_20231127173744](https://github.com/deeplearning4j/deeplearning4j/assets/62920348/0832dc0a-fd5c-4b99-8c7d-fd21800af633)

**Comment by agibsonccc** [comment]
@lqscr88  I'm not going to support word2vec running on cuda. I"m not sure what your issue is but it's more than likely a local issue with your windows installation. If you have a non word2vec application you're trying to run I'll troubleshoot this further with you. Beyond that since I know for a fact this is not a bug and it's something with your local workstation I'm going to ask that you post on the forums: https://community.konduit.ai/ that's where you ask for help. The issue tracker is only for bugs.

**Comment by lqscr88** [comment]
ok, thank you
