### ISSUE TITLE
Apply to remove dependency deeplearning4j-datasets from project deeplearning4j-core

### ISSUE THREAD

**Issue by RuiBaiXYZ** [deeplearning4j/deeplearning4j#10041]
#### Issue Description

This is not a bug.
When code reading, I found that deeplearning4j-core does not import anything from deeplearning4j-datasets.
Expect to remove this dependency to keep the project concise.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version  Master branch
* Platform information (OS, etc)  N/A
* CUDA version, if used  N/A
* NVIDIA driver version, if in use  N/A

#### Additional Information

 N/A

**Comment by agibsonccc** [comment]
@RuiBaiXYZ for something this simple mind maybe submitting a PR? I'll get to these last few minor issues after I'm done with GPU testing.

**Comment by agibsonccc** [comment]
Merged here: https://github.com/deeplearning4j/deeplearning4j/commit/6082079d30bf877d6306b7db28dc11de5328635a
