### ISSUE TITLE
Init pretrained models HTTP status code 403

### ISSUE THREAD

**Issue by aeiplatform** [deeplearning4j/deeplearning4j#10043]
#### Issue Description

Pretrained models are not available during `initPretrained()`.

#### Version Information

* Deeplearning4j version `1.0.0-M2.1`

#### Additional Information

```
Server returned HTTP response code: 403 for URL: https://dl4jdata.blob.core.windows.net/models/resnet50_dl4j_inference.v3.zip
```

Have the models been moved?

**Comment by timer-180** [comment]
@agibsonccc, is the new repo with training data complete? Is there any updates on this?

**Comment by aeiplatform** [comment]
@timer-180 seems to be working again

**Comment by agibsonccc** [comment]
Thanks for confirming! When I do the migration I'll make sure to have a page on that as well.
