### ISSUE TITLE
error when compiling (exception in thread "main" java.lang.ExceptionInInitializerError)

### ISSUE THREAD

**Issue by AmbyH** [deeplearning4j/deeplearning4j#10062]
I've been trying to use the multilayer network but I run into errors when I try to run my code; my code hasn't ran even once. 
I use MacOS with a M2, running on IntelliJ Idea. 

Gist with error message and pom file:
[https://gist.github.com/AmbyH/96547972936ad70287d7570391a5b8db](https://gist.github.com/AmbyH/96547972936ad70287d7570391a5b8db)

pls help :)

**Comment by agibsonccc** [comment]
@AmbyH could you tell me where you got the idea to use beta7? All versions of the software must be consistent. Please never use more than 1 version and always use the newer release. Stick to 1.0.0-M2.1.

**Comment by AmbyH** [comment]
well im pretty much a beginner, im not really sure what im doing and there arent any tutorials or guides on what im trying to work on so im just testing out things. by what you said, do you mean that I should just delete the dependency of beta7? because after I do that, i get errors on a few of my import statements:
import org.deeplearning4j.datasets.iterator.impl.ListDataSetIterator;
import org.deeplearning4j.nn.api.OptimizationAlgorithm;
import org.deeplearning4j.nn.conf.MultiLayerConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.layers.DenseLayer;
import org.deeplearning4j.nn.conf.layers.OutputLayer;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.deeplearning4j.nn.weights.WeightInit;

**Comment by agibsonccc** [comment]
@AmbyH  just ensure whatever artifact ids you see should always be the latest version. Different versions will not be compatible with each other. For further help please ping me ( @agibosnccc) on the forums: https://community.konduit.ai/ so I get notifications when you need help.  Beta7 is a release that predates the M1. 

Thanks!
