### ISSUE TITLE
CSVVariableSlidingWindowRecordReader not actually splitting by delimiter?

### ISSUE THREAD

**Issue by NTrixner** [deeplearning4j/deeplearning4j#10068]
#### Issue Description

When using CSVVariableSlidingWindowRecordReader to split a large train file into windows, the entries are actually just singular lines of csv data.
When looking into the code of CSVVariableSlidingWindowRecordReader.java, the delimiter never seems to be used.

#### Version Information

DL4J version: 1.0.0-M2.1

**Comment by NTrixner** [comment]
Adding "delimiter" as a second parameter to the "super" call at MyCSVVariableSlidingWindowRecordReader::85 fixes this issue - should I create a PR?

**Comment by agibsonccc** [comment]
@NTrixner  yes please do. Thanks!
