### ISSUE TITLE
Wrong module name for slf4j API specified in module-info.java files

### ISSUE THREAD

**Issue by Erdragh** [deeplearning4j/deeplearning4j#10071]
#### Issue Description
Some java modules in this repository require a non-existent module from slf4j.
For example, here a module named `slf4j.api` is required
https://github.com/deeplearning4j/deeplearning4j/blob/13471cd197a82d89492ec8273690eb7b833a9194/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java9/module-info.java#L23

Which slf4j does not have/export: https://github.com/qos-ch/slf4j/blob/master/slf4j-api/src/main/java9/module-info.java

#### Version Information

* Deeplearning4j version: `1.0.0-M2.1`
* Platform information: Linux x86_64

#### Additional Information

This did not seem to be an issue when I tried to run my code directly via the Gradle `application` plugin, however, the goal is to use this library in a Minecraft mod using the [NeoForge](https://github.com/neoforged) modding environment. When I try to run my code from a mod, NeoForge's launching procedure throws the following exception, before any code is even executed.
```
Exception in thread "main" java.lang.module.FindException: Module slf4j.api not found, required by nd4j.cpu
	at java.base/java.lang.module.Resolver.findFail(Resolver.java:892)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:491)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:297)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:196)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at DevLaunch@1.0.0/net.neoforged.devlaunch.Main.main(Main.java:54)
```

Debugging the `BootstrapLauncher` [on line 196](https://github.com/McModLauncher/bootstraplauncher/blob/863489e5fd99bcca018b53af8e9f8df2391c6390/src/main/java/cpw/mods/bootstraplauncher/BootstrapLauncher.java#L196) and evaluating the various fields there shows `nd4j.cpu`, `org.slf4j` but never `slf4j.api`.

See also this conversation in a support channel on the NeoForge project's official Discord server:
![image](https://github.com/deeplearning4j/deeplearning4j/assets/29674493/e48b239f-eaa3-45fa-980d-5fbd8a895307)

**Comment by Erdragh** [comment]
It seems that this library just depends on an old version of slf4j:
https://github.com/deeplearning4j/deeplearning4j/blob/13471cd197a82d89492ec8273690eb7b833a9194/pom.xml#L229
where a different module name is used. Is there a reason it hasn't been updated?

**Comment by agibsonccc** [comment]
@Erdragh in my PR I've updated it. You can just do dependencyManagemnt in the mean time. If that's your only issue please close this. https://github.com/deeplearning4j/deeplearning4j/pull/10052

**Comment by Erdragh** [comment]
Yes this is my only issue. I’m going to close it then. Could you elaborate on/link to documentation about what you mean by “dependencyManagement”?

**Comment by agibsonccc** [comment]
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html

**Comment by Erdragh** [comment]
Well, I haven't mentioned it, but I'm using Gradle. But also, just overriding/excluding the transitive dependency on slf4j doesn't help with the fact that the module name that's required has changed. I can't just use an older version of slf4j because it's provided by the runtime environment (Minecraft) on which I don't have any influence.

**Comment by agibsonccc** [comment]
I'm a bit confused. I don't think anyone asked you to use an older version.
I linked you the dependencyManagment concept with the understanding that
you know what it would do for you: override the version of the software
being brought in by dl4j. No one's asking you to switch build systems or
use an older version. It's been standard for over a decade now that 3rd
party dependencies themselves have dependencies and they may conflict.
It's why build systems have built in ways of managing that. You just have
to tell the system what to use. Conflict resolution is standard in gradle
too. Just googling brings up:
https://stackoverflow.com/questions/56638350/replicating-maven-dependencymanagement-tag-from-inside-gradle-build

In the future, for any java dev you ever do where you run in to something
like this I'd google "maven concept gradle" or something similar.

**Comment by Erdragh** [comment]
> override the version of the software being brought in by dl4j

Would that change dl4j's and its components' module requirements?

To try and elaborate on the exact issue I'm having again:

DL4J and its components use java modules. These are _required_ to be enforced in the environment I'm in. DL4J and its components have a requirement on the `slf4j-api` module. This module does not exist in newer versions of slf4j, as it's been renamed to `org.slf4j`. The version of slf4j is forced by the environment (Minecraft) and I cannot change it to use a version that does still use the old `slf4j-api` name, which would have been an easy fix.
This results in the bootstrap of the modded Minecraft environment to not even try and start anything because it can't fully resolve the java module requirements.

So the question about dependency management is:
> Does overriding the version of slf4j that dl4j depends on automatically also make it use the new module names?

**Comment by agibsonccc** [comment]
@Erdragh I've never heard of the module system having issues with dependencyManagement/overrides. It shouldn't. The main issue you'd deal with would be api compatibility for..basically any java library. I've never had issues with slf4j unless it's been a backend issue. As long as you're only depending on on api you should be fine.

From the sounds of it, instead of overriding the version you should just do an exclusion and introduce your own to work around the issue.

This should work: https://stackoverflow.com/questions/30540047/how-do-i-write-this-maven-exclusion-code-in-gradle

**Comment by Erdragh** [comment]
Alright, I `exclude` slf4j and some other dependencies now. It didn't fix anything, the module's are still missing.

Then I added various source sets for modules that are missing (not just `slf4j-api`) with dummy `module-info`s (I assume that's what you meant by "introduce your own to work around the issue").

Now NeoForge's bootstrap launcher doesn't complain about missing modules anymore, but during startup the following happened:

https://gist.github.com/Erdragh/39cf4f1d261225d09ea00a2bdbda85d0

Even with the dummy modules, the library won't have the classes it needs, so at this point I'm just at the mercy of waiting for an update that updates the dependencies and module-info files. The `slf4j-api` issue doesn't seem to be the only one with versions/modules, considering #10065 for example.

I don't want to be annoying but the PR with the "baseline set of fixes" has been open for over a year at this point. Is there a release schedule or something similar for which I could look?

**Comment by agibsonccc** [comment]
@Erdragh  yeah unfortunately I have to break this up in to a set of PRs. I've been building out tooling to rewrite a lot  of core components.  The framework's accumulated some technical debt that I'm cleaning up. 

I will start doing that break up next week.

In terms of roadmap, the main focus is stability and interop with some of the newer fast math backends for language models.

What you want is basically just the module part.

Unfortunately beyond that, guaranteed timelines are only for folks who actually support the framework's development.


I've cut custom releases for folks who need something urgently. Otherwise I'm hoping to roll out this rewrite in the next couple of months. 

Since you're not likely in that bucket I can at least assist you with just making the changes you need. I would suggest opening a pull request with what you're looking for.  I'll do what I can to help you with ensuring everything works out. 

For now, I'm still wondering about a workaround for you.  What version of java are you running? 17? I'd be happy to at least help test something for you.

**Comment by Erdragh** [comment]
> I would suggest opening a pull request with what you're looking for

I assume this means into this repo? I've tried setting up the dev env locally, where I've run into multiple problems:
1. Reloading the maven project in IDEA takes ages, presumably linked to these?
   
   ![A bunch of warnings about not being able to download from some specific maven](https://github.com/deeplearning4j/deeplearning4j/assets/29674493/c80735db-f313-4cd0-a744-104fef8b161b)
2. Unresolved maven plugins
   
   ![Error messages about being unable to resolve a certain maven plugin](https://github.com/deeplearning4j/deeplearning4j/assets/29674493/43dac194-75d9-4ec1-8785-3bbb3466dd06)
3. Running `compile` results in the log being spammed with specifically these two kinds of messages:
   ```
   /usr/include/absl/base/internal/nullability_impl.h:56:60: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
   56 |   static_assert(nullability_internal::IsSupportedType<std::remove_cv_t<T>>,
      |                                                            ^~~~~~~~~~~
      |                                                            remove_cv
   ```

   ```
   /usr/include/absl/base/policy_checks.h:79:2: error: #error "C++ versions less than C++14 are not supported."
      79 | #error "C++ versions less than C++14 are not supported."
         |  ^~~~~
   In file included from /usr/include/absl/base/config.h:92,
                    from /usr/include/absl/base/attributes.h:37,
                    from /usr/include/absl/strings/string_view.h:39,
                    from /home/erdragh/Coding/AI/deeplearning4j/libnd4j/blasbuild/cpu/flatbuffers-src/include/flatbuffers/base.h:217,
                    from /home/erdragh/Coding/AI/deeplearning4j/libnd4j/blasbuild/cpu/flatbuffers-src/include/flatbuffers/flatbuffers.h:20,
                    from /home/erdragh/Coding/AI/deeplearning4j/libnd4j/include/graph/scheme/array_generated.h:26,
                    from /home/erdragh/Coding/AI/deeplearning4j/libnd4j/include/array/DataTypeUtils.h:30,
                    from /home/erdragh/Coding/AI/deeplearning4j/libnd4j/include/array/NDArray.h:27,
                    from /home/erdragh/Coding/AI/deeplearning4j/libnd4j/include/helpers/impl/../MmulHelper.h:27,
                    from /home/erdragh/Coding/AI/deeplearning4j/libnd4j/include/helpers/impl/MmulHelper.cpp:25:
   /usr/include/absl/base/policy_checks.h:79:2: error: #error "C++ versions less than C++14 are not supported."
      79 | #error "C++ versions less than C++14 are not supported."
         |  ^~~~~
   ```

   Where I assume that, being on an up-to-date Arch Linux installation my system libraries are just too new to work with the compiling done for dl4j?
   
   The error about C++14 especially confuses me, because I have `gcc` at 14.1.1 and `clang` at 17.0.6

   However, I'm not familiar with javacpp so I don't really know how to resolve these errors.

> What version of java are you running?

Java 21

> I'd be happy to at least help test something for you.

I've made my repo public now: https://github.com/Erdragh/KAI 

The `main` branch has the issue I described initially, the `wacky-workaround` branch is where I did the dummy modules.

**Comment by agibsonccc** [comment]
@Erdragh  I'll be doing some of the modularization work tomorrow. Let me take a closer look at this then. Sorry for the delay.

**Comment by agibsonccc** [comment]
@Erdragh  I took a quick look at your repo. Can you add a small test I can run from intellij?  My only goal will be to run this with java 17 and see what the module errors are so I can push a quick fix for you. Thanks!

**Comment by Erdragh** [comment]
I'm using it in a Minecraft environment which requires Java 21, but I can see what I can do, I'll bump this thread once I have.

**Comment by agibsonccc** [comment]
Your network runner should be enough I think. Just ensure that java 21
triggers the issues as is and it should be an easy fix.

**Comment by Erdragh** [comment]
I've pushed a `module-error` branch to my repo which removes the whole Minecraft stuff. It produces a _different_ module error now, so I'm not certain whether it reproduces the slf4j-api one, but here you go anyway:
```
> Task :run FAILED
Error occurred during initialization of boot layer
java.lang.module.FindException: Error reading module: /home/erdragh/.gradle/caches/modules-2/files-2.1/org.deeplearning4j/deeplearning4j-modelimport/1.0.0-M2.1/243b6fe760e61d75917392c4d61f318716504f1e/deeplearning4j-modelimport-1.0.0-M2.1.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Package org.deeplearning4j.frameworkimport.keras.keras.layers.convolutional not found in module
3 actionable tasks: 2 executed, 1 up-to-date
```
