### ISSUE TITLE
Android BLAS dependency error

### ISSUE THREAD

**Issue by Refikcanmalli** [deeplearning4j/deeplearning4j#1012]
I am sharing example android project for deeplearning4j which fails on finding BLAS dependency files. I have tried to implement JVM flags by editting gradle.properties file with addition of 
```
org.gradle.jvmargs=-Dcom.github.fommil.netlib.BLAS=com.github.fommil.netlib.F2jBLAS 
-Dcom.github.fommil.netlib.LAPACK=com.github.fommil.netlib.F2jLAPACK 
-Dcom.github.fommil.netlib.ARPACK=com.github.fommil.netlib.F2jARPACK
```
code line and it did not work.

Link to project  = https://github.com/Refikcanmalli/dl4j-android.git
Link to full stack trace = https://gist.github.com/Refikcanmalli/b3189184ae41bb9a6999

**Comment by taisukeoe** [comment]
I've confirmed your project runs successfully with above PR in ND4J.

Once above PR is merged, would you please install latest ND4J SNAPSHOT from github source into your local maven repository, and then modify nd4j-x86 version in your project dependencies?

**Comment by Refikcanmalli** [comment]
I have added snapshot of nd4j rc3.9 it pass blas dependency error but new exception is thrown . I am sharing the stack trace https://gist.github.com/Refikcanmalli/5f924e2927d79088d34d

**Comment by agibsonccc** [comment]
We're moving to libnd4j this won't be an issue.
