### ISSUE TITLE
Anyway to get a new release with updated dependencies?

### ISSUE THREAD

**Issue by matthewcummings** [deeplearning4j/deeplearning4j#10151]
#### Issue Description

Please describe our issue, along with:
I'm using the https://mvnrepository.com/artifact/org.deeplearning4j/deeplearning4j-core/1.0.0-M2.1 release of this library but a number of my apps which use it are failing security scans because this project references libraries like `guava` which have new updated versions.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - 1.0.0-M2.
* Platform information (OS, etc) - Linux but I think this affects all OS releases

#### Contributing

Here's my PR: https://github.com/deeplearning4j/deeplearning4j/pull/10152

**Comment by agibsonccc** [comment]
@matthewcummings Unfortunately I've been in the middle of a major rewrite of the underlying c++ (you can see some of it in the last few PRS)
I"m in the middle of getting the basics working again in the unit tests but I'm done with what refactoring/streamlining I want to do.

 As this isn't a specific bug I'll have to close this.  You're welcome to build from source and contribute but the work being done right now is way too many in the weeds for new folks.
 
 For your own use case if you're worried about guava just do a dependency exclusion /override in maven. I'm closing this.

**Comment by matthewcummings** [comment]
OK, sounds good. Thank you for the quick response.
