### ISSUE TITLE
Compatibility Issues Between Deeplearning4j 1.0.0-SNAPSHOT and deeplearning4j-examples Repository (1.0.0-M2.1)

### ISSUE THREAD

**Issue by lyd1992** [deeplearning4j/deeplearning4j#10158]
I am currently using the `master` branch of Deeplearning4j (version `1.0.0-SNAPSHOT`) with commit ID `d91b73488b43cce19cc24a918428dfa08a53cd4b`. However, when trying to use the official [deeplearning4j-examples repository](https://github.com/deeplearning4j/deeplearning4j-examples/tree/master), I encountered issues because the examples rely on Deeplearning4j version `1.0.0-M2.1`.

Due to API changes in the latest `1.0.0-SNAPSHOT` version, some of the Deeplearning4j APIs used in `deeplearning4j-examples` are outdated and result in errors during execution.

- **Expected behavior:** The examples should run successfully with the latest version of Deeplearning4j (`1.0.0-SNAPSHOT`).
- **Encountered behavior:** Some examples fail due to incompatible API changes between `1.0.0-M2.1` and `1.0.0-SNAPSHOT`.

#### Version Information

* **Deeplearning4j version:** `1.0.0-SNAPSHOT` (commit: `d91b73488b43cce19cc24a918428dfa08a53cd4b`)
* **Deeplearning4j-examples version:** `1.0.0-M2.1`
* **Platform information:** (e.g., OS: Linux, Architecture: x86_64&ARM)
* **CUDA version, if used:** Not applicable / or specify version
* **NVIDIA driver version, if used:** Not applicable / or specify version

#### Additional Information

- **Error log or stack trace:** See attached Gist for the full error log: [Gist Link].
- **pom.xml:** The `pom.xml` file of the `deeplearning4j-examples` repository is also attached in this Gist for reference: [Gist Link].

#### Contributing

I would like to know:
1. Is there any plan to update and maintain the `deeplearning4j-examples` repository to support the latest Deeplearning4j `1.0.0-SNAPSHOT` version?
2. If not, what would be the recommended approach to test the latest Deeplearning4j version (`1.0.0-SNAPSHOT`) with examples or other resources?

If needed, I am willing to contribute by updating the examples repository for compatibility with the latest Deeplearning4j version. Guidance on the best approach to do so would be appreciated.

Thank you!
<img width="725" alt="1733292422114" src="https://github.com/user-attachments/assets/7e094adb-38ef-4946-8e80-ef99cf40b70a">

**Comment by agibsonccc** [comment]
@lyd1992 yes that's expected. The most I'd really do right now if you want to run the examples from source is fork them for now and update your branch. When the software is stable and released the examples will be updated appropriately.

Also please note master is very much in a WIP state yet. I'd stick to M2.1 for now unless you're looking to contribute in some way.

 I'm closing this as it's a known issue and intended. If you want specific help with contributing to the software it'd be appreciated but please do take that up on the forums. Otherwise please use M2.1. Thanks!
