### ISSUE TITLE
ModelSerializer.writeModel causes exception writing to a closed stream

### ISSUE THREAD

**Issue by Siebje** [deeplearning4j/deeplearning4j#10154]
#### Issue Description

To reproduce:
- Call ModelSerializer.writeModel(Model, OutputStream) after setting up a model to write to a file output

Expected:
- The file is saved to disk

Actual:
- IOException is thrown because DataOutputStream.close() calls DataOutputStream.flush(), but the underlying stream is already closed

#### Version Information

Please indicate relevant versions, including, if relevant:

* DL4J: 1.0.0-M2.1
* Windows 11

#### Additional Information

The error occurs because the code wraps a ZipOutputStream in a DataOutputStream. In one of the last lines, the ZipOutputStream is passed to an external write call, which automatically closes the stream. Because the ZipOutputStream is wrapped, it doesn't notify its outside wrapper (the DataOutputStream) that the underlying stream is closed, which causes the issue.

This can be solved fairly simply by passing the DataOutputStream to all the native write calls instead of passing the ZipOutputStream.

**Comment by agibsonccc** [comment]
@Siebje  if you don't mind filling out the ECA please feel free to submit a PR to get the credit. Thanks!

**Comment by Siebje** [comment]
@agibsonccc Yes, thanks. I think I have filled out all the required docs, and I've rebased all my commits to include the signature. I hope it's good to go now.
