### ISSUE TITLE
Failed to Load H5 Model

### ISSUE THREAD

**Issue by xqi-nr** [deeplearning4j/deeplearning4j#10161]
#### Issue Description

- expected behavior: 
   I develop a java service and build it into a runnable docker image based on ubuntu:22.04. The service is supposed to load a NN model which is trained by TF+Keras in Python and is saved as an h5 model file. I expect the Java service should load the model in h5 file successfully during start.

- encountered behavior: I see the following error when the Java code loads the Keras model in h5 file 

```
Warning: Versions of org.bytedeco:javacpp:1.5.8 and org.bytedeco:hdf5:1.12.1-1.5.7 do not match.
2024-12-17 06:38:31,122{UTC} [main] WARN  o.d.n.m.keras.utils.KerasModelUtils - Could not read keras backend used (no backend field found) 

Keras major version has to be either 1 or 2 (3 provided). Please file an issue at https://github.com/eclipse/deeplearning4j/issues.
```

Could anyone help take a look how can I fix the issue? 
Thank you in advance.
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: org.deeplearning4j:deeplearning4j-core:1.0.0-M2.1
* Platform information (OS, etc): 
   Mac OS X 14.7.1 aarch64
   Gradle version: Gradle 8.4
   Java Version: 21
   
   
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

```
    implementation "org.deeplearning4j:deeplearning4j-core:1.0.0-M2.1"
    implementation "org.nd4j:nd4j-native:1.0.0-M2.1"
    implementation "org.nd4j:nd4j-tensorflow:1.0.0-M2.1"
    implementation "org.bytedeco:tensorflow-platform:1.15.5-1.5.8"
```

**Comment by agibsonccc** [comment]
@xqi-nr use keras 1 or 2. It says right in the error. I'm closing this. The resolution is just a downgrade.
