### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Could not find jnind4jcpu in class, module, and library paths

### ISSUE THREAD

**Issue by xqi-nr** [deeplearning4j/deeplearning4j#10163]
#### Issue Description

- expected behavior: 
   I develop a java service and build it into a runnable docker image based on ubuntu:22.04 image. My laptop is Mac OS X 14.7.1 aarch64 with M1 chip. The service is supposed to load a NN model which is trained by TF+Keras (Tensorflow 2.15.0 and Keras 2) in Python and is saved as an h5 model file. I expect the Java service should load the model in h5 file successfully during start.

- encountered behavior: I see the following error when the Java code loads the Keras model in h5 file 

```
Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: https://deeplearning4j.konduit.ai/nd4j/backend
        at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:107)
        at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:41)
        ... 37 more
Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
2024-12-19T03:05:13,248+0000 [1 21] com.newrelic.agent.core.CoreServiceImpl INFO: JVM is shutting down
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2458)
2024-12-19T03:05:13,250+0000 [1 21] com.newrelic.agent.core.CoreServiceImpl INFO: New Relic Agent has shutdown
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
        at java.base/java.lang.System.loadLibrary(System.java:2063)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1800)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1402)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1214)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
        at org.nd4j.linalg.cpu.nativecpu.bindings.Nd4jCpu.<clinit>(Nd4jCpu.java:14)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:534)
        at java.base/java.lang.Class.forName(Class.java:513)
        at org.nd4j.common.config.ND4JClassLoading.loadClassByName(ND4JClassLoading.java:62)
        at org.nd4j.common.config.ND4JClassLoading.loadClassByName(ND4JClassLoading.java:56)
        at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:97)
        ... 38 more
Caused by: java.lang.UnsatisfiedLinkError: Could not find jnind4jcpu in class, module, and library paths.
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1767)
        ... 48 more
```

Could anyone help take a look how can I fix the issue? 
I notice this issue https://github.com/deeplearning4j/deeplearning4j/issues/9860 but it cannot help in my case.

Thank you in advance.
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: org.deeplearning4j:deeplearning4j-core:1.0.0-M2.1
* Platform information (OS, etc): 
   Mac OS X 14.7.1 aarch64 with M1 chip
   Gradle version: Gradle 8.4
   Java Version: 21
   
   
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

```
    implementation "org.deeplearning4j:deeplearning4j-core:1.0.0-M2.1"
    implementation "org.nd4j:nd4j-native-platform:1.0.0-M2.1"
```

**Comment by agibsonccc** [comment]
Closing this again. There's no hdf5 implementation for mac arm64 only the nd4j native cpu bindings. Convert it on another platform. 

The next release should have one available. (Sorry folks usually always ask that)

 No I don't have a guaranteed timeline on when that is. 

Just convert it on another platform for now. You only need to convert it once.

**Comment by xqi-nr** [comment]
> Closing this again. There's no hdf5 implementation for mac arm64 only the nd4j native cpu bindings. Convert it on another platform.
> 
> The next release should have one available. (Sorry folks usually always ask that)
> 
> No I don't have a guaranteed timeline on when that is.
> 
> Just convert it on another platform for now. You only need to convert it once.

Thanks for the quick reply. What does it mean for "convert it on another platform "?

**Comment by agibsonccc** [comment]
Literally anywhere else. Windows, Linux Mac Intel. If you read the errors
we output you can infer what the issues are.

**Comment by SourceSeeker-SameOrigin** [comment]
when upgrade nd4j for "Mac M2 arch arm64"?  Sorry, I also encountered a similar problem, I tried to manually compile nd4j, but I also encountered many problems

**Comment by agibsonccc** [comment]
@Dilemmacpy  you need to use nd4j-native with the macosx-arm64 suffix. You can't just use nd4j-native-platform. Unfortunately that shortcut mostly assumes intel based platforms. You don't need to manually compile it.

**Comment by SourceSeeker-SameOrigin** [comment]
But I use "DL4J M2 &amp; ND4J-Native-platform" still prompt "no jnilib...dylib", the "jnilib....dylib" is not exist
&nbsp;


慕雨笙歌诉清风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Adam ***@***.***&gt;; 
发送时间: 2025年1月9日(星期四) 凌晨5:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [deeplearning4j/deeplearning4j] java.lang.UnsatisfiedLinkError: Could not find jnind4jcpu in class, module, and library paths (Issue #10163)














 
@Dilemmacpy  you need to use nd4j-native with the macosx-arm64 suffix. You can't just use nd4j-native-platform. Unfortunately that shortcut mostly assumes intel based platforms. You don't need to manually compile it.

**Comment by agibsonccc** [comment]
@Dilemmacpy  I'm not going to comment on this again. If you're refusing to upgrade I can't help you.  M2.1 has been out for years now and has been stable.  I specifically told you NOT to use nd4j-native-platform and *why* if you aren't sure what I mean please use baidu translate to try to understand. I'm sorry there is a language barrier.

**Comment by sobhunv** [comment]
Hello , just for sharing, I tried with these dependencies on Mac Os M1, it works: 
build.gradle.kts file:

    val dl4jVersion = "1.0.0-M2.1"
    implementation("org.deeplearning4j:deeplearning4j-core:$dl4jVersion")
    implementation("org.nd4j:nd4j-api:$dl4jVersion")
    runtimeOnly("org.nd4j:nd4j-native-platform:$dl4jVersion")
    implementation("org.datavec:datavec-api:$dl4jVersion")
    implementation("org.nd4j:nd4j-native:$dl4jVersion:macosx-arm64")
    implementation("org.bytedeco:openblas:0.3.21-1.5.8:macosx-arm64")

Thanks
V.S

**Comment by SourceSeeker-SameOrigin** [comment]
Thanks

**Comment by agibsonccc** [comment]
@sobhunv you don't need nd4j-native-platform there. nd4j-native-platform is just an aggregator pom for intel platforms that brings in openblas. If you add openblas without the classifier to that you can do the same thing.

@Dilemmacpy if something wasn't working you could have pinged again.  I mentioned you needed to upgrade and you never followed up. 

@sobhunv  is using the new version like I mentioned and just did what I mentioned.

M2 *specifically* had issues that needed to be fixed.
