### ISSUE TITLE
Test time forward pass may (unnecessarily) store activations

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1021]
During network training: activations are stored during the forward pass, so they can be used later in backprop step.

Layer inputs also appear to be stored at test time, even though they won't be reused later.
For example:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/BaseLayer.java#L354

This appears to cause a (small, constant size) memory leak.

**Comment by raver119** [comment]
We have this concept implemented long ago, it can be turned on/off via CacheMode option.
