### ISSUE TITLE
Fix variable length time series + bidirectional LSTM

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1030]
The new bidirectional LSTM implementation will not work correctly with the current variable length time series (masking) implementation.
The issue is that the bidirectional LSTM reverse pass will be receiving non-zero activations from times beyond the end of the shorter/padded time series. This will likely adversely affect network performance.

**Comment by agibsonccc** [comment]
Did you ever get around to this?

**Comment by AlexDBlack** [comment]
Still needs to be done.

**Comment by agibsonccc** [comment]
Still relevant?

**Comment by AlexDBlack** [comment]
Implemented here: https://github.com/deeplearning4j/deeplearning4j/pull/2699
Will  be merged soon.
