### ISSUE TITLE
Array form of wordsNearest seems not to be working, at least when the array only has 1 element

### ISSUE THREAD

**Issue by mikegwf1** [deeplearning4j/deeplearning4j#1048]

**Comment by mikegwf1** [comment]
Look at this gist https://gist.github.com/mikegwf1/dc8afd05e9fec8c4b379
which I generated with this code: https://gist.github.com/mikegwf1/493a7af031a97f74604f
The first set of results are generated using the "fast" array form of wordsNearest where the first array contains only 1 element and the second array is empty
the second set of results are generated using the scalar form of wordsNearest


The results are not the same. The array form of the method seems to be missing terms. If you look at "earnings", for example, the retrieved term "results" appears in the second set with a high similarity, but it is missing from the first set.

These results were generated with the following model:

https://drive.google.com/open?id=0B_ok6MxSyATZWjN0d2pRTG9JRlU

**Comment by raver119** [comment]
Fixed https://github.com/deeplearning4j/deeplearning4j/pull/1052

Will be merged soon.

Thanks for flagging this issue.
