### ISSUE TITLE
Documentation: (technical) details and guidelines for distributed training

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1051]
Need to document things like:
- how various hyperparameters like .iterations() and truncated BPTT work on Spark
- Training data for Spark: Canova RecordReaders, sequence files
- Spark specific hyperparameters
- Some training guidelines and suggestions (i.e., differences between local and distributed training, how to tune Spark learning, warm starting etc)

**Comment by jpatanooga** [comment]
+1

definitely needed

**Comment by tomthetrainer** [comment]
+1 absolutely, I think a spark architecture page with diagrams and the like is needed.

**Comment by tomthetrainer** [comment]
Is there a ticket or design doc describing the spark architecture?

**Comment by agibsonccc** [comment]
@tomthetrainer http://deeplearning4j.org/spark

**Comment by tomthetrainer** [comment]
I assume the two pages, 
http://deeplearning4j.org/spark
and
http://deeplearning4j.org/spark-gpus 

cover this issue.
