### ISSUE TITLE
Zoom for Histogram Listener

### ISSUE THREAD

**Issue by 125626748** [deeplearning4j/deeplearning4j#1057]
I want to zoom In/Out in the Histogram Listener to see the scores recently.

Now the UI is like the image below.

![coord](https://cloud.githubusercontent.com/assets/8222739/12448999/179556a0-bfb5-11e5-8344-1b1d96a8a24f.png)

Since the range of the scores over the entire iterations is large, so it's barely visualizable what's going on for recent iteration, If I can zoom in like the image below, I can get a sense that the score is still diminish in this smaller scale.

![after](https://cloud.githubusercontent.com/assets/8222739/12449053/749e7a02-bfb5-11e5-93b1-75f21d73d037.png)

**Comment by raver119** [comment]
Implemented in: https://github.com/deeplearning4j/deeplearning4j/pull/1061
