### ISSUE TITLE
There is a way to get the position of classified shapes?

### ISSUE THREAD

**Issue by yuripourre** [deeplearning4j/deeplearning4j#1059]
The [video example](https://github.com/deeplearning4j/dl4j-0.4-examples/blob/master/src/main/java/org/deeplearning4j/examples/video/VideoClassificationExample.java) works perfectly but I would like to know the position (x,y,width,height) of the classifed shapes. Is it possible?

**Comment by agibsonccc** [comment]
We could work on it. File an issue on deeplearning4j/deeplearning4j if you're interested.

**Comment by AlexDBlack** [comment]
One idea that comes to mind: look for the index of the maximal activation for the CNN filters in the upper-most CNN layer. (or: maybe do a softmax average on the filter activations).
hopefully one of the filters corresponds approximately to each shape.
You would want to mess with the network structure to maintain the original image size... so no max pooling, then add padding on the CNN layers. The position of max activations / softmax average should then correspond to the x/y position (pixels) in the original image.

**Comment by yuripourre** [comment]
Thank you for the answers, I really need this feature.

I will open an issue.
