### ISSUE TITLE
Cross-build modules in deeplearning4j-scaleout for different versions of Scala

### ISSUE THREAD

**Issue by Ingwar** [deeplearning4j/deeplearning4j#1062]
Currently modules in `deeplearning4j-scaleout` (`deeplearning4j-scaleout-akka` and all modules in `spark`) are tied to the specific version of Scala, 2.10.4, which makes their usage from Scala applications hard. It would be great to have this modules build for different Scala versions (at least, 2.10 and 2.11). It also would be nice to have Scala version embedded in artifacts id's in a way compatible with sbt (e.g., `dl4j-spark_2.11`).

**Comment by Ingwar** [comment]
It also looks like that `dl4j-spark` indirectly locked on Scala version via `canova-spark`, so, probably, deeplearning4j/canova#113 should be resolved first.

**Comment by agibsonccc** [comment]
No more akka dep. Not relevant anymore.
