### ISSUE TITLE
Configuration json change applied correctly

### ISSUE THREAD

**Issue by 125626748** [deeplearning4j/deeplearning4j#1066]
Say I save my old model as json & parameters to disk as a checkpoint.
Later I change some configuration in the json and read it to run a new model.
Is this change applied correctly to the new model?

**Comment by agibsonccc** [comment]
It would be yes. We already cover model persistence:

http://deeplearning4j.org/modelpersistence

We save the config and the model separately.

**Comment by 125626748** [comment]
Thanks
