### ISSUE TITLE
Review parameter initialization for RBMs/DBNs

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1068]
This page describes an autoencoder architecture built from RBM layers. http://deeplearning4j.org/deepautoencoder.html
The documentation notes that:
"Those layers initially have the same weights as their counterparts in the pretraining net, except that the weights are transposed; i.e. they are not initialized randomly.)"
The sample architecture provided there doesn't actually do this; the parameters for each layer are just initialized randomly. Furthermore, as far as I know, this functionality is not yet implemented in MultiLayerNetwork or elsewhere.

**Comment by tomthetrainer** [comment]
Alex, 

Please clarify what you mean by "this functionality is not yet implemented in MultiLayerNetwork or elsewhere" 

If you meant non-random weight initialization, I fixed that. 

If you meant a broader "this" let me know,

**Comment by AlexDBlack** [comment]
I meant the functionality of the first and last layers having the same (transposed) weights, second and second last, etc. I'm not sure if that's the expected behaviour as per the literature or not - cc @nyghtowl who has been looking at RBMs recently.

**Comment by nyghtowl** [comment]
The functionality that Alex listed above regarding transposing the weights between the first and last layer and then the subsequent layers as you move into the net has not been built into RBM yet. Focus on recent up dates was to get RBM and AutoEncoders working.

Needs to be added and then it can be documented. Thus, noting it as an enhancement.

**Comment by tomthetrainer** [comment]
Any recent changes to RBM's DBN's that should be added to that page?

**Comment by nyghtowl** [comment]
No additional changes right now

**Comment by tomthetrainer** [comment]
This is complete
