### ISSUE TITLE
Add an easy way to turn a Word2Vec into an RDD for Spark (and reverse)

### ISSUE THREAD

**Issue by tobh** [deeplearning4j/deeplearning4j#1070]
It would be great if there would be an easy way to serialize a Word2Vec independent of size (so using it components) to an RDD stream (and reverse) to allow saving abitrary sized Word2Vecs using Sparks default methods on RDD streams.

I can re-use part of the code in WordVectorSerializer to do this but it would be nice to have a very simple way to do it so there is no ambiguity on how to use it and so you can be sure to reconstruct a valid Word2Vec (and if necessary make it immutable so it can't be trained with more data).

**Comment by raver119** [comment]
Text serialization for Spark-based w2v models was added: https://github.com/deeplearning4j/deeplearning4j/pull/1084

This allows you to save/load WordVectors using InputStream and OutputStream.

More improvements are still incoming.

**Comment by raver119** [comment]
Some clarification needed.

At this moment assumed scenario is: 
- You build model somehow (using spark or standalone)
- You serialize model using files or OutputStream (Hadoop FSDataOutputStream should work too)
- You deserialize w2v instance, and use it. Locally or using broadcast for spark.

Is your use scenario different somehow?

**Comment by raver119** [comment]
This issue is probably solved with 3 available model serialization methods:

1. Java binary serialization is available.
2. TXT serialization into any output stream.
3. S3ModelSave working properly too now.

So i'm closing this issue for now. If you'll have any additional feature requests - please reopen this issue and add more details.
