### ISSUE TITLE
Enhance Spark Word2Vec to allow more configurability and use a builder for it to make it safe

### ISSUE THREAD

**Issue by tobh** [deeplearning4j/deeplearning4j#1071]
E.g. add a builder similar to the default Word2Vec implementation that allows minimial word counts etc to be configured. It should use a builder like the default version to allow verification and avoid miss-use.

**Comment by raver119** [comment]
Implemented: https://github.com/deeplearning4j/deeplearning4j/pull/1084

Should be available with rc3.9 release

**Comment by tobh** [comment]
Great. Thanks.
