### ISSUE TITLE
Add an easy way to get classified shapes' position

### ISSUE THREAD

**Issue by yuripourre** [deeplearning4j/deeplearning4j#1072]
As I pointed in #1059 the video example works pretty good but I am trying to classify/retrieve multiple shapes in an image.

It would be awesome if there is an easy way to get shape's position like (x,y,width,height).

Thank you for this great library

**Comment by yuripourre** [comment]
@agibsonccc: Can you please give me a hint on where to start?

Later I will think about the @AlexDBlack suggestion.

**Comment by AlexDBlack** [comment]
one other idea: you can try occluding parts of the image, and watch the activations. See for example http://cs231n.github.io/understanding-cnn/

**Comment by yuripourre** [comment]
Thank you very much for the link, it will be very useful.

**Comment by agibsonccc** [comment]
We're going to start using javacv which should allow this.

**Comment by saudet** [comment]
Wouldn't that be more something along the lines of https://github.com/rbgirshick/py-faster-rcnn?
