### ISSUE TITLE
Measuring the performance metric of the DeepAutoencoder

### ISSUE THREAD

**Issue by alexde989** [deeplearning4j/deeplearning4j#1074]
I am trying to implement an autoencoder after readting the documentation given over here-:
http://deeplearning4j.org/deepautoencoder.html

I am trying to follow this example
https://github.com/deeplearning4j/dl4j-0.4-examples/blob/master/src/main/java/org/deeplearning4j/examples/deepbelief/DeepAutoEncoderExample.java

But my problem is that this example does not provide a Evaluation metric on how well the auto encoder is doing.

Can someone supply the code for the evaluation metrics(F1 score, precision, recall) so that I know exactly how well this example is performing ?

**Comment by agibsonccc** [comment]
Unsupervised. Not possibly by definition.
