### ISSUE TITLE
Document necessity to augment Spark classpath in order to get OpenBLAS support

### ISSUE THREAD

**Issue by Ingwar** [deeplearning4j/deeplearning4j#1079]
To get OpenBLAS support in Spark environment netllib should be in the spark classpath. The easiest way to achieve this is to add the application fat JAR to the Spark classpath (via `--driver-class-path` for local runs and, probably `spark.executor.extraClassPath` for clusters).

I think, it should be documented.

**Comment by chrisvnicholson** [comment]
added to our spark.html page
