### ISSUE TITLE
WordVectorSerializer.readParagraphVectorsFromText adds all words to the list of labels

### ISSUE THREAD

**Issue by davidtinker** [deeplearning4j/deeplearning4j#1083]
The bug is here (approx line 437):

                } else if (split[0].equals("E")) {
                    // we have usual element, aka word here
                    word.setSpecial(false);
                    word.markAsLabel(false);
                    labels.add(word.getLabel()); // this should be in the label branch only

I will send a PR in a bit.

**Comment by raver119** [comment]
Yea, wrong order. Ty. I've just fixed it.

**Comment by davidtinker** [comment]
That was quick! Thanks a stack!
