### ISSUE TITLE
Monitor tools for Spark-based learning

### ISSUE THREAD

**Issue by Ingwar** [deeplearning4j/deeplearning4j#1086]
As far as I can understand, it's not possible to use existing iteration listeners like `ParamAndGradientIterationListener` or `ScoreIterationListener` when model is trained on Spark. I think, having some tools to monitor distributed learning is important thing for framework with heave accent on data parallelism and distributed systems.

**Comment by raver119** [comment]
This issue will be addressed within this branch: https://github.com/deeplearning4j/deeplearning4j/pull/1133

We'll provide two options:
- Separate executable UiServer, powered with dropwizard.
- Servlet WAR package compatible with Tomcat etc.

So, when running training at spark cluster, you'll be able to provide URL for UiServer instance, which be used to collect reports from your network (or from multiple training processes)

**Comment by raver119** [comment]
Implemented. Will be merged into master soon, and will be available at rc3.9.
