### ISSUE TITLE
Overload NeuralNetConfiguration.Builder's list method to accept an Array of Layers

### ISSUE THREAD

**Issue by wmeddie** [deeplearning4j/deeplearning4j#1092]
In the current implementation of NeuralNetConfiguration.Builder() it's easy to add a new layer and forget to update the number of layers in the configuration.  Just accepting an Array of layers would be a good shortcut for defining a simple flat set of layers.

    MultiLayerNetwork model = MultiLayerNetwork(new NeuralNetConfiguration.Builder()
        .seed(123)
        .iterations(10)
        .optimizationAlgo(OptimizationAlgorithm.LINE_GRADIENT_DESCENT).learningRate(0.1)
        .list(new Layer[] {
            new DenseLayer.Builder().nIn(100).nOut(1000).activation("relu").build(),
            new OutputLayer.Builder(LossFunction.NEGATIVELOGLIKELIHOOD)
                .nIn(1000).nOut(10).activation("softmax").weightInit(WeightInit.XAVIER).build()
        }).build()
    )

**Comment by AlexDBlack** [comment]
See: https://github.com/deeplearning4j/deeplearning4j/pull/1095
that PR adds a varargs list method, so you can do things like
```java
.list( new DenseLayer.Builder()...build(),
new Outputlayer.Builder()...build())
```
