### ISSUE TITLE
Review API for layer activation functions (via enum, custom activation functions)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1093]
At present: layer activation functions are specified via a String. Using an enum for the common activation functions would be easier.

Additionally: allow for custom activation functions to be used in a network (activation functions not defined in ND4J main code)

**Comment by huitseeker** [comment]
@AlexDBlack @eraly I think this was fixed by https://github.com/deeplearning4j/deeplearning4j/commit/41ef334174cecb3f2df346863a3c30091527c58a

**Comment by AlexDBlack** [comment]
Yes, activations were overhauled a while ago; this should have been closed then.
