### ISSUE TITLE
Need example for AutoEncoder

### ISSUE THREAD

**Issue by alexde989** [deeplearning4j/deeplearning4j#1098]
I am new to Ml and i have to use dl4j in my project now.

is it possible to get a simple example of an AutoEncoder in dl4j that does 
Input -> Encoding -> View Encoded Output

Encoded Output -> Decoding -> view Decoded output

**Comment by chrisvnicholson** [comment]
Please see our stacked autoencoder example: https://github.com/deeplearning4j/dl4j-0.4-examples/tree/master/src/main/java/org/deeplearning4j/examples/autoencoder
