### ISSUE TITLE
K-fold cross validation

### ISSUE THREAD

**Issue by zzyxzz** [deeplearning4j/deeplearning4j#1099]
A proper function to do k-folder cross validation would be good for evaluation.
Thanks.

**Comment by soilad** [comment]
#### Updates?
Guys an updates as to when this enhancement will be out?

**Comment by agibsonccc** [comment]
Implement it yourself? We don't have it on the immediate roadmap yet.

**Comment by soilad** [comment]
Oh. 
Fine i guess I'll work it out then.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/blob/63d6e2520acec97bce5a052512d1a73163163fd1/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/api/iterator/KFoldIterator.java
