### ISSUE TITLE
Word2Vec : odd formats can lead to misleading results 

### ISSUE THREAD

**Issue by sebastiennoir** [deeplearning4j/deeplearning4j#1100]
As a newbie, I tried to use the sample file [text8](http://mattmahoney.net/dc/text8.zip) also used in Spark ML examples.
I ran into trouble because the file is a 1 line file of 100Mo words. This took more that 15 hours to process on a decent machine.
It would be good to have a warning for this kind of odd input, thus avoiding misleading results.

**Comment by michellemay** [comment]
Indeed, spark does not cope well with one-liners like that.   Here, we modified cleanup perl script to output one line per paragraph of the original text of this corpus.

**Comment by raver119** [comment]
As temporary solution warning on misaligned input was added.

General solution to be decided.
