### ISSUE TITLE
Word2Vec LookupTable documentation error

### ISSUE THREAD

**Issue by Habitats** [deeplearning4j/deeplearning4j#1106]
I'm going through the Word2Vec examples, but I cannot get the following code to work:

```
WeightLookupTable weightLookupTable = wordVectors.lookupTable();
Iterator<INDArray> vectors = weightLookupTable.vectors();
INDArray wordVector = vectors.getWordVectorMatrix("myword");
double[] wordVector = vectors.getWordVector("myword");
```

`vectors` is an `Iterator`, and does not have the `getWordVectorMatrix` etc methods. The methods do however belong to `Word2Vec`, so I suppose it's just supposed to be `wordVectors` (referring to the `Word2Vec` instance), and not `vectors` on the last two lines.

**Comment by raver119** [comment]
Could you please point me to the place, where you got this piece of code?

**Comment by Habitats** [comment]
Oh, yeah of course. http://deeplearning4j.org/word2vec.html

**Comment by raver119** [comment]
Fixed. 

Thanks for pointing this out.
