### ISSUE TITLE
Two implementations of ClusterSet class

### ISSUE THREAD

**Issue by rohanar** [deeplearning4j/deeplearning4j#1107]
org.deeplearning4j.clustering.cluster.ClusterSet AND org.deeplearning4j.clustering.ClusterSet

**Comment by rohanar** [comment]
getDistanceFunction() is available only in org.deeplearning4j.clustering.ClusterSet

**Comment by AlexDBlack** [comment]
Thanks. Removed duplicate copies:
https://github.com/deeplearning4j/deeplearning4j/pull/1108
Remaining version doesn't have getDistanceFunction(), but has getAccumulation() which seems equivalent (though String vs. class). At any rate, I deleted the ones that is not used anywhere.
