### ISSUE TITLE
results of Word2VecRawTextExample look random

### ISSUE THREAD

**Issue by danielnaber** [deeplearning4j/deeplearning4j#1109]
I run the `Word2VecRawTextExample`, changing only the output path, then `TSNEStandardExample` changing its input path so it works on the result of `Word2VecRawTextExample`. Output at the end is `o.d.plot.Tsne - Error at iteration 99 is -2339546.0951366173`. I've changed the pom.xml to use Java 8 because I need that for coming experiments.

Result of t-sne doesn't look like e.g. numbers are close together (only showing a few numbers here):

    -185.7744967772112,-53.83800111329771,two 
    446.80788151044163,72.97290252143095,one 
    -88.67127468964938,894.7182802651655,three 
    346.01074122547953,638.493961875932,four

Screenshot of gnuplot (also only a few words, as otherwise it's unreadable without tuning gnuplot): http://danielnaber.de/tmp/dl4j/graph.png

Other files (no changes from git other than path and Java 8): http://danielnaber.de/tmp/dl4j/pom.xml, http://danielnaber.de/tmp/dl4j/Word2VecRawTextExample.java, http://danielnaber.de/tmp/dl4j/TSNEStandardExample.java

**Comment by danielnaber** [comment]
The problem seems to be in the t-SNE example, not in the word2vec example. I think so because when I add the result of the word2vec example (http://danielnaber.de/tmp/dl4j/word2vec-test-data.csv and http://danielnaber.de/tmp/dl4j/word2vec-test-labels.csv) to an online t-SNE (http://cs.stanford.edu/people/karpathy/tsnejs/csvdemo.html), it works nicely, e.g. day, night, week, and year are nicely grouped (I stopped the online t-SNE after about 1000 iterations).

**Comment by raver119** [comment]
Yep, there were two bugs in our TSNE. Visualization got fixed, and second one, TSNE is queued up for fixing now.

**Comment by Milanvdm** [comment]
TSNE seems to be bugged for me as well: 
output logs: https://gist.github.com/Milanvdm/a50ae2f7288ca1ac25b8
code I use: https://gist.github.com/Milanvdm/fd872d1fc6ba34acccb3

**Comment by raver119** [comment]
T-SNE seems to be fixed: https://github.com/deeplearning4j/deeplearning4j/pull/1133

Will be merged into master later, though.
