### ISSUE TITLE
Word2Vec doc issue

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#1113]
On page dedicated to word2vec, we need to explain people, that Word2Vec expects input aligned to 1 sentence per line, due to the nature of algorithm. So, if someone is going to use text in wrong format (like whole corpus on 1 line, or something like that), he'll get into troubles. That's why training corpus should be split into sentences prior to feeding it to the Word2Vec. 

Any method will work for that: opennlp tools, custom sentence boundary detectors. Even default java implementations will work better then unformatted input.

**Comment by raver119** [comment]
P.s. if someone's interested why is that.

If average sentence contains 6 words, and window size is 5, maximum theoretical number of 10 skipgram rounds will be achieved on 0 words. Sentence isn't long enough to have full window set with words. Rough maximum number of 5 sg rounds is available there for all words in such sentence. 

But if your "sentence" is 1000k words length, you'll have 10 skipgram rounds for every word in this sentence, excluding the first 5 and last five. So, you'll have to spend WAY more time building model + cooccurrence statistics will be shifted due to the absense of sentence boundaries.

**Comment by raver119** [comment]
One more "popular" issue to be covered there:

Memory use for Word2Vec:
The major memory consumer in w2v is weghts matrix. Math is simple there: NumberOfWords x NumberOfDimensions x 2 x DataType memory footprint.

So, if you build w2v model for 100k words using floats, and 100 dimensions, your memory footprint will be 100k x 100 x 2 x 4 (float size) = 80MB RAM just for matri + some space for strings, variables, threads etc.

If you load pre-built model, it uses roughly 2 times less RAM then during build time, so it's 40MB RAM.

And the most popular model used so far is Google News model. There's 3M words, and vector size 300. That gives us 3.6GB only to load model. And you have to add 3M of strings, that do not have constant size in java. So, usually that's something around 4-6GB for loaded model depending on jvm version/supplier, gc state and phase of the moon.

**Comment by tomthetrainer** [comment]
Added info to the Q and A section,
