### ISSUE TITLE
Several issues with documentation.

### ISSUE THREAD

**Issue by alexott** [deeplearning4j/deeplearning4j#1117]
I like your documentation, but there is small usability issue with it - all the pages have the same title, and when, for example, I save particular page into Pocket, or something like, then I can distinguish one page from another.

Another issue is that the HTML of the pages isn't valid - all content is located after closing body tag. For example, this is result of validation: https://validator.w3.org/nu/?doc=http%3A%2F%2Fdeeplearning4j.org%2Fgettingstarted.html

I didn't find the source of documentation, and if you point me to it, I can try to fix these issues & make the PR.

Thank you!

**Comment by agibsonccc** [comment]
We use github pages to generate it. The project is managed by a gh-pages branch and github pages markdown:
FWIW, we love pull requests. Thanks!:

https://github.com/deeplearning4j/deeplearning4j/tree/gh-pages

**Comment by chrisvnicholson** [comment]
Hi Alex - Thanks for flagging that. I've been leaving the "title" slot blank at the top of each page (by mistake), and it looks like that makes the title default to the website description. I'll start updating those...

**Comment by alexott** [comment]
Thank you for taking care for this Chris.

You're right, this is caused by leaving the title slot empty, so it's filled with default value in the https://github.com/deeplearning4j/deeplearning4j/blob/gh-pages/_includes/head.html#L14. I thought to change this line to contain project short name, to something like, to distinguish the pages from other projects:

     DL4J: {{ page.title }}

I also thought about automatically extracting the first H1 tag from the pages & use it as the page title, but it looks like it may take some time to implement.

**Comment by alexott** [comment]
Fixed via #1127 & #1120
