### ISSUE TITLE
Broken link to examples

### ISSUE THREAD

**Issue by avishaylivne** [deeplearning4j/deeplearning4j#1122]
The link to examples on spark is broken.
The link is here https://github.com/deeplearning4j/deeplearning4j/tree/master/deeplearning4j-scaleout/spark/dl4j-spark-ml#examples
and it points to
https://github.com/deeplearning4j/dl4j-spark-ml-examples

**Comment by chrisvnicholson** [comment]
please don't use spark-ml. i'll get rid of that documentation. use spark like this: https://github.com/deeplearning4j/dl4j-spark-cdh5-examples
