### ISSUE TITLE
What are the recommened database for storing data for deeplearning4j

### ISSUE THREAD

**Issue by oak-tree** [deeplearning4j/deeplearning4j#1136]
Hey there, I searched the documents and I did not find any mention about the `database platform ` advice to use with `deeplearning4j`. Maybe you can supply some information about this subject?

Thanks,
Oak

**Comment by agibsonccc** [comment]
It really depends on the problem. Nothing really deals with unstructured
data that well.

I mean if you have a time series problem a time series database is
preferred.

If you are doing images then a different one might be preferred.

The harder part of this is loading data. This is why we built canova.

**Comment by oak-tree** [comment]
Thanks for the information. My plan to work on image but I have to consider `scalability` in mind when selecting the `db` because it expects to grow in 5k images per week.

**Comment by agibsonccc** [comment]
For images it's all over the place for what people use. We mainly deal with hadoop clusters ourselves.
