### ISSUE TITLE
Broken links to nd4j-examples from nd4j.org

### ISSUE THREAD

**Issue by broartem** [deeplearning4j/deeplearning4j#1137]
* In http://nd4j.org/matrixwise.html, the first paragraph "(The example code lives here.)" points to 404 page  https://github.com/SkymindIO/nd4j/blob/master/nd4j-examples/src/main/java/org/nd4j/examples/MatrixOperationExample.java
* In http://nd4j.org/reshapetranspose.html, the first paragraph "(Example code.)" points to 404 page https://github.com/deeplearning4j/nd4j/blob/master/nd4j-examples/src/main/java/org/nd4j/examples/ReshapeOperationExample.java

It seems like links above should point to repo https://github.com/SkymindIO/nd4j-examples

**Comment by chrisvnicholson** [comment]
fixed
