### ISSUE TITLE
Check S3ModelSaver 

### ISSUE THREAD

**Issue by akioWS** [deeplearning4j/deeplearning4j#1146]
As quickly discussed over [gitter](https://gitter.im/deeplearning4j/deeplearning4j?at=56c20f2538f56aa31f3a1c2e), `S3ModelSaver` is not working properly.

When trying to save a Word2Vec model, the following warning is sent:
```
WARN  [2016-02-15 17:32:24,745] com.amazonaws.services.s3.AmazonS3Client: No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors.
```
In the S3 bucket, a file with 0B is created. The methods `load` and `exists` are also lacking implementation.

**Comment by raver119** [comment]
Fixed in: https://github.com/deeplearning4j/deeplearning4j/pull/1133

This pr/branch will be merged a bit later though.
