### ISSUE TITLE
Ambigious class names in api and conf packages

### ISSUE THREAD

**Issue by Habitats** [deeplearning4j/deeplearning4j#1154]
I'm working myself through the documentation on the [site](http://deeplearning4j.org/restrictedboltzmannmachine.html), writing out all of the examples by hand, and I'm finding it troublesome that things like `Layer` exist in both `org.deeplearning4j.nn.api` and `org.deeplearning4j.nn.conf` packages. As the examples on the site does not make any mention of the imports, I have to either consult the source, or resort to trial and error to get things to work.

It's by no means a major issue, but it prevents auto-import, and adds to the confusion for new users. E.g. I just spent some time trying to figure out why my `model` did not have the `setListeners()` method, wondering whether it's due to outdated examples on the site, or something else.

**Comment by AlexDBlack** [comment]
One easy solution: provide the imports along with example code, to avoid users having to determine exactly which class to import. For example, the conf vs. implementations - there is a configuration class and an implementation class for each type of layer (DenseLayer, GravesLSTM, etc).

**Comment by Habitats** [comment]
I should add that the identical names make entirely breaks Scala's type inference, leading to the requirement of explicit typing.

E.g. IntelliJ was unable to infer the following variable assignment without explicit parameters:
`val model = LayerFactories.getFactory(conf.getLayer).create(conf)`

**Comment by tomthetrainer** [comment]
Marking this as won't fix, but will seek to avoid complete code examples without linking to either gist or example that includes imports.
