### ISSUE TITLE
Regression example doesn't regress properly

### ISSUE THREAD

**Issue by atollFP** [deeplearning4j/deeplearning4j#1155]
Following this tutorial: [linear regression](http://deeplearning4j.org/linear-regression.html)
and running this: [pastebin](http://pastebin.com/3uyKyCPU) but also plotting the true function plotXY(x,y), you get those 2 very different plots: [plots](http://i.imgur.com/GGykiy8.png).  The regression is wrong

**Comment by AlexDBlack** [comment]
the short version: it was just a tuning issue with the old example.
I've added a new/better regression example here:
https://github.com/deeplearning4j/dl4j-0.4-examples/blob/master/src/main/java/org/deeplearning4j/examples/regression/RegressionMathFunctions.java
I've added a link to that in the documentation, and removed the link to that pastebin example.
