### ISSUE TITLE
Spark error after fitDataSet "unread block data"  in current master (3.9-SNAPSHOT)

### ISSUE THREAD

**Issue by devlop16** [deeplearning4j/deeplearning4j#1156]
Spark throws an error after fitDataSet "unread block data"  in current master (3.9-SNAPSHOT), working on 3.8

**Comment by nyghtowl** [comment]
@devlop16 is this still an issue?

**Comment by nyghtowl** [comment]
Closing. If this is still an issue please reopen and provide code that is generating this issue
