### ISSUE TITLE
Spark example repo does not exists (scene-classification-spark)

### ISSUE THREAD

**Issue by Habitats** [deeplearning4j/deeplearning4j#1162]
The [Spark documentation page](http://deeplearning4j.org/spark) points to the `scene-classification-spark` repo, which does not exists:
`fatal: repository 'https://github.com/deeplearning4j/scene-classification-spark/' not found`

I think I've seen the example somewhere else, but I cannot remember.

**Comment by nyghtowl** [comment]
Link fixed
