### ISSUE TITLE
Need example for inputting a timeseries for classifciation problems

### ISSUE THREAD

**Issue by alexde989** [deeplearning4j/deeplearning4j#1167]
I am right now working on a problem that involves inputting a readings taken from a patient and classifying whether that patient is healthy or not.

Now these reading are in a form of a time series. That is it may be a ECG or an EEG. 

How would you do this in DL4j ? Basically take the Iris example lets for say for each flower if the petal length, sepal length would have been a time series.

**Comment by jpatanooga** [comment]
an example of this is coming for our upcoming Strata talk on timeseries
classification w RNNs in DL4J

http://conferences.oreilly.com/strata/hadoop-big-data-ca/public/schedule/detail/47439

code repo:

https://github.com/jpatanooga/dl4j-rnn-timeseries-examples

Eventually I'll pull this code into the main dl4j examples set.

**Comment by agibsonccc** [comment]
This has been added long ago.
