### ISSUE TITLE
how to read the ui brower graphs

### ISSUE THREAD

**Issue by helloworld1973** [deeplearning4j/deeplearning4j#1170]
what the meaning of param_0_W  param_0_RW  param_0_b
![image](https://cloud.githubusercontent.com/assets/10842919/13196918/8cdfb2c2-d818-11e5-89a8-6d15b1e58ecc.png)
![image](https://cloud.githubusercontent.com/assets/10842919/13196927/c8b5ca2a-d818-11e5-868c-608cc9a7f8d1.png)

what the graphs mean? In which kinds of graphs means work well?

![image](https://cloud.githubusercontent.com/assets/10842919/13196907/3fbda706-d818-11e5-9b33-e55944e78ecd.png)

**Comment by agibsonccc** [comment]
We will try to explain that a bit clearer. The crux of it here: Parameters are per layer. W_0 is the weight matrix of the first layer. 

Those should be roughly normally distributed over time. The last graph should obviously be going down. That's your error. Hope that helps!

**Comment by helloworld1973** [comment]
Thank you very much @agibsonccc

**Comment by helloworld1973** [comment]
By the way,what's _RW and _b mean? @agibsonccc
