### ISSUE TITLE
Loading data from array 

### ISSUE THREAD

**Issue by hmoghadam** [deeplearning4j/deeplearning4j#1174]
Hi there,
I just want to predict next step of time series based on an array as input something like attach file.
[test.txt](https://github.com/deeplearning4j/deeplearning4j/files/139890/test.txt)

The problem is: The constructor SequenceRecordReaderDataSetIterator(INDArray, INDArray, int, int, boolean, SequenceRecordReaderDataSetIterator.AlignmentMode) is undefined

So would you please let me know how can we create DataSetIterator with INDArray as input for Many-to-One.

Additional question is: in this time series the label is not important so is it any way to create DataSetIterator without any label.

Thank you so much.

**Comment by AlexDBlack** [comment]
You probably want to use the combination of:
- Nd4j.create(double[]) to create your INDArray
- MultiLayerNetwork.rnnTimeStep(INDArray) to predict the next step

For the latter, take a look at this: http://deeplearning4j.org/usingrnns#rnntimestep

I'll close this for now, but comment here if that doesn't solve your problem.
