### ISSUE TITLE
Heap breaks at the time of W2V Model reload

### ISSUE THREAD

**Issue by vvpreetham** [deeplearning4j/deeplearning4j#1185]
Created a w2v Model with the following specs (gist : https://gist.github.com/vvpreetham/5562c8cfd0527a29c1ee)

file sizes as follows (This is a scaled down corpus to show the effect of the error)

![file_size](https://cloud.githubusercontent.com/assets/16869974/13266676/0e918428-da2e-11e5-94f3-f40cf9a45b88.jpg)

- Using : unstemmed_product_desc.txt as input corpus
- Model Saved : noinit_unstemmed_adagrad_v1000_5f.bin

While I was able to fit the model in probably about 4G or less RAM, saving and loading the model at load time breaks the heap.

Its the same machine, same RAM allocation. No changes...

**Comment by raver119** [comment]
This issue looks to be fixed within this pr: https://github.com/deeplearning4j/deeplearning4j/pull/1133

However, it will be merged to master a bit later.
