### ISSUE TITLE
Conflict between deeplearning4J and Neo4J / Lucene in Java web application

### ISSUE THREAD

**Issue by rpinquie** [deeplearning4j/deeplearning4j#1189]
Hi,

I am developing a Java web application with JSF 2 framework and the Neo4J database with its embedded Lucene's capabilities. Everything works fine.

In parallel, I added the deeplearning4j's dependencies, created a new class in the test package to try Glove and Word2vec examples. When I run both examples as a mere Java Application it works properly too.

However, after deploying my web app, when I try to access it via localhost:8080/iseenrea I get a bunch of conflicts in the console. You can see the console messages here: https://github.com/rpinquie/rpinquie.github.io/blob/master/d4j.Neo4j.Lucene.errors.txt 

This is maybe due to conflicting ports or maven dependencies - isn't it?

Cheers,

Romain

**Comment by raver119** [comment]
Lucene isn't actually used for w2v/glove for quite some time now.
So just make sure you're using the most recent dl4j/nd4j.

Also, you can exclude lucene using maven, since it's not used for w2v/glove

**Comment by rpinquie** [comment]
I am using the latest 0.4-rc3.8 version of DL4J and don't have Lucene dependencies; however, Spring Data Neo4j relies on Lucene for full text capability, and I need it. Any idea that may fix my problem?

**Comment by raver119** [comment]
I've said: you can exclude specific subdependencies, for any of your dependency using maven.
```
 <dependency>
            <groupId>some.developer</groupId>
            <artifactId>some-artifact</artifactId>
            <version>1.2.3</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by rpinquie** [comment]
I removed those dependencies:

`<exclusion>
                <groupId>org.apache.lucene</groupId>
                <artifactId>lucene-analyzers-common</artifactId>
            </exclusion>
            <exclusion>
            	<groupId>org.apache.lucene</groupId>
				<artifactId>lucene-core</artifactId>
            </exclusion>
            <exclusion>
	            <groupId>org.apache.lucene</groupId>
				<artifactId>lucene-queryparser</artifactId>
            </exclusion>
            <exclusion>
	            <groupId>junit</groupId>
				<artifactId>junit</artifactId>
            </exclusion>`

Doesn't change anything. I am not 100% sure that it's a dependency problem.

**Comment by raver119** [comment]
post gist with full pom.xml

http://gist.github.com

**Comment by rpinquie** [comment]
Here is it: https://gist.github.com/rpinquie/c84690cd9ce690dbdf1d

**Comment by raver119** [comment]
It actually should fail for you. All exclusions should be wrapped into
```
 <exclusions></excusions
```

Check my example above. It's detailed enough.

**Comment by rpinquie** [comment]
Sorry, I am blind... I don't have conflicts anymore, the web app and DL4J examples work perfectly now.

Thanks a lot.

**Comment by raver119** [comment]
You're welcome
