### ISSUE TITLE
MultipleEpochsIterator doesn't behave like a for-loop of reset and fit

### ISSUE THREAD

**Issue by atollFP** [deeplearning4j/deeplearning4j#1190]
They're behavior are not equivalent. 

I believe the issue is here 
`public boolean hasNext() {
    return iter.hasNext() && passes < numPasses;
}`

when the iter is empty but passes < numPasses, the MEI still have a the next passes and hasNext should not return false.

**Comment by raver119** [comment]
Right, there should be || instead of &&.
