### ISSUE TITLE
Text Vectorizers and Stemming produce wrong results on .transform()

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#1203]
I'm trying to do multi-class classification on some text documents, and for the last few days had the problem that regardless of what I tried the networks converged on something like the average of my labels.

So when I had no idea what else to try I turned to taking another look at my input data, and discovered that my TextVectorizer (TfidfVectorizer) always returns a zero array, regardless of its input unless I put in already stemmed words. So I investigated the problem some more and found this:
[Link to Source](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/bagofwords/vectorizer/TfidfVectorizer.java#L82)
```java
  private INDArray tfidfForInput(String text) {
        INDArray ret = Nd4j.create(1, cache.numWords());
        Tokenizer tokenizer = tokenizerFactory.create(text);
        List<String> tokens = tokenizer.getTokens();

        for(int i = 0;i < tokens.size(); i++) {
            int idx = cache.indexOf(tokens.get(i));
            if(idx >= 0)
                ret.putScalar(idx, tfidfWord(tokens.get(i)));
        }
        return ret;
    }
```
So calling `.transform("text")` will only tokenize its input, but not perform any stemming on it. While adding `.stem(true)` on the Builder for the Vectorizer will result in the PorterStemmer being applied to the tokens while filling the vocab ([as seen here](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/word2vec/actor/VocabActor.java#L199)).

This behavior is not constrained to the TfidVectorizer, but is also found in the [BagOfWordsVectorizer](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/bagofwords/vectorizer/BagOfWordsVectorizer.java#L131) and to me definitely looks like a bug.

**Comment by raver119** [comment]
Since dl4j-nlp tries to be language-agnostic, the following solution is considered:

1. Stemming is removed from options.
2. Vocab building migrated to new codebase, that's currently used within w2v/d2v/glove. So, no more Akka there.
3. Stemming and such a things are handled through TokenPreProcessors. Corresponding stemming preprocessors will be available out of box.

Things are happening here: https://github.com/deeplearning4j/deeplearning4j/pull/1237

However, will be mergd into master a bit later.
