### ISSUE TITLE
Docs: Clarify labels/classes handling for image loading

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1206]
Image data pipeline: http://deeplearning4j.org/image-data-pipeline

This page should explain the structure of the images:
i.e., /lfw/somelabel0/img0.jpg, /lfw/somelabel1/img20.jpg, etc

It should also explain what that the labels list should contain - i.e., it's a list of unique labels (i.e., names of subdirectories), not a list of labels for each example.
Also clarify how the order of the list relates to the order of the outputs in the network/data (i.e., they are the same).

Ideally: This page should also explain alternative file structures (i.e., classes based on file name instead of parent directory).

**Comment by tomthetrainer** [comment]
I will get to this, there was nice content on that page when I did my first timid updates of it. More confident now, May make this a more comprehensive page, or may add a chain of docs that cover ingestion/labelling/normalization more completely for all input types. 

Depends on how much time I have, more or less a note to myself for next week, either quick clean this page, or dig deeper and refactor.

**Comment by tomthetrainer** [comment]
I am closing this issue and have opened up an issue to create a dedicated page on all label generation from datavec #3212
