### ISSUE TITLE
Clustering Examples

### ISSUE THREAD

**Issue by tomdev55** [deeplearning4j/deeplearning4j#1212]
Are there any examples for clustering, i.e. the usage of BaseClusteringAlgorithm class and the possible distance function inputs?
For example I am trying this:
https://gist.github.com/anonymous/9ba2e4f8ced694101787
And I get:
https://gist.github.com/anonymous/c56f65e76e8dd4fa7c0c

**Comment by agibsonccc** [comment]
It's not quite what you're looking for here..but it's a start. https://github.com/deeplearning4j/deeplearning4j/pull/3602 I updated the kmeans module and at least added a test to show you how to set it up given a matrix and get classifications out. That should be enough for most people.
