### ISSUE TITLE
normalizeZeroMeanZeroUnitVariance doesn't export mapping

### ISSUE THREAD

**Issue by GrtAndPwrflTrtl** [deeplearning4j/deeplearning4j#1213]
As a practical matter, you need to be able to repeat the exact same mapping during testing. So if this function exists, shouldn't it export a mapping? And possibly include an inverse function to apply the mapping to data.

**Comment by raver119** [comment]
Specifically for standard normalization approaches the best way would be using InputPreProcessors configured within your model. So, in this way model persistence guarantees persistence of your InputPreprocessors as well.
