### ISSUE TITLE
CLI build issue on Windows (RPM)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1217]
Build error on Windows 8.1 using maven:

[INFO] --- rpm-maven-plugin:2.1.5:rpm (default) @ deeplearning4j-cli-api ---
[WARNING] rpm version string truncated to 0.4
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] DeepLearning4j ..................................... SUCCESS [  0.575 s]
[INFO] dl4j-test-resources ................................ SUCCESS [ 38.716 s]
[INFO] deeplearning4j-core ................................ SUCCESS [ 15.905 s]
[INFO] DeepLearning4j-scaleout-parent ..................... SUCCESS [  0.014 s]
[INFO] deeplearning4j-scaleout-api ........................ SUCCESS [  0.883 s]
[INFO] deeplearning4j-scaleout-zookeeper .................. SUCCESS [  1.259 s]
[INFO] deeplearning4j-scaleout-akka ....................... SUCCESS [  4.270 s]
[INFO] deeplearning4j-nlp ................................. SUCCESS [ 14.000 s]
[INFO] DeepLearning4j-AWS ................................. SUCCESS [  1.385 s]
[INFO] hadoop-yarn ........................................ SUCCESS [  0.014 s]
[INFO] cdh4 ............................................... SUCCESS [  3.490 s]
[INFO] deeplearning4j-nlp-yarn ............................ SUCCESS [  3.168 s]
[INFO] org.deeplearning4j.spark ........................... SUCCESS [  4.225 s]
[INFO] dl4j-spark ......................................... SUCCESS [ 14.511 s]
[INFO] dl4j-spark-nlp ..................................... SUCCESS [ 13.251 s]
[INFO] dl4j-spark-ml ...................................... SUCCESS [ 35.718 s]
[INFO] deeplearning4j-graph ............................... SUCCESS [  2.076 s]
[INFO] deeplearning4j-cli ................................. SUCCESS [  0.014 s]
[INFO] deeplearning4j-cli-api ............................. FAILURE [  5.094 s]
[INFO] deeplearning4j-ui .................................. SKIPPED
[INFO] dl4j-caffe ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:39 min
[INFO] Finished at: 2016-03-03T00:26:49+11:00
[INFO] Final Memory: 127M/651M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:rpm-maven-plugin:2.1.5:rpm (default) on project deeplearning4j-cli-api: Unable to query for default vendor from RPM: Error while executing process. Cannot run program "rpm": Cr
eateProcess error=2, The system cannot find the file specified -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :deeplearning4j-cli-api

**Comment by raver119** [comment]
That's because maven rpm plugin relies on underlying rpm package provider. So that will fail on everything but redhat/centos. However, cygwin will probably work too.

**Comment by agibsonccc** [comment]
My advice would be to define a maven profile that only triggers with
certain linux versions.

**Comment by AlexDBlack** [comment]
Look like this has been fixed.

**Comment by jimmyleeeeee** [comment]
what  is the solution?

**Comment by agibsonccc** [comment]
@jimmyleeeeee locking this. We don't have the CLI anymre.
