### ISSUE TITLE
Semi-Supervised Recursive auto encoders

### ISSUE THREAD

**Issue by ErikTromp** [deeplearning4j/deeplearning4j#122]
Just flagging this for next release.

**Comment by agibsonccc** [comment]
Cool thanks!  I can likely do a minor release with semi supervised following up here. I have some uses myself for the unsupervised one, but I'll be glad to get it in there.

**Comment by aritasimoes** [comment]
Just a short note to say I'm also interested in the unsupervised RAE. I'm currently trying to use the implementation that is already available in the snapshot version for a text application. It would be great if we could have a discussion on this. Thanks in advance!

**Comment by ErikTromp** [comment]
I would also still be very interested in this.

**Comment by pizirun** [comment]
+1, thanks.
