### ISSUE TITLE
two versions of SerializationUtils exists

### ISSUE THREAD

**Issue by bennythedataguy** [deeplearning4j/deeplearning4j#1227]
1) org.nd4j.linalg.util.SerializationUtils
2) org.deeplearning4j.util.SerializationUtils

This is confusing as hell.  There can be only one.

![highlander-duncan-katana](https://cloud.githubusercontent.com/assets/16317063/13516767/fe46b4d0-e171-11e5-9188-cffa83cda86f.jpg)

**Comment by eraly** [comment]
Not ideal. But there are many many other things that are even more confusing about dl4j. Like two layer.java or the duplicate names for the conf and implementations for all the layers. For now, we are going to keep thing as they are.
