### ISSUE TITLE
ND4J serialization not compatible between 0.4-rc3.9-SNAPSHOT and 0.4-rc3.8

### ISSUE THREAD

**Issue by bennythedataguy** [deeplearning4j/deeplearning4j#1228]
Steps to repeat: 
1) Serialize an INDarray with Nd4j.write(arr) in 0.4-rc3.8
2) Deserialize INDarray with Nd4j.read(dis) in 0.4-rc3.9-SNAPSHOT

you may get this error:
java.lang.RuntimeException: java.io.StreamCorruptedException: invalid stream header: 00000002

---

writing in 0.4-rc3.8:
final ByteArrayOutputStream baos = new ByteArrayOutputStream();
final DataOutputStream dos = new DataOutputStream(baos);
Nd4j.write(net.params(), dos);

reading in 0.4-rc3.9-SNAPSHOT
ByteArrayInputStream bis = new ByteArrayInputStream(paramsBinData);
DataInputStream dis = new DataInputStream(bis);
INDArray params = Nd4j.read(dis);

**Comment by AlexDBlack** [comment]
Just to repeat what I said to @bennythedataguy in gitter:
Afaik there's no fundamental reason why serialization should break between 0.4-rc3.8 and 3.9. If possible, we should maintain serializability/deserializability of INDArrays between versions.

**Comment by nyghtowl** [comment]
@bennythedataguy is this still an issue?

**Comment by AlexDBlack** [comment]
Afaik, yes: see also
https://github.com/deeplearning4j/nd4j/issues/832
https://github.com/deeplearning4j/nd4j/issues/784

We may end up having broken serialization between 3.8 and 3.9, but then (with the version header stuff) we should be able to maintain backward compatibility for any releases thereafter.

**Comment by nyghtowl** [comment]
Tagging it so that at the very least it gets communicated out on the release

**Comment by agibsonccc** [comment]
Not relevant anymore.
