### ISSUE TITLE
A same Dense layer for different input (all the depth of a 3d tensor)

### ISSUE THREAD

**Issue by rubenfiszel** [deeplearning4j/deeplearning4j#1231]
A dense layer that you could apply  in a Computational graph in the same way to all the depth of a tensor, 

In the Keras library, it exists under the name of TimeDistributedDense.

**Comment by AlexDBlack** [comment]
If I understand this correctly, TimeDistributedDense is just a dense layer used in the context of RNNs, applied at every step of the sequence and every example.
We already support that: the standard DenseLayer + preprocessors works with RNNs quite well.

**Comment by nyghtowl** [comment]
@atollFP does Alex's response address your request?

**Comment by atollFP** [comment]
Not really, at least not what I would like to do. I want to apply a same layer for differents incoming layer in a computation graph.

for instance you could have weight tying constraint.

**Comment by turambar** [comment]
Duplicated by https://github.com/deeplearning4j/deeplearning4j/issues/2865, which has a more detailed discussion. Hence, I'm closing this.
