### ISSUE TITLE
Information about word2vec maven configuration is outdated on the website

### ISSUE THREAD

**Issue by kivan-mih** [deeplearning4j/deeplearning4j#1232]
Information about word2vec maven config is outdated in http://deeplearning4j.org/word2vec . Word2vec throws an exception on build() using this config. Needs to be actualised.

**Comment by raver119** [comment]
Your issue is caused with nd4j-jblas backend, not by w2v itself. Please use nd4j-x86 backend instead, and you'll be all good. Especially if you'll temporary set negativeSampling(0)
