### ISSUE TITLE
SequenceVector Serialization 

### ISSUE THREAD

**Issue by Milanvdm** [deeplearning4j/deeplearning4j#1233]
It would be logic if SequenceVectors could be saved after they are trained. When applied on very large databases, this step is already intensive work and should be able to stored as backup/later use.

Saving the full model is already offered for Word2Vec:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/loader/WordVectorSerializer.java#L646

**Comment by raver119** [comment]
What would you say about JSON for serialization?

**Comment by Milanvdm** [comment]
Doesn't really matter if the model can be loaded in again. JSON seems like a good way to safe a large model so that's fine.

**Comment by raver119** [comment]
Ok, i'll look for other options there, and will add something suitable.

**Comment by Milanvdm** [comment]
Looking forward to this! This way I can split of my computation time so I don't lose everything when something goes wrong half way :)

**Comment by raver119** [comment]
Implemented here: https://github.com/deeplearning4j/deeplearning4j/pull/1237

However, isn't properly tested yet and will be merged into master later.
