### ISSUE TITLE
Can nextRandom be a negative number?

### ISSUE THREAD

**Issue by Da-Huang** [deeplearning4j/deeplearning4j#1235]
I noticed that dl4j-nlp is using the following code to calculate next random number everywhere.
```java
// AtomicLong nextRandom
nextRandom.set(nextRandom.get() * 25214903917L + 11);
```
Such calculation can make nextRandom become a nagative number, which causes some strange behaviors, I think.

e.g.
At [line 129 in SkipGram.java](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/learning/impl/elements/SkipGram.java#L129), it passes `(int) nextRandom.get() % window` to [`skipGram()`](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/learning/impl/elements/SkipGram.java#L143) as [`b`](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/learning/impl/elements/SkipGram.java#L148).
I think it should have reduced the window by a random size, but such behavior can make the window extended.

**Comment by raver119** [comment]
As for random: confirmed as bug and changed to abs. Thanks!

However, will be merged into master a bit later.

**Comment by Da-Huang** [comment]
Thanks. : )

Just a suggestion: I think that it might be tidier to update the random number by a random number generator.

**Comment by raver119** [comment]
that's just plain transfer from original c code, and the bug you've spotted comes from fact there's unsigned long used :)
