### ISSUE TITLE
DBOW handles only the very beginning words in each sentence?

### ISSUE THREAD

**Issue by Da-Huang** [deeplearning4j/deeplearning4j#1236]
The implementation of [dbow](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/learning/impl/sequence/DBOW.java#L100-L109) in dl4j-nlp doesn't seem to make sense.

Supposed that we have one label for each document. `labels.size()` will be 1, so that `c` can only be `0` due to [`if(c >= 0 && c < labels.size())`](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/learning/impl/sequence/DBOW.java#L104). When `i` is big enough (e.g. twice of the `window`), `c` won't be `0` so that `skipGram.iterateSample` won't be called.

Besides, I don't think [`if(a != window)`](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/learning/impl/sequence/DBOW.java#L102) make sense neither, according to the following figure.
![image](https://cloud.githubusercontent.com/assets/6611045/13572434/4cf14f50-e4b5-11e5-99b1-bcd5b0e7ecfc.png)

**Comment by raver119** [comment]
You're looking into current master, right?

**Comment by Da-Huang** [comment]
@raver119 yes.

**Comment by raver119** [comment]
Actually you're right here. There should be primitive roll over words -> labels, without any windows on dbow phase. Looks like copy & paste issue :/

Thanks for letting me know!

**Comment by raver119** [comment]
p.s. fixed, and will be merged a bit later.

**Comment by Da-Huang** [comment]
wow, great! thanks!
