### ISSUE TITLE
BatchNorm + ActivationLayer performance issue

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#1238]
UPDATE: #1536 provided an update to the algorithm and differentiated the approach between dnn (gamma & beta per activation) and cnn (gamma & beta per feature map). Performance is still not meeting expectations. 

Help is wanted to review and confirm layer configuration. Gradient check tests have been added but partially fail. Also, check this example: https://github.com/deeplearning4j/ComputerVision-examples/blob/master/src/main/java/org/deeplearning4j/examples/cv/cifar/TestModels/BatchNormModel.java regarding performance and disregard the warning about reset which is an unrelated issue.

**Comment by nyghtowl** [comment]
Pending im2col and col2im fixes before this can be tackled

**Comment by nyghtowl** [comment]
The #134 issue was in the way of continuing to debug this issue but the issue still exists Troubleshooting can continue.

**Comment by EdwardRadical** [comment]
BatchNormModel does not exist anymore.

**Comment by nyghtowl** [comment]
@EdwardRadical its still there. It's been collapsed into a script with multiple models: https://github.com/deeplearning4j/ComputerVision-examples/blob/master/src/main/java/org/deeplearning4j/examples/cv/TestModels/CifarCaffeModels.java#L201

**Comment by agibsonccc** [comment]
Is this still relevant? @raver119 @AlexDBlack

**Comment by nyghtowl** [comment]
Resolved in previous release
