### ISSUE TITLE
Increasing heap size while training CNN

### ISSUE THREAD

**Issue by JohnTheDang** [deeplearning4j/deeplearning4j#1242]
The memory heap size keep increasing as I train my CNN using spark. My training set is at about 10 mb (around 3000 images), but after training for about 10 epochs, the program always throws some kind of out of memory exception, like Java heap size or GC overhead. I have changed the xmx setting to use 4g, and I have confirmed that the application uses 4g while training by looking at JProfiler connected to IntelliJ. I can unfortunately not include my image data set, as it is medical images that I'm not sure that I can share, but I'll try to include everything else.

I have added build.sbt, sbt.txt, src, stack trace as txt, in the zip file. Also included an image of the profiling of a run instance, where the uppermost value of the y-axis is 4g. (Green is free space and blue is used space). Adding an image of the GC activity too.

Memory:
![telemetry](https://cloud.githubusercontent.com/assets/17123674/13601233/d96a0818-e52e-11e5-807e-e31253340a11.png)

GC: 
![telemetry_2](https://cloud.githubusercontent.com/assets/17123674/13601279/34986d2e-e52f-11e5-85fd-ce65640ff49d.png)

[Memory Issue.zip](https://github.com/deeplearning4j/deeplearning4j/files/163095/Memory.Issue.zip)

Memory Issue v2
[Memory Issue.zip](https://github.com/deeplearning4j/deeplearning4j/files/163974/Memory.Issue.zip)

**Comment by raver119** [comment]
Any chance for screenshot from jvisualvm (or anything like it) memory sampling tab?

**Comment by JohnTheDang** [comment]
I haven't used that before, but I'll try to fix it and rerun the program.

**Comment by JohnTheDang** [comment]
Do you mean visualvm, https://visualvm.java.net/ ?

**Comment by raver119** [comment]
Any profiler report will be welcome tbh.

JVisualVM is the part of java dirtibution, it's in your bin folder

**Comment by JohnTheDang** [comment]
Hmm, do you mean what classes that are taking up space, like double[] and int[]?

**Comment by raver119** [comment]
Yes, exactly. I need overall picture of allocations, so i could start my investigation with something in hands.

**Comment by JohnTheDang** [comment]
Alright, will fix that!

**Comment by agibsonccc** [comment]
Is there any way we could get an isolated example we can run too?

**Comment by JohnTheDang** [comment]
Sorry, but I'm not sure if I'm allowed to share the images, as they're medical images that I've gotten from a company. I'll ask my supervisor about it tomorrow. At least I've uploaded a new map with the requested pictures of allocations.

**Comment by raver119** [comment]
Thank you very much, updated archive is totally awesome!

**Comment by JohnTheDang** [comment]
Thanks! Hope it works out!

**Comment by JohnTheDang** [comment]
Was unfortunately not allowed to send the images to you for testing, but I'll see if I can create an artificial data set that gives the same problem!

**Comment by raver119** [comment]
Don't worry, as long as we have your source code, images won't be an issue.

**Comment by treo** [comment]
Please try the following: Create your model, and then directly save its parameters without any training, and then reload them (http://deeplearning4j.org/modelpersistence shows how to do that) - When reloading the parameters I have found that for some reason the memory usage does not icrease.

Note, that as you didn't do any training yet, you shouldn't try to save the updater.

As can be seen in Issue #1258, the memory requirements went down from peaks of over 10GB and rising to peaks of about 3.5GB.

**Comment by JohnTheDang** [comment]
Tried saving the model and then starting a new program to load and train the NN, but still gives the same problem with pretty much the same symptoms as I had earlier. What I can't really wrap my head around is why the GC starts increasing in activity after about an hour and the heap space stays pretty much flat most of the time in the last maybe 20 minutes.

**Comment by agibsonccc** [comment]
I'd be curious for an update on this. We fixed some memory leak issues recently.

**Comment by JohnTheDang** [comment]
Are the fixes on r3.8 or on the latest snapshot?

**Comment by agibsonccc** [comment]
Latest.

**Comment by JohnTheDang** [comment]
Where could I find the latest snapshot, i.e. what should I add to my pom.xml?

**Comment by treo** [comment]
You'll have to build it from source

**Comment by JohnTheDang** [comment]
How do I do that?

**Comment by treo** [comment]
Depends on your OS, for windows you can follow these instructions: https://github.com/deeplearning4j/libnd4j/blob/master/windows.md

**Comment by JohnTheDang** [comment]
Uhmm, this looks a bit too advanced for me, is it ok if I wait with testing until the new update is released?
