### ISSUE TITLE
Race condition in Word2Vec / SequenceVectors

### ISSUE THREAD

**Issue by stefanjanssen** [deeplearning4j/deeplearning4j#1243]
I ran into a race condition in Word2Vec in deeplearning4j. I'm using an older version, but I can see the responsible code is still in the repo.

Basically, in SequenceVectors.java line 167 a producer (AsyncSequencer) thread is created and several consumer threads (VectorCalculationsThread). The producer uses a isRunning flag to signal that is running, but this is only set at the start of the run() method (line 772). Before that it is set to false. It is possible for the consumers to be all picked up by the scheduler before the producer thread, resulting in them exiting before anything has been produced. The producer thread then hangs wondering why nobody is consuming anything.

**Comment by raver119** [comment]
AsyncSequencer is going to be retired before next release, and will be replaced with FilteredSequenceIterator, as simple wrapper over iterator passed in.

But yes, you're totally right, there's definitely possible rc. As quick fix i'll set it to true at object instantiation time.

**Comment by raver119** [comment]
Fixed: https://github.com/deeplearning4j/deeplearning4j/pull/1237

However, will be merged into master a bit later.
