### ISSUE TITLE
Getting started a binary segmentation task

### ISSUE THREAD

**Issue by AldoMarzullo** [deeplearning4j/deeplearning4j#1246]
Dear All,
I would implement a neural network in order to perform a binary supervised classification task. More precisely I have a set of raw "input" images and a set of binary "target" images containing a segmentation of some object of the input image.

![image](https://cloud.githubusercontent.com/assets/8161416/13617208/c75fc956-e57d-11e5-9270-658578893d3f.png)

I followed this [tutorial](http://deeplearning4j.org/image-data-pipeline) but I am still a bit confused about how to set the problem. I think I have to create the dataset using the raw "input" images, but I need some way to pass to the network also the "target" images.

Imaging a structure similar to the following:
![image](https://cloud.githubusercontent.com/assets/8161416/13617810/d9b22358-e580-11e5-95b5-582b5f213f3a.png)

My output level should be of the same dimension of the input layer, so that my label could not be just a class for the entire image (like dog, cat, etc.) concatenated to the input image (as this line of code do `RecordReader recordReader = new ImageRecordReader(28, 28, true, labels);`)

This is the very first time for me with convolutional neural networks, so any hint, advice or reading will be useful and appreciate.

Thanks for any help!

**Comment by AlexDBlack** [comment]
The first (and perhaps easiest) approach that comes to mind for loading the data would be to use two separate image record readers, and manually create a new DataSet from them... so the first would give you your input, and the second would give you your labels. Input and labels would be in completely separate directories.

Using that approach, you have to ensure the iteration order is the same, which you can do by ensuring that the file names (and subdirectories) are the same between the different folders.

**Comment by AldoMarzullo** [comment]
@AlexDBlack Thank you for the reply,
[This](http://pastebin.com/uWxnFXC7) is the code I am writing up to now based on the **mnist** tutorial. 
I created the two dataset, and, if I understood your hint, I have to create a new dataset of the form `[inputImg, labelImg]`, but I didn't get how..

Moreover, I am getting a weird exception when I iterate the dataset: `"java.lang.IllegalArgumentException: Index [1] must not be >= shape[d]."` What does it mean?

**Comment by AlexDBlack** [comment]
Try using the RecordReaderDataSetIterator with the (RecordReader, int batchSize) constructor - i.e., without labels. And don't bother with the "traverse dataset to get each labels" thing - in your case, your labels are the other images.

As for creating the new data set, try something like this:
```java
while(inputIter.hasNext()){
    DataSet f = inputIter.next();
    DataSet l = labelsIter.next();
    DataSet newData = new DataSet(f.getFeatures(),l.getFeatures())
}

```

**Comment by AldoMarzullo** [comment]
Ok, I am starting to understand!
Just another couple of questions: 
I think I have the same problem as this [issue #128](https://github.com/deeplearning4j/Canova/issues/128). My dataset is the [DRIVE](http://www.isi.uu.nl/Research/Databases/DRIVE/) database, where the input images are **.tif** and the labels are **.gif**.

Moreover `DataSet next = labelsIter.next();` is returning `null`

**Comment by agibsonccc** [comment]
Closing this - come in to gitter for more help.

**Comment by ioannisbaptista** [comment]
@AldoMarzullo did your code work? I'm trying to do something similar, segmenting streets and avenues in urban images, but I'm a beginner and I do not know how to mount the pipeline. Just like you, I have the TIFF urban image and a PNG ROI, containing black pixels corresponding to the pixels in the original image that belong to the streets and avenues. My goal is to mount a CNN that gives as output the probability of a pixel being or not of an avenue or street. Above a certain threshold, true, otherwise false. Can you (or anyone) help me with a piece of code or some explanation? =(

**Comment by AlexDBlack** [comment]
@ioannisbaptista Please don't post on issues that have been closed for over 2 years.
If you want help with this, ask in our gitter channel - https://gitter.im/deeplearning4j/deeplearning4j - or open a new issue with more details on your data format (at the very least, we'd need to know how the images are 'linked' - i.e., how do you know image X corresponds to segmentation mask Y?).
