### ISSUE TITLE
PosUimaTokenizerFactory NPE

### ISSUE THREAD

**Issue by mlaubre** [deeplearning4j/deeplearning4j#1250]
PosUimaTokenizerFactory  causes  java.lang.NullPointerException
Same on ver 0.4-rc3.8 and 0.4-rc3.9-SNAPSHOT

Samples:
POM.xml: https://gist.github.com/mlaubre/7a82d9979ff99fc8d0f2
Java code: https://gist.github.com/mlaubre/3e3666cad6327bc3b823
Error log: https://gist.github.com/mlaubre/9009f512c92770172b6e

Regards
ML

**Comment by raver119** [comment]
Fixed and improved: https://github.com/deeplearning4j/deeplearning4j/pull/1237

However, it will be merged into master a bit later.
