### ISSUE TITLE
Getting results from neural net

### ISSUE THREAD

**Issue by lsrom** [deeplearning4j/deeplearning4j#1252]
I played around with provided examples and got my own net working. I wanted to give it a single input and have printed the result for it.  

For example: 
``I have training sample of about 10k images with letters. After learning I would like to take one image, input it into the net and have it tell me what letter it is.  ``

Maybe I missed it in examples somewhere but if not this would be great improvement to your documentation and examples.

**Comment by agibsonccc** [comment]
FWIW, In general - you use the network.output() after it's already an ndarray. I'd need a bit more information. Are you having a hard time interpreting probabilities? Data pipelines for building a test array?
