### ISSUE TITLE
Epoch listener for SequenceVectors

### ISSUE THREAD

**Issue by LukasMasuch** [deeplearning4j/deeplearning4j#1253]
Feature request: Could you consider adding a simple epoch listener to sequence vectors. That would be really helpful for evaluating the accuracy of the vector space after every epoch. I'm dealing with 3GB of textual data and it would take too long to wait for all epochs to see if the configuration made a positive impact on the accuracy. I have currently implemented this in my dl4j version in this way:
```Java
private EpochListener epochListener;

public void setEpochListener(EpochListener epochListener){
    this.epochListener = epochListener;
}

public interface EpochListener {
    void epochCompleted(int epoch,WordVectors wordVectors);
}
```
An I call it on the completion of every epoch:
```Java
if (epochListener != null){
      epochListener.epochCompleted(currentEpoch,this);
 }
```

**Comment by raver119** [comment]
Code will be refactored and included in the master branch.

**Comment by raver119** [comment]
After refactoring it's implemented in the following way:

There's 2 possible reasons to activate listener: end of epoch, or sequence passed. Like every 2nd epoch, or every 100000th sequence passed.

As example i've provided SerializingListener, that can serialize model after X epochs or lines.

**Comment by LukasMasuch** [comment]
Thanks @raver119! The refactored listener is very helpful.
