### ISSUE TITLE
Effective use of dropout for recurrent neural networks

### ISSUE THREAD

**Issue by Elroch** [deeplearning4j/deeplearning4j#1265]
A number of recent papers say dropout can be a very effective regularization technique for recurrent neural networks, but only if it is not applied to the recurrent connections. Can DL4J incorporate this? See [http://arxiv.org/abs/1409.2329](http://arxiv.org/abs/1409.2329) , [http://arxiv.org/abs/1312.4569](http://arxiv.org/abs/1312.4569)

**Comment by AlexDBlack** [comment]
Dropout as implemented for RNNs in DL4J is done on the input connections/activations only, not the recurrent connections. So we already have this.

**Comment by Elroch** [comment]
Thanks, great to hear!
