### ISSUE TITLE
Changable parameter for leakyReLU

### ISSUE THREAD

**Issue by JohnTheDang** [deeplearning4j/deeplearning4j#1275]
It would be nice to have a way to change the parameter of leakyReLU, as it seems to be a possibly important hyper parameter. Would be even better if there was a way to implement the randomized leaky ReLU as described in the paper http://arxiv.org/pdf/1505.00853.pdf

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/1338
