### ISSUE TITLE
The 'dlf4j' tag does not seem to be searchable/viewable on StackOverflow

### ISSUE THREAD

**Issue by hotmeatballsoup** [deeplearning4j/deeplearning4j#1278]
When asking a new question, if you attempt to search for the '`dl4j`' tag, it does not show up in the search results.

**Comment by saudet** [comment]
"deeplearning4j" is there as a tag: http://stackoverflow.com/questions/tagged/deeplearning4j  Do we need "dl4j" as well?

**Comment by agibsonccc** [comment]
The acronym would be easier.

**Comment by saudet** [comment]
We can vote to create a synonym here:
http://stackoverflow.com/tags/deeplearning4j/synonyms
Those who can, please vote!
