### ISSUE TITLE
preserialization number of labels != deserialization number of labels

### ISSUE THREAD

**Issue by montyhall** [deeplearning4j/deeplearning4j#1287]
FileInputStream inStream = new FileInputStream(new File(trainDataPath));
int labelPosition = 0;
int textPosition = 1;
  	
LabelAwareListSentenceIterator iter = new LabelAwareListSentenceIterator(inStream,"\t",labelPosition,textPosition);

ParagraphVectors paragraphVectors = new ParagraphVectors.Builder()
            .useAdaGrad(useAdaGrade)
            .learningRate(learnRate)
            .minLearningRate(minLearnRate)
            .batchSize(batchSize)
            .epochs(epochs)
            .trainWordVectors(true)
            .tokenizerFactory(tokenizer)
            .minWordFrequency(minWordFreq)
            .stopWords(stopwords)
            .iterations(iterations)
            .layerSize(layerSize)
            .windowSize(windowSize)
            .iterate(iterator)
            .build();

    // Start model training
    paragraphVectors.fit();

// shows 28 labels
log.info("...lables ('"+vectors.getLabelsSource().getLabels().size()+"')");
	    vectors.getLabelsSource()
	    .getLabels()
	    .forEach(System.out::println);

WordVectorSerializer.writeWordVectors(paragraphVectors,"/tmp/paragraphVectors");

WordVectorSerializer.readParagraphVectorsFromText("/tmp/paragraphVectors");

// shows 26 labels
log.info("...vectorizer's labels ('"+vectors.getLabelsSource().getLabels().size()+"')");
	  	vectors.getLabelsSource().getLabels()
	  	.forEach(k -> log.info("...\t"+k));

**Comment by raver119** [comment]
As i've explained in gitter, this is logical flaw withing vocab that's under reconsideration now.

https://github.com/deeplearning4j/deeplearning4j/issues/1130
