### ISSUE TITLE
Histogram iteration listener: add ratio of parameters to gradients

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1299]
Currently: we have a line charts of the mean magnitudes for parameters and gradients. Adding an additional set of charts with the ratios of these would be quite useful. So literally, a time series of (mean absolute parameter values) / (mean absolute gradient values).

Presumably this would be placed under the bottom-right mean magnitudes section.

EDIT: also (if possible) the distribution of activations wouldn't be a bad idea...

**Comment by agibsonccc** [comment]
Not relevant with new UI.
