### ISSUE TITLE
What's the difference between nn.layers.recurrent.GravesLSTM and nn.conf.layers.GravesLSTM

### ISSUE THREAD

**Issue by w31122534** [deeplearning4j/deeplearning4j#1302]
I am a beginner, and try to understand the program. I don't know the difference between  org.deeplearning4j.nn.layers.recurrent.GravesLSTM and nn.conf.layers.GravesLSTM, besides, how can I use them.

**Comment by agibsonccc** [comment]
Your question is so vague I can't even begin to understand what you're asking. Just import our examples and start running those. I'm not quite sure why you're trying to dig in to the internals.

https://github.com/deeplearning4j/dl4j-0.4-examples

Come back with something less vague and we can help you.

**Comment by w31122534** [comment]
We want to predict future Sensor data. Our tutor suggests that we achieve base on the GravesLSTM (org.deeplearning4j.nn.layers.recurrent.GravesLSTM). But the GravesLSTMCharModellingExample just bases on(conf.layers.GravsLSTM), so We don't know how to use the GravesLSTM implement to predict future Sensor data.

**Comment by raver119** [comment]
Just pick up examples, there's few of them, using GravesLSTM

**Comment by AlexDBlack** [comment]
Note the names: org.deeplearning4j.nn.layers.recurrent.GravesLSTM vs. nn.**conf**.layers.GravesLSTM: the latter is the configuration class, the former actually contains the forward pass and backprop code. Each layer in DL4J has both configuration and implementation.
You should never have to deal directly with the implementation classes, only the configuration classes.

See also:
http://deeplearning4j.org/usingrnns
http://deeplearning4j.org/lstm
http://deeplearning4j.org/recurrentnetwork

**Comment by w31122534** [comment]
Thank you very much, your replies help me a lot.
