### ISSUE TITLE
Shape mismatch when using batch size > 0 with SequenceRecordReaderDataSetIterator

### ISSUE THREAD

**Issue by eanie** [deeplearning4j/deeplearning4j#1306]
When I attempt to use SequenceRecordReaderDataSetIterator with a batch size above 1, I get the following error:

Exception in thread "main" java.lang.IllegalArgumentException: Shapes do not match: x.shape=[100, 100], y.shape=[10, 10, 100]

If I use a batch size of 1, it all works, but the training is erratic as would be expected.

Code example here:  https://gist.github.com/eanie/a1ee0aa8e66485159432

Example data here:  https://gist.github.com/eanie/420d481d889fab4fa40f

Pom file used: https://gist.github.com/eanie/8cf2f4aeef99d26d0be7

**Comment by agibsonccc** [comment]
This has been fixed I think?

**Comment by AlexDBlack** [comment]
Since this was posted the error handling and exceptions for RecordReaderDataSetIterator and SequenceRecordReaderDataSetIterator have been given a pass. It hasn't come up since, either.
