### ISSUE TITLE
Problems using conv layers in CG

### ISSUE THREAD

**Issue by joel-odlund** [deeplearning4j/deeplearning4j#1307]
There seem to be a problem configuring CGs  with conv layers

a simple example,  with stack trace in comments

https://gist.github.com/joel-odlund/4dad9d7fccb34dc2d23c

**Comment by joel-odlund** [comment]
it was suggested to try with a multilayer network config 
https://gist.github.com/AlexDBlack/a4421654a356b03b5f36

seems that this has the same issue, so apparently not related to CG after all

**Comment by AlexDBlack** [comment]
In the latest version of nd4j/dl4j, I'm not seeing any issues with either the CG or MLN versions of the above.
