### ISSUE TITLE
Implement pooling over time (max/average temporal pooling)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1309]
Certain architectures require max pooling over time. For example, the following architectures require it:
http://emnlp2014.org/papers/pdf/EMNLP2014181.pdf
http://arxiv.org/pdf/1503.08909v2.pdf
http://arxiv.org/pdf/1504.01561v1.pdf

**Comment by jsteggink** [comment]
I've seen soms interest in max-over-time on Gitter and it is also something I would be interested to use. Anyone willing to work on this?

**Comment by raver119** [comment]
@jsteggink Yes, looks like we'll be implementing this one

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/2699
