### ISSUE TITLE
Packages not found while running examples

### ISSUE THREAD

**Issue by arthur-dai-618** [deeplearning4j/deeplearning4j#1312]
I followed exactly the steps on http://deeplearning4j.org/quickstart, after IntelliJ downloaded all the dependencies, I select an example and hit run. Then I get lots of errors saying packages related with deeplearning4j, nd4j, slf4j and so on don't exist. Like this:
Error:(3, 27) java: package org.canova.api.util doesn't exist
Error:(4, 44) java: package org.deeplearning4j.models.embeddings doesn't exist
Error:(5, 53) java: package org.deeplearning4j.models.embeddings.inmemory doesn't exist
Error:(6, 51) java: package org.deeplearning4j.models.embeddings.loader doesn't exist
Error:(7, 42) java: package org.deeplearning4j.models.word2vec doesn't exist
Error:(8, 42) java: package org.deeplearning4j.models.word2vec doesn't exist
Error:(9, 61) java: package org.deeplearning4j.models.word2vec.wordstore.inmemory doesn't exist
None of the examples can be run. I'm new to java and maven, could someone tell me why and how to solve this? Thanks in advance!

**Comment by arthur-dai-618** [comment]
I figured it out, when create project from existing sources, I should select "import from maven".

**Comment by AlexDBlack** [comment]
Ok, cool. I'll close this then. Usually it comes up automatically with the option to manage via maven.
