### ISSUE TITLE
Bug in SequenceRecordReaderDataSetIterator.java, method reset() 

### ISSUE THREAD

**Issue by wangyu0air** [deeplearning4j/deeplearning4j#1315]
`381    public void reset() {
 382       recordReader.reset();
 383*      labelsReader.reset();
 384       cursor = 0;
 385       stored = null;
 386       useStored = false;
 387   }`

I got NullPointerException in line 383, I review the code in this file, found that labelsReader can be null when initialized. Maybe here should test "singleSequenceReaderMode == false" before reset labelsReader.

**Comment by AlexDBlack** [comment]
Thanks for flagging this. This has already been fixed in DL4J master, but is an issue in 0.4-rc3.8.
