### ISSUE TITLE
WordVectorSerializer loadTxtVectors from an InputStream

### ISSUE THREAD

**Issue by cmitocar** [deeplearning4j/deeplearning4j#1318]
Can you guys implement a method:

`WordVectorSerializer.loadTxtVectors(InputStream)`

Because this line does not work when the file I'm loading is in a jar:

```
filePath = new ClassPathResource("cardio2-dx-sgns-symps.vec").getFile().getAbsolutePath();
dxSySiWordVec = WordVectorSerializer.loadTxtVectors(new File(filePath));
```

**Comment by raver119** [comment]
1) This is already implemented at current master.

2) You're getting wrong whole idea of ClassPathResource.

File resource = new ClassPathResource("cardio2-dx-sgns-symps.vec").getFile();
dxSySiWordVec = WordVectorSerializer.loadTxtVectors(resource);

That should work, at least if you're using Canova for ClassPathResource.

**Comment by cmitocar** [comment]
Sir. It does not work. If the above mentioned lines are in a class that end up in a jar. And the file I'm loading is in the jar then it does not load

**Comment by raver119** [comment]
Could you please provide gist of your pom.xml?

**Comment by cmitocar** [comment]
Attaching piece of pom.xml
[pom.txt](https://github.com/deeplearning4j/deeplearning4j/files/189404/pom.txt)
