### ISSUE TITLE
Fix evaluation for binary classification case (1 output)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1322]
Currently: Evaluation class doesn't seem to work correctly for binary (single output) case

**Comment by turambar** [comment]
If this is still outstanding post-Strata, I can pitch in.

**Comment by AlexDBlack** [comment]
Thanks. I'm hoping to get this taken care of today if possible :)

**Comment by turambar** [comment]
Haha, thanks! In that case, I'll get out of the way and touch base on some other things post-Strata.

**Comment by AlexDBlack** [comment]
Implemented here: https://github.com/deeplearning4j/deeplearning4j/pull/1326
