### ISSUE TITLE
allow MultipleEpochsIterator to work with DataSet (not just DataSetIterator)

### ISSUE THREAD

**Issue by brooksandrew** [deeplearning4j/deeplearning4j#1330]
I'd like to use MultipleEpochsIterator with a CNN I'm training, but I already have my data/image ingestion pipeline setup and I'm not using ImageRecordReader.  It would be nice to have way to from DataSet or NDArrays directly to DataSetIterator so I can use MultipleEpochsIterator without reworking my backend.

I believe this could be adding a method to DataSet called something like "toDataSetIterator" or allowing MultipleEpochsIterator to be more flexible and take a DataSet rather than just DataSetIterator.

This comes from a question I asked today on Gitter and suggested by @nyghtowl

**Comment by AlexDBlack** [comment]
This can be done with existing functionality in two steps:
List<DataSet> list = DataSet.asList()
DataSetIterator iter = new ListDataSetIterator(list, batchSize)

https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/DataSet.java#L672
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/datasets/iterator/impl/ListDataSetIterator.java

**Comment by nyghtowl** [comment]
@AlexDBlack thanks for identifying the solution in our codebase. Learn something new. I'm reopening this because want to track adding DataSetIterator enhancement to take in DataSet or INDarray objects.

**Comment by brooksandrew** [comment]
@AlexDBlack awesome, thanks!  i've implemented the ListDataSetIterator and got it working.
@nyghtowl thanks for tracking it.  adding to DataSetIterator would be nice :)

**Comment by brooksandrew** [comment]
I'm running into problems when I get to the Evaluation class. It seems the getLabels method on ListDataSetIterator returns java.util.List[String] = null instead of my labels. I tried feeding the Evaluation class an NDArray of my labels, but that didn't work either.

See reproducible example below. I'm using Scala. Should I be taking a different approach with the Evaluation class, or is there a bug here? My ultimate goal is transition my CNN to using batches with multiple epochs. i'm following this example

val dlab = Vector(1,1,0,0,1,0).map(x=>Vector(x)).toNDArray
val ddata = Vector(Vector(90,90,91,88), Vector(80,80,81,78), Vector(7,6,5,5), Vector(4,4,4,4), Vector(76, 72, 73, 72), Vector(56, 62, 80, 82)).toNDArray
val dset = new DataSet(ddata, dlab)

val dsiter = new ListDataSetIterator(dset.asList(), 2)
val eval = new Evaluation(dsiter.getLabels()) // this is what I'd like to do, but encountering error.
print(dsiter.getLabels()) // i believe this is the error. it returns "java.util.List[String] = null" instead of [1,1,0,0,1,0]
