### ISSUE TITLE
Multi-layer perceptron? 

### ISSUE THREAD

**Issue by danyaljj** [deeplearning4j/deeplearning4j#1337]
I can see that you have a class for [multi-layer network](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java), although I am not sure if it is the good old-fashioned ["multi-layer perceptron"]() (and if so, whether it is functional or not, since it is not listed in your [documentations](http://deeplearning4j.org/neuralnetworktable).) 
Any comments are highly appreciated.

**Comment by agibsonccc** [comment]
This is just a multi layer network with dense layers and backprop true. I'm closing this.

**Comment by danyaljj** [comment]
I don't quite understand what you saying; 
(1) Do you have a working MLP implementation? 
(2) If not, are you planning to add one?

**Comment by agibsonccc** [comment]
I'm not quite sure what's not to get. I said the MLP is just a configuration. Look closer at our documentation and you'd see this.

**Comment by danyaljj** [comment]
Gooood! Now you said it!
