### ISSUE TITLE
Updater error in Spark yarn-cluster mode

### ISSUE THREAD

**Issue by threedliteguy** [deeplearning4j/deeplearning4j#1340]
Spark job in yarn-cluster mode gets error on example code.

spark-submit --class org.deeplearning4j.examples.rnn.GravesLSTMCharModellingExample \
    --master yarn-cluster  \
    --deploy-mode cluster   \
    --num-executors 4 \
    --driver-memory 4g \
    --executor-memory 4g \
    --executor-cores 8 \
    --conf "spark.yarn.jar=hdfs://dodeca2.local:8020/spark-assembly-1.6.1-hadoop2.6.0.jar"  \
    --conf "spark.driver.extraJavaOptions=-Dhdp.version=2.4.0.0-169"  \
    --conf "spark.yarn.am.extraJavaOptions=-Dhdp.version=2.4.0.0-169"  \
 hdfs://dodeca2.local:8020/dl4j-spark-cdh5-examples-1.0-SNAPSHOT.jar 

Tried 4 and 8 executors on a single node Ambari 2.2.1 cluster on Ubuntu.  Got different errors (attached logs):

java.lang.IllegalStateException: No updater to combine
        at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.runIteration(SparkDl4jMultiLayer.java:382)

and 

16/04/01 07:18:20 WARN scheduler.TaskSetManager: Lost task 30.0 in stage 32.0 (TID 805, dodeca2.local): java.lang.NullPointerException
        at org.deeplearning4j.nn.updater.MultiLayerUpdater.access$000(MultiLayerUpdater.java:20)
        at org.deeplearning4j.nn.updater.MultiLayerUpdater$MultiLayerUpdaterAggregator.aggregate(MultiLayerUpdater.java:78)
        at org.deeplearning4j.spark.impl.common.updater.UpdaterElementCombiner.call(UpdaterElementCombiner.java:11)

[updater-error.txt](https://github.com/deeplearning4j/deeplearning4j/files/199586/updater-error.txt)
[updater-error-2.txt](https://github.com/deeplearning4j/deeplearning4j/files/199587/updater-error-2.txt)

**Comment by AlexDBlack** [comment]
We've made a considerable number of changes to both spark and updaters since this was posted.
AFAIK combining updaters should be much more robust now.
