### ISSUE TITLE
Add version to deeplearning4j-cli download URL

### ISSUE THREAD

**Issue by Sitin** [deeplearning4j/deeplearning4j#1352]
The problem
-----------------
Currently DL4J CLI can be download from `https://s3-us-west-2.amazonaws.com/skymind/bin/deeplearning4j-cli.tar.gz`. Which means we can't create correctly versioned packages (I am working on Homebrew formula but it's relevant for all package management systems).

Solution
-----------
Add DL4J version to deeplearning4j-cli download url, e.g. `https://s3-us-west-2.amazonaws.com/skymind/bin/deeplearning4j-cli-0.4-rc3.8.tar.gz`.

**Comment by Sitin** [comment]
Just ping me when this will be implemented and I will update Homebrew formula.

**Comment by nyghtowl** [comment]
If we can add Homebrew to the next implementation then  #1355 should stand otherwise that should be commented out in the next release.

**Comment by tmundt** [comment]
Is this issue solved?

**Comment by agibsonccc** [comment]
We are not supporting this.
