### ISSUE TITLE
Bug in PosUimaTokenizer

### ISSUE THREAD

**Issue by vasants** [deeplearning4j/deeplearning4j#1354]
looks there is a small bug in PosUimaTokenizer in snapshot 3.8 - public PosUimaTokenizer(String tokens,AnalysisEngine engine,Collection<String> allowedPosTags) {
if(engine == null)
PosUimaTokenizer.engine = engine; ... should be PosUimaTokenizer.engine == null in the if condition.. not sure if its fixed in 3.9

**Comment by nyghtowl** [comment]
code shows fixed
