### ISSUE TITLE
Embrace syntax highlighting in gh-pages

### ISSUE THREAD

**Issue by Sitin** [deeplearning4j/deeplearning4j#1356]
Currently DL4J uses indentation for code blocks which does not support syntax highlighting:

```
// I am a comment that looks like a code
class GrayscaleDude {
    public void doBoringStuff() {
        /* too boring to be mentioned */
    }
}
```

It became even worse in case of real world examples which [may require line feeds](http://deeplearning4j.org/modelpersistence) on some devices.

Once [moved to Jekyll 3.0](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0) GitHub started to use `kramdown` and `Rouge` as a default Markdown renderers for `gh-pages` which means we may now switch to beautiful and widely known 
```<lang>
```
syntax without any changes to `_config.yml`.

``` java
class LifeInColors {
    // distinguishable comment
    public LifeInColors perverse(GrayscaleDude sadMan) {
        return /* to bright to be exposed */;
    }
}
```

Much better!

**Comment by chrisvnicholson** [comment]
hey folks - so i've been playing with this. i have the iris DBN example looking decent. 

http://deeplearning4j.org/iris-flower-dataset-tutorial.html

pls see the markdown on the editing page. the indents still need a little work. we should apply this to the tutorials where we're showing people a lot of code.
