### ISSUE TITLE
segfault on RNN neural net training

### ISSUE THREAD

**Issue by bennythedataguy** [deeplearning4j/deeplearning4j#1359]
* this segfault happens after a non-deterministic number of iterations
* Using GravesBidirectionalLSTM and GravesLSTM

Here's the error message:

A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x0000000115f6ff33, pid=72640, tid=4867
JRE version: Java(TM) SE Runtime Environment (7.0_67-b01) (build 1.7.0_67-b01)
Java VM: Java HotSpot(TM) 64-Bit Server VM (24.65-b04 mixed mode bsd-amd64 compressed oops)
Problematic frame:
C [libnd4j.dylib+0x2df33] functions::reduce::ReduceFunction<float>::exec(float, int, float, float, int, int, int)+0x4b3

**Comment by bennythedataguy** [comment]
Also, training on batch data, so dims are N x M x T. Dataset created by doing Dataset.merge on a list of data sets.

**Comment by saudet** [comment]
Solved?

**Comment by bennythedataguy** [comment]
I think this has to do with using an old rc3.9 snapshot, so it's not a bug
