### ISSUE TITLE
BaseEarlyStoppingTrainer Epoch not updated if EvaluateEveryNEpoch is > 1

### ISSUE THREAD

**Issue by sadatanwer** [deeplearning4j/deeplearning4j#1364]
I noticed that if the evaluateEveryMEpoch is set to a value > 1, the count of epoch counter is not getting update properly. I think this is mainly because the increment is present in the wrong loop here 
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/earlystopping/trainer/BaseEarlyStoppingTrainer.java#L255

The incrementer is present inside the if () statement, which never gets touched after the first epoch. I should be places outside this if().

**Comment by nyghtowl** [comment]
Thanks for catching this. Fixed with #1374
