### ISSUE TITLE
WavFileRecordReader is not implemented

### ISSUE THREAD

**Issue by plexfit** [deeplearning4j/deeplearning4j#1369]
WavFileRecordReader was mentioned here but it's not implemented n the current deeplearning4j:
http://deeplearning4j.org/image-data-pipeline

Chatted with @agibsonccc  and he said that it might have been removed in earlier versions. Please help us check and confirm.

**Comment by nyghtowl** [comment]
Looks like its in a different location from the doc [here](https://github.com/deeplearning4j/Canova/blob/master/canova-data/canova-data-audio/src/main/java/org/canova/sound/recordreader/WavFileRecordReader.java)

And that image just needs to be updated

**Comment by nyghtowl** [comment]
This does exist in Canova as noted in the image.
