### ISSUE TITLE
sha256 mismatch when installing cli

### ISSUE THREAD

**Issue by skocbek** [deeplearning4j/deeplearning4j#1376]
Following instructions on http://deeplearning4j.org/gettingstarted#cli, I tried installing CLI on a OS X machine and got a SHA256 mismatch.

OS: El Capitan 
Java 8
Homebrew 0.9.9

brew install homebrew/science/deeplearning4j-cli
==> Installing deeplearning4j-cli from homebrew/science
==> Downloading https://s3-us-west-2.amazonaws.com/skymind/bin/deeplearning4j-cli.tar.gz
###### ################################################################## 100.0%

Error: SHA256 mismatch
Expected: aaa664958f5d53570d02d75e7f61a491f5f75372d5721bf4f6c1efe31e971fcb
Actual: b42451cf3c437fa648878b3fde07b7fd521997c0ae22568bb565a13efe00b7d0
Archive: /Library/Caches/Homebrew/deeplearning4j-cli-0.4-rc3.8.tar.gz
To retry an incomplete download, remove the file above.

**Comment by Sitin** [comment]
@agibsonccc. This happened because of #1352. It seems that remote file was updated. I suggest to add semver tag and then I will update the formula.

**Comment by Andy-P** [comment]
I'm receiving the same error as of Sept 17th
Os: EL Capitan
Java 1.7.0
Homebrew 0.9.9

> brew install homebrew/science/deeplearning4j-cli
==> Installing deeplearning4j-cli from homebrew/science
==> Downloading https://s3-us-west-2.amazonaws.com/skymind/bin/deeplearning4j-cli.tar.gz
Already downloaded: /Users/andre/Library/Caches/Homebrew/deeplearning4j-cli-0.4-rc3.8.tar.gz
Error: SHA256 mismatch
Expected: aaa664958f5d53570d02d75e7f61a491f5f75372d5721bf4f6c1efe31e971fcb
Actual: a26bafef4c2fcb9536611409b9158b4793739a847db7345d2b69f583f42e62c2
Archive: /Users/andre/Library/Caches/Homebrew/deeplearning4j-cli-0.4-rc3.8.tar.gz
To retry an incomplete download, remove the file above.

**Comment by agibsonccc** [comment]
cli not relevant anymore.
