### ISSUE TITLE
Examples for Doc2vec on spark

### ISSUE THREAD

**Issue by cqnguyen** [deeplearning4j/deeplearning4j#1401]
Can you guys provide an Apache Spark example for the use of Doc2vec (paragraph2vec) with Apache Spark. It would be greatly appreciated.

**Comment by raver119** [comment]
Unfortunately we don't have proper spark doc2vec implementation right now. It'll be there after current work on backend stuff is done.

**Comment by nkwoh01** [comment]
this looks resolved
