### ISSUE TITLE
Score Iteration NaN

### ISSUE THREAD

**Issue by geekprogramming** [deeplearning4j/deeplearning4j#1411]
I don't know why my CNN Score Iteration is NaN. Who can explain for me? Thank so much.
09:54:37.023 [main] INFO  o.d.o.l.ScoreIterationListener - Score at iteration 60 is NaN
09:54:43.917 [main] INFO  o.d.o.l.ScoreIterationListener - Score at iteration 80 is NaN
09:54:50.709 [main] INFO  o.d.o.l.ScoreIterationListener - Score at iteration 0 is NaN
09:54:57.389 [main] INFO  o.d.o.l.ScoreIterationListener - Score at iteration 20 is NaN
09:55:04.316 [main] INFO  o.d.o.l.ScoreIterationListener - Score at iteration 40 is NaN
09:55:11.941 [main] INFO  o.d.o.l.ScoreIterationListener - Score at iteration 60 is NaN
09:55:19.314 [main] INFO  o.d.o.l.ScoreIterationListener - Score at iteration 80 is NaN
09:55:26.277 [main] INFO  o.d.o.l.ScoreIterationListener - Score at iteration 0 is NaN
.............

**Comment by agibsonccc** [comment]
Closing this, this is a tuning issue. Please come in to gitter for tuning help: https://gitter.im/deeplearning4j/deeplearning4j/tuninghelp
