### ISSUE TITLE
squared gradient momentum and min squared gradient in rms prop

### ISSUE THREAD

**Issue by rubenfiszel** [deeplearning4j/deeplearning4j#1419]
Hello,

I'm trying to reproduce results achieved by this paper

http://www.readcube.com/articles/10.1038/nature14236?shared_access_token=Lo_2hFdW4MuqEcF3CVBZm9RgN0jAjWel9jnR3ZoTv0P5kedCCNjz3FJ2FhQCgXkApOr3ZSsJAldp-tw3IWgTseRnLpAc9xQq-vTA2Z5Ji9lg16_WvCy4SaOgpK5XXA6ecqo8d8J7l4EJsdjwai53GqKt-7JuioG0r3iV67MQIro74l6IxvmcVNKBgOwiMGi8U0izJStLpmQp6Vmi_8Lw_A%3D%3D

Page 10, They use rms prop with the tweaking of squared gradient momentum and min squared gradient with the rmsprop updater. I saw no such things in deeplearning4j.

**Comment by AlexDBlack** [comment]
I'm going to close this now, given that we have support for custom updaters.
