### ISSUE TITLE
Null pointer exception after maven update on generalValidaiton()

### ISSUE THREAD

**Issue by Railer** [deeplearning4j/deeplearning4j#1421]
After doing a maven update on deeplearning4j-core-SNAPSHOT-3.9 I get the following:
https://gist.github.com/Railer/c40acd81efa1c4b471c22873ccd94e88

**Comment by nyghtowl** [comment]
Null layer issue form comp graph resolved 66acec0dbdc608dba5f47dd2b6a937334dbcada4
