### ISSUE TITLE
Getting started guide needs to explain tools & setup better.

### ISSUE THREAD

**Issue by Cryddit** [deeplearning4j/deeplearning4j#1425]
You're going to get a few C/C++ devs, like me, who are finally getting dragged into using Java for the first time, just because Deeplearning4j is an awesome resource and the Stuttgart Neural Network Testbed (an earlier similar project in C/C++) is no longer maintained.  And, like me, some of them are going to arrive with no already-working java dev environment and no knowledge of the tools you're using.

So the "getting started" guide needs to be more explicit about those tools.

*mention the mvn command, what it does, and that it has to be invoked from shell in the same directory as a pom.xml file.  

*mention that you need to "mvn eclipse:eclipse" in the directory with the pom.xml file INSTEAD of letting eclipse attempt to parse the pom.xml file.  The pom.xml file provided with the project is not compatible with the way the most recent eclipse (Mars release) parses them, and it will miss downloading dl4j and nd4j.  The current mvn on the other hand parses the file correctly and will download everything.  I doubt if this is an issue with IntelliJ but I haven't checked. 

*mention that pom.xml file is what maven names project files, and that that's what you have to find in order to work with a maven project. 

*Mention that even though this is a 'git' repository, the dev tools will call it a maven project not a git project.  This is an issue if attempting to import (but see note above about never letting eclipse attempt to import a pom.xml file). 

*Mention that installing the right (version 7+) JDK is not enough.  You must also make sure that you have the matching JRE installed.  Some distributions separate them and can have conflicting versions. Also you must have your *own* installation of the JDK/JRE, because otherwise the distro's package manager is going to have a fight with the needs of your java development environment.   Also version 7+ is not yet in the stable distribution of Debian.

*Mention the minimum version of eclipse/intelliJ in which the maven/mylin integration that your getting started guide assumes, actually exists.  As of 21-April-2016, an appropriate eclipse is not in the stable or testing distros of Debian.

*Mention that you must not install these tools as root.  If you do, then whenever they start trying to download plugins or auto-update, they'll be trying (and failing) to scribble on directories owned by root.  If you want that feature to work you have to run the installer as a regular user so it lands somewhere it's got permission to write. 

Also important to mention in a getting started guide: maven will fail mysteriously if it doesn't have write access to ~/.m2. So if you happen to already have that directory and it belongs to something else? The whole thing won't work until you change the permissions. This can actually happen due to a conflict with an ancient macro processor, but there is no need to explain why: anybody it can happen to will immediately KNOW why when they see the directory name.

**Comment by Cryddit** [comment]
Should be labeled "documentation" and assigned ... I dunno, some low-to-medium priority, I guess.  I expect relatively few people to be affected by this.  But it's crazy if you're one of them.

**Comment by Cryddit** [comment]
Oh.  Thank you @ncleaver. I forked the repo, and I was going to start with this.  But I can't find the doc folder.  Where is the source for the getting started guide?  Do I need to fork a different project to work on docs?

**Comment by ncleaver** [comment]
No problem. If you check out the [Developer Guide](http://deeplearning4j.org/devguide), it contains info/instructions about the DL4J site. Scroll down to "Contributing Documentation: How the Websites Work". 

We do anticipating releasing an update to some of the getting started docs soon though, so I'd start somewhere else if you'd like for now. I'd love your input on the new version when released though, and thanks for the details above!

**Comment by ncleaver** [comment]
Quickstart explains use of IntelliJ IDE only, for now. Otherwise issues here addressed, or will be moved to additional maven troubleshooting shortly.
