### ISSUE TITLE
Which maven dependency contains org.deeplearning4j.nn.conf.layers.EmbeddingLayer?

### ISSUE THREAD

**Issue by rasoolims** [deeplearning4j/deeplearning4j#1428]
I cannot import org.deeplearning4j.nn.conf.layers.EmbeddingLayer;

My current pom.xml is the following:

'''
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>MyGroupID</groupId>
    <artifactId>MyArtifactId</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <nd4j.version>0.4-rc3.8</nd4j.version>
        <dl4j.version>0.4-rc3.8</dl4j.version>
        <canova.version>0.0.0.14</canova.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-nlp</artifactId>
            <version>0.4-rc3.8</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>${dl4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-x86</artifactId>
            <version>${nd4j.version}</version>
        </dependency>

        <dependency>
            <artifactId>canova-api</artifactId>
            <groupId>org.nd4j</groupId>
            <version>${canova.version}</version>
        </dependency>
    </dependencies>
</project>
'''

**Comment by AlexDBlack** [comment]
Embedding layer was added after 0.4-rc3.8 was released.
It will be available in the next release (we are targeting 16th May for that).

**Comment by rasoolims** [comment]
Is there anything in the stable version that has a similar functionality?

**Comment by AlexDBlack** [comment]
Not exactly, no.

Well, yes if you count the fact that a DenseLayer with a one-hot input (like [0,0,1,0,0]) is mathematically the same as the embedding layer, just a lot less efficient (due to a matrix multiply with mostly zeros in it).
