### ISSUE TITLE
SequenceVectors.java is plotting constant minLearningRate instead of current learning rate

### ISSUE THREAD

**Issue by silentsnooc** [deeplearning4j/deeplearning4j#1431]
Just a minor issue but just so you guys don't forget to change that :P

`SequenceVectors` plots the `minLearningRate` which should actually be the _current_ learning rate I guess:

```
log.info("Epoch: [" + currentEpoch+ "]; Words vectorized so far: [" + wordsCounter.get() + "];  Lines vectorized so far: [" + linesCounter.get() + "]; learningRate: [" + minLearningRate + "]");
```

See: [SequenceVectors.java#L199](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/sequencevectors/SequenceVectors.java#L199)

**Comment by agibsonccc** [comment]
Hasn't this been fixed?

**Comment by raver119** [comment]
Fixed ages ago.
