### ISSUE TITLE
Add other LSTM variants

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1440]
(As of the time of posting: this is lower priority. But is worth considering for the future).

A number of LSTM variants exist: http://arxiv.org/pdf/1503.04069v1.pdf
Some of these variants have fewer parameters without significantly impacting performance.

**Comment by Cryddit** [comment]
Yes.  My favorite missing piece is the parallel LSTM for remembering patterns.  

![lstm](https://cloud.githubusercontent.com/assets/5466806/14774258/16fe45b8-0a69-11e6-824d-45b960ec856b.png)

I did this in C++ and found it useful.  If I figure out everything it has to be connected to in dl4j's architecture I'll do it here.

**Comment by AlexDBlack** [comment]
We have both LSTM and GravesLSTM. The former supports CuDNN.
Others don't have good enough relative performance to justify implementing (or to justify the performance hit of not having CuDNN)
