### ISSUE TITLE
MultiLayerNetwork.numParams(): NPE if net has not been initialized

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1441]
calling MultiLayerNetwork.numParams() before .init() gives a null pointer exception.
Also: the javadoc is inaccurate; should say that it returns the number of parameters (including biases) for the network.

**Comment by eraly** [comment]
returns 0 with a logger message saying call init
https://github.com/deeplearning4j/deeplearning4j/pull/1824
