### ISSUE TITLE
VPTree|KDTree

### ISSUE THREAD

**Issue by Milanvdm** [deeplearning4j/deeplearning4j#1443]
An issue to remind you guys to check the clustering algorithms.

KDTree seems to be very slow on my hand.
It is not clear on how to use VPTree to find the knn for a Datapoint which is not in the tree itself. Also, the index for Datapoint seems a bit out of place.

**Comment by agibsonccc** [comment]
I've done a ton with the vptree at this point. I would recommend using that. @huitseeker also did some work on kdtrees it looks like. I'm closing this.
