### ISSUE TITLE
Get an automated CI infrastructure in place so people don't have to build stuff from source

### ISSUE THREAD

**Issue by owlmsj** [deeplearning4j/deeplearning4j#145]
Or how could I package the last stable version to a runnable jar? 

Checked at download.html but the latest is 0.0.3.2.5

Tried to generate a simple runnable and via maven shade plugin. Neither worked...

Sure this a dumb question, but dont know what to do. 

Just a link / tutorial will help!

Thanks!

**Comment by agibsonccc** [comment]
Not yet. Will work on getting this out here soon.

**Comment by pinthor** [comment]
Thanks, @agibsonccc ! Is there an estimated time when it is ready? Something that I could help?

**Comment by agibsonccc** [comment]
We want to get an automated infrastructure in place for this. I'm working on migrating off of travis so we can do a CI -> release cycle rather than the way we're doing it right now.

**Comment by agibsonccc** [comment]
Done. http://build.deeplearning4j.org

**Comment by owlmsj** [comment]
Great!
