### ISSUE TITLE
[Documentation] Is X feasible?

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#1450]
We keep getting questions about "Is x common thing feasible with deeplearning4j?" Yes. Yes it is.
We need to add a page we can link to explaining this. If a link to a page isn't sufficient answer for someone asking  that question (they already obviously haven't read the website)  they are clearly demonstrating unwillingness to do any reading. I think also updating the gitter guidelines calling this stuff out will be helpful.

We need to run a great community, but the questions need to be of value, not just laziness.

**Comment by ncleaver** [comment]
Agreed. I'll look at the current "Beginners, please read" too. I wonder if there is a better/more obvious/more annoying way to display that intro, or force read/agree on joining. I don't think so, but I'll check.
