### ISSUE TITLE
[3.9 UiServer GUI] Axis are sometimes hard to read and interpret due to overlapping numbers etc

### ISSUE THREAD

**Issue by Habitats** [deeplearning4j/deeplearning4j#1455]
The screenshot pretty much speaks for itself:
![capture](https://cloud.githubusercontent.com/assets/1082096/14815483/e898689a-0bab-11e6-99d6-7cd1efb5ac67.PNG)

Does the Y-axsis on the left show 0.0001 or 0.00001? It's hard to tell without checking the source.

**Comment by treo** [comment]
To solve this problem I'd suggest to switch to the 1e-X format when the numbers get smaller than 0.001

**Comment by agibsonccc** [comment]
New UI. Not relevant.
