### ISSUE TITLE
[Docs] Broken link: using rnns page

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1457]
Link on the using rnns page is broken:
![image](https://cloud.githubusercontent.com/assets/2360237/14818775/34fe5b8a-0c02-11e6-903c-3321ecc4b533.png)

Should point to
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/api/iterator/DataSetIterator.java

**Comment by ncleaver** [comment]
updated link
