### ISSUE TITLE
Remove application.conf from deeplearning4j-nlp artifact

### ISSUE THREAD

**Issue by wobu** [deeplearning4j/deeplearning4j#1458]
@gitter channel i was told this configuration is just some leftover and can be removed

Nevertheless libraries shouldn't deliver an application.conf.
In my case this conflicts somehow with the application.conf in my test scope and the test cases, which uses akka, are failing.

**Comment by raver119** [comment]
Actually we should remove akka dependency, since there should be nothing relying on it anymore.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/1470
