### ISSUE TITLE
Add convenience function for getting number of inputs/outputs for a layer (or net)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1461]
Afaik, there are currently no easier ways to determine the number of inputs to a network. For example, getting it from the config currently requires something like this:

``` java
((FeedForwardLayer)net.getLayer(0).conf().getLayer()).getNIn()
```

This is quite inelegant; we should provide a convenience method for this...

**Comment by eraly** [comment]
.summary() does this now.
