### ISSUE TITLE
Request for INDArray.putScalar(int row, int col, double val)

### ISSUE THREAD

**Issue by dkmisra** [deeplearning4j/deeplearning4j#1463]
Can we have the following function

``INDArray.putScalar(int row, int col, double val);``

Currently you have to do this as ``INDArray.putScalar(new int[]{int row, int col}, double val);``

However, if you call these functions 10000s of time every few seconds then these temporary integer arrays can annoy GC. 

The analog function ``INDArray.getDouble(int row, int col)`` exists.

**Comment by AlexDBlack** [comment]
Thanks. Closing this one in favor of this issue: https://github.com/deeplearning4j/nd4j/issues/870
