### ISSUE TITLE
error in running deeplearning4j-example:Word2VecRawTextExample

### ISSUE THREAD

**Issue by mansiisnam** [deeplearning4j/deeplearning4j#1464]
i get this error: 
Information:Using javac 1.7.0_79 to compile java sources
Information:2016-04-29 11:15 - Compilation completed with 1 error and 0 warnings in 2s 331ms
Error:java: java.lang.ArrayIndexOutOfBoundsException: 465790

**Comment by raver119** [comment]
Mind posting full stack exception?

**Comment by mansiisnam** [comment]
Thank you for your reply! It's the problem of software(idea).
