### ISSUE TITLE
Better flow on quick start for dependencies (what's needed to start a new project)

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#1467]
From @JuhoKupiainen
So here is what I did... I created a new Scala project and added deeplearning4j-core, nd4j-x86 and org.nd4j to its build.sbt file as dependencies as suggested by this page: http://deeplearning4j.org/quickstart.html. Unfortunately when I tried to resolve the dependencies with sbt, it could not find the canova dependency... So I thought I'd try without it... So I copy pasted the DBNMnist example source code to a file in the project and since Eclipse didn't whine about any missing dependencies I ran the app.

We need to find a way of summarizing a minimal pom example and that referencing:
https://github.com/deeplearning4j/dl4j-0.4-examples (the pom.xml in the root)

is the easiest way to do that;

**Comment by ncleaver** [comment]
Will fix this week - part of ongoing updates to a few documentation pages.

**Comment by ncleaver** [comment]
minimal pom and dependencies already updated
