### ISSUE TITLE
[Docs] Document how to use Evaluation and RegressionEvaluation classes

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1483]
Afaik these are not discussed at all on the website.
(RegressionEvaluation was added after 0.4-rc3.8 was released)

**Comment by AlexDBlack** [comment]
Old issue, but still relevant. Updating here instead of opening a new issue

In addition to the above, we need to document:
- ROC and ROCMultiClass
- ROC HTML export
- How to perform evaluation for Spark (Evaluation class and ROC)

Note that ROCMultiClass and the ROC HTML export was added after 0.7.2 was released.

**Comment by tomthetrainer** [comment]
Sample Doc then find a place to put it, probably in the Intro to Neural Net section

# Evaluating model output

Deeplearning4J provides an Evaluation Iterface for evaluating how well your model performed. 

https://deeplearning4j.org/doc/org/deeplearning4j/eval/IEvaluation.html

An example 

```
Evaluation eval = new Evaluation(3);
INDArray output = model.output(testData.getFeatureMatrix());
eval.eval(testData.getLabels(), output);
log.info(eval.stats());
log.info(eval.confusionToString());
log.info(String.valueOf(eval.falsePositiveRate(0)));
```

```
RegressionEvaluation eval = new RegressionEvaluation(3);
eval.eval(labels,predicted);

```

ROC (Receiver Operating Characteristic) for binary classifiers, using the specified number of threshold steps.

More later..

**Comment by AlexDBlack** [comment]
@tomthetrainer yep, that's good. doesn't have to be sophisticated IMO.
I'd mention a few additional things:
(a) Evaluation class supports top N accuracy (i.e., top 5 etc - commonly used for imagenet models)
(b) the .evaluate(DataSetIterator), .evaluateRegression(DataSetIterator), etc methods on MultiLayerNetwork
(c) It is possible to merge IEvaluation instances - might be relevant/useful sometimes
(d) evalTimeSeries can take into account a mask array - i.e., masked-out time steps won't be counted in the stats.

**Comment by tomthetrainer** [comment]
Build a rough draft and pass to mara

**Comment by AlexDBlack** [comment]
https://deeplearning4j.org/evaluation
