### ISSUE TITLE
Clarifying the documentation on "importing a time series" for RNN networks. 

### ISSUE THREAD

**Issue by mhotrx** [deeplearning4j/deeplearning4j#1485]
This issue concerns clarifying the explanation on how to import time series data in the section  http://deeplearning4j.org/usingrnns#data. after the line "each line in the data files represents one time step."

This issue was answered by Alex Black and here is my paraphrasing of his explanation: 

<<When importing time series data using the class CSVSequenceRecordReader each line in the data files represents one time step with the earliest time series observation in the first row (or first row after header if present) and the most recent observation in the last row of the csv.  Each feature time series is a separate column of the of the csv file.   For example if you have five features in time series, each with 120 observations, and a training & test set of size 53 then there will be 106 input csv files(53 input, 53 labels).  The 53 input csv files will each have five columns and 120 rows.   The label csv files will have one column (the label) and one row.  >>

**Comment by mhotrx** [comment]
above text between<> was removed by formatter.  

When importing time series data using the class CSVSequenceRecordReader each line in the data files represents one time step with the earliest time series observation in the first row (or first row after header if present) and the most recent observation in the last row of the csv.  Each feature time series is a separate column of the of the csv file.   For example if you have five features in time series, each with 120 observations, and a training & test set of size 53 then there will be 106 input csv files(53 input, 53 labels).  The 53 input csv files will each have five columns and 120 rows.   The label csv files will have one column (the label) and one row.

**Comment by tomthetrainer** [comment]
Added additional info on csv sequence record reader
