### ISSUE TITLE
Example of unsupervised anomaly detection using DL4J?

### ISSUE THREAD

**Issue by nouramoubayed** [deeplearning4j/deeplearning4j#149]
Dear Everyone, 

DL4J claims the ability to solve anomaly detection problems (spam filtering/ fraud detection). can you please refer me to a documentation or example on how to solve such problems using it? 
thanks

**Comment by jpatanooga** [comment]
Spam filter is the canonical two class classification training problem.

I that case you'd have two sets of emails ("ham", "spam" as they are
referred to in literature for this exercise). Each kind of email would have
a different label on it. We'd train the DBN to convergence and then use
this model to classify new emails.

Does this make sense?

Anomaly detection takes on more nuance depending on the vertical, but its
fundamentally a classification problem as well.

JP

**Comment by nouramoubayed** [comment]
Thank Josh for your reply, 

I have around 30GB of unlabelled data and the goal is to detect anomaly behaviour.  

In the spam detection example the data is most likely labeled spam/good and the classifier is then trained with good samples and tested with spam/good data, 

do you have any deep learning example in mind that can apply anomaly detection for unlabelled data (unsupervised)?

**Comment by rkommineni77** [comment]
Deep Learning models can act as generative models. So, if you just train entire dataset using unsupervised learning, the model should learn all the regular patterns. In prediction phase, for each sample get a reconstruction error. If reconstruction error is too high, you can assume that sample is an outlier/anomaly.

**Comment by agibsonccc** [comment]
Thanks @rkommineni77  for answering this. Closing.
