### ISSUE TITLE
Add validation for nIn and nOut

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#1493]
Add validation for nIn and nOut especially for layers when it is required (e.g. output layer or when using batchnorm without cnn) vs when it's not (e.g. local response normalization layer) and for special cases (e.g. cnnInputSize is set).

Consider when developing functionality for #1461

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/2307
