### ISSUE TITLE
IllegalStateException when installing custom loss function

### ISSUE THREAD

**Issue by fac2003** [deeplearning4j/deeplearning4j#1497]
Hello, I am trying to install a custom loss function in DL4J v0.4-rc3.8 on the GravesLSTMCharModellingExample. I used:
    
```
public class CustomLoss extends BaseLossFunction {
        @Override
        public String name() {
            return "CustomLoss";
        }
… (all function throw UnsupportedOperationException at this time)
}
```

```
String customLossFunction= "CustomLoss";
OptimizationAlgorithm optimizationAlgo = OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT;
...
.layer(2,
new RnnOutputLayer.Builder(LossFunctions.LossFunction.CUSTOM).customLossFunction(customLossFunction).activation("softmax")
```

I expected an exception in the loss function implementation. Instead, I get:

> Exception in thread "main" java.lang.IllegalStateException: Invalid loss function: CUSTOM
>     at org.deeplearning4j.nn.layers.BaseOutputLayer.getGradientsAndDelta(BaseOutputLayer.java:210)
>     at org.deeplearning4j.nn.layers.BaseOutputLayer.backpropGradient(BaseOutputLayer.java:133)
>     at org.deeplearning4j.nn.layers.recurrent.RnnOutputLayer.backpropGradient(RnnOutputLayer.java:74)

**Comment by fac2003** [comment]
(I tried testing this against 0.4-rc3.9-SNAPSHOT but got a different issue.)

> Exception in thread "main" java.lang.AbstractMethodError: org.nd4j.linalg.cpu.CpuNDArrayFactory.toFlattened(CLjava/util/Collection;)Lorg/nd4j/linalg/api/ndarray/INDArray;
> 	at org.nd4j.linalg.factory.Nd4j.toFlattened(Nd4j.java:1577)
> 	at org.deeplearning4j.nn.layers.BaseLayer.params(BaseLayer.java:260)
> 	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.params(MultiLayerNetwork.java:846)
> 	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pack(MultiLayerNetwork.java:905)
> 	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.initMask(MultiLayerNetwork.java:1769)
> 	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:364)

**Comment by treo** [comment]
At the moment you can't use rc3.9 from the snapshot repository, you have to build it from source yourself.

**Comment by fac2003** [comment]
I have not found instructions for building from master on GitHub and it looks like I am missing some dependencies so I will wait for some more stable snapshot. Looks like the issue was addressed from what I could tell with the source. Since the code was reorganized, is there any reason why you would not use polymorphism on LossFunctions and still need to rely on enums and a special custom case where you use a class?

**Comment by eraly** [comment]
Closing
