### ISSUE TITLE
add Levenberg-Marquardt algorithm and Bayesian regularization

### ISSUE THREAD

**Issue by rawhazard** [deeplearning4j/deeplearning4j#1499]
L-M algorithm together with Bayesian regularization is a really powerful combination for some kind of problem. They together can dramatically reduce training time and improve generalization capability of the network (see Neural Netowork Matlab Toolbox). Suggest to add this features to the library.

**Comment by abvaalgit** [comment]
two years has passed from this definition issue ...do this added to project

**Comment by AlexDBlack** [comment]
@abvaalgit No, it hasn't been added, and it's not a priority for us. (I think you're the second person to ask since the original issue?)

**Comment by abvaalgit** [comment]
so how can i fitt data set and able to predict new data ..
hkw can i train my network by input layer hiddin layer and output layer ..just like in Matlab fitting neural network tools

**Comment by AlexDBlack** [comment]
@abvaalgit Please don't go asking unrelated questions on long-closed issues.
Have a look at the quickstart and our examples.
https://deeplearning4j.org/docs/latest/deeplearning4j-quickstart
https://github.com/deeplearning4j/dl4j-examples
