### ISSUE TITLE
Maven archetypes for starting your own DL4J project

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#1500]
Maven supports archetypes for generating the basic code and structure of a new project. 

Using a maven archetype, it would be easier to start a new project based on dl4j. There could even be several like:
- A blank slate, with only the correct dependencies set up
- A hello world type of project for...
  - using an already trained model
  - training a new model from your data

**Comment by tomthetrainer** [comment]
I agree a maven archetype would be great.

**Comment by georgerb** [comment]
+1 for a maven archetype

**Comment by sabman** [comment]
see: https://github.com/wmeddie/dl4j-trainer-archetype

**Comment by tomthetrainer** [comment]
@wmeddie Do you want to take ownership of this ticket? 

You seem to have more Maven power than I have.

**Comment by raver119** [comment]
What we're going to do with this? Maybe polish & publish mentioned archetype?

cc @wmeddie

**Comment by wmeddie** [comment]
Yeah.  If we are happy with the structure of https://github.com/wmeddie/dl4j-trainer-archetype I can just move it over.  If anyone has any opinions on how it should look like I'm happy to implement them.  I do think maybe we want a slightly more minimal template.

**Comment by AlexDBlack** [comment]
Closing this in favor of https://github.com/deeplearning4j/deeplearning4j-docs/issues/46
