### ISSUE TITLE
deeplearning4j-core unit test failures

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1508]
The following unit tests are currently failing:

~~GradientCheckTestsComputationGraph.testLSTMWithSubset~~
~~TestVariableLengthTSCG.testVariableLengthSimple, .testOutputMasking~~
~~BatchNormalizationTest.testCnnShapeBatchNormBack, .testDnnShapeBatchNormBack~~
**Crash on: GravesBidirectionalLSTMTest.testConvergence()**
~~TestDropout.testDropoutSimple, .testDropoutMultiLayer~~
~~TestVariableLengthTS.testVariableLengthSimple, .testOutputMasking~~
~~TestDecayPolicies.testLearningRateScheduleSingleLayer, .testLearningRateScheduleMLN~~
~~WeightInitUtilTests.testRelu, .testVI, .testUniform, .testNormalize, .testXavier~~

**Comment by AlexDBlack** [comment]
Partially fixed: https://github.com/deeplearning4j/deeplearning4j/pull/1511

**Comment by nyghtowl** [comment]
No longer crashing. If still crashing reopen.
