### ISSUE TITLE
word2vec visualization not working in 0.0.3.3

### ISSUE THREAD

**Issue by rkommineni77** [deeplearning4j/deeplearning4j#151]
When I try to visualize vectors created by word2vec (through tsne plot, http://localhost:8080/render), I get a blank page. 
After careful examination the vectors that are generated are like this:
225453.07718360753,-219777.60215940353,play 
197225.36281318875,-199289.82967921722,dur 

I believe in 0.0.3.2.8 (from https://groups.google.com/d/msg/deeplearning4j/eaIlOXha3E8/FFknXjdK2FUJ) , the coordinates are: 
0.48167046033089944, -2.242607378700511,Think  

While, I am not really sure if there are issues in TSNE itself, I believe d3 scaling issue.

I am not a d3 expert, but something like:
var xMax = d3.extent(x, function(d) { return +d;});     
var yMax = d3.extent(y, function(d) { return +d; });    
 scaleX = d3.scale.linear().domain([+xMax[0], +xMax[1]]).       range([0, 1]);   
 scaleY = d3.scale.linear().domain([+xMax[0], +xMax[1]]).     range([0, 1]);

should scale ordinates back to 0 to 1. There may be a better way to scale these values.

**Comment by pinthor** [comment]
Same here. But running the latest example of Word2VecExample  gaves me page HTTP ERROR 500

**Comment by takawitter** [comment]
This problem seems to be of dropwizard:0.7.0.
I'm working on moving to dropwizard 0.8.0.
Now it works but I still got poor image..
https://github.com/takawitter/deeplearning4j/pull/1
https://github.com/takawitter/deeplearning4j/pull/1/files
