### ISSUE TITLE
Implement adversarial loss

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#1515]
Adversarial found to be more effective than MSE for unsupervised continuous datasets

Review http://arxiv.org/pdf/1511.06434v2.pdf and papers recently released at ICLR 2016

**Comment by raver119** [comment]
@AlexDBlack what would you say, do we want this?

**Comment by AlexDBlack** [comment]
GAN-related loss functions should go in samediff (and maybe can be just something we import), if we do decide to support it.
