### ISSUE TITLE
Add eval(DataSetIterator)

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#1523]
We should be able to pass a test datasetiterator for evaluation. It should run the while loop and print results.

**Comment by AlexDBlack** [comment]
Essentially equivalent functionality on MultiLayerNetwork:
https://github.com/deeplearning4j/deeplearning4j/blob/3996c6165f1cd011c1d5e3d36841e5343f84d419/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java#L2203

**Comment by nyghtowl** [comment]
I just added output version to take in DataSetIterator because thought I wanted to use it for one of the examples. Agree with Alex that evaluate he pointed to handles this. @agibsonccc what else are you wanting here or can we close?

**Comment by agibsonccc** [comment]
Nah that's good thanks!
