### ISSUE TITLE
BlackOut to speed up RNN for large datasets (esp vocab)

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#1524]
Review paper http://arxiv.org/pdf/1511.06909v7.pdf for opportunities to integrate techniques.

**Comment by dapifer** [comment]
This appears to be a duplicate of #1491.  Will be addressing it there; can we close this as a duplicate?

**Comment by AlexDBlack** [comment]
Closed as duplicate: https://github.com/deeplearning4j/deeplearning4j/issues/1491
