### ISSUE TITLE
Nd4j init NullPointerException

### ISSUE THREAD

**Issue by mlaubre** [deeplearning4j/deeplearning4j#1525]
Hi

Unable to create words vector on latest snapshot.
 - Executing the following piece of code: https://gist.github.com/mlaubre/e7a5ea75a76cba6daf5dd4824a2c0d5d
 - I get this error: https://gist.github.com/mlaubre/57bf9f648d010cc01710e0f1d69fef93
 - Maven POM: https://gist.github.com/mlaubre/fdf53363c817960da6aef072cedbbbb9

Regrads
Martin Laubre
martin.laubre@gmail.com

**Comment by raver119** [comment]
Unfortunately you're not using latest code. nd4j-x86 was retired month ago. For rc3.9 valid backends are:
- nd4j-native
- nd4j-cuda-7.x

But they are not available as snapshots yet, and should be built manually.

**Comment by pavin** [comment]
i have the same problem. nd4j-api-rc3-9-snapshot's  throws NullPointerException as below

Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:4788)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4716)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:148)


wait your help.

**Comment by treo** [comment]
@pavin 
The exactly same thing applies to you: If you are going to use rc3.9-SNAPSHOT, you have to build from source AND use nd4j-native instead of nd4j-x86.
