### ISSUE TITLE
ArrayOutOfBound when training model

### ISSUE THREAD

**Issue by thisIsNiceName** [deeplearning4j/deeplearning4j#1528]
Hi, so as I said in the title, everytime i try to train my model i have an arrayOutOfBoundException.
From what i understand on the live chat, it's because of my RecordReader constructor parameters, but i'm not really sure to understand what the labelIndex is. 
Also, how to tell the model to only train of the first N pictures of each classes ? 

One of you asked me to sumbit an issue so here is it. 

I use as a dataSet the apple_pie and baby_back_ribs folder of this database : https://www.vision.ee.ethz.ch/datasets_extra/food-101/

Here are the 2 folders if you want to test my code with the dataset and not download the whole dataBase : http://puu.sh/oOvpG/618a771dd3.zip

The error i got is the following : 

**Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 56
	at org.nd4j.linalg.util.FeatureUtil.toOutcomeVector(FeatureUtil.java:38)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.getDataSet(RecordReaderDataSetIterator.java:207)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:150)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:288)
	at org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:42)
	at DeepLearningImage.main(DeepLearningImage.java:203)**

everytime in the function toOutcomeVector, the index is a way higher value that the numOutcomes, wich in my case is equals to 2.

Here is the source code : http://puu.sh/oOvKI/4c5fc30f57.java

Thank you very much

**Comment by thisIsNiceName** [comment]
Fixed the issue. Still if someone could re-explain me what that labelIndex parameter represent because i did not understand it at all

**Comment by nyghtowl** [comment]
labelIndex is the position in the list that has the label numerical value; thus, label index. When you append a label to the feature list you need to track the position in the list where you store that label value. And note the label value is just a numerical representation for your label.

Let's say you have 10 classifications where bird is the 3rd classification or represented by 3. If you have a picture of a bird that is 28X28 pixels and you append the label. You will put number 3 at the end of the feature list which is of length 784. The feature list starts with index 0 and goes to 783. When you append the label it is put into the index position 784. So you would pass in the labelIndex 784.
