### ISSUE TITLE
Word2Vec Lucene conflict with Elasticsearch

### ISSUE THREAD

**Issue by alexminnaar** [deeplearning4j/deeplearning4j#153]
I created a SentenceIterator class the uses Elasticsearch (version 1.3.4) to retrieve text data that I parse into sentences.  It seems that the Elasticsearch client's Lucene dependency conflicts with Word2Vec's Lucene dependency.  It creates the error

```java.lang.NoSuchMethodError: org.apache.lucene.util.UnicodeUtil.UTF16toUTF8(Ljava/lang/CharSequence;IILorg/apache/lucene/util/BytesRef;)V```

which means that there are multiple versions of Lucene on the classpath.  Specifically, I believe that it is Word2Vec's ```fit()``` method that uses Lucene.  I am using Scala with sbt.

**Comment by smarthi** [comment]
Its may be multiple versions in the classpath on your end. DL4j is presently at Lucene 4.10.3, ElasticSearch 1.3.4 is at Lucene 4.9.1.  

The method signature that's in error is available in 4.10.3 but not in 4.9.1 which is ElasticSearch's lucene version.  Possible that you could upgrade your ElasticSearch to 1.4.3 then u will not be seeing this error ?

**Comment by agibsonccc** [comment]
Going to close this. Please re open if there's another class path issue. Thanks!
