### ISSUE TITLE
package java.time.format does not exist in java 7, its available in java 8

### ISSUE THREAD

**Issue by jagadale** [deeplearning4j/deeplearning4j#1533]
compiling deeplearning4j on 
hardware details - power/ppc64le and 
Ubuntu14.04.4, 
using openjdk java-7
------
Its been found that last component of build is failed with following error. As per deeplearning4j dependency I am using java-7 but expected package it not available.  

[package-time.formate-not-found.txt](https://github.com/deeplearning4j/deeplearning4j/files/263099/package-time.formate-not-found.txt)

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project deeplearning4j-ui-components: Compilation failure: Compilation failure:
[ERROR] /home/jagadale/mldl/dl4j/deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-ui-components/src/main/java/org/deeplearning4j/ui/components/chart/style/StyleChart.java:[30,24] package java.time.format does not exist
[ERROR] /home/jagadale/mldl/dl4j/deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-ui-components/src/main/java/org/deeplearning4j/ui/components/chart/style/StyleChart.java:[30,24] package java.time.format does not exist
[ERROR] -> [Help 1]

**Comment by AlexDBlack** [comment]
Thanks. That's due to an accidental (and, unused) import.
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/1534
