### ISSUE TITLE
Build failure of deeplearning4j-ui-components

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#1543]
Cloned a fresh repo of DL4J. ui-components is failing to build
```
[INFO] deeplearning4j-ui-components ....................... FAILURE [  1.299 s]
```

Output that I could grab from the most recent build:
https://gist.github.com/crockpotveggies/cd8c9ff996c37e0636d7735d1834476a

**Comment by AlexDBlack** [comment]
Fixed: https://github.com/deeplearning4j/deeplearning4j/pull/1544

**Comment by crockpotveggies** [comment]
@AlexDBlack nice work and thanks for the quick response!
