### ISSUE TITLE
Implement Custom Loss Functions

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1546]
(Opening this issue to get the discussion started)

Relevant classes, for reference:
- Built-in loss calculation code: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/lossfunctions/LossCalculation.java
- BaseOutputLayer that call the above https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/BaseOutputLayer.java

To properly implement this so that it is easy for users: we'll need to do a few things
1. Create a simple interface that users have to implement, to actually define the functionality
2. Provide methods in the configuration that take the above interface
3. Solve the configuration -> JSON and JSON -> configuration issue (possibly via classpath discovery of the above interfaces) - both for MultiLayerNetwork and ComputationGraph

Some other things of note:
- We'll should make the gradient checking util much easier to use (i.e., auto-sets relevant configuration options) so that users can actually check their implementations. Plus, document it
- Provide at least one example of how to use this functionality

Overall: adding this functionality shouldn't be especially hard; main thing is to get the design right.

**Comment by fac2003** [comment]
Looks about right, but to implement 3, I would suggest the standard Java service provider mechanism. See 
https://docs.oracle.com/javase/tutorial/ext/basics/spi.html
Essentially, in addition to the implementation for each CustomLoss you would make sure these implementations are defined in a jar file with a manifest that declares that each implementation satistifes the service provider.

As an example, consider this code from Goby:

https://github.com/CampagneLaboratory/goby/tree/stable/src/edu/cornell/med/icb/goby/compression/ChunkCodecHelper.java

   ```
private static final ServiceLoader<ChunkCodec> codecLoader = ServiceLoader.load(ChunkCodec.class);

 private ChunkCodecHelper() {
    }

    public static synchronized ChunkCodec load(String codecName) {
        ChunkCodec codec = null;
        if (codecName != null) {
            codecLoader.reload();
            for (final ChunkCodec c : codecLoader) {

                if (c.name().equals(codecName)) {
                    LOG.debug("Will use chunk codec " + c.name());
                    codec = c;
                    break;
                }
            }
            if (codec == null) {
                LOG.warn("Could not find codec " + codecName);
            }
        }
        return codec;
    }
```

Look in [build.xml](https://github.com/CampagneLaboratory/goby/blob/stable/build.xml) for the manifest declaration that defines the implementation of the service providers supported by the JAR:

```
<manifest>
                <attribute name="Specification-Title" value="Goby"/>
                <attribute name="Specification-Vendor"
                           value="Institute for Computational Biomedicine (ICB), Weill Medical College of Cornell University"/>
                <attribute name="Implementation-Version" value="${label} (${buildstamp})"/>
                <attribute name="Implementation-Vendor"
                           value="Institute for Computational Biomedicine (ICB), Weill Medical College of Cornell University"/>
                <attribute name="Main-Class" value="edu.cornell.med.icb.goby.modes.GobyDriver"/>
                <attribute name="Built-By" value="${user.name}"/>
            </manifest>

            <service type="edu.cornell.med.icb.goby.reads.ReadCodec">
                <provider classname="edu.cornell.med.icb.goby.reads.ReadCodecImpl"/>
                <provider classname="edu.cornell.med.icb.goby.reads.ReadCodec2"/>
            </service>
            <service type="edu.cornell.med.icb.goby.compression.ChunkCodec">
                <provider classname="edu.cornell.med.icb.goby.compression.NullChunkCodec"/>
                <provider classname="edu.cornell.med.icb.goby.compression.NotCompressedChunkCodec"/>
                <provider classname="edu.cornell.med.icb.goby.compression.GZipChunkCodec"/>
                <provider classname="edu.cornell.med.icb.goby.compression.BZip2ChunkCodec"/>
                <provider classname="edu.cornell.med.icb.goby.compression.HybridChunkCodec1"/>
                <provider classname="edu.cornell.med.icb.goby.compression.HybridChunkCodec2"/>
            </service>
            <!-- define the implementation of NormalizationMethods as Java ServiceProviders: -->
            <service type="edu.cornell.med.icb.goby.stats.NormalizationMethod">
                <provider classname="edu.cornell.med.icb.goby.stats.BullardUpperQuartileNormalization"/>
                <provider classname="edu.cornell.med.icb.goby.stats.AlignedCountNormalization"/>
            </service>
        </jar>

```

**Comment by fac2003** [comment]
Also, the config should simply accept an implementation of LossFunction, and consult the implementation to retrieve its name when it needs to serialize to JSON (or use the name to look up the implementtion using the service provider to go from JSON to conf). There is no reason that the user of the library should have to set the function twice (as custom, then as its name). 

You can then remove the enum that currently indicates the type of function because you will always have a loss function, which can provide all you need (name and implementation of the methods whose code is currently handled differently according to enum).

**Comment by AlexDBlack** [comment]
@fac2003 thanks. yeah, service provider is probably the better mechanism.
Same JSON issue for custom layers and custom GraphVertex implementations (latter is for ComputationGraph) so we'll probably want to implement all 3 using the same approach.

**Comment by agibsonccc** [comment]
This is done.
