### ISSUE TITLE
Out of date advice for DocumentIterator

### ISSUE THREAD

**Issue by robinchesterman** [deeplearning4j/deeplearning4j#1550]
On[ this page](http://deeplearning4j.org/word2vec) of the docs (possibly others) it says to use SentenceIterator wherever possible.

Apparently as of rc3.8 it doesn't matter.

**Comment by raver119** [comment]
Since rc3.7 (or 3.8?) we don't care about which iterator user passes into w2v/d2v/glove/seqvec model. Everything gets wrapped into proper thing transparently.

**Comment by tomthetrainer** [comment]
Done
