### ISSUE TITLE
web site: scaling on AWS broken link

### ISSUE THREAD

**Issue by fac2003** [deeplearning4j/deeplearning4j#1557]
The new web site looks great, but a broken link: http://deeplearning4j.org/gpu_aws.html
See paragraph:

A. A versatile n-dimensional array class for Java and Scala, DL4J is Scalable on Hadoop, utlizes GPU support for **scaling on AWS**, includes Canvova, a general vectorization tool for Machine-Learning libs, and most of all relies on ND4J: A linear algebra library 2x as fast as Numpy.

**Comment by chrisvnicholson** [comment]
fixed
