### ISSUE TITLE
[Doc] about description of cosine distance in word2vec

### ISSUE THREAD

**Issue by everpeace** [deeplearning4j/deeplearning4j#156]
At the second last paragraph of ["Introduction to Word2vec"](https://github.com/SkymindIO/deeplearning4j/blob/gh-pages/word2vec.md#introduction-to-word2vec):

> Broadly speaking, we measure words' proximity to each other through their cosine similarity, which gauges the distance/dissimilarity between two word vectors. __A perfect 90-degree angle represents identity__; i.e. France equals France, while Spain has a cosine distance of 0.678515 from France, the highest of any other country.

I think 90-degree doesn't mean "identity" but 0-degree.  What would be the original intention of the author??

**Comment by agibsonccc** [comment]
Ah right. This means high cosine similarity. Say it means close to identity.
