### ISSUE TITLE
Performance problems with DropOut in 3.9

### ISSUE THREAD

**Issue by mjakobus** [deeplearning4j/deeplearning4j#1562]
It seems there is a performance problem with dropOut in Version 3.9.

For a small ffn with 3 denseLayers an epoch takes 187ms. If I set dropOut to 0 but leave reagularization on true, the time per epoch shrinks to about 50ms.

The network:
```
        MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                .seed(seed)
                .iterations(iterations)
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                .learningRate(2e-3)
                .regularization(true)
                .updater(Updater.NESTEROVS)
                .momentum(0.9)
                .list(4)
                .layer(0, new DenseLayer.Builder().nIn(inputNum).nOut(28)
                        .weightInit(WeightInit.RELU)
                        .activation("leakyrelu")
                        .dropOut(0.9)
                        .build())
                .layer(1, new DenseLayer.Builder().nIn(28).nOut(32)
                        .weightInit(WeightInit.RELU)
                        .activation("leakyrelu")
                        .dropOut(0.8)
                        .build())
                .layer(2, new DenseLayer.Builder().nIn(32).nOut(32)
                        .weightInit(WeightInit.RELU)
                        .activation("leakyrelu")
                        .dropOut(0.8)
                        .build())
                .layer(3, new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD)
                        .nIn(32)
                        .nOut(outputNum)
                        .activation("softmax")
                        .build())
                .pretrain(false)
                .backprop(true)
                .build();
```

Here the hotspot screenshot:
![hotspots_profiled_mkl_39_call_tree](https://cloud.githubusercontent.com/assets/17254924/15369759/52bf4b6e-1d34-11e6-8a9e-650f2d65c428.png)

**Comment by mjakobus** [comment]
One more thing:
Cuda performance is enormously affected by this issue.
Time per epoch with cuda and dropout: **270ms**
Time per epoch with cuda and dropout=0: **60ms** 

Graphicscard: GTX 950

**Comment by raver119** [comment]
This will be fixed in a bit different way, without putScalar etc.

**Comment by mjakobus** [comment]
Thanks for working on this issue. The bad dropout performance is quite annoying, because it is an important regularization method.
Seems like the next release is like christmas for me :+1:

**Comment by raver119** [comment]
Don't worry, it'll have proper performance for both cpu and cuda

**Comment by raver119** [comment]
Implemented here: https://github.com/deeplearning4j/deeplearning4j/pull/1656 
here: https://github.com/deeplearning4j/nd4j/pull/1015
and here: https://github.com/deeplearning4j/libnd4j/pull/237

Now dropout is fully native for both cpu and cuda.

However, will be merged a bit later.
