### ISSUE TITLE
Spark DBN is very slow on MNIST data

### ISSUE THREAD

**Issue by xlmxlm** [deeplearning4j/deeplearning4j#1567]
It took about 30 mins to run DBN on Windows Deeplerning4j. Then I construct an exactly same DBN network on Spark DL4J. It took over 27 hours.

**Comment by raver119** [comment]
Yea, DBN is subject for optimizations in nearest future. As well as spark improvements. We're going introduce viable solutions there after we done with general native code.

**Comment by agibsonccc** [comment]
I'm closing this. Spark optimizations are next.
