### ISSUE TITLE
[Doc] viterbi snippet doesn't show up in Word2vec

### ISSUE THREAD

**Issue by everpeace** [deeplearning4j/deeplearning4j#157]
In the section of ["Moving Windows"](https://github.com/SkymindIO/deeplearning4j/blob/gh-pages/word2vec.md#windows), there is a part which seems to display some code snippet for setting up viterbi algorithm:

> ```<script src="http://gist-it.appspot.com/https://github.com/agibsonccc/java-deeplearning/blob/master/deeplearning4j-examples/src/main/java/org/deeplearning4j/example/word2vec/MovingWindowExample.java?slice=112:121"></script>```

However, the link doesn't work and `MovingWindowExample.java` has already gone ([dl4j-examples](https://github.com/SkymindIO/dl4j-examples) doesn't contain the file either).  Which link would be the most appropriate?

**Comment by agibsonccc** [comment]
Ah that's out of date. Will work on taht.
