### ISSUE TITLE
No spark 2.11 package for canova-spark

### ISSUE THREAD

**Issue by davireis** [deeplearning4j/deeplearning4j#1570]
Yesterday I was migrating from rc3.8 to rc3.9, and I see that dl4j-spark depends on spark-core_${scala.binary.version}, which is perfect because I can set this in my build to get the 2.11 spark version, compatible with the rest of my build. However, it also depends on canova-spark, which depends on the hardcoded spark-core_2.10. Can we use the same build setup from dl4j-spark for canova-spark?

**Comment by agibsonccc** [comment]
This is fixed now.  https://github.com/deeplearning4j/Canova/pull/168
