### ISSUE TITLE
[Doc] on description of label handling in Window class in Word2vec

### ISSUE THREAD

**Issue by everpeace** [deeplearning4j/deeplearning4j#158]
In the last part of the section ["Moving Windows"](https://github.com/SkymindIO/deeplearning4j/blob/gh-pages/word2vec.md#windows), there is a paragraph below:

> If you do this:
> ```    String label = window.getLabel();```
> on anything containing that window, it will automatically contain that label. This is used in bootstrapping a prior distribution over the set of labels in a training corpus.

I can't understand this paragraph exactly.  Could you explain a little bit more detail??  Just getting label change the internal state of that window????

**Comment by agibsonccc** [comment]
The label is the label for a particular window. This is for supervised learning of segments of text.
