### ISSUE TITLE
SequenceRecordReaderDataSetIterator: implement regression on multiple columns

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1581]
RecordReaderDataSetIterator supports this: https://github.com/deeplearning4j/deeplearning4j/blob/6a0efffb3ad831db60153552632315e03df6ce8f/deeplearning4j-core/src/main/java/org/deeplearning4j/datasets/canova/RecordReaderDataSetIterator.java#L114

However, there is no equivalent multiple-regression-columns constructor for SequenceRecordReaderDataSetIterator: https://github.com/deeplearning4j/deeplearning4j/blob/ceb478e64985754b2b80126b3b4030017680ef9f/deeplearning4j-core/src/main/java/org/deeplearning4j/datasets/canova/SequenceRecordReaderDataSetIterator.java#L96

**Comment by agibsonccc** [comment]
This is done?

**Comment by AlexDBlack** [comment]
I'm going to close this as a "won't fix" - RecordReaderMultiDataSetIterator + MultiDataSetWrapperIterator can do it, and we'll be changing things quite a bit once the datavec rewrite is implemented...
