### ISSUE TITLE
lstm example 

### ISSUE THREAD

**Issue by vinayakumarr** [deeplearning4j/deeplearning4j#1587]
I have data set which is given below
3 3 373 27 9 615 9 16 10 34 0 8 0 199 65917 1319 122 402 319 183
3 3 77 12 4 66 4 3 0 5 0 14 3 50 106 139 38 164 53 109
3 3 86 6 2 6 2 0 0 1 0 25 0 4 284 77888 19 66 11 25
3 3 469 21 7 291 7 43 15 82 0 207 0 181 115646 59073 294 928 112 675
3 3 2090 21 7 4035 7 17 8 40 0 317 10 717 1033 25661 142 2054 1795 1023
3 3 691 18 6 597 6 30 16 61 0 245 18 273 719 2352305 213 1106 324 719
6 6 229 0 8 526 0 11 1 13 0 6 5 101 7246 2082 120 141 288 1570
3 3 1158 9 3 649 3 16 6 17 1 247 38 477 592 987626 82 1305 653 707
4 4 211 0 10 429 0 16 9 20 0 3 0 106 42725 27302 4280 133 477 1567

The first column is the target which has 9 classes and around 1803 features. I am trying to apply lstm for prediction. I would like to implement lstm for my dataset to test with different network topologies as one memory block with one cell, two memory block with two cell,three memory block with three cell and four memory block with four cell. could you please provides the example for the above dataset.

**Comment by AlexDBlack** [comment]
DL4J's LSTM implementation is exactly the same as every other LSTM implementation out there - i.e., there is no independent control over "memory block" and "cell" counts (fwiw nobody really uses that terminology either). To control the number of LSTM units, it's just .nOut(...) in the configuration.
