### ISSUE TITLE
HistogramIterationListener error

### ISSUE THREAD

**Issue by mrroots** [deeplearning4j/deeplearning4j#1591]
with rc3.9:
model.setListeners(new HistogramIterationListener(1));
->
INFO  [2016-05-25 06:48:47,586] org.eclipse.jetty.util.log: Logging initialized @4623ms
INFO  [2016-05-25 06:48:47,640] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: assets for path /assets/*
      port: 0
      port: 0
WARN  [2016-05-25 06:48:47,718] org.glassfish.jersey.internal.Errors: The following warnings have been detected: HINT: Cannot create new registration for component type class org.deeplearning4j.ui.exception.GenericExceptionMapper: Existing previous registration found for the type.

INFO  [2016-05-25 06:48:47,726] io.dropwizard.server.ServerFactory: Starting UiServer
WARN  [2016-05-25 06:48:47,746] org.glassfish.jersey.internal.Errors: The following warnings have been detected: HINT: Cannot create new registration for component type class io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper: Existing previous registration found for the type.

INFO  [2016-05-25 06:48:47,800] org.eclipse.jetty.setuid.SetUIDListener: Opened application@3f6da92d{HTTP/1.1}{0.0.0.0:56483}
INFO  [2016-05-25 06:48:47,800] org.eclipse.jetty.setuid.SetUIDListener: Opened admin@387de9e3{HTTP/1.1}{0.0.0.0:56484}
INFO  [2016-05-25 06:48:47,803] org.eclipse.jetty.server.Server: jetty-9.2.9.v20150224
WARN  [2016-05-25 06:48:47,935] org.eclipse.jetty.util.component.AbstractLifeCycle: FAILED i.d.j.MutableServletContextHandler@1ab0e6f7{/,null,STARTING}: java.lang.NoClassDefFoundError: org/glassfish/jersey/process/internal/RequestExecutorFactory
! java.lang.ClassNotFoundException: org.glassfish.jersey.process.internal.RequestExecutorFactory
! at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_40]
! at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_40]
! at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_40]
! at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_40]
! at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.7.0_40]
! at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_40]
! at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.7.0_40]
! ... 66 common frames omitted
! Causing: java.lang.NoClassDefFoundError: org/glassfish/jersey/process/internal/RequestExecutorFactory
! at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.7.0_40]
! at java.lang.ClassLoader.defineClass(ClassLoader.java:792) ~[na:1.7.0_40]
! at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.7.0_40]
! at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[na:1.7.0_40]
! at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[na:1.7.0_40]
! at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.7.0_40]
! at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_40]
! at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_40]
! at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_40]
! at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.7.0_40]
! at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_40]
! at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.7.0_40]

**Comment by AlexDBlack** [comment]
This looks like a dependency conflict, not an issue with dl4j.
The UI relies on dropwizard, which has a bunch of transitive dependencies. Including projects with conflicting versions of the transitive dependencies (such as Spark, amongst others) can cause these sorts of issues. Use exclusions in maven or remove the dependency that is causing the issue.
