### ISSUE TITLE
Time series forecast using numerical data

### ISSUE THREAD

**Issue by AnnaKim77** [deeplearning4j/deeplearning4j#1592]
Hi, there.

I make RNN codes for predict(forecast) N step at a time by reference to BasicRNNExample.java.

-> Sample code(BasicRNNExample.java) used character type data. I apply this code to my numerical data. character data must to perform vectorization but my data can use in the raw.
(using CSVRecordReader)

In Prediction step, I use **MultiLayerNetwork.rnnTimeStep(testInit)** and print it(my code are as below)

```javascript
        for (int epoch = 0; epoch < 10; epoch++) {

            System.out.println("Epoch : " + epoch);

            // 4-1. train the data
            net.fit(trainingData);
            // 4-2. clear current stance from the last example
            net.rnnClearPreviousState();
            // 4-3. put the first number into the rnn as initialization
            INDArray testInit = Nd4j.zeros(1, 1);
            testInit.putScalar(new int[]{0, 0}, 3.5);

            INDArray compOutput = net.output(testInit);

            INDArray output = net.rnnTimeStep(testInit);
            System.out.println("outputvalue : " + output.toString());
//          System.out.println("output : " + output.tensorAlongDimension(output.size(0)-1,1,0));
            
//            for (int j = 0; j <= 25000; j++) {
//                double outputValue = output.getDouble();
//                System.out.println(outputValue);
//
//                INDArray nextInput = Nd4j.zeros(1,1);
//                nextInput = nextInput.putScalar(new int[]{0, 0}, outputValue);
//                output = net.rnnTimeStep(nextInput);
//
//            }

        }
```

The output value might be probability. isn't it? (cuz, outputvalues were under 1)
I want to get real predict value. how i get it?

**Comment by agibsonccc** [comment]
Change the output to identity instead of softmax.

**Comment by AnnaKim77** [comment]
@agibsonccc i used "tanh" activation function . And there is no "identity" in activation function list.

**Comment by agibsonccc** [comment]
Which "list" are you looking at? o_0

https://github.com/deeplearning4j/dl4j-0.4-examples/blob/master/src/main/java/org/deeplearning4j/examples/feedforward/regression/RegressionSum.java#L67

**Comment by AnnaKim77** [comment]
@agibsonccc oh i didn't saw that. and i have one more question. my data's length is 5000. and i predict 10 step ahead from the last value of input data. In this situation, **j<5010** code is correct?  
```javascript
for(int j= 0 ; j <5010;j++){
double outputValue = output.getDouble();
System.out.println(ouputValue);
}   
```

and testInit value is first value of input data.
