### ISSUE TITLE
Problems when loading gray scale 16 bit .png images

### ISSUE THREAD

**Issue by JohnTheDang** [deeplearning4j/deeplearning4j#1594]
I have a data set of 16 bit gray scale .png images. When I try to load them using my code from rc3.8 in the new version, rc3.9, the feature matrix in each data set is seen as just zeros.
The code is here: https://gist.github.com/JohnTheDang/173b4f8b7e89e03f0142d901daee0104
Can it be that Dl4j has lost support of 16 bit images?

I have included two example images.
![000000_0-a_upper_small](https://cloud.githubusercontent.com/assets/17123674/15537035/8b69f672-2274-11e6-909b-0ac3a042075c.png)
![000000_0-p_upper_small](https://cloud.githubusercontent.com/assets/17123674/15537036/8e7cbd9a-2274-11e6-9c1e-54b7973b02d2.png)

**Comment by crockpotveggies** [comment]
@saudet was the new Canova OpenCV native loader included in the rc3.9 release?

**Comment by saudet** [comment]
Yes it was

**Comment by saudet** [comment]
Should be fixed now. Thanks for reporting!
