### ISSUE TITLE
CUDA Error - MemcpyAsync failed

### ISSUE THREAD

**Issue by DevinCalado** [deeplearning4j/deeplearning4j#1595]
Hey guys.  I just setup CUDA on my windows machine- I ran the nVidia CUDA examples without issues.  I'm trying to get started with CUDA in dl4j now, but I'm running into an error that I can't seem to find any reference to online:

https://gist.github.com/DevinCalado/cd97307e9e66a0392ccbc43cab25a32e

I've added the following to my POM and commented out the native-x86 backend dependency:
```
  <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-cuda-7.5</artifactId>
            <version>${nd4j.version}</version>
   </dependency>
```

Has anyone seen this error before?  Any ideas?  Thanks,

**Comment by raver119** [comment]
Could you please show me your full pom.xml?

**Comment by raver119** [comment]
Nevermind. I've checked your log and know the answer.

rc3.9 release contained a bug, that was affecting some of our examples. It's already fixed (fixes are available at current libnd4j master) and we'll have release with fixes availabe.

**Comment by DevinCalado** [comment]
Thanks.  I'll give it a go on the next release.
