### ISSUE TITLE
multiple binding problem with dl4j-spark and deeplearning4j-ui

### ISSUE THREAD

**Issue by pavin** [deeplearning4j/deeplearning4j#1596]
my pom.xml includes dl4j-spark and i just add deeplearning4j-ui

I am now getting

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/pavin/.m2/repository/org/slf4j/slf4j-log4j12/1.7.10/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/pavin/.m2/repository/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.deeplearning4j.ui.weights.HistogramIterationListener.<init>(HistogramIterationListener.java:64)
	at org.deeplearning4j.ui.weights.HistogramIterationListener.<init>(HistogramIterationListener.java:58)

**Comment by aditidatta** [comment]
Please refer to the website [http://www.slf4j.org/codes.html#multiple_bindings](url)

It says:
> SLF4J API is designed to bind with one and only one underlying logging framework at a time. If more than one binding is present on the class path, SLF4J will emit a warning, listing the location of those bindings.
When multiple bindings are available on the class path, select one and only one binding you wish to use, and remove the other bindings. For example, if you have both slf4j-simple-1.7.21.jar and slf4j-nop-1.7.21.jar on the class path and you wish to use the nop (no-operation) binding, then remove slf4j-simple-1.7.21.jar from the class path.
The list of locations that SLF4J provides in this warning usually provides sufficient information to identify the dependency transitively pulling in an unwanted SLF4J binding into your project. In your project's pom.xml file, exclude this SLF4J binding when declaring the unscrupulous dependency. For example, cassandra-all version 0.8.1 declares both log4j and slf4j-log4j12 as compile-time dependencies. Thus, when you include cassandra-all as a dependency in your project, the cassandra-all declaration will cause both slf4j-log4j12.jar and log4j.jar to be pulled in as dependencies. In case you do not wish to use log4j as the the SLF4J backend, you can instruct Maven to exclude these two artifacts as shown next:
```
<dependencies>
  <dependency>
    <groupId> org.apache.cassandra</groupId>
    <artifactId>cassandra-all</artifactId>
    <version>0.8.1</version>
    <exclusions>
      <exclusion> 
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-log4j12</artifactId>
      </exclusion>
      <exclusion> 
        <groupId>log4j</groupId>
        <artifactId>log4j</artifactId>
      </exclusion>
    </exclusions> 
  </dependency>
</dependencies>
```
>

Try to edit the pom.xml file in the directory deeplearning4j-ui. 
Can you please show the pom.xml files of those two packages?

**Comment by pavin** [comment]
Thank you.

But, i already did it and then met another problem.
additionaly other several attempts have failed

Exception in thread "main" java.lang.NoSuchFieldError: WRITE_DURATIONS_AS_TIMESTAMPS
	at com.fasterxml.jackson.datatype.joda.ser.DurationSerializer.<init>(DurationSerializer.java:28)
	at com.fasterxml.jackson.datatype.joda.ser.DurationSerializer.<init>(DurationSerializer.java:25)
	at com.fasterxml.jackson.datatype.joda.JodaModule.<init>(JodaModule.java:45)
	at io.dropwizard.jackson.Jackson.configure(Jackson.java:44)
	at io.dropwizard.jackson.Jackson.newObjectMapper(Jackson.java:23)
	at io.dropwizard.setup.Bootstrap.<init>(Bootstrap.java:64)
	at io.dropwizard.Application.run(Application.java:68)
	at org.deeplearning4j.ui.UiServer.createServer(UiServer.java:191)
	at org.deeplearning4j.ui.UiServer.getInstance(UiServer.java:81)
	at org.deeplearning4j.ui.weights.HistogramIterationListener.<init>(HistogramIterationListener.java:64)
	at org.deeplearning4j.ui.weights.HistogramIterationListener.<init>(HistogramIterationListener.java:58)

**Comment by aditidatta** [comment]
I had the same problems. Not all the dependencies are added to the pom files. I had to check all the dependencies and edit the pom files if needed. There were many errors while building. And sometimes what happens that the jar files of all the dependencies don't get properly downloaded like a jar file will be there in the maven repository but it will be broken. So you need to fix these. Btw did you successfully build libn4j, nd4j and canova?

Along with the exceptions, `[ERROR]` tags during build may help you to understand the problem better. 

And you can always download the already built jar files of the project until the fixes are there.

**Comment by pavin** [comment]
do i have to build nd4j and libnd4j manually? 
combination of deeplearning4j-core and deeplearing4j-ui worked well without any manual build.
What should I do? what should i check?

**Comment by raver119** [comment]
There's always an option: execute UiServer separately, out of spark, and use it.

**Comment by aditidatta** [comment]
No you don't have to build manually.

> 
additionaly other several attempts have failed
>
Exception in thread "main" java.lang.NoSuchFieldError: **WRITE_DURATIONS_AS_TIMESTAMPS**
at com.fasterxml.jackson.datatype.joda.ser.DurationSerializer.(DurationSerializer.java:28)
>

I think your `jackson-databind` version is older than what is needed. You will atleast need **v2.5** to use WRITE_DURATIONS_AS_TIMESTAMPS. #https://github.com/FasterXML/jackson-databind/issues/616

To check the version, you just need to check the value of `<jackson.version>` property from `dropwizard-parent-0.8.0.pom` file (which can be found in `<your dropwizard maven repo>/dropwizard-parent/` )

You can also follow what raver119 suggested.

**Comment by pavin** [comment]
I think the problem is that dl4j-spark use jackson-databind 2.4.4 and deeplearing4j-ui use 2.5.1
I want to use dl4j-spark and jacson-databind together.

**Comment by agibsonccc** [comment]
My suggestion here would be to take a look at:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/dl4j-spark/pom.xml

Maybe add a dependency management section for the relevant versions of
jackson you need? We would love a minor pull request for this.
