### ISSUE TITLE
Fatal error while training CNN

### ISSUE THREAD

**Issue by rawhazard** [deeplearning4j/deeplearning4j#1597]
This error appears from time to time, while training a CNN. OS and hardware details are included in the logs here attached.
Log file:
https://gist.github.com/rawhazard/8999f30a8b42f35980cee6200043056a
Source code:
https://gist.github.com/rawhazard/68797b7d02d34492ab84b61659a2419a

**Comment by saudet** [comment]
Have you tried to build from source? They are chances that https://github.com/deeplearning4j/libnd4j/pull/207 fixed this issue.

**Comment by rawhazard** [comment]
Are you talking about OpenBLAS? Should I build OpenBLAS from source?

**Comment by treo** [comment]
No, he means building libnd4j and ND4J from source

**Comment by rawhazard** [comment]
Can you point me to a guide to do that? Is [this](https://github.com/deeplearning4j/libnd4j/blob/master/windows.md) enough for installing BOTH nd4j and libnd4j from source?

**Comment by treo** [comment]
Yes, that should be enough.

**Comment by eraly** [comment]
@rawhazard Did you run into any more problems?

**Comment by rawhazard** [comment]
Not so far...apparently compiling rc3.10 SNAPSHOT solved the problem. This is a good guide that may be useful to the case:
http://deeplearning4j.org/buildinglocally

**Comment by agibsonccc** [comment]
Thanks. Closing this then.
