### ISSUE TITLE
Documentation request: List of layers available and how to use

### ISSUE THREAD

**Issue by TheDoorIsBroken** [deeplearning4j/deeplearning4j#1602]
Looking for a cheat sheet to help understand the various types of layers (ConvolutionLayer, SubsamplingLayer..) in a multilayer Neural network , and rules for using them (eg builder errors when one illegally follows another)

**Comment by AlexDBlack** [comment]
Quickref covers all layer types: https://deeplearning4j.org/quickref#layers
