### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by xhudik** [deeplearning4j/deeplearning4j#1603]
```
git clone https://github.com/deeplearning4j
cd deeplearning4j
./setup.sh
```

_[ERROR] Failed to execute goal on project deeplearning4j-core: Could not resolve dependencies for project org.deeplearning4j:deeplearning4j-core:jar:0.4-rc3.10-SNAPSHOT: Could not find artifact **org.nd4j:nd4j-native:jar:0.4-rc3.10-SNAPSHOT** in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]_

nd4j-native:jar:0.4-rc3.10-SNAPSHOT - desnt exist yet. There should be something else

thanks

**Comment by agibsonccc** [comment]
@xhudik That script doesn't work right now. We need to work on libnd4j in to that script.

**Comment by xhudik** [comment]
@agibsonccc  - how can i compile the project? Is there some working work around?

**Comment by AlexDBlack** [comment]
@xhudik we suggest people don't compile unless they have a good reason to (like, actually developing nd4j or dl4j). Otherwise, use the versions on maven central.
If you do want to develop dl4j: go here https://gitter.im/deeplearning4j/deeplearning4j/earlyadopters
