### ISSUE TITLE
 HistogramIterationListener with dl4j-spark

### ISSUE THREAD

**Issue by pavin** [deeplearning4j/deeplearning4j#1616]
i tested HistogramiterationListerner with deeplearning4j-core and it works well.
now, i'm testing HistogramiterationListerner on Spark (deeplearning4j-ui & dl4j-spark)
and facing a lot of dependency conflicts.
so i wonder  it is possible using HistogramIterationListern on spark.

**Comment by raver119** [comment]
Yes, it is possible.

At very least there's two options:
- You can manually exclude jersey 1.x in hadoop/spark deps, and it'll use jersey 2.x coming with dropwizard
- You can use remote UiServer

**Comment by pavin** [comment]
Thank you!!
I solve that so easily with your help :)
