### ISSUE TITLE
symbol lookup error when executing dl4j-0.4-examples on POWER with CUDA

### ISSUE THREAD

**Issue by negiyas** [deeplearning4j/deeplearning4j#1620]
When I execute dl4j-0.4-examples on POWER with CUDA.
It causes errors with the following error messages.
I pulled and built the latest version of DL4J from the git.

Picked up _JAVA_OPTIONS: -Dos.arch=ppc64le
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building DeepLearning4j Examples 0.4-rc0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.4.0:java (default-cli) @ deeplearning4j-examples ---
o.d.e.c.LenetMnistExample - Load data....

o.d.e.c.LenetMnistExample - Build model....
/shared/java-8-openjdk-ppc64el/bin/java: symbol lookup error: /tmp/javacpp655291853668108/libjnind4j.so: undefined symbol: _ZN9NativeOps16setOmpNumThreadsEi

**Comment by agibsonccc** [comment]
That looks like an out of date libnd4j

**Comment by eraly** [comment]
@negiyas Can you rebuild with the latest releases of libnd4j?
