### ISSUE TITLE
Evaluation is error prone

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#1624]
Evaluation and data sets should be reviewed.

One suggestion would be 1 class to encapsulate all the logic for evaluating a test set.

**Comment by agibsonccc** [comment]
Extending from this maybe a trainer class might be a good start? Eg a spark trainer and a normal trainer? This could encapsulate the train test pipeline.

**Comment by AlexDBlack** [comment]
We now have evaluate(DataSetIterator) and evaluateRegression(DataSetIterator), evaluateRoc() and doEvaluation(IEvaluation, DataSetIterator) methods for MultiLayerNetwork (and equivalents for Spark). These make evaluation much simpler than it used to be.
