### ISSUE TITLE
TfidfRecordReader doesn't append the labels correctly

### ISSUE THREAD

**Issue by AkshitaT** [deeplearning4j/deeplearning4j#1625]
My implementation of TfidfRecordReader is giving me the following output:

Examples labeled as 1 classified by model as 0: 44 times
Examples labeled as 1 classified by model as 1: 5956 times
Warning: class 0 has never appeared as a true label. This class was excluded from the average recall

Where, 1 is Spam and 0 is ham. My dataset has 3340 ham and 3350 spam emails. After performing certain fine tuning measures, I debugged the network, and checked the ‘IntWritable' field in the ‘records’ field has the appended label value set to ‘1’ for EVERY record. Looks like, TfidfRecordReader is not reading the labels correct.

Reproducible repo: https://github.com/AkshitaT/StackedDenoisingAutoencoder-Spam/tree/master

Debugger screenshot for reference:
<img width="1280" alt="screen shot 2016-05-31 at 2 28 35 pm" src="https://cloud.githubusercontent.com/assets/5699550/15689863/1708b4ac-273e-11e6-9549-83d341e95dc2.png">

Console Output: https://gist.github.com/AkshitaT/3cae0fc19694119d5e5c63de5c43a1b2

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/Canova/pull/192
