### ISSUE TITLE
The training crashes the jvm randomly 

### ISSUE THREAD

**Issue by sadatanwer** [deeplearning4j/deeplearning4j#1630]
Hey,
I noticed that at times during the training phase of my EarlyStoppingTrainer the jvm crashes and its usually 
```
# JRE version: Java(TM) SE Runtime Environment (8.0_65-b17) (build 1.8.0_65-b17)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.65-b01 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libnd4j.dylib+0x2802f]  _ZN9functions6reduce14ReduceFunctionIfE10execScalarEPfPiS3_+0xef
```

Just rerunning the code usually works fine, and this is very random, or at least I dont really know what are the chain of events that are leading to it.

**Comment by raver119** [comment]
Are you able to compile from sources? Probably it's already fixed on current master of libnd4j/nd4j

**Comment by sadatanwer** [comment]
Ah no, I have not tried the latest, this is with the 3.9 release. I can check that in a few days.

**Comment by agibsonccc** [comment]
I'm guessing this has been fixed with the release going out monday. I'm closing this.
