### ISSUE TITLE
Predict method throws error with RNN

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#1639]
Need to investigate and resolve

**Comment by agibsonccc** [comment]
Has this been resolved? /cc @AlexDBlack

**Comment by nyghtowl** [comment]
Still an outstanding todo

**Comment by AlexDBlack** [comment]
I'd say the only real change here is to throw a useful exception on 3+d input arrays.
The predict method (returning an int array) doesn't make sense for time series.
