### ISSUE TITLE
Adding AUC to the org.deeplearning4j.eval.Evaluation class 

### ISSUE THREAD

**Issue by soilad** [deeplearning4j/deeplearning4j#1644]
Ideally, adding visualization of an _ROC curve along with the corresponding AUC_.

Otherwise, provision of _AUC in the Evaluation class_ (.stats method) would help to readily evaluate a model on a metric besides the F1 score.

**Comment by pabloa** [comment]
+1

**Comment by agibsonccc** [comment]
We've added ROC: https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/eval/ROC.java
