### ISSUE TITLE
NaN's after running StandardScaler fit() and transform() on dataset

### ISSUE THREAD

**Issue by DevinCalado** [deeplearning4j/deeplearning4j#1646]
Hi guys, I've been having issues with normalizing my training data. I'm getting NaN results on the std calculation that used in the StandardScaler. The issue seems to have popped up a few days ago for me and I haven't been able to figure out why.

My POM:
https://gist.github.com/DevinCalado/5b0283435fe077533d0fd35bf12b2ef3

Scaling code:
https://gist.github.com/DevinCalado/37d0a8337ebf0eca5e1b413d16b998f3

Training data read from CSV, before normalization step:
https://gist.github.com/DevinCalado/61a02e88147bd5f6a2cccab5555fb8bf

Training data after running scaler.fit() and scaler.transform:
https://gist.github.com/DevinCalado/ac1da78fbafccb8471a47ea53ae55c28

I don't see any reason why I am receiving NaN's on this training data. It should be valid.

Any thoughts?

**Comment by AlexDBlack** [comment]
If you look at your training data, you have some columns with all the same value (all 0s or all 1s).
Standard scalar does (value - mean)/stdev -> stdev = 0 for columns with all of the same values.

Now, we *could* add something like a small epsilon value (perhaps conditionally, if stdev = 0 for a column) but that wouldn't work well for something like all 1s (i.e., 1/1e-6 = 1e6).

@eraly maybe you can add a simple check for stdev of 0 (or, max==min for min/max normalization) and output a warning via a logger to StandardScaler and the new Normalizers (in the fit(DataSetIterator) method)?

**Comment by DevinCalado** [comment]
Ah, that makes a lot of sense. I guess that's why I have been only running into this issue on small subsets of ~3m records.  

Thanks for pointing it out!

**Comment by eraly** [comment]
Will do.

**Comment by eraly** [comment]
@DevinCalado Thanks for filing this issue. It actually unearthed another bug in our C++ backend.
Changes merged into master. Closing.

**Comment by DevinCalado** [comment]
@eraly No problem. Cheers!
