### ISSUE TITLE
org.deeplearning4j.earlystopping.saver.getLatestModel() loading the best mode instead of the latest model

### ISSUE THREAD

**Issue by dhewzulla** [deeplearning4j/deeplearning4j#1651]
org.deeplearning4j.earlystopping.saver.LocalFileModelSaver.java (version 0.4-rc3.11-SNAPSHOT)

line 100:

 @Override
    public MultiLayerNetwork getLatestModel() throws IOException {
        String confOut = FilenameUtils.concat(directory,bestFileNameConf);
        String paramOut = FilenameUtils.concat(directory,bestFileNameParam);
        String updaterOut = FilenameUtils.concat(directory,bestFileNameUpdater);
        return load(confOut,paramOut,updaterOut);
    }

as the result it is loading the best model, instead of the latest model, I think it should be corrected to the following:

 @Override
    public MultiLayerNetwork getLatestModel() throws IOException {
        String confOut = FilenameUtils.concat(directory,latestFileNameConf);
        String paramOut = FilenameUtils.concat(directory,latestFileNameParam);
        String updaterOut = FilenameUtils.concat(directory,latestFileNameUpdater);
        return load(confOut,paramOut,updaterOut);
    }

**Comment by agibsonccc** [comment]
Mind submitting a pull request? Happy to discuss it there.

**Comment by dhewzulla** [comment]
ok, will do it. Thank you.
