### ISSUE TITLE
Histogram iteration listener: biases not always rendering correctly

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1653]
Consider the following config:
https://gist.github.com/thisIsNiceName/d84282393bf0661be9469c4fa04eb3b5

Note that the biases (layer 10) aren't rendering correctly here:
![image](https://cloud.githubusercontent.com/assets/2360237/15853751/bb26c91a-2ce9-11e6-8397-461b1a3f974a.png)

**Comment by agibsonccc** [comment]
Not relevant: New GUI
