### ISSUE TITLE
missmatche npl:paravec dominant groups

### ISSUE THREAD

**Issue by DYelamos** [deeplearning4j/deeplearning4j#1657]
Hello. I am running paragraphVectorsClassifierExample with these modifications under videogame reviews. 

For each labeled class i have 1000 train population and 400 test population.

The last bit in the output is a simple class in which i collect results. 

`

package org.deeplearning4j.examples.nlp.paragraphvectors;

public class ParagraphVectorsClassifierExample {

    ParagraphVectors paragraphVectors;
    LabelAwareIterator iterator;
    TokenizerFactory tokenizerFactory;

    private static final Logger log = LoggerFactory.getLogger(ParagraphVectorsClassifierExample.class);

    public static void main(String[] args) throws Exception {

      ParagraphVectorsClassifierExample app = new ParagraphVectorsClassifierExample();
      app.makeParagraphVectors();
      app.checkUnlabeledData();
        /*
                Your output should be like this:

                Document 'health' falls into the following categories:
                    health: 0.29721372296220205
                    science: 0.011684473733853906
                    finance: -0.14755302887323793

                Document 'finance' falls into the following categories:
                    health: -0.17290237675941766
                    science: -0.09579267574606627
                    finance: 0.4460859189453788

                    so,now we know categories for yet unseen documents
         */
    }

    void makeParagraphVectors()  throws Exception {
      ClassPathResource resource = new ClassPathResource("paravec/bygame/labeled");

      // build a iterator for our dataset
      iterator = new FileLabelAwareIterator.Builder()
              .addSourceFolder(resource.getFile())
              .build();

      tokenizerFactory = new DefaultTokenizerFactory();
      tokenizerFactory.setTokenPreProcessor(new CommonPreprocessor());
      // ParagraphVectors training configuration
      paragraphVectors = new ParagraphVectors.Builder()
              .learningRate(0.035)
              .minLearningRate(0.005)
              .batchSize(1000)
              .epochs(20)
              .iterate(iterator)
              .trainWordVectors(true)
              .tokenizerFactory(tokenizerFactory)
              .sampling(0.05)
              .build();

      // Start model training
      paragraphVectors.fit();
    }

    void checkUnlabeledData() throws FileNotFoundException {
        HashMap<String, Integer> dic= new HashMap<>();
        ArrayList<Result> results= new ArrayList<>();
        int groups=0;

      /*
      At this point we assume that we have model built and we can check
      which categories our unlabeled document falls into.
      So we'll start loading our unlabeled documents and checking them
     */
     ClassPathResource unClassifiedResource = new ClassPathResource("paravec/bygame/unlabeled");
     FileLabelAwareIterator unClassifiedIterator = new FileLabelAwareIterator.Builder()
             .addSourceFolder(unClassifiedResource.getFile())
             .build();

     /*
      Now we'll iterate over unlabeled data, and check which label it could be assigned to
      Please note: for many domains it's normal to have 1 document fall into few labels at once,
      with different "weight" for each.
     */
     MeansBuilder meansBuilder = new MeansBuilder(
         (InMemoryLookupTable<VocabWord>)paragraphVectors.getLookupTable(),
           tokenizerFactory);
     LabelSeeker seeker = new LabelSeeker(iterator.getLabelsSource().getLabels(),
         (InMemoryLookupTable<VocabWord>) paragraphVectors.getLookupTable());
        Writer writer = null;
        try {
            writer = new BufferedWriter(new OutputStreamWriter(
                new FileOutputStream("log_rec_games2.txt"), "utf-8"));
        }
        catch(Exception e){
            log.error("FAILED OPENING FILE");
        }
        int i=0;
     while (unClassifiedIterator.hasNextDocument()) {

         LabelledDocument document = unClassifiedIterator.nextDocument();
         INDArray documentAsCentroid = meansBuilder.documentAsVector(document);
         List<Pair<String, Double>> scores = seeker.getScores(documentAsCentroid);

         /*
          please note, document.getLabel() is used just to show which document we're looking at now,
          as a substitute for printing out the whole document name.
          So, labels on these two documents are used like titles,
          just to visualize our classification done properly
         */
         log.info("written" + i);
         i++;

         String lable=document.getLabel();
         int index;
         /*Build the result array*/
         if(dic.isEmpty()){
             /*if this is the first entry of the dictionary*/
             dic.put(lable,groups);
             index=groups;
             groups++;
             results.add(new Result(lable));
         }else{
             if(dic.containsKey(lable)){
                 index=dic.get(lable);
             }else{
                 dic.put(lable,groups);
                 index=groups;
                 groups++;
                 results.add(new Result(lable));
             }
         }
         Result actualResult=results.get(index);
         try {

             writer.write("Document '" + lable + "' falls into the following categories: \n" );
             writer.write("With text:" +document.toString() +"\n");
             Double max = -1.1;
             String correct="null";
             for (Pair<String, Double> score: scores) {
                 writer.write("        " + score.getFirst() + ": " + score.getSecond()+"\n\n");
                 actualResult.addResult(score.getFirst(),score.getSecond());
                 if(max<score.getSecond()){
                     max=score.getSecond();
                     correct=score.getFirst();
                 }
             }
             actualResult.addCorrect(correct);

         } catch (IOException ex) {
             log.error("COULD NOT WRITE");
         }

     }
        for(Result r: results){
            try {
                writer.write(r.getResults());
            } catch (IOException ex) {
                log.error("COULD NOT WRITE");
            }
        }
        try {
            writer.close();
        } catch (Exception ex) {/*ignore*/
        }

    }
}
`

Here is the output of my program:

`
The group A has the next accuracies for each other class:
B average cos distance: -0.08151683720294386
B has an accuracy of  : 0/400
A average cos distance: 5.093872889119667E-4
A has an accuracy of  : 0/400
C average cos distance: 0.7569797006249428
C has an accuracy of  : 400/400
D average cos distance: 0.19814932759851217
D has an accuracy of  : 0/400
E average cos distance: 0.5440101922303439
E has an accuracy of  : 0/400
F average cos distance: 0.025434730636952736
F has an accuracy of  : 0/400

The group B has the next accuracies for each other class:
B average cos distance: -0.037045918115909446
B has an accuracy of  : 0/400
A  average cos distance: -0.045483740557806414
A  has an accuracy of  : 0/400
C average cos distance: 0.7549091298040003
C has an accuracy of  : 399/400
D average cos distance: 0.19445993211120366
D has an accuracy of  : 0/400
E average cos distance: 0.5314711512625218
E has an accuracy of  : 0/400
F average cos distance: 0.006557742160221096
F has an accuracy of  : 1/400

The group F has the next accuracies for each other class:
B average cos distance: -0.04110614491859451
B has an accuracy of  : 0/400
A  average cos distance: -0.04103634840539598
A  has an accuracy of  : 0/400
C average cos distance: 0.7270043413882377
C has an accuracy of  : 393/400
D average cos distance: 0.19797361596487462
D has an accuracy of  : 0/400
E average cos distance: 0.4780905103310943
E has an accuracy of  : 0/400
F average cos distance: 0.08513673244291567
F has an accuracy of  : 7/400

The group D has the next accuracies for each other class:
B average cos distance: -0.06557882378227077
B has an accuracy of  : 0/400
A  average cos distance: -0.05980065737850964
A  has an accuracy of  : 0/400
C average cos distance: 0.737154654674232
C has an accuracy of  : 398/400
D average cos distance: 0.2816178100928664
D has an accuracy of  : 0/400
E average cos distance: 0.5319411465525627
E has an accuracy of  : 1/400
F average cos distance: -0.008207999747210124
F has an accuracy of  : 1/400

The group C has the next accuracies for each other class:
B average cos distance: -0.07964973058493342
B has an accuracy of  : 0/400
A  average cos distance: -0.025440956405800533
A  has an accuracy of  : 0/400
C average cos distance: 0.774757861699909
C has an accuracy of  : 399/400
D average cos distance: 0.17464863223023713
D has an accuracy of  : 0/400
E average cos distance: 0.49410620303824543
E has an accuracy of  : 0/400
F average cos distance: 0.033661291514326876
F has an accuracy of  : 1/400

The group E has the next accuracies for each other class:
B average cos distance: -0.093063611688558
B has an accuracy of  : 0/400
A  average cos distance: -0.05646174754147069
A  has an accuracy of  : 0/400
C average cos distance: 0.7035126116871834
C has an accuracy of  : 350/400
D average cos distance: 0.23969208743423223
D has an accuracy of  : 0/400
E average cos distance: 0.6192192045599222
E has an accuracy of  : 50/400
F average cos distance: -0.034791482893406285
F has an accuracy of  : 0/400
`

As you can see, group C is the dominant one, and they are very different topics. I dont know what to do to change the output so that it starts making more sense. I can only suppose that i am doing something wrong since the output is so very weird. Thanks for your time

**Comment by raver119** [comment]
Can i see your text corpus?

**Comment by DYelamos** [comment]
you mean all of it? the whole 7000 reviews?

**Comment by raver119** [comment]
How big archive would that be?

**Comment by DYelamos** [comment]
(1000 text training files * 7 folders) +(400 text testing files *7 folders)= 7000+2100 = 9100 text files of about 23 MB

**Comment by raver119** [comment]
Yes, i want full archive then :)

**Comment by DYelamos** [comment]
This data is the result of a 6 month project, I am a bit reluctant as in publicly giving it away.

**Comment by raver119** [comment]
You have 2 options:
1) Send it to me using email
2) Do not share it at all.

I can't force you, but without seeing actual corpus, i can't tell if something is wrong or not, neither i can help with params tuning.

**Comment by DYelamos** [comment]
Let me ask my tutor. I will get back to you in a few hours.

**Comment by raver119** [comment]
Sure

**Comment by DYelamos** [comment]
Okay i will email them to you. It is a part of my bachellor's Thesis so I would appreciate a minimum ammount of distribution. Thanks beforehand.

**Comment by raver119** [comment]
Don't worry, it won't leave my desktop.

And thanks, I'll take a look there soon.
7 июня 2016 г. 20:00 пользователь "DYelamos" <notifications@github.com>
написал:

**Comment by DYelamos** [comment]
Any luck?

**Comment by raver119** [comment]
I've checked your corpus. Poke me in gitter when you'll be online, please.

**Comment by raver119** [comment]
Issue was investigated: actually single-domain corpus, with neglectible differences between labels, etc.

Closing this issue now.
