### ISSUE TITLE
Tutorials not updated

### ISSUE THREAD

**Issue by Mortomes** [deeplearning4j/deeplearning4j#1661]
At least one of the tutorials (and javadoc) has not been updated. The restricted boltzmann machine tutorial (http://deeplearning4j.org/restrictedboltzmannmachine.html) uses the following line of code.

Layer model = LayerFactories.getFactory(conf.getLayer()).create(conf);  

There is however no create method that takes only one parameter, even though this is still listed in the javadoc.

**Comment by DeerMichel** [comment]
How to do it that it works?
