### ISSUE TITLE
ParagraphVectors inferVector does not return vectors

### ISSUE THREAD

**Issue by XilunChen** [deeplearning4j/deeplearning4j#1662]
I'm trying to infer the vector for a new document using a trained paragraph vector model, but the infer method does not give me the vector, I checked in function     
public INDArray inferVector(List<VocabWord> document, double learningRate, double minLearningRate, int iterations) 
returns null;

and the new document label is randomly generated, and not included in the vocabulary

How can I get the vector for a new document using inferVector method?

Thanks

**Comment by raver119** [comment]
I'm sorry, but inferVector meant to be protected for now. Implementation wasn't finished yet, and will be available in next release.

**Comment by XilunChen** [comment]
Hi Raver119,

Thanks for the quick reply, looking forward to the next release!

**Comment by alexfloyd** [comment]
Same here, thanks raver!

**Comment by andresgs77** [comment]
To infer a vector for a new document given a trained model is a key functionality that will boost the api usage.   

@raver119 do you have an approximate date for the next release?

**Comment by raver119** [comment]
Sorry, right now main priority is CUDA performance & multi-gpu scaling. After it's finished - i'll get back to NLP.

**Comment by raver119** [comment]
Implemented. Example is here: https://github.com/deeplearning4j/dl4j-examples/pull/234

Will be merged soon&trade; and will be available with 0.6.0 release next week.
