### ISSUE TITLE
Add a simple preprocessor for images ([0,255] -> [0,1])

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1665]
We should have something like this built in. Maybe a *slightly* more sophisticated version, with specified range of *a* to *b* instead of just 0 to 1, so users can do things like -0.5 to 0.5, or -1 to 1 if they want.

https://gist.github.com/AlexDBlack/1b85903103e8db12e076224e4f519e6e

**Comment by saudet** [comment]
Image values are not always from 0 to 255 though, some images are 16-bit, some 32-bit, integer, or float, and those BTW already come with values in [0..1]...

**Comment by eraly** [comment]
I am thinking nd4j.

**Comment by eraly** [comment]
I added the third argument so the user can specify how many bits are used in the representation of the pixel vals. A value of 1 is to be given if the values are already in [0,..1] and need to be scaled to something else.

https://github.com/deeplearning4j/nd4j/pull/1045

**Comment by eraly** [comment]
Added tests. Everything passing. Closing.
