### ISSUE TITLE
Question: How to initialize EmbeddingLayer with pre-trained word vectors?

### ISSUE THREAD

**Issue by rasoolims** [deeplearning4j/deeplearning4j#1667]
I want to initialize the EmbeddingLayer with pre-trained word vectors. How can I do this?

```java
 EmbeddingLayer wordLayer = new EmbeddingLayer.Builder().nIn(vocabSize).nOut(wordVectorDimension).activation("identity").build();
```

**Comment by AlexDBlack** [comment]
Have a look at how the weights are handled in the code: https://github.com/deeplearning4j/deeplearning4j/blob/3062057d09803ae6db58e8f19c7bf07f82dc7db3/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/feedforward/embedding/EmbeddingLayer.java#L80

There's no one-step process for doing this (yet).
The approach you'll have to use: initialize your network. Load your word vectors. Get the embedding layer from the MultiLayerNetwork, and get the weights using getParam(WEIGHT_KEY).
This should be a vocabSize x wordVector size; each row is a word vector (the index of the row corresponds to the index of the word). Then transfer your word vectors to that weight array.

Does that make sense?

**Comment by rasoolims** [comment]
What if I use a ComputationGraph? It seems that GetParams is not implemented.

https://github.com/deeplearning4j/deeplearning4j/blob/7d247ddf37875f01ba7ec6c3be6d3497360beb4d/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/graph/ComputationGraph.java#L1358

**Comment by rasoolims** [comment]
This is how I did this and it seems to be working correctly:

```java
  org.deeplearning4j.nn.layers.feedforward.embedding.EmbeddingLayer layer =
                    (org.deeplearning4j.nn.layers.feedforward.embedding.EmbeddingLayer)
                     net.getLayer(0);
INDArray weights = layer.getParam(DefaultParamInitializer.WEIGHT_KEY);
INDArray rows = Nd4j.createUninitialized(new int[]{vocabSize, weights.size(1)}, 'c');
for (int i = 0; i < vocabSize; i++) {
    double[] embeddings = getEmbeddings(i); // getEmbeddings is my own function
    if (embeddings != null) {
         INDArray newArray = Nd4j.create(embeddings);
         rows.putRow(i, newArray);
     } else { // if there is no pre-trained embedding value for that specific entry
          rows.putRow(i, weights.getRow(i));
     }
}
// finally put rows in place of weights
layer.setParam("W", rows);
```

**Comment by AlexDBlack** [comment]
Right, you want getParam on the layer. What you've done is essentially what I was suggesting.

**Comment by shengc** [comment]
Apologize to comment on a closed issue, but I think my question is best asked here. If I have to use a trained word vector to initialize weights of a embedding layer, obviously I dont want back propagation to update the weights during training. How should I make it happen ? Or is it already the way how embedding layer is working ?
