### ISSUE TITLE
Anomaly Detection with DL4J?

### ISSUE THREAD

**Issue by nouramoubayed** [deeplearning4j/deeplearning4j#167]
Hi everyone, 

I want to use DL4J for Anomaly detection, my dataset is a combination of behaviour data with GPS trackers, data from twitter....). 
I know I have to use RBM to learn the features or only use the pre-train step of the DBN. 

I was looking for some example/advices about the following issues:

-how do I declare and feed a new data ? what types of data can i use? 
-how do I retrieve the reconstruction error? 

many thanks,

**Comment by agibsonccc** [comment]
I'm closing this since you appear to have found a method that suits you.

**Comment by archenroot** [comment]
@nouramoubayed 
Have you finished your implementation?

If yes, could you provide any kind of sample implementation?
