### ISSUE TITLE
Where to find support? The gitter link is "404".

### ISSUE THREAD

**Issue by Sraw** [deeplearning4j/deeplearning4j#1670]
I have some problems about bp neural network. But it seems nowhere to find any support.
The link on README.md is outdated and just returned "404 not found".

**Comment by raver119** [comment]
We have gitter chat, that has somebody from team like 24/7. Here's the proper link: https://gitter.im/deeplearning4j/deeplearning4j

And thanks for flagging broken link.

**Comment by chrisvnicholson** [comment]
fixed
