### ISSUE TITLE
Document: how to get optimal (computational) performance out of DL4J/ND4J

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1675]
Things like:
- Minibatch size
- Order/strides for input data (esp. RNNs)
- Whether SGD or line search optimizers should be used
- Choice of activation functions
- Iterations vs. epochs

Also: Spark. Performance tradeoffs here vs. different configurations are non-obvious.

**Comment by huitseeker** [comment]
see also #2192

**Comment by huitseeker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DataVec & al. - improve open-source documentation related to workflow](https://trello.com/c/3u3jt2lF/5-datavec-al-improve-open-source-documentation-related-to-workflow)

**Comment by agibsonccc** [comment]
http://deeplearning4j.org/native
http://deeplearning4j.org/benchmarking
http://deeplearning4j.org/distributed
