### ISSUE TITLE
ModelSerializer: updater saving is not independent of backend

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1676]
Consider model updater saving here:
https://github.com/deeplearning4j/deeplearning4j/blob/ddeccd003bfd80d39188b071190cbbc411530c8a/deeplearning4j-core/src/main/java/org/deeplearning4j/util/ModelSerializer.java#L99

It seems to use standard java serialization for the updaters, which works fine, until you train on one backend and try to load the model (with an updater) on another.
Note that there is currently no way of serializing updaters that actually *is* platform independent. We will need to fix that first.

**Comment by eraly** [comment]
https://github.com/deeplearning4j/nd4j/pull/1059

This fix will allow us to stream ndarrays and read them in across backends.

**Comment by eraly** [comment]
So this is now done
https://github.com/deeplearning4j/nd4j/pull/1092
