### ISSUE TITLE
FileLabelAwareIterator java.io.FileNotFoundException: (Too many open files in system)

### ISSUE THREAD

**Issue by ehallmark** [deeplearning4j/deeplearning4j#1686]
I'm getting a FileNotFoundException when using the org.deeplearning4j.text.documentiterator.FileLabelAwareIterator

The issue seems to be that the BufferedReaders are never closed, and Unix systems place a limit on the number of open files that a single process can have. I closed each BufferReader after setting up each LabeledDocument to fix the issue.

More about this type of issue: http://stackoverflow.com/questions/4289447/java-too-many-open-files

**Comment by ehallmark** [comment]
Similar issue (and similar fix) for the FilenamesLabelAwareIterator...

**Comment by raver119** [comment]
Thanks for highlighting this, fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/1656

However, it'll be merged a bit later

**Comment by ehallmark** [comment]
Thanks!
