### ISSUE TITLE
LocalFileModelSaver should use ModelSerializer

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#1694]
Currently the LocalFileModelSaver manually saves the model into files, and while `.getBestModel` can be used to get it right after writing, it isn't as simple with a cold start.

Instead it should use the ModelSerializer that was introduced in rc3.9.

**Comment by raver119** [comment]
Implemented here: https://github.com/deeplearning4j/deeplearning4j/pull/1656

Will be merged a bit later.
