### ISSUE TITLE
Unable to  run WordVectorSerializer.writeFullModel()/loadFullModel() after upgrading to 0.4-rc3.10

### ISSUE THREAD

**Issue by locuslin** [deeplearning4j/deeplearning4j#1703]
I failed to load the WordVector when using WordVectorSerializer.writeFullModel() and loadFullModel(),which ran well on 0.4-rc3.9.
the error message is as follows
`Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class org.deeplearning4j.models.embeddings.loader.VectorsConfiguration] from Floating-point number (0.0024726231566347748); no one-double/Double-arg constructor/factory method
 at [Source: java.io.StringReader@ce5a68e; line: 1, column: 1]
	at org.deeplearning4j.models.embeddings.loader.VectorsConfiguration.fromJson(VectorsConfiguration.java:96)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadFullModel(WordVectorSerializer.java:787)
	at org.deeplearning4j.examples.nlp.word2vec.Word2VecUptrainingExample.main(Word2VecUptrainingExample.java:86)`

For convenience, this runs on dl4j-examples.

I compared the code of writeFullModel()  in 0.4-rc3.10 to that in  0.4-rc3.9,and found that the code `printWriter.println(conf.toJson())` in line 685 and `printWriter.println(vw.toJson())` in line 761 has been commented ,which is not in 0.4-rc3.9.Is that the reason why I failed to run the example?
Please check this.
Thank you.

**Comment by raver119** [comment]
Yes, this is a bug. It's already fixed on current master. As workaround you can copy those methods (or entire class) to your project and use them instead.

Sorry for inconveniences.
