### ISSUE TITLE
Document ConvolutionalIterationListener: how to use + screenshots

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1706]
Afaik we don't have any documentation on this.

Here's a test of it being used for LFW:
https://github.com/deeplearning4j/deeplearning4j/blob/859bdd0f302444ac04c33179afc8af500e959b89/deeplearning4j-ui-parent/deeplearning4j-ui/src/main/java/org/deeplearning4j/ui/weights/ConvolutionalIterationListener.java

**Comment by raver119** [comment]
Yes, and as far as i remember i was urged to switch to cuda while messing with this iterator, so i'll better check it's state first, and then provide documentation draft

**Comment by agibsonccc** [comment]
Closing due to deprecation.
