### ISSUE TITLE
learningRateSchedule and setMomentumSchedule do not change learning rate and momentum over time!

### ISSUE THREAD

**Issue by rasoolims** [deeplearning4j/deeplearning4j#1707]
```java
Map<Integer, Double> momentumSchedule = new HashedMap();
        double m = 0.001;
        for(int i=1;i<100000;i++){
            momentumSchedule.put(i,Math.min(m,0.9999));
            m+=0.001;
 }

Map<Integer, Double> learningRateSchedule = new HashedMap();
        double lr = 0.1;
        for(int i=1;i<100000;i++){
            learningRateSchedule.put(i,lr);
            lr*=0.96;
}

NeuralNetConfiguration.Builder confBuilder =  new NeuralNetConfiguration.Builder()
      .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
      .learningRateDecayPolicy(LearningRatePolicy.Schedule)
      .learningRateSchedule(learningRateSchedule)
       .regularization(true).l2(0.0001);
confBuilder.setMomentumSchedule(momentumSchedule);

/**
**  constructed deep net based on @confBuilder here (removed for readability)
**/


for (int i=0;i<epoch,i++){
 while (trainIter.hasNext()) {
     net.fit(trainIter.next());

  // always print the same number (0.1 and 0.9) 
  System.out.println("learning rate:"+(net.getLayer(last_layer_index)).conf().getLearningRateByParam("W"));
    System.out.println("momentum:"+(net.getLayer(last_layer_index)).conf().getLayer().getMomentum());
    }
trainIter.reset()
}
```

**Comment by AlexDBlack** [comment]
Confirmed as an issue. Problem here is that the iteration count in BaseOptimizer is not being updated currently. Thus iteration count is always being passed as 0, to the schedules.
https://github.com/deeplearning4j/deeplearning4j/blob/b5473e0904485dc64c552ea94f24af0080c14a68/deeplearning4j-core/src/main/java/org/deeplearning4j/optimize/solvers/BaseOptimizer.java#L288
https://github.com/deeplearning4j/deeplearning4j/blob/b5473e0904485dc64c552ea94f24af0080c14a68/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/updater/BaseUpdater.java#L88


Fixing the iteration count is easy. However, we also want the iteration count to be persisted along with the network, such that if the network is saved + reloaded, the schedule is continued (not reset).

**Comment by AlexDBlack** [comment]
Thanks for flagging. That's now fixed + added an additional test based on your code.
I'll fix the iteration count persistance thing I mentioned separately.

**Comment by rasoolims** [comment]
How should I use the latest version in POM file?

**Comment by rasoolims** [comment]
For the meanwhile, this is how I fixed the problem for my code (working with the stable release):

```java
 for(int i=0;i<num_of_layers;i++){
       double lr =  (net.getLayer(i)).conf().getLearningRateByParam("W");
      (net.getLayer(i)).conf().setLearningRateByParam("W",lr*0.96);
       lr =  (net.getLayer(i)).conf().getLearningRateByParam("b");
       (net.getLayer(i)).conf().setLearningRateByParam("b",lr*0.96);
}
```

My manual checks show it works (and also improves convergence speed)

**Comment by AlexDBlack** [comment]
I think this was already mentioned in gitter, but you'll have to build everything from source (which is non-trivial to do - need c++ build tools, etc).
If you do want to give that a shot, jump in here and we'll see what we can do. https://gitter.im/deeplearning4j/deeplearning4j/earlyadopters

Also fwiw it shouldn't be more than a couple of weeks before the next release (rough estimate). So if your workaround does everything you need, it might be easier to just wait.
