### ISSUE TITLE
Docs: Add an "Introduction to DL4J" or "Programming Guide" type page

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1716]
This sort of page would (usually) be the first places users go, after the quickstart guide and examples.

It would concisely explain the core concepts - stuff people need to know and/or know about, such as:
- What is ND4J, Canova, etc
- What an INDArray, DataSet, DataSetIterator etc is
- Types of layers available in DL4J
- What options are available for data normalization
- Mention that the UI exists
  etc

Something like the Spark programming guide seems like a good example of this sort of document:
http://spark.apache.org/docs/latest/programming-guide.html

**Comment by treo** [comment]
I've whipped up a first draft, a lot of stuff is still missing, but it is a start and that's always better then staring at a white page :)

So please feel free to add, change, delete and correct stuff that I've got wrong.

**Comment by ncleaver** [comment]
Thanks for all the work - I made some minor changes to language here and there to the current content.

**Comment by treo** [comment]
I just updated some of the links to point to the javadoc instead of github. As far as I'm concerned, I think most of the the points @AlexDBlack mentions should be covered. So @ncleaver feel free to clean up the language some more :)

**Comment by treo** [comment]
Any feedback? @ncleaver, @chrisvnicholson, @AlexDBlack, @agibsonccc?

**Comment by tomthetrainer** [comment]
I like this, if nobody has linked it into the navigation panel I will go ahead and do that
