### ISSUE TITLE
No serialization functionality for spark word2vec in WordVecSerializer

### ISSUE THREAD

**Issue by davireis** [deeplearning4j/deeplearning4j#1718]
One cannot serialize a org.deeplearning4j.spark.models.embeddings.word2vec.Word2Vec instance, because http://deeplearning4j.org/doc/org/deeplearning4j/models/embeddings/loader/WordVectorSerializer.html does not have an overload. It does have overloads for other subclasses of WordVectors, but not for the spark one.

There is an almost work-around: convert your spark model in a regular one by calling:

```
val localModel = new Word2Vec()
localModel.setLookupTable(sparkWord2Vec.getLookupTable)
localModel.setVocab(sparkWord2Vec.getVocab)
```

That model cannot be serialized with writeFullModel since it lacks side effects of the training it did not go through, which will result in null pointer being thrown due to lack of syn1 and expTable. But it is still possible to do:

```
WordVectorSerializer.writeWordVectors(localModel, "path")
```

And that model can almost be loaded with:

```
WordVectorSerializer.loadTxtVectors(new File("path"))
```

Except for the fact that https://github.com/deeplearning4j/deeplearning4j/commit/98bd41423ecd40c830aeba5449acc3c2f39892a9 did not get into the rc3.10 release. So, this workaround only works in head as of now.

It would be much nicer to have dedicated serialization functionality for spark.

**Comment by raver119** [comment]
writeFull model fix and loadTxtVectors fix was applied after 3.10 release, so it will be available soon, with next release. As workaround solution you can just copy-paste these methods into your project, and use them instead.

Re: spark w2v serialization. Spark doesn't need it. There's available universal method right for that: https://github.com/deeplearning4j/deeplearning4j/blob/98bd41423ecd40c830aeba5449acc3c2f39892a9/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/loader/WordVectorSerializer.java#L360-L360

It takes lookup table only, and saves it to file/outputstream (even hdfs output stream will work there), so this method is viable for any environment.
