### ISSUE TITLE
Docs: document spark training functionality

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1723]
Docs should discuss (and where appropriate, provide examples of configuration for):
- What SparkDl4jMultiLayer and SparkComputationGraph are (and how they work)
- What a TrainingMaster is and does
- For each TrainingMaster implementation, explain:
  - What the parameters are
  - Best practices for setting/tuning these parameters
- How to use the SparkTrainingStats functionality (enabling, interpreting, using them to improve performance)

**Comment by agibsonccc** [comment]
http://deeplearning4j.org/spark
