### ISSUE TITLE
DL4J unable to use multiple GPUs

### ISSUE THREAD

**Issue by fac2003** [deeplearning4j/deeplearning4j#1725]
We are benchmarking DL4J on a linux box with 8 K80 GPUs. When running the spark Graves example, only one GPU sees utilization, ranging from 5-63% usage. 
We enabled the multi-GPU setting with  CudaEnvironment.getInstance().getConfiguration().allowMultiGPU(true);
Here's a trace: https://gist.github.com/fac2003/44d17565a7f95691c8097d964a440beb

We built from source using ND4J commit:
commit d74bb5dee7741fc8e8b32f771a4cc47ac2625fa5
Author: Samuel Audet <samuel.audet@gmail.com>
Date:   Mon Jun 6 10:11:10 2016 +0900

**Comment by raver119** [comment]
Please, build from current libnd4j and nd4j master.

Also, use following configuration:

CudaEnvironment.getInstance().getConfiguration().allowMultiGPU(true).setMemoryModel(MemoryModel.DELAYED);

**Comment by fac2003** [comment]
We just built from the latest masters, added  CudaEnvironment.getInstance().getConfiguration().allowMultiGPU(true).setMemoryModel(MemoryModel.DELAYED); and got this:
```

o.n.n.NativeOps - Number of threads used for linear algebra 32
Using existing text file at /tmp/Shakespeare.txt
o.n.j.a.c.i.BasicContextPool - Creating new context...
o.n.j.a.c.i.BasicContextPool - Creating new stream for device [0]...
o.n.j.a.c.i.BasicContextPool - Creating new cuBLAS handle for device [0]...
o.n.j.a.c.i.BasicContextPool - Creating new stream for device [0]...
o.n.j.h.i.CudaZeroHandler - Creating bucketID: 5
o.n.j.h.i.CudaZeroHandler - Creating bucketID: 4
o.n.j.h.i.CudaZeroHandler - Creating bucketID: 2
o.n.j.h.i.CudaZeroHandler - Creating bucketID: 3
o.n.j.h.i.CudaZeroHandler - Creating bucketID: 1
o.n.j.h.i.CudaZeroHandler - Creating bucketID: 0
o.d.o.s.BaseOptimizer - Objective function automatically set to minimize. Set stepFunction in neural net configuration to change default settings.
o.d.s.i.m.SparkDl4jMultiLayer - Running distributed training:  (averaging each iteration = true), (iterations = 1), (num partions = 16)
o.n.j.a.c.i.BasicContextPool - Creating new context...
o.n.j.a.c.i.BasicContextPool - Creating new stream for device [0]...
o.n.j.a.c.i.BasicContextPool - Reusing blas here...
o.n.j.a.c.i.BasicContextPool - Creating new context...
o.n.j.a.c.i.BasicContextPool - Creating new stream for device [0]...
o.n.j.a.c.i.BasicContextPool - Reusing blas here...
o.d.s.i.m.SparkDl4jMultiLayer - Broadcasting initial parameters of length 559877
o.n.j.a.c.i.BasicContextPool - Creating new context...
o.n.j.a.c.i.BasicContextPool - Creating new stream for device [0]...
o.n.j.a.c.i.BasicContextPool - Reusing blas here...
o.n.j.a.c.i.BasicContextPool - Creating new context...
Exception in thread "UniGC thread 3" o.n.j.a.c.i.BasicContextPool - Creating new stream for device [0]...
java.lang.IllegalStateException: Can't happen ever
	at org.nd4j.jita.handler.impl.CudaZeroHandler.purgeDeviceObject(CudaZeroHandler.java:912)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.purgeDeviceObject(AtomicAllocator.java:418)
	at org.nd4j.jita.allocator.impl.AtomicAllocator$UnifiedGarbageCollectorThread.run(AtomicAllocator.java:591)
```

**Comment by raver119** [comment]
Confirming this one.

**Comment by raver119** [comment]
Please build things from sources from my branches in libnd4j, nd4j, and dl4j. Branch name is the same everywhere: r119_various.

Things are fixed/improved there.

**Comment by raver119** [comment]
Are you running tests on multi-gpu system?

**Comment by fac2003** [comment]
Yes. Now trying to skip the test and check DL4J.

**Comment by raver119** [comment]
Tbh, i hadn't run those test with multiple gpus. On single gpu i have only 1 test failing, but that failure doesn't matter right now.

**Comment by fac2003** [comment]
I was able to build libnd4j and nd4j, but dl4j in your branch requires:

The following artifacts could not be resolved: org.nd4j:canova-nd4j-common:jar:0.0.0.17-SNAPSHOT, org.nd4j:canova-api:jar:0.0.0.17-SNAPSHOT, org.nd4j:canova-nd4j-image:jar:0.0.0.17-SNAPSHOT: Could not find artifact org.nd4j:canova-nd4j-common:jar:0.0.0.17-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]

You don't distribute these snapshots so I can't build this project for your branch.

Downgrading to the latest stable release 0.0.0.16 does not compile because of some constructors missing in canova:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project deeplearning4j-core: Compilation failure: Compilation failure:
[ERROR] /home/mas2182/DL4J/sources/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/datasets/iterator/impl/CifarDataSetIterator.java:[78,23] no suitable constructor found for CifarLoader(int,int,int,org.canova.image.transform.ImageTransform,int,boolean)

**Comment by raver119** [comment]
there's Canova repo: https://github.com/deeplearning4j/Canova

**Comment by fac2003** [comment]
I managed to compile DL4J, but the new master breaks compatibility with the code we used for benchmarking. For instance, we use AsyncIterator for performance, but its signature or inheritance graph has changed. Will have to look into it more or try other examples, if we can compile them.

incompatible types: org.deeplearning4j.datasets.iterator.AsyncDataSetIterator cannot be converted to org.deeplearning4j.datasets.iterator.DataSetIterator


Similar compilation errors are found with dl4j examples:

[ERROR] dl4j-0.4-examples/src/main/java/org/deeplearning4j/examples/unsupervised/deepbelief/DBNMnistFullExample.java:[44,32] incompatible types: org.deeplearning4j.datasets.iterator.impl.MnistDataSetIterator cannot be converted to org.deeplearning4j.datasets.iterator.DataSetIterator

**Comment by raver119** [comment]
that's the change coming in next release, we had DataSetIterator interfaces defined in both Dl4j and Nd4j, and different methods/classes were using different interfaces. Now it'll be only one interface for everything.

**Comment by fac2003** [comment]
I'm sure it's fine. It just does not make it easy to just compile our benchmark with the new version to give you feedback.

**Comment by raver119** [comment]
Could you just change import for DataSetIterator impl? 

import org.nd4j.linalg.dataset.api.iterator.DataSetIterator;

**Comment by fac2003** [comment]
I would have to change the code on my desktop, where I did not compile from master. I'll have to pass. I have other obligations this week.

**Comment by raver119** [comment]
Ok, anyway thanks for your help. We'll test it internally at morning :)

**Comment by raver119** [comment]
Initial multi-gpu support implemented and will be available in next release.
