### ISSUE TITLE
Ensure build .sh scripts (for scala versions) terminate if first build fails

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1726]
Across most of the projects (nd4j, canova, dl4j, arbiter) we have scripts for building multiple scala versions.
The current versions of these all seem to continue with the second build step, even if the first one fails - due to the amount of console output, it's very easy to miss the result of the first build.

**Comment by saudet** [comment]
Inserting `set -eu` at the top of every script will do that for us.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/1727 (and various similar PRs in nd4j, canova, arbiter).

@saudet I didn't modify libnd4j (./buildnativeoperations.sh): -u causes issues with $2 and the like ("unbound variable" at line 17 with it when building cpu). Less of an issue there though.
