### ISSUE TITLE
possible data loss in loadTxt method WordVectorSerializer.java

### ISSUE THREAD

**Issue by joachimdb** [deeplearning4j/deeplearning4j#1728]
in method `loadTxt` in https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/loader/WordVectorSerializer.java, lines 1044 to 1142

In case that `hasHeader` is `false` the first line in the `vectorsFile` already contains a word+vector entry which is never processed due to the `iter.nextLine()` call at line 1053.

**Comment by raver119** [comment]
Hm, no, it shouldn't happen. 
If hasHeader == false, line contains valid vector string, and it's processed at line 1091
