### ISSUE TITLE
DL4J UI doesn't work when not connected to internet

### ISSUE THREAD

**Issue by jsteggink** [deeplearning4j/deeplearning4j#1729]
When there is no internet connection the DL4J UI components can't find the js and css library files, which are provided by the corresponding CDNs. Best would be to add the libraries instead of relying on the external CDNs.

**Comment by agibsonccc** [comment]
@raver119 I think we bundle things now?

**Comment by raver119** [comment]
Yep, in 0.6.0 it was all bundled.

However, don't know how new UI work, and what resources are used.

**Comment by AlexDBlack** [comment]
No longer relevant.
