### ISSUE TITLE
why isn't there dbn package or DBN class in models.classifier of 0.0.3.3 version

### ISSUE THREAD

**Issue by nilday** [deeplearning4j/deeplearning4j#173]
I notice that there isn't anything about dbn in version 0.0.3.3?Thus deeplearning4j-examples won't work as introduced in quick-start because it's based on dbn.
There is dbn package in version 0.0.3.2.7 but since 0.0.3.0 it disappears.Why?Is there something I can use instead?

**Comment by agibsonccc** [comment]
In the new version, we focus on using a MultiLayerNetwork with the layers specified as an RBM for a DBN. Rather than the brittle architecture dl4j had before, everything is composed of layers. A Layer can be used in a multi layer network.
