### ISSUE TITLE
buildnativeoperations.sh fails for new/clean installs of dl4j

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1730]
Completely fresh installs of dl4j seem to fail currently due to the build order of dependencies:

[ERROR] Failed to execute goal on project deeplearning4j-cli-spark: Could not resolve dependencies for project org.deeplearning4j:deeplearning4j-cli-spark:jar:0.4-rc3.11-SNAPSHOT: Could not find artifact org.deeplearning4j:dl4j-spark_2.11:jar:0.4-rc3.11-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]

It seems that somehow deeplearning4j-cli-spark somehow depends on deeplearning4j-spark_2.11, which fails when building the scala 2.10 versions the first time around.

It seems possibly to simply switch the order (build 2.11 before 2.10) but this may be indicative of other issues.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/1731 Mind checking if this fixed it?

**Comment by AlexDBlack** [comment]
Tested locally, and fresh build seems to be working now.
