### ISSUE TITLE
Failure to find org.nd4j:nd4j-cuda-7.5:jar:0.4-rc3.11-SNAPSHOT

### ISSUE THREAD

**Issue by breandan** [deeplearning4j/deeplearning4j#1732]
> [ERROR] Failed to execute goal on project deeplearning4j-cuda-7.5: Could not resolve dependencies for project org.deeplearning4j:deeplearning4j-cuda-7.5:jar:0.4-rc3.11-SNAPSHOT: Failure to find org.nd4j:nd4j-cuda-7.5:jar:0.4-rc3.11-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]

Received the following error when building dl4j. It appears the artifact is not yet hosted on Sonatype Nexus?

**Comment by raver119** [comment]
It's not a bug. If you want to build things from sources - you also need to build libnd4j and nd4j from sources.

Here's guide how to do this on Windows: https://github.com/deeplearning4j/libnd4j/blob/master/windows.md

On linux it's way more simple: https://github.com/deeplearning4j/libnd4j/blob/master/README.md
