### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space when reading in data

### ISSUE THREAD

**Issue by mrdeanplumbley** [deeplearning4j/deeplearning4j#174]
Using 0.0.3.3.3.alpha1-SNAPSHOT

When I read in a CSV dataset using either the fetcher or iterator I get a Java heap space error when there are > 5000 samples

       DataSetIterator iter = new MultipleEpochsIterator(3,new CSVDataSetIterator(10,500,trainInputs,vectorLength));

while (iter.hasNext()) {
    DataSet next = iter.next(); //ERROR ON THIS LINE
    next.normalizeZeroMeanZeroUnitVariance();
    d.fit(next);
    next.getFeatureMatrix().data().destroy();
    next.getLabels().data().destroy();
}

Changing the batch/input number in the iterator makes no difference

I get the same with the CSV fetcher 

This is code copy/pasted from previous builds so is unique to new version 

Thanks for the help

Dean

**Comment by agibsonccc** [comment]
Change the nd4j data type to float and let me know if that works. You can do that either -Ddtype=float, or Nd4j.dyype = DataBuffer.FLOAT in code.

**Comment by mrdeanplumbley** [comment]
Yes, well spotted!

Thanks
