### ISSUE TITLE
Error when attempting to visualize network using model.setListeners(new HistogramIterationListener(1))

### ISSUE THREAD

**Issue by JavaFXpert** [deeplearning4j/deeplearning4j#1742]
When attempting to visualize a network using the following method of MultiLayerNetwork:
setListeners(new HistogramIterationListener(1))

I receive the following error:
o.d.e.f.m.MLPMnistSingleLayerExample - Build model....
/Users/jamesweaver/dl4j-0.4-examples/target/classes/dropwizard.yml has an error:
Unrecognized field at: template
Did you mean?:
server
metrics
uploadPath
logging

Removing the template and defaultName lines from dropwizard.yml resulted in successfully launching the visualization.

**Comment by agibsonccc** [comment]
Not relevant now. New UI.
