### ISSUE TITLE
Reinforcement learning functionality for ComputationGraph.

### ISSUE THREAD

**Issue by FelixVoelker** [deeplearning4j/deeplearning4j#1745]
Would be great to train a ComputationGraph with reinforcement learning algorithms or at least to get the backpropGradient for the updater of the graph like it is possible for a MultiLayerNetwork.

**Comment by agibsonccc** [comment]
@rubenfiszel

**Comment by AlexDBlack** [comment]
This is something I'm hoping to look at this week for @rubenfiszel anyway. Might be easier for me to do it, given I wrote the rest of the ComputationGraph stuff.

**Comment by agibsonccc** [comment]
However it gets done  ;)

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/1837/files
