### ISSUE TITLE
WordVectorSerializer LoadGoogleModel() - format of weightMatrix for setSyn0 is false - transpose() necessary

### ISSUE THREAD

**Issue by c0der1337** [deeplearning4j/deeplearning4j#175]
Hello guys,

there is a big mistake in the WordVectorSerializer loadGoogleModel() method. The weightMatrix is in a false format and due to this the loaded word vectors make no sense. 

in line 101 is the error:  lookupTable.setSyn0(weightMatrix);
correct: lookupTable.setSyn0(weightMatrix.transpose());

With the current version the Syn0 in the lookupTabe is seen as 300 words (columns) with 300.000 vector size (rows). Due to this the results for simililarity and nearest neighboors are unexpected. The transpose() will correct this by transpose the weight matrix in the required format with 300.00 words (rows) and 300 (columns). I need a lot of time to found this error :-(

**Comment by agibsonccc** [comment]
What version is this?

**Comment by agibsonccc** [comment]
Ok, I added a fix for the ndarray. Let me know how it works. Thanks!

**Comment by zaemyung** [comment]
Hi,

I've just encountered the same problem of getting the results:
words nearest day: [snowcapped_Caucasus, pulverizes_boulders, Mezze_Cafe, Bim_Skala_Bim, RAFFAELE, righthander_Kyle_Drabek, Thirsty_Owl, divider_pistons, Shilpa_Goenka, Mauri_Liberati, USA_TODAY_Reid_Cherner]

words nearest museum: [snowcapped_Caucasus, pulverizes_boulders, Mezze_Cafe, Bim_Skala_Bim, RAFFAELE, righthander_Kyle_Drabek, Thirsty_Owl, divider_pistons, Shilpa_Goenka, Mauri_Liberati, USA_TODAY_Reid_Cherner]

words nearest woman: [snowcapped_Caucasus, pulverizes_boulders, Mezze_Cafe, Bim_Skala_Bim, RAFFAELE, righthander_Kyle_Drabek, Thirsty_Owl, divider_pistons, Shilpa_Goenka, Mauri_Liberati, USA_TODAY_Reid_Cherner]

I think I've cloned the lastest versions of nd4j and dl4j.
Any suggestions? Thanks!!

**Comment by brokenBrain** [comment]
I've encountered the same problem as well. Is there anyway I can fix this without accessing the source code for loadGoogleFile? I use maven, so I get the jars directly.

**Comment by agibsonccc** [comment]
HI,

Unfortunately you will have to compile from source for the fixed version.
We will be working on a new release here shortly. (We've spent the last few
months doing QA)
ᐧ
