### ISSUE TITLE
Defunct code in word2vec example

### ISSUE THREAD

**Issue by mattsheppard** [deeplearning4j/deeplearning4j#1753]
In http://deeplearning4j.org/word2vec#just under "Tokenizing the Data" there's an 'if' branch which prints a newline if a token ends in 'ly' or 'ing' - What's the reason for that? Some sort of not quite completed warning logging (if those endings were expected to be removed)? Or is there something I'm missing...

Checked in chat, and @raver119 suggested it was very likely just defunct code which should be removed.

**Comment by vladimir-nazarenko** [comment]
Seems to be closed.
