### ISSUE TITLE
Docs: clarify image loading in MNIST/RBM tutorial

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1766]
http://deeplearning4j.org/rbm-mnist-tutorial.html

This is misleading: "Typically, a DataSetIterator handles inputs and data-set-specific concerns like binarizing or normalization. For MNIST, the following does the trick:"

Normalization functionality isn't built into DataSetIterator per-se; it's a separate step that users have to do, _except for_ MNIST iterator which has it built in (MNIST being a special case for testing purposes, not any real-world use)

**Comment by tomthetrainer** [comment]
Fixed,
