### ISSUE TITLE
NullPointerException with the JCublas backend in Word2Vec

### ISSUE THREAD

**Issue by aritasimoes** [deeplearning4j/deeplearning4j#177]
I'm trying to run my word2vec script (in clojure and OSX) using the GPU, but I get a NullPointerException right after the weight resetting step.

The only change I made was to replace my nd4j backend: instead of [org.nd4j/nd4j-jblas "0.0.3.5.5.2"] I used [org.nd4j/nd4j-jcublas-osx-6.5 "0.0.3.5.5.2"]. I checked my CUDA install and it's working properly.

Thanks in advance.

**Comment by agibsonccc** [comment]
Mind posting the stack trace?

**Comment by aritasimoes** [comment]
It's simply:

CompilerException java.lang.NullPointerException, compiling:(core.clj:20:12) 

with that line referring to my call to the word2vec .fit method.

**Comment by agibsonccc** [comment]
I deployed a lot of fixes to the CUDA support. Would you mind looking at this when you get the chance?

**Comment by aritasimoes** [comment]
After cleaning install nd4j, I get the following:

Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load the native library.
Error while loading native library "JCudaDriver-apple-x86_64" with base name "JCudaDriver"
Operating system name: Mac OS X
Architecture         : x86_64
Architecture bit size: 64
Stack trace from the attempt to load the library as a resource:
java.lang.NullPointerException: No resource found with name '/lib/libJCudaDriver-apple-x86_64jnilib'


I do have a /lib/libJCudaDriver-apple-x86_64dylib , though.

**Comment by agibsonccc** [comment]
Ok great. If you use:

nd4j-jcublas-${YOUR_VERSION} with the artficact Id and setup your LD_LIBRARY_PATH you should be set to go.

http://docs.nvidia.com/cuda/cuda-getting-started-guide-for-mac-os-x/#axzz3Tc7ILv7a
