### ISSUE TITLE
 java.lang.NullPointerException with MergeVertex and EmbeddingLayer

### ISSUE THREAD

**Issue by rasoolims** [deeplearning4j/deeplearning4j#1784]
In a ComputationGraphConfiguration, I have a MergeVertex that concatenates several EmbeddingLayers. I want to make the EmbeddingLayers to have the same embedding dictionaries (i.e. the first layer and the second layer are the same but they point to different word positions in the sentence). When I use the same embeddingLayer, I get a null pointer exception

```java
EmbeddingLayer e1 = new EmbeddingLayer.Builder().nIn(inDim).nOut(outDim).activation("identity")
                .weightInit(WeightInit.DISTRIBUTION).dist(new GaussianDistribution(0, 0.01)).build();

 ComputationGraphConfiguration confComplex = confBuilder.graphBuilder()
  .addInputs("s0w", "s1w")
  .addLayer("L1", e1, "s0w")
  .addLayer("L2", e1, "s1w")
  .addVertex("concat", new MergeVertex(),"L1","L2")
  .addLayer("h1", new DenseLayer.Builder().nIn(2 * wordDimension)
  .weightInit(WeightInit.DISTRIBUTION).dist(new GaussianDistribution(0, 0.01)).biasInit(0.2)
  .nOut(options.hiddenLayer1Size).activation("relu").build(), "concat")
  .addLayer("out", new OutputLayer.Builder(LossFunction.NEGATIVELOGLIKELIHOOD)
  .nIn(options.hiddenLayer1Size).nOut(possibleOutputs).activation("softmax").build(), "h1")
  .setOutputs("out")
  .backprop(true).build();
```

> Exception in thread "main" java.lang.NullPointerException
	at org.deeplearning4j.nn.updater.graph.ComputationGraphUpdater.update(ComputationGraphUpdater.java:79)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.updateGradientAccordingToParams(BaseOptimizer.java:282)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:155)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:56)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:662)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:632)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:585)

**Comment by AlexDBlack** [comment]
Unfortunately you can't just share the same layer configuration object between multiple layers, and expect it to work at this point. There's a lot that goes on behind the scenes as far as actually initializing the implementation layer classes.
```java
.addLayer("L1", e1, "s0w")
.addLayer("L2", e1, "s1w")
```
Even if we solve the configuration issue to allow you to do this (giving you a shared layer in the net itself as per what you are trying to do with the configuration), the resulting network won't work given the current design (around view arrays for parameters and gradients).

This sort of functionality is going to require some proper design and implementation work around parameter sharing. https://github.com/deeplearning4j/deeplearning4j/issues/1785

**Comment by rasoolims** [comment]
I got around it by doing the following:

```java
/**
assume that num_of_shared_embedding_layers first layers should share parameters
**/
// init all those layers that we want with the same values
INDArray wArr = net.getLayer(0).getParam("W");
INDArray bArr = net.getLayer(0).getParam("b");
for (int i = 1; i < num_of_shared_embedding_layers; i++) {
   net.getLayer(i).setParam("W",wArr);
   net.getLayer(i).setParam("b",bArr);
}

for (int iter = 0; iter < T; iter++) {
    trainIter.reset();
    while (trainIter.hasNext()) {
       // remember what we had before times the number of layers minus one (we need do 
      // subtract it later because the final value is the original value plus sum 
      // of gradients)
      INDArray wArrBefore = net.getLayer(0).getParam("W").mul(num_of_shared_embedding_layers-1);
      INDArray bArrBefore = net.getLayer(0).getParam("b").mul(num_of_shared_embedding_layers-1);

      net.fit(trainIter.next());
 
     // recalculate the new values
     INDArray wArr = net.getLayer(0).getParam("W");
     INDArray bArr = net.getLayer(0).getParam("b");

     // add all other layers to the first one
      for (int i = 1; i < num_of_shared_embedding_layers; i++) {
            wArr.addi(net.getLayer(i).getParam("W"));
            bArr.addi(net.getLayer(i).getParam("b"));
      }

     // subtract with wArrBefore and bArrBefore (now it is equal to the original 
     // value + gradients for all those layers)
      wArr = wArr.subi(wArrBefore);
      bArr = bArr.subi(bArrBefore);

     // write back to all layers (now it is equal to what we want)
      for (int i = 0; i < num_of_shared_embedding_layers; i++) {
           net.getLayer(i).setParam("W", wArr);
           net.getLayer(i).setParam("b", bArr);
      }
}

```

Even with a large amount of training instances, I find a very small runtime overhead to the original running time.
