### ISSUE TITLE
Import caffe pre trained model

### ISSUE THREAD

**Issue by jrabary** [deeplearning4j/deeplearning4j#179]
Having the ability to import pre-trained caffe model : 
- Does deeplearning4j uses the same DAG architecture as caffe ?
- How about weight sharing for example in a siamese network ?

**Comment by lucmichalski** [comment]
+1

**Comment by JozoVilcek** [comment]
+1

**Comment by y22ma** [comment]
Would really appreciate exporting functionality as well. Train the model using DL4J and deploy them on smaller machines running Caffe for real-time application.

**Comment by agibsonccc** [comment]
@y22ma Dl4j's whole point is that its hooked up to something like kafka for stream processing? Could you provide compelling numbers for this use case?

**Comment by y22ma** [comment]
It really spawn from my personal use case. My biggest pain point right now is the amount of time spent in training, and with my current setup, the training time is capped by the numbers and speed of GPUs in a single machine. DL4J allows me to vary the speed the training using more than machines at a time, so I have more control over the training time, but there is no quick way for me to deploy the trained net on an embedded platform such as a TK1.

Coming from a robotics background, I see tons of applications for this type of use case of DL4J.

**Comment by agibsonccc** [comment]
Got it. We're thinking of different kinds of data pipelines. Cool ,we can talk about that. That will be a separate issue though.

**Comment by agibsonccc** [comment]
Handled via keras import.
