### ISSUE TITLE
LFW iterator unit tests failing

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1794]
Multiple tests using LFW iterator are failing.

~~DataSetIteratorTests.testLfwModel: NPE~~
~~DataSetIteratorTest.testLfwIterator: failing~~
~~DataSetIteratorTest.testBatchSizeOfOne: failing~~
LocalUnstructuredDataFormatterTest.testRearrange: NPE

First 3 seem to be fixed after this: https://github.com/deeplearning4j/deeplearning4j/pull/1797

**Comment by agibsonccc** [comment]
Fixed. https://github.com/deeplearning4j/deeplearning4j/pull/1807
