### ISSUE TITLE
Loading a model fails to work with OpenCV 2.4.11

### ISSUE THREAD

**Issue by stephanduq** [deeplearning4j/deeplearning4j#1801]
If you try to load a model, and you have also loaded OpenCV 2.4.11 in your pom, the model will load indefinitely. 

Both ModelSerializer.restoreMultiLayerNetwork(file) and the old MultiLayerConfiguration.fromJson() workflow can both be used to replicate this behavior.

Removing opencv from the pom solves the issue. (but then ofcourse you are without OpenCV 2.4)

**Comment by saudet** [comment]
Could you provide sample source code along with the pom.xml file to replicate that?

**Comment by stephanduq** [comment]
Ofcourse, here is the POM.

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>groupId</groupId>
    <artifactId>SergeAutoStyle</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <nd4j.version>0.4-rc3.10</nd4j.version>
        <dl4j.version>0.4-rc3.10</dl4j.version>
        <mysql.version>5.1.36</mysql.version>
    </properties>



    <dependencies>
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
            <version>2.4.2</version>
        </dependency>

        <dependency>
            <groupId>org.imgscalr</groupId>
            <artifactId>imgscalr-lib</artifactId>
            <version>4.2</version>
        </dependency>

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>${mysql.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.5</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-api</artifactId>
            <version>${nd4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-ui</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>${dl4j.version}</version>

            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>*</artifactId>
                </exclusion>



            </exclusions>

        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive>
                        <manifest>
                            <mainClass>sergeauto.SergeAuto</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>

        </plugins>
    </build>
</project>
`
And this is how I load the model

`
File modelFile = new File("styleclassifiers/" + modelId.getKey());
MultiLayerNetwork model = ModelSerializer.restoreMultiLayerNetwork(modelFile);
`

After assembling the project into a jar, the problem returns

**Comment by stephanduq** [comment]
Making sure that nd4j-native was build with a linux classifier fixed the issue.

**Comment by saudet** [comment]
OpenCV isn't in the pom.xml file... so it's not an issue with OpenCV??

**Comment by stephanduq** [comment]
I wasn't getting any exceptions or error, so I have a feeling multiple problems where happening at the same time. And I haven't been able replicate the issue in this project. I have another project lying around that is using OpenCV quite heavily that I'm going to port today. If there is an OpenCV bug I will find it there!
