### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#1803]
TestCanovaDataSetFunctions.testCanovaDataSetFunction:96 expected:<4> but was:<0>
BagOfWordsVectorizerTest.testBagOfWordsVectorizer:111 expected:<1.0> but was:<0.0>
TfidfVectorizerTest.testTfIdfVectorizer:104 expected:<0.0> but was:<1.0>
GloveTest.testGloVe1:121 null
SequenceVectorsTest.testGlove1:322 null
TestSerialization.testModelSerde:57 » IndexOutOfBounds 12

**Comment by nyghtowl** [comment]
Note TestCanovaDataSetFunctions issue is the same as: https://github.com/deeplearning4j/DataVec/issues/2

**Comment by raver119** [comment]
I'll take care of dl4j-nlp tests, hasn't noticed failures there...

**Comment by eraly** [comment]
I am looking at the Serialization test.

**Comment by eraly** [comment]
https://github.com/deeplearning4j/nd4j/pull/1104
Fixed the serialization issue

**Comment by raver119** [comment]
BoW & TF-IDF errors can be ignored for now, got them fixed but not merged - just filesystem sorting issue. 

But GloVe issue isn't fixed and can't find root of the problem yet. Code wasn't changed since original rewrite, but it's just not working. Looking for hidden linked changes now.

**Comment by agibsonccc** [comment]
Can this be closed yet?

**Comment by raver119** [comment]
Unfortunately not yet :(
