### ISSUE TITLE
Bug found in ModelSerializer

### ISSUE THREAD

**Issue by hrbitteur** [deeplearning4j/deeplearning4j#1816]
Bonjour,
In 4.0 release, method **restoreMultiLayerNetwork(InputStream is)** in **ModelSerializer** class is obviously wrong. Starting line 248, you can read:
```
        while((entry = zipFile.getNextEntry()) != null) {
            switch (entry.getName()) {
                case "configuration.json":
                    DataInputStream dis = new DataInputStream(zipFile); // <== NO!
                    params = Nd4j.read(dis); // <== NO!
                    gotConfig = true;
                    break;
                case "coefficients.bin":
                    DataInputStream dis2 = new DataInputStream(zipFile);
                    params = Nd4j.read(dis2);
                    gotCoefficients = true;
                    break;
```
In other words, when processing the zip entry "configuration.json", you actually try to read 'params' value! Based on code of the overloaded method (the one expecting a File argument), I would suggest to use:
```
            case "configuration.json":
                BufferedReader reader = new BufferedReader(new InputStreamReader(zipfile));
                String line = "";
                StringBuilder js = new StringBuilder();
                while ((line = reader.readLine()) != null) {
                    js.append(line).append("\n");
                }
                json = js.toString();
                gotConfig = true;
                break;
```
My advice would be to avoid code duplication between the 3 methods restoreMultiLayerNetwork() which differ on their argument (String vs File vs InputStream) and stick to a single implementation (the one using InputStream) since the 2 other ones could easily delegate to it.

Bye,
/Hervé

**Comment by agibsonccc** [comment]
Pull requests welcome :)

**Comment by raver119** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/1828
