### ISSUE TITLE
Broken link on site

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#1820]
http://deeplearning4j.org/simple-image-load-transform.html
second link on this page leads to https://github.com/deeplearning4j/dl4j-0.4-examples/blob/earlybird/src/main/java/org/deeplearning4j/examples/dataExamples/ImagePipelineExample.java

which is outdated link. Here's proper one:

https://github.com/deeplearning4j/dl4j-0.4-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/dataExamples/ImagePipelineExample.java

**Comment by chrisvnicholson** [comment]
fixed
