### ISSUE TITLE
Using NGramTokenizerFactory for vectors

### ISSUE THREAD

**Issue by renuka98** [deeplearning4j/deeplearning4j#1834]
I would like to vectorize ngrams and hence used the ngram tokenizer.  It does not seem to be working fine. Here is the code I tried using NGramTokenizerFactory

```
// Split on white spaces in the line to get words
```

   TokenizerFactory t1 = new DefaultTokenizerFactory();
   t1.setTokenPreProcessor(new CommonPreprocessor());
    TokenizerFactory t = new NGramTokenizerFactory(t1, 1, 3);

```
     System.out.println("Building model....");
   Word2Vec vec = new Word2Vec.Builder()
           .minWordFrequency(5)
           .iterations(1)
           .layerSize(100)
           .seed(42)
           .windowSize(5)
           .iterate(iter)
           .tokenizerFactory(t)
           .build();
vec.fit();
double weight = vec.similarity("memory", "semantic");  //returns a null.
```

However, if I just use the DefaultTokernizerFactory, it returns the similarity measure.

A small part of the serialized vectors is shown below
_Az92_[seems,_Az92_to] -0.012880571186542511 -0.002391873626038432 ..........
_Az92_[then] -0.008083909749984741 -0.013380923308432102.........................
_Az92_[for,_Az92_breakfast] 0.04253905266523361 0.024196598678827286  .........
_Az92_[type,_Az92_of] .......

**Comment by raver119** [comment]
Az92 is just temporary delimiter for tokens within n-gram. I'll check why it's not replaced back on output. 

As temporary workaround just replace it to whatever you want.

**Comment by dimsable** [comment]
raver119,

Can you please tell if there is any progress with this issue?
On version 0.6.0 I see same error:
_Az92_[calvin,_Az92_klein] -0.06634753197431564 0.2689773440361023 0.41148582100868225
