### ISSUE TITLE
Review Evaluation.evalTimeSeries and RegressionEvaluation.evalTimeSeries

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1839]
https://github.com/deeplearning4j/deeplearning4j/blob/1147f9d1c4034be9b7a9e36e87aae6f91e6097c5/deeplearning4j-core/src/main/java/org/deeplearning4j/eval/Evaluation.java#L255

Given semi-recent changes to RNNs (last few months): output (and label) order for RNNs is likely to be f order. The current implementations there will always result in a copy in this case, which has some performance overhead.

**Comment by raver119** [comment]
I guess this isn't relevant anymore?
