### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jnind4j in java.library.path

### ISSUE THREAD

**Issue by NathanPelli** [deeplearning4j/deeplearning4j#1840]
Hey,
     Help me.  I am running into this problem.I am confused.
    **java.lang.UnsatisfiedLinkError: no jnind4j in java.library.path** 
     I run my application on centos 64 bit,jdk 1.8 64bit server.And I tried the solution
 -Djava.library.path=""   But it does not work.The problem is still there.I do not know why,would you please show me the solution to solve this problem.
   Thank You Very Much !

**Comment by raver119** [comment]
Take a look here please: https://github.com/deeplearning4j/deeplearning4j/issues/1819

**Comment by NathanPelli** [comment]
I've seen it : #1819  . and I have tried all the tips ,it still not wok.So strange

**Comment by raver119** [comment]
Add more details on your environment please. Are you using single workstation, or making jar on one system, and launching on another one?

Also, please, show your pom.xml

**Comment by NathanPelli** [comment]
I build a flat jar with maven on windows 7 and run the jar on centos.Does it matter ? Here is one part of my pom.xml as follows :
 <dependency>
     <groupId>org.deeplearning4j</groupId>
     <artifactId>deeplearning4j-ui-components</artifactId>
     <version>${dl4j.version}</version>
   </dependency>
   <dependency>
     <groupId>org.deeplearning4j</groupId>
     <artifactId>deeplearning4j-nlp</artifactId>
     <version>${dl4j.version}</version>
   </dependency>






   <dependency> 
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native</artifactId>
    <version>0.4.0</version>
   </dependency>

**Comment by raver119** [comment]
Yes, that matters a lot. If you build uber jar on one OS, and run on other - you need to add nd4j-native backend with both classifiers manually, since by default maven will pack only jars for your current OS.

**Comment by NathanPelli** [comment]
ok , I know that. And when I add the classifiers ,it still not work.
<dependency> 
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native</artifactId>
    <version>0.4.0</version>
   <classifier>linux-x86_64</classifier>
   </dependency>

**Comment by raver119** [comment]
show full pom.xml please, not a parts of it.

**Comment by NathanPelli** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>

	<groupId>com.guess</groupId>
	<artifactId>scheduler</artifactId>
	<version>0.3.0</version>
	<packaging>jar</packaging>
	<name>hdxscheduler</name>
	<url>http://maven.apache.org</url>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<nd4j.version>0.4.0</nd4j.version> 
    	<dl4j.version>0.4.0</dl4j.version>
	</properties>
<!-- 	<repositories> -->
<!-- 		 <repository> -->
<!-- 			<id>ProjectRepo</id> -->
<!-- 			<name>ProjectRepo</name> -->
<!-- 			<url>file://${project.basedir}/src/main/resources/libs</url> -->
<!-- 		</repository>  -->
<!-- 		<repository> -->
<!-- 			<id>nitinka.mvn.repo</id> -->
<!-- 			<url>https://github.com/nitinka/mvn-repo/raw/master</url> -->
<!-- 		</repository> -->
<!-- 		<repository> -->
<!-- 			<id>sonatype-nexus-snapshots</id> -->
<!-- 			<name>Sonatype Nexus Snapshots</name> -->
<!-- 			<url>http://oss.sonatype.org/content/repositories/snapshots</url> -->
<!-- 		</repository> -->
<!-- 		<repository> -->
<!-- 			<id>repo.codahale.com</id> -->
<!-- 			<url>http://repo.codahale.com/</url> -->
<!-- 		</repository> -->
<!-- 	</repositories> -->

	<pluginRepositories>
	        <pluginRepository>
	            <id>huodongxing</id>
	            <name>Team Plugin Repository</name>
	            <url>http://192.168.5.24:8081/nexus/content/groups/public</url>
	        </pluginRepository>
	    </pluginRepositories>
	<dependencies>
		<dependency>
			<groupId>io.dropwizard</groupId>
			<artifactId>dropwizard-core</artifactId>
			<version>0.8.1</version>
		</dependency>
		<dependency>
			<groupId>io.dropwizard</groupId>
			<artifactId>dropwizard-db</artifactId>
			<version>0.8.1</version>
		</dependency>
		<dependency>
		  <groupId>io.dropwizard.modules</groupId>
		  <artifactId>dropwizard-elasticsearch</artifactId>
		  <version>0.8.0-1</version>
		</dependency> 
		<dependency>
			<groupId>io.dropwizard</groupId>
			<artifactId>dropwizard-jdbi</artifactId>
			<version>0.8.1</version>
		</dependency>
		<dependency>
			<groupId>com.hubspot.dropwizard</groupId>
			<artifactId>dropwizard-guice</artifactId>
			<version>0.8.0</version>
			<exclusions>
                <exclusion>
                    <groupId>aopalliance</groupId>
                    <artifactId>aopalliance</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.google.code.findbugs</groupId>
                    <artifactId>annotations</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>javax.inject</groupId>
                    <artifactId>javax.inject</artifactId>
                </exclusion>
            </exclusions>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>5.1.30</version>
		</dependency>
		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>mail</artifactId>
			<version>1.4</version>
		</dependency>
		<dependency>
			<groupId>org.quartz-scheduler</groupId>
			<artifactId>quartz</artifactId>
			<version>2.2.1</version>
		</dependency>
		<dependency>
			<groupId>org.quartz-scheduler</groupId>
			<artifactId>quartz-jobs</artifactId>
			<version>2.2.1</version>
		</dependency>
		<dependency>
			<groupId>gexin-rp</groupId>
			<artifactId>gexin-rp-sdk-base</artifactId>
			<version>4.0.0.7</version>
		</dependency>
		<dependency>
			<groupId>gexin-rp</groupId>
			<artifactId>gexin-rp-sdk-http</artifactId>
			<version>4.0.1.2</version>
		</dependency>
		<dependency>
			<groupId>gexin-rp</groupId>
			<artifactId>gexin-rp-sdk-template</artifactId>
			<version>4.0.0.4</version>
		</dependency>
		<dependency>
			<groupId>com.google.protobuf</groupId>
			<artifactId>protobuf-java</artifactId>
			<version>2.6.1</version>
		</dependency>
			<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>18.0</version>
		</dependency>
		<dependency>
	        <groupId>commons-io</groupId>
	        <artifactId>commons-io</artifactId>
	        <version>2.1</version>
	    </dependency>
	     <dependency>  
            <groupId>javax.transaction</groupId>  
            <artifactId>jta</artifactId>  
            <version>1.1</version>  
        </dependency>
        <dependency>
            <groupId>org.codehaus.jackson</groupId>
            <artifactId>jackson-mapper-asl</artifactId>
            <version>1.9.2</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.jackson</groupId>
            <artifactId>jackson-core-asl</artifactId>
            <version>1.9.2</version>
        </dependency>
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>2.6.1</version>
        </dependency>
        <dependency>
		  <groupId>antlr</groupId>
		  <artifactId>stringtemplate</artifactId>
		  <version>2.3b6</version> <!-- I am not sure if this specific version is meant to be used though -->
		</dependency>
        <dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.10</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-all</artifactId>
			<version>1.9.5</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.dropwizard</groupId>
			<artifactId>dropwizard-testing</artifactId>
			<version>0.8.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
              <groupId>com.rabbitmq</groupId>
              <artifactId>amqp-client</artifactId>
              <version>3.5.3</version>
        </dependency>
		<dependency>
	      <groupId>commons-httpclient</groupId>
	      <artifactId>commons-httpclient</artifactId>
	      <version>3.1</version>
        </dependency>
		 <dependency>
			<groupId>net.sf.json-lib</groupId>
			<artifactId>json-lib</artifactId>
			<version>2.3</version>
			<classifier>jdk15</classifier>
		</dependency>
		<dependency>
    		<groupId>org.apache.logging.log4j</groupId>
    		<artifactId>log4j-api</artifactId>
    		<version>2.3</version>
  		</dependency>
  		<dependency>
   			<groupId>org.apache.logging.log4j</groupId>
   	 		<artifactId>log4j-core</artifactId>
   	 		<version>2.3</version>
  		</dependency> 
  	<!-- 以下是整合Word2Vec和fudanNLP功能 -->	
  	<dependency>
    <groupId>commons-cli</groupId>
    <artifactId>commons-cli</artifactId>
    <version>1.2</version>
    </dependency>
    <dependency>
    <groupId>fudannlp</groupId>
    <artifactId>fudannlp</artifactId>
    <version>1.0</version>
    </dependency>
    <dependency>
    <groupId>trove</groupId>
    <artifactId>trove</artifactId>
    <version>1.0</version>
    </dependency> 	
    
    <dependency>
     <groupId>org.deeplearning4j</groupId>
     <artifactId>deeplearning4j-ui-components</artifactId>
     <version>${dl4j.version}</version>
   </dependency>
   <dependency>
     <groupId>org.deeplearning4j</groupId>
     <artifactId>deeplearning4j-nlp</artifactId>
     <version>${dl4j.version}</version>
   </dependency>
<!--    <dependency> -->
<!--      <groupId>org.nd4j</groupId> -->
<!--      <artifactId>nd4j-native</artifactId>  -->
<!--      <version>${nd4j.version}</version> -->
<!--      <classifier>linux-x86_64</classifier> -->
<!--    </dependency>	 -->
   <dependency> 
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native</artifactId>
    <version>0.4.0</version>
   </dependency>
<!--    <dependency> -->
<!--     <groupId>org.nd4j</groupId> -->
<!--     <artifactId>nd4j-native-api</artifactId> -->
<!--     <version>0.4-rc3.9</version> -->
<!--    </dependency> -->
<!--    <dependency> -->
<!--     <groupId>org.deeplearning4j</groupId> -->
<!--     <artifactId>deeplearning4j-core</artifactId> -->
<!--     <version>0.4-rc3.9</version> -->
<!--    </dependency> -->
<!--    <dependency> -->
<!--     <groupId>org.nd4j</groupId> -->
<!--     <artifactId>nd4j-backends</artifactId> -->
<!--     <version>0.4.0</version> -->
<!--     <type>pom</type> -->
<!--    </dependency> -->
<!--    <dependency> -->
<!--     <groupId>org.nd4j</groupId> -->
<!--     <artifactId>canova-api</artifactId> -->
<!--     <version>0.0.0.17</version> -->
<!--    </dependency> -->
<!--    <dependency> -->
<!--     <groupId>org.nd4j</groupId> -->
<!--     <artifactId>nd4j-jblas</artifactId> -->
<!--     <version>0.4-rc3.6</version> -->
<!--    </dependency> -->
<!--    <dependency> -->
<!--     <groupId>org.nd4j</groupId> -->
<!--     <artifactId>canova-nd4j-image</artifactId> -->
<!--     <version>0.0.0.17</version> -->
<!--    </dependency> -->
<!--    <dependency> -->
<!--     <groupId>org.nd4j</groupId> -->
<!--     <artifactId>canova-nd4j-codec</artifactId> -->
<!--     <version>0.0.0.17</version> -->
<!--    </dependency> -->
<!--    <dependency> -->
<!--     <groupId>org.nd4j</groupId> -->
<!--     <artifactId>nd4j-cuda-7.5</artifactId> -->
<!--     <version>0.4.0</version> -->
<!--    </dependency> -->
	</dependencies>
	<build>
		<plugins>
		    <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
            <plugin>  
            <!-- 发布插件 -->  
            <groupId>org.apache.maven.plugins</groupId>  
            <artifactId>maven-deploy-plugin</artifactId>  
            <version>2.5</version>  
        </plugin>  
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.4</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.2</version>
                <configuration>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>META-INF/*.SF</exclude>
                                <exclude>META-INF/*.DSA</exclude>
                                <exclude>META-INF/*.RSA</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>com.guess.SchedulerApplication</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
		</plugins>
	</build>
</project>

**Comment by raver119** [comment]
Uncomment dep with classifier please, pack your jar, upload, execute on remote server, and show full output you get there.

**Comment by NathanPelli** [comment]
ok,now I do as you say,here is the full pom.xml ：
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>

	<groupId>com.guess</groupId>
	<artifactId>hdxscheduler</artifactId>
	<version>0.3.0</version>
	<packaging>jar</packaging>
	<name>hdxscheduler</name>
	<url>http://maven.apache.org</url>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<nd4j.version>0.4.0</nd4j.version> 
    	<dl4j.version>0.4.0</dl4j.version>
	</properties>

	<pluginRepositories>
	        <pluginRepository>
	            <id>huodongxing</id>
	            <name>Team Plugin Repository</name>
	            <url>http://192.168.5.24:8081/nexus/content/groups/public</url>
	        </pluginRepository>
	    </pluginRepositories>
	<dependencies>
		<dependency>
			<groupId>io.dropwizard</groupId>
			<artifactId>dropwizard-core</artifactId>
			<version>0.8.1</version>
		</dependency>
		<dependency>
			<groupId>io.dropwizard</groupId>
			<artifactId>dropwizard-db</artifactId>
			<version>0.8.1</version>
		</dependency>
		<dependency>
		  <groupId>io.dropwizard.modules</groupId>
		  <artifactId>dropwizard-elasticsearch</artifactId>
		  <version>0.8.0-1</version>
		</dependency> 
		<dependency>
			<groupId>io.dropwizard</groupId>
			<artifactId>dropwizard-jdbi</artifactId>
			<version>0.8.1</version>
		</dependency>
		<dependency>
			<groupId>com.hubspot.dropwizard</groupId>
			<artifactId>dropwizard-guice</artifactId>
			<version>0.8.0</version>
			<exclusions>
                <exclusion>
                    <groupId>aopalliance</groupId>
                    <artifactId>aopalliance</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.google.code.findbugs</groupId>
                    <artifactId>annotations</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>javax.inject</groupId>
                    <artifactId>javax.inject</artifactId>
                </exclusion>
            </exclusions>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>5.1.30</version>
		</dependency>
		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>mail</artifactId>
			<version>1.4</version>
		</dependency>
		<dependency>
			<groupId>org.quartz-scheduler</groupId>
			<artifactId>quartz</artifactId>
			<version>2.2.1</version>
		</dependency>
		<dependency>
			<groupId>org.quartz-scheduler</groupId>
			<artifactId>quartz-jobs</artifactId>
			<version>2.2.1</version>
		</dependency>
		<dependency>
			<groupId>gexin-rp</groupId>
			<artifactId>gexin-rp-sdk-base</artifactId>
			<version>4.0.0.7</version>
		</dependency>
		<dependency>
			<groupId>gexin-rp</groupId>
			<artifactId>gexin-rp-sdk-http</artifactId>
			<version>4.0.1.2</version>
		</dependency>
		<dependency>
			<groupId>gexin-rp</groupId>
			<artifactId>gexin-rp-sdk-template</artifactId>
			<version>4.0.0.4</version>
		</dependency>
		<dependency>
			<groupId>com.google.protobuf</groupId>
			<artifactId>protobuf-java</artifactId>
			<version>2.6.1</version>
		</dependency>
			<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>18.0</version>
		</dependency>
		<dependency>
	        <groupId>commons-io</groupId>
	        <artifactId>commons-io</artifactId>
	        <version>2.1</version>
	    </dependency>
	     <dependency>  
            <groupId>javax.transaction</groupId>  
            <artifactId>jta</artifactId>  
            <version>1.1</version>  
        </dependency>
        <dependency>
            <groupId>org.codehaus.jackson</groupId>
            <artifactId>jackson-mapper-asl</artifactId>
            <version>1.9.2</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.jackson</groupId>
            <artifactId>jackson-core-asl</artifactId>
            <version>1.9.2</version>
        </dependency>
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>2.6.1</version>
        </dependency>
        <dependency>
		  <groupId>antlr</groupId>
		  <artifactId>stringtemplate</artifactId>
		  <version>2.3b6</version> 
		</dependency>
        <dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.10</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-all</artifactId>
			<version>1.9.5</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.dropwizard</groupId>
			<artifactId>dropwizard-testing</artifactId>
			<version>0.8.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
              <groupId>com.rabbitmq</groupId>
              <artifactId>amqp-client</artifactId>
              <version>3.5.3</version>
        </dependency>
		<dependency>
	      <groupId>commons-httpclient</groupId>
	      <artifactId>commons-httpclient</artifactId>
	      <version>3.1</version>
        </dependency>
		 <dependency>
			<groupId>net.sf.json-lib</groupId>
			<artifactId>json-lib</artifactId>
			<version>2.3</version>
			<classifier>jdk15</classifier>
		</dependency>
		<dependency>
    		<groupId>org.apache.logging.log4j</groupId>
    		<artifactId>log4j-api</artifactId>
    		<version>2.3</version>
  		</dependency>
  		<dependency>
   			<groupId>org.apache.logging.log4j</groupId>
   	 		<artifactId>log4j-core</artifactId>
   	 		<version>2.3</version>
  		</dependency> 
  	<dependency>
    <groupId>commons-cli</groupId>
    <artifactId>commons-cli</artifactId>
    <version>1.2</version>
    </dependency>
    <dependency>
    <groupId>fudannlp</groupId>
    <artifactId>fudannlp</artifactId>
    <version>1.0</version>
    </dependency>
    <dependency>
    <groupId>trove</groupId>
    <artifactId>trove</artifactId>
    <version>1.0</version>
    </dependency> 	
    
    <dependency>
     <groupId>org.deeplearning4j</groupId>
     <artifactId>deeplearning4j-ui-components</artifactId>
     <version>${dl4j.version}</version>
   </dependency>
   <dependency>
     <groupId>org.deeplearning4j</groupId>
     <artifactId>deeplearning4j-nlp</artifactId>
     <version>${dl4j.version}</version>
   </dependency>
   <dependency> 
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native</artifactId>
    <version>0.4.0</version>
    <classifier>linux-x86_64</classifier>
   </dependency>
	</dependencies>
	<build>
		<plugins>
		    <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
            <plugin>  
            <groupId>org.apache.maven.plugins</groupId>  
            <artifactId>maven-deploy-plugin</artifactId>  
            <version>2.5</version>  
        </plugin>  
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.4</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.2</version>
                <configuration>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>META-INF/*.SF</exclude>
                                <exclude>META-INF/*.DSA</exclude>
                                <exclude>META-INF/*.RSA</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>com.guess.HdxSchedulerApplication</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
		</plugins>
	</build>
</project>

and execute the jar,got the ouput as follows:
INFO  [2016-07-19 11:20:47,632] org.eclipse.jetty.server.ServerConnector: Started admin@4349754{HTTP/1.1}{0.0.0.0:9091}
INFO  [2016-07-19 11:20:47,632] org.eclipse.jetty.server.Server: Started @3242ms
ERROR [2016-07-19 11:20:50,123] org.quartz.core.ErrorLogger: An error occured instantiating job to be executed. job= 'HDX_GROUP.RecommendTagJob'
! java.lang.UnsatisfiedLinkError: no nd4j in java.library.path
! at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[na:1.8.0_92]
! at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[na:1.8.0_92]
! at java.lang.System.loadLibrary(System.java:1122) ~[na:1.8.0_92]
! at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:726) ~[hdxscheduler-0.3.0.jar:0.3.0]
! at org.bytedeco.javacpp.Loader.load(Loader.java:492) ~[hdxscheduler-0.3.0.jar:0.3.0]
! ... 27 common frames omitted
! Causing: java.lang.UnsatisfiedLinkError: no jnind4j in java.library.path
! at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[na:1.8.0_92]
! at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[na:1.8.0_92]
! at java.lang.System.loadLibrary(System.java:1122) ~[na:1.8.0_92]
! at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:726) ~[hdxscheduler-0.3.0.jar:0.3.0]
! at org.bytedeco.javacpp.Loader.load(Loader.java:501) ~[hdxscheduler-0.3.0.jar:0.3.0]
! at org.nd4j.nativeblas.NativeOps.<clinit>(NativeOps.java:31) ~[hdxscheduler-0.3.0.jar:0.3.0]
! at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:33) ~[hdxscheduler-0.3.0.jar:0.3.0]
! at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_92]
! at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_92]
! at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1

**Comment by raver119** [comment]
In your latest pom.xml there's no backend defined.

**Comment by NathanPelli** [comment]
But when I omit the classfiers,the output shows  no jnind4j in java.library.path error

**Comment by raver119** [comment]
just add both classifiers, one for workstation, other one for your server.

**Comment by NathanPelli** [comment]
in my case, you mean both "    <classifier>linux-x86_64</classifier>"  and "    <classifier>windows-x86_64</classifier>"     ?

**Comment by raver119** [comment]
yep. So you'll technically have 2 nd4j-native dependencies, one for windows, other one for linux

**Comment by NathanPelli** [comment]
<dependency> 
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native</artifactId>
    <version>0.4.0</version>
    <classifier>linux-x86_64</classifier>
   </dependency>
   <dependency> 
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native</artifactId>
    <version>0.4.0</version>
    <classifier>windows-x86_64</classifier>
   </dependency>

Like this ?
I tried ,and the error stays the same .

**Comment by NathanPelli** [comment]
it cost me a few days, and I still can not get the answer.
when I add the classfiers(one or two classfiers),the error says no backend is defined.But when I omit the classfiers,the error says no jnind4j in java.library.path.It is so confusing

**Comment by NathanPelli** [comment]
someone help ?

**Comment by raver119** [comment]
Sure someone will help, but it's not like a real-time chat here and thinking takes some time too ;)

**Comment by agibsonccc** [comment]
Use 

<dependency>
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native-platform</artifactId>
    <version>0.4.0</version>
</dependency>

**Comment by NathanPelli** [comment]
thanks all you guys. Finally,I get the solution as follows:
<dependency> 
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native</artifactId>
    <version>0.4.0</version>
   </dependency>
    <dependency> 
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native</artifactId>
    <version>0.4.0</version>
    <classifier>linux-x86_64</classifier>
   </dependency>

should omit the classfier "windows-x86_64"
Thank you very much @raver119 @agibsonccc
