### ISSUE TITLE
Extend Computation Graph to be able to Build Dataflow / FRP / Reactive Computational Networks

### ISSUE THREAD

**Issue by sirinath** [deeplearning4j/deeplearning4j#1841]
Computation Graph can be extended edges represent data flows and vertices can represent more arbitrary computations on the input data. This perhaps can be factored out and the NN framework can be  a special case of the computing framework.

Also have a look at: http://tinkerpop.apache.org/docs/current/reference/#graphcomputer but this is a bit complicated.

**Comment by agibsonccc** [comment]
Right - we intended to do that. We're going to build that in nd4j first. We'll see about integrating those later.

**Comment by sirinath** [comment]
Is it possible to prioritise this as I a looking for a good Java high performance dataflow / FRP framework.

Also see: http://noflojs.org/, https://nifi.apache.org/, https://github.com/pothosware/pothos (http://www.pothosware.com/), https://www.tensorflow.org/ to get ideas. Unlike TensorFlow please keep it generic computing framework.

**Comment by agibsonccc** [comment]
Not really. We already use nifi. We prioritize paying customers unfortunately. No one who feeds me wants this feature right now and we certainly don't have a good use case for it.

**Comment by raver119** [comment]
Implemented as SameDiff and available on in 1.0.0-alpha & current master.
