### ISSUE TITLE
Multi window pass for Deep Walk and Word2Vec

### ISSUE THREAD

**Issue by mike-tamir** [deeplearning4j/deeplearning4j#1842]
Add a feature to the Deep Walk and Word2Vec implementations that allow for multiple passes in the training of the Matrix with different size windows.  Prevents bias from single window size models.

**Comment by raver119** [comment]
Got link to a paper? Or mind adding some details?

**Comment by raver119** [comment]
Initial version available here: https://github.com/deeplearning4j/deeplearning4j/pull/1855

@mike-tamir waiting for your response in PM :)
