### ISSUE TITLE
Help with RNN

### ISSUE THREAD

**Issue by Gabri95** [deeplearning4j/deeplearning4j#1848]
I was trying to add support for RNN on this project https://github.com/UnyieldingOrca/dl4j-rl

but i'm having some problem with feeding the net more than one input

Using the net "in real-time", so giving it an input (an INDArray of one dimension) at each timestep with the rrnTimeStep() method, it's ok.
My problem comes when I try to give it more inputs at one time (a 2 dimensional INDArray, in which each row is an input): it throws an "java.lang.IllegalArgumentException: A rows must equal C rows" at org.nd4j.linalg.api.blas.params.GemmParams.<init>(GemmParams.java:32)
more information can be found here: https://gist.github.com/Gabri95/8bfc53216dc5eb145d79efd8affa6a89

here is the code: https://gist.github.com/Gabri95/bb5951d89be7b90d4dd39ae0156caedd

**Comment by AlexDBlack** [comment]
I ran your TestRL code. I didn't run into any issues there.
I need something that I can run (one-click) to debug this.

**Comment by Gabri95** [comment]
I've updated the code if you want to check it. Now you can execut the main in the NeuralNetwork class.
With this code I get the exception "java.lang.IllegalArgumentException: A rows must equal C rows at org.nd4j.linalg.api.blas.params.GemmParams.<init>(GemmParams.java:32)"
