### ISSUE TITLE
Writing customized loss (objective) functions.

### ISSUE THREAD

**Issue by rasoolims** [deeplearning4j/deeplearning4j#1852]
How can I create customized loss (objective) functions? I just found this http://deeplearning4j.org/customizelossfunction but was not clear enough.

**Comment by mschaars** [comment]
I believe you have to currently do this manually for things like RL. https://github.com/deeplearning4j/deeplearning4j/issues/1178 contains basic code (scroll to the bottom) to do this.

**Comment by agibsonccc** [comment]
Done now.
