### ISSUE TITLE
Maven properties not propagating correctly in pom files

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1857]
0.4.0 dl4j-spark_2.11:
![image](https://cloud.githubusercontent.com/assets/2360237/17023928/30dfd288-4f99-11e6-89b9-46fb14ed2755.png)

0.4.0 dl4j-spark_2.10:
![image](https://cloud.githubusercontent.com/assets/2360237/17024065/b6b25e94-4f99-11e6-8754-3d44c73b70af.png)

What is occuring:
Property ```<scala.binary.version>``` is being picked up for artifact id, but is not being propagated properly for the dependencies in child poms.
So, command line override with version 2.10 results in an artifact of name dl4j-spark_2.10, but keeps using default (2.11) for the dependencies like datavec-spark_${scala.binary.version}

Things I've tried, without success:
- removing any extra properties (scala.binary.version is now defined only in highest parent pom) https://github.com/deeplearning4j/deeplearning4j/pull/1856
- adding an intermediate property ```<scala.binary.version2>${scala.binary.version}</scala.binary.version2>```, and using that for the dependencies
- adding an extra property in the child poms and overriding that on the command line too (no idea why *that* didn't work - it should)

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/Canova/pull/231
