### ISSUE TITLE
RBM reconstruction error? 

### ISSUE THREAD

**Issue by nouramoubayed** [deeplearning4j/deeplearning4j#186]
I am trying to use DL4J library to pre-train RBM net and measure the reconstruction error for every sample (entities with high error are then considered outliers) on unsupervised dataset. 

unfortunately there are no such examples in the examples set of the library. can anyone please let me know how to do so? 

many thanks

**Comment by agibsonccc** [comment]
Pretrain the RBM on data as normal. Set a threshold (distance from the mean reconstruction error of the training data). Keep track of mean reconstruction error over time for each mini batch you train by summing. Divide by the number of batches in your training set. The reconstruction error of the RBM itself is the mean of the mini batch (meaning summing over the reconstruction error of each mini batch and dividing by the number of mini batches is roughly equivalent)

I'm not going to have a recipe for doing everything for you. There would be an endless amount of use cases and I'd never be able to make new features let alone improve some of the more basic things that need to be improved.
