### ISSUE TITLE
nGrams value is not being assigned correctly - it is hardcoded to 1. 

### ISSUE THREAD

**Issue by technologycoder** [deeplearning4j/deeplearning4j#1862]
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/dl4j-spark-nlp/src/main/java/org/deeplearning4j/spark/models/embeddings/word2vec/Word2Vec.java#L508

nGrams value is always assigned value 1?

**Comment by raver119** [comment]
Fixed, thanks.
