### ISSUE TITLE
Page's Text

### ISSUE THREAD

**Issue by gsw85** [deeplearning4j/deeplearning4j#1867]
http://deeplearning4j.org/lstm , and also for other languages 

There is a person pointed out $h_t$  instead of h_t

**Comment by gsw85** [comment]
It is not request, there is a user from gitter telling me that $h_t$ should be the correct one, I am not sure if it is correct, so Adam ask me to file an issue here

**Comment by ejunprung** [comment]
im confused as well. h_t refers to the function. what does $ represent?

**Comment by chrisvnicholson** [comment]
$ is sometimes used to represent variables. The variable h_t is the hidden state of the LSTM at a certain time stamp. We are representing variables in red font on this page, so I don't think we need to add the $. I'm closing this issue.
