### ISSUE TITLE
The docs on RBM's "propUp" and "propDown" methods are confusing

### ISSUE THREAD

**Issue by nikita-volkov** [deeplearning4j/deeplearning4j#1870]
The docs seem to describe the opposite effect to what the methods are doing.
- https://github.com/deeplearning4j/deeplearning4j/blob/2e4382084d55487b44e6eeb05eda6a88ff62f74f/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/feedforward/rbm/RBM.java#L349-L354
- https://github.com/deeplearning4j/deeplearning4j/blob/2e4382084d55487b44e6eeb05eda6a88ff62f74f/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/feedforward/rbm/RBM.java#L359-L364

**Comment by eraly** [comment]
We are dropping support for RBMs in favour of newer and more effective methods. Please take a look at variational autoencoders 
https://github.com/deeplearning4j/dl4j-examples/tree/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/unsupervised/variational
