### ISSUE TITLE
Add per-output masking

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1877]
Current masking functionality: used for time series. i.e., "example is present/absent at this time step"

Per-output masking would have a 0 or 1 for each _output_ rather than each *example. Conditionally masking inputs isn't needed (just set inputs to zero manually) but there's a use case for masking individual outputs.
Possible use cases include things like missing data (i.e., N output values, but only M<N are know for this example), and perhaps some RL use-cases.

Mathematically, this isn't hard to do (current implementation is muliColumnVector, new would just be muli); the challenge is to do this in a way that doesn't result in:
(a) confusion for users,
(b) unintentionally using the wrong type (timeseries per example vs. every output)

One possibility would be to use the rank of the arrays: if mask array has rank equal to the input/output, then it must be per-output masking; otherwise, if the mask array has rank of 1 less than the input/output arrays, then it must be per-example masking.

**Comment by AlexDBlack** [comment]
Added here: https://github.com/deeplearning4j/deeplearning4j/pull/2993

**Comment by EdeMeijer** [comment]
Very nice, this could probably simplify my setup quite a bit. I noticed MCXENT + Softmax is not supported yet, is that something that will be added any time soon?

**Comment by AlexDBlack** [comment]
I wasn't going to look at MCXENT + softmax right now - I'd need to do the math (the other cases are easy), and I don't need it right now.

What's the use-case you have in mind for that though? My thinking is that in a lot of cases, MCXENT+softmax doesn't make a lot of sense - labels are usually a one-hot vector - I'm not sure what a label like [0,0,1] combined with a mask array like [0,1,1] would really mean in practice.

**Comment by EdeMeijer** [comment]
Good point there. I'm experimenting with multiple MCXENT outputs (multiple one-hot vectors in a comp graph) where some outputs might be masked while other's aren't, but of course it's not possible to combine this into a single output to begin with. Brain fart.

I agree that masking one-hot vectors on a per-class level doesn't make much sense.

**Comment by tomlue** [comment]
EdeMeijer it appears that what you are describing is done by this group https://arxiv.org/pdf/1502.02072.pdf. Could you describe why multitask learning with multiple classification tasks can't benefit from non-uniform masking?

**Comment by AlexDBlack** [comment]
@tomlue Please don't go posting on issues that have been closed for nearly 18 months now
You're unlikely to get a response.
Furthermore seems you're confusing masking types - per-example masking is fine. Per-output masking for non-binary multi-class doesn't make sense.
If you have a feature request or question - better to ask here - https://gitter.im/deeplearning4j/deeplearning4j
