### ISSUE TITLE
plotVocab(calculation); stuck?      

### ISSUE THREAD

**Issue by nouramoubayed** [deeplearning4j/deeplearning4j#188]
Hi, 

after fixing the NullPointerException in Word2VecTests.java file, the run gets stuck at the following line
vec.lookupTable().plotVocab(calculation); 
it has been running for 24 hours now, is that normal?  
thanks

**Comment by agibsonccc** [comment]
Redirect the discussion here:
https://github.com/deeplearning4j/deeplearning4j/issues/151
