### ISSUE TITLE
MultiLayernetwork and ComputationGraph update()

### ISSUE THREAD

**Issue by rubenfiszel** [deeplearning4j/deeplearning4j#1882]
Update a Neural Net from its gradient.

Current function update(Gradient gradient) is currently UnsupportedException

**Comment by nyghtowl** [comment]
@rubenfiszel Are you looking for this to update just the gradients or the params? We have it built out so update(Gradient) in base layer updates the params but my hunch is you just want it to update gradients.

**Comment by rubenfiszel** [comment]
I wanted to update the params with each update. If there was a way to
update the gradient that would be even better but I can make it work with
the former.

**Comment by nyghtowl** [comment]
fix #1949
