### ISSUE TITLE
CNN + WordVectors = Serious Performance Problems

### ISSUE THREAD

**Issue by astier** [deeplearning4j/deeplearning4j#1884]
Hi,

I mentioned this issue also briefly here: https://github.com/deeplearning4j/deeplearning4j/issues/1850
Now I search for a workaround to get better training performance. Because right now it seems to me like the implementation of the ConvNet isn't optimized to work with wordvectors.

WHAT I DO

I build a ConvNet to classify the sentiment of tweets (positive, negative, neutral) by using wordvectors to represent the words. The wordvectors are aligned in the depth (50 dimensions). The tweet/words in the width (30 words). Therefore every tweet-matrix is 30x50. Because ConvNets expect an 3rd dimension I create one artificially so the matrix is 1x30x50. Logically it's the same like 30x55 but I still have to create the 3rd dimension otherwise I get exceptions. But thats not the problem.

PROBLEM

I want to iterate with a filter e.g. over 4 words. Unfortunately only filter sizes are allowed where width==height otherwise I get Exceptions like:

`Exception in thread "main" java.lang.IllegalStateException: Column of left array 8700 != rows of right 3100 or rows of left array 20 != columns of right 3`

So I have to create a filter of the size 4x4 to iterate over 4 words. But my matrix is only 1x30x55. My solution is: Add artificial rows to the matrix filled with zeros so it fits the height of the filter. The matrix is now 4x30x50. If I want to iterate over more words like 10 I would have to create a 10x30x50 matrix where 9 rows are filled with zeros. This are 9x30x50=13500 unnecessary weights.

SUGGESTION

If I do something wrong then please help. Otherwise it would be very useful if you could fix the problem that the filters have always to be an square. I need filters with size 1xn where n>1.

EDIT: Forget the padding part I had before.

Thanks!

**Comment by treo** [comment]
This looks like you are doing something wrong. From the point of view of the CNN implementation it doesn't care whether you are feeding it a grayscale picture or a word vector matrix. And gray scale pictures work just fine.

Going by the code you have in #1850, I guess that you don't actually load the data into the expected format. If I recall correctly (I'm not using CNN's myself a lot), it is supposed to be of shape 1x1500 (1 example, 1500 features = 50x30), and then you tell ConvolutionLayerSetup the actual shape of the matrix so it can setup all the necessary additional steps.

**Comment by astier** [comment]
So is it possible to build filters with the size mxn where m!=n? Lets assume I have 50x30. Now I still want to iterate with a filter over 10 words. Therefore I need a filter like 50x10. But then again I will get an Exception because I can not build filters where width != height or not?

**Comment by astier** [comment]
Another problem is when making an 50x30 matrix for a tweet is the way the next Conv-Layer would transform it. Lets assume I create 10 filters each 50x10 . The Conv-Layer would take the tweet-matrix 50x30 and would spit out a matrix of 1x21x10. If I want now to iterate in the next layer again with a filter over 10 words I would need a filter like 1x10. But like I said it before I can not do it because the ConvNet would throw an exception.

![cnn_transformation](https://cloud.githubusercontent.com/assets/4218786/17133601/119d9180-5327-11e6-8d24-42233c31f128.png)
