### ISSUE TITLE
Integrate custom chart with deeplearning4j-ui

### ISSUE THREAD

**Issue by rubenfiszel** [deeplearning4j/deeplearning4j#1885]
My Reinforcement Learning agent produce data (x:Epoch, y:Cumulative reward) that I would like to display on the current ui. 

Currently I use a charting library and push each new data point to it. How to integrate with deeplearning4j-ui ?

**Comment by raver119** [comment]
Great. Will you be able to use abstraction like IterationListener?

**Comment by raver119** [comment]
I mean - i should wrap REST interface to some abstraction. Will something like iterationListener enough? Or you need just simple method(x, y) and URL where it'll be rendered?

**Comment by rubenfiszel** [comment]
Yes

Ruben Fiszel

2016-07-26 8:24 GMT-07:00 raver119 <notifications@github.com>:

**Comment by raver119** [comment]
Ok, hold on there.

**Comment by AlexDBlack** [comment]
Btw, if you want quick and dirty charting via a static HTML page:

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-ui-parent/deeplearning4j-ui-components/src/main/java/org/deeplearning4j/ui/standalone/StaticPageUtil.java
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-ui-parent/deeplearning4j-ui-components/src/test/java/org/deeplearning4j/ui/TestStandAlone.java

That's non-interactive so isn't exactly what you need. Just mentioning it as an FYI.
