### ISSUE TITLE
EMR with dl4j

### ISSUE THREAD

**Issue by japhar81** [deeplearning4j/deeplearning4j#1887]
Opening this for discussion -- going to endeavor to figure this out and document the process..

**Comment by AlexDBlack** [comment]
Plan here is to set up a spark cluster and run learning on it, essentially?

**Comment by japhar81** [comment]
thats the general idea 👍

**Comment by AlexDBlack** [comment]
Cool. Yeah, getting some proper spark documentation up has been on my radar for a while. This is definitely something we need.

**Comment by huitseeker** [comment]
This should help: https://github.com/deeplearning4j/dl4j-examples/pull/424 Mind having a look, @japhar81 ?

**Comment by agibsonccc** [comment]
http://deeplearning4j.org/spark got updated recently
