### ISSUE TITLE
Score at iteration X is Nan for every iteration if any input or output is homogeneous

### ISSUE THREAD

**Issue by danielr2e** [deeplearning4j/deeplearning4j#1890]
Tested with the iris.txt example - open excel and change one column to have all the same values. Training will no longer work (score is always NaN). Change a single cell to a different value, training works again.

**Comment by raver119** [comment]
It looks like issue is within NormalizerStandardize()

**Comment by eraly** [comment]
@danielr2e I cannot reproduce this. The code should not give nan's even with constant values.
There is a test that passes:
https://github.com/deeplearning4j/nd4j/blob/cf3664e61ee547710ef56ba3ddb907ca74c8fef3/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/dataset/NormalizerStandardizeTest.java#L220

I cannot reproduce this. Post your pom please?

**Comment by danielr2e** [comment]
Ah, actually I'm using the Scala port of CSVExample, which is supposedly identical but appears to do normalization in a different way:  

https://github.com/kogecoo/dl4j-0.4-examples-scala/blob/master/src/main/scala/org/deeplearning4j/examples/misc/csv/CSVExample.scala

I'm also using SBT, not maven, here are the SBT entries relevant to DL4J:

  "org.deeplearning4j" % "deeplearning4j-core" % "0.4-rc3.10",
  "org.nd4j" % "nd4j-native" % "0.4-rc3.10" % "runtime" classifier "" classifier "macosx-x86_64",
  "org.nd4j" % "nd4j-native" % "0.4-rc3.10" % "runtime" classifier "" classifier "linux-x86_64",
  "org.bytedeco" % "javacpp" % "1.2.2",

**Comment by eraly** [comment]
Yeah. That is outdates code that is being deprecated.  Can you use the new api for normalization? It is available in 3.10. 

https://github.com/deeplearning4j/dl4j-0.4-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/dataExamples/CSVExample.java

Please open another issue if you find problems with that.

**Comment by saudet** [comment]
But we should still be updating the scala examples though...

**Comment by ChenJiaoyan** [comment]
I use the new api for normalization in https://github.com/deeplearning4j/dl4j-0.4-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/dataExamples/CSVExample.java, but the problem still exists.

**Comment by agibsonccc** [comment]
@ChenJiaoyan This problem is from July. Could you come in to gitter please? I am closing further comments on this because this has nothing to do with your problem. I replied to you on twitter as well.
