### ISSUE TITLE
Update all tests to new DataVec functionality

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1893]
Currently, there are still some tests using older Canova functionality (canova RecordReaderDataSetIterator, etc). These need to be updated to the newer DataVec equivalents.

**Comment by huitseeker** [comment]
I see nothing left:
```
huitseeker@sleipnir➜huitseeker/DL4J/DataVec(master✗)» ag RecordReaderDataSetIterator
huitseeker@sleipnir➜huitseeker/DL4J/DataVec(master✗)»                 [6:16:18]
```
Is this still valid @AlexDBlack  ?
