### ISSUE TITLE
Intermittent unit test failure: AsyncDataSetIteratorTest.hasNext1

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1894]
Out of around 10 runs, 2 failures:
![image](https://cloud.githubusercontent.com/assets/2360237/17164747/85478040-540e-11e6-931c-a00b832eb98c.png)
![image](https://cloud.githubusercontent.com/assets/2360237/17164771/aae78052-540e-11e6-8bd2-c89d2bd0b183.png)

**Comment by raver119** [comment]
That was possible only in test that has 0 load between fetches. Fixed now, though.
