### ISSUE TITLE
ExistingDataSetIterator (+ others): not safe with preprocessors & multiple epochs

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1898]
Preprocessing is being applied multiple times.
It should be applied only once (first epoch only, and result stored) OR should be applied to a copy.

```java
    public static void main(String[] args){
        DataSetIterator iris = new IrisDataSetIterator(1,150);
        NormalizerStandardize norm = new NormalizerStandardize();
        norm.fit(iris);
        iris.reset();
        List<DataSet> list = new ArrayList<>();
        while(iris.hasNext()) list.add(iris.next());
        Collections.shuffle(list, new Random(12345));

        iris = new ExistingDataSetIterator(list);
        iris.setPreProcessor(norm);

        for( int i=0; i<10; i++ ){
            iris.reset();
            while(iris.hasNext()){
                System.out.println(iris.next().getFeatureMatrix());
            }
            System.out.println("-------------------");
        }
    }
```

First epoch:
[1.28, 0.34, 1.10, 1.45]
[0.80, -0.12, 0.99, 0.79]
[-1.87, -0.12, -1.51, -1.44]
...

Second epoch:
[-5.53, -6.29, -1.51, 0.33]
[-6.12, -7.36, -1.57, -0.54]
[-9.35, -7.36, -3.00, -3.47]
...

Tenth epoch:
[-147.64, -9,581.91, -4.92, -36.76]
[-150.37, -10,462.19, -4.92, -44.48]
[-165.37, -10,462.19, -4.93, -70.70]
...

**Comment by raver119** [comment]
So basically only one concept affected: where iterator is created for existing in-memory dataset source.
In all other cases, where iterator retrieves datasets from any persistent storage - it's not an issue.

**Comment by raver119** [comment]
As discussed earlier, temporary fix applied: we mark dataSets as preprocessed, and skip them. As i see only 3 iterators affected right now: Existing iterator, IteratorIterator, and List iterator. All 3 were updated to honor that mark.

Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/1855
