### ISSUE TITLE
Skip-layers DL4J

### ISSUE THREAD

**Issue by Alex-Cosma** [deeplearning4j/deeplearning4j#1899]
Greetings!

I am currently implementing [NEAT](http://nn.cs.utexas.edu/downloads/papers/stanley.ec02.pdf) in Java 8 using some new fancy constructs as most implementations are rather old.  
Basically, the approach evolves networks on a genetic algorithm. Those networks can look like [this](http://prntscr.com/by64n8) so basically, from what I understand, because the neuron connections can skip layers, it is a skip-layer or recurrent neural network.
As an input for DL4J I would have a list of connections for each neurons. They are marked as input, hidden or output. My question is, is there any way I can simply create a basic feed-forward (no backprop) network based on those connections? 
I have managed to build if I added some constraints as to form only consecutive layer connections. That was easy and it worked just fine, however I couldn't for the life of me find any way in which to do the skip-layers part because, well, when loading the parameter-weights, they are always loaded for consecutive layers. So, this code:

```
    public Network(List<INDArray> synapseWeights) {
        net = buildNetwork(synapseWeights);
        net.init();

        Layer[] layers = net.getLayers();
        for (int i = 0; i < layers.length; i++) {
            Layer layer = layers[i];
            layer.setParam("W", synapseWeights.get(i));
        }
    }
```

works just fine and I am able to really nicely construct the network but **without** skip-layers. The `synapseWeights` list contains an ordered between-layer list of weights. Of course, for a skip-neuron network it would look somewhat different.

Thank you for making such a lovely project open source and have a wonderful day!

**Comment by AlexDBlack** [comment]
This is possible with ComputationGraph.

**Comment by cowwoc** [comment]
@Alex-Cosma Please let me know if you've managed to implement NEAT on top of DL4J. I'm interested in trying it out.

**Comment by Alex-Cosma** [comment]
@cowwoc here you go! tell me if you need help https://bitbucket.org/Alex-Cosma/j8neat/
