### ISSUE TITLE
"o.d.o.l.ScoreIterationListener - Score at iteration ____ is NaN" when training on GPU's with Cuda

### ISSUE THREAD

**Issue by justineyster** [deeplearning4j/deeplearning4j#1907]
Getting a "Score at iteration ____ is NaN" message when training a CNN on GPU's/Cuda on the latest version of dl4j. Was told to open an issue by Alex Black when I brought this up in the gitter. Note that if I just change the dl4j backend to native-dl4j, everything runs completely fine and this issue does not occur with all else equal. Everything you need to see should be in this gist: https://gist.github.com/justineyster/1f10745c957dfd7d8f7bbee70255920b

**Comment by raver119** [comment]
What os and gpu you have there?

**Comment by raver119** [comment]
and there's no error messages or something like that? exceptions? CUDA errors?

**Comment by justineyster** [comment]
Right. No exceptions or CUDA errors.

**Comment by raver119** [comment]
I want to reproduce your issue on my hardware. Please provide some more details:
- number of images per class
- image format (doubt that matters, though)
- CNNConfiguration source

Currently i suspect some kind overflow at reductions, or something like that. But don't see any options besides full reproduction :(

**Comment by raver119** [comment]
And one more question:

Could you please run LenetMnistExample on the same box, using CUDA, and post its results?

**Comment by justineyster** [comment]
Right. Here's the info:

- Number of images per class: ~5,000 x 5 classes

- Image format: .jpg or .JPG

- CNN configuration source: code is already in the gitter. Custom. Loosely based on Alexnet. See the file named "Source Code" in the gitter. Lines 59-61 provide the breakdown on the values we're using to train.

Will run LenetMnistExample now and post results to the gitter.

**Comment by raver119** [comment]
Thanks for the details, that's helpful.

Any results for LenetMnistExample available?

**Comment by raver119** [comment]
So, i've grabbed your source code, and Caltech102 dataset. Got 5 categories, 200 images per category.
Here's training results:

https://gist.github.com/raver119/4dc3d428ce7ba105838ea84148df4480

Results are pretty equal for both CPU and CUDA.
Memory use during traing 4.7GB - 6GB.

**Comment by raver119** [comment]
The only modification i've added to your source code, is resize transformer applied, since i had not 200x200 images available. So images were resized on the fly using DataVec.

**Comment by raver119** [comment]
So, waiting for your response about LenetMnist example. Issue is definitey not reproducible for me.

**Comment by raver119** [comment]
Also, i've checked this configuration against FLOAT and HALF dataType - everything works as intended. However, i'm unable to test on DOUBLES, just don't have enough gpu ram.

**Comment by raver119** [comment]
I've managed to reproduce something that looks like your issue, not sure if that's it though, since i don't see any special CUDA configuration options in your sources. But maybe that's tesla, or ppc or whatever.

Anyway, i'm working on it now.
Thanks for flagging this issue.

**Comment by raver119** [comment]
As temporary workaround please try this configuration:

CudaEnvironment.getInstance().getConfiguration()
            .allowMultiGPU(false)
            .setMaximumGridSize(512)
            .setMaximumBlockSize(512)
            .setMaximumDeviceCacheableLength(1024 * 1024 * 1024L)
            .setMaximumDeviceCache(6L * 1024 * 1024 * 1024L)
            .setMaximumHostCacheableLength(1024 * 1024 * 1024L)
            .setVerbose(false)
            .enableDebug(true);


Add this as first line in main() method.

**Comment by raver119** [comment]
Hypothetically your issue is fixed here: https://github.com/deeplearning4j/nd4j/pull/1167

Tomorrow we'll have release day, so we'll find out if that helps you as well as me.

**Comment by justineyster** [comment]
Right. Thank you very much for working on this issue. I added the LenetMnistExample output, in case you still wanted to take a look. It completed successfully but with some errors printed out at the end. Again, thanks for the support.

**Comment by raver119** [comment]
Release is available now. Let me know if your issue is fixed now.

**Comment by justineyster** [comment]
The fix worked! Thank you very much for your involvement in DL4J. You're incredible valuable to this community @raver119.
