### ISSUE TITLE
NotStrictlyPositiveException caused by NeuralNetConfiguration.Builder

### ISSUE THREAD

**Issue by carschno** [deeplearning4j/deeplearning4j#192]
In the class `NeuralNetConfiguration#Builder`, the call `Nd4j.getDistributions().createNormal(1,0)` (line 960) causes a `NotStrictlyPositiveException` because the 2nd parameter (std dev) has to be positive rather than 0.

**Comment by agibsonccc** [comment]
Pushed up my latest changes. I fixed that last night and forgot about it.
