### ISSUE TITLE
Error 4 when using GPU

### ISSUE THREAD

**Issue by Jydago** [deeplearning4j/deeplearning4j#1923]
Getting this error when trying to train a conv net using GPU
https://gist.github.com/Jydago/cb1f24d73b3cd00c81210009d0a80506

It works when using CPU. I am working on Windows 10, using IntelliJ with scala version 2.11.8, Cuda version 7.5.17, dl4j and nd4j version 0.4.0, canova 0.0.0.17.
My computer has a Geforce GTX 950M GPU.

And here is a snippet of the code that I use
https://gist.github.com/Jydago/1e2a2a958a1338deb4cd28eb585162bc

**Comment by raver119** [comment]
Please add this line: CudaEnvironment.getInstance().getConfiguration().enableDebug(true).setVerbose(true);

As first line of your app, run it again, and send NEW full output log.

**Comment by Jydago** [comment]
Here is the new output, though I couldn't copy the full output, as the cmd window couldn't fit it all.
https://gist.github.com/Jydago/a2e1b65cdfb564fe2997556417d4a1b1

**Comment by raver119** [comment]
bsi_cnn[ERROR] Exception in thread "main" java.lang.IllegalArgumentException: Unable to split on size equal or larger than the number of rows (# numExamples=128, numHoldout=10240)

Fix this issue first please

**Comment by Jydago** [comment]
Ops, sorry, made a minor change in code. Fixed it now and updated the gist

**Comment by Jydago** [comment]
I have found out that if I train the network using only 2 as batch size, I can run the code.

**Comment by raver119** [comment]
Where's your network configuration? Can i have it too?

**Comment by Jydago** [comment]
I have written some wrappers for the various layers, so the configurations are in a seperate file from the actual network builder.
https://gist.github.com/Jydago/a252075e2510502576609ce1117c534c

**Comment by raver119** [comment]
@Jydago you're building from sources these days, can you please tell me if this issue is viable for current master or mGRID branch (which is better), and provide me with recent output?

**Comment by agibsonccc** [comment]
Closed due to inactivity.
