### ISSUE TITLE
Computation Graph doesn't calculate nIns

### ISSUE THREAD

**Issue by andreas-eberle** [deeplearning4j/deeplearning4j#1934]
As requested by @nyghtowl, I open this issue following the discussion on gitter.

I tried to run the GoogLeNet example configuration. After fixing some configuration problems, I ran into the issue that the nIns aren't calculated properly although I added the `.setInputTypes(InputType...)` as described in http://deeplearning4j.org/compgraph. 

I get the following error: https://gist.github.com/andreas-eberle/22725bed3baa59e2c6542a7121d8d68e

**Comment by nyghtowl** [comment]
Information to help debug:

the input/output handled here:
https://github.com/deeplearning4j/deeplearning4j/blob/68cf60609fbd9df0d3d432138672487cb5d7bdb0/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/conf/graph/LayerVertex.java#L95

preprocessors in the LayerVertex implementation: https://github.com/deeplearning4j/deeplearning4j/blob/68cf60609fbd9df0d3d432138672487cb5d7bdb0/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/graph/vertex/impl/LayerVertex.java#L42


ComputationGraphConfiguration.addPreProcessors does the actual calculations and adding:
https://github.com/deeplearning4j/deeplearning4j/blob/de295755f85e4ad00089e6b00607fc2e6c679b51/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/conf/ComputationGraphConfiguration.java#L263

**Comment by AlexDBlack** [comment]
Thanks for reporting this.
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/1944
