### ISSUE TITLE
Gitter Widget on deeplearning4j.org is partially overlapped by navbar

### ISSUE THREAD

**Issue by morriswinkler** [deeplearning4j/deeplearning4j#1938]
The widget has two buttons ( upper right corner) to eider pop out the widget to a new tab or close it. Both this buttons do not work since the main navbar overlaps the widget.

![screen shot 2016-08-04 at 11 27 14](https://cloud.githubusercontent.com/assets/4302527/17397458/7affea5c-5a38-11e6-8f8c-6fcb037f36d7.png)

**Comment by agibsonccc** [comment]
Could you post this to the main gitter repo? https://github.com/gitterHQ/gitter ?

**Comment by morriswinkler** [comment]
Are you sure that this is a gitter problem ? Could you also explain why.
