### ISSUE TITLE
Missmatch of MergeVertex inputs is not detected on build (ComputationGraph)

### ISSUE THREAD

**Issue by andreas-eberle** [deeplearning4j/deeplearning4j#1939]
I have build a network with Computation Graph (with the intention to build GoogLeNet). Due to a missconfiguration the following exception was thrown during training:

https://gist.github.com/andreas-eberle/8cf897d5de94108e71d2694e9ed20217

After I debugged the code, I found that there was an error in my configuration. However, the misconfiguration was not detected on the .build() call (which I would have expected).  

I created a smaller example that reproduces the problem:
https://gist.github.com/andreas-eberle/2cf7293767d251802b891c4a05fdafa8

In lines 89 to 91, the wrong input is specified. It should be "max11" instead of "cnn4". The result is that the merge node gets three inputs with size 10x10 and one with size 5x5 (when feeding the network with initial images of size 40x40).

I think this misconfiguration should be detected when building the network, instead of during runtime. 

I'm using version 0.5.0.

**Comment by AlexDBlack** [comment]
So, I looked into this. If I add the following line to your config, I get an exception:
.setInputTypes(InputType.convolutional(40,40,1));
```
Exception in thread "main" org.deeplearning4j.nn.conf.inputs.InvalidInputTypeException: Invalid input: MergeVertex cannot merge CNN activations of different width/heights:first [depth,width,height] = [256,10,10], input 3 = [128,5,5]
```
That's basically what I expected to happen.

So it's only going to check those inputs if you use the inputTyes functionality. I don't believe it's possible/practical to detect that sort of mis-configuration without providing that input size information to the network. (Unless you have any ideas how to check that?)

**Comment by andreas-eberle** [comment]
Thanks!
