### ISSUE TITLE
Mismatch during backpropagation with CompuationGraph

### ISSUE THREAD

**Issue by andreas-eberle** [deeplearning4j/deeplearning4j#1940]
While trying to build up GoogLeNet, I received the following exception during training:

https://gist.github.com/andreas-eberle/7130e8a6dd0be4a66fce1d1e42e04057

It looks like the forward step was done successfully without any mismatch. However, the backward propagation then crashes with a mismatch. 

I created a smaller version of my configuration that reproduces the issue:

https://gist.github.com/andreas-eberle/907ff706c713960fd412737c2512fb5b

As input I used images of size 40x40 with one grayscale channel. The dl4j version is 0.5.0.

**Comment by AlexDBlack** [comment]
Still looking into this.
FYI unfortunately I did find a separate bug affecting computation graphs with subsampling layers: https://github.com/deeplearning4j/deeplearning4j/pull/1944

**Comment by AlexDBlack** [comment]
OK, so as mentioned in gitter: was getting a crash.
Turns out your net is misconfigured + lack of input validation causing the crash in native code: https://github.com/deeplearning4j/nd4j/issues/1187

Input depth is misconfigured at line 85.

**Comment by andreas-eberle** [comment]
Thx, I just found a second misconfiguration in line 103. The number of inputs should be 192.

**Comment by andreas-eberle** [comment]
After I fixed the last error in line 104 (inputs should be 48), it worked. Therefore I'm closing this ticket.
