### ISSUE TITLE
Misleading GettingStarted guide

### ISSUE THREAD

**Issue by subsilico** [deeplearning4j/deeplearning4j#1941]
This page: http://deeplearning4j.org/gettingstarted.html makes is seem that https://github.com/deeplearning4j/libnd4j should be followed when installing dl4j. This can lead to windows users trying to use https://github.com/deeplearning4j/libnd4j/blob/master/windows.md. This leads to many headaches for them.

The gettingstarted should reflect that users need only use maven and not build their own.

**Comment by tomthetrainer** [comment]
Added note to that page to refer to the more complete buildinglocally page.
