### ISSUE TITLE
NullPointerException in MultiLayerNetwork.java

### ISSUE THREAD

**Issue by carschno** [deeplearning4j/deeplearning4j#195]
In line 357 of `MultiLayerNetwork.java`, the call `layerWiseConfigurations.getConf(i).getLayerFactory()` yields null, resulting in a NullPointerException. I experience this when running the reconstruct/DBNExample in deeplearning4j-examples:
> Exception in thread "main" java.lang.NullPointerException
>	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:357)
>	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.initializeLayers(MultiLayerNetwork.java:323)
>	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.setInput(MultiLayerNetwork.java:1384)
>	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:155)
>	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1023)
>	at org.deeplearning4j.reconstruct.DBNExample.main(DBNExample.java:47)

**Comment by carschno** [comment]
The same happens when running `OtherExamples.java`, btw:
> Exception in thread "main" java.lang.NullPointerException
>	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.init(MultiLayerNetwork.java:357)
>	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.initializeLayers(MultiLayerNetwork.java:323)
>	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.setInput(MultiLayerNetwork.java:1384)
>	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:201)
>	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1138)
>	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1173)
>	at org.deeplearning4j.OtherExample.main(OtherExample.java:53)

**Comment by agibsonccc** [comment]
Fixed. Added the LayerFactory declaration to the builder.
