### ISSUE TITLE
INDArray serialization EOFException in 0.5.0

### ISSUE THREAD

**Issue by Treiblesschorle** [deeplearning4j/deeplearning4j#1950]
After writing a INDArray, a EOFException is thrown when reading the array.
Here is code to reproduce:
https://gist.github.com/Treiblesschorle/7106288afd02a030f36b6f292912086d
The same code works with 0.4-rc3.10.

If the ZipOutputStream is additionally wrapped in a DataOutputStream during writing it works.

**Comment by raver119** [comment]
You're using outdated write call. Please consider using this one meanwhile: https://github.com/deeplearning4j/nd4j/blob/6f8438869e310a0f1e7cb8f832e5e2a47cf4712f/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java#L2277-L2277

**Comment by raver119** [comment]
Fixed and merged: https://github.com/deeplearning4j/nd4j/pull/1191

Thanks for finding it.
