### ISSUE TITLE
Optimize Evaluation (and RegressionEvaluation)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#1964]
https://github.com/deeplearning4j/deeplearning4j/blob/0dbd47dec3ba85476305d9e64267d90457d83850/deeplearning4j-core/src/main/java/org/deeplearning4j/eval/Evaluation.java

getRow and argmax operations should be done batch-wise, instead of for each row in a loop.

**Comment by agibsonccc** [comment]
This happened.
