### ISSUE TITLE
core should not compile-depend on logging framework

### ISSUE THREAD

**Issue by reckart** [deeplearning4j/deeplearning4j#1968]
A library should not compile-depend on logging framework. DL4J-core is coded against slf4j-api, but still has a compile dependency on logback-classic and logback-core. These dependencies should be removed or switch to scope "test" if they are required for testing. Having these dependencies as compile-time dependencies requires downstream users to explicitly exclude them if they want to use another logging backend with slf4j.

**Comment by reckart** [comment]
This is related because dsiutils is a dependency of DL4J: https://github.com/vigna/DSI-Utilities/issues/2

**Comment by saudet** [comment]
Switching their scope to test sounds good. Could you send a PR for that and dsiutils? I guess we should also show users how to readd those log dependencies in dl4j-examples...

**Comment by reckart** [comment]
I am reporting this issue after chatting with @agibsonccc. I am also subject to time constraints, so we agreed to at least record the issues as not to forget them. Another problem is that setting up a build environment for DL4J is not trivial. I cannot build the required projects. If you could fix that to  enable checking out the code and simply run a "mvn clean install", that would certainly help.

You likely have the environment already set up. The change is trivial.

**Comment by agibsonccc** [comment]
Fixed a while back.
