### ISSUE TITLE
Move image-related stuff out of core

### ISSUE THREAD

**Issue by reckart** [deeplearning4j/deeplearning4j#1969]
Move image-related stuff out of core. The core dependency on datavec-data-image pulls in many dependencies that are generally not needed, e.g. dependencies on various image processing libraries, even ffmpeg.

**Comment by saudet** [comment]
Again, please send a PR to clarify how you see this organized and also try to update dl4j-examples, if possible, so we can see how this is going to look like for an end user.

**Comment by agibsonccc** [comment]
I told him to do this actually. I'd be willing to sit down and do this
actually. I had attempted this before but lost it due to time constraints.
This will make it easier.

**Comment by reckart** [comment]
Well, I can tell you what I am currently doing - I am excluding the respective dependencies:

```
<dependency>
      <groupId>org.deeplearning4j</groupId>
      <artifactId>deeplearning4j-core</artifactId>
      <version>${dl4j.version}</version>
      <exclusions>
        <!-- Image stuff not needed -->
        <exclusion>
          <groupId>org.nd4j</groupId>
          <artifactId>canova-nd4j-image</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.datavec</groupId>
          <artifactId>datavec-data-image</artifactId>
        </exclusion>
        <!-- UI stuff not needed -->
        <exclusion>
          <groupId>org.freemarker</groupId>
          <artifactId>freemarker</artifactId>
        </exclusion>
        <!-- Using another logging backend, this only causes conflicts -->
        <exclusion>
          <groupId>ch.qos.logback</groupId>
          <artifactId>logback-classic</artifactId>
        </exclusion>
        <exclusion>
          <groupId>ch.qos.logback</groupId>
          <artifactId>logback-core</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

**Comment by agibsonccc** [comment]
Closing due to large scale refactoring. deeplearning4j-nn is now our main dsl and has been refactoreed out of core.
