### ISSUE TITLE
Move dropwizard stuff out of dl4j-nlp

### ISSUE THREAD

**Issue by reckart** [deeplearning4j/deeplearning4j#1970]
The dl4j-nlp module has dependencies on dropwizard which is not really needed for the core NLP functionality. This should be moved into a dl4j-nlp-ui module to significantly reduce the set of transitive dependencies of dl4j-nlp.

**Comment by saudet** [comment]
Sounds good I think. Do you have a concrete PR that we can run and test?

**Comment by reckart** [comment]
Nope. Currently, I just exclude these dependencies in my project. I am reporting this issue after chatting with @agibsonccc so it does not get forgotten.

**Comment by agibsonccc** [comment]
Yeah that's fine. Sorry for the confusion! This will be a great place to
get to work actually.

**Comment by agibsonccc** [comment]
Can't do this without some extra work. There is some TSNE related stuff in there.

**Comment by agibsonccc** [comment]
We've removed dropwizard completely.
