### ISSUE TITLE
Factor out ClearTK-related stuff from NLP module

### ISSUE THREAD

**Issue by reckart** [deeplearning4j/deeplearning4j#1972]
For basic DL NLP, ClearTK is not required. In fact, having it there can cause dependency conflicts when a user wants to use an alternative NLP preprocessing pipeline. To minimize the dependency footprint of the NLP module, the ClearTK-related code should be moved to a separate module.

**Comment by agibsonccc** [comment]
Finally got around to this. I split the module in to a UIMA module. Closing this.
