### ISSUE TITLE
dsiutils actually required?

### ISSUE THREAD

**Issue by reckart** [deeplearning4j/deeplearning4j#1973]
Searching for `it.unimi.dsi` in the GitHub search on this repo yields only one code hit in the POM of dl4j-nlp. It seems to be unnecessary.

Btw. you can utilize the maven dependency plugin [`analyze`](http://maven.apache.org/plugins/maven-dependency-plugin/analyze-mojo.html) goal to check for unnecessary dependencies.

**Comment by reckart** [comment]
Related to https://github.com/deeplearning4j/deeplearning4j/issues/1968 because dsiutils draws in logback-classic.

**Comment by AlexDBlack** [comment]
Thanks. Removed: https://github.com/deeplearning4j/deeplearning4j/pull/1995
