### ISSUE TITLE
"No CUDA devices were found" on MAC

### ISSUE THREAD

**Issue by jns1** [deeplearning4j/deeplearning4j#1977]
Hej guys I run into problems with Cuda on MAC.
I used the latest https://github.com/deeplearning4j/dl4j-examples as a starting point. (0.5 version)
The native version runs flawless. As soon as I change <nd4j.backend>nd4j-cuda-7.5-platform</nd4j.backend> in the parent pom I run into the described problem.

Here is the stacktrace. https://gist.github.com/jns1/0372e45978d203e7cc8f083834c0de55

I have all cuda drivers installed:
This is what I get on my bash:

**kextstat | grep -i cuda**
208 0 0xffffff7f836aa000 0x2000 0x2000 com.nvidia.CUDA (1.1.0) 5AFE550D-6361-3897-912D-897C13FF6983 <4 1>

**nvcc: NVIDIA (R) Cuda compiler driver**
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Apr_11_13:23:40_CDT_2016
Cuda compilation tools, release 7.5, V7.5.26

**Mac OS:**
w_vers -productVersion
10.11.6

**./deviceQuery gives:** 
Detected 1 CUDA Capable device(s)

Device 0: "GeForce GT 650M"
  CUDA Driver Version / Runtime Version          7.5 / 7.5
  CUDA Capability Major/Minor version number:    3.0
  Total amount of global memory:                 1024 MBytes (1073414144 bytes)
  ( 2) Multiprocessors, (192) CUDA Cores/MP:     384 CUDA Cores
  GPU Max Clock rate:                            900 MHz (0.90 GHz)
  Memory Clock rate:                             2508 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 262144 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

I even went to the energy settings and turned off automatic graphics switching. I still get the same problem. Do you guys have any idea what could be wrong?
I'm also sure that nvcc is present in the path, as I did a System.out.println(System.getenv("PATH")); which confirmed that '/Developer/NVIDIA/CUDA-7.5/bin is in the path'

**Comment by saudet** [comment]
There's known issues with Optimus on both Windows and Mac, unfortunately. It's not clear exactly what the problem is, but on Mac, Homebrew usually does a better job of installing CUDA properly than just the installer from NVIDIA. Have you tried to use Homebrew to install CUDA?

**Comment by jns1** [comment]
I used the standard NVidia installer. I'll try homebrew this evening.

**Comment by raver119** [comment]
Yes please, try uninstall your current CUDA toolkit, and install using nvidia.
Also, after you do it - please show us CUDA version once again.

**Comment by jns1** [comment]
Hej there. I uninstalled the original CUDA drivers and did a brew cask install cuda.
The result is exacty the same

This is what I get: nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Apr_11_13:23:40_CDT_2016
Cuda compilation tools, release 7.5, V7.5.26


kextstat | grep -i cuda
  224    0 0xffffff7f836a7000 0x2000     0x2000     com.nvidia.CUDA (1.1.0) 5AFE550D-6361-3897-912D-897C13FF6983 <4 1>

./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GT 650M"
  CUDA Driver Version / Runtime Version          7.5 / 7.5
  CUDA Capability Major/Minor version number:    3.0
  Total amount of global memory:                 1024 MBytes (1073414144 bytes)
  ( 2) Multiprocessors, (192) CUDA Cores/MP:     384 CUDA Cores
  GPU Max Clock rate:                            900 MHz (0.90 GHz)
  Memory Clock rate:                             2508 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 262144 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

**Comment by raver119** [comment]
Strange, but your CUDA toolkit version wasn't changed:  V7.5.26

**Comment by jns1** [comment]
True.
This is what Brew did: 
==> Creating Caskroom at /usr/local/Caskroom
==> Downloading http://developer.download.nvidia.com/compute/cuda/7.5/Prod/local_installers/cuda_7.5.27_mac.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask cuda
==> Running installer script CUDAMacOSXInstaller.app/Contents/MacOS/CUDAMacOSXInstaller

I checked that /Developer/NVIDIA/CUDA-7.5/bin/nvcc was gone so I think the data must be from brew.  cuda_7.5.27_mac.dmg vs V7.5.26 seems to be fishy tough.

**Comment by jns1** [comment]
I don't know if that helps: This is org.nd4j.jita.conf.Configuration right before the crash.
Is there a way to enable loggin for the C-code?


this	Configuration  (id=27)	
	allocationModel	Configuration$AllocationModel  (id=85)	
		name	"CACHE_ALL" (id=132)	
			hash	0	
			hash32	0	
			value	(id=144)	
		ordinal	2	
	availableDevices	ArrayList<E>  (id=86)	
		elementData	Object[0]  (id=129)	
		modCount	0	
		size	0	
	bannedDevices	ArrayList<E>  (id=89)	
		elementData	Object[0]  (id=129)	
		modCount	0	
		size	0	
	commandLanesNumber	4	
	commandQueueLength	3	
	crossDeviceAccessAllowed	true	
	debug	false	
	debugTriggered	0	
	executionModel	Configuration$ExecutionModel  (id=90)	
		name	"SEQUENTIAL" (id=133)	
			hash	0	
			hash32	0	
			value	(id=140)	
		ordinal	0	
	firstMemory	AllocationStatus  (id=91)	
		name	"DEVICE" (id=134)	
		ordinal	2	
	forceSingleGPU	false	
	gatherStatistics	false	
	gpuAllocAggressiveness	Aggressiveness  (id=93)	
		name	"REASONABLE" (id=97)	
			hash	0	
			hash32	0	
			value	(id=98)	
		ordinal	1	
	gpuDeallocAggressiveness	Aggressiveness  (id=93)	
		name	"REASONABLE" (id=97)	
		ordinal	1	
	hostDeallocAggressiveness	Aggressiveness  (id=93)	
		name	"REASONABLE" (id=97)	
		ordinal	1	
	initialized	AtomicBoolean  (id=95)	
		value	0	
	maximumBlockSize	128	
	maximumDeviceAllocation	4294967296	
	maximumDeviceCache	1073741824	
	maximumDeviceCacheableLength	100663296	
	maximumDeviceMemoryUsed	0.85	
	maximumGridSize	256	
	maximumHostCache	3221225472	
	maximumHostCacheableLength	100663296	
	maximumSingleDeviceAllocation	1073741824	
	maximumSingleHostAllocation	9223372036854775807	
	maximumZeroAllocation	4342153216	
	memoryModel	Configuration$MemoryModel  (id=114)	
	minimumRelocationThreshold	5	
	minimumTTLMilliseconds	10000	
	nativeOps	NativeOps  (id=102)	
	numberOfGcThreads	6	
	poolSize	32	
	preallocationCalls	10	
	usePreallocation	true	
	verbose	false	
	zeroCopyFallbackAllowed	false

**Comment by raver119** [comment]
In your particular case there's nothing to log. CUDA driver says you have 0 available CUDA devices. Just nothing to log or debug. It sounds like either nvidia optimus/maximus bug with contexts (happens on laptops sometimes) or binary incompatibility bug. But i'd vote for first option.
