### ISSUE TITLE
Word2Vec is stuck with o.d.b.v.BaseTextVectorizer - latch count 308045 with queued 309256 

### ISSUE THREAD

**Issue by naveen-tirupattur** [deeplearning4j/deeplearning4j#198]
I am trying to create word vector using dl4j and I see my code is stuck with following log message:

o.d.b.v.BaseTextVectorizer - latch count 308045 with queued 309256
o.d.b.v.BaseTextVectorizer - latch count 308045 with queued 309256
o.d.b.v.BaseTextVectorizer - latch count 308045 with queued 309256
o.d.b.v.BaseTextVectorizer - latch count 308045 with queued 309256

I removed all the white spaces from my documents and I am running this on my macbook with yosemite and 8g RAM.

**Comment by tmbo** [comment]
I got the same issue also on Yosemite / 8gb.

**Comment by agibsonccc** [comment]
Is this for 3.2.x? 3.3 doesn't have this problem.

**Comment by naveen-tirupattur** [comment]
This is with 3.3.2.

<properties>
        <nd4j.version>0.0.3.5.5.2</nd4j.version>
        <dl4j.version>0.0.3.3.2.alpha1</dl4j.version>
    </properties>

**Comment by naveen-tirupattur** [comment]
I figured out the problem.  The queued counter counts all the sentences and latch counter counts all the processed sentences. Since the empty sentences were not being processed the latch counter is not getting updated. So the code is stuck waiting to for the empty sentences to be processed. I removed the empty sentences from my data and it is working fine now.
