### ISSUE TITLE
App get stuck when trying to open browser for HistogramIterationListener

### ISSUE THREAD

**Issue by pierrebonneau** [deeplearning4j/deeplearning4j#1986]
I'm trying to use the `HistogramIterationListener`, works well with the `AdditionRNN.java` example. When I use it in my application, the URL is correctly produced but it get stuck when it comes to open the browser or a new tab, so the training doesn't go any further (it does without the listener).

[pom.xml](https://gist.github.com/pierrebonneau/3a56d22c930d362539c3d2297718f8e2)

**Comment by raver119** [comment]
Aha. So it sounds like a dependency conflict somewhere in your pom.xml

**Comment by pierrebonneau** [comment]
Hmm :/ Any idea wich one it could be, or how to find it out ?

**Comment by raver119** [comment]
that should be something network-related. httpcomponents, jersey (if present), etc.

So i'd suggest to start checking mvn dependency:tree to check for overrides there
