### ISSUE TITLE
Storing uint8 INDArray (to save space) and normalize them later

### ISSUE THREAD

**Issue by rubenfiszel** [deeplearning4j/deeplearning4j#1989]
As discussed in the gitter.

I'm saving grayscaled images stored as 1 channel uint8 INDArray. To save spaces, I'd like the type of those arrays to be uint8 (4 times less memory usage).

Then when they are used as input of a convolution setup, they should be normalized (eg: divided by 128 then add -1). This can be done easily be a preprocessor.

**Comment by raver119** [comment]
Well, we're going to have multiple storage formats available: FP16, FP8, and uint8. Some kind of neat interface would be required for uniform conversions between them and processing formats: FP16, FP32, FP64.

**Comment by raver119** [comment]
So, approximate plan is:
- Single API entry point for compression/decompression over arrays
- Extensible interface, suited for multiple possible conversion formats
- Reflection to scan classpath for available compressors/decompressors

**Comment by raver119** [comment]
Implemented long ago.
