### ISSUE TITLE
VideoClassificationExample doesn't work - cudnn error

### ISSUE THREAD

**Issue by jfolt** [deeplearning4j/deeplearning4j#1991]
I get this on Windows 8.1. LenetMnistExample works fine.

Number of parameters in network: 56844
Layer 0 nParams = 9030
Layer 1 nParams = 0
Layer 2 nParams = 2710
Layer 3 nParams = 24550
Layer 4 nParams = 20350
Layer 5 nParams = 204
Starting training...
Exception in thread "main" java.lang.RuntimeException: cuDNN status = 9
    at org.deeplearning4j.nn.layers.convolution.CudnnConvolutionHelper.checkCudnn(CudnnConvolutionHelper.java:57)
    at org.deeplearning4j.nn.layers.convolution.CudnnConvolutionHelper.backpropGradient(CudnnConvolutionHelper.java:199)
    at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.backpropGradient(ConvolutionLayer.java:128)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.truncatedBPTTGradient(MultiLayerNetwork.java:1279)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1805)
    at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:152)
    at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:54)
    at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doTruncatedBPTT(MultiLayerNetwork.java:1215)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1477)
    at org.deeplearning4j.examples.recurrent.video.VideoClassificationExample.main(VideoClassificationExample.java:158)

**Comment by jfolt** [comment]
I downloaded examples on August 6.

**Comment by saudet** [comment]
It works just fine on my machine (Fedora 23) with cuDNN 5:
```
Number of parameters in network: 56844
Layer 0 nParams = 9030
Layer 1 nParams = 0
Layer 2 nParams = 2710
Layer 3 nParams = 24550
Layer 4 nParams = 20350
Layer 5 nParams = 204
Starting training...
o.d.o.l.ScoreIterationListener - Score at iteration 0 is 45.57967941271812
o.d.o.l.ScoreIterationListener - Score at iteration 1 is 41.002512711572926
o.d.o.l.ScoreIterationListener - Score at iteration 2 is 40.58291620575811
o.d.o.l.ScoreIterationListener - Score at iteration 3 is 42.46900015639249
o.d.o.l.ScoreIterationListener - Score at iteration 4 is 41.91443230945931
...
```
Is there anyone else that is able to reproduce this? @AlexDBlack? @raver119?

**Comment by raver119** [comment]
@jfolt what happens if you remove deeplearning4j-cuda-7.5 dependency? Does example work wihout cuDNN?

**Comment by jfolt** [comment]
Yes, without cudnn dependency it trains OK (no errors). Uses very little GPU (1-10%), and 2307MiB memory.

With cudnn it happens every time.

**Comment by jfolt** [comment]
I will take back the GPU usage note. It uses more (up to 100%). But exactly every 5 iterations it freezes for a 20-30 seconds (only then the GPU usage is so small). CPU usage is the same though at any time (20%).

**Comment by jfolt** [comment]
Without cudnn the example trains, but doesn't work in the end (out of GPU memory). I could create another issue for that, but I was hoping using cudnn would resolve that.

Number of parameters in network: 56844
Layer 0 nParams = 9030
Layer 1 nParams = 0
Layer 2 nParams = 2710
Layer 3 nParams = 24550
Layer 4 nParams = 20350
Layer 5 nParams = 204
Starting training...
o.d.o.l.ScoreIterationListener - Score at iteration 0 is 45.588874363687616
o.d.o.l.ScoreIterationListener - Score at iteration 1 is 41.009729106061755
o.d.o.l.ScoreIterationListener - Score at iteration 2 is 40.580339008484444
.....
o.d.o.l.ScoreIterationListener - Score at iteration 223 is 41.458705276524725
o.d.o.l.ScoreIterationListener - Score at iteration 224 is 40.66893257132321
Epoch 0 complete
o.n.j.h.i.CudaZeroHandler - No available [HOST] memory, sleeping for a while...
o.n.j.h.i.CudaZeroHandler - No available [HOST] memory, sleeping for a while...
....
no change from here.

It starts using 2.3G memory and ends with this:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 368.81                 Driver Version: 368.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 960    WDDM  | 0000:01:00.0      On |                  N/A |
|  0%   40C    P8     8W / 160W |   3835MiB /  4096MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by raver119** [comment]
Try switching to HALF datatype. No issues will help you there, since CNN networks are memory intensive, and it's known behavior.

**Comment by jfolt** [comment]
I thought this was an issue because this is your unmodified example. Every example you provide should work (on a reasonable GPU), otherwise it gives a really bad impression especially for people who just start with dl4j.

I will try HALF datatype. Thanks.

**Comment by raver119** [comment]
Reasonable GPU is a vague definition tbh. 

Also, in your particular case it's HOST memory being low too, so something like -Xmx8G won't hurt as i see. CUDA will just switch to host memory if device memory isn't available. But if there's no host memory available - not too much i can do.

**Comment by agibsonccc** [comment]
I'm going to have to step in here. The original example was running fine on the cpu (which is what we were mainly using when this started) I'm going to have disagree that every example should run on a crap gpu though. We can't buy the whole world good gpus here.

Much of that stuff is related to good ETL though. Video IS going to be more intensive. Many people run video compute workloads on titan x's and larger gpus anyways.

I agree that documentation is one thing here which is fine.

The rest of that though is frankly uncalled for though. If there's a problem send us a pull request to improve it. We have limited bandwidth as it is and I have very low tolerance for complaints about something you're getting for free. Keep the comments on topic.

**Comment by jfolt** [comment]
I am not creating those issues to complain!

It may be hard to believe, but the primary intent here is to help you with bugs which you didn't find yet. I really like this project, but have a hard time to convince people in my company who use torch7.

GPU with 4GB memory is definitely not a crap, not yet :-). I will try to increase CPU heap size. Thanks.

**Comment by raver119** [comment]
Don't be offended please, but there's lots of models out there, which can't fit even into 8GB memory. Especially with "proper" input data  :)

All that stuff is really sensitive to available hardware.

**Comment by agibsonccc** [comment]
Right that's fine. I'm just pointing out how this should be done. "This should magically just run on every gpu" vs "We can document what to expect" are very different things though.

As I said we also welcome pull requests.

FWIW: I'm glad you are involved. This project is very much not targeted at that crowd though. Typically the people using lua of all things (at least use python?) aren't usually taking stuff to production. There's a very large enterprise focus.  The "closest" we are getting to that crowd is our scala api which immitates keras:
https://www.slideshare.net/darthmile/dl4j-at-workday-meetup

Anyways - since the conversation is around heap space, I'm closing this. Feel free to ask us questions and support back in the gitter channel. I'm happy to give you more ammo but I'm not expecting to win that crowd anytime soon ;).

**Comment by jfolt** [comment]
Well, the primary purpose of this issue was the cudnn bug, which is still not fixed. I realize it may be too hard to do without a reproduce. But if there is anything I can help with (create logs or run some diagnostics), let me know.

**Comment by raver119** [comment]
Which cuDNN version you have there? Just realized it wasn't asked before

**Comment by jfolt** [comment]
Version 5. It works great with LenetMnistExample and many other things I tried (I never used anything with BPTT though).

**Comment by raver119** [comment]
I wonder, what's NOT_SUPPORTED then...

**Comment by AlexDBlack** [comment]
I ran the video example on Windows 10 with cuda, cudnn and native; fresh clone of the examples (so version 0.5.0 for everything there)
Native runs fine, but I'm getting the following issue on both cuda and cudnn.
The issue looks kinda familiar (to that axpy on different underlying length arrays situation we have discussed), but looking at the line numbers I don't think that should be occuring here. Will need to look into this more though.

https://gist.github.com/AlexDBlack/b8697903d49cc2759ad329f95f503469

**Comment by raver119** [comment]
Hm, but as far as i remember, we've partially lifted restrictions on axpy right before 0.5.0 release

**Comment by AlexDBlack** [comment]
Alright, so looks like I somehow had some old code in my maven repository. After deleting my local maven files and rerunning, the results are as follows:
native and nd4j-cuda-7.5: both work fine
deeplearning4j-cuda-7.5 (i.e., cudnn): same stack trace as @jfolt 
Exception in thread "main" java.lang.RuntimeException: cuDNN status = 9
	at org.deeplearning4j.nn.layers.convolution.CudnnConvolutionHelper.checkCudnn(CudnnConvolutionHelper.java:57)
	at org.deeplearning4j.nn.layers.convolution.CudnnConvolutionHelper.backpropGradient(CudnnConvolutionHelper.java:199)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.backpropGradient(ConvolutionLayer.java:128)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.truncatedBPTTGradient(MultiLayerNetwork.java:1279)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1805)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:152)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:54)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.doTruncatedBPTT(MultiLayerNetwork.java:1215)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1477)
	at org.deeplearning4j.examples.recurrent.video.VideoClassificationExample.main(VideoClassificationExample.java:157)

**Comment by raver119** [comment]
So, in general: it works for @saudet on linux, and fails on windows, with cryptic NOT_SUPPORTED call.

The only thing that comes to mind here, is Nvidia WDDM driver restrictions on large memory allocations, etc.

**Comment by jfolt** [comment]
I changed some options which affect memory usage, but that didn't help. It fails now (the same way) much quicker though :-).

public static final int N_VIDEOS_TO_GENERATE = 10;
public static final int V_NFRAMES = 50;
int miniBatchSize = 2;
Also changed number of filters in the first CNN layer from 30 to 10
(didn't know how to change the video frame size due to some hardcoded values)

**Comment by saudet** [comment]
Well this is odd. It runs just fine in Windows 10 (as well as Fedora 23) on my machine (GeForce GT 640M).

**Comment by agibsonccc** [comment]
I think it's what raver was saying. It's likely the WDDM..
We've ran in to this a lot with windows/CUDA.

**Comment by raver119** [comment]
Hmmm... if it on Sam's Windows 10 on older gpu - it's even more strange then.

Main problem - there's no source code for cuDNN. Nothing to debug :(

**Comment by saudet** [comment]
Is this still happening with CUDA 8.0 and cuDNN 5.1?
