### ISSUE TITLE
IndexOutOfBoundsException with CUDA half precision

### ISSUE THREAD

**Issue by andreas-eberle** [deeplearning4j/deeplearning4j#1993]
When running my configuration with CUDA default precision, it works. However, when I run it with half precision, I get the following error:

https://gist.github.com/andreas-eberle/0992b97fe8062f148344a37f712273ce

This is the configuration I used.

https://gist.github.com/andreas-eberle/64eec96888651dd2543c8bc0ecf3501d

The input I use are 40x40 images with one channel.

**Comment by raver119** [comment]
This issue should be already fixed on current master.
