### ISSUE TITLE
Asynchronous Stochastic Gradient Descent MultiLayerNetwork and ComputationGraph

### ISSUE THREAD

**Issue by rubenfiszel** [deeplearning4j/deeplearning4j#1997]
Enable async gradient descent on MultiLayerNetwork and ComputationGraph.

See: 
[paper 1](https://arxiv.org/abs/1505.04956)
[Hogwild](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=0ahUKEwjboLionbfOAhVJKGMKHeQhB0MQFggyMAI&url=https%3A%2F%2Fwww.eecs.berkeley.edu%2F~brecht%2Fpapers%2FhogwildTR.pdf&usg=AFQjCNE9XrK7aEEQxMC2XkWxXrfyC90y2A&sig2=E-tEQOSf3RoTNbGbfK2uYQ)
[paper 3](https://papers.nips.cc/paper/5751-asynchronous-parallel-stochastic-gradient-for-nonconvex-optimization.pdf)

**Comment by agibsonccc** [comment]
This is handled by the new parameter server. I am consolidating this topic under that.
