### ISSUE TITLE
MultiLayerConfiguration: Switch ConvolutionLayerSetup to use InputType functionality

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2000]
Recent PR considerably refactored the nIns/preprocessor/validation componet of ComputationGraph.
Much of this functionality can be reused for MultiLayerConfiguration.

https://github.com/deeplearning4j/deeplearning4j/pull/1994

**Comment by agibsonccc** [comment]
This is done.
