### ISSUE TITLE
Improve Tsne usability

### ISSUE THREAD

**Issue by QuentinAmbard** [deeplearning4j/deeplearning4j#2001]
I'm trying to use a TSNE reduction but face several issues, so I'd like to share some idea
- I need to get the result of the reduction (not interested by a file on the file system) but find no way to do so. I would suggest to add a method `getReduceMAtrix()` that return `Y`
- imo `plot` method should not fit the data, it should just plot (so instead of `plot(matrix,nDims,labels,path)` we should do `tsne.fit(matrix,nDims).plot(labels,path)`
- the method `fit(INDArray data, int nDims)` should be removed.  `nDims` is already set by the builder and calling this method change the tsne configuration, that's a big side-effect and I think it's confusing for the user.
  Generally speaking `nDims` should never be set as parameter of a method since it's something we define in the builder and can change with a setter. Method relying on it such `InMemoryLookupTable.plotVocab` should simply rely on the given tsne instance. If needed an assert on the tsne dimension could be added but that's it
- I would set the default value of `theta` in the Builder to `0.5`
- I find it strange to have the `BufferedWriter` declared inside the Tsne Object, imo something else should be in charge of creating a new file and generating the csv, but I undestand a lot of class rely on this method so it might be hard to change. Maybe adding a method with a generic `Writer` instead of a path could be a first step. Something like `tsne.fit(matrix,nDims).plot(labels,writer)`
- Object relying on the plot method such as `InemoryLookupTable.plotVocab(Tsne tsne, int numWords, UiConnectionInfo connectionInfo)`  first create a tmp file and then read this temp file and load it in-memory. I would recommand to add a method plot that just return the list of string, or to delegate the csv creation to another object.
- the method calculate of the parent Tsne class should probably be hidden (protected)

What do you think ? I'd be happy to help and work on this issue, please don't hesitate to give me some feedback

**Comment by agibsonccc** [comment]
Thank you! We would definitely help you with a pull request if you started
one! Feel free to reach out for feedback.

**Comment by Avricot** [comment]
Hi @agibsonccc , I made a few modifications but I can't find a way to build the projet. I've got missing dependancies of 0.5.1-SNAPSHOT versions (datavec-nd4j-common etc.), do you have a maven repo with night builds I could use to build against these versions ? Thanks

**Comment by raver119** [comment]
No, we usually build all things manually in advance.

**Comment by agibsonccc** [comment]
![screenshot at 2017-07-26 20-00-07](https://user-images.githubusercontent.com/1144306/28617983-97b3f9e0-723d-11e7-9715-1e91f9786988.png)
 Upload a file. Run save. 
Should be pretty easy now:
https://github.com/deeplearning4j/deeplearning4j/pull/3735

Not relevant.
