### ISSUE TITLE
how to use cbow instead of skip-gram to train word2vec in deeplearning4j 

### ISSUE THREAD

**Issue by jiadongzh** [deeplearning4j/deeplearning4j#2006]
Dear all,

The page of http://deeplearning4j.org/word2vec states that:
"It does so in one of two ways, either using context to predict a target word (a method known as continuous bag of words, or CBOW), or using a word to predict a target context, which is called skip-gram. We use the latter method because it produces more accurate results on large datasets."

However, I want to know: 
how to use cbow instead of skip-gram to train word2vec in deeplearning4j？I note that deeplearning4j includes CBOW.java.

Thank you very much for you any help.

**Comment by raver119** [comment]
Just a builder method:

Word2Vec.Builder()..elementsLearningAlgorithm(new CBOW<VocabWord>())
