### ISSUE TITLE
Computation Graph configuration validation calculation incorrect resulting in exception when building the network

### ISSUE THREAD

**Issue by andreas-eberle** [deeplearning4j/deeplearning4j#2007]
After pulling the latest changes from the master, I cannot run my network configurations any more. I produced a small example showing the problem.

https://gist.github.com/andreas-eberle/a3219304d0e85f287c6357dfd15c680e

I create the network with an imageSize of 40 => image of size 40x40 with one channel. I load the data in the FeedForward style.

This is the exception I get:

https://gist.github.com/andreas-eberle/3427ed9ff0bcf5e99682a48fcf8cb3f6

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/2008
