### ISSUE TITLE
Add MultiDataSetIterator that takes multiple DataSetIterators and combines them

### ISSUE THREAD

**Issue by andreas-eberle** [deeplearning4j/deeplearning4j#2009]
I'd like to have a MultiDataSetIterator that can take several DataSetIterators as argument to use them as data source. This would make it easy to combine existing iterators for combined networks. Furthermore, this would allow modular development of DataSetIterators which are then combined for the MultiDataSet.

**Comment by raver119** [comment]
AFAIK implemented long ago.
