### ISSUE TITLE
Crash on deserializing updater when using half precision

### ISSUE THREAD

**Issue by andreas-eberle** [deeplearning4j/deeplearning4j#2011]
I just trained a network with cuda and half precision. Now I wanted to continue the training, again with half precision. In order to do so, I serialized the network and updater and try to deserialize it again. I used the serialisation/deserialisation code a lot now, so that should be ok. However, I get the following exception when loading the updater: 

https://gist.github.com/andreas-eberle/144cdfb56023cbc42bb14bcb27e3aed5

My serialisation code looks like this:

https://gist.github.com/andreas-eberle/10f479f5846f2983a0fc90bf2feac009

I'm using 0.5.0.

**Comment by andreas-eberle** [comment]
Update: The same happens when I use your ModelSerializer class. Here is the stack trace

https://gist.github.com/andreas-eberle/a294006978bcde124d68ce2b40172c51

**Comment by andreas-eberle** [comment]
I should also note that when I try to deserialize the configuration with normal precision, the deserialization works (does not crash) but complains about the different data types and that this can cause a loss of data.

**Comment by raver119** [comment]
Fixed here: https://github.com/deeplearning4j/nd4j/pull/1223

Thanks for highlighting this one.
