### ISSUE TITLE
ElementWiseVertex: element-wise product not yet implemented

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2014]
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/graph/vertex/impl/ElementWiseVertex.java

**Comment by agibsonccc** [comment]
We have a PR on this now I believe?

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/3541
