### ISSUE TITLE
cnn-non-static

### ISSUE THREAD

**Issue by ghost** [deeplearning4j/deeplearning4j#2016]
Hello dear dl4j-devs,

Yoon Kim talks in his paper _Convolutional Neural Networks for Sentence Classification_ about _cnn-non-static_ where he basically propagates the error back to the word-vectors to learn better wordvectors. Would be nice if there would be an easy way to do that with dl4j.

Have a nice day,
Aleks

**Comment by agibsonccc** [comment]
@AlexDBlack doesn't the global pooling take care of this or is there more to do?

**Comment by raver119** [comment]
Embedding Layer should do that i guess.
