### ISSUE TITLE
Switch gradient clipping to native boolean indexing ops

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2017]
BooleanIndexing.applyWhere: used for gradient clipping.
https://github.com/deeplearning4j/deeplearning4j/blob/c18d7061d4931f60872cd1af4b1c23797075ccda/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/updater/BaseUpdater.java#L183

This will be using the java fallback, not the new/fast native code.

**Comment by raver119** [comment]
Merged today.
