### ISSUE TITLE
Enhance transfer learning functionality

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2021]
One use case: user wants to do transfer learning.
i.e., train a CNN on imagenet, then replace the output layer. Two possibilities here:
- Fine tune all parameters in the network
- Keep all but the output layer parameters fixed

Some functionality we could add to make this easier:
- Some way of transferring the parameters from one network to another, without having to do it manually (layer by layer)
  - Could do: a "replaceLayer" method? Or when nin/out are the same, a "reinitializeLayerParameters" method?
- Provide finetune(DataSet) and finetune(DataSetIterator) methods for training the output layer only
  - More general case that might be worth considering: train the top N layers only

**Comment by AlexDBlack** [comment]
Also: a transfer learning example would be a good idea...

**Comment by quertenmont** [comment]
I would also be interested to have an example/work around  which is working on current dl4j release
to transfer learning from one network to another one.

**Comment by agibsonccc** [comment]
We are finally finishing this.

**Comment by renyingxin** [comment]
Is this functionality finished, will appreciate if you provide a detailed example, as AlexDBlack told.
the same function for tensorflow:
https://www.kernix.com/blog/image-classification-with-a-pre-trained-deep-neural-network_p11

**Comment by eraly** [comment]
@renyingxin Thanks for the link to the example. I am finishing one up and will take a look at the link you posted.

**Comment by eraly** [comment]
There are examples in 0.8.0 now
