### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by caoquyvu** [deeplearning4j/deeplearning4j#2022]
Page not found : https://github.com/deeplearning4j/dl4j-examples/blob/master/src/main/java/org/deeplearning4j/examples/recurrent/word2vecsentiment/Word2VecSentimentRNN.java when i clicked to sentiment analysis on http://deeplearning4j.org/word2vec#intro

**Comment by ejunprung** [comment]
Fixed as well. Correct link: https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/word2vecsentiment/Word2VecSentimentRNN.java
