### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by caoquyvu** [deeplearning4j/deeplearning4j#2023]
Page not found : https://github.com/deeplearning4j/dl4j-examples/blob/master/src/main/java/org/deeplearning4j/examples/nlp/word2vec/Word2VecRawTextExample.javawhen i clicked to "A Working Example" on http://deeplearning4j.org/word2vec#intro

**Comment by ejunprung** [comment]
This has been fixed. The correct link should have been https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/word2vec/Word2VecRawTextExample.java
