### ISSUE TITLE
Visualizing Network Training with HistogramIterationListener, not working

### ISSUE THREAD

**Issue by ale86ch** [deeplearning4j/deeplearning4j#2027]
I'm trying to see the histogram using the HistogramIterationListener but when the code is running it print in the console the link and when I open it, it doesn't show anything the webpage says: No data available! Please check, if HistogramIterationListener was enabled
also in the navbar it doesn't show any available session.

Those are some information about my OS, source code and pom.xml

OS: Windows 10 Education 64bit, Version 1607, Build 14393.51
Browser: Google Chrome 52.0.2743.116
Antivirus: -
Firewall: -

Source code: https://gist.github.com/ale86ch/f584e3471e3959d025e6e2943f38c74a
pom.xml: https://gist.github.com/ale86ch/712acaadfd990de7d8711266379fd573

**Comment by raver119** [comment]
Not a bug, user mistake. At line 133 HistogramListener is defined, but at line 187 it's overwritten with ScoreListener.
