### ISSUE TITLE
Docs/website: Add a maven pom file / project generator

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2028]
Spring initializer: http://start.spring.io/
That allows people to set up a project very quickly, even if they don't know maven. We could add something similar for DL4J.

How this would work for DL4J:
- Specify artifact ID etc
- Specify DL4J/ND4J version
- Specify nd4j native vs. cuda
- Tick boxes for optional dependencies: ui, nlp, spark, arbiter, etc.
  then: "Generate Maven pom.xml" and "Generate SBT" etc buttons.

**Comment by huitseeker** [comment]
See also https://github.com/deeplearning4j/deeplearning4j/issues/1466

**Comment by huitseeker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DataVec, workflow & al. - improve documentation](https://trello.com/c/3u3jt2lF/5-datavec-workflow-al-improve-documentation)

**Comment by crockpotveggies** [comment]
Issue moved to [deeplearning4j/deeplearning4j-docs #46](https://github.com/deeplearning4j/deeplearning4j-docs/issues/46) via [**ZenHub**](https://www.zenhub.com/)
