### ISSUE TITLE
Parameter sharing over many computation graphs

### ISSUE THREAD

**Issue by quertenmont** [deeplearning4j/deeplearning4j#2030]
Hello,

Sorry for asking my question on the github issues tracker, but I didn't find any better appropriate place.
I'd like to train several computation graphs which share most of their inputs and first layers.
Typically, I have N group of 10-20 input features each.  I expect the feature in each group to be uncorrelated with the features of the other groups, so it would make sense to build a dense multi-layer network for each group and then make a computation graph to recombine  each of these through a merge vertex.

However, my problem is that not all of my data have data for all of  the groups.
In that case, I would like to ignore the input features from the missing groups.
So a priori I would need to build a computation graph for each different case of missing groups...  (unless you can suggest me a better way to deal with it)
that's not ideal... but that's life and technically possible .

Nevertheless, I would still like to train (and benefits from prior training) on the groups are present.
Is there a way to use the same layer (sharing parameters) in different computation graphs ?
This would be very convenient, so I can maximize the use of my data for the training of the first layers.

If that's not feasible, could you recommend a workaround ?

I join a small schematic of what I am talking about
![image](https://cloud.githubusercontent.com/assets/4639944/17959013/e07dcffa-6a9d-11e6-86c3-a73bb5c748b3.png)

Thanks in advance for your help,
Loic

**Comment by agibsonccc** [comment]
We're doing gradient sharing now... Beyond that I feel like 1 computation graph with masking is what you're looking for here.
