### ISSUE TITLE
Update gradle instructions to correct scope

### ISSUE THREAD

**Issue by mschaars** [deeplearning4j/deeplearning4j#2031]
In the buildtool docs (http://deeplearning4j.org/buildtools), the gradle section instructs to use:

provided "org.deeplearning4j:deeplearning4j-core:0.5.0"

Using the provided scope here is outdated (should be compile) and will lead to problems with creating distributions.

**Comment by saudet** [comment]
Could you send a pull request?

**Comment by jjustinic** [comment]
This documentation issue was corrected with pull request #4480 and has been merged to the gh-pages branch. This issue can be closed.
