### ISSUE TITLE
the  EmbeddingLayer is not prefect enough

### ISSUE THREAD

**Issue by zhangluoyang** [deeplearning4j/deeplearning4j#2034]
I do think, the EmbeddingLayer is not prefect enough.  i want to make EmbeddingLayer 's input support [batch_size,input_size] and output is [batch_size,input_size,embedding_size]
just like LookupTable's function. for example, batch_size=2,input_size=2,embedding_size=2. then is input data is a matrix [[1,2],[0,1]],i want to get a output result from EmbeddingLayer is [[[0.1,0.2],[0.2,0.3]],[[0.0,0.1],[0.1,0.2]]].

**Comment by raver119** [comment]
@AlexDBlack what do you think about this issue these days? there were lots of changes since 2016...

**Comment by maxpumperla** [comment]
@raver119 this is already possible today, not sure since when. what @zhangluoyang requests is essentially what keras does. User wants (2, 2) --> (2, 2, 2), we do (2, 1, 2) --> (2, 2, 2). So it's just a matter of reshaping your input to [bs, 1, tsLen] and set recurrent input. done.
