### ISSUE TITLE
ScoreIterationListener is under-reporting when using truncated BPTT

### ISSUE THREAD

**Issue by anovstrup** [deeplearning4j/deeplearning4j#2044]
While training an RNN on time series data with 450 time steps and a truncation length of 100, `ScoreIterationListener` is reporting the score 4 times per epoch. I expected 5 parameter updates and therefore 5 score reports per epoch. 

My main worry is that the under-reporting could indicate that no parameter update is being performed for the last 50 time steps of my data.

**Dataset Details**
I have a training dataset with 8 multivariate time series consisting of 450 time steps, 65 input features, and 2 one-hot output labels (i.e., the feature tensor's shape is 8x65x450 and the label tensor's shape is 8x2x450). I am treating the full dataset as a single minibatch.

**Network Configuration**

``` scala
    val truncatedBackPropLength = 100
    val numInputs = 65
    val numHiddenNodes = 20
    val conf = new Builder()
      .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT).iterations(1)
      .updater(Updater.ADAM).adamMeanDecay(0.9).adamVarDecay(0.999)
      .regularization(true).l1(1e-4).dropOut(0.5)
      .weightInit(WeightInit.XAVIER)
      .learningRate(1e-4)
      .list()
      .layer(0, new GravesLSTM.Builder().nIn(numInputs).nOut(numHiddenNodes)
        .activation("tanh").build())
      .layer(1, new RnnOutputLayer.Builder().nIn(numHiddenNodes)
        .activation("softmax")
        .lossFunction(LossFunctions.LossFunction.MCXENT)
        .nIn(numHiddenNodes).nOut(2).build())
      .pretrain(false)
      .backprop(true)
      .backpropType(BackpropType.TruncatedBPTT)
      .tBPTTBackwardLength(truncatedBackPropLength).tBPTTForwardLength(truncatedBackPropLength)
      .build()
```

**Comment by raver119** [comment]
How exactly ScoreIterationListener configured? Show constructor line please

**Comment by anovstrup** [comment]
```scala
val net = new MultiLayerNetwork(conf)
net.init()
net.setListeners(new ScoreIterationListener(1))
```
