### ISSUE TITLE
ModelSerializer.writeModel(Model, OutputStream, boolean) closes stream despite not opening it

### ISSUE THREAD

**Issue by reckart** [deeplearning4j/deeplearning4j#2046]
Methods should not close streams that they have not opened themselves. `ModelSerializer.writeModel(Model, OutputStream, boolean)` closes the passed outputstream - this e.g. hinders writing the model to a ZIP file.

A possible workaround is to wrap the passed outputstream using a CloseShieldOutputStream.

**Comment by raver119** [comment]
Actually that looks like the only viable solution, since it's ZipOutputStream who actually passes close() to underlying stream. 

Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2063

Thanks for highlighting this issue.
