### ISSUE TITLE
"Score vs. Iteration #" is misleading

### ISSUE THREAD

**Issue by reckart** [deeplearning4j/deeplearning4j#2052]
The "Score vs. Iteration #" plot in dl4j-ui does not actually show iterations (at least not those iterations that one configures on a network). It rather shows how many mini-batches have been processed. Same for the ScoreIterationListener and possibly in other places.

How about changing either those labels to e.g. "Score vs. Mini-batch #" and ScoreMiniBatchListener etc.?

**Comment by treo** [comment]
Iterations are a little bit special in DL4J. Say you have 4 mini-batches A, B, C and D. The Iteration that you are seeing is how often a mini-batch has been used. So if you set `.iterations(3)` on the network configuration and you feed it an epoch, you will see 12 iterations reported and the network will have seen the data as AAABBBCCCDDD. If you were to set `.iterations(1)` and feed it just one epoch again, it would report 4 iterations and the network will have seen the data as ABCD.

So changing it to "Score vs. Mini-Batch #" or "ScoreMiniBatchListener" doesn't actually make it better. The number it represents is more closely related to the number of updates that have been made to the network parameters. So maybe "ScoreUpdateListener" and "Score vs. Update #" are less confusing?

**Comment by reckart** [comment]
The confusing part is that the term "iterations" is overloaded with two concepts. Using separate suitable terms for the concept should resolve the confusion. "update" seems a suitable term.

**Comment by AlexDBlack** [comment]
.iterations(int) has been removed.
