### ISSUE TITLE
java.lang.OutOfMemoryError: Cannot allocate 2 + 5909359200 bytes (> Pointer.maxBytes)

### ISSUE THREAD

**Issue by lycchn** [deeplearning4j/deeplearning4j#2055]
When running class Word2VecUpTrainingExample and using C trained size 1,73 GB I get following Error message:

     Exception in thread "main" java.lang.OutOfMemoryError: Cannot allocate 2 + 5909359200 bytes (> Pointer.maxBytes)
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:486)
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:120)
	at org.bytedeco.javacpp.FloatPointer.allocateArray(Native Method)
	at org.bytedeco.javacpp.FloatPointer.<init>(FloatPointer.java:68)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:457)
	at org.nd4j.linalg.api.buffer.FloatBuffer.<init>(FloatBuffer.java:57)
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createFloat(DefaultDataBufferFactory.java:238)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1224)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1199)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:230)
	at org.nd4j.linalg.cpu.nativecpu.NDArray.<init>(NDArray.java:111)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:247)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4335)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4297)
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3550)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readBinaryModel(WordVectorSerializer.java:217)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadGoogleModel(WordVectorSerializer.java:116)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadGoogleModel(WordVectorSerializer.java:96)
	at org.deeplearning4j.examples.nlp.word2vec.Word2VecUptrainingExample.main(Word2VecUptrainingExample.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code 1`

POM xml:
         <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org   /2001/XMLSchema-instance"
        
     xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <groupId>org.deeplearning4j</groupId>
    <artifactId>deeplearning4j-examples-parent</artifactId>
    <version>0.5-SNAPSHOT</version>
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>

    <prerequisites>
        <maven>3.0.5</maven>
    </prerequisites>

    <name>DeepLearning4j Examples Parent</name>
    <description>Examples of training different data sets</description>
    <properties>
        <nd4j.backend>nd4j-native-platform</nd4j.backend>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <shadedClassifier>bin</shadedClassifier>
        <java.version>1.7</java.version>
        <nd4j.version>0.5.0</nd4j.version>
        <dl4j.version>0.5.0</dl4j.version>
        <datavec.version>0.5.0</datavec.version>
        <arbiter.version>0.5.0</arbiter.version>
        <guava.version>19.0</guava.version>
        <jfreechart.version>1.0.13</jfreechart.version>
        <maven-shade-plugin.version>2.4.3</maven-shade-plugin.version>
        <exec-maven-plugin.version>1.4.0</exec-maven-plugin.version>
    </properties>

    <modules>
        <module>dl4j-examples</module>
        <module>dl4j-spark-examples</module>
        <module>datavec-examples</module>
        <module>dl4j-cuda-specific-examples</module>
    </modules>

</project>
`

Just trying to load my C trained data leads to the aforementioned error. With the following code:

    package org.deeplearning4j.examples.nlp.word2vec;

    import org.datavec.api.util.ClassPathResource;    
    import org.deeplearning4j.models.embeddings.WeightLookupTable;
    import org.deeplearning4j.models.embeddings.inmemory.InMemoryLookupTable;
    import org.deeplearning4j.models.embeddings.loader.WordVectorSerializer;
    import org.deeplearning4j.models.word2vec.VocabWord;
    import org.deeplearning4j.models.word2vec.Word2Vec;
    import org.deeplearning4j.models.word2vec.wordstore.inmemory.InMemoryLookupCache;
    import org.deeplearning4j.text.sentenceiterator.BasicLineIterator;
    import org.deeplearning4j.text.sentenceiterator.SentenceIterator;
    import org.deeplearning4j.text.tokenization.tokenizer.preprocessor.CommonPreprocessor;
    import org.deeplearning4j.text.tokenization.tokenizerfactory.DefaultTokenizerFactory;
    import org.deeplearning4j.text.tokenization.tokenizerfactory.TokenizerFactory;
    import org.slf4j.Logger;
    import org.slf4j.LoggerFactory;
    import java.io.*;
    import java.util.Collection;

    /**
     * This is simple example for model weights update after initial vocab building.
     * If you have built your w2v model, and some time later you've decided that it can be
     * additionally trained over new corpus, here's an example how to do it.
     *
     * PLEASE NOTE: At this moment, no new words will be added to vocabulary/model.
     * Only weights update process will be issued. It's often called "frozen vocab training".
     *
     * @author raver119@gmail.com
     */
    public class Word2VecUptrainingExample {

    private static Logger log = LoggerFactory.getLogger(Word2VecRawTextExample.class);

    public static void main(String[] args) throws Exception {
        /*
                Initial model training phase
         */

        /*String filePath = new ClassPathResource("raw_sentences.txt").getFile().getAbsolutePath();

        log.info("Load & Vectorize Sentences....");
        // Strip white space before and after for each line
        SentenceIterator iter = new BasicLineIterator(filePath);
        // Split on white spaces in the line to get words
        TokenizerFactory t = new DefaultTokenizerFactory();
        t.setTokenPreProcessor(new CommonPreprocessor());

        // manual creation of VocabCache and WeightLookupTable usually isn't necessary
        // but in this case we'll need them
        InMemoryLookupCache cache = new InMemoryLookupCache();
        WeightLookupTable<VocabWord> table = new InMemoryLookupTable.Builder<VocabWord>()
                .vectorLength(100)
                .useAdaGrad(false)
                .cache(cache)
                .lr(0.025f).build();

        log.info("Building model....");
        Word2Vec vec = new Word2Vec.Builder()
                .minWordFrequency(5)
                .iterations(1)
                .epochs(1)
                .layerSize(100)
                .seed(42)
                .windowSize(5)
                .iterate(iter)
                .tokenizerFactory(t)
                .lookupTable(table)
                .vocabCache(cache)
                .build();

        log.info("Fitting Word2Vec model....");
        vec.fit();

        Collection<String> lst = vec.wordsNearest("day", 10);
        log.info("Closest words to 'day' on 1st run: " + lst);

        /*
            at this moment we're supposed to have model built, and it can be saved for future use.
         */
        //WordVectorSerializer.writeFullModel(vec, "pathToSaveModel.txt");
        File gModel = new File("C:\\Users\\bsc\\Desktop\\test.bin");
        Word2Vec word2Vec = (Word2Vec) WordVectorSerializer.loadGoogleModel(gModel, true);
        /*
            Let's assume that some time passed, and now we have new corpus to be used to weights update.
            Instead of building new model over joint corpus, we can use weights update mode.
         */
        //Word2Vec word2Vec = WordVectorSerializer.loadFullModel("pathToSaveModel.txt");

        /*
            PLEASE NOTE: after model is restored, it's still required to set SentenceIterator and TokenizerFactory, if you're going to train this model
         */
        /*SentenceIterator iterator = new BasicLineIterator(filePath);
        TokenizerFactory tokenizerFactory = new DefaultTokenizerFactory();
        tokenizerFactory.setTokenPreProcessor(new CommonPreprocessor());

        word2Vec.setTokenizerFactory(tokenizerFactory);
        word2Vec.setSentenceIter(iterator);

        log.info("Word2vec uptraining...");

        word2Vec.fit();

        lst = word2Vec.wordsNearest("day", 10);
        log.info("Closest words to 'day' on 2nd run: " + lst);

        /*
            Model can be saved for future use now
         */

        }
    }

VM options:
    # custom IntelliJ IDEA VM options
    -server
    -Xms1024m
    -Xmx6000m
    -XX:ReservedCodeCacheSize=240m
    -XX:+UseConcMarkSweepGC
    -XX:SoftRefLRUPolicyMSPerMB=50
    -ea
    -Dsun.io.useCanonCaches=false
    -Djava.net.preferIPv4Stack=true
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:-OmitStackTraceInFastThrow

I have 8gb ram

**Comment by raver119** [comment]
Intellij -Xmx value has nothing to do with memory limit of your app. You should set Xmx specifically for the app you're launching.

**Comment by lycchn** [comment]
so I tried to set -Xmx for my java app and decreased my test.bin file to 1.8MB to check if it works with an even smaller model but still I get the same error. surprisingly the following error message never changed accordingly to my model size. it always says 5909359200 bytes, it could be that it doesnt load my file test.bin but some other file? 

     Exception in thread "main" java.lang.OutOfMemoryError: Cannot allocate 202980 + 5909359200 bytes (> Pointer.maxBytes)

**Comment by raver119** [comment]
That's easy to check. Give me your current source, and full stack trace.

First suspect there is test.bin file still contains original number of words at first "line", not a decreased one.

**Comment by lycchn** [comment]
ok checked your suggestions and your were right. Now it works fine. thank you very much!

**Comment by raver119** [comment]
Cool

**Comment by JafferWilson** [comment]
@raver119   @lycchn  What was the suggestion. Please let me know. I have the same problem.

**Comment by agibsonccc** [comment]
@JafferWilson it's right there in raver's comment:
>> First suspect there is test.bin file still contains original number of words at first "line", not a decreased one.

**Comment by JafferWilson** [comment]
@agibsonccc  Yes it is having the same length. I am using Google New Vector from here: https://github.com/mmihaltz/word2vec-GoogleNews-vectors
Kindly let me know the problem is still there.

**Comment by raver119** [comment]
@JafferWilson please define, which "the same problem" you have?

**Comment by raver119** [comment]
give us full stack trace of your exception

**Comment by JafferWilson** [comment]
@raver119 Thank you for your reply. I resolved it. The problem was due to the RAM of my system when I shifted to 8 GB it is working fine. :)

**Comment by raver119** [comment]
Cool
