### ISSUE TITLE
Memory Leak leads to java.lang.OutOfMemoryError: Cannot allocate xxx bytes (> Pointer.maxBytes)

### ISSUE THREAD

**Issue by ChessPoker** [deeplearning4j/deeplearning4j#2059]
Here is an example of training which begins at around 3:32 PM and slows down dramatically at 3:35 PM.
Console output log is [here](https://gist.github.com/ChessPoker/6adc9354fa8ec686dcd747282434263f).
The log shows that the first 8 epochs proceeded quickly. Epoch 8 was 15 seconds. Epoch 9, however, was 294 seconds (20X slowdown).

Here is screenshot of VisualVM's monitor tab.
![monitor](https://cloud.githubusercontent.com/assets/8595703/18187481/bd8c1b48-705e-11e6-9fc5-8cdad6a7366b.png)

The Heap is growing consistently during the first 8 epochs, then trouble at epoch 9 around 3:35.

GC settings are: -XX:MinHeapFreeRatio=67 -XX:MaxHeapFreeRatio=99 -Xms16384m.
System.gc() is invoked before training and before validation every epoch.

Here is the heap list from visualVM: 
![heaplist](https://cloud.githubusercontent.com/assets/8595703/18187630/fe592eb2-705f-11e6-9847-ac0b4a1fae0b.png)

org.bytedeco.javacpp.Pointer$NativeDeallocator is consuming a lot of memory. It was growing consistently during training. Sorry I didn't get a snapshot from earlier prior to epoch 9. But I did witness the NativeDeallocator instance count rising and rising during the earlier epochs.

Environment Vars:
OMP_NUM_THREADS=1
LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2016.3.210/linux/mkl/lib/intel64_lin/
MKL_THREADING_LAYER=GNU
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgomp.so.1

Network Config is [here.](https://gist.github.com/ChessPoker/b34c830f1366da8c21a155b2d2f1ce30)

ParallelWrapper is being used with 16 workers.

Hardware:
CPU:  2 x Intel Xeon E5-2687Wv3, 3.1 GHz (10-Core, HT, 25MB Cache, 160W) 22nm
RAM:  64GB (8 x 8GB DDR4-2133 ECC Registered 1R 1.2V DIMMs) Operating at 2133 MT/s Max

DataSetIterator config is [here.](https://gist.github.com/ChessPoker/5679482f961f9ec736bf2fd89ae84864)
I'm using CachingDataSetIterator.

My speculation:
I think it is odd that the used heap continues to grow so consistently without abatement after the first epoch. I think these algorithms use exponential moving averages, rather than save a history of past values, so heap usage shouldn't continue rising epoch after epoch like this (please correct me if I'm wrong). It looks like a memory leak to me.

I've had this happen a few times over the last couple of days. Increasing -Xmx just kicks the can down the road. That is, the bug just takes longer to surface.

**Comment by saudet** [comment]
This should be fixed with the latest code from the master branch of JavaCPP. Could you make sure that is what you are running?

**Comment by ChessPoker** [comment]
I did:
git clone https://github.com/bytedeco/javacpp.git
cd javacpp/
mvn clean install -DskipTests -Dmaven.javadoc.skip=true

And reran. Now epoch zero is taking forever. It's been 15 minutes at least so far and still the epoch is not completed (it used to take 30 seconds).

VisualVM says org.bytedeco.javacpp.Pointer.deallocator() is taking biggest percentage of self time.
org.bytedeco.javacpp.Pointer.physicalBytes[native]() is taking the biggest self time (cpu).

Did I do this correctly? Am I running master branch now?

**Comment by AlexDBlack** [comment]
```return new CachingDataSetIterator(new BaseDatasetIterator(miniBatchSize, bFetcher.totalExamples(), bFetcher), new InMemoryDataSetCache());```

The CachingDataSetIterator would be the first thing to check here... that was a community PR. Could be causing the leak?
I'd try it without the caching iterator, see if you still have problems.

**Comment by saudet** [comment]
@ChessPoker Yes, it looks alright w.r.t to JavaCPP, but it seems too many temporary objects get created...

**Comment by ChessPoker** [comment]
@AlexDBlack Ran an experiment just now to test the Iterators. After hundreds of passes through the training and validation sets there is no increase in heap.  It's just a non-trending saw-tooth pattern as you would normally expect to see when there is no leak.

**Comment by ChessPoker** [comment]
I forgot to mention that I built the whole stack yesterday from master: 0.5.1-SNAPSHOT

**Comment by ChessPoker** [comment]
@saudet The reason for the slow down is due to an UnsatisfiedLinkError on calling Pointer.physicalBytes(). I must have old binaries. I put in a fix that initializes a boolean, usePhysicalBytes=true, that flips to false on an UnsatisfiedLinkError and thereafter we don't have to waste so much time throwing and catching it all day.

The code is [here](https://gist.github.com/ChessPoker/900e9e5ac872e86bcd3fc9a62e5b659d)

Now an epoch is back down to 14 seconds like before.

Also, good news the memory leak is gone. So I think you are correct that the master branch fixes the leak.

**Comment by ChessPoker** [comment]
@saudet I have read about JavaCPP and I think I should not be getting an UnsatisfiedLinkError because I built the latest JavaCPP using Maven and it downloaded the latest binary javacpp-1.2.3-bin. Should we close this issue (since the memory leak is fixed on Master) and open a new issue about the UnsatisfiedLinkError?
Also, wondering about whether the boolean flag quick fix I have on my local repository is worth a pull request?

**Comment by saudet** [comment]
This is a function that needs to be built in the binaries, such as the ones from ND4J. Just rebuild ND4J and that won't happen anymore.
