### ISSUE TITLE
problem training CNN with word2vect output

### ISSUE THREAD

**Issue by jdpitt** [deeplearning4j/deeplearning4j#2064]
My input files are one sentence per line.

This is the gist
https://gist.github.com/jdpitt/aa4280c2c1d4807646ce34ce760efd46

**Comment by astier** [comment]
I think you have to use a DatasetIterator or to write your own one which aligns the wordvectors of a sentence in a 2D array or in a 4D Matrix (NumberOfSentences x  depth x height x width). Right now its something different. Probably 3D.

**Comment by jdpitt** [comment]
Thank you for answering. However, I think I need more information regarding how to write my own iterator because I do not know the exact data structure in which the model is expecting the data to execute a CNN. I di use a data set iterator already 

//        Merge the labels and the features
        Iterable featuresAndLabels = mergeFeaturesWithLabels(sentencesMatrix,falseLabels);
//      Create the data set iterator
        log.info("Convert to data set iterator....");
        DataSetIterator trainData = new INDArrayDataSetIterator(featuresAndLabels,1);

I create a 2D array already and model.fit complained, so I created a 3D array where the last dimension is just one. 

I am really lost in this, I do not know how to continue. Any help is appreciated. 

Thank you very much

**Comment by astier** [comment]
I'm not an expert for dl4j. Just a guy like you who tries to work somehow with it. So I don't know if it's the perfect solution but I wrote my own DataSetIterator. It reads already preprocessed tweets from a file. The format has to be for each row of the file like following:
_class tweet_
where the class can be positive, negative or neutral. Class and tweet are tab-separated. Then it searches for wordvectors in a lookUpTable (I use GloVe Twitter) for each word in the tweet and puts the vectors in a 4 dimensional matrix. Heres the code:

https://gist.github.com/astier/fa520498119620e54e279cd5179f2d3c

You can study it to write your own iterator. Maybe it looks complicated but its really not.

**Comment by jdpitt** [comment]
Thanks for the reply. I will check your code
