### ISSUE TITLE
RBM uses Commons Math for Random Sampling

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#2073]
RBM's don't train as fast as they could because they still use commons math.

![image](https://cloud.githubusercontent.com/assets/509379/18252846/2061ad84-7391-11e6-863a-41895d52edbd.png)

**Comment by agibsonccc** [comment]
We need to migrate our distribution stuff over to native yet I believe.

**Comment by treo** [comment]
Dropout is already a native op. I created the issue mainly as a todo list item :)

**Comment by agibsonccc** [comment]
This is done now I think.
