### ISSUE TITLE
not able to serialize the model ModelSerializer

### ISSUE THREAD

**Issue by charlsjoseph** [deeplearning4j/deeplearning4j#2079]
I'm trying to serialize a model  using ModelSerializer. but it is not actually serializing. I cant find it in the respective directory. But with in the same program, I was able to restore the same file and use it.

But the model gets vanished from the directory after the program completes. 

  val modelFile = new File("/home/cloudera/NeuralNets/YHOO.model");
  modelFile.deleteOnExit();
  println("writing into : " + modelFile.getAbsolutePath + " : " + modelFile.getAbsoluteFile  + " : " + modelFile.getTotalSpace);
  ModelSerializer.writeModel(sparkNeuralNetwork.getNetwork, modelFile, true);
  //val  model = ModelSerializer.restoreMultiLayerNetwork(modelFile)

**Comment by agibsonccc** [comment]
deleteOnExit will do that

**Comment by raver119** [comment]
Are you kidding? :)

***modelFile.deleteOnExit();***

**Comment by charlsjoseph** [comment]
Oh sorry.. I overlooked it. I thought it is deleteOnExist.

**Comment by charlsjoseph** [comment]
I'm able to do it after i removed it. Thanks all. 


[cloudera@quickstart NeuralNets]$ ls
[cloudera@quickstart NeuralNets]$ ls
YHOO.model
[cloudera@quickstart NeuralNets]$
