### ISSUE TITLE
Exception  java.lang.NoSuchMethodError: org.nd4j.linalg.factory.Nd4j.rand([ILorg/apache/commons/math3/random/RandomGenerator;)Lorg/nd4j/linalg/api/ndarray/INDArray; 	at org.deeplearning4j.models.embeddings.inmemory.InMemoryLookupTable.resetWeights(InMemoryLookupTable.java:377)

### ISSUE THREAD

**Issue by jjzhu** [deeplearning4j/deeplearning4j#209]
git pull 0.0.3.3

try to use vec.fit()

**Comment by agibsonccc** [comment]
Anytime you see anything remotely like this please ensure you pull in the new sources from canova and nd4j and mvn clean install on the sources.

**Comment by jjzhu** [comment]
Is canova a new branch? 
I actually pulled all new resources for deeplearning4j at 0.0.3.3 branch and nd4j at master branch.

**Comment by agibsonccc** [comment]
Canova is the 3rd project we have: https://github.com/deeplearning4j/Canova

I have a setup.sh in the root of deeplearning4j that should install everything from source for you.

**Comment by jjzhu** [comment]
thanks, just cloned. Did not see the deeplearning4j folder? 

folders I have: canova-api canova-data canova-nd4j
