### ISSUE TITLE
Add MultiLayerUpdater.clone() and ComputationGraphUpdater.clone()

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2096]
Doesn't give us anything that  we can't do with the state view array, but might be easier for users.

**Comment by raver119** [comment]
I guess this issue is still viable?

**Comment by AlexDBlack** [comment]
Technically, yes - but I haven't needed this - and we haven't had any users asking for it - since the original issue was opened. So I'll close it.
