### ISSUE TITLE
MultiDataSet support in org.deeplearning4j.parallelism.ParallelWrapper

### ISSUE THREAD

**Issue by AlexanderSerbul** [deeplearning4j/deeplearning4j#2111]
Please add support for MultiDataSets in org.deeplearning4j.parallelism.ParallelWrapper and abstract MultiDataSetIterator.

**Comment by AlexanderSerbul** [comment]
Noticed swallowed exceptions in ParallelWrapper (inside Thread.run after start model fitting). If model contains errors, training hangs without info about exception. Please fix, thank you.

**Comment by raver119** [comment]
Actually, ParallelWrapper is going to get overhaul for 0.7.0. It was just test tool initially. So if you have any ideas/features/bugs in mind - feel free to post them here, feedback is always welcome.

**Comment by raver119** [comment]
Both issues fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2124

Thanks for highlighting those.
