### ISSUE TITLE
GPU is not being fully utilized

### ISSUE THREAD

**Issue by scotthong** [deeplearning4j/deeplearning4j#2114]
System Information: 

nd4j-backend: nd4j-cuda-0.8.0
GPU Hardware: GTX 1070
Driver Version: 372.70
OS: Windows 7 64 bit
Java: 1.8.0_102-b14

Example Program: 
The 
java -cp target/classes;target/ComputerVision-examples-1.0-SNAPSHOT.jar org.deeplearning4j.examples.cv.cifar10.Cifar

GPU Load Monitoring using GPU-Z:

The GPU load on average is about 20%. 
When using the nd4j-native backend running on CPU, the CPU load average (using task manager) is about 50%. 

When running the LFW example using the "nd4j-cuda-0.8.0" backend

java -cp target/classes;target/ComputerVision-examples-1.0-SNAPSHOT.jar org.deeplearning4j.examples.cv.labeledFacesWild.LFW

The GPU load average is only about 10%.

The question is that, why dl4j is not taking the full computing capabilities of a local GPU?

**Comment by raver119** [comment]
That's wrong question.

Proper question is: what PerformanceListener shows your for both CPU and GPU?
