### ISSUE TITLE
ConvolutionalIterationListener output doesn't seem right

### ISSUE THREAD

**Issue by ramgo2** [deeplearning4j/deeplearning4j#2120]
![image](https://cloud.githubusercontent.com/assets/13745960/18739022/4e18342a-80be-11e6-92a5-2b7964bd6ab2.png)

I'm running Lenet example with my data and ConvolutionalIterationListener. The data has 3 classes (elephant, chair, balloon). Often I see the small images in the 2nd layer output to be not matching the input image. What I mean is, for the elephant input you can see Chair in the second layer. Is this normal? Also, what's the 3rd layer of images that are shown? There are 5 of those, not sure what they correspond to.

is there a good sample screenshot of what to expect in the ConvolutionalIterationListener? And also, shouldn't the final output be a label?

**Comment by raver119** [comment]
Those images are just "zoomed-in" images from your second layer, taken randomly. Actually it's a good idea to add label there as last layer.

**Comment by ramgo2** [comment]
Ok.. the 2nd layer is showing images of a chair while the input image is that of an elephant.  Why is it so?

**Comment by raver119** [comment]
Obviously, bug. Probably image got token from another example within batch. I'll take a look there

**Comment by raver119** [comment]
Hypothetically fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2153

Will be merged a bit later. Thanks for highlighting this issue.
