### ISSUE TITLE
ParallelWrapper stops after a short time

### ISSUE THREAD

**Issue by Alcalol** [deeplearning4j/deeplearning4j#2123]
When the normal MultiLayerNetwork is used inside a while loop for the iterator, things works as normal.  However when the MultiLayerNetwork is put inside the ParallelWrapper, a couple of strange things happen:

1. During Epoch 2 batch 1, a short while (maybe 5 minutes in or so) the entirely thing stops working.  The process is still running but CPU usage drops to idle, GPU load drops to 0% and CudaCachingZeroProvider no longer outputs cache info (Both GPU and normal memory appears to remain populated).

2.  The miniBatchSize was set to 32 and the data has at least 300,000 timesteps, however epoch 1 only has 1 batch run before it moves onto batch 2

Things I have tried to no avail:
1. Changing batch size up or down
2. Data Size up or down (but still enough rows for more than one batch)
3. Change worker size between 2 and 4
4. Change prefetchbuffer for parallel wrapper up and down
5. Tried various values for averagingFrequency from 1 to 20
6. Tried useLegacyAveraging true or false
7. Tried wrapper with wrapper.fit inside epoch for loop as well as MultiEpochsIterator
8. Tried various combination of CudaEnvironment settings as well as leaving everything as default

Side notes:
I have looked inside the iterator to make sure it does contain data and the data appears correct
I am currently running two GTX 780 cards (SLi disabled)
The computer has 16GB of ram and at no point was all the memory used up (13gb max during tests)
My java code is inside NetBeans IDE 8.1 with Maven 3.0.5
The DL4J and ND4J versions are 0.6.0 [ jar] Central

**Comment by raver119** [comment]
show me how you configure ParallelWrapper please

**Comment by Alcalol** [comment]
```
            System.out.println("Setting up network structure");
            MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                    .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT).iterations(1)
                    .learningRate(0.02)
                    .rmsDecay(0.95)
                    .seed(12345)
                    .regularization(true)
                    .l2(0.001)
                    .weightInit(WeightInit.XAVIER)
                    .updater(Updater.RMSPROP)
                    .list()
                    .layer(0, new GravesLSTM.Builder().nIn(iterClassification.inputColumns()).nOut(lstmLayerSize)
                            .activation("tanh").build())
                    .layer(1, new GravesLSTM.Builder().nIn(lstmLayerSize).nOut(lstmLayerSize)
                            .activation("tanh").build())
                    .layer(2, new RnnOutputLayer.Builder(LossFunction.MCXENT).activation("softmax")
                            .nIn(lstmLayerSize).nOut(nOut).build())
                    //.backpropType(BackpropType.TruncatedBPTT).tBPTTForwardLength(tbpttLength).tBPTTBackwardLength(tbpttLength)
                    .backpropType(BackpropType.Standard)
                    .pretrain(false).backprop(true)
                    .build();

            System.out.println("Initializing network");
            MultiLayerNetwork net = new MultiLayerNetwork(conf);
            net.init();
            
            
            ParallelWrapper wrapper = new ParallelWrapper.Builder(net)
                    .prefetchBuffer(12)
                    .workers(2)
                    .averagingFrequency(1)
                    .reportScoreAfterAveraging(true)
                    .useLegacyAveraging(false)
                    .build();
```

I've included network config and network init in case I did something wrong there

**Comment by raver119** [comment]
Can i have full output you're getting there? As gist please

**Comment by Alcalol** [comment]
https://gist.github.com/Alcalol/be3f268aea012fdf2fe2eef2297745e3

From start to finish.

**Comment by Alcalol** [comment]
So... an update to this issue.  After trying parallel processing with spark and it still didn't work, I decided to have a look at what's inside my iterator in case the data was causing the problem.  It was.

Turns out I had been using a CSVSequenceRecordReader, SequenceRecordReader and SequenceRecordReaderDataSetIterator for loading data, and for some reason it loads the entire contents of all files into a single time step of the iterator.  By changing to non Sequence editions of the above (CSVRecordReader, RecordReader and RecordReaderDataSetIterator), the correct batches were finally loaded into each time step and is now working.

This also indirectly solved point 2, because there was only one timestep in the Sequence type iterator of everything, so it only ran once and there was nothing else to do.

**Comment by raver119** [comment]
As far as i understand issue is resolved now.

**Comment by muldon** [comment]
I had the same problem. After I set the batchSize the problem was solved. I thought that this was not necessary once I had set iterations and epochs because I figured the code would automatically calculate the non set variables...

**Comment by AlexDBlack** [comment]
@muldon could you please open a new issue for this, with some code to reproduce it?
Also post the version you are using there (you should be on 0.9.1)
