### ISSUE TITLE
Add InputType for embedding layers

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2128]
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/inputs/InputType.java

We currently have InputType for other use cases, but not embedding layers...

**Comment by raver119** [comment]
It looks like this issue is still viable?

**Comment by AlexDBlack** [comment]
Closing in favor of: https://github.com/deeplearning4j/deeplearning4j/issues/4997
