### ISSUE TITLE
Error in MNIST tutorial - DeepLearning4J

### ISSUE THREAD

**Issue by thushv89** [deeplearning4j/deeplearning4j#214]
Hello,
I just went through the Deeplearning4J MNIST tutorial (http://deeplearning4j.org/mnist-tutorial.html) and the tutorial uses DBN class which is not available in version 0.0.3.3 as mentioned in issue #173 
Is there any resource which explains how to use DeapLearning4J 0.0.3.3 for MNIST without DBN class?

**Comment by agibsonccc** [comment]
Those tutorials are for 0.0.3.2. Please look at the 0.0.3.3 examples (ensuring you install 0.0.3.3 from source) for the most up to date.
