### ISSUE TITLE
Add maven enforcer rules

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2144]
Check for invalid dependencies setup: both scala 2.10 and 2.11 in the same project; maybe other things like implementation of logging (instead of just slf4j), non-test scope ND4J dependencies in dl4j, etc.
Plus anything else we can think of...

These should be added to DL4J, ND4J and DataVec

**Comment by agibsonccc** [comment]
@huitseeker did this
