### ISSUE TITLE
Implement RReLU activation?

### ISSUE THREAD

**Issue by bnsh** [deeplearning4j/deeplearning4j#2147]
Hi. I use RReLU's in my Torch networks... But, it seems to be missing in dl4j... The relevant paper for RReLU is https://arxiv.org/abs/1505.00853 and here is a link to RReLU's docs in Torch: https://github.com/torch/nn/blob/master/doc/transfer.md#rrelu

Basically, just like an ReLU, but in pythonish pseudocode:

```
lo = 1/8
hi = 1/3
if input > 0:
    return input
else if mode == "training":
    return input * uniform_random(lo, hi)
else if mode == "test":
    return input * (lo + hi) / 2.
```

**Comment by AlexDBlack** [comment]
As noted in gitter: this might be a good excuse/opportunity to do some refactoring around activation functions
Specifically: Split activation functions out into their own interface. This will give us:
- Support for custom activation functions (without modifying dl4j/nd4j)
- Activation functions with learnable parameters (like maxout)
- Proper support for activation functions with configuration (like the low/high values in rrelu)
- Support for activation functions with different train vs. test behaviour (like rrelu)

**Comment by raver119** [comment]
RReLu is pretty easy to add, only question is params configuration right now. How you would like to configure them in current meta.

**Comment by AlexDBlack** [comment]
RRelu is nov available here: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/activations/impl/ActivationRReLU.java

This was part of some refactoring for the activation function into classes (with an enum option also).
