### ISSUE TITLE
Scalar multiplication bug in nd4j?

### ISSUE THREAD

**Issue by FelixVoelker** [deeplearning4j/deeplearning4j#2149]
I have some problems with the scalar multiplication of the nd4j cuda backend.

Here are the tests and outputs I ran:

https://gist.github.com/d0fe252184db3d4f5d7741f7743e1463.git

OS: Windows 7
Card: NVIDIA GeForce GTX 770
CUDA: 7.5
ND4J: 0.6.0

This is how I set up the CUDA environment:
CudaEnvironment.getInstance().getConfiguration().allowMultiGPU(true).setMemoryModel(Configuration.MemoryModel.DELAYED);

I get many reflections debug messages like this:
02:09:11.029 [main] DEBUG org.reflections.Reflections - could not scan file org/deeplearning4j/ui/weights/js/todoModel.js in url file:/C:/Users/User/.m2/repository/org/deeplearning4j/deeplearning4j-ui/0.6.0/deeplearning4j-ui-0.6.0.jar with scanner SubTypesScanner

Don't know if these are helpful. If so, I can post all of them.

**Comment by FelixVoelker** [comment]
Problem is solved by removing the Configuration.MemoryModel.DELAYED.

**Comment by FelixVoelker** [comment]
Memory Model was used in response to this issue https://github.com/deeplearning4j/deeplearning4j/issues/1725. However, the use of multiple GPU does not throw an exception for me anymore. But there is definitely a clash between the delayed memory model and ND4J.

**Comment by raver119** [comment]
yea, delayed memory model is going to be removed, because we've got better workaround concept for unknown initial locations.
