### ISSUE TITLE
train google model further with own corpus

### ISSUE THREAD

**Issue by Du-Li** [deeplearning4j/deeplearning4j#2151]
I tried to import google model and train it further with my own corpus. However, it threw an NPE when calling syn1Neg.rows() in line 240 of SkipGram.java. It seems like some data structures like syn1Neg are not initialized with useExistingModel().

**Comment by Du-Li** [comment]
@raver119 I was a bit confused. have you resolved this issue in some way? or is the issue totally irrelevant?

**Comment by raver119** [comment]
You had created 2 issues on 1 problem. I've closed this one, and picked the other one.

**Comment by Du-Li** [comment]
@raver119 okay. thanks.

**Comment by Du-Li** [comment]
I just confirmed that the same issue also existed when importing my own doc2vec model and training it further. Some data structures such as syn1Neg are not initialized with useExisingModel(). So an NPE was thrown in SkipGram.java line 240 when calling syn1Neg.rows().

**Comment by Du-Li** [comment]
so this issue is somewhat related to the other issue #2152 but they are not the same.

**Comment by Du-Li** [comment]
@raver119 it seems these two issues are different. shall we re-open this issue?

**Comment by raver119** [comment]
No, they are not different.
