### ISSUE TITLE
separate hierarchical softmax and negative sampling

### ISSUE THREAD

**Issue by Du-Li** [deeplearning4j/deeplearning4j#2152]
In the DL4J code (SequenceVectors, ParagraphVectors, Word2Vec), we should more cleanly separate the two implementation strategies, HS and NS, and make them configurable.

In addition, I noticed warnings somewhere in your documentation and code against importing Google model because it does not include Huffman tree. By my understanding, we don't need Huffman tree is we use negative sampling. It seems that your code assumes and uses Huffman tree. Separating HS and NS cleanly may make it easier to import google model and train it further.

**Comment by raver119** [comment]
HS/NS are separate now. silent syn1Neg init is in process :)

**Comment by Du-Li** [comment]
I just confirmed that the same issue also existed when importing my own doc2vec model and training it further. Some data structures such as syn1Neg are not initialized with useExisingModel(). So an NPE  was thrown in SkipGram.java line 240 when calling syn1Neg.rows().

**Comment by raver119** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2153

Will be merged a bit later, as usually.

**Comment by Du-Li** [comment]
@raver119 will this fix be part of your next release 0.6.1? when will 0.6.1 be released?

**Comment by agibsonccc** [comment]
Yes. We dont comment on release timelines.
