### ISSUE TITLE
Please support Word2Vec on GPU or spark

### ISSUE THREAD

**Issue by manvendratomar** [deeplearning4j/deeplearning4j#2155]
Please support Word2Vec on GPU or spark.

**Comment by raver119** [comment]
Word2Vec on spark is supported actually.

**Comment by manvendratomar** [comment]
@raver119 so can i use spark with GPU's for word2Vec training?

**Comment by raver119** [comment]
No, only CPU.

To use GPU with w2v and it's derivatives current algorithm should be transformed for CUDA-style parallelism first.

**Comment by manvendratomar** [comment]
Ok peace. Thank you. @raver119.
