### ISSUE TITLE
Please support portability from Spark Word2Vec to local Word2Vec and vice-versa

### ISSUE THREAD

**Issue by manvendratomar** [deeplearning4j/deeplearning4j#2156]
Since i need to train word2Vec model for huge data for once and then i need to train on small batches which i can do locally. So is there a way to convert one type of to another?

**Comment by raver119** [comment]
Technically it's possible without any hacks. Both spark & standalone w2v model consist of 2 main entities: Vocab & LookupTable. So at any given time you're able to save/restore/swap them.

**Comment by manvendratomar** [comment]
But my problem was if i used those vocab and lookuptable and assign it to standalone model, then can i retrain it on new data.
