### ISSUE TITLE
ImagePipelineExample of DL4J-examples always displays the original images

### ISSUE THREAD

**Issue by JieZou1** [deeplearning4j/deeplearning4j#2158]
I am experimenting ImagePipelineExample of DL4J-examples. It seems that ShowImageTransform always displays the original images, instead of transformed 50x50 images. Is this true? And then the comments in the codes are not very accurate?

**Comment by saudet** [comment]
The "before and after" refers only to the `MultiImageTransform` object, not the `RecordReaderDataSetIterator` one. If you could suggest a different way of phrasing that, please send a pull request, and we will be happy to merge it! Thanks
