### ISSUE TITLE
DL4j/ND4j unstable on Mac

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#2161]
It looks like silent stack corruption happens somewhere with nd4j-native. To be fixed asap.

**Comment by treo** [comment]
If I remember correctly there were people who said that they have that problem with Apple's BLAS implementation but not with OpenBLAS. Not sure if that is a related problem, but wanted to mention it anyway.

**Comment by raver119** [comment]
I think that's another issue, it's reproducible for Susan only with 0.6.1

5 окт. 2016 г. 12:26 пользователь "Paul Dubs" <notifications@github.com>
написал:

**Comment by saudet** [comment]
@eraly Does it happen with both OpenBLAS and Accelerate (Apple's default BLAS that gets used by CMake if OpenBLAS isn't installed)?

**Comment by raver119** [comment]
It's reproducible for me on Mac too, just confirmed it. Running without
OpenBLAS

5 окт. 2016 г. 13:35 пользователь "Samuel Audet" <notifications@github.com>
написал:

**Comment by raver119** [comment]
I can provide crash logs, sure, but two crashes i've been able to reproduce,happened in different places within nd4j-tests, with different info in dump.

**Comment by raver119** [comment]
Right, that's not blas-related. At least one of +- reproducible tests sets causing crash is this one:

https://github.com/deeplearning4j/nd4j/blob/9b8539acec5d332d11f255c4bfac56a3db083c8e/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/api/ndarray/TestSerializationFloatToDouble.java

In this case crash looks like this:

```
15:33:37,561 INFO  ~ Running org.nd4j.linalg.api.ndarray.TestSerializationFloatToDouble on backend org.nd4j.linalg.cpu.nativecpu.CpuBackend
The data type is DOUBLE
15:33:37,988 WARN  ~ Loading a data stream with type different from what is set globally. Expect precision loss
java(64074,0x70000e9c5000) malloc: *** error for object 0x7fa0a656f9b8: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
AFTER DATATYPE HERE: FLOAT
```

**Comment by saudet** [comment]
The problem is probably there on Linux as well, just not causing a crash. Running that through Valgrind is probably a good idea.

**Comment by raver119** [comment]
Yep, agreed.

5 окт. 2016 г. 15:43 пользователь "Samuel Audet" <notifications@github.com>
написал:

**Comment by raver119** [comment]
Issue seems to be fixed now. Neither originally localized tests or "Run All Tests" causing crash anymore.

**Comment by raver119** [comment]
... for me. But still crashing for Susan.

**Comment by raver119** [comment]
False flag. Issue is fixed to Susan as well.

**Comment by dmmiller612** [comment]
I am seeing this issue when running spark locally, just in the last day. It didn't happen in the past, and I am wondering if there is something I can do to address the problem? I am also running on a mac as well.

**Comment by agibsonccc** [comment]
@dmmiller612 Mind opening a new issue with way more details please?
