### ISSUE TITLE
Word2Vec models differ from one build to another 

### ISSUE THREAD

**Issue by mikegwf1** [deeplearning4j/deeplearning4j#2162]
Using the build configuration below and the same input corpus, successive runs of word2vec produce different models.  This is using 0.6.0 - I dont know what the behavior was in previous versions:

        Word2Vec vec = new Word2Vec.Builder()
                .minWordFrequency(5)
                .iterations(1)
                .learningRate(0.025)
                .layerSize(150)
                .seed(42)
                .sampling(0)
                .negativeSample(5)
                .windowSize(10)
                //.useAdaGrad(true)
                .useAdaGrad(false)
                .iterate(iter)
                .workers(4)
                .tokenizerFactory(t)
                //.elementsLearningAlgorithm(new CBOW<VocabWord>())
                .elementsLearningAlgorithm(new SkipGram<VocabWord>())
                .build();

**Comment by raver119** [comment]
Hypothetically fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2153

Will be merged a bit later, as usually.
