### ISSUE TITLE
Improve Autoencoder Performance

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#2163]
Autoencoders like DropConnect need to corrupt their inputs, currently this is still done through Apache Commons math. I guess that it shoud be possible to move this into native ops instead.

![image](https://cloud.githubusercontent.com/assets/509379/19193018/a5d1fcc8-8ca8-11e6-9c51-2af9fa476d76.png)

**Comment by raver119** [comment]
I think this issue isn't relevant anymore.
