### ISSUE TITLE
The activation functions should be enums

### ISSUE THREAD

**Issue by SadatAnwar** [deeplearning4j/deeplearning4j#2164]
I know I am saying this out way too late, but should you consider making the activation functions as enums? Or some sort of constants? No point keeping them as strings. I thought of creating a PR and doing it my self, but the project has moved so far ahead (1310 commits) and now so is ND4J it will take me a while just to update everything

**Comment by agibsonccc** [comment]
This jives us maybe doing custom activations actually. Thank for bringing this up. We've done

**Comment by AlexDBlack** [comment]
Right. See comments here: https://github.com/deeplearning4j/deeplearning4j/issues/2147

**Comment by AlexDBlack** [comment]
Activation functions have been refactored into classes, with an enum option for the config:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/activations/Activation.java

https://github.com/deeplearning4j/deeplearning4j/pull/2538
https://github.com/deeplearning4j/nd4j/pull/1530

**Comment by SadatAnwar** [comment]
Like! 👍
