### ISSUE TITLE
NLP Feature - Is this Word2Vec impl online/incremental or could it be?

### ISSUE THREAD

**Issue by owlmsj** [deeplearning4j/deeplearning4j#217]
Dont know much about the algorithm itself, but these kind of feature would be great.

**Comment by agibsonccc** [comment]
To start the discussion, we can do this with streaming. Not sure about changing the vocab though. In the case of the vocab, we would need to add new rows to the weight matrices.

**Comment by chrisvnicholson** [comment]
incremental is now implemented: https://github.com/deeplearning4j/deeplearning4j/pull/895

**Comment by raver119** [comment]
Online implementation is in the implementation process, and should be ready soon(tm)
