### ISSUE TITLE
java.io.FileNotFoundException: ... (Too many open files)

### ISSUE THREAD

**Issue by ambraspace** [deeplearning4j/deeplearning4j#2179]
I'm getting this error when trying to train a simple CNN. Training data consist of two classes, one with 26100 images (positive samples) and 261.000 images (negative samples).
The images are in separate folders named "0" and "1" under parent folder "detection". Images are grayscale JPGs.

Here's the code:

`	public static void main(String[] args) {
		
		double bestF1 = 0.5f;
		
		int imageWidth = 13;
		int imageHeight = 13;
		int channels = 1;
		int outputNum = 2;
		int numEpochs = 100;
		int batchSize = 100;
		int rngSeed = 123;
		int iterations = 1;
		
		RecordReader rr = new ImageRecordReader(imageHeight, imageWidth, channels, new ParentPathLabelGenerator(), 256.0);
		
		try {
			rr.initialize(new FileSplit(new File("detection"), null, true));
		} catch (IOException e) {
			e.printStackTrace();
			return;
		} catch (InterruptedException e) {
			e.printStackTrace();
			return;
		}		

		// Try to count how many examples are there in the RecordReader
		int j=0;
		while (rr.hasNext()) {
			j++;
			rr.next();
			System.out.println(j);
		}
`

I usually get errors after 4000 open files.

`java.io.FileNotFoundException: detection/0/04035-144-96.jpg (Too many open files)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.datavec.image.loader.NativeImageLoader.asMatrix(NativeImageLoader.java:194)
	at org.datavec.image.recordreader.BaseImageRecordReader.next(BaseImageRecordReader.java:204)
	at com.ambraspace.recognition.dl4j.Net12detection.main(Net12detection.java:68)`

**Comment by raver119** [comment]
Right, FileInputStream wasn't closed :(

I've merged fix.

Thanks for highlighting.
