### ISSUE TITLE
Data starvation diagnostics

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#2181]
It should be nice to have basic data starvation diagnostics for training time, to help people to find & identify bottlenecks.

**Comment by raver119** [comment]
Also: https://github.com/deeplearning4j/deeplearning4j/issues/2182

**Comment by agibsonccc** [comment]
Doesn't the PerformanceListener take care of this now?

**Comment by raver119** [comment]
Yep, safe to close :)
