### ISSUE TITLE
Training loop spends much more time fetching data than fitting it.

### ISSUE THREAD

**Issue by jgainesau** [deeplearning4j/deeplearning4j#2182]
Working with a plain vanilla MLP, reading records from a file via a CSVRecordReader.

GPU utilization mostly sits at zero percent, spiking up to 40% for a few seconds now and then.

System specs: 1 GTX 960 GPU w/4GB RAM, 16GB RAM and core i7 on host.

Training dataset has 1,190 features and around 200K examples.

With a batch size of 5000, it seems as if the GPU is being starved of data:

016-10-17 21:54:01,716 INFO c.p.a.Preprocess - Working with 1190 features; batch size 5000
2016-10-17 21:54:20,295 INFO c.p.a.Preprocess - Fetch time: 5277; fit time: 269
2016-10-17 21:54:25,090 INFO c.p.a.Preprocess - Fetch time: 4654; fit time: 141
2016-10-17 21:54:29,557 INFO c.p.a.Preprocess - Fetch time: 4303; fit time: 163
2016-10-17 21:54:34,108 INFO c.p.a.Preprocess - Fetch time: 4387; fit time: 164
2016-10-17 21:54:38,674 INFO c.p.a.Preprocess - Fetch time: 4398; fit time: 168
2016-10-17 21:54:43,205 INFO c.p.a.Preprocess - Fetch time: 4363; fit time: 168
2016-10-17 21:54:47,678 INFO c.p.a.Preprocess - Fetch time: 4309; fit time: 163
2016-10-17 21:54:52,481 INFO c.p.a.Preprocess - Fetch time: 4630; fit time: 173

So fetching is taking roughly 40x longer than fitting

Reducing the batch size to 50-75 gets the fetch time roughly aligned with the fit time (30-40ms for both), but there's probably not much parallelism on the GPU at those batch sizes.

It would be great if fetching could keep up with fitting, or at least if there was better tooling to help diagnose this.

**Comment by jgainesau** [comment]
https://gist.github.com/jgainesau/75ce13f9ac36252c1067686861c4dfa2

**Comment by AlexDBlack** [comment]
So I guess we need YourKit/VisualVM to confirm, but my guess would be CSV parsing...
about ~1ms per line to read, parse, and create Writable objects then convert to an NDArray for 1190 features doesn't sound that unreasonable...
Still a bottleneck, however.

If it's actually that we can possibly utilize NDArrayWritable instead, to skip the intermediate Writable object creation. Native/parallel *might* be viable here for parsing (though we can just prefetch + batch to make it worth the native call)


@jgainesau in the mean time: one workaround might be to use DataSet.save(File) and then use this:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/ExistingMiniBatchDataSetIterator.java
For multiple epochs, at least you'll only be parsing your data once.

**Comment by raver119** [comment]
Yea, that's quite possible. But this issue also overlaps with my current issue with "high number of copies over PCIe" for batches, so i want to check for similar issues in other places.

**Comment by AlexDBlack** [comment]
Right
BTW, if we want to get *really* crazy here... https://github.com/antonmks/nvParse
:)

**Comment by raver119** [comment]
:)

**Comment by jgainesau** [comment]
@AlexDBlack thanks for the suggestion.

I found another iterator called DoublesDataSetIterator. Loading up all the data into one of these makes the fetch time go to zero no matter how large the batch is.

E.g. replace lines 8-14 of the gist with:

```
final trainingDoubles = []
init.processedTrainData.eachLine { line ->
        final split = line.split(',').collect { it as double }
        trainingDoubles.add(new Pair(split[0..numFeatures-1] as double[], [split[-1]] as double[]))
}
final trainingIterator = new DoublesDataSetIterator(trainingDoubles, batchSize)

final testDoubles = []
init.processedTestData.eachLine { line ->
        final split = line.split(',').collect { it as double }
        testDoubles.add(new Pair(split[0..numFeatures-1] as double[], [split[-1]] as double[]))
}
final testIterator = new DoublesDataSetIterator(testDoubles, batchSize)
``` 

I think that class and the other extensions of AbstractDataSetIterator have some limitations, but from what I can see, they suggest some possible optimizations.

RecordReaderDataSetIterator, for instance, seems to do a *lot* of work for *every* record, on *every* call to next(), in the getDataSet method. A lot of that work seems to be related to figuring out what kind of data we're working with. There might be optimizations in cases where (for instance) all the data consists of doubles.

**Comment by raver119** [comment]
How that change affects utilization?

**Comment by jgainesau** [comment]
It still rarely gets higher than 40%, but it stays pegged there rather than sitting mostly at zero and spiking up every so often.

Memory usage on the GPU is about the same, maybe a bit higher - 900MB or so instead of 800MB.

**Comment by raver119** [comment]
Great, thanks.

**Comment by raver119** [comment]
jfyi: that change shouldn't affect memory use in any way, because memory gets consumed by request + cache factor. So your tweak for better data feeding doesn't change actual memory use. Only loops become faster.

**Comment by AlexDBlack** [comment]
BTW, can you confirm the versions you are using? 0.6.0 for DL4J/ND4J/DataVec?

**Comment by jgainesau** [comment]
Yes, 0.6.0 for both.

**Comment by jgainesau** [comment]
FWIW, before I stumbled across the DoublesDataSetIterator, I wrote a custom record reader that read the whole file into memory as a byte array. 

This made no difference to the amount of time to fetch data. 

I guess this supports the idea that the culprit is the CSV parsing and the stuff downstream of that.
