### ISSUE TITLE
Implement Threshold Layer

### ISSUE THREAD

**Issue by jbaker-dstl** [deeplearning4j/deeplearning4j#2185]
Torch has the concept of a Threshold layer, which will change values in a tensor that fall below a given threshold value. For instance, this could change small values (below 1e-6) to zero (or to a minimum value).

Implementation of this layer in DL4J would allow for easier conversion between Torch and DL4J.

The Threshold layer code is at https://github.com/torch/nn/blob/master/Threshold.lua, and there is also a discussion of how it works at https://groups.google.com/forum/#!topic/torch7/iHL9eL3Iva4

**Comment by raver119** [comment]
So that's basically RELU layer without matmul.

It can be implemented using SameDiff now. I dont think there's any need in individual layer for that.
