### ISSUE TITLE
SentenceIterator over java.sql.ResultSet

### ISSUE THREAD

**Issue by nzv8fan** [deeplearning4j/deeplearning4j#2195]
In the last few weeks I've been playing with locally building word2vec models. 

To do this I have dumped a set of data out of a postgres database into a file to use with dl4j's word2vec example code. However, longer term I would like to train a model by directly iterating over examples in a set of database results. 

Is there an implementing class of SentenceIterator that uses a java.sql.ResultSet or similar. 

If not I'll build one myself and happy to contribute it back here if it would be helpful to the project overall.

**Comment by agibsonccc** [comment]
No there's not. We'd be happy to take a PR though.

**Comment by raver119** [comment]
I'm closing this one, since PR is already merged.
