### ISSUE TITLE
Support for convolutional layers with dynamic input sizes

### ISSUE THREAD

**Issue by gewoonrik** [deeplearning4j/deeplearning4j#2206]
I'd love to have support for convolutional layers with dynamic input sizes. (as described in https://arxiv.org/pdf/1404.2188.pdf?utm_medium=App.net&utm_source=PourOver)
This would also include dynamic pooling.

**Comment by AlexDBlack** [comment]
Yep. And we support fully convolutional (variable output size) with CnnLossLayer now.
