### ISSUE TITLE
ComputationalGraph and ParallelWrapper

### ISSUE THREAD

**Issue by fac2003** [deeplearning4j/deeplearning4j#2209]
Computational graphs support multiple inputs and outputs.
ParallelWrapper provides training on multiGPU boxes.
Unless I am missing something, ParallelWrapper does not support training computational graphs (up to 0.6.0). The capability would be useful to train computational graphs on multi-GPU boxes (I assume spark with GPU supports this).

**Comment by agibsonccc** [comment]
Yes it does just cast model to computation graph:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/parallelism/ParallelWrapper.java

**Comment by raver119** [comment]
Sorry, MultiDataSets training was missed initially. But it's already available on current master.

**Comment by fac2003** [comment]
Looks like we will have to wait until 0.7 for this capability. It is in master, but not in 0.6.0.

**Comment by raver119** [comment]
That's exactly what i've said, right.

**Comment by raver119** [comment]
Btw, nothing could stop you from copying that class from current master, and inject it manually to your project. It's self-containing.

**Comment by fac2003** [comment]
That's a good point. Thanks.
