### ISSUE TITLE
nd4j-api-0.0.3.5.5.3-SNAPSHOT.jar  this package in mvn repository  is out of date

### ISSUE THREAD

**Issue by snowlord** [deeplearning4j/deeplearning4j#221]
nd4j-api-0.0.3.5.5.3-SNAPSHOT.jar  this package in mvn repository  is out of date

nd4j-api-0.0.3.5.5.3-SNAPSHOT.jar
the package in server repository org.nd4j.linalg.api.ndarray SliceOp has two methods. 
nd4j-api-0.0.3.5.5.3-SNAPSHOT.jar
the package i compiled it by myself  nd4j org.nd4j.linalg.api.ndarray SliceOp has only method
because of the difference of the upper.so i can't compile sucessfully.

it shows SliceOp is abstract class.

how do i do?

**Comment by agibsonccc** [comment]
Install from source for now please.

**Comment by snowlord** [comment]
it still does't work. deeplearning4j version  is 0.0.3.3.3.alpha1-SNAPSHOT.

**Comment by agibsonccc** [comment]
Could you tell me how you're compiling it? You're not giving me anything to go on here. Are you building nd4j and canova from source followed by deeplearning4j? I have a setup.sh with the commands you need to run in the root directory.
