### ISSUE TITLE
softmax not summing to 1.0

### ISSUE THREAD

**Issue by Joshuaalbert** [deeplearning4j/deeplearning4j#2210]
Very simply I'm getting that the sum of the outputs of a softmax layer is not equal to 1.0.

**Comment by raver119** [comment]
Can i see sample code that reproduces this issue?

**Comment by Joshuaalbert** [comment]
It's a fairly complicated code, and extracting one piece isn't straightforward. I can try putting together a piece that I think will reproduce it.

**Comment by raver119** [comment]
That would be very nice of you, because right now i see from tests - it works properly.

I.e tests here: https://github.com/deeplearning4j/nd4j/blob/cef913fec0f9788908ddf04f2077c2a9294aee60/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/ops/OpExecutionerTestsC.java#L351-L351

So i'd like to see reproducible code that breaks it.

**Comment by Joshuaalbert** [comment]
Working on it

**Comment by Joshuaalbert** [comment]
Okay, where shall I put it for you to run?

**Comment by raver119** [comment]
https://gist.github.com

**Comment by Joshuaalbert** [comment]
https://gist.github.com/Joshuaalbert/d5b397d72fde26415c137682f8ff0f3c

**Comment by Joshuaalbert** [comment]
Anyone able to run that?

**Comment by agibsonccc** [comment]
@Joshuaalbert we'll get to this before the next release. As raver mentioned we have tests covering this.

**Comment by raver119** [comment]
I plan this particular issue for later time today. It's nr.3 in my queue.

**Comment by Joshuaalbert** [comment]
Thanks guys

**Comment by AlexDBlack** [comment]
```java
confBuilder.addLayer("output", new GravesLSTM.Builder()
	.nIn(conf.numSumNodes).nOut(numOutput)
	.activation("softmax").build(), "sumLayer"+(conf.numSumLayers-1));
```

This isn't possible. You can't and shouldn't apply softmax as the activation function for a LSTM.
Check figure 1 here: you are setting G and H to softmax.
https://arxiv.org/pdf/1503.04069v1.pdf
Note the element-wise multiplication with the sigmoids: even if the softmax works exactly as you expect there, that element-wise multiplication means that the output will (almost) never sum to exactly 1.

What I would suggest instead: add a DenseLayer + Softmax above your LSTM layer. You'll need a preprocessor to handle that transition - that should be added automatically as you are already using setInputType.

**Comment by Joshuaalbert** [comment]
Oh course! Thanks, and glad it's that simple.

**Comment by Joshuaalbert** [comment]
Also in this case because I'm not using RNNOutputLayer, it doesn't have 3d output. The transition to DenseLayer from 3d->2d is  set but the output isn't 3d. I'll open a new issue.
