### ISSUE TITLE
Update RBM UI functionality to new UI implementation

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2213]
Previously: UpdateActivationsIterationListener and UpdateFilterIterationListener were available for 
With the UI refactoring here (https://github.com/deeplearning4j/deeplearning4j/pull/2169) these will no longer be available.

So: update and add back in RBM training functionality, as per (for example) http://yosinski.com/media/papers/Yosinski2012VisuallyDebuggingRestrictedBoltzmannMachine.pdf

**Comment by eraly** [comment]
We can close this
