### ISSUE TITLE
IllegalArgumentException during training.

### ISSUE THREAD

**Issue by keskella** [deeplearning4j/deeplearning4j#2217]
I get a strange error when fitting my RNN, 

IllegalArgumentException: A rows must equal C rows. MMul attempt: [975, 300]x[300, 1200]; result array provided: [416, 1200]

java.lang.IllegalArgumentException: A rows must equal C rows.

This gist has stacktrace,.
https://gist.github.com/keskella/e0a337a54e7d4bed0f3cc44baced45cb

this gist has example of the data. The error happened several hours in to the training period, after having gone through the data with csvsequencerecordreader.
https://gist.github.com/keskella/d46657c1411656d42dc6c9cc89bb3f9e

this gist has the code.
https://gist.github.com/keskella/18a59638995e3d937022571fae8ff723

**Comment by AlexDBlack** [comment]
My best guess here: this is a problem with how you are using rnnTimeStep.
Specifically, only way I can see this occurring is if you aren't properly calling rnnClearPreviousState() between iterations.
That is, you are doing rnnTimeStep with some minibatch size, and then feeding it new data with a different minibatch size.

https://deeplearning4j.org/usingrnns#rnntimestep
"However, if you want to start making predictions for a new (entirely separate) time series: it is necessary (and important) to manually clear the stored state, using the MultiLayerNetwork.rnnClearPreviousState() method. This will reset the internal state of all recurrent layers in the network."

https://gist.github.com/keskella/18a59638995e3d937022571fae8ff723
Looking at line 103 here: you should probably be using output, not rnnTimeStep.
