### ISSUE TITLE
Include a copy of the AL 2.0 license in all jars

### ISSUE THREAD

**Issue by kottmann** [deeplearning4j/deeplearning4j#2223]
Deeplearning4j is licensed under AL 2.0 and to comply with the license it would be good include a copy of the license itself in all distributables.

As far as I can see DL4J distributes jars via remote repositories and those jars currently don't contain the license.

I couldn't figure out how to just include the LICENSE file in the root directory of this git repository.
One solution to share one LICENSE file is the remote resource plugin and place shared files in a new deeplearing4j-build-resoruces module.

The approach is described here in detail [1] at the end. The article is quite old but as far as I know it still applies today.

You might want to consider to create a new repository for deeplearning4j-builld-resources to be able to include this in all the repositories you have e.g. also nd4j.

[1] http://blog.sonatype.com/2008/04/how-to-share-resources-across-projects-in-maven/

**Comment by kottmann** [comment]
I did the update to the parent pom now and also created the deeplearing4j-build-resources module. If they are in the same project there are issues with cyclic a dependency. I am not sure how this can be resolved. At Apache UIMA we release the build resources separately if they change from time to time to get around this issue.

Anyway, I believe in your case you need the deeplearning4-build-resources in a separate repository so it can be used by all the builds in the different repositories you have. 

Please review it here: 
https://github.com/kottmann/deeplearning4j/tree/2223

**Comment by agibsonccc** [comment]
We do something similar like this for tests with a dl4j-test-resources. I wouldn't be against a second repo.

**Comment by agibsonccc** [comment]
@kottmann https://github.com/deeplearning4j/deeplearning4j-build-resources

**Comment by agibsonccc** [comment]
@kottmann since you guys are looking at adding dl4j now, the(apache tika already has as of last month) is there anything we should revisit here?

**Comment by huitseeker** [comment]
Fix in https://github.com/deeplearning4j/deeplearning4j-build-resources/pull/1

**Comment by raver119** [comment]
I think we can close this this issue now? 

cc @agibsonccc

**Comment by agibsonccc** [comment]
I...think so? The headers I think make it compliant?

**Comment by raver119** [comment]
Cool!
