### ISSUE TITLE
IterationListeners  not producing results when passed to loaded trained model

### ISSUE THREAD

**Issue by anandkoirala** [deeplearning4j/deeplearning4j#2227]
When i pass the savedNetwork.setListeners(new ConvolutionalIterationListener(1)); to a model that was saved and re-loaded for prediction, there is no hearing from listeners..

**Comment by agibsonccc** [comment]
You can call onModel manually. This is all the fit() call does internally after it does an update.

**Comment by AlexDBlack** [comment]
Right, listeners are only called during training - not normal (test time) forward pass.
I'll close this, unless your are doing more training on your network?
