### ISSUE TITLE
OutOfMemoryError ParagraphVectors

### ISSUE THREAD

**Issue by Treiblesschorle** [deeplearning4j/deeplearning4j#2234]
Since I switched from 0.5.0 to 0.6.0 I'm getting OutOfMemoryErrors for the same code using Word2Vec on Linux. On Windows it works fine.

Word2Vec Config:
https://gist.github.com/Treiblesschorle/fa0af0df8105562271e6ec47c8f9bcb3

Error:
https://gist.github.com/Treiblesschorle/edc768ae4e3f9a8fd63b956c1a0ad21a

I'm training on the "raw_sentences.txt" from the DL4J Word2Vec examples. Xmx is 3g.

**Comment by agibsonccc** [comment]
Could you try just adding more heap space? We haven't done anything significant that would warrant that. We respect Xmx and do our own  memory management.

**Comment by raver119** [comment]
Show full source code. Something else has to be wrong.

**Comment by Treiblesschorle** [comment]
Full source code is mostly KNIME stuff, I will try to isolate some code and post it here.

**Comment by raver119** [comment]
Ok. Can you please try current master w2v and confirm it's still an issue, because w2v/paravec were migrated to native code recently.

**Comment by Treiblesschorle** [comment]
The current master seems to fix the problem.

**Comment by Treiblesschorle** [comment]
The problem occurred again. This time on Windows, too.

Code to reproduce on Windows:
https://gist.github.com/Treiblesschorle/2e67ed32e4255b89cfa6eeafabec6b96
using -Xmx500m and 0.7.1

Error:
https://gist.github.com/Treiblesschorle/2e32d9ae989c6d246cd46857586a3dd7

**Comment by raver119** [comment]
Please set .batchSize to something like 384, and run again

**Comment by Treiblesschorle** [comment]
Choosing a higher batchSize solved the issue for the mentioned configuration, however, I still have some problems. I ran some further tests. When training several ParagraphVector models at the same time for some iteration it eventually throws an OutOfMemoryError.

Code to reproduce:
https://gist.github.com/Treiblesschorle/571070036dd8cb8c5ee043ac1ee85bf1
and
https://gist.github.com/Treiblesschorle/7be815febfb3f23d150000a02387a5cd
using -Xmx620m and 0.7.2 on Linux

Error:
https://gist.github.com/Treiblesschorle/923274ac48ecdd30aa8b4daed74b6406

**Comment by raver119** [comment]
Hmm, i've never thought about training w2v/d2v in that way. I should check that.

**Comment by Treiblesschorle** [comment]
Is there any news on this?

**Comment by raver119** [comment]
Spent 5 hours running similar code in loop, however without 620MB limitation, no issues.

So i'm tending to say it's not a leak or something, in worst case it's case of higher-then-desired memory footprint. I'll keep investigating in that direction.
