### ISSUE TITLE
Jackson exception with Spark early stopping training

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2237]
Reported by @tombear1 on gitter:

https://gist.github.com/tombear1/bff764a4c97cbbf3d45f9b6aedc2dfa4

https://gist.github.com/tombear1/10aeead8efb6d2d69c5c48daf68ebad7

**Comment by tombear1** [comment]
Affects 0.6.0
Seems to be fixed in 0.6.1

**Comment by AlexDBlack** [comment]
Shading of Jackson libraries seems to have fixed this.
