### ISSUE TITLE
Unit test/CI unit test failures

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2240]
**Unit test failures on master**

**deeplearning4j-core
~~testGradientCnnFfRnn -> should pass, just small gradients/precision issue~~
MultiLayerTest.testOutput, testPredict -> exception     - intermittent? (passing when run in isolation)
MultipleEpochsIteratorTest.testCifarDataSetIteratorReset -> exception   -   intermittent? (passing when run in isolation)
~~ConvolutionLayerSetupTest.testMnistLenet~~
~~BackTracklineSearchTest.testBackTrackLineHessian~~
TestComputationGraphNetwork.testCGEvaluation
~~WeightInitUtilTest.testXavier~~
(first 3 are CIFAR iterator related?)

**deeplearning4j-spark**
All passing.

**deeplearning4j-nlp**
All passing.

**deeplearning4j-nlp-uima**
~~~Word2VecTests.testLoadingWordVectors - > java.io.FileNotFoundException:~~~ 

Otherwise all passing.

Note however that there are some tests failing on Jenkins that are not failing locally (will update once the above PR has run)

**Comment by raver119** [comment]
Hm. I've probably missed something, w2v serializer tests (those in nlp-uima) are passing for me locally. I'll take a look at morning.

**Comment by nyghtowl** [comment]
I'll look at the ones that appear Cifar in the morning.

**Comment by nyghtowl** [comment]
Its not about Cifar in those cases. I'm also getting intermittent errors on TestComputationGraphNetwork.testCGEvaluation and recently got a failure on which seems intermittent:

WeightInitUtilTest.testXavier
TestVariableLengthTSCG.testVariableLengthSimple
TestVariableLengthTS.testVariableLengthSimple

**Comment by raver119** [comment]
test with missing file is fixed

**Comment by nyghtowl** [comment]
I pulled cifardataset iterator from the tests in order to help simplify the focus.
