### ISSUE TITLE
NPE on LSTM Spark Training

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2242]
https://gist.github.com/avkumar/06d865e7e7441d01745b580dfc81bff2

Stack trace:
https://gist.github.com/avkumar/117c4320166721af9f26becc22c208c0

**Comment by AlexDBlack** [comment]
So running this locally using 0.6.0 (only modification is paths for data): I'm not getting any issues. Output is shown in the gist below.

@avkumar can you confirm the version you are using? 0.6.0?
I'll need to reproduce this before I can debug it.

https://gist.github.com/AlexDBlack/c5f0ae860943c867f61ecc46a9cf3608

**Comment by avkumar** [comment]
@AlexDBlack  
https://gist.github.com/avkumar/0673d057c63d89760cc9a4da4bddc485

**Comment by AlexDBlack** [comment]
Is this using the exact same data you gave me? Because again, it runs fine, but is only doing 33 splits...
Checking the line numbers on 0.6.0, looks like the parameters vector is returning null. The only way I can think that could occur is if not a single one of the executors get any data - which, given the way splitting is done, should be impossible...

Again, I need to reproduce this before I can debug it.

**Comment by avkumar** [comment]
Yes. It is exactly the same data and exactly the same code. 
Can it be because of too many partitions in my case?
Since i am running on linux VM, I have only one core. Default number of workers which is 1.

**Comment by AlexDBlack** [comment]
As noted on gitter - I was able to reproduce this by setting the number of workers to 1. (which as I said is a bad idea for a lot of reasons).
So confirmed this as an edge case bug - thanks. I'll get that fixed soon. Not sure there's much you can do on your ond, other than increasing the number of workers > 1 (or not using spark training).

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2256
But note this also: https://github.com/deeplearning4j/deeplearning4j/issues/2257
