### ISSUE TITLE
Null Pointer Exception when running dl4j-spark unit tests

### ISSUE THREAD

**Issue by tombear1** [deeplearning4j/deeplearning4j#2245]
Null Pointer Exception when running dl4j-spark unit tests using current 0.6.1 master (30-10-16)
java.lang.NullPointerException
at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingWorker.processMinibatch(ParameterAveragingTrainingWorker.java:125)
https://gist.github.com/tombear1/7a142c15b6bfbbd64871051757fd77a5

might be the same as https://github.com/deeplearning4j/deeplearning4j/issues/2242

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2246
https://github.com/deeplearning4j/deeplearning4j/issues/2242 is likely a different issue.
