### ISSUE TITLE
Convolutional layer working with text sequences

### ISSUE THREAD

**Issue by jsteggink** [deeplearning4j/deeplearning4j#2258]
Something I've been trying to get to work with DL4J is having a convolutional layer for text sequences. I'm not sure if it's possible at all at this moment. If it is, it would be great if someone could make an example. If not, then it's a feature request. I know the max pooling over time is not supported yet, so the focus of this issue would be on the sequence to CNN part.

Simple example:
text sequence input (characters or embeddings) -> CNN -> max pooling over time -> RNN -> sequence output

**Comment by AlexDBlack** [comment]
Now possible; example here will be merged on next release: https://github.com/deeplearning4j/dl4j-examples/pull/353
