### ISSUE TITLE
doc2vec training is not utilizing full processing power of a virtual machine

### ISSUE THREAD

**Issue by HiranD** [deeplearning4j/deeplearning4j#2264]
In a virtual machine that is having 20 cores overall CPU (intel Xeon 2GHz) utilization is around 20% when training a word2vec model.. is there any way to utilize it fully... 
and config is..
```
paragraphVectors = new ParagraphVectors.Builder()
			.learningRate(0.025)
			.minLearningRate(0.001)
			.batchSize(100)
			.minWordFrequency(1)
	                .iterations(1)
			.epochs(20)
			.layerSize(100)
			.windowSize(5)
			.stopWords(new ArrayList<String>(stopwords))
			.iterate(iterator)
			.trainWordVectors(true)
			.tokenizerFactory(tokenizerFactory)
			.build();

paragraphVectors.fit();
```
![1](https://cloud.githubusercontent.com/assets/17349959/19961724/167d5b70-a1da-11e6-9146-cf1deba9e428.png)
![2](https://cloud.githubusercontent.com/assets/17349959/19993510/44fd7af6-a26c-11e6-9309-b8d58f6eeee6.png)
![3](https://cloud.githubusercontent.com/assets/17349959/19993699/9cce6f1e-a26d-11e6-89c5-19f5bbfcf2f3.png)

**Comment by raver119** [comment]
Word2Vec & Doc2Vec got an overhaul, and in next release performance will be significantly higher.
