### ISSUE TITLE
Word2Vec Performance in Spark

### ISSUE THREAD

**Issue by jobernberger** [deeplearning4j/deeplearning4j#2272]
I've been testing the word2vec implementation with a spark cluster that includes 36 datanodes.  Each node is not identical, but all are are at least 96G RAM and are 2 CPU systems with 6 cores each that are hyperthreaded so the OS sees 24 cores.  Most CPUs are in the E5-2640 range.

I've been running inside of spark with:
spark-submit --class com.ngc.bigdata.word2vecmodelbuilderspark.ModelBuilder --master yarn --deploy-mode client --driver-memory 8g --executor-memory 8g --executor-cores 1 --num-executors 32 /home/joeo/Word2VecModelBuilderSpark-1.0-SNAPSHOT.jar

The code reads in a text file that is a bunch of sentences - one per line all lower case.  This particular file is 42MBytes.
corpus = sparkContext.textFile("hdfs://cordelia:8020/clusterTest/output.txt.finalPhrase", 32);
This produces 32 partitions.
I then run:
Word2Vec word2Vec = new Word2Vec.Builder()
                .setNGrams(1)
                .tokenizerFactory(t)
                .seed(42L)
                .negative(25)
                .useAdaGrad(false)
                .layerSize(150)
                .windowSize(5)
                .learningRate(0.025)
                .minLearningRate(0.0001)
                .iterations(1)
                .batchSize(200)
                .minWordFrequency(5)
                .stopWords(Arrays.asList("three"))
                .useUnknown(true)
                .build();

In contrast to the 'C' version of word2vec:
time ./word2vec -train output.txt.finalPhrase -output output.txt.finalPhrase.bin1 -cbow 0 -size 200 -window 5 -negative 25 -hs 0 -sample 1e-5 -threads 24 -binary 1 -iter 1
The 'C' version takes 17 seconds to run on a single server.
The dl4j version takes 9 minutes 10 seconds to run on 32 machines.  Nearly all the time is spend in the collect at Word2Vec.java:207 (taking 6.4 min).

I've also noticed that when I increase the size of the corpus to 1.9G, I get OutOfMemory errors.  For this file I use word2phrase to create phrases:
Words processed: 327000K Vocab size: 25960K

ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Container killed by YARN for exceeding memory limits. 9.0 GB of 9 GB physical memory used. Consider boosting spark.yarn.executor.memoryOverhead.
This is with 12g for driver-memory and 8g for executor.  With 21g of RAM, I get this error:
Job aborted due to stage failure: Total size of serialized results of 11 tasks (2.1 GB) is bigger than spark.driver.maxResultSize (2.0 GB)

**Comment by agibsonccc** [comment]
This has been fixed with the latest PR I believe?
