### ISSUE TITLE
Document new LossLayer and Vertices for ComputationGraph

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#2276]
New ComputationGraph functionality will soon be available via https://github.com/deeplearning4j/deeplearning4j/issues/2275. This includes a parameterless `LossLayer` and vertices for performing triplet loss.

This opens up a lot of new functionality and configurations of ComputationGraph. It's worth adding this to the documentation, and we need to better understand how it will benefit users.

**Comment by tomthetrainer** [comment]
@crockpotveggies I added a comment at the top of this page. 
https://deeplearning4j.org/compgraph

As for understanding how this will benefit users? How do we go about that? Do you want me to ask for feedback to gitter channel from that page, or create a ticket for comments, or was it a Rhetorical comment. 

Leaving open if you have feedback on

**Comment by crockpotveggies** [comment]
Looks great to me :)

Regarding benefitting users, I was thinking we add a small paragraph about how these graph vertices have been used in the wild. For example, these vertices were used for Triplet Training, and triplets wouldn't exist without them.

**Comment by tomthetrainer** [comment]
Will reading this

http://crockpotveggies.com/2016/11/05/triplet-embedding-deeplearning4j-facenet.html

give me what I need to know to add that paragraph? 

Blog post, news page, content in release-notes might be other ways to let the base know.

**Comment by crockpotveggies** [comment]
Yes, I believe this paragraph is the most informative when helping a user
understand the benefits when in context:

"To properly train a neural network to create vision embeddings, you must
split your data into triplets before passing through a network (there are
also other ideas such as center loss that I won't describe here). This
involves passing three examples through the neural network, and examining
the "loss" at the end. 3 images are passed, where the first x is the anchor
class, and x+ is a positive example of that image, and x- is a negative
example of that image. This leads to 2D representations of each image
placed on a hypersphere, and each subsequent representation can be
compared, linearly. You no longer have to re-train the neural network in
order to identify new objects or faces."

**Comment by AlexDBlack** [comment]
I'm going to close this - they are all listed in the quickref guide.
https://deeplearning4j.org/quickref
