### ISSUE TITLE
NeuralNetConfiguration is not compatible with latest version of jackson-databind

### ISSUE THREAD

**Issue by alex-glasman** [deeplearning4j/deeplearning4j#2277]
NeuralNetConfiguration uses AnnotatedClass.construct() method from jackson-databind library. 
It currently follows pre 1.7 version of this method signature:
        construct(Class<?> cls, AnnotationIntrospector aintr, MixInResolver mir)
At the same time recent signature (in 2.8.1 version) is following:
        construct(JavaType type, MapperConfig<?> config, MixInResolver mir)

It will be great to fix this incompatibility to be able to use latest version of jackson-databind library.

**Comment by AlexDBlack** [comment]
We are now using a shaded version of Jackson throughout DL4J and DataVec
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/NeuralNetConfiguration.java#L37

One consequence of this is that you can now use any other version of Jackson on the classpath, without running into issues.
