### ISSUE TITLE
Truncated BPTT doesn't work when forward length > time series length

### ISSUE THREAD

**Issue by EdeMeijer** [deeplearning4j/deeplearning4j#2278]
I'm training a RNN on time series of varying length, and tried to apply truncated BPTT. I saw warnings appear indicating that truncated BPTT can't be done because the time series are to short. Looking at the code, it just seems to skip the whole update in this case, not learning anything.

To verify that the model wasn't being trained in these cases, I set the lenghts to very large values to make sure that all my time series would always be too small. 
```
builder.backpropType(BackpropType.TruncatedBPTT).tBPTTBackwardLength(10000).tBPTTForwardLength(10000);
```
As expected, during training my console was filled with these warnings:
```
o.d.n.m.MultiLayerNetwork - Cannot do TBPTT: Truncated BPTT forward length (10000) > input time series length (357)
```
Also, it processed epochs very fast, and I verified that training error remained exactly the same over multiple epochs.

The message comes from MultiLayerNetwork line 1191. Here it emits the warning and just returns. In my case, it's called from `fit(DataSetIterator iterator)` on line 1060. It doesn't check if Truncated BPTT worked or was skipped.
```
if(layerWiseConfigurations.getBackpropType() == BackpropType.TruncatedBPTT) {
    doTruncatedBPTT(next.getFeatureMatrix(),next.getLabels(),next.getFeaturesMaskArray(),next.getLabelsMaskArray());
}
else {
    ...
```
I would expect that, in case the time series is too short to truncate, the normal training approach would be applied for these training examples.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/2286
