### ISSUE TITLE
How to avoid the  'Invalid input configuration'

### ISSUE THREAD

**Issue by htw2012** [deeplearning4j/deeplearning4j#2279]
Hello,

when I want to stack more convs and poolings in CNN.And I set the type as `same`.But it will get the exception like: 

> java.lang.IllegalStateException: Invalid input configuration (layer name = "MaxPooling-0") for height: inHeight=32, kernelH=5, padH=0, strideH=5; (32-5+2*0)/5 is not an integer

	
Is there any way to automatically infer the shape to avoid the exception?Like put more paddings.

**Comment by htw2012** [comment]
Also I use the InputType.convolutionalFlat(heigh,width(),channels)

**Comment by AlexDBlack** [comment]
Your configuration is invalid - only certain combinations of input, kernel size, strides and padding work for CNNs.
See "Constraints on strides" section here: http://cs231n.github.io/convolutional-networks/
