### ISSUE TITLE
ArrayIndexOutOfBoundsException: 1 at IteratorMultiDataSetIterator.next(IteratorMultiDataSetIterator.java:79)

### ISSUE THREAD

**Issue by AllenWGX** [deeplearning4j/deeplearning4j#2290]
I run an example of ComputationGraph(code url : https://github.com/deeplearning4j/dl4j-examples/blob/d5434eac99bc58c7bbf1e4a435d12f9b4e85def9/src/main/java/org/deeplearning4j/examples/rnn/seq2seq/Sequence2Sequence.java ) in the Spark local and cluster mode(the code above has been modified to Spark), an exception as the title described is thrown. I debug the code at IteratorMultiDataSetIterator.java:79 and find that some problems may be here:
![bug](https://cloud.githubusercontent.com/assets/23058056/20124591/77dfaf44-a662-11e6-9e13-7cc76e3b9c5a.png)
In this for-loop, if there are two input features vectors and one output vector(just as the example in above URL), out-of-bounds exception will be thrown when executing the code in the red block. And the code in the blue block may be changed to "getLabels(i)". So I modify the code as below:
![modify](https://cloud.githubusercontent.com/assets/23058056/20124801/142fdc92-a664-11e6-8200-832f949e6b82.png)
In this way, the code can be successfully executed on the Spark local and cluster mode.I'm not sure whether there is bug here. Please help me see this...

**Comment by AlexDBlack** [comment]
Sorry for not getting to this sooner. That's definitely a bug.

Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2327
