### ISSUE TITLE
When dl4j could support keras model?

### ISSUE THREAD

**Issue by kiwighost** [deeplearning4j/deeplearning4j#2299]
Hello, thanks for doing a great work in dl4j. I just wondering that when dl4j could support keras model please? Do you have any schedule please? I am looking forwards to hearing from you.

Best wishes,
Richard

**Comment by agibsonccc** [comment]
We already support it in master. Please don't file issues asking for the release. I've also already clarified *this already exists* in gitter. When I say there's a working implementation in master, please don't assume that *it doesn't exist at all*. It just means it's not in maven central.

**Comment by kiwighost** [comment]
Thank you for the quickly response. I will have a try for the release.

best wishes,
Richard
