### ISSUE TITLE
InputType.recurrent(size) in 0.6.1 fails to pass args

### ISSUE THREAD

**Issue by Joshuaalbert** [deeplearning4j/deeplearning4j#2300]
I just upgraded from 0.5.1 to 0.6.1 with the master branch and my ComputationalGraph model conf now breaks at:

```.setInputTypes(InputType.recurrent(numInputs))```

This calls ```new InputTypeRecurrent(size);``` but in nn.conf.inputs.InputType their is no constructor for InputTypeRecurrent!

```
@AllArgsConstructor @Getter
    public static class InputTypeRecurrent extends InputType{
        private int size;

        @Override
        public Type getType() {
            return Type.RNN;
        }

        @Override
        public String toString(){
            return "InputTypeRecurrent(" + size + ")";
        }
    }
```
Where is size being set or used?

EDIT:  I think ```InputType.recurrent(numInputs)``` (and the other counter parts) are useless legacy since you can just use new ```InputType.InputTypeRecurrent()```

**Comment by Joshuaalbert** [comment]
I'm not sure why it wouldn't work but then now it does. But after recompiling twice the error was fixed. Maybe Lombok randomly started stopping so it didn't see @AllArgsConstructor?

**Comment by saudet** [comment]
Yes there is: @AllArgsConstructor
