### ISSUE TITLE
Word2Vec getLayerSize() method doesn't return the correct layer size

### ISSUE THREAD

**Issue by chenmiaogit** [deeplearning4j/deeplearning4j#2304]
I loaded the Google word2vec model using model = (Word2Vec) WordVectorSerializer.loadGoogleModel(gModel, true); and then I want to find the layer size by using model.getLayerSize(), but this doesn't return me the correct layer size -- it should be 300, but what it returns is 100.

**Comment by raver119** [comment]
Fixed on current master.

Thanks for highlighting this issue.
