### ISSUE TITLE
4sec startup time caused by reflection scan?

### ISSUE THREAD

**Issue by mburo** [deeplearning4j/deeplearning4j#2308]
Playing with some DL4J sample code I am experiencing ~4 sec startup time when executing the code below:

    return new NeuralNetConfiguration.Builder()
      .seed(seed)
      .iterations(iterations)      .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
      .learningRate(learningRate)
      .weightInit(WeightInit.XAVIER)
      .updater(Updater.NESTEROVS).momentum(0.9)
      .list()
// ....

When switching logging on this line prints out thousands of lines like the following:

6297 [main] DEBUG org.reflections.Reflections  - could not scan file jdk/nashorn/internal/runtime/resources/fx/swt.js in url file:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-1.b16.fc24.x86_64/jre/lib/ext/nashorn.jar with scanner TypeAnnotationsScanner
6297 [main] DEBUG org.reflections.Reflections  - could not scan file jdk/nashorn/internal/runtime/resources/fx/media.js in url file:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-1.b16.fc24.x86_64/jre/lib/ext/nashorn.jar with scanner SubTypesScanner
6297 [main] DEBUG org.reflections.Reflections  - could not scan file jdk/nashorn/internal/runtime/resources/fx/media.js in url file:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-1.b16.fc24.x86_64/jre/lib/ext/nashorn.jar with scanner TypeAnnotationsScanner
6297 [main] DEBUG org.reflections.Reflections  - could not scan file jdk/nashorn/internal/runtime/resources/version.properties in url file:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-1.b16.fc24.x86_64/jre/lib/ext/nashorn.jar with scanner SubTypesScanner

ending with this:

7159 [main] INFO org.reflections.Reflections  - Reflections took 2922 ms to scan 114 urls, producing 4295 keys and 21984 values 

time output for just running above configuration line:

real    0m4.344s
user    0m7.285s
sys     0m0.341s

Time is independent of network size.

Is there a way to switch off scanning, or providing a way of caching the results at least? 4 secs startup time seems excessive.

My environment:

- Fedora 24 x86_64, I7 2.4 GHz laptop
- DL4J 0.6.0
- java-1.8.0-openjdk-1.8.0.111-1.b16
- starting the application with
java -ea -d64 -Xmx800m -Djava.library.path=./external/lib -classpath "dist/dependency/*:dist/micTest.jar" micTest "$@"
  where dist/depency/ contains dozens of jar files

**Comment by AlexDBlack** [comment]
As noted in gitter:
Reflection scanning is to allow for custom functionality (custom layers, graph vertices, loss functions, input preprocessors etc) and still be able to use JSON serialization. This is necessary for model serializer and spark to function with custom code.

It's done once per JVM and on my PC it's around a second or so. Reviewing the code, I can see one way to speed that up a bit.

**Comment by mburo** [comment]
"It's done once per JVM and on my PC it's around a second or so."

Are the results supposed to be saved to be reused later? If not, even 1 sec delay everytime time an application is started, IMHO, is a bit too much. I am not up-to-date when it comes to Java frameworks, but wouldn't plain inheritance solve that problem - like implementing a serialization interface? Anyway - I hope this problems gets resolved.

**Comment by AlexDBlack** [comment]
I don't think there's a feasible way to reliably cache the results - you might add a custom layer/preprocessor/whatever to your classpath any time you run your program - and there would be no way to know when to update the cache vs. use it.

I will however add a way to disable this (via a system property) so that if an extra second *really* matters, (and you aren't using custom layers etc) the scanning won't occur.

I'm currently working on some optimizations to make it faster in general, however.

And no - inheritence does not solve the problem - we still need to know the types that actually implement the interface (or extend the class) to be able to correctly serialize/deserialize them to/from JSON via Jackson.

**Comment by mburo** [comment]
OK.
"extra second really matters" - actually on my system it's 4.3 secs wall clock and more than 7 secs CPU time.

**Comment by AlexDBlack** [comment]
I've made some optimizations to both DL4J and ND4J's use of the reflections library to improve performance during initialization.
https://github.com/deeplearning4j/nd4j/pull/1424
https://github.com/deeplearning4j/deeplearning4j/pull/2310

You can now also pass "-Dorg.deeplearning4j.config.custom.enabled=false" (i.e., system property) if you want to skip the classpath scan for custom layers.


Total startup time (main method start to completion of first initialized network) is around 1.15 seconds on my machine (from 4.5 before) - that's a cold start including ND4J, DL4J and dependent library initialization steps. After that, second network initialization (for a small test network) occurs in 1-2ms.
I assume you were measuring the *total* initialization time, including ND4J and all other dependent libraries, as that's in line with what I'm seeing.

Reflections still takes some of that - but remaining time is SLF4J inititialization, native library loading, Jackson initialization etc.
