### ISSUE TITLE
Nd4j.scalar infinite recusrion

### ISSUE THREAD

**Issue by Mi5ke** [deeplearning4j/deeplearning4j#2319]
It is possible for Nd4j.scalar to recurse infinitely. If the ND4j.dtype is FLOAT, but the working type is set to be HALF for a GPU (using DataTypeUtil.setDTypeForContext(DataBuffer.Type.HALF);), then everything works fine, except for Nd4j.scalar(float), as used by the DataSet.normalize() method, and elsewhere.

The scalar method tests for the data type being FLOAT or DOUBLE, and otherwise re-calls the scalar method with the float argument cast to an int. Unfortunately, the only matching method in those circumstances, is the scalar(float) method itself - so infinite recursion occurs.

Not a problem if the datatypes are all set consistently - but that may not be the case with saved/loaded DataSets?

**Comment by raver119** [comment]
How you've managed to get Nd4j.dtype as float, if context was set to HALF?

**Comment by raver119** [comment]
hm. are you using Nd4j.dtype field directly? as in not a Nd4j.dataType() method?

**Comment by Mi5ke** [comment]
DataTypeUtil.setDTypeForContext(DataBuffer.Type.HALF);
		Nd4j.dtype = DataBuffer.Type.FLOAT;
		..... load stuff ......
		dataset.normalize();

fails, but the other way around works....

		Nd4j.dtype = DataBuffer.Type.FLOAT;
		DataTypeUtil.setDTypeForContext(DataBuffer.Type.HALF);
              ......

Example code on deeplearning4j seems to use the Nd4j.dtype directly, which is what I copied.

**Comment by raver119** [comment]
Right, i'm making Nd4j.dtype protected now. Nd4j.dataType() getter should be used, since it honors context properly & does honor concurrent access.

Thanks for the highlighting this issue

**Comment by Mi5ke** [comment]
The dataType method only seems to return the datatype, not set it.

**Comment by Mi5ke** [comment]
The TSNEStandardExample uses this directly, as do some example(s) in the documentation.

**Comment by raver119** [comment]
yes. To set dataType different method is used:

https://github.com/deeplearning4j/dl4j-examples/blob/050a14c1623671e290afa637869c5e4abde0a2bc/dl4j-cuda-specific-examples/src/main/java/org/deeplearning4j/examples/multigpu/MultiGpuLenetMnistExample.java#L43-L43

```
DataTypeUtil.setDTypeForContext(DataBuffer.Type.HALF);
```

**Comment by Mi5ke** [comment]
I think that is a mistake.... just using
 		DataTypeUtil.setDTypeForContext(DataBuffer.Type.HALF);
alone causes the same problem. Try calling normalize on any DataSet, and it recurses infinitely.

**Comment by raver119** [comment]
Show me minimal code that reproduces such recursion please

**Comment by Mi5ke** [comment]
`	public static void main(String[] args) {
		DataTypeUtil.setDTypeForContext(DataBuffer.Type.HALF);
		INDArray first = Nd4j.rand(20, 10);
		INDArray second = Nd4j.rand(3, 20);
		DataSet data = new DataSet(first, second);

		data.normalize();
	}`

**Comment by raver119** [comment]
Fixed, thanks for highlighting this issue

**Comment by Mi5ke** [comment]
OK... so the workaround for my currently crashing program is... to still set Nd4j.dtype directly?
What happens about all the example code out there in web-land, if dtype will be protected?
When will the fixed code be available to download from Maven?

Thanks

Mike

**Comment by raver119** [comment]
I've already updated that TSNE example: 
- use Nd4j.dataType() to get current value
- use Nd4j.setDataType(your_datatype) to set new value.

Basically, old mechanics you were using before was a bug, because technically you were getting inconsistent dtype in different methods. In other words: Nd4.dtype field was a legacy code, and i had to remove that use.

**Comment by Mi5ke** [comment]
I don't have a Nd4j.setDatatype(...) method.... might have a v0.5 lingering in the classpath somewhere... will check.

**Comment by Mi5ke** [comment]
My Nd4j is coming from nd4j-api-0.6.0.jar - and no setDataType method is there,

**Comment by raver119** [comment]
You don't have it because i've added it to master few minutes ago. But for 0.6.0 there's another approach also available, i've posted it before.

 DataTypeUtil.setDTypeForContext(DataBuffer.Type.HALF); <--- this one

And anyway, in nearest hours release process will begin, testing & polishing is almost done now.

**Comment by Mi5ke** [comment]
Yes - but that's the line of code in my minimal code (above) which crashes when normalising, if you remember. Look forward to the new release :-).

**Comment by raver119** [comment]
Yes, and that recursion is caused by a bug, which is fixed on master after your report :)
