### ISSUE TITLE
Spark with YARN on Ubuntu 16.04 crashes

### ISSUE THREAD

**Issue by EdeMeijer** [deeplearning4j/deeplearning4j#2320]
Not really a DL4j issue but maybe nice to mention somewhere in the docs. When running a Spark on YARN cluster on Ubuntu 16.04 machines, chances are that after finishing a job, all processes owned by the user running Hadoop/YARN are killed. Some digging made clear that it's related to a bug in Ubuntu, which is documented at https://bugs.launchpad.net/ubuntu/+source/procps/+bug/1610499. There's also a Stackoverflow discussion about it at http://stackoverflow.com/questions/38419078/logouts-while-running-hadoop-under-ubuntu-16-04.

Some workarounds are suggested. The first is to add 
```
[login]
KillUserProcesses=no
```
to `/etc/systemd/logind.conf`, and rebooting. The other is to copy the `/bin/kill` binary from Ubuntu 14.04 and use that one instead. My own solution was to just downgrade to Ubuntu 14.04 for now, until this is properly fixed. Just FYI.

**Comment by EdeMeijer** [comment]
@huitseeker suggested running `sudo loginctl enable-linger hadoop_user_name` on the cluster nodes and this fixed the problem too. Might be useful to document somewhere.

**Comment by tomthetrainer** [comment]
Closed, edited the two spark pages
https://deeplearning4j.org/spark
https://deeplearning4j.org/spark-gpus

Added notes header and warning at bottom of page, 
It would be nice to have a styled icon for this like the scorpion breakout box in OReilly books

**Comment by huitseeker** [comment]
This is a consequence of systems under systemd, with a systemd-logind > v230 :
http://unix.stackexchange.com/a/293093
Therefore, at the moment, it concernes every Linux except Slackware and Gentoo. /cc @tomthetrainer
