### ISSUE TITLE
the latest version of jar 

### ISSUE THREAD

**Issue by kuluofenghun** [deeplearning4j/deeplearning4j#2330]
I cannot find the nd4j 0.6.1 jar and datavec 0.6.1 jar. Could you provide them for me to use?

**Comment by AlexDBlack** [comment]
The most recent release was 0.6.0. The next release will be out within a few days.
0.6.1-SNAPSHOT refers to the current development version - no JAR files are available.

**Comment by kuluofenghun** [comment]
Can I use the open source of ND4j to build the JAR files?


At 2016-11-18 16:50:29, "Alex Black" <notifications@github.com> wrote:


The most recent release was 0.6.0. The next release will be out within a few days.
0.6.1-SNAPSHOT refers to the current development version - no JAR files are available.

**Comment by AlexDBlack** [comment]
It is possible, but not reccommended. You need to build the *full* stack - libnd4j (which is c++ and cuda), nd4j, datavec, dl4j. That can be quite difficult to do.
I'd suggest waiting for the next release.

Is there a reason why you need the current development version?

**Comment by kuluofenghun** [comment]
Because we are using the project deeplaerning4j-modelimport. The maven project need the latest JAR files, or it will appear error in the maven project. If thereare any way to solve the question?



At 2016-11-18 17:25:40, "Alex Black" <notifications@github.com> wrote:


It is possible, but not reccommended. You need to build the full stack - libnd4j (which is c++ and cuda), nd4j, datavec, dl4j. That can be quite difficult to do.
I'd suggest waiting for the next release.

Is there a reason why you need the current development version?

**Comment by raver119** [comment]
Yes, there's few options:
1) Build whole stack manually: libnd4j -> nd4j -> datavec -> dl4j
2) Wait a bit for next release, which is getting prepared atm.

There's no other options.

**Comment by kuluofenghun** [comment]
Now we are in hurry to load a keras model in Java. So I want to ask you, when can I get the next release? Or there is another way to load keras model in Java?



At 2016-11-18 18:16:29, "raver119" <notifications@github.com> wrote:


Yes, there's few options:
1) Build whole stack manually: libnd4j -> nd4j -> datavec -> dl4j
2) Wait a bit for next release, which is getting prepared atm.

There's no other options.

**Comment by agibsonccc** [comment]
Could you post what model you are trying to load? And no we are literally
the only option.

**Comment by kuluofenghun** [comment]
we want to load a keras modelthrough the Model Class in the the project deeplaerning4j-modelimport. Our keras model is a Functional API model where the config and weights were saved separately using calls to model.to_json() and model.save_weights(...). In the maven project, the lastest version of JAR files are needed. Or there is any other way to load the model?





At 2016-11-21 14:53:51, "Adam Gibson" <notifications@github.com> wrote:
Could you post what model you are trying to load? And no we are literally
the only option.

**Comment by agibsonccc** [comment]
And again: If you want to tell us when to do a release sign up for a
skymind support contract.

I know what your goals are and I am also telling you that the release is
not ready yet.

Nothing you get for free has ANY obligation yo give you guarantees.

**Comment by kuluofenghun** [comment]
Thanks for your reply!






At 2016-11-21 15:09:09, "Adam Gibson" <notifications@github.com> wrote:
And again: If you want to tell us when to do a release sign up for a
skymind support contract.

I know what your goals are and I am also telling you that the release is
not ready yet.

Nothing you get for free has ANY obligation yo give you guarantees.

**Comment by raver119** [comment]
0.7.0 is available via maven now.
