### ISSUE TITLE
The value of negative in InMemoryLookupTable does not get persisted when saving the Word2Vec model.

### ISSUE THREAD

**Issue by KonceptGeek** [deeplearning4j/deeplearning4j#2331]
The value of negative variable in InMemoryLookupTable does not get persisted when saving the Word2Vec model. This causes an issue when the model is reloaded using WordVectorSerializer.readWord2Vec() and tuning the vectors need to be with new training data with negativeSample of Word2Vec model set to a value > 0. Currently to handle this issue the following needs to be done:

`
Word2Vec word2Vec = WordVectorSerializer.readWord2Vec(new File(modelPath));
((InMemoryLookupTable) word2Vec.getLookupTable()).setNegative(5.0);
word2Vec.getLookupTable().resetWeights(false);
`

After performing the above steps, the model weights can be further tuned with new training data.

**Comment by raver119** [comment]
Show how you've saved your model, please.

**Comment by raver119** [comment]
Issue was fixed some time ago, and isn't reproducible on current master.
