### ISSUE TITLE
HistogramIterationListener extremely  slow

### ISSUE THREAD

**Issue by thhart** [deeplearning4j/deeplearning4j#2337]
I am evaluating dl4j-examples based on version 0.6.0. When I run with the HistogramIterationListener the computation becomes extremely slow like 10 times slower, what might be the reason for this? It shows results in a browser so it is working in general but really slow.

```
        MultiLayerNetwork model = createModelAlex();
        model.init();
        model.setListeners(new ScoreIterationListener(1), new HistogramIterationListener(1 ));
        //model.setListeners(new ScoreIterationListener(1));
```

**Comment by agibsonccc** [comment]
New UI going out next release, not relevant.
