### ISSUE TITLE
Wrong score calculation

### ISSUE THREAD

**Issue by thhart** [deeplearning4j/deeplearning4j#2339]
I am testing with some images and have following result, I understand it is a bad example since it is not working obviously but I want to point that the accuracy is wrong calculated then. I have two classes which in this example all are biased to only one input class, in this situation the score should not be 0.5. As an alternative I would log a message stating that the calculation is not possible/reliable, "excluding" is not a good option IMHO because it somehow implies the calculation score is still comparable but in fact it is a major failure.

```
Examples labeled as 0 classified by model as 0: 39 times
Examples labeled as 1 classified by model as 0: 39 times

Warning: class 1 was never predicted by the model. This class was excluded from the average precision

==========================Scores========================================
 Accuracy:  0.5
 Precision: 0.5
 Recall:    0.5
 F1 Score:  0.5
========================================================================

```

**Comment by agibsonccc** [comment]
Maybe making it configurable would be good? We get all sorts of strange calculations when including non counted classes.

**Comment by raver119** [comment]
This issue was fixed looong ago
