### ISSUE TITLE
RNN Regression result differs between 0.6.1-SNAPSHOT and 0.7.0

### ISSUE THREAD

**Issue by dan-lind** [deeplearning4j/deeplearning4j#2350]
Running 0.6.1-SNAPSHOT
<img width="677" alt="screen shot 2016-11-22 at 06 44 13" src="https://cloud.githubusercontent.com/assets/433464/20512931/f937d6aa-b082-11e6-9d8d-dd2582901a9d.png">

Running 0.7.0
<img width="675" alt="screen shot 2016-11-22 at 06 41 12" src="https://cloud.githubusercontent.com/assets/433464/20512930/f9379168-b082-11e6-9cb7-9568d9d62f83.png">

My regression results have changed just by upgrading from 0.6.1-SNAPSHOT (commit 0d6c5f38a77f51ca7b800ab2478dad810750d966) to 0.7.0.

Adam suggested it might be due to XAVIER weight init has been changed, so I tried with XAVIER_LEGACY, but it doesn't seem to make a difference.

The code I'm running can be found here (dl4j-examples fork, data available in same repo): 
https://github.com/dan-lind/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/regression/RegressionExample.java

**Comment by saudet** [comment]
Could you try to pinpoint the commit over the past 11 days that causes the behavior to change?

**Comment by AlexDBlack** [comment]
Is this specific to any backend? i.e., are you using native or cuda?

(Also, as an aside: .activation("sigmoid") on LSTM isn't the best choice. Usually tanh is used with LSTMs)

**Comment by dan-lind** [comment]
I'm using native.

I can do some testing with RNG seeds in the afternoon, don't have my laptop with me atm.

Thanks for the aside ;-)

**Comment by raver119** [comment]
> So weight init on 0.6.0 with a given seed probably won't be the same as 0.7.0 with the same seed.

Definitely. There will be nothing common in such two sequences.

**Comment by dan-lind** [comment]
Did some testing, seed is clearly the reason. I'll close the issue
