### ISSUE TITLE
Webpage collpases menu in Firefox

### ISSUE THREAD

**Issue by thhart** [deeplearning4j/deeplearning4j#2352]
I have a Linux running with Firefox, when I open a page the whole menu gets collapsed, this is very annoying when reading through your valued documentation.

How to reproduce:
1. Open https://deeplearning4j.org
2. Click on "Tuning and training" -> menu gets expanded
3. Click on "Visualize, Monitor and Debug Network Learning" -> menu gets collapsed

**Comment by ejunprung** [comment]
@thhart Hi Thomas. This is because you're navigating to a new page. It's not specific to Firefox/Linux. 

When there is time, I'll see if we can make the menu persist across pages. Definitely sounds like a better experience.
