### ISSUE TITLE
WordVectorSerializer writeWord2VecModel is not saving modelUtils information. 

### ISSUE THREAD

**Issue by KonceptGeek** [deeplearning4j/deeplearning4j#2357]
The WordVectorSerializer.writeWord2VecModel() function is not storing the modelUtils information that was assigned when building the model. For example, when building the Word2Vec object if the modelsUtils was set to TreeModelUtils and then the model was persisted using the above specific function, on reading the extended model, Word2Vec object's modelUtils is set to BasicModelUtils.

**Comment by raver119** [comment]
Right, it wasn't supposed to be saved actually, but i'm pretty ok to add that option to VectorsConfiguration for persistence.

**Comment by raver119** [comment]
Improvement is merged now.
