### ISSUE TITLE
Does RecordReaderDataSetIterator support multilabel classification datasets

### ISSUE THREAD

**Issue by vedina** [deeplearning4j/deeplearning4j#2360]
Could you please tell if `RecordReaderDataSetIterator` could generate multilabel classification datasets, and if not, what's the way to go?

Also, the [RecordReaderDataSetIterator.java#L119](https://github.com/deeplearning4j/deeplearning4j/blob/d6d913a8613060efccecb1911920cced4ea9d0a3/deeplearning4j-core/src/main/java/org/deeplearning4j/datasets/datavec/RecordReaderDataSetIterator.java#L119) seems to set labelIndexTo to the same value as labelindexFrom, regardless of the number of possible labels. Is this intentional?

````
public RecordReaderDataSetIterator(RecordReader recordReader, WritableConverter converter, int batchSize, int labelIndex,
                                       int numPossibleLabels, int maxNumBatches, boolean regression) {
        this(recordReader, converter, batchSize, labelIndex, labelIndex, numPossibleLabels, maxNumBatches, regression);
    }
````

Thanks

**Comment by vedina** [comment]
As per Gitter answer multi label classification is not supported directly

**Comment by yylonly** [comment]
you can use multi label regression RecordReader instead
