### ISSUE TITLE
Clustering produces fake centers with distanceFunction = "euclidean", does not work with distanceFunction = "cosinesimilarity"

### ISSUE THREAD

**Issue by mikegwf1** [deeplearning4j/deeplearning4j#2361]
I am clustering normalized word vectors using KMeansClustering and distanceFunction = "euclidean". and labeling the points using the word string. When I iterate through the centers of the clusters, I see that fake points seem to have been created as the centers of the clusters, even when there is just one point in the cluster.  For example,

ID: 07f748e4-7e35-4b1a-92a5-1b8eb67b103b LABEL: null COUNT: 10
html, http, mm, htm, mis, website, opermessages, web, www, currentopermessages

and

ID: 05817f12-fdf0-46e4-8ad8-44b71d3d5674 LABEL: null COUNT: 1
company

Is this correct behavior?

Also, if I use distanceFunction = "cosinesimilarity", then clusters having a single point indeed have that point as the center, as in the following:

ID: 2 LABEL: busses

However, such points also appear in other multi point clusters:

ID: 35a11c98-8d9d-4196-a4a0-c21487685b9e LABEL: null
nicely, costing, coale, linklaters, busses

so such points are appearing in multiple clusters!

**Comment by agibsonccc** [comment]
I don't feel like this is a bug.  This is likely a consequence of kmeans + cosine similarity behavior. What we needed to do here was make sure clusters are updated with respect to the distance metric. The logic itself was fine.
