### ISSUE TITLE
Training several networks at the same time leads to different results

### ISSUE THREAD

**Issue by Treiblesschorle** [deeplearning4j/deeplearning4j#2366]
Since switching from 0.6.0 to 0.7.0:
When training several networks on different threads at the same time the output of each network is different. All networks have the same configuration (with seed) and are trained on the same data. For evaluation, the same data is used as well.
As expected, when training the networks sequentially the results are the same.

Code to reproduce:
I modified the MLPMnistSingleLayerExample:
https://gist.github.com/Treiblesschorle/6eb13a505771a0b1fa2773ba1aa9a062

And created a trainer class:
https://gist.github.com/Treiblesschorle/9c7e764cf20db2e7abf219ab078d11b1

Example code outputs the following:
https://gist.github.com/Treiblesschorle/ff3adb117e8426ed5b8ea5b478eb6ccb

I'm on Windows 10 x64

**Comment by AlexDBlack** [comment]
I ran your code on 0.7.0, on Windows 10 x64, nd4j-native.

Results with MKL: consistently the same each time.
https://gist.github.com/AlexDBlack/d81045a18703c48586aa225924383fdf

Results with openblas: consistently different, when multithreaded
https://gist.github.com/AlexDBlack/b30797912d274ab2b2a53e2a7333b178

Looks like this might be a thread safety issue with openblas?

**Comment by AlexDBlack** [comment]
I rebuilt nd4j following the instructions here: https://github.com/deeplearning4j/deeplearning4j/issues/2353#issuecomment-262728273

The test seems to be consistently giving the same results with that. Perhaps it's the same underlying issue?

**Comment by saudet** [comment]
Changes in the commit above fixes this issue. The cause is different, but it is due to OpenBLAS...

**Comment by AlexDBlack** [comment]
Seems to be fixed - no reports of this issue since.
