### ISSUE TITLE
Update glossary re: new weight init

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2371]
https://deeplearning4j.org/glossary

Xavier initialization has been changed in 0.7.0 to align with the Glorot paper.
Also Caffe now seems to use 2/(fanIn+fanOut)

This section should also explain what fanIn/Out are, with respect to the nIn/nOut parameters of each layer in DL4J.

**Comment by tomthetrainer** [comment]
done
