### ISSUE TITLE
DataBuffer.Type.HALF and DataBuffer.Type.Float on same model get quite different accuracy

### ISSUE THREAD

**Issue by yylonly** [deeplearning4j/deeplearning4j#2375]
When i use DataBuffer.Type.Float to train my 15 layers NN with 2000 nodes in each layer, i can get 64% accuracy. 

When I change DataBuffer.Type.HALF to train the same configuration NN, i can only get 9.8% accuracy. 

I really wanna to use FLOAT, but even for the K40, it can hold that 'big' model, i got out of memory error.  

Any solutions?  

Thanks

**Comment by raver119** [comment]
Show configuration of your NN please.


But yes, half assumes way more tricky tuning - precision loss is expensive thing.

**Comment by yylonly** [comment]
>         NeuralNetConfiguration.Builder builder = new NeuralNetConfiguration.Builder()
>                 .seed(seed)
>                 .iterations(iterations)
>                 .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
>                 .learningRate(0.1)
>                 .biasLearningRate(0.02)
>                 .learningRateDecayPolicy(LearningRatePolicy.Step)
>                 .lrPolicyDecayRate(0.001)
>                 .lrPolicySteps(5000) 
>                 .weightInit(WeightInit.XAVIER_UNIFORM)
>                 .regularization(true)
>                 .l2(1e-3)
>                 .miniBatch(true)
>                 
>                 .gradientNormalization(GradientNormalization.RenormalizeL2PerLayer)
>                 .updater(Updater.NESTEROVS)
>                 .momentum(0.9);
>                 
>                 
>         MultiLayerConfiguration mconf = builder.list()
>                 .layer(0, new DenseLayer.Builder().nIn(numInputs).nOut(numHiddenNodes)
>                         .activation("tanh")
>                         .build())
>                 .layer(1, new DenseLayer.Builder().nIn(numHiddenNodes).nOut(numHiddenNodes)
>                         .activation("tanh")
>                         .build())
>                 .layer(2, new DenseLayer.Builder().nIn(numHiddenNodes).nOut(numHiddenNodes)
>                         .activation("tanh")
>                         .build())
>                 .layer(3, new DenseLayer.Builder().nIn(numHiddenNodes).nOut(numHiddenNodes)
>                         .activation("tanh")
>                         .build())
>                 .layer(4, new DenseLayer.Builder().nIn(numHiddenNodes).nOut(numHiddenNodes)
>                        .activation("tanh")
>                         .build())
>                 .layer(5, new DenseLayer.Builder().nIn(numHiddenNodes).nOut(numHiddenNodes)
>                         .activation("tanh")
>                         .build())
>                 .layer(6, new DenseLayer.Builder().nIn(numHiddenNodes).nOut(numHiddenNodes)
>                         .activation("tanh")
>                         .build())
>                 .layer(7, new DenseLayer.Builder().nIn(numHiddenNodes).nOut(numHiddenNodes)
>                         .activation("tanh")
>                         .build())
>                 .layer(8, new DenseLayer.Builder().nIn(numHiddenNodes).nOut(numHiddenNodes)
>                         .activation("tanh")
>                         .build())
>                 .layer(9, new DenseLayer.Builder().nIn(numHiddenNodes).nOut(numHiddenNodes)
>                         .activation("tanh")
>                         .build())
>                 .layer(10, new DenseLayer.Builder().nIn(numHiddenNodes).nOut(numHiddenNodes)
>                         .activation("tanh")
>                         .build())
>                 .layer(11, new DenseLayer.Builder().nIn(numHiddenNodes).nOut(numHiddenNodes)
>                         .activation("tanh")
>                         .build())
>                 .layer(12, new DenseLayer.Builder().nIn(numHiddenNodes).nOut(numHiddenNodes)
>                        .activation("tanh")
>                         .build())
>                 .layer(13, new DenseLayer.Builder().nIn(numHiddenNodes).nOut(numHiddenNodes)
>                         .activation("tanh")
>                         .build())
>                 .layer(14, new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD)
>                         .activation("softmax")
>                         .nIn(numHiddenNodes).nOut(numOutputs).build())
>                 .pretrain(false).backprop(true).build();

the variable `numHiddenNodes = 2000`, when `numHiddenNodes = 3000 ` that will lead out of memory error for my two K40 GPUs.  

Btw, Batchsize  is 100,  I found the batchsize is not very effect the memory allocation. but the hidden node number does.

And How to control the preallocation memory in the GPU. 

I use cudaconfig.setMaximunDeviceCache() and .setMaximumDeviceAllocation(), both of them are not working. I also try prefetchBuffer() of ParallelWrapper, that also did not work. 

So, if i wanna pre allocation 10G GPU memory for my NN trainn. how to do that?

Thanks

**Comment by yylonly** [comment]
And the **batchsize** will also quite effect the accuracy. When i try batchsize = 5000 and 10000, that will lower accurcy. Seems the score can not decrease when using big batchsize.

**Comment by raver119** [comment]
Preallocation doesn't work that way. It works via cache in Nd4j. I.e. on first iteration memory gets allocated from device, and on further iterations it's reusing the same memory chunks.

And both of methods you've mentioned are working, there's no room to fail, just 2 getters.

**Comment by raver119** [comment]
btw, what is numInputs and numOutputs? And what batchSize you use there? And what total number of examples available?

**Comment by yylonly** [comment]
numInputs is 784
numOutputs is 10 
Batchsize is 100
Total training set is 60000

**Comment by yylonly** [comment]
`Configuration cudaconfig = CudaEnvironment.getInstance().getConfiguration();
				
 cudaconfig	.allowMultiGPU(true)

	     .setMaximumDeviceCache(10L * 1024L * 1024L * 1024L )
	    .setMaximumDeviceAllocation(10L * 1024L * 1024L * 1024L )
            .allowPreallocation(true)
            
           .setMaximumDeviceMemoryUsed(0.95)
            .allowCrossDeviceAccess(true);`

This is my cuda setting using that two pre allocation method to request 10g for my training. However, the nvida-smi shows:
>Sat Nov 26 13:47:47 2016       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.93     Driver Version: 352.93         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40m          On   | 0000:02:00.0     Off |                    0 |
| N/A   44C    P0   113W / 235W |   4887MiB / 11519MiB |     92%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K40m          On   | 0000:84:00.0     Off |                    0 |
| N/A   38C    P0   105W / 235W |   2513MiB / 11519MiB |     72%      Default |
+-------------------------------+----------------------+----------------------+                                                                             
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     24541    C   /home/yb37418/jdk1.8.0_112/bin/java           4820MiB |
|    1     24541    C   /home/yb37418/jdk1.8.0_112/bin/java           2446MiB |
+-----------------------------------------------------------------------------+

Is there any cuda environment variable to make this work?

Thanks

**Comment by AlexDBlack** [comment]
"When i try batchsize = 5000 and 10000, that will lower accurcy."
What is probably happening here: larger batch size means ferer parameter updates per epoch. So, you are probably doing fewer updates overall if you are doing a fixed number of epochs.
Batch size of 5000 or 10000 is way too large though, it's simply inefficient.

And training > 50 million parameters from 60000 examples (I assume you are using mnist) especially without some significant regularization, isn't a good idea.
Why not use a CNN?

**Comment by raver119** [comment]
You hadn't read javadoc for CUDA configuration methods you're using :(
They all have totally different sense.

**Comment by yylonly** [comment]
For the big batch size, I suppose BP caculate average sum of gratienet descend, even that is not inefficient, but that could not less much accuracy. 

I am not sure the batch size should be equal to the number of gpu cores or not? Or there should have some other standards?

I try FF with 15 layers, LeNet, and AlexNet. CNN is more inefficient for trainning because of fewer paramaters than full contected NN. but we can only get less accuracy result. I am not using mnist. But have same number of dataset.  

Any Comments?

**Comment by yylonly** [comment]
I read javadoc of deeplearning4j, but I still not can figure out, how to pre-allocation memory for my trainning. Just like 10g GPU memory.  Please point out the API, if could. Thanks

**Comment by raver119** [comment]
It's impossible for CUDA device memory, we use Just-in-Time allocation, with further reuse.

I.e. memory gets allocated for some INDArray, array is used for some time, then JVM garbage collector purges it as unused, but we keep that allocated memory for reuse, and as soon as next allocation request comes - it gets served from cache, instead of new allocation call.

In other words preallocation happens during first training iteration.

**Comment by yylonly** [comment]
Okay I see, Thanks
