### ISSUE TITLE
IntelliJ do not show graph from MLPClassifierLinear

### ISSUE THREAD

**Issue by gdelrioifc** [deeplearning4j/deeplearning4j#2377]
Hi,

I've began to use dl4j and installed it on a Linux iron 3.10.0-327.36.2.el7.x86_64. I followed the instructions to install it and run the examples. The specifics of my set up is detailed below:

IntelliJ IDEA 2016.3. Build #IC-163.7743.44, built on November 17, 2016
JRE: 1.8.0_112-release-408-b2 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Apache Maven 3.3.9

I did not change any code on the example, simply run it. I get the text described in the first image of the Quick Start Guide using MLPClassifierLinear, but I do not get the two windows where the graphs for training and testing are suppose to show. I do not know why I do not see these graphs and it seems to me this is an important piece of information I'll need for future projects. 

I'd appreciate any help on this matter.

Thanks,

Gabriel

**Comment by thhart** [comment]
Hi Gabriel, I checked and have no problems with the Windows, both Train and Test are shown for the example. I have quite the same environment, please post your console output and try to step through the code with the Debugger to check where it might fail. If it gets to PlotUtil step into it if the frame display call is reached.

**Comment by RyanJonesBKK** [comment]
Hi, I also had a similar problem. I followed the tutorial step by step and it told me another graph would appear showing the multilayer perceptron (MLP), but only the text was displayed.
![deeplearning](https://cloud.githubusercontent.com/assets/14212265/20663641/79081f0c-b515-11e6-8995-80d397efa9d9.png)

**Comment by thhart** [comment]
@RyanJonesBKK You are running LenetMnistExample which is not programmed to show any results windows by default, please check the example carefully.

**Comment by gdelrioifc** [comment]
Hi Thomas,

I solved the problem…I think I need to become more familiar with
IntelliJ…just debugging the code will present the two extra windows, but
not the run command….I do not understand why is this, but it seems this is
not related to dl4j, but intelliJ.

I appreciate your help.

Best,

Gabriel
