### ISSUE TITLE
Fail to import development to Idea

### ISSUE THREAD

**Issue by thhart** [deeplearning4j/deeplearning4j#2379]
I tried to follow the instructions as specified here: https://deeplearning4j.org/buildinglocally.html
However I could not succeed to get it work (without major manual changes).

1. The instructions seem a bit outdated, e.g. maven3 is part of latest Linux releases, so it is not necessary to include special ppa for Ubuntu for instance.
2. The main problem lies in the nd4j-jackson package for which there are a couple of dependencies in dl4j core to JsonInclude. Howewer it is not clear why this special annotation is really necessary since it looks like a very special derivate of fasterxml.jackson. Probably it is worth to merge this. Further more the annotation is missing in the source and only can get compiled via maven doing some special things. But even if maven can compile Intellij idea does not see compiled snapshot jars in the source tree and has problems to include these. (see screenshot attached). 
3. In the building locally instructions from above there is shortly spoken of "appropriately replace versions with the SNAPSHOT version currently on the master POM". IMHO this should be extended more to what it means and what it implies, does the local maven repository have to be overwritten by all maven compiled jars?

Minor:
It would be nice to have some more instructions specially related to Intellij Idea. How to import the modules in detail and which modules should be activated for which purpose of development. Also which plugins are necessary to activate: lombok, scala.

![screen-002](https://cloud.githubusercontent.com/assets/2632538/20640062/a157734a-b3d5-11e6-95c0-90c48a2fc14d.png)

**Comment by AlexDBlack** [comment]
Can you do two things:
(a) post the full output from the ND4J install in a gist
(b) check if .m2/repository/org/nd4j/jackson exists or not

**Comment by thhart** [comment]
a. https://gist.github.com/thhart/395663eeb6fa4b6512b1cff4e034d885.js

b.
```
% /home/th/.m2/repository/org/nd4j/jackson/0.7.1-SNAPSHOT: ls -al                                                                                                                                              th@orca [13:50]
total 1948
drwxrwxr-x 2 th th    4096 Nov 25 11:56 .
drwxrwxr-x 4 th th    4096 Nov 25 11:56 ..
-rw-rw-r-- 1 th th 1951414 Nov 26 13:41 jackson-0.7.1-SNAPSHOT.jar
-rw-rw-r-- 1 th th     430 Nov 25 11:20 jackson-0.7.1-SNAPSHOT.jar.lastUpdated
-rw-rw-r-- 1 th th     354 Nov 26 13:41 jackson-0.7.1-SNAPSHOT-javadoc.jar
-rw-rw-r-- 1 th th    3345 Nov 26 13:41 jackson-0.7.1-SNAPSHOT.pom
-rw-rw-r-- 1 th th     275 Nov 25 11:20 jackson-0.7.1-SNAPSHOT.pom.lastUpdated
-rw-rw-r-- 1 th th    1953 Nov 26 13:41 jackson-0.7.1-SNAPSHOT-sources.jar
-rw-rw-r-- 1 th th    1111 Nov 26 13:41 maven-metadata-local.xml
-rw-rw-r-- 1 th th     265 Nov 26 13:41 _remote.repositories
-rw-rw-r-- 1 th th     354 Nov 25 11:20 resolver-status.properties
% /home/th/.m2/repository/org/nd4j/jackson/0.7.1-SNAPSHOT: jar tf jackson-0.7.1-SNAPSHOT.jar | grep JsonInclude                                                                                                th@orca [13:50]
org/nd4j/shade/jackson/annotation/JsonInclude$Include.class
org/nd4j/shade/jackson/annotation/JsonInclude.class

```

**Comment by AlexDBlack** [comment]
I'm really not sure what you are expecting from a messy/incomplete/failed build like that...
To be in any way useful, you need to at least install nd4j-native. Which means first building native binaries (libnd4j).

Once you've built libnd4j (./buildnativeoperations.sh + set LIBND4J_HOME) then rebuild ND4J with something like the following:
./buildmultiplescalaversions.sh clean install -DskipTests -pl '!nd4j-cuda,!nd4j-cuda-platform'
http://stackoverflow.com/questions/8304110/skip-a-submodule-during-a-maven-build


I suspect the Jackson issue you are getting is symptomatic of something else - i.e., you can't find some other required dependency (like nd4j-native: it's a test dependency in DL4J) and so IntelliJ is stopping the import process early.
Same thing for DataVec, if you haven't installed that successfully.

**Comment by thhart** [comment]
Hi Alex, I am really not in the situation to judge what I should expect from nd4j and what not. However I am still convinced there is something broken in the distribution. But let's go step by step:

1. libnd4j was compiled and set
2. in fact I did not use the scala build script, this helped to build the remaining modules, for my testing I used the mvn install. By the way also the build script **build-dl4j-stack.sh** (which I used from the beginning) is using mvn install, probably it is worth to fix this
3. After successful building Idea still did not find the new jars, I added manually the pointer to the special jackson jars which where stilled missed
4. Finally I got dl4j compiled 

Thanks for your time, investigating and checking, I hope I can give something back to the community soon.

PS: you can not exclude nested maven modules with -pl, I did comment out the cuda modules in the pom file

**Comment by agibsonccc** [comment]
None of the development team or external contributors have had these problems. I have a strange feeling there' a missing gap here somewhere. I am not going to close this issue but until one of us can reproduce problems you're running in to I am going to mark this issue as suspect.

**Comment by AlexDBlack** [comment]
At this point: I'm thinking it has to be something with IntelliJ. The nd4j-jackson JARs are in your .m2 directory, even with your earlier install.

Some possibilities:
- Project is not managed correctly with Maven (i.e., doesn't have maven support set up correctly in IntelliJ)
- Auto-import is disabled or not working (try: right click on project tree -> maven ->reimport)
- IntelliJ cache isn't being updated for some reason (try: file -> Inavlidate caches / restart -> Invalidate and Restart)
- Old IntelliJ or Maven versions

**Comment by thhart** [comment]
One short idea: probably maven got "confused" with an installation of dl4j-examples before. Caches I cleaned already. I will consider to go through it again in a clean system.
