### ISSUE TITLE
Keras model import fails with json mapping exception

### ISSUE THREAD

**Issue by jakobkirkegaard** [deeplearning4j/deeplearning4j#2387]
Minimum code that reproduces the issue in 0.7.1-SNAPSHOT (commit 6fc6fff278f78e7ad661aff268a34fe5d0fc1b00):

```
import org.deeplearning4j.nn.modelimport.keras.Model;
public class KerasImportTest {
    public static void main(String[] args) throws Exception {
        Model.importModel("keras.jsn", "data.h5");
}
}

[complete_stack_trace.txt](https://github.com/deeplearning4j/deeplearning4j/files/616741/complete_stack_trace.txt)

[keras.jsn.txt](https://github.com/deeplearning4j/deeplearning4j/files/616744/keras.jsn.txt)

Content of data.h5 not relevant for issue, same exception caught with empty file.


```

**Comment by tomthetrainer** [comment]
Have you tried Model.importSequentialModel(json_file,hdf5file)

I was able to get that to work for me.

**Comment by jakobkirkegaard** [comment]
I have tried both  Model.importSequentialModel and ModelConfiguration.importSequentialModelConfigFromFile with the same resulting exception.

**Comment by tomthetrainer** [comment]
I was able to import your JSON using the following, Perhaps you can workaround based on this. 

I un-escaped your JSON. 
Put it in a file, 

My import code looks like this, 


```
package org.deeplearning4j.examples.dataExamples;

import org.deeplearning4j.nn.conf.MultiLayerConfiguration;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;

/**
 * Created by tomhanlon on 11/28/16.
 */
public class BugTest {
    public static void main(String[] args)throws Exception `{`
          MultiLayerConfiguration config = org.deeplearning4j.nn.modelimport.keras.ModelConfiguration.importSequentialModelConfigFromFile("/Users/tomhanlon/tensorflow/bug.json");
        MultiLayerNetwork model = new MultiLayerNetwork(config);
        model.init();
    }
```

**Comment by tomthetrainer** [comment]
You may hit another bug when you go to train this model. It may be missing an output layer, we are working on a patch for that right now.

**Comment by turambar** [comment]
@jakobkirkegaard Your Keras config JSON file is malformed, which is causing Jackson to choke. You have a valid serialized JSON string saved _within_ another string. In Keras, I should be able to [load your model](https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model) config using the following commands:

```
import json
from keras.models import model_from_json

config = open(PATH_TO_CONFIG_FILE, 'r').read()
model = model_from_json(config)
```

but I get a `TypeError: string indices must be integers` error when doing so. To successfully load your config using Keras, I need to do:

```
config = json.load(open(PATH_TO_CONFIG_FILE, 'r'))
model = model_from_json(config)
```

What this suggests is that you're taking a properly serialized Keras model config JSON (as returned by `model.to_json()`) and then serializing it again to disk using `json.dump(...)`. You shouldn't do that. You should take the serialized model config JSON and just directly write it to a text file. Check out the `json` documentation [here](https://docs.python.org/2/library/json.html#module-json) for info about proper usage of `load` and `dump` functions is to serialize and deserialize python objects (e.g., dictionary) to and from a string.
