### ISSUE TITLE
Provide option to clear temp files generated during WordVectorSerializer

### ISSUE THREAD

**Issue by KonceptGeek** [deeplearning4j/deeplearning4j#2393]
I have a use case in which I have a word2vec server continuously running and `WordVectorSerializer.writeWord2VecModel` is called at scheduled intervals. As new temp files are generated every time the function is called, the disk utilization continuously increases and for big models it can be quite a lot. Possible to provide an option in the serializer to delete the temp files once the model is written?

**Comment by raver119** [comment]
Implemented/fixed.
