### ISSUE TITLE
Phrase issues

### ISSUE THREAD

**Issue by KonceptGeek** [deeplearning4j/deeplearning4j#2399]
I created a trigram word2vec model using the NGramTokenizer. When looking at nearestWords, I have the following observations:
1. When looking at nearest words of unigrams, majority of the top 1000 nearest words are always unigrams.
2. When looking at nearest words of bigrams, majority of the top 1000 nearest words are always bigrams.
3. When looking at nearest words of trigrams, majority of the top 1000 nearest words are always trigrams.

When a bigram or trigram is not in the vocab and we call `wordsNearest(Collection<String> positive,Collection<String> negative,int top)` the results for top 1000 are always unigrams.

**Comment by raver119** [comment]
What modelUtils you're using? BasicModelUtils?

**Comment by KonceptGeek** [comment]
Configuration that was used:
```
word2Vec = new Word2Vec.Builder()
                .minWordFrequency(10)
                .layerSize(200)
                .learningRate(0.025)
                .minLearningRate(0.0001)
                .windowSize(5)
                .sampling(0.001)
                .seed(1)
                .workers(8)
                .negativeSample(5)
                .iterations(5)
                .stopWords(new ArrayList<String>())
                .elementsLearningAlgorithm(new SkipGram<VocabWord>())
                .useHierarchicSoftmax(false)
                .allowParallelTokenization(false)
                .tokenizerFactory(tokenizerFactory)
                .iterate(word2VecContentIterator)
                .build();
```

**Comment by KonceptGeek** [comment]
@raver119 yes, I'm using BasicModelUtils
