### ISSUE TITLE
Method org.apache.spark.input.PortableDataStream#close is deprecated and shouldn't be used

### ISSUE THREAD

**Issue by elyast** [deeplearning4j/deeplearning4j#2402]
It affects following classes in spark integration project:
```
LoadSerializedDataSetFunction
PortableDataStreamDataSetIterator
PortableDataStreamMultiDataSetIterator
```

It's actually dangerous to call close method in spark 1.6.x since it does nothing, which could lead to resource leaks

I will create pull request

**Comment by elyast** [comment]
#2403 is a pull request

**Comment by raver119** [comment]
Merged. Thanks.
