### ISSUE TITLE
Determine input sizes for specific layers

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#2405]
Currently building a diagnostic tool that will allow me to map the activations across the Computation Graph. What's missing is the ability to know the shape of an input for a specific layer.

i.e., "what is the size of the activations for all layers, given this input?"

Came up in discussion with @AlexDBlack

**Comment by AlexDBlack** [comment]
This functionality already exists internally for MultiLayerConfiguration and ComputationGraph Configuration (used for validation, setting nIns etc).
So it's more a case of making this functionality publicly accessible, in a way that is useful for users.

**Comment by AlexDBlack** [comment]
Added here: https://github.com/deeplearning4j/deeplearning4j/pull/5031
