### ISSUE TITLE
Module deeplearning4j-ui_2.11:0.7.0 doesn`t work on jdk1.7

### ISSUE THREAD

**Issue by matrixlibing** [deeplearning4j/deeplearning4j#2413]
When i migrate from 0.5.0 to 0.7.0, encounted a exception.My code run on hadoop-cluster(2.6.0-cdh5.5.0) with spark framework.

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigValue : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.spark.SSLOptions$.parse(SSLOptions.scala:200)
	at org.apache.spark.SecurityManager.<init>(SecurityManager.scala:245)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:249)
	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:193)
	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:288)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:457)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:59)
	at com.iflytek.vine.model.AdLogClassific.main(AdLogClassific.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

My pom.xml is 

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>vine-parent</artifactId>
        <groupId>com.iflytek.vine</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>vine-ml</artifactId>

    <name>Vine Machine Learning</name>
    <packaging>jar</packaging>

    <properties>
        <dl4j.version>0.7.0</dl4j.version>
        <nd4j.version>0.7.0</nd4j.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>${dl4j.version}</version>
        </dependency>

        

        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native-platform</artifactId>
            <version>${nd4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_${scala.binary.version}</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-mllib_${scala.binary.version}</artifactId>
        </dependency>

        
            
            
        

        <dependency>
            <groupId>com.iflytek.vine</groupId>
            <artifactId>vine-core</artifactId>
            <version>${parent.version}</version>
        </dependency>

        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>dl4j-spark_${scala.binary.version}</artifactId>
            <version>${dl4j.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.scala-lang</groupId>
                    <artifactId>scala-library</artifactId>
                </exclusion>

                <exclusion>
                    <groupId>org.apache.spark</groupId>
                    <artifactId>spark-core_2.11</artifactId>
                </exclusion>

                <exclusion>
                    <groupId>org.apache.spark</groupId>
                    <artifactId>spark-mllib_2.11</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.apache.parquet</groupId>
            <artifactId>parquet-avro</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.parquet</groupId>
            <artifactId>parquet-column</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.parquet</groupId>
            <artifactId>parquet-hadoop</artifactId>
            <version>1.8.1</version>
        </dependency>

        <dependency>
            <groupId>org.apache.avro</groupId>
            <artifactId>avro</artifactId>
        </dependency>

        <dependency>
            <groupId>org.scalatest</groupId>
            <artifactId>scalatest_${scala.binary.version}</artifactId>
        </dependency>

        <dependency>
            <groupId>eu.bitwalker</groupId>
            <artifactId>UserAgentUtils</artifactId>
            <version>1.21-SNAPSHOT-kf</version>
        </dependency>

        <dependency>
            <groupId>org.scala-lang.modules</groupId>
            <artifactId>scala-xml_2.11</artifactId>
            <version>1.0.1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.scala-lang</groupId>
                    <artifactId>scala-library</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>scala-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by AlexDBlack** [comment]
We use the Play framework for the UI (and MapDB for the backend storage), both of which have a hard requirement on java 8. We may look at replacing the MapDB component with something java 7 compatible in the future (that'll allow you to use the remote UI functionality as per the link below), though I should note that Java 7 reached end-of-life over 18 months ago at this point...

Here's notes on the UI + Spark:
https://deeplearning4j.org/visualization#sparkui

**Comment by agibsonccc** [comment]
https://www.cloudera.com/documentation/enterprise/release-notes/topics/cdh_rn_new_in_cdh_59.html This is still relevant for production environments.

**Comment by AlexDBlack** [comment]
FYI the RemoteUIStatsStorageRouter described here https://deeplearning4j.org/visualization#sparkui is defined in deeplearning4j-core which is java 7 compatible.
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/api/storage/impl/RemoteUIStatsStorageRouter.java

(Though as of 0.7.0, Datavec (a dl4j dependenyc) was released with java 8 instead of java 7 language level. That has been fixed as of 0.7.1 which should be out shortly)

**Comment by yinyayun** [comment]
when i use version 0.7.0,I found the page loading slowly,and sometimes even can't open the page.

**Comment by AlexDBlack** [comment]
@yinyayun Can you open a new (separate) issue on github with more details?
I'd need to know things like your system, network configuration, etc in order to debug that.

**Comment by agibsonccc** [comment]
Datavec is now back to being java 7 compatible as of 0.7.1 (released an hour ago with spark bug fixes)

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/2488

The above PR adds 'J7StatsListener' and 'J7FileStatsStorage' classes, and makes InMemoryStatsStorage now Java 7 compatible. There are still dependencies requiring java 8, but I've tested stats collection on a sytem with JDK 7 only, and it works fine.

These can be dropped in for spark training, by replacing StatsListener and FileStatsStorage with the above.

Of course, the UI itself still requires Java 8, as it is based on the Play framework. In those cases, run it is a separate JVM, or save the stats to a file, and load them on a separate PC with java 8 later.
https://deeplearning4j.org/visualization#sparkui
