### ISSUE TITLE
v0.7.0 - Cuda: Under certain circumstances ultra slow

### ISSUE THREAD

**Issue by mjakobus** [deeplearning4j/deeplearning4j#2416]
Hi @raver119 , 

for my business case it is unfortunately necessary that I have a lot of java objects in the memory. But these object have no interaction with deeplearning4j or nd4j. Its just a list of objects each one containing another list of objects.
I noticed that the cuda backend is getting really slow if there are a lot of objects loitering around in the memory (java objects, which are not affecting nd4j and which are doing nothing).

**My measurements:**

```
        // - GPU Performance (Nvidia GTX 950 2048MB) -
        //Without GarbageData:                  3000 samples/sec
        //With GarbageData (1Mio. Objects):     10 samples/sec
        //With GarbageData (50Mio. Objects):    10 sample/year (?) ;-)

        // - CPU Performance (Intel Core i5 6500 + MKL & 16Gb RAM) -
        //Without GarbageData:                  16000 samples/sec
        //With GarbageData (1Mio. Objects):     16000 samples/sec
        //With GarbageData (50Mio. Objects):    16000 samples/sec
```

**System details:**
- Deeplearning4j, nd4j, datavec version: 0.7.0
- Cuda Version 7.5
- Graphics Card: Nvidia Geforce GTX 950 with 2048MB
- Windows 10

**Condensed setup of my program (for reproducing the problem)**:
https://gist.github.com/mjakobus/cf3f076220e98c3ec727205a4ead1f0f

And the DoublesDataSetShuffleIterator (needed as a workaround for issue #2397)
https://gist.github.com/mjakobus/539c85a2866f1165e3f5911dc6a284a1

You can turn the creation of the objects on/off with " boolean createDataGarbage = true;"

The hotspots in each case are also a bit different:
**Cuda with 1 Mio. Objects**:
![with_garbadge](https://cloud.githubusercontent.com/assets/17254924/20786689/d186010a-b7a7-11e6-9112-bbab7e0b0217.PNG)

**Cuda without 1 Mio. Objects**:
![without_garbadge](https://cloud.githubusercontent.com/assets/17254924/20786694/d62a0670-b7a7-11e6-99b9-aebe662b9548.PNG)

Best regards,
 Martin

**Comment by mjakobus** [comment]
Btw. if it is helpful: The visual jvm snapshots from each case:

**With 1 Mio. Objects** 
[with_garbadge.zip](https://github.com/deeplearning4j/deeplearning4j/files/624009/with_garbadge.zip)


**Without 1 Mio. Objects** 
[without_garbadge.zip](https://github.com/deeplearning4j/deeplearning4j/files/624010/without_garbadge.zip)

**Comment by raver119** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/2355

**Comment by mjakobus** [comment]
Sorry, might be a duplicate. Should I copy my issue as a comment to #2355?

**Comment by raver119** [comment]
Nah, i'll just keep this one as additional reference.

**Comment by mjakobus** [comment]
@raver119 
I did additional measurements (using an adapted PerformanceIterationListener), showing that the performance with cuda is affected from the first instanced java object on, whereas the native mkl performance is not affected at all. Looking like this is not a problem which is only affecting java vms with a huge amount of instanced objects.

I'm not a memory/garbage collection specialist, but for me it is looking like with cuda there is perhaps a constant iteration over all generated Java objects? Just guessing ;) 

**Perfromance Native with MKL:**
![native_mkl](https://cloud.githubusercontent.com/assets/17254924/20805952/32bb51e0-b7f9-11e6-8442-88ada9eeedb3.PNG)

**Performance Cuda 7.5:**
![cuda](https://cloud.githubusercontent.com/assets/17254924/20805961/3e2fe3a6-b7f9-11e6-9eba-2747ed8d709b.PNG)

x: Number of instances Java Obects * 1000
y: Samples per second

**Comment by raver119** [comment]
Native is affected (or at least was affected at the moment i was taking my measurements few days ago) as well, just higher pressure is needed. It's mostly about System.gc() calls being used within backends. We are going to get rid of them, but not for this 0.7.1 hotfix release.

**Comment by raver119** [comment]
I mean: we call for System.gc() for our own purposes, and if there's a lot stuff registered within JVM - it takes more time to traverse it for JVM GC. That's literally what happens. We are investigating two viable ways to get rid of System.gc() calls, but that's not an easy/trivial solution to implement, and takes some time.

**Comment by mjakobus** [comment]
I just wanted to confirm, that it is indeed the System.gc() calls, which are slowing down the program. I rewrote my ExampleProgram so that System.gc() was called twice per iteration and testet it with **native MKL**:

**Results Native MKL with 2x System.gc() call per Iteration:**
![native_mkl_with_gc_calls](https://cloud.githubusercontent.com/assets/17254924/20845636/565bfb72-b8c6-11e6-8ea1-1584cd9afd63.PNG)

**Comment by agibsonccc** [comment]
Closing in favor of #2477
