### ISSUE TITLE
method  undefined

### ISSUE THREAD

**Issue by kuluofenghun** [deeplearning4j/deeplearning4j#2421]
we are trying to load a saved keras model, but there are some error in my project. In the method
private static MultiLayerConfiguration importSequentialModelConfig(Map<String,Object> kerasConfig)
            throws IOException, IncompatibleKerasConfigurationException 

the 201th line: the method getL1() and getL2() are undefined for the type Layer

**Comment by agibsonccc** [comment]
This sounds like a version mismatch. Please make sure you are using the latest version (0.7.0) Please come in to gitter for anymore help.
