### ISSUE TITLE
Allow Custom Loss Functions

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#243]
Allow custom cost functions to be specified in configuration.

**Comment by EronWright** [comment]
The challenge is to support this without conflating configuration with execution classes.   

My suggestion is that the user extend the appropriate 'cost function' configuration class.  At execution time, a factory would find an appropriate execution class via a serviceloader.  The user jar would supply a service provider of some sort.   The first-party cost functions could be handled in this way too.

Happy to hack on it if the suggestion seems too complicated.

**Comment by smarthi** [comment]
Agree with Eron. That's a cleaner way of doing it, have the user provide a custom jar and look it up via factory method.

**Comment by agibsonccc** [comment]
Easier method: Dynamic class path discovery via op executioner/op factory. Do class path discovery once via reflections library. Pull out At the end of the day they can create a communication op and include it from anywhere. For legacy purposes allow them to pass in an enum or a string.

Using Nd4j.getOpFactory().createOp("name") they can just pass a name to the configuration.

**Comment by EronWright** [comment]
Adam your suggestion is very similar - ServiceLoader simply formalizes the discovery process.

**Comment by agibsonccc** [comment]
Right. I thought about how to do this already. This doesn't break backwards compat either.

**Comment by EronWright** [comment]
BTW, if we allow user code to supply custom configuration subtypes, then we must worry about how Jackson polymorphism will work.   The JsonSubTypes annotation is used in various places.  Fortunately, additional subtypes may be dynamically added to the ObjectMapper - see [ObjectMapper::registerSubtypes](http://fasterxml.github.io/jackson-databind/javadoc/2.1.1/com/fasterxml/jackson/databind/ObjectMapper.html#registerSubtypes(com.fasterxml.jackson.databind.jsontype.NamedType...)). 

The ultimate solution would then be for user code to supply a service provider that a) enumerates the possible configuration subtypes (for inclusion into the ObjectMapper at both configuration and execution time), and b) provides implementations at execution time.

**Comment by agibsonccc** [comment]
Done. Everything is discovered via reflection.
