### ISSUE TITLE
questions for modelimport project

### ISSUE THREAD

**Issue by kuluofenghun** [deeplearning4j/deeplearning4j#2432]
Hi,
We have been trying to import keras model using dl4j. The version of dl4j is 0.7.1 from git source. Eclipse with jdk 8 is used for this project.
I download the zip source code. Some issues we have encountered so far:
1. In the pom.xml file, there are some questions as follows:
	- Plugin execution not covered by lifecycle configuration: net.alchim31.maven:scala-maven-plugin:3.2.2:add-source (execution: scala-compile-first, 
	  phase: process-resources)
	- Plugin execution not covered by lifecycle configuration: net.alchim31.maven:scala-maven-plugin:3.2.2:compile (execution: scala-compile-first, 
	  phase: process-resources)
	- Plugin execution not covered by lifecycle configuration: net.alchim31.maven:scala-maven-plugin:3.2.2:testCompile (execution: scala-test-compile, 
	  phase: process-test-resources)
	- Plugin execution not covered by lifecycle configuration: com.lewisd:lint-maven-plugin:0.0.8:check (execution: pom-lint, phase: validate)
	- Plugin execution not covered by lifecycle configuration: net.alchim31.maven:scala-maven-plugin:3.2.2:add-source (execution: scala-test-compile, 
	  phase: process-test-resources)
	 
2.  In the deeplearning4j-modelimport project in my eclipse, some methods for layer are not defined, such as layer.getActivationFunction(), layer.getLayerName(),layer.getWeightInit()
 layer.getL1(),layer.getL2(),layer.getDropOut(), layer.getNOut()
 
 Can you give us some suggestions? Thank you!
![method-undefined](https://cloud.githubusercontent.com/assets/23549708/20876581/2392e5cc-bafe-11e6-8dd7-87a19b08d8ca.png)

**Comment by agibsonccc** [comment]
Any reason you're using source rather than maven central?

**Comment by kuluofenghun** [comment]
we are using the released 0.7.1 zip source code. I import the maven project into my eclipse. so I 'm using maven central. Is there any other reason for this issue?

**Comment by turambar** [comment]
@kuluofenghun this looks like a dependency issue, not a problem with model import per se.

**Comment by turambar** [comment]
Closing this because it does not concern an outstanding bug or feature request and there has been no follow-up from the @kuluofenghun for three weeks.
