### ISSUE TITLE
Keras VGG16 import fails

### ISSUE THREAD

**Issue by benqua** [deeplearning4j/deeplearning4j#2440]
I tried the new (keras) modelimport functionality. 

To do so, I cloned [https://github.com/fchollet/deep-learning-models](https://github.com/fchollet/deep-learning-models) and added 
`model.save('models/vgg16_keras.h5')`
Then, I do:
```
import org.deeplearning4j.nn.modelimport.keras.Model

object ImportKerras {
  def main(args: Array[String]): Unit = {
    val model = Model.importFunctionalApiModel("./models/vgg16_keras.h5")
  }
}
```
and it fails with a NotImplementedException.

The example is built with the Keras functional API. I also tried with another vgg16 model based on the sequential api and got an IncompatibleKerasConfigurationException.

I open this issue to keep track on the progress on the import of pre-trained Keras models.
Pre-trained VGG16 are useful for image classification and well tested in Keras. It is an easy example to test if the imported DL4J model predictions match Keras predictions (see #2417).

It would be really nice to be able to use Keras deep-learning-models in DL4J! Tell me if I can help testing something.

**Comment by agibsonccc** [comment]
Thanks for reporting this @turambar will take a look.

**Comment by kuluofenghun** [comment]
Did you load you model successfully? We are also trying to load a keras model in java, but it failed? I also can't add right dependency information in pom.xml. Can you  help me to load the model? I build my project in eclipse, JDK 1.8.

**Comment by benqua** [comment]
Hi @kuluofenghun, 

No, as stated above, I couldn't import a keras model in java.
The keras import module is clearly still a work in progress; you might get more information about the evolution of this module by following this issue (that's why I opened it).

Regarding your pom.xml issue, I cannot help. Have a look at the example dl4j project (https://github.com/deeplearning4j/dl4j-examples) and do the same, it should work.

**Comment by benqua** [comment]
There are two points in this issue:

1. modelimport doesn't support the Keras models built with the functional API
2. modelimport throws an IncompatibleKerasConfigurationException when importing a VGG16 model built with the keras sequential API.

A little bit more information for point (2): I tried to import the VGG16 model built with the sequential api available at  https://github.com/heuritech/convnets-keras and the importmodel complains because the import of ZeroPadding2D keras layer is not supported.

`org.deeplearning4j.nn.modelimport.keras.IncompatibleKerasConfigurationException: Unsupported keras layer type ZeroPadding2D For more information, see https://deeplearning4j.org/model-import-keras.
	at org.deeplearning4j.nn.modelimport.keras.LayerConfiguration.buildLayer(LayerConfiguration.java:105)
	at org.deeplearning4j.nn.modelimport.keras.ModelConfiguration.importSequentialModelConfig(ModelConfiguration.java:188)
	at org.deeplearning4j.nn.modelimport.keras.ModelConfiguration.importSequentialModelConfig(ModelConfiguration.java:70)
	at org.deeplearning4j.nn.modelimport.keras.Model.importModel(Model.java:220)
	at org.deeplearning4j.nn.modelimport.keras.Model.importModel(Model.java:195)
	at org.deeplearning4j.nn.modelimport.keras.Model.importSequentialModel(Model.java:150)
`

I am not really sure the ZeroPadding2D layers are mandatory (they are part of the functional VGG16 model by fchollet). This week-end, I will try to adapt the VGG16 sequential model to get ride of the ZeroPadding2D layers and report back the result.

Still, the support of the functional API would be great as it is the one used by fchollet for the keras deep-learning-models repository.

**Comment by benqua** [comment]
I did remove the ZeroPadding2D layers (by adding border_mode='same' to the convolution layer).
The model still works fine in keras.

Now, I get another exception when trying to import the model and the weights in dl4j with 
` val model = Model.importSequentialModel("./models/vgg16_keras_seq_model.json", "./models/vgg16_keras_seq_weights")`

`java.lang.IllegalStateException: Mis matched lengths: [2097152] != [102760448]
	at org.nd4j.linalg.util.LinAlgExceptions.assertSameLength(LinAlgExceptions.java:40)
	at org.nd4j.linalg.api.ops.BaseTransformOp.<init>(BaseTransformOp.java:48)
	at org.nd4j.linalg.api.ops.impl.transforms.Set.<init>(Set.java:25)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:1126)
	at org.deeplearning4j.nn.layers.BaseLayer.setParam(BaseLayer.java:277)
	at org.deeplearning4j.nn.modelimport.keras.Model.importWeights(Model.java:389)
	at org.deeplearning4j.nn.modelimport.keras.Model.importModel(Model.java:234)
	at org.deeplearning4j.nn.modelimport.keras.Model.importModel(Model.java:195)
	at org.deeplearning4j.nn.modelimport.keras.Model.importSequentialModel(Model.java:150)
	at name.benq.ImportKerras$.main(ImportKeras.scala:9)
	at name.benq.ImportKerras.main(ImportKeras.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
` 

@turambar tell me if I can do something else to help you with this issue.

**Comment by turambar** [comment]
@benqua @kuluofenghun Support for the Functional API should be ready in the next 24 hours. Will post an update here once it is. Then I'll get to work directly on this issue.

**Comment by turambar** [comment]
@benqua @kuluofenghun The `model_loading` branch now supports Functional API, at least for relatively straightforward graphs without exotic reshapes and merges. Should be incorporated into the forthcoming release (by end of week) if you don't want to build from source. I will commence testing and debugging the [VGG](https://github.com/fchollet/deep-learning-models/blob/master/vgg16.py) and [Inception](https://github.com/fchollet/deep-learning-models/blob/master/inception_v3.py) models tomorrow.

**Comment by bbartlett-beamio** [comment]
Hello, has anyone been able to successfully import either of the VGG or Inception Models? I tried the following but I get a null pointer exception which I traced to the weight load. It seems that the weight keys are different than the vertex layer names? Same issue with Inception as well... (using the 0.7.2 release)

'KerasModelImport kmi = new KerasModelImport("theanoVGG16JSON.txt", "theanoVGG16Weights.h5");
KerasModel kerasModel = new KerasModel(kmi.getModelJson(), null, null, kmi.getWeights(), false);
ComputationGraph cgGraph = kerasModel.getComputationGraph(true);'

**Comment by agibsonccc** [comment]
@bbartlett-beamio You will be able to in the next release. @turambar / @eraly got it working.  A status update might not hurt here though.

**Comment by bbartlett-beamio** [comment]
@agibsonccc just checked and it appears that 0.7.2 was released 27 days ago. I would have thought the functionality discussed in this thread would be available? @turambar @eraly , do you know if the weights load correctly on master?

**Comment by turambar** [comment]
@bbartlett-beamio Thank you for your enthusiastic support of this project. It's good to know folks are eagerly awaiting the results of our ongoing development efforts. Full support for VGG16 import can be found in the [model_loading](https://github.com/deeplearning4j/deeplearning4j/tree/model_loading) branch at this moment and should be integrated into master shortly.

You can find a succinct summary of the Keras model import syntax in [this gist](https://gist.github.com/turambar/be0a96a02fd1ba3f6010bc0d17fc90dc).

FYI: the Theano backend has been tested more thoroughly than the TensorFlow backend at this moment, but our expectation is that TF should work fine.

**Comment by bbartlett-beamio** [comment]
@turambar thanks for the update and gist!

**Comment by turambar** [comment]
We're closing this for now: expect changes in `model_loading` branch to be merged over the weekend and then to be included in the next release.
