### ISSUE TITLE
Sequential Model load failed

### ISSUE THREAD

**Issue by kuluofenghun** [deeplearning4j/deeplearning4j#2444]
I am trying to load a saved keras model, it is very helpful for us.
But I meet some questions. My code is as follow:

import org.deeplearning4j.nn.modelimport.keras.Model;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class modelimport {
	private static final Logger log = LoggerFactory.getLogger(modelimport.class);

	public static void main(String[] args) throws Exception {
		String jsnPath = "C:\\Users\\liuying\\Desktop\\keras model\\intent_dnn_model_v1.jsn";
		String hdfPath = "C:\\Users\\liuying\\Desktop\\keras model\\intent_dnn_weights_v1.h5";
		MultiLayerNetwork model = Model.importSequentialModel(jsnPath, hdfPath);
		System.out.println("loaded");
	}
}

but it failed and the error information is 
![qq 20161206141219](https://cloud.githubusercontent.com/assets/23549708/20914981/0ac8e206-bbbe-11e6-857a-c17600cce32a.png)

Could you help me to solve this?

**Comment by kuluofenghun** [comment]
This is my pom.xml file
[pom.zip](https://github.com/deeplearning4j/deeplearning4j/files/633121/pom.zip)

**Comment by agibsonccc** [comment]
This isn't a dl4j problem. You mis specified your own path. If you look at the end you misspelled json on the format.

**Comment by kuluofenghun** [comment]
I tried to load a saved keras model, it would be really nice to be able to load keras model in DL4j. I am using the new released 0.7.1 in maven central.
But it failed. I can't add the right dependency information into my pom.xml.  Then I try to git clone the source, but it also failed because of my network.
Can you provide the git source or the right pom.xml to me by email? It is really helpful for my work. Thank you!






At 2016-12-06 14:47:34, "Adam Gibson" <notifications@github.com> wrote:


This isn't a dl4j problem. You mis specified your own path. If you look at the end you misspelled json on the format.
