### ISSUE TITLE
leakyReluAlpha value is lost

### ISSUE THREAD

**Issue by lpaatero** [deeplearning4j/deeplearning4j#2446]
Setting leakyReluAlpha value in NeuralNetConfiguration.Builder seems to be lost at some point in version 0.7.1.
Following code fragment demonstrates problem:

```
new NeuralNetConfiguration.Builder()
        .leakyreluAlpha(0.1)
...
MultiLayerConfiguration conf = builder.build();
    MultiLayerNetwork model = new MultiLayerNetwork(conf);

```
then printing value
`System.err.println("alpha" +model.conf().getLeakyreluAlpha() );
gives 0.0

Looking from source, it seems that NeuralNetConfiguration builder never initializes NeuralNetConfiguration parameter leakyReluAlpha, and thus it is always 0.

**Comment by AlexDBlack** [comment]
Thaks for reporting.
We're in the process of overhauling how activation functions are handled, at which point this issue (and the configuration option in general) will be obsolete. I'll keep this issue open until then I guess?

Keep an eye on the following for that:
https://github.com/deeplearning4j/nd4j/pull/1476
https://github.com/deeplearning4j/deeplearning4j/issues/2225

**Comment by lpaatero** [comment]
Workaround for this would be nice.

Doing conf.getConf(0).setLeakyreluAlpha(0.1) after builder.build()  does not seem to change  alpha in layer (at least based on serialized output of model).

**Comment by AlexDBlack** [comment]
No longer relevant activation functions have been refactored into classes: https://github.com/deeplearning4j/deeplearning4j/pull/2538
https://github.com/deeplearning4j/nd4j/pull/1530
