### ISSUE TITLE
ComputationGraph `training` parameter not propagated

### ISSUE THREAD

**Issue by EdeMeijer** [deeplearning4j/deeplearning4j#2449]
Not 100% sure but in `ComputationGraph::score(MultiDataSet dataSet, boolean training)`, on line 1422 there is a call to `computeScore` with a hard coded `true` for `training`. In MultiLayerNetwork, the same method actually passes the given `training` parameter in there, so I think this is a bug. Can't easily test or make a PR right now because master is broken, so I'll leave this here for you :)

**Comment by AlexDBlack** [comment]
Only affects output layer (rest of graph forward pass is OK). Still a bug, however.

https://github.com/deeplearning4j/deeplearning4j/pull/2450

**Comment by EdeMeijer** [comment]
Sure, it didn't bother me, just noticed it.
