### ISSUE TITLE
Loading Google word2vec model from stream

### ISSUE THREAD

**Issue by arunwizz** [deeplearning4j/deeplearning4j#2458]
Currently to load Google word2vec model through WordVectorSerializer class, it seems loading via File is the only option, is there anyway to load model from stream? That would allow to keep model in a classpath and avoid file path.

**Comment by raver119** [comment]
No, we're not hiding any special methods. 
But obviously you can write your own method for it, just based on this code: https://github.com/deeplearning4j/deeplearning4j/blob/af60b77b09392da7f1648f027f75bd629f302409/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/loader/WordVectorSerializer.java#L224-L224

As you can see, there's minor concern there: you need to know in advance, if that's gzip-ed model or not.

**Comment by raver119** [comment]
Also, we have ClassPathResource impl, that should work for you. It's available in utilities of DataVec.

**Comment by arunwizz** [comment]
Thanks @raver119, will you accept PR in case I overload readBinaryModel() function for stream in above class?

**Comment by raver119** [comment]
Sure, why not if it will be nice. Come to our gitter channel, and we'll discuss signatures, to make sure use of new methods will be clear for users.

**Comment by arunwizz** [comment]
cool, will ping you on gitter soon.

**Comment by arunwizz** [comment]
@raver119 - I noticed loadGoogleModel() method is now deprecated. Does it make sense to overload it for input stream now? May be we need to see if alternate model loading methods can be overloaded from input stream. What do you say?

**Comment by raver119** [comment]
Methods that accepts File as input are being shifted to single signature, instead of 5 different ones.

But obviously, such shift is impossible for methods that take InputStream argument. So that particular method won't be removed: you're speaking about edge use case.

**Comment by arunwizz** [comment]
Ok, so if I understood correctly loadGoogleModel() is going to stay. And I can still think of coming up with input stream based signature for this.
