### ISSUE TITLE
Cannot run dl4j with Spring Boot based Applications

### ISSUE THREAD

**Issue by jvence** [deeplearning4j/deeplearning4j#2459]
There's an issue with JaxbAnnotationModule. It would appear that it doesn’t extend com.fasterxml.jackson.databind.Module. 

Here's the error: 
Caused by: java.util.ServiceConfigurationError: com.fasterxml.jackson.databind.Module: Provider org.nd4j.shade.jackson.module.jaxb.JaxbAnnotationModule not a subtype

Full stacktrace:
https://gist.github.com/jvence/88ca3f0f6cf948fcfc130782b22649dd

dl4j version 0.7.0

**Comment by kuluofenghun** [comment]
your gist URL above can't be opened

**Comment by kuluofenghun** [comment]
I meet some question:Exception in thread "main" java.lang.NoClassDefFoundError: org/nd4j/shade/jackson/core/type/TypeReference

I also try git source of dl4j, the same error in the project.
Can you help me to solve this?

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/issues/2459
That PR removes the dependencies pulling in JabxAnnotationModule
