### ISSUE TITLE
Summary line in UI overview is off

### ISSUE THREAD

**Issue by EdeMeijer** [deeplearning4j/deeplearning4j#2465]
In the 'Model Score vs. Iteration' graph on the overview page in the UI, the summary line is scaled wrong horizontally. I'm pretty sure it should be full width.

![summary](https://cloud.githubusercontent.com/assets/5758565/21011021/8864de12-bd4f-11e6-959b-4103831ce07b.png)

I tried in Chrome and Firefox, both show the same thing. I'm using a fairly recent 0.7.2. Let me know if you need more info.

**Comment by AlexDBlack** [comment]
I think I know what's happening here: the UI backend subsamples the data (i.e., render every N points when necessary) to avoid posting too much network comm and rendering time.
The summary line should be using the x-position points from the data itself, rather than just a counter for the x position.

**Comment by EdeMeijer** [comment]
I noticed the subsampling, because the graph can be very jumpy. There's basically a lot of aliasing going on, would it maybe an idea to use averaging instead of sampling? If we average in frames of powers of 2, then we could keep a cache of averaged data and re-average those values if the sampling window doubles again, so that stuff stays fast.

**Comment by AlexDBlack** [comment]
The reason I didn't go for averaging in the first place as I didn't want to lose too much information about the variability of loss function over time. Subsampling a random variable has the same variance, but the average of a random variable has smaller variance. IMO the variability of the score vs. iter chart is useful information that I'd like to maintain if possible.

Other than that, averaging would be preferable. I'm open to revisiting that design though.

**Comment by EdeMeijer** [comment]
So maybe introduce a band plot showing variance around the mean? Ah well, it's not that big an issue, just an idea. An aligned trend line would be nice though :)

**Comment by AlexDBlack** [comment]
Fixed here, will be merged later: https://github.com/deeplearning4j/deeplearning4j/pull/2538
