### ISSUE TITLE
model.output(...) crashes on 0.7.1

### ISSUE THREAD

**Issue by tombear1** [deeplearning4j/deeplearning4j#2467]
Usage of model.output(...) crashes on 0.7.1 but runs fine on 0.6.0
Don't know if it's relevant but I'm calling output() on a model broadcasted via SparkContext, like here:

```
    val bModel = sc.broadcast(model)
    def getOutput(ds: DataSet) = {
      val output = bModel.value.output(ds.getFeatures)
      ...
    }
```

This is the RNN model config that i'm using:
https://gist.github.com/tombear1/7c588e5d48da95892cdb99e0a9f479f4

What's weird is that sometimes it results in _Unable to get number of of rows for a non 2d matrix_ error:
https://gist.github.com/tombear1/f284f37b44a93140be62bc7b3e0731ea
and sometimes in _Input that is not a matrix; expected matrix (rank 2), got rank 3 array with shape [1, 2, 8]_ error:
https://gist.github.com/tombear1/e1bc20f5a47184a1947d79df9d92993a

**Comment by AlexDBlack** [comment]
I'm guessing this doesn't occur when run without spark (I can't see how it would).
So my best guess would be a serialization issue?

For reference, here's how we handle models + broadcasts in spark training: we keep config + params separate, and initialize a model from them.

https://github.com/deeplearning4j/deeplearning4j/blob/0d6c5f38a77f51ca7b800ab2478dad810750d966/deeplearning4j-scaleout/spark/dl4j-spark/src/main/java/org/deeplearning4j/spark/api/worker/NetBroadcastTuple.java

https://github.com/deeplearning4j/deeplearning4j/blob/0d6c5f38a77f51ca7b800ab2478dad810750d966/deeplearning4j-scaleout/spark/dl4j-spark/src/main/java/org/deeplearning4j/spark/impl/paramavg/ParameterAveragingTrainingWorker.java#L89

**Comment by tombear1** [comment]
Yay, broadcasting NetBroadcastTuple instead of model works great! Wasn't aware of it. Thanks a lot!
