### ISSUE TITLE
Dropout overwrites previous layer's output

### ISSUE THREAD

**Issue by turambar** [deeplearning4j/deeplearning4j#2469]
The `Drop.applyDropout(*)` function applies dropout _in place_, modifying the input vector. Thus, when it is used in DL4J layers, e.g., `BaseLayer.applyDropOutIfNecessary(*)` [here](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/layers/BaseLayer.java#L462), it overwrites the previous layer's output. This yields unexpected results when trying to get out individual layer's activations from a forward pass.

Note this is *only* a problem during `training=true` mode.

Here's a [gist](https://gist.github.com/turambar/87ef94ca85ad21f7952cf360ac7b98c7).

**Comment by turambar** [comment]
Proposed fix [here](https://github.com/deeplearning4j/deeplearning4j/blob/model_loading/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/layers/BaseLayer.java#L462): when dropout is applied during the `applyDropOutIfNecessary(*)` function, we duplicate the input.

**Comment by agibsonccc** [comment]
Didn't this get fixed?

**Comment by turambar** [comment]
@agibsonccc Uh, yes, yes it did. Closing now.
