### ISSUE TITLE
Cuda backend slows down over time

### ISSUE THREAD

**Issue by reidswanson** [deeplearning4j/deeplearning4j#2477]
Training a mini-batch takes longer and longer each iteration when using the cuda backend, but I don't see the same issue when switching to the native/cpu backend. On the first few iterations it processes about 110 examples/sec. After about 50-60 iterations it starts training at about half that speed and by 150 iterations it is processing less then 1 example a second. With the cpu backend it consistently processes about 30 examples/sec for over 300 iterations/batches.

Some relevant hardward/software specs
GPU: GTX 1080
OS: Linux
Driver: 375.20
CUDA: 8.0.44
PCIE v2 x16

Here is my network config with some relevant parameters:
```
nin = 12715
options.hiddenStates = 200
nout = 19
numberOfTimesteps = 20
batchSize = 128
```
Note the LossIntegerMSE is virtually the same as LossMSE except I round all values to the nearest integer.
```
NeuralNetConfiguration.Builder builder = new NeuralNetConfiguration.Builder();

 ListBuilder listBuilder =
	builder
		.optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
		.iterations(1)
		.learningRate(0.01)
		.dropOut(0.5)
		.seed(0)
		.regularization(true)
		.l2(0.0001)
		.weightInit(WeightInit.XAVIER)
		.updater(Updater.NESTEROVS)
		.momentum(0.95)
		.learningRateDecayPolicy(LearningRatePolicy.Inverse)
		.lrPolicyDecayRate(0.99)
		.lrPolicyPower(0.0005)
		.list();

int layerNumber = 0;
listBuilder
	.layer(
		layerNumber++, 
			new GravesLSTM.Builder()
				.nIn(nin)
				.nOut(options.hiddenStates)
				.activation("tanh")
				.gradientNormalization(GradientNormalization.ClipL2PerParamType)
				.build()
		);

int nHiddenLayers = 1;
for (int i = 0; i < nHiddenLayers; ++i) {
	listBuilder
		.layer(
			layerNumber++, 
			new GravesLSTM.Builder()
				.nIn(options.hiddenStates)
				.nOut(options.hiddenStates)
				.activation("tanh")
				.gradientNormalization(GradientNormalization.ClipL2PerParamType)
				.build()
			);
}

listBuilder
	.layer(
		layerNumber,
		new RnnOutputLayer.Builder(new LossIntegerMSE())
			.nIn(options.hiddenStates)
			.nOut(nout)
			.activation("identity")
			.build()
		);

return
	listBuilder
		.backpropType(BackpropType.TruncatedBPTT)
		.tBPTTForwardLength(options.truncatedBackPropSteps)
		.tBPTTBackwardLength(options.truncatedBackPropSteps)
		.pretrain(false)
		.backprop(true)
		.build();
       
```
Here's a snapshot of jvisualvm starting roughly at the beginning during some data preprocessing through about 100 iterations.
![jvisualvm-snapshot-2](https://cloud.githubusercontent.com/assets/802748/21087628/8ed7d404-bfdc-11e6-9e9d-f8114c31c8ee.png)

And a snapshot of nvidia-smi around the same time
![nvidia-smi](https://cloud.githubusercontent.com/assets/802748/21087638/a825c470-bfdc-11e6-9037-1e97d95019c7.png)

**Comment by raver119** [comment]
74% of time is GC, sure it's getting slower.

Please check this two issues, it explains what happens: 
- https://github.com/deeplearning4j/deeplearning4j/issues/2416
- https://github.com/deeplearning4j/deeplearning4j/issues/2355

**Comment by reidswanson** [comment]
Ok, it looks like it's the issue where I generate a bunch of stuff before computation and then the GC spends a bunch of time traversing the objects each iteration. If I understood the other threads correctly, you're trying to implement a way to avoid the garbage collector in a (hopefully) next release, which should help with this problem.

Thanks for the pointers and sorry I didn't see them earlier.

**Comment by raver119** [comment]
This issue is addressed here: https://github.com/deeplearning4j/nd4j/pull/1731

**Comment by AlexDBlack** [comment]
Closing this - was addressed long ago with workspaces.
