### ISSUE TITLE
compile bug, can you help me?

### ISSUE THREAD

**Issue by xuxilei** [deeplearning4j/deeplearning4j#2478]
[INFO] DeepLearning4j ..................................... SUCCESS [  1.686 s]

[INFO] deeplearning4j-nn .................................. FAILURE [  0.293 s]

[ERROR] Failed to execute goal on project deeplearning4j-nn: Could not resolve dependencies for project org.deeplearning4j:deeplearning4j-nn:jar:0.7.2-SNAPSHOT: Failed to collect dependencies at org.nd4j:nd4j-api:jar:0.7.2-SNAPSHOT: Failed to read artifact descriptor for org.nd4j:nd4j-api:jar:0.7.2-SNAPSHOT: Could not transfer artifact org.nd4j:nd4j-api:pom:0.7.2-SNAPSHOT from/to sonatype-nexus-sn

ERROR] For more information about the errors and possible solutions, please read the following articles:

[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by agibsonccc** [comment]
Please don't blindly just jump in to doing things without reading the proper documentation(https://deeplearning4j.org/buildinglocally) or consulting our gitter channel: https://gitter.im/deeplearning4j/deeplearning4j

Blindly jumping in is never good practice for any new project you try ;)
