### ISSUE TITLE
compile bug(1)

### ISSUE THREAD

**Issue by xuxilei** [deeplearning4j/deeplearning4j#2482]
I  obey you: https://deeplearning4j.org/buildinglocally , "Building Manually"
cd deeplearning4j
mvn clean install -DskipTests -Dmaven.javadoc.skip=true

I meet:
[ERROR] Failed to execute goal on project deeplearning4j-nn: Could not resolve dependencies for project org.deeplearning4j:deeplearning4j-nn:jar:0.7.2-SNAPSHOT: The following artifacts could not be resolved: org.nd4j:nd4j-api:jar:0.7.2-SNAPSHOT, org.nd4j:jackson:jar:0.7.2-SNAPSHOT: Could not find artifact org.nd4j:nd4j-api:jar:0.7.2-SNAPSHOT in sonatype-nexus-snapshots

**Comment by agibsonccc** [comment]
The guide steps you through this you need to clone everything.
