### ISSUE TITLE
ImageRecordReader link broken

### ISSUE THREAD

**Issue by gsw85** [deeplearning4j/deeplearning4j#2493]
Page: https://deeplearning4j.org/datavec
Section: Reading Records, Iterating Over Data

"The **ImageRecordReader** is a subclass of the RecordReader and is built to automatically take in 28 x 28 pixel images. Thus, LFW images are scaled to 28 pixels x 28 pixels. You can change dimensions to match your custom images by changing the parameters fed to the ImageRecordReader, as long as you make sure to adjust the nIn hyperparameter, which will be equal to the product of image height x image width." 

The link for  ImageRecordReader is broken:

**Comment by chrisvnicholson** [comment]
fixed
