### ISSUE TITLE
Conv Net Example hitting an error and failing on MultiLayer

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#250]
Error: Exception in thread "main" java.lang.IllegalStateException: Unable to get number of cols for a non 2d matrix

Failiing at:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java#L395

**Comment by agibsonccc** [comment]
FIxed this in another branch to be merged. I throw an error when figuring out the type for the multi layer network when it doesn't know what it is rather than the fallback. This should make a lot of things less mysterious.
