### ISSUE TITLE
Broken link in eigenvector documentation

### ISSUE THREAD

**Issue by gsw85** [deeplearning4j/deeplearning4j#2502]
Page: https://deeplearning4j.org/eigenvector
section: Just Give Me the Code

broken link:  eigenvectors

in the sentence of:
You can see how we do eigenvectors in ND4J, a numerical computing library for the JVM that handles n-dimensional arrays, broadly inspired by Numpy. ND4J has Java and Scala APIs, runs on Hadoop and Spark, and is roughly twice as fast as Numpy/Cython on very large matrix operations.

**Comment by chrisvnicholson** [comment]
fixed
