### ISSUE TITLE
NullPointerException when training ParagraphVectors

### ISSUE THREAD

**Issue by ErikTromp** [deeplearning4j/deeplearning4j#2504]
I am getting a NullPointerException when calling `fit` on ParagraphVectors (running on GPU, using 0.7.1):

```
java.lang.NullPointerException: null
at org.deeplearning4j.models.embeddings.inmemory.InMemoryLookupTable.consume(InMemoryLookupTable.java:689) ~[deeplearning4j-nlp-0.7.1.jar:na]
at org.deeplearning4j.models.sequencevectors.SequenceVectors.buildVocab(SequenceVectors.java:103) ~[deeplearning4j-nlp-0.7.1.jar:na]
at org.deeplearning4j.models.sequencevectors.SequenceVectors.fit(SequenceVectors.java:178) ~[deeplearning4j-nlp-0.7.1.jar:na]
at org.deeplearning4j.models.paragraphvectors.ParagraphVectors.fit(ParagraphVectors.java:448) ~[deeplearning4j-nlp-0.7.1.jar:na]
at tuktu.deeplearn.models.Doc2Vec.train(Doc2Vec.scala:141) ~[classes/:na]
```

The code I am using can be found here (excerpt): https://gist.github.com/ErikTromp/87c6ffc11dbecf79174b74b2ea538743
Running on a small dataset works fine (same code), but running it on a larger one (larger word embedding file too) results in this error.

Parameters:
```
"min_word_frequency": 5,
"iterations": 5,
"epochs": 5,
"layer_size": 50,
"learning_rate": 0.025,
"window_size": 5,
"sampling": 0,
"batch_size": 4000,
"word2vec_model": "vectors.bin"
```

**Comment by raver119** [comment]
Right, fit() is the issue here, which isn't supposed to be used with existingWordVectors being set.

I'll provide proper handling on this usecase.

**Comment by ErikTromp** [comment]
Are you saying that I shouldn't call .fit on doc2vec entirely when I load existing word vectors? I was planning on using my pre-trained word vectors (on large unlabeled data) as starting point to next load in DL4J and use doc2vec for classification purposes. Is this not possible then?

**Comment by raver119** [comment]
At least that's not in list of currently supported functionality. Probably, if existingModel is full - why not then... I should think about it. But right now nobody tested thing you're trying to do.

**Comment by ErikTromp** [comment]
Okay, clear. Weird thing is though, that when I use the exact same code, also with pre-trained word vectors from the google implementation, but then on a significantly smaller dataset, it does finish properly and I do not encounter the error.

**Comment by raver119** [comment]
As i've said - that use scenario looks possible (_NOT FOR GOOGLE MODEL!_), i just need to check math for that use case, and ensure that model contains not the weights only, but HS/Neg states.

**Comment by ErikTromp** [comment]
OK, looking forward - I'll continue on a different path for now then. Will monitor this issue.

**Comment by raver119** [comment]
Issue is addressed here: https://github.com/deeplearning4j/deeplearning4j/pull/2520

Now we explicitly check, if existingModel contains syn1/syn1Neg defined.
