### ISSUE TITLE
ModelSerializer - add options to persist Normalizers

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2506]
Idea: add and load a DataNormalization instance to/from a zip file created with the ModelSerializer.

Being a zip file, it should be possible to add and load the normalizer in a separate step to the model saving/loading, but to/from the same file.

So ModelSerializer.addNormalizerToModel(File f, DataNormalization) and ModelSerializer.loadNormalizerFromFile(File f)

**Comment by raver119** [comment]
Implemented here: https://github.com/deeplearning4j/deeplearning4j/pull/2521/files
