### ISSUE TITLE
UI: activations don't account for masking

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2508]
The UI provides mean and standard deviation values for the activation arrays.
Currently, it ignores masking arrays - the masked values may artifically increase/decrease the mean/stdev.

**Comment by EdeMeijer** [comment]
Here's a gist with an example to reproduce it

https://gist.github.com/EdeMeijer/995351c3d98ad7f1012890d9e07619e6

I added a hidden layer to the example to demonstrate that it's not just about the input layer, but all the layers. The output of this example is
```
{in=[[-1.22, 0.00, 1.22, -2,450.71, -2,450.71]], L1=[[0.84, 0.36, 0.05, 3,163.91, 4,458.20]]}
```

**Comment by raver119** [comment]
@AlexDBlack can we close this issue?

**Comment by AlexDBlack** [comment]
Yes, I believe this was normalizer related - masks were (then, but fixed now) not being use to set values back to 0.
