### ISSUE TITLE
Can't allocate [HOST] memory: 301858816 on multy GPUs training

### ISSUE THREAD

**Issue by n-gregori** [deeplearning4j/deeplearning4j#2522]
hello, i've big trouble with training Google LeNet (Vgg too) with a pretty large image's dataset. now im' using aws instance with 8 GPUs Tesla K80 with 12g each and 490g of ram. this is the problem: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Can't allocate [HOST] memory: 301858816; threadId: 105 
[exeption.txt](https://github.com/deeplearning4j/deeplearning4j/files/657897/exeption.txt)

**Comment by raver119** [comment]
Please, provide ***full*** output log. Exception itself is interesting, but useless. Full log needed.

**Comment by raver119** [comment]
Also, please show source code used to reproduce this crash. If you want to keep it private, you can send it to me as gist ( https://gist.github.com/ )

**Comment by n-gregori** [comment]
[faces-multi_exception.txt](https://github.com/deeplearning4j/deeplearning4j/files/657909/faces-multi_exception.txt)



line 109 in MultiGpuGraphTrainer.scala cited in the exception is:

def trainEpoch(epochN: Int, save: Boolean, keep: Int): String = {
    
    wrapper.fit(datasetTrain)

**Comment by raver119** [comment]
Hm, surprising, but it really looks like OOM message.

What CUDA version you have there?

**Comment by n-gregori** [comment]
CUDA version: 8.0 
DL4J version: 0.7.0

**Comment by raver119** [comment]
Posting full log as gist for future reference: https://gist.github.com/raver119/c144846f7dc0459c0a7a8816208af962

**Comment by raver119** [comment]
Show Dl4j-related source code please, and tell me what input data dimensions are. Image dimensions i mean.

**Comment by raver119** [comment]
P.s. also please consider using 0.7.1, it contains few important fixes for bugs found after 0.7.0 releases

**Comment by n-gregori** [comment]
the dataset thai i used is:
381 labels
100 images x label at 224x224 3 channels

**Comment by agibsonccc** [comment]
Something non obvious: Could you share the architecture? (I know you said vgg 16 but config still helps) and were you using cudnn or raw dl4j?

**Comment by raver119** [comment]
cudnn is used there.

**Comment by raver119** [comment]
but i see suspicious reports from ParallelWrapper, and i want to see how exactly things are set up.

**Comment by n-gregori** [comment]
@raver119 i sent private gist to your email address

**Comment by raver119** [comment]
@n-gregori can you please also show deviceQuery output?

**Comment by raver119** [comment]
also, please apply these two changes to your config:
- set 1GB max cache: .setMaximumDeviceCache(1024 * 1024 * 1024L)
- fall back to legacy averaging: .useLegacyAveraging(true)

**Comment by raver119** [comment]
And one more thing: you say workers set to 8, but i see it's only 2 in logs. Are you sure about 8?

**Comment by n-gregori** [comment]
@raver119 initially i tried with 8 workers and finally with 2.

**Comment by n-gregori** [comment]
@raver119 

i've now installed 0.7.1, versions.

cuda settings:

  CudaEnvironment.getInstance().getConfiguration()
    .allowMultiGPU(true)
    .allowCrossDeviceAccess(true)
    .setMaximumDeviceCacheableLength(1024 * 1024 * 1024L)
    .setMaximumDeviceCache(1024 * 1024 * 1024L)
    .setMaximumHostCacheableLength(1024 * 1024 * 1024L)
    .setMaximumHostCache(1024 * 1024 * 1024L)
    .setMaximumGridSize(512)
    .setMaximumBlockSize(512)

  CudaEnvironment.getInstance().getConfiguration().allowMultiGPU(true)


and parallel wrapper:

    wrapper = new ParallelWrapper.Builder(net.asInstanceOf[MultiLayerNetwork])
        .prefetchBuffer(prefetchBuffer)
        .workers(workers)
        .averagingFrequency(averagingFrequency)
        .reportScoreAfterAveraging(true)
        .useLegacyAveraging(true)
        .build()


using ec2-amazon instance p2.8xlarge:
8 GPUs Tesla K80 with 12g each and 490g of ram


i'm trying to train VggC net on the same dataset (381 labels
100 images x label at 224x224 3 channels)

finally i get the same exception....

What's wrong?

**Comment by paulhanke** [comment]
... seeing same issue on 0.7,2

**Comment by raver119** [comment]
@paulhanke yep, we're aware of that. Fix for this issue will be the part of next major release.

**Comment by raver119** [comment]
Fixed long ago
