### ISSUE TITLE
Categorization of Applications

### ISSUE THREAD

**Issue by 9xgame** [deeplearning4j/deeplearning4j#2532]
Hello,
I’m studying Computer Engineering at İstanbul. I’m working on the project “categorization of applications using deep learning” on a very small dataset named Sharejar. I can’t figure it out, I’m stuck. Is there any chance to help me?
Thank you

http://www.cs.wm.edu/semeru/catml_ese/

**Comment by agibsonccc** [comment]
Hi, The gitter channel and this issues repository are not for general deep learning questions, if you intend on using the framework please come back with a more specific question.
