### ISSUE TITLE
Cannot restore saved word2vec by WordVectorSerializer

### ISSUE THREAD

**Issue by samuel281** [deeplearning4j/deeplearning4j#2533]
Hi, I'm trying to train a word2vec model on spark and save it on the local file system to use it later.
I think I could train and save the model succesfully but I got following exception when I try to read the model by WordVectorSerializer 

---------------- message start ------------
java.lang.IllegalArgumentException: Word must not be null or empty
	at org.deeplearning4j.models.word2vec.VocabWord.<init>(VocabWord.java:58)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadTxt(WordVectorSerializer.java:1736)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecFromText(WordVectorSerializer.java:970)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2Vec(WordVectorSerializer.java:892)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2241)
	at kr.pe.samuel281.dl.demo.TestW2v.main(TestW2v.java:24)
Exception in thread "main" java.lang.RuntimeException: Unable to guess input file format. Please use corresponding loader directly
---------------- message end ---------------------

Here are the code snippet and the env information:
https://gist.github.com/samuel281/fbb7dc90f5e95e3dbb22e8446ac7cd3b

dl4j version : 0.7.0
java version "1.8.0_101" HotSpot 64-bit Server
Saved word2vec : https://drive.google.com/file/d/0Bw6sMBsPeusXaXdtbWhfTTRfeWs/view?usp=sharing

**Comment by samuel281** [comment]
I've found that each vocab ends with Carriage Return in the word vectors file.
WordVectorSerializer encode each vocab with b64 encode and remove Line feed but it doesn't handle carriage return.
https://github.com/deeplearning4j/deeplearning4j/blob/deeplearning4j-0.7.1/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/loader/WordVectorSerializer.java#L2587

I'm not sure is this the root cause but Base64 uses CR + LF as its CHUNK_SEPARATOR
https://github.com/apache/commons-codec/blob/1.10/src/main/java/org/apache/commons/codec/binary/Base64.java#L74

https://github.com/apache/commons-codec/blob/1.10/src/main/java/org/apache/commons/codec/binary/Base64.java#L660

If this is case then it can be fixed easily by removing the CR, too.

**Comment by agibsonccc** [comment]
Thanks for diagnosing this!

**Comment by raver119** [comment]
Interesting why test doesn't capture that neither on windows or linux... But clearly that's my mistake. Fix incoming.

**Comment by raver119** [comment]
@samuel281 what OS you have there?

**Comment by samuel281** [comment]
@raver119 
Tested on Mac OS X El Capitan.

Interestingly, This doesn't happen when I run the code in the IDE. (IntelliJ + junit runner)
It only happens when I submit the job with spark-submit whether locally or not.
I don't know the reason why but this could be the reason that the test doesn't capture it.

Anyway, I've found this could be fixed by adding CR in the string argument, too.
https://github.com/samuel281/deeplearning4j/blob/master/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/loader/WordVectorSerializer.java#L2587

Built 0.7.2-SNAPSHOT and tested on my local and spark cluster.

**Comment by raver119** [comment]
0.7.2 was released few hours ago. Could you please check, if applied fix helps there?

P.s. i have macOS sierra as well, but tests pass here as well.

**Comment by samuel281** [comment]
@raver119 
This seems to be fixed! Thanks for your quick update!

**Comment by raver119** [comment]
Thanks for highlighting this issue.

**Comment by tgalery** [comment]
Hi @raver119 we have trained a model using gensim and serialized that out in C binnary format. When we load that up using DL4J we get the error mentioned here. Anything we might be doing wrong ?

We are loading the file in scala using the line `val model = WordVectorSerializer.readWord2VecModel(f)`, where `f` is a string that represents the path to the file (we also tried using a Java file interface) but the error is the same and we are using DL4J version `0.8.0`. The stacktrace is:

```
val model = WordVectorSerializer.readWord2VecModel(f)
java.lang.RuntimeException: Unable to guess input file format. Please use corresponding loader directly
  at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2480)
  at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2268)
```

**Comment by MarianaLucut** [comment]
Hi @tgalery . I have the same issue: 'Unable to guess input file format. Please use corresponding loader directly'. Have you found a solution for this?

**Comment by raver119** [comment]
Yes. Use corresponding loader directly. There's bunch of methods available in WordVectorSerializer, that support different formats. Despite they are tagged as deprecated, they still work and won't go anywhere soon.
