### ISSUE TITLE
Word2vec: Implement pluggable updater

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#254]
Right now word2vec is slower on gpus due to operations being broken up in to tokens rather than all at once. It would be good to have a pluggable updater that used matrix multiplies rather than segmented dot products for gradient caclulations.

**Comment by agibsonccc** [comment]
Note to self: Curious if this could extend to other kinds of neural networks.

**Comment by agibsonccc** [comment]
This could be helped by https://github.com/deeplearning4j/nd4j/issues/115

**Comment by ncleaver** [comment]
#115 closed
