### ISSUE TITLE
Confused by too many sources/examples

### ISSUE THREAD

**Issue by oak-tree** [deeplearning4j/deeplearning4j#2540]
Hey,
I'm new user of `dl4j`.  I'm looking for trained dl4j on `ImagNet` using 1 of the top Imagenet Challange. Then I want to do extra training on my own database.  
I looked for pretrained models but It seems that there is none for `dl4j` Moreover, it seems there are too many resources and this confused me a bit... for example:

https://deeplearning4j.org/model-zoo
https://github.com/deeplearning4j/dl4j-examples/
https://github.com/deeplearning4j/dl4j-model-z/
https://github.com/deeplearning4j/ImageNet-Example/

I'm looking for a good place to start with the full imagenet db ( I read the quickstart and etc.. in the main website)
Thanks!

**Comment by tomthetrainer** [comment]
oak-tree, 

We are in the process of expanding both our pre-trained models and the ability to import keras models, we intend to support the more popular models. What pre-trained model are you looking for. 

None of the links you mention provides a pre-trained model. Some of them provide the configuration if you had the time or resources to train on your own. We are currently aggressively working on developing our collection of pre-trained models. 

To summarize the resources you mention. 
https://deeplearning4j.org/model-zoo
As we add trained models this is where we would put them, currently it just holds the code to design the neural net, not the trained model. 

https://github.com/deeplearning4j/dl4j-examples/

These are our examples, I encourage you to explore them. 

https://github.com/deeplearning4j/dl4j-model-z/

That is the github page we use for building the modelzoo

https://github.com/deeplearning4j/ImageNet-Example/
That looks like a work in progress front end to build each of the networks, some of the same ones as in the model zoo.
