### ISSUE TITLE
Pre-release testing issues

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2542]
ND4J native:
- [ ] TADTests.testEquality1:65 ```expected:<true> but was:<false>```
- [ ] IndexingTestsC.testPutRowIndexing:44 » IllegalState Mis matched lengths: [1] !...	https://github.com/deeplearning4j/nd4j/issues/1498

ND4J CUDA
- [ ] Same 2 as above
- [x] StackAggregatorTests.testTrailingFrames2:92 ```expected:<2> but was:<1>```

///////////////////////
DL4J core (native)
- [x] DataSetIteratorTest.testCifarModel - due to this: https://github.com/deeplearning4j/DataVec/issues/112 [fixed here: https://github.com/deeplearning4j/DataVec/pull/145 ]
- [x] ModelSerializerTest.testWriteMInModelInputStream - 
- [x] org.deeplearning4j.nn.layers.DropoutLayerTest (3 failures) [fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2545 ]

DL4J parallel-wrapper (native)
- [x] TestParallelEarlyStopping: 3 failures

deeplearning4j-scaleout-parallelwrapper-parameter-server (native)
- [x] ParameterServerParallelWrapperTest (java.lang.ClassNotFoundException: akka.cluster.ClusterActorRefProvider) [fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2545 ]

//////////////////////

DL4J + cuda:
- One minor precision issue fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2547
- Seeing org.deeplearning4j.spark.models.embeddings.word2vec.Word2VecTest stall on CUDA (not concerned about this though given upcoming rewrite)

////////////////////////

Examples: Native - run all tests (same as release testing) - no issues

Examples: CUDA - all good except for:
-  [x]  Multi-GPU - getting "ND4J is missing dependenices" - probably my environment?

Examples: CUDNN (TODO)

/////////////////////////
Note: after running the above I merged https://github.com/deeplearning4j/nd4j/pull/1537
(Have only run ND4J unit tests since)

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/1533 fixed the interval stuff.

**Comment by raver119** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/2544 <-- fixes ModelSerializer/Normalizer saving test on Windows

**Comment by raver119** [comment]
https://github.com/deeplearning4j/nd4j/pull/1536 <-- fixes StackAggregator test, just "bad test" issue.

**Comment by raver119** [comment]
multi-gpu issue is fixed, CudaEnvironment was used before actual Nd4j instantiation, which became impossible with recent backend loader changes
