### ISSUE TITLE
deeplearning4j as backend for keras

### ISSUE THREAD

**Issue by pkoperek** [deeplearning4j/deeplearning4j#2556]
I want to be able to learn the keras model by using deeplearning4j at the backend. From keras user point of view it shouldn't require a lot of changes in code (although couple/several additional lines are ok). The idea for the first iteration is to re-use the keras model-import implemeted by @turambar. It is going to 

Scope:
* Keras (Python) side: small lib which will provide a wrapper for the model, hijack the `.fit()` method and perform the following:
  * dump the dataset for the learning into HDF5 file 
  * dump the model 
  * start the dl4j server
  * start learning by calling the server with learning parameters
  * tear down the server when learning session ends (??? not sure about this one)
* DL4J (Java) side: 
  * Server (single function: reads the model, dataset, performs the learning according to the spec)

Communication will be implemented with the use of py4j. 
 
Issues omitted:
* caching on the server side
* communication protocol should be probably turned into something more robust (thrift? protobufs?)

**Comment by wmeddie** [comment]
Very interesting idea.  I wonder how well numpy and keras run inside Jython.

**Comment by AlexDBlack** [comment]
Some of this discussion might also be relevant to the data set export step: https://github.com/deeplearning4j/nd4j/issues/1521

**Comment by pkoperek** [comment]
@wmeddie I've checked that path: unfortunately because C-extensions are not supported by Jython it is not possible currently to simply run keras this way (numpy relies heavily on C-extensions). I'm working on a "hacky" solution with a client-server communication (described roughly in the issue description).

**Comment by hiiroo** [comment]
But during that client-server connection, isn't data going to be passed through python to java? This will create a bottleneck right? (I'm assuming an online-training system where data does not come as batches...)

**Comment by agibsonccc** [comment]
@hiiroo no data is passed back and forth. It's all RPCed from python, java takes over after that. We're aware of the limitations of pyspark and wanted to bypass that. Spark's way of doing it is a no go for deep learning.
