### ISSUE TITLE
ParallelWrapper OOMs never logged

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#2557]
It's possible for each training thread to experience an OOM and silently fail without logging anything. This code here (and exception handling in general) needs to be looked at:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-scaleout-parallelwrapper/src/main/java/org/deeplearning4j/parallelism/ParallelWrapper.java#L54

@raver119

**Comment by raver119** [comment]
Issue fixed, merge incoming. TL/DR not a OOM
