### ISSUE TITLE
Generating TFIDF

### ISSUE THREAD

**Issue by jageshmaharjan** [deeplearning4j/deeplearning4j#2561]
I am trying to generate a TFIDF, am i doing it correctly
```
SentenceIterator iter = new LineSentenceIterator(new File("/home/jugs/Desktop/Dataset/ReviewJSON.txt"));
TokenizerFactory t = new DefaultTokenizerFactory();
t.setTokenPreProcessor(new CommonPreprocessor());
TfidfVectorizer tfidfVectorizer = new TfidfVectorizer.Builder()
            .setMinWordFrequency(5).setStopWords(StopWords.getStopWords()).setTokenizerFactory(t).setIterator(iter).build();

        tfidfVectorizer.fit();
```
Because, i couldn't find the tfidf scores, while accessing the TFIDF class object, "tfidfVectorizer"
`tfidfVectorizer.vocab`

**Comment by raver119** [comment]
What exactly you can't find? https://github.com/deeplearning4j/deeplearning4j/blob/c5c33a65cb011738a4bd219d5d8beb0d5ecd24d9/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/bagofwords/vectorizer/TfidfVectorizer.java#L96-L96 

This method returns you INDArray based on previously fit corpus

**Comment by jageshmaharjan** [comment]
Oh i see, i got the answer after seeing the "TfidfVectorizer" class implementation.
Thank you, :)
