### ISSUE TITLE
FileStatsStorage: MapDB file concurrent access issues

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#2565]
When using FileStatsStorage in combination with ParallelWrapper and DL4J UI in the same JVM, there appears to be a lot of concurrent file access and eventually a deadlock. Worth examining, perhaps throwing an exception to tell the user to use remote router.

@AlexDBlack

**Comment by AlexDBlack** [comment]
The suspect here according to @crockpotveggies is the use of MapDB in a highly concurrent environment.
Note that standard Spark training insertions and 'run UI in a separate JVM' for reads should be OK.

I have not encountered this in any of my testing to date, but haven't tested parallel wrapper + FileStatsStorage extensively.

J7FileStatsStorage (based on SQLite) is a possible workaround.

**Comment by crockpotveggies** [comment]
I'll expect to create a reproducible repo I can share in the next week and
will DM to @AlexDBlack

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/3690
