### ISSUE TITLE
Add a neural net model inference batcher class that makes it easy to do inference from multiple threads.

### ISSUE THREAD

**Issue by wmeddie** [deeplearning4j/deeplearning4j#2569]
Deploying a trained model as a REST service with a request/response style interface means having to synchronize access to the model from multiple threads or cloning the entire model for every request.  Ideally there should be a class that wraps a ComputationGraph or MultiLayerNetwork batches all requests made within a certain time window from multiple threads before executing them.

The wrapper should work in environments that require managed thread pools like JavaEE containers.

**Comment by raver119** [comment]
Thanks

**Comment by EdeMeijer** [comment]
Sounds good, but I'd advise to also support a batch style request in your REST endpoint. Imagine a single client needing to infer a bunch of inputs from one script/thread, it would still be forced to do a lot of single requests in sequence. If this would be the only client, it would constantly be waiting for the time window to expire and it's one request to be fulfilled. Still not very efficient in that use case.

**Comment by agibsonccc** [comment]
So are we talking something which will process ndarrays? Or will this need to take in raw data?

**Comment by raver119** [comment]
Implemented long ago, known as ParallelInference
