### ISSUE TITLE
UI server overview tab stuck at loading while model/system tabs are ok

### ISSUE THREAD

**Issue by ZhongBaby** [deeplearning4j/deeplearning4j#2572]
I run the model training, the overview tab of http://localhost:9000/train/overview display empty charts, and Model and Training Information stuck at loading...
But I switch to model/system tabs they are displaying things like updates per iteration, memory use per iteration.
![overview](https://cloud.githubusercontent.com/assets/8222739/21465637/52378c6a-c9e6-11e6-9ce2-6a103031ae13.PNG)
![model](https://cloud.githubusercontent.com/assets/8222739/21465639/6202f08a-c9e6-11e6-8267-b734d100c5ac.PNG)

Here's my [gist](https://gist.github.com/ZhongBaby/9e32eae5c67b0a0ab4b3af2c5d8d7902)

Update1:
I change updater from AdaDelta to Nesterov and the overview tab is ok again.
It seems like when the optimization encounters difficulty, the overview tab will stop drawing.
Yes it's a bug.

**Comment by AlexDBlack** [comment]
We've seen some issues with NaNs causing problems before (front end JSON parsing chokes on 'NaN' as an invalid number). This was at least partly solved in 0.7.2 (for the model page ratios), but needs to be confirmed for the overview page data.

**Comment by ZhongBaby** [comment]
thanks.

**Comment by AlexDBlack** [comment]
I'll re-open this issue until it's tested and confirmed as solved - mainly I'd like to double check NaNs in the score vs. iteration chart.

**Comment by ZhongBaby** [comment]
Alright. I want ask can this library add more recent techniques e.g. WeightInit is lacking he_normal whereas keras has it.
Because I encounter difficulty in training a same architecture which composed of 13 layers that achieve 86% accuracy in kaggle's <start with julia> google street character recognition.

**Comment by agibsonccc** [comment]
@ZhongBaby That has nothing to do with this issue. Could you please file a separate issue for feature requests? I'm deleting your comment. It's just not relevant.

**Comment by AlexDBlack** [comment]
NaNs causing the overview page to not load (while model page still loads) was confirmed and fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2613
The above PR will be merged shortly.
