### ISSUE TITLE
Missing javacv installation dependency explanation at image pipeline document

### ISSUE THREAD

**Issue by ZhongBaby** [deeplearning4j/deeplearning4j#2574]
In [Image transform pipeline](https://deeplearning4j.org/simple-image-load-transform) document, It seems to lack the explanation of the installation of [javacv](https://github.com/bytedeco/javacv) library if I want to use FilterImageTransform, Otherwise I will encounter NoClassDefFoundException.
Thanks!

**Comment by saudet** [comment]
It should work without doing anything special. Could you provide more details about the error that you are getting?

**Comment by ZhongBaby** [comment]
I can use ColorConversionTransform, So I suppose JavaCV dependencies are auto resolved.
Here's my [gist](https://gist.github.com/ZhongBaby/e29755031b3dc21489ed24f2c6f5cb2b).
What else details do you need I can upload later.

**Comment by saudet** [comment]
FilterImageTransform uses FFmpeg actually, but it's not included by default because it's under LGPL. So it's a documentation issue?

**Comment by ZhongBaby** [comment]
So what I have to do in order to use Filter Image Transform?
Download FFmpeg for windows from [here](https://ffmpeg.org/download.html#build-windows)?

**Comment by saudet** [comment]
No, just put all of JavaCV in your class path:
https://github.com/bytedeco/javacv#downloads

**Comment by ZhongBaby** [comment]
I add this to my pom.xml:
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacv-platform</artifactId>
    <version>1.3</version>
  </dependency>

But I'm still getting NoClassDefException.
Isn't that all of JavaCV?

**Comment by saudet** [comment]
Ah, yes, this will work only in the next release. Please wait a bit...

**Comment by ZhongBaby** [comment]
So I should close this issue now?

**Comment by tomthetrainer** [comment]
Added additional docs to that page,

simple-image-load-transform

**Comment by ZhongBaby** [comment]
(1)In the [docs](https://deeplearning4j.org/simple-image-load-transform#javacv--opencv-and-ffmpeg-filters), it says in versions 7.2 which is actually 0.7.2?
(2)the dependency xml is lacking indents and newlines.
