### ISSUE TITLE
Warp Image transform may be filled the black background with edge color

### ISSUE THREAD

**Issue by ZhongBaby** [deeplearning4j/deeplearning4j#2575]
For example if I want to train a neural net to classify character in image.
I think after the warp image transformation, the black background maybe filled with edge color so that it is closer to unseen dataset distribution.
I think the second image is better.
![1](https://cloud.githubusercontent.com/assets/8222739/21469648/d747a0ea-ca98-11e6-8995-8458543769e1.PNG)
![1 - copy](https://cloud.githubusercontent.com/assets/8222739/21469654/4db661e4-ca99-11e6-90d4-b7059c34e57f.PNG)

**Comment by agibsonccc** [comment]
Please reword this issue. If it's a feature request please make it more explicit. These kinds of issues should be going on: https://github.com/deeplearning4j/DataVec/issues

**Comment by ZhongBaby** [comment]
Sorry. I will move to DataVec issues.
