### ISSUE TITLE
Not possible to override only a single arbitrary layer

### ISSUE THREAD

**Issue by tlewowski** [deeplearning4j/deeplearning4j#258]
When running IrisExample out-of-the-box (current master), the following warning message appears in the log:
`o.d.n.m.MultiLayerNetwork - Output layer not instance of output layer returning.`

It might be that it is not possible to override arbitrary layer - although `ClassifierOverride` takes layer number as an argument, it's user, `MultiLayerConfiguration` has the following piece of code:

```
        public MultiLayerConfiguration.Builder override(ConfOverride override) {
            this.confOverrides.put(Integer.valueOf(this.confOverrides.size()), override);
            return this;
        }
```

which means that overrides are put one after another in order of addition, not relying on any indexing

later there is usage in `NeuralNetConfiguration`:

<pre>              
        public MultiLayerConfiguration build() {
            if(this.layerwise.size() != this.hiddenLayerSizes.length + 1) {
                throw new IllegalStateException("Number of hidden layers mut be equal to hidden layer sizes + 1");
            } else {
                ArrayList list = new ArrayList();

                for(int i = 0; i < this.layerwise.size(); ++i) {
<b>                    if(this.confOverrides.get(Integer.valueOf(i)) != null) {
                        ((ConfOverride)this.confOverrides.get(Integer.valueOf(i))).overrideLayer(i, (NeuralNetConfiguration.Builder)this.layerwise.get(i));</b>
                    }

                    list.add(((NeuralNetConfiguration.Builder)this.layerwise.get(i)).build());
                }

                return (new org.deeplearning4j.nn.conf.MultiLayerConfiguration.Builder()).backward(this.backward).inputPreProcessors(this.inputPreProcessor).useDropConnect(this.useDropConnect).pretrain(this.pretrain).preProcessors(this.preProcessors).hiddenLayerSizes(this.hiddenLayerSizes).confs(list).build();
            }
        }
</pre>

fragment in bold seems to be an assumption that configuration overrides are being stored with affected layers as indices, which is not the case according to implementation of `MultiLayerConfiguration.Builder`

I'm not sure if it's a bug in implementation or examples, but it doesn't feel right behavior, so I'm posting it here.

**Comment by EronWright** [comment]
Sorry for the inconvenience.    The builder's override method has an overload (see [here](https://github.com/deeplearning4j/deeplearning4j/blob/deeplearning4j-parent-0.0.3.3.3.alpha1/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/conf/MultiLayerConfiguration.java#L403)) that accepts the layer index.  Please use that method, thanks.
