### ISSUE TITLE
PerformanceListener doesn't work with MultiDataSet

### ISSUE THREAD

**Issue by Paranaix** [deeplearning4j/deeplearning4j#2594]
Running `fit()` with a MultiDataSetIterator on a graph with `PerformanceListener` attached causes an exception:

> Exception in thread "main" java.lang.UnsupportedOperationException: Cannot return single input: ComputationGraph  has multiple inputs
> 	at org.deeplearning4j.nn.graph.ComputationGraph.input(ComputationGraph.java:1657)
> 	at org.deeplearning4j.optimize.listeners.PerformanceListener.iterationDone(PerformanceListener.java:66)
> 	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:65)
> 	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51)
> 	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:744)

**Comment by tomthetrainer** [comment]
What version?

**Comment by raver119** [comment]
Issue was fixed: https://github.com/deeplearning4j/deeplearning4j/pull/2599

Thanks for highlighting this issue.
