### ISSUE TITLE
questions about AdditionRNN

### ISSUE THREAD

**Issue by yuimo123** [deeplearning4j/deeplearning4j#2600]
i have read the documents about rnn(lstm) and computationgraph, and i can understand the examples in dl4j-examples but AdditionRNN.
as i can see, AdditionRNN is a seq2seq model, it converts a sequence to a fixed size vectoer C, and then input C to a decoder to generate a result.
but in this example, there a two inputs, and the second one directly connects to the decoder.
i am confused by this input(which is red in the picture), and do not know how to contruct the input in other examples
![default](https://cloud.githubusercontent.com/assets/23448230/21540175/756b50b2-cde8-11e6-91d9-e293ac264247.png)

maybe, you can give more comments in AdditionRNN,  and more examples about seq2seq

thanks a lot.

**Comment by eraly** [comment]
@yuimo123 
Track https://github.com/deeplearning4j/deeplearning4j/issues/2635 for enhancements here. Thanks for bringing this up.

**Comment by eraly** [comment]
@yuimo123 
I was incorrect about this. I will update the example with comments and close this issue out after they have been reviewed. Thanks for the issue.

**Comment by yuimo123** [comment]
ok. thanks a lot.

**Comment by eraly** [comment]
@yuimo123 I wrote some helper methods to print the step through the decoder during testing. This should make things a bit clear.
Eventually we will add a wrapper of some kind as mentioned in the issue linked to in the comment above. Thanks.

**Comment by yuimo123** [comment]
hi, eraly. thanks for the explanation and the code. it's now very clear for me to unstand this example and RNN. i have read the code, and maybe found a mistake below.
for this line:
 maxIndex += i;
maybe it should be
 maxIndex = start + i;

public String[] prepToString(int sum, boolean goFirst)
        int maxIndex = start;
        //add in digits
        for (int i = 0; i < sumString.length(); i++) {
            decoded[start + i] = Character.toString(sumString.charAt(i));
            maxIndex += i;
        }
        maxIndex++;

thanks for your explanation again.
