### ISSUE TITLE
addition of RPN for CNN in examples

### ISSUE THREAD

**Issue by anandkoirala** [deeplearning4j/deeplearning4j#2605]
When we require to detect multiple instances of object in an image, use of RPN (Region Proposal Network) is common. I feel this missing in DL4j. Hoping someone will help to contribute on this part...
Thanks

**Comment by AlexDBlack** [comment]
Closing this - we have a YOLO layer, which is IMO superior to R-CNN.

https://github.com/deeplearning4j/deeplearning4j/blob/3c260c3a607b91d1cbbde495b76c7d1827ba0851/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/layers/objdetect/Yolo2OutputLayer.java

It's available on snapshots, and there's a house number example here: https://github.com/deeplearning4j/dl4j-examples/pull/589/files
