### ISSUE TITLE
The Prerequisites of the examples should tell the use to use Oracle JDK instead of openJDK

### ISSUE THREAD

**Issue by du48s03** [deeplearning4j/deeplearning4j#2608]
The example ImageDrawer requires javafx, which is included in the path by Oracle JDK but not OpenJDK. In order to compile the examples, the user has to comment out that example or install Oracle JDK instead. This should be included in the instructions.

**Comment by RobAltena** [comment]
Added a comment to the example. FYI: Someone reported no issues using OpenJDK and OpenFXjfx.
