### ISSUE TITLE
GPU issues

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#261]
With latest dl4j & nd4j:

Trying to train simple network, and found that using nd4j-jcublas7 leads to dead cycle without any exceptions. Changing jcublas for jblas fixes the problem, and network trains.

As far as i see, single core on pc gets busy, gpu bus controller gets loaded, gpu load is around 70%, memory is jumping between 192 and 236 MB. But nothing happens, even if you wait long enough.

Btw, there's no up-to-date version of examples with multithreaded setup for dl4j.

**Comment by agibsonccc** [comment]
When the gpudeps branch gets merged I'm going to push another release that will fix a lot of the load issues. I'm testing right now on multiple cores (with each thread being able to leverage whatever gpus are on the system among other things)

**Comment by raver119** [comment]
omw there then :)
