### ISSUE TITLE
Add support for the Keras Convolution1D/MaxPooling1D/AveragePooling1D layers

### ISSUE THREAD

**Issue by nharada1** [deeplearning4j/deeplearning4j#2620]
Being able to use 1D sequence models from Keras in DL4J would be awesome. Since I'm fairly certain these operations are implemented under the hood as special cases of 2D conv I wouldn't think this would be a huge undertaking. I might even take a crack at this myself once I acquaint myself with the DL4J codebase.

**Comment by turambar** [comment]
@nharada1 Right on. This is on our radar. I think your intuition is correct (it's a special case of DL4J's 2D convolution), so should be doable. We would LOVE for you to take a crack and would be thrilled to support you on it.

**Comment by turambar** [comment]
@nharada1 1D convolutional and pooling layers are implemented and undergoing testing. If you're interested, here's the PR: https://github.com/deeplearning4j/deeplearning4j/pull/2976.

**Comment by eraly** [comment]
In the release now
