### ISSUE TITLE
Doc: HALF Datatype description missing cons

### ISSUE THREAD

**Issue by fahman** [deeplearning4j/deeplearning4j#2625]
Here: https://deeplearning4j.org/gpu#half-datatype the wording shows only the pros of using the HALF datatype. As discussed in gitter, a setence or two on cons could be helpful.

e.g. Score being NaN during training because of halfing of gradient down to, what, 0? Causing division with zero?

**Comment by raver119** [comment]
Well, "if .. can afford" was meant to be such a warning, because list of cons is kinda small and obvious: precision. But sure, i'll add few lines about that.

**Comment by fahman** [comment]
Here some text from gitter written by some dude and raver119
> I was looking into speeding up DL4J by using "DataTypeUtil.setDTypeForContext(DataBuffer.Type.HALF);" I tried running the DL4J cuda example with and without that line of code. When I use that line, the code runs about 3 times slower than when I don't use that line. I thought setting the DataType should have made the code run faster. Any idea why HALF made the code significantly slower?

raver119 @ raver119
yes, few of those
first suspect is: you’re on old device
second suspect: task is small, and fp16 -> float -> fp16 conversion isnt paying back
third suspect: something bad happens. after you’ll add some details, we’ll both know what exactly :grinning:
but i’d vote for second suspect :grinning:
in reality fp16 is made for high-end device: tesla p100
for all other devices it’s ram saver + bandwidth saver on ops with large operands
also, we’re using half only right now
half2 support will be added soon™

**Comment by raver119** [comment]
Fixed.
