### ISSUE TITLE
Doc: Dead link in gradient normalization description

### ISSUE THREAD

**Issue by fahman** [deeplearning4j/deeplearning4j#2626]
Here: https://deeplearning4j.org/troubleshootingneuralnets#gradient-normalization

at the very end of paragraph there's link to an example (https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/conf/GradientNormalization.java) which is not there anymore.

The working link is this: https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/GradientNormalization.java

although maybe it would be helpful to point reader additionally to this: https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/test/java/org/deeplearning4j/nn/updater/TestGradientNormalization.java

**Comment by tomthetrainer** [comment]
Thanks for the bug report, fixed.
