### ISSUE TITLE
Add inference of new document in ParagraphVectors

### ISSUE THREAD

**Issue by pommedeterresautee** [deeplearning4j/deeplearning4j#263]
I have seen this conversation : https://groups.google.com/forum/m/#!topic/deeplearning4j/AfnBu0tPCLU

I would be also interested in a new feature for ParagraphVectors/doc2vec: the capacity to get a vector for a document never seen before and inferred after a model has been trained on a dataset.

The idea is to get the vector related to a query for information retrieval of documents already learned.
Therefore I don't want to start a new learning to include the learning.

Such approach is cited in the paper of Qoc and almost implemented in Gensim (all links in this conversation https://groups.google.com/forum/#!topic/gensim/EFy1f0QwkKI and the fork with the implementation is there https://github.com/gojomo/gensim).

Would it be possible to get the same feature in this more "production ready" implementation of ParagraphVectors/doc2vec?

Kind regards,
Michael

**Comment by ErikTromp** [comment]
Just to add to that, this might be interesting too:
http://arxiv.org/pdf/1505.01504v1.pdf

**Comment by pommedeterresautee** [comment]
Some interesting comment about this paper:
http://www.reddit.com/r/thisisthewayitwillbe/comments/35ny1b/a_fixedsize_encoding_method_for_variablelength/

Is there an existing implementation somewhere?

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/454
