### ISSUE TITLE
Library sources sometimes do not match the bytecode

### ISSUE THREAD

**Issue by alex-42** [deeplearning4j/deeplearning4j#2632]
I am using the latest deeplearing4J libraries (0.7.2) and in several cases, the source jars do not match the compiled jars. 

E.g. in org.deeplearning4j.datasets.iterator.BaseDatasetIterator, the sources lack the getPreProcessor() method.

The project is built using mavencentral as a jar provider.

**Comment by agibsonccc** [comment]
That's because of lombok.
