### ISSUE TITLE
Add convenience methods/classes for Seq2Seq models

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2635]
Sequence to sequence models can be build using ComputationGraph.
However, they would be easier to construct if we had convenience methods for this. For example, we could do something along the lines of this:

```java
ComputationGraphConfiguration conf = new NeuralNetConfiguration.Builder()
    .seq2Seq()
    .encoder()
    .addLayer("encoderLayer0",...)
    .encoderOutput("encoderLayer0")
    .decoder()
    .addLayer("decoderLayer0",...)
    .decoderOutput("decoderLayer0",...)
    .build()
```
This (or something like it) would be a bit clearer, and would save the user from manually messing with (or having to understand) things like LastTimeStepVertex or DuplicateToTimeSeriesVertex.

Alternatively (or perhaps additionally) we could subtype ComputationGraph with some extra convenience methods. Most notably: at test time, we want to keep the input/encoder fixed, while time stepping the decoder output. Currently, this is not possible with ComputationGraph/RnnTimeStep - but wouldn't be that hard to implement. (Of course, we *could* add specialized methods to ComputationGraph for this, but I would rather not clutter the ComputationGraph api futher with methods that can only be used for a small number of models in DL4J)

**Comment by JoaoBarreto255** [comment]
Have how to add an attention mechanism?
