### ISSUE TITLE
Make back-end messages more meaningful

### ISSUE THREAD

**Issue by Stevod** [deeplearning4j/deeplearning4j#2640]
When changing between native and ND4j back-ends the "JCublasBackend" back-end message which shows first has no meaning unless the user understands about the underlying libraries (and few will). Can it be changed to something simpler and more meaningful to the GPU/algebraic layman?

**Comment by raver119** [comment]
Closing this one as duplicate: https://github.com/deeplearning4j/nd4j/issues/1573
