### ISSUE TITLE
modern networks?

### ISSUE THREAD

**Issue by hrstoyanov** [deeplearning4j/deeplearning4j#2642]
has anyone in the community looked into, or is in the process of development more advanced dl4j models, such as sum-product networks, residual networks, or generative adversarial networks? I am just asking as i might end upndoing some of those...

**Comment by AlexDBlack** [comment]
ResNet should be pretty easy with with ComputationGraph (elementwise vertex, merge vertex etc), no new functionality need for that
we've recently added VAEs https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/unsupervised/variational/VariationalAutoEncoderExample.java
and may look at variational recurrent autoencoders soon (depending on our needs for clients)

We've recently also added functionality for triplet embedding network (https://arxiv.org/abs/1412.6622)

FYI some architectures are here (or WIP here): https://github.com/deeplearning4j/ImageNet-Example

AFAIK nobody is looking at sum product networks for DL4J.


If you are looking to implement any of these architectures with the intent of open sourcing them (or the required functionality) (and assuming you don't have a support contract with Skymind or anything) we'll typically help out where we can. For example, I helped with design and debugging for @crockpotveggies triplet embedding network implementation.

**Comment by AlexDBlack** [comment]
Another option: Keras model import. If you can find a pretrained model in Keras, you may be able to import it. We're not 100% coverage of Keras functionality/layers yet - but we're prioritizing building out functionality based on what people are actually using in practice.
https://deeplearning4j.org/keras
https://deeplearning4j.org/model-import-keras

**Comment by agibsonccc** [comment]
GANS would be good to work on. We typically only add stuff that's matured to the framework though. We're very clearly not a research framework for prototyping ideas. When we implement a new neural net, we typically survey the landscape and pick the best implementation and also take time to do due diligence on what other researchers have ran in to. "GANS" for instance is actually a lot of different variants. There's a variety of use cases out there and various ways of implementing things. There are a lot of papers out there that improve on an existing implementation. We frankly aren't interested in proactively trying to add every possible neural net.

Instead we are just going to import from the keras folks where they already have a vibrant community working on that stuff. I'm closing this in lieu of alex answering the rest.
