### ISSUE TITLE
UI Stops updating

### ISSUE THREAD

**Issue by Tostino** [deeplearning4j/deeplearning4j#2643]
The UI overview page stops updating for me after a while, and it turns out that the cause is a NaN value being sent over in the stddevUpdate which is calculated in the call to: calculateSummaryStats(model.gradient().gradientForVariable(), BaseStatsListener.StatType.Stdev);

When the UI gets the NaN value, it is unable to parse the json and no-longer updates.

**Comment by AlexDBlack** [comment]
Thanks. This is a known issue that has already been fixed here:
https://github.com/deeplearning4j/deeplearning4j/pull/2613
