### ISSUE TITLE
Add more support for import model from keras

### ISSUE THREAD

**Issue by bingyupiaoyao** [deeplearning4j/deeplearning4j#2646]
When I import model create by keras example "babi_memnn.py", I got "Specifying different initialization for LSTM inner cells not supported."

Could we support more for that? thx

**Comment by tomthetrainer** [comment]
Thanks for noting this, we are actively working on Keras Model import at this time. My advice would be to use the latest version of DeepLearning4j and for Keras I believe the theano backend has better support by us at the moment.
