### ISSUE TITLE
Method learningRateScoreBasedDecayRate does nothing

### ISSUE THREAD

**Issue by lpaatero** [deeplearning4j/deeplearning4j#2653]
NeuralNetConfiguration.Builder method learningRateScoreBasedDecayRate sets parameter lrScoreBasedDecay, but this parameters is not used anywhere.

It looks like method learningRateScoreBasedDecayRate should be either removed or implemented.

**Comment by AlexDBlack** [comment]
Obsolete - method has been removed.
