### ISSUE TITLE
build issue : Failure to find org.deeplearning4j:dl4j-test-resources:jar:0.7.3-SNAPSHOT

### ISSUE THREAD

**Issue by lefromage** [deeplearning4j/deeplearning4j#2667]
[ERROR] Failed to execute goal on project deeplearning4j-parent: Could not resolve dependencies for project org.deeplearning4j:deeplearning4j-parent:pom:0.7.3-SNAPSHOT: Failure to find org.deeplearning4j:dl4j-test-resources:jar:0.7.3-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]

this happened on ubuntu 14.04

[WARNING] The POM for org.deeplearning4j:dl4j-test-resources:jar:0
.7.3-SNAPSHOT is missing, no dependency information available
[INFO] -----------------------------------------------------------
-------------
[INFO] Reactor Summary:
[INFO]
[INFO] DeepLearning4j ..................................... FAILURE [  0.054 s]
[INFO] deeplearning4j-nn .................................. SKIPPED
[INFO] deeplearning4j-modelimport ......................... SKIPPED

I guess a workaround is to:
git clone https://github.com/deeplearning4j/dl4j-test-resources

I am using the publicly available build-dl4j-stack.sh from
wget https://gist.githubusercontent.com/crockpotveggies/9948a365c2d45adcf96642db336e7df1/raw/64329b463b014f466512d7c08028c3988660e23a/build-dl4j-stack.sh

**Comment by lefromage** [comment]
same issue in Centos

**Comment by lefromage** [comment]
a workaround is to do in deeplearning4j directory

 git clone https://github.com/deeplearning4j/dl4j-test-resources
 cd dl4j-test-resources
   mvn clean install -DskipTests -Dmaven.javadoc.skip=true 
cd ..

then continue the build with like
./change-scala-versions.sh 2.10
mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!:deeplearning4j-cuda-8.0' 

and get eventually:
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] DeepLearning4j ..................................... SUCCESS [  2.025 s]
[INFO] deeplearning4j-nn .................................. SUCCESS [  9.481 s]
[INFO] deeplearning4j-modelimport ......................... SUCCESS [  3.523 s]
[INFO] deeplearning4j-ui-parent ........................... SUCCESS [  0.131 s]
[INFO] deeplearning4j-ui-components ....................... SUCCESS [  2.507 s]
[INFO] deeplearning4j-core ................................ SUCCESS [  5.936 s]
[INFO] deeplearning4j-ui-model ............................ SUCCESS [  5.060 s]
[INFO] deeplearning4j-play ................................ SUCCESS [  7.240 s]
[INFO] DeepLearning4j-scaleout-parent ..................... SUCCESS [  0.074 s]
[INFO] org.deeplearning4j.spark ........................... SUCCESS [  5.198 s]
[INFO] dl4j-spark ......................................... SUCCESS [ 10.904 s]
[INFO] Dl4j Streaming ..................................... SUCCESS [  5.379 s]
[INFO] DeepLearning4j-AWS ................................. SUCCESS [  4.970 s]
[INFO] deeplearning4j-nlp-parent .......................... SUCCESS [  0.072 s]
[INFO] deeplearning4j-nlp ................................. SUCCESS [  5.997 s]
[INFO] dl4j-spark-nlp ..................................... SUCCESS [ 10.853 s]
[INFO] dl4j-spark-parameterserver ......................... SUCCESS [ 10.000 s]
[INFO] deeplearning4j-parallel-wrapper .................... SUCCESS [  6.613 s]
[INFO] deeplearning4j-scaleout-parallelwrapper-parameter-server SUCCESS [  8.853 s]
[INFO] deeplearning4j-ui-resources ........................ SUCCESS [  0.401 s]
[INFO] deeplearning4j-ui .................................. SUCCESS [  7.454 s]
[INFO] deeplearning4j-ui-remote-iterationlisteners ........ SUCCESS [  2.511 s]
[INFO] deeplearning4j-graph ............................... SUCCESS [  4.632 s]
[INFO] deeplearning4j-nlp-uima ............................ SUCCESS [ 11.170 s]
[INFO] deeplearning4j-nlp-korean .......................... SUCCESS [  4.488 s]
[INFO] deeplearning4j-nlp-japanese ........................ SUCCESS [  6.923 s]
[INFO] DL4J Keras support ................................. SUCCESS [ 17.433 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:40 min
[INFO] Finished at: 2017-01-11T02:48:33-06:00
[INFO] Final Memory: 246M/4017M
[INFO] ------------------------------------------------------------------------

**Comment by marker68** [comment]
How's about:
```
mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!:deeplearning4j-cuda-8.0' -P release
```
in `deeplearning4j` folder?

**Comment by lefromage** [comment]
that works ! 
maybe that should be in the documentation :D

**Comment by euler16** [comment]
how to do it without cuda installation

**Comment by agibsonccc** [comment]
This is fixed. The builddl4jstack.sh should also help.
