### ISSUE TITLE
Issue using Nd4j create in clojure

### ISSUE THREAD

**Issue by saikatkumardey** [deeplearning4j/deeplearning4j#2669]
I am facing the following error on running 
` (Nd4j/create 3) `

java.lang.NoClassDefFoundError: Could not initialize class org.nd4j.linalg.factory.Nd4j
/home/skd/EIG/experiments/trial/src/trial/core.clj:8 trial.core/eval5879
/home/skd/EIG/experiments/trial/src/trial/core.clj:8 trial.core/eval5879
       Compiler.java:6927 clojure.lang.Compiler.eval
       Compiler.java:6890 clojure.lang.Compiler.eval
            core.clj:3105 clojure.core/eval
            core.clj:3101 clojure.core/eval
              eval.clj:79 lighttable.nrepl.eval/->result
              eval.clj:76 lighttable.nrepl.eval/->result
            core.clj:2515 clojure.core/partial[fn]
            core.clj:2646 clojure.core/map[fn]
          LazySeq.java:40 clojure.lang.LazySeq.sval
          LazySeq.java:49 clojure.lang.LazySeq.seq
              RT.java:521 clojure.lang.RT.seq
             core.clj:137 clojure.core/seq
            core.clj:2700 clojure.core/filter[fn]
          LazySeq.java:40 clojure.lang.LazySeq.sval
          LazySeq.java:49 clojure.lang.LazySeq.seq
              RT.java:521 clojure.lang.RT.seq
             core.clj:137 clojure.core/seq
            core.clj:3024 clojure.core/dorun
            core.clj:3039 clojure.core/doall
            core.clj:3039 clojure.core/doall
             eval.clj:128 lighttable.nrepl.eval/eval-clj
             eval.clj:127 lighttable.nrepl.eval/eval-clj
          RestFn.java:442 clojure.lang.RestFn.invoke
             eval.clj:189 lighttable.nrepl.eval/eval2207[fn]
             AFn.java:152 clojure.lang.AFn.applyToHelper
             AFn.java:144 clojure.lang.AFn.applyTo
             core.clj:646 clojure.core/apply
            core.clj:1881 clojure.core/with-bindings*
            core.clj:1881 clojure.core/with-bindings*
          RestFn.java:425 clojure.lang.RestFn.invoke
             eval.clj:179 lighttable.nrepl.eval/eval2207[fn]
             eval.clj:178 lighttable.nrepl.eval/eval2207[fn]
         MultiFn.java:229 clojure.lang.MultiFn.invoke
              core.clj:86 lighttable.nrepl.core/queued[fn]
            core.clj:2459 clojure.core/comp[fn]
interruptible_eval.clj:159 clojure.tools.nrepl.middleware.interruptible-eval/run-next[fn]
              AFn.java:22 clojure.lang.AFn.run
ThreadPoolExecutor.java:1142 java.util.concurrent.ThreadPoolExecutor.runWorker
ThreadPoolExecutor.java:617 java.util.concurrent.ThreadPoolExecutor$Worker.run
          Thread.java:745 java.lang.Thread.run

Here are my dependencies:

` :dependencies [[org.clojure/clojure "1.8.0"]
               [org.nd4j/nd4j-native-platform "0.7.2"]]`
 

I imported [org.nd4j.linalg.factory Nd4j ] in core.clj and tried to run:

`(Nd4j/create 3)`

and obtained the aforementioned error.

**Comment by raver119** [comment]
Any news on dl4j-examples run?

**Comment by saikatkumardey** [comment]
I used nd4j-native and got the exception https://gist.github.com/saikatkumardey/5b240a6c8dcc182c9fc3a022a7a86156

Then I figured that the problem could be with apache commons-io, hence, I added commons-io-2.5 jar on my classpath and now it works fine :)

Here's the updated project.clj: https://gist.github.com/saikatkumardey/24ad174aab4dcfb61411450c82d080df

**Comment by raver119** [comment]
So it works for you now?

**Comment by saikatkumardey** [comment]
yes

**Comment by raver119** [comment]
It looks like Clojure got very cryptic deps management there :)

I'm closing this issue then. Thanks for letting us know about fix applied.

**Comment by saikatkumardey** [comment]
Thanks to you and Adam for help :)
