### ISSUE TITLE
Weird effects with native and cuda backends both on classpath

### ISSUE THREAD

**Issue by fahman** [deeplearning4j/deeplearning4j#2670]
So in dl4j 0.7.2 there is this gorgeous solution: https://github.com/deeplearning4j/nd4j/pull/1508 This allows to put both backend APIs on classpath and decide which backend to use in runtime based on availability of native/cuda libraries.

I am attempting to reduce size of uber-jar/fat-jar because atm it is over 300MB! While attempting this I have encountered following issue:

`java -Dorg.deeplearning4j.ui.port=8089 -cp deeplearning4j-play_2.11-0.7.2.jar:my-application-using-dl4j.jar:jcommander-1.27.jar my.application.AutoencoderTrainingJob -some_params`

produces this log:

> 2017-01-11 17:58:31,796 INFO  o.r.Reflections - Reflections took 275 ms to scan 1 urls, producing 401 keys and 1742 values
> 2017-01-11 17:58:31,806 INFO  o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
> 2017-01-11 17:58:32,051 INFO  o.r.Reflections - Reflections took 189 ms to scan 1 urls, producing 401 keys and 1742 values
> 2017-01-11 17:58:32,052 INFO  o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
> Exception in thread "main" java.lang.ExceptionInInitializerError
>         at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:41)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>         at java.lang.Class.newInstance(Class.java:442)
>         at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5646)
>         at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5554)
>         at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:189)
> ...
> Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
>         at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:40)
>         at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:16)
>         ... 20 more
> Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path
>         at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
>         at java.lang.Runtime.loadLibrary0(Runtime.java:870)
>         at java.lang.System.loadLibrary(System.java:1122)
>         at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:945)
>         at org.bytedeco.javacpp.Loader.load(Loader.java:750)
>         at org.bytedeco.javacpp.Loader.load(Loader.java:657)
>         at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:10)
>         at java.lang.Class.forName0(Native Method)
>         at java.lang.Class.forName(Class.java:348)
>         at org.bytedeco.javacpp.Loader.load(Loader.java:712)
>         at org.bytedeco.javacpp.Loader.load(Loader.java:657)
>         at org.nd4j.nativeblas.Nd4jCpu$NativeOps.<clinit>(Nd4jCpu.java:54)
>         at java.lang.Class.forName0(Native Method)
>         at java.lang.Class.forName(Class.java:264)
>         at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:23)
>         ... 21 more

removing ONLY jcommander-1.27.jar so that:

`java -Dorg.deeplearning4j.ui.port=8089 -cp deeplearning4j-play_2.11-0.7.2.jar:my-application-using-dl4j.jar my.application.AutoencoderTrainingJob -some_params`

produces this log:

> 2017-01-11 18:19:52,608 INFO  o.r.Reflections - Reflections took 263 ms to scan 1 urls, producing 401 keys and 1742 values
> 2017-01-11 18:19:52,638 INFO  o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
> 2017-01-11 18:19:52,874 INFO  o.r.Reflections - Reflections took 183 ms to scan 1 urls, producing 401 keys and 1742 values
> 2017-01-11 18:19:52,882 INFO  o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
> 2017-01-11 18:19:53,875 INFO  o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 32
> 2017-01-11 18:19:53,973 INFO  o.r.Reflections - Reflections took 80 ms to scan 1 urls, producing 29 keys and 176 values
> 2017-01-11 18:20:10,290 INFO  o.r.Reflections - Reflections took 866 ms to scan 1 urls, producing 389 keys and 1509 values
> 2017-01-11 18:20:11,775 INFO  o.n.n.Nd4jBlas - Number of threads used for BLAS: 0
> 2017-01-11 18:20:15,707 INFO  o.r.Reflections - Reflections took 2643 ms to scan 2 urls, producing 2438 keys and 23684 values
> 2017-01-11 18:20:15,731 DEBUG o.d.n.c.NeuralNetConfiguration - Registering class for JSON serialization: org.deeplearning4j.nn.conf.layers.DropoutLayer as subtype of org.deeplearning4j.nn.conf.layers.Layer
> 2017-01-11 18:20:15,734 DEBUG o.d.n.c.NeuralNetConfiguration - Registering class for JSON serialization: org.deeplearning4j.nn.conf.layers.DropoutLayer as subtype of org.deeplearning4j.nn.conf.layers.Layer
> 2017-01-11 18:20:15,737 WARN  o.d.n.c.ComputationGraphConfiguration - Warning: new network default sets pretrain to false.
> 2017-01-11 18:20:15,737 WARN  o.d.n.c.ComputationGraphConfiguration - Warning: new network default sets pretrain to false.
> 2017-01-11 18:20:15,737 WARN  o.d.n.c.ComputationGraphConfiguration - Warning: new network default sets backprop to true.
> 2017-01-11 18:20:15,737 WARN  o.d.n.c.ComputationGraphConfiguration - Warning: new network default sets backprop to true.
> Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/jcommander/ParameterException
>         at org.deeplearning4j.ui.api.UIServer.getInstance(UIServer.java:25)
>         at my.app.AutoencoderTrainingJob$.delayedEndpoint$my$app$AutoencoderTrainingJob$1(AutoencoderTrainingJob.scala:194)
>         at my.app.AutoencoderTrainingJob$delayedInit$body.apply(AutoencoderTrainingJob.scala:30)
>         at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
>         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
>         at scala.App$$anonfun$main$1.apply(App.scala:76)
>         at scala.App$$anonfun$main$1.apply(App.scala:76)
>         at scala.collection.immutable.List.foreach(List.scala:381)
>         at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
>         at scala.App$class.main(App.scala:76)
>         ...
> Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.ParameterException
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>         ... 12 more

Notice:
- when providing jar for the missing class, CpuBackend is being loaded
- when not providing jar for the missing class, JCublasBackend is being loaded
- my uber jar contains this dependency: "org.nd4j" % "nd4j-cuda-8.0"  % "0.7.2 classifier "linux-x86_64"

**Comment by fahman** [comment]
Further observation is that removing "org.deeplearning4j"  %% "deeplearning4j-ui" % "0.7.2" solves the issue, but then obviously no UI is available.

**Comment by raver119** [comment]
But there's no deeplearning4j-ui module in 0.7.2
Only deeplearning4j-ui_2.10 or deeplearning4j-ui_2.11

**Comment by fahman** [comment]
@raver119 that is correct. I have tested with dee4plearning4j-ui_2.11 (the double %% in sbt adds the necessary scala 2.11 to the assembly name)
