### ISSUE TITLE
Document learning rate schedules

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2671]
Specifically:
(a) what LR schedules are available, and how to use them 
https://github.com/deeplearning4j/deeplearning4j/blob/91a481ae8f5bcb4c9ff3463c1bba2df69d7325d2/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/LearningRatePolicy.java

and,
(b) What the actual mathematical form of these are (and ideally: with example graphs for common configurations)

**Comment by tomthetrainer** [comment]
Would the graphs be something we could screen capture from the UI, or something we would have to write some code for.

**Comment by AlexDBlack** [comment]
We could capture this from the UI, though perhaps it might be better if one of us plots them manually (i.e., based on the mathematical formulas in the implementation) with perhaps a few different settings for each for comparison. That might help users understand them better.
I could look at that perhaps over the weekend, if you want.

**Comment by AlexDBlack** [comment]
LR schedules are covered here: https://deeplearning4j.org/quickref#config-schedules
