### ISSUE TITLE
Docs: Clarify NLP functionality in DL4J

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2681]
https://deeplearning4j.org/nlp

Deeplearning4j is not a NLP library, but does have some NLP components in order to build W2V pipelines and the like.

We should clarify/emphasize on that page that DL4J is not intended to be comparable to Stanford CoreNLP or tools like NLTK.

Some suggestions:
- Rename page to "Deeplearning4j's NLP functionality"
- Emphasize what NLP functionality we have, and why
- Compare to other tools like CoreNLP and NLTK

**Comment by tomthetrainer** [comment]
Alex, Made a most basic patch to this page, changed the title. 

re-open if not satisfactory,
