### ISSUE TITLE
Bias initialization configuration: not used in LSTM

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2684]
LSTM has forget gate bias init which is set/used correctly, but Layer config also defines a 'biasInit' option that isn't currently utilized for the LSTM. It's unusual to configure the biases on anything but the forget gate in an LSTM, but given we have the option already, it should be possible.

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/layers/Layer.java#L71

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/params/GravesLSTMParamInitializer.java

**Comment by raver119** [comment]
Is this issue still relevant?
