### ISSUE TITLE
Multi-class text classification

### ISSUE THREAD

**Issue by bashartalafha** [deeplearning4j/deeplearning4j#2685]
I want to make a text classification on my own dataset, it contains at each line (in train/test) a text assigned to a specific class.
for example:
1, Hello World
2, this is an example
3, test test test
2, hello deep learning
...
Number of classes is 5. How can I make a text classification using LSTM and Word2vec?? I would be grateful if you could provide me with any example for multi-class text classification.
Many thanks,,

**Comment by raver119** [comment]
Basically that's example what you want https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/word2vecsentiment/Word2VecSentimentRNN.java
