### ISSUE TITLE
Add ability to render UI components via upload

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#2698]
Training sessions - Upload FileStats for rendering a training session
TSNE (this is done I think?) - Upload a csv render charts
Model rendering: Upload a model config or model (optional) to render either a model layout or histogram the parameters

There could be others here?

**Comment by AlexDBlack** [comment]
Pretrained models: view list of available models, click to view config, click to download from some source on the internet.
