### ISSUE TITLE
dl4j version 0.7.2 VocabCache<T>.totalNumberOfDocs() returns 0

### ISSUE THREAD

**Issue by jing-zhou** [deeplearning4j/deeplearning4j#2700]
Hello,
I am training a w2v with "pre-addressed" Chinese corpus. 
 the traing code snippet runs as follows 

 ```
File file = new File(filePath);
        
        if(!file.isFile()){
        	logger.error("the file:" + '\"' + filePath + '\"' + "does not exit");
        	return;
        }
	
        SentenceIterator iter = new FileSentenceIterator(file);

        TokenizerFactory t = new DefaultTokenizerFactory();
        t.setTokenPreProcessor(new CommonPreprocessor());
         
    	vectors = new Word2Vec.Builder()
    			.minWordFrequency(5)
    			.iterations(Params.iterations)
    			.epochs(Params.epochs)
    			.layerSize(Params.layerSize)
    			.seed(42)
    			.windowSize(11)
    			.iterate(iter)
    			.tokenizerFactory(t)
    			.stopWords(stopList)
    			.build();
    		vectors.fit();
```
  of which:   "Params.iterations" equals 1, "Params.epochs" equals 1, 	"Params.layerSize"	equals 500;

below is a sample of a part of the "pre-addressed" chinese corpus (~1GB, in the form of a .txt file; this part is about Russian history, Peter the third, from Wiki)

```
[[10155]]
彼 得 三 世 · 费 奥 多 罗 维 奇 （ ，
原名 卡 尔 · 彼 得 · 乌 尔 里 希 ，
，
） ，
1762 年
任
俄罗斯 帝国
皇帝 ，
荷 尔 斯 泰 因 · 哥 道 普 的卡 尔 · 腓 特 烈 和 安 娜 · 彼 得 罗 芙 娜 之 子 ，
彼得大帝
的 外孙 。
彼 得 三 世 本 來 是
德意志 人
，
幾 乎 不 會 說
俄 語
。
彼 得 三 世 因
伊丽莎白 · 彼 得 罗 芙 娜
女皇 无 嗣 ，
他 在 1744 年 被 挑选 成为 俄罗斯 皇位 继承人 。
1762 年 彼 得 三 世 即位 后 ，
是 为 荷 尔 斯 泰 因 - 哥 道 普 -
罗 曼 诺 夫 王朝
的 开始 。
```

after the training finished, I saved the w2v to a file by the code : 

`WordVectorSerializer.writeWord2VecModel(vectors, filePath);`

then I reloaded the saved file with this code: 

`WordVectorSerializer.readWord2VecModel(filePath, true);`

I intend to use "tf-idf" to extract keywords from a text before any further processing. 
I get  "tf" by just counting the occurrence of a word within the text;  I intend to get "idf" by the following formular: 
`
double idf = Math.log10(vocabCache.totalNumberOfDocs()/vocabCache.docAppearedIn(word))`

and here comes the problem: I got  "-infinity" for all the "idf" of the words, which renders any comparing impossible. 

I step-traced into execution and found out that the "totalNumberOfDocs()" always returns a zero; which had caused the problem.

**Comment by jing-zhou** [comment]
with a second thought, maybe this problem should not prevent my calculation of "idf".
"totalNumberOfDocs" is a fixed number, it imposes same influence to all "idf" results under same context; so it reduced to a constant "factor" , and I can put any non-zero number in the place, right?

**Comment by raver119** [comment]
In terms of w2v, number of documents isn't guaranteed to have any viable meaning. I.e. in your case you're feeding model with SentenceIterator - how can we know number of actual documents behind lines of text? 

P.S. For BoW/TF-IDF we have separate vectorizer, which cares about number of docs, but in w2v..

**Comment by agibsonccc** [comment]
I'm imagining we could track the statistics though? What about adding a new method to the sentence iterator? https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/text/sentenceiterator/FileSentenceIterator.java We could do a numDocs() like that?

**Comment by raver119** [comment]
But what sense in that? We already have document iterators, so if one of those is used - we should have reliable statistics.

**Comment by raver119** [comment]
Well, anyway, we do get that information during Vocab construction. It just isn't supposed to be stored in w2v model. I'll check where we could store it within w2v/d2v models. 

P.S. We also have separate vocab serialization method for TF-IDF/BoW, maybe we could save it there.

**Comment by jing-zhou** [comment]
w2v is a semantic tools based on word, the normal way of handling a sentence is to sum up the corresponding word vectors. yet this operation might "blur" the result vector into normal distribution ("white noise") as sentence gets longer. so it is better to pick out the "keywords" rather than discriminant adding.
tf-idf could be a simple yet effective way, and it could also be (comparatively) easily get as a "by-product" during w2v training...
a dedicated TF-IDF/BoW vectorizer is not "cheap" in term of compute capacity...

**Comment by raver119** [comment]
I'm not arguing with you, your requests is viable :) And I've even said - we already do that. Here's the place: https://github.com/deeplearning4j/deeplearning4j/blob/d963f886559243efe89ffff62f189b8578ff6b49/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/word2vec/wordstore/VocabConstructor.java#L199-L199

We just don't save this field anywhere during serialization, and i'll find the place where we could save it.

**Comment by raver119** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2766

Now totalNumberOfDocs is serialized too, together with w2v/d2v models.
