### ISSUE TITLE
ADAM optimizer needs to use epsilon

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#2705]
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/updater/LayerUpdater.java#L248

Currently the ADAM optimizer isn't using epsilon. However, it's a usable hyperparameter with ADAM, and Inception networks might not even train if this hyperparameter can't be set.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/2706

Same issue with RMSProp (also fixed).
