### ISSUE TITLE
Fat Jars + Graceful Degredation

### ISSUE THREAD

**Issue by JosephCatrambone** [deeplearning4j/deeplearning4j#271]
Is it possible to pack ND4j + DL4j into a fat Jar so that it will run with CUDA on GPU capable machines and gracefully downgrade to BLAS (or even plain Java) on machines without runtimes?  I believe JBlas packages fat Jars with lots of native runtimes.  Perhaps DL4j could include the essentials in some Jars or add a writeup on how to build it with leaner/fatter Jar files?

**Comment by EronWright** [comment]
Yes this is possible.  Simply create a fat jar that contains DL4J plus one or more ND4J backends (e.g. CUDA + netlib).   The GPU backend will be used if possible and gracefully downgrade as necessary.
