### ISSUE TITLE
Typo in RNN example and maven build example on homepage found

### ISSUE THREAD

**Issue by c0der1337** [deeplearning4j/deeplearning4j#2719]
https://deeplearning4j.org/usingrnns#testtimemasking

    INDArray linspace = Nd4j.lin**S**pace(1,longestTimeSeries,longestTimeSeries);
the s should be lowercase

        int thisTimeSeriesLastIndex = lastTimeStepIndices.**get**(i);
method: get should be getInt

The maven example from https://deeplearning4j.org/buildtools doesn't work. 
Reason: version is not available online, maybe someone can fix it with 0.7.2?
Advice for improvement: Also add the required backend depency of nd4j that you can run dl4j by adding these two depencies.

<dependency>
    <groupId>org.deeplearning4j</groupId>
    <artifactId>deeplearning4j-core</artifactId>
    <version>0.7.2</version>
</dependency>
 <dependency>
   <groupId>org.nd4j</groupId>
   <artifactId>nd4j-native-platform</artifactId>
   <version>0.7.2</version>
 </dependency>
</dependencies>

**Comment by tomthetrainer** [comment]
Fixed
