### ISSUE TITLE
Word2VecDataSetIterator produces NullPointerException while training with MultiLayerNetwork

### ISSUE THREAD

**Issue by tlhylmz** [deeplearning4j/deeplearning4j#2721]
The exception log is: https://gist.github.com/tlhylmz/8db9b0274a563bc79da61abec0a6ed26

Example usage: DataSetIterator train = new Word2VecDataSetIterator(vec,new LabelAwareListSentenceIterator(new FileInputStream(new File(DATA_PATH_2)), " ", 0, 1), labels);

**Comment by raver119** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2766

Original issue is wrong handling of of sliding window padding.
