### ISSUE TITLE
Code quality: Example - Using @Deprecated with comments and Javadoc links

### ISSUE THREAD

**Issue by archenroot** [deeplearning4j/deeplearning4j#2722]
Hi guys,

this is first of all great approach you have done with deeplearning4j, I like it a lot!

One think I would like to remind, do you use for example SonarQuebe or some quality checking software for automated QA fo source code?

I found few @Deprecated marks, but without really usefull comment about:

1. why it is deprecated
2. what is new api and concerns to be taken while migrating to new api

Sonar and pipeline in Jenkins for example will do this automatically with selected quality level threshold and won't allow to pushing in source written in some unexpected form. This is in general to be used.

**Comment by AlexDBlack** [comment]
I did a pass on deeplearning4j-nn (and spark, etc). That's reasonably good as far as deprecations.

However, it looks like there's a number of places in deeplearning4j-nlp that have deprecated tags without a corresponding ```@deprecated``` javadoc tag - cc @raver119

**Comment by AlexDBlack** [comment]
Duplicate: https://github.com/deeplearning4j/deeplearning4j/issues/2807
