### ISSUE TITLE
Spark Requirements missing on WIndows - Hint in the Quickstart-Guide

### ISSUE THREAD

**Issue by J-F-B-M** [deeplearning4j/deeplearning4j#2724]
After downloading and importing the Example-Project I ran into problems when running any example using Spark. Especially I seem to miss the winutils.exe from Hadoop.

Can you please add a hint to the Quickstart-Guide that if any problems regarding Spark are encountered this is a possible Problem-Source? It was not immediatly obvious to me that Spark is built on/with Hadoop and that I need to install manually as I've not used it before, making this exception come out of the blue.

Something along the lines of:
"If you encounter problems when running Spark-Examples, check if you installed all of [Sparks Requirements]\([http://stackoverflow.com/a/38735202/3892515](http://stackoverflow.com/a/38735202/3892515)\)"

Link is a SO-answer on how to setup Spark in local mode, which reads as it should cover all problems. If that is too much to get it running please mention that as well. The full list of requirements listed seems a bit scary just to try out DL4J and would actually scare me away.

**Comment by tomthetrainer** [comment]
I patched the quickstart with a Q and A about this issue, thanks for reporting.
