### ISSUE TITLE
Find and link example from Peter Lin @woolfel

### ISSUE THREAD

**Issue by tomthetrainer** [deeplearning4j/deeplearning4j#2725]
https://github.com/deeplearning4j/deeplearning4j/blob/gh-pages/eclipse-quickstart.md

**Comment by tomthetrainer** [comment]
See if he has anything else .

**Comment by huitseeker** [comment]
!?? What's the link with Peter Lin ?

**Comment by tomthetrainer** [comment]
They seem to have been added, he built some eclipse docs
