### ISSUE TITLE
Examples: Update SDA Examples

### ISSUE THREAD

**Issue by LeoIV** [deeplearning4j/deeplearning4j#2732]
The example of the Stacked Denoising Autoencoder (https://deeplearning4j.org/stackeddenoisingautoencoder.html) is outdated. The code cannot be executed since (for example) the RMSE_XENT loss function is no longer supported.

An updated example would be nice at this place.

**Comment by letui** [comment]
yes ,i hope it could be update

**Comment by agibsonccc** [comment]
Consider using https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/unsupervised/variational/VariationalAutoEncoderExample.java
