### ISSUE TITLE
Build WebApp for VGG model inference

### ISSUE THREAD

**Issue by tomthetrainer** [deeplearning4j/deeplearning4j#2734]
I was hoping to have a "flashy demo" for class that shows model prediction with VGG16. 

Here is a gist with code that does model prediction given file path. 

https://gist.github.com/tomthetrainer/dd7c1a43995861788a3f9ca2b7accacf

I could make that into a java filechoser gui, but I was hoping to make a web app.

**Comment by chrisvnicholson** [comment]
@AlexDBlack @agibsonccc @crockpotveggies hey guys - i added you as assignees just to make sure you saw this. tom's building an image recognition demo and he's now trying to plug it into a web app. running into a blocker when he tries to save the model. instead it has to load every time, which takes 4 minutes.

**Comment by tomthetrainer** [comment]
Basically, I can get model prediction working as a standalone java class, as shared above. 

When I go to splice that into a web app I struggle. 

I had a play version "working", but it was reloading the neural network each request. At 4 minutes that was not satisfactory. 

Play framework under intellij when imported from SBT was unstable.

**Comment by crockpotveggies** [comment]
Best thing here is to create a pool of workers that are initialized outside of the request thread. Play! is becoming a heavy framework, but you have a couple options if you don't want to stick with it. My off-the-top suggestion is to create an Akka worker in the background and in your Play! controller send messages to it. You can set up the Play! controller to send a message to your actor, and complete the request asynchronously by returning the future created by your message promise.

**Comment by tomthetrainer** [comment]
I got a demo working with spark java

Will close this ticket

**Comment by tomthetrainer** [comment]
I got a demo working with sparkjava, Thanks Justin.

**Comment by crockpotveggies** [comment]
Glad I could help!

**Comment by crockpotveggies** [comment]
Alright, I can easily write some AJAX that interacts with the demo server as long as we modify the CORS headers. Can you add the following domains to allowed origins?

- http://localhost/
- http://crockpotveggies.com/
- https://deeplearning4j.org/
- https://skymind.io/
- https://skymind.ai/

The best way to do this is to add a CORS filter in SparkJava. You can modify the code from this Gist: https://gist.github.com/zikani03/7c82b34fbbc9a6187e9a

What you would then do is match the `Origin` header to the list of domains above. Then respond with one of the allowed domains (you will have to add the `http://` or `https://`), or not add the header if the domain comes from `http://attacker.com` for example.

The other headers will also be necessary:

```
Access-Control-Allow-Headers: *
Access-Control-Allow-Methods: GET,PUT,POST,DELETE,OPTIONS
```

While I'm making a home for the UI code, are we in agreement that a new sub-item of `Demo` in the DL4J left navbar `Getting Started` section makes the most sense?

**Comment by crockpotveggies** [comment]
Ah quick note on the `Access-Control-Allow-Headers` I think that spec changed in early 2016. This StackOverflow describes some of it: http://stackoverflow.com/questions/13146892/cors-access-control-allow-headers-wildcard-being-ignored

**Comment by crockpotveggies** [comment]
@tomthetrainer oh sorry, just re-read your original email and it sounds like you already know *how* to add these headers. Unless you put a wildcard domain, those domains will suffice :)

**Comment by crockpotveggies** [comment]
Okay one more thing that would really demonstrate the power of this demo. Can you return the feed-forward time? So return JSON would look something like this:

```
{  
   "data":[  
      {  
         "label":"espresso",
         "prediction":38.31146
      },
      {  
         "label":"cup",
         "prediction":4.0962706
      },
      {  
         "label":"eggnog",
         "prediction":2.588317
      }
   ],
   "performance":{  
      "feedforward":121
   }
}
```

**Comment by crockpotveggies** [comment]
Slight change on the previous domain, can you just make it `localhost` and minus the port? Will also edit my original comment.

**Comment by crockpotveggies** [comment]
![screen shot 2017-02-20 at 7 41 54 pm](https://cloud.githubusercontent.com/assets/1445295/23150001/c8a1c668-f7a4-11e6-9192-0073750b2af4.png)

**Comment by tomthetrainer** [comment]
Not sure how to get the performance time you requested, 
"performance":{  
      "feedforward":121

**Comment by crockpotveggies** [comment]
@tomthetrainer I think the easiest way to do this is via:

```
long ffTime = System.currentTimeMilis()
net.feedForward(input)
ffTime = ffTime-System.currentTimeMillis()
```

**Comment by raver119** [comment]
AFAIK demo was implemented long ago.
