### ISSUE TITLE
Add Truncated Normal Distribution to Weight Init

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#2736]
Truncated normal distribution redraws weights when a weight initialization falls outside a specified distribution. This has been used by some researchers to achieve better training results on resnets.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard5/tf.truncated_normal_initializer.md

**Comment by AlexDBlack** [comment]
This is now possible:
https://github.com/deeplearning4j/deeplearning4j/blob/a3b729b35c14eacafb02f87488065d8c0da0c8cb/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/distribution/TruncatedNormalDistribution.java
