### ISSUE TITLE
Activations UI fails for large networks

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#2737]
Visiting the UI activations page at localhost:9000/activations fails when a network is significantly large, such as 4 million parameters. The refresh rate of 3 seconds is too fast because the image isn't finished loading. Also, when the ConvolutionalIterationListener is set to a higher number, refreshing the page too frequently can unnecessarily use up too much memory and cause the associated process to die (as observed below).

```
[14983.392531] Out of memory: Kill process 32301 (java) score 989 or sacrifice child
[14983.400449] Killed process 32301 (java) total-vm:111779592kB, anon-rss:48827496kB, file-rss:0kB
```

**Comment by AlexDBlack** [comment]
I haven't seen this issue since (and no user reports of it being a problem).
If memory serves me, we implemented subsampling of points and a couple of other backend optimizations since this, which helped?
