### ISSUE TITLE
Broken link in the doc

### ISSUE THREAD

**Issue by rishikksh20** [deeplearning4j/deeplearning4j#2744]
In Quickstart home page the link of `Architecture` under `Open Source Community`  side menu throws `404 page not found` message  after clicking on it.

**Comment by tomthetrainer** [comment]
Thanks

**Comment by rkfg** [comment]
Duplicate of #2323

**Comment by tomthetrainer** [comment]
Commented out so no more 404, real issue, we need an architecture page
