### ISSUE TITLE
Need for a CTC Layer

### ISSUE THREAD

**Issue by technologistkj** [deeplearning4j/deeplearning4j#2746]
Team, a layer implementing CTC cost function will be a great plus for Speech/Gesture/OCR recognition applications. Request you to please consider adding a CTC layer.

**Comment by doofin** [comment]
+1

**Comment by agibsonccc** [comment]
We won't be doing this. Use samediff/TF import when it comes out.

**Comment by doofin** [comment]
Would you like to provide more information about samediff in dl4j ? I can barely get anything about it

**Comment by agibsonccc** [comment]
@doofin it will be in the next release, stay tuned! Come in the gitter channel if you have any other questions.
