### ISSUE TITLE
Add orthogonal weight initializer

### ISSUE THREAD

**Issue by turambar** [deeplearning4j/deeplearning4j#2748]
A la [Saxe, et al., 2013)[http://arxiv.org/abs/1312.6120]. Common for RNNs these days (use by Keras LSTM by default). Here is the [Keras code](https://github.com/fchollet/keras/blob/master/keras/initializations.py#L88) as a reference.

**Comment by AlexDBlack** [comment]
I still want this one :)

**Comment by turambar** [comment]
Concur.

**Comment by agibsonccc** [comment]
Ahh - thought we had it already?

**Comment by turambar** [comment]
A reminder about this: it's not Keras *per se* -- we need to add the initializer itself to DL4J before we can support importing it from Keras configs. So perhaps not @maxpumperla's purview?

**Comment by maxpumperla** [comment]
man, @turambar I like how you try to keep my backlog small. :)

**Comment by maxpumperla** [comment]
#4062

**Comment by huitseeker** [comment]
@maxpumperla you can add "fixes #2748" in the commit message of your PR which addresses that to auto-close this issue when the commit is merged.

**Comment by maxpumperla** [comment]
@huitseeker I know! :) what I can't do automatically is remembering which tickets relate to the PR (I think we had 4 issues regarding inits)
