### ISSUE TITLE
ModelImport Documentation summary and input

### ISSUE THREAD

**Issue by tomthetrainer** [deeplearning4j/deeplearning4j#2752]
Team, 

Thinking about the modelimport docs, putting some questions here. 

1. I assume it has stabilized to where I can go ahead and make a video to replace the old one, comment if not. 

2. Will it only be Keras? 

3. What about this talk of dl4j and backend for Keras, is that crazy talk or real talk? 

Real rough outline below, to get my thoughts in order. 

# ModelImport

DL4J supports importing of Keras Models. 

# Model Zoo

Will eventually include many of the models available [here](https://github.com/fchollet/deep-learning-models) and [here](http://caffe.berkeleyvision.org/model_zoo.html), such as:

* VGG16
* VGG19
* ResNet50
* Inception v3
* CRNN for music tagging (maybe?)

We intend to support import by having pre-built examples demonstrating each. 

**Is that true** ?

# Video showing VGG16 import

* Link to video (not made yet)

# Importing you own models

Documentation on what is supported and how to do it. 

# Retraining models

Details on how to run additional training on models

# ModelSerializer

They should be encouraged to import once, and then further saving and loading is done here in DL4J

# Transfer Learning

I might need some input on this. It is replacing the last layer with a clean slate and retraining with new dataset? 

# Changing your pom to get model import

# Overview of the modelimport classes

# Important notes

* pre-process your images in the same manner that the network was trained

**Comment by eraly** [comment]
It's stabilized. 
On the other models - I think inception is high on the list. I don't know the priority on the others. @turambar? @chrisvnicholson and @agibsonccc's call?

The transfer learning stuff is starting to take shape. Will make it into the next release. So maybe put that off for later?

**Comment by turambar** [comment]
@tomthetrainer:

Re: (1.), it has stabilized. Moving forward, we will support two APIs:
* static functions in [KerasModelImport](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/KerasModelImport.java): **for most users and standard use cases**, these provide streamlined helper functions to build (a) a DL4J model from an HDF5 model archive, (b) a DL4J model from a Keras config stored as a JSON file and weights stored in an HDF5 weights archive, (c) a DL4J model *configuration* from a Keras config stored as a JSON file. We may add additional functions (for, e.g., InputStream inputs) as needed. These also assume `Functional API` --> `ComputationGraph` and `Sequential` --> `MultiLayerNetwork` mappings.
* Builder-pattern constructors in [KerasModel]() and [KerasSequentialModel]() that are more flexible. For example, they support Keras config stored as a YAML string and allow one to import a Keras `Sequential` model as a `ComputationGraph` (and eventually, vice versa).

Please see [this gist](https://gist.github.com/turambar/be0a96a02fd1ba3f6010bc0d17fc90dc) for examples the official (`Functional API` --> `ComputationGraph`) syntax moving forward.

**Comment by turambar** [comment]
(2.) As far as I know, yes. Hypothetically, Keras imports Caffe (I don't know how broad that support is; need to look into that) so we get that indirectly. Keras is being adopted as *the* (or at least, supported as *an*) official high-level API for TensorFlow. That with its market share, make it the most worth our effort.

**Comment by turambar** [comment]
(3.) TL;DR: real talk.

More detailed response: as I understand things, we're not building a *backend* in the same sense as the Theano or TensorFlow backends. Rather, we're building a pipeline that allows one to specify a model in Keras and then train or deploy it on a DL4J server via Keras model import. @crockpotveggies and @pkoperek can correct me or comment further.

**Comment by turambar** [comment]
@tomthetrainer:

Re: Model Zoo, it's not a *Keras Model Zoo*. Rather, we are going to set up our own Caffe-/Keras-style model zoo of pretrained DL4J models. It just so happens that we may populate our model zoo with models that have been imported from other frameworks.

As to which models, I think we can safely say that we will include at least VGG (done) and Inception (in progress). I dunno which other ones yet.

**Comment by turambar** [comment]
Re: Transfer Learning, yes in general, though we don't know exactly what this will look like. @eraly and I (with feedback from @nyghtowl and @AlexDBlack and community) are working out details.

**Comment by tomthetrainer** [comment]
Question on enforceTrainingConfig(true) 

true = Model can be trained further
OR
true= model can not be trained further

Looks like True is the default in either case. If that is the case then by default the loaded models can be trained further ?

**Comment by tomthetrainer** [comment]
Updated this page, https://deeplearning4j.org/model-import-keras

**Comment by turambar** [comment]
@tomthetrainer The model can be trained in either case. The `enforceTrainingConfig` argument controls how the importer handles unsupported model configurations that impact training only and not inference/prediction. For example, Keras allows custom weight regularizers (other than *L_1* and *L_2*) that DL4J does not support.

If you want to import a pre-trained model ONLY for inference, then you should set `enforceTrainingConfig=false`. Unsupported training-only configurations generate warnings but model import will proceed.

If you want to import a model for training and want to ensure the resulting model matches a trained Keras model as closely as possible, then you should set `enforceTrainingConfig=true`. In that case, unsupported training-only configurations will throw an `UnsupportedKerasConfigurationException` and stop model import.

**Comment by tomthetrainer** [comment]
@eraly @tomthetrainer I built a bunch of stuff to support end-to-end Keras model import unit tests (end-to-end ==> comparing per-layer activations, final model output, overall performance, etc.)
So step one is train a model in Keras and use the save_model_details and save_model_output functions to save model and model output to disk. The latter stores sample inputs and outputs to an HDF5 archive. Here is an example that runs the stock MNIST MLP example from the Keras repos (using the magic of imp.load_source).
I then add the output to dl4j-test-resources under modelimport/keras/…. Here is MLP example.
Finally, here’s a sample end-to-end unit test, for that sample MNIST MLP example.

Links from same..
https://github.com/deeplearning4j/keras/blob/master/dl4j-modelimport/util.py#L33

https://github.com/deeplearning4j/keras/blob/master/dl4j-modelimport/util.py#L59
https://github.com/deeplearning4j/keras/blob/master/dl4j-modelimport/make_mnist_mlp_unit_test.py
https://github.com/deeplearning4j/dl4j-test-resources/tree/master/src/main/resources/modelimport/keras/examples/mnist_mlp
https://github.com/deeplearning4j/deeplearning4j/blob/kerasModelImport/deeplearning4j-modelimport/src/test/java/org/deeplearning4j/nn/modelimport/keras/KerasModelEndToEndTest.java#L41

**Comment by crockpotveggies** [comment]
A heads up that this PR has been opened and will be merged later this week: https://github.com/deeplearning4j/deeplearning4j/pull/3412

This is the new native model zoo. I'm currently converting some pretrained models from Keras so they will be available in DL4J.

@tomthetrainer happy to walk through it with you when it's ready.

**Comment by maxpumperla** [comment]
@tomthetrainer I'm picking up model import now, including documentation. This thread is pretty long by now. Can we maybe collect requirements in a more structured way?

Let me know what you need in terms of docs and I can start thinking about it. Thanks!

**Comment by tomthetrainer** [comment]
@maxpumperla I am mentioning  @bkanui in this comment because she is working on documentation. She is very busy with other stuff but perhaps we can get her input. Agreed this thread is a mess, we may want to close and open a more structured document. 

If we have an opportunity to generate a well organized collection of docs for this I support it and can provide some input. Let's see if @bkanui has some feedback and decide how to procede

**Comment by maxpumperla** [comment]
@tomthetrainer thanks for your message here, and your email. I also have the feeling this thread might not be that helpful anymore and we should consider migrating this discussion somewhere else.

**Comment by bkanui** [comment]
Responding through email, but was this generated? I’d respond there, if I could figure that out. I don’t see where on gitter this came from.

@tomthetrainer, which ‘thread’ are you talking about? I didn’t see this content in the issue:https://github.com/deeplearning4j/deeplearning4j/issues/1494#issuecomment-319312950 <https://github.com/deeplearning4j/deeplearning4j/issues/1494#issuecomment-319312950>

I think it would be useful to have a meeting to chat. Would love to apply all our brains to some doc structure/what’s where plans. What timeframes are good for both of you? @maxpumperla and @tomthetrainer. Maybe this Friday?

Thanks
Bethany

**Comment by turambar** [comment]
Basecamp

**Comment by maxpumperla** [comment]
@tomthetrainer @bkanui I've merged a PR updating model import docs, I'm not sure if it suffices to close this ticket. Please let me know

**Comment by tomthetrainer** [comment]
Yeah let's close this one.
