### ISSUE TITLE
WordVectorSerializer: Can't read ParagraphVectors with layer size < 3

### ISSUE THREAD

**Issue by Treiblesschorle** [deeplearning4j/deeplearning4j#2755]
If I write ParagraphVectors with a layer size < 3 with `writeParagraphVectors(ParagraphVectors vectors, OutputStream stream)` and read them again with `readParagraphVectors(InputStream stream)` then I get an NullPointerException. The problem seems to be that in `loadTxt(File vectorsFile)` it assumes anything having less than 4 whitespace separated values to be a header. Hence, it skips the first line. See:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/loader/WordVectorSerializer.java#L1727

In my tests I'm on 0.6.0, however, the line did not change in 0.7.2 . I don't know if the problem is fixed otherwise until 0.7.2 .

**Comment by raver119** [comment]
Ugh. Just out of curiousity - what's the use case for paravec layer size 2? :)

**Comment by Treiblesschorle** [comment]
Our sanity testcases :D Or if i want to directly plot the vectors without PCA etc.

**Comment by raver119** [comment]
I think the best possible solution here would be just to add the same header. That'll improve compatibility with other frameworks, and will address your issue as well.

**Comment by raver119** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/2766

Now we just add header to CSV files, like other platforms do.
