### ISSUE TITLE
WordVectorSerializer.writeWord2VecModel does not work with Word2Vec objects configured to have a specific "unknownElement"

### ISSUE THREAD

**Issue by AWoelfel** [deeplearning4j/deeplearning4j#2761]
` val vec = new Word2Vec.Builder()
      .elementsLearningAlgorithm(elementsLearningAlgorithm)
      .seed(seed)
      .minWordFrequency(minWordFrequency)
      .iterations(iterations) 
      .layerSize(dimensions)
      .windowSize(windowSize) 
      .useHierarchicSoftmax(true)
      .sampling(sampling) 
      .workers(workerCount)
      .iterate(sequenceIterator)
      .unknownElement(new VocabWord(1.0, ThoughtCorpusIterator.UNK_TOKEN)).useUnknown(true).build()`

and later

`WordVectorSerializer.writeWord2VecModel(vec, outStream)`

leads to : 
java.lang.NullPointerException
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.writeWordVectors(WordVectorSerializer.java:412)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.writeWordVectors(WordVectorSerializer.java:387)

WordVectorSerializer.java:408 //T element = vocabCache.elementAtIndex(x);
return null as the special unknown element is not present in the index.

**Comment by AWoelfel** [comment]
totally forgot to mention: 
we are using deeplearning4j-nlp-0.7.2.jar

**Comment by raver119** [comment]
Fix is implemented here: https://github.com/deeplearning4j/deeplearning4j/pull/2766

Also special test was added: https://github.com/deeplearning4j/deeplearning4j/blob/a085a5f2a60b8f9d3b5c2f97426e3408f8d213f9/deeplearning4j-nlp-parent/deeplearning4j-nlp-uima/src/test/java/org/deeplearning4j/models/word2vec/Word2VecTests.java#L401-L401

Thanks for highlighting this issue.
