### ISSUE TITLE
Documentation for ParagraphVectors learning rate

### ISSUE THREAD

**Issue by oliverdain** [deeplearning4j/deeplearning4j#2770]
Most of your algorithms allow one to specify pretty fine grained learning parameters (e.g. `LearningRatePolicy`) but `ParagraphVectors` only allows you to specify a learning rate and a minimum learning rate. It's not entirely clear what kind of learning rate schedule this corresponds to. As far as I know there aren't any other learning rate tuning options.

**Comment by raver119** [comment]
It's the same decaying mechanism as original w2v implementation: equal step decay.

**Comment by raver119** [comment]
P.s. if you have any other viable ideas there: just let us know :)
