### ISSUE TITLE
Allow pre-tokenized text with Word2Vec/ParagraphVectors

### ISSUE THREAD

**Issue by oliverdain** [deeplearning4j/deeplearning4j#2772]
In our situation I have some text that I've already tokenized (to do part of speech tagging, etc.) Unfortunately the implementation of ParagraphVectors requires that you provide your text as a String and that you provide a TokenizerFactory. As a work-around I simply concatenate my tokens with spaces and then use the default tokenizer. This works but is ugly.

Gitter conversation about this:

https://gitter.im/deeplearning4j/deeplearning4j?at=588a8f39c0f28dd8624a77ad

**Comment by raver119** [comment]
We already have that. It's called SequenceVectors. Word2Vec/ParaVec/GloVe and DeepWalk soon, are all internally just extensions over SequenceVectors<VocabWord>, and SequenceVectors class allows you directly passing Sequence<VocabWord> (or any other type that extends SequenceElement) to learning algorithms. Technically, Word2Vec/ParaVec/etc classes are just used to convert strings/documents to Sequence<VocabWord> 

@tomthetrainer we should highlight that somehow in our NLP docs.

**Comment by tomthetrainer** [comment]
Added a reference to the larger NLP documentation ticket #2701

**Comment by oliverdain** [comment]
Took a quick look at `SequenceVectors`. I think I see how to use it for word2vec, but I don't see how to apply labels for a doc2vec implementation. The builder takes a `SequenceIterator<T>` and `SequenceIterator` doesn't appear to allow you to provide a label for your sequence.

**Comment by raver119** [comment]
Sequence&lt;T&gt; has labels setters/getters: https://github.com/deeplearning4j/deeplearning4j/blob/d43e49d372821dc54a9890395b26c30c81e95495/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/sequencevectors/sequence/Sequence.java#L119-L119

You can actually check how we handle internal text->sequence conversion, it does translates LabelledDocument to Sequence&lt;VocabWord&gt;
