### ISSUE TITLE
Documentation on building locally outdated/wrong

### ISSUE THREAD

**Issue by danimateos** [deeplearning4j/deeplearning4j#2786]
I have found the following defects in the [documentation for building locally]:

* Reference to a [(community-provided) script][original script] that fails (`build-dl4j-stack.sh`):
  ** does not find libnd4j: https://gist.github.com/danimateos/f529cef386994d7813e4dfd186e0ed07
  ** does not use the -cc flag when building libnd4j

* The block of code at the end uses a checkexit function that is not defined: it is defined in the above script, so I guess that's where it came from?

[documentation for building locally]: https://deeplearning4j.org/buildinglocally
[original script]: https://gist.github.com/crockpotveggies/9948a365c2d45adcf96642db336e7df1

**Comment by raver119** [comment]
I've updated instructions there, but we're yet to decide what to do with that script.
Probably we should just put it, say, in dl4j repo and keep it up-to-date...
