### ISSUE TITLE
BarnesHutTsne uses cosinesimilarity as distance

### ISSUE THREAD

**Issue by wobu** [deeplearning4j/deeplearning4j#2813]
BarnesHutTsne initializes default with:
- https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/plot/BarnesHutTsne.java#L87
- https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/plot/BarnesHutTsne.java#L751

this value is passed to VPTree at https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/plot/BarnesHutTsne.java#L182

And finally uses the inverted / negated cosine similarity at here
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/clustering/sptree/DataPoint.java#L76

Second questions:
Shouldn't it be a distance like 1 - cosine similarity instead of cosine similarity alone?

**Comment by raver119** [comment]
Ah, so that's not TSNE, but BarnesHutTsne.

**Comment by wobu** [comment]
ah sry for the misunderstanding
