### ISSUE TITLE
UI doesn't show full model if backprop is set to false

### ISSUE THREAD

**Issue by reidswanson** [deeplearning4j/deeplearning4j#2814]
When pretraining is set to false (e.g., in the example for [stacked denoising autoencoders](https://deeplearning4j.org/stackeddenoisingautoencoder.html)) the full model is not visible in the UI. Only the individual layers, except the output, are included.

**Comment by AlexDBlack** [comment]
By design. UI has different sessions for layerwise pretraining vs. backprop.
During pretraining, only the currently trained layer should be present in the corresponding session.
