### ISSUE TITLE
NGramTokenizer tokenizes the string representation of a list

### ISSUE THREAD

**Issue by mjhugo** [deeplearning4j/deeplearning4j#2819]
I'm trying to use an NGramTokenizer on the DL4J Word2VecRawTextExample.  I took the example as is, modified the tokenizer factory from `DefaultTokenizerFactory` to `NGramTokenizerFactory` like this:

```java
TokenizerFactory t = new NGramTokenizerFactory(new DefaultTokenizerFactory(),1, 3);
```

and I changed the value sent into `vec.wordsNearest` from `day` to `[day]`

```java
log.info("Closest Words:");
Collection<String> lst = vec.wordsNearest("[day]", 10);
System.out.println("10 Words closest to '[day]': " + lst);
```

but I'm not getting anything out of that:

```
10 Words closest to '[day]': []
```

Turns out the NGramTokenizer is adding brackets (a `.toString()` representation of a list) to the tokens.

Using the following:

```java
Collection<String> lst = vec.wordsNearest(" [day]", 10);
```
results in the output:

```
10 Words closest to 'day': [ [day, ],  [night],  [was, every],  [every],  [another, day],  [every, day],  [today, s],  [but, today],  [day, after],  [one, day]]
```

@raver119 [suggested opening an issue](https://gitter.im/deeplearning4j/deeplearning4j?at=58949d854c04e9a44e676a85)

> that should be:
> a) configurable brackets
> b) no spaces if brackets are used

In looking at [the code](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/text/tokenization/tokenizer/NGramTokenizer.java#L50), I think the intent was to separate the tokens with a space, e.g. `[another, day]` should be `another day`

**Comment by raver119** [comment]
fix is merged
