### ISSUE TITLE
Unsupervised learning?

### ISSUE THREAD

**Issue by DzianisH** [deeplearning4j/deeplearning4j#2825]
Would you support unsupervised learning algorithms (e.g. PCA)? May be it is good idea to add this class of algorithms to deeplearning4j.

**Comment by agibsonccc** [comment]
We have autoencoders and have had them for years. We also support RBMs.  We just updated our kmeans. PCA would go in nd4j, we need to do a bit more work on PCA there, open a separate issue for that.
