### ISSUE TITLE
MapTupleToPairFlatMap is not defined properly and sparkNet.fit(...) throws a java.lang.AbstractMethodError exception

### ISSUE THREAD

**Issue by RoiViber** [deeplearning4j/deeplearning4j#2828]
Note: in org.deeplearning4j.spark.impl.common.repartition.MapTupleToPairFlatMap there's an override method returning the wrong object type (Iterable instead of Iterator), and apparently that compiles and throws a runtime exception, just like in https://issues.apache.org/jira/browse/SPARK-902

the exception is as follows:

> Name: org.apache.spark.SparkException
> Message: Job aborted due to stage failure: Task 18 in stage 119.0 failed 4 times, most recent failure: Lost task 18.3 in stage 119.0 (TID 141251, ip-10-45-214-56.ec2.internal): java.lang.AbstractMethodError: org.deeplearning4j.spark.api.worker.ExecuteWorkerFlatMap.call(Ljava/lang/Object;)Ljava/util/Iterator;
> 	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:152)
> 	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:152)
> 	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:785)
> 	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:785)
> 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:86)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> Driver stacktrace:
> StackTrace: 	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:152)
> 	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:152)
> 	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:785)
> 	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:785)
> 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:86)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> Driver stacktrace:
>   at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1454)
>   at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1442)
>   at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1441)
>   at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
>   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
>   at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1441)
>   at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
>   at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
>   at scala.Option.foreach(Option.scala:257)
>   at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
>   at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1667)
>   at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1622)
>   at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1611)
>   at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
>   at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
>   at org.apache.spark.SparkContext.runJob(SparkContext.scala:1873)
>   at org.apache.spark.SparkContext.runJob(SparkContext.scala:1936)
>   at org.apache.spark.rdd.RDD$$anonfun$aggregate$1.apply(RDD.scala:1091)
>   at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
>   at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
>   at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
>   at org.apache.spark.rdd.RDD.aggregate(RDD.scala:1084)
>   at org.apache.spark.api.java.JavaRDDLike$class.aggregate(JavaRDDLike.scala:425)
>   at org.apache.spark.api.java.AbstractJavaRDDLike.aggregate(JavaRDDLike.scala:45)
>   at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingMaster.processResults(ParameterAveragingTrainingMaster.java:770)
>   at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingMaster.doIteration(ParameterAveragingTrainingMaster.java:659)
>   at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingMaster.executeTrainingDirect(ParameterAveragingTrainingMaster.java:372)
>   at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingMaster.executeTraining(ParameterAveragingTrainingMaster.java:346)
>   at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.fit(SparkDl4jMultiLayer.java:225)
>   at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.fit(SparkDl4jMultiLayer.java:212)
>   at $$$3bc635731c76d9176b3dadeb3d4f167$$$$anonfun$1.apply$mcVI$sp(<console>:312)
>   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
>   ... 140 elided
> Caused by: java.lang.AbstractMethodError: org.deeplearning4j.spark.api.worker.ExecuteWorkerFlatMap.call(Ljava/lang/Object;)Ljava/util/Iterator;
>   at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:152)
>   at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:152)
>   at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:785)
>   at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:785)
>   at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
>   at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
>   at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
>   at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
>   at org.apache.spark.scheduler.Task.run(Task.scala:86)
>   at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
> 
> 
> 
>

**Comment by agibsonccc** [comment]
Did we ever determine the source of this?

**Comment by AlexDBlack** [comment]
May have been fixed here (which was a couple of days after this issue was opened): https://github.com/deeplearning4j/deeplearning4j/commit/8ce2d75c22f29d8569e6b1d7db0c8ba0e2f761e5
Need to confirm before closing.

**Comment by AlexDBlack** [comment]
Closing this as resolved (by the earlier-mentioned commit). I've run both the spark unit tests and two of the spark examples all using Spark 2 - I'm not seeing any issues there.

**Comment by AlexDBlack** [comment]
Now seeing this on one of the examples, after rebuilding. Not sure what's up yet (or why I didn't see it previously).

**Comment by AlexDBlack** [comment]
Looks like it's the same issue we had with scala versions (and why we couldn't use profiles for that): the resulting POMs still contain properties which are read from the defaults (in deeplearning4j-parent pom), instead of being hard-coded to the actual value that was present during the build.
The result: dl4j spark 2 is pulling in datavec spark 1.

I think I didn't see it before because I did the change + install manually. Fix is to not use properties, and use find/replace for everything.

**Comment by jzhusc** [comment]
@AlexDBlack I've met the same problem running MNIST spark examples on google cloud dataproc
with the gradle
``compile group: 'org.bytedeco', name: 'javacpp', version: '1.3.1'
    compile "org.deeplearning4j:dl4j-spark_2.11:0.7.2"
    compile group: 'org.nd4j', name: 'nd4j-native-platform', version: '0.7.2'``
Is there any fix?

**Comment by agibsonccc** [comment]
@jzhusc this will be fixed in the next release.

**Comment by AlexDBlack** [comment]
@jzhusc @agibsonccc actually, no - this particular issue is impossible to occur with 0.7.2.
My guess is that you are trying to run DL4J 0.7.2 on Spark 2, which isn't supported until the next release.

**Comment by jzhusc** [comment]
@AlexDBlack yes I did. So the DL4J for now only support Spark1?

**Comment by agibsonccc** [comment]
Yes. Spark 2 comes next release.

**Comment by jzhusc** [comment]
@agibsonccc gotcha. Thanks a lot!
btw, what the 2.11 stands for in
``compile group: 'org.deeplearning4j', name: 'dl4j-spark_2.11', version: '0.7.2'``

**Comment by AlexDBlack** [comment]
2.11 = scala version
Our scala versioning scheme is the same as everything else with multiple scala versions (including, Spark).

**Comment by yanenlisc** [comment]
when will the next release (0.7.3) come out?
