### ISSUE TITLE
AdaGrad configuration error (NeuralNetConfiguration.Builder)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#283]
In summary: when setting up a network (NeuralNetConfiguration.Builder), setting useAdaGrad(false) doesn't actually set this is the layers after model initialization.
i.e., model.getLayers()[i].conf().isUseAdaGrad() == true, after calling useAdaGrad(false) on the builder.
Simple example: https://gist.github.com/AlexDBlack/bd4e608c5189182d83a6

**Comment by agibsonccc** [comment]
Fixed.
