### ISSUE TITLE
Scaling in k-means clustering

### ISSUE THREAD

**Issue by mikegwf1** [deeplearning4j/deeplearning4j#2830]
Hi,
  I am clustering word vectors obtained from a dl4j w2v model, using the following method.
     String distanceFunction = "euclidean";
       KMeansClustering kmc = KMeansClustering.setup(clusterCount, par.minDistributionVariationRate, distanceFunction, true);

clusterCount = 10000, and minDistributionVariationRate = .025.  I am clustering about 300,000 vectors with a dimensionality of 250.  

This takes a good 10 hours on an 8 core system.  However, the cpu power of my system is only 30-40% utilized during the clustering process.  Running, W2V, for example, cpu utilization stays around 100%.  I would like to have clustering take better advantage of the system cpu power.  Are there any parameters to tweak?  If not, is there a way you can improve the parallelism?

Thanks,
Michael Sperling
203-644-9195

**Comment by agibsonccc** [comment]
This should be fixed in the latest release. We ran in to this already.

**Comment by mikegwf1** [comment]
Hi,
  This is good to hear.  Do you mean 0.7.2 or the release after that? If
so, when do you expect the next release?  FYI, the problem exists in 0.7.2.
Thanks,
Mike
