### ISSUE TITLE
Documentation on interpretation of nn-UI visualization is lacking

### ISSUE THREAD

**Issue by ghost** [deeplearning4j/deeplearning4j#2842]
More documentation on how to read nn-UI visualization would be nice.

**Comment by tomthetrainer** [comment]
Agreed

**Comment by AlexDBlack** [comment]
Post release I want to get a blog post out, that should help with this. I totally agree that more info here would be better.

**Comment by tomthetrainer** [comment]
@AlexDBlack Status of blog post? If no blog post I can work up some better docs.
