### ISSUE TITLE
Wrong usage of repository

### ISSUE THREAD

**Issue by khmarbaise** [deeplearning4j/deeplearning4j#285]
On your page http://deeplearning4j.org/maven.html you are referencing on ibiblio as central repository. This is simply wrong. Ibiblio is *only* a mirror but not Central.. Maven uses Maven Central 
This can seen here: 

http://maven.apache.org/repository/index.html

Furthermore can be checked by looking into the [maven super pom](http://maven.apache.org/ref/3.3.3/maven-model-builder/super-pom.html) or [for older versions](http://maven.apache.org/ref/3.0.5/maven-model-builder/super-pom.html).
either https://repo.maven.apache.org/maven2 or http://repo.maven.apache.org/maven2/ instead which is the central repository.

**Comment by agibsonccc** [comment]
@chrisvnicholson Would you mind updating the screenshot? I think this is a valid concern here. @khmarbaise You're absolutely right. Thanks for submitting the issue.
