### ISSUE TITLE
Create a normalization page

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#2858]
We should have a page we can link to that explains how to use the normalizers including:
reverting labels and inputs
different kinds of normalization and the trade offs
persistence (saving them)
explain the fit method (eg: how to initialize the normalizer)

**Comment by nmaynes** [comment]
@agibsonccc I would be interested in helping put this together.

**Comment by agibsonccc** [comment]
@nmaynes  /cc @tomthetrainer  thanks! This can happen via github pages: https://github.com/deeplearning4j/deeplearning4j/tree/gh-pages

Look at some of the mark down files in the root directory and follow that. We just use github flavored markdown. Thanks for the help!

**Comment by nmaynes** [comment]
I began writing up a [document](https://github.com/nmaynes/deeplearning4j/blob/gh-pages/normalization.md). Can someone take a look and let me know if I am going in the right direction. I still need to add the examples. While writing the intro I realized consistency in referring to normalization/regularization would be prudent. Which term will be used in deeplearning's documentation? The building-neural-net-with-dl4j tutorial uses regularization.

**Comment by agibsonccc** [comment]
Wrong kind of normalization ;). We are talking about zero mean unit variance, scale zero to 1 and how to use those transformers.

**Comment by nmaynes** [comment]
If I am understanding, the tutorial should go over the following classes in deeplearning4j and provide basic instructions on why to use them, their trade offs, and working example code.

- BaseInputPreProcessor
- UnitVarianceProcessor
- ZeroMeanAndUnitVariancePreProcessor
- ZeroMeanPrePreProcessor

I want to make sure I grasp what a normalization page would look like in the deeplearning4j tutorials before spending time writing something up.

**Comment by agibsonccc** [comment]
Indeed :D . Wait till next release though. @EdeMeijer wrote our new normalizers.
