### ISSUE TITLE
Can't load word2vec model trained on Google News Corpus

### ISSUE THREAD

**Issue by Sherafgan** [deeplearning4j/deeplearning4j#2859]
I wanted to use the word2vec model trained on Google News Corpus which downloaded [here](https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz). But I get this exception:
`0 [main] INFO org.nd4j.linalg.factory.Nd4jBackend  - Loaded [CpuBackend] backend
157 [main] INFO org.nd4j.nativeblas.NativeOpsHolder  - Number of threads used for NativeOps: 4
225 [main] DEBUG org.reflections.Reflections  - going to scan these urls:
jar:file:/root/VecSearch/target/VecSearch-0.7-SNAPSHOT-jar-with-dependencies.jar!/
704 [main] INFO org.reflections.Reflections  - Reflections took 468 ms to scan 1 urls, producing 29 keys and 176 values 
1082 [main] DEBUG org.deeplearning4j.models.embeddings.loader.WordVectorSerializer  - Trying simplified model restoration...
1103 [main] DEBUG org.deeplearning4j.models.embeddings.loader.WordVectorSerializer  - Trying CSV model restoration...
1103 [main] DEBUG org.deeplearning4j.models.embeddings.loader.WordVectorSerializer  - Trying binary model restoration...
Exception in thread "main" java.lang.RuntimeException: Unable to guess input file format. Please use corresponding loader directly
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2352)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2229)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2245)
	at indexer.Indexer.main(Indexer.java:23)`

I have no idea on which version of the word2vec the model was trained, I just was following [this tutorial](https://deeplearning4j.org/word2vec#setup).

**Here is the pom.xml file dependencies:**
`<properties>
        <nd4j.version>0.7.2</nd4j.version>
        <dl4j.version>0.7.2</dl4j.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-nlp</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native-platform</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
         
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.22</version>
        </dependency>
    </dependencies>`

**And here is the class with main method:**

`     
import org.apache.log4j.BasicConfigurator;

import org.deeplearning4j.models.embeddings.loader.WordVectorSerializer;
import org.deeplearning4j.models.word2vec.Word2Vec;

import java.io.File;
import java.io.IOException;

public class Indexer {
    private final static String SENTENCES_PATH = "data/ready/sentences.txt";
    private final static String GNC_MODEL_PATH = "models/GoogleNews-vectors-negative300.bin.gz";

    public static void main(String[] args) throws IOException {
        BasicConfigurator.configure();

        File gModel = new File(GNC_MODEL_PATH);
        Word2Vec vec = WordVectorSerializer.readWord2VecModel(gModel);
    }
}`

OS: Ubuntu 16.04.1 x64

**Comment by agibsonccc** [comment]
There's a loadGoogleModel you need to use. You don't use read word2vec.

**Comment by raver119** [comment]
readWord2Vec() handles that internally, but something went wrong according to output...

> org.deeplearning4j.models.embeddings.loader.WordVectorSerializer - Trying binary model 

That's fallback to the google-like binary model.

@Sherafgan what WordVectorSerializer.loadGoogleModel() method says if you use it? As i see you have relative paths there, maybe that's the case?

**Comment by Sherafgan** [comment]
@agibsonccc  I tried with `loadGoogleModel` and it worked, thanks! But IDE says that the method is deprecated as you can see [here](http://imgur.com/a/H6rPZ), although the javadoc [here](https://deeplearning4j.org/doc/org/deeplearning4j/models/embeddings/loader/WordVectorSerializer.html#loadGoogleModel-java.io.File-boolean-) says it is not. Smth is wrong here)

@raver119 Yeah, the relative path also was wrong, but don't know whether it was the case. I will try the initial `readWord2VecModel` later and reply here, maybe the relative path was the case.

**Comment by raver119** [comment]
Aha, that's fine then. This issue was already fixed, and file existence checks were added some time ago,

**Comment by Sherafgan** [comment]
:D Okay, thank you for rapid response!
