### ISSUE TITLE
deeplearning4j-core: CounterMapTest passes/fails

### ISSUE THREAD

**Issue by sonaliii** [deeplearning4j/deeplearning4j#286]
The CounterMapTest passes on some occasions and fails on other occasions. No changes have been made to the code in between these test runs.

**Comment by smarthi** [comment]
I was seeing the consistent failures with this too, didn't really have the time to dig into it

**Comment by agibsonccc** [comment]
This is related to race conditions.

**Comment by agibsonccc** [comment]
Fixed.
