### ISSUE TITLE
UI: score vs. iteration doesn't correctly display negative scores

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2862]
Under most circumstances, scores are positive - but can be negative for things like VAEs which utilize negative log likelihood. For example, NLL can be negative with a very small standard deviation

![image](https://cloud.githubusercontent.com/assets/2360237/22917025/70b6ca0c-f2d6-11e6-8a99-1bd48e41f8fe.png)

**Comment by reidswanson** [comment]
To help keep track of duplicates [here's a similar issue I filed a few days ago](https://github.com/deeplearning4j/deeplearning4j/issues/2829)...

**Comment by AlexDBlack** [comment]
Fixed here, will be merged soon: https://github.com/deeplearning4j/deeplearning4j/pull/2872
