### ISSUE TITLE
deeplearning4j-keras module creates shaded jar

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2863]
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-keras/pom.xml#L127

Currently, a build/install results in a 96MB shaded jar - this is bad practice, and we don't want to be releasing this onto maven central.

![image](https://cloud.githubusercontent.com/assets/2360237/22924998/476384ae-f2fb-11e6-98b6-1513539c22fe.png)

**Comment by huitseeker** [comment]
@crockpotveggies

**Comment by crockpotveggies** [comment]
Yup this would be an artifact from its original author. I can remove it in my current branch.
