### ISSUE TITLE
Dependency confilct between dl4j and Jersey

### ISSUE THREAD

**Issue by junyongyou** [deeplearning4j/deeplearning4j#2864]
I want to use jersey 2.17 to build Uri for a Rest request. However, it seems my codes actually use Jersey 1.9, even though I didn't it in my Gradle dependency. Does anybody know which library in DL4J import Jersey 1.9? Because I can see it in my library list after refreshing Gradle. 

Here are my Gradle dependency and exception report: https://gist.github.com/junyongyou/406d4b3559c0b6a244f1af0e7095da6b

**Comment by raver119** [comment]
Use this command `mvn dependency:tree -Dverbose` and you'll see all transitive dependencies yourself

**Comment by raver119** [comment]
p.s. it comes from dl4j-ui
