### ISSUE TITLE
DL4J with CPU-backend crash on Windows 10 Pro

### ISSUE THREAD

**Issue by rohrl** [deeplearning4j/deeplearning4j#2887]
DL4J with CPU backend crashes on Windows 10 Pro.
Crashes when trying to evaluate Inception V3 imported from Keras (Theano backend).
I'm attaching crash log.
Below is a piece of logs before the crash:
```
com.nuix.load.image.d - Image size: 199 W x 299 H
org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 8
org.reflections.Reflections - Reflections took 90 ms to scan 8 urls, producing 29 keys and 185 values 
org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 8
org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [32]; Memory: [157.7GB];
org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [OPENBLAS]

```

**Comment by rohrl** [comment]
[crash.log.txt](https://github.com/deeplearning4j/deeplearning4j/files/786430/crash.log.txt)

**Comment by rohrl** [comment]
Stack extracted from above file:
```
Stack: [0x0000000000050000,0x0000000000150000],  sp=0x000000000014dd80,  free space=1015k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libnd4jcpu.dll+0x10923a]
C  [jnind4jcpu.dll+0x1391e]
C  0x0000000002a25c54

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.nd4j.nativeblas.Nd4jCpu$NativeOps.execScalarFloat(Lorg/bytedeco/javacpp/PointerPointer;ILorg/bytedeco/javacpp/FloatPointer;ILorg/bytedeco/javacpp/FloatPointer;IFLorg/bytedeco/javacpp/FloatPointer;J)V+0
j  org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(Lorg/nd4j/linalg/api/ops/ScalarOp;)V+609
j  org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(Lorg/nd4j/linalg/api/ops/Op;)Lorg/nd4j/linalg/api/ops/Op;+19
j  org.nd4j.linalg.api.ndarray.BaseNDArray.divi(Ljava/lang/Number;Lorg/nd4j/linalg/api/ndarray/INDArray;)Lorg/nd4j/linalg/api/ndarray/INDArray;+38
j  org.nd4j.linalg.api.ndarray.BaseNDArray.divi(Ljava/lang/Number;)Lorg/nd4j/linalg/api/ndarray/INDArray;+3
j  org.nd4j.linalg.dataset.api.preprocessor.ImagePreProcessingScaler.preProcess(Lorg/nd4j/linalg/api/ndarray/INDArray;)V+8
```

**Comment by saudet** [comment]
Could you also provide some small self-contained sample code to reproduce the crash?

**Comment by rohrl** [comment]
```
BufferedImage image = ImageIO.read(f.toFile());

                                                       // load image as nd4j matrix
                                                       NativeImageLoader imageLoader = new NativeImageLoader(299, 299, 3);
                                                       INDArray input = imageLoader.asMatrix(image);

                                                       // scale scalars to range (-1, 1)
                                                       ImagePreProcessingScaler scaler = new ImagePreProcessingScaler(-1, 1);
                                                       scaler.preProcess(input);

                                                       // evaluate network outputs for the input matrix
                                                       Stopwatch sw = Stopwatch.createStarted();
                                                       INDArray output = network.output(false, input)[0];
                                                       System.out.println("Evaluation took " + sw);
```

**Comment by saudet** [comment]
Wait a minute, you're getting a EXCEPTION_ILLEGAL_INSTRUCTION. That probably means your CPU is too old for the binaries...

**Comment by rohrl** [comment]
It's Intel Xeon CPU x7560,  32 logical cores - how can this be too old ?

I built the binary on a different machine (Windows as well) - can this matter ?

**Comment by rohrl** [comment]
+ it shouldn't crash the JVM anyway, even if it's too old

**Comment by agibsonccc** [comment]
@rohrl It *should* crash the JVM. It's JNI. And yes: different OSes matter quite a bit. Can we see your pom?

**Comment by saudet** [comment]
@rohrl Don't build from source use the binaries from Maven.

**Comment by raver119** [comment]
It looks like @saudet is right, probably binaries were built with -a native on one box, and launched on other box?

**Comment by rohrl** [comment]
@saudet @agibsonccc The build was done on Windows 7 and the crash on Windows 10 - both OS'es fall under same dependency classifier. If there is hardware/OS that causes crashes maybe it should be checked upfront in Java and failed with an exception? Could you explain how a release version is going to have lesser likelihood of such crash than a build from master - is the release tested on a variety of hardware and OS versions ? 
I'm trying to asses if the current design with DL4J is safe for us - we can't afford frequent crashes. Our clients install our product on many different machines, usually high spec like the one reported, so we need high level of confidence that crash won't happen..
Thanks

**Comment by raver119** [comment]
@rohrl that crash with 98% chance was caused by you using `-a native` switch, without understanding what it does.  Release binaries are NOT using this switch, and won't ever use it. 

Release binaries are built for generic x86-64 arch, without any system-specific specs.

**Comment by raver119** [comment]
P.s. cpu you've mentioned is from 2010. So, if you've built your binaries with native switch on modern desktop cpu, say core i5 from 2015/2016, there you have missing instructions.

**Comment by rohrl** [comment]
I see. So I should just remove "-a native' and it should be fine? 
So this switch is for optimising the performance for a particular machine?

**Comment by rohrl** [comment]
@raver119  indeed, after building without `-a native` it works fine. Thanks
