### ISSUE TITLE
Provide an example about generating vectors from provided sentences

### ISSUE THREAD

**Issue by ssaltin** [deeplearning4j/deeplearning4j#2896]
I'm trying to find a way to train W2V model with provided tokens. I've already tokenized and lemmatized tokens, some of them are n-grams such as: "mc Donald's" "LA Lakers" "European Union" and I've them in a data structure as: List<List<String>> sentences

And I want to add them to W2V as:

// read, sentence extract, lemmatize with different ways and generate List<List<String>> sentences 

for (List<String> sentenceTokens : sentences) {
// provide a way to feed W2V
}

Is it possible to provide a sample project for this logic so I can find neighbours such as W2V.wordsNearest("LA Lakers", 10);?

**Comment by raver119** [comment]
All you need to make this work is to provide Iterable<Sequence<VocabWord>> here: https://github.com/deeplearning4j/deeplearning4j/blob/cc927e0c5c0c4ebc5b8a7bbb1640e8c46568d17b/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/sequencevectors/iterators/AbstractSequenceIterator.java#L59-L59


If you have tokenized sentences, it usually means that you have Collection<String>.  Wrap those Strings into VocabWord, and provide Iterable<Sequence<VocabWord>>. Each sentence will be represented as Sequence<VocabWord>, and you're done.
