### ISSUE TITLE
CLI dl4j - iris example from cli failing with Null Pointer Error

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#290]
$ dl4j train -conf /path/to/cli_train_unit_test_conf.txt -m /path/to/model_multi.json -input /path/to/iris.txt

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/Skymind/dl4j/lib/logback-classic-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/Skymind/dl4j/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
16:58:29,650 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
16:58:29,650 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
16:58:29,651 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/usr/local/Skymind/dl4j/lib/deeplearning4j-core-0.0.3.3.4.alpha1-SNAPSHOT.jar!/logback.xml]
16:58:29,651 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
16:58:29,651 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/usr/local/Skymind/dl4j/lib/deeplearning4j-core-0.0.3.3.4.alpha1-SNAPSHOT.jar!/logback.xml]
16:58:29,651 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/usr/local/Skymind/dl4j/lib/nd4j-api-0.0.3.5.5.4-SNAPSHOT.jar!/logback.xml]
16:58:29,668 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@887af79 - URL [jar:file:/usr/local/Skymind/dl4j/lib/deeplearning4j-core-0.0.3.3.4.alpha1-SNAPSHOT.jar!/logback.xml] is not of type file
16:58:29,712 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
16:58:29,716 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
16:58:29,724 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
16:58:29,748 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:58:29,796 |-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is set to [logs/application.log]
16:58:29,797 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
16:58:29,798 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
16:58:29,800 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:58:29,804 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.catalina.core] to DEBUG
16:58:29,804 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework] to DEBUG
16:58:29,804 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.deeplearning4j] to INFO
16:58:29,804 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ERROR
16:58:29,804 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
16:58:29,804 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
16:58:29,804 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
16:58:29,806 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@7fac631b - Registering current configuration as safe fallback point

SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
o.d.c.s.Train - [dl4j] - executing local ... 
o.d.c.s.Train - using training input: tmp/dl4j-cli-example/data/irisSvmLight.txt
Exception in thread "main" java.lang.NullPointerException
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:159)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:936)
	at org.deeplearning4j.cli.subcommands.Train.execLocal(Train.java:169)
	at org.deeplearning4j.cli.subcommands.Train.execute(Train.java:137)
	at org.deeplearning4j.cli.driver.CommandLineInterfaceDriver.doMain(CommandLineInterfaceDriver.java:51)
	at org.deeplearning4j.cli.driver.CommandLineInterfaceDriver.main(CommandLineInterfaceDriver.java:60)

**Comment by agibsonccc** [comment]
Fixed.
