### ISSUE TITLE
Support for fully-convolutional networks

### ISSUE THREAD

**Issue by vzamboni** [deeplearning4j/deeplearning4j#2904]
In order to avoid image input size limitation in object detection tasks should be interesting to implement fully-convolutional support which is from a pre trained conv net:

- convert last fully connected layer(s) into convolutional layer(s) (as described [here](http://tech.gilt.com/deep/learning/2016/05/18/fully-connected-to-convolutional-conversion) and [here](http://cs231n.github.io/convolutional-networks/#convert) )

- let users apply the network to any size images and receive an heatmap of detections through the original image (as described [here](https://arxiv.org/pdf/1502.02766.pdf) )

**Comment by turambar** [comment]
Duplicates issue here: https://github.com/deeplearning4j/deeplearning4j/issues/2818.
