### ISSUE TITLE
Word2Vec BasicModelUtils.wordsNearest

### ISSUE THREAD

**Issue by silvioOlivastri** [deeplearning4j/deeplearning4j#2905]
Hi,

I testing the method 

`public Collection<String> wordsNearest(Collection<String> positive, Collection<String> negative, int top)`

found instead `BasicModelUtils` class. I follow the [gensim example](https://radimrehurek.com/gensim/models/word2vec.html) to do that, specifically my refer is:

```
>>> model.most_similar(positive=['woman', 'king'], negative=['man'])
[('queen', 0.50882536), ...]
```

because **'man' is to 'king' as 'woman' is to ... 'queen'**.

So, with DL4J my code is:

```
Word2Vec vec = WordVectorSerializer.readWord2VecModel(new File("GoogleNews-vectors-negative300.bin.gz"));

System.out.println(vec.wordsNearest(
                Arrays.asList(new String[]{"king", "woman"}), 
                Arrays.asList(new String[]{"man"}),
                1));
```

the output was `[king]`, but it should be `[queen]`.
If I set "top" parameter from 1 to 5 the output was `[king, queen, monarch, princess, crown_prince]`.

How can the answer contains a word of the query list (`[king]`) ? I think it's bug, right?

**Comment by raver119** [comment]
What's the question?
Without seeing full source code - i can't say anything viable - there's multiple ways to spoil things.

I.e.:
- model could be normalized before this call
- word vectors could actually mismatch your expectations

Show your source code as gist please.

**Comment by silvioOlivastri** [comment]
Sorry, I modify the question :)

I hope it's more clear!

**Comment by silvioOlivastri** [comment]
Any news?

**Comment by raver119** [comment]
Yes, that was a minor bug, those king/queen words should be just removed.

Fix applied. Thanks for highlighting this issue.
