### ISSUE TITLE
Comparing frameworks documentation issue for TensorFlow

### ISSUE THREAD

**Issue by DzianisH** [deeplearning4j/deeplearning4j#2914]
Here _https://deeplearning4j.org/compare-dl4j-torch7-pylearn#tensorflow_ you say that TF doesn't support JVM users, but it is not true anymore. Check TF's API page for more details _https://www.tensorflow.org/api_docs/_.

**Comment by agibsonccc** [comment]
We should be careful what "support" means. We have our own presets for TF as well (with more features):
https://github.com/bytedeco/javacpp-presets

Main thing of note here is: You can't really build much with it. You can kinda serve models with it, but it's not actually a full blown api. (This is the same problem the presets have). There's a significant amount of functionality only available in python. Thanks for filing this.

**Comment by tomthetrainer** [comment]
I modified the wording so it should be technically accurate but still deliver our point. 

"Although there is experimental support for a Java API it is not currently considered stable, we do not consider this a solution for the Java and Scala communities."

If the original ticket submitter has further issue, feel free to re-open. We want to be accurate. 

Actually I assume that page can use updating in other areas, just patched this particular sentence for now.
