### ISSUE TITLE
Correction: How to Use Deeplearning4J in Android Apps

### ISSUE THREAD

**Issue by Cawfree** [deeplearning4j/deeplearning4j#2924]
The Gradle dependencies should be updated to:

    compile 'org.deeplearning4j:deeplearning4j-core:0.7.2'

    compile 'org.nd4j:nd4j-native:0.7.2'

    compile 'org.nd4j:nd4j-native:0.7.2:android-x86'

    compile 'org.nd4j:nd4j-native:0.7.2:android-arm'

_(The ARM architcture is prevalent for Android devices.)_

**Comment by tomthetrainer** [comment]
Edited this page, https://deeplearning4j.org/android

Added the compile for android arm, 

Thanks for the bug report

**Comment by Cawfree** [comment]
Hey Tom, 

Thanks for the update, and no problem!

Sorry to be a total hassle, but I've found that the safest implementation to use is:
`compile group: 'org.nd4j', name: 'nd4j-native-platform', version: '0.7.2'`

(Instead of selecting specific targets i.e. `android-x86` or `android-arm`.)

This lets the library take care of the underlying implementation; the current approach still poses some possible integration headaches.

Cheers!
