### ISSUE TITLE
ComputationGraph model cannot continue to train after restoring from file.

### ISSUE THREAD

**Issue by liulhdarks** [deeplearning4j/deeplearning4j#2930]
I have stopped to train the ComputationGraph model after some epochs, and the score have droped from 9.x to 2.x, and then I saved the model to file.
buf when I restore the model and try to continue to train, but the score start from 9.x, and it seems the weights or updater have been reset after restoring from file. I have reproduced the problem by dl4j-example "AdditionRNN". see the detail code from the url below. https://gist.github.com/liulhdarks/bfc2f633d7ee8beca0a750a3c807647e

**Comment by AlexDBlack** [comment]
Looks like this is just a simple bug in your model loading code: you load the model, but don't actually return it (your loadModel() method always returns null).
https://gist.github.com/liulhdarks/bfc2f633d7ee8beca0a750a3c807647e#file-additionrnn2-java-L113

Scores look correct to me if I add the proper return statement.
