### ISSUE TITLE
Build Lucene index over javadoc, examples, and other resources

### ISSUE THREAD

**Issue by tomthetrainer** [deeplearning4j/deeplearning4j#2934]
Building with deeplearning4j is complicated by the fact that some code is part of ND4J, some is part of DataVec and some is part of deeplearning4J

It would be nice to index all of that and make it searchable. 

The search hadoop project is what I am thinking of. 

http://search-hadoop.com/

On a less grand scale, it is just one of the lucene based indexers, SolR probably, that builds a facetted search. 

For example I am searching for the javadoc on RecordReaderDataSetIterator. 
RecordReader is in DataVecDoc, RecordReaderDataSetIterator is in the deeplearning4J doc, but the transforms and normalizers are probably in the nd4J doc. 

So separation of code is good for development, but it is challenging for the beginners when coding, a search page over an index could bridge the gap. 

I am assigning myself, but someone else may have more experience with this. I think it is fairly straightforward, set up sources, rebuild index at intervals and SOLR makes it easy. 

@huitseeker Adding you in case you have SOLR, Lucene or elastic search experience

**Comment by tomthetrainer** [comment]
Not sure this is feasible given time and effort.

**Comment by huitseeker** [comment]
@tomthetrainer I agree -_-
