### ISSUE TITLE
DL4J job run with spark-submit fails with "java.util.ServiceConfigurationError: org.nd4j.linalg.factory.Nd4jBackend: Provider org.nd4j.linalg.cpu.nativecpu.CpuBackend not found"

### ISSUE THREAD

**Issue by mindcrime** [deeplearning4j/deeplearning4j#2935]
I am running Spark 2.10 on my development laptop, trying to run a DL4J job in standalone mode.  The command line is:

> spark-submit --master local --class org.fogbeam.dl4j.spark.ExpMain3 target/dl4j-spark-0.0.1-SNAPSHOT.jar

The console output is here:

https://gist.github.com/mindcrime/7bff8c4512834f1f26115cf342fde1df

The pom.xml is here:

https://gist.github.com/mindcrime/c11d8d3bd44b9db59857deb122027663

**Comment by raver119** [comment]
Spark 2.x support will be introduced in next nearest release only.

As for exception: dl4j-spark-0.0.1-SNAPSHOT.jar <-- are you sure this file is an uber jar?

**Comment by agibsonccc** [comment]
This was related to the shade plugin.

**Comment by mindcrime** [comment]
It turn out that the problem was as follows:

1. In the Maven shade plugin configuration, I had the "minimizeJar" setting set to "true"
`<minimizeJar>true</minimizeJar>`

2. I don't understand the exact algorithm that the shade plugin uses to determine which classes aren't used, but for some reason it was excluding (some|most|all|???) of the classes from the nd4j-native-platform, including CpuBackend.

3. I changed the setting to "false"
`<minimizeJar>false</minimizeJar>`
and rebuilt the project, and the problem was resolved.

This might be worth noting in the DL4J documentation, for anybody who is building their projects using Maven, and building an uber jar for use with Spark.

**Comment by mindcrime** [comment]
> Spark 2.x support will be introduced in next nearest release only.

Thanks for pointing that out.  It wasn't related to my original problem, but after resolving that problem, I did run into another issue related to using Spark 2.x.  I switched to 1.6.3 and everything works like a charm.
