### ISSUE TITLE
Build issue: dl4j-spark-nlp-java8 + scala 2.10 fails

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2942]
Default scala 2.11 builds fine, dl4j-spark-nlp-java8_2.10 fails:

To reproduce: start with dl4j master, run the following:
./change-scala-versions.sh 2.10
mvn clean install -DskipTests

https://gist.github.com/AlexDBlack/a01ad4c345d3997c97c5991a9024ee60

**Comment by raver119** [comment]
I've did the following:

built nd4j for 2.10, built datavec for 2.10, and here's build log for dl4j:

TL/DR: Build success

https://gist.github.com/raver119/bd674dd14af1689f1e03d65e73799d8f

**Comment by AlexDBlack** [comment]
Looks like it was just an outdated nd4j build on my machine. Tried again and it's working fine. Closing this.
