### ISSUE TITLE
Garbage Collection on RNNs

### ISSUE THREAD

**Issue by Stevod** [deeplearning4j/deeplearning4j#2943]
Original problem was CPU bound due to GC according to raver119, who advised me to disable explicitGC in JVM, which led to Out of Memory. after 4-6 hours training. 

Screen shot of original problem attached, and code was send via raver19's 1-to-1 gitter inbox.

![cpubound](https://cloud.githubusercontent.com/assets/6758915/23406595/9e01d20e-fdb7-11e6-84ed-26a18be78711.jpg)

**Comment by agibsonccc** [comment]
Just going to note we intend on taking a crack at GC next.

**Comment by Stevod** [comment]
Thanks Adam, I'm still getting memory problems which means that I can't get complete convergence at all, so it's really annoying as I can't effectively assess any set of hyper-parameters. Let me know if I can test any stuff that you are working on.

**Comment by raver119** [comment]
Workspaces should address your issue: https://github.com/deeplearning4j/nd4j/pull/1731

**Comment by agibsonccc** [comment]
Closing this in favor of the overall GC issue.
