### ISSUE TITLE
ParagraphVectors: "inferVector" always retrieve same vector, no matter which labelled document is provided!

### ISSUE THREAD

**Issue by todoacien** [deeplearning4j/deeplearning4j#2944]
Make use of "public INDArray inferVector(LabelledDocument document)" for my tests.

I basically created some methods to test the quality of the inferred vectors.
What I do is to randomly extract few labelled documents from the corpus. For each of them, I infer their vectors. then I retrieved the top 5-10 closest documents, so I should expect to see in the top the original document.
For DM model, it seems to be working. I get on top of the list the original document not matter which random document I have picked for the test.
For the DBOW model instead, I always get the same top N list label of documents for any random pick of labelled document.

I created these methods to evaluate quality of inferred vectors:
https://gist.github.com/todoacien/d556f3f1f21d527ccf67eceb8498ee23

I used these JSON options to perform the tests on ParagraphVectors infervectors:
    "paragraphVectorConfiguration": {
    "leaningRate":0.01,
    "minLearningRate" : 0.0005,
    "batchSize" : 500,
    "epochs" : 1,
    "trainWordVectors": true,
    "layerSize" : 50,
    "language" : "",
    "windowSize" : 10,
    "iterations" : 5,
    "minWordFrequency" : 2,
    "sampling" : 0.0001
  },

Thanks in advance Raver119 ;-)

**Comment by raver119** [comment]
Fix applied, merge incoming
