### ISSUE TITLE
pls add AtrousConvolution to dl4J and(or) add AtrousConvolution2D to imported layers from keras

### ISSUE THREAD

**Issue by Apostol77794** [deeplearning4j/deeplearning4j#2950]
Hello. I'm trying to import a model from ssd https://github.com/rykov8/ssd_keras Keras and facing a problem. In dl4j no AtrousConvolution2D https://keras.io/layers/convolutional/#atrousconvolution2d . Implement it please in dl4j and in keras imports.

**Comment by turambar** [comment]
@Apostol77794 Got it! This is on our radar now. @AlexDBlack FYI.

**Comment by kmotohas** [comment]
Hello. I'd like to use SSD on DL4J too. Any progress on this topic?

**Comment by turambar** [comment]
Reminder: we need to add a DL4J implementation of this layer before we can import it from Keras. So perhaps not @maxpumperla's purview?

**Comment by maxpumperla** [comment]
as a side note: atrous conv layers have been deprecated in keras 2 (dilation now happens as additional argument through regular conv layers).

@AlexDBlack @turambar at some point we should discuss how to go about this. see #3413 for this as well

**Comment by maxpumperla** [comment]
Since #3922 has been merged, we can next include this in model import. @Apostol77794 will let you know once it's done.

**Comment by maxpumperla** [comment]
#3938
