### ISSUE TITLE
Performance problem when doing word embedding with Nd4j

### ISSUE THREAD

**Issue by harperjiang** [deeplearning4j/deeplearning4j#2952]
I have a large text corpus and a word embedding matrix. For each word I obtain an integer index and use that index to fetch a vector from the matrix. I then combine each batch of the fetched vectors as a matrix and do some computations. I use Nd4j.get(INDArrayIndex...) and Nd4j.create(List<INDArray>) to do the fetch and combine work. 

However, the program runs much slower comparing to the numpy version. When I tried to optimize the program, I noticed significant amount of time is consumed by BaseNDArray.getDouble. @raver119 told me this is bad as it keeps doing scalar operations. May I have your suggestion what is the correct way to do my work? Thanks!

**Comment by agibsonccc** [comment]
Using anything in java is of course going to be a bad idea. A few things can speed this up, using operations directly:
https://github.com/deeplearning4j/nd4j/blob/aafbd0101b1a10a0d4dae1a2671895410a1708b2/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/ops/transforms/Transforms.java#L741-L741

Batching your operations also helps. Either way using for loops in java is just a bad idea. For the concatneation you should be using Nd4j.concat not doing that manually yourself.
https://github.com/deeplearning4j/nd4j/blob/b38c9df2067147949fcd60a5dcdb71030544a02c/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java#L5208-L5208

Could you post what your numpy version looks like? I mean nd4j is literally "numpy for java" so the same lessons apply (things should be vectorized)

What you are doing in java is the equivalent of doing it in python (with a for loop) if you are doing vectorized ops in python why not java? Seems a bit strange to me. I am closing this only to tell you to focus on using nd4j like you would numpy. Come back in to the channel if you need help mapping out the operations to their equivalents in in nd4j.

**Comment by harperjiang** [comment]
Thank you for the comments. I figured out that the BaseNDArray.broadcast takes significant amount of time. I switched to Broadcast Ops and the hotspots changed. I am still monitoring the performance improvement.

In numpy, I can do ``data[np.int32(idx),:]'' to use a NDArray as index. I thought in Nd4j the equivalent operation is first to convert the index array to int using NDArrayUtil.toInt and then INDArray.get with specified index. However in my experiments the Nd4j operation is much slower than numpy version (over 3x slower).

**Comment by raver119** [comment]
Show me please, what exactly you're doing, and what exactly is slower then numpy. As gist, please.

**Comment by harperjiang** [comment]
@raver119. I have created a gist [here](https://gist.github.com/harperjiang/363b7250c15ab726d48e8cde40c23544) with a README showing my problem, and minimal working example of both numpy / Nd4j version. Thank you!

**Comment by raver119** [comment]
I'm sorry, not sure how i can you help here. Your numpy code is somewhat vecorized, including rng stuff.

And your nd4j code is mix of jvm loops and just a bunch of vectorized ops. It's just not optimal code.

**Comment by raver119** [comment]
P.s. you might want to take a look into our LSTM impl:

https://github.com/deeplearning4j/deeplearning4j/blob/c08a5d054342f8aed1fae77364fa30751f08c643/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/layers/recurrent/GravesLSTM.java

https://github.com/deeplearning4j/deeplearning4j/blob/aa0960d63b4a0022e5031b7ba8860513f26d5763/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/layers/recurrent/LSTMHelpers.java

**Comment by raver119** [comment]
Also:
1) can i see your sbt config?
2) can i see how exactly you got 6 seconds timing on concat? It sounds a bit weird for me.
3) INDArray.addiRowVector(b)/addiColumnVector() can be used instead of manual op invocation.
4) Order of arrays matters for better performance on gemm and other ops.

**Comment by harperjiang** [comment]
@raver119  Thank you for your promptly feedback! I will study your LSTM impl as you suggested. For the other questions, please see my response below.

1. My actual code in numpy will read the input from a text file. It doesn't use rng. The rng in the MWE is just used to generate a sample input. 

2. I was using Intellij to do Scala and use default sbt config. I also rewrite the code using Java. Same result.

3. Please see [this gist](https://gist.github.com/harperjiang/5ae6d9efb0da22b4c23e0356ecf34c7a) for how I get 6 seconds on concat. In this example I did a matrix multiplication of A and B. Then concat the result with C. The operation is repeated 500 times. If I only do matrix mul, the time is ~450 ms. When I do both steps, the total time is ~6500 ms

**Comment by raver119** [comment]
2. Sbt config: i mean something, where i can see your dependencies you're using.

3. I've wrote simple test that does concat on non-cached arrays in cycle. Here's a [gist](https://gist.github.com/raver119/a21bd99c7dcfbb41d112a3012a573d36). As i see results lay around 100-150 microseconds per concat. Here's output [gist](https://gist.github.com/raver119/0d2298bcc44a31d4739a9314853fac40).

**Comment by raver119** [comment]
3.1 Same story for GEMM. Around 85 microseconds per GEMM call.

3.2 Obviously, F order speeds up both concat & GEMM. GEMM goes down to ~65 us, and concat to 85 us.


In other words: i don't see anything even close to time you report.

**Comment by raver119** [comment]
Please note: i'm talking about us/microseconds here. Not milliseconds.

**Comment by harperjiang** [comment]
This looks like a environment related issue. As when I run your gist on my machine, the majority running time is around 100us. This is the same as yours. However, I get many big numbers ( over 10000 us). Here's my output [gist](https://gist.github.com/harperjiang/992b22b1b66b9b1a5ba50a61f659675b). Do you mind sharing your hardware/software environment?

**Comment by raver119** [comment]
Sure, just casual i7 4790, non overclocked, ubuntu 16.04.
In both gemm and concat i have some fluctuations, but they are somewhat neglectable.

**Comment by harperjiang** [comment]
I compared you gist and mine, finally notice where the performance difference comes from. In your gist, 
you are doing mmul out of the loop. But if you move the mmul into the loop (don't count its time, of course), the performance of concat will become bad drastically. Here's the [gist](https://gist.github.com/harperjiang/847a1f7f02fd219553761ef06154c349) I use. I also attach the modification below.

Frankly speaking, I don't quite understand why moving the mmul operation into the loop will make the concat operation slow.


// Your code, which has ~100us average on concat. Do the mmul out of the loop
INDArray embed = fwdmap.mmul(c2v);
for (int x = 0; x < embeds.size(); x++) {
	long time1 = System.nanoTime();
	INDArray concat = Nd4j.concat(1, embeds.get(x), h0s.get(x));
	long time2 = System.nanoTime();

// My code. Do the mmul in the loop but doesn't count its time. The result is 5~10 ms
for (int x = 0; x < embeds.size(); x++) {
	embed = fwdmap.mmul(c2v);
	long time1 = System.nanoTime();
	INDArray concat = Nd4j.concat(1, embeds.get(x), h0s.get(x));
	long time2 = System.nanoTime();

**Comment by raver119** [comment]
Here's updated [test](https://gist.github.com/raver119/77c4d9950262a17622b75ce3fe5ae332) and [output](https://gist.github.com/raver119/923e504158ee75adf11d9088e4840af0).

**Comment by harperjiang** [comment]
Ah [here's](https://gist.github.com/harperjiang/a2ce22a515612fc49d7b4e82d179f601) what I get using the updated test code. You can see the GEMM part is the same as your result. But the CONCAT is indeed slow on my machine. I used two different machines (i7-5557, i5-3470) and all have similar results.
 
Do you think this could be caused by some configuration? I download nd4j through maven with no additional configuration.

**Comment by raver119** [comment]
Try to set env variable OMP_NUM_THREADS to 2, run once again, and show me results.

**Comment by harperjiang** [comment]
This is amazing! With the environment variable set to 2 I got exactly the same test result as yours - much much faster! Thank you so much!

If you don't mind, could you explain why the thread num should be set to 2? Cause I have 4 cores on both my i5 and i7. In addition, is there other similar environment variables I should pay attention to? Thank you!

**Comment by raver119** [comment]
You don't have 4 cores in your i5 and i7. In both cases you have only 2 physical cores + 2 HyperThreading "virtual cores". More details can be found here: https://deeplearning4j.org/native

**Comment by harperjiang** [comment]
Thanks!

**Comment by raver119** [comment]
Btw, thanks to @saudet with next release better cores detection routines become available & used: https://github.com/deeplearning4j/nd4j/blob/fe5259fb8835931d1ab7c64aa6a396a33738a834/nd4j-backends/nd4j-api-parent/nd4j-native-api/src/main/java/org/nd4j/nativeblas/NativeOpsHolder.java#L42-L42

So, on your system it should pick 2 as default value automatically
