### ISSUE TITLE
VGG-16 Web Demo

### ISSUE THREAD

**Issue by tomthetrainer** [deeplearning4j/deeplearning4j#2959]
Can we add an error when they submit an image that is too large?

Nginx returns

```
413 Request Entity Too Large

nginx/1.10.0 (Ubuntu)
```

If the javascript can catch the header and give a message, or if I need to do something to the server let me know

@crockpotveggies

**Comment by raver119** [comment]
... or just slightly reconfigure it to allow larger images?

**Comment by tomthetrainer** [comment]
looks like 2MB, I will update nginx to 10MB

**Comment by raver119** [comment]
Should be ok. Tomcat's default is 50 afaik, so only nginx should be updated.

**Comment by tomthetrainer** [comment]
Closing this, Updated to 10M
client_max_body_size 10M;
