### ISSUE TITLE
Question: Building a multi layer RNN for Doc Classification.

### ISSUE THREAD

**Issue by ammarshadiq** [deeplearning4j/deeplearning4j#2966]
Hi, Can anyone help me on some pointer how to construct a custom network on DL4J? My plan is for document classification with two layer RNN, the first layer represent sentence and would be fed every word representation on a sentence and the second layer represent the document by feeding the previous sentence representation to the RNN. 

The error propagation to calibrate the weight of the first layer would come from all the way after the second layer error is computed. The "general" idea of the network would look like the picture bellow.

![network-rep](https://cloud.githubusercontent.com/assets/596298/23546477/0138cc34-0000-11e7-9347-5c2e68c158f7.png)

My question is should i implement my own custom layer? would it be possible with DL4J to construct such a network configuration? and Which example should i really look into for implementing it?

**Comment by AlexDBlack** [comment]
I'll need think about this more, it's not something we support currently. This will require custom (or additional) functionality for both the layers and the data pipeline.

Some questions first: Is this from a particular paper? Word vectors or one-hot for the input?

**Comment by ammarshadiq** [comment]
I'm planning to use word vector as input, and no it's not from a particular paper.

**Comment by turambar** [comment]
@ammarshadiq @AlexDBlack Correct me if I'm wrong, but this looks like a dynamic computation graph ("dynamic" in [this sense](https://arxiv.org/abs/1701.03980), i.e., you have to generate a new computation graph for each example). Assuming so, this is all the rage in NLP academia these days (several NLP folks have told me that no one uses Theano or TF because of their limited support for dynamic graphs). Dunno how hard it would be to add in DL4J, but worth putting on the roadmap.

**Comment by AlexDBlack** [comment]
I was thinking we might be able to do this without anything really fancy.

Sequences are 3d input, sequences of sequences can be 4d. So we have data with shape along the lines of [minibatch, vectorSize, sentenceLength, documentLength].
If we use the (proposed to be implemented) time distributed layer, we can implement the lower half of the graph by representing the data as [minibatch x documentLength, vectorSize, sentenceLength] into the RNN, then reshaping the output back to the 4d format.

Finally, to feed the data into tho document/sentence RNN (top part of the graph): we'd need something equivalent to 'select last time step vertex', that instead operates on the 4d representation. It'd use the (3d) mask array to select the last time step of the output of the lower RNN activations, to build a standard 3d time series dataset with shape [minibatch, lowerRnnSize, documentLength]. It'd have to handle the conversion of the 3d masks to 2d masks also.

**Comment by turambar** [comment]
@alexdblack OK yeah, that works for this architecture! The "DistributedAlongAxis" functionality should be done relatively soon.

For the "get last time step" vertex, maybe do a more general version that grabs entry i dimension j based on constructor args i and j?

Also if the goal is to convert each sentence into a vector, we could also do a global pooling layer.

**Comment by turambar** [comment]
Also, yet another reason to consider an overhaul InputTypes.

**Comment by agibsonccc** [comment]
Would this be a reason to have InputVertexes rather than input types?

**Comment by AlexDBlack** [comment]
We have input vertices in compgraph, but they don't currently have any metadata assocated with them (they are just a name/label, essentially).
But it's not a bad idea: addInput("myInput", InputType.whatever(x,y,z)) might have some benefits.
