### ISSUE TITLE
Spark standalone training doesn't work without configuring default Hadoop FS

### ISSUE THREAD

**Issue by EdeMeijer** [deeplearning4j/deeplearning4j#2969]
With my new Spark setup using Spark standalone for clustering I was getting this null pointer exception:

```
java.lang.NullPointerException
	at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingMaster.processResults(ParameterAveragingTrainingMaster.java:773)
	at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingMaster.doIterationPathsMDS(ParameterAveragingTrainingMaster.java:723)
	at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingMaster.executeTrainingPathsMDSHelper(ParameterAveragingTrainingMaster.java:595)
	at org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingMaster.executeTrainingMDS(ParameterAveragingTrainingMaster.java:456)
	at org.deeplearning4j.spark.impl.graph.SparkComputationGraph.fitMultiDataSet(SparkComputationGraph.java:235)
```

Running the same training code in Spark local mode worked fine, so that was weird. After comparing the output of local and cluster (client) mode, I noticed this:
```
17/03/03 12:41:17 INFO mapred.FileInputFormat: Total input paths to process : 0
```
Whereas in local mode, this was a non-zero number. 

After some debugging I was able to pinpoint the problem to `ParameterAveragingTrainingMaster.exportIfRequiredMDS()`, where the result RDD of exported file path names was empty.

As it turned out, the reason the exporting didn't work was because I didn't configure the `spark.hadoop.fs.defaultFS` setting to point to my Hadoop instance. Because of this, the hadoop client defaulted to local file system mode for `rdd.saveAsTextFile()` which is used for exporting the RDD of paths. This doesn't work well in clustered mode, as the data parts are saved to the local file systems of random cluster nodes, but the following `sc.textFile()` call that reads back that RDD of paths only reads the drivers file system. Besides that, the actual data was also scattered across node file systems, so even if the paths could be read, the data would not be available for reading.

After configuring the hadoop default file system, the path RDD and the exported data sets were saved to and read from HDFS and everything worked as expected.

Now, besides this, nothing required me to specify the default hadoop file system because I was creating training data RDDs from fully qualified HDFS URIs. Not surprisingly, everything worked when I set the training masters rddTrainingApproach to Direct (my first attempt to figure out what was wrong). This bypasses the exporting.

I'm not sure what the solution is here. Hadoop is not required per se since you can run DL4j on Spark in local mode and in that case the local file system works fine. Also, users might choose to distribute their data files to all the worker nodes and use the local file system. In the latter case, the exporting functionality really doesn't make much sense though.

Actually, maybe you could do this: only allow Export mode if either the master is set to `local`, or if the Filesystem is HDFS. Otherwise, default to Direct mode and log a big fat warning that this is the case and how it can be solved by configuring a default hadoop fs.

**Comment by EdeMeijer** [comment]
As a side note, I was wondering why this didn't happen before, but back then I was using YARN. My guess is that YARN automatically configures the Hadoop fs through environment variables or something like that.

**Comment by agibsonccc** [comment]
@EdeMeijer usually there is a pre defined hadoop conf. I'm assuming your cluster already had that configured. YARN doesn't do that on its own.

**Comment by EdeMeijer** [comment]
@agibsonccc ah yes you're right there, I indeed had a Hadoop config on that YARN cluster. This time however, my driver runs in a Docker container in which I only installed Spark (so there's no Hadoop config) and I'm passing the base hdfs:// url as an environment variable to the driver app.

**Comment by agibsonccc** [comment]
Since you *usually* have to configure hdfs in some way *anyways* I would suggest just creating a set of files and maybe mounting them in the containers?

**Comment by EdeMeijer** [comment]
Sure, that's another solution. I just want to save the next poor soul from the same debugging session I went through. In fact, I'm already working on a PR, it's pretty simple stuff.

**Comment by EdeMeijer** [comment]
Closing since my PR is merged :)
