### ISSUE TITLE
Serializing Paragraph Vectors (Doc2Vec)

### ISSUE THREAD

**Issue by ml-tn** [deeplearning4j/deeplearning4j#297]
I am trying to generate paragraph embedding for my dataset using ParagraphVectors class.
Working with Word2Vec there's a WordVectorSerializer making possible to store the generated vectors in a file using the WordVectorSerializer.writeWordVectors method.
What's the equivalent for ParagraphVectors ?

**Comment by agibsonccc** [comment]
The way paragraphvectors works is the labels are just appended to the end of the lookup table for words. You can just use WordVectorSerializer all the same.
