### ISSUE TITLE
[Feature request] Add labels metadata

### ISSUE THREAD

**Issue by loretoparisi** [deeplearning4j/deeplearning4j#2987]
I'm building a **word2vec** and **doc2vec** model, where input data are documents that may belong to different types i.e. articles, blog, etc.
Everything works smoothly in the framework, and I get the output labels/distance from the model.
What it is missing is that for each label, I cannot add (or I do not know how) additional metadata, like a `type` field, that could be helpful, as post processing, to group labels (in this case by type) of Doc2Vec, when calculating top similarity or nearest, etc.

**Comment by raver119** [comment]
Are you speaking about LabelledDocument additional fields, or? Add some background please.

**Comment by loretoparisi** [comment]
@raver119 Yes, it could be this. By example, let's consider a blog post title, or a web page title, etc in a Doc2Vec, etc where now I'm using as labels the titles. In the output I cannot rely on these as keys, since they could collide, etc., also I would keep the labels (human readable), to be explored in a tensorboard PCA model, so only (I assume) additional fields could help.

**Comment by raver119** [comment]
I still don't get the problem. If you just want to attach some fields to individual tokens or labels - why not just use SeqVec directly? It takes any &lt;T extends SequenceElement&gt; so you can add as fields as you want.

**Comment by loretoparisi** [comment]
@raver119 I think that `SeqVec` could work, I will check it, and close this if it is solved. Thanks for now.

**Comment by silvioOlivastri** [comment]
So, should I create three new classes? For Example MyWord2Vec, MyVocabWord and MyParagraphVectors:

```
public class MyParagraphVectors extends MyWord2Vec {
...
}

public class MyWord2Vec extends SequenceVectors<MyVocabWord> {
...
}

public class VocabWord extends SequenceElement implements Serializable {
...

   public void setMetadata(List<String> metadata) {
            this.metadata = metadata;
   }

   public List<String> getMetadata() {
           return this.metadata;
   }
}
```

If yes, then where I should call `setMetadata(...)` to insert my data from my custom iterator function?

**Comment by raver119** [comment]
You don't have to create MyParaVec and MyWord2Vec, just MyVocabWord

And then use SequenceVectors&lt;MyVocabWord&gt;

**Comment by silvioOlivastri** [comment]
Ok, good, but unfortunately I have this problem:

```
// Iterator
        LabelAwareSentenceIterator labelAwareSentenceIterator = new ...

        // Tokenizer
        TokenizerFactory tokenizerFactory = new DefaultTokenizerFactory();
        tokenizerFactory.setTokenPreProcessor(new Preprocessor());
        boolean allowParallelTokenization = true;

        // Transform
        SentenceTransformer transformer = (new SentenceTransformer.Builder())
                .iterator(labelAwareSentenceIterator).tokenizerFactory(tokenizerFactory)
                .allowMultithreading(allowParallelTokenization)
                .build();
        SequenceIterator<MyVocab> sequenceIterator = new AbstractSequenceIterator.Builder(transformer).build();

        // Default Configuration
        this.configuration = new VectorsConfiguration();
        this.configuration.setAllowParallelTokenization(true);
        this.configuration.setLayersSize(100);
        this.configuration.setSequenceLearningAlgorithm("org.deeplearning4j.models.embeddings.learning.impl.sequence.DBOW");

        log.info("Pre-building...");
        this.sequenceVectors = new SequenceVectors.Builder<MyVocab>(this.configuration)
                .trainSequencesRepresentation(true)
                .iterate(sequenceIterator)
                .build();

        this.configuration = this.sequenceVectors.getConfiguration();

        this.sequenceVectors.fit();

        VocabCache<MyVocab> vocab = this.sequenceVectors.getVocab();

        System.out.println(vocab.numWords());
        System.out.println(vocab.tokenFor("you").getWord());
```

Error:

```
Exception in thread "main" java.lang.ClassCastException: org.deeplearning4j.models.word2vec.VocabWord cannot be cast to myEmbedding.MyVocab
	at myEmbedding.Embedding.<init>(Embedding.java:91)
	at myEmbedding.Embedding.main(Embedding.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

MyVocab class is:

```
public class MyVocab extends SequenceElement {
    private String word;
    protected Long vocabId;
    protected Long affinityId;

    
    public static MyVocab none() {
        return new MyVocab(0.0D, "none");
    }

    public MyVocab(double wordFrequency, String word) {
        if(word != null && !word.isEmpty()) {
            this.word = word;
            this.elementFrequency.set(wordFrequency);
        } else {
            throw new IllegalArgumentException("Word must not be null or empty");
        }
    }

    public MyVocab() {
    }

    @Override
    public String getLabel() {
        return this.word;
    }

    public String getWord() {
        return this.word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public boolean equals(Object o) {
        if(this == o) {
            return true;
        } else if(!(o instanceof MyVocab)) {
            return false;
        } else {
            MyVocab myVocab = (MyVocab)o;
            return this.word == null?myVocab.word == null:this.word.equals(myVocab.getWord());
        }
    }

    public int hashCode() {
        int result = this.word == null?0:this.word.hashCode();
        return result;
    }

    public String toString() {
        return "MyVocab{wordFrequency=" + this.elementFrequency + ", index=" + this.index + ", word=\'" + this.word + '\'' + ", codeLength=" + this.codeLength + '}';
    }

    @Override
    public String toJSON() {
        ObjectMapper mapper = mapper();

        try {
            return mapper.writeValueAsString(this);
        } catch (JsonProcessingException var3) {
            throw new RuntimeException(var3);
        }
    }

    public Long getVocabId() {
        return this.vocabId;
    }

    public void setVocabId(Long vocabId) {
        this.vocabId = vocabId;
    }

    public Long getAffinityId() {
        return this.affinityId;
    }

    public void setAffinityId(Long affinityId) {
        this.affinityId = affinityId;
    }

}
```

**Comment by raver119** [comment]
Your exception is thrown here: 	at myEmbedding.Embedding.<init>(Embedding.java:91)
Can you show me what happens on that line 91?

**Comment by silvioOlivastri** [comment]
Sorry, the line 91 is:

`System.out.println(vocab.tokenFor("you").getWord());`

**Comment by raver119** [comment]
No, it won't work this way.

SentenceTransformer transformer = (new SentenceTransformer.Builder())
                .iterator(labelAwareSentenceIterator).tokenizerFactory(tokenizerFactory)
                .allowMultithreading(allowParallelTokenization)
                .build();


This thing will produce VocabWord internally during tokenization.

**Comment by raver119** [comment]
Hypothetically i can provide generic support for SentenceTransformer, but i'm not sure if that'll really help. You'll have to specify something like MyVocabWordFactory that'll be creating MyVocabWords.

But it might be significantly easier for you to just provide your own Iterable&lt;Sequence&lt;MyVocabWord&gt;&gt;

**Comment by silvioOlivastri** [comment]
Ok, thank you very much!

I suppose that I create MySequenceIterator directly instead of using my old LabelAwareSentenceIterator for take my source data and apply the tokenizer inside.

```
public class MySequenceIterator implements SequenceIterator<MyVocab> {

    @Override
    public boolean hasMoreSequences() {
        return false;
    }

    @Override
    public Sequence<MyVocab> nextSequence() {
        return null;
    }

    @Override
    public void reset() {

    }
}
```

**Comment by silvioOlivastri** [comment]
Ok, thank you very much!

I had to create three new classes: 

```
public class MySentenceTransformer implements SequenceTransformer<MyVocab, String>, Iterable<Sequence<MyVocab>>  { ... }

public class MyBasicTransformerIterator implements Iterator<Sequence<MyVocab>> { ... }

public class ParallelTransformerIterator implements Iterator<Sequence<MyVocab>> { ... }

```

Now all works well :)

Can I create MySequenceIterator directly instead of using my old LabelAwareSentenceIterator for take my source data and apply the tokenizer inside? Or I must use the Transformers class as I did?

For example:

```
public class MySequenceIterator implements SequenceIterator<MyVocab> {

    @Override
    public boolean hasMoreSequences() {
        return false;
    }

    @Override
    public Sequence<MyVocab> nextSequence() {
        return null;
    }

    @Override
    public void reset() {

    }
}
```

Ps: Thank you so much for all the help, it's very important for me!

**Comment by raver119** [comment]
Transformer is just an abstraction that's used for graphs & raw text. Basically you can bass any Iterable&lt;Sequence&lt;MyVocabWord&gt;&gt; right into AbstractSequenceIterator builder, and it'll work for you.
