### ISSUE TITLE
Error trying to import the Google News Corpus Model

### ISSUE THREAD

**Issue by hkz1000** [deeplearning4j/deeplearning4j#2989]
Here is my code:
 File gModel = new File("GoogleNews-vectors-negative300.bin.gz");
 Word2Vec vec = WordVectorSerializer.readWord2VecModel(gModel);
 Collection<String> lst = vec.wordsNearest("clock", 5);
 System.out.println("5 Words closest : " + lst);

I am getting an error with the second line:
Exception in thread "main" java.lang.RuntimeException: Unable to guess input file format.

**Comment by raver119** [comment]
Provide absolute path for model. 99.9% chances you don't have that file in your "current" folder.

**Comment by hkz1000** [comment]
I replaced the first line with:
String filePath = new ClassPathResource("GoogleNews-vectors-negative300.bin.gz").getFile().getAbsolutePath();
File gModel = new File(filePath);

and now I get the error: "Resource 'GoogleNews-vectors-negative300.bin.gz' cannot be found."

which is weird since the bin.gz file is in the same directory as the code

**Comment by raver119** [comment]
Just to what i've told you to do: provide absolute path to file. Do not use ClassPathResource, do not set relative path. Just provide absolute path.
