### ISSUE TITLE
Update mnist downloader to use a mirrored download location

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2990]
If possible, we should be hosting MNIST on a location we control (Azure, AWS etc).
The default hosting location is currently (and has been before, in the past) inaccessable: http://yann.lecun.com/exdb/mnist/

Perhaps we even want to give users the option to specify the download location (system property) for future-proofing?

Workaround:
Use: https://web.archive.org/web/20160117040036/http://yann.lecun.com/exdb/mnist/
Download the 4 files (.gz) to your home directory's /MNIST folder and unzip them

**Comment by agibsonccc** [comment]
archive.org could work here.

**Comment by saudet** [comment]
GitHub probably has more bandwidth though, especially in Asia. We might be able to host it with the releases feature https://github.com/deeplearning4j/dl4j-examples/releases ?
