### ISSUE TITLE
Output page contains obsolete code

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#2991]
https://deeplearning4j.org/output

The code block at the above link contains very old code (DoubleMatrix, getFirst etc haven't been part of the API for a long time).

**Comment by tomthetrainer** [comment]
Patched this page so the code is at least up to date and an earlier paragraph is a little clearer. 

Closing for now, evaluation should be a feature page with full details and focus just on evaluation class
