### ISSUE TITLE
OutOfMemoryError after thousands of iterations

### ISSUE THREAD

**Issue by dwr-psandhu** [deeplearning4j/deeplearning4j#2995]
I am getting OutOfMemoryError after thousands of iterations. The gist for all the files is here 
https://gist.github.com/dwr-psandhu/3cfceea505e31a99ab8d4672d1babc96

The training proceeds for many epochs till this error happens.

**Comment by raver119** [comment]
There's at least 1 structure that HAS to grow over time: InMemoryStatsStorage. It just has to grow while you keep rolling. So it can be the root of your problem hypothetically.

**Comment by dwr-psandhu** [comment]
Noted. Before you spend too much on this. I am running it under a profiler (jvisualvm) as I suspect it is also because I am opening windows that probably use up more and more memory as time goes on.

**Comment by raver119** [comment]
Are you opening NEW windows using java, and not closing them?

**Comment by dwr-psandhu** [comment]
Yes. And so it might be related to those.

**Comment by raver119** [comment]
Might? No, It's _definitely_ second memory "leak" you have there. Windows are not free, neither StatsListener is :(

I'm closing this issue for now, but please, if you'll find any more evidences without these 2 things - please let me know ASAP.
