### ISSUE TITLE
MNIST is not available at its usual location anymore, failing some tests

### ISSUE THREAD

**Issue by huitseeker** [deeplearning4j/deeplearning4j#2996]
See also :
https://github.com/tensorflow/tensorflow/issues/209
https://github.com/Lasagne/Lasagne/issues/587

We download MNIST in `MnistFetcher`, this results in the error:

```
ava.lang.RuntimeException: java.io.IOException: Could not download /exdb/mnist/train-images-idx3-ubyte.gz
properly despite trying 3 times, check your connection.
```

**Comment by raver119** [comment]
Working on this now.

**Comment by raver119** [comment]
I've uploaded corresponding files to benchmark azure instance, and updated MnistFetcher.

**Comment by huitseeker** [comment]
See also https://github.com/deeplearning4j/deeplearning4j/issues/2990
