### ISSUE TITLE
Setting CUDA grid size creates NaNs

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#3000]
Setting CUDA grid size to 512 degrades network scores into NaNs. Using CUDA 8 on master branch.

Usage: `CudaEnvironment.getInstance().getConfiguration().setMaximumGridSize(cudaGridSize)`

Result:
```
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 0 is 8.521245163904679
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 1 is 8.438281933109966
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 2 is NaN
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 3 is NaN
```

If grid size is larger than 1024, network performs normally.

**Comment by raver119** [comment]
In other words, something goes wrong, if number of blocks is too small.

**Comment by raver119** [comment]
Apparently, it's not Col2Im/Im2Col, not a Reduce/IndexReduce and not a Broadcast.

**Comment by raver119** [comment]
After investigation we have strong feeling it's just numerical underflow/overflow, and grid size is just booster here.  Using DOUBLE datatype fixes issue.
