### ISSUE TITLE
Please add the layer name and/or index to exceptions

### ISSUE THREAD

**Issue by jadedfire** [deeplearning4j/deeplearning4j#3002]
If the context of the exception allows, it would help greatly during debugging if the layer name or id was known from the exception.

**Comment by AlexDBlack** [comment]
I did a pass on this since the last release (along with adding default layer names for multilayernetwork if not set) - was there a specific location you ran into this for, so I can double check it?

**Comment by jadedfire** [comment]
not sure what you are asking for, perhaps my request was too vague. what i was requesting is that whenever an exception is thrown, if the layer name or id is available from within the context of the catch(), that said name/id be included in the exception message.

**Comment by jadedfire** [comment]
if you are asking for a specific code location where this could potentially be recommended, perhaps in BaseLayer.preOutput() where the if(input.rank() != 2 || input.columns() != W.rows() ) results in an exception. without digging, i am not sure if the layer name/id is available from that context however.

**Comment by AlexDBlack** [comment]
I had a quick look through the code. There have definitely been improvements since the last release, but there's still a number of exceptions without this info. I'll leave this open, and we'll take a look at some point in the (hopefully near) future.

**Comment by AlexDBlack** [comment]
Layer names and indexes are added to all layer exceptions here: https://github.com/deeplearning4j/deeplearning4j/pull/3364/files
