### ISSUE TITLE
Dl4j website css

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#3004]
The header menu doesn't work well when the window is moved. There is a lot of overlapping text.
This was chrome on mac.

**Comment by slinlee** [comment]
The navbar stays pushed down from the top after scrolling. Only applies to tabletview and smaller

<img width="522" alt="screenshot 2017-03-09 16 36 43" src="https://cloud.githubusercontent.com/assets/1197406/23777011/a40395f8-04e6-11e7-8f1a-3edaaedeaf21.png">

**Comment by slinlee** [comment]
Fixed by #3056
