### ISSUE TITLE
Review updater design and add support for custom updaters

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3005]
This would allow users to experiment with things like this: https://github.com/deeplearning4j/nd4j/issues/1692

Some steps required to add this:
- custom updater support in the layer configuration classes
- handle JSON (in NeuralNetConfiguration) for custom updaters
- Modify LayerUpdater updater initialization https://github.com/deeplearning4j/deeplearning4j/blob/1f8af820c29cc5567a2c5eaa290f094c4d1492a7/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/updater/LayerUpdater.java#L254

Edit: Another thing I would like to do is  break the configuration for updaters out into classes.
So, instead of something like ```updater(Updater.ADAM).adamMeanDecay(...)...``` we do either ```.updater(new Adam.builder().meanDecay(...).build())``` or ```.updater(new Adam(mean,var))```
This type of design also gives us block updater support for custom updaters (i.e., updater combining for my recent changes).

My concern here is that with the current design as we add more and more updaters, we end up with a situation where the hyperparameters for all other updaters are:
- Present on all of the builder patterns
- Always present in the JSON representation of the network
even when they are being used.
For example, adding the Eve updater (https://arxiv.org/pdf/1611.01505v1.pdf) will add 4 (or 6) new hyperparameters that will always be present (methods/json) even when using any other updater.

**Comment by crockpotveggies** [comment]
I agree with moving the params to the updater class itself. This is something that often affects me when trying to make the updater configurable in a project.

**Comment by AlexDBlack** [comment]
Implemented here: https://github.com/deeplearning4j/deeplearning4j/pull/3373
Refactoring complete and custom updaters are now supported.
