### ISSUE TITLE
vectorizer in numWordsEncountered overflow

### ISSUE THREAD

**Issue by mzhai2** [deeplearning4j/deeplearning4j#302]
totalWords = vectorizer.numWordsEncountered();
        if(totalWords < 1)
            throw new IllegalStateException("Unable to train, total words less than 1");
totalWords is long but Lucene invertedIndex totalWords() returns int from lucene. Need to use long to store more than 2B words. Works if you just change Lucene's int to a long and create a new method returning that long in invertedIndex.

**Comment by agibsonccc** [comment]
Mind submitting a PR?

**Comment by mzhai2** [comment]
submitted
