### ISSUE TITLE
Review (Sequence)RecordReaderDataSetIterator for sequence classification

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3025]
RecordReaderDataSetIterator: can't handle sequences (SequenceRecordReader)
SequenceRecordReaderDataSetIterator: *can* handle sequences, but it's not really possible to use it with non-sequence labels.

For example: suppose I have a time series input, and want to use global pooling + a standard OutputLayer

Edit: it should be noted that RecordReaderMultiDataSetIterator can handle this - but produces MultiDataSets...

**Comment by raver119** [comment]
Is this issue safe to close now?
