### ISSUE TITLE
ParagraphVectors.inferVectors generate null vectors

### ISSUE THREAD

**Issue by ReggieYang** [deeplearning4j/deeplearning4j#3027]
I was running the example code at https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/paragraphvectors/ParagraphVectorsInferenceExample.java, but the inference vector I get was a null vector. The file simple.pv was found correctly because I can get wordVectors from the model. However I can not infer the paragraph vector for given text. Also, the similarity of different text in the example code is always 1.0.

Output on windows 7, Intelli Idea, java 1.8, java code in the example:
 o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
	o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 4
	o.d.m.s.SequenceVectors - Building learning algorithms:
	o.d.m.s.SequenceVectors -           building SequenceLearningAlgorithm: [PV-DBOW]
	o.d.m.s.SequenceVectors -           building ElementsLearningAlgorithm: [SkipGram]
	o.d.e.n.p.ParagraphVectorsInferenceExample - Cosine similarity A/B: 1.0
	o.d.e.n.p.ParagraphVectorsInferenceExample - Cosine similarity A/A2: 1.0

**Comment by raver119** [comment]
You get null because you're passing text which has no words from vocab.

And SkipGram issue was fixed recently.
