### ISSUE TITLE
MultiLayerConfiguration issues (input pre-processors)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#303]
Looking at the MultiLayerConfiguration class: https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/conf/MultiLayerConfiguration.java

Some things don't seem correct to me, mainly regarding the inputPreProcessors field (Map<Integer,InputPreProcessor>). Though there may be legitimate design reasons for (at least some of) the current implementation that I'm not aware of. If so, apologies and please disregard.
 
- hashCode() does not consider inputPreProcessors map, but does include processors map (i.e., OutputPreProcessor map). Should consider both?

- toString(): as above (i.e., no inputPreProcessors map contents in String output)

- equals(): does not consider either input or output preprocessor maps. Networks with different input/output processing should not be considered equal? Also see hashCode(): present implementation allows network configurations with different output preprocessors to be equal (according to equals() method), but have different hash codes, violating general contract for hashCode method).

- No setter for inputPreProcessors map (even though an analogous setter for output preprocessors exists: setProcessors(Map))

Also note that MultiLayerConfiguration.Builder .toString(), equals() and .hashCode() methods seem to exhibit the same issues.

**Comment by AlexDBlack** [comment]
Two other really minor issues, this time with NeuralNetConfiguration. (seems too small to open a new issue for, so I'll just put it here):

In copy constructor, lines 251 and 267 are identical: "this.visibleUnit = neuralNetConfiguration.visibleUnit;"
Also lines 252 and 277: "this.hiddenUnit = neuralNetConfiguration.hiddenUnit;"

**Comment by AlexDBlack** [comment]
Another set of problems with the same copy constructor NeuralNetConfiguration(NeuralNetConfiguration neuralNetConfiguration):
This constructor does not copy/set the following fields: stepFunction, variables, kernel, l1, featureMapSize

**Comment by AlexDBlack** [comment]
Also: NeuralNetConfiguration.variables() and NeuralNetConfiguration.getVariables() are identical, except for name.

**Comment by AlexDBlack** [comment]
Also: NeuralNetConfiguration.Builder.resetAdaGradIterations() and NeuralNetConfiguration.Builder.adagradResetIterations() -> identical. Plus both are called in Builder.clone() method.
And NeuralNetConfiguration.Builder.clone() calls useAdaGrad() twice, does not call/set: kernel, k, corruptionLevel.

**Comment by agibsonccc** [comment]
Thanks for looking through this: 

I've changed the copy constructor to using reflection. This won't happen again. I've suitably changed the other Builder to do this as well.

Re: variables. You're right. This was more of a code generation oversight.

In the MultiLayerConfiguration I've fixed the setter issue.
