### ISSUE TITLE
[Feature request] Obtain Doc2Vec/ParagraphVector document embedding (without specifying labels)

### ISSUE THREAD

**Issue by bartdp1** [deeplearning4j/deeplearning4j#3030]
I have a set of documents for which i want to obtain a vector embedding, one vector for each document, after which i would like to cluster them. All of this in unsupervised fashion; the documents are not labeled on beforehand. 

Preferablly the embedding is found using the PV-DM algorithm from the corresponding Quoc, Mikolov paper: https://cs.stanford.edu/~quocle/paragraph_vector.pdf

From the documentation of ParagraphVectors, i found that labels are required. It would be an addition to add the functionality to obtain the embedding without classifiying. 

PS: Maybe this is already possible with the current implementation (perhaps using the SequenceVector class?) However, i was unable to find any documentation on this class. If this is the case, a push in the right direction would be greatly appreciated.

**Comment by raver119** [comment]
Labels are not required. If you don't have any - it's technically just inference task, over existing word vectors.

**Comment by bartdp1** [comment]
Shouldn't Document vectors and Word vectors be determined simultaneously in the training phase, for the documents in the training set?

**Comment by bartdp1** [comment]
Sorry, but your comment still somewhat confuses me. It would be greatly appreciated if you could comment on the following question:
Does the current Doc2Vec implementation determines Document vectors and Word vectors simultaneously in the training phase? Or does it detetermines Word vectors with Word2Vec first, and then inferences Document vectors for "training documents"?

**Comment by raver119** [comment]
If you don't provide labels, they will be generated dynamically using LabelsSource, one label per document. I.e. DOC_0, DOC_1 and so on.

**Comment by bartdp1** [comment]
I have no interest in some sort of label, only in the vector representation of the Documents.

**Comment by raver119** [comment]
Then it'll be inferrence over existing w2v model. I don't see any other options, if you don't have any labels before training.

**Comment by bartdp1** [comment]
Note that the algorithm in the original paper determines Paragraph vectors and word vectors simultaneously, not first w2v and then paragraph vectors.

**Comment by raver119** [comment]
Great. Then provide algorithm with labels, and you'll have it exactly as explained in that paper.

**Comment by luckaB** [comment]
Hi @bartdp1,
I know this issue is over a year old now, but I got here because I am dealing with exactly the same problem. Did you manage to solve it somehow? If so, could you please tell me how? I am asking beacuse I don't think you and raver119 understood each other very well, so I don't consider your question to be answered here :)

**Comment by raver119** [comment]
Please do not post in old closed topics. "Exactly the same problem" isn't telling us anything. If you have any problem - just file an issue, and we'll try to help you.
