### ISSUE TITLE
CudaConstantHandler excessive object creation

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#3031]
Investigating an issue I originally thought was UI-related but I am unsure if this is a general memory leak with cuda management itself. BaseStatsListener.getHistogram:744 will excessively call this operation:

```
org.nd4j.linalg.api.ops.impl.transforms.Histogram hOp =
    new org.nd4j.linalg.api.ops.impl.transforms.Histogram(entry.getValue(), nBins);
Nd4j.getExecutioner().exec(hOp);
```

The problem is that over time (say 40,000 iterations) this will result in excessive object creation and performance will degrade to 1/6 of original iteration throughput.

These calls result in the problem:

```
CudaGridExecutioner.java:215 org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.invoke(TransformOp) 47 2056 516721704
CudaExecutioner.java:1259 org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.validateDataType(DataBuffer$Type, Op) 35 1544 516692048
DefaultOpExecutioner.java:498 org.nd4j.linalg.api.ops.BaseOp.extraArgsDataBuff() 35 1544 516692048
...
...
ProtectedCudaConstantHandler.java:320 org.nd4j.jita.constant.ProtectedCudaConstantHandler.moveToConstantSpace(DataBuffer) 5 241 516634176
ProtectedCudaConstantHandler.java:128 org.nd4j.jita.constant.ConstantProtector.persistDataBuffer(DataBuffer) 5 227 516633840
ConstantProtector.java:44 <...> java.util.concurrent.CopyOnWriteArrayList.add(Object) 5 227 516633840
```

![screen shot 2017-03-13 at 10 12 23 am](https://cloud.githubusercontent.com/assets/1445295/23866759/05f9f4ee-07d7-11e7-8017-61a3cc2e5aaa.png)

@raver119 any ideas here?

**Comment by raver119** [comment]
So, no. 227 objects/500mb in cache doesn't sound like something catastrophic for me. However, quite interesting what are those objects.

I'm more interested in those 19888 objects in histograms.

**Comment by raver119** [comment]
P.s. idea is simple: irrelevant. In next major release we should get rid of GC as much as possible.

**Comment by raver119** [comment]
Re: GC https://github.com/deeplearning4j/nd4j/pull/1731

Re: excessive object creation can't be confirmed.

**Comment by nbondoux** [comment]
I also object excessive object creation in constant buffer. I don't have very deep knowledge of nd4j's code, but tried to investigate. It seems that any cuda operation creating a scalar (like for instance the score calculation in Deeplearnin4j's SGD) will try to create a new entry in the constant cache:

In CudaGridExcecutioner, there is this code:

   if (ret.isScalar()) {
            float res = nativeOps.execReduceScalarFloat(xShapeInfoHostPointer, op.opNum(), (FloatPointer) x,
           (IntPointer) xShapeInfo, (FloatPointer) extraArgs);
           AtomicAllocator.getInstance().registerAction(context, op.z(), op.x(), op.y());
           ret.assign(res);
           op.setFinalResult(res);
         }

the assign(res) line here will do a ScalarOp which will itself try to register a new constant in the cache, thus a memory leak.

**Comment by raver119** [comment]
Doesn't sound realistic really:

Here's corresponding code: https://github.com/deeplearning4j/nd4j/blob/510a97389c52ac2eec3fbda71249b8c195428091/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/linalg/cpu/nativecpu/cache/ConstantBuffersCache.java#L18-L35

Basically we only allow 100 cached objects, which is enough for average nn.

**Comment by raver119** [comment]
However, it should be good idea to use constant memory counter instead of fixed number.

**Comment by nbondoux** [comment]
I'm talking of a caching done in the jita backend, not in native cpu backend. In ProtectedCudaConstantHandler, caches are simple maps without any maximum defined.

**Comment by raver119** [comment]
Hm. Good catch. Logic there is a bit different. Fix incoming.

**Comment by raver119** [comment]
Fixed here: https://github.com/deeplearning4j/nd4j/pull/1977

Now it only stores references that are possible to fit into device constant memory. So, 48KB in general case.

**Comment by raver119** [comment]
Thanks for highlighting!
