### ISSUE TITLE
[Feature Request] Allowing word2vec model training without using SentenceIterator. 

### ISSUE THREAD

**Issue by ambarishpande** [deeplearning4j/deeplearning4j#3032]
I am trying to get data from hdfs line by line and tokenizing it separately. Now I have a list of tokenized words which I would like to feed to word2vec for training. Current API does not allow a word2vec.train(ArrayList<String> words) if I get such a method I would be call the train method multiple times for different words.

I only have a single line at time and not the entire corpus.

**Comment by raver119** [comment]
Which word2vec impl we're speaking about right now? SentenceIterator stuff is for standalone. And it's possible to train from pre-tokenized words, but w2v mechanics assumes, that you'll do at least 2 passes over training corpus: once to build vocabulary, and other one to train model.

**Comment by ambarishpande** [comment]
I am talking about standalone implementation.

**Comment by raver119** [comment]
So, can you provide, say, java Iterable impl? If yes, then you can use this approach immediately using SequenceVectors generic class.

**Comment by ambarishpande** [comment]
I have all the  words in sentence with me in a ArrayList of strings. Can I send its iterator to the word2vec implementation?

**Comment by raver119** [comment]
Check out this example: https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/sequencevectors/SequenceVectorsTextExample.java

Basically you'll use your iterable instead of transformer. All you need is to wrap your individual tokens into VocabWord.

**Comment by ambarishpande** [comment]
Oh I am sorry. Got caught up in other activities. I'll try that. I think that will solve my problem.
