### ISSUE TITLE
how to read data from hdfs in csv format, then train in dl4j with spark? 

### ISSUE THREAD

**Issue by neverjoe** [deeplearning4j/deeplearning4j#3036]
how to read data from hdfs in csv format, then train in dl4j with spark? Anyone can give me a example?

**Comment by wmeddie** [comment]
Please see the BasicDataVec example: https://github.com/deeplearning4j/dl4j-examples/blob/master/datavec-examples/src/main/java/org/datavec/transform/basic/BasicDataVecExample.java

**Comment by neverjoe** [comment]
after parser the csv data in hdfs, how to transform to JavaRDD<DataSet>?

**Comment by wmeddie** [comment]
That is just plain spark:
`
JavaRDD<String> stringData = sc.textFile(directory);
`
The DataVec magic starts at Line 148 

https://github.com/deeplearning4j/dl4j-examples/blob/master/datavec-examples/src/main/java/org/datavec/transform/basic/BasicDataVecExample.java#L148

**Comment by ustbxyls** [comment]
after parser the csv data in hdfs, how to transform to JavaRDD<DataSet>?

is there any example for this ?!
