### ISSUE TITLE
GPU not utilized efficiently during training

### ISSUE THREAD

**Issue by sorensf** [deeplearning4j/deeplearning4j#3038]
I'm experiencing a couple of issues getting DL4j to utilize all of my GPU.

I'm running the AnimalsClassification example with some minor changes, and a larger dataset obtained by copying the existing images a couple of times (for a total of 2438 images). The run() method in the following code is run with the vm arguments "-ea -Xms16000m -Xmx32000m -XX:+UseG1GC":
https://gist.github.com/sorensf/7309f2ee9811c6b1d462e037ad123fd5

I ran it with all three models (one of them a custom one that is my main interest). For all of the models the GPU did not experience much load, in particular for the custom model.

My initial assumption was that reading from disk and converting the images might be the bottleneck, so I tried to preload all datasets in memory (using DataSetIteratorInMemory from https://gist.github.com/sorensf/7309f2ee9811c6b1d462e037ad123fd5) but it did not have an impact on the performance.

Is there something I am missing to make it perform better?

On a side note I could not run the custom model with the same batchsize as the other models as I got an out of memory exception from CUDA, which seems a bit odd as the average memory used is quite low.

In summary the issues I am seeing is:
1) The GPU does not seem to be saturated with load.
2) The custom model I have made seems even more erratic in the load than the standard models.
3) The custom model sporadically uses significantly more memory the the average.

I have included graphs as well as log files from GPU-Z, as well as the output from each of the runs.

LeNet model:
![lenet graph](https://cloud.githubusercontent.com/assets/26085887/23894837/ed8697dc-08a3-11e7-8baa-e5112a4a6b6a.jpg)

AlexNet model:
![alexnet graph](https://cloud.githubusercontent.com/assets/26085887/23894835/ed5d7406-08a3-11e7-8bf8-ad0fab468053.jpg)

Custom model (batchsize 32) :
![custom-32 graph](https://cloud.githubusercontent.com/assets/26085887/23894834/ed5afc58-08a3-11e7-9ec4-f00e4e6fcf4c.jpg)

Custom model (batchsize 64) :
![custom-64 graph](https://cloud.githubusercontent.com/assets/26085887/23894836/ed7067c8-08a3-11e7-9981-284aafb52330.jpg)

[pom.xml as txt](https://github.com/deeplearning4j/deeplearning4j/files/847352/pom.xml.txt)

[Lenet out.txt](https://github.com/deeplearning4j/deeplearning4j/files/840824/Lenet.out.txt)
[Alexnet out.txt](https://github.com/deeplearning4j/deeplearning4j/files/840819/Alexnet.out.txt)
[Custom-32 out.txt](https://github.com/deeplearning4j/deeplearning4j/files/840822/Custom-32.out.txt)
[Custom-64 out.txt](https://github.com/deeplearning4j/deeplearning4j/files/840823/Custom-64.out.txt)
[Lenet out with performance listener.txt](https://github.com/deeplearning4j/deeplearning4j/files/847280/Lenet.out.with.performance.listener.txt)

[Lenet GPU-Z Sensor Log.txt](https://github.com/deeplearning4j/deeplearning4j/files/840821/Lenet.GPU-Z.Sensor.Log.txt)
[Alexnet GPU-Z Sensor Log.txt](https://github.com/deeplearning4j/deeplearning4j/files/840817/Alexnet.GPU-Z.Sensor.Log.txt)
[Custom-32 GPU-Z Sensor Log.txt](https://github.com/deeplearning4j/deeplearning4j/files/840820/Custom-32.GPU-Z.Sensor.Log.txt)
[Custom-64 GPU-Z Sensor Log.txt](https://github.com/deeplearning4j/deeplearning4j/files/840818/Custom-64.GPU-Z.Sensor.Log.txt)

**Comment by rkfg** [comment]
While @raver119 fixes the CUDA backend and the overall memory model, you can try some fixes that I've used to improve GPU utilization:
1) try not to use G1GC, it seems to be ineffective for DL4J (anyway, test with it and without);
2) experiment with Nd4j.getMemoryManager().setAutoGcWindow(), the default is 100 ms, that is the period between explicit System.gc() calls to free the GPU memory. Start with 1000 and see if you hit the memory limit, there will be messages that host memory used instead of GPU. I was able to double the performance with this simple tweak but YMMV.

**Comment by sorensf** [comment]
Thanks for taking a look @rkfg.

1. This did not seem to have any effect in my case. The reason I enabled it in the first place was from reading https://deeplearning4j.org/benchmark, but I guess that page might be out-of-date.
2. This also gave me a double in performance. After I tried this I also tried setting (as recommended by https://deeplearning4j.org/gpu):
`CudaEnvironment.getInstance().getConfiguration().setMaximumDeviceCacheableLength(1024 * 1024 * 1024L).setMaximumDeviceCache(0.5 * AVALIABLE_DEVICE_MEMORY * 1024 * 1024 * 1024L).setMaximumHostCacheableLength(1024 * 1024 * 1024L).setMaximumHostCache(0.5 * AVALIABLE_DEVICE_MEMORY * 1024 * 1024 * 1024L);`
Which seem to have the same effect on my performance, but in my case actually uses less memory on the GPU. With this set, the slower garbage collection did no longer affect my performance.

I assume you have been trying out running a couple of the DL4j examples on GPU, do to happen to have any benchmarks you would be willing to share? I haven't really been able to locate any documentation about what sort of performance one should expect.

On a side note I tried running my custom model in a python-based deep learning framework, which took about 3.5 secounds per epoch, compared to the now (using your comment in 2.) 2.5 minutes per epoch in DL4j, so I expect there is something more fundamental that I am doing wrong at the moment. At least according to https://deeplearning4j.org/benchmark one should be able to achieve similar performance when everything is setup correctly.

**Comment by raver119** [comment]
3.5 seconds vs 2.5 minutes is slightly too weird... x42 difference... O_o

**Comment by sorensf** [comment]
I believe I might have found where I messed up. I am using an environment as described in the quickstart guide with:
`git clone https://github.com/deeplearning4j/dl4j-examples.git`
And then using 
`mvn clean package`
To build the dl4j-examples-0.8-SNAPSHOT-bin.jar. To use GPU I had changed the root pom.xml to
`<nd4j.backend>nd4j-cuda-8.0-platform</nd4j.backend>` ([pom.xml (.).txt](https://github.com/deeplearning4j/deeplearning4j/files/858376/pom.xml.txt))
However I had not changed the pom.xml in the sub-directory "dl4j-examples". 

Now after changing it to the following [pom.xml (dl4j-examples).txt](https://github.com/deeplearning4j/deeplearning4j/files/858377/pom.xml.dl4j-examples.txt) (changes are marked with `<!-- CHANGE -->`) the training is much faster (was I using multiple backends at the same time or something?).

I not yet used to working with maven, so would someone please take a glance at the pom.xml's to check if they make sense now?

I'll do a bit more testing to make sure this was in fact the problem, and then probably close the issue in a day or two if that is alright?

**Comment by raver119** [comment]
No, with your change you've basically added cuDNN option, that usually improves performance for CNN

**Comment by sorensf** [comment]
Some updates on the performance following enabling cuDNN. For all tests the throughput was high enough that I needed to set saveDataSetsInMemory=true; for the GPU to be saturated.

Custom model: Previously I would run out of memory at a batch size of 64, now I could increase it up until 1024 with ever running out of memory (at this point my data set was only two batches so I stopped increasing it).

Model Custom-64: No longer crashes and has a steady GPU load of ~70%. Only at higher batchsizes the GPU will have enough data to parallize to reach 100% load. 

Model Custom-32: Previously took 2 minutes per epoch, now takes 4,35 seconds per epoch (again with only a GPU load of ~70%).

**Comment by johnhuang-jh** [comment]
With cuDNN, the training speed would gradually decreased after thousand iterations. I split the data into many pieces, each 1000 iterations size, then release the dataset, shutdown AsyncDataSet background thread, and create a new dataset to continue training. by this way, the speed can keep in high performance for a long time.

**Comment by raver119** [comment]
@johnhuang-jh this particular slowdown sounds like GC issue. This issue is being worked on now.

**Comment by ygyg70** [comment]
I have the same experience - average GPU utilization is about 15%. 
dl4j 0.9.1
Windows 10
GTX 970 GPU
CUDA 8

**Comment by raver119** [comment]
Mind adding some more information to your post? Right now it tells us nothing.
I.e. some source code?

**Comment by ygyg70** [comment]
My code is a copy of the text classification example.
I put my data in - 9 classes, 200,000 records.
I am new to this, please let me know what other information could be relevant.

        ComputationGraphConfiguration config = new NeuralNetConfiguration.Builder()
                .trainingWorkspaceMode(WorkspaceMode.SINGLE).inferenceWorkspaceMode(WorkspaceMode.SINGLE)
                .weightInit(WeightInit.RELU)
                .activation(Activation.LEAKYRELU)
                .updater(Updater.ADAM)
                .convolutionMode(ConvolutionMode.Same)      //This is important so we can 'stack' the results later
                .regularization(true).l2(0.0001)
                .learningRate(0.01)
                .graphBuilder()
                .addInputs("input")
                .addLayer("cnn3", new ConvolutionLayer.Builder()
                        .kernelSize(3, vectorSize)
                        .stride(1, vectorSize)
                        .nIn(1)
                        .nOut(cnnLayerFeatureMaps)
                        .build(), "input")
                .addLayer("cnn4", new ConvolutionLayer.Builder()
                        .kernelSize(4, vectorSize)
                        .stride(1, vectorSize)
                        .nIn(1)
                        .nOut(cnnLayerFeatureMaps)
                        .build(), "input")
                .addLayer("cnn5", new ConvolutionLayer.Builder()
                        .kernelSize(5, vectorSize)
                        .stride(1, vectorSize)
                        .nIn(1)
                        .nOut(cnnLayerFeatureMaps)
                        .build(), "input")
                .addVertex("merge", new MergeVertex(), "cnn3", "cnn4", "cnn5")      //Perform depth concatenation
                .addLayer("globalPool", new GlobalPoolingLayer.Builder()
                        .poolingType(globalPoolingType)
                        .dropOut(0.5)
                        .build(), "merge")
                .addLayer("out", new OutputLayer.Builder()
                        .lossFunction(LossFunctions.LossFunction.MCXENT)
                        .activation(Activation.SOFTMAX)
                        .nIn(3 * cnnLayerFeatureMaps)
                        .nOut(Constants.LABELS.length)
                        .build(), "globalPool")
                .setOutputs("out")
                .build();

**Comment by raver119** [comment]
Convolution networks can’t underperform on gpus.
Show your iterators setup etc. Issue is somewhere else.

**Comment by ygyg70** [comment]
Here is the iterator setup:
        String path = FilenameUtils.concat(Constants.DATA_PATH, type.dataPath);
        List<String> sentences = new LinkedList<>();
        List<String> labels = new LinkedList<>();
        for (String label : Constants.LABELS) {
            if( DATASET_ITERATOR_TYPE.PREDICT.equals( type )){
                labels.add(label);
                sentences.add("");
            } else {
                File file = new File(path + label + ".txt");
                System.out.println("Reading label: " + label);
                try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
                    while (true) {
                        String line = reader.readLine();
                        if (line == null) break;
                        labels.add(label);
                        sentences.add(line);
                    }
                }
            }
        }
        CollectionLabeledSentenceProvider sentenceProvider = new CollectionLabeledSentenceProvider(sentences, labels, rng);
        return new CnnSentenceDataSetIterator.Builder()
                .sentenceProvider(sentenceProvider)
                .wordVectors(wordVectors)
                .minibatchSize(minibatchSize)
                .maxSentenceLength(maxSentenceLength)
                .useNormalizedWordVectors(true /* false */)
                .build();

**Comment by ygyg70** [comment]
Here is the iterator setup:

    public static DataSetIterator getDataSetIterator(DATASET_ITERATOR_TYPE type, WordVectors wordVectors, int minibatchSize, int maxSentenceLength, Random rng) throws IOException {
        String path = FilenameUtils.concat(Constants.DATA_PATH, type.dataPath);
        List<String> sentences = new LinkedList<>();
        List<String> labels = new LinkedList<>();
        for (String label : Constants.LABELS) {
            if( DATASET_ITERATOR_TYPE.PREDICT.equals( type )){
                labels.add(label);
                sentences.add("");
            } else {
                File file = new File(path + label + ".txt");
                System.out.println("Reading label: " + label);
                try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
                    while (true) {
                        String line = reader.readLine();
                        if (line == null) break;
                        labels.add(label);
                        sentences.add(line);
                    }
                }
            }
        }
        CollectionLabeledSentenceProvider sentenceProvider = new CollectionLabeledSentenceProvider(sentences, labels, rng);
        return new CnnSentenceDataSetIterator.Builder()
                .sentenceProvider(sentenceProvider)
                .wordVectors(wordVectors)
                .minibatchSize(minibatchSize)
                .maxSentenceLength(maxSentenceLength)
                .useNormalizedWordVectors(true /* false */)
                .build();
    }

**Comment by raver119** [comment]
Can you please open new issue, and provide your source code as gist? Sharing micro pieces without formatting doesn't help :(
