### ISSUE TITLE
Lack of example to demonstrate QLearningDiscreteConv

### ISSUE THREAD

**Issue by JasonHao123** [deeplearning4j/deeplearning4j#3039]
revision: 36a3d25dc81075f973d4406f78c26d82985de4fa
task:  master (#249)
reason:
Delete Doom.java
We can't have examples encouraging people to build from source.  I will move this in to a separate repo.

**Comment by agibsonccc** [comment]
Closing this in favor of: https://github.com/deeplearning4j/rl4j/issues/27
