### ISSUE TITLE
Lack of example to create RDD[DataSet] from HDFS CVS file

### ISSUE THREAD

**Issue by verbocity** [deeplearning4j/deeplearning4j#3040]
I would like to see an example how to read a CSV file from HDFS and how to turn it into a RDD[DataSet] directly instead of using sc.parallelize, preferably with the RecordReaderDataSetIterator.

**Comment by raver119** [comment]
That's exactly what i've been speaking about yesterday. Raw text -> Vectors transformation should have better coverage in DataVec and DL4j Spark

**Comment by huitseeker** [comment]
See #3036

**Comment by ustbxyls** [comment]
#3036 : this example just said how to read data from csv file, like  JavaRDD<List<Writable>> parsedInputData = stringData.map(new StringToWritablesFunction(rr));

but, how can we convert  JavaRDD<List<Writable>> to  JavaRDD<DataSet>, and assign batchsize of DataSet. I want to got the input of SparkDl4jMultiLayer.fit().

Is there any example ?
