### ISSUE TITLE
Documentation for word2vec is kind of outdated.

### ISSUE THREAD

**Issue by reid3290** [deeplearning4j/deeplearning4j#3042]
I am working through the [word2vec](https://deeplearning4j.org/word2vec). But apparently the code about vistualizing is outdated and can not work.
```
log.info("Plot TSNE....");
        BarnesHutTsne tsne = new BarnesHutTsne.Builder()
                .setMaxIter(1000)
                .stopLyingIteration(250)
                .learningRate(500)
                .useAdaGrad(false)
                .theta(0.5)
                .setMomentum(0.5)
                .normalize(true)
                .usePca(false)
                .build();
        vec.lookupTable().plotVocab(tsne);
```
Could any one update it? It will be really appreciated.

**Comment by rj93** [comment]
Did you discover a way to plot this?

**Comment by reid3290** [comment]
No. I still do't know how to do it.

**Comment by tomthetrainer** [comment]
Our examples have a working tsne, there had been some issues but it appears to work now. 

https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/tsne/TSNEStandardExample.java

I am closing the ticket. If however you have issues adapting the working example to your example feel free to re-open
