### ISSUE TITLE
404 Error https://deeplearning4j.org/doc/org/updater

### ISSUE THREAD

**Issue by sonalgupta** [deeplearning4j/deeplearning4j#3044]
There are links on the website to `deeplearning4j.org/doc/org` that are not working. E.g. https://deeplearning4j.org/updater has the link https://deeplearning4j.org/doc/org/deeplearning4j/nn/updater/AdamUpdater.html. I'm getting 404 error. 
<img width="946" alt="screen shot 2017-03-14 at 2 33 01 pm" src="https://cloud.githubusercontent.com/assets/4138767/23923423/dd3cd83a-08c3-11e7-9cb8-a8af9dcfc0c0.png">

**Comment by tomthetrainer** [comment]
Thanks for the bug report, fixed Adam and AdaDelta links, 

Please inform us if you find other issues.

Closing this
