### ISSUE TITLE
Custom activation functions (not directly implementing IActivation) not being registered as a subtype

### ISSUE THREAD

**Issue by catodique** [deeplearning4j/deeplearning4j#3047]
I ran into a problem while playing with DL4J.
I created a custom activation function for my network and tryied to attach the ui listener.
All is working but the model viewer.
here are the infos for my code 

stack trace
https://gist.github.com/catodique/b9294ae815f0ed3ccb89f23d0cf45d5f

pom.xml
https://gist.github.com/catodique/06689b13b57f2d9a786f8a3d22b610b5

code
https://gist.github.com/catodique/30693a1844c64c8402a2d7fbc12ed40e

**Comment by AlexDBlack** [comment]
This doesn't look specific to the UI - rather, your custom activation function can't be loaded.

```
Caused by: org.nd4j.shade.jackson.databind.JsonMappingException: Could not resolve type id 'CosActivation' into a subtype of [simple type, class org.nd4j.linalg.activations.IActivation]: known type ids = [Cube, ELU, HardSigmoid, HardTanh, IActivation, Identity, LReLU, RReLU, ReLU, Sigmoid, SoftPlus, SoftSign, Softmax, TanH]
```

Two possibilities here:
1. Your custom activation function class isn't on the classpath (i.e., save json -> load later without). Look like that isn't the case from your code
2. Something has gone wrong with registering custom subtypes for JSON serialization

@catodique Can you try the following, and let me know if it throws the same exception?
```
String str = conf.toJson();
MultiLayerConfiguration c2 = MultiLayerConfiguration.fromJson(str);
```

**Comment by catodique** [comment]
Hello I tried this and yes I had the same exception.
I was thinking that was because I had to register my activation function.

https://gist.github.com/catodique/493dd6fb413b81d1316348b8f109bc07

**Comment by AlexDBlack** [comment]
@catodique I was able to reproduce this.
My guess: your custom activation function (you didn't provide it) is extending another activation function class - such as BaseActivationFunction. It isn't being properly discovered by the reflection library.

There's an easy workaround: take your pick of the following:
```CosActivation extends BaseActivationFunction implements IActivation```
```CosActivation implements IActivation```

**Comment by catodique** [comment]
yes you were right.

here is my activation function. Sorry I didn't add it before.

https://gist.github.com/catodique/81470ada93e78d3231988c3579957799

**Comment by AlexDBlack** [comment]
Should no longer be an issue after this PR: https://github.com/deeplearning4j/deeplearning4j/pull/4956
