### ISSUE TITLE
DL4J Training UI show wrong char encoding in non english language

### ISSUE THREAD

**Issue by hoangtocdo90** [deeplearning4j/deeplearning4j#3048]
![capture](https://cloud.githubusercontent.com/assets/22963463/23942830/dc071136-09b0-11e7-9d5e-9a3d766d1228.PNG)
Here my screen capture.
formerly i remember it's work normal but when i upgrade to deeplearning4j-ui_2.11 0.7.2
only english work correct, sound like encoding problem
thanks!

**Comment by slinlee** [comment]
Hi @hoangtocdo90 thanks for reporting this. Can you help provide some more info so I can start digging into this? What language are you using and what browser/OS combination?

Thanks.

**Comment by hoangtocdo90** [comment]
let me rechecking in my linux , im using Windows 10 and every browser not showing correct in non english.
i'm trying in Internet Explorer Google Chrome and Opera and Microsoft EDGE but have same result. Here is my pom.xml 
https://gist.github.com/hoangtocdo90/3567c7e5d8e71e913be5be426bea6432
Thankyou!!

**Comment by hoangtocdo90** [comment]
Hi guys in my Feroda linux every things work normally ! I'm using japanese

**Comment by AlexDBlack** [comment]
In case it's relevant/useful information: I haven't had any language rendering issues in Windows 10 (Chrome/Firefox) for any of the UI languages we support. Windows is configured for English in my case.

**Comment by kepricon** [comment]
FYI, just tested on my ubuntu 16.04. both of chrome and firefox doesn't have any language rendering issues.

**Comment by slinlee** [comment]
@hoangtocdo90 ok, so just to confirm, you're only seeing this issue when you're using Windows 10, but it happens in any browser. Do other websites in Japanese work fine on that same computer?

**Comment by slinlee** [comment]
@hoangtocdo90 Let us know if you see this error again. For now, I'm going to close the issue. Thanks!
