### ISSUE TITLE
problem about ParagraphVectors classfier example

### ISSUE THREAD

**Issue by weiweiwang** [deeplearning4j/deeplearning4j#3050]
org.deeplearning4j.examples.nlp.paragraphvectors.ParagraphVectorsClassifierExample

## the validation code snippet is as below:
     MeansBuilder meansBuilder = new MeansBuilder(
         (InMemoryLookupTable<VocabWord>)paragraphVectors.getLookupTable(),
           tokenizerFactory);
     LabelSeeker seeker = new LabelSeeker(iterator.getLabelsSource().getLabels(),
         (InMemoryLookupTable<VocabWord>) paragraphVectors.getLookupTable());

     while (unClassifiedIterator.hasNextDocument()) {
         LabelledDocument document = unClassifiedIterator.nextDocument();
         INDArray documentAsCentroid = meansBuilder.documentAsVector(document);
         List<Pair<String, Double>> scores = seeker.getScores(documentAsCentroid);

         /*
          please note, document.getLabel() is used just to show which document we're looking at now,
          as a substitute for printing out the whole document name.
          So, labels on these two documents are used like titles,
          just to visualize our classification done properly
         */
         log.info("Document '" + document.getLabel() + "' falls into the following categories: ");
         for (Pair<String, Double> score: scores) {
             log.info("        " + score.getFirst() + ": " + score.getSecond());
         }
     }

## my problem is
     why this example does not use the nearestLabels api to validate the test data, instead it uses MeansBuilder and LabelSeeker, the code logic is very the same as ParagraphVectors.predict() does, and the predict api is marked deprecated, I'm confused about this example

**Comment by raver119** [comment]
Ye, this example was written before inferVector() and nearestLabels() methods were introduced.

I'll update it.
