### ISSUE TITLE
DL4J import keras model throw Cannot import weights with rank 5. 

### ISSUE THREAD

**Issue by silencemao** [deeplearning4j/deeplearning4j#3053]
when i import a keras model , which use 3d Convolution , buy it throw Cannot import weights with rank 5. Why?  when i use the iris model , it can work .but this can not , anyone can help me? thanks

**Comment by eraly** [comment]
We don't currently support 3d convolutions.

**Comment by agibsonccc** [comment]
Closing this in favor of a favor request for 3d convolutions.
