### ISSUE TITLE
RBM: Calculating gradient like this may have an issue

### ISSUE THREAD

**Issue by vlovsky** [deeplearning4j/deeplearning4j#3057]
https://github.com/deeplearning4j/deeplearning4j/blob/ed6547956b08df9a9477936d65db7dc80bc75874/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/layers/feedforward/rbm/RBM.java#L166-L182
Depending on the algorithm used, the gradient calculated here could be wrong. See below. 

Please explain those differences. If possible, please provide the origin of the current algorithm.

Algorithm#1 in this paper http://www.iro.umontreal.ca/~lisa/publications2/index.php/attachments/single/20 has it like this:

W ← W + e(h0v0' − Q(h1. = 1|v1)v1')
b ← b + e(h0 − Q(h1. = 1|v1))
vb ← vb + e(v0 − v1)

java code translates like this:
wGradient = input().transposei().mmul(probHidden.getFirst()).subi(negVProb.transpose().mmul(negHProb))
|
v
v0'Q(h0. = 1|v0) − P(v1 = 1|h0)'Q(h1. = 1|v1)

hBiasGradient = probHidden.getFirst().sub(negHProb).sum(0);
|
v
Q(h0. = 1|v0) − Q(h1. = 1|v1)

vBiasGradient = input.sub(negVProb).sum(0);
|
v
v0 − P(v1 = 1|h0)

**Comment by eraly** [comment]
It's probably wrong :)

**Comment by agibsonccc** [comment]
So it's been a *long* time, but here's the original references:
Y. Bengio, P. Lamblin, D. Popovici, H. Larochelle: Greedy Layer-Wise Training of Deep Networks, Advances in Neural Information Processing Systems 19, 2007

P. Vincent, H. Larochelle, Y. Bengio, P.A. Manzagol: Extracting and Composing Robust Features with Denoising Autoencoders, ICML' 08, 1096-1103, 2008

**Comment by eraly** [comment]
Grazzi @agibsonccc

**Comment by vlovsky** [comment]
This is _almost_ the same paper I sited. Here is the full paper with algos: http://www.iro.umontreal.ca/~lisa/pointeurs/BengioNips2006All.pdf

**Comment by vlovsky** [comment]
Also, I'm not sure what this is h0*v0' in it. It obviously _can't_ be done.

**Comment by vlovsky** [comment]
Started implementing RBM from scratch as a set of reference examples #410. See if you want to pull this.

**Comment by vlovsky** [comment]
410 is a pull request in deeplearning4j/dl4j-examples

**Comment by agibsonccc** [comment]
I will be the one looking at this before we go a step further here. I
unfortunately have a talk nearly every day next week and have other things
way higher on my priority list here.

Creating these pull requests is just going to create more work for me. I
will not be merging something that should be going into dl4j proper.

Please wait before doing anything more here.

**Comment by vlovsky** [comment]
sure thing

**Comment by agibsonccc** [comment]
Thanks!

**Comment by vlovsky** [comment]
I finally got to review the RBM code based on the samples I created. I noticed that there are pieces of code that someone commented out while tuning. In few words the states are set based on probabilities or sampled values. There is a good piece of documentation how to tune them: https://www.cs.toronto.edu/~hinton/absps/guideTR.pdf I was able to replicate this in my samples with good results (see below). 

I you'd like I can make appropriate changes to RBM, or give you my raw code.
 
![tuned](https://cloud.githubusercontent.com/assets/26049325/24169260/68e774f0-0e53-11e7-8b88-cd406e750e21.png)

**Comment by eraly** [comment]
We are dropping support for RBMs in favour of newer and more effective methods. Please take a look at variational autoencoders 
https://github.com/deeplearning4j/dl4j-examples/tree/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/unsupervised/variational
