### ISSUE TITLE
Deeplearning4j UI does not respect custom port property 

### ISSUE THREAD

**Issue by drlebedev** [deeplearning4j/deeplearning4j#3058]
Deeplearning4j UI in version 0.8.0 does not respect org.deeplearning4j.ui.port System property set.

```
     String portProperty = System.getProperty(UI_SERVER_PORT_PROPERTY);
```

portProperty that is read in PlayUIServer is not used.

**Comment by AlexDBlack** [comment]
Fixed: https://github.com/deeplearning4j/deeplearning4j/pull/3074
