### ISSUE TITLE
Google's word2vec returns Infinity as similarity values

### ISSUE THREAD

**Issue by amouhoub** [deeplearning4j/deeplearning4j#306]
The new versions of dl4j returns an Infinity value for the similarity between words no matter what the words are (in the vocab or not).

<h3>EDIT</h3>
The file doesn't seem to be totally loaded, some words in the vocab are skipped somewhere
For the unit test in:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/test/java/org/deeplearning4j/models/word2vec/WordVectorSerializerTest.java#L69
The total number of words in the vocab loaded from
>GoogleNews-vectors-negative300.bin.gz

is equal to 2997292 and not 3000000

**Comment by agibsonccc** [comment]
This was with master?

**Comment by amouhoub** [comment]
Yes, with master

**Comment by amouhoub** [comment]
I verified that the words I tested were included in the vocabulary. So the issue seems in the similarity calculation

**Comment by agibsonccc** [comment]
Ok that helps a bit. I'd like to get this down to a use case I can put into
a unit test. Any ideas for a smaller test case?

**Comment by amouhoub** [comment]
I don't know, it didn't work with google's trained w2v. you can either use it in the unit test or train one on a small dataset using google's "C" w2v

**Comment by agibsonccc** [comment]
We've had some discussions on gitter about this and it could have been an nd4j issue if at all. I kept this open because I thought it could have been the loader but it hasn't been that either.

**Comment by agibsonccc** [comment]
This is fixed now. The bug was related to the way the float was being read from the data input stream.
