### ISSUE TITLE
MultiTimestepRegressionExample example crashes

### ISSUE THREAD

**Issue by mikhail247** [deeplearning4j/deeplearning4j#3060]
MultiTimestepRegressionExample.java throws an exception Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: op.X length should be equal to op.Y length: [[2, 1, 2, 1, 1, 0, 1, 99]] != [[2, 1, 1, 1, 1, 0, 1, 99]]

**Comment by eraly** [comment]
Fixed in master. Thanks!
