### ISSUE TITLE
Android APK is big, how to reduce resources or code

### ISSUE THREAD

**Issue by onexuan** [deeplearning4j/deeplearning4j#3062]
I build an apk with deeplearning4j, but it is big, how to reduce resources or code

**Comment by raver119** [comment]
Please show which dependencies you've used for your Android app?

**Comment by agibsonccc** [comment]
One thing usually is only including deeplearning4j-nn instead of deeplearning4j-core.

**Comment by onexuan** [comment]
compile 'org.deeplearning4j:deeplearning4j-core:0.7.2'
compile 'org.nd4j:nd4j-native:0.7.2'
compile 'org.nd4j:nd4j-native:0.7.2:android-arm'

@raver119

**Comment by onexuan** [comment]
it will be better that if it support lightweight to using in android

**Comment by raver119** [comment]
I've just built it myself, 80MB. dl4j-nn + nd4j-native:arm

**Comment by saudet** [comment]
With Maven we can use profiles (see https://github.com/deeplearning4j/deeplearning4j/issues/2877), but with Gradle, I think we'll need to define a bunch of exclusions. I'm afraid we'll need to make a plugin for Gradle to make this easier.

**Comment by saudet** [comment]
Actually, I think we can do like I've done with JavaCV. We put all the "-platform" dependencies in the "nd4j-native-platform" module, so if the user only includes "nd4j-native" and/or "nd4j-x.x-cuda" as dependency, we don't get the "-platform" dependencies for CUDA and OpenBLAS either.

**Comment by huitseeker** [comment]
Should we have a Proguard-equipped build for Android as well ?
https://developer.android.com/studio/build/shrink-code.html

**Comment by saudet** [comment]
That's usually for the end application developers, and it doesn't work for JNI...

**Comment by raver119** [comment]
Damn, forgot to click comment button after writing comment :(

I doubt it will give too much for us at this point. Right now major part of shaded jar - our binary files. Once that solved - hypothetically we could look into it, but proguard will be called for user's own app anyway

**Comment by B0yma** [comment]
could you tell me the size of apk after this manipulations?

**Comment by saudet** [comment]
Try it with the SNAPSHOT binaries!

**Comment by B0yma** [comment]
sorry man i dont know how to do that, can you write guide how to do this plz

**Comment by saudet** [comment]
see #3227

**Comment by B0yma** [comment]
so i download some binaries and put them into libs folder and it normally compiled but when it started on harddevice i get exception 
>  04-15 20:09:19.659 22324-22350/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
>                                                    Process: com.boymaws.myapplication, PID: 22324
>                                                    java.lang.VerifyError: org/nd4j/linalg/factory/Nd4j
>                                                        at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:187)
>                                                        at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:137)
>                                                        at com.boymaws.myapplication.MainActivity.loadNet2(MainActivity.java:94)
>                                                        at com.boymaws.myapplication.MainActivity.access$000(MainActivity.java:19)
>                                                        at com.boymaws.myapplication.MainActivity$1.run(MainActivity.java:85)
>                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
>                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
>                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
>                                                        at java.lang.Thread.run(Thread.java:841)
all libs that i use

- nd4j-gson-0.8.1-20170411.024849-43
- javacpp-1.3.3-20170405.135305-3
- nd4j-api-0.8.1-20170413.065828-97
- nd4j-native-api-0.8.1-20170411.024833-43
- nd4j-native-0.8.1-20170411.024846-43-android-arm
- json-20131018
- deeplearning4j-nn-0.8.1-20170411.041412-15
- deeplearning4j-core-0.8.1-20170411.041414-15
- datavec-data-image-0.8.1-20170411.040742-16

**Comment by saudet** [comment]
Please open another issue and provide more details.
