### ISSUE TITLE
incremental intent classification learning with pagraphvectors

### ISSUE THREAD

**Issue by weiweiwang** [deeplearning4j/deeplearning4j#3063]
I'm working a conversation platform like https://api.ai or https://www.ibmwatsonconversation.com, whenever user creates an intent, he/she will provide some user intent examples(like 5 or more)，if i only use the provided user intent examples, pargraphvectors can not get enough data for training and causes a bad accuracy, besides I found some only-exists-in-one-sentence words get an almost zero vector.

Because of that, I want to provide paragraph a basic wordvectors(trained from a large corpus)，and let the paragraphvectors learn base on this basic wordvectors. However, I found that once wordvectors provided through useExistingWordVectors, the trainElementsRepresentation(false) is called, so no new vocabword will be learned from new data incrementally, and this will cause bad classification or even cannot inferVector because  tokenized rawText can not match any word in the vocabcache.

And another practical engineering problem for memory usage with the above incremental method, even though the paragraphvectors can do incemental learning, the basic wordvectors is normally very large. As a conversation platform, i need to provide every agent/workspace a separate model(paragraphvectors),  this will cause too much memory usage and  will need much machine instances.  My solution(not verifed) based on inremental-learning-support-paragraphvectors is to wrapper a wordvectors which hold two separate word2vec instances, one from user examples and the other form large corpus, and the method calls on the large-corpus-word2vec is remote from another centralized and distributed server

**Comment by raver119** [comment]
If you're sure you want that, do the following:

1) get VectorsConfiguration bean from w2v/paravec model, and set trainElementsRepresentation to true
2) set training algorithm to PV-DM

In this case you'll still be getting words updated. 

Meanwhile i'll investigate, why i've set that thing to false in builder.

**Comment by weiweiwang** [comment]
thanks @raver119
