### ISSUE TITLE
cuDNN CUDNN_STATUS_EXECUTION_FAILED on certain batch/GC windows

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#3064]
```
[main] ERROR java.lang.Throwable - Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: MemcpyAsync H2H failed: [140405908257904] -> [1112606498304]
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.parallelism.ParallelWrapper.fit(ParallelWrapper.java:403)
[main] ERROR java.lang.Throwable - 	at ai.bernie.train.ClassifierTraining.run(ClassifierTraining.java:242)
[main] ERROR java.lang.Throwable - 	at ai.bernie.train.ParallelOptimization.main(ParallelOptimization.java:121)
[main] ERROR java.lang.Throwable - Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: MemcpyAsync H2H failed: [140405908257904] -> [1112606498304]
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.parallelism.ParallelWrapper$Trainer.waitTillRunning(ParallelWrapper.java:814)
[main] ERROR java.lang.Throwable - 	at org.deeplearning4j.parallelism.ParallelWrapper.fit(ParallelWrapper.java:401)
[main] ERROR java.lang.Throwable - 	... 2 more
[main] ERROR java.lang.Throwable - Caused by: java.lang.IllegalStateException: MemcpyAsync H2H failed: [140405908257904] -> [1112606498304]
```

See gist for full output: https://gist.github.com/crockpotveggies/e20d56c57c523982f5acbb37620b447a

**Comment by crockpotveggies** [comment]
Interestingly, tuning both cache and GC frequency alleviated memory errors:

```
    CudaEnvironment.getInstance().getConfiguration()
      // key option enabled
      .allowMultiGPU(true)
      .allowCrossDeviceAccess(true)
      // we're allowing larger memory caches
      .setMaximumDeviceCache(6L * 1024L * 1024L * 1024L)
      .setMaximumHostCache(8L * 1024L * 1024L * 1024L)
      // cross-device access is used for faster model averaging over pcie
      .allowFallbackFromDevice(false)
      .setNumberOfGcThreads(6);

    Nd4j.getMemoryManager().togglePeriodicGc(true);
    Nd4j.getMemoryManager().setAutoGcWindow(50);
    Nd4j.getMemoryManager().setOccasionalGcFrequency(0);
```

I reduced the AutoGcWindow to a small value of `50`. I also had to reduce my batch size to 16. It appears GC cannot keep up with GPU execution.

**Comment by crockpotveggies** [comment]
Updated title of issue since this appears to be happening on both ParallelWrapper and single device training. On ParallelWrapper it manifests as an H2H memory sync issue. On single device it often manifests as `CUDNN_STATUS_EXECUTION_FAILED`.

Some guesses here are that GC window/cache/batch size are affecting this.

**Comment by crockpotveggies** [comment]
I made GC window, batch size, and device cache easily tunable. Here's a table of these params, and the resulting error:

| ParallelWrapper | Batch size  | GC Window  | Device Cache  | NaNs | Error  |
|---|---|---|---|---|---|
| no | 16  | 110  | 6  | n/a |  Can't allocate [HOST] memory: 9437184; threadId: 1 |
| no | 16  | 110  | 7  | yes  | CUDNN_STATUS_EXECUTION_FAILED |
| no | 12  | 110  | 7  | yes  | CUDNN_STATUS_EXECUTION_FAILED |
| no | 24  | 110  | 7  |  yes | CUDA error at /home/justin/Projects/libnd4j/blas/cuda/NativeOps.cu:4851 code=77(<unknown>) "result" |
| no |  24 | 110  | 7  | n/a  | CUDNN_STATUS_EXECUTION_FAILED |
| no | 24  | 300  | 7  | yes  | CUDNN_STATUS_EXECUTION_FAILED |
| no | 24  | 80  | 6  | yes  | CUDNN_STATUS_EXECUTION_FAILED |
| no | 24  | 80  | 3  | yes  | CUDNN_STATUS_EXECUTION_FAILED  |
| yes | 24 | 80 | 8 | n/a | CUDNN_STATUS_INTERNAL_ERROR |
| yes | 24 | 80 | 6 | n/a | CUDNN_STATUS_NOT_INITIALIZED |

**Comment by saudet** [comment]
Does this happen only when using cuDNN? No issues without?

**Comment by crockpotveggies** [comment]
Yes only happens when cuDNN is enabled. When disabled, NaN scores disappear. I've also tried enabling/disabling double precision with no change in outcome.

**Comment by saudet** [comment]
I mean, the MemcpyAsync errors too only happen with cuDNN?

**Comment by crockpotveggies** [comment]
Correct, MemcpyAsync only happens with cuDNN

**Comment by raver119** [comment]
Sounds like gc race condition? Something gets deallocated prematurely?

**Comment by crockpotveggies** [comment]
Agree is it possible cuDNN moves fast enough to trigger a race condition?
What about GC?

**Comment by saudet** [comment]
Let's try to find something easy to debug here. Are you having any issues with the MultiGpuLenetMnistExample sample? It seems to be working fine here...

**Comment by crockpotveggies** [comment]
Negative I haven't been having issues with the example. I spent some time
on the problem this morning and the mystery deepens. cuDNN doesn't seem to
be loading into my local environment at all after a reboot, even after
including the deeplearning4j-cuda-8.0 dependency and doing a clean rebuild.

Is it possible this is due to some sort of local environment issue?

**Comment by crockpotveggies** [comment]
Ah sorry, I hit send too early. It is NOT my local environment, I had
double precision enabled.

Changing the GC window to 15 simplifies the problem. the
CUDNN_INTERNAL_ERROR goes away and I'm left with the following:

```
[main] INFO CLSTAGE2-0.1LR-48BATCH - Beginning parallel training....
CUDA error at /home/justin/Projects/libnd4j/blas/cuda/NativeOps.cu:4841
code=77(<unknown>) "result"
CUDA error at /home/justin/Projects/libnd4j/blas/cuda/NativeOps.cu:4822
code=77(<unknown>) "result"
CUDA error at /home/justin/Projects/libnd4j/blas/cuda/NativeOps.cu:4841
code=77(<unknown>) "result"
CUDA error at /home/justin/Projects/libnd4j/blas/cuda/NativeOps.cu:4801
code=77(<unknown>) "result"
Failed on [140258331191840] -> [1118419890176], size: [5852], direction:
[0], result: [77]
[ParallelWrapper trainer 1] WARN org.nd4j.jita.handler.impl.CudaZeroHandler
- Out of [DEVICE] memory, host memory will be used instead: deviceId: [1],
requested bytes: [48]
```

It appears it can't allocate memory fast enough. Possibly a race condition?
My network is much more complex than the MNIST example, so there's a lot
more gears turning...

**Comment by raver119** [comment]
This thread isn't going anyway, just wastes your time. Give me some code i can run locally, and i'll find & fix issue.

**Comment by crockpotveggies** [comment]
You can use the same repo I've sent you previously. Just change your run
params to this:

`java -Xmx24g -cp build/libs/train-triplet-embeddings-0.1-SNAPSHOT-all.jar
ai.bernie.train.ParallelOptimization true true false 0.1 48 2 ADAM 0.001
XAVIER 25 2 /home/YOUR_DATA_PATH_HERE/`

Note the 25 above is GC window, and the 2 is device cache (I've
experimented with different values)

**Comment by raver119** [comment]
what is "device cache" in this case?

**Comment by crockpotveggies** [comment]
from `ParallelOptimization.java`

```
CudaEnvironment.getInstance().getConfiguration()
      // key option enabled
      .allowMultiGPU(true)
      .allowCrossDeviceAccess(true)
      // we're allowing larger memory caches
      .setMaximumDeviceCache(deviceCache * 1024L * 1024L * 1024L)
      .setMaximumHostCache(12L * 1024L * 1024L * 1024L)
      // cross-device access is used for faster model averaging over pcie
      .allowFallbackFromDevice(false)
      .setNumberOfGcThreads(6);
```

**Comment by crockpotveggies** [comment]
@raver119 just realized your copy of the repo doesn't have same configurations. feel free to pull from BitBucket

**Comment by crockpotveggies** [comment]
I ran `cuda-memcheck` and here's some output: https://gist.github.com/crockpotveggies/bee9ff1e9091bd82adb5f3dd1556bd7b

**Comment by raver119** [comment]
That's interesting. Literally second time in my life i see cuda-memcheck gives something valuable in output :)

**Comment by crockpotveggies** [comment]
Awesome. It's replicable too:

```
========= Invalid __global__ read of size 4
=========     at 0x00000c50 in maxwell_scudnn_128x64_medium_nn
=========     by thread (47,0,0) in block (0,0,0)
=========     Address 0x1046cbffff8 is out of bounds
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 (cuLaunchKernel + 0x2c5) [0x209035]
=========     Host Frame:/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.10 [0x564e51]
=========     Host Frame:/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.10 [0x5829f3]
=========     Host Frame:/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.10 [0x30346e]
=========     Host Frame:/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.10 [0x107dfe]
=========     Host Frame:/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.10 [0x1099e7]
=========     Host Frame:/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.10 [0xd0ec3]
=========     Host Frame:/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.10 (cudnnConvolutionForward + 0x806) [0x41af6]
=========     Host Frame:/home/justin/.javacpp/cache/train-triplet-embeddings-0.1-SNAPSHOT-all.jar/org/bytedeco/javacpp/linux-x86_64/libjnicudnn.so (Java_org_bytedeco_javacpp_cudnn_cudnnConvolutionForward + 0x2ef) [0x1ecaf]
=========     Host Frame:[0x7fdb79017a14]
=========
========= Program hit cudaErrorLaunchFailure (error 4) due to "unspecified launch failure" on CUDA API call to cudaStreamSynchronize.
CUDA error at /home/justin/Projects/libnd4j/blas/cuda/NativeOps.cu:4841 code=4(cudaErrorLaunchFailure) "result"
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x2f4e33]
=========     Host Frame:/home/justin/.javacpp/cache/train-triplet-embeddings-0.1-SNAPSHOT-all.jar/org/nd4j/nativeblas/linux-x86_64/libnd4jcuda.so [0x410e2e]
=========     Host Frame:/home/justin/.javacpp/cache/train-triplet-embeddings-0.1-SNAPSHOT-all.jar/org/nd4j/nativeblas/linux-x86_64/libnd4jcuda.so (_ZN9NativeOps17streamSynchronizeEPv + 0xc) [0x165c4c]
=========     Host Frame:/home/justin/.javacpp/cache/train-triplet-embeddings-0.1-SNAPSHOT-all.jar/org/nd4j/nativeblas/linux-x86_64/libjnind4jcuda.so (Java_org_nd4j_nativeblas_Nd4jCuda_00024NativeOps_streamSynchronize + 0x87) [0x3e0f7]
=========     Host Frame:[0x7fdb79658384]
=========
```

**Comment by saudet** [comment]
Ah yes by default cuDNN uses a lot of memory. You should try the NO_WORKSPACE AlgoMode:
https://github.com/deeplearning4j/deeplearning4j/search?utf8=%E2%9C%93&q=AlgoMode

**Comment by crockpotveggies** [comment]
Confirmed NO_WORKSPACE AlgoMode seems to have alleviated the issue. Let me
try this with a long-running process and report back.

**Comment by crockpotveggies** [comment]
Long-running process has been going for more than an hour now with no
issues. Next question is: does an underlying issue still exist? I.e.:
should I be able to use fastest algo mode with my current setup (2xTitanX
GPU, 64GB RAM)?

**Comment by saudet** [comment]
Maybe, how much more memory does it allocate? Maybe it's having to allocate that memory on the host, and we're triggering bugs in cuDNN because they don't expect people to do that :)

**Comment by crockpotveggies** [comment]
In total or per call? It fails randomly with different values. Sometimes it
will try to allocate 28MB and fail. Other times it's as small as 248 bytes.
I'm not sure how I can track total allocation without a profiler.

**Comment by saudet** [comment]
I meant, what is the difference between in bytes with and without NO_WORKSPACE? If cuDNN is trying to allocate on the host, you'll get warnings in the log, for example:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-cuda/src/main/java/org/deeplearning4j/nn/layers/convolution/CudnnConvolutionHelper.java#L157

**Comment by crockpotveggies** [comment]
I do not get any kind of warnings with NO_WORKSPACE. With fastest algorithm
it gives me errors in various order, but usually the host runs out of
memory before the device.

On Tue, Mar 21, 2017 at 7:58 PM Samuel Audet <notifications@github.com>
wrote:

I meant, what is the difference between in bytes with and without
NO_WORKSPACE? If cuDNN is trying to allocate on the host, you'll get
warnings in the log, for example:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-cuda/src/main/java/org/deeplearning4j/nn/layers/convolution/CudnnConvolutionHelper.java#L157

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/deeplearning4j/deeplearning4j/issues/3064#issuecomment-288284202>,
or mute the thread

**Comment by crockpotveggies** [comment]
Do we want to wait until workspaces are ready from @raver119 before closing this?

**Comment by raver119** [comment]
I think this issue isn't relevant for quite some time now.
