### ISSUE TITLE
All cuDNN scores are NaN

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#3066]
Possibly related to https://github.com/deeplearning4j/deeplearning4j/issues/3064

I've also tried enabling double precision to see if the issue is related to underflow from center loss. However, NaNs persisted. I suspect my model configuration has surfaced an issue with our cuDNN binding that was not detected in tests.

@raver119 @saudet thoughts?

**Comment by agibsonccc** [comment]
Did this get fixed with 6.0?

**Comment by crockpotveggies** [comment]
Not sure yet, currently getting UNSUPPORTED status from cuDNN.

**Comment by crockpotveggies** [comment]
Discovered something while reading cuDNN docs: 

> When beta[0] is zero, the output is not read and may contain any uninitialized data (including NaN). The storage data type for alpha[0], beta[0] is float for HALF and FLOAT tensors, and double for DOUBLE tensors. These parameters are passed using a host memory pointer.

@AlexDBlack I think you might have best insight here, if we're getting NaNs back is that going to eventually create a problem later in training?

**Comment by raver119** [comment]
What's up there?

**Comment by crockpotveggies** [comment]
This should now be fixed. Closing...
