### ISSUE TITLE
MultiLayerConfiguration weight initialization with set RNG seed issue

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#307]
The intended behaviour when setting the RNG in a MultiLayerConfiguration object (for example, passing a DefaultRandom with a given seed for debugging purposes) is that the same parameter/weight initialization should be identical each time (when used with weightInit(WeightInit.DISTRIBUTION).

At present the weights seem to differ on each initialization when specifying a given RNG/seed.

Simple test case:

public static void main(String[] args) throws Exception {
        MultiLayerNetwork model1 = new MultiLayerNetwork(getConf());
        model1.init();
        
        MultiLayerNetwork model2 = new MultiLayerNetwork(getConf());
        model2.init();
        
        float[] p1 = model1.params().data().asFloat();
        float[] p2 = model2.params().data().asFloat();
        System.out.println(Arrays.toString(p1));
        System.out.println(Arrays.toString(p2));

        org.junit.Assert.assertArrayEquals(p1,p2,0.0f);
    }
    
    private static MultiLayerConfiguration getConf(){
        MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
        .layer(new RBM())
        .nIn(2).nOut(1)
        .weightInit(WeightInit.DISTRIBUTION).dist(new NormalDistribution(0,1))
        .rng(new DefaultRandom(12345L))	//RNG with specified seed
        .list(2)
        .hiddenLayerSizes(5)
        .override(1, new ClassifierOverride())
        .build();
        return conf;
    }

**Comment by agibsonccc** [comment]
Fixed with unit test.
