### ISSUE TITLE
ParallelWrapper usMQ has no effect for MultiDataSets

### ISSUE THREAD

**Issue by fac2003** [deeplearning4j/deeplearning4j#3070]
@raver119 ParallelWrapper: The fit method that takes a MDS ignores the useMQ flag. In contrast, the fit method that takes a DataSet implements support for relocating datasets across multiple GPU devices. 

As a result, trying to cache a lot of MDS in memory when training on multiple GPUs fails because all the data is put on the first GPU. This is a significant problem because caching the whole dataset on the devices can yield massive performance improvements on all epochs but the first (I am talking about 5-10 times speed up here). 

The best way to fix this would be to create a common interface for MultiDataSets and DataSets, and write new code against the interface so that both implementations are supported by the same implementation. If that's impossible for whatever reason, then the MagicQueue implementation and support would need to be duplicated to support both.

**Comment by fac2003** [comment]
OK, understood. I am afraid we won't be able to provide feedback at this time then. All our code is written against MDS implementations (I did not want to have to support two and we have problems that need multiple inputs or outputs).

**Comment by raver119** [comment]
Hmmm... Since you're ok working with  current master anyway, i could add that implementation, if you promise to send me feedback :)

**Comment by fac2003** [comment]
We can build from source if you push a new implementation for this to master and yes, I promise we will test it and provide feedback.

**Comment by raver119** [comment]
Hey, sorry for the delay. MQ option should be working for MDS too now. On current master.

**Comment by fac2003** [comment]
Thanks. We will rebuild master on our server and let you know how it goes.

**Comment by raver119** [comment]
Thanks. However, please note: workspaces are enabled by default for PW.

**Comment by fac2003** [comment]
Is there a page somewhere that describes what workspaces are and what they entail? I have seen the word mentioned, just don't know what it is precisely.

**Comment by raver119** [comment]
It's "in progress yet". In short - it's funny way to get rid of GC and reduce memory footprint.

**Comment by raver119** [comment]
https://deeplearning4j.org/workspaces
