### ISSUE TITLE
plugin repo with ID scala-tools.org is broken

### ISSUE THREAD

**Issue by thushv89** [deeplearning4j/deeplearning4j#308]
When trying to build from the source. Maven cannot resolve scala-tools dependencies because the following url doesn't exist anymore
http://scala-tools.org/repo-releases

suggested solution: can be replaced with https://oss.sonatype.org/content/groups/scala-tools/

Found in:
deeplearning4j/deeplearning4j-scaleout/spark/pom.xml

**Comment by agibsonccc** [comment]
Fixed.
