### ISSUE TITLE
RBM requires some public entry points to do the "encoding" or "decoding" as part of DBN

### ISSUE THREAD

**Issue by vlovsky** [deeplearning4j/deeplearning4j#3085]
There is no entry point to do the activation of RBM in the reverse (decoding) direction with respect to activate(). Methods propDown and sampleVisibleGivenHidden are not part of any public interface. So, currently it's not possible to utilize RBM to decode without extracting layers from the NN and using them individually.

**Comment by raver119** [comment]
In case of architecture that contains multiple  sequential RBM (like this one: https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/unsupervised/deepbelief/DeepAutoEncoderExample.java) 

It's pretty much possible to activate, say, levels 0-5, or 6-10 separately.

**Comment by vlovsky** [comment]
DBN is not really a feed forward net and this example will not work. Its possible to train first half of the layers in this example (I don't know what's the reason to have the second half actually). Still it will not decode anything because DBN is using the hidden biases to encode and the visible biases to decode. activate() in RBM uses hidden biases to encode. There are no alternatives to decode.

**Comment by raver119** [comment]
Right, i've just mentioned the way to invoke selected subset of layer on higher abstraction. We probably could do something like that for RBM itself.

**Comment by vlovsky** [comment]
While working on it I found that the best results come from training one layer on all samples and epochs before starting to train the next layer. Also, this is a must for greedy layer by layer training, where weights are inherited by the next layer.

This is all possible with the current setup, but the code to pull this strings directly on RBM is messy. It would be very nice to be able to have a higher level abstraction that would allow shifting learning to the next layer once all work is done with the previous.

**Comment by eraly** [comment]
We are dropping support for RBMs in favour of newer and more effective methods. Please take a look at variational autoencoders 
https://github.com/deeplearning4j/dl4j-examples/tree/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/unsupervised/variational
