### ISSUE TITLE
UI Trainer module is not friendly to pretrained net's

### ISSUE THREAD

**Issue by vlovsky** [deeplearning4j/deeplearning4j#3086]
The "Model" tab of the UI showed only one layer, despite having multiple in the code. I think the reason for this is that following code gathers model configuration into JSON after 1st iteration is complete. This means for pre-trained NNs it's called in the first layer of the NN instead of the overall NN. 

https://github.com/deeplearning4j/deeplearning4j/blob/1f8af820c29cc5567a2c5eaa290f094c4d1492a7/deeplearning4j-ui-parent/deeplearning4j-ui-model/src/main/java/org/deeplearning4j/ui/stats/BaseStatsListener.java#L627-L659

This probably causes other side effects in the Model tab of Trainer UI. For example, no statics are displayed.

**Comment by raver119** [comment]
Yep, all IterationListeners are executed at the end of iteration

**Comment by vlovsky** [comment]
screenshot of the issue can be found in #388

**Comment by AlexDBlack** [comment]
Current design is to separate pretrain vs. standard backprop. In theory, they should get different session IDs.
Consider something like VAEs: each VAE "layer" actually shows multiple layers when plotted in the UI during layerwise pretraining; and we have different iteration counts for pretrain vs. backprop etc.

I'd be open to revisiting how we handle pretrain vs. backprop in the UI, but this isn't a simple bug or anything. In the short term (as long as everything works re: session IDs) it's not a priority IMO.

**Comment by vlovsky** [comment]
I figured that it wasn't a simple issue. But there should be a simple workaround to allow Trainer UI to work when pretraining. After all it's the most important phase of the RBM for instance. Currently it's impossible to see NN structure or even the first RBM layer statistics during pretraining. I will play with VAE and see if this is an RBM-only problem.

By the way there is also a NPE when accessing the name of the pseudo layer. I think happens when clicking on that funny looking layer in the NPE structure on the Model tab.

**Comment by vlovsky** [comment]
Filed an issue for the NPE. Back to this issue. It seems that it is RBM only problem because I see several layers in VAE example and all of them do report statistics unlike the RBM.

**Comment by vlovsky** [comment]
Found the root cause. 
Prefix of the parameters in RBM (they don't exist) are not equal to the layer name. I can fix it by following how it is done in the VariationalAutoencoderParamInitializer (obviously with other relevant updates elsewhere to update their names), or I can fix it in the TrainModule that accesses the parameters: https://github.com/vlovsky/deeplearning4j/blob/1d629384b902ea0b59a7e0965f641285b743e6ba/deeplearning4j-ui-parent/deeplearning4j-play/src/main/java/org/deeplearning4j/ui/module/train/TrainModule.java#L1021-L1027
Which way do you prefer?
