### ISSUE TITLE
Suggestion in build-dl4j-stack script 

### ISSUE THREAD

**Issue by djKooks** [deeplearning4j/deeplearning4j#3088]
I'm looking on DataVec, and nd4j project currently. Local directory tree were like this.
```
/DataVec
/deeplearning4j
/nd4j
```
In this form, script `build-dl4j-stack` removes local `DataVec`, `nd4j` directory and replace with new one.
How about let local repo remains if it exists?

**Comment by raver119** [comment]
It's done to ensure the most recent copies are used. However it's definitely sub-optimal behavior. We should just `git reset --hard` all repos, and pull them.

**Comment by huitseeker** [comment]
This was solved by https://github.com/deeplearning4j/deeplearning4j/commit/47eefd83fa2b2f236e25ead7da831ef6cd956974

**Comment by djKooks** [comment]
@huitseeker Thanks!
