### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#3089]
Evaluation class performance with cuda backend requires investigation. I clearly see performance issues there. GPU utilization is spiky, and evaluation as process definitely takes much more time then it should take.

**Comment by crockpotveggies** [comment]
Confirmed I'm seeing the same thing. 62000 images on my net should take 6 minutes to complete, but takes longer than 20 minutes. Never really figured it out.

**Comment by raver119** [comment]
I guess this issue was resolved too.
