### ISSUE TITLE
Long-running cuDNN process results in NaN scores

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#3091]
Currently when deserializing a pretrained model (w/ saved updater state) and attempting to continue training, scores appear as NaN when cuDNN is enabled.

However if I remove cuDNN as a dependency, scores return to normal.

Please let me know how I can help debug this. I can provide a copy of the pretrained model as well as a copy of my repo/data via PM.

**Comment by crockpotveggies** [comment]
Suggest @saudet have a look.

**Comment by raver119** [comment]
_guess mode_ From cuDNN perspective there should be no real differences **after** layers are created. So if something is wrong on our side, it should be around layers instantiation i guess.

**Comment by raver119** [comment]
@crockpotveggies can you please check, if turning CudaGridExecutioner off fixes issue?

**Comment by crockpotveggies** [comment]
Changed this in my properties file:
opexec= org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner

Still no effect, scores are NaN

**Comment by raver119** [comment]
Thanks... :(

**Comment by crockpotveggies** [comment]
![screen shot 2017-03-28 at 4 35 13 pm](https://cloud.githubusercontent.com/assets/1445295/24432463/4619de34-13d7-11e7-84d0-9840ce49d3ee.png)

Leaving this here so we can track it. The issue persists not just with pretrained models, but also when training during a long-running process. In the image above, I enabled cuDNN and after a certain period of time all scores drop to NaN and the process is unrecoverable.

After chatting with @AlexDBlack I believe this is a separate cuDNN issue, perhaps a bug with cuDNN itself, and is not related to https://github.com/deeplearning4j/deeplearning4j/issues/3026

**Comment by AlexDBlack** [comment]
There certainly haven't been any reports of this recently. So I'll close it.
We can re-open if it resurfaces.
