### ISSUE TITLE
Cannot use CPU ND4j backend for training when cuDNN dependency is added

### ISSUE THREAD

**Issue by sorensf** [deeplearning4j/deeplearning4j#3098]
I tried building a DL4j jar with both GPU and CPU backend for ND4j while also having enabled cuDNN. Training on GPU worked fine, but after switching the backend to CPU an exception is thrown from CudnnConvolutionHelper.

**Comment by saudet** [comment]
It works just fine here. Could you provide more details about how you are building and running your application?

**Comment by sorensf** [comment]
Sure. (Most of this is copied from when described my setup in #3038). 

I am using an environment as described in the quickstart guide with:
`git clone https://github.com/deeplearning4j/dl4j-examples.git`
And then using 
`mvn clean package`
To build the dl4j-examples-0.8-SNAPSHOT-bin.jar. To use GPU I have changed the root pom.xml to
`<nd4j.backend>nd4j-cuda-8.0-platform</nd4j.backend>` ([pom.xml (.).txt](https://github.com/deeplearning4j/deeplearning4j/files/858376/pom.xml.txt))
And I have changed the pom.xml in the sub-directory "dl4j-examples" to the following [pom.xml.dl4j-examples.txt](https://github.com/deeplearning4j/deeplearning4j/files/869965/pom.xml.dl4j-examples.txt) (changes are marked with `<!-- CHANGE -->`).

**Comment by saudet** [comment]
Ok, could you also copy/paste what shows up on the console when you run an example?

**Comment by sorensf** [comment]
Sorry, I will not have access to the code again for a while. But I can describe as best I can from memory, although the of cource might not be of much use. I was using the system variable BACKEND_PRIORITY_CPU=200 to switch to CPU. 

When running on GPU is was like (copied again from #3038) 
 INFO | Loaded [JCublasBackend] backend
 INFO | Number of threads used for NativeOps: 32
 INFO | Reflections took 297 ms to scan 3 urls, producing 29 keys and 189 values 
 INFO | Backend used: [CUDA]; OS: [Windows 7]
 INFO | Cores: [12]; Memory: [31,3GB];
 INFO | Blas vendor: [CUBLAS]
 INFO | Device name: [GeForce GTX 1080]; CC: [6.1]; Total/free memory: [8589934592]

When running on CPU it instead printed it was using MKL, and none of the GPU related things were printed.

**Comment by sorensf** [comment]
If it helps, I initially asked about the issue in the gitter channel where @raver119 mentioned it was something that was missed and I should make an issue, so he might know more about it.

**Comment by raver119** [comment]
> When running on CPU it instead printed it was using MKL, and none of the GPU related things were printed.

And then it failed with cuDNN, right?

**Comment by sorensf** [comment]
Yes, at the point where model.fit(..) was called, it throws.

**Comment by sorensf** [comment]
By the way, if you still have trouble reproducing the issue. The model I used when the exception was thrown was the custom model from: https://gist.github.com/sorensf/7309f2ee9811c6b1d462e037ad123fd5, I guess that might have an effect that it is convolutional.

**Comment by saudet** [comment]
I see what's going on. Basically, we need to make sure that nd4j-cuda is loaded as backend before trying to load cuDNN. Thanks for reporting!

**Comment by sorensf** [comment]
I've recently upgraded to Dl4j 0.9.1 for this fix, but it still doesn't seem to work in my setup, actually it has slightly gotten worse. My workflow is still that I train a model on GPU and then use it in a VM with CPU (simulated here with BACKEND_PRIORITY_CPU = 200), previously this was possible, and only failed when I tried training on CPU. Now I am no longer able to deserialize the GPU trained models at all on the CPU VM - see the output for the stacktrace
[deserialization-exception.txt](https://github.com/deeplearning4j/deeplearning4j/files/1295322/deserialization-exception.txt)

**Comment by raver119** [comment]
This issue was already fixed yesterday.
