### ISSUE TITLE
cuda Error Launch Failure when dataset too large for memory

### ISSUE THREAD

**Issue by Joshuaalbert** [deeplearning4j/deeplearning4j#3100]
I am trying to train with a multidataset that is too big for memory. The logger then says it will use host memory.
Then after a while the process goes zombie with,
```
CUDA error at C:/Users/josh/dl4j/build/libnd4j/blas/cuda/NativeOps.cu:4851
code=4(cudaErrorLaunchFailure) "result"
```
Is it generally impossible to use CUDA when the data doesn't fit into the memory? 
Or can it do part at a time (as it seems to do)?
It seems to fail after about 30 iterations of fit.

**Comment by raver119** [comment]
It's not about memory amount.

Show your nn configuration and pom.xml please

**Comment by Joshuaalbert** [comment]
Trying to reproduce.

**Comment by crockpotveggies** [comment]
@raver119 I wonder if this is another CNN fastest algorithm issue? Perhaps trying to use NO_WORKSPACE could work here?

**Comment by Joshuaalbert** [comment]
I've reproduced with this pom.xml
https://gist.github.com/Joshuaalbert/399f33ab59de0a29720f1f101e639152

**Comment by raver119** [comment]
And nn configuration?

**Comment by Joshuaalbert** [comment]
the model is a simple lstm stack and works with the native backend. Also the cuda backend was working yesterday and the only difference I can think of was that I didnt attach a stats listener UI. Maybe the problem comes from using InMemoryStatsStorage when memory isnt completely on host or device? or is it's location transparent in that process.

**Comment by raver119** [comment]
"Simple LSTM" is very vague definition. Please show me nn conf, and data feeding pipeline.

**Comment by Joshuaalbert** [comment]
Here's the nn and training loop
https://gist.github.com/Joshuaalbert/9df97e1ffd9f36a5bbac0e85362a9dc7

**Comment by Joshuaalbert** [comment]
It seems to happen with stats listener ui.

**Comment by raver119** [comment]
Surprising. Can you please run with CUDA and without UI stuff? Just to confirm issue is localized to UI?

**Comment by Joshuaalbert** [comment]
I am doing that now.

**Comment by Joshuaalbert** [comment]
So far without the stats UI it's running fine. Now, do you think it depends on whether I use FileStatsStorage or InMemoryStatsStorage? I would imagine that part doesn't make a difference. It must be somewhere an assumption is made where the stats are stored.

**Comment by raver119** [comment]
Well, we know that for versions <= 0.8.0 there were no issues with CUDA+UI, besides of excessive GC activity. So it was definitely working. Not sure what was changed in that field on current master :/

**Comment by Joshuaalbert** [comment]
@AlexDBlack would you know the answer to that?

**Comment by raver119** [comment]
@Joshuaalbert can you just try the same code with 0.8.0 from maven central?

**Comment by Joshuaalbert** [comment]
I just had this error without the UI.
It happened after ~10 hours of training. Though during this time my laptop was opened and closed several times by airport staff. 
```
CUDA error at libnd4j/blas/cuda/NativeOps.cu:4705 code=30(cudaErrorUnknown) "result" 
CUDA error at libnd4j/blas/cuda/NativeOps.cu:4851 code=30(cudaErrorUnknown) "result" 
```

**Comment by Joshuaalbert** [comment]
@raver119 I'm not exactly sure how to get maven to pull the 0.8 version. I always compile locally.

**Comment by Joshuaalbert** [comment]
I ran with 0.8 from maven repo using UI. I get code 4 this time. The same as the original one.
Note that above when I got running without UI and still got the error that it was error 30.
```
CUDA error at C:/projects/skymind/deploy/windows-x86_64/libnd4j/blas/cuda/NativeOps.cu:4851 code=4(cudaErrorLaunchFailure) "result"
```

**Comment by raver119** [comment]
O_o

**Comment by raver119** [comment]
Please give me your system info.

Os, gpu model name, cpu model, motherboard model (if not laptop) or laptop model name (if laptop)

**Comment by Joshuaalbert** [comment]
It's a laptop Lenovo P50 with a Xeon 1505M v5 cpu, nvidia quadro m2000m (cc 5.0), windows 10.

**Comment by AlexDBlack** [comment]
> Now, do you think it depends on whether I use FileStatsStorage or InMemoryStatsStorage? I would imagine that part doesn't make a difference. It must be somewhere an assumption is made where the stats are stored.
No INDArrays are stored, and no INDArrays are passed between threads, with the UI.

I'll try to run this later, see if I can reproduce it.

**Comment by Joshuaalbert** [comment]
@AlexDBlack @raver119 with regards to the run without UI that also resulted in a crash. I will run again. I suspect it was due to my laptop being open and closed quickly and at random by airport security, because the crash occurs normally within 30minutes of starting and in this case it had been running for 10+ hours no problems until I had to fly.
