### ISSUE TITLE
Unsupported keras layer type Convolution1D.

### ISSUE THREAD

**Issue by Davidott4** [deeplearning4j/deeplearning4j#3101]
I'm attempting to import a pre-trained model into DL4J from keras. 

However 

 ComputationGraph model=KerasModelImport.importKerasModelAndWeights(myModel,myWeights);

throws the error:

UnsupportedKerasConfigurationException: Unsupported keras layer type Convolution1D. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.

Is there any plan to implement this functionality in the near future, or is there a work-around using 2D convolutions to reproduce a 1D convolution's performance?

**Comment by AlexDBlack** [comment]
We have 1d convolution layers in DL4J now - looks like they didn't make in into the Keras model import functionality, as of 0.8.0. In theory it shouldn't be too hard to add now, @turambar ?

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/KerasLayer.java#L249

**Comment by turambar** [comment]
Yeah, this slipped by me in the last release. Here's a PR: https://github.com/deeplearning4j/deeplearning4j/pull/3102 if you're feeling adventurous, @Davidott4. Looks OK but needs testing prior to merge.

**Comment by maxpumperla** [comment]
Closing #3923
