### ISSUE TITLE
Refactor IEvaluation methods (better design & given new per-output masking support)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3106]
Currently: we have eval and evalTimeSeries methods. This made sense when masks were only used for per-example time-series cases - but now we have per-output masking also.

Consequently, it probably makes sense to deprecate evalTimeSeries and just use a single eval (and eval with a mask overload) for everything. This may make things easier for users, also; numerous users end initially trying to use eval instead of evalTimeSeries (not realizing they should be using the later).

Edit: while we're at it, some ComputationGraph evaluation overloads for multi-output cases would be quite useful...

Edit2: add SparkComputationGraph evaluation methods too...

**Comment by raver119** [comment]
I think this issue was implemented some time ago.
