### ISSUE TITLE
[Question] Deep learning other than NN?

### ISSUE THREAD

**Issue by hrstoyanov** [deeplearning4j/deeplearning4j#3109]
Hello,
DL4J is heavily tilted towards NN? Any plans to explore other deep learning approaches?  

A couple of recent publications suggest that DNN might be just a big hoax, memorizing input data, never generalizing or learning:
https://arxiv.org/pdf/1703.06857.pdf 
https://arxiv.org/pdf/1611.03530.pdf 

Other publications point to "just as good" learning algorithms without the need of pricey GPUs:
https://arxiv.org/abs/1702.08835

**Comment by agibsonccc** [comment]
There are 3 conferences and multiple billion dollar public company research labs that say you are plenty wrong. I'm closing this and will not be interested in further discussion of this.
