### ISSUE TITLE
fasttext implementation required

### ISSUE THREAD

**Issue by weiweiwang** [deeplearning4j/deeplearning4j#3113]
fasttext is proven much better than paragraph vector, and paragraph vector result in the original paper can not be reimplement according to https://groups.google.com/forum/#!msg/word2vec-toolkit/Q49FIrNOQRo/DoRuBoVNFb0J

i tried fasttext and paragraph vector on same data(7 labeled short text, 16M), paragraph vector get a accuracy around 75% while fasttext get a 87% accuracy, so i recommend fasttext implementation is included in deeplearning4j

fastext source code in c++
https://github.com/facebookresearch/fastText

**Comment by saudet** [comment]
This will need to be mapped by the presets:
https://github.com/bytedeco/javacpp-presets/issues/346

**Comment by saudet** [comment]
Sorry, I believe I incorrectly closed this. Marking as duplicate of #4258, so let's keep that one opened.
