### ISSUE TITLE
Is there an example of using multiple channels?

### ISSUE THREAD

**Issue by rj93** [deeplearning4j/deeplearning4j#3116]
I am trying to implement a CNN using word2vec, and would like to use multiple channels. One using the pre-trained google news embedding, and another embedding I create using my dataset. 

I have looked for some examples, but can't seem to find any, could someone point me in the correct direction?

**Comment by raver119** [comment]
it's just channel dimension > 1, nothing special there.

**Comment by rj93** [comment]
How do I create the dataset for it?

**Comment by raver119** [comment]
On your own. Basically you'll be doing the same thing we do in CnnSentenceDataSetIterator, but will be filling different channels with different vectors.

**Comment by rj93** [comment]
I know I have to do it on my own, but even in CnnSentenceDataSetIterator there is no mention of channels

**Comment by AlexDBlack** [comment]
To be clear: you have two separate word vector models, and you want to concatenate them?
The CnnSentenceDataSetIterator doesn't currently support that - only single channel. But the code itself isn't that complicated, so you should be able to adapt it easily enough.

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/iterator/CnnSentenceDataSetIterator.java#L125

Line 125: there's an indices array.
Say you have 2 vectors/channels:
First channel: ```indices[1] = NDArrayIndex.point(0);```
Second channel: ```indices[1] = NDArrayIndex.point(1);```
and so on.
The rest should be pretty much the same.

**Comment by raver119** [comment]
Right, as i've said above - channel dimension will be  > 1. In that iterator dimension is hardcoded to 1. In your case it'll be 2, 3, 5 whatever you have there :)

And they will be filled exactly the same way it's filled in that iterator.
