### ISSUE TITLE
Error with MultiGpu classification images to 7 classes

### ISSUE THREAD

**Issue by MikeF23** [deeplearning4j/deeplearning4j#3122]
My code on gist: 
https://gist.github.com/MikeF23/9056573520e794cc3fc090c1374875c3

I have an error: 
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: org.nd4j.shade.jackson.databind.JsonMappingException: Could not resolve type id 'mean' into a subtype of [simple type, class org.deeplearning4j.nn.conf.distribution.Distribution]: known type ids = [Distribution, binomial, gaussian, normal, uniform]
 at [Source: {
  "backprop" : true,
  "backpropType" : "Standard",
  "confs" : [ {
    "iterationCount" : 0,
    "l1ByParam" : {
      "b" : 0.0,
      "W" : 0.0
    },
    "l2ByParam" : {
      "b" : 0.0,
      "W" : 5.0E-4
    },
    "layer" : {
      "convolution" : {
        "activationFn" : {
          "ReLU" : { }
        },
        "adamMeanDecay" : "NaN",
        "adamVarDecay" : "NaN",
        "biasInit" : 0.0,
        "biasLearningRate" : 0.01,
        "convolutionMode" : "Truncate",
        "cudnnAlgoMode" : "PREFER_FASTEST",
        "dist" : {
          "mean" : 0.0,
          "std" : 0.01
        },
        "dropOut" : 0.0,
        "epsilon" : "NaN",
        "gradientNormalization" : "RenormalizeL2PerLayer",
        "gradientNormalizationThreshold" : 1.0,
        "kernelSize" : [ 11, 11 ],
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 5.0E-4,
        "l2Bias" : 0.0,
        "layerName" : "cnn1",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "momentum" : 0.9,
        "momentumSchedule" : { },
        "nin" : 3,
        "nout" : 96,
        "padding" : [ 3, 3 ],
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "stride" : [ 4, 4 ],
        "updater" : "NESTEROVS",
        "weightInit" : "DISTRIBUTION"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : {
      "b" : 0.01,
      "W" : 0.01
    },
    "learningRatePolicy" : "Step",
    "lrPolicyDecayRate" : 0.1,
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : 100000.0,
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 42,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ "W", "b" ]
  }, {
    "iterationCount" : 0,
    "l1ByParam" : { },
    "l2ByParam" : { },
    "layer" : {
      "localResponseNormalization" : {
        "activationFn" : {
          "ReLU" : { }
        },
        "adamMeanDecay" : "NaN",
        "adamVarDecay" : "NaN",
        "alpha" : 1.0E-4,
        "beta" : 0.75,
        "biasInit" : 0.0,
        "biasLearningRate" : 0.01,
        "dist" : {
          "normal" : {
            "mean" : 0.0,
            "std" : 0.01
          }
        },
        "dropOut" : 0.0,
        "epsilon" : "NaN",
        "gradientNormalization" : "RenormalizeL2PerLayer",
        "gradientNormalizationThreshold" : 1.0,
        "k" : 2.0,
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 5.0E-4,
        "l2Bias" : 0.0,
        "layerName" : "lrn1",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "momentum" : 0.9,
        "momentumSchedule" : { },
        "n" : 5.0,
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "updater" : "NESTEROVS",
        "weightInit" : "DISTRIBUTION"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : { },
    "learningRatePolicy" : "Step",
    "lrPolicyDecayRate" : 0.1,
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : 100000.0,
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 42,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ ]
  }, {
    "iterationCount" : 0,
    "l1ByParam" : { },
    "l2ByParam" : { },
    "layer" : {
      "subsampling" : {
        "activationFn" : {
          "ReLU" : { }
        },
        "adamMeanDecay" : "NaN",
        "adamVarDecay" : "NaN",
        "biasInit" : 0.0,
        "biasLearningRate" : 0.01,
        "convolutionMode" : "Truncate",
        "dist" : {
          "normal" : {
            "mean" : 0.0,
            "std" : 0.01
          }
        },
        "dropOut" : 0.0,
        "eps" : 1.0E-8,
        "epsilon" : "NaN",
        "gradientNormalization" : "RenormalizeL2PerLayer",
        "gradientNormalizationThreshold" : 1.0,
        "kernelSize" : [ 3, 3 ],
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 5.0E-4,
        "l2Bias" : 0.0,
        "layerName" : "maxpool1",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "momentum" : 0.9,
        "momentumSchedule" : { },
        "padding" : [ 0, 0 ],
        "pnorm" : 0,
        "poolingType" : "MAX",
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "stride" : [ 2, 2 ],
        "updater" : "NESTEROVS",
        "weightInit" : "DISTRIBUTION"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : { },
    "learningRatePolicy" : "Step",
    "lrPolicyDecayRate" : 0.1,
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : 100000.0,
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 42,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ ]
  }, {
    "iterationCount" : 0,
    "l1ByParam" : {
      "b" : 0.0,
      "W" : 0.0
    },
    "l2ByParam" : {
      "b" : 0.0,
      "W" : 5.0E-4
    },
    "layer" : {
      "convolution" : {
        "activationFn" : {
          "ReLU" : { }
        },
        "adamMeanDecay" : "NaN",
        "adamVarDecay" : "NaN",
        "biasInit" : 1.0,
        "biasLearningRate" : 0.01,
        "convolutionMode" : "Truncate",
        "cudnnAlgoMode" : "PREFER_FASTEST",
        "dist" : {
          "mean" : 0.0,
          "std" : 0.01
        },
        "dropOut" : 0.0,
        "epsilon" : "NaN",
        "gradientNormalization" : "RenormalizeL2PerLayer",
        "gradientNormalizationThreshold" : 1.0,
        "kernelSize" : [ 5, 5 ],
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 5.0E-4,
        "l2Bias" : 0.0,
        "layerName" : "cnn2",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "momentum" : 0.9,
        "momentumSchedule" : { },
        "nin" : 96,
        "nout" : 256,
        "padding" : [ 2, 2 ],
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "stride" : [ 1, 1 ],
        "updater" : "NESTEROVS",
        "weightInit" : "DISTRIBUTION"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : {
      "b" : 0.01,
      "W" : 0.01
    },
    "learningRatePolicy" : "Step",
    "lrPolicyDecayRate" : 0.1,
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : 100000.0,
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 42,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ "W", "b" ]
  }, {
    "iterationCount" : 0,
    "l1ByParam" : { },
    "l2ByParam" : { },
    "layer" : {
      "localResponseNormalization" : {
        "activationFn" : {
          "ReLU" : { }
        },
        "adamMeanDecay" : "NaN",
        "adamVarDecay" : "NaN",
        "alpha" : 1.0E-4,
        "beta" : 0.75,
        "biasInit" : 0.0,
        "biasLearningRate" : 0.01,
        "dist" : {
          "normal" : {
            "mean" : 0.0,
            "std" : 0.01
          }
        },
        "dropOut" : 0.0,
        "epsilon" : "NaN",
        "gradientNormalization" : "RenormalizeL2PerLayer",
        "gradientNormalizationThreshold" : 1.0,
        "k" : 2.0,
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 5.0E-4,
        "l2Bias" : 0.0,
        "layerName" : "lrn2",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "momentum" : 0.9,
        "momentumSchedule" : { },
        "n" : 5.0,
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "updater" : "NESTEROVS",
        "weightInit" : "DISTRIBUTION"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : { },
    "learningRatePolicy" : "Step",
    "lrPolicyDecayRate" : 0.1,
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : 100000.0,
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 42,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ ]
  }, {
    "iterationCount" : 0,
    "l1ByParam" : { },
    "l2ByParam" : { },
    "layer" : {
      "subsampling" : {
        "activationFn" : {
          "ReLU" : { }
        },
        "adamMeanDecay" : "NaN",
        "adamVarDecay" : "NaN",
        "biasInit" : 0.0,
        "biasLearningRate" : 0.01,
        "convolutionMode" : "Truncate",
        "dist" : {
          "normal" : {
            "mean" : 0.0,
            "std" : 0.01
          }
        },
        "dropOut" : 0.0,
        "eps" : 1.0E-8,
        "epsilon" : "NaN",
        "gradientNormalization" : "RenormalizeL2PerLayer",
        "gradientNormalizationThreshold" : 1.0,
        "kernelSize" : [ 3, 3 ],
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 5.0E-4,
        "l2Bias" : 0.0,
        "layerName" : "maxpool2",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "momentum" : 0.9,
        "momentumSchedule" : { },
        "padding" : [ 0, 0 ],
        "pnorm" : 0,
        "poolingType" : "MAX",
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "stride" : [ 2, 2 ],
        "updater" : "NESTEROVS",
        "weightInit" : "DISTRIBUTION"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : { },
    "learningRatePolicy" : "Step",
    "lrPolicyDecayRate" : 0.1,
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : 100000.0,
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 42,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ ]
  }, {
    "iterationCount" : 0,
    "l1ByParam" : {
      "b" : 0.0,
      "W" : 0.0
    },
    "l2ByParam" : {
      "b" : 0.0,
      "W" : 5.0E-4
    },
    "layer" : {
      "convolution" : {
        "activationFn" : {
          "ReLU" : { }
        },
        "adamMeanDecay" : "NaN",
        "adamVarDecay" : "NaN",
        "biasInit" : 0.0,
        "biasLearningRate" : 0.01,
        "convolutionMode" : "Truncate",
        "cudnnAlgoMode" : "PREFER_FASTEST",
        "dist" : {
          "mean" : 0.0,
          "std" : 0.01
        },
        "dropOut" : 0.0,
        "epsilon" : "NaN",
        "gradientNormalization" : "RenormalizeL2PerLayer",
        "gradientNormalizationThreshold" : 1.0,
        "kernelSize" : [ 3, 3 ],
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 5.0E-4,
        "l2Bias" : 0.0,
        "layerName" : "cnn3",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "momentum" : 0.9,
        "momentumSchedule" : { },
        "nin" : 256,
        "nout" : 384,
        "padding" : [ 1, 1 ],
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "stride" : [ 1, 1 ],
        "updater" : "NESTEROVS",
        "weightInit" : "DISTRIBUTION"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : {
      "b" : 0.01,
      "W" : 0.01
    },
    "learningRatePolicy" : "Step",
    "lrPolicyDecayRate" : 0.1,
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : 100000.0,
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 42,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ "W", "b" ]
  }, {
    "iterationCount" : 0,
    "l1ByParam" : {
      "b" : 0.0,
      "W" : 0.0
    },
    "l2ByParam" : {
      "b" : 0.0,
      "W" : 5.0E-4
    },
    "layer" : {
      "convolution" : {
        "activationFn" : {
          "ReLU" : { }
        },
        "adamMeanDecay" : "NaN",
        "adamVarDecay" : "NaN",
        "biasInit" : 1.0,
        "biasLearningRate" : 0.01,
        "convolutionMode" : "Truncate",
        "cudnnAlgoMode" : "PREFER_FASTEST",
        "dist" : {
          "mean" : 0.0,
          "std" : 0.01
        },
        "dropOut" : 0.0,
        "epsilon" : "NaN",
        "gradientNormalization" : "RenormalizeL2PerLayer",
        "gradientNormalizationThreshold" : 1.0,
        "kernelSize" : [ 3, 3 ],
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 5.0E-4,
        "l2Bias" : 0.0,
        "layerName" : "cnn4",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "momentum" : 0.9,
        "momentumSchedule" : { },
        "nin" : 384,
        "nout" : 384,
        "padding" : [ 1, 1 ],
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "stride" : [ 1, 1 ],
        "updater" : "NESTEROVS",
        "weightInit" : "DISTRIBUTION"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : {
      "b" : 0.01,
      "W" : 0.01
    },
    "learningRatePolicy" : "Step",
    "lrPolicyDecayRate" : 0.1,
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : 100000.0,
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 42,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ "W", "b" ]
  }, {
    "iterationCount" : 0,
    "l1ByParam" : {
      "b" : 0.0,
      "W" : 0.0
    },
    "l2ByParam" : {
      "b" : 0.0,
      "W" : 5.0E-4
    },
    "layer" : {
      "convolution" : {
        "activationFn" : {
          "ReLU" : { }
        },
        "adamMeanDecay" : "NaN",
        "adamVarDecay" : "NaN",
        "biasInit" : 1.0,
        "biasLearningRate" : 0.01,
        "convolutionMode" : "Truncate",
        "cudnnAlgoMode" : "PREFER_FASTEST",
        "dist" : {
          "mean" : 0.0,
          "std" : 0.01
        },
        "dropOut" : 0.0,
        "epsilon" : "NaN",
        "gradientNormalization" : "RenormalizeL2PerLayer",
        "gradientNormalizationThreshold" : 1.0,
        "kernelSize" : [ 3, 3 ],
        "l1" : 0.0,
        "l1Bias" : 0.0,
        "l2" : 5.0E-4,
        "l2Bias" : 0.0,
        "layerName" : "cnn5",
        "learningRate" : 0.01,
        "learningRateSchedule" : null,
        "momentum" : 0.9,
        "momentumSchedule" : { },
        "nin" : 384,
        "nout" : 256,
        "padding" : [ 1, 1 ],
        "rho" : "NaN",
        "rmsDecay" : "NaN",
        "stride" : [ 1, 1 ],
        "updater" : "NESTEROVS",
        "weightInit" : "DISTRIBUTION"
      }
    },
    "leakyreluAlpha" : 0.0,
    "learningRateByParam" : {
      "b" : 0.01,
      "W" : 0.01
    },
    "learningRatePolicy" : "Step",
    "lrPolicyDecayRate" : 0.1,
    "lrPolicyPower" : "NaN",
    "lrPolicySteps" : 100000.0,
    "maxNumLineSearchIterations" : 5,
    "miniBatch" : false,
    "minimize" : true,
    "numIterations" : 1,
    "optimizationAlgo" : "STOCHASTIC_GRADIENT_DESCENT",
    "pretrain" : false,
    "seed" : 42,
    "stepFunction" : null,
    "useDropConnect" : false,
    "useRegularization" : true,
    "variables" : [ "W", "b" ]
  }, {
    "iterationCount" : 0,
    "l1ByParam" : { },
    "l2ByParam" : { },
    "layer" : {
      "subsampling" : {
        "activationFn" : {
          "ReLU" : { }
        },

**Comment by raver119** [comment]
One of layers has wrong distribution set somehow:
```
"dist" : {
"mean" : 0.0,
"std" : 0.01
},
```
`Normal` distribution identifier is missing somehow. It's not any specific to GPU backend.

**Comment by MikeF23** [comment]
I has used standard example of AlexNet in d4j sources

**Comment by kepricon** [comment]
@MikeF23 please see https://github.com/deeplearning4j/deeplearning4j/pull/3277
