### ISSUE TITLE
Serialization issue: AbstractCache logger should either be static or transient

### ISSUE THREAD

**Issue by yarki** [deeplearning4j/deeplearning4j#3123]
Questionable declaration:
`private Logger logger = LoggerFactory.getLogger(AbstractCache.class);`

Source code:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/word2vec/wordstore/inmemory/AbstractCache.java

**Comment by yarki** [comment]
Otherwise an instance produced on Logback-powered environment will experience deserialization issues on Log4j-powered environment.

**Comment by raver119** [comment]
Fixed in my branch, will merge as other improvements ready.

**Comment by yarki** [comment]
Great, thanks!
