### ISSUE TITLE
Bug in SentenceIteratorConverter class

### ISSUE THREAD

**Issue by silvioOlivastri** [deeplearning4j/deeplearning4j#3125]
Hi,

I think there is a bug into `SentenceIteratorConverter` class [here](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/text/sentenceiterator/interoperability/SentenceIteratorConverter.java#L53) 

My solution is:

```
 @Override
    public LabelledDocument nextDocument() {
        LabelledDocument document = new LabelledDocument();

        document.setContent(backendIterator.nextSentence());
        if (backendIterator instanceof LabelAwareSentenceIterator) {
            List<String> labels = ((LabelAwareSentenceIterator) backendIterator).currentLabels();
            if (labels != null) {
                for (String label : labels) {
                    document.addLabel(label);
                    generator.storeLabel(label);
                }
            } else {
                String label = ((LabelAwareSentenceIterator) backendIterator).currentLabel();
                if (label != null) {
                    document.addLabel(label);
                    generator.storeLabel(label);
                }
            }
        } else if (generator != null)
            document.addLabel(generator.nextLabel());

        return document;
    }
```

from `if (labels != null)` to `if (label != null)`.

**Comment by raver119** [comment]
Yep, clearly a typo. However, there shouldn't be any implementations limited to single label. If there's such an impl - please let us know.

**Comment by silvioOlivastri** [comment]
I use a `MyLabelAwareSentenceIterator` with:

```
@Override
    public synchronized String currentLabel() { return this.currentLabel; }

    @Override
    public synchronized List<String> currentLabels() { return null; }
```

Because I don't need to multiple labels. Obviously, I generated a `Sequence` without Label.
To "fix" them, I wrote:

```
    @Override
    public synchronized List<String> currentLabels() { return Arrays.asList(this.currentLabel); }
```

**Comment by raver119** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/3141

Will be merged later. Thanks for highlighting this issue

**Comment by AlexDBlack** [comment]
Closing - fixed as per previous comment (PR was merged long ago).
