### ISSUE TITLE
Add support for Keras 2

### ISSUE THREAD

**Issue by turambar** [deeplearning4j/deeplearning4j#3129]
For details see:

- blog post: https://blog.keras.io/introducing-keras-2.html
- release notes: https://github.com/fchollet/keras/wiki/Keras-2.0-release-notes
- updated docs: https://keras.io/
- history: https://github.com/fchollet/keras/issues/5299

**Comment by tomthetrainer** [comment]
Any idea on progress with this? @turambar I am referencing this ticket in others, is there a pull request or any other relevant details.

**Comment by maxpumperla** [comment]
done
