### ISSUE TITLE
Fix RNTN Rng like MultiLayer

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#313]
Currently rng for random seed in RNTN not functioning. Use the following from MultiLayer to fix:

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/conf/MultiLayerConfiguration.java#L355

**Comment by agibsonccc** [comment]
Little unclear about this one. It assigns an RNG just fine. If it doesn't find an RNG it uses Nd4j.getRandom().

Just use Nd4j.getRandom().setSeed(yourseed);

It will work transparently. You shouldn't need to specify an RNG either way. 

I'm going to close this.

**Comment by nyghtowl** [comment]
Still an issue setRng is not working and needs to be fixed. Nd4j.getRandom().setSeed(seed) is an alternative so this is a low priority fix.

**Comment by agibsonccc** [comment]
This was an nd4j bug.  Test case:
https://github.com/deeplearning4j/nd4j/blob/40727e2ed6a26c84d4bd1dc62cfb7fd4435147aa/nd4j-tests/src/test/java/org/nd4j/linalg/api/rng/RngTests.java
