### ISSUE TITLE
Arbiter - Setting convolutional as input type in MultiLayerSpace.

### ISSUE THREAD

**Issue by herofe** [deeplearning4j/deeplearning4j#3131]
When creating a MultiLayerSpace with convolutional layers and pooling, using the function
`.setInputType(InputType.convolutionalFlat(...))`
in the Builder() makes the MultiLayerSpace calculate number of inputs to layers incorrect at runtime.

On the other hand if using the deprecated 
`.cnnInputSize(...)`
the MultiLayerSpace is working as expected.

**Comment by agibsonccc** [comment]
Closing in favor of issue on arbiter.
