### ISSUE TITLE
Unit test failures: Regression (v0.5.0 through 0.7.1) tests currently failing on Distribution json

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3136]
```
java.lang.RuntimeException: org.nd4j.shade.jackson.databind.JsonMappingException: Unexpected token (END_OBJECT), expected FIELD_NAME: missing property 'type' that is to contain type id  (for class org.deeplearning4j.nn.conf.distribution.Distribution)
```

**Comment by agibsonccc** [comment]
Failing test: https://github.com/deeplearning4j/deeplearning4j/blob/1f8af820c29cc5567a2c5eaa290f094c4d1492a7/deeplearning4j-core/src/test/java/org/deeplearning4j/regressiontest/RegressionTest060.java#L96-L96

**Comment by AlexDBlack** [comment]
Fixed and passing on this PR; will be merged soon(ish).
https://github.com/deeplearning4j/deeplearning4j/pull/3373
