### ISSUE TITLE
Add section on tuning guide for explaining nan

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#3138]
A lot of folks struggle with what to do with NAN.  Most of the time they don't know about numerical underflow. The tuning section can explain what numerical underflow is.

Even linking to:
http://www.deeplearningbook.org/contents/optimization.html

We should explain what precision is and how that relates gradients being so small they end up being NAN.
They can *try* using double data type instead but it's usually recommended they just retune their net first.

Following the basic tuning tips and monitoring the results is the way to ensure NAN doesn't show up anymore.

**Comment by rkfg** [comment]
Would be also good to explain when and why negative score could appear and whether it's related to underflow and what to look at to fix it.

**Comment by rkfg** [comment]
Also, there's a knob called `Nd4j.ENFORCE_NUMERICAL_STABILITY = true;`, it's been said that this setting is deprecated and should not be used, but it helps to get rid of NaNs. I skimmed through the source and it looks like NaNs are replaced with 1e-5 or something so there's no underflow. It really fixes the score values but it's not clear what are the downsides (except for it being deprecated).

**Comment by raver119** [comment]
Downsides for ENS are simple:
- performance hit. You'll call for additional op after any op.
- you're curing symptoms, not a problem itself. If your network produces NaNs - there's something going wrong way, and NaNs removal won't fix learning process.

**Comment by tomthetrainer** [comment]
I can not find what page is considered our tuning guide, might have to re-org that tuning and optimization navigation panel

**Comment by rkfg** [comment]
@tomthetrainer I explicitly linked it in my comment above.

**Comment by tomthetrainer** [comment]
I have edited that page, added a section on nan.
