### ISSUE TITLE
Amazon EMR Spark DL4J Example

### ISSUE THREAD

**Issue by abholer** [deeplearning4j/deeplearning4j#3142]
Hi,

I built a small example how to execute the TrainingStatsExample spark example on Amazon EMR. Could be usefull for a quickstart guide.

Steps:

1) Build uber jar from dl4j-spark-examples artefact
2) Enter AWS credentials, S3 bucket and other config in java files below
3) Create EMR Instance with AwsEmrInstanceCreate.java
4) Upload uber jar to S3 with AwsUberJarUpload.java
5) Execute Spark step running TrainingStatsExample on EMR with AwsEmrSparkSubmit.java

I am happy if I could help. Keep up the good work.

Regards

Sascha

[awsemrexample.zip](https://github.com/deeplearning4j/deeplearning4j/files/877051/awsemrexample.zip)

**Comment by abholer** [comment]
AwsEmrInstanceCreate withSteps(enableDebugging) seems to cause issues. better remove it.

**Comment by abholer** [comment]
creating StepFactory with region fixes the enableDebugging issue:

StepFactory stepFactory = new StepFactory(builder.getRegion() + ".elasticmapreduce");

**Comment by agibsonccc** [comment]
Oh awesome! Could you submit a pull request to the examples: https://github.com/deeplearning4j/dl4j-examples ?

**Comment by abholer** [comment]
i did some tests on amazon emr using your spark example TrainingStatsExample. 

In my first test I used a single slave. Runtime was 2 hours, 16 minutes.
In my second test i used 4 slaves. Runtime was 2 hours, 5 minutes.

EMR config and spark submit arguments are basically as shown in the example.

**Comment by abholer** [comment]
-i did not do any memory optimizations
-cuda was also not used

is the bad scaling a problem with the example or missing memory optimization/cluster config?

**Comment by abholer** [comment]
https://github.com/deeplearning4j/dl4j-examples/pull/424
