### ISSUE TITLE
issue ClassPathResouce with spark

### ISSUE THREAD

**Issue by TakahiroInabe** [deeplearning4j/deeplearning4j#3144]
**Example:**
java -cp target/datavec-examples-0.8-SNAPSHOT-bin.jar org.datavec.transform.basic.BasicDataVecExample

**Exception:**
Exception in thread "main" java.io.IOException: Not a file: file:/var/folders/sh/32c7kh0n6ll891v9vsh1pk100000gp/T/assistantd

**Reason:**
'org.datavec.api.util.ClassPathResource' creates the "datavec_tmp" file directly under "java.io.tmpdir" when the target resource is in jar format, but spark also creates folders at the same position, so if you have specified the parent directory with textFile of JavaSparkContext for reading , It finds the folder created by spark and fails to read the datavec_tmp file.

**Comment by agibsonccc** [comment]
Moved to: https://github.com/deeplearning4j/deeplearning4j/issues/3144
