### ISSUE TITLE
net output with cudnn requires 35G memory as single chunk

### ISSUE THREAD

**Issue by vzamboni** [deeplearning4j/deeplearning4j#3148]
I'm trying to get the output of a fully-convolutional model(with a conv layer as last layer) on an image and I can see that it is trying to allocate 35G as single chunk.

I'm using tesla k80 on a 60G node with 
scala 2.11
java 1.8
deeplearning4j 0.8.0
cuda 8.0

Stacktrace is here: [https://gist.github.com/vzamboni/5425ae659d942b5fb2623e8b9f183505](https://gist.github.com/vzamboni/5425ae659d942b5fb2623e8b9f183505)

With different images sizes, and with different model input sizes I get different memory allocations.
Image that's causing the 32G alloc is 597, width: 467, channels: 3

The layer that's causing the issue is a convolutional layer, index 7 (the model has 13 layers) with 256 filters, kernel 3, stride 1, padding 1, outH 116, outW 148

**Comment by raver119** [comment]
What was image dimensions and batch size for that 32GB alloc?

**Comment by vzamboni** [comment]
image was height: 597, width: 467, channels: 3 and I'm classifying 1 single image

**Comment by saudet** [comment]
Using the NO_WORKSPACE AlgoMode will probably help for that:
https://github.com/deeplearning4j/deeplearning4j/issues/3064#issuecomment-288151878

**Comment by crockpotveggies** [comment]
@vzamboni did setting the cudnn algorithm preference for your convolution layers solve your issue?

**Comment by vzamboni** [comment]
Sorry for the late reply, actually setting NO_WORKSPACE AlgoMode to all convolutional layers solved the problem and I'm able to use the model.

**Comment by AlexDBlack** [comment]
Resolved - closing this.
I've opened a docs issue so we can get this documented at some point. https://github.com/deeplearning4j/deeplearning4j/issues/3369
