### ISSUE TITLE
ParallelWrapper isn't compatible w/ deserialized updater state

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#3152]
When deserializing a model and continuing training, PW cannot use existing updater state due to how params are copied to workers. @raver119 do you know what the specific issue is there? I can take a look at it.

**Comment by raver119** [comment]
Support for pretrained model should work here: https://github.com/deeplearning4j/deeplearning4j/pull/3141

Would be nice to see your confirmation.

**Comment by crockpotveggies** [comment]
@raver119 I'll have a test ready shortly. Let's get my model working on your branch and then we can confirm the fix works.

**Comment by AlexDBlack** [comment]
This looks fixed to me: both the test (from here https://github.com/deeplearning4j/deeplearning4j/issues/3202) and actually running this on my model (that I previously had an issue with) look ok.
