### ISSUE TITLE
ParallelWrapper + LR schedules not handled correctly?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3153]
LR schedules are derived from the iteration count in the model and updated during training. But the master model doesn't get updated by the averaging process. Learning rate schedules are handled in Spark by manually updating the iteration counts in the master model:

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/dl4j-spark/src/main/java/org/deeplearning4j/spark/impl/paramavg/ParameterAveragingTrainingMaster.java#L929

Furthermore, tests for PW iteration counts like this would be a good idea too:

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/dl4j-spark/src/test/java/org/deeplearning4j/spark/impl/paramavg/TestSparkMultiLayerParameterAveraging.java#L705

**Comment by crockpotveggies** [comment]
![screen shot 2017-03-29 at 10 57 17 pm](https://cloud.githubusercontent.com/assets/1445295/24489569/20c70c5e-14d3-11e7-8173-512ca2b8c162.png)

Confirmed this happens with any model trained with PW. The LR in the image above should be 0.005, but it is 0.1

**Comment by raver119** [comment]
I've fixed it in my branch.
