### ISSUE TITLE
Build issue on current master

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3155]
When using buildmultiplescalaversions.sh - looks like the first build works (Spark 1 + 2.11) but the second (Spark 2 + 2.11) fails

https://gist.github.com/AlexDBlack/2cd549497bd541de1b3d97326a13d4fc

**Comment by huitseeker** [comment]
We can revert https://github.com/deeplearning4j/deeplearning4j/pull/3139 if you need it quick.
