### ISSUE TITLE
The running result of the jar file is different from the running result in IDEA

### ISSUE THREAD

**Issue by initeasylife** [deeplearning4j/deeplearning4j#3156]
I trained the word2vec model in IDEA and output the "model.txt"
everything is OK.
But,I package .jar file with maven,and the output "model.txt" of the jar file is different from the running result in IDEA.There is no error,but two "model.txt" are different(The input file "sentences.txt" is same).

**Comment by agibsonccc** [comment]
This isn't really actionable for us. Please refile the issue on the examples with more context.
