### ISSUE TITLE
RBM deserialization throws NullPointer when trying to load model from 0.6.0 in 0.8.0

### ISSUE THREAD

**Issue by Treiblesschorle** [deeplearning4j/deeplearning4j#3164]
I serialized an RBM + OutputLayer in 0.6.0 and try to deserialize it with 0.8.0 . Loading the Updater and the Config works fine but if I try to set the Parameters of the MultiLayerNetwork I get an NullPointerException. In 0.6.0 I serialized the Model the following way:
https://gist.github.com/Treiblesschorle/438c752bca3e4fc2aaa77c6f98cb0fc7

In 0.8.0 I just do the opposite and try to restore the model like that:
https://gist.github.com/Treiblesschorle/8c9838baf9229dcd2df71b41c9cad089

Then I get an NullPointerException here:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/layers/BasePretrainNetwork.java#L180

because 'getParam(s)' with s=bB returns null.

I'm on Windows 10 x64.

Any suggestions for a workaround?

**Comment by agibsonccc** [comment]
@Treiblesschorle save the params and update your config manually. Reinstantinate your model with the config and call  setParams().

**Comment by Treiblesschorle** [comment]
So changing the variable name from 'bB' to 'vb'? When I do that it tells me that the parameter lengths do not match.

**Comment by Treiblesschorle** [comment]
@agibsonccc any idea?

**Comment by agibsonccc** [comment]
Hmm - not sure RBMs should have only 3 variables: W VB and HB what variables are you seeing?

**Comment by agibsonccc** [comment]
So there should be 3 variables in 0.6.0 b,bb, and w bb was a typo that I think we fixed. Could you verify that there are 3 variables? It might just simply be renaming it.
