### ISSUE TITLE
RNTN shutdown

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#317]
@agibsonccc first merge PR mw_expand_rntn_eval before merging ag_fix_actor_shutdown

The ag_fix_actor_shutdown branch is a start of fixing the RNTN shut down issue. Fit is called multiple times in batch so it cannot be shutdown directly in the method but needs some type of guard to capture when it will no longer be used. Or ActorSystem should be pulled completely.

**Comment by agibsonccc** [comment]
If I remember, you had a branch for this. Can I close this?

**Comment by nyghtowl** [comment]
This lists the branch with the code you started. Its not done and is an outstanding issue till its done or we decide to go with the fix I put in place.

**Comment by nyghtowl** [comment]
Was fixed. RNTN is not currently working but this can be reopened if needed when RNTN is fixed.
