### ISSUE TITLE
How to predict unlabelled data with trained model in spark

### ISSUE THREAD

**Issue by mykidong** [deeplearning4j/deeplearning4j#3171]
Hi,

I have written some codes as below to predict unlabelled dataset using broadcasting trained model in spark, but I am not sure if it is correct:

        JavaRDD<DataSet> unLabelledData = ...;

        log.info("***** Load the model *****");
        File modelPath = new File("target/mnist-model.zip");
        //Load the model
        MultiLayerNetwork restored = ModelSerializer.restoreMultiLayerNetwork(modelPath);

        // broadcast trained model.
        Broadcast<MultiLayerNetwork> broadcastModel = sc.broadcast(restored);

        log.info("***** Predict unlabelled dataset *****");
        unLabelledData.foreach(new Predict(broadcastModel));

        ........................

        private static class Predict implements VoidFunction<DataSet> {
            private Broadcast<MultiLayerNetwork> broadcastModel;

            public Predict(Broadcast<MultiLayerNetwork> broadcastModel) {
                this.broadcastModel = broadcastModel;
            }

            @Override
            public void call(DataSet dataSet) throws Exception {
                // TODO: This way is correct???????
                int[] predicted = broadcastModel.getValue().predict(dataSet.getFeatures());

                System.out.println("predicted: " + Arrays.toString(predicted));
            }
        }

If it is not correct way, could you show me some examples to predict unlabelled data in spark?

- Kidong Lee.

**Comment by agibsonccc** [comment]
Just use network.output from the actual spark next itself. You wouldn't use the .predict method. We have tons of examples of how to do this in the dl4j examples already. Use a foreach on an rdd dataset if you'd like.
