### ISSUE TITLE
task can never be finished when dl4j/word2vec+spark+cuda

### ISSUE THREAD

**Issue by linzaihui** [deeplearning4j/deeplearning4j#3172]
I use Class org.deeplearning4j.spark.models.embeddings.word2vec.Word2Vec to do word-embedding with multiple GPUs. And have a problem, tasks on stage 4 can never get finished. I paste some code and log.
Code:
SparkConf sparkConf = new SparkConf()
       		.setMaster("local[*]").setAppName("WordEmbedding")
	        .set("spark.driver.maxResultSize","8g")
	        .set("spark.driver.memory", "16g")
	        .set("spark.executor.memory","16g");
        // Set SparkContext
        JavaSparkContext sc = new JavaSparkContext(sparkConf);
        Word2Vec vec = new Word2Vec.Builder()
	        .setNGrams(1)
	        .tokenizerFactory("com.gci.dl.word2vec.SimpleTokenizerFactory")
	        .seed(42L)
	        .negative(10)
	        .useAdaGrad(false)
	        .layerSize(conf.getLayerSize())
	        .windowSize(conf.getWindowSize())
	        .learningRate(0.025)
	        .minLearningRate(0.0001)
	        .iterations(conf.getIterations())
	        .batchSize(100)
	        .minWordFrequency(conf.getMinWordFrequency())
	        .useUnknown(true)
	        .build();

        JavaRDD<String> data=sc.textFile(conf.getFolder());//a folder of 600 files, totally 2.85MB
	vec.train(data);
pom.xml
	<properties>
		<nd4j.backend>nd4j-cuda-8.0-platform</nd4j.backend>
		<maven.javadoc.skip>true</maven.javadoc.skip>
		<source.skip>true</source.skip>
		<dl4j.version>0.8.0</dl4j.version>
	</properties>
	<dependencies>
		
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-nlp</artifactId>
			<version>${dl4j.version}</version>
		</dependency>
		
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-cuda-8.0</artifactId>
			<version>${dl4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-cuda-8.0</artifactId>
			<version>${dl4j.version}</version>
			<classifier>linux-x86_64</classifier>
		</dependency>
		
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>dl4j-spark_2.11</artifactId>
			<version>${dl4j.version}_spark_2</version>
		</dependency>
		
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>dl4j-spark-nlp_2.11</artifactId>
			<version>${dl4j.version}_spark_2</version>
		</dependency>

log:
14:54:45,672 INFO  ~ Running Spark version 2.1.0
14:54:45,903 WARN  ~ Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
14:54:46,007 WARN  ~ Your hostname, user-Super-Server resolves to a loopback address: 127.0.1.1; using 192.168.6.144 instead (on interface eno2)
14:54:46,008 WARN  ~ Set SPARK_LOCAL_IP if you need to bind to another address
...
14:55:27,263 INFO  ~ Found block rdd_4_3 locally
14:55:27,263 INFO  ~ Found block rdd_5_3 locally
14:55:27,264 INFO  ~ Block rdd_7_3 stored as values in memory (estimated size 1448.0 B, free 8.7 GB)
14:55:27,264 INFO  ~ Added rdd_7_3 in memory on 192.168.6.144:40225 (size: 1448.0 B, free: 8.7 GB)
14:55:35,136 INFO  ~ Number of threads used for BLAS: 0
15:06:09,302 INFO  ~ Finished task 12.0 in stage 4.0 (TID 2412). 873908 bytes result sent to driver
15:06:09,306 INFO  ~ Starting task 56.0 in stage 4.0 (TID 2456, localhost, executor driver, partition 56, PROCESS_LOCAL, 6338 bytes)
15:06:09,307 INFO  ~ Running task 56.0 in stage 4.0 (TID 2456)
--at the end of log

**Comment by raver119** [comment]
There's no way old implementation will be efficient enough on cuda with spark.

We have alpha-version of new spark nlp implementation that uses parameter server approach, but it isn't polished enough yet.
