### ISSUE TITLE
Workspaces & model use, aka inference

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#3175]
Ok, we introduce workspaces for models training, to ensure better performance. 
But that also brings another problem: workspace memory exposure.

Methods like model.activations() or feedforward() signatures might bring INDArrays attached to workspaces out of real scope, thus out of any deallocation control. So we probably should review signatures exposing INDArrays out of MLN/CG models.

Plus, it adds complexity for inference using any given model: Some model can be quite big int terms of memory use, and can be measured in gigabytes. So, once workspace is initialized for some model, it should be better to reuse one given model (i.e. one per device) then trying to bring up multiple independent models. So, as we've discussed before - now it's ideal time to introduce ParallelInference thing, similar to ParallelWrapper, that'll reuse existing model by either batching, or serial queue. Or both hehe.

@agibsonccc @AlexDBlack @saudet what's your thoughts here guys?

**Comment by agibsonccc** [comment]
I would say maybe take a crack at ParallelInference and see what that looks like with real code first? We can do a review of that perhaps after we understand the dynamics there? I already do something like this internally anyways - it wouldn't be hard to build something like this I'd imagine.

**Comment by raver119** [comment]
ParallelInference isn't a big deal, i already have draft for it, so tomorrow i'll have prototype running at least for sequential inference. Memory is main concern here.

**Comment by agibsonccc** [comment]
Summarizing my thoughts in gitter: Automate/hide this as much as possible. If we can start by pre encoding this in the mln/CG itself we can and should hit most cases like that.
 Touching this directly should only be for power users.

**Comment by raver119** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/3183

**Comment by raver119** [comment]
Implemented long ago.
