### ISSUE TITLE
Gradient calculation of RBM

### ISSUE THREAD

**Issue by doerrhoefer-clemens** [deeplearning4j/deeplearning4j#3176]
#### Gradient as in Learning Deep Architectures for AI by Yoshua Bengio 

I am implementing Semantic Hashing from Ruslan Salakhutdinov and Geoffrey Hinton so I expanded the RBM class with a Poisson distribution and sampling. And I stumbled upon a discrepancy in the calculation of the wGradient.
In the original code it is calculated as
input().transposei().mmul(probHidden.getFirst()).subi(**negVProb**.transpose().mmul(negHProb));

But according to Learning Deep Architectures for AI Algorithm 1 the gradient is calculated as 
W <- W + epsilon*(h_1*x' - Q(h_2=1|x_2)x_2')
So in my opinion it the correct gradient should be
input().transposei().mmul(probHidden.getFirst()).subi(**negVSamples**.transpose().mmul(negHProb));

Both Versions should work.

**Comment by agibsonccc** [comment]
Closing this in favor of: https://github.com/deeplearning4j/deeplearning4j/issues/3057
