### ISSUE TITLE
SparkDl4jMultilayer bug for the predict method when using an LSTM

### ISSUE THREAD

**Issue by dmmiller612** [deeplearning4j/deeplearning4j#3182]
I currently get the exception: 

`java.lang.IllegalArgumentException: passed in array must be a vector`

when using an LSTM multiLayerConfiguration with SparkDl4jMultilayer. I see what is happening, and I could fix it, however, there may be a cleaner way that you guys know of. Here is the mlConfiguration, which was taken from the example repo. I was doing a little bit of a bug hunt with the spark-ml module, and found this, even when hitting SparkDl4jMultilayer directly.

```
    private MultiLayerConfiguration getNN2() {
        return new NeuralNetConfiguration.Builder()
                .seed(123)    //Random number generator seed for improved repeatability. Optional.
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT).iterations(1)
                .weightInit(WeightInit.XAVIER)
                .updater(Updater.NESTEROVS).momentum(0.9)
                .learningRate(0.005)
                .gradientNormalization(GradientNormalization.ClipElementWiseAbsoluteValue)  //Not always required, but helps with this data set
                .gradientNormalizationThreshold(0.5)
                .list()
                .layer(0, new GravesLSTM.Builder().activation(Activation.TANH).nIn(2).nOut(10).build())
                .layer(1, new RnnOutputLayer.Builder(LossFunctions.LossFunction.MCXENT)
                        .activation(Activation.SOFTMAX).nIn(10).nOut(2).build())
                .pretrain(false).backprop(true).build();
    }
```

Basically, what I see happening is in 'predict' in class SparkDl4jMultilayer (or the code here):

```
    public Vector predict(Vector point) {
        return MLLibUtil.toVector(network.output(MLLibUtil.toVector(point)));
    }
```

`network.output(MLLibUtil.toVector(point))` is setting the shape of the output from [.01, .99] to [[.01, .99]]. When it hits MLLibUtil.toVector, it has a check called 'isVector' on the INDArray, and since the shape is different, it is causing it to fail. We could flatten this vector, if its shape has changed in the SparkMultiLayerNetwork. But that might be covering another internal bug. That part I don't know.

I could also be doing something wrong as well. 

So to recap, to reproduce, you can just create a SparkMultilayerNetwork, using the configuration from above (or any RNN config), then create a spark mllib vector using something like `Vectors.dense(.01,.02,.03)`, then hit 'predict' on SparkMultilayerNetwork. I am using DL4J 0.8.0, I have found the bug when using gpus and cpus, and Spark 2 and 1 (both seemed to have problems). This has failed on g2.2xlarges (amazon), r3.xlarge, and my personal mac computer.

**Comment by dmmiller612** [comment]
The flatten solution would change this method:

```
    public static Vector toVector(INDArray arr) {
        if (!arr.isVector()) {
            throw new IllegalArgumentException("passed in array must be a vector");
        }
        double[] ret = new double[arr.length()];
        for (int i = 0; i < arr.length(); i++) {
            ret[i] = arr.getDouble(i);
        }

        return Vectors.dense(ret);
    }
```

to something like with maybe a sanity exception or something:

```
    public static Vector toVector(INDArray arr) {
        return Vectors.dense(arr.data().asDouble());
    }
```

Can we always reliably rely on FloatBuffer's asDouble method (I am assuming we can). Since it is implied that it should be returning a vector, would it be too big of a step to flatten it?

**Comment by agibsonccc** [comment]
What concerns me about running predict with spark.ml and assuming it's a vector for RNNs is: Spark.ml's api literally can't handle tensors. I'm not sure how you expect to  run a prediction like that.

**Comment by dmmiller612** [comment]
Yeah, both spark ml and mllib have this problem right now. Should there be something that warns someone of this shortcoming when using rnns with spark multilayer? Are there times where the rnn outputlayer with spark would return something like `[[1.0, 2.0], [3.0,4.0]]`, or will it always be like above?

**Comment by dmmiller612** [comment]
I am going to close this if that is okay, since we at least found a work around.
