### ISSUE TITLE
Memory Isolation (working arrays and layer fields)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3183]
(Opened after discussion with @raver119 )

Currently: users can access just about anything: inputs, epsilons, layer fields, etc. With the previous/existing memory management, this was OK. With workspaces: this design is unsafe as INDArrays could be out of scope (getLayer(int).getInput().doSomething() -> things explode).
Of course, we *can* make everything accessible safe - at the cost of performance.

Ultimately, the question is: **what information/arrays should users have access to, for any given task?**

Some initial thoughts:
- **Fit methods (fit(DataSet), fit(DataSetIterator) etc)**: users should not have access to inputs, activations, errors, masks or (where relevant) TBPTT state. The net should be left in a "clean" state after these operations (and consequently, workspaces can be used for *everything* allocated with a fit operation)
- **Activate/feedForward methods**: Perhaps users should only have access to the returned arrays, with all other fields/arrays cleared as per the fit methods
    - This would allow for higher efficiency (i.e., output -> only one array has to be taken from workspace, or not allocated to workspace in the first place)
    - However, that would means that some things, (like MultiLayerNetwork.backpropGradient(INDArray epsilon)) would have to work differently (i.e., currently it relies on the user doing a feedForward call first, so the stored inputs could be reused during the backprop step)
- **rnnTimeStep and similar**: users need to have access to the stored RNN state, however we should intercept the calls and ensure they are removed from the workspace (if necessary)

Another option (instead of clearing the layers - this which would give us thread safety too) is to remove the input/epsilon/whatever fields from Layers entirely, and store them in a separate object (created by MLN/CG). This would get passed to the layer for forward/backward operations, so there is no stored state for users (or other threads) to get. With workspaces, working memory is already thread safe so it's just input/epsilon fields.

@raver119 has also mentioned cleaning up and standardizing the interfaces (Model, or some sub-interface) between MLN and CG; the idea being that anything on this interface would be safe, anything else would not be.

**Comment by raver119** [comment]
re: States. I'm totally agree with your state-flush suggestion. No state preserved - no issues will ever happen. So  cleansing loop that'll nullify corresponding fields - is certainly worth consideration here. Fast & efficient solution for part of this problem.

re: Activate & feedForward methods. CG has 5 different public feedForward signatures. MLN has 9 signatures.  11 different public activate() signatures for MLN. Do users REALLY need that zoo? Let's narrow the list down to 1-2 signatures which will be universal, and will give user what he wants, just detached from any workspaces. 

re: RNN, RBM, Encoders: Edge case. Obviously there are special methods/states important for model use. But once we have explicit list of such methods, we can ensure the same as above: if user-space method is called - we return INDArrays detached from any workspaces. If model-space method is called - general rules apply.

**Comment by raver119** [comment]
cc @agibsonccc

**Comment by raver119** [comment]
Ah, and while we're working on this. Let's unify DataSet & MultiDataSet interfaces. Basically our DataSet is MultiDataSet that's limited to single INDArrays for all possible fields :)

**Comment by AlexDBlack** [comment]
DataSet has a lot of methods that are single-array specific, and extra methods that aren't widely used in practice (and would be a pain to implement for multiple arrays). I'm up for making DataSet the standard/only one (remove those methods, make the DataSet interface extend the MultiDataSet interface) if we clean those up though. That will definitely be a breaking change though.

**Comment by fac2003** [comment]
Regarding the DataSet, MultiDataSet design. You could probably have a facade:

an object that wraps a DataSet, but extends MultiDataSet. Then, write all the DL4J code against the MultiDataSet interface . Anybody who does not want to deal with the complexity of MultiDataSet (or has already implemented DataSet) only needs to wrap it into a facade instance before calling DL4J methods with the facade.

I have not looked into the DataSet methods in a while, but a facade seems an option to consider if all methods of a MultiDataSet can be implemented as functions of the DataSet methods.

**Comment by raver119** [comment]
Yep, facade pattern is definitely an option here if we want those methods from DataSet.

**Comment by AlexDBlack** [comment]
Closing this - fit ops etc now consistently clear layer states. Accessing leaked arrays out of scope should be much more difficult now.
