### ISSUE TITLE
Why dl4j too consume memory？？？

### ISSUE THREAD

**Issue by yangxueping** [deeplearning4j/deeplearning4j#3184]
#### Issue Description

why dl4j too consume memory? why?  
My corpus size is 2.5G, but it uses light on all the workers on the memory, about 30g memory

#### Version Information

* Deeplearning4j version  0.8.0
* spark 2.1.0  on standalone(master 2 cores 8G, worker 4 cores 16G)
* use CPU

#### Contributing
I training my lstm model.

this is my spark-submit:
nohup spark-submit --class com.godwom.nlp.app.sentiment.Main --master spark://master:7077 --driver-memory 6G --executor-memory 6G --conf "spark.executor.extraJavaOptions=-Dorg.bytedeco.javacpp.maxbytes=8589934592"   --conf spark.standalone.executor.memoryOverhead=8704 --conf spark.locality.wait=0 sparkapp-sentiment-1.0-SNAPSHOT.jar /bitbeyond-data/rawdata/comment/20170322/jd/* &

**Comment by raver119** [comment]
We're actively working on this issue: https://github.com/deeplearning4j/nd4j/pull/1731

**Comment by AlexDBlack** [comment]
Closing this - workspaces are now merged, and memory consumption is considerably reduced on master when it is enabled.
