### ISSUE TITLE
Is SparkParagraphVectors  unfinished?

### ISSUE THREAD

**Issue by JoseCaravaca** [deeplearning4j/deeplearning4j#3185]
Hello,

I built a system using ParagraphVectors without spark and the library works properly. However, now I am trying to build a system using SparkParagraphVectors, I know I have to use different classes and methods but I found many methods that seem to be incomplete.

For example, I can't instantiate an object of SparkParagraphVectors because the constructor is protected and the class doesn't have a Builder, so I am using SparkSequenceVectors. Or the class SparkDM, which always throws an exception because its getTrainingDriver method always returns null.

I'm using maven with the following dependency:
<dependency>
	<groupId>org.deeplearning4j</groupId>
	<artifactId>dl4j-spark-nlp-java8_2.10</artifactId>
	<version>0.8.0_spark_1</version>
</dependency>

So my question is, are these classes incomplete or am I using them in a bad way?

**Comment by raver119** [comment]
Sorry, this stuff will be ready & announced in next release only.
