### ISSUE TITLE
Wrong Z value returned by MultiLayerNetwork.computeZ

### ISSUE THREAD

**Issue by BartKeulen** [deeplearning4j/deeplearning4j#3191]
#### Issue Description

When computing the z values of a model using the [computeZ](https://deeplearning4j.org/doc/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.html#computeZ-org.nd4j.linalg.api.ndarray.INDArray-boolean-) function it returns the wrong values. The problem can be viewed with this [gist](https://gist.github.com/BartKeulen/00ef00291338f1ad662089f62439a374).

- Expected: The z-value is calculated using the activations of the previous layer.
- Encountered: The z-value is calculated using the z-values of the previous layer.

The gist outputs the z-values for all four layers and the preOutput value. The z-value for the fourth layer should be similar to the preOutput value, this is not the case. The z-value of the third layer is not correct either, at the bottom of the script I have added some code that calculates the correct z-values. Using different activation functions for the hidden layer does not change the values return by computeZ. 

#### Version Information

* Deeplearning4j version: 0.8.0
* OS: Ubuntu 16.04.1 LTS
* Java version: 1.8.0_121

#### Contributing

At the bottom of the gist I have included a script for computing the correct z-values. If you agree with this method I can create a pull request (first time so didn't want to do it immediately).

**Comment by raver119** [comment]
side note: @AlexDBlack see that gist? That's what i'm afraid of...

https://github.com/deeplearning4j/deeplearning4j/issues/3183

**Comment by AlexDBlack** [comment]
Yeah, computeZ is wrong - it should be passing activation functions (not pre-out) to the next layer.
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java#L639

We'll need to call both preOut (to return) and activate (to do the forward pass) on each layer. That's inefficient but necessary, as in some cases (like LSTM) activations don't cleanly decompose into activationFn(preOut).

**Comment by AlexDBlack** [comment]
Fixed here: will be merged soon.
https://github.com/deeplearning4j/deeplearning4j/pull/3358

**Comment by agibsonccc** [comment]
Of note - snapshots are available so you can get the fix now.
