### ISSUE TITLE
Integrate model-zoo natively with DL4J

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#3196]
#### Issue Description

Currently dl4j-model-z sits in a separate standalone repo and has fallen behind with DL4J development. In addition, it's nearly impossible to infer default dimensions for inputs and test model stability as development progresses.

This issue proposes a native project module that is user-friendly which provides the following functionality:

- models are accessible by adding a maven dependency
- model configurations can be built, imported, and "transferred"
- pretrained models can also be imported and downloaded from a central repository

#### Version Information

SNAPSHOT and future development

#### Contributing

I've currently rebuilt models from our zoo for popular CNNs in benchmarks as well as have built a model selector with metadata. I'm hopeful this can be migrated into a proper module.

**Comment by crockpotveggies** [comment]
cc @tomthetrainer @agibsonccc

**Comment by huitseeker** [comment]
👍 👏
