### ISSUE TITLE
Conv Layer number of feature maps pulling from number of channels

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#321]
Current understanding is number of feature maps is in the first position of the filterSize parameters. In ConvolutionUtils, the numFeatureMaps methods pulls from the second position in filterSize (e.g. where channels are set) vs the first position of the list. 

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/util/ConvolutionUtils.java#L78

In ConvolutionLayer, this line appears to set the featureMaps number:  https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/convolution/ConvolutionLayer.java#L113

The line after it looks like its setting channels. However, both use the same numFeatureMaps method for determining their value and in the case of CNNMnist example they both equal 1 when filterSize is {8,1,28,28}.

**Comment by agibsonccc** [comment]
The second number should be number of channels.

**Comment by nyghtowl** [comment]
ConvolutionUtils numFeatureMaps should point to shape[0] vs shape[1] if its setting number of feature maps.

**Comment by agibsonccc** [comment]
Submit a PR

**Comment by nyghtowl** [comment]
Yeah logging as issue. Will need to do more digging to figure out what specifically needs to change and its ripple effects.

**Comment by agibsonccc** [comment]
This is fixed now. Will merge gradientupdate branch today.
