### ISSUE TITLE
Setting learingRateSchedule with large map kills performance

### ISSUE THREAD

**Issue by DanPederEriksen** [deeplearning4j/deeplearning4j#3211]
Steps to reproduce:
In MultiGpuLenetMnistExample.java
1. Comment out the line setting learning rate
`//.learningRate(.01)//.biasLearningRate(0.02)`
2. Add the following two lines just below setting the learning rate.
`.learningRateSchedule(learningRateSchedule(3307, 0.99))
.learningRateDecayPolicy(LearningRatePolicy.Schedule)`
3. Add this method to the end of the file.
`private static Map<Integer, Double> learningRateSchedule(int miniBatches, double decayFactor) {
        Map<Integer, Double> learningRateSchedule = new HashMap<>();
        double lr = .01;
        int count = 0;
        for (int i = 0; i < 1000; i++) {
            for (int j = 0; j < miniBatches; j++) {
                learningRateSchedule.put(count, lr);
                count++;
            }
            lr *= decayFactor;
        }
        return learningRateSchedule;
    }`

4. Run the example.

Expected result:
Takes about the same time to run.

Actual result:
Getting to interation 200 took 12 minutes. Compared to not changing the code it took 30 seconds.
 
  
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.8.0
* platform information (OS, etc): Windows 10
* CUDA version: 8
* NVIDIA driver version: NVidia Geforce GTX 1080 Ti 21.21.13.7892

**Comment by crockpotveggies** [comment]
Can you tell us the object count in `learningRateSchedule`? Simple debugger breakpoint on `return learningRateSchedule;` and using the IntelliJ "Evaluate Expression" interface should let you call `.size()` and display it.

**Comment by DanPederEriksen** [comment]
The size in the example I gave is 3307000. 

The performance impact can also be seen with lower numbers. E.g. When the map is of size 33070 the first epoch completes in 29047ms. When no schedule is used epoch completion time is 18774ms.

**Comment by crockpotveggies** [comment]
> 3307000

So 3 million objects? That's the direct cause there. What's happening is not DL4J at all, but you're seeing JVM garbage collection pausing everything. Why such a huge learning rate schedule? What's the use case?

Even 33,000 objects is a lot. Again, that's java GC (pausing to check every object reference in that map). The only option here is to move the collection off-heap. There are a couple libraries that assist with this, but you'll need to ensure it is a compatible type.

**Comment by crockpotveggies** [comment]
p.s. are you trying to set a learning rate for each iteration? You actually doing need to do that.

You can simply do this:

```
    Map<Integer, Double> lrSchedule = new HashMap<>();
    lrSchedule.put(0, 1.0);
    lrSchedule.put(100, 0.1);
    lrSchedule.put(150000, 0.01);
    lrSchedule.put(300000, 0.005);
    lrSchedule.put(800000, 0.001);
```

**Comment by DanPederEriksen** [comment]
Yes, I was trying to set the learning rate every iteration. I thought I had to... Your example clearly shows that is not the case.

Only setting learningrate for every epoch does solve the issue for me. 

Thank you for your help.

**Comment by crockpotveggies** [comment]
@DanPederEriksen thanks! I also updated our examples and documentation so future users don't make the same mistake :)
