### ISSUE TITLE
the UI just says loading and the browser console is throwing exceptions.

### ISSUE THREAD

**Issue by copypasteearth** [deeplearning4j/deeplearning4j#3215]
UI just text and says "loading" everywhere console is throwing exceptions

using the latest version of chrome
57.0.2987.133 (Official Build) (64-bit)
windows 7
hewlet packard
HP Envy 14 notebook
intel i5 cpu m480 2.76ghz
ram 4gb
latest deeplearning4j

chrome log
```
Uncaught ReferenceError: $ is not defined
    at overview:250
overview:258 Uncaught ReferenceError: renderOverviewPage is not defined
    at overview:258
overview:258 Uncaught ReferenceError: renderOverviewPage is not defined
    at overview:258
(anonymous) @ overview:258
overview:258 Uncaught ReferenceError: renderOverviewPage is not defined
    at overview:258
(anonymous) @ overview:258
overview:258 Uncaught ReferenceError: renderOverviewPage is not defined
    at overview:258
(anonymous) @ overview:258
overview:258 Uncaught ReferenceError: renderOverviewPage is not defined
    at overview:258
(anonymous) @ overview:258
```
java log

o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 2
o.n.n.Nd4jBlas - Number of threads used for BLAS: 2
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 7]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [4]; Memory: [0.8GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [OPENBLAS]

o.d.u.p.PlayUIServer - UI Server started at http://localhost:9000
o.d.u.p.PlayUIServer - StatsStorage instance attached to UI: InMemoryStatsStorage(uid=8f1d0b29)

**Comment by AlexDBlack** [comment]
Probably the same issue as this: https://github.com/deeplearning4j/deeplearning4j/issues/3121
Unfortunately at this point: (a) I don't know what's happening, and (b) don't have a way to reproduce it.

The only other thing I can think to ask: how exactly are you running your project? Via an IDE (IntelliJ, Eclipse?) or building and running a JAR (using maven shade or similar)?

**Comment by copypasteearth** [comment]
Im running on intellij, i upgraded to windows 10 and still the same problem. I tried chrome, edge and android (through chrome) all the same problem. Through the console i see assets/css folder but i dont see assets/js folder which is referenced in the <script>

**Comment by AlexDBlack** [comment]
Thanks. At this point: it's most likely something to do with the backend (asset routing/serving) and not the front-end itself. So the browser probably won't matter (thanks for testing though). An issue with packaging (bad shade config or similar meaning assets are absent) might have explained it, but if you are running directly through IntelliJ, you should be fine.

For the record, I'm running Windows 10 and haven't run into any issues like this before.

One final thing: can you run this in your project, and tell me what you get?
```
        import org.nd4j.linalg.io.ClassPathResource;

        ClassPathResource cpr = new ClassPathResource("deeplearning4jUiAssets/js/train/overview.js");
        System.out.println("Exists: " + cpr.exists());
```

**Comment by copypasteearth** [comment]
it returned true.

**Comment by AlexDBlack** [comment]
Odd. So the asset is available on the classpath, and it *should* be able to serve it.

One last idea: can you add breakpoints on all of the return statements here, and tell me which return statement it is hitting for that file? I'm thinking maybe there's an unchecked exception that's getting swallowed or something... either that, or there's a problem with reading the contents from the input stream.

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-ui-parent/deeplearning4j-play/src/main/java/org/deeplearning4j/ui/play/staticroutes/Assets.java

**Comment by copypasteearth** [comment]
the debugger wont pause at those breakpoints because they are in jars i think i just tried.

**Comment by AlexDBlack** [comment]
No worries. Usually you can just open the class (easiest: import the Assets class into any class -> click on the import statement -> ctrl + B) then add your breakpoints and run in debug mode. You'll need to manually open your browser and navigate to ```http://localhost:9000/assets/js/train/overview.js``` before it'll try to execute that code path. Let me know if you get it working.

**Comment by copypasteearth** [comment]
i hit ctrl + B on the import statement and it says cannot find declaration to go to

**Comment by copypasteearth** [comment]
i tried it like this

Assets ass = new Assets("deeplearning4jUiAssets/js/train/overview.js");
  -->breakpoint      ass.apply("deeplearning4jUiAssets/js/train/overview.js");

and then i got caught on the input stream, if im doing it right i imported the class and did the 2 lines above

 try {
            inputStream = new ClassPathResource(fullPath).getInputStream();
        } catch (Exception e) {
            log.debug("Could not find asset: {}", s);
    ->>        return ok();
        } catch (Throwable t) {
            return ok();
        }

**Comment by AlexDBlack** [comment]
OK, so it's returning where you've marked ```->> return ok();```? Great, that's progress.
Can you give me more details for that exception? i.e., the message, and any stack trace info you can see (or, just expand them in the debugger and post a screenshot)

**Comment by copypasteearth** [comment]
i actually got it to use the breakpoints from the UIExample instead of what i posted up there, looks like a filenotfoundexception

![debug](https://cloud.githubusercontent.com/assets/6181334/24860588/57b58706-1dc3-11e7-9eb1-32fd67906e27.PNG)

**Comment by copypasteearth** [comment]
do you think its the spaces in my folder name %20?

**Comment by AlexDBlack** [comment]
Great, that's very helpful. 👍 
I'm guessing it's probably due to spaces in the path (which I don't have on my system - explaining why I haven't been able to reproduce before). If that is the cause, should be able to reproduce it - and hopefully fix it - now.

**Comment by copypasteearth** [comment]
can i just rename my folder or is intellij, or maven already have it registered or something as it is?

**Comment by copypasteearth** [comment]
keep me posted on what to do to get it running ok? i would just like to have it running by about the middle of may thats when im going to really dive in on summer break

**Comment by AlexDBlack** [comment]
One workaround may be to use maven shade to build a jar file that includes the resources; if that is run from a location that doesn't have spaces in the path, it *should* work (if indeed that is the cause).

**Comment by copypasteearth** [comment]
well keep me posted on if you can fix the problem and when i can reclone the repository

**Comment by copypasteearth** [comment]
i just made a new user on windows 10 with no spaces in the user folder name and the UIExample ran perfectly.  It was definetly the spaces in the folder name
