### ISSUE TITLE
Problem loading RBM model from 0.6.0 in 0.8.0

### ISSUE THREAD

**Issue by Treiblesschorle** [deeplearning4j/deeplearning4j#3218]
For original problem description see: https://github.com/deeplearning4j/deeplearning4j/issues/3164

The model from 0.6.0 I'm trying to load in 0.8.0
[rbm_model_.0.6.0.zip](https://github.com/deeplearning4j/deeplearning4j/files/909425/rbm_model_.0.6.0.zip)

It contains the model config as json, the updater saved using an ObjectOutputStream, and the model parameter. The original problem was that a variable was missing (see mentioned issue) so it threw an NPE when I tried loading it in 0.8.0. The model from 0.6.0 contains the parameters "bB", "b", "W".

I tried renaming the variable "bB" to "vB" manually. However, then I get an error that the parameter lengths do not match anymore.

Code to reproduce in 0.8.0 using the .zip I provided:
https://gist.github.com/Treiblesschorle/f6aa1d208ccc9cf965c6dceb9e39a21e

Parameter Array lengths ( model.params().length() ):
0.8.0 : 236585
0.6.0 : 235801

**Comment by Treiblesschorle** [comment]
@agibsonccc new issue as discussed with @dietzc

**Comment by dietzc** [comment]
any news on this? @agibsonccc

**Comment by agibsonccc** [comment]
@dietzc sorry haven't been able to get to this yet - let me briefly look at this tomorrow.

**Comment by dietzc** [comment]
great, thanks!

**Comment by agibsonccc** [comment]
Can I get the code for both 0.6.0 and 0.8.0 as well?

**Comment by Treiblesschorle** [comment]
There is a link to a gist (https://gist.github.com/Treiblesschorle/f6aa1d208ccc9cf965c6dceb9e39a21e) in the issue description. The code is the same for both versions.

**Comment by agibsonccc** [comment]
@Treiblesschorle what I would like is the intended model config as a java file though.

**Comment by Treiblesschorle** [comment]
Like this? : https://gist.github.com/Treiblesschorle/aa3ec05efeea26af5df6667cb18dd9a9
Code is the same for both versions.

**Comment by agibsonccc** [comment]
thanks!

**Comment by dietzc** [comment]
any news on this?

**Comment by AlexDBlack** [comment]
I recall that at one point, the RBM visible bias parameters weren't included in the full net parameters array (it was used for backprop params only). I can't remember exactly when that change happened, but before that the visible biases weren't being saved and aren't won't be there to be re-loaded in later versions.

Assuming that's the case, there's not really much we can do to fix it. The only workaround I can think of is manually load the config, then manually load the params, split them up manually (order is weights then biases for each layer), use setParam() on each layer, and leave the visible biases as zeros. That's a fair bit of work and might not be viable.

So I'm going to close this as a 'do not fix' - we *could* in principle implement manual backward compatibility to do what I mentioned above, but that's a lot of work and I don't think it has high enough ROI for us to look at it.

**Comment by agibsonccc** [comment]
Yeah that *would* explain some things. That was mainly what I was hoping to understand was *if* it was actually fixable. Looking at this it appears not to be the bcase.
