### ISSUE TITLE
Options for deeplearning4j-keras module

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#3219]
#### Issue Description

Currently we have an incomplete module `deeplearning4j-keras` sitting in master branch. This module only really works for Docker environments and using `network.fit()` in python. Since @agibsonccc has created https://github.com/deeplearning4j/jumpy the approach that this module has taken is obsolete.

It would appear the users who originally tested it are no longer using it. Additionally, jumpy will provide superior keras support and provide a better path to keras backend integration.

Opening this issue to assess options:
- Do we delete the module and remove it from master?
- Do we let the module remain until jumpy is ready?

**Comment by maxpumperla** [comment]
@crockpotveggies @agibsonccc there was some activity lately (month ago) on `deeplearning4j-keras`. Is that module still alive? Shall we keep it for now?

**Comment by crockpotveggies** [comment]
@maxpumperla sorry late reply here, we should retire that module.
