### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by benjaminhviid** [deeplearning4j/deeplearning4j#3220]
When I try to evaluate my network, I receive this error:

 ```
A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0xa) at pc=0x0000000129607b10, pid=1359, tid=0x0000000000001c03
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libnd4j.dylib+0x4ab10]  simdOps::Im2col<float>::execSpecial(float*, int*, float*, int*, float*, int*, int*) (._omp_fn.804)+0x3b0
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/benjaminhviid/FPSAgent-master/TorcsSupervisedLearning/hs_err_pid1359.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

I have included (hopefully) all appropriate scripts in this gist: gist: https://gist.github.com/benjaminhviid/fd895f3432e72c5f5530c74e3c8ae961

I have narrowed the issue down to line 60 in `Evaluator.java`: 
`INDArray output = network.output(Nd4j.create(ImageTool.toScaledDoubles(td.getPixelData()), new int[] { 8, 3, td.getWidth(), td.getHeight()}), false);`

I have ensured that the values in the int array are correct, as well as the size of the byte array returned by `td.getPixelData()`. I also use `ImageTool.toScaledDoubles(byte[] pixels)` without problems when I train my network, so I suspect that the problem is with `network.output(...)` where `network` is of type`MultiLayerNetwork`.

Also printing the length of `ND4j.create(...)` gives 1411200 (length * width * 8 = 280 * 210 * 8), so that seems to also be working as expected. 

Versions: 
Java version 1.8.0_121
Dl4j version 0.8 
macOS Sierra version 10.12.4 (using CPU).

**Comment by saudet** [comment]
Does it happen only when using data from `TrainingData.getPixelData()`?

In any case, it would help if you could reproduce that without other libraries in the way. They might be the cause of the crash...

**Comment by benjaminhviid** [comment]
@saudet, I haven't tried to collect the pixel data by other means, but I'm using `TrainingData.getPixelData()` when training the network with no trouble. Apart from that I've debugged the pixel data when just before the error occurs and the values and length of array looks correct.

**Comment by saudet** [comment]
In any case, ff we can't reproduce the bug with a smaller program, I think what we should do next is run Valgrind on that: https://github.com/deeplearning4j/libnd4j/wiki/Debugging-libnd4j

If you would have the time to do that, let us know if you find any suspicious memory access that way! Thanks

**Comment by benjaminhviid** [comment]
Closing the issue. The error happened because of a wrong parameter in ```ImageTool.toScaledDoubles(td.getPixelData()), new int[] { 8, 3, td.getWidth(), td.getHeight()}), false);```. Changing it to ```ImageTool.toScaledDoubles(td.getPixelData()), new int[] { 1, 3, td.getWidth(), td.getHeight()}), false);``` resolved the problem.
