### ISSUE TITLE
Docs: Add details on snapshots

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3227]
Given that snapshots are now available, we should provide information on how to use them.
We used to have this information (long ago, when we previously had snapshots); I couldn't find this info presently, however.

In a nutshell:
1. Change the version to the current dev version (as on github): that's currently ```0.9.2-SNAPSHOT```
2. Add the following to your pom

```
    <repositories>
        <repository>
            <id>snapshots-repo</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>daily</updatePolicy>  <!-- Optional, update daily -->
            </snapshots>
        </repository>
    </repositories>
```
Note that update policies (and more info on this section generally) are explained here: http://maven.apache.org/pom.html#Repositories

Edit: we should add a note on this page about snapshots (as an alternative to building) too: https://deeplearning4j.org/buildinglocally

**Comment by raver119** [comment]
Added: https://deeplearning4j.org/snapshots
