### ISSUE TITLE
Can't allocate [HOST] memory

### ISSUE THREAD

**Issue by Treiblesschorle** [deeplearning4j/deeplearning4j#3229]
I'm trying to train AlexNet like network on 100x100x3 images using DL4J 0.8.0 . After an hour of training I get the following error (without the KNIME parts) : 
https://gist.github.com/Treiblesschorle/145a14ec3f871f1c0b53764685c6bd78

OS & Ram:
Xmx26g
Windows 10 x64

NVCC:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Mon_Jan__9_17:32:33_CST_2017
Cuda compilation tools, release 8.0, V8.0.60

cuDNN:
v5.1

GPU:
GTX 1080

Profiler:
![profiler](https://cloud.githubusercontent.com/assets/7195415/24907379/4078c96e-1ebc-11e7-9551-8955f050a209.jpg)

**Comment by raver119** [comment]
Are you sure that's full output log? Usually failed host memory allocation is caused by some kernel crash.

**Comment by raver119** [comment]
Also, can you please post gist with nn conf and your feeding/training pipeline. As far as i understand there's some threads used etc...

**Comment by Treiblesschorle** [comment]
Unfortunately thats all my eclipse is showing me. The threads are from KNIME. NN conf and feeding/training pipeline is done by other KNIME functionality. So I'm using custom DataSetIterator and nothing from DataVec. I can try reproducing outside of KNIME.

**Comment by raver119** [comment]
That would be awesome.

**Comment by Treiblesschorle** [comment]
Couldn't reproduce for some reason. I'll create a new issue if it happens again with code to reproduce.
