### ISSUE TITLE
PW+cuDNN only supports batches in multiples of 8

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#3231]
#### Issue Description

When using ParallelWrapper and cuDNN together, it appears cuDNN will only support batch sizes in multiples of 8. For reasons not fully understood, when launching PW with a batch size such as 74 there will be illegal memory access errors and other strange behavior. Using 72 or 80 or 64 alleviates the problem.

We will need to create an error or warning for users who will not understand this, nor know how to debug it.

The issue appears cuDNN specific and is outside the control of DL4J.

#### Version Information

Master branch.

* 0.8.1-SNAPSHOT
* Ubuntu 16.04
* CUDA 8.0
* cuDNN 6.0
* ParallelWrapper w/ 2 workers

#### Contributing

Will eventually submit a PR for this after some further testing.

**Comment by AlexDBlack** [comment]
Haven't seen any issues related to this recently - closing this as no longer relevant.
