### ISSUE TITLE
Lack of support for training models with both original and transformed datasets

### ISSUE THREAD

**Issue by antdood** [deeplearning4j/deeplearning4j#3236]
#### Issue Description

To have my model trained with both transformed and original datasets, I need to have 2 recordreaders and datasetiterators. It would be nice to have the ability to train a model with both transforms and original datasets easier. Somehow. Adam Gibson stated something in the lines of "we could probably add a transform that treats the transform as just an adiditional "next" method to be called".

**Comment by saudet** [comment]
Is this about DataVec?
