### ISSUE TITLE
Docs: add details on windows Spark setup

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3237]
If hadoop is not set up correctly on Windows, it's possible to get the following issue when running Spark:

(Note that this isn't specific to DL4J, but it's a common issue)

@wmeddie from gitter
>Download winutils.exe from https://github.com/steveloughran/winutils and put it into the null/bin/winutils.exe (or create a hadoop folder and add that to HADOOP_HOME I think)

https://gist.github.com/AlexDBlack/cc93b62d4e29c3e8fe9627b567cb7314

**Comment by tomthetrainer** [comment]
I will add this to quickstart, troubleshooting section, another ticket was similar to this.  I wonder if another doc or soemthing searchable is better.

**Comment by tomthetrainer** [comment]
Updated quickstart, re-open if you feel it should also be in another doc, this is the second time for this issue in the last week, so it needs to be covered well. 

I wonder wether the users were doing spark transform process, or distributed training, we could add a note on any pages we have for those topics
