### ISSUE TITLE
Wrong incrementor in an inner loop

### ISSUE THREAD

**Issue by lifove** [deeplearning4j/deeplearning4j#3238]
#### Issue Description

In a recent snapshot, I've found a wrong usage of an incrementor in an inner loop at deeplearning4j-nn/src/main/java/org/deeplearning4j/datasets/iterator/impl/MovingWindowDataSetFetcher.java

```
 50         for (int i = 0; i < list.size(); i++) {
 51             INDArray label = list.get(i).getLabels();
 52             List<INDArray> windows =
 53                             new MovingWindowMatrix(list.get(i).getFeatureMatrix(), windowRows    , windowColumns, true)
 54                                             .windows(true);
 55             for (int j = 0; j < windows.size(); j++) {
 56                 flipped.add(new DataSet(windows.get(i), label));
 57             }
 58             flipped.add(list.get(i));
 59         }
```
In Line 56, windows.get(i) should be windows.get(j)? This might be a trivial thing but just wanted to report just in case. Thanks!

**Comment by Howard-2** [comment]
I agree it should be windows.get(j).
if it is not, it can be cause of the out of the length. if j > i.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/3644
