### ISSUE TITLE
Early Stopping ignoring GPU

### ISSUE THREAD

**Issue by Stevod** [deeplearning4j/deeplearning4j#3240]
#### Issue Description

I have recently added the Early Stopping Trainer to a working project, to avoid me having to babysit the training process so much. While the trainer appears to work well, I see from nvidia-smi monitoring tool that it uses 0% GPU, so presumably it is falling back to CPU. The GPU is fully enabled (as shown by JCublasBackend), and is utilised at around 30% for the same project without EarlyStopping. Is there something else I need to do to enable GPU with EarlyStopping?

#### Version Information

* Deeplearning4j version: 0.8
* platform information (OS, etc): Ubuntu 16.10, 64 bit, 
* CUDA version, if used 0.8
* NVIDIA driver version, if in use: 379.39
* GPU: GTX 1070
#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by crockpotveggies** [comment]
EarlyStoppingTrainer is not compatible with ParallelWrapper. You will need to use the `EarlyStoppingParallelTrainer` which is multi-GPU compatible. Note: this requires adding a special dependency to your POM:

```
artifactId: deeplearning4j-parallel-wrapper_2.11
```

**Comment by raver119** [comment]
@Stevod do you have 1 gpu? or use PW?

**Comment by raver119** [comment]
Please provide PerformanceListener output for both cases, with & without EarlyStopping

**Comment by crockpotveggies** [comment]
@raver119 it's possible that the `nd4j-native` dependency is being used instead of `nd4j-cuda-*`?

**Comment by raver119** [comment]
We'll see soon. As soon as @Stevod posts perflistener output :)

**Comment by raver119** [comment]
P.S. full output please.

**Comment by Stevod** [comment]
Will post full output tomorrow, but in the middle of a long run (using CPU) overnight.
