### ISSUE TITLE
Android loading single image 

### ISSUE THREAD

**Issue by B0yma** [deeplearning4j/deeplearning4j#3245]
#### Issue Description

Hello im trying to load image from bitmap using NativeImageLoader
`

       File file = new File(filechose);
        // Use NativeImageLoader to convert to numerical matrix

        NativeImageLoader loader = new NativeImageLoader(height, width, channels);

        // Get the image into an INDarray

        INDArray image = loader.asMatrix(file);

        // 0-255
        // 0-1
        DataNormalization scaler = new ImagePreProcessingScaler(0,1);
        scaler.transform(image);
        // Pass through to neural Net

        INDArray output = model.output(image);`

 class but this class has in import 
 java.awt.image.BufferedImage; so android cant compile program

> Error:(145, 40) error: cannot access BufferedImage
> class file for java.awt.image.BufferedImage not found
> Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.

i know that i can load image from file but i dont want to do that
so how can i load one bitmap?

Dependencies
 compile 'org.deeplearning4j:deeplearning4j-core:0.7.2'
    compile 'org.nd4j:nd4j-native:0.7.2'
    compile 'org.nd4j:nd4j-native:0.7.2:android-arm'
    compile "org.slf4j:slf4j-simple:1.7.9"

**Comment by crockpotveggies** [comment]
@saudet any ideas on this one?

**Comment by saudet** [comment]
In what format do you have your data?

**Comment by B0yma** [comment]
i have images format PNG

**Comment by cmvikas94** [comment]
I have made an image classification model using Keras in Python which is in **".h5"** format. I am trying to use it in my Android application using Deeplearning4j. 

I am facing a similar issue as mentioned by @B0yma, when I try to do image classification by loading a **Mat** image using NativeImageLoader constructor. The code is as follows :

```
NativeImageLoader nativeImageLoader = new NativeImageLoader(60, 60, 3);
INDArray image = nativeImageLoader.asMatrix(testImage);   // testImage is of Mat format

// 0-255 to 0-1
DataNormalization scaler = new ImagePreProcessingScaler(0, 1);
scaler.transform(image);
// Pass through to neural Net
INDArray output = model.output(image);
INDArray labels = model.getLabels();
```


When the app builds it gives an error at the second line of the code above i.e  `INDArray image = nativeImageLoader.asMatrix(testImage);` 

I get the following error when I build the apk:

```
Error:(1109, 51) error: cannot access BufferedImage
class file for java.awt.image.BufferedImage not found
```

I tried to find the solution but [this](http://stackoverflow.com/a/33210293/7665986) and [this](http://stackoverflow.com/a/6345814/7665986) says that AWT package is not supported in Android. 

Please help me with a solution or a work around.  Thank you.

**Comment by saudet** [comment]
This has been fixed. Please try 0.8.1-SNAPSHOT.

**Comment by cmvikas94** [comment]
Thank you for the response. I am really glad as Keras models can be used on Android directly. I really appreciate your work and efforts. Cheers!

**Comment by B0yma** [comment]
@cmvikas94 if u have version below 0.8.1-SNAPSHOT u can use BaseImageLoader which extends Native
but u need convert bitmap to InputStream
