### ISSUE TITLE
how to load saved model of keras in dl4j

### ISSUE THREAD

**Issue by gauravshelangia** [deeplearning4j/deeplearning4j#3246]
I have saved my Keras model in **JSON** file and model weights in separate **weights.h5** file.

I am using Gradle to build my application. Below is my Gradle script : 

apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/INDEX.LIST'
    }

    defaultConfig {
        applicationId "com.example.gaurav.mtargetclient"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-beta5'
    testCompile 'junit:junit:4.12'

    compile 'com.google.android.gms:play-services-appindexing:8.4.0'
    compile 'com.qozix:tileview:2.2.6'

    compile 'org.deeplearning4j:deeplearning4j-core:0.7.2'
    compile 'org.nd4j:nd4j-native:0.7.2'
    compile 'org.nd4j:nd4j-native:0.7.2:android-x86'
    compile 'org.nd4j:nd4j-native:0.7.2:android-arm'
}

After this, I am not able to use modelimport Method. It show **cannot resolve the symbol **modelimport****

Please help me how can I import the saved model in dl4j

**Comment by crockpotveggies** [comment]
First thing: I see you're using 0.7.2. The latest version is 0.8.0. You might benefit to upgrade.

Second, please add this dependency here: http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22deeplearning4j-modelimport%22

**Comment by tomthetrainer** [comment]
Yes particularly for Keras Model Import, I suggest upgrade as well.

**Comment by gauravshelangia** [comment]
I added the following line in my Gradle script:
    maven { url 'https://mvnrepository.com/artifact/org.deeplearning4j/deeplearning4j-core' }
but even then it is showing me the same error. 

Maybe I am doing something wrong.
Can you please tell me how can I properly modify my Gradle file so that I can use this library.
