### ISSUE TITLE
Android load neural net and minimize app size

### ISSUE THREAD

**Issue by B0yma** [deeplearning4j/deeplearning4j#3260]
#### Issue Description
Hello im trying to load neural net and minimize app size so i downoad required JARs from 
https://oss.sonatype.org/content/repositories/snapshots/org/
and out into libs folder,program compiled succesful but whet it started on device it crashes and android studio give exception 

> 04-15 20:09:19.659 22324-22350/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
> Process: com.boymaws.myapplication, PID: 22324
> java.lang.VerifyError: org/nd4j/linalg/factory/Nd4j
> at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:187)
> at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:137)
> at com.boymaws.myapplication.MainActivity.loadNet2(MainActivity.java:94)
> at com.boymaws.myapplication.MainActivity.access$000(MainActivity.java:19)
> at com.boymaws.myapplication.MainActivity$1.run(MainActivity.java:85)
> at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
> at java.lang.Thread.run(Thread.java:841)

all libs that i use
nd4j-gson-0.8.1-20170411.024849-43
javacpp-1.3.3-20170405.135305-3
nd4j-api-0.8.1-20170413.065828-97
nd4j-native-api-0.8.1-20170411.024833-43
nd4j-native-0.8.1-20170411.024846-43-android-arm
json-20131018
deeplearning4j-nn-0.8.1-20170411.041412-15
deeplearning4j-core-0.8.1-20170411.041414-15
datavec-data-image-0.8.1-20170411.040742-16

code of loading net
MultiLayerNetwork model = ModelSerializer.restoreMultiLayerNetwork(netconffilepath);

#### Version Information
device OS - android 4.4

**Comment by agibsonccc** [comment]
Have you tried just googling this? createScalarTransform This doesn't feel specific to dl4j..

**Comment by B0yma** [comment]
yes googled but its dont solve my problem
i think that causes error
`params = Nd4j.read(confFromJson1);`
Nd4j class
```
public static INDArray read(DataInputStream dis) throws IOException {
        DataBuffer shapeInformation = createBuffer(new int[1], Type.INT);
        shapeInformation.read(dis);
        int length = Shape.length(shapeInformation);
        DataBuffer data = CompressedDataBuffer.readUnknown(dis, (long)length);
        return createArrayFromShapeBuffer(data, shapeInformation);
    }
```

so DataBuffer  is from 

> java.awt.image
> Class DataBuffer
> java.lang.Object
> java.awt.image.DataBuffer

**Comment by saudet** [comment]
Please use Maven or Gradle: https://deeplearning4j.org/android

**Comment by agibsonccc** [comment]
Let me be a bit more blunt: I will close this issue if you don't. We categorically don't support people building things manually.

**Comment by agibsonccc** [comment]
@B0yma did using maven/gradle fix it? Sorry, there's just a ton of dependencies. It's near impossible to do things manually.

**Comment by B0yma** [comment]
its working by using gradle but app size -100mb, i wanted to make it around 20mb or less

**Comment by saudet** [comment]
@B0yma Try to use ProGuard, that's what it's for: https://developer.android.com/studio/build/shrink-code.html
