### ISSUE TITLE
Keras Model Import - Paths not available on Android

### ISSUE THREAD

**Issue by gauravshelangia** [deeplearning4j/deeplearning4j#3261]
I try to import keras model from two file modeljson file and another is modelweights file in android. But while I run the app it gives me the following error: 

Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Paths;
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.Paths" on path: DexPathList

please help me what can I do to resolve the error. 

Thanks

**Comment by AlexDBlack** [comment]
The problem here: Keras model import uses ```java.nio.file.Paths```, but this is not available on Android.

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-keras/src/main/java/org/deeplearning4j/keras/HDF5MiniBatchDataSetIterator.java#L68
http://stackoverflow.com/questions/23638181/noclassdeffounderror-on-android

**Comment by AlexDBlack** [comment]
@gauravshelangia one workaround of course is to import it on a desktop (with oracle or openjdk JVM) and save it to DL4J format.

**Comment by gauravshelangia** [comment]
Thanks, I will try this.

**Comment by gauravshelangia** [comment]
I tried the method you suggested but it gives me the error while importing saved model in dl4j : 
**Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.InvalidKerasConfigurationException: Could not determine number of outputs for layer: no output_dim or nb_filter field found.**

**Comment by gauravshelangia** [comment]
Solved this problem. 
Actually, this problem arises if I use Keras-2. So I tried to save my model using Keras-1.1.0 and it works perfectly. Also able to import the model on android. 

Please look into this if I am wrong @AlexDBlack

**Comment by saudet** [comment]
@gauravshelangia Err, HDF5 doesn't support Android. I would be curious to know how you got it working.

In any case, we shouldn't use NIO2 unless we really need it because it doesn't work on Android. @turambar @pkoperek Any good reasons to have it there?

**Comment by gauravshelangia** [comment]
Yes, HDF5 doesn't support Android and also **java.nio.file.Paths** is not available on android. To get it working I do the following:
1. First, import the model in dl4j on desktop
2. Second, write the model using **ModelSerializer** 
3. And last, restore the model in android

**Comment by saudet** [comment]
That sounds more like it. @tomthetrainer Should we document that somewhere on https://deeplearning4j.org/model-import-keras or https://deeplearning4j.org/android I guess?

**Comment by gauravshelangia** [comment]
@saudet Yes, please document this. It will be very helpful.

**Comment by GYXie** [comment]
The `output_dim` was changed to `units` after version 2.0.0. Ref:https://github.com/keras-team/keras/releases?after=2.0.6

**Comment by maxpumperla** [comment]
@GYXie that's reflected in Keras import code already.
