### ISSUE TITLE
Performance Metric

### ISSUE THREAD

**Issue by geekco2000** [deeplearning4j/deeplearning4j#3265]
Hi, 

I'd like to know if there is a performance metric like this in the project (for MLP regression problem) :
sqrt ( ( Z(yi - y^) / yi )² / n ) -> look like a little bit of RMSE metric
With Z : Sum from i to n
        yi : Actual value i
      y^ : Predicted value i 

Or maybe I need to program it myself. 

Thank you.

**Comment by AlexDBlack** [comment]
Does this have a name and/or reference (paper, etc)?
Also looks a bit like MAPE: https://github.com/deeplearning4j/nd4j/blob/aafbd0101b1a10a0d4dae1a2671895410a1708b2/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/lossfunctions/impl/LossMAPE.java


This could be implemented as a custom loss function:
https://github.com/deeplearning4j/dl4j-examples/tree/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/lossfunctions

**Comment by geekco2000** [comment]
Thank you for your answer. 

It doesn't really have a name (I think), I have  just changed a bit the RMSE function to have a better understanding of my performance metric.  But MAPE looks like good, thanks for that.
Otherwise, do you have any project example using MAPE function (prediction values, actual values, displaying the output, ...). Then I will adapt it with my use case.

Thank you for your time !!

**Comment by geekco2000** [comment]
I think I got the point : 
.layer(9, new OutputLayer.Builder(LossFunctions.LossFunction.MEAN_ABSOLUTE_PERCENTAGE_ERROR) 
**For anyone would need help about this 

Otherwise, to use this metric for the test data, any idea ? 
Because usually, I do like this : 
	  val evaluation = sparkNet.evaluateRegression(testData)
	  println(evaluation.stats)
But now I'd like to print the MAPE error !

Thank you

**Comment by AlexDBlack** [comment]
To use the metric for  test data: implement your own IEvaluation instance (or, just extend BaseEvaluation).
https://github.com/deeplearning4j/deeplearning4j/tree/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/eval

Then just call MultiLayerNetwork.doEvaluation with an instance of your evaluation class.

You can also score each example using MultiLayerNetwork.scoreExamples -> gives the score for each example separately, for the given loss function.
