### ISSUE TITLE
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/iterator/CnnSentenceDataSetIterator.java

### ISSUE THREAD

**Issue by andywang85** [deeplearning4j/deeplearning4j#3267]
#### Issue Description
line 215:
List<String> tokens = tokenizeSentence(p.getFirst());

the size of  tokens maybe is 0. 

Please describe our issue, along with:
- expected behavior
- encountered behavior

#### Version Information
0.8
Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by AlexDBlack** [comment]
Reproduced here and fixed: https://github.com/deeplearning4j/deeplearning4j/pull/3585
That PR will be merged soon.
