### ISSUE TITLE
TBPTT: ensure history/states are detached from workspace

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3268]
https://github.com/deeplearning4j/deeplearning4j/blob/1f8af820c29cc5567a2c5eaa290f094c4d1492a7/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/layers/recurrent/GravesLSTM.java#L87

**Comment by raver119** [comment]
https://github.com/deeplearning4j/deeplearning4j/blob/235171c9fcbf8e9590c0210874edf1c0267edea2/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java#L1247

**Comment by raver119** [comment]
Implemented.
