### ISSUE TITLE
save datasets in parallel manner

### ISSUE THREAD

**Issue by kepricon** [deeplearning4j/deeplearning4j#3270]
# What I'm going to do
write **DataSetSaver**(this name can be changed) which can save datasets in parallel mode

# purpose
there are some situations we should **make pre-saved datasets**. For examples, benchmarks(https://deeplearning4j.org/benchmark#etl--asynchronous-etl) or training on large image datasets(like ImageNet). sometimes it takes lots of time. this can be helpful for the situations.

**Comment by raver119** [comment]
Don't forget to make it configurable: number of workers should be configurable at very least.

**Comment by kepricon** [comment]
thanks for your comments. I've applied your opinion in the PR.

**Comment by huitseeker** [comment]
All merged !
