### ISSUE TITLE
Waiting when transfer learning is tried

### ISSUE THREAD

**Issue by papperwing** [deeplearning4j/deeplearning4j#3274]
##### Expected Behaviour:
Program should prepare images for VGG16 model in RecorReaderDataSetIterator and start to process them inside network.

##### Encountered behaviour:
Program wrote down information about frozen layers and after that it is stucked.

Unfortunately the first run where I was waiting 30 minutes get killed from some reason but it seems that another run caused same problem.

There is added screenshots from JVisualVM.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version : 0.8.0
* platform information (OS, etc) : linux server (debian)
* CUDA version, if used : not used
* NVIDIA driver version, if in use : not used

![snimek z 2017-04-19 14-49-02](https://cloud.githubusercontent.com/assets/5627436/25180763/8a97cbae-250f-11e7-8532-6cb8c5fe8da7.png)
![snimek z 2017-04-19 14-49-05](https://cloud.githubusercontent.com/assets/5627436/25180764/8d64bfb8-250f-11e7-9a20-bdef170e29a5.png)
![snimek z 2017-04-19 14-49-36](https://cloud.githubusercontent.com/assets/5627436/25180768/8eee7f9a-250f-11e7-896d-c604aead86bd.png)
![snimek z 2017-04-19 14-49-41](https://cloud.githubusercontent.com/assets/5627436/25180770/90408faa-250f-11e7-8829-29d00f145223.png)

**Comment by raver119** [comment]
Please show threads dump

**Comment by papperwing** [comment]
https://gist.github.com/papperwing/ae7c4544fc39b72094bb72551b048667

**Comment by raver119** [comment]
According to your dump, app is running without any issues.

**Comment by papperwing** [comment]
So based on that, inicialization of record reader can take significant time based on model type?

**Comment by papperwing** [comment]
Problem is based totally in different place and it is not related to DL4J. 
Problem was caused in my project when jar was created that some changes (added logs) wasn't propagated and it seemed as program was frozen even when it was computing fit method.
Thank you for your help.
