### ISSUE TITLE
Input/OutputPreProcessor issues

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#328]
(a) Multiple input/output preprocessors need equals and hashCode methods
	Why? If only so that unit tests can pass. :)
	MultiLayerConfiguration.equals() and hashCode() depend on behaviour of the input/output preprocessor equals/hashCode methods; default equals/hashCode methods are insufficient (for example, MultiLayerNeuralNetConfigurationTest.testJson() fails due to this, when doing equals on MultiLayerConfiguration -> json -> MultiLayerConfiguration).
	Fix might might take advantage of Lombok, once PR (https://github.com/deeplearning4j/deeplearning4j/pull/320) is merged?
	
(b) AggregatePreProcessor and ComposableOutputPostProcessor are functionally identical

(c) (Assuming it is not deleted/deprecated) ComposableOutputPostProcessor should be renamed ComposableOutputPreProcessor for consistency, given that it implements the OutputPreProcessor interface

**Comment by agibsonccc** [comment]
I deleted (b). I moved the input and output pre processors around and added base classes for each that define the equals method as the class.
