### ISSUE TITLE
Not able to train cnn with cuDNN on 0.8.1-SNAPSHOT

### ISSUE THREAD

**Issue by DanPederEriksen** [deeplearning4j/deeplearning4j#3280]
The following code:
https://gist.github.com/anonymous/8d817a65270ad6e3ebff7200921ca203

Results in the following memory error:
"RuntimeException: Failed to allocate 2326528 bytes from DEVICE [0] memory"
https://gist.github.com/anonymous/b987e6e89f0dbf242a0f66ca88fe5d36

The same code works for the 0.8.0 release.

#### Version Information
dl4j 0.8.1-SNAPSHOT
Windows 10, CUDA 8 and cuDNN.
Gfx card Nvidia GTX 1080 Ti. driver version 381.65.

**Comment by DanPederEriksen** [comment]
TrainUtil can be found here: https://gist.github.com/anonymous/41ca5dd913da77bf0a78f2259f944050

**Comment by raver119** [comment]
Can you please check if this is still an issue for latest snapshot? There were lots of changes recently
