### ISSUE TITLE
WorkspaceMode.SEPARATE does not work while SINGLE works somewhat

### ISSUE THREAD

**Issue by DanPederEriksen** [deeplearning4j/deeplearning4j#3281]
Code: https://gist.github.com/anonymous/da00503b9a3b9ebaeca69023dc8f4193

0.8.0 works fine and keeps improving each epoch for this code. 0.8.1-SNAPSHOT with single works for one epoch and fails on the second. Separate workspacemode does not work at all. Trains to 11%

Console output with single:
https://gist.github.com/anonymous/7a5adcce927ac92ac129a0a748308164
Epoch 0 trains to 82%, epoch 1 trains to 10.7% (9 outcomes)

Console output with separate:
https://gist.github.com/anonymous/4a7cbb6251906a3cd6fbc05d762556c2
Epoch 0 trains to 11%.

Version Information:
dl4j 0.8.1-SNAPSHOT
Windows 10, CUDA 8 and cuDNN.
Gfx card Nvidia GTX 1080 Ti. driver version 381.65.

**Comment by raver119** [comment]
Show TrainUtil too please. Model you've shown can't fail regardless of workspace mode. So it has to be something with your training approach.

**Comment by DanPederEriksen** [comment]
TrainUtil can be found here: https://gist.github.com/anonymous/41ca5dd913da77bf0a78f2259f944050

**Comment by raver119** [comment]
Aha. That explains. Please get rid of ALL AsyncDataSetIterators, just do not use them and try again.
I think there's just race condition happens internally.

**Comment by DanPederEriksen** [comment]
Removing AsyncDataSetIterators solves the issue for me. Snapshot now trains as 0.8.0.

**Comment by raver119** [comment]
Please try latest snapshot, such issues should be fixed now. Please try and confirm/decline.

**Comment by AlexDBlack** [comment]
Closing this as inactive - we haven't seen any workspace issues for a while. We can reopen if it reoccurs.
