### ISSUE TITLE
7x worse performance on - 0.8.1-SNAPSHOT: Attaching UIServer to training cnn using cuDNN gives 

### ISSUE THREAD

**Issue by DanPederEriksen** [deeplearning4j/deeplearning4j#3282]
On 0.8.1-SNAPSHOT:
Attaching UIServer when training, one epoch goes from 0.9 minutes to 8 minutes.

Code:
https://gist.github.com/anonymous/e3053e7fc74718239c718b4b62f4ca60
https://gist.github.com/anonymous/989adc2796be225db8f1857ec17866ff

Console output showing bad performance:
https://gist.github.com/anonymous/fb6df04aef47c916fea4e2c2ab685760

Console output when UIServer is removed:
https://gist.github.com/anonymous/29db46e9ae8c41436737c537db281d3f

Version Information:
dl4j 0.8.1-SNAPSHOT
Windows 10, CUDA 8 and cuDNN.
Gfx card Nvidia GTX 1080 Ti. driver version 381.65.

**Comment by raver119** [comment]
So, in other words: iteration time never changes, but overall epoch time suffers a lot.
That probably means, that listener invocation time isn't measured, and slowdown resides in listener. Probably that UI listener :)

**Comment by DanPederEriksen** [comment]
Profiling from jvisualvm:
https://www.dropbox.com/s/oablenqlfmmn6p3/bad-performance.png?dl=0

**Comment by raver119** [comment]
Can i have something more then one screenshot? Times shown there are so small...

**Comment by DanPederEriksen** [comment]
I am not getting good numbers with the instrumentation. The sampler is what gives me the best data:
https://www.dropbox.com/s/ephh4gyrb9ujnzz/bad-performance2.png?dl=0

**Comment by raver119** [comment]
Aha, this one is better. Thanks

**Comment by raver119** [comment]
Ultra important note here: performance does NOT degrade over time. So this time listener itself is suspect.

**Comment by AlexDBlack** [comment]
Yes, StatsListener is the likely cause here.

However, based on the gist, I'm not suprised it's slow:
- Collecting stats *every single iteration* (performance/score listeners are every 1000 iterations by comparison)
- Using in-memory storage (though, workspaces should minimize the JVM impact)

StatsListener is relatively expensive, in that it calculates multiple things (mean magnitude, histograms, etc) independently for every single array separately, for activations, gradients, updates and parameters.
Batched ops may be possible here, to improve performance.

**Comment by DanPederEriksen** [comment]
If collecting stats every single iteration is not a good idea this example should probably be updated:
https://deeplearning4j.org/visualization

**Comment by AlexDBlack** [comment]
@DanPederEriksen yeah, that's a fair point - we could explain this better (including in the examples)
