### ISSUE TITLE
GravesLSTM and Time Series (with Gaps) regression learning

### ISSUE THREAD

**Issue by sascha08-15** [deeplearning4j/deeplearning4j#3284]
I am trying to use a GravesLSTM network to predict time series (regression).
The question I have, is how do I deal with Gaps in DL4J?
The time series have larger gaps (end at 6pm, continue at 8 am next day, but in between changes to the values happen) - I'd assume this messes-up any learning as the gaps cannot really be fed into the network (but currently are).
* How to deal with that fact?
* How would I would implement it using DL4J? Here are my thoughts:
	* Use an iterator with batches for a single day only (1 batch=one day)
	* Reset saved network state using the method rnnResetState on each next invocation

**Comment by sascha08-15** [comment]
No comments?
My implementation so far uses an iterationlistener in combination with the iterator holding the data.
Would be great to hear some opinions on this.
Thanks in advance!

**Comment by tomthetrainer** [comment]
I apologize for the delay, 

Have you reviewed this paper? 

https://arxiv.org/abs/1606.01865

Masking is one approach
