### ISSUE TITLE
Score/Fitting Inconsistency after saving/restoring Model

### ISSUE THREAD

**Issue by zpankr** [deeplearning4j/deeplearning4j#3303]
#### Issue Description

I'm attempting to create a time series model based on the Timestep Regression Examples provided on the dl4j-examples package. The gist for my test file is here:
https://gist.github.com/zpankr/6fda52463316bbc91152a0878b95b6fa
I've also included IBM_raw.txt 
[IBM_raw.txt](https://github.com/deeplearning4j/deeplearning4j/files/956100/IBM_raw.txt)
which contains the training/testing data.

During development I've found some necessity in saving and restoring models for further refitting and use. Saving and restoring works flawlessly, the models are consistent in terms of the result if they've been previously fitted.
The problem lies on attempting to fit a few times in one session and then a few others in another, which differs from fitting the same epochs in a single session.
Example:
Fitting 21 epochs in a single session results in a score (at 20) of ~429.
Fitting 10 epochs in one session and 11 in another results in a score (at 20 total) of ~455
(At 15 the score differs even more, at 4776 on the former and 361 in the latter)

After brief discussion in the Gitter, no obvious issues with my testing code were found and we've decided to open an issue.

Deeplearning4j version: 0.8.0
Platform: Windows 7, Java 8_111

Sorry if I forgot anything. Any ideas?

**Comment by raver119** [comment]
I think this issue was fixed long ago.
