### ISSUE TITLE
CUDA out of memory crash during parallel training

### ISSUE THREAD

**Issue by Alcalol** [deeplearning4j/deeplearning4j#3304]
When using parallel trainer (CUDA) to train 10 networks one after another, GPU memory does not seem to clear but rather uses GPU memory in a cumulative fashion.  So just as an example if each network requires 1024mb of memory to process, the GPU memory usage would start at 1024 for network 1, then 2048 for network 2 etc etc until memory is full and the application crashes.  This information was gained by studying sensor information in GPU-Z.

It might be worth noting that this crash does not happen while doing single GPU (non parallel) training, however I cannot say for sure if this is just delaying the inevitable by lowering memory requirement per cycle or if the issue does not apply.

I am currently using CUDA version 8.0.61 (also tried 8.0.44), and version 0.8.0 of DL4j (2.11?) and ND4J on a windows 10 machine consisting of 2x GTX 780 cards with SLi mode turned off.  My nvidia graphics driver version is 381.89.

Please find following the full error log, as well as the various classes in my code which creates and trains the network.

error log
https://gist.github.com/Alcalol/974771e6d3bb6ae4202c2cc4d22a79a3

Network creater class
https://gist.github.com/Alcalol/1c24f5176cecc09d30c5b7eb70db8de0

trainer class
https://gist.github.com/Alcalol/64fced41384f9d30db38b7f5868c2d73

main class
https://gist.github.com/Alcalol/5c276ffa3024cdf63f965e43375b5303

Thanks

**Comment by raver119** [comment]
Right, that looks like flaw of nd4j memory cache implementation. That's bad news.

There's good news though: at current snapshot, with workspaces enabled the hat shouldn't be an issue anymore, since it doesn't rely on cache for individual INDArray allocations.
