### ISSUE TITLE
Loading VGG16 takes to much memory

### ISSUE THREAD

**Issue by papperwing** [deeplearning4j/deeplearning4j#3307]
#### Issue Description
- encountered behavior
--Loading model VGG16 use 25giga of memory and that seems to be to much.

Link to dropbox with tared folder:
https://www.dropbox.com/s/340dl8ytpibto8c/images.tar.gz?dl=0

In folder there is:
 - start.sh starts app (need parameters).
 - README contain prepared start with parameters and explanaition what does parameters mean
 - static/ containing 10k images in structure
 - dataset.csv containing information about images

Project repository:
https://github.com/papperwing/image-net

#### Version Information
Please indicate relevant versions, including, if relevant:
* Deeplearning4j version : 8.0
* platform information (OS, etc) : linux (debian)
* CUDA version, if used : not used
* NVIDIA driver version, if in use : not used

**Comment by raver119** [comment]
Thanks, i'll take a look there

**Comment by papperwing** [comment]
I added code to new github repository, link is added to main description.

**Comment by papperwing** [comment]
https://github.com/papperwing/image-net/tree/optimalization
I added some stuff for optimization, removed splitting and storing datasets  for testing and moved logic into dataset preproces. I hoped that it will lead to both time and memory improvements but instead memory consumption raised and time seems to be same as in master branch.

**Comment by saudet** [comment]
Could you try to reduce the maximum memory (usually manually via the -Xmx command line option) and see what happens? Memory consumption should reduce, and then that would be a solution.

**Comment by papperwing** [comment]
Sorry I just didn't closed issue. Problem was with  missing parameters both for workspace and jvm . Now I am able to fit it into much lower memory.
