### ISSUE TITLE
Iris and MNIST DataSetIterator incorrect behaviour with batch size of 1

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#331]
Issue 1 - Iris:
Example output are all zero (except for first example) when iterator is created with batch size of 1. Output seems correct with batch size of 2+. Doesn't seem to depend on total number of examples requested from iterator. Issue seems to be unique to IrisDataSetIterator (not MNIST/LFW iterators).
Tested with ND4J 3.5.5.6-SNAPSHOT and JBLAS back-end only.
Code and console output follow.
```java
DataSetIterator iter1 = new IrisDataSetIterator(3, 3);		//Output seems correct
DataSetIterator iter2 = new IrisDataSetIterator(1, 3);		//Output/labels are all zero after first example

System.out.println("----- 3 examples per batch -----");
System.out.println(iter1.next());

System.out.println("----- 1 example per batch -----");
while(iter2.hasNext()) System.out.println(iter2.next());
```

----- 3 examples per batch -----
===========INPUT===================
[[5.099999904632568, 3.5, 1.399999976158142, 0.20000000298023224]
 [4.900000095367432, 3.0, 1.399999976158142, 0.20000000298023224]
  ,[4.699999809265137, 3.200000047683716, 1.2999999523162842, 0.20000000298023224]]

=================OUTPUT==================
[[1.0, 0.0, 0.0]
 [1.0, 0.0, 0.0]
  ,[1.0, 0.0, 0.0]]

----- 1 example per batch -----
===========INPUT===================
[5.099999904632568, 3.5, 1.399999976158142, 0.20000000298023224]
 
=================OUTPUT==================
[1.0, 0.0, 0.0]
 
===========INPUT===================
[4.900000095367432, 3.0, 1.399999976158142, 0.20000000298023224]
 
=================OUTPUT==================
[0.0, 0.0, 0.0]
 
===========INPUT===================
[4.699999809265137, 3.200000047683716, 1.2999999523162842, 0.20000000298023224]
 
=================OUTPUT==================
[0.0, 0.0, 0.0]

////////////////////////////////////////////////////////
Issue 2: MNIST iterator:
Relatively minor issue. When using batch size of 1, iterator contains one less example than expected. This issue seems isolated to MNIST (Iris and LFW iterators seem to return correct number of examples with batch size of 1).

```java
DataSetIterator miter1 = new MnistDataSetIterator(3,9);		//Works, iterator gives 3 batches
DataSetIterator miter2 = new MnistDataSetIterator(1,3);		//Iterator gives 2 batches, should return 3

int count1 = 0;
while(miter1.hasNext()){
	miter1.next();
	count1++;
}
int count2 = 0;
while(miter2.hasNext()){
	miter2.next();
	count2++;
}
System.out.println("Expect 3, got: " + count1 + ", " + count2 );

DataSetIterator miter3 = new MnistDataSetIterator(1,100);	//Iterator gives 99 batches, should give 100
int count3 = 0;
while(miter3.hasNext()){
	miter3.next();
	count3++;
}
System.out.println("Expected 100, got: " + count3 );

DataSetIterator miter4 = new MnistDataSetIterator(1,1);
System.out.println("miter4.hasNext(): " + miter4.hasNext() );
```

Output:
Expect 3, got: 3, 2
Expected 100, got: 99
miter4.hasNext(): false

**Comment by agibsonccc** [comment]
There's a likely edge case here. Good find!

**Comment by AlexDBlack** [comment]
I'm working on a fix and unit test for these issues. Think I've got MNIST fixed, looking into Iris now. I'll submit a PR when that's done.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/333

**Comment by AlexDBlack** [comment]
PR merged.
