### ISSUE TITLE
Workspace Setting on Computational Graph not working

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#3312]
Using the 0.8.1-SNAPSHOT, when building a computational graph, it is possible to put `.workspaceMode` before and after `.graphBuilder()`. Only if it is set *before* it, the setting will actually stick. I expect it to work in both positions.

**Comment by AlexDBlack** [comment]
No longer possible to set workspace mode after graphBuilder(); works as expected when set before.
