### ISSUE TITLE
Unsupported keras layer type Model

### ISSUE THREAD

**Issue by pharnoux** [deeplearning4j/deeplearning4j#3313]
Hi,

I'm trying to load a CNN model with a dense layer at the end saved with Keras but it's not working.

That's my code : 

```
net = KerasModelImport.importKerasSequentialModelAndWeights(PATH_TO_H5_FILE,false);
```

And I get this : 

```
org.deeplearning4j.nn.modelimport.keras.UnsupportedKerasConfigurationException: Unsupported keras layer type Model. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.KerasLayer.getKerasLayerFromConfig(KerasLayer.java:254)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.helperPrepareLayers(KerasModel.java:190)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:99)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:56)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel$ModelBuilder.buildSequential(KerasModel.java:581)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:140)
	at com.ibm.watson.sentimentanalysis.model.DeepLearning4JModel.load(DeepLearning4JModel.java:71)
	at com.ibm.watson.sentimentanalysis.model.DeepLearning4JModel.main(DeepLearning4JModel.java:99)
```

Am I missing a step ?
Could it be a Keras version problem ? I'm using 1.2.1. Should I be using another one ?

**Comment by chiaolun** [comment]
1. There are two types of keras models, Model and Sequential. To import a Model you use ```KerasModelImport.importKerasModelAndWeights```, without the ```Sequential```.

2. This doesn't work, however, if you nest models within each other. I've had to take out the layers and flatten a model before it could be imported by dl4j.

**Comment by agibsonccc** [comment]
Also of note - make sure your model is keras 1. We will be supporting keras 1 and 2 soon.

**Comment by pharnoux** [comment]
@chiaolun, @agibsonccc  thanks for the quick response !

The model I'm trying to load is a sequential model. When I try to load it with `importKerasModelAndWeights`, I get this : 
```
org.deeplearning4j.nn.modelimport.keras.InvalidKerasConfigurationException: Expected model class name Model (found Sequential). For more information, see http://deeplearning4j.org/model-import-keras.
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:135)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:97)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel$ModelBuilder.buildModel(KerasModel.java:576)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:104)
	at org.deeplearning4j.nn.modelimport.keras.DeepLearning4JModel.load(DeepLearning4JModel.java:73)
	at org.deeplearning4j.nn.modelimport.keras.DeepLearning4JModel.main(DeepLearning4JModel.java:101)
```

Digging a bit deeper, looks like my layer's name is "Model" when it should be one supported [here](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/KerasLayer.java#189)

I'm using a Convolution 1D layer, so this issue seem to be related to this #3101 and #3102.
I tried pulling the code from the kerasModelImport branch (as suggested in #3102), yet it doesn't compile. 
Looks like it is looking for `KerasConvolution1D` [here](https://github.com/deeplearning4j/deeplearning4j/blob/kerasModelImport/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/KerasLayer.java#L220) which is not included in the provided keras layers.

Anything I can do to make this work ?
Also, when are you planning on releasing this import KerasConvolution1D feature ?

**Comment by LeeTL1220** [comment]
Whatever happened to the Convolution1D import PR?  I see the ``kerasModelImport`` branch, but it is a bit old and (as reported above) does not compile.

**Comment by turambar** [comment]
@pharnoux what exactly is a "Model" layer? This suggests that the import code thinks your model configuration is a layer configuration, which in turn suggests that your model configuration is malformed (or perhaps Keras 2?). Please share your model configuration JSON or model HDF5 so we can properly help.

**Comment by turambar** [comment]
@pharnoux @LeeTL1220 @agibsonccc yeah, I apologize: the 1D convolution import stuff became orphaned when I was pulled onto another project. Other Skymind personnel are taking over Keras development, so things should start moving again soon!

**Comment by maxpumperla** [comment]
@turambar can you point me to your pending 1D conv work? I can take this from here.

@pharnoux @LeeTL1220 I will further investigate from here. Did anything change? Does it magically work now? ;) Any update on your progress would be awesome.

**Comment by maxpumperla** [comment]
@pharnoux also, does this simply boil down to the lack of conv1D or is there something else wrong? Could you please provide your model configuration JSON or model HDF5 as gist, so we can properly help?

**Comment by pharnoux** [comment]
@maxpumperla @turambar 
The problem was that the conv1D was not supported and also that we could not load the word embedding layer of the model we exported with Keras. We had to use a simpler layer and remove the word embeddings from the model to load the as a separate file to make this work.

**Comment by maxpumperla** [comment]
@pharnoux OK, I just want to understand what's going on here. We already have a ticket for conv1d support, see #3101, and this layer type "Model" seems to be misconfiguration, as @turambar suggests.

In light of this, would it make sense to close this issue or is there something to be done still?

**Comment by turambar** [comment]
I vote close it.

**Comment by maxpumperla** [comment]
OK, me too. @pharnoux if you disagree or run into trouble again, please feel free to reopen. thanks

**Comment by LeeTL1220** [comment]
@turambar @maxpumperla This was just lack of Conv1D from my point of view.
