### ISSUE TITLE
ERROR: Exception caught in Netty: java.lang.NoSuchMethodError: org.jboss.netty.handler.codec.http.HttpRequest.headers()Lorg/jboss/netty/handler/codec/http/HttpHeaders

### ISSUE THREAD

**Issue by mhauschild** [deeplearning4j/deeplearning4j#3332]
Hi,
tried to run the DL4J UI. While requesting localhost:9000 in the browser I get an empty response and that exception below pops up.
Has anyone had the same issue?

Thanks a lot.

###
UIServer uiServer = UIServer.getInstance();
StatsStorage statsStorage = new InMemoryStatsStorage();
model.setListeners(new StatsListener(statsStorage));
uiServer.attach(statsStorage);
...
#### Version Information

* Deeplearning4j version: 0.8.0
* platform information (Win10)

2017-04-30 00:08:04 [New I/O worker #1] play.api.LoggerLike$class.error()
ERROR: Exception caught in Netty: java.lang.NoSuchMethodError: org.jboss.netty.handler.codec.http.HttpRequest.headers()Lorg/jboss/netty/handler/codec/http/HttpHeaders;
	at play.core.server.netty.PlayDefaultUpstreamHandler.getHeaders(PlayDefaultUpstreamHandler.scala:313)
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anon$1.<init>(PlayDefaultUpstreamHandler.scala:107)
	at play.core.server.netty.PlayDefaultUpstreamHandler.play$core$server$netty$PlayDefaultUpstreamHandler$$createRequestHeader$1(PlayDefaultUpstreamHandler.scala:99)
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$6.apply(PlayDefaultUpstreamHandler.scala:123)
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$6.apply(PlayDefaultUpstreamHandler.scala:121)
	at scala.util.Either.fold(Either.scala:97)
	at play.core.server.netty.PlayDefaultUpstreamHandler.messageReceived(PlayDefaultUpstreamHandler.scala:120)
	at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:62)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by AlexDBlack** [comment]
```Exception caught in Netty: java.lang.NoSuchMethodError: ```

My guess: you've probably got conflicting versions of dependencies (netty, etc) in your project. This can occur if you mix multiple UI libraries (play + dropwizard) or could in principle occur with other libraries (like Spark + play). DL4J uses the Play framework for our UI.

You might be able to gain some insight using "mvn dependency:tree" on the command line (assuming you are using maven).

**Comment by mhauschild** [comment]
Thanks a lot that feedback. At the first look I couldn't find any conflicts regarding netty. All netty dependencies occur within the dl4j ui itself. Neither could I find any spark dependencies. Not sure how I continue to fix that issue. :(

or could this issue also regard to any hadoop dependency?

Here a cutout with all netty occurrences:
>[INFO] +- org.deeplearning4j:deeplearning4j-ui_2.10:jar:0.8.0:compile
[INFO] |  +- org.deeplearning4j:deeplearning4j-play_2.10:jar:0.8.0:compile
[INFO] |  |  +- com.typesafe.play:play-java_2.10:jar:2.4.6:compile
[INFO] |  |  |  +- org.scala-lang:scala-library:jar:2.10.5:compile
[INFO] |  |  |  +- com.typesafe.play:play_2.10:jar:2.4.6:compile
[INFO] |  |  |  |  +- com.typesafe.play:build-link:jar:2.4.6:compile
[INFO] |  |  |  |  |  \- com.typesafe.play:play-exceptions:jar:2.4.6:compile
[INFO] |  |  |  |  +- com.typesafe.play:play-iteratees_2.10:jar:2.4.6:compile
[INFO] |  |  |  |  |  \- com.typesafe:config:jar:1.3.0:compile
[INFO] |  |  |  |  +- com.typesafe.play:play-json_2.10:jar:2.4.6:compile
[INFO] |  |  |  |  |  +- com.typesafe.play:play-functional_2.10:jar:2.4.6:compile
[INFO] |  |  |  |  |  \- com.typesafe.play:play-datacommons_2.10:jar:2.4.6:compile
[INFO] |  |  |  |  +- com.typesafe.play:play-netty-utils:jar:2.4.6:compile
[INFO] |  |  |  |  +- com.typesafe.play:twirl-api_2.10:jar:1.1.1:compile
[INFO] |  |  |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.12:compile
[INFO] |  |  |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.12:compile
[INFO] |  |  |  |  +- ch.qos.logback:logback-core:jar:1.1.3:compile
[INFO] |  |  |  |  +- ch.qos.logback:logback-classic:jar:1.1.3:compile
[INFO] |  |  |  |  +- com.typesafe.akka:akka-actor_2.10:jar:2.3.13:compile
[INFO] |  |  |  |  +- com.typesafe.akka:akka-slf4j_2.10:jar:2.3.13:compile
[INFO] |  |  |  |  +- org.scala-stm:scala-stm_2.10:jar:0.7:compile
[INFO] |  |  |  |  +- org.joda:joda-convert:jar:1.7:compile
[INFO] |  |  |  |  +- javax.transaction:jta:jar:1.1:compile
[INFO] |  |  |  |  +- com.google.inject:guice:jar:4.0:compile
[INFO] |  |  |  |  |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  |  |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  |  |  |  \- com.google.inject.extensions:guice-assistedinject:jar:4.0:compile
[INFO] |  |  |  +- org.scala-lang.modules:scala-java8-compat_2.10:jar:0.3.0:compile
[INFO] |  |  |  +- org.hibernate:hibernate-validator:jar:5.0.3.Final:compile
[INFO] |  |  |  |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  |  |  \- com.fasterxml:classmate:jar:1.0.0:compile
[INFO] |  |  |  +- org.jboss.logging:jboss-logging:jar:3.2.1.Final:compile
[INFO] |  |  |  +- org.springframework:spring-context:jar:4.1.6.RELEASE:compile
[INFO] |  |  |  +- org.springframework:spring-core:jar:4.1.6.RELEASE:compile
[INFO] |  |  |  +- org.springframework:spring-beans:jar:4.1.6.RELEASE:compile
[INFO] |  |  |  +- net.jodah:typetools:jar:0.4.3:compile
[INFO] |  |  |  +- com.google.code.findbugs:jsr305:jar:2.0.3:compile
[INFO] |  |  |  +- org.apache.tomcat:tomcat-servlet-api:jar:8.0.21:compile
[INFO] |  |  |  \- org.javassist:javassist:jar:3.19.0-GA:compile
[INFO] |  |  +- com.typesafe.play:play-netty-server_2.10:jar:2.4.6:compile
[INFO] |  |  |  +- com.typesafe.play:play-server_2.10:jar:2.4.6:compile
[INFO] |  |  |  +- io.netty:netty:jar:3.10.4.Final:compile
[INFO] |  |  |  \- com.typesafe.netty:netty-http-pipelining:jar:1.1.4:compile
[INFO] |  |  +- com.typesafe.akka:akka-contrib_2.10:jar:2.3.13:compile
[INFO] |  |  |  +- com.typesafe.akka:akka-remote_2.10:jar:2.3.13:compile
[INFO] |  |  |  |  \- org.uncommons.maths:uncommons-maths:jar:1.2.2a:compile
[INFO] |  |  |  \- com.typesafe.akka:akka-persistence-experimental_2.10:jar:2.3.13:compile
[INFO] |  |  |     +- org.iq80.leveldb:leveldb:jar:0.5:compile
[INFO] |  |  |     |  \- org.iq80.leveldb:leveldb-api:jar:0.5:compile
[INFO] |  |  |     \- org.fusesource.leveldbjni:leveldbjni-all:jar:1.7:compile
[INFO] |  |  |        +- org.fusesource.leveldbjni:leveldbjni:jar:1.7:compile
[INFO] |  |  |        |  \- org.fusesource.hawtjni:hawtjni-runtime:jar:1.8:compile
[INFO] |  |  |        +- org.fusesource.leveldbjni:leveldbjni-osx:jar:1.5:compile
[INFO] |  |  |        +- org.fusesource.leveldbjni:leveldbjni-linux32:jar:1.5:compile
[INFO] |  |  |        +- org.fusesource.leveldbjni:leveldbjni-linux64:jar:1.5:compile
[INFO] |  |  |        +- org.fusesource.leveldbjni:leveldbjni-win32:jar:1.5:compile
[INFO] |  |  |        \- org.fusesource.leveldbjni:leveldbjni-win64:jar:1.5:compile
[INFO] |  |  +- org.reflections:reflections:jar:0.9.10:compile
[INFO] |  |  |  \- com.google.code.findbugs:annotations:jar:2.0.1:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.4.4:compile
[INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-scala_2.10:jar:2.4.4:compile
[INFO] |  |  |  +- org.scala-lang:scala-reflect:jar:2.10.4:compile
[INFO] |  |  |  \- com.thoughtworks.paranamer:paranamer:jar:2.6:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.4.4:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.4.4:compile
[INFO] |  |  +- com.typesafe.akka:akka-cluster_2.10:jar:2.3.13:compile
[INFO] |  |  \- com.beust:jcommander:jar:1.27:compile
[INFO] |  +- javax.ws.rs:javax.ws.rs-api:jar:2.0:compile
[INFO] |  +- org.deeplearning4j:deeplearning4j-ui-model:jar:0.8.0:compile
[INFO] |  |  +- org.agrona:Agrona:jar:0.5.4:compile
[INFO] |  |  +- org.mapdb:mapdb:jar:3.0.2:compile
[INFO] |  |  |  +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.0.2:compile
[INFO] |  |  |  |  \- org.jetbrains.kotlin:kotlin-runtime:jar:1.0.2:compile
[INFO] |  |  |  +- org.eclipse.collections:eclipse-collections-api:jar:7.1.1:compile (version selected from constraint [7.0.0,7.20.0))
[INFO] |  |  |  |  \- net.jcip:jcip-annotations:jar:1.0:compile
[INFO] |  |  |  +- org.eclipse.collections:eclipse-collections:jar:7.1.1:compile (version selected from constraint [7.0.0,7.20.0))
[INFO] |  |  |  +- org.eclipse.collections:eclipse-collections-forkjoin:jar:7.1.1:compile (version selected from constraint [7.0.0,7.20.0))
[INFO] |  |  |  +- net.jpountz.lz4:lz4:jar:1.3.0:compile
[INFO] |  |  |  \- org.mapdb:elsa:jar:3.0.0-M5:compile
[INFO] |  |  \- org.xerial:sqlite-jdbc:jar:3.15.1:compile
[INFO] |  \- org.deeplearning4j:deeplearning4j-ui-resources:jar:0.8.0:compile

Any comments or feedback are highly appreciated.

**Comment by mhauschild** [comment]
Hi,
I removed all dependencies who correspond to *netty*. Now I got just those netty dependency by the dl4j framework.
Does anybody see here why the exception still occurs? 
![image](https://cloud.githubusercontent.com/assets/16018113/25912485/bc3d8960-35b7-11e7-9cc3-eddc5acbbe84.png)

**Comment by AlexDBlack** [comment]
@mhauschild I can't see any issues from  what you've posted, so it's a bit of a mystery.

Could you post your complete pom.xml file? That might provide some insights as to possible causes.

**Comment by Whongb** [comment]
it is conflicting versions of dependencies, my project is ok now .thank you @AlexDBlack  @mhauschild
