### ISSUE TITLE
Review and refactor ETL and iterator APIs

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3338]
Some issues and things that could be improved:
- DataSet and MultiDataSet split (including: DataSetIterator, MultiDataSetIterator; preprocessors etc)
    - Long term: it would be better to combine these. Otherwise: we end up having 2 of everything... preprocessors, normalizers, fit methods, etc.
    - The challenge here: probably 75+% of users will have single input/output array nets, and shouldn't have to deal with the INDArray[]s of the current MultiDataSet
- RecordReaderDataSetIterator and RecordReaderMultiDataSetIterator:
    - 2 separate implementations, but in reality the former is a special case of the latter
    - Also: should these be in DL4J, or DataVec? They are dependent on ND4J and DataVec APIs only, afaik
    - While we are at it: let's make them persistable to/from JSON
- (Spark) DataVecDataSetFunction: should be a simple wrapper around the RecordReaderDataSetIterator, and not have any actual implementation
    - Could also be moved to DataVec too
- Normalization for Spark: we should be able to use the exact same APIs to run normalization and preprocessing in Spark training...
    - And it should be possible to fit a normalizer on spark and use it locally - or vice-versa
    - Spark ```fit(RDD<DataSet>)``` can't use preprocessors in general currently either
    - This should be easy enough: the main thing we need to add is the ability to merge normalizers (it'd be the exact same process as Evaluation via the IEvaluation interface, which can also be done in a distributed manner)

**Comment by raver119** [comment]
Is this issue still viable?

**Comment by AlexDBlack** [comment]
Yes and no. Given the (long promised) datavec refactoring, this will all be taken care of there.
