### ISSUE TITLE
Optimize SubsamplingLayer - dedicated ops instead of im2col + reduce

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3345]
For subsampling, currently we do im2col then do a reduce (mean, max, sum, pnorm).

However, we could combine these two: i.e., do the same im2col op, but do a running reduce op on the elements as we iterate over them.

This gives us:
- No need to manually allocate a very large im2col result array
- Faster performance: process the data once, rather than processing it twice, separately

**Comment by raver119** [comment]
Was implemented long ago.
