### ISSUE TITLE
Saving and Loading SequenceVectorText

### ISSUE THREAD

**Issue by Jonna28** [deeplearning4j/deeplearning4j#3349]
I tried to save and load the sequencevectorText example and it ends up with the following error.
I have pasted the program i have tried. Kindly let me know where it goes wrong.

package org.deeplearning4j.examples.nlp.sequencevectors;

import org.deeplearning4j.models.embeddings.loader.WordVectorSerializer;
import org.deeplearning4j.models.sequencevectors.SequenceVectors;
import org.deeplearning4j.models.sequencevectors.interfaces.SequenceElementFactory;
import org.deeplearning4j.models.sequencevectors.serialization.VocabWordFactory;
import org.deeplearning4j.models.word2vec.VocabWord;
import org.deeplearning4j.text.tokenization.tokenizer.preprocessor.CommonPreprocessor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;

import org.datavec.api.util.ClassPathResource;
import org.deeplearning4j.models.word2vec.wordstore.inmemory.AbstractCache;
import org.deeplearning4j.text.sentenceiterator.BasicLineIterator;
import org.deeplearning4j.text.tokenization.tokenizerfactory.TokenizerFactory;
import org.deeplearning4j.text.tokenization.tokenizerfactory.DefaultTokenizerFactory;
import org.deeplearning4j.models.sequencevectors.transformers.impl.SentenceTransformer;
import org.deeplearning4j.models.sequencevectors.iterators.AbstractSequenceIterator;
import org.deeplearning4j.models.word2vec.wordstore.VocabConstructor;
import org.deeplearning4j.models.embeddings.WeightLookupTable;
import org.deeplearning4j.models.embeddings.inmemory.InMemoryLookupTable;
import org.deeplearning4j.models.embeddings.learning.impl.elements.SkipGram;
import org.deeplearning4j.models.embeddings.loader.VectorsConfiguration;

/**
 * This is example of abstract sequence of data is learned using SequenceVectors. In this example, we use text sentences as Sequences, and VocabWords as SequenceElements.
 * So, this example is  a simple demonstration how one can learn distributed representation of data sequences.
 *
 * For training on different data, you can extend base class SequenceElement, and feed model with your Iterable. Aslo, please note, in this case model persistence should be handled on your side.
 *
 * *************************************************************************************************
 * PLEASE NOTE: THIS EXAMPLE REQUIRES DL4J/ND4J VERSIONS >= rc3.8 TO COMPILE SUCCESSFULLY
 * *************************************************************************************************
 * @author raver119@gmail.com
 */
public class SequenceVectorsTextExample {

    protected static final Logger logger = LoggerFactory.getLogger(SequenceVectorsTextExample.class);

    public static void main(String[] args) throws Exception {

        SequenceVectorsTextExample train = new SequenceVectorsTextExample();
        train.SequenceVectorTrain();
        train.SequenceVectorTest();
    }

    public void SequenceVectorTrain() throws IOException {

        SequenceElementFactory f1 = new VocabWordFactory();

        ClassPathResource resource = new ClassPathResource("travelInsuranceCorpus.txt");
        File file = resource.getFile();

        AbstractCache<VocabWord> vocabCache = new AbstractCache.Builder<VocabWord>().build();

        BasicLineIterator underlyingIterator = new BasicLineIterator(file);

        TokenizerFactory t = new DefaultTokenizerFactory();
        t.setTokenPreProcessor(new CommonPreprocessor());

        SentenceTransformer transformer = new SentenceTransformer.Builder()
            .iterator(underlyingIterator)
            .tokenizerFactory(t)
            .build();

        AbstractSequenceIterator<VocabWord> sequenceIterator = new AbstractSequenceIterator.Builder<>(transformer).build();

        VocabConstructor<VocabWord> constructor = new VocabConstructor.Builder<VocabWord>()
            .addSource(sequenceIterator, 5)
            .setTargetVocabCache(vocabCache)
            .build();

        constructor.buildJointVocabulary(false, true);

        WeightLookupTable<VocabWord> lookupTable = new InMemoryLookupTable.Builder<VocabWord>()
            .lr(0.025)
            .vectorLength(150)
            .useAdaGrad(false)
            .cache(vocabCache)
            .build();

        lookupTable.resetWeights(true);

        SequenceVectors<VocabWord> vectors = new SequenceVectors.Builder<VocabWord>(new VectorsConfiguration())

            .minWordFrequency(5)
            .lookupTable(lookupTable)
            .iterate(sequenceIterator)
            .vocabCache(vocabCache)
            .batchSize(250)
            .iterations(100)
            .epochs(1)
            .resetModel(false)
            .trainElementsRepresentation(true)
            .trainSequencesRepresentation(false)
            .elementsLearningAlgorithm(new SkipGram<VocabWord>())
            .build();

        vectors.fit();
        File locationToSave = new File("d:/dl4j/sequenceVectorTrainedModel.zip");
        boolean saveUpdater = true;
        WordVectorSerializer.writeSequenceVectors(vectors, f1, "d:/dl4j/sequenceVectorTrainedModel.zip");
    }

    public void SequenceVectorTest() throws IOException {

        SequenceElementFactory f1 = new VocabWordFactory();
        File locationToSave = new File("d:/dl4j/sequenceVectorTrainedModel.bin");
        SequenceVectors<VocabWord> vectors = WordVectorSerializer.readSequenceVectors(f1, locationToSave);
        double sim = vectors.similarity("insurance", "policy");
        logger.info("insurance/policy similarity: " + sim);

    }
}

Error:

o.d.m.s.SequenceVectors - Epoch: [1]; Words vectorized so far: [53844811];  Lines vectorized so far: [7400000]; learningRate: [1.4067073564852652E-4]
o.d.m.s.SequenceVectors - Epoch: [1]; Words vectorized so far: [54149500];  Lines vectorized so far: [7458400]; learningRate: [1.0E-4]
o.d.m.s.SequenceVectors - Time spent on training: 621629 ms
Exception in thread "main" java.lang.RuntimeException: org.nd4j.shade.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 1]
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer$ElementPair.fromEncodedJson(WordVectorSerializer.java:2212)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readSequenceVectors(WordVectorSerializer.java:2071)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readSequenceVectors(WordVectorSerializer.java:2048)
	at org.deeplearning4j.examples.nlp.sequencevectors.SequenceVectorsTextExample.SequenceVectorTest(SequenceVectorsTextExample.java:113)
	at org.deeplearning4j.examples.nlp.sequencevectors.SequenceVectorsTextExample.main(SequenceVectorsTextExample.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.nd4j.shade.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 1]
	at org.nd4j.shade.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at org.nd4j.shade.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3607)
	at org.nd4j.shade.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3547)
	at org.nd4j.shade.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer$ElementPair.fromEncodedJson(WordVectorSerializer.java:2210)
	... 9 more

Process finished with exit code 1

Please help me with this. Thanks in advance.

**Comment by cy9707** [comment]
老哥 你这问题解决了没

**Comment by raver119** [comment]
@cy9707 please use english language, if possible. And please, file new issues if you face problem, do not post in closed issues.
