### ISSUE TITLE
Frozen layers are disregarded when training with Spark

### ISSUE THREAD

**Issue by sethah** [deeplearning4j/deeplearning4j#3351]
#### Issue Description

I am trying to do transfer learning with Spark. In the code below, I have loaded a model which has the following structure:

"fc1 (input)" -> "fc2" -> "predictions"

I intend to only train the predictions. 

````scala
    val tm = new ParameterAveragingTrainingMaster.Builder(1)
        .averagingFrequency(param.averagingFrequency)
        .workerPrefetchNumBatches(2)
        .batchSizePerWorker(param.batchSizePerWorker)
        .rddTrainingApproach(RDDTrainingApproach.Export)
        .build()

      val fineTuneConf = new FineTuneConfiguration.Builder()
        .learningRate(param.learningRate)
        .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
        .updater(Updater.NESTEROVS)
        .momentum(param.momentum)
        .regularization(true)
        .l2(param.regularization)
        .seed(seed)
        .build()
      val restoredNetwork = new TransferLearning.GraphBuilder(restored)
        .fineTuneConfiguration(fineTuneConf)
        .setFeatureExtractor("fc2")
        .build()

      val model = new SparkComputationGraph(sc, restoredNetwork, tm)
````

The parameters for "fc2" should not change - they should be frozen - but still, they do. I have also tested this same code, but NOT using the Spark trainer and it works as expected.

The problem, AFAICT, is this: when the computation graph is broadcast, only its configuration and its parameters get serialized. Then, the workers reconstruct the graph from the config and params. However, in `TransferLearning.GraphBuilder.build()` the `newConfig` does not reflect that some of the layers are frozen. The `newGraph`, however, does have the frozen layers. This explains why it works locally, but not on the Spark executors. 

I have not quite figured out how to fix this, though it seems as simple as adding the frozen layers to the configuration in the `build()` method. At this point, I'm relatively confident this is a bug, but definitely possible I've overlooked something.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.8.0
* platform information (OS, etc): Mac OSX Sierra 10.12.4

#### Contributing

I can look into this, though I won't be upset if someone else wants to fix it faster.

**Comment by sethah** [comment]
cc @huitseeker @AlexDBlack

**Comment by eraly** [comment]
It's a bug. We wanted to keep the conf devoid of references to frozen layers. We might still want to. Although not sure how we want to work around this right now.

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/3653
Issue will be closed once that PR is merged.
