### ISSUE TITLE
ComputationGraph.score() returns the same score for different DataSets

### ISSUE THREAD

**Issue by mjakobus** [deeplearning4j/deeplearning4j#3354]
#### Issue Description

```
double valScore = model.score(valDataSet);
double testScore = model.score(testDataSet);

System.out.println("Val Score: " + valScore + " - Test Score: " + testScore + " - Scores equal: " + (valScore == testScore));
```

Example output:

> Val Score: 0.2700222558983315 - Test Score: 0.2700222558983315 - Scores equal: true

The score of the two (randomly generated) DataSets is always the same. This behaviour appeared a few days ago using the snapshot-0.8.1 with the cuda backend and is still present (just reimported the maven dependencies a few minutes ago).

**Example program for reproduction:**
https://gist.github.com/mjakobus/c9fa4a0159355c0abfcb9284a9690c8d

Line 118-122: Creating the DataSets
Line 398-404: Calling the score() function with the created DataSets

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: snaptshot 0.8.1
* platform information (OS, etc): Windows 10 64 bit, Java 8
* CUDA version, if used: cuda 8.0 backend

**Comment by AlexDBlack** [comment]
This is reproducable - on both native and cuda backends, with current master (0.8.1-SNAPSHOT)
Scores are indeed different with 0.8.0 release (only tested native).

So far I've ruled out workspaces as the cause here,  but haven't isolated it beyond that.

**Comment by raver119** [comment]
I've set both workspace modes to NONE, and result is the same.

**Comment by raver119** [comment]
And yes, i'm sure that option works, i've added printout of workspaces for current thread, and that's what i have after every epoch:

```
Val Score: 0.2755936933816051 - Test Score: 0.2755936933816051 - Scores equal: true
o.n.l.m.p.BasicWorkspaceManager - Workspace statistics: ---------------------------------
Val Score: 0.2743769241266396 - Test Score: 0.2743769241266396 - Scores equal: true
o.n.l.m.p.BasicWorkspaceManager - Workspace statistics: ---------------------------------
Val Score: 0.27530370478753724 - Test Score: 0.27530370478753724 - Scores equal: true
o.n.l.m.p.BasicWorkspaceManager - Workspace statistics: ---------------------------------
Val Score: 0.2739141535832005 - Test Score: 0.2739141535832005 - Scores equal: true
o.n.l.m.p.BasicWorkspaceManager - Workspace statistics: ---------------------------------
Val Score: 0.272276647056457 - Test Score: 0.272276647056457 - Scores equal: true
o.n.l.m.p.BasicWorkspaceManager - Workspace statistics: ---------------------------------

**Comment by AlexDBlack** [comment]
I've tried to cut this down to something more manageable. And I've confirmed that score calculation is wrong for both datasets.

https://gist.github.com/AlexDBlack/e1bec417640a77c205f4d63839e8304d

**Comment by AlexDBlack** [comment]
Got it. Check lines 1777 vs. 1801.

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/graph/ComputationGraph.java#L1777-L1801

double score -> used to have a different scope than it does now - it used to shade ComputationGraph.score, now it doesn't.

Fix incoming.

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/3357
I'll merge that once tests have finished.
