### ISSUE TITLE
mvn clean install is failing

### ISSUE THREAD

**Issue by arnabroy** [deeplearning4j/deeplearning4j#3355]
[INFO] Reactor Summary:
[INFO] 
[INFO] DeepLearning4j Examples Parent ..................... SUCCESS [  9.024 s]
[INFO] DeepLearning4j Examples ............................ SUCCESS [05:53 min]
[INFO] dl4j-spark-examples ................................ SUCCESS [  1.057 s]
[INFO] dl4j-spark ......................................... SUCCESS [04:52 min]
[INFO] datavec-examples ................................... SUCCESS [02:56 min]
[INFO] DeepLearning4j CUDA special examples ............... FAILURE [31:34 min]
[INFO] nd4j-examples ...................................... SKIPPED
[INFO] Reinforcement Learning4j Examples .................. SKIPPED
[INFO] arbiter-examples ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 45:28 min
[INFO] Finished at: 2017-05-04T01:14:41-07:00
[INFO] Final Memory: 57M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project dl4j-cuda-specific-examples: Could not resolve dependencies for project org.deeplearning4j:dl4j-cuda-specific-examples:jar:0.8-SNAPSHOT: The following artifacts could not be resolved: org.nd4j:nd4j-cuda-8.0:jar:linux-x86_64:0.8.0, org.nd4j:nd4j-cuda-8.0:jar:macosx-x86_64:0.8.0, org.nd4j:nd4j-cuda-8.0:jar:linux-ppc64le:0.8.0: Could not transfer artifact org.nd4j:nd4j-cuda-8.0:jar:linux-x86_64:0.8.0 from/to central (https://repo.maven.apache.org/maven2): GET request of: org/nd4j/nd4j-cuda-8.0/0.8.0/nd4j-cuda-8.0-0.8.0-linux-x86_64.jar from central failed: Read timed out -> [Help 1]

**Comment by raver119** [comment]
>  GET request of: org/nd4j/nd4j-cuda-8.0/0.8.0/nd4j-cuda-8.0-0.8.0-linux-x86_64.jar from central failed: Read timed out -> [Help 1]

That's problem with your ISP, not with examples or dl4j.
