### ISSUE TITLE
GradientAdjustment: momentum parameter

### ISSUE THREAD

**Issue by asenfter** [deeplearning4j/deeplearning4j#336]
The momentum parameter in class org.deeplearning4j.optimize.GradientAdjustment is used to increase the current gradient like this:

```
if (momentum > 0) 
    gradient.addi(gradient.mul(momentum).addi(gradient.mul(1 - momentum)));
```

For arbitrary momentum>0 the code therefore simply does the the same like

```
gradient.addi(gradient) or gradient.muli(2)
```

**Comment by agibsonccc** [comment]
It took me a bit to decipher what you meant. I'm going to repurpose this as an excuse to implement RMS Prop and the step cache needed for nesterov's. Should have this done soon.

**Comment by agibsonccc** [comment]
Done:
https://github.com/deeplearning4j/deeplearning4j/blob/bef15d6a5329e095746c328575e25eb962383928/deeplearning4j-core/src/main/java/org/deeplearning4j/optimize/GradientAdjustment.java#L125-125

This will be merged in to master by EOD. Need to add adadelta yet as well.
