### ISSUE TITLE
List of Install Steps * these are just notes, probably need to add to quickstart

### ISSUE THREAD

**Issue by tomthetrainer** [deeplearning4j/deeplearning4j#3366]
I am building a new machine for Labs, 

I find the following steps are needed

Update Maven
Find path to javaxrt ? Or whatever that package is. THis.. JAVAFX_HOME

Needs to be set.

This is quick way to get maven... might violate some best practices in package management by over-riding symlink for /usr/bin/mvn, meaning some update might blow this away as the mvn pacakge owned that symlink

latest=$(curl http://www-us.apache.org/dist/maven/maven-3/ | tac | sed -ne 's/[^0-9]*\(\([0-9]\.\)\{0,3\}[0-9]\).*/\1/p' | head -1)
  124  wget http://www-us.apache.org/dist/maven/maven-3/$latest/binaries/apache-maven-$latest-bin.tar.gz
  125  sudo tar -zxf apache-maven-$latest-bin.tar.gz -C /usr/local/
  126  sudo ln -s /usr/local/apache-maven-$latest/bin/mvn /usr/bin/mvn
  127  ls /usr/bin/mvn
  128  rm /usr/bin/mvn
  129  sudo ln -s /usr/local/apache-maven-$latest/bin/mvn /usr/bin/mvn
  130  mvn -version

**Comment by huitseeker** [comment]
No, this is the fast way to get maven : 
https://github.com/deeplearning4j/java_deps/blob/master/tasks/main.yml#L7

JAVAFX_HOME is only needed for dl4j-examples if your Java is < 1.8, see:
https://github.com/deeplearning4j/dl4j-examples/blob/master/pom.xml#L129

**Comment by huitseeker** [comment]
More context here: https://github.com/deeplearning4j/dl4j-examples/#known-issues

**Comment by RobAltena** [comment]
Installing maven should not be any more complicated than:
sudo apt-get install maven

This might not get you the latest version (3.3.9 vs 3.5.0), but it will get you a good enough version to do deeplerning4J.

**Comment by huitseeker** [comment]
This was an issue for dl4j-examples, solved by the addition of the external javafx jar to the dependencies of the dl4j-examples module under IntelliJ. Much more documentation in https://github.com/deeplearning4j/dl4j-examples/blob/master/README.md#on-intellij

Closing this for now as the issues seem resolved, please open another issue under the dl4j-examples repo if you're facing other issues @tomthetrainer.

**Comment by tomthetrainer** [comment]
Thanks @huitseeker I meant to make this a documentation issue,
