### ISSUE TITLE
MultiLayerNetwork/ComputationGraph: add "multiple eval in one pass" option

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3371]
Sometimes: we want to do multiple evaluations... Evaluation and ROC, for example
MultiLayerNetwork/ComputationGraph.doEvaluation methods only support one. It's wasteful to either
(a) manually iterate (no workspaces)
(b) do 2 passes, when 1 would be enough

**Comment by raver119** [comment]
Implemented
