### ISSUE TITLE
IterationListeners and workspaces

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#3376]
After looking into some 3rd party IterationListener, i think it's really good idea to push all IterationListeners invocations out of training workspaces. To reduce chances someone will do something that will enforce workspace size to explode

**Comment by AlexDBlack** [comment]
Good idea. This stops workspaces from breaking users' existing custom listeners, and makes then less error prone for people who don't *really* understand workspaces (i.e., most people).
Where it's safe to do so (in our own listeners): we should manually handle workspaces internally.

**Comment by raver119** [comment]
Implemented
