### ISSUE TITLE
missing carriage return characters when reading text with FilenamesLabelAwareIterator 

### ISSUE THREAD

**Issue by todoacien** [deeplearning4j/deeplearning4j#3382]
#### Issue Description

Carriage return characters are missing from Labelled documents that are provided by "FilenamesLabelAwareIterator " iterator.
When checking content from labelled documents, there are not end of lines characters, so that, all lines are concanated together.

Visible when doing:  https://gist.github.com/todoacien/35adc1f94097c66d79e002da7a3bf476

#### Version Information

* Deeplearning4j 0.7.2
* platform information Windows

**Comment by raver119** [comment]
Fixed
