### ISSUE TITLE
Parallel Early stopping training causes ND4JIllegalStateException: memset failed

### ISSUE THREAD

**Issue by Alcalol** [deeplearning4j/deeplearning4j#3386]
When using parallel early stopping trainer, after some amount of training a ND4JIllegalStateException is thrown with reason as "memset failed".  P2P (isCrossDeviceAccessSupported()) is false.  Was asked by Raver119 to raise issue.

Dl4j 0.8.1 snapshot
Windows 10
Cuda version 8.0.61
NVidia driver 381.89
2x GTX 780 with SLi off

was also asked to provide network config, earlystopping config and data description, provided in gist below.

https://gist.github.com/Alcalol/a84c3ffb982833ef7d7f2dc87148a120

**Comment by raver119** [comment]
Issue is fixed now.
