### ISSUE TITLE
LabelAwareIterator could not be used in word2vec iterator method

### ISSUE THREAD

**Issue by sivu1** [deeplearning4j/deeplearning4j#3391]
#### Issue Description

Compilation error : `The method iterate(DocumentIterator) in the type Word2Vec.Builder is not applicable for the arguments (LabelAwareIterator)`

The interface `LabelAwareIterator` is implemented to the use case needed which in my case to read pdf files for word2vec. So, I have implemented the interface to read pdf files via `pdfbox` and returns each file as type `LabelledDocument` and iterator as type `LabelAwareIterator`. The iterator was working good when tested alone, but in `word2vec.builder().iterate()`  the datatype `LabelAwareIterator` was not accepted as an argument.

#### Version Information
Deeplearning4j version 0.8.0 on Windows

**Comment by raver119** [comment]
Clearly fixed long ago.
