### ISSUE TITLE
dl4j-spark : log4j.properties & logback.xml 

### ISSUE THREAD

**Issue by geekco2000** [deeplearning4j/deeplearning4j#3395]
Hello, 

I'm actually tring to implement my own dl4j-spark project (based on examples), but there is something I haven't found any answer nowhere, in the project : dl4j-examples-scala, there is a folder called "ressources" 
(dl4j-examples-scala/dl4j-spark-examples/dl4j-spark/src/main/), there are two files, "log4j.properties" and "logback.xml". I am sure these files are important in some way, but I don't know what's the purpose of them ? Could someone can tell me more about them please ? 

Thank you !

**Comment by marcel-93** [comment]
I would suggest to you asking this question on the gitter channel. There you have direct contact to the developer.
[https://gitter.im/deeplearning4j/deeplearning4j](url)

**Comment by AlexDBlack** [comment]
@geekco2000 They are for logging - configuration files for log4j and logback respectively.
We (like a lot of the java world) use SLF4J, which plugs into different logging implementations, including log4j or logback.
https://www.slf4j.org/

**Comment by geekco2000** [comment]
Thanks you guys !
