### ISSUE TITLE
Mention use of Lombok in docs for contributors 

### ISSUE THREAD

**Issue by kajsa** [deeplearning4j/deeplearning4j#3399]
https://deeplearning4j.org/buildinglocally doesn't mention the need for the lombok plugin for IntelliJ (and possibly other IDEs).

Following the instructions under "Building Manually" correctly gives a project that builds from Maven. Importing the project into IntelliJ (without lombok plugin) results in many compilation errors that are very confusing to someone without experience with Lombok.

Additionally, for potential contributors or others who want/need to run tests, it would be worth including a link to the dl4j-test-resources repo.

**Comment by crockpotveggies** [comment]
Documentation has been updated. Thank you for letting us know about this, please feel free to continue to file issues about gaps in documentation.
