### ISSUE TITLE
UI does not initiate when multiple input and outputs, but everything else fine

### ISSUE THREAD

**Issue by Joshuaalbert** [deeplearning4j/deeplearning4j#3401]
#### Issue Description

I have working code that works with the UI normally, but when I add multiple input/output it seems to confuse the UI. Nothing is updated on the UI. Learning can occur and the score is not updated on the UI. 

#### Version Information

0.8.0

**Comment by AlexDBlack** [comment]
"Seems to confuse the UI" - I'll need a configuration.
I've done multi-task and multiple input networks in the UI previously, without issue.

**Comment by Joshuaalbert** [comment]
Here's the conf: https://gist.github.com/Joshuaalbert/b36ab4ec2de3dd27a59ee7ea91f0f394

You can load with 
```
ComputationGraphConfiguration cgconf = new ValueRangeConf(1,1,1).getConf();
		ComputationGraph model = new ComputationGraph(cgconf);
        model.init();
        StatsStorage statsStorage = new InMemoryStatsStorage(); 
        int listenerFrequency = 1;
        UIServer uiServer = UIServer.getInstance();
        StatsListener statsList = new StatsListener(statsStorage, listenerFrequency);
        model.setListeners(statsList, new ScoreIterationListener(Constants.NEURAL_NET_ITERATION_LISTENER));
        uiServer.attach(statsStorage);
```

**Comment by AlexDBlack** [comment]
I can't run that - I'm missing ```ComputationGraphConf``` class and ```com.tactico.tm.nn.Constants```

**Comment by Joshuaalbert** [comment]
I've updated to not require those things.

**Comment by nkwoh01** [comment]
This looks resolved
