### ISSUE TITLE
Feature Request: Arbiter MultiLayerSpace only supports identical auto-gen'd layerspaces 

### ISSUE THREAD

**Issue by Stevod** [deeplearning4j/deeplearning4j#3406]
There is a parameter for the MultiLayerSpace (duplicateConfig) which allows the possibility of creating variable numbers of auto-generated layers, with different hyperparameters for each layer. Unfo, this is not yet implemented, which reduces the value of the Arbiter in exploring different NN architectures. Could it be added please?

This is the error, which I have checked in the github source code. My code is working fine using the Arbiter with identical layers (i.e. the duplicateConfig parameter is true)   

Exception in thread "main" java.lang.UnsupportedOperationException: Not yet implemented
	at org.deeplearning4j.arbiter.MultiLayerSpace.getValue(MultiLayerSpace.java:71)
	at org.deeplearning4j.arbiter.MultiLayerSpace.getValue(MultiLayerSpace.java:24)
	at 

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version =0.8
* platform information (OS, etc) = Ubuntu 16.10
* CUDA version, if used - 8
* NVIDIA driver version - 375.39

**Comment by AlexDBlack** [comment]
Moved to Arbiter repo: https://github.com/deeplearning4j/Arbiter/issues/80
