### ISSUE TITLE
train status not post to remote ui server

### ISSUE THREAD

**Issue by SidneyLann** [deeplearning4j/deeplearning4j#3425]
#### Issue Description
train status not post to remote ui server when run by spark submit, but when run in local mode,the remote ui server got the train status.

- expected behavior
remote ui server shown the diagram about training status

- encountered behavior
train status not post to remote ui server when run by spark submit

#### Version Information
dl4j 0.8
centos 7
mesos 1
spark 2.1
scala 2.11

**Comment by SidneyLann** [comment]
package com.bj.imgreg;

import java.io.InputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.FileStatus;
import org.apache.spark.SparkConf;
import org.apache.spark.api.java.JavaRDD;
import org.apache.spark.api.java.JavaSparkContext;
import org.apache.spark.api.java.function.Function;
import org.datavec.image.loader.NativeImageLoader;
import org.deeplearning4j.api.storage.StatsStorageRouter;
import org.deeplearning4j.api.storage.impl.RemoteUIStatsStorageRouter;
import org.deeplearning4j.eval.Evaluation;
import org.deeplearning4j.nn.api.OptimizationAlgorithm;
import org.deeplearning4j.nn.conf.GradientNormalization;
import org.deeplearning4j.nn.conf.LearningRatePolicy;
import org.deeplearning4j.nn.conf.MultiLayerConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.Updater;
import org.deeplearning4j.nn.conf.distribution.Distribution;
import org.deeplearning4j.nn.conf.distribution.GaussianDistribution;
import org.deeplearning4j.nn.conf.distribution.NormalDistribution;
import org.deeplearning4j.nn.conf.inputs.InputType;
import org.deeplearning4j.nn.conf.layers.ConvolutionLayer;
import org.deeplearning4j.nn.conf.layers.DenseLayer;
import org.deeplearning4j.nn.conf.layers.LocalResponseNormalization;
import org.deeplearning4j.nn.conf.layers.OutputLayer;
import org.deeplearning4j.nn.conf.layers.SubsamplingLayer;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer;
import org.deeplearning4j.spark.impl.paramavg.ParameterAveragingTrainingMaster;
import org.deeplearning4j.ui.stats.StatsListener;
import org.deeplearning4j.util.ModelSerializer;
import org.nd4j.linalg.activations.Activation;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.dataset.api.preprocessor.DataNormalization;
import org.nd4j.linalg.dataset.api.preprocessor.ImagePreProcessingScaler;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.linalg.lossfunctions.LossFunctions;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.beust.jcommander.JCommander;
import com.beust.jcommander.Parameter;
import com.beust.jcommander.ParameterException;

public class PicRecognitionMain implements Serializable {
  private static final Logger log = LoggerFactory.getLogger(PicRecognitionMain.class);
  @Parameter(names = "-useSparkLocal", description = "Use spark local (helper for testing/running without spark submit)", arity = 1)
  private boolean useSparkLocal = true;
  protected static int height = 100;
  protected static int width = 100;
  protected static int channels = 3;
  protected static int numLabels = 4;
  protected static long seed = 42;
  protected static Random rng = new Random(seed);
  protected static int listenerFreq = 1;
  protected static int iterations = 1;
  @Parameter(names = "-epochs0", description = "epochs0", arity = 1)
  protected static int epochs0 = 2;
  @Parameter(names = "-epochs1", description = "epochs1", arity = 1)
  protected static int epochs1 = 1;
  protected static boolean saveUpdater = true;
  private final Map<String, Integer> labelNames = new HashMap<>();
  private final List<String> labelList = new ArrayList<>();
  private static final NativeImageLoader imageLoader = new NativeImageLoader(height, width, channels);
  private final DataNormalization scaler = new ImagePreProcessingScaler(0, 1);
  private final String imageFolder = "/spark/animals";
  private final String modelPath = "/spark/model.zip";

  public static void main(String[] args) throws Exception {
    new PicRecognitionMain().entryPoint(args);
  }

  private void entryPoint(String[] args) throws Exception {
    // Nd4j.ENFORCE_NUMERICAL_STABILITY = true;
    // Handle command line arguments
    JCommander jcmdr = new JCommander(this);
    try {
      jcmdr.parse(args);
    } catch (ParameterException e) {
      // User provides invalid input -> print the usage info
      jcmdr.usage();
      try {
        Thread.sleep(500);
      } catch (Exception e2) {
      }
      throw e;
    }

    labelNames.put("bear", 0);
    labelNames.put("deer", 1);
    labelNames.put("duck", 2);
    labelNames.put("turtle", 3);

    labelList.add("bear");
    labelList.add("deer");
    labelList.add("duck");
    labelList.add("turtle");

    // Set up the Spark-specific configuration
    int examplesPerWorker = 8; // i.e., minibatch size that each worker gets
    int averagingFrequency = 3; // Frequency with which parameters are averaged

    // Set up Spark configuration and context
    SparkConf sparkConf = new SparkConf();
    if (useSparkLocal) {
      sparkConf.setMaster("local[*]");
      log.info("Using Spark Local");
      long maxMem = Runtime.getRuntime().maxMemory();
      log.info("max mem=" + maxMem);
    }
    sparkConf.setAppName("DL4J Spark Stats Example");
    JavaSparkContext jsc = new JavaSparkContext(sparkConf);
    Configuration config = jsc.hadoopConfiguration();
    HdfsUtil hdfsUtil = new HdfsUtil(config);

    log.info("Load data....");
    FileStatus[] fileStatuses = hdfsUtil.listStatus(imageFolder, config);
    List<String> trainPaths = new ArrayList<>();
    List<String> testPaths = new ArrayList<>();
    for (FileStatus fileStatus : fileStatuses) {
      String filePath = imageFolder + "/" + fileStatus.getPath().getName();
      FileStatus[] fileStatuses2 = hdfsUtil.listStatus(filePath, config);
      for (FileStatus fileStatus2 : fileStatuses2) {
        String filePath2 = filePath + "/" + fileStatus2.getPath().getName();
        int r = (int) (Math.random() * 10);
        if (r % 5 == 0)
          testPaths.add(filePath2);
        else
          trainPaths.add(filePath2);
      }
    }

    JavaRDD<String> rddTrainPath = jsc.parallelize(trainPaths);
    JavaRDD<DataSet> rddImageTrain = getDataSet(rddTrainPath);
    JavaRDD<String> rddTestPath = jsc.parallelize(testPaths);
    JavaRDD<DataSet> rddImageTest = getDataSet(rddTestPath);

    ParameterAveragingTrainingMaster patMaster = new ParameterAveragingTrainingMaster.Builder(1).workerPrefetchNumBatches(2) // Async prefetch 2 batches for each worker
        // .averagingFrequency(averagingFrequency).batchSizePerWorker(examplesPerWorker).rddTrainingApproach(RDDTrainingApproach.Direct).exportDirectory(hdfsUtil.HOST + "/spark/tmp").build();
        // .averagingFrequency(averagingFrequency).batchSizePerWorker(examplesPerWorker).rddTrainingApproach(RDDTrainingApproach.Export).exportDirectory("/home/slann/tmp").build();
        .averagingFrequency(averagingFrequency).batchSizePerWorker(examplesPerWorker).build();

    try {
      MultiLayerNetwork ppModel = null;
      InputStream is = hdfsUtil.open(modelPath);
      if (is == null) {
        MultiLayerConfiguration netConf = getConfiguration();
        ppModel = new MultiLayerNetwork(netConf);
        log.info("***** new model *****");
      } else {
        ppModel = ModelSerializer.restoreMultiLayerNetwork(is);
        log.info("***** restored model *****");
      }

      // Create the Spark network
      SparkDl4jMultiLayer sparkNetwork = new SparkDl4jMultiLayer(jsc, ppModel, patMaster);
      sparkNetwork.setCollectTrainingStats(true);
      StatsStorageRouter remoteUIRouter = new RemoteUIStatsStorageRouter("http://192.168.0.34:9000");
      sparkNetwork.setListeners(remoteUIRouter, Collections.singletonList(new StatsListener(null)));
      // sparkNetwork.setListeners(new StatsListener(remoteUIRouter));
      // sparkNetwork.setListeners(new ScoreIterationListener(10));
      // StatsStorage ss = new FileStatsStorage(new File("myNetworkTrainingStats.dl4j"));
      // sparkNetwork.setListeners(ss, Collections.singletonList(new StatsListener(null)));

      for (int i = 0; i < epochs0; i++) {
        for (int j = 0; j < epochs1; j++) {
          sparkNetwork.fit(rddImageTrain);
          log.info("///////////////////////////////////////////////////////////////////////////////////////////Completed Epoch {}", i + "," + j);
        }

        // Perform evaluation (distributed)
        Evaluation evaluation = sparkNetwork.evaluate(rddImageTest);
        log.info("***** Evaluation *****");
        log.info(evaluation.stats());

        ModelSerializer.writeModel(ppModel, hdfsUtil.saveFile(modelPath), saveUpdater);
        log.info("***** saved model *****");
        Thread.sleep(10000);
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
    // Delete the temp training files, now that we are done with them (if fitting for multiple epochs: would be re-used)
    patMaster.deleteTempFiles(jsc);
    log.info("****************Example finished********************");
  }

  private JavaRDD<DataSet> getDataSet(JavaRDD<String> rddPath) {
    JavaRDD<DataSet> rddImage = rddPath.map(new Function<String, DataSet>() {
      private boolean first = false;

      @Override
      public DataSet call(String hdfsPath) throws Exception {
        Configuration config = new Configuration();
        HdfsUtil hdfsUtil = new HdfsUtil(config);
        InputStream dis = hdfsUtil.open(hdfsPath);
        INDArray features = imageLoader.asRowVector(dis);
        String[] tokens = hdfsPath.split("\\/");
        String label = tokens[tokens.length - 2];
        INDArray labels = Nd4j.zeros(4);
        labels.putScalar(0, labelNames.get(label), 1.0);
        DataSet dataSet = new DataSet(features, labels);
        dataSet.setLabelNames(labelList);
        scaler.preProcess(dataSet);

        return dataSet;
      }
    });

    return rddImage;
  }

  private MultiLayerConfiguration getConfiguration() {
    double nonZeroBias = 1;
    double dropOut = 0.5;

    MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder().seed(seed).weightInit(WeightInit.DISTRIBUTION).dist(new NormalDistribution(0.0, 0.01)).activation(Activation.RELU)
        .updater(Updater.NESTEROVS).iterations(iterations).gradientNormalization(GradientNormalization.RenormalizeL2PerLayer).optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
        .learningRate(1e-3).biasLearningRate(1e-3 * 2).learningRateDecayPolicy(LearningRatePolicy.Step).lrPolicyDecayRate(0.1).lrPolicySteps(100000).regularization(true).l2(5 * 1e-4).momentum(0.9)
        .miniBatch(false).list().layer(0, convInit("cnn1", channels, 96, new int[] { 11, 11 }, new int[] { 4, 4 }, new int[] { 3, 3 }, 0))
        .layer(1, new LocalResponseNormalization.Builder().name("lrn1").build()).layer(2, maxPool("maxpool1", new int[] { 3, 3 }))
        .layer(3, conv5x5("cnn2", 256, new int[] { 1, 1 }, new int[] { 2, 2 }, nonZeroBias)).layer(4, new LocalResponseNormalization.Builder().name("lrn2").build())
        .layer(5, maxPool("maxpool2", new int[] { 3, 3 })).layer(6, conv3x3("cnn3", 384, 0)).layer(7, conv3x3("cnn4", 384, nonZeroBias)).layer(8, conv3x3("cnn5", 256, nonZeroBias))
        .layer(9, maxPool("maxpool3", new int[] { 3, 3 })).layer(10, fullyConnected("ffn1", 4096, nonZeroBias, dropOut, new GaussianDistribution(0, 0.005)))
        .layer(11, fullyConnected("ffn2", 4096, nonZeroBias, dropOut, new GaussianDistribution(0, 0.005)))
        .layer(12, new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD).name("output").nOut(numLabels).activation(Activation.SOFTMAX).build()).backprop(true).pretrain(false)
        .setInputType(InputType.convolutionalFlat(height, width, channels)).build();

    return conf;
  }

  private ConvolutionLayer convInit(String name, int in, int out, int[] kernel, int[] stride, int[] pad, double bias) {
    return new ConvolutionLayer.Builder(kernel, stride, pad).name(name).nIn(in).nOut(out).biasInit(bias).build();
  }

  private ConvolutionLayer conv3x3(String name, int out, double bias) {
    return new ConvolutionLayer.Builder(new int[] { 3, 3 }, new int[] { 1, 1 }, new int[] { 1, 1 }).name(name).nOut(out).biasInit(bias).build();
  }

  private ConvolutionLayer conv5x5(String name, int out, int[] stride, int[] pad, double bias) {
    return new ConvolutionLayer.Builder(new int[] { 5, 5 }, stride, pad).name(name).nOut(out).biasInit(bias).build();
  }

  private SubsamplingLayer maxPool(String name, int[] kernel) {
    return new SubsamplingLayer.Builder(kernel, new int[] { 2, 2 }).name(name).build();
  }

  private DenseLayer fullyConnected(String name, int out, double bias, double dropOut, Distribution dist) {
    return new DenseLayer.Builder().name(name).nOut(out).biasInit(bias).dropOut(dropOut).dist(dist).build();
  }

}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
package com.bj.imgreg;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Date;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.FileStatus;
import org.apache.hadoop.fs.FileSystem;
import org.apache.hadoop.fs.Path;

public class HdfsUtil {
  public final String HOST = "hdfs://fin1:9000";
  private FileSystem fs = null;

  public HdfsUtil(Configuration config) throws URISyntaxException, IOException {
    fs = FileSystem.get(new URI(HOST), config);
  }

  public FileStatus[] listStatus(String path, Configuration config) throws Exception {
    FileStatus[] fileStatuses = null;
    try {
      Path file = new Path(path);
      fileStatuses = fs.listStatus(file);
    } catch (Exception e) {
      throw e;
    } finally {
      // if (fs != null)
      // fs.close();
    }
    return fileStatuses;
  }

  public InputStream open(String path) throws Exception {
    InputStream dis = null;
    try {
      Path file = new Path(path);
      if (!fs.exists(file)) {
        return null;// throw new RuntimeException("no such file");
      }
      dis = fs.open(new Path(path));
    } catch (Exception e) {
      throw e;
    } finally {
      // if (fs != null)
      // fs.close();
    }
    return dis;
  }

  public OutputStream saveFile(String path) throws Exception {
    OutputStream ois = null;
    try {
      Path file = new Path(path);
      if (fs.exists(file)) {
        fs.rename(file, new Path(path.replace("model.zip", "/model/model" + new Date().getTime() + ".zip")));
      }
      ois = fs.create(file);
    } catch (Exception e) {
      e.printStackTrace();
      throw e;
    } finally {
      // if (fs != null)
      // fs.close();
    }
    return ois;
  }

  public void close() throws IOException {
    fs.close();
  }
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>img.reg</groupId>
	<artifactId>img-reg</artifactId>
	<version>1.0</version>
	<packaging>pom</packaging>

	<name>img-reg</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<nd4j.backend>nd4j-native-platform</nd4j.backend>
		<java.version>1.8</java.version>
		<nd4j.version>0.8.0</nd4j.version>
		<dl4j.version>0.8.0</dl4j.version>
		<datavec.version>0.8.0</datavec.version>
		<dl4j.spark.version>0.8.0_spark_2</dl4j.spark.version>
		<datavec.spark.version>0.8.0_spark_2</datavec.spark.version>
		<scala.binary.version>2.11</scala.binary.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-core_${scala.binary.version}</artifactId>
			<version>2.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>dl4j-spark_${scala.binary.version}</artifactId>
			<version>${dl4j.spark.version}</version>
		</dependency>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-native-platform</artifactId>
			<version>${nd4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-core</artifactId>
			<version>${dl4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-nn</artifactId>
			<version>${dl4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-ui_${scala.binary.version}</artifactId>
			<version>${dl4j.version}</version>
		</dependency>
		<dependency>
			<groupId>com.beust</groupId>
			<artifactId>jcommander</artifactId>
			<version>1.60</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.1</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<modules>
		<module>pian-img</module>
	</modules>

</project>

**Comment by AlexDBlack** [comment]
This looks correct (assuming the adress is correct and the UI instance is set up correctly there):
```
      StatsStorageRouter remoteUIRouter = new RemoteUIStatsStorageRouter("http://192.168.0.34:9000");
      sparkNetwork.setListeners(remoteUIRouter, Collections.singletonList(new StatsListener(null)));
```

Are you getting any errors/warnings from the remote UI router? It'll log if there are posting failures or connection issues, for example.

**Comment by SidneyLann** [comment]
I just don't know must use hdfs by call .exportDirectory("/spark/tmp"), no problem now.

**Comment by agibsonccc** [comment]
@SidneyLann thanks for clarifying!

**Comment by SidneyLann** [comment]
Thanks
