### ISSUE TITLE
GravesLSTM example CPU utilization

### ISSUE THREAD

**Issue by SergeyZYX** [deeplearning4j/deeplearning4j#3426]
Question on official dl4j example org.deeplearning4j.examples.recurrent.seqclassification.UCISequenceClassificationExample

It's using GravesLSTM RNN, trainset 450 records, testset 150.
Trainset dimensions 450 x 1 x 60.
Divided in mini batches 10 x 1 x 60.

After 40 epochs with 1 iteration, test dataset f1 score is 0,99 perfect!

This operation took dl4j 11 minutes on 2 cores CPU, considering size of dataset and time consumption I tried to find a way to speed up whole process. This example utilizes only 50% of CPU power. I asked for help and get recommendation to increase minibatch size to get more CPU utilization.

As this example dataset is very small we could set minibatch size to cover whole dataset.
So I set minibatch size = 450
The result - the example is broken.

TrainSet @ epoch 0: Accuracy = 0,22, F1 = 0,22
TestSet  @ epoch 0: Accuracy = 0,21, F1 = 0,25

TrainSet @ epoch 39: Accuracy = 0,22, F1 = 0,27
TestSet  @ epoch 39: Accuracy = 0,21, F1 = 0,25

It just don't want to learn any more. I guess is there some bug in implementation?
And if minibatch size cover all records at once can we exchange:
40 epochs * 1 iteration 
to
1 epoch * 40 iterations
is it equal in this case?

0.8-SNAPSHOT
Windows 10, Corei5 CPU (2 cores only)

**Comment by saudet** [comment]
50% CPU utilization is sort of by design. Try to increase the value of the OMP_NUM_THREADS environment variable, but it probably won't reduce the total execution time:
https://deeplearning4j.org/native#omp_num_threads
