### ISSUE TITLE
MultiGPU / ParallelWrapper throwing NPE with StatsListener attached to model

### ISSUE THREAD

**Issue by edobm** [deeplearning4j/deeplearning4j#3427]
#### Issue Description
Wraped model using ParallelWraper to utilize multiple GPUs with attached StatsListener.
ParallelWraper throws NPE.

#### Version Information

<dependencies>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>0.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-ui_2.11</artifactId>
            <version>0.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-cuda-8.0-platform</artifactId>
            <version>0.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.datavec</groupId>
            <artifactId>datavec-api</artifactId>
            <version>0.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-parallel-wrapper_2.11</artifactId>
            <version>0.8.0</version>
        </dependency>
</dependencies>

CODING:

        StatsStorage statsStorage = new InMemoryStatsStorage();
   
        network.init();
        network.setListeners(new ScoreIterationListener(listenerFreq));
      
        // Commenting out this lines solves the issue
       network.setListeners(new StatsListener(statsStorage));** 
        

       //  Just added these lines to test MultiGPU from 
       //  https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-cuda-specific-examples/src/main/java/org/deeplearning4j/examples/multigpu/MultiGpuLenetMnistExample.java

        // ParallelWrapper will take care of load balancing between GPUs.
        ParallelWrapper wrapper = new ParallelWrapper.Builder(network)
                // DataSets prefetching options. Set this value with respect to number of actual devices
                .prefetchBuffer(24)
                // set number of workers equal or higher then number of available devices. x1-x2 are good values to start with
                .workers(4)
                // rare averaging improves performance, but might reduce model accuracy
                .averagingFrequency(3)
                // if set to TRUE, on every averaging model score will be reported
                .reportScoreAfterAveraging(true)
                // optinal parameter, set to false ONLY if your system has support P2P memory access across PCIe (hint: AWS do not support P2P)
                .useLegacyAveraging(true)
                .build();
                
       // Now having subsequent calls to wrapper.fit() istead of network.fit()

**Comment by agibsonccc** [comment]
This should work fine out of the box.. look at our spark tips for the UI. It should be similar:
http://deeplearning4j.org/visualization
