### ISSUE TITLE
Inconsistent results with cudnn 5.1 and 6.0

### ISSUE THREAD

**Issue by gaava** [deeplearning4j/deeplearning4j#3431]
Hello,
I'm getting inconsistent results after each training with cudnn 5.1 and 6.0 without changing any parameters.
To reproduce this in AnimalClassification example i'm doing following steps:
1. Download dl4j examples and use it in IntelliJ
2. Follow these steps:
https://deeplearning4j.org/cudnn
to use cudnn. Attaching my pom file below:
[pom.zip](https://github.com/deeplearning4j/deeplearning4j/files/1016002/pom.zip)
3. For testing purposes i'm lowering epoch from 50 to 10 
4. Run training multiple times
5. Results below:

 Accuracy:        0,2143
 Precision:       0,2083
 Recall:          0,25
 F1 Score:        0,2273
 
 Accuracy:        0,1429
 Precision:       0,0667
 Recall:          0,1667
 F1 Score:        0,0952
 
 Accuracy:        0,3571
 Precision:       0,3952
 Recall:          0,3542
 F1 Score:        0,3736

---------------------------------------------------------
Please notice: I have the same issue with cudnn 6.0
Let me know if i can provide more information

* Deeplearning4j version 0.8.0 for cudnn 5.1 or 0.8.1-SNAPSHOT for cudnn 6.0
* Windows 10 64 bit
* CUDA 8.0
* CUDNN 5.1 or 6.0
* NVIDIA driver version 381.89
* Using Geforce 1070

**Comment by saudet** [comment]
cuDNN in general is not deterministic, but some parts of it are, for example as discussed here:
https://groups.google.com/forum/#!topic/torch7/bkVMKmmwG1A
It would require some investigation, so I believe this is a question of documentation...

**Comment by agibsonccc** [comment]
@crockpotveggies wasn't this related to some issues you were seeing with 5.1?

**Comment by crockpotveggies** [comment]
Yes we have an open issue with Nvidia right now and they're working on it
in their current sprint.
