### ISSUE TITLE
Dense layers are changing data shape without mask shape[potential bug?]

### ISSUE THREAD

**Issue by levil221** [deeplearning4j/deeplearning4j#3432]
#### Issue Description
Basically my last layer(output Layer) is telling me that my data had a wrong mask shape. When i'm trying to train my network with dense layers i got this problem, but issue is resolved when im commenting my danse layers and change output layer to rnn output layer, so i think problem is not in my data. neither less i don't know where problem lies and i'm stuck.

- what i wanted: run smoothly
- reality: exception thrown

#### Version Information
0.8.0, 0.8.1  - shanpshot
Win 10
cpu only

links:
my network configuration: https://gist.github.com/levil221/e8a1b22a21df2859e38428d9833558e7
stack trace at 0.8.1-snapshot : https://gist.github.com/levil221/aba19e93691140c32db12af3d05a8314
stack trace at 0.8.0 : https://gist.github.com/levil221/df01e303a65b2744076849b6615ffed9

**Comment by AlexDBlack** [comment]
> but issue is resolved ... change output layer to rnn output layer

So, use an RnnOutputLayer? If your labels are sequences, then that's what you should be using.
https://deeplearning4j.org/usingrnns#rnnoutputlayer

**Comment by levil221** [comment]
i may express myself badly, im having those errors when i have dense layers at the end, its resolved when im removing it and instead having fully connected layer i ending up just hwit cnn+rnn

**Comment by AlexDBlack** [comment]
The dense layers shouldn't make any difference - that is:
- I expect an error with dense layers and output layer (this is an incorrect configuration)
- I *don't* expect an error with dense layers and an RnnOutputLayer (this is correct)

**Comment by levil221** [comment]
I dont know what you mean by your post buti can't put RnnOutputLayer instead of OutputLayer. RnnOutputLayer accept only rank 3 array, and dense layers are outputting rank 2 array.

**Comment by AlexDBlack** [comment]
Closing this. Solution is to use an RnnOutputLayer + an appropriate FeedForwardToRnnPreProcessor before it.
