### ISSUE TITLE
LocalFileGraphSaver doesnt create path if not exist.

### ISSUE THREAD

**Issue by papperwing** [deeplearning4j/deeplearning4j#3437]
When epoch is trained in EarlyStoppingTrainer the library tries to save bestGraph.bin but if path doesn't exist application fails. 

If file.mkdirs is called somewhere inside it could save long training when folder is accidentally deleted from outside.

version of DL4J: 0.8.1_SNAPSHOT

**Comment by AlexDBlack** [comment]
Thanks. Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/3585
