### ISSUE TITLE
CnnSentenceDataSetIterator Performance on GPU

### ISSUE THREAD

**Issue by wmeddie** [deeplearning4j/deeplearning4j#3438]
#### Issue Description

CnnSentenceDataSetIterator, when used with a CUDA nd4j backend is significantly slower than when using the CPU.

On a CPU PerformanceListener shows on average the following number:

```
    INFO  o.d.o.listeners.PerformanceListener - ETL: 0 ms; iteration 6; iteration time: 2467 ms; samples/sec: 25.942; batches/sec: 0.405; score: 1.2638685717755782;
````

The same program when using the GPU via BACKEND_PRIORITY_GPU gets the following numbers:

```
    INFO  o.d.o.listeners.PerformanceListener - ETL: 2350 ms; iteration 6; iteration time: 7193 ms; samples/sec: 8.898; batches/sec: 0.139; score: 1.2638684525658597;
```

The CnnSentenceDataSetIterator is configured using the following code:

```
        WordVectors vectors = WordVectorSerializer.loadStaticModel(new File(vectorsPath));

        CnnSentenceDataSetIterator trainIter = new CnnSentenceDataSetIterator.Builder()
                .sentenceProvider(trainProvider)
                .maxSentenceLength(100)
                .tokenizerFactory(new JapaneseTokenizerFactory(true))
                .minibatchSize(64)
                .wordVectors(vectors)
                .build();
```

#### Version Information

* Deeplearning4j 0.8.1-SNAPSHOT
* CentOS 7 and Windows 10
* CUDA 8/Driver Version: 375.51

**Comment by raver119** [comment]
I wonder if that's still the case, or workspaces and disabled gc fix it?

**Comment by AlexDBlack** [comment]
If memory serves me, the issue was CG load due to the vocab size (millions of String objects).
Workspaces and GC tuning should help a lot with this - but we should benchmark it again.

**Comment by raver119** [comment]
I think so too, workspaces and disabled periodic gc should have solved it

**Comment by wmeddie** [comment]
I too think that was the fix.  Soon after this we were training on GPU within 1 second of Keras so I think we can close this.
