### ISSUE TITLE
Docs: Missing updater animations

### ISSUE THREAD

**Issue by marcel-93** [deeplearning4j/deeplearning4j#3440]
This paragraph should show animations of the updaters but they are missing.
https://deeplearning4j.org/building-neural-net-with-dl4j#animation-of-updaters

Think the animations should include something like this:
* https://cs231n.github.io/neural-networks-3/#baby
* http://1.bp.blogspot.com/-K_X-yud8nj8/VPmIBxwGlsI/AAAAAAAACC0/JS-h1fa09EQ/s1600/Saddle%2BPoint%2B-%2BImgur.gif
* http://sebastianruder.com/content/images/2016/09/saddle_point_evaluation_optimizers.gif
* http://sebastianruder.com/content/images/2016/09/contours_evaluation_optimizers.gif
* http://2.bp.blogspot.com/-q6l20Vs4P_w/VPmIC7sEhnI/AAAAAAAACC4/g3UOUX2r_yA/s1600/s25RsOr%2B-%2BImgur.gif

**Comment by tomthetrainer** [comment]
I put those images back up, there is a chance they will be cleared by some process, if that happens I will  find another way to host them.
