### ISSUE TITLE
Add an 'early termination' (Multi)DataSetIterator

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3442]
The idea: I have an iterator, with say 10k minibatches, but I want to do something every 1k minibatches, that doesn't fit the listener pattern well.

Basically, it'd do something like:
```
public boolean hasNext() {
    return underlying.hasNext() && minibatchCount < terminationPoint;
}
```
every other method would essentially pass through to the underlying iterator.

Priority: low ("nice to have")

**Comment by eraly** [comment]
Merged after review. Closing.
