### ISSUE TITLE
Early stop on meeting any one of the several epoch termination type conditions

### ISSUE THREAD

**Issue by bikashg** [deeplearning4j/deeplearning4j#3444]
#### Issue Description

I wanted an early stop : either when the desired number of epochs (eg: 200) had been met or the score at any epoch was less than the desired threshold (eg: 0.008). So I did this :  
 

EarlyStoppingConfiguration<ComputationGraph> esConf = new EarlyStoppingConfiguration.Builder<ComputationGraph>()
                .epochTerminationConditions(new MaxEpochsTerminationCondition(200),new BestScoreEpochTerminationCondition(0.008, true))
                .scoreCalculator(new DataSetLossCalculatorCG(validationDataSetIterator, true))
                .evaluateEveryNEpochs(1)
                .modelSaver(new LocalFileGraphSaver(outputBaseDir))
                .build();

but my training continues for 200 epoch even when the loss was already less than 0.008 (For example : it was already 0 well ahead of 200 epochs)

![1](https://cloud.githubusercontent.com/assets/17159812/26356853/c0408c9a-3fcd-11e7-9ccc-43f5854c3851.jpg)

#### Version Information

* Deeplearning4j version : 0.8.1-SNAPSHOT
* platform information (OS, etc) : Ubuntu 14.04, 64 bits
* CUDA version, if used : 7.5
* NVIDIA driver version, if in use : 367.48

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by AlexDBlack** [comment]
Closing this - (a) outdated, and (b) there's 2 different scores here.
The score the termination condition is evaluated on is provided by the DataSetLossCalculator; the score you show in the graph is the score on the minibatch. They are different things.
