### ISSUE TITLE
MiniBatchFileDataSetIterator forgets about masks of underlying DataSet.

### ISSUE THREAD

**Issue by mbkennel** [deeplearning4j/deeplearning4j#3445]
#### Issue Description

I wish to train a feedforward network with per-example weights (i.e. some examples should count more than others).  It seems as though this means I need a DataSet with a labelsMask array of size (N,1) with N being the number of examples, and the value being the non-negative scalar corresponding to the per example weight.  (The ergonomics of the name 'labelsMask' can also be questioned). 

During training I make minibatches from MiniBatchFileDataSetIterator(dataSet, batchSize). 

I expected the minibatches to appropriately slice up the masks, along with the features and outcomes. 

    public void testPerExampleMasking() throws IOException {
        int numExamples = 25;
        int numFeatures = 4;
        int batchSize = 5; 
        INDArray features = Nd4j.randn(new int[]{numExamples, numFeatures}, 123L);
        INDArray outcome = Nd4j.randn(new int[]{numExamples, 1}, 123L);
        INDArray perExampleWeights = Nd4j.rand(new int[]{numExamples, 1}, 123L); // confusingly called labelsMask
        
        DataSet dataSet = new DataSet(features, outcome, null, perExampleWeights); 
        
        MiniBatchFileDataSetIterator dsi = new MiniBatchFileDataSetIterator(dataSet, batchSize); 
        while (dsi.hasNext()) {
            DataSet dataSetMini = dsi.next();
            INDArray labelsMask = dataSetMini.getLabelsMaskArray();
            assert labelsMask != null; // ASSERTION FAILS on DL4J 0.8.0
        }
    }

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.8.0
* platform information (OS, etc): Scientific Linux 6.9 (think CentOS/RHEL)
* CUDA version, if used:  none
* NVIDIA driver version, if in use: none

**Comment by eraly** [comment]
A couple of things here - Masks are only supported for 3d datasets meant for use with RNNs with variable time steps. Supporting per example masking for other scenarios is filed as an enhancement currently. The MiniBatchFileDataSetIterator is meant for use with 2d datasets only (which don't have a concept of mask currently). The right behaviour here would be to throw an exception at a suitable place along this chain of logic.

**Comment by mbkennel** [comment]
OK, thanks.  That fact "Masks are only supported for 3d datasets meant for use with RNNs with variable time steps." is implicit knowledge that I never knew about.  Is it documented somewhere?  (As a new user, even after reading through examples significantly, many of the meanings and intents is not well documented.  I have had to hunt through various pieces of complex source code with more frequency than I prefer). 

Moreover, my **real** goal is per-example cost-weighting, i.e. some examples count more than others and this value can be provided by the user with the data. 

I would imagine that this should be an additional piece of data within a DataSet: a tuple of features, outcomes, and per-example costs, and everything dealing with DataSet should deal with it appropriately.

**Comment by eraly** [comment]
The closest we had was a community PR that went inactive
https://github.com/deeplearning4j/deeplearning4j/pull/2659

If you could file documentation issue to clarify some of the things you have brought up it would be great. We are always looking to improve on our docs and with the pace of dev work it can fall behind.

And it turns out recently we added support for per output masking ..so yeah docs need updating
https://github.com/deeplearning4j/deeplearning4j/pull/2659

**Comment by mbkennel** [comment]
In my understanding with a chat with Adam, #2659 was never merged as it turned out to be much more difficult to do right than originally believed.

**Comment by raver119** [comment]
@eraly is this issue still viable?

**Comment by eraly** [comment]
We should close this. This is tracked elsewhere as an enhancement.
https://github.com/deeplearning4j/deeplearning4j/issues/2616
