### ISSUE TITLE
Way to obtain label similarity from ParagraphVectors.nearestLabels

### ISSUE THREAD

**Issue by wayerr** [deeplearning4j/deeplearning4j#3447]
Now a `ParagraphVectors.nearestLabels(..)` - returning a collection of labels, but internally it have a `List<BasicModelUtils.WordSimilarity>` which contains pairs - label=>similarity. 

Also, i do not have any other way to obtain similarity label to text because `ParagraphVectors.similarityToLabel(java.lang.String, java.lang.String)` - deprecated.

**Comment by raver119** [comment]
Not sure i'm following first question.

But answer for second question is simple: use inferVector() method first, it'll give you vector for document unseen before.

**Comment by wayerr** [comment]
> it'll give you vector for document unseen before.

Ok, but how i can get similarity to "top10 labels" (for example) from this vector?

**Comment by raver119** [comment]
call for nearestLabels(), it accepts INDArray

**Comment by wayerr** [comment]
It return collection of labels, but i need list of label and similarity of this label.

**Comment by raver119** [comment]
but once you have label, you can get vector for it, so you can call for Transforms.cosineSim() in loop

**Comment by wayerr** [comment]
>but once you have label, you can get vector for it, so you can call for Transforms.cosineSim() in loop

That already done in 'nearestLabels'. What about simply expose it?
