### ISSUE TITLE
Layers with no params trigger NPE for L1/L2 calc

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#3449]
#### Issue Description

On ComputationGraph (and possibly MLN), `calcL1` and `calcL2` is called for each layer in the network. The issue is that for layers with zero parameters like ZeroPaddingLayer, if the base layer methods for calculating L1/L2 are not overridden an NPE will be triggered.

#### Version Information

Master

#### Contributing

Looks like some refactoring will be required if we don't want to override calcL1/L2. Some guidance on how to proceed will be helpful.

**Comment by AlexDBlack** [comment]
As noted in gitter: my thinking is that layers like ZeroPaddingLayer don't have any parameters in the first place, and consequently the ```calculateXByParam``` (and similar) methods should never be called in the first place.

**Comment by AlexDBlack** [comment]
Test added here for L1/L2 calculation on all no-param layers: https://github.com/deeplearning4j/deeplearning4j/pull/3585

I also checked the source on ZeroPaddingLayer, and it correctly overrides l1/l2 methods, returning 0.
