### ISSUE TITLE
I cant build the project... :( 

### ISSUE THREAD

**Issue by jariojose** [deeplearning4j/deeplearning4j#3459]
#### Issue Description

Profile "test-nd4j-native" is not activated.
Profile "test-nd4j-cuda-8.0" is not activated.

Reactor Summary:

DeepLearning4j .................................... FAILURE [4.626s]
deeplearning4j-nn ................................. SKIPPED
deeplearning4j-modelimport ........................ SKIPPED
deeplearning4j-ui-parent .......................... SKIPPED
deeplearning4j-ui-components ...................... SKIPPED
(...)

#### Version Information

Please indicate relevant versions, including, if relevant:

* 0.8.1
* Gnome-Ubuntu

**Comment by huitseeker** [comment]
You can either pass `-DskipTests=true` to not test, or, as the message indicates, specify a profile for tests : `-Ptest-nd4j-native` runs on CPU, `-Ptest-nd4j-cuda` works on CUDA. In any of these cases, note we have some failing tests on master at this precise moment.

**Comment by jariojose** [comment]
Thank you! :+1:
