### ISSUE TITLE
Word2Vec : nulls and UNK in wordsNearest()

### ISSUE THREAD

**Issue by amouhoub** [deeplearning4j/deeplearning4j#346]
Words Nearest return UNK and null at the top of the nearest words in word2vec.

The following example is for the word "day" from the example in `Word2VecRawTextExample.java`
```
o.d.w.Word2VecRawTextExample - Similar words to 'day' : [UNK, null, STOP, public, mr, hi, money, white, federal, former, member, may, government, $, official, old, doe, people, --, best, can]
```
I noticed the same thing in `GoogleNews-300 model`. words nearest are almost random as well
For the word "day", the nearest words are :

```
[Inc._Nasdaq_MWRK, Deepak_Varma, Matveyeva, macular_degeneration_AMD, Antoine_Girouard, Michelangelo_Leonardo_da, NEDO, Lindsay_Dares, By_HARRY_R., Czech_Airlines_��SA, Mortgage_Packagers]
```

It seems to me from the first example as if the `org.nd4j.linalg.factory.Nd4j.sortWithIndices()` is sorting things in the inverse order or that the calculated similarity values are given inverted values (negative maybe). Hence, the top similar words for day in the first example are UNK then null. But this is just my point of view

**Comment by agibsonccc** [comment]
Those are gone now. Thanks!
