### ISSUE TITLE
Invalid handling of Conv Layer in SubsetVertex

### ISSUE THREAD

**Issue by woru** [deeplearning4j/deeplearning4j#3469]
SubsetVertex doesn't work for CNN input type.

There's an error in 
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/graph/SubsetVertex.java line 104.

It should be
```java
return InputType.convolutional(conv.getWidth(), conv.getHeight(), from - to + 1);
```
but right now it's:

```java
 return InputType.convolutional(from - to + 1, conv.getWidth(), conv.getHeight());
```

**Comment by AlexDBlack** [comment]
Yes, you are (almost) correct:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/graph/SubsetVertex.java#L37
>In the case of convolutional (4d) activations, this is done along depth.

The relevant method signature:
> public static InputType convolutional(int height, int width, int depth) {

The corrected version should be:
```
return InputType.convolutional(conv.getHeight(), conv.getWidth(), from - to + 1);
```

Feel free to open a pull request, or I'll push that fix up later.

**Comment by AlexDBlack** [comment]
Was fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/3555
