### ISSUE TITLE
[DOC] ND4J vs Numpy

### ISSUE THREAD

**Issue by sethah** [deeplearning4j/deeplearning4j#3475]
#### Issue Description

The page [here](https://deeplearning4j.org/compare-dl4j-torch7-pylearn#jvm-considerations) says:
"Deeplearning4j’s underlying linear algebra computations, performed with ND4J, have been shown to run at least twice as fast as Numpy on very large matrix multiplies." It links to a page [here](http://nd4j.org/benchmarking) which is under construction.

I was actually hoping to find the results that show this, but as an aside this documentation should be updated IMO, choosing from:

1. Removing the claim until results are available
2. Filling in the benchmarking page for ND4J
3. Linking to some other document that includes results

I didn't see any issue on nd4j or here to track it.

#### Version Information

NA

**Comment by agibsonccc** [comment]
@sethah mind showing us the benchmark code you're using?
Would be great to compare.

**Comment by sethah** [comment]
Oh I don't have any benchmark code. Actually, I was mostly just curious what the claim was in reference to and if maybe that was available somewhere. It seems to reference something, but I couldn't find anything searching google.

**Comment by agibsonccc** [comment]
Ahh the original benchmark we had was old from someone who was working with it last summer. We can just flag it for now. Nd4j is definitely a ton faster by now (especially with all of our c++ internatls)

**Comment by sethah** [comment]
Sounds good, thanks for following up @agibsonccc!
