### ISSUE TITLE
Word2Vec Builder standard parameters

### ISSUE THREAD

**Issue by felipebravom** [deeplearning4j/deeplearning4j#3477]
#### Issue Description

Hi,
Where can I find the default values for most of the parameters of Word2Vec.Build (e.g., useAdaGrad, negativeSample) ?
Thanks.	

#### Version Information
0.8 

#### Contributing
I'm implementing a Weka wrapper for Word2Vec and knowing these values would be helpful.

**Comment by raver119** [comment]
I.e. here: https://github.com/deeplearning4j/deeplearning4j/blob/f79799709ee1a99ebde92dde47ae9c093f94d22d/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/loader/VectorsConfiguration.java

**Comment by felipebravom** [comment]
Thanks!
I still can't find default values for some parameters though (e.g,
allowParallelTokenization, workers)
Cheers.
Felipe

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/sequencevectors/SequenceVectors.java#L369
