### ISSUE TITLE
Add workspaces for pre-training

### ISSUE THREAD

**Issue by mattbushell** [deeplearning4j/deeplearning4j#3485]
#### Issue Description

Implement workspaces for pretraining.

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java : 1062

#### Version Information

Please indicate relevant versions, including, if relevant:

* 0.8.1-SNAPSHOT

**Comment by AlexDBlack** [comment]
We have workspaces for pretraining now (and also in 1.0.0-alpha... pretty sure it was in 0.9.1 too?)
https://github.com/deeplearning4j/deeplearning4j/blob/cd84e694c481af12eaa8d8c44b129f4b35b82534/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java#L326-L376
