### ISSUE TITLE
Conflict with dependency 'junit:junit'

### ISSUE THREAD

**Issue by maxgfr** [deeplearning4j/deeplearning4j#3486]
Hi everyone,

My aim is to use deeplearning4j for android to read the model that I created previously on my desktop.

To do that, I create an application on android. I started to work with deeplearning4j 0.7.2 until I had a problem. I saw that this problem was fix in 0.8..0 so I decided to update to the new version : 

`dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    wearApp project(':wear')
    compile 'com.google.android.gms:play-services-wearable:10.2.6'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'

    compile 'org.deeplearning4j:deeplearning4j-core:0.8.0'
    compile 'org.nd4j:nd4j-native:0.8.0'
    compile 'org.nd4j:nd4j-native:0.8.0:android-arm'
    compile 'org.nd4j:nd4j-native:0.8.0:android-x86'
}`

Unfortunetly, when I tried to do that in my gradle file I had this issue :

> Error:Conflict with dependency 'junit:junit' in project ':mobile'. Resolved versions for app (4.8.2) and test app (4.12) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

Thank you in advance to help me 😄

**Comment by saudet** [comment]
That's a problem with Android. It gives you the solution at the URL above, so please follow those instructions.

**Comment by mrezza91** [comment]
I have same probelem did you fix it?please tell it here

**Comment by rockbass2560** [comment]
I used the next script in the file build.gradle of app project

`android{
     configurations.all {
        resolutionStrategy.force "junit:junit:4.8.2"
    }
}`

The script enforces gradle to use a specific version of the library
