### ISSUE TITLE
SparkComputationGraph: add JavaRDD<MultiDataSet> evaluation methods

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3493]
SparkComputationGraph has plenty of evaluation methods, but only for ```JavaRDD<DataSet>```. We should add support for ```JavaRDD<MultiDataSet>``` also (and maybe ```RDD<(Multi)DataSet>``` too).

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/dl4j-spark/src/main/java/org/deeplearning4j/spark/impl/graph/SparkComputationGraph.java#L505-L641

**Comment by agibsonccc** [comment]
Didn't we add these?

**Comment by AlexDBlack** [comment]
Added here: https://github.com/deeplearning4j/deeplearning4j/pull/3621
Will be merged soon.
