### ISSUE TITLE
Add StatsStorage introspection/storage information

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3494]
The idea: I have a StatsStorage instance, with *some* stuff in it.
I can query it of course for session IDs etc; but it would be nice to be able to do a simple ```myStatsStorage.report()`` which would list:

- Session IDs
- Worker IDs and types for each session
- Number of records, record types, listener types etc.

Priority: low (nice to have)

**Comment by agibsonccc** [comment]
I actually need this for SKIL anyways.

**Comment by raver119** [comment]
Is this issue still viable?

**Comment by AlexDBlack** [comment]
I'd put it at quite low priority... let's re-open if/when we actually want to use this somewhere.
