### ISSUE TITLE
[question] Do you plan something similar like TensorFlow has for Visualization?

### ISSUE THREAD

**Issue by archenroot** [deeplearning4j/deeplearning4j#3497]
I definitely like current robustness of this library. But was also playing with other frameworks and especially TensorFlow has quite interesting GUI for discovering what is happening inside the network. 

There is quite impressive project called VLR Studio which supports Node based visual programming, maybe something to consider?

But in general this is just the question if you plan to invest into visualization in general.

Thanks again for this impressive stuff here.

**Comment by agibsonccc** [comment]
Did you see this? http://deeplearning4j.org/visualzation What more do you want specifically?

**Comment by huitseeker** [comment]
we also have specifically architecture & gradient visualization, see:
https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/misc/centerloss/CenterLossLenetMnistExample.java
for an example

**Comment by archenroot** [comment]
Thanks for comments, this is more general question about current capabilities and possible future way. 
There is lot of similarity from node based programming.

I had in my mind for example:
https://www.tensorflow.org/get_started/graph_viz
https://www.tensorflow.org/get_started/embedding_viz
http://www.sw-engineering-candies.com/blog-1/experimental-visualization-of-artificial-neural-network-with-webgl
or more artistic based approach:
https://www.cybercontrols.org/neuralnetworks

Pure Node based programming approach dummy example:
https://cdn1.epicgames.com/ue/item/BasicNeuralNetwork_Screenshot_02-1920x1080-59679d01250dfd621d361a29f876cbf2.png

**There is great VRL Studio project which could be possibly utilized:**
http://vrl-studio.mihosoft.eu/

I am not requesting anything concrete, but more monitoring and checking current visualization capabilities, future plans.

Thanks for your inputs.

**Comment by agibsonccc** [comment]
We have autodiff coming  as well. I could see us adding similar ideas later.

**Comment by archenroot** [comment]
Thanks.
