### ISSUE TITLE
SBT fails to import dependencies

### ISSUE THREAD

**Issue by vimalaguti** [deeplearning4j/deeplearning4j#3507]
#### Issue Description

While updating the build.sbt fille to snapshot version of dl4j, sbt might fails to import some of the dependencies, more precisely fails on : 
dl4j-spark
deeplearning4j-cuda-8.0
nd4j-cuda-8.0-platform

Error messages:
```
SBT project import
			[warn] 	[FAILED     ] org.bytedeco.javacpp-presets#cuda-platform;8.0-1.3!cuda-platform.jar(src):  (0ms)
			[warn] ==== local: tried
			[warn]   C:\Users\metreta\.ivy2\local\org.bytedeco.javacpp-presets\cuda-platform\8.0-1.3\srcs\cuda-platform-sources.jar
			[warn] ==== public: tried
			[warn]   https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/cuda-platform/8.0-1.3/cuda-platform-8.0-1.3-sources.jar
[FAILED     ] org.nd4j#nd4j-native-platform;0.8.0!nd4j-native-platform.jar(src):  (0ms)
```

Solution: remove .ivy2\ folder.
Looks like I cannot use at the same time version 0.8.0 and snapshot on different projects and sbt pointing at the same cache folder.
One solution is to give to each version a different ivy2 path : https://stackoverflow.com/questions/23845357/changing-ivy-cache-location-for-sbt-projects-in-intellij-idea

#### Version Information

deeplearning4j and nd4j from 0.8.0 to 0.8.1-SNAPSHOT
platform: windows 10 64bit
scala 2.11

**Comment by huitseeker** [comment]
hanks a lot for filing this issue! However, to better reproduce your problem, we're going to need a bit more information:

- a pointer to the `build.sbt` you're updating
- your edited `build.sbt`

You can submit it in your issue, or as a [gist](https://help.github.com/articles/about-gists/) if particularly long. Thanks in advance for helping us out!
