### ISSUE TITLE
It's very difficult to visualize or debug "manually" trained networks

### ISSUE THREAD

**Issue by Plazmaz** [deeplearning4j/deeplearning4j#3509]
#### Issue Description
When using a custom method, such as a genetic algorithm to set the weights of a Network, it is very difficult or impossible to visualize and debug the structure and training of that network. To even get the structure of a network to display, I am currently forcing an update using this (very hacky) method:
```
statsListener.setUpdateConfig(new DefaultStatsUpdateConfiguration.Builder()
                .collectHistogramsUpdates(false)
                .collectMeanUpdates(false)
                .collectStdevUpdates(false)
                .collectMeanMagnitudesUpdates(false)
                .build());
network.setListeners(statsListener)
statsListener.iterationDone(network, 0);
statsListener.getNewStatsReport()
```
This also throws errors whenever a layer of the network is selected. This, combined with a lack of any relevant documentation, makes it almost impossible to implement a genetic algorithm for training.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.8.0
* platform information (OS, etc): Windows 10 Pro Insider Preview, Build 16188.rs_prerelease.170430-1928

**Comment by agibsonccc** [comment]
I'm not really sure how to scope this...if you're still interested in this be ready to send us a pull request if you want help extending the UI or the like.
