### ISSUE TITLE
Validation for output layers

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#3512]
#### Issue Description
Right now in the latest version a null pointer is thrown if an output layer isn't present.
Instead we should catch this in the layer validation when backprop is true.
Please describe our issue, along with:
- expected behavior
Throw a better error message about output layers and the comp graph
- encountered behavior
NullPointerException that takes a second to track down.
Thanks to @bnsh 
#### Version Information
0.8.0
Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by AlexDBlack** [comment]
Fixed here, with tests: https://github.com/deeplearning4j/deeplearning4j/pull/3585
