### ISSUE TITLE
KerasInceptionV3Net.java  Unknown exception

### ISSUE THREAD

**Issue by MoriatyC** [deeplearning4j/deeplearning4j#3520]
#### Issue Description

I imported the dl4j-examples as a new maven project and I wanna ran the KerasInceptionV3Net.java.
But it had a Unknown exception.
```
2017-06-13 21:41:40 INFO  KerasInceptionV3Net:52 - Importing Inception model from data/inception-model.json
2017-06-13 21:41:40 INFO  KerasInceptionV3Net:53 - Importing Weights model from data/inception-model-weights.h5
Exception in thread "main" java.lang.RuntimeException: Unknown exception.
	at org.bytedeco.javacpp.hdf5$H5File.allocate(Native Method)
	at org.bytedeco.javacpp.hdf5$H5File.<init>(hdf5.java:12713)
	at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.<init>(Hdf5Archive.java:61)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel$ModelBuilder.weightsHdf5Filename(KerasModel.java:603)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:176)
	at edu.usc.irds.dl.dl4j.examples.KerasInceptionV3Net.<init>(KerasInceptionV3Net.java:55)
	at edu.usc.irds.dl.dl4j.examples.KerasInceptionV3Net.main(KerasInceptionV3Net.java:108)
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:
  #000: C:\autotest\HDF5110ReleaseRWDITAR\src\H5F.c line 579 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: C:\autotest\HDF5110ReleaseRWDITAR\src\H5Fint.c line 1208 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: C:\autotest\HDF5110ReleaseRWDITAR\src\H5Fsuper.c line 273 in H5F__super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file

Process finished with exit code 1
```

#### Version Information

* Deeplearning4j version: dl4j-import-example
* platform information :win7-64bit

**Comment by tomthetrainer** [comment]
Here is a workaround from our training classes that succeeds in importing inception. 
Here are the Keras saved weights. 

https://github.com/tomthetrainer/KerasWorkshop/releases

Here is the java that imports it and tests. 
https://github.com/tomthetrainer/KerasWorkshop/blob/master/training-labs/src/main/java/ai/skymind/training/solutions/KerasModelimportInceptionV3.java

**Comment by tomthetrainer** [comment]
FYI,

We only support Keras models exported in Keras 1.x, if you are using 2.x that may be an issue.

**Comment by MoriatyC** [comment]
I used this demo https://github.com/tomthetrainer/KerasWorkshop/blob/master/training-labs/src/main/java/ai/skymind/training/solutions/KerasModelimportInceptionV3.java on my Windows OS.It had some err and the log said ```Failed to write core dump. Minidumps are not enabled by default on client versions of Windows```

**Comment by saudet** [comment]
Potentially, @MoriatyC are you using the latest version of the modelimport module?
http://search.maven.org/#search%7Cga%7C1%7Cmodelimport

**Comment by MoriatyC** [comment]
@saudet I used the project above.https://github.com/tomthetrainer/KerasWorkshop/blob/master/training-labs/src/main/java/ai/skymind/training/solutions/KerasModelimportInceptionV3.java  and this https://github.com/USCDataScience/dl4j-kerasimport-examples/tree/master/dl4j-import-example

**Comment by saudet** [comment]
The later is using 0.8.1-SNAPSHOT, so that should be alright, but the former isn't:
https://github.com/tomthetrainer/KerasWorkshop/blob/master/training-labs/pom.xml#L102

**Comment by MoriatyC** [comment]
I modified the pom to `<dependency>
      <groupId>org.deeplearning4j</groupId>
      <artifactId>deeplearning4j-modelimport</artifactId>
      <version>0.8.0-2</version>
    </dependency>` and run the KerasModelImportInceptionV3.java and have this[gist](https://gist.github.com/MoriatyC/16ce3a1ce945dec5c902e337509776e6).

**Comment by agibsonccc** [comment]
Adding cuda to the mix isn't exactly my idea of a "simple" test case here. Try native and also make sure your version is keras 1 not 2. (I mentioned this on stackoverflow already. You can NOT ignore that)

**Comment by agibsonccc** [comment]
Great! Look at: https://github.com/deeplearning4j/dl4j-examples/tree/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/transferlearning/vgg16 Can you try to file an issue with some code we can look at for the gpu?

**Comment by maxpumperla** [comment]
@MoriatyC do I understand correctly that what you try to do works if you're not using cuda?  Following @agibsonccc 's suggestion, would you mind opening another ticket with a full example we can investigate?

**Comment by ejunprung** [comment]
FYI. I don't think this is a bug nor is it related to CPU vs GPU. I've recently solved this exact issue.

@MoriatyC If you're still seeing that error, try navigating to C:\Users\MoriatyC\.dl4j\trainedmodels. This is where the model should be stored. 

It's likely that your h5 file is corrupt or missing. Perhaps you don't have enough disk space to save the entire model so it was partially downloaded and became unusable. Try the below.

1. Delete the entire "trainedmodels" folder mentioned above.
2. Run import again to re-download the model.

If that still fails, download the entire model manually using the link provided in the stack trace and put it in the "trainedmodels" folder. That should fix it.
