### ISSUE TITLE
Automated versioning

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#3522]
Can we automatically inject ND4j/DL4j versions somewhere? It would be nice to add that information to Nd4jEnvironmentInformation for debugging purposes...

Plus automated check for versions equality between DL4j/ND4j. This way we can automatically detect users mixing different versions of artifacts.

**Comment by huitseeker** [comment]
This is closed by https://github.com/deeplearning4j/nd4j/pull/2016 and its sibling PRs.
