### ISSUE TITLE
Lstm Spark issue (Prefetch)

### ISSUE THREAD

**Issue by bpark738** [deeplearning4j/deeplearning4j#3523]
#### Issue Description

Code + Error: https://gist.github.com/bpark738/d5d8b8d77ac8cdcd04babee9d7cccc7a
Pom File: https://gist.github.com/bpark738/f36612461c7d0ed6d07a4cf97f995bdf
Data: https://github.com/SkymindIO/MultitaskPhysionetLab (run sh file)

#### Version Information

Using 0.8.1-SNAPSHOT

### Solution

Solved by changing from .workerPrefetchNumBatches(2) to .workerPrefetchNumBatches(0)

**Comment by raver119** [comment]
%#%@#!!!!

**Comment by raver119** [comment]
***hypothetically*** fixed, please check after snapshot is recompiled

**Comment by raver119** [comment]
Any news there?

**Comment by bpark738** [comment]
Yeah looks good. Thanks so much!
