### ISSUE TITLE
Spark dataframe input to the dl4j model

### ISSUE THREAD

**Issue by daksh-agarwal** [deeplearning4j/deeplearning4j#3529]
There should be a method through which we can give feature columns and target column from the spark dataframe to the dl4j model.

**Comment by dmmiller612** [comment]
https://github.com/deeplearning4j/deeplearning4j/tree/master/deeplearning4j-scaleout/spark/dl4j-spark-ml This should be what you are looking for. It isn't released, yet. Open to more ideas, if this doesn't fit exactly what you are looking for.

**Comment by oguzserbetci** [comment]
Hi thanks for that! SparkComputationGraph would be great.

**Comment by agibsonccc** [comment]
@dmmiller612 we'lll be doing a release within the next 24 hours. expect it soon thanks for the help!

**Comment by raver119** [comment]
Implemented.

**Comment by rickyhai11** [comment]
Could you please provided the link for this implemented part and examples ?
Thanks for your great efforts
