### ISSUE TITLE
Problem in importing keras model when use gpu 

### ISSUE THREAD

**Issue by MoriatyC** [deeplearning4j/deeplearning4j#3536]
#### Issue Description
When I used this [demo ](https://github.com/tomthetrainer/KerasWorkshop/blob/master/training-labs/src/main/java/ai/skymind/training/solutions/KerasModelimportInceptionV3.java),it will have this strange [problem](https://gist.github.com/MoriatyC/46ffd2de46c03e3439f3a4c1500f5fd1)

        

#### Version Information
* Deeplearning4j version: 0.8.0
* platform information WIN7-64bit
* CUDA version 8.0
* gtx960 4g

#### Contributing

When I changed pom.xml from 
`        <nd4j.backend>nd4j-native-platform</nd4j.backend>`
to `<nd4j.backend>nd4j-cuda-8.0-platform</nd4j.backend>`
It works well.Thanks for @agibsonccc . 's help.

**Comment by saudet** [comment]
Are you using the bug fixed 0.8.0-2 version of the modelimport module here?
https://github.com/tomthetrainer/KerasWorkshop/blob/master/training-labs/pom.xml#L102

**Comment by tomthetrainer** [comment]
@MoriatyC 

Are you able to make progress using inception? 

That version of the Labs was not well tested on Windows machines. 

Let us know your goals, so we can see if we can help you and also close this ticket. 

If you can get Inception imported once I would suggest you save it with ModelSerializer and then stay in DL4J for further training or inference. 

The Maven Configuration for those Labs was created in haste to allow success in Linux Virtual Machine for Labs, but was also known to be working on my Mac, that said, changes where made in haste so the Maven config might be a bit Dodgy particularly for windows. 

We also may have Inception in our model zoo, or I could save in DL4J for you or something similar to get you moving forward.

**Comment by MoriatyC** [comment]
@saudet yes, I used the 0.8.0-2.here is the pom.
```
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>ai.skymind.training</groupId>
    <artifactId>training-parent</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <groupId>ai.skymind.training</groupId>
  <artifactId>training-labs</artifactId>
  <version>1.0-SNAPSHOT</version>
  <name>training-labs</name>
  <url>http://maven.apache.org</url>

<!-- added -->

  <repositories>
    <repository>
      <id>snapshots-repo</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>

  <distributionManagement>
    <snapshotRepository>
      <id>sonatype-nexus-snapshots</id>
      <name>Sonatype Nexus snapshot repository</name>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </snapshotRepository>
    <repository>
      <id>nexus-releases</id>
      <name>Nexus Release Repository</name>
      <url>http://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
    </repository>
  </distributionManagement>

  <dependencyManagement>
    <dependencies>
 
      <dependency>
        <groupId>org.nd4j</groupId>
        <artifactId>nd4j-cuda-8.0-platform</artifactId>
        <version>0.8.0</version>
      </dependency>
    </dependencies>
  </dependencyManagement>





  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.nd4j</groupId>
      <artifactId>nd4j-native-platform</artifactId>
     <version>0.8.0</version>
    </dependency>

    <dependency>
      <groupId>org.deeplearning4j</groupId>
      <artifactId>deeplearning4j-core</artifactId>
      <version>0.8.0</version>
    </dependency>

    <dependency>
      <groupId>org.deeplearning4j</groupId>
      <artifactId>deeplearning4j-ui_2.10</artifactId>
      <version>0.8.0</version>
    </dependency>

    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>19.0</version>
    </dependency>

    <dependency>
      <groupId>org.deeplearning4j</groupId>
      <artifactId>deeplearning4j-modelimport</artifactId>
      <version>0.8.0-2</version>
    </dependency>

    <dependency>
      <groupId>com.sparkjava</groupId>
      <artifactId>spark-core</artifactId>
      <version>2.5.4</version>
    </dependency>


    <dependency>
      <groupId>com.typesafe</groupId>
      <artifactId>config</artifactId>
      <version>1.3.1</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>



  </dependencies>
</project>
```
@tomthetrainer Thanks for your help. I have finished my work. As I said, when I closed the nd4j.backend<nd4j-cuda-8.0-platform>, it works well. I just want to get features from specified layer with a good pre-trained model. I suggest you can provide us more pre-trained model like keras, for example inception, inception-no-top etc, so that we don't need to transform ourself.
