### ISSUE TITLE
SELU Activation Function Feature

### ISSUE THREAD

**Issue by dmmiller612** [deeplearning4j/deeplearning4j#3537]
Currently Twitter release a  paper that included a couple of cool things that would be nice to have in Deeplearning4j: https://arxiv.org/pdf/1706.02515.pdf. One would be the SELU activation function. There is also a new normalization scheme with it, and an "Alpha Dropout". I'd be willing to take a stab at this, if I get enough time.

**Comment by AlexDBlack** [comment]
You're too late - it's already done. :)
https://github.com/deeplearning4j/nd4j/pull/1879

Feel free to open a new (separate) issue for alpha dropout.
