### ISSUE TITLE
Evaluation + Output + CUDA: output differs within evaluation method

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3538]
The following unit test passes on native, but fails on CUDA. Using latest ND4J/libnd4j + Windows.

The cause: the network output from silentOutput during evaluation differs vs.:
(a) calling the silentOutput method using reflection
(b) calling the standard output method

https://gist.github.com/AlexDBlack/0fb7c3348d3a2594b76e1c2135a4999d

Difference for final assertion on CUDA backend:
![image](https://user-images.githubusercontent.com/2360237/27267984-dbcec526-54ef-11e7-8615-18d0f8bc369a.png)

(the remaining values - not shown in image above - are all equal)

**Comment by raver119** [comment]
O_o

**Comment by AlexDBlack** [comment]
Yeah, it's odd, I couldn't work out what's up after trying to isolate it (it's not workspaces, not an issue with the input, and doesn't happen on native...).

**Comment by raver119** [comment]
Aha.

Nd4j.getExecutioner().commit() after silentOutput()?

**Comment by raver119** [comment]
I guess this issue can be closed now?
