### ISSUE TITLE
Evaluation.java: flipped numbers in "Examples labeled as"

### ISSUE THREAD

**Issue by mmithril** [deeplearning4j/deeplearning4j#3547]
#### Issue Description

org.deeplearning4j.eval.Evaluation.stats() prints out: "Examples labeled as ... classified by model as ...". These numbers are flipped. It is obvious when executed with trivial inputs:

```NDArray realOutcomes = new NDArray(new double[][]{{1}, {1}});
NDArray guesses = new NDArray(new double[][]{{0}, {0}});
Evaluation evaluation = new Evaluation();
evaluation.eval(realOutcomes, guesses);
System.out.println(evaluation.stats()); 
```

Outputs:
`Examples labeled as 0 classified by model as 1: 2 times`
Instead of:
`Examples labeled as 1 classified by model as 0: 2 times`

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j 0.8.0
* Windows 7
* CUDA not used
* NVIDIA not used

**Comment by marcel-93** [comment]
#3410 Think this could be the same problem
