### ISSUE TITLE
Project idea: Provide support for OpenCL 1.2 devices

### ISSUE THREAD

**Issue by viper7882** [deeplearning4j/deeplearning4j#3553]
Hi @AlexDBlack ,

Hugh Perkins has created [Coriander](https://github.com/hughperkins/coriander-dnn) that could run NVIDIA® CUDA™ code on OpenCL 1.2 devices. You might want to take a look if that suits your need to connect your Deep Learning software to OpenCL 1.2 devices. Kindly attribute his name and his contribution in case if you plan to use his work.

**Comment by raver119** [comment]
> Both linux and Mac systems stand a reasonable chance of working ok.

To be honest, that doesn't sounds like being worth all the hassle.
Once we'll decide we go for OpenCL - we can just port libnd4j directly, since we're in charge of every single byte there. But general OpenCL problem is still right there - fragmentation & compatibility issues.

**Comment by raver119** [comment]
Don't get me wrong please, Coriander looks like a nice thing. But all sudden incompatibility issues will become our problem, we'll have to support something we don't have control over.

**Comment by raver119** [comment]
@viper7882 are there any perf & compatibility tests i can see?

**Comment by viper7882** [comment]
Hi @raver119 ,

I saw the tests are done in https://github.com/hughperkins/coriander-dnn/tree/master/test, is that what you are looking for?

**Comment by archenroot** [comment]
I am rather interested in this project, it is indirectly related by converting CUDA into portable C++ which can run on AMD as well:
https://github.com/ROCm-Developer-Tools/HIP

**Comment by agibsonccc** [comment]
Closing this..can't say we're interested and there's not really a compelling use case. Consider working on nd4j if you want this.
