### ISSUE TITLE
MultiLayerNetwork from deeplearning4j and XGBoostEstimator conflict

### ISSUE THREAD

**Issue by deil87** [deeplearning4j/deeplearning4j#3554]
For some reason I can't instantiate MultiLayerNetwork before running fitting process for XGBoostEstimator. I was trying to figure out who is responsible for error(DNN or XGB) but it seems that I can't do this without knowing libraries' implementations. So I'm going to create the same issue in XGBoost as well.

```
val net = new MultiLayerNetwork(new NeuralNetConfiguration.Builder()
      .seed(seed)
      .iterations(iterations)
      .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
      .learningRate(learningRate)
      .weightInit(WeightInit.XAVIER)
      .updater(Updater.SGD)
      .momentum(0.9)
      .list
      ..... //layers
       .build)
      .pretrain(false).backprop(true)
      .build)

val parametersMap: Map[String, Any] = Map(....)
val xGBoostEstimator = new XGBoostEstimator(parametersMap)
val model = xGBoostEstimator.fit(trainingFold)
val predictions = model.transform(validationFold)
```
This order of initializations will cause fatal error:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fff8fd9e818, pid=67952, tid=38147
#
# JRE version: Java(TM) SE Runtime Environment (8.0_65-b17) (build 1.8.0_65-b17)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.65-b01 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libc++abi.dylib+0x25818]  _ZNK10__cxxabiv117__class_type_info27has_unambiguous_public_baseEPNS_19__dynamic_cast_infoEPvi+0x0
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/deil/Development/Projects/kaggle_sberbank/hs_err_pid67952.log

```
Here is a full dump:
[hs_err_pid67952.txt](https://github.com/deeplearning4j/deeplearning4j/files/1090574/hs_err_pid67952.txt)

**Comment by deil87** [comment]
As I understand these two tools are using JNI for calling c++ under the hood and something has gone wrong there.

**Comment by raver119** [comment]
As i see this crash happens in XGB, not ND4j. Can i see log with crash happening in our code?

**Comment by raver119** [comment]
However, problem is probably with shared libraries that are loaded within same context.

**Comment by deil87** [comment]
Yes, I do understand this. But I think it's possible to do a wrong things with using shared libraries for both XGB or DL4J. If there is some state that cause this error we can't say for sure who is breaking rules/conventions of using shared resources. Correct me if I'm wrong.

**Comment by raver119** [comment]
There's no such a thing as "conventions of using shared resources". Every binary app out there uses resources it needs to run. It's also known as "DLL hell". You can even easily get it in Java will all existing build & deps management tools. Versions clash is the same thing as this one :)

So, can i see crash that happens in our code? If there's such log, i could get idea what exactly causes this issue.

**Comment by deil87** [comment]
Sorry for my maybe silly assumptions :) I'm a familiar with C as well ( but maybe not enough). But still can't understand how adding code from one library DL4J ( that uses particular DLL's) can affect another code from different library -XGBoost ( that uses different DLL's or maybe the same). 

Dump that I assigned is all I have, and of course you can close this issue.  But I think we can't just blame 'DLL hell'... people are responsible for all  hell actually. So you are suggesting that error could be in one particular DLL that is not properly handle case when it is using from both library simultaniously?

**Comment by agibsonccc** [comment]
I'm closing this. Get feedback from the xgboost folks. @raver119 isn't "hand waving" dll hell. He is merely stating that it can happen. ABI compatible code for c++ across multiple project is "dll hell". The stack trace isn't coming from us. Get some feedback from the xgboost folks and link this issue then come back.

**Comment by raver119** [comment]
That's all goes down to old shared library load mechanics.
Imagine app A uses openblas 2.9.10, and app B uses openblas 2.10.11. If both apps exist in the same process space, they will be loading shared libraries sequentially. So, first app launched will load everything. And once app B will try to load the openblas library - it'll fail, because it's already loaded. Just different version, not expected one. And that eventually will lead to problems. That's what's probably happening right now.

**Comment by raver119** [comment]
And yes, i'm just saying - i need to see crash logs coming out of dl4j, just because i'm familiar with codebase, and probably will be able to track issue down. But i'm not aware of XGBoost internals, and can't spend time learning source code there :(

**Comment by deil87** [comment]
@raver119 Thank you for your complete answers! Really appreciate your help! Of course you can't.... thanks anyway!

**Comment by raver119** [comment]
Just give us something related to dl4j/nd4j in logs, and we'll be glad to help.

**Comment by deil87** [comment]
I just thought that C is just another level of indirection and this level uses another resources for it's use - threads, memory...whatever(and it's true actually). And some dll can for example "eat" or block all resources that needed for another dll as well. And this will cause an error. ( And let's imagine DL4J is author of this first dll).

I am waiting for response from XGBoost folks

**Comment by raver119** [comment]
Nope, it's all tied to single process space, created by you, once you've launched JVM. All threads, native libraries etc - are all tied to original process tree.

**Comment by deil87** [comment]
Got it :)
