### ISSUE TITLE
Missing transfer learning API for MultiLayerNetwork

### ISSUE THREAD

**Issue by papperwing** [deeplearning4j/deeplearning4j#3560]
#### Issue Description

Method for transfer learning methods are existing only for ComputationGraph and not for MultiLayerNetwork. In Zoo there are models which are defined as MultiLayerNetwork and without this API they are not much usable.

#### Version Information
0.8.1-SNAPSHOT

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/transferlearning/TransferLearning.java#L62

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/test/java/org/deeplearning4j/nn/transferlearning/TransferLearningMLNTest.java
