### ISSUE TITLE
License problem: org.json json no longer consistent with ASL 2.0 -- "Good, not Evil" clause

### ISSUE THREAD

**Issue by tballison** [deeplearning4j/deeplearning4j#3561]
Apache Tika now uses dl4j.  Thank you!  

While fixing https://issues.apache.org/jira/browse/TIKA-1804, we noticed that dl4j uses org.json's json library, which has been determined to be not consistent with the Apache Software License 2.0 because it limits use: "The Software shall be used for Good, not Evil.".  See ASF's determination [on TC-50](https://issues.apache.org/jira/browse/TC-50) and [here](https://lists.apache.org/thread.html/9627a9278d263378a2045d4bffccb6e83b9f01bb783c6dd6fa325faf@%3Clegal-discuss.apache.org%3E)

You _should_ be able to swap in Ted Dunning's clean-room ASL friendly version with little to no change in code (your mileage will vary).

`<dependency>
  <groupId>com.tdunning</groupId>
  <artifactId>json</artifactId>
  <version>1.8</version>
</dependency>`

**Comment by agibsonccc** [comment]
I thought you were just a twitter bot. Great to see you! Done. Thanks for using dl4j.

**Comment by tballison** [comment]
Do I really tweet that much?  Now everyone can do evil with dl4j!  Bwahaahaha.  Ugh.
But seriously, thank you for all of your work on dl4j and for this small mod.
