### ISSUE TITLE
Metal 2 support for GPU acceleration

### ISSUE THREAD

**Issue by virl** [deeplearning4j/deeplearning4j#3563]
In upcoming macOS High Sierra, Apple will introduce Metal 2 API, which allow even laptop users utilize high-end video cards in eGPU enclosures. Also Apple working on modular Mac Pro, which will have standard PCI-E expansion slots for video cards (and iMac Pro available in December will have top-notch GPU too).

Considering all this, macOS GPU support in for Metal 2 compute API will be welcomed by machine learning developers that use Macs as development environment.

**Comment by archenroot** [comment]
@virl is there any benefit over CUDA or OpenCL, to me this is another vendorlock technology by apple, but I agree this is probably just beginning of not only compute, but VR related stuff by Apple. You will get probably soon support of TensorRT, so what will be the befefit of this stuff, I am not sure.

**Comment by virl** [comment]
@archenroot Basically Apple settled on The GPU/CNN API for their platform and it will be Metal 2 — it is vendor lock in the same measure as CUDA is vendor lock on NVidia.
It means that within a year almost all relatively modern Macs (including upcoming Mac Pro) will be good machine learning workstations.

So benefit for your project of Metal 2 support would be large increase of potential user base.

**Comment by agibsonccc** [comment]
We'll need to be careful here on what's considered a "user base". At our core we mainly target linux and windows enterprise environments. Mac is galaxies away from that. We have support for pis and ios after some community pull requests  - but overall it's hard for me to consider macs even remotely  an "ML workstation".

**Comment by raver119** [comment]
Guys, let Metal 2/High Sierra to be released first :)

**Comment by archenroot** [comment]
@virl you are right, I meant it here in the context, that CUDA is supported on multiple platforms windows, linux, max osx.

But this Metal 2 stuff is only bound to Apple, this is just my personal statement, but no interest in something like this.

**Comment by agibsonccc** [comment]
Can't really say we're worried about this. Re raise this later on when this comes out. When you do let's have that discussion on nd4j not dl4j (dl4j barely knows about hardware)
