### ISSUE TITLE
ComputationGraphConfiguration.GraphBuilder.setOutputs() add outputs instead of setting them

### ISSUE THREAD

**Issue by papperwing** [deeplearning4j/deeplearning4j#3569]
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/ComputationGraphConfiguration.java#L675

Graph builder is in setter only adding other values, which can lead to for user unexpected behaviour.

#### Solution:
rename method to addOutputs and creating one which will repace outputs.

**Comment by papperwing** [comment]
If you suggest some way, I could try to prepare patch for this.

**Comment by AlexDBlack** [comment]
Fixed here; will merge soon: https://github.com/deeplearning4j/deeplearning4j/pull/3570
