### ISSUE TITLE
ResNet50 in EarlyStopping is using huge amount of memory.

### ISSUE THREAD

**Issue by papperwing** [deeplearning4j/deeplearning4j#3571]
#### Issue Description
After loading model from Zoo and presaving data both is passed to early stopping which fails on lack of memory end eat ups 15G memory in seconds. (https://gist.github.com/papperwing/5e366f08d5966bcaf8c1f7a74fda40d0)

Memory parameters were -Xmx8G and -Dorg.bytedeco.javacpp.maxbytes=15737418240 (15G)
Batch size is set to 32 images and minibatch saved from presave has 18M.

Model loading: https://github.com/papperwing/image-net/blob/alexnet/modules/image-net-model-creator/src/main/java/cz/muni/fi/imageNet/model/creator/ModelBuilderImpl.java#L145 

RecordReader: https://github.com/papperwing/image-net/blob/alexnet/modules/image-net-core/src/main/java/cz/muni/fi/imageNet/core/manager/ImageNetRecordReader.java

Wrapper around presave and earlyStopping: https://github.com/papperwing/image-net/blob/alexnet/modules/image-net-core/src/main/java/cz/muni/fi/imageNet/core/manager/ImageNetRunner.java#L85

Presave: https://github.com/papperwing/image-net/blob/alexnet/modules/image-net-core/src/main/java/cz/muni/fi/imageNet/core/manager/ImageNetRunner.java#L154

EarlyStopping: https://github.com/papperwing/image-net/blob/alexnet/modules/image-net-core/src/main/java/cz/muni/fi/imageNet/core/manager/ImageNetRunner.java#L233

#### Version Information

Server: Debian 86G memory without GPU
DL4J: 0.8.1-SNAPSHOT

**Comment by papperwing** [comment]
Here is method for generating model based on resnet: https://github.com/papperwing/image-net/blob/alexnet/modules/image-net-api/src/main/java/cz/muni/fi/imageNet/api/ImageNetAPI.java#L51

**Comment by raver119** [comment]
You've allowed your JVM to take 23GB of RAM in total. It takes 15GB. What you complain about then?

What happens if you set lower limits?

**Comment by papperwing** [comment]
Problem is that it fails during learning that its not able to allocate more memory.

**Comment by raver119** [comment]
What happens if you enable workspaces?

**Comment by papperwing** [comment]
Maybe it is bug, because ResNet50() takes workspaceMode but is nothing doing with it. 
After adding this setting into configuration memory consumption is still bigger than selected limit.

**Comment by raver119** [comment]
Aha.
Is issue reproducible if you run with presaved datasets?

**Comment by papperwing** [comment]
Yes it is. I created test which takes presaved data And it also failed. (https://github.com/papperwing/image-net/blob/alexnet/modules/image-net-model-creator/src/test/java/cz/muni/fi/imageNet/ResnetMemoryConsumptionTest.java)

**Comment by raver119** [comment]
I've cloned repo, and got data copy. With default Xmx value (1/4 of system ram) and no jcpp maxbytes set - issue isn't reproducible for me. It works, however it's quite heavy thing.

**Comment by crockpotveggies** [comment]
Considering the age of this issue, and introduction of workspaces, going to assume this is solved. Closing.
