### ISSUE TITLE
A place for useful gists in documentation.

### ISSUE THREAD

**Issue by tlaukkan** [deeplearning4j/deeplearning4j#3577]
Could there be a community modifiable location for useful gists?

**Comment by tomthetrainer** [comment]
we use gh-pages to deliver content, let me see if we can do this securely

**Comment by tomthetrainer** [comment]
Actually @tlaukkan do you have some that you would like to suggest? Perhaps we can seed the page with a few and then ask them to make suggestions through an issue

**Comment by nkwoh01** [comment]
This looks resolved
