### ISSUE TITLE
[question] TensorRT 2.0 support

### ISSUE THREAD

**Issue by archenroot** [deeplearning4j/deeplearning4j#3587]
Hi guys,

this is just to check if you plan to integrate support of TensorRT 2?

Thanks for info.

**Comment by agibsonccc** [comment]
Is it finally out of beta yet? Last time we looked at it the docs weren't there. We were hoping to integrate it with kafka or something along those lines though.

**Comment by archenroot** [comment]
@agibsonccc  Actually there is out 2.1:
https://docs.nvidia.com/deeplearning/sdk/tensorrt-release-notes/rel_2.1.html
