### ISSUE TITLE
Upgrade to openNLP 1.8 version

### ISSUE THREAD

**Issue by lingvisa** [deeplearning4j/deeplearning4j#3592]
#### Issue Description

The current openNLP is 1.8 version on Apache and the deeplearning4j is using 1.5. I tested and found some errors that should really be fixed and the openNLP author says they should have been fixed. The 1.5 was using old models trained. 
For example, "I love costco!", where "costco!" is tokenized as one token, which is very bad.
#### Version Information

It would be really great if deeplearning4j can upgrade to use the OpenNLP 1.8 version, which is current. Thank you.

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by smarthi** [comment]
there's soon gonna be a OpenNLP 1.8.1 release early next week, i would hold
off until then. Where in dl4j are they using OpenNLP anyways ?

**Comment by lingvisa** [comment]
Deeplearning4j is using it for text processing.

**Comment by smarthi** [comment]
ok, i would hold off until the OpenNLP 1.8.1 release happens, subsequently there will be new models that will be published.

**Comment by lingvisa** [comment]
Thank you. Then will there be a new release of DeepLearning4j in maven?

**Comment by smarthi** [comment]
It would be helpful to both Dl4J and OpenNLP project teams if u could
explain ur use case and what you are trying to accomplish so that we could
better help you  - before we get into the next maven release of dl4j or
opennlp - what is it you are trying to accomplish first?

**Comment by lingvisa** [comment]
I use want to do text processing in the deeplearnig4j platform, so openNLP is the basic component and deeplearning4j will consume the output of openNLP. There are some apperant errors in the 1.5 version in tokenization and POS tagging, and at least some issues have been fixed in later versions. Anyway, the 1.5 version was quite old.

**Comment by agibsonccc** [comment]
So it looks like cleartk hasn't been updated in a few years..not sure what to tell you here. I'd just suggest not using it. We can always create a new set of tools in the uima module. Very few folks were using it as it was.
