### ISSUE TITLE
Cannot deploy KNN models for large NDArrays

### ISSUE THREAD

**Issue by turambar** [deeplearning4j/deeplearning4j#3595]
#### Issue Description

KNN server appears to be hardwired to load the "neighbor" points matrix from disk as a Base64 encoded string (See [this line](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nearestneighbor-server/src/main/java/org/deeplearning4j/nearestneighbor/server/NearestNeighborsServer.java#L67)). Unfortunately, there appears to be a limit on the size of NDArrays that ND4J can store using Base64 (see this ND4J issue: https://github.com/deeplearning4j/nd4j/issues/1897).

Already filed as a ND4J issue, but I'm raising this here as well to ask whether there are alternative storage formats for NDArrays that we should consider? Feel free to shout "No!" especially if the Base64 bug is an easy fix.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Build DL4J, ND4J from source

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/3599
