### ISSUE TITLE
Tokenizerfactory and iterators are not persisted when saving/loading paragraphVectors

### ISSUE THREAD

**Issue by Hetterick** [deeplearning4j/deeplearning4j#3598]
#### Issue Description

I save my (labelled) PV with writeParagraphVectors and then read it with readParagraphVectors.
When doing nearestLabels I get a java.lang.NullPointerExcepetion
It enters into the function and then at List<String> tokens = tokenizerFactory.create(rawText).getTokens() it fails : indeed, tokenizerFactory (and iterators) are not persisted :/

**Comment by agibsonccc** [comment]
These shouldn't need to be persistable. You can create those yourself.
