### ISSUE TITLE
EarlyStoppingTraining running less epochs with training data

### ISSUE THREAD

**Issue by nsivaramakrishnan** [deeplearning4j/deeplearning4j#3605]
#### Issue Description
Am trying early stopper code for Cifar dataset. In score calculator, DataSetLossCalculator is used and for that Cifar test data (10k images) is passed and while creating EarlyStoppingTrainer, Cifar train data (50k images) is passed. With batch size and epochs set to 50 and 5000, the number of iterations that it runs is approximately around 200 instead of 1000 (50000/50). Also, while creating the model, the number of iterations is set to 1.

#### Version Information

* Deeplearning4j version - 0.8
* platform information (OS, etc)  - Linux fmc-gpu2 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* CUDA version - 8.0.44
* NVIDIA driver version - 367.48

#### Sample code

		// Load training data
		CifarDataSetIterator cifarTrainDataset = new CifarDataSetIterator(50, 50000, true);

		// Load test data
		// CifarDataSetIterator cifarTestDataset = new CifarDataSetIterator50, 10000, false);

		// Create early stopping configuration..
		EarlyStoppingModelSaver saver = new LocalFileModelSaver("/tmp/");
		EarlyStoppingConfiguration esConf = new EarlyStoppingConfiguration.Builder()
			.epochTerminationConditions(new MaxEpochsTerminationCondition(5000))
			.evaluateEveryNEpochs(1)
			.iterationTerminationConditions(new MaxTimeIterationTerminationCondition(1440, TimeUnit.MINUTES))
			.scoreCalculator(new DataSetLossCalculator(cifarTestDataset, true))
			.modelSaver(saver)
			.build();

		EarlyStoppingTrainer trainer = new EarlyStoppingTrainer(esConf, network, cifarTrainDataset);

**Comment by AlexDBlack** [comment]
This looks like a bad design in CifarDataSetIterator. I'll close this issue in favor of the underlying issues:
https://github.com/deeplearning4j/DataVec/issues/343
https://github.com/deeplearning4j/deeplearning4j/issues/3607

Once those are solved + merged (and new snapshots have had time to build/deploy), you can get the fix by switching to snapshots using the information here: https://github.com/deeplearning4j/deeplearning4j/issues/3227
