### ISSUE TITLE
Reading CSV File issue

### ISSUE THREAD

**Issue by gjossep** [deeplearning4j/deeplearning4j#3610]
#### Issue Description

Trying to read csv files with the 0.8.1-SNAPSHOT is throwing up errors:

The error is: https://gist.github.com/gjossep/bc0d28f47f0ebe53efa030d8fada1c82

The full stack: https://gist.github.com/gjossep/65b798f9d369699335ebd9ffc7435814

The full source code: https://gist.github.com/gjossep/1043b011acec86d5450b3c07b04a7294

The pom.xml: https://gist.github.com/gjossep/a4cda09e3973f04ef8c87283a16a8425

Each data line is a flat array of 32*400 = 12800 samples + 1 label at the end of each line.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.8.1-SNAPSHOT
* ND4J version: 0.8.1-SNAPSHOT with Cuda
* platform information (OS, etc): Windows 10
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

I would really like for this to work. Im not sure whats going on. I ran a test on the CSV files afterwards and they seem fine.

Thanks for your help.

**Comment by AlexDBlack** [comment]
Looks like an input issue:

Here's a segment of output.csv, which clearly has an invalid line:
![image](https://user-images.githubusercontent.com/2360237/27862945-2da1a192-61cb-11e7-9518-455c22f2e2fc.png)

I also noticed a blank line at the end of each of the CSVs, which *might* cause a similar issue.

I've opened an issue to improve the error messages for this condition - see https://github.com/deeplearning4j/deeplearning4j/issues/3626
