### ISSUE TITLE
Spark: Suppress CG/MLN init/workspace logs when initializing nets in spark workers

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3622]
Here's the log output for a small Spark evaluation unit test... this seems a *little* excessive: :)

https://gist.github.com/AlexDBlack/e4fdc64271e7c4413abc16e17ce21f59

**Comment by raver119** [comment]
Ugh... ye, it was supposed to be called once... But you've got multiple independent threads...

**Comment by raver119** [comment]
Related issue: https://github.com/deeplearning4j/rl4j/issues/45

**Comment by AlexDBlack** [comment]
We might want to look at a general 'suppress warnings when for spark or parallel wrapper' type mode here (but we *do* probably want to log warnings once, for one model)...
Other warnings that can be logged multiple times:
- Frozen layer warnings
- General configuration warnings

**Comment by raver119** [comment]
Implemented/Fixed
