### ISSUE TITLE
Error with maven lifecycle mapping under eclipse oxygen, m2e

### ISSUE THREAD

**Issue by Hottemax** [deeplearning4j/deeplearning4j#3625]
#### Issue Description

Eclipse m2e fails with

> java.lang.IllegalArgumentException: Missing parameter for pluginExecutionFilter. groupId, artifactId, versionRange and goals must be specificed, but found: groupId = 'com.lewisd'
> artifactId = 'lint-maven-plugin'
> versionRange = '[0.0.11,)'
> goals = '[]'
> at org.eclipse.m2e.core.internal.lifecyclemapping.model.PluginExecutionFilter.checkAllFieldsSet(PluginExecutionFilter.java:320)

#### Version Information

- master head  Revision: 158a8e446cec556111bef7140d990979ec3a2ac5 Date: 03.07.2017 19:17:23
- eclipse oxygen Release (4.7.0)
-  m2e  (1.8.0.20170516-2043)

**Comment by LuckyIlam** [comment]
Any idea to correct this problem ?

**Comment by HelloXT** [comment]
same issue

**Comment by huitseeker** [comment]
https://github.com/deeplearning4j/deeplearning4j/commit/9ab4e3f8c481ff6e475252b3505beb142fcbfda5#commitcomment-23125460

**Comment by Hottemax** [comment]
Hi, I accidentally created this issue in the wrong project; the reported issue pertains to the master branch of the [dl4j-examples](https://github.com/deeplearning4j/dl4j-examples) repository.

Very sorry to have caused this confusion, can this be moved? Otherwise feel free to close it.
Thank you.

**Comment by bingyu00** [comment]
i have the same problem

**Comment by agibsonccc** [comment]
@romeokienzler do you have any insights on this?

**Comment by Jiraboas** [comment]
I have the same problem. Please provide a solution for this. Thanks.

**Comment by romeokienzler** [comment]
Hi, what's the status on this issue? I've got a working solutions how to use eclipse and maven here:

Just follow the setup instructions and let me know if you are getting the same issue
https://www.ibm.com/developerworks/analytics/library/iot-deep-learning-anomaly-detection-3/index.html?ca=drs-

**Comment by Hottemax** [comment]
For me, the problem is resolved  (on the dl4j-examples master branch).

**Comment by romeokienzler** [comment]
perfect!

@huitseeker please consider closing
