### ISSUE TITLE
Error loading pre-trained CIFAR-10 model

### ISSUE THREAD

**Issue by jesuino** [deeplearning4j/deeplearning4j#3628]
#### Issue Description

Trying to load this pre-trained model which URL I took from deeplearnin4j-zoo and I am having a NPE. 

Model URL: http://blob.deeplearning4j.org/models/vgg16_dl4j_cifar10_inference.v1.zip

The code:
~~~
import java.io.File;
import java.net.URL;
import org.datavec.image.loader.NativeImageLoader;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.deeplearning4j.util.ModelSerializer;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.dataset.api.preprocessor.ImagePreProcessingScaler;

public class VGG16 {

	public static void main(String[] args) throws Exception {
		URL imgUrl = new URL("https://www.cs.toronto.edu/~kriz/cifar-10-sample/airplane1.png");
		File file = new File("vgg16_dl4j_cifar10_inference.v1.zip");
		MultiLayerNetwork model = ModelSerializer.restoreMultiLayerNetwork(file);
	        //the NPE is when loading the model, so disregard the other part of the code
	}
}
~~~

What I have is a NPE when it tries to read the configuration:

~~~
Exception in thread "main" java.lang.NullPointerException
	at org.deeplearning4j.nn.conf.MultiLayerConfiguration.fromJson(MultiLayerConfiguration.java:137)
	at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:239)
	at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:138)
	at org.fxapps.deeplearning.VGG16.main(VGG16.java:18)
~~~

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
0.8.0

* platform information (OS, etc)

RHEL 7

**Comment by tomthetrainer** [comment]
I wonder if @crockpotveggies can advise here?

**Comment by tomthetrainer** [comment]
@jesuino 
The modelzoo feature is part of 0.8.1 or 0.9.0 

See the docs here, 
https://deeplearning4j.org/model-zoo

Can you try your code with the snapshot of 0.8.1 ? 

This page should have enough information to assist in enabling and using snapshots
https://deeplearning4j.org/linux.html

If not comment in this thread and I can assist.

**Comment by jesuino** [comment]
Hello,
Thank you. I wanted to confirm if I was not doing anything wrong. I will use a 8.x or 9.x GA release once it is available, I won't be using SNAPSHOT for now.

I am closing this.

**Comment by jesuino** [comment]
My error was that vgg16_dl4j_cifar10_inference.v1.zip is a ComputationGraph and not a MultiLayerNetwork! It might be useful for others.
