### ISSUE TITLE
ClassNotFoundException WordVectorSerializer

### ISSUE THREAD

**Issue by GrayHulk** [deeplearning4j/deeplearning4j#3637]
#### Issue Description

Please describe our issue, along with:
- Sorry , I don't well English
   I excute source -> vec = (Word2Vec) WordVectorSerializer.loadGoogleModel(gModel, true);
  Caused by: java.lang.ClassNotFoundException: org.deeplearning4j.models.embeddings.loader.WordVectorSerializer

maven lib normal
compile normal 
why  this problem? help please 

I'm study English

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j -nlp- 0.4-rc3.9
* windos10

**Comment by raver119** [comment]
Show your pom.xml

**Comment by GrayHulk** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>DNN</groupId>
  <artifactId>DNN</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <resources>
      <resource>
        <directory>src</directory>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.3</version>
        <configuration>
          <source>1.6</source>
          <target>1.6</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <properties>
        <nd4j.backend>nd4j-native</nd4j.backend>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <shadedClassifier>bin</shadedClassifier>
        <java.version>1.7</java.version>
        <nd4j.version>0.4-rc3.9</nd4j.version>
        <dl4j.version>0.4-rc3.9</dl4j.version>
        <canova.version>0.0.0.16</canova.version>
        <arbiter.version>0.0.0.7</arbiter.version>
        <guava.version>19.0</guava.version>
        <jfreechart.version>1.0.13</jfreechart.version>
        <maven-shade-plugin.version>2.4.3</maven-shade-plugin.version>
        <exec-maven-plugin.version>1.4.0</exec-maven-plugin.version>
        <jackson.version>2.8.4</jackson.version>
  </properties>
  <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>nd4j-native</artifactId>
                <version>${nd4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>nd4j-cuda-7.5</artifactId>
                <version>${nd4j.version}</version>
            </dependency>
          
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-nlp</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-ui</artifactId>
            <version>${dl4j.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>${guava.version}</version>
        </dependency>
 
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>${nd4j.backend}</artifactId>
        </dependency>

        <dependency>
            <artifactId>canova-nd4j-image</artifactId>
            <groupId>org.nd4j</groupId>
            <version>${canova.version}</version>
        </dependency>
        <dependency>
            <artifactId>canova-nd4j-codec</artifactId>
            <groupId>org.nd4j</groupId>
            <version>${canova.version}</version>
        </dependency>

        <dependency>
            <groupId>jfree</groupId>
            <artifactId>jfreechart</artifactId>
            <version>${jfreechart.version}</version>
        </dependency>

        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>arbiter-deeplearning4j</artifactId>
            <version>${arbiter.version}</version>
        </dependency>
        <dependency>
		    <groupId>com.fasterxml.jackson.core</groupId>
		    <artifactId>jackson-core</artifactId>
		    <version>${jackson.version}</version>
		</dependency>
        
        <dependency>
             <groupId>com.fasterxml.jackson.core</groupId>
             <artifactId>jackson-databind</artifactId>
             <version>${jackson.version}</version>
         </dependency>
         <dependency>
            	<groupId>org.nd4j</groupId>
                <artifactId>nd4j-jackson</artifactId>
                <version>${nd4j.version}</version>
          </dependency>
          <dependency>
            	<groupId>org.nd4j</groupId>
                <artifactId>nd4j-api</artifactId>
                <version>${nd4j.version}</version>
          </dependency>
    </dependencies>
</project>

**Comment by raver119** [comment]
Your pom.xml is VERY old.
Please check out our examples, and dependencies used there: https://github.com/deeplearning4j/dl4j-examples

**Comment by kepricon** [comment]
@GrayHulk  we have gitter channels 

this is the main channel
https://gitter.im/deeplearning4j/deeplearning4j
and this the kr channel
https://gitter.im/deeplearning4j/deeplearning4j/deeplearning4j-kr
