### ISSUE TITLE
Android support for executing trained models

### ISSUE THREAD

**Issue by virl** [deeplearning4j/deeplearning4j#3648]
Greetings.

For my current job I need support for executing trained models on Android with minimum API level 15.

**Comment by raver119** [comment]
And what stops you from doing that?

**Comment by virl** [comment]
@raver119 Currently I'm in project planing phase, so I'm assessing different libraries for model execution on Android.

What scares me specifically in DL4J is that it uses NDK for execution and also that (as I understand) it requires building resulting app only for single processor architecture (due to native dependencies).
And also that it requires API level 21 (I need 15 or at least 16).

**Comment by virl** [comment]
@raver119 Also I'm concerned about model format lock-in: currently I'm planning to train model on PC using DL4J, but it may not be so in future, so I need for Android model execution library to support importing models from well-known formats.

Also I'm concerned about general bloat of framework regarding just execution: DEX limit, APK size, memory footprint, etc. Basically I don't want to embed in the app entire neural net toolkit to just execute pre-trained model.

I need something similar to Apple's CoreML in usability and convenience.

**Comment by raver119** [comment]
Aha. That's better, but still not sure what you want from us in this case?

re: NDK. Yes, we use JNI, however, you can embed both x86 & arm backends as i know. Or, you can have different apk's in Google Play built for different cpu architectures. So this question is beyond our scope really.

re: Android API Level. To be honest i'm not sure where l21 requirement comes from.

re: memory footprint: deeplearning4j-nn module contains only neural net stuff. Use that one if you want. smaller footprint.

re: CoreML. Not sure what to tell you here.

**Comment by virl** [comment]
@raver119 Is there some standard guide/tutorial on how to embed DL4J in android app?

Different APKs for different architectures is not an option, because app is not mine and used by tens of thousands users already.

API level 21 comes from here: https://deeplearning4j.org/android

**Comment by saudet** [comment]
@virl API level 21 is "for best results", it probably runs fine with API level 15, especially for  just deeplearning4j-nn. DL4J on the desktop can also import Keras model, so as long as you have models available in that format, they will be usable with DL4J from Android. Does that answer your questions?

**Comment by virl** [comment]
@saudet Thanks.
