### ISSUE TITLE
InferenceMode.BATCHED does not work

### ISSUE THREAD

**Issue by andr3a87** [deeplearning4j/deeplearning4j#3649]
#### Issue Description

Please describe our issue, along with:
- expected behavior: app run
- encountered behavior: exception

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.8.1-SNAPSHOT
* platform information (OS, etc): ubuntu 17.04
* CUDA version, if used:  8.0
* NVIDIA driver version, if in use

#### Contributing

val network = ModelSerializer.restoreComputationGraph(netPath, true)
val inf = new ParallelInference.Builder(network)
  .inferenceMode(InferenceMode.BATCHED)
  .batchLimit(10)
  .workers(4)
  .build()

images.par.foreach( img: opencv_core.Mat =>
	val indarray_reg = new NativeImageLoader().asMatrix(img)
	val pred: INDArray = inf.output(indarray_reg)
)

Exception: "Got rank 5 array as input to ConvolutionLayer (layer name = block1_conv1, layer index = 1) with shape [5, 1, 3, 224, 224]. Expected rank 4 array with shape [minibatchSize, layerInputDepth, inputHeight, inputWidth]."

if I remove .par from collection images it work. If I use InferenceMode.SEQUENTIAL it work.

**Comment by raver119** [comment]
Looks like Nd4j.pile() bug. Fix incoming.

**Comment by raver119** [comment]
Fixed, thanks for highlighting this issue.
