### ISSUE TITLE
The network is splitted on 2 gpu instead have a copy on each gpu

### ISSUE THREAD

**Issue by andr3a87** [deeplearning4j/deeplearning4j#3660]
#### Issue Description

Please describe our issue, along with:
- expected behavior: Each gpu have a copy of network
- encountered behavior: The network is splitted on gpus

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.8.1-SNAPSHOT
* platform information (OS, etc): Ubuntu 17.04
* CUDA version, if used: 8.0
* NVIDIA driver version, if in use

#### Contributing

Before installing the second gpu, the RAM busy on the gpu was 4GB. After inserting a second card, the RAM busy on first board is 2.2Gb and on second is 1.8Gb. I use this settings:

val parallelInf = new ParallelInference.Builder(network)
          .inferenceMode(InferenceMode.SEQUENTIAL)
          .workers(2)
          .build()

**Comment by raver119** [comment]
If you have 2 gpus - both gpus have copy of your model.

**Comment by andr3a87** [comment]
The size dimension of my network is 4gb. If each gpu have a copy, each gpu have busy at least 4gb of RAM, but this doesn't happen.

**Comment by raver119** [comment]
That's wrong conclusion, sorry. Each model gets replicated to its own device. There's no other behavior possible, unfortunately.

**Comment by raver119** [comment]
I hadn't closed this issue yet only because it's reminder for me, that device_0 doesn't need replication. So it needs the same tweak i made recently for ParallelWrapper.

But otherwise, your issue isn't an issue, and expected behavior.

**Comment by andr3a87** [comment]
ok, thanks you so much.

**Comment by raver119** [comment]
> device_0 doesn't need replication. 

This was implemented long ago.
