### ISSUE TITLE
Code sample in quick start guide doesn't compile

### ISSUE THREAD

**Issue by CedricReichenbach** [deeplearning4j/deeplearning4j#3662]
The code snippet in the [Quick Start Guide](https://deeplearning4j.org/quickstart) looks like a minimal example of a multi layer configuration, but actually doesn't compile because it's incomplete. In order to end up with a `MultiLayerConfiguration` (builder), at least an additional `list()` call should be included, e.g.

```java
MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
        .iterations(1)
        .weightInit(WeightInit.XAVIER)
        .activation("relu")
        .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
        .learningRate(0.05)
        // ... other hyperparameters
        .list()
        .backprop(true)
        .build();
```

**Comment by tomthetrainer** [comment]
I added the change that you suggest here, closing ticket, re-open if other issues remain.
