### ISSUE TITLE
Best Practices Doc

### ISSUE THREAD

**Issue by tomthetrainer** [deeplearning4j/deeplearning4j#3668]
We could use a "Best Practices Doc" that describes the following. 

Below from Edward Junprung
* basic ETL, 
* loading the training UI, 
* saving models per epoch, 
* reducing memory usage, 
* expectation on how long it will take, 
* etc. 

@bkanui If the issue remains here it should become a documentation page, blog or some other form for this are potential options.

**Comment by tomthetrainer** [comment]
@bkanui , 

Let's do the following. 

1. Build a document page for this and put it on our main deeplearning4j.org site. 
2. Use this as an example of working towards a template page for docs. 

I propose we make a link under the navigation panel on the left for Neural Networks

I propose we call the page "best practices" 

Start with a header paragraph something like. 

Many options are available when building a neural network and often best practices are a moving target, for example the explosion of slightly differing activation functions in the relu family, or the move from sigmoind to relu. The goal of this page is to provide best practices guidlelines to some common questions. 

Then bullets with html anchors ( I think the pages with headers and anchors are a good choice for a template, I would accept input of course)

The bullets would be what is described in Ed's request and in the first comment to this issue. 

Next steps: 

We can either create a "draft" page on the master branch, this is the easiest path. 

Or we can create a fork, and the changes to the fork and merge. 

Also if we want we can use this as a chance to get you further educated in the wonders of jekyl and we can set up a local environment for you.

**Comment by bkanui** [comment]
Sounds like a plan. I'm in.

**Comment by tomthetrainer** [comment]
Moving to private repo
