### ISSUE TITLE
MNIST downloader: add checksum / validation

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3670]
It seems it is possible (though unlikely) for the downloaded MNIST data to be corrupted, but still read as if nothing is wrong.
The only symptom in my case: examples using the corrupted MNIST data would not learn. No exception or anything, just learning doesn't proceed as expected.

While we are at it: we should solve the "unexpected end of ZLIB stream" 'bad down' error once and for all (i.e., warn and re-download if it fails a check-sum or hash or something).

I've attached the contents of my /MNIST directory that was able to cause this:
[MNIST_Silent_Corruption.zip](https://github.com/deeplearning4j/deeplearning4j/files/1144209/MNIST_Silent_Corruption.zip)

[MNIST_Silent_Corruption_2.zip](https://github.com/deeplearning4j/deeplearning4j/files/1182243/MNIST_Silent_Corruption_2.zip)

**Comment by raver119** [comment]
Fix applied. Shouldn't ever happen anymore.
