### ISSUE TITLE
Deconvolution and unpooling for semantic segmentation?

### ISSUE THREAD

**Issue by OliverColeman** [deeplearning4j/deeplearning4j#3671]
I'd like to implement something like Learning Deconvolution Network for Semantic Segmentation (https://arxiv.org/abs/1505.04366). It doesn't look like there are deconvolution or unpooling layer implementations in DL4J. Is this on the roadmap?

**Comment by OliverColeman** [comment]
#2818

**Comment by AlexDBlack** [comment]
We'd love to have them - but they are not on the immediate roadmap, unfortunately.
Let us know if you'd be interested in trying to implement them.

**Comment by patrickgitacc** [comment]
Are you working on a deconvolutional function?

**Comment by AlexDBlack** [comment]
Deconv was implemented semi-recently: https://github.com/deeplearning4j/deeplearning4j/search?utf8=%E2%9C%93&q=deconvolution&type=
