### ISSUE TITLE
Minor bugs with "ParallelWrapper"

### ISSUE THREAD

**Issue by SummerRainET2008** [deeplearning4j/deeplearning4j#3674]
#### Issue Description
1. ParallelWrapper.fit(DataSetIterator source).
Should not do "source.reset()" first, otherwise this function can not continue to run from last exit. 
More, ComputationGraph.fit(...) runs as expected. So if we use the ParallelWrapper.fit() in example "org.deeplearning4j.examples.recurrent.encdec", then it would run into an error.

2. ParallelWrapper.Trainer.run()
The "replicatedModel" only copy the config of "originalModel", but does not copy its parameter. Then we can not continue to train using a previous model as its initialization, which is quite bad.

Please describe our issue, along with:
- expected behavior

- encountered behavior
 

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version

#### Contributing
Quite simple updates.

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
Both issues are fixed/improved in current master, and only valid for 0.8.0 and below.

However, iterator.reset() is called if iterator.resetSupported() == true.
