### ISSUE TITLE
Gracefully handle WordVectorsImpl.getWordVectors given List of no known words

### ISSUE THREAD

**Issue by knightcode** [deeplearning4j/deeplearning4j#3677]
This loop below in the implementation of getWordVectors below potentially empties the entire `indexes` array. If so, passing it to Nd4j.pullRows will cause an IllegalStateException to be thrown. The user has no mechanism to determine if this will happen other than a try/catch. Is there a more graceful way to handle this? Would it be possible to return an INDArray filled with the vectors for UNK?

```java
while(ArrayUtils.contains(indexes, -1)) {
    indexes = ArrayUtils.removeElement(indexes, -1);
}
```

**Comment by alexanderst** [comment]
Fix was merged.
