### ISSUE TITLE
Unsupported keras layer type Cropping2D

### ISSUE THREAD

**Issue by mshpyl** [deeplearning4j/deeplearning4j#3683]
Hello!

I'm trying to import a pre-trained model into DL4J from keras.

But importKerasModelAndWeights(myModel,myWeights) throws the error:

    UnsupportedKerasConfigurationException: Unsupported keras layer type Cropping2D.

Is there any plan to implement this functionality, or is there a work-around?

Thanks in advance.

**Comment by maxpumperla** [comment]
@mshpyl took a while, but it's in 0.9.2-SNAPSHOT now
