### ISSUE TITLE
Deadlock with UI

### ISSUE THREAD

**Issue by firasdib** [deeplearning4j/deeplearning4j#3684]
#### Issue Description

Using the UI sometimes results in a deadlock. Thread dump below here: https://gist.github.com/firasdib/08d1c94a519ef650be1f4fe23afae0a2

#### Version Information

* Deeplearning4j 0.8.0
* platform information: OSX

**Comment by AlexDBlack** [comment]
I've had very sporadic reports of MapDB causing deadlocks, but I've never been able to reproduce it...

Other gists pulled from gitter for this:
https://gist.github.com/firasdib/2a8e62d32a8817dcbd46dd5ebef73cb8
https://gist.github.com/firasdib/bcee1d815b032e25a9cc7c51e09f0e80
https://gist.github.com/firasdib/ffd017a436a4e4706ec973c782ded863
https://gist.github.com/firasdib/d35077e86dc14ecbfdde6f19960161c0

**Comment by AlexDBlack** [comment]
I was able to reproduce this, fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/3690
