### ISSUE TITLE
Training on AWS fails with CUDNN Exception

### ISSUE THREAD

**Issue by edobm** [deeplearning4j/deeplearning4j#3692]
#### Issue Description

https://gist.github.com/edobm/f592af3849a0972fd1db48412813b0be

#### Version Information
0.8.1-SNAPSHOT

#### Contributing

I will conduct further experiments on AWS p2.{1|8|16}xlarge instances if required

**Comment by raver119** [comment]
show your pom.xml too please.

**Comment by raver119** [comment]
As discussed in gitter, solely memory issue, and workspaces helped to step over it.

Closing this now, feel free to open new issue if something else happens.
