### ISSUE TITLE
CUDA stream synchronization failed

### ISSUE THREAD

**Issue by edobm** [deeplearning4j/deeplearning4j#3694]
#### Issue Description

Following exception is thrown sometimes:

[https://gist.github.com/edobm/505d4ac5b222d0747ca9ee697deb1e8a](https://gist.github.com/edobm/505d4ac5b222d0747ca9ee697deb1e8a)

#### Version Information

Please indicate relevant versions, including, if relevant:

0.8.1-SNAPSHOT
Windows 10 64
CUDA 8.0

**Comment by raver119** [comment]
This wall of text gives me nothing.

Please consider adding:
- gist with your source code
- gist with your pom.xml
- this wall of text as gist

**Comment by edobm** [comment]
Changed to gist

**Comment by raver119** [comment]
Isn't this issue resolved now? I remember we did something with you?
