### ISSUE TITLE
BasicModelUtils.java  line 201     version:0.8.0 

### ISSUE THREAD

**Issue by lovetomorrow** [deeplearning4j/deeplearning4j#3695]
Is it a bug? 

    for (String word : tempRes) {
            if (!positive.contains(word) && !negative.contains(negative) && realResults.size() < top)
                realResults.add(word);
        }

**Comment by AlexDBlack** [comment]
A little context here might help... I mean where is this from, for starters?

**Comment by lovetomorrow** [comment]
Oh,It my fault.

Its in BasicModelUtils.java  line 201 
The method was called wordsNearst

`  public Collection<String> wordsNearest(@NonNull Collection<String> positive, @NonNull Collection<String> negative,
                    int top) {
        // Check every word is in the model
        for (String p : SetUtils.union(new HashSet<>(positive), new HashSet<>(negative))) {
            if (!vocabCache.containsWord(p)) {
                return new ArrayList<>();
            }
        }

        INDArray words = Nd4j.create(positive.size() + negative.size(), lookupTable.layerSize());
        int row = 0;
        //Set<String> union = SetUtils.union(new HashSet<>(positive), new HashSet<>(negative));
        for (String s : positive) {
            words.putRow(row++, lookupTable.vector(s));
        }

        for (String s : negative) {
            words.putRow(row++, lookupTable.vector(s).mul(-1));
        }

        INDArray mean = words.isMatrix() ? words.mean(0) : words;

        Collection<String> tempRes = wordsNearest(mean, top + positive.size() + negative.size());
        List<String> realResults = new ArrayList<>();

        for (String word : tempRes) {
            if (!positive.contains(word) && !negative.contains(negative) && realResults.size() < top)
                realResults.add(word);
        }

        return realResults;
    }`

**Comment by raver119** [comment]
But what is a bug?

**Comment by raver119** [comment]
This segment applies filtering to results, to exclude original words (both positive and negative) from output set

**Comment by lovetomorrow** [comment]
`if (!positive.contains(word) && !negative.contains(negative)&& realResults.size() < top)`

I mean this line. 
`!negative.contains(negative)`

**Comment by raver119** [comment]
Ah. Ye, bug.

Thanks for highlighting.

**Comment by raver119** [comment]
Fixed. Thanks!
