### ISSUE TITLE
Learning rate schedule based on epoch count

### ISSUE THREAD

**Issue by firasdib** [deeplearning4j/deeplearning4j#3700]
#### Issue Description

It would be beneficial to have a schedule where one could specify the total amount of epochs and have the learning rate be adjusted by a factor each epoch. As mentioned in [this](https://arxiv.org/pdf/1611.00801.pdf) paper, they have a schedule where the learning rate is updated by a factor `x` which can be calculated like this:

```
initialLearningRate * x^{epochCount} = finalLearningRate
```

**Comment by agibsonccc** [comment]
This could potentially be apart of the pipeline api? It's harder to support epoch based workflows right now aside from manually calculating the iterations ourselves (which we could do internally)

**Comment by firasdib** [comment]
For anyone ending up here, this is how I decided to solve it until a better solution comes along:

```java
final Map<Integer, Double> lrSchedule = new HashMap<>();
final int iterationsPerEpoch = ...; // Total samples divided by batch count
final double epochDecayValue = Math.pow(FINAL_LEARNING_RATE / LEARNING_RATE, 1.0 / EPOCH_COUNT);

for (int i = 0; i < EPOCH_COUNT; i++) {
    lrSchedule.put(iterationsPerEpoch * i, Math.pow(epochDecayValue, i) * LEARNING_RATE);
}
```

**Comment by AlexDBlack** [comment]
ISchedules interface allows schedules to be based on epochs or learning rate
https://github.com/deeplearning4j/deeplearning4j/pull/3985
