### ISSUE TITLE
setParamTable unimplemented 

### ISSUE THREAD

**Issue by miracle1949** [deeplearning4j/deeplearning4j#3701]
#### Issue Description
For documentation of MultiLayerNetowrk found at https://deeplearning4j.org/doc/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.html
This function
`setParamTable(java.util.Map<java.lang.String,org.nd4j.linalg.api.ndarray.INDArray> paramTable)Setter for the param table`
is not actually implemented. 
Please indicate this in the documentation.

**Comment by AlexDBlack** [comment]
Method was implemented here: https://github.com/deeplearning4j/deeplearning4j/pull/3773
