### ISSUE TITLE
Test Failures on Mac-Os

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/deeplearning4j#3705]
### nearestneighbor-core
Tests in error: 
  ~~VpTreeNodeTest.testVPSearchOverNaturals1D:180->testVPSearchOverNaturalsPD:213~~ PASSES
  ~~VpTreeNodeTest.testVPSearchOverNaturals2D:185->testVPSearchOverNaturalsPD:213~~ PASSES
  ~~VpTreeNodeTest.vpTreeTest:156 » IllegalState Mis matched lengths: [3] != [2]~~ NPE now
java.lang.NullPointerException
	at org.deeplearning4j.clustering.vptree.VPTree.<init>(VPTree.java:117)

### deeplearning4j-core
Fails sporadically...
TestOptimizers - 
testRastriginFnOptLBFGSMultipleSteps and testRastriginFnOptLBFGSMultipleSteps

###  dl4j-spark
Failed tests:
 ~~TestSparkComputationGraph.testEvaluationAndRocMDS:358 expected:<0.615> but was:<0.9814000012412665>~~ updated
TestSparkComputationGraph.testEvaluationAndRocMDS Expected :0.9934
Actual   :1.0

### deeplearning4j-parallel-wrapper
Failed tests:
  TestListeners.testListeners:47->testListenersForModel:130 expected:<3> but was:<4>
  TestListeners.testListenersGraph:64->testListenersForModel:130 expected:<3> but was:<4>
Tests in error: 
  ParallelWrapperTest.testParallelWrapperRun:106 » Runtime java.lang.RuntimeExce...
  ParallelWrapperMainTest.runParallelWrapperMain:80 » Runtime java.lang.RuntimeE...

### dl4j-spark-nlp-java8
Tests in error: 
  SparkSequenceVectorsTest.testFrequenciesCount
  SparkWord2VecTest.testStringsTokenization1

### dl4j-spark-ml
Tests in error:
 SparkDl4jNetworkTest.testNetwork
AutoEncoderNetworkTest.testAutoencoderSave

### deeplearning4j-ui
Tests in error:
  TestSerialization.testModelSerde:49 » NullPointer

**Comment by eraly** [comment]
### deeplearning4j-zoo
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.144 sec <<< FAILURE! - in org.deeplearning4j.zoo.TestDownload
testDownloadAllModels(org.deeplearning4j.zoo.TestDownload)  Time elapsed: 1.88 sec  <<< ERROR!
java.lang.IllegalStateException: Pretrained model file failed checksum. If this error persists, please open an issue at https://github.com/deeplearning4j/deeplearning4j.
	at org.deeplearning4j.zoo.TestDownload.testDownloadAllModels(TestDownload.java:53)

**Comment by AlexDBlack** [comment]
TestSparkComputationGraph.testEvaluationAndRocMDS was test issue, fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/3742

**Comment by eraly** [comment]
Haven't ran updated nlp tests and part of the scale out. Everything else is updated.
