### ISSUE TITLE
ConvolutionalIterationListener: IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by edobm** [deeplearning4j/deeplearning4j#3715]
#### Issue Description

Calculated bounds for rnd.nextInt() evaluates to 0 whats causes IAE:

https://gist.github.com/edobm/228bda357bcce87096ec496295a258b1

#### Version Information

Please indicate relevant versions, including, if relevant:
0.8.1-SNAPSHOT

**Comment by raver119** [comment]
Fixed, thanks for highlighting this issue.
