### ISSUE TITLE
nd4j-cpu fails to compile on mvn clean install

### ISSUE THREAD

**Issue by brettins** [deeplearning4j/deeplearning4j#372]
https://gist.github.com/brettins/46a4e2e4206ae683b507

Windows 7

**Comment by agibsonccc** [comment]
So I noticed this:
[ERROR] Failed to execute goal org.bytedeco:javacpp:0.11:build (process-classes) on project nd4j-x86: Failed to execute JavaCPP Builder: Cannot run program "cl"

Could you try this please?
http://www.itechtalk.com/thread3595.html

**Comment by agibsonccc** [comment]
We have this down. Install the visual studio compiler and put it in your path.
