### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by papperwing** [deeplearning4j/deeplearning4j#3723]
After few iteration I got this error:
https://gist.github.com/papperwing/cdad486bb811022d71addbcd29e176f9

Here is link to tarred run folder consisting of IDEA runConfiguration (it is needed to copy into idea folder) and tmp folder containing presaved data for test.
https://drive.google.com/file/d/0B5lEbcbm2laiUWlFX2VHN2NjczA/view?usp=sharing

Here is link to github repository of project:
https://github.com/papperwing/image-net

For reprodiction it should be possible to download repository, open it in IDEA IDE, copy runConfiguration ResnetMemoryConsumptionTest_ResnetMemoryConsumptionTest.xml into .idea/runConfigurations. Then in ide change workingDirectory in "Edit Configuration" setting to test folder extracted from tar and run test. Issue has popped out after first three iterations in two consecutive runs.

Test location: https://github.com/papperwing/image-net/blob/master/modules/image-net-model-creator/src/test/java/cz/muni/fi/image/net/ResnetMemoryConsumptionTest.java

**Comment by raver119** [comment]
Fixed, thanks for highlighting this issue.

For historic reference: oom on native side. Added ptr validation.
