### ISSUE TITLE
CUDA + LSTM implementation + workspaces - exception on character example

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3731]
Take the character example, switch to LSTM layer (from GravesLSTM), set WorkspaceMode.Single for both and we get the following exception:
https://gist.github.com/AlexDBlack/79265da24e82b43b0cf895db2648fcca

Note that GravesLSTM, which shares most of the code with LSTM, is fine.

I'm assuming this is workspace related (array/s being leaked outside of scope) but I can't see any differences between GravesLSTM and LSTM that would explain it...

**Comment by raver119** [comment]
Fixed
