### ISSUE TITLE
Unsupervised pre-train then supervised fine-tuning

### ISSUE THREAD

**Issue by ringyhz** [deeplearning4j/deeplearning4j#3732]
Hi,

I recently started studying deep learning. One paper I read says that we can pre-train a deep belief network using unlabelled data, then use labelled data for fine tuning. I browsed through the deeplearn4j.org tutorials but didn't find a tutorial or example code that shows how this is done. Can you show me an example how to train a model using deeplearning4j first using unlabelled data then using labelled data?

Thanks

**Comment by tomthetrainer** [comment]
I will look into this.

**Comment by tomthetrainer** [comment]
I need help with this. 
@turambar @eraly @crockpotveggies

**Comment by crockpotveggies** [comment]
Bad news here is we are dropping support for RBMs/deep belief networks in general in favour of newer and more effective methods. Good news is I'd like to direct you to variational autoencoders which we are giving the pedestal https://github.com/deeplearning4j/dl4j-examples/tree/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/unsupervised/variational

Regarding fine-tuning using labelled data, not sure that's something we'll immediately add an example for. However, I'll direct you to transfer learning which may help: https://deeplearning4j.org/transfer-learning

Closing this for now.
