### ISSUE TITLE
Example Testing - Issues

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3743]
**Multi-GPU Character RNN**
Take Multi-GPU version of GravesLSTMCharModellingExample, set int exampleLength = 200; instead of 1000; also added a ```if(iteration % 100 == 0) {``` inside the listener iterationDone method.
Notably: verbose mode -> seems to run without crashing... ```CudaEnvironment.getInstance().getConfiguration().enableDebug(true).setVerbose(true);```

https://gist.github.com/AlexDBlack/fa49ade5fbea9aba2c7374ed1fe94c35

**Multi-GPU LeNet** (same result with FP16 and FP32, 2x GTX970s, Windows)
Basically: not learning. Single GPU version learns fine.
https://gist.github.com/AlexDBlack/8db7e1ad841c6f1f0440f0e34a75a91b

**MLPMnistDistributedExample**, Windows - (error re: network address - given it's being run on a single machine, it's probably not a big deal)
https://gist.github.com/AlexDBlack/b6cd7baf32dd963aaab4e198be1447ef

**Comment by agibsonccc** [comment]
Seeing issues on Glove/gpu with gradient exploding. Doesn't happen on cpu.
https://gist.github.com/agibsonccc/d16d750a84e2bef2ca975907159e0765

Example:
https://github.com/deeplearning4j/dl4j-examples/blob/c021b4514f6521a58be890114e9073e36b1cd6bf/dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/glove/GloVeExample.java#L63

**Comment by raver119** [comment]
LeNet fixed.

**Comment by AlexDBlack** [comment]
Closing this after re-testing examples.
