### ISSUE TITLE
Setting DataType.Double causes a problem with some layers when using cuda.

### ISSUE THREAD

**Issue by wmeddie** [deeplearning4j/deeplearning4j#3749]
#### Issue Description

Sample code and output: https://gist.github.com/wmeddie/42b44e1a8e8427226c579cc852174b79

The above code has two issues, but the first surprising one was that adding `Nd4j.setDataType(DataBuffer.Type.DOUBLE);` causes a ND4JIllegalStateException.

Stack Trace: https://gist.github.com/wmeddie/42b44e1a8e8427226c579cc852174b79#file-output-cuda-datatype-double-L299

Using the BACKEND_PRIORITY_CPU both float and double versions work (output included)

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j 0.8.1-SNAPSHOT (as of afternoon 7/27
* Windows 10
* CUDA 8 CuDNN 6

**Comment by agibsonccc** [comment]
I wonder if this is related to nd4j initialization order @raver119 ?

**Comment by raver119** [comment]
99% chance yes.

Move Nd4j.dtype change to first line, so it's called before CUDA backend has it's buffers initialized.

Post update here after that.

**Comment by wmeddie** [comment]
Putting `Nd4j.setDataType(DataBuffer.Type.DOUBLE);` as the first line didn't have any effect.  I also try putting it in a static initializer as well.

**Comment by raver119** [comment]
O_O

**Comment by raver119** [comment]
Fixed. Thanks for highlighting this.
