### ISSUE TITLE
Remote UI and spark conflict issues: Need better documentation

### ISSUE THREAD

**Issue by tomthetrainer** [deeplearning4j/deeplearning4j#3751]
Spark conflicts with our UI forcing the need for a remote UI. This is covered rather well (I think) in the docs under distributed training, however it seems they could be re-organized or clarified in some way. Opening this issue for a general revue and clarification of the UI documentation to verify it is well covered in a central easy to find location. 

I will close https://github.com/deeplearning4j/deeplearning4j/issues/2617

And refer all discussion to this issue.

**Comment by beatngu13** [comment]
Unfortunately, the [`UIExample`](https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/userInterface/UIExample.java) crashes for the same reason. How's one supposed to fix this?

Moreover, why does the [doc](https://deeplearning4j.org/visualization#sparkui) explicitly mentions that the remote UI functionality "will require the `deeplearning4j-ui_2.10` or `deeplearning4j-ui_2.11` dependency"? Doesn't step one of the tutorial says it's a prerequisite anyway?

**Comment by clavvis** [comment]
I tried AnimalsClassification from dl4j-examples and had the same error as is described in #2617.
I dont need Spark. So I removed this dependency:
			<groupId>org.datavec</groupId>
			<artifactId>datavec-spark_${scala.binary.version}</artifactId>
from my pom.xml and example is working.
