### ISSUE TITLE
Put the documentation in a separate repository or separate directory. 

### ISSUE THREAD

**Issue by RobAltena** [deeplearning4j/deeplearning4j#3759]
#### Issue Description
We have the documentation under a branch in the main repository.  It probably is cleaner to have the docs in a separate repository, or in a separate directory under the master branch.

#### Contributing
Happy to contribute on this. Lets have a little discussion here first.

**Comment by agibsonccc** [comment]
We cant. This would break github pages which relies on the gh-pages brancgh
