### ISSUE TITLE
Incorrect warning about `ADAM`-updater params in 0.8.1

### ISSUE THREAD

**Issue by firasdib** [deeplearning4j/deeplearning4j#3760]
#### Issue Description

I just updated to 0.8.1 from 0.8.0 and had previously this in my config:
```java
.updater(Updater.ADAM)
.adamMeanDecay(...)
.adamVarDecay(...)
```

These functions are now deprecated, but when I ran my code I saw the following in the console output:
```
adamVarDecay is set but will not be applied unless the updater is set to Adam.
adamMeanDecay is set but will not be applied unless the updater is set to Adam.
```

Which does not seem right, regardless of deprecation.

#### Version Information

* 0.8.1
* OSX

**Comment by AlexDBlack** [comment]
Thanks. Reproduced and fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/3773
