### ISSUE TITLE
Conversion between Spark Matrix and Nd4j Matrix (as INDArray) is wrong in MLLibUtil

### ISSUE THREAD

**Issue by rauwuckl** [deeplearning4j/deeplearning4j#3767]
#### Issue Description

In the class MLLibUtil the Conversion between a Spark Matrix and a INDArray is wrong. The DataBuffer in Spark Matrices seems to be organized in "f"-Style by default, while INDArrays use "c"-Style by default.

Some Test Code that is currently failing to illustrate the problem:

https://gist.github.com/rauwuckl/ae21794c325240cf2cfc40d15ce2301c

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.8.0
* Spark version: 2.1

#### Contributing

I have a bugfix already locally but I can't yet get my development version of dl4j to work. So I can't test and therefore can't submit the pull request yet. But if nobody is faster I would submit it sometime in the next few weeks when I have time.

**Comment by raver119** [comment]
I'm afraid, that if Spark Matrix has only one option (F-order), and we have both options available - the only possible "fix" here is enforced transpose to/from C/F order.

**Comment by rauwuckl** [comment]
mh here is how I fixed it for myself:
https://github.com/rauwuckl/deeplearning4j/blob/bugfix_MLLibUtil/deeplearning4j-scaleout/spark/dl4j-spark/src/main/java/org/deeplearning4j/spark/util/MLLibUtil.java

I think it is also a problem if you use it on a View. Since the databuffer for the view still contains all the data, doesn't it?

**Comment by raver119** [comment]
I've already applied fixes. Waiting for review/merge now.

**Comment by raver119** [comment]
Fix merged, thanks for highlighting this one.
