### ISSUE TITLE
How can i make sure GPU is used?

### ISSUE THREAD

**Issue by chenjinyuan87** [deeplearning4j/deeplearning4j#3768]
#### Issue Description
I'm trying using dl4j to train my model, and i selected the GPU version.
But it seems still using CPUs to calculate the results. 
When running the model, it costs more then 10 GM memory, and about 1000% cpu (My cpu has 16 kernels).
The GPU status is：
Mon Jul 31 20:31:37 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M40 24GB      Off  | 0000:04:00.0     Off |                    0 |
| N/A   44C    P0    63W / 250W |   7565MiB / 22939MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0    167136    C   java                                          7531MiB |
+-----------------------------------------------------------------------------

The training speed is extremely slow, it costs more than 30 secs / iteration.

Could you help me to find out the problem?

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
The dependency in pom is:

        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>0.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-nlp</artifactId>
            <version>0.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-cuda-8.0</artifactId>
            <version>0.8.0</version>
        </dependency>

* platform information (OS, etc)
CentOS Linux release 7.3.1611 (Core)

* CUDA version, if used
The CUDA version is 8.0

* NVIDIA driver version, if in use
 NVIDIA UNIX x86_64 Kernel Module  375.26  Thu Dec  8 18:36:43 PST 2016

Thanks a lot.

**Comment by agibsonccc** [comment]
Are you trying to use word2vec with cuda? That's not a good idea in general.

**Comment by chenjinyuan87** [comment]
Yes, I'm using word2vec.
Could you please tell me what should i do?

**Comment by agibsonccc** [comment]
Just use cpu for word2vec.  I mean the embeddings and everything else end up taking really long to load on the gpu among other things right now. I'm closing this. There's nothing more to do here.

We need to implement an alternate structure for embeddings. We will do that at a later date though.
