### ISSUE TITLE
RBM not learning

### ISSUE THREAD

**Issue by cqiaoYc** [deeplearning4j/deeplearning4j#3785]
I want to use DBN for regression. But the RBM don't learning. What's wrong with me? My code:
int iterations = 100;
        int listenerFreq = iterations / 5;
        long seed = 200;
        double learnRate = 0.01;

        MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                .seed(seed)
                .iterations(iterations)
                .learningRate(learnRate)
                .regularization(true).l2(1e-4)
                .list()
                .layer(0, new RBM.Builder().nIn(this.featureCount).nOut(featureCount * 1 / 2).lossFunction(LossFunctions.LossFunction.KL_DIVERGENCE).build())
                .layer(1, new RBM.Builder().nIn(featureCount * 1 / 2).nOut(featureCount * 1 / 4).lossFunction(LossFunctions.LossFunction.KL_DIVERGENCE).build())
                .layer(2, new RBM.Builder().nIn(featureCount * 1 / 4).nOut(featureCount * 1 / 8).lossFunction(LossFunctions.LossFunction.KL_DIVERGENCE).build())
                .layer(3, new RBM.Builder().nIn(featureCount * 1 / 8).nOut(featureCount * 1 / 16).lossFunction(LossFunctions.LossFunction.KL_DIVERGENCE).build())
                .layer(4, new RBM.Builder().nIn(featureCount * 1 / 16).nOut(featureCount * 1 / 32).lossFunction(LossFunctions.LossFunction.KL_DIVERGENCE).build())
                .layer(5, new OutputLayer.Builder(LossFunctions.LossFunction.MSE).activation(Activation.TANH).nIn(featureCount * 1 / 32).nOut(1).build())
                .pretrain(true)
                .backprop(true)
                .build();

        MultiLayerNetwork model = new MultiLayerNetwork(conf);
        model.init();
        model.setListeners(new ScoreIterationListener(listenerFreq));
        model.fit(trainDataSet); 

Output:
train stats: 
real=0.30000001192092896,predict=-0.07733020931482315
real=0.20000000298023224,predict=-0.07790719717741013
real=0.20000000298023224,predict=-0.07697547972202301
real=0.0,predict=-0.07709220051765442
real=0.20000000298023224,predict=-0.07896068692207336
real=0.10000000149011612,predict=-0.07756499946117401
real=-0.10000000149011612,predict=-0.0772671103477478

If repalce the RBMs with DenseLayer, it is OK. 
maven:
 <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>0.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-nn</artifactId>
            <version>0.8.0</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native</artifactId>
            <version>0.8.0</version>          
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp</artifactId>
            <version>1.3.3</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-jblas</artifactId>
            <version>0.4-rc3.6</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>4.3.10.RELEASE</version>
        </dependency>
        
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-api</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-cuda-8.0</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
<nd4j.version>0.8.0</nd4j.version>
OS is win10, OpenJDK 8.0

**Comment by raver119** [comment]
> org.nd4j
nd4j-jblas
0.4-rc3.6

Side note: you can't use that thing now. There's no more support for jblas

**Comment by cqiaoYc** [comment]
nd4j-jblas is nothing to the result.

**Comment by raver119** [comment]
Right, that's why i've used "side note" words.

**Comment by raver119** [comment]
Beyond that - i'd suggest trying latest snapshot. As i remember there were some fixes related to RBMs, that might be applied after 0.8.0 release.

**Comment by cqiaoYc** [comment]
I replace with 0.9.0 release. An exception (java.lang.ExceptionInInitializerError) come:
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\XX\.javacpp\cache\cuda-8.0-6.0-1.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jnicuda.dll: Can't find dependent libraries
Remove nd4j-cuda-8.0-0.9.0,  It still does not learning.

**Comment by cqiaoYc** [comment]
I let iterations = 1,2,3,4,5...The results were (in sample):
int iterations = 1;train stats: 
real=0.10000000149011612,predict=-0.6561343669891357
real=-0.20000000298023224,predict=-0.6552271246910095
real=-0.10000000149011612,predict=-0.6556174755096436
real=0.20000000298023224,predict=-0.6558666229248047
real=0.0,predict=-0.6554686427116394
real=0.20000000298023224,predict=-0.6554767489433289
real=0.0,predict=-0.6554561853408813
real=0.20000000298023224,predict=-0.6555951237678528
real=0.10000000149011612,predict=-0.655453622341156
real=-0.10000000149011612,predict=-0.6555641889572144
===========================================
int iterations = 2;test stats: 
real=0.10000000149011612,predict=-0.5780273675918579
real=-0.20000000298023224,predict=-0.5770466327667236
real=-0.10000000149011612,predict=-0.5774682760238647
real=0.20000000298023224,predict=-0.5777463316917419
real=0.0,predict=-0.5773093700408936
real=0.20000000298023224,predict=-0.5773161053657532
real=0.0,predict=-0.5772966146469116
real=0.20000000298023224,predict=-0.5774427056312561
real=0.10000000149011612,predict=-0.5772991180419922
===========================================
int iterations = 3;train stats: 
real=0.10000000149011612,predict=-0.48786377906799316
real=-0.20000000298023224,predict=-0.48682743310928345
real=-0.10000000149011612,predict=-0.4872725009918213
real=0.20000000298023224,predict=-0.48757490515708923
real=0.0,predict=-0.4871060252189636
real=0.20000000298023224,predict=-0.4871117174625397
real=0.0,predict=-0.4870932996273041
real=0.20000000298023224,predict=-0.48724398016929626
real=0.10000000149011612,predict=-0.48710179328918457
real=-0.10000000149011612,predict=-0.4872252941131592
=========================================
int iterations = 4;train stats: 
real=0.10000000149011612,predict=-0.3930881917476654
real=-0.20000000298023224,predict=-0.3920252025127411
real=-0.10000000149011612,predict=-0.39248088002204895
real=0.20000000298023224,predict=-0.39279934763908386
real=0.0,predict=-0.3923111855983734
real=0.20000000298023224,predict=-0.3923163414001465
real=0.0,predict=-0.39229902625083923
real=0.20000000298023224,predict=-0.39245057106018066
real=0.10000000149011612,predict=-0.3923141062259674
real=-0.10000000149011612,predict=-0.39243847131729126
===========================================
int iterations = 5;train stats: 
real=-0.20000000298023224,predict=-0.30222803354263306
real=-0.10000000149011612,predict=-0.3024686276912689
real=0.10000000149011612,predict=-0.3025442361831665
real=-0.10000000149011612,predict=-0.30270054936408997
real=0.10000000149011612,predict=-0.30271658301353455
real=-0.10000000149011612,predict=-0.3026362359523773
real=0.20000000298023224,predict=-0.30238014459609985
real=0.0,predict=-0.30256763100624084
real=0.10000000149011612,predict=-0.30260851979255676
real=0.0,predict=-0.3025434613227844

From the results, with the increase of iterations, the predicted values are approaching 0. But for each iterations, the predictive values are very close. I adjusted the parameter" weightinit", but the results didn't change.

**Comment by agibsonccc** [comment]
You are using an old version of dl4j. We do not support old versions. Use the latest from the examples.
http://github.com/deeplearning4j/dl4j-examples

Please look at our tuning docs. 
http://deeplearning4j.org/troubleshootingneuralnets
