### ISSUE TITLE
Add `limit` option to word2vec directly

### ISSUE THREAD

**Issue by firasdib** [deeplearning4j/deeplearning4j#3793]
#### Issue Description

Limiting the vocabulary size for the word2vec model is quite difficult as it stands today as you'll have to manually recreate all the datastructures that are otherwise created under the hood, just to set this option.

Would be great if you could just set this directly on the word2vec builder.

#### Version Information

* Deeplearning4j version 0.9.0

**Comment by raver119** [comment]
Option was added.

**Comment by firasdib** [comment]
Thank you. Is there a snapshot for 0.9.0 which will contain this fix?

**Comment by raver119** [comment]
Sure no. It was added few hrs ago, so you'll have to wait till snapshots rebuild.
