### ISSUE TITLE
Saving Word2vec model serializes dynamic classes

### ISSUE THREAD

**Issue by firasdib** [deeplearning4j/deeplearning4j#3794]
#### Issue Description

I used a lambda as my pre-preocessor and it got serialized. When I try to run the model I get an error saying it can't find that lambda: https://gist.github.com/firasdib/8b8f0f81a58f3ff5671099c473118d3e

`config.json` contains the following:

```
"tokenPreProcessor":"se.lth.cs.nlp.EntityRecognizer.NeuralNetwork.Word2Vec$$Lambda$2/1121891386"
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 0.9.0
* platform information (OS, etc) Linux

**Comment by raver119** [comment]
That's more of design issue... Usually people care about pipeline persistence. But that clearly should be up to user. Maybe we'll just print out warning instead of exception.

**Comment by raver119** [comment]
Behavior changed.

**Comment by firasdib** [comment]
How was it changed?
