### ISSUE TITLE
Cnn Protein secondary structure prediction

### ISSUE THREAD

**Issue by dionisole** [deeplearning4j/deeplearning4j#3801]
Greetings,

I want to train a cnn with a csv file for protein secondary structure prediction. I have a csv file with the 20 msa input parameters and the last column is the amino label. How i can set conv layers sizes and what Record readers should i use???

**Comment by AlexDBlack** [comment]
Closing this: looks like this was resolved (based on the code in this issue): https://github.com/deeplearning4j/nd4j/issues/2041
