### ISSUE TITLE
Add option to normalize word2vec vectors as they are created

### ISSUE THREAD

**Issue by firasdib** [deeplearning4j/deeplearning4j#3802]
It would be useful to be able to create a word2vec model and save it already normalized, instead of having to call `getWordVectorMatrixNormalized` during runtime which is quite expensive.

**Comment by raver119** [comment]
You don't need anything special for that, it's just linear algebra and 2 calls on syn0 matrix.

p.s. it's happening automatically, if you use BasicModelUtils (which is default) and calling for any of  wordsNearest() methods.

**Comment by firasdib** [comment]
Can you please show how?

I currently do the following:

```java
final Word2Vec w2v = new Word2Vec.Builder()
  // ...
  .build();

w2v.fit();

WordVectorSerializer.writeWord2VecModel(w2v, outputFile);
```

Where would your proposed solution fit in?

**Comment by raver119** [comment]
How do what?

I've already told one message above: if you'll call w2v.wordsNearest("someword", 10); after fit() call - matrix will be normalized internally, so your saved copy will be normalized too.

**Comment by raver119** [comment]
And manual normalization is 1 line of code:

https://github.com/deeplearning4j/deeplearning4j/blob/6fe354cbe9305b095690c4b1939ef44d39ce5c57/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/reader/impl/BasicModelUtils.java#L237

**Comment by firasdib** [comment]
I'm not using `wordsNearest` though. I'm looking to save my model normalized.

**Comment by firasdib** [comment]
Wait, maybe I'm not following here...

Are you telling me that if I call `wordsNearest` after `fit`, regardless of the word I look for, the entire in-memory matrix will be normalized and thus that will persist when I save it?

If so, thats good to know, but a super ugly solution.
