### ISSUE TITLE
Sentences beginning with Space characters leads to unexpected behavior

### ISSUE THREAD

**Issue by rpatra** [deeplearning4j/deeplearning4j#3807]
#### Issue Description
The expected behavior is that "space" characters should be ignored while training. For example, the following document leads to error:
LabelledDocument(id=null, content= 8353 7855 5131 11511 3682 10692 3682 7895 3682 8181 1191 2327 11073 ........ 1030, labels=[bio])

However, when I got rid of the extra "space" character as the beginning of the content, then the training goes on as expected.

#### Version Information

* Deeplearning4j version: 0.8.0
* platform information: MacOS

**Comment by rpatra** [comment]
Code that generated this issue:
https://gist.github.com/rpatra/7447fdf38d5682cdde92ef0f30bd6680

**Comment by raver119** [comment]
Add example of "bad sentence" too please.

**Comment by rpatra** [comment]
if I generate sentence like this:
                       String oneWalk="";
                        for(PgxVertex<Long> vertex: walk){
                                oneWalk= oneWalk+" "+vertex.getId();
                        }
                        LabelledDocument document = new LabelledDocument();
                        document.setContent(oneWalk);
                        document.addLabel("mrkt");
                        documents.add(document);

Then, the issue occurs. It seems its not an issue with space, since trim() does not solve it.
However, when I do something like this, then it works:
                for(VertexSequence<Long> walk: randWalks_bio){
                        String oneWalk="bi";
                        for(PgxVertex<Long> vertex: walk){
                                oneWalk= oneWalk+" "+vertex.getId();
                        }
                        LabelledDocument document = new LabelledDocument();
                        document.setContent(oneWalk.trim());
                        document.addLabel("bio");
                        documents.add(document);
                }

**Comment by rpatra** [comment]
Document: LabelledDocument(id=null, content=bi 1365 7416 1365 6263 1365 7662 1365 10192 1365 8490 1365 9862 1365 3855 1365 4318 3262 2220 2192 9965, labels=[bio])
This works
Document: LabelledDocument(id=null, content=1365 7416 1365 6263 1365 7662 1365 10192 1365 8490 1365 9862 1365 3855 1365 4318 3262 2220 2192 9965, labels=[bio]) This does not

**Comment by raver119** [comment]
So, your input is always numeric. Thanks, i'll check it out.

**Comment by rpatra** [comment]
Yes, if its always numeric, then this error occurs: org.nd4j.linalg.exception.ND4JIllegalStateException: Text passed for inference has no matches in model vocabulary.
And after checking the cache.numWords(), its 6, which is number of labels. So, the numeric words are not treated as words probably.

**Comment by raver119** [comment]
Aha, that explains everything.

Here's part of code you're using:
```
                TokenizerFactory t = new DefaultTokenizerFactory();
                t.setTokenPreProcessor(new CommonPreprocessor());
```

I don't know why you've used CommonPreprocessor, if your tokens are all numberic. That preprocessor removes all digits from strings.

p.s. Copy-paste is bad approach for machine learning :)

**Comment by rpatra** [comment]
Thanks for pointing it out!

I could not find details regarding the preprocessor in the javadocs (https://deeplearning4j.org/doc/) which led me to use this one as its used mostly everywhere.

It more of an implementation-level details for the preprocessor than machine-learning stuff ;)


--
Rhicheek

________________________________
