### ISSUE TITLE
Shift output layer gradient calculation conditional from MultiLayer to OutputLayer

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#382]
OutpuLayer class already has a gradient method that includes conditionals on loss functions. Need to review the current calculations under that method and switch the current conditional out of doBackWard under MultiLayer into OutputLayer.

Code to move: 
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java#L1076-L1084

**Comment by agibsonccc** [comment]
That makes no sense. The gradient here is specific to the output layer. Not to mention the multi layer network is a holder not an actual model itself.

**Comment by agibsonccc** [comment]
This is a better declaration of the problem:
https://github.com/deeplearning4j/deeplearning4j/issues/380

**Comment by agibsonccc** [comment]
This has been done.
