### ISSUE TITLE
UI: J7FileStatsStorage is slow

### ISSUE THREAD

**Issue by papperwing** [deeplearning4j/deeplearning4j#3825]
#### Issue Description
Loading of data from storage takes a lot of time. In one try (one in images) it took 90s to load data and also it ended with exception on server side.

Server log: https://gist.github.com/papperwing/e854648ca51173dbffb62cd2e29cd474

FireFox log: https://gist.github.com/papperwing/34d87eac0d52caf2cb3d5b3f653e47c4

PrintScreens with htop and state

![snimek z 2017-08-08 15-43-10](https://user-images.githubusercontent.com/5627436/29074815-eb216866-7c50-11e7-9b71-2a2d92afaf2d.png)
![snimek z 2017-08-08 15-43-32](https://user-images.githubusercontent.com/5627436/29074816-eb3fd6d4-7c50-11e7-97ac-72d91e8c198a.png)
![snimek z 2017-08-08 15-44-44](https://user-images.githubusercontent.com/5627436/29074819-eb61c640-7c50-11e7-93de-9f6b1f871853.png)

Machine spec with lshw: https://gist.github.com/papperwing/3f629c4f9e2bbbc70fc2a49b2db937de

#### Version Information

Please indicate relevant versions, including, if relevant:
* java: oracle 1.8.0_144
* os: linux
* dl4j: 0.9.0
* firefox: 47.0

**Comment by papperwing** [comment]
Storage_file: https://drive.google.com/file/d/0B5lEbcbm2laiQ280RHh1bno2a00/view?usp=sharing
Code: https://github.com/papperwing/image-net/blob/master/modules/visualizer/src/main/java/cz/muni/fi/imagenet/visualizer/Visualizer.java

**Comment by AlexDBlack** [comment]
Looks like this is specific to J7FileStatsStorage - i.e., the SQLite storage backend.

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/3907
