### ISSUE TITLE
Unable to set UNK in word2vec model

### ISSUE THREAD

**Issue by firasdib** [deeplearning4j/deeplearning4j#3826]
#### Issue Description

I load my model from file and want to set the UNK word to something besides the default, but seems to be ignored.

```java
        model = WordVectorSerializer.readWord2VecModel(...);

        model.setUNK("foo");

        System.out.println(model.getUNK());
```

Still prints "UNK" instead of "foo".

Ping @raver119 

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 0.9.0
* platform information (OS, etc) osx/linux

**Comment by raver119** [comment]
Well, it's possible to change it, but it doesn't make too much sense tbh. Your UNK word during training becomes average of all unknown words. And simple replacement won't give you equivalent.

But if you want that - change it via configuration.

**Comment by raver119** [comment]
Fixed.

**Comment by firasdib** [comment]
What if you train a different UNK word from the default one used in DL4J? Thats my use case.

**Comment by raver119** [comment]
I've already answered that question, and applied fix as well.

**Comment by constantinembufung** [comment]
count = [['UNK', -1]]
