### ISSUE TITLE
The class LucenInvertedIndex is missing

### ISSUE THREAD

**Issue by arifainchtein** [deeplearning4j/deeplearning4j#3840]
Hello,
I am trying to compile the BagOfWordsVectorizerTest example but one of the dependencies is missing.  Specifically:

org.deeplearning4j.text.invertedindex.LuceneInvertedIndex;

it seems that this class existed in 0.0.0.4-RC1 but it is no longer in the 0.9.0 release.

Is there an updated example of BagOfWordsVectorizerTest which runs on th latest release?  Or where can I find the class LuceneInvertedIndex?

thanks

**Comment by agibsonccc** [comment]
We aren't supporting lucene anymore.

**Comment by arifainchtein** [comment]
ok, thanks for the response. also it seems that the method getLabelsSource is not visible.  Is there a new version of this example that compiles to the current code?
thanks
