### ISSUE TITLE
OSX doesn't need ldconfig in build-dl4j-stack.sh

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#3841]
#### Issue Description
https://github.com/deeplearning4j/deeplearning4j/blob/master/build-dl4j-stack.sh#L93

@firasdib ran in to issues with building from source on osx. It seems like we can remove this?
Please describe our issue, along with:
- expected behavior
- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by huitseeker** [comment]
Fixing. In the meantime a workaround is to specify a chip (cpu | gpu) explicitly by using the `-c` flag
