### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by luizcruzjf** [deeplearning4j/deeplearning4j#3845]
Dead link in page.
https://deeplearning4j.org/glossary.html#VGG

For link 
https://github.com/deeplearning4j/ImageNet-Example/tree/master/src/main/java/imagenet/Models

**Comment by tomthetrainer** [comment]
Thanks for the report, patched this pointed the link at the modelzoo 
https://github.com/deeplearning4j/deeplearning4j/tree/master/deeplearning4j-zoo/src/main/java/org/deeplearning4j/zoo/model
