### ISSUE TITLE
slow and memory issues when run a larger model on standalone spark cluster

### ISSUE THREAD

**Issue by jasstionzyf** [deeplearning4j/deeplearning4j#3848]
#### Issue Description

- I run a dl4j MultiLayerNetwork on spark standalone cluster with one big machine (32 core and 126GB memory) for test,
 [program code](https://gist.github.com/jasstionzyf/400b372d3dda9a5fe730e76c96c1f722)
 [config](https://gist.github.com/jasstionzyf/83368dbc50d3521712c38fc52a7d3f15)
 ### the standalone spark  cluster config:
    one master + three workers (each worker with 15GB memory)
i hope the program can run fast and normal without any memory issues,  for i config the executor only one task , and also the off-heap memory to 20GB through spark.executor.extraJavaOptions

- encountered behavior
   however,   the program stay slower then i expected,  after i check the machine status, the worker machines can not keep busy for the driver program slow,  when you check the driver program machine, you can see several cpu of it keep 100%,  it very like java full GC,  but actually i confirm it is not, also  according to the spark logs, it seems big broadcast values transfer between driver to executors is big program once the trained network is large (from my example,  the task result from executor task can read to 700M )
   also the program can run some times without any crash though slow above,  but after few hours,  the executor just crash for the [OutOfMemoryError ](https://gist.github.com/jasstionzyf/8ce70d3eadeb56d1f8f57b54f86bca4b)
   

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 0.8.1-snapshot (should before 2017-08-09)
* platform information (OS, etc) centos

**Comment by jasstionzyf** [comment]
later, i make a test (run mnist program on spark cluster) to confirm my spark cluster is normal,
the mnist program normal (not so slow and no memory issues), 
also later i change my code to reduce network size, code [here](https://gist.github.com/jasstionzyf/a523158c770f0eb9f5a407b63f729c9e)
config [here](https://gist.github.com/jasstionzyf/bc705df54ad20b88ef1fec45dd2f1c4c)
then i run the program on same spark cluster,  it runs also normal without any memory issues and very slow issues even i set the executors task number to 8 (by spark.executor.cores=8).

so from above cases, i have few thoughts:

- when network size larger, why run some times later throw OutOfMemoryError ? actually i think 20GB is enough one task to train for my network szie ?   but with little network size (my updated program)  , it run very well ,  it seems multi tasks reuse only one workspaces, also seems the workspaces can release quickly,   from the machine status, the memory alwayes keep a low memory usage.

- about the spark driver program slow,   seems you guys has finished better solution,
  for my observe , i think currently spark driver slow mainly for two reasons:
  one is broadcast values between  driver and executors, 
  another one ：currently does dl4j  wait all the task finished and fetch all the task results, the average to update parameters, if it is fast to use not synchronize update network parameters for the driver program

**Comment by jasstionzyf** [comment]
when i use spark to train a vgg16 module while frozen belown block4_pool layer,   the spark driver problem really slow as same as previously large multi networks

**Comment by raver119** [comment]
Closed due to inactivity + now we have gradients sharing + workspaces, and that solves lots of perf-related problems.
