### ISSUE TITLE
Can I initialize word2vec with google news model and train it further with local corpus

### ISSUE THREAD

**Issue by rangansen** [deeplearning4j/deeplearning4j#3850]
My intent is to initialize word2vec with google news model and train it further with local corpus, so that the model can benefit from the richness of the google model/dataset, and also learn the additional context of the local corpus. But I am not able to get it working.

Using method Word2Vec.Builder.useExistingWordVectors  does not seem to have any effect as the parameter is ignored
****************************
@Override
        protected Builder useExistingWordVectors(@NonNull WordVectors vec) {
            return this;
        }
**********************

Also, if I load the existing model directly as Word2Vec, using WordVectorSerializer. readWord2VecModel, set the training parameters (iterations, learning rate, sentenceIterators with for the local corpus etc) and train it again (fit) , it seems that the none of the newer words in the local corpus is included in the vocab or the lookuptable.

What should be the right way to do it? Can someone please help?

**Comment by raver119** [comment]
Yes it's possible. Sorry for the delay.
