### ISSUE TITLE
Files left in temp folder after serializing model with normalizer

### ISSUE THREAD

**Issue by ajohnsonz** [deeplearning4j/deeplearning4j#3855]
#### Issue Description

When calling ModelSerializer.addNormalizerToModel(...) a temp file is created, and a 'deleteOnExit' hook is registered. However, if the JVM is extremely long-running these files build up, or if the JVM is force-terminated (eg kill -9) then these files are never deleted.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/4326
