### ISSUE TITLE
`JointParallelDataSetIterator` sometimes only uses one thread

### ISSUE THREAD

**Issue by firasdib** [deeplearning4j/deeplearning4j#3866]
#### Issue Description

I'm not entirely sure how to reproduce this or why it happens, but sometimes it seems like only one thread is being used. I believe this is when I try to reset the iterator to start all over again, and sometimes it ends up in a weird state. It usually ends up working again after its been reset.

Here's the reset code
```java
    @Override
    public void reset() {
        // Reset the iterators
        super.reset();

        // Reset these variables to the original values
        states = new MultiBoolean(numProducers, true);
        resetTracker = new MultiBoolean(numProducers, false, true);
        allDepleted.set(false);
        counter.set(0L);
    }
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 0.9.2-SNAPSHOT
* platform information (OS, etc) Linux

**Comment by raver119** [comment]
As i remember, this issue was solved in gitter.
