### ISSUE TITLE
Add warnings for cuda backend + no CuDNN

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#3868]
Idea: If user is...
(a) using CUDA backend, and
(b) using a layer that supports CuDNN (conv, subsampling, LRN, LSTM etc)

Warn the user that they would get much better performance by using CuDNN. And, provide a link on how to set it up.

This should be logged only once per JVM, regardless of how many networks/layer types are running without CuDNN.

**Comment by saudet** [comment]
What if we just tell users to include `deeplearning4j-cuda` when the want CUDA, and put that link in the warning message? It already fall backs to non-cuDNN kernels after displaying the warning, and we can leave `nd4j-native` in the class path too, so no need to switch the backend.

**Comment by AlexDBlack** [comment]
A warning message saying "use deeplearning4j-cuda" (plus maybe a link) is basically what I had in mind here.

As for recommending deeplearning4j-cuda a best practice, instead of recommending nd4j-cuda? Hm, maybe. We *can* leave nd4j-native on the classpath too, but that means an extra what, 300mb download (native libraries, all platforms) + extra JAR bloat by default. Maybe profiles for the examples might be better.
