### ISSUE TITLE
Reshape layers not imported from Keras

### ISSUE THREAD

**Issue by yquemener** [deeplearning4j/deeplearning4j#3872]
#### Issue Description

Creating a Reshape layer in Keras:
`model.add(Reshape((13, 13, 5, 25)))`
and saving it with 
`model.to_json()`
and then loading it in DL4J using `KerasModelImport.importKerasSequentialModelAndWeights`
leads to the following error:

>Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.UnsupportedKerasConfigurationException: Unsupported keras layer type Reshape. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
>	at org.deeplearning4j.nn.modelimport.keras.KerasLayer.getKerasLayerFromConfig(KerasLayer.java:261)
>	at org.deeplearning4j.nn.modelimport.keras.KerasModel.helperPrepareLayers(KerasModel.java:191)
>	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:99)
>	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:56)
>	at org.deeplearning4j.nn.modelimport.keras.KerasModel$ModelBuilder.buildSequential(KerasModel.java:646)
>	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:235)

Expected behavior:
it should import correctly and generate (I guess?) a kind of reshape layer. 

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version : 0.9.1 (release)
* Ubuntu 17.04, Linux 4.10 64 bits
* CUDA 8.0
* NVIDIA nvidia_375 on a GeForce GTX 1050 Ti Mobile

**Comment by maxpumperla** [comment]
this should work with #3876
