### ISSUE TITLE
UI Not reporting anything

### ISSUE THREAD

**Issue by iihusseinali** [deeplearning4j/deeplearning4j#3877]
#### Issue Description

Please describe our issue, along with:
-  Expected behavior: display network performance.

- Encountered behavior: Nothing is being displayed in the UI. No model information, no data being displayed. 

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.9.1
* platform information (OS, etc): PC
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

#### Contributing

I am happy to contribute code.

**Comment by AlexDBlack** [comment]
This is impossible to reproduce or debug based on the provided information.
Can you give us something else to work with - ideally, something we can run locally to reproduce the issue?

**Comment by iihusseinali** [comment]
How about this for a start?

https://gist.github.com/iihusseinali/fb0c405630c66585659775a9e647473e

What else can I provide you to help you look into it?

**Comment by AlexDBlack** [comment]
No UI content was due to two sequential setListener calls, not an issue/bug with the UI itself.
