### ISSUE TITLE
Unsupported keras layer type Conv2D

### ISSUE THREAD

**Issue by skeydan** [deeplearning4j/deeplearning4j#3886]
Could you please add this?
Thanks!

**Comment by maxpumperla** [comment]
Hi @skeydan this is a keras2 layer. We currently only support keras <= 1.2.2, but the open PR #3831 will address this. Hope to merge it early next week.

**Comment by skeydan** [comment]
cool, thanks! Early next week would be great.

**Comment by maxpumperla** [comment]
@skeydan done now, checkout master

**Comment by skeydan** [comment]
Sorry for asking this - when do you plan to release this? Building locally sounds like a lot of work...
Or is there a way to get a jarfile for this updated version somehow?
Thank you very much!!!

**Comment by AlexDBlack** [comment]
@skeydan if you don't want to build from source (we don't recommend it) you should be able to use snashots... instructions here: https://github.com/deeplearning4j/deeplearning4j/issues/3227

**Comment by skeydan** [comment]
Works like a charm - thank you!!!
