### ISSUE TITLE
ListBuilder.layer(...) shouldn't need the index.

### ISSUE THREAD

**Issue by stolsvik** [deeplearning4j/deeplearning4j#3888]
Currently, when you use the ListBuilder, you need to specify the index for each layer. This is rather error prone when you copy-paste a layer, add a layer, reorganize layers etc.

Since the ListBuilder has full knowledge about the currently added layers, it could just find the current max number, and add the layer "below" that. This can thus be retrofitted straight in, just make an additional layer method w/o the index, have that method find the current max-num and invoke the existing with that number+1.

This would make the fluent API a bit more fluent:

This:

                 .list()
                .layer(0, new DenseLayer.Builder()
                        .nOut(1000)
                        .build())
                .layer(1, new DenseLayer.Builder()
                        .nOut(500)
                        .build())
                .layer(2, new DenseLayer.Builder()
                        .nOut(1000)
                        .build())
                .layer(3, new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD) //create hidden layer
                        .activation(Activation.SOFTMAX)
                        .nOut(numOutputs)
                        .build())
                .setInputType(InputType.feedForward(numInputs))

would become:

                .list()
                .layer(new DenseLayer.Builder()
                        .nOut(1000)
                        .build())
                .layer(new DenseLayer.Builder()
                        .nOut(500)
                        .build())
                .layer(new DenseLayer.Builder()
                        .nOut(1000)
                        .build())
                .layer(new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD) //create hidden layer
                        .activation(Activation.SOFTMAX)
                        .nOut(numOutputs)
                        .build())
                .setInputType(InputType.feedForward(numInputs))

.. without the problem of having to re-index all the indices if you want to e.g. add a new DropoutLayer at the top..

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/3900
