### ISSUE TITLE
ListBuilder should override the setInputType(..) method

### ISSUE THREAD

**Issue by stolsvik** [deeplearning4j/deeplearning4j#3889]
Currently, the setInputType(..) method exists on the MultiLayerConfiguration.Builder. The ListBuilder inherits this. The problem is that setInputType() (obviously) returns MultiLayerConfiguration.Builder, which makes it impossible to write a config as such:

                .list()
                .setInputType(InputType.feedForward(numInputs))
                .layer(0, new DenseLayer.Builder()
                        .nOut(1000)
                        .build())
                .layer(1, new DenseLayer.Builder()
                        .nOut(500)
                        .build())
                .layer(2, new DenseLayer.Builder()
                        .nOut(1000)
                        .build())
                .layer(3, new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD) //create hidden layer
                        .activation(Activation.SOFTMAX)
                        .nOut(numOutputs)
                        .build())
Notice how this can be "linearly" read as the entire layer-stack, with the inputs specified at top, and the output at bottom. (Combined with #3888, this would be pretty fluent).

You currently have to put the setInputType below the last layer, since you "loose" the ListBuilder type after that.

If the setInputType() was overridden on the ListBuilder class, but narrowing (specializing) the return type to ListBuilder, the above config would be valid.

The narrowing of return type was allowed from Java 5. https://stackoverflow.com/a/20514762/39334

**ADDED: I just realized that it would possibly be better if the method was named or aliased to inputType(..) instead of setInputType(..)**. Also, shortcuts for the most used InputTypes could be added: feedForwardInputs(28*28)...

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/3900
