### ISSUE TITLE
Go through examples, removing usage of @deprecated functionality

### ISSUE THREAD

**Issue by stolsvik** [deeplearning4j/deeplearning4j#3890]
Currently, when you compile the examples project, you get 69 warnings, of which 67 are @deprecation warnings. Most of these evidently relate to keras.trainedmodels.TrainedModelHelper and TrainedModels.

However, there are also some usages of deprecated methods in NeuralNetConfiguration.Builder. Notably e.g. .momentum(..) which is Nesterovs-specific.

Since other examples point out that you should do new Nesterovs(momentum) for these cases, new users (like me) get a bit uncertain of what is supposed to be the main way to use the API.

Go through examples, removing @deprecation warnings.

**Comment by RobAltena** [comment]
Moving this one to the examples:
https://github.com/deeplearning4j/dl4j-examples/issues/524
