### ISSUE TITLE
Decide whether enum-based Updater.NESTEROVS or new Nesterovs() is preferred way

### ISSUE THREAD

**Issue by stolsvik** [deeplearning4j/deeplearning4j#3891]
In the examples, it is currently not easy to understand whether you should use the enum-based updater-configuration, or the concrete class-version.

That is, either
  .updater(Updater.NESTEROVS)
or
  .updater(new Nesterovs())

The point is that since builder.momentum(..) is deprecated, you should use the new Nesterovs(momentum).

**Comment by AlexDBlack** [comment]
My thinking  here: Enumeration for all defaults (what most users will use), ```.updater(new X(<args>))``` to customize. No-arg ```new X()``` approach and enumeration are equivalent.

**Comment by AlexDBlack** [comment]
Updater enumeration has been deprecated: https://github.com/deeplearning4j/deeplearning4j/blob/80260f8c86a47a2821b771a23465595d310c8a46/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/NeuralNetConfiguration.java#L941
