### ISSUE TITLE
epochStart() - Way to notify the model that a new learning epoch starts

### ISSUE THREAD

**Issue by stolsvik** [deeplearning4j/deeplearning4j#3894]
Since epochs aren't really a part of the learning (you only get that implicit by the fit(iterator)), a method whereby the user  could notify the model that an epoch had started could maybe be of use.  E.g. model.epochStart().

This was brought up in #3503.

This could also be of use for things like ScoreIterationListener, as it would then know the difference between a mini batch, and an epoch.

The model should keep a counter of the epochs, and pass that to any  listeners. Note that when epoch 0 was started, this is before any learning had taken place. I personally find it nice to know how the score and accuracy etc are right after weight inits etc.

This method would obviously be invoked automatically when using the  fit(iterator), while if you used fit(dataset), you'd have to signal to  the model yourself when whatever you consider an epoch starts.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/3957
