### ISSUE TITLE
Layer.Builder.dropout(..) needs better javadoc

### ISSUE THREAD

**Issue by stolsvik** [deeplearning4j/deeplearning4j#3896]
The JavaDoc should be specific where the dropout applies: Is it "above" or "below" this layer? Compared to if you used an actual DropoutLayer. Also, the name of the dropout parameter should be "retainFraction" or similer wording that implies "the number of neurons retained", since this is pretty important to get right. (it is currently "dropout", arguably easy to misunderstand for the exact opposite).

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/3900
