### ISSUE TITLE
Unnecessary invocation of builder.regularization(true) when employing regularization

### ISSUE THREAD

**Issue by stolsvik** [deeplearning4j/deeplearning4j#3897]
When using the NeuralNetConfigurationBuilder.Builder, the examples show that you must both set regularization(true), then l1(..) or l2(..) or dropout(..) (others?).

This is hard to understand - does this toggle some special mode? If I do not call that, won't the l2(..) call do anything?

If it is important for l1(..) and the other regularization methods to have some state in the config toggled to true, could they not set it themselves?

The fluency of the API is somewhat hindered by this - you need to read those two methods in conjunction with each other. The method regularization() would make sense if it return a new Regularization.Builder() instance or somesuch, but it doesn't.

I assume the call to regularization(true) does not do *anything* by itself, i.e. without also calling l1(..) or similar? If it does, then it should be javadocced better.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/3900
