### ISSUE TITLE
Reflections take too much time

### ISSUE THREAD

**Issue by wmeddie** [deeplearning4j/deeplearning4j#3899]
#### Issue Description

There are a few parts in DL4J that do reflections to find sub-types of interfaces (for custom UI modules, custom layers, etc.).  In large applications and "App Servers" the sheer number of classes cause this to take an exuberant amount of time (on the order of days).  

We should centralize all classpath scanning in a single class and restrict it to org.nd4j, org.datavec, and org.deeplearning4j by default. For custom layers we should allow people to specify package prefixes they would like to scan in a property file or via the central scanning class.

**Comment by AlexDBlack** [comment]
Centralizing reflections, where we need it, is a great idea - we should do that.

As for custom functionality: there are a number of places where this is needed
- JSON
    - DL4J: custom layers etc (register subtypes)
    - Arbiter, for generics (FixedValue<Whatever> -> JSON)
- Custom UI modules
- Version check


Let's look at these separately.

1. DL4J custom layers:

Lets move from wrapper class to fully-qualified class names. ```@class``` tag. That works fine without reflections for subtypes.
Only reason it hasn't been done already: (a) legacy reasons, and (b) maintaining backward compatibility will take some work (it's doable, but a bit complex)
Result: No reflections for any custom functionality there, except perhaps when required for legacy custom layers (do that on demand when required, if model loading fails without it).

Allowing users to specify package prefixes for scanning would work, but it's bad for users (I really don't like it for usability/support).


2. Custom UI modules
Disabled by default, let's deprecate the reflection approach and encourage people to use service loader instead.
Result: No need to use reflections here.


3. Version check
Only need to scan classpath for resources matching /ai/skymind/*-git.properties
Three ideas here:
(a) if we can walk the directory /ai/skymind/ (in the jar) and list files, then we don't need full classpath scanning
(b) as a somewhat ugly alternative: hardcode a list of paths in VersionCheck (one for each module in ND4J, DL4J, etc)
(c) work out a way to write out a list of paths (maven plugin?) per parent module - so we just need to load /ai/skymind/versioncheck-dl4j.txt, /ai/skymind/versioncheck-nd4j.txt etc (each would have full paths, as per (b)). Just need to hard-code those txt files from parent pom


4. Arbiter generics
https://github.com/deeplearning4j/Arbiter/blob/master/arbiter-core/src/main/java/org/deeplearning4j/arbiter/optimize/serde/jackson/JsonMapper.java

Let's remove the use of JacksonReflectionLoader (and, hence Reflections library) entirely.
Replacement: best idea I have is to:
(a) whenever we serialize an object, walk the object graph to determine types of all nested objects
(b) reinitialize the JSON mapper if/when required, to handle previously unknown types
(c) use ```@class``` field everywhere (I think we already do?) so we don't need to scan for deserialization purposes

**Comment by AlexDBlack** [comment]
As noted in gitter - I'll look at the DL4J custom functionality side of this.

**Comment by AlexDBlack** [comment]
Reflections library has been removed from DL4J entirely - addressed here: https://github.com/deeplearning4j/deeplearning4j/pull/4956 and https://github.com/deeplearning4j/deeplearning4j/pull/4950
