### ISSUE TITLE
Binary javacpp openblas causes crash in OpenSuse Linux

### ISSUE THREAD

**Issue by thhart** [deeplearning4j/deeplearning4j#3903]
I had some trouble operating dl4j 0.9.1 with the default maven dependency set as provided by dl4j-examples deployed to a production system based on OpenSuse Leap 42.2. Java crashed heavy with core dumps.
It turned out that the native openblas implementation is not working well in different Linux. However the kernel (4.4.x) and gcc versions are not much different to our developing system Ubuntu  where it runs well. My solution was to strip out the libopenblas.so from the openblas-0.2.19-1.3-linux-x86_64.jar and rely on the OS provided openblas libraries. Usually we have no problems with native library sharing in different Linux flavors but obviously openblas is a heavy in this.

I am aware it is actually not a bug, but wanted to post here if others come around. Also I think it is worth to remark this as a probable problems. There might be two solutions thinkable:

1.  Remove the OpenBlas binary dependency and provide "only" the JNI bridge and request to install the OS openblas always.
2. Use a Java implementation by default, this might not be the fastest but is good for evaluation. For performance optimization someone could later introduce native libs. Unfortunately I am not aware of such a library yet.

PS: Sorry for posting here, I think it is a distribution related thing, not sure if dl4j-examples better fit.

**Comment by saudet** [comment]
This issue should be moved to https://github.com/bytedeco/javacpp-presets/issues so please repost over there if you would like further feedback.

I'll be updating the presets to OpenBLAS 0.2.20 soon. Maybe it's something they've already fixed in that version. Could you check again at that point?

**Comment by saudet** [comment]
SNAPSHOT binaries are now available. Could you try them out by including the following dependencies to you pom.xml file? Thanks!
```xml
<dependency>
    <groupId>org.bytedeco.javacpp-presets</groupId>
    <artifactId>openblas</artifactId>
    <version>0.2.20-1.3.4-SNAPSHOT</version>
</dependency>
<dependency>
    <groupId>org.bytedeco.javacpp-presets</groupId>
    <artifactId>openblas</artifactId>
    <version>0.2.20-1.3.4-SNAPSHOT</version>
    <classifier>linux-x86_64</classifier>
</dependency>
```
