### ISSUE TITLE
GradientSharingTrainingMaster should implement setListeners

### ISSUE THREAD

**Issue by deichbrise** [deeplearning4j/deeplearning4j#3908]
#### Issue Description

GradientSharingTrainingMaster should handle IterationListeners. Currently setListeners in GradientSharingTrainingMaster is not implemented but declared as optional.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.9.1
* platform information (OS, etc): All

**Comment by alexanderst** [comment]
Was already fixed earlier.
