### ISSUE TITLE
Missing documentation for TransferLearningAPI

### ISSUE THREAD

**Issue by papperwing** [deeplearning4j/deeplearning4j#3909]
In documentation is missing info, how in existing model it is possible to edit parameters of existing layer like dropout or l1, l2 regularization and other setting of layers with persisting learned weights.

**Comment by papperwing** [comment]
Reason for this is, that I found only global setting of l1 l2 which doesn't suite well for every layer in my AlexNet taken from Zoo.

**Comment by tomthetrainer** [comment]
Have you seen this content? 
https://deeplearning4j.org/transfer-learning

**Comment by papperwing** [comment]
Yeah thats exactly place where I was searching and I didnt found how to do the stuff I mentioned. Also I was looking into VGG16 examples.

**Comment by tomthetrainer** [comment]
We may need some additional docs then,

@eraly can you answer the above questions

**Comment by eraly** [comment]
You have full control over any of the new layers you add on with the transfer learning API.

i.e. 
```
new TransferLearning.GraphBuilder(?)
            ...
            .addLayer("fc3",new DenseLayer.Builder().l1(?).l2(?).dropOut(?)...build(),"fc2") 
            ...

```
If you want to modify the l1,l2,dropout on only certain existing layers but not on others there currently isn't a way unfortunately.

A hack would be to write out the json modify it by hand and read it back in with the weights.

**Comment by eraly** [comment]
Noted as an enhancement request. Thanks.
