### ISSUE TITLE
Support more basic weight initialisers

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/deeplearning4j#3916]
Though this might not be high priority, supporting more weight initialisers should be relatively simple to do. I'll refer to https://keras.io/initializers/ for naming conventions. This ticket collects weight init enhancements, for more complicated inits we could split it up.

Low hanging:
- [x] Ones
- [x] Constant
- [x] Identity

a bit less trivial:
- [x] Normal
- [x] Orthogonal
- [x] Lecun uniform
- [x] Variance scaling (seems to be the new default initialiser in keras).

**Comment by maxpumperla** [comment]
see here as well: https://github.com/deeplearning4j/nd4j/issues/2074

**Comment by raver119** [comment]
Normal - what it means in this case? Just normal distribution? Keras has multiple initializers with "normal" word used.

**Comment by maxpumperla** [comment]
@raver119 normal alias RandomNormal is really just a random normal variable. I guess we have that already, but it is not mapped in model import.

**Comment by maxpumperla** [comment]
I've just listed everything we're missing, simply check the stuff we already have in nd4j

**Comment by raver119** [comment]
Yes, such distributions like normal, uniform, are covered with both native ops, and corresponding Distribution implementations in nd4j. 

For normal - that'll be GaussianDistribution native op, and NormalDistribution distribution impl, which uses mentioned native op underneath

https://github.com/deeplearning4j/nd4j/blob/aafbd0101b1a10a0d4dae1a2671895410a1708b2/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/rng/distribution/impl/NormalDistribution.java

**Comment by raver119** [comment]
***lecun_normal, he_uniform, glorot_uniform*** etc - all these distributions are using the same normal/uniform distributions, just either stddev or limits differ. Nd4j native ops allow you to do that without any problems

**Comment by raver119** [comment]
Same for Variance scaling. It's built on top of truncated normal, which we've added recently.

**Comment by raver119** [comment]
Just one thing here: our RNG operations assume non-negative element-wise stride, so might fail on weird views. If that suddenly becomes problem - let me know please.

**Comment by raver119** [comment]
For reference: Orthogonal init: https://github.com/fchollet/keras/blob/b200b7d19c6b00a99bd890b925c1c0d887c1b303/keras/initializers.py#L223

**Comment by AlexDBlack** [comment]
Ones and identity added here: https://github.com/deeplearning4j/deeplearning4j/pull/3984

Not sure on how we go about implementing the constant init. TBH I'd rather not pollute the API with something like a .weightInitConstant(double) method that 99.9% of users will never use.
For madel import: I'm half tempted to just add a dummy distribution that gives a constant value out, and just map it to WeightInit.DISTRIBUTION + .dist(ConstantDistribution(x)).

**Comment by maxpumperla** [comment]
@AlexDBlack I'd be absolutely happy with the dummy dist. I've never used `Constant` myself ever, but if it's simple to add for import, let's do it.

**Comment by AlexDBlack** [comment]
@maxpumperla Dummy distribution added here: https://github.com/deeplearning4j/nd4j/pull/2124

**Comment by maxpumperla** [comment]
#4062
