### ISSUE TITLE
Support 3D pooling layers

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/deeplearning4j#3918]
#### Issue Description

Add max and avg 3D pooling layers. /cc @raver119

**Comment by maxpumperla** [comment]
yep, I'll add all the 3D convenience layers once the basic conv3d layer is merged, thanks @raver119

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/layers/Subsampling3DLayer.java
