### ISSUE TITLE
Evaluation class logic error

### ISSUE THREAD

**Issue by EronWright** [deeplearning4j/deeplearning4j#392]
The class incorrectly counts the true negatives, leading to understated accuracy.  That is probably good news!

For a given row, when the guess is correct then the true positive should be incremented for the guessed class, and the true negative should be incremented for every other class.   Yet, the logic relies on the confusion matrix's list of known classes to perform the latter.  The classes are not known upfront but are discovered as the dataset is evaluated.  Therefore, the true negative will not be reliably incremented until all classes are seen at least once.

**Comment by agibsonccc** [comment]
I'll at least start the discussion here. So the way it works right now is we stream in the examples.

What I'm imagining is we create a new constructor that takes in the classes (thus getting rid of the empty constructor) which should fix the problem.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/472

**Comment by Gaduo** [comment]
https://www.youtube.com/watch?v=FAr2GmWNbT0
