### ISSUE TITLE
Support deconvolution 2D layers

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/deeplearning4j#3920]
#### Issue Description

Support deconvolution 2D layers

**Comment by AlexDBlack** [comment]
a.ka. deconvolution, fractionally strided, transpose convolution.
Keras implements this as Conv2DTranspose - https://keras.io/layers/convolutional/#conv2dtranspose

https://arxiv.org/abs/1603.07285v1
http://www.matthewzeiler.com/pubs/cvpr2010/cvpr2010.pdf

**Comment by raver119** [comment]
Will be implemented as part of: https://github.com/deeplearning4j/nd4j/issues/2146

**Comment by raver119** [comment]
Implemented.
