### ISSUE TITLE
How to Translate the Extracted INDArray Feature Matrix into Readable Matrix

### ISSUE THREAD

**Issue by kareemnaguib** [deeplearning4j/deeplearning4j#3926]
Hi,

I am a bit new to DL4J and have gone through the examples which are really great and helpful.
I am using RNN to classify text which works fine, but I need to extract the feature matrix the NN has fetched from the text.

In the code there is:

INDArray features = t.getFeatureMatrix();

but the question, how can I translate this feature matrix from INDArray into readable text?
I want to extract some words weights to build some statistics.

Thanks

**Comment by AlexDBlack** [comment]
Generally, if you want statistics: that's done before your data is converted to a DataSet(Iterator).
There's a bunch of different possible representations in NLP... word vectors, words (as one-hot), text as a sequence of characters... some might be convertable back to a human readable format, others not.

It really depends on your data pipeline and representation, and it's impossible to answer this question without knowing exactly what you are doing.
