### ISSUE TITLE
flatten layer too restrictive

### ISSUE THREAD

**Issue by shengc** [deeplearning4j/deeplearning4j#3927]
let's say if we have training data like this
[brown fox jumps], [fox jumps over], [jumps over lazy], [over lazy dog]

I want to convert each word into its corresponding word vectors, and then concatenate these vectors to represent the training data. What I can do is I provide vector of the integers to an embedding layer whose weights are the real word vectors. Assuming size of the word vector is 100, so the output of the embedding layer for a training data would be 3 * 100. Now I want to flatten this matrix into a vector of size 300 * 1 before feeding it to the next layer just as I plan. Here comes the problem, dl4j does not provide a flatten layer out of the box, like Keras does. The preprocessor of dl4j layer only cares about cnn and rnn layers, but in my case, obviously this is a feed forward layer.  I am thinking Is it possible to add a convolutional layer right after the embedding layer to do the flattening ? If yes, how should I do it ? Thanks!

**Comment by maxpumperla** [comment]
@shengc you're right in that we don't have a dl4j preprocessor in place that directly mimics what keras does, however for keras model import we do have a `KerasFlatten` layer that does what you want, see:

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/layers/KerasFlatten.java#L68-L90

Also, in the same module we also have a more general `Reshape` preprocessor, see:

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/preprocessors/ReshapePreprocessor.java

@AlexDBlack maybe we should move this `Reshape` preprocessor to the respective core module? Supporting `Flatten` in general could also be of value.

**Comment by shengc** [comment]
@maxpumperla Thanks for the tip. It looks like `ReshapePreprocessor` is not in 0.9.1 yet ? Also, how should I use it ? Does the below snippet make sense to you ?

```scala
val map = conf.getInputPreProcessors
// probably dl4j prohibits setting preprocessor on a vertex, so I will just set it on a layer.
map.put("hidden", new ReshapePreprocessor(Array(3, 100), Array(300)))
conf.setInputPreProcessors(map)
val graph = new ComputationGraph(conf.build())
```

**Comment by shengc** [comment]
Ok I managed to let it work by hacking `ReshapeProcessor`. However the model behaves in a bizarre way in that the model score keeps bouncing back and forth, which seems that it has a hard time to converge, and the prediction result is terrible , and by no means can be compared with the model for which I did all the heavy lifting to generate the concatenated word vectors as input. I don't think dl4j supports the notion of flattening in its current shape, and some superficial hack like what I did does not help.

**Comment by maxpumperla** [comment]
@shengc embedding layer now produces 3d output reliably after import, so this should work:

https://github.com/deeplearning4j/deeplearning4j/blob/ebed91e9ab4d07a2599c38c322258cb8931f51e1/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/layers/core/KerasFlatten.java#L89-L91

Let me know if you need anything else.
