### ISSUE TITLE
Update the javadocs to say org.nd4j.linalg.primitives.Pair instead of org.deeplearning4j.berkeley.Pair

### ISSUE THREAD

**Issue by tripathysa** [deeplearning4j/deeplearning4j#3928]
org.deeplearning4j.berkeley.Pair was replaced by org.nd4j.linalg.primitives.Pair 2 weeks ago. The javaDoc still shows the berkeley.Pair. We need to update the docs.

**Comment by AlexDBlack** [comment]
Outdated - javadoc has been updated since.
https://deeplearning4j.org/doc/
