### ISSUE TITLE
Proper end-to-end prediction comparisons for model import

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/deeplearning4j#3937]
#### Issue Description

We already have the infrastructure and resp. tests in place to compare dl4j output of imported models to original keras model output. Many of the unresolved remaining issues surrounding model import concern "output discrepancies" between keras and dl4j.

Use the methods available in `KerasModelEndToEndTest` to do proper layer-by-layer output comparisons. 

---
Original remarks from @turambar in code (mostly removed now):
- find a more elegant fix for the per-layer activation comparisons since some layers (e.g., ActivationLayer) overwrite previous layer's activations when run in train=false mode.
- ndarray.equalsWithEps(ndarray) appears to be broken
-  investigate why this fails for some layers:
    `compareINDArrays(layerName, activationsKeras.get(layerName), activationsDl4j, EPS);`
- investigate why this fails when max difference is ~1E-7!
   `compareINDArrays("predictions", predictionsKeras, predictionsDl4j, EPS);`

**Comment by turambar** [comment]
Cool, I'll keep an eye on this!

**Comment by maxpumperla** [comment]
we've been adding many more tests since this has been written, in particular LSTMs and CNNs have been tested quite thoroughly. I'm OK with the state of this.
