### ISSUE TITLE
import keras 2.X model

### ISSUE THREAD

**Issue by dutyhong** [deeplearning4j/deeplearning4j#3953]
#### Issue Description

i wonder when is it supported in deeplearning4j that importing the model trained by keras 2.X?

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by agibsonccc** [comment]
We've merged this recently, we aren't importing everything though. If you use snapshots or build from source and end up trying it, post your neural net you are trying to use in an issue.
