### ISSUE TITLE
Possible bug on CachingDataSetIterator method

### ISSUE THREAD

**Issue by luizcruzjf** [deeplearning4j/deeplearning4j#3960]
#### Issue Description

Not sure if this is a bug, but this was described as "fishy" in the chat.
Shouldnt CachingDataSetIterator.batch() return sourceIterator.batch()? Right now it returns sourceIterator.numExamples() and RecordReaderDataSetIterator does not support that.
#### Version Information

pom file
https://gist.github.com/luizcruzjf/4ab7d6cf76d0f4e8169789e4a6cb87a4

Running on windows 10, using Eclipse

**Comment by AlexDBlack** [comment]
Looks wrong to me:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/api/iterator/CachingDataSetIterator.java#L85

**Comment by eraly** [comment]
Thanks @luizcruzjf
