### ISSUE TITLE
KerasGlobalPooling layer does not allow to set the collapseDimensions flag

### ISSUE THREAD

**Issue by StefanoSamele** [deeplearning4j/deeplearning4j#3971]
The current KerasGlobalPooling class allows only to build a GlobalPoolingLayer with collapseDimensions flag set as true; whether to collapse dimensions should be instead dynamically deduced by the context of the net, i.e. the following layer.

DL4J version: 0.9.2-SNAPSHOT

**Comment by maxpumperla** [comment]
Thinking about this a little, I don't think keras does dynamic collapsing at all. It will keep dimensions, unless explicitly reshaped. So, I think it might be enough to set `collapseDimensions` to `false` (even though dl4j default is true).

@StefanoSamele does this reasoning make sense to you or are you aware of any situation in which, for _model import_ , `collapseDimensions`  should indeed be `true`?

**Comment by StefanoSamele** [comment]
Currently I am not aware of any situation in which, for model import, `collapseDimensions` should be `true`.
I do believe, as you said, that usually keras keeps the dimensions and reshape them in case of need with the following layer.
Thanks for the clarification.

**Comment by maxpumperla** [comment]
@StefanoSamele fixed now, let me know if this works for you.
