### ISSUE TITLE
`KerasLstm` import 

### ISSUE THREAD

**Issue by shengc** [deeplearning4j/deeplearning4j#3972]
I am curious how does dl4j imports an Keras LSTM layer where `return_sequences=True`? I browsed the code of `KerasLstm.java`, and has not been able to find where `return_sequences` can be set on the corresponding `GravesLSTM` layer.

**Comment by maxpumperla** [comment]
@shengc right now we don't support this flag, you're right. Short-term I will throw an error `return_sequences=True`, since import can't really work then. Mid-term I'll see what I can do to support it.

**Comment by maxpumperla** [comment]
I re-mapped to LSTM and now throw a warning. That's the only thing I can do for now, but we'll need to tackle this properly at some point.
