### ISSUE TITLE
Gradient check edge cases found for certain padding configurations

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/deeplearning4j#3975]
#### Issue Description

When adding `ZeroPadding1D` layers, we noticed that in `CNN1DGradientCheckTest` test, if we replace `SIGMOID` by `TANH`, a few (about 4 out of 100) of the tests will fail.

After consulting with @AlexDBlack we might have hit an edge case somewhere in the underlying code. Need to further investigate this.

**Comment by raver119** [comment]
Is it fixed now?

**Comment by AlexDBlack** [comment]
Confirmed fixed - passes with TANH now too for that test.
