### ISSUE TITLE
LayerBuilder is missing method .lrPolicyDecayRate(double)

### ISSUE THREAD

**Issue by papperwing** [deeplearning4j/deeplearning4j#3977]
In OutputLayer.Builder() is missing method .lrPolicyDecayRate(Double) which lead into inability to use different learning rate in layer than in the rest of model together with decaying learning rate.

DL4J version 0.9.1

**Comment by eraly** [comment]
There are major improvements/changes coming to learning rate and schedules in general. The learning rate (and schedules) will be passed in via updaters. This antiquates this issue therefore closing.

Here is the PR currently:
https://github.com/deeplearning4j/deeplearning4j/issues/3981
