### ISSUE TITLE
Build Errors on OS X 10.10.3

### ISSUE THREAD

**Issue by dbl001** [deeplearning4j/deeplearning4j#399]
Here's the error:

[ERROR] Failed to execute goal on project deeplearning4j-core: Could not resolve dependencies for project org.deeplearning4j:deeplearning4j-core:jar:0.0.3.3.5.alpha2-SNAPSHOT: The following artifacts could not be resolved: org.nd4j:canova-api:jar:0.0.0.5-SNAPSHOT, org.nd4j:nd4j-api:jar:0.0.3.5.5.6-SNAPSHOT, org.nd4j:nd4j-jblas:jar:0.0.3.5.5.6-SNAPSHOT: Failure to find org.nd4j:canova-api:jar:0.0.0.5-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]

David-Laxers-MacBook-Pro:deeplearning4j davidlaxer$ java -version
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)
David-Laxers-MacBook-Pro:deeplearning4j davidlaxer$ 

David-Laxers-MacBook-Pro:deeplearning4j davidlaxer$ mvn --version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T09:37:52-08:00)
Maven home: /Users/davidlaxer/Downloads/apache-maven-3.2.1
Java version: 1.8.0_05, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.4", arch: "x86_64", family: "mac"
David-Laxers-MacBook-Pro:deeplearning4j davidlaxer$ 

David-Laxers-MacBook-Pro:deeplearning4j davidlaxer$ mvn clean install -DskipTests -Dmaven.javadoc.skip=true
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.deeplearning4j:cdh4:jar:0.0.3.3.5.alpha2-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.hadoop:hadoop-common:jar -> duplicate declaration of version ${hadoop.version} @ line 89, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.deeplearning4j:dl4j-spark:jar:0.0.3.3.5.alpha2-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.scala-tools:maven-scala-plugin is missing. @ line 60, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.deeplearning4j:dl4j-spark-nlp:jar:0.0.3.3.5.alpha2-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.scala-tools:maven-scala-plugin is missing. @ org.deeplearning4j:spark:0.0.3.3.5.alpha2-SNAPSHOT, /Users/davidlaxer/deeplearning4j/deeplearning4j-scaleout/spark/pom.xml, line 47, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.deeplearning4j:dl4j-spark-ml:jar:0.0.3.3.5.alpha2-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.scala-tools:maven-scala-plugin is missing. @ org.deeplearning4j:spark:0.0.3.3.5.alpha2-SNAPSHOT, /Users/davidlaxer/deeplearning4j/deeplearning4j-scaleout/spark/pom.xml, line 47, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.deeplearning4j:spark:pom:0.0.3.3.5.alpha2-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.scala-tools:maven-scala-plugin is missing. @ line 47, column 21
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.deeplearning4j:deeplearning4j-cli-api:jar:0.0.3.3.5.alpha2-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.nd4j:nd4j-jblas:jar -> duplicate declaration of version ${nd4j.version} @ line 83, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] DeepLearning4j
[INFO] dl4j-test-resources
[INFO] deeplearning4j-core
[INFO] DeepLearning4j-scaleout-parent
[INFO] deeplearning4j-scaleout-api
[INFO] deeplearning4j-scaleout-zookeeper
[INFO] deeplearning4j-scaleout-akka
[INFO] deeplearning4j-nlp
[INFO] DeepLearning4j-AWS
[INFO] hadoop-yarn
[INFO] cdh4
[INFO] deeplearning4j-nlp-yarn
[INFO] org.deeplearning4j.spark
[INFO] dl4j-spark
[INFO] dl4j-spark-nlp
[INFO] dl4j-spark-ml
[INFO] deeplearning4j-cli
[INFO] deeplearning4j-cli-api
[INFO] deeplearning4j-ui
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building DeepLearning4j 0.0.3.3.5.alpha2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ deeplearning4j-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ deeplearning4j-parent ---
[INFO] 
[INFO] >>> maven-source-plugin:2.4:jar (attach-sources) @ deeplearning4j-parent >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ deeplearning4j-parent ---
[INFO] 
[INFO] <<< maven-source-plugin:2.4:jar (attach-sources) @ deeplearning4j-parent <<<
[INFO] 
[INFO] --- maven-source-plugin:2.4:jar (attach-sources) @ deeplearning4j-parent ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ deeplearning4j-parent ---
[INFO] Installing /Users/davidlaxer/deeplearning4j/pom.xml to /Users/davidlaxer/.m2/repository/org/deeplearning4j/deeplearning4j-parent/0.0.3.3.5.alpha2-SNAPSHOT/deeplearning4j-parent-0.0.3.3.5.alpha2-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building dl4j-test-resources 0.0.3.3.5.alpha2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ dl4j-test-resources ---
[INFO] Deleting /Users/davidlaxer/deeplearning4j/dl4j-test-resources/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ dl4j-test-resources ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ dl4j-test-resources ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 43 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ dl4j-test-resources ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ dl4j-test-resources ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/davidlaxer/deeplearning4j/dl4j-test-resources/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ dl4j-test-resources ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ dl4j-test-resources ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ dl4j-test-resources ---
[INFO] Building jar: /Users/davidlaxer/deeplearning4j/dl4j-test-resources/target/dl4j-test-resources-0.0.3.3.5.alpha2-SNAPSHOT.jar
[INFO] 
[INFO] >>> maven-source-plugin:2.4:jar (attach-sources) @ dl4j-test-resources >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ dl4j-test-resources ---
[INFO] 
[INFO] <<< maven-source-plugin:2.4:jar (attach-sources) @ dl4j-test-resources <<<
[INFO] 
[INFO] --- maven-source-plugin:2.4:jar (attach-sources) @ dl4j-test-resources ---
[INFO] Building jar: /Users/davidlaxer/deeplearning4j/dl4j-test-resources/target/dl4j-test-resources-0.0.3.3.5.alpha2-SNAPSHOT-sources.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ dl4j-test-resources ---
[INFO] Installing /Users/davidlaxer/deeplearning4j/dl4j-test-resources/target/dl4j-test-resources-0.0.3.3.5.alpha2-SNAPSHOT.jar to /Users/davidlaxer/.m2/repository/org/deeplearning4j/dl4j-test-resources/0.0.3.3.5.alpha2-SNAPSHOT/dl4j-test-resources-0.0.3.3.5.alpha2-SNAPSHOT.jar
[INFO] Installing /Users/davidlaxer/deeplearning4j/dl4j-test-resources/pom.xml to /Users/davidlaxer/.m2/repository/org/deeplearning4j/dl4j-test-resources/0.0.3.3.5.alpha2-SNAPSHOT/dl4j-test-resources-0.0.3.3.5.alpha2-SNAPSHOT.pom
[INFO] Installing /Users/davidlaxer/deeplearning4j/dl4j-test-resources/target/dl4j-test-resources-0.0.3.3.5.alpha2-SNAPSHOT-sources.jar to /Users/davidlaxer/.m2/repository/org/deeplearning4j/dl4j-test-resources/0.0.3.3.5.alpha2-SNAPSHOT/dl4j-test-resources-0.0.3.3.5.alpha2-SNAPSHOT-sources.jar
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building deeplearning4j-core 0.0.3.3.5.alpha2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.nd4j:canova-api:jar:0.0.0.5-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.nd4j:nd4j-api:jar:0.0.3.5.5.6-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.nd4j:nd4j-jblas:jar:0.0.3.5.5.6-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] DeepLearning4j .................................... SUCCESS [  1.862 s]
[INFO] dl4j-test-resources ............................... SUCCESS [02:09 min]
[INFO] deeplearning4j-core ............................... FAILURE [  0.694 s]
[INFO] DeepLearning4j-scaleout-parent .................... SKIPPED
[INFO] deeplearning4j-scaleout-api ....................... SKIPPED
[INFO] deeplearning4j-scaleout-zookeeper ................. SKIPPED
[INFO] deeplearning4j-scaleout-akka ...................... SKIPPED
[INFO] deeplearning4j-nlp ................................ SKIPPED
[INFO] DeepLearning4j-AWS ................................ SKIPPED
[INFO] hadoop-yarn ....................................... SKIPPED
[INFO] cdh4 .............................................. SKIPPED
[INFO] deeplearning4j-nlp-yarn ........................... SKIPPED
[INFO] org.deeplearning4j.spark .......................... SKIPPED
[INFO] dl4j-spark ........................................ SKIPPED
[INFO] dl4j-spark-nlp .................................... SKIPPED
[INFO] dl4j-spark-ml ..................................... SKIPPED
[INFO] deeplearning4j-cli ................................ SKIPPED
[INFO] deeplearning4j-cli-api ............................ SKIPPED
[INFO] deeplearning4j-ui ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:13 min
[INFO] Finished at: 2015-07-06T10:02:38-08:00
[INFO] Final Memory: 14M/181M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project deeplearning4j-core: Could not resolve dependencies for project org.deeplearning4j:deeplearning4j-core:jar:0.0.3.3.5.alpha2-SNAPSHOT: The following artifacts could not be resolved: org.nd4j:canova-api:jar:0.0.0.5-SNAPSHOT, org.nd4j:nd4j-api:jar:0.0.3.5.5.6-SNAPSHOT, org.nd4j:nd4j-jblas:jar:0.0.3.5.5.6-SNAPSHOT: Failure to find org.nd4j:canova-api:jar:0.0.0.5-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :deeplearning4j-core
David-Laxers-MacBook-Pro:deeplearning4j davidlaxer$

**Comment by agibsonccc** [comment]
This doesn't have anything to do with osx. Please install nd4j and canova from source. Thanks!

**Comment by dbl001** [comment]
Thank You!

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] DeepLearning4j .................................... SUCCESS [  1.948 s]
[INFO] dl4j-test-resources ............................... SUCCESS [01:53 min]
[INFO] deeplearning4j-core ............................... SUCCESS [ 30.613 s]
[INFO] DeepLearning4j-scaleout-parent .................... SUCCESS [  0.078 s]
[INFO] deeplearning4j-scaleout-api ....................... SUCCESS [  1.008 s]
[INFO] deeplearning4j-scaleout-zookeeper ................. SUCCESS [  3.403 s]
[INFO] deeplearning4j-scaleout-akka ...................... SUCCESS [ 10.757 s]
[INFO] deeplearning4j-nlp ................................ SUCCESS [ 20.457 s]
[INFO] DeepLearning4j-AWS ................................ SUCCESS [  5.936 s]
[INFO] hadoop-yarn ....................................... SUCCESS [  0.028 s]
[INFO] cdh4 .............................................. SUCCESS [ 12.881 s]
[INFO] deeplearning4j-nlp-yarn ........................... SUCCESS [  4.799 s]
[INFO] org.deeplearning4j.spark .......................... SUCCESS [ 14.901 s]
[INFO] dl4j-spark ........................................ SUCCESS [ 32.517 s]
[INFO] dl4j-spark-nlp .................................... SUCCESS [ 30.704 s]
[INFO] dl4j-spark-ml ..................................... SUCCESS [02:47 min]
[INFO] deeplearning4j-cli ................................ SUCCESS [  0.101 s]
[INFO] deeplearning4j-cli-api ............................ SUCCESS [  5.672 s]
[INFO] deeplearning4j-ui ................................. SUCCESS [  9.918 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:48 min
[INFO] Finished at: 2015-07-06T12:45:00-08:00
[INFO] Final Memory: 116M/453M
[INFO] ------------------------------------------------------------------------
David-Laxers-MacBook-Pro:deeplearning4j davidlaxer$

**Comment by dbl001** [comment]
-rw-r--r--   1 davidlaxer  staff    476 Jul  6 09:34 setup.sh

should setup.sh have an execute bit set (e.g. - chmod o+x setup.sh)?
