### ISSUE TITLE
MaskArrays will propagate nans

### ISSUE THREAD

**Issue by yylonly** [deeplearning4j/deeplearning4j#3992]
There have four tasks for my network. Some value is missing represented as NaN. Like this number of trainning set is 2
[0.78, 0.70]
[0.98, 0.94]
[0.00, NaN]
[0.00, 0.01]
Therefore, I build mask arrays for masking the NaN value without computed in cost Function
[1.00, 1.00]
[1.00, 1.00]
[1.00, 0.00]
[1.00, 1.00]

I try three ways for making this work:
1. net.setLayerMaskArrays(null, outputmask);
2. net.fit(data.getFeatures(), data.getLabels(), null, outputmask);
3. net.getLayer("Bioavailability").setMaskArray(outputmask[2]);

After invoking fit() function, All of those approaches make the net score as NaN.  Then I only fit into 1 data without NaN, Network can compute right error.  Therefore, the mask array did not working in any methods.

My network configuration is:
```
ComputationGraphConfiguration conf = new NeuralNetConfiguration.Builder()
   .seed(123456)
   .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
   .learningRate(0.1)
   .updater(Updater.NESTEROVS)
   .momentum(0.9)
   .weightInit(WeightInit.XAVIER_UNIFORM)
   .graphBuilder()
   .addInputs("input")		       
   .addLayer("L3", new DenseLayer.Builder().activation(Activation.RELU).nIn(1024).nOut(50).build(), "L1")
   .addLayer("Bioavailability", new OutputLayer.Builder().activation(Activation.SIGMOID)
		                .lossFunction(LossFunctions.LossFunction.L2)
		                .nIn(50).nOut(1).build(), "L3")
   .addLayer("BloodProteinBinding", new OutputLayer.Builder().activation(Activation.SIGMOID)
		                .lossFunction(LossFunctions.LossFunction.L2)
		                .nIn(50).nOut(1).build(), "L3")
   .addLayer("HalfLife", new OutputLayer.Builder().activation(Activation.SIGMOID)
		                .lossFunction(LossFunctions.LossFunction.L2)
		                .nIn(50).nOut(1).build(), "L3")
   .addLayer("VolumeofDistribution", new OutputLayer.Builder().activation(Activation.SIGMOID)
		                .lossFunction(LossFunctions.LossFunction.L2)
		                .nIn(50).nOut(1).build(), "L3")
   .setOutputs("Bioavailability","BloodProteinBinding", "HalfLife", "VolumeofDistribution")
   .backprop(true)
   .build();
```

Both ND4J and DL4J version are 0.8.0..

Any ideas?  Thanks

**Comment by yylonly** [comment]
I also try to use single output layer with one mask array, get the same result
```
.addLayer("AllinOne", new OutputLayer.Builder().activation(Activation.SIGMOID)
   .lossFunction(LossFunctions.LossFunction.L2)
   .nIn(50).nOut(4).build(), "L3")
```

[[0.78, 0.98, 0.00, 0.00],
 [0.70, 0.94,   NaN, 0.01]]

[[1.00, 1.00, 1.00, 1.00],
 [1.00, 1.00, 0.00, 1.00]]

Score: NaN

**Comment by yylonly** [comment]
Note: After I change the NaN to any other double value. Mask is worked......

Mask Array
[[1.00, 1.00, 1.00, 1.00],
[1.00, 1.00, 0.00, 1.00]]

Score: 0.5663096904754639

[[1.00, 1.00, 1.00, 1.00],
[1.00, 1.00, 1.00, 1.00]]

Score: 0.6927887201309204

But this way is not perfect solution....  I think this is not hard to solve anyway.....

**Comment by eraly** [comment]
The behaviour you are seeing (I think) is by design. You want to be aware of the nans you have in your input data.

I would also suggest looking into datavec where you can set a schema specifying that nans are not allowed and what range of values are allowed etc etc. 

You can clear nans with Nd4j.clearNans(someArr). This will replace your nans with zeros. 

You can also replace the nans with whatever value you would like.
Nd4j.getExecutioner().exec(new ReplaceNans(someArr,valueToReplaceNaN)

A hacky way to figure out where the nans are in your ndarray would be Nd4j.clearNans(someArr.divi(someArr)) this will give you 1s with non nan values and 0 where there are nans.

**Comment by AlexDBlack** [comment]
Right, I agree with closing this - NaNs are propagated by IEE754, and it makes sense to follow these semantics for mathematical operaitons. Furthermore, adding NaN checks at every iteration would add overhead with no benefit for >99% of users.

**Comment by eraly** [comment]
Thanks
