### ISSUE TITLE
Invalid configurations in Computation Graph possible

### ISSUE THREAD

**Issue by firasdib** [deeplearning4j/deeplearning4j#3993]
#### Issue Description

When creating a graph you're able to create invalid configurations (that are silently ignored?).

See below for an invalid example and an example of how it should be done:
**Invalid example**
```
.addInputs("x", "y") // 2 separate inputs
.addLayer("foo", DenseLayer, "x") // first layer takes in "x", does something, and outputs "foo"
.addLayer("bar", DenseLayer, "y") // same here, but takes "y" and outputs "bar"
.addLayer("baz", DenseLayer, "foo", "bar")
```

**Valid example**
```
.addInputs("x", "y") // 2 separate inputs
.addLayer("foo", DenseLayer, "x") // first layer takes in "x", does something, and outputs "foo"
.addLayer("bar", DenseLayer, "y") // same here, but takes "y" and outputs "bar"
.addVertex("merge", MergeVertex, "foo", "bar")
.addLayer("baz", DenseLayer, "merge");
```

It would be great if an error was thrown, or a warning emitted, that explains the new behavior of the graph.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 0.9.2

**Comment by AlexDBlack** [comment]
This is totally valid - the two code samples are in fact identical in practice. The merge mergex is automatically added in the "invalid" code case. Merge vertices are automatically added when required for any single-input layers/vertices that get multiple inputs.
