### ISSUE TITLE
Bug in RBMIrisExample - NeuralNetPlotter

### ISSUE THREAD

**Issue by randombishop** [deeplearning4j/deeplearning4j#400]
I get this error at the end of the example, probably related to windows / python :

o.d.p.NeuralNetPlotter - Std error [Traceback (most recent call last):,   File "C:\Users\nabil\AppData\Local\Temp\graphs\plot.py", line 150, in <module>,     plot_matrices(path, plot_type, filename),   File "C:\Users\nabil\AppData\Local\Temp\graphs\plot.py", line 69, in plot_matrices,     plt.savefig(filename, format='png'),   File "C:\Anaconda\lib\site-packages\matplotlib\pyplot.py", line 577, in savefig,     res = fig.savefig(*args, **kwargs),   File "C:\Anaconda\lib\site-packages\matplotlib\figure.py", line 1476, in savefig,     self.canvas.print_figure(*args, **kwargs),   File "C:\Anaconda\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 161, in print_figure,     FigureCanvasAgg.print_figure(self, *args, **kwargs),   File "C:\Anaconda\lib\site-packages\matplotlib\backend_bases.py", line 2211, in print_figure,     **kwargs),   File "C:\Anaconda\lib\site-packages\matplotlib\backends\backend_agg.py", line 526, in print_png,     filename_or_obj = open(filename_or_obj, 'wb'), IOError: [Errno 2] No such file or directory: 'C:\\Users\\nabil\\AppData\\Local\\Temp\\\\graphs/5ee8313a-497d-4ce2-a72e-501219176d3f\\weightHistograms.png']

**Comment by nyghtowl** [comment]
@randombishop: I adjusted how the file names are set to allow for dynamic setting of file separator. I don't have Windows. Try pulling the latest dl4j and see if the problem was resolved.

**Comment by randombishop** [comment]
@nyghtowl thanks for the correction, it seems to solve the path problem, but the vizualisation is still not working, here is the ending lines in my console :

**Comment by nyghtowl** [comment]
Looks like its running. Check the folder C:\Users\nabil\AppData\Local\Temp\\graphs\8d6dd638-a30d-44b0-bdfd-9660c8e3ba90\ to see if it has images. If it doesn't that's a different error. I'm going to close this since the path issue is resolved.

**Comment by randombishop** [comment]
![weighthistograms](https://cloud.githubusercontent.com/assets/7156021/8631335/4ad49bce-2763-11e5-94bf-159fe96c06d8.png)
![activationplot](https://cloud.githubusercontent.com/assets/7156021/8631336/4b405742-2763-11e5-80f1-1bf8856b53af.png)

**Comment by nyghtowl** [comment]
Great
