### ISSUE TITLE
Numerical underflow from sigmoid

### ISSUE THREAD

**Issue by papperwing** [deeplearning4j/deeplearning4j#4006]
Training modified alexNet with output layer consisting of 7 neurons with activation Sigmoid and loss fucntion XENT lead to numerical underflow. 

@AlexDBlack  suggested that there could be added eps

>Alex Black
>@AlexDBlack
>11:42
>@papperwing hm, look at the preout values... sigmoid(-559) will give you numerical underflow  open an issue, we can probably add an eps in there to avoid it more generally, you might be able to handle that with tuning (regularization etc)

![snimek z 2017-09-05 10-40-23](https://user-images.githubusercontent.com/5627436/30055384-8b05f65a-922f-11e7-9665-f51c3697ec47.png)

DL4J version 0.9.1

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/nd4j/pull/2121
