### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by JZ051** [deeplearning4j/deeplearning4j#4013]
[####] Issue Description

OutOfMemoryException after some hours when repeating DL4J-runs (from data reading and parsing into DataSets, to splitting, training and testing).

Pom, Code, Stacktrace in this [Gist ](https://gist.github.com/JZ051/d6a57d3c1d8c101a7407e842943a6e81)

I'm running DL4J repeatedly. I think I reinitialize all variables and did not expect such an error. Somehow, something on the off-heap memory remains, while new stuff gets added. 

I start my experiments as a JUnit Test and pass these parameters -Dorg.bytedeco.javacpp.maxbytes=8589934592
-Dorg.bytedeco.javacpp.maxphysicalbytes=8589934592
-Xmx1g

If more code is needed, I will post it into 

#### Version Information

* DL4J version: 0.9.2
* platform information: Win10 (64bit); i5 2*2,8Ghz; 12GB DDR3 RAM;  

Steps already tried: upgrade from 0.9.1 to 0.9.2 and increase of off-heap memory from default to, in the end, 8GB.

**Comment by raver119** [comment]
Okay, what happens if/when you enable workspace use for training? It's not reflected in your source code

**Comment by thhart** [comment]
Maybe related: #3961

**Comment by JZ051** [comment]
@raver119 : I had so far only added: ".trainingWorkspaceMode(WorkspaceMode.NONE)", now trying with "SINGLE". I will know more tomorrow, as it takes about 28h to crash with that error.

**Comment by thhart** [comment]
@JZ051 Can you try to reproduce with lower memory settings? Then you will hit earlier.

**Comment by JZ051** [comment]
@thhart Yes I could. But I wouldnt know exactly, to where I could go with it and I'm leaving soon anyways for another assignment at work, so I wouldnt know until tomorrow anyway. And I'd like my program do generate some data until then.

**Comment by thhart** [comment]
@raver119 This is a nasty one for sure, please let us know how we can support to narrow the reason.

**Comment by raver119** [comment]
No worries, once i merge my current branch, i'll focus on your 2 issues

**Comment by JZ051** [comment]
I closed the issue for the moment, as it looks like it has been resolved - by replacing .trainingWorkspaceMode(WorkspaceMode.NONE) with .trainingWorkspaceMode(WorkspaceMode.SINGLE). In the beginning, I thought that "NONE" was to be used if no workspace was setup in the code. Sorry for the bother.
