### ISSUE TITLE
ImportError: No module named PIL

### ISSUE THREAD

**Issue by dbl001** [deeplearning4j/deeplearning4j#402]
2015-07-07 15:05:02,361 - [ERROR] - from org.deeplearning4j.plot.NeuralNetPlotter in main
				
Std error [Traceback (most recent call last):,   File "/var/folders/nj/nphdkhyj6s1dttb0pd9zb2wc0000gn/T/graphs/plot.py", line 5, in <module>,     from PIL import Image, ImportError: No module named PIL]

**Comment by dbl001** [comment]
David-Laxers-MacBook-Pro:logs davidlaxer$ conda install pil
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /Users/davidlaxer/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    lcms-1.19                  |                0         205 KB
    pil-1.1.7                  |           py27_2         351 KB
    setuptools-18.0.1          |           py27_0         341 KB
    pip-7.1.0                  |           py27_0         1.4 MB
    ------------------------------------------------------------
                                           Total:         2.2 MB

The following NEW packages will be INSTALLED:

    lcms:       1.19-0       
    pil:        1.1.7-py27_2 

The following packages will be UPDATED:

    pip:        7.0.3-py27_0  --> 7.1.0-py27_0 
    setuptools: 17.1.1-py27_0 --> 18.0.1-py27_0

Proceed ([y]/n)? y

Fetching packages ...
lcms-1.19-0.ta 100% |################################| Time: 0:00:00 496.53 kB/s
pil-1.1.7-py27 100% |################################| Time: 0:00:00 700.44 kB/s
setuptools-18. 100% |################################| Time: 0:00:00 656.30 kB/s
pip-7.1.0-py27 100% |################################| Time: 0:00:01   1.37 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
David-Laxers-MacBook-Pro:logs davidlaxer$

**Comment by agibsonccc** [comment]
It might not be following your python path properly?

**Comment by agibsonccc** [comment]
Closed due to inactivity.
