### ISSUE TITLE
40 Techniques Used by Data Scientists

### ISSUE THREAD

**Issue by ashuezy** [deeplearning4j/deeplearning4j#4021]
Go through the link it will help in your quest.

http://www.datasciencecentral.com/profiles/blogs/40-techniques-used-by-data-scientists

**Comment by huitseeker** [comment]
Interesting link, but we'll need a little more on how it relates to DL4J. Closing until then — feel free to reopen if you want to write original content explaining which & how those techniques relate to this project.
