### ISSUE TITLE
getLayer() method in Class NeuralNetConfiguration

### ISSUE THREAD

**Issue by dbl001** [deeplearning4j/deeplearning4j#403]
I'm getting a 'method undefined' error for the class NeuralNetConfiguration in TestSerialization, etc.
![screen shot 2015-07-07 at 4 15 14 pm](https://cloud.githubusercontent.com/assets/3105499/8559593/81641b44-24c3-11e5-85da-a662ac9571f0.png)

        AutoEncoder da = LayerFactories.getFactory(conf.getLayer()).create(conf, Arrays.<IterationListener>asList(new ScoreIterationListener(1), new HistogramIterationListener(1)),0);

**Comment by agibsonccc** [comment]
Install the lombok plugin for eclipse.

**Comment by dbl001** [comment]
Could lombok be added to: pom.xml?

<dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.14.6</version>
            <scope>provided</scope>
        </dependency>

http://stackoverflow.com/questions/22310414/how-to-configure-lombok-in-eclipse-luna

**Comment by agibsonccc** [comment]
It also needs to be added to the ide.
ᐧ
