### ISSUE TITLE
"No CUDA devices were found in system" on Mac with CUDA-7.5

### ISSUE THREAD

**Issue by nikita-volkov** [deeplearning4j/deeplearning4j#4037]
I'm getting "No CUDA devices were found in system" from **ND4J 0.9.1** on **OS X 10.10** with **CUDA-7.5**. All the deps and CUDA are correct. I've tried running with **ND4J 0.4.0** and it works. So the issue must be somewhere in ND4J and there must be a bug committed somewhere in between the mentioned releases.

**Comment by raver119** [comment]
Try to install CUDA 8.0 instead of 7.5. Maybe some binary compatibility issues are hidden somewhere...

**Comment by raver119** [comment]
P.s. with next release CUDA 7.5 support goes.

**Comment by nikita-volkov** [comment]
Unfortunately CUDA-8.0 is incompatible with OS X 10.10, so I'll have to reinstall the whole OS for that.

**Comment by agibsonccc** [comment]
We
