### ISSUE TITLE
Can't get TicTacToe example to run

### ISSUE THREAD

**Issue by schrum2** [deeplearning4j/deeplearning4j#4043]
#### Issue Description

Question about dl4j-examples on tictactoe: From what I can tell, I'm supposed to run TicTacToeData first to generate a TicTacToe resource file which is then used by the other programs in this package. However, every main method in this package, including TicTacToeData results in a "Exception in thread "main" java.lang.IllegalStateException: Resource 'TicTacToe' cannot be found."

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
   Windows 7 and Windows 10
   DL4J 0.9.1

**Comment by agibsonccc** [comment]
Closed in favor of: https://github.com/deeplearning4j/dl4j-examples/issues/538
