### ISSUE TITLE
UI server reporting masked steps

### ISSUE THREAD

**Issue by Wilwilly** [deeplearning4j/deeplearning4j#4044]
On the UI server all steps are reported, even masked one.

As a result we get charts full of spikes, which makes them hard to read (check attached images). The problem appears on all charts, not just Model Score vs Iteration.

![image](https://user-images.githubusercontent.com/31029137/30284326-fae6775e-96f0-11e7-8d61-86201c4abab3.png)
![image](https://user-images.githubusercontent.com/31029137/30284328-fe1fc966-96f0-11e7-9be4-c9e2a0750773.png)

**Comment by AlexDBlack** [comment]
I agree it's a little ugly, but I'm not sure exactly what we could do here...
FWIW it's uncommon to have a tbptt segment that's completely masked out, as is the case here (at least as I understand it from gitter)... you're still doing a parameter update during those completely masked steps, but with 0s out, 0 gradient, and 0 score. So it's legitimate to be reporting 0s for that IMO.
