### ISSUE TITLE
UpSampling2d on Cuda causes JVM Crash

### ISSUE THREAD

**Issue by wmeddie** [deeplearning4j/deeplearning4j#4049]
#### Issue Description

Running the code below with CUDA-8 causes an EXCEPTION_ACCESS_VIOLATION and JVM crash.

https://gist.github.com/wmeddie/d178136519f8a3502c4bb73fac1a8e0a

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.9.2-SNAPSHOT
* platform information: Windows 10
* CUDA version: 8.0
* NVIDIA driver version: 381.89 (1050)

**Comment by raver119** [comment]
Please run without CUDA and confirm that's the issue on CPU as well.
There's no CUDA kernel for upsampling right now anyway, so CPU is used for this op

**Comment by wmeddie** [comment]
Oh, didn't know that.  CPU runs fine.

**Comment by raver119** [comment]
O_o

**Comment by raver119** [comment]
Max has nothing to do here. As i see - CUDA backend crashes in CustomOp helper.

**Comment by raver119** [comment]
And it looks like windows-specific issue again. Just checked linux - no issues here.

**Comment by raver119** [comment]
Issue fixed.
