### ISSUE TITLE
Ressource: "raw_sentences" missing in deeplearning4j-scaleout/spark/dl4j-spark-nlp/src/test/resources

### ISSUE THREAD

**Issue by olafhel** [deeplearning4j/deeplearning4j#406]
java.io.FileNotFoundException: class path resource [raw_sentences.txt] cannot be resolved to URL because it does not exist

	at org.deeplearning4j.spark.models.embeddings.glove.GloveTest.testGlove(GloveTest.java:45)

**Comment by olafhel** [comment]
also cause failure for Word2VecTest

**Comment by agibsonccc** [comment]
That's likely related to dl4j-test-resources not being included as a
dependency. Would you mind adding that to the pom with ${project.version}
and seeing what that does?
ᐧ

**Comment by agibsonccc** [comment]
With scope test of course
ᐧ

**Comment by olafhel** [comment]
The resource is actually missing.
Even by adding the dependency in the poms

        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>dl4j-test-resources</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>

**Comment by agibsonccc** [comment]
This has been added.
