### ISSUE TITLE
Different outputs of AtrousConvolution Layer using cpu and gpu backend

### ISSUE THREAD

**Issue by StefanoSamele** [deeplearning4j/deeplearning4j#4075]
In the following simple net, the atrous convolution layer produces different outputs as per backend used (native cpu vs gpu with cuDNN):

https://gist.github.com/StefanoSamele/90c3deda6e07c9452c5514d7854f2b50

The two different outputs are:

https://gist.github.com/StefanoSamele/5cc29af2ce0a7ad76379f2b170eee09c

We also noticed that the difference in the behavior appears only when the dilation rate is equal or higher than 3. The outputs are in a sort of way "shifted".

We are using the following DL4J version: 0.9.2-SNAPSHOT

**Comment by AlexDBlack** [comment]
For the record: dilation 3 or higher does *not* use CuDNN, even if CuDNN is enabled - I ran into CuDNN exceptions there when implementing dilation (the CuDNN docs don't say anything about it).

**Comment by StefanoSamele** [comment]
Does this mean that the exception is related to the nd4j-CUDA backend?

**Comment by AlexDBlack** [comment]
Yes, for stride 3, it means CPU and GPU (nd4j, not cudnn) are both being used.
