### ISSUE TITLE
AlexNet pre-trained for ImageNet

### ISSUE THREAD

**Issue by schrum2** [deeplearning4j/deeplearning4j#4081]
I would appreciate having pre-trained ImageNet weights for AlexNet in the model zoo. Such a model seems to already exist in Caffe: https://github.com/BVLC/caffe/tree/master/models/bvlc_alexnet

**Comment by saudet** [comment]
There appears to be a pretrained Keras model for AlexNet here, for example:
https://github.com/heuritech/convnets-keras
And Deeplearning4j should be able to import those just fine:
https://deeplearning4j.org/model-import-keras
Let us know if you encounter any issues with that though!

**Comment by schrum2** [comment]
Perhaps I simply need to figure out how to do this manually, or maybe there is something wrong with the hd5 file. The example that you point out indicates that both an hd5 file and a json file are needed. I can only find the hd5 file on the site you point out. There is a method that can supposedly import the weights using only the hd5 file, but when I use it, the exception I get indicates that this file does not have the configuration info needed from the json file. Specifically:

org.deeplearning4j.nn.modelimport.keras.InvalidKerasConfigurationException: Model configuration attribute missing from ../alexnet_weights.h5 archive.. For more information, see http://deeplearning4j.org/model-import-keras.
	at org.deeplearning4j.nn.modelimport.keras.KerasModel$ModelBuilder.modelHdf5Filename(KerasModel.java:617)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:155)

I could try to make a json file manually, though I feel like that would be very error prone. Is there an easier course? The AlexNet configuration is already available in the ModelZoo after all. I'm just wondering if there is a way to save myself lots of hassle.

Thanks!

**Comment by tomthetrainer** [comment]
Multiple ways to save a keras model. 

The h5 may have weights only, or weights and config. 

https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model

You should strive to find alexnet weights and config. It should be out there, I will look real quick as well.

**Comment by tomthetrainer** [comment]
I suggest you use the code example that provided the weights, 
https://github.com/heuritech/convnets-keras

Use the python keras example provided there. 

Once that keras example loads the weights, and already has the model then call the proper keras save function to get the config and weights in a single h5 file, or optionally save the model config and weights separately and import into dl4j from that export. 

Seems like the quickest way to get a config and weights that are known to work together.

**Comment by schrum2** [comment]
Indeed, I tried that. However, this code seems to rely on an outdated version of Keras and doesn't run (at least, I couldn't get it to work). I'll fiddle with it a bit more, or try to install an older version of Keras I guess.

**Comment by saudet** [comment]
We can install old version of Keras: https://github.com/fchollet/keras/issues/5852#issuecomment-287632439
