### ISSUE TITLE
Glossary Link : AlexNet Broken

### ISSUE THREAD

**Issue by aldrin233** [deeplearning4j/deeplearning4j#4086]
The Link of the AlexNet Example in the [Glossary ](https://deeplearning4j.org/glossary)is not working.

Broken Link - > `https://github.com/deeplearning4j/ImageNet-Example/blob/master/src/main/java/imagenet/Models/AlexNet.java`

**Comment by saudet** [comment]
@crockpotveggies Redirect to https://github.com/deeplearning4j/dl4j-model-z/blob/master/src/main/java/org/deeplearning4j/AlexNet.java ?

**Comment by crockpotveggies** [comment]
Yes that is a logical change. We should be redirecting everything to models in the zoo. I'll update this now.
