### ISSUE TITLE
SequenceRecordReaderDataSetIterator calls preProcess twice per next()

### ISSUE THREAD

**Issue by lilalinux** [deeplearning4j/deeplearning4j#4103]
#### Issue Description

SequenceRecordReaderDataSetIterator calls preProcess twice per next()
It's called already at the ed of mdsToDataSet() and directly after it returns again:
---------------------------------------------
    private DataSet mdsToDataSet(MultiDataSet mds) {
	...
        if (preProcessor != null) {
            preProcessor.preProcess(ds);
        }

        return ds;
    }
    ...
    public DataSet next(int num) {
	...
        DataSet ds = mdsToDataSet(mds);

        if (preProcessor != null) {
            preProcessor.preProcess(ds);
        }
	...
    }
---------------------------------------------
#### Version Information

Current master
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/datasets/datavec/SequenceRecordReaderDataSetIterator.java#L331

#### Contributing

Fix: https://github.com/deeplearning4j/deeplearning4j/pull/4104

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/4104
