### ISSUE TITLE
Exception Access Violation in libnd4jcpu.dll

### ISSUE THREAD

**Issue by ajohnsonz** [deeplearning4j/deeplearning4j#4118]
#### Issue Description

Training the model, suddenly it crashed during epoch 22 (roughly 170000 iterations) with the following error:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000695f7010, pid=6148, tid=0x00000000000010fc
#
# JRE version: Java(TM) SE Runtime Environment (8.0_102-b14) (build 1.8.0_102-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.102-b14 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [libnd4jcpu.dll+0x177010]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\dev\workspace\peakio\theo-data-neural-net\hs_err_pid6148.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

```

#### Version Information

Please indicate relevant versions, including, if relevant:

Windows 7 64-bit
Java 1.8.0_102
nd4j backend: nd4j-native-platform
dl4j version: 0.9.1

[hs_err_pid6148.log](https://github.com/deeplearning4j/deeplearning4j/files/1336468/hs_err_pid6148.log)

**Comment by raver119** [comment]
Epoch 22? This one will be amazing to debug....

**Comment by raver119** [comment]
Show your source code please.

**Comment by ajohnsonz** [comment]
I was trying to narrow down the code where it was being caused, but after restarting my PC, I can no longer reproduce the issue - corrupted memory that got cleared by a restart perhaps? Can probably close this issue for now.

**Comment by raver119** [comment]
:/

Please let us know if you'll manage to reproduce this issue somehow. However, i hadn't heard of issues with concat for quite some time now.
