### ISSUE TITLE
Wrongly documented parameter for javaCPP on memory page

### ISSUE THREAD

**Issue by papperwing** [deeplearning4j/deeplearning4j#4119]
On the page https://deeplearning4j.org/memory there is mentioned parameter maxPhysicalBytes and how to set it as parameter of jvm. Parameter setting is in camelcase but it should be in lowercase, otherwise it is not passed into right place. 

Also there is missing information about if it should be parameter of app or parameter of jvm. I tested it as jvm parameter and it was correctly passed into Pointer variable.

**Comment by raver119** [comment]
Fixed. Thanks for highlighting this issue.

**Comment by Treiblesschorle** [comment]
`Example: Configuring 1GB initial on-heap, 2GB max on-heap, 8GB off-heap:
-Xms1G -Xmx2G -Dorg.bytedeco.javacpp.maxbytes=8G -Dorg.bytedeco.javacpp.maxPhysicalBytes=8G`

This sentence is still camelcase.

**Comment by AlexDBlack** [comment]
@Treiblesschorle thanks, fixed here: https://github.com/deeplearning4j/deeplearning4j/commit/f01514e65aad03a0a970caa4dadaea3b9015612b
