### ISSUE TITLE
Small bug in ReshapePreprocessor

### ISSUE THREAD

**Issue by StefanoSamele** [deeplearning4j/deeplearning4j#4123]
Looking into the ReshapePreprocessor I noticed that there is a strict equality involving two different arrays of int (line 87). Shouldn't be a check on the shapes i.e. the content of the two arrays?

**Comment by maxpumperla** [comment]
thanks. will look into it!

**Comment by AlexDBlack** [comment]
Yes, that was a bug. Fixed here: https://github.com/deeplearning4j/deeplearning4j/commit/ed975f452e18079b13f32258509cfe7099c1c799
