### ISSUE TITLE
Import model from Keras 2.0

### ISSUE THREAD

**Issue by Menion93** [deeplearning4j/deeplearning4j#4124]
#### Issue Description

I want to import a model I made with the latest version of Keras 2.x into DL4k 0.91. When I try to import the model and the weights I got an error about output_dim not found, so i added in the json model file "output_dim"

` "config":[  
      {  
         "class_name":"Dense",
         "config":{  
         "name":"dense_9",
         "trainable":true,
            "batch_input_shape":[  
               null,
               2,
               10
            ],
	"output_dim":1,  <-----  `

Now It asks me for "init" field: 

> InvalidKerasConfigurationException: Keras layer is missing init field

I tried looking into the source code but I cannot find this method KerasLayer.getWeightInitFromConfi, I only found 

 `getWeightL1RegularizationFromConfig`

Maybe I'am looking in the wrong version of DL4J.

Is it a bug, I am doing something wrong, or keras 2.x model import is not supported?

**Comment by agibsonccc** [comment]
@Menion93 you should upload all your files to the issue and we can take a closer look.

**Comment by Menion93** [comment]
This is the keras model import and weights

[neura_network_models.zip](https://github.com/deeplearning4j/deeplearning4j/files/1344938/neura_network_models.zip)


this is the line that import the model and the weights

> network = KerasModelImport.importKerasSequentialModelAndWeights(
>                     config.base_path_nn + trasnf + "-net_model",
>                     config.base_path_nn + trasnf + "-weights");

**Comment by maxpumperla** [comment]
@Menion93 thanks for reporting this. I can't unzip your file (it's also only suspiciously low 5k in size), can you send again? At least provide a gist with the model yaml, please.

Two things of note:
1. The error is thrown in the initialization utils here:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/utils/KerasInitilizationUtils.java#L201

2. If you are using keras 2, then your model really does not have an `init` key word, that only exists in keras 1. In keras 2 it is `kernel_initializer`, see e.g.

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/test/resources/configs/keras2/imdb_lstm_tf_keras_2_config.json#L84

vs 

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/test/resources/configs/keras1/imdb_lstm_tf_keras_1_config.json#L12

It seems model-import interprets your model as a keras 1 model. This shouldn't happen, as long as your yaml specifies the keras version like this: `"keras_version": "2.0.6"`

**Comment by Menion93** [comment]
Thank you for your reply, I'll post the model file on pastebin right here

[model](https://pastebin.com/qDWqjPW4)

Tomorrow I wil try to convert from keras 2 to keras 1.

I downloaded the zip on windows and it works, before the uploaded I changed its extension from .rar to .zip but Windows still manage to unzip it. Yes it is only 5kb, it is a small net.

Even if you try to create the model without importing the weights with this command

`            KerasModelImport.importKerasSequentialConfiguration(config.base_path_nn + trasnf + "-net_model.json");
`

The same error will appear

Here are the model and the weights on [GD](https://drive.google.com/open?id=0B1ceW-eLdVXURE1BSG4tOXN3Wnc)

**Comment by Menion93** [comment]
It seems that [this](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/utils/KerasModelUtils.java#L97) is unable to find the string "keras_version" as you pointed, but it is present actually.
Also [this ](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/utils/KerasModelUtils.java#L279) works correctly because the filed "class_name" is recognized in the json, so "keras_version" must be too because it is right down it. 
I suspect that [config.getFieldKerasVersion](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/utils/KerasModelUtils.java#L97) is not returning "keras_version" because if I change the value of "keras_version" in a string like "abc", the [exception](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/utils/KerasModelUtils.java#L108) is not thrown.

**Comment by maxpumperla** [comment]
@Menion93 this is simple to check, would you please start a debugger to see what `kerasMajorVersion` evaluates to? My suspicion is that it will return `1`, but it should be `2`. Still, it's a little confusing to me... have never seen this behaviour before.

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/utils/KerasModelUtils.java#L113

**Comment by Menion93** [comment]
@maxpumperla  I do not know how set a breakpoint on the source because I imported it in intelliJ with maven, so I have only the compiled code. Still in the debugger I saw in the parsed Json the field "keras_version" with value "2.0.8".

**Comment by rainjacket** [comment]
I don't understand this thread, isn't it known that version 0.9.1 doesn't support keras 2 models? Or is there a nuance I'm missing here.

**Comment by Menion93** [comment]
I did not know, but I asked it at my very first post :P 
So is there a version that support keras 2? @rainjacket

**Comment by rainjacket** [comment]
As it was explained to me, Keras 2 will work in the next stable version, as it's already supported by 0.9.2-SNAPSHOT.
