### ISSUE TITLE
OpenBlass stuck on sgemm operation

### ISSUE THREAD

**Issue by papperwing** [deeplearning4j/deeplearning4j#4132]
After several days of learning network it got stuck and is taking a lot of cpu and it is consuming large amount of memory too. Together with @raver119 we figured out it is stuck in sgemm operation in openblass. 

Here is added second thread dump [dump.txt](https://github.com/deeplearning4j/deeplearning4j/files/1348336/dump.txt) (I deleted first but  main #1 part was same by look).

It is stuck there from saturday 2017-09-30 14:13:26 now is monday 2017-10-02 10:48 so it is there for almost three days (not sure if it is stuck on same operation for whole time)

I am using UI file storage and EarlyStopping but based on @raver119 information it is probably not problem of these parts.

Here is model config in enlighted part: https://github.com/papperwing/image-net/blob/master/modules/image-net-model-creator/src/main/java/cz/muni/fi/image/net/model/creator/ModelBuilderImpl.java#L203-L254
Here is early stopping in enlighted part: https://github.com/papperwing/image-net/blob/master/modules/image-net-core/src/main/java/cz/muni/fi/image/net/core/manager/ImageNetTrainer.java#L234-L285

It also happend before several time (after several days of learning) but I didn't take thread dump before. It happend with alexNet cconfig after several day of training.

Unfortunately I dont have jmx connection attached there but I have that process still running hopping for miracle recovery :). So if there is any other additional information needed and there is not needed jmx connection to obtain it I can still provide information.

version of DL4J: 0.9.1
os: Debian
GPU: not used

**Comment by saudet** [comment]
Could you try with OpenBLAS 0.2.20?
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/openblas/

**Comment by papperwing** [comment]
It took four days of learning to get into that point, so it will probably take a while.

**Comment by papperwing** [comment]
`
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>openblas</artifactId>
            <version>0.2.20-1.3.4-SNAPSHOT</version>
        </dependency>`

Is this correct and desired dependency?

**Comment by saudet** [comment]
Use the "openblas-platform" one to get the binaries as well.

**Comment by saudet** [comment]
It might be a bug somewhere in the optimized functions of OpenBLAS, especially if you're using an AMD CPU. I've added some documentation for that here: https://deeplearning4j.org/native#fallback-mode
