### ISSUE TITLE
Improvement/clarrification of WeightInit.DISTRIBUTION

### ISSUE THREAD

**Issue by papperwing** [deeplearning4j/deeplearning4j#4133]
In the moment one must set weightInit in configuration of layer or network to WeightInit.Distribution and then one must set function .dist(). It is bit confusing. Could be there way that it is dealt same way as with updaters (nesterovs in particular) where you create new instance of weightInit and in that instance you set specifical parameters? 

Example:
.weightInit(new NormalDistribution().mean(0).sd(0.2*(2/inputCount+numberOfClasses))

Also if there is well defined interface of necessary things for weightInit, one can play with it a bit and try to use some exoctic funtion on their own.

**Comment by maxpumperla** [comment]
@papperwing I agree here. If time permits I want to refactor this soon.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/4326
