### ISSUE TITLE
Solution for serving models similar to TensorFlow serving

### ISSUE THREAD

**Issue by ghisvail** [deeplearning4j/deeplearning4j#4134]
I am currently using [TensorFlow serving](https://github.com/tensorflow/serving) to serve machine learning models serialized from TensorFlow in a production environment (AWS-based). I was wondering whether something similar could be achieved with DL4J?

**Comment by tomthetrainer** [comment]
Skymind provides SKIL for model serving https://skymind.ai/products

Or you could manage things manually on your own if the model versioning and management piece is not too complicated. 

For example I have taken a few examples and wrapped a simple web interface around the model to create a rest service.  

See, 
https://deeplearning4j.org/demo-classifier-vgg16

And
http://engineering.skymind.io/how-to-build-an-image-classification-web-app-with-vgg-16

Basically it is similar to deploying another java app. 

mvn package, to build a jar with dependencies. 

Ship jar to AWS server. 

Execute class

java -cp jar_with_dependencies.jar path_to_class

Let me know more details and I can help advise. 

Many models, with model versioning and monitoring.. I recommend SKIL. 

Few models with relatively static versioning, you can wrap up your code and deploy. 

To get from Keras with a tensorflow backend you can use our keras model import. 

To get from base tensorflow computation graph, to dl4j.. this is a new feature, and I would wait for an engineer to provide details. 

We may have an ami with dependencies for dl4j already loaded.

**Comment by ghisvail** [comment]
> Let me know more details and I can help advise.

We are talking an application with a handful of models which are run independently for each request.

> Many models, with model versioning and monitoring.. I recommend SKIL.

Define "many" and "monitoring" in this context?

> Few models with relatively static versioning, you can wrap up your code and deploy.

Define "static" in this context?

Model-wise, I suspect we are currently on the "few" more than the "many" side.

> To get from Keras with a tensorflow backend you can use our keras model import.

I watched the tutorial on the Skymind Youtube channel. Looked pretty straightforward indeed.

> To get from base tensorflow computation graph, to dl4j.. this is a new feature, and I would wait for an engineer to provide details.

Our models are produced from a mixture of TF and Keras behind the scenes. The feature you describe could help us transition from a different model serving solution. Would that be specific to SKIL though?

**Comment by tomthetrainer** [comment]
We announced our release of SKIL last week, 

https://skymind.ai/platform

Also as a side demonstration I built some REST wrappers as Java Servlets, 

https://github.com/SkymindIO/RestDemos

Do we need to keep this ticket open?

**Comment by maxpumperla** [comment]
I vote to close

**Comment by tomthetrainer** [comment]
Closing this issue.
