### ISSUE TITLE
occurrences cannot be negative: -33

### ISSUE THREAD

**Issue by Tum4ik** [deeplearning4j/deeplearning4j#4144]
[files.zip](https://github.com/deeplearning4j/deeplearning4j/files/1356108/files.zip)
#### Issue Description

Please describe our issue, along with:
- expected behavior - simple evaluating of network
- encountered behavior - exception

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - 0.9.1
* platform information (OS, etc) - Windows7 64-bit
* CUDA version, if used - not used
* NVIDIA driver version, if in use - 385.69

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by AlexDBlack** [comment]
Can you post the full stack trace you are getting in a gist? (gist.github.com)
Obviously we can't run your code snippets without the full project (which we probably don't need to debug this).

**Comment by Tum4ik** [comment]
Hi. Thank you for reply. But I think we can close this topic because I've found my mistake. I had in my answers matrix ements with values 1 and 2 instead 0 and 1.
