### ISSUE TITLE
MultiDataSetIterator -- Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Hadi-H** [deeplearning4j/deeplearning4j#4147]
#### Issue Description
I get "Segmentation fault (core dumped)" error when I try to use MultiDataSetIterator in a ComputationGraph having 2 output classifier. Here is a link to the code:
https://gist.github.com/Hadi-H/443a21f21204b5e6a88b9869a45994f3

This is my pom file: https://gist.github.com/Hadi-H/5d96a5309acf7e52d812fdcde9b69b71
OS: Ubuntu Server 16.04 LTS
Config: 16 vcpus, 64 GB memory

This is the error, which I get:
https://gist.github.com/Hadi-H/bd14f194c0785bdd0c07a54c01877563

Here is a link to the /home/hadi/jarFiles/hs_err_pid46365.log:
https://gist.github.com/Hadi-H/ece4910059a400e619c823334fc26bbd
Any help is very appreciated.

**Comment by saudet** [comment]
Which version of DL4J are you using?

**Comment by Hadi-H** [comment]
Thanks for the prompt reply. The dl4j version is 0.9.1. I've also attached my pom file

**Comment by raver119** [comment]
can you please add /home/hadi/jarFiles/hs_err_pid46365.log to the issue?

**Comment by Hadi-H** [comment]
Sure, I've added the hs_err_pid46365.log

**Comment by AlexDBlack** [comment]
Closing as outdated - we haven't had reports of this since, and there has been a ton of workspace-related fixes since 0.9.1 (which is by far the most likely candidate for these sorts of crashes).
