### ISSUE TITLE
naming rules

### ISSUE THREAD

**Issue by clavvis** [deeplearning4j/deeplearning4j#4151]
Hi all,

I suggest these naming rules:

a) every name of interface starts with "I" (for example IConfiguration)

b) every name of enum starts with "E" (for example EDataType)

c) every name of abstract class starts with "A" (for example ABaseLayer)

These naming rules make orientation in project more easy.

Have a nice day

  clavvis

**Comment by huitseeker** [comment]
Thanks for the suggestion, we'll take it under consideration.
