### ISSUE TITLE
Word2Vec's wordsNearest() is very slow.

### ISSUE THREAD

**Issue by lingvisa** [deeplearning4j/deeplearning4j#4154]
#### Issue Description

My testing code is like the following:
 
```
String path = new ClassPathResource("models/GoogleNews-vectors-negative300.bin.gz").getFile().getAbsolutePath();
Word2Vec word2vec = WordVectorSerializer.readWord2VecModel(new File(path))

               String word = "beautiful";          
               for (int i=0; i<10000000; i++) {
                        Collection<String> words = word2vec.wordsNearest(word, 10);
                        log.info(String.valueOf(i));
                    }

```
#### Version Information
My dl4j is 0.9.1, and I am running on Windows 10 machine, 2 cores, 16G RAM. What I wanted to do is to find related words of a word in a loop, and in that loop a large number of files are processed. The model I used in the testing code above is the public Google news word2vec model, which is very slow, if you run the testing code and watch how far it is going. My own model is smaller and it runs quicker, but still it's slows, which essentially prevents me from calling this method in my application.
    
It would be very nice to know what's the issue and whether there is any way to make it reasonably faster to be used in practical use cases like I described above.

**Comment by raver119** [comment]
Not a real issue.
