### ISSUE TITLE
duplicate classes

### ISSUE THREAD

**Issue by clavvis** [deeplearning4j/deeplearning4j#4157]
I found a lot of duplicate classes (exactly file names). Some are not problem. But some are very unhappy solution. For me are important Layer classes.

Filter: "Layer"
ActivationLayer.java         \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
ActivationLayer.java         \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers
BaseLayer.java               \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
BaseLayer.java               \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers
BaseOutputLayer.java         \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
BaseOutputLayer.java         \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers
BaseRecurrentLayer.java      \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
BaseRecurrentLayer.java      \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers\recurrent
CenterLossOutputLayer.java   \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
CenterLossOutputLayer.java   \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers\training
Convolution1DLayer.java      \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
Convolution1DLayer.java      \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers\convolution
ConvolutionLayer.java        \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
ConvolutionLayer.java        \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers\convolution
DenseLayer.java              \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
DenseLayer.java              \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers\feedforward\dense
DropoutLayer.java            \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
DropoutLayer.java            \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers
EmbeddingLayer.java          \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
EmbeddingLayer.java          \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers\feedforward\embedding
FrozenLayer.java             \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers\misc
FrozenLayer.java             \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers
GlobalPoolingLayer.java      \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
GlobalPoolingLayer.java      \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers\pooling
Layer.java                   \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\api
Layer.java                   \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
LayerVertex.java             \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\graph
LayerVertex.java             \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\graph\vertex\impl
LossLayer.java               \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
LossLayer.java               \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers
OutputLayer.java             \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
OutputLayer.java             \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers
RnnOutputLayer.java          \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
RnnOutputLayer.java          \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers\recurrent
Subsampling1DLayer.java      \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
Subsampling1DLayer.java      \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers\convolution\subsampling
SubsamplingLayer.java        \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
SubsamplingLayer.java        \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers\convolution\subsampling
Yolo2OutputLayer.java        \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers\objdetect
Yolo2OutputLayer.java        \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers\objdetect
ZeroPadding1DLayer.java      \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
ZeroPadding1DLayer.java      \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers\convolution
ZeroPaddingLayer.java        \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\conf\layers
ZeroPaddingLayer.java        \deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers\convolution
Files count: 44

First could be LayerConfiguration (for example).
Second could be (for example) LayerData, LayerProperties.

Unique class names are much more better than using full class names.

[DFN_All.txt](https://github.com/deeplearning4j/deeplearning4j/files/1366750/DFN_All.txt)

**Comment by agibsonccc** [comment]
In practice, you  (the user) will never see this. These are meant to have the implementations easily discoverable.  Maybe it's not ideal but honestly the config DSL and packaging are pretty clear.

**Comment by clavvis** [comment]
I'm codding user. I will see it all my codding time.

**Comment by agibsonccc** [comment]
If you're using the layer config imports properly  you should be fine. You shouldn't be directly instantiating layer implementations. You use multi layer network with the configurations.

**Comment by clavvis** [comment]
I would like to use deep belief network. I investigate example VariationalAutoEncoderExample. Author use both classes VariationalAutoEncoder. One time is used full class name. If I need to show internal layer values I need to use full class name too. It's really not ideal.
