### ISSUE TITLE
NaN in word coordinates after running tsne plot

### ISSUE THREAD

**Issue by jarutis** [deeplearning4j/deeplearning4j#416]
I was running Word2vec [example](http://deeplearning4j.org/word2vec.html) on a small (10k sentence) dataset everything went fine, but I got NaN in words coordinates during tsne ploting.

```scala
val tsne = new BarnesHutTsne.Builder()
  .setMaxIter(1000)
  .stopLyingIteration(250)
  .learningRate(500)
  .useAdaGrad(false)
  .theta(0.5)
  .setMomentum(0.5)
  .normalize(true)
  .usePca(false)
  .build()
vec.lookupTable().plotVocab(tsne)
```

Setting `Nd4j.ENFORCE_NUMERICAL_STABILITY = true` fixed the problem.

**Comment by agibsonccc** [comment]
This has been fixed.
