### ISSUE TITLE
Improve parameter averaging from single, centralized service to ring/tree topology

### ISSUE THREAD

**Issue by romeokienzler** [deeplearning4j/deeplearning4j#4160]
#### Improve parameter averaging from single, centralized service to ring/tree topology

Currently, DL4J uses a centralized parameter averaging service and AERON as middle-ware

As described [here](https://arxiv.org/abs/1708.02188) using a ring/tree topology for the parameter averaging pass is significantly faster

Are there any plans to make this available for DL4J as well?

**Comment by raver119** [comment]
DL4J, right now has 2 modes: 
- centralized params averaging (it doesn't involve Aeron)
- all-to-all gradients sharing (it involves Aeron for out-of-spark comms)

**Comment by romeokienzler** [comment]
Cool, so what is the communication pattern for the 2nd option?

N:N? how are the averaged gradients actually computed?

**Comment by raver119** [comment]
http://nikkostrom.com/publications/interspeech2015/strom_interspeech2015.pdf

**Comment by romeokienzler** [comment]
delayed individual weight propagation seems to be a reasonable and state-of-the-art way of doing it
