### ISSUE TITLE
Javadoc typo - MultiLayerNetwork.java

### ISSUE THREAD

**Issue by ajohnsonz** [deeplearning4j/deeplearning4j#4162]
#### Issue Description

The MultiLayerNetwork method `score(DataSet dataset)` has javadoc saying: 

> Sets the input and labels and returns a score for the prediction with respect to the true labels This is equivalent to score(DataSet, boolean) with training==true

 
This should read `with training==false`

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/4804
