### ISSUE TITLE
More flexible BalancedPathFilter

### ISSUE THREAD

**Issue by eypros** [deeplearning4j/deeplearning4j#4166]
Enhancement proposal:

Since `BalancedPathFilter` returns a completely balanced dataset among classes and `RandomPathFilter` a just random permutation of the samples (or a random permuted subset of the whole dataset) maybe a more flexible approach between those two might be handy is some cases.

Case study: the Flowers dataset used in VGG16 transfer-learning examples downloads 3670 images of flowers split into 5 classes as follows:
Daisy 633
Dantelion 898
Roses 641
Sunflowers 699
Tulips 799

`BalancedPathFilter` can at maximum return 5*633=3165 samples in total. Meaning 505 samples are not used. `RandomPathFilter` on the other hand can return all but in an unbalanced fashion. 
The unbalance in this case is not severe though. Taking as measure the smallest class we have:
The largest class is 898/633 = 1.41 times the smallest class.
So, in this case there could be a  `BalancedPathFilter` with an extra parameter to cope with the cases where we want a pretty much balanced set but with an allowed unbalanced inside some limits e.g. 1.5 time the smallest class. In this case all samples in Flowers dataset would be included and also some distribution of sample order could be enforced (obviously with the new unbalance the previous approach wont work).

**Comment by saudet** [comment]
Note that the original intent was that on each epoch, the whole set of images could be resampled. The current API doesn't make that easy to do I think, but if we do it that way, unless we're doing only one epoch, all the images have a chance of getting used.

In any case, let's move this discussion to https://github.com/deeplearning4j/DataVec/issues/347, thanks!
