### ISSUE TITLE
UCISequenceClassificationExample link on tour page is broken.

### ISSUE THREAD

**Issue by SanderGielisse** [deeplearning4j/deeplearning4j#4172]
Link on the tour page is broken.
On the tour page https://deeplearning4j.org/examples-tour section UCISequenceClassificationExample.java

Redirects to;
https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/seqClassification/UCISequenceClassificationExample.java

Which shows;
Page not found.

Link should instead by;
https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/seqclassification/UCISequenceClassificationExample.java

Note the capital in seqclassification and seqClassification.

**Comment by tomthetrainer** [comment]
Thanks for the report, I fixed it.
