### ISSUE TITLE
Trying to use regression with an input image and an output image

### ISSUE THREAD

**Issue by DonaldAlan** [deeplearning4j/deeplearning4j#4174]
#### Issue Description

I'm trying to learn to colorize images. So want to do a regression. 

If I make recordReader return a list of Writables of length 2 (first being a grey image of shape `[1, 1, 100, 100]`, and the second being a flattened colored image of shape `[1, 30000]`) and then call the constructor `public RecordReaderDataSetIterator(RecordReader recordReader, int batchSize, int labelIndexFrom, int labelIndexTo, boolean regression)` with `labelndexFrom=labelIndexTo=1` and `regression=true`, I get `a java.lang.IndexOutOfBoundsException: Index: 1, Size: `  at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritablesBatched(RecordReaderMultiDataSetIterator.java:298).

But if I make the RecordReader return a list where the 0th element is the grey image, and the subsequent 30000 elements in the list (for a 100x100 image) are the colored pixels (DoubleWritables), and with labelIndexTo= 30000, I get a different exception:` java.lang.UnsupportedOperationException: Unknown operation for batch reader` in convertWritablesBatched of RecordReaderMultiDataSetIterator.

Is my approach wrong? Do I need to write a custom version of RecordReaderDataSetIterator?

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version:    dl4j-examples (synched with master pretty recently)
* platform information (OS, etc): Windows 10
* CUDA version, if used  
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by DonaldAlan** [comment]
Color.txt is a copy of Colorizer.java  (The UI doesn't let me attach a java file, and the code is too preliminary to check in.)
[Colorizer.txt](https://github.com/deeplearning4j/deeplearning4j/files/1385125/Colorizer.txt)

[ColorizerRecordReader.txt](https://github.com/deeplearning4j/deeplearning4j/files/1385126/ColorizerRecordReader.txt)

[ColorizerRecordReader2.txt](https://github.com/deeplearning4j/deeplearning4j/files/1385127/ColorizerRecordReader2.txt)

**Comment by saudet** [comment]
The correct line is commented out:

> //DataSetIterator iter = new RecordReaderDataSetIterator(rr,batchSize, 1,
1, true);

**Comment by DonaldAlan** [comment]
@saudet,   The line right afterward is the same, because `labelIndexTo` is set to 1.    

Here are more details about the exception:
```
o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 32
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [3.5GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
o.n.l.j.o.e.CudaExecutioner - Device name: [GeForce GTX 1070]; CC: [6.1]; Total/free memory: [8589934592]
parent.size() = 1
In main: 2 writables for the image, with get(0): class org.datavec.api.writable.NDArrayWritable with get(1): class org.datavec.api.writable.NDArrayWritable
arrayWritable0's indArray is of length 1024 with shape [1, 1, 32, 32]
arrayWritable1's indArray is of length 3072 with shape [1, 3072]
o.d.n.m.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: NONE; inference: SEPARATE]
Epoch=====================0
parent.size() = 1
Exception in thread "ADSI prefetch thread" java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$AsyncPrefetchThread.run(AsyncDataSetIterator.java:442)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritablesBatched(RecordReaderMultiDataSetIterator.java:298)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertFeaturesOrLabels(RecordReaderMultiDataSetIterator.java:267)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:240)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:177)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:306)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:393)
	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:51)
	at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$AsyncPrefetchThread.run(AsyncDataSetIterator.java:423)
```

**Comment by saudet** [comment]
Are you sure you are running the latest code from the master branch? Could
you also post your pom.xml file?

**Comment by DonaldAlan** [comment]
I re-pulled from master and rebuilt but I still get that IndexOutOfBoundsException. Here's my pom.xml (renamed to pom.txt):
[pom.txt](https://github.com/deeplearning4j/deeplearning4j/files/1385544/pom.txt)

**Comment by DonaldAlan** [comment]
BTW, I notice that Intellij complains that "The library source does not match the bytecode for class RecordReaderMultiDatasetIterator", though the equivalent line shows up whether I view source or the class file.

**Comment by raver119** [comment]
> The library source does not match the bytecode for class RecordReaderMultiDatasetIterator

This message should be ignored, you see it due to Lombok.

**Comment by DonaldAlan** [comment]
Updated Colorizer.txt (.java) fixing some minor bugs mostly irrelevant to the exception I'm seeing.
[Colorizer.txt](https://github.com/deeplearning4j/deeplearning4j/files/1385896/Colorizer.txt)

**Comment by saudet** [comment]
You're still using 0.9.1 apparently:
```xml
        <version>0.9.1</version>
```
That line should be "0.9.2-SNAPSHOT".

**Comment by DonaldAlan** [comment]
Sorry, I changed it to 0.9.2-SNAPSHOT and reimported and rebuilt but I continue to get the same exception.

**Comment by DonaldAlan** [comment]
@saudet, when you say I should use 0.9.2-SNAPSHOT, please clarify which pom.xml and which lines.  There's a pom.xml in dl4j-examples/, but there's also one in dl4j-examples/dl4j-examples/.  I presume you mean the former.  But also, do you mean that I should change line 9?:
```
    <groupId>org.deeplearning4j</groupId>
    <artifactId>deeplearning4j-examples-parent</artifactId>
    <version>0.9.1</version>  <!--   here? -->
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>
```
Or do you mean I should some of the lines further below?:
```
        <nd4j.version>0.9.1</nd4j.version>
        <dl4j.version>0.9.1</dl4j.version>
        <datavec.version>0.9.1</datavec.version>
        <arbiter.version>0.9.1</arbiter.version>
        <rl4j.version>0.9.1</rl4j.version>
```

**Comment by saudet** [comment]
Ah, you're using the parent pom file from the examples, so yes we need to update those as well.

**Comment by DonaldAlan** [comment]
I'm sorry, you need to be more explicit. What lines do I update exactly, please.

**Comment by saudet** [comment]
Simply replace every instance of "0.9.1" by "0.9.2-SNAPSHOT".

**Comment by DonaldAlan** [comment]
I replaced 0.9.1 by 0.9.2-SNAPSHOT in the root pom.xml and in the subdirectories' pom.xmls. Then I get:
```
Error:(4, 47) java: cannot find symbol
  symbol:   class InvalidKerasConfigurationException
  location: package org.deeplearning4j.nn.modelimport.keras
Error:(5, 47) java: cannot find symbol
  symbol:   class UnsupportedKerasConfigurationException
  location: package org.deeplearning4j.nn.modelimport.keras
Error:(47, 65) java: cannot find symbol
  symbol:   class InvalidKerasConfigurationException
  location: class org.deeplearning4j.examples.transferlearning.vgg16.FitFromFeaturized
Error:(26, 58) java: cannot find symbol
  symbol:   class UnsupportedKerasConfigurationException
  location: class org.deeplearning4j.examples.transferlearning.vgg16.dataHelpers.FlowerDataSetIteratorFeaturized
```
etc.

**Comment by saudet** [comment]
That means you'll need to update your code to reflect changes in the API...

**Comment by DonaldAlan** [comment]
It's not my code that failed to compile. It's pre-existing code.

**Comment by saudet** [comment]
Then remove it! Don't try to run someone's else code

**Comment by DonaldAlan** [comment]
Well, you needn't help debug every step.  Sorry.   I fixed the compilation errors (by removing the imports and generalizing some thrown exceptions).  Now it compiles!  But when I run it, I get (progress!):
```
Exception in thread "main" java.lang.NoSuchMethodError: org.nd4j.linalg.learning.config.IUpdater.applySchedules(ID)V
	at org.deeplearning4j.nn.conf.layers.LayerValidation.updaterValidation(LayerValidation.java:85)
	at org.deeplearning4j.nn.conf.layers.LayerValidation.updaterValidation(LayerValidation.java:35)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.copyConfigToLayer(NeuralNetConfiguration.java:1378)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.configureLayer(NeuralNetConfiguration.java:1318)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.build(NeuralNetConfiguration.java:1301)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.build(NeuralNetConfiguration.java:304)
	at org.deeplearning4j.examples.convolution.Colorizer.makeTrainingModel(Colorizer.java:302)
	at org.deeplearning4j.examples.convolution.Colorizer.main(Colorizer.java:128)
```

**Comment by DonaldAlan** [comment]
I'm going to use a ComputationGraph instead of a MultiLayerNetwork, so that I can use skip connections.  And I'll follow https://blog.floydhub.com/colorizing-b&w-photos-with-neural-networks/ (per Adam's suggestion) and use a LAB color model.  So this issue is moot. Closing.
