### ISSUE TITLE
build failure on the current master

### ISSUE THREAD

**Issue by kepricon** [deeplearning4j/deeplearning4j#4184]
#### Issue Description

looks like updated nd4j apis is not applied to the dl4j
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/kepricon/git/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/layers/convolution/subsampling/SubsamplingLayer.java:[34,59] package org.nd4j.linalg.api.ops.impl.transforms.convolution does not exist
[INFO] 1 error
```
here is the more logs : https://gist.github.com/kepricon/f399777b1b0675b827c9857a0f2bcd28

#### Version Information

* Deeplearning4j version
dl4j current master(a30cdfd69ca8270aaa0b8bab9bf5247a2ef55993)
nd4j current master(1696dbb839a32f0c6353532c0427a6fe2af42895)

**Comment by agibsonccc** [comment]
Did you update dl4j? I definitely fixed this.

**Comment by agibsonccc** [comment]
Sorry try again I forgot to merge this: https://github.com/deeplearning4j/deeplearning4j/pull/4176
