### ISSUE TITLE
Workspaces usage in WordVector

### ISSUE THREAD

**Issue by Treiblesschorle** [deeplearning4j/deeplearning4j#4188]
The recent Workspaces feature seems not to be used in Word2Vec or Doc2Vec training.
E.g. here: https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/sequencevectors/SequenceVectors.java#L192-L272
Is there any plan to add that?

**Comment by raver119** [comment]
Yep, there is such plan.

ср, 18 окт. 2017 г. в 13:16, David Kolb <notifications@github.com>:

**Comment by dietzc** [comment]
> Yep, there is such plan.

is there a timeline, expected release etc for this?

**Comment by raver119** [comment]
Implemented
