### ISSUE TITLE
output method of convolutional net does not check input shape

### ISSUE THREAD

**Issue by schrum2** [deeplearning4j/deeplearning4j#4200]
In version 0.9.1 of DL4J:

I've found that in a convolutional network, the "output" method will happily accept inputs with an incorrect shape. Specifically, set up a convolutional network using MultiLayerConfiguration and finalize it using 

setInputType(InputType.convolutional(20, 10, 2)).build();

This network should accept inputs with height 20, width 10, and 2 channels. Then, I can create an input of all zeros like so:

double[] linearInputs = new double[400];
int[] inputShape = new int[] {1, 2, 20, 10};
INDArray input = Nd4j.create(linearInputs, inputShape, 'c');
INDArray output = model.output(input, false); 

This will work fine. HOWEVER, the following code will also execute without error:

double[] linearInputs = new double[400];
int[] inputShape = new int[] {1, 2, 10, 20}; // <--- Just swapped order of 10 and 20
INDArray input = Nd4j.create(linearInputs, inputShape, 'c');
INDArray output = model.output(input, false); 

The code should really throw an exception in the case where the input shape is incorrect.

**Comment by AlexDBlack** [comment]
Can you post the full network configuration you are using?
I was under the impression that this should be checked/handled already.

**Comment by schrum2** [comment]
https://gist.github.com/schrum2/a206374869d08aebdfdab889f3d469d2

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/4326
