### ISSUE TITLE
TestSetRegressionScoreFunction.class not jackson/json serialization

### ISSUE THREAD

**Issue by cqiaoYc** [deeplearning4j/deeplearning4j#4201]
There is not jackson/json serialization for TestSetRegressionScoreFunction.class, and using it in arbiter can result to an exception thrown.

#### Version Information

* Deeplearning4j version: 0.9.1

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/Arbiter/pull/113
