### ISSUE TITLE
Suggesting trivial small corrections to be done in transfer-learning page 

### ISSUE THREAD

**Issue by jesuino** [deeplearning4j/deeplearning4j#4204]
#### Issue Description

There are a few small corrections that must be done in documentation [1]

- I believe that a casting is required on the following code:
~~~
ComputationGraph pretrainedNet = zooModel.initPretrained(PretrainedType.IMAGENET);
~~~
The following seems to work for me:
~~~
ComputationGraph pretrainedNet = (ComputationGraph) zooModel.initPretrained(PretrainedType.IMAGENET);
~~~

- The weight init WeightInit.Xavier is in lower case, it should be WeightInit.XAVIER
- The double quotes sometimes are using character ” when it should be "

[1] ComputationGraph pretrainedNet = zooModel.initPretrained(PretrainedType.IMAGENET);

#### Version Information

Dl4J 9.1

**Comment by chrisvnicholson** [comment]
i think i fixed this. @crockpotveggies, you may be using a text editor that's converting your straight quotes into curly ones, which might result in an error.
