### ISSUE TITLE
Updater parameters are overwritten by BaseLayer default parameters

### ISSUE THREAD

**Issue by slang03** [deeplearning4j/deeplearning4j#4207]
##### Expected behavior
Updater parameters set by `.updater(new Adam(...))` should not be overwritten by default initialization of `BaseLayer` parameters. 

##### Encountered behavior
`BaseLayer` initializes `adamMeanDecay` and `adamVarDecay` with 0  [here](https://github.com/deeplearning4j/deeplearning4j/blob/deeplearning4j-0.9.1/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/layers/BaseLayer.java#L73). When setting an updater via `updater(new Adam(...))` the Adam object gets validated ([here](https://github.com/deeplearning4j/deeplearning4j/blob/deeplearning4j-0.9.1/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/NeuralNetConfiguration.java#L1318)) on the `build()` call of the netconfig - checking whether they are NaN or not. Not NaN means set by the user and therefore the Adam object parameter gets overwritten [here](https://github.com/deeplearning4j/deeplearning4j/blob/deeplearning4j-0.9.1/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/layers/LayerValidation.java#L105). This is the case since the BaseLayer initializes its parameters with 0 and the validation therefore assumes, this was set by the user.
#### Version Information

* Deeplearning4j version: v0.9.1
* platform information (OS, etc): Linux

**Comment by raver119** [comment]
I'm afraid this issue is irrelevant after recent API overhaul.
