### ISSUE TITLE
"mvn test" is broken

### ISSUE THREAD

**Issue by EronWright** [deeplearning4j/deeplearning4j#421]
Many of the unit tests rely on resources from the dl4j-test-resources module, and locate the resource with `ClassPathResource::getFile()`.   That approach works in the IntelliJ IDE but doesn't work on the command-line.  The reason is, in the latter case the test-resources dependency is provided as a JAR on the classpath (and `getFile` cannot formulate a path to an enclosed resource).

```
$ cd deeplearning4j-core
$ mvn -Dtest=CSVDataSetIteratorTest test

java.io.FileNotFoundException: class path resource [csv-example.csv] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/Users/eron/.m2/repository/org/deeplearning4j/dl4j-test-resources/0.0.3.3.5.alpha2-SNAPSHOT/dl4j-test-resources-0.0.3.3.5.alpha2-SNAPSHOT.jar!/csv-example.csv
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:205)
	at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:52)
	at org.deeplearning4j.datasets.iterator.CSVDataSetIteratorTest.testCSV(CSVDataSetIteratorTest.java:32)
```

This problem will preclude running the unit tests in travis-ci.

**Comment by agibsonccc** [comment]
Interesting. We can change this to InputStream based parsing which should generalize a lot better. Thanks for flagging this.

**Comment by EronWright** [comment]
I will work on a minimal solution for this.
