### ISSUE TITLE
Tmp files clean-up behaviour

### ISSUE THREAD

**Issue by Treiblesschorle** [deeplearning4j/deeplearning4j#4211]
Encountered behavior:
Currently, files like 'restoreXXXXXXXXmultiLayer' and 'paravecXXXXXXXXXXX' which are created by the ModelSerializer and WordVectorSerializer will be deleted after the JVM exits.

Desired behavior:
If you have a very long running loop serializing and deserializing models, this will fill up the tmp dir. I wonder if they could be directly deleted after the model was loaded?

* Deeplearning4j version: 0.9.1
* platform information (OS, etc): Windows 10

**Comment by AlexDBlack** [comment]
I believe ModelSerializer was fixed for this a long time ago... can't speak to WordVectorSerializer, however.

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/util/ModelSerializer.java
