### ISSUE TITLE
next() on SequenceRecordReaderDataSetIterator transforms data wrong when preprocessors are set

### ISSUE THREAD

**Issue by Tschigger** [deeplearning4j/deeplearning4j#4213]
#### Files

[labels_0.txt](https://github.com/deeplearning4j/deeplearning4j/files/1421750/labels_0.txt)
[features_0.txt](https://github.com/deeplearning4j/deeplearning4j/files/1421752/features_0.txt)

**What I am doing**
To play around, I constructed a time series which has 1 feature per timestep. Features are uniformly distributed between 100,000 and 100,001, so mean is 100,000.5. I then try to apply a normalizer to the iterator.

```
val startNumber = 0
val endNumber = 0

val featureReader = CSVSequenceRecordReader(0, ",")
val labelReader = CSVSequenceRecordReader(0, ",")
featureReader.initialize(NumberedFileInputSplit ("features_%d.txt", startNumber, endNumber))
labelReader.initialize(NumberedFileInputSplit ("labels_%d.txt", startNumber, endNumber))

val miniBatchSize = 1
val iter = SequenceRecordReaderDataSetIterator(featureReader, labelReader, miniBatchSize, 0, true, SequenceRecordReaderDataSetIterator.AlignmentMode.ALIGN_END)

val normalizer = NormalizerMinMaxScaler(0.0,1.0)
normalizer.fit(iter)
iter.setPreProcessor(normalizer)
val hopeFullyNormalized = iter.next()
```

**What I expect**

A dataset with features between 0.0 and 1.0

**What I get**

A dataset with features between -99,999 and -100,000. So it seems the transformation has been applied twice. The same thing happens when I use `NormalizerStandardize` instead of `NormalizerMinMaxScaler`. Here, transformation is applied twice too, which results in features with mean -346,707 and std 3.44 instead of mean 0 and std 1. Interestingly, both normalizers have the correct properties after fitting them to the iter. Also, if I do **not** use iter.setPreProcessor(), but just pull the dataset with `iter.next()` and do the transformation manually with `normalizer.transform(dataset)`, everything works as expected.

#### Version Information

* Deeplearning4j version 0.9.1
* Ubuntu 16.04
* Happens under native and CUDA.

**Comment by Tschigger** [comment]
I wrote before that if I transform the dataset manually (without setting the preprocessor to the iterator), everything works fine. But this is only true for `NormalizerMinMaxScaler`. With `NormalizerStandardize`, I get features with a mean of -49.33 and an std of ~1 when transforming manually.

**Comment by Tschigger** [comment]
https://github.com/eraly/dl4j-RNNs/blob/master/src/main/java/io/skymind/training/ibm/recurrent/seqClassification/UCISequenceClassificationExample.java

has the same issue, i.e. if you call `trainData.next()` after line 83, normalization is messed up.

**Comment by AlexDBlack** [comment]
I ran the code on master - normalization is fine.
This was fixed I believe here: https://github.com/deeplearning4j/deeplearning4j/commit/6e76c49e0df0654643a437ce77c7acb9874e30cc#diff-c9c0fc7047f7f8698cf81713fe92829d
