### ISSUE TITLE
Performance comparison with parallel or non-parallel tokenzation in Word2Vec example 

### ISSUE THREAD

**Issue by lingvisa** [deeplearning4j/deeplearning4j#4218]
#### Issue Description
In running the default Word2VecRawTextExample example on my Ubuntu machine Intel i7-6700, I noticed that when "allowParallelTokenization()" is set to 'false', the vocabulary construction process is several times faster than when it's set to "true". In my case, "tokenization" is very heavy, and currently, even if it's set to 'true' on a server with multiple cores and large amount of text, my CPU utilization is always close to about 50%. I hope to be able to use more CPU resources for language analysis process (which comes from the 'tokenization' process) to speed up the vocabulary construction. I noticed that after vocabulary construction is done, the 'learning' stage is fully utilizing CPU, nearly 90% on average, and that's what i want for tokenization stage.

In my application, I pass each sentence as a string to the nlp engine. The engine does all kinds of analysis including the tokenization and returns results to me. So in this typical case, CPU needs to optimizally used for NLP analysis, otherwise, it has no other major work to do but to wait. 

On my Windows machine, 'false' also runs faster, although difference is smaller comopared to Ubuntu. But again, 'vocubalary construction' or tokenization uses little CPU, about 10%.

I hope CPU is utilized in vocabulary construction in a similar pattern as 'leaning' stage. The latter uses CPU more meaningfully. It would be nice at least to have a way to allow more CPU usage during tokenization.

Two logs I tested on two settings are here:
https://gist.github.com/lingvisa/c3c8125b8fd5b0f6bc16ab838d120223
https://gist.github.com/lingvisa/0e44aaafab91931c246edf94a1468c4c

**Comment by raver119** [comment]
So, i've checked source code one again and applied few tweaks. but logic still stays the same: if you're using simple tokenizer (like whitespace one) - you don't need multithreaded tokenization. All those threads and nested buffers just won't pay back. At other hand - if tokenizer itself IS computation-heavy - all that will be paying back good enough.

All depends on actual tokenizer.

**Comment by lingvisa** [comment]
Thanks, raver. So the tweaks going to be 0.9.2 release and what's the time frame?
