### ISSUE TITLE
ComputationGraph example shows increasing memory usage until failure

### ISSUE THREAD

**Issue by bixbyr** [deeplearning4j/deeplearning4j#4224]
This code runs for a minute or two with linearly growing memory usage, then terminates with an out of memory exception. The examples are very small data, and the ComputationGraph has only ~24M parameters.

Scala: 2.12.12
OS: Windows 10 (sadly)
Memory: 16GB
JVM args: -Xms1G -Xmx2G -Dorg.bytedeco.javacpp.maxbytes=8G -Dorg.bytedeco.javacpp.maxphysicalbytes=8G

``
import org.deeplearning4j.nn.conf.{NeuralNetConfiguration, WorkspaceMode}
import org.deeplearning4j.nn.conf.graph.ElementWiseVertex
import org.deeplearning4j.nn.conf.inputs.InputType
import org.deeplearning4j.nn.conf.layers._
import org.deeplearning4j.nn.graph.ComputationGraph
import org.nd4j.linalg.lossfunctions.LossFunctions.LossFunction.{MSE, NEGATIVELOGLIKELIHOOD}
import org.nd4j.linalg.learning.config.Nesterovs
import org.nd4j.linalg.activations.Activation.{RELU, TANH}
import org.deeplearning4j.nn.conf.ConvolutionMode.Same

class MultiTaskNetwork {

  val l2RegParam = 10e-4
  val momentumParam = 0.9

  // todo Needs rate schedule for learning rate
  private val networkBaseConf = new NeuralNetConfiguration.Builder()
    .trainingWorkspaceMode(WorkspaceMode.SEPARATE)
    .learningRate(0.01)
    .updater(new Nesterovs(momentumParam))
    .graphBuilder()
    .setInputTypes(InputType.convolutional(17,19,19))
    .addInputs("input")
    .addLayer("baseConvolution", new ConvolutionLayer.Builder(Array(3,3), Array(1,1)).convolutionMode(Same).nIn(17).nOut(256).l2Bias(l2RegParam).build, "input")
    .addLayer("baseBatchNorm", new BatchNormalization.Builder().build, "baseConvolution")
    .addLayer("baseReLu", new ActivationLayer.Builder().activation(RELU).build, "baseBatchNorm")

  private val (networkTrunkConf, lastBlockOutput) = (1 to 20).foldLeft((networkBaseConf, "baseReLu")) {
    case ((partialNetworkConf, inputName), blockNumber) =>
      /*
      Each residual block applies the following modules sequentially to its input:
      (1) A convolution of 256 filters of kernel size 3 ×  3 with stride 1
      (2) Batch normalization
      (3) A rectifier nonlinearity
      (4) A convolution of 256 filters of kernel size 3 ×  3 with stride 1
      (5) Batch normalization
      (6) A skip connection that adds the input to the block
      (7) A rectifier nonlinearity
       */

      val confWithNextBlock = partialNetworkConf
        .addLayer(s"block${blockNumber}Conv1", new ConvolutionLayer.Builder(Array(3,3), Array(1,1)).convolutionMode(Same).nOut(256).l2Bias(l2RegParam).build, inputName)
//        .addLayer(s"block${blockNumber}Conv1", new ConvolutionLayer.Builder(Array(3,3), Array(1,1)).convolutionMode(Same).nIn(17).nOut(256).l2Bias(l2RegParam).build, inputName)
        .addLayer(s"block${blockNumber}BatchNorm1", new BatchNormalization.Builder().build, s"block${blockNumber}Conv1")
        .addLayer(s"block${blockNumber}ReLu1", new ActivationLayer.Builder().activation(RELU).build, s"block${blockNumber}BatchNorm1")
        .addLayer(s"block${blockNumber}Conv2", new ConvolutionLayer.Builder(Array(3,3), Array(1,1)).convolutionMode(Same).nOut(256).l2Bias(l2RegParam).build, s"block${blockNumber}ReLu1")
//        .addLayer(s"block${blockNumber}Conv2", new ConvolutionLayer.Builder(Array(3,3), Array(1,1)).convolutionMode(Same).nIn(17).nOut(256).l2Bias(l2RegParam).build, s"block${blockNumber}ReLu1")
        .addLayer(s"block${blockNumber}BatchNorm2", new BatchNormalization.Builder().build, s"block${blockNumber}Conv2")
        .addVertex(s"block${blockNumber}SkipConnection", new ElementWiseVertex(ElementWiseVertex.Op.Add), inputName, s"block${blockNumber}BatchNorm2")
        .addLayer(s"block${blockNumber}Output", new ActivationLayer.Builder().activation(RELU).build(), s"block${blockNumber}SkipConnection")
      (confWithNextBlock, s"block${blockNumber}Output")
  }

  val fullNetworkConf = networkTrunkConf
    /*
    Policy head
    (1) A convolution of 2 filters of kernel size 1 ×  1 with stride 1
    (2) Batch normalization
    (3) A rectifier nonlinearity
    (4) A fully connected linear layer that outputs a vector of size 192 +  1  =   362, corresponding to logit probabilities for all intersections and the pass move
     */
    .addLayer("policyConv", new ConvolutionLayer.Builder(Array(1,1), Array(1,1)).convolutionMode(Same).nOut(2).l2Bias(l2RegParam).build, lastBlockOutput)
    .addLayer("policyBatchNorm", new BatchNormalization.Builder().activation(RELU).build, "policyConv")
    .addLayer("policyReLu", new ActivationLayer.Builder().activation(RELU).build, "policyBatchNorm")
    .addLayer("policyFullyConnected", new DenseLayer.Builder().nOut(362).l2Bias(l2RegParam).build, "policyReLu")
    .addLayer("policyOutput", new OutputLayer.Builder().lossFunction(MSE).nOut(362).build, "policyFullyConnected")
    // Should this be the probit?

    /*
    Value head
    (1) A convolution of 1 filter of kernel size 1 ×  1 with stride 1
    (2) Batch normalization
    (3) A rectifier nonlinearity
    (4) A fully connected linear layer to a hidden layer of size 256
    (5) A rectifier nonlinearity
    (6) A fully connected linear layer to a scalar
    (7) A tanh nonlinearity outputting a scalar in the range [− 1,  1]
     */
    .addLayer("valueHeadConv", new ConvolutionLayer.Builder(Array(1,1), Array(1,1)).convolutionMode(Same).nOut(1).l2Bias(l2RegParam).build, lastBlockOutput)
    .addLayer("valueBatchNorm", new BatchNormalization.Builder().activation(RELU).build, "valueHeadConv")
    .addLayer("valueReLu", new BatchNormalization.Builder().activation(RELU).build, "valueBatchNorm")
    .addLayer("valueFullyConnectedReLu", new DenseLayer.Builder().nOut(256).activation(RELU).l2Bias(l2RegParam).build, "valueReLu")
    .addLayer("valueSingleNode", new DenseLayer.Builder().nIn(256).nOut(1).activation(TANH).l2Bias(l2RegParam).build, "valueFullyConnectedReLu")
    .addLayer("valueOutput", new OutputLayer.Builder().lossFunction(NEGATIVELOGLIKELIHOOD).nOut(1).build, "valueSingleNode")
    .setOutputs("valueOutput", "policyOutput")
    .build()

  val network = new ComputationGraph(fullNetworkConf)
}

@SerialVersionUID(123L)
class LabeledDataSet(var examples: List[LabeledDataPoint], var filenames: List[String]) extends Serializable

  def loadSerializedDataSet(path: String): LabeledDataSet = {
    val d = new File(path)
    if(d.exists){
      val ois = new ObjectInputStream(new FileInputStream(path))
      val ds = ois.readObject.asInstanceOf[LabeledDataSet]
      ois.close()
      ds
    } else new LabeledDataSet(List(), List())
  }

  def main(args: Array[String]): Unit = {
    val serializedFilePath = """D:\starfruit_serialized""" // replace w/ unzipped contents

    val ds = loadSerializedDataSet(serializedFilePath).examples.take(128)
    println(s"Finished loading serialized data set, number of examples: ${ds.length}")

    val separateDs = ds map { point =>
      new MultiDataSet(Array[INDArray](point.featureRepresentation), Array[INDArray](point.nextMove, point.wonGame))
    }
    val merged = MultiDataSet.merge(separateDs.asJava)

    val multiTaskNetwork = new MultiTaskNetwork()
    multiTaskNetwork.network.init()
    println(multiTaskNetwork.network.numParams())

    val nEpochs = 3

    Nd4j.getMemoryManager.setAutoGcWindow(5000)
    println("Starting training")
    for (i <- 0 to nEpochs) {
      multiTaskNetwork.network.fit(merged)
      println("*** Completed epoch {} ***", i)

      println("Evaluate model....")
    }
  }
}

``

Build information:
name := "Starfruit"

version := "0.1"

scalaVersion := "2.11.11"

val nd4jVersion = "0.9.1"

// https://mvnrepository.com/artifact/org.deeplearning4j/deeplearning4j-core
libraryDependencies += "org.deeplearning4j" % "deeplearning4j-core" % nd4jVersion

// https://mvnrepository.com/artifact/org.nd4j/nd4s_2.11
libraryDependencies += "org.nd4j" % "nd4s_2.11" % nd4jVersion

libraryDependencies += "org.nd4j" % "nd4j-native-platform" % nd4jVersion

[starfruit_serialized.gz](https://github.com/deeplearning4j/deeplearning4j/files/1425950/starfruit_serialized.gz)

**Comment by bixbyr** [comment]
Update:

Code to the entire project can be downloaded from https://github.com/bixbyr/starfish

**Comment by raver119** [comment]
Can you please add some datasets, or emulation of the datasets to your project?

**Comment by raver119** [comment]
p.s. code you've provided via repo doesn't match serialized dataset you've posted here.

**Comment by raver119** [comment]
So, you have 43 (fourty three) convolution layers within. im2col dimensionality within: [128, 256, 19, 19, 3, 3]. That's 500mb per im2col only. 

You have 134 (one hundred thirty four) total layers. So, number of activations stored during training is supposed to grow over time. 

WIth all that stuff kept in mind, i have one more question: Why do you think your nn should fit in 8GB or 10GB of ram?

**Comment by raver119** [comment]
p.s. here's unrolled configuration of the nn: https://gist.github.com/raver119/06a3daaec11f4ec15feafc6019ec7031

**Comment by bixbyr** [comment]
I would assume this should fit into 8-10GB of ram because the number of actual parameters is quite small. I think if I'm understanding your comment that the intermediary size of a mini-batch as it is passing through the network is going to balloon up at the convolutions layers since DL4J is processing all examples concurrently rather than sequentially, before computing the mean gradient and doing back-prop? 

If I understand correctly, then the mini batch size needs to be even smaller to avoid the blow up we're seeing here?

The serialized version was before converting the winner to an INDArray rather than a Double, since I didn't realize that I'd have to convert it before entering each example in. I can post a fixed version which includes src data for a couple hundred examples instead of serialized classes.

**Comment by bixbyr** [comment]
Follow up to previous comment: if the entire mini batch is being evaluated concurrently by the network, is there any way to gc after we've passed through a convolution layer? None of these intermediary representation should be required once the layer has been evaluated, and even leaving aside questions of efficiency when training on the CPU, I don't see how this workflow could run even on an industrial strength GPU if all of the intermediary evaluation data is retained for all convolutions for all elements of a mini-batch at once.

**Comment by raver119** [comment]
Unfortunately that's wrong assumption. In convolution network weights aren't usually significant. But activations and internal allocations are. As i've mentioned above - 500mb per single im2col in single convolution layer.

But anyway - please push fixed version to your repo, so i could actually run your network.

**Comment by bixbyr** [comment]
Pushed new commit w/ a sample tar file which can be used to produce > 100 examples w/o any external dependencies (save for correcting the path since I was having trouble with accessing resources in the jar for some reason).

**Comment by AlexDBlack** [comment]
Memory use is considerably lower here: https://github.com/deeplearning4j/deeplearning4j/pull/4900
You can access that via snapshots (or try again after the next release): https://deeplearning4j.org/snapshots
