### ISSUE TITLE
Documentation page shows 404: page not found

### ISSUE THREAD

**Issue by sanjay51** [deeplearning4j/deeplearning4j#4225]
#### Issue Description
Example: https://deeplearning4j.org/programmingguide/datavec - 404 page

Reproduction steps:
* Search for "dl4j saveUpdater" on google,
https://www.google.com/search?q=dl4j+saveUpdater&oq=dl4j+saveUpdater&aqs=chrome..69i57.2335j0j7&sourceid=chrome&ie=UTF-8

* The first link that comes up is, https://deeplearning4j.org/programmingguide/08_deploy
Click on it.

* From this page, if you click on any link on the left pane, it takes you to a "404: Page not found" page.
e.g. https://deeplearning4j.org/programmingguide/datavec

Ideally it should redirect to the correct path (assuming the path structure changed recently), i.e. https://deeplearning4j.org/datavec

#### Version Information
N/A. Browser: Chrome
#### Contributing
N/A

**Comment by tomthetrainer** [comment]
@crockpotveggies FYI, the programming guide being one directory down causes nav panel to link to non-existent links one directory down. 

Maybe nav-panel or whole page has some setting we can use to fix that?

**Comment by crockpotveggies** [comment]
@tomthetrainer can you screenshot and link to where this is happening? I don't see the behavior on my end.

cc @chrisvnicholson

**Comment by crockpotveggies** [comment]
Fixed with https://github.com/deeplearning4j/deeplearning4j/commit/00eec3db5999c4204db72543709d4141aa1c6fc8
