### ISSUE TITLE
dl4j-caffe build broken, missing ressource

### ISSUE THREAD

**Issue by olafhel** [deeplearning4j/deeplearning4j#423]
in the pom.xml

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generate-sources</id>
                        <phase>generate-sources</phase>
                        <configuration>
                            <tasks>
                                <exec executable="protoc">
                                    <arg value="--java_out=src/main/java" />
                                    <arg value="src/resources/proto/caffe.proto" />
                                </exec>
                            </tasks>
                            <sourceRoot>src/main/java</sourceRoot>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

cause an error because there is no src/resources/proto/caffe.proto

**Comment by agibsonccc** [comment]
Fixed.
