### ISSUE TITLE
Broken link to sentence classification example in the computation graph docs

### ISSUE THREAD

**Issue by anovstrup** [deeplearning4j/deeplearning4j#4231]
In [this section](https://deeplearning4j.org/compgraph#usecases) of the documentation of computation graphs, the [link to a convolutional networks for sentence classification](http://www.people.fas.harvard.edu/~yoonkim/data/emnlp_2014.pdf) example is broken.

**Comment by anovstrup** [comment]
The link was actually to a paper, but a link to [this example](https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/sentenceclassification/CnnSentenceClassificationExample.java) might be just as useful.

**Comment by ejunprung** [comment]
@anovstrup This has been fixed. Thank you for pointing this out!
