### ISSUE TITLE
Convert a MultiLayerNetwork into a ComputationGraph

### ISSUE THREAD

**Issue by slang03** [deeplearning4j/deeplearning4j#4233]
#### Issue Description

It is currently not possible to convert a MultiLayerNetwork into a ComputationGraph in a straightforward fashion. My use case is the following: I've got a class which contains a Model from the ModelZoo. Though some models from the ModelZoo are of type MultiLayerNetwork and some are ComputationGraph. Therefore, it would be good to convert those of type MLN into a CG.

**Comment by tomthetrainer** [comment]
I discussed this with some of the engineering team, and you are correct, conversion is not a feature we have currently implemented. 

I tried a few things, MultiLayerConfig to JSON, and then ComputationGraph from JSON but that had issues. One approach that might work would be extracting Layer by Layer and importing Layer by Layer.

**Comment by slang03** [comment]
I have written a small conversion method as shown in [this](https://gist.github.com/slang03/53d69216a7d75ab83ddc23f5c3fb080a) gist. It works for me but I'm very sure, that I'm missing a lot of cases where it is not working yet. I could make a PR, though I have no clue at which point (which class) this functionality should be implemented

**Comment by AlexDBlack** [comment]
@slang03 that gist looks to be heading in the right direction.
Obviously the parameters need to be copied over too. And preprocessors also.

The setInputtypes probably shouldn't be necessary in general when converting an MultiLayerNetwork to a ComputationGraph (as an already instantiated network should have the nIns and preprocessors already set). And we don't currently store the InputType anyway.

**Comment by slang03** [comment]
Yes, I should have mentioned that the gist code was for the situation of an initialized network. If you could give me a hint where this would be implemented? I'm not too familiar with the dl4j structure yet.

**Comment by AlexDBlack** [comment]
There's a bunch of places where this could be placed in DL4J
My initial thought would be to put it here:
https://github.com/deeplearning4j/deeplearning4j/tree/master/deeplearning4j-core/src/main/java/org/deeplearning4j/util
We could call it something like ```NetworkConverter.toCompGraph(MultiLayerNetwork)```

It might also be convenient to have a static method, ```ComputationGraph.fromMultiLayerNetwork(MultiLayerNetwork)``` or something (that just uses util class/method), so it's easier for users to find. I'd probably want to keep the functionality itself out of ComputationGraph class (it's big enough as it is).

If we use that, then (as deeplearning-core depends on deeplearning4j-nn) we'd maybe put it here:
https://github.com/deeplearning4j/deeplearning4j/tree/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/util

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/4394
