### ISSUE TITLE
K-Means implementation is very slow

### ISSUE THREAD

**Issue by KidCrippler** [deeplearning4j/deeplearning4j#4234]
I'm trying to use DL4J's (version 0.9.1) K-Means implementation. I set it up as follows:

int CLUSTERS = 5;
int MAX_ITERATIONS = 300;
String DISTANCE_METRIC = "cosinesimilarity";
KMeansClustering KMEANS = KMeansClustering.setup(CLUSTERS, MAX_ITERATIONS, DISTANCE_METRIC);
My data points are vectors of size 300 (doubles), and my test set is comprised of ~ 100 data points each time (give or take). I'm running it on my CPU (4 cores) in a single threaded fashion.

Evaluation takes a very long time (a few seconds per example).

I took a peek inside the algorithm's implementation and it looks like its concurrency level is very high - a lot of tasks (Runnable) are being created (one per data point, to be exact) and executed in parallel. Perhaps this is an overkill? Is there any way I can control it through configuration? Other ways to speed it up?

I've also posted a [question](https://stackoverflow.com/questions/46995912/deeplearning4j-k-means-very-slow) regarding this issue in Stackoverflow.

**Comment by alexanderst** [comment]
Performance fixed, merged.
