### ISSUE TITLE
DL4J 0.9.1 : MetaDatas get lost in BaseDataFetcher.initializeCurrFromList(examples) 

### ISSUE THREAD

**Issue by namsor** [deeplearning4j/deeplearning4j#4251]
Hi! We've tried DL4J with word embedding (Word2Vec). We found quite convenient to put the original words as metadata in the input dataset. 

(1) To the original sample classifier, in the DataFetcher we added:
```
DataSet ds = new DataSet(fnLnV, outcome);
                            ds.setExampleMetaData(metadata);
                            ds.setLabelNames(Arrays.asList(LABELS));
```
(2) So when we evaluate the model, we can easily print the input/expected output/actual output:

```
 log.info("Evaluate model....");
        Evaluation eval = new Evaluation(outputNum); 
        while (namsorValidate.hasNext()) {
            DataSet next = namsorValidate.next();
            INDArray output = model.output(next.getFeatureMatrix()); //get the networks prediction
            List<Serializable> metas = next.getExampleMetaData();
            for (Serializable meta : metas) {
                fw.append(meta+"|");
                String labelStr = NamSorDataFetcher.label(output, i);
                fw.append(labelStr+"\n");
                i++;
            }
            eval.eval(next.getLabels(), output); //check the prediction against the true class
        }   
        log.info(eval.stats());
```

(3) For that to work we had to override the BaseDataFetched initializeCurrFromList() as it didn't retain the metadatas. Perhaps this is a bug?

    @Override
    protected void initializeCurrFromList(List<DataSet> examples) {
        //if (examples.isEmpty())
          //  log.warn("Warning: empty dataset from the fetcher");
        curr = null;
        INDArray inputs = createInputMatrix(examples.size());
        INDArray labels = createOutputMatrix(examples.size());
        // super() bug fix
        List<Serializable> metas = new ArrayList(examples.size());
        for (int i = 0; i < examples.size(); i++) {
            INDArray data = examples.get(i).getFeatureMatrix();
            INDArray label = examples.get(i).getLabels();
            inputs.putRow(i, data);
            labels.putRow(i, label);
            // super() bug fix
            metas.addAll(examples.get(i).getExampleMetaData());
        }
        curr = new DataSet(inputs, labels);
        // super() bug fix
        curr.setExampleMetaData(metas);
        examples.clear();
    }

I hope this is what MetaData are for. If so, it would be good to patch the BaseDataFetcher with the missing curr.setExampleMetaData(metas). Also, it would be good to have MetaData in the DL4J samples. 

Thanks for the good work, DL4J people!
Best,
E.

#### Issue Description

Please describe our issue, along with:
- expected behavior
- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by AlexDBlack** [comment]
Iom going to close this as a "won't fix" - BaseDatafetcher is used only for Iris, MNIST and EMNIST iterators (none of which support metadata), mainly for legacy reasons - I would advise against extending these classes for custom pipelines.

A better approach would be to implement a custom RecordReader and use RecordReader(Multi)DataSetIterator, which properly supports metadata.
