### ISSUE TITLE
useMDS flag incorrectly documented and should be removed

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/deeplearning4j#4264]
#### Issue Description

In `org.deeplearning4j.parallelism` the boolean flag `useMDS`, which is about using MultiDataSets, is incorrectly documented as being about the deprecated `MagicQueue`

```
@param useMDS whether to use the {@link org.deeplearning4j.parallelism.MagicQueue}
```

I'm currently removing `MagicQueue` in #4050. 

@raver119 tells me we should get rid of `useMDS` altogether, as this can be figured out internally and doesn't have to be provided by the user

**Comment by raver119** [comment]
User doesn't provide mds anymore. It happens internally, based on fit() method used.
