### ISSUE TITLE
Dependency broken: deeplearning4j-nn:jar pom

### ISSUE THREAD

**Issue by cliffbdf** [deeplearning4j/deeplearning4j#4265]
#### Issue Description

deeplearning4j-nn:jar depends on nd4j-jackson:jar:0.9.1-SNAPSHOT, but the Sonatype maven repo only has 0.9.2.

Please describe our issue, along with:
- expected behavior

mvn compile should work, but it fails. Running mvn package -X shows the dependencies.

- encountered behavior

Maven build failure with "The following artifacts could not be resolved: org.nd4j:nd4j-jackson:jar:0.9.1-SNAPSHOT, org.datavec:datavec-api:jar:0.9.1-SNAPSHOT, org.datavec:datavec-data-image:jar:0.9.1-SNAPSHOT"

#### Version Information

		<deeplearning4j.version>0.8.1-SNAPSHOT</deeplearning4j.version>
		
		<nd4j.version>0.9.2-SNAPSHOT</nd4j.version>
		<slf4j.version>1.7.12</slf4j.version>
		<logback.version>1.1.2</logback.version>

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by saudet** [comment]
I'm not seeing that anywhere in the codebase. Could you provide a link? Thanks

**Comment by cliffbdf** [comment]
Perhaps it is not worth resolving this issue. Do you guys push our jars to Sonatype Nexus and then test that by building from those dependencies? I am only specifying 0.8.1-SNAPSHOT for deeplearning4j because that is the latest version in Sonatype:
https://oss.sonatype.org/content/repositories/snapshots/org/deeplearning4j/deeplearning4j-core/

If version .9 were in there, I could use that, and I would not have the build issue that I have reported.

**Comment by cliffbdf** [comment]
Important: people who use DL4J expect to be able to pull the jar files from the maven repository - they will not expect to have to build DL4J from source. This is not like Python where people use source - they use the binaries - and it is not like Go where people have to compile for their architecture. In the Java world, people pull jar files using maven and so it is really important to keep the official maven repo up to date (in your case, you use Sonatype), and to run integration tests that pull from that instead of using locally cached jars. Otherwise, you have no way of knowing if the right binaries (jars) have been published.

Can version .9 of all the packages please be pushed to Sonatype?

https://oss.sonatype.org/content/repositories/snapshots/org/deeplearning4j/

I really don't want to have to clone the whole DL4J repo and build from source - that's not the "Java way".

**Comment by cliffbdf** [comment]
Never mind - it is in releases - I was using snapshots. It would be a good idea to put it in snapshots too in the future, so that people don't have to change their repository URL.
