### ISSUE TITLE
SimpleCNN in zoo model has no output layer

### ISSUE THREAD

**Issue by benqua** [deeplearning4j/deeplearning4j#4275]
#### Issue Description
In the zoo model, there is a [SimpleCNN](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-zoo/src/main/java/org/deeplearning4j/zoo/model/SimpleCNN.java) network. This network has not output layer and is not trainable as is.

Shouldn't the last layer be an output layer at [L127](https://github.com/deeplearning4j/deeplearning4j/blob/862b8aa13a3bee57d9699aea77f1bac8cad16969/deeplearning4j-zoo/src/main/java/org/deeplearning4j/zoo/model/SimpleCNN.java#L127) ?

**Comment by raver119** [comment]
@crockpotveggies Where we are with this?

**Comment by crockpotveggies** [comment]
The new API now allows you to specify that an output layer is not necessary. Closing.
