### ISSUE TITLE
Enforcer profiles error

### ISSUE THREAD

**Issue by clavvis** [deeplearning4j/deeplearning4j#4278]
I tried  mvn clean install on deeplearning4j and I received error:

[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-choice-of-nd4j-test-backend) @ deeplearning4j-parent ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireActiveProfile failed with message:
Profile "test-nd4j-native" is not activated.
Profile "test-nd4j-cuda-8.0" is not activated.

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] DeepLearning4j ..................................... FAILURE [  2.281 s]
[INFO] deeplearning4j-nearestneighbors-parent ............. SKIPPED
.......
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce-choice-of-nd4j-test-backend) on project deeplearning4j-parent: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]

I have just fresh project 0.9.2 SNAPSHOT (git fetch upstream).

Could you help?

**Comment by AlexDBlack** [comment]
Use ```mvn clean install -DskipTests```

**Comment by clavvis** [comment]
Thank you

**Comment by thaear** [comment]
i face this problem Anyone can explain what happen 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] DeepLearning4j ..................................... SUCCESS [ 14.294 s]
[INFO] deeplearning4j-nearestneighbors-parent ............. SUCCESS [  0.483 s]
[INFO] nearestneighbor-core ............................... SUCCESS [ 29.409 s]
[INFO] deeplearning4j-modelimport ......................... SUCCESS [ 15.679 s]
[INFO] deeplearning4j-ui-parent ........................... SUCCESS [  1.486 s]
[INFO] deeplearning4j-ui-components ....................... SUCCESS [02:31 min]
[INFO] deeplearning4j-core ................................ SUCCESS [ 27.115 s]
[INFO] deeplearning4j-ui-model ............................ SUCCESS [ 22.127 s]
[INFO] deeplearning4j-play ................................ SUCCESS [ 24.143 s]
[INFO] DeepLearning4j-scaleout-parent ..................... SUCCESS [  0.249 s]
[INFO] Spark parent ....................................... FAILURE [30:32 min]
[INFO] dl4j-spark ......................................... SKIPPED
[INFO] Dl4j Streaming ..................................... SKIPPED
[INFO] DeepLearning4j-AWS ................................. SKIPPED
[INFO] deeplearning4j-nlp-parent .......................... SKIPPED
[INFO] deeplearning4j-nlp ................................. SKIPPED
[INFO] dl4j-spark-nlp ..................................... SKIPPED
[INFO] deeplearning4j-parallel-wrapper .................... SKIPPED
[INFO] dl4j-spark-parameterserver ......................... SKIPPED
[INFO] dl4j-spark-nlp-java8 ............................... SKIPPED
[INFO] dl4j-spark-ml ...................................... SKIPPED
[INFO] deeplearning4j-scaleout-parallelwrapper-parameter-server SKIPPED
[INFO] deeplearning4j-ui-resources ........................ SKIPPED
[INFO] deeplearning4j-ui .................................. SKIPPED
[INFO] deeplearning4j-ui-standalone ....................... SKIPPED
[INFO] deeplearning4j-graph ............................... SKIPPED
[INFO] deeplearning4j-cuda ................................ SKIPPED
[INFO] deeplearning4j-nlp-uima ............................ SKIPPED
[INFO] deeplearning4j-nlp-korean .......................... SKIPPED
[INFO] deeplearning4j-nlp-japanese ........................ SKIPPED
[INFO] deeplearning4j-nlp-chinese ......................... SKIPPED
[INFO] deeplearning4j-zoo ................................. SKIPPED
[INFO] deeplearning4j-nearestneighbors-model .............. SKIPPED
[INFO] deeplearning4j-nearestneighbors-client ............. SKIPPED
[INFO] deeplearning4j-nearestneighbor-server_2.11 ......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 35:21 min
[INFO] Finished at: 2018-03-18T00:29:41-07:00
[INFO] Final Memory: 166M/936M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.3.1:compi                                                               le (scala-compile-first) on project spark_2.11: Execution scala-compile-first of                                                                goal net.alchim31.maven:scala-maven-plugin:3.3.1:compile failed: Plugin net.alc                                                               him31.maven:scala-maven-plugin:3.3.1 or one of its dependencies could not be res                                                               olved: Could not transfer artifact org.scala-lang:scala-library:jar:2.10.5 from/                                                               to central (https://repo.maven.apache.org/maven2): GET request of: org/scala-lan                                                               g/scala-library/2.10.5/scala-library-2.10.5.jar from central failed: Read timed                                                                out -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit                                                               ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea                                                               d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResoluti
