### ISSUE TITLE
Slow computing of fit after switch to master

### ISSUE THREAD

**Issue by papperwing** [deeplearning4j/deeplearning4j#4280]
I switched to master from 0.9.1 and now one iteration is taking 15 seconds to compute. I have JCudaBackend loaded based on output, bud there is error about not using cuDnn even when cuDnn I have installed (I copied files into right places)

https://gist.github.com/papperwing/5102571742b0c7e5ec84a23ffe9e5b03

Also after switching score which is obtained from fit is not much changing.

I am attaching whole log: https://gist.github.com/papperwing/e8a3c9e4812ff76ab8a007eb5f18fe13

I have two suspicions here about that score:
1) There can be problem in computation because of changes in frozen layers
2) Because it is also slow and there is that problem about cuDNN there could be problem with my build

The second one can be easily tested if any one of you guys could quickly run it. And if it will behave in similar manner its not problem of my build of dl4j.

Version of cuda: 8.0
Version of dl4j: yesterday master

**Comment by papperwing** [comment]
repository: https://github.com/papperwing/image-net
dataset: https://gist.github.com/papperwing/dd91d455de5ae895b9568d54b0b7baf8
program params: https://gist.github.com/papperwing/c3dddf5046bb10a9e9923f094d28c333

**Comment by papperwing** [comment]
Graph of long time learning (cca 8 hours) corresponding to the log mentioned in issue.
![snimek obrazovky 19](https://user-images.githubusercontent.com/5627436/32652428-870279ee-c604-11e7-9f68-405fc83130d0.png)

**Comment by saudet** [comment]
Since you're using CUDA 8.0, make sure to try cuDNN 6.0 in addition to 7.0.

**Comment by papperwing** [comment]
I tried cuDNN 6.0 and also I added dependency for deeplearning4j-cuda but it didn't help. There is slight improvement in speed of iteration though.

In the log there is major part exceptions from deeplearning4j-cuda
log: https://gist.github.com/papperwing/51e3f20d765c59586e4011661b2c9bc0

At the end of log there is also small piece of score for iterations where you can see speed and score behavior.

**Comment by raver119** [comment]
That's not a bug, i think 2 things are happening:
1) You don't have cuDNN working.
2) On current master few convolution-related ops are working as CPU-only.

So, there comes your slowdown.

**Comment by saudet** [comment]
It says "ClassNotFoundException: org.nd4j.jita.allocator.Allocator", which
can only happen if ND4J isn't in the class path...

**Comment by papperwing** [comment]
@raver119 I tried to switch back to see if cudnn is used on 0.9.1 and based on log: https://gist.github.com/papperwing/8afada6275cefe6ccf6bcecacc2ceef1at line 724 til line 831 cudnn is used. So my only suspect here is not that cudnn is not install or working (It is working in tensorflow) but maybe I somehow wrongly built this modules.

@saudet Is your comment meant as "You had not something done during building?" If yes do you have any suspicion what I could do badly?

**Comment by papperwing** [comment]
I don't know why, but problem has solved itself somehow. I have no idea what caused change.

**Comment by saudet** [comment]
I'm guessing you had incompatible binaries in your class path. Unless we call Maven with the "--no-snapshot-updates" option, it may download broken SNAPSHOT artifacts...
