### ISSUE TITLE
AnimalsClassification does not work on my PC

### ISSUE THREAD

**Issue by liashchynskyi** [deeplearning4j/deeplearning4j#4287]
When I run AnimalsClassification example it compiles and runs successfully, but in a few seconds throws the following error 
https://gist.github.com/liashchynskyi/42188441dad3747867574e8b8fc50a97

Other examples run fine (I tried to run LanetMnist) and Nd4J also works.

When I added a new user in windows 10 and fixed the bugs in the registry by CleanMaster then it worked, but when i did the same from my main user account it does not work.

#### Version Information

* Deeplearning4j version: 0.9.1
* Java: 1.8.0_151
* Maven: 3.5.2
* platform information (OS, etc): Windows 10 x64, 4 GB RAM, AMD Athlon 64 x2 Dual Core 4800+
* IDE: Intellij Idea

I am do not use CUDA yet

#### Dependency Tree
https://gist.github.com/liashchynskyi/dc6b8f540fd11a7dd48d46ced6d5cf39

**Comment by saudet** [comment]
> AMD Athlon 64 x2 Dual Core 4800+

So I guess there's a bug in the assembly routines for AMD processors in OpenBLAS. According to https://github.com/xianyi/OpenBLAS/wiki/faq#choose_target_dynamic setting the "OPENBLAS_CORETYPE" environment variable to maybe "Athlon", should work around the issue.

Could you please report this issue upstream though?

**Comment by AlexDBlack** [comment]
I suspected that too when I saw the CPU model, though @liashchynskyi posted this in gitter:
> I forgot to say... sorry, but when I added a new user in windows 10 and fixed the bugs in the registry then it worked, but when i did the same from my main user account it does not work

@liashchynskyi one possible workaround here maybe be to install Intel MKL (it's free).
Then add the directory containing mkl_rt.dll (such as ```C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2017.0.109\windows\redist\intel64_win\mkl\```) to your PATH env variable.

**Comment by liashchynskyi** [comment]
@saudet @AlexDBlack When I added **OPENBLAS_CORETYPE = Athlon** it works. 
I will test it a few more times and if everything will be fine then close the issue. Thanks a lot, guys 👍

**Comment by AlexDBlack** [comment]
@saudet I wonder if this is something we should be checking for, somewhere? OR at least documenting?
That said, I doubt there are many people still running Athlons these days...

**Comment by saudet** [comment]
It's a bug in OpenBLAS, so if we're to fix something, I think we should fix that there.

As for documenting this, it would probably a good idea to document it together at:
https://deeplearning4j.org/native#fallback-mode

**Comment by saudet** [comment]
Done: https://github.com/deeplearning4j/deeplearning4j/commit/5d748bd6d90fd9047468c917eae98207d3690a03#diff-75c2df2bd3c98b49e8f5d4a8890020fe

Thanks for testing this out @liashchynskyi !
