### ISSUE TITLE
ClassNotFoundException: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException

### ISSUE THREAD

**Issue by CuichenTao** [deeplearning4j/deeplearning4j#4290]
i got the error when i use deeplearning4j to word2vec, and cannot fix with it, anybody help?
![image](https://user-images.githubusercontent.com/12867240/32708881-ba2e1782-c867-11e7-98bc-292b845c352d.png)

 Deeplearning4j-0.9.1
 spark-1.6.0
 scala-2.10.5
 platform Linux16.04
 NVIDIA : no nvidia

my code:
`import org.apache.spark.SparkConf;
import org.apache.spark.api.java.JavaRDD;
import org.apache.spark.api.java.JavaSparkContext;
import org.deeplearning4j.models.embeddings.wordvectors.WordVectors;
import org.deeplearning4j.spark.models.embeddings.word2vec.Word2Vec;
import org.deeplearning4j.text.tokenization.tokenizer.preprocessor.LowCasePreProcessor;
import org.deeplearning4j.text.tokenization.tokenizerfactory.DefaultTokenizerFactory;
import org.deeplearning4j.text.tokenization.tokenizerfactory.TokenizerFactory;
import java.util.Collection;
public class Word2VecTest1 {
    public static void main(String[] args) throws Exception {
        SparkConf sparkConf = new SparkConf().setMaster("local[*]").setAppName("sparktest");
        JavaSparkContext sc = new JavaSparkContext(sparkConf);
        JavaRDD<String> corpus = sc.textFile("/home/chen/test/corpus_all/corpus_all_1000000.txt");
        TokenizerFactory t = new DefaultTokenizerFactory();
        t.setTokenPreProcessor(new LowCasePreProcessor());
        Word2Vec word2Vec = new Word2Vec.Builder().setNGrams(1)
                .tokenizerFactory(t).seed(42L).negative(3).useAdaGrad(false).layerSize(100).windowSize(5)
                .learningRate(0.025).minLearningRate(0.0001).iterations(1).batchSize(1000).minWordFrequency(5)
                .useUnknown(true).build();
        word2Vec.train(corpus);
        Collection<String> words = word2Vec.wordsNearest("animal", 10);
        printWords("animal", words, word2Vec);
        sc.stop();
    }

    private static void printWords(String target, Collection<String> list, WordVectors vec) {
        System.out.println("Words close to [" + target + "]:");
        for (String word : list) {
            double sim = vec.similarity(target, word);
            System.out.print("'" + word + "': [" + sim + "], ");
        }
        System.out.print("\n");
    }
}`

**Comment by AlexDBlack** [comment]
@CuichenTao please post your pom.xml file (in a gist - gist.github.com - or something like pastebin)

**Comment by CuichenTao** [comment]
i just import those jars to my project,  without pom.xml:
![Uploading Screenshot from 2017-11-13 12-01-27.png…]()
:

**Comment by CuichenTao** [comment]
i don't have add pom.xml in my project , just import those jars:

canova-api-0.0.0.17.jar
canova-spark_2.11-0.0.0.17.jar
datavec-spark_2.11-0.9.1_spark_1.jar
deeplearning4j-nlp-0.9.1.jar
dl4j-spark_2.11-0.9.1_spark_1.jar
dl4j-spark_2.11-0.9.1_spark_2.jar
dl4j-spark-nlp_2.11-0.9.1_spark_1.jar
guava-23.0.jar
jackson-0.9.1.jar
nd4j-api-0.9.1.jar
nd4j-buffer-0.9.1.jar
nd4j-common-0.9.1.jar
nd4j-jcublas-common-0.4-rc3.7.jar
nd4j-native-0.9.1.jar
nd4j-native-api-0.9.1.jar
nd4j-native-platform-0.8.0.jar
nd4j-native-platform-0.9.1.jar
nd4j-x86-0.4-rc3.8.jar

**Comment by agibsonccc** [comment]
We will not support this. You're not even trying to follow our docs here.
