### ISSUE TITLE
Keras Model Import LSTM unable to handle return_sequences=False

### ISSUE THREAD

**Issue by akamlani** [deeplearning4j/deeplearning4j#4295]
#### Issue Description
Keras Model Import unable to handle LSTM `return_sequnces=False` case.  This is common before attaching to Dense Layer.

Received the following in the Log:
```
KerasLstm - Keras setting 'return_sequences = False' is not properly supported,
DL4J's LSTM layer returns sequences by default
```
Reference the following gist for the Keras Model (via Functional API):
https://gist.github.com/akamlani/f0371c3f91ad3e809a706b026bbf8ddb

#### Version Information
* 0.9.2-SNAPSHOT (Per 11/12)
* Keras 2.0.7 + TensorFlow 1.3.0
* MacOS
* CPU Based

**Comment by maxpumperla** [comment]
@akamlani thanks for reporting this. Note that since 0.9.1 the only thing we changed to this part of the code base is _adding this warning_, i.e. this never worked (you seem to have claimed in gitter it did). :)

**Comment by maxpumperla** [comment]
Note to self: use _LastTimeStepVertex_ to tackle this.

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/graph/rnn/LastTimeStepVertex.java

**Comment by maxpumperla** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/4420

**Comment by maxpumperla** [comment]
@akamlani
