### ISSUE TITLE
RNN Issues on master

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4297]
LSTM gradient checks:

![image](https://user-images.githubusercontent.com/2360237/32760994-041d8d7c-c945-11e7-8b14-dbbc467efc68.png)

**Comment by AlexDBlack** [comment]
I suspect this may be due to: https://github.com/deeplearning4j/nd4j/issues/2264

**Comment by maxpumperla** [comment]
@AlexDBlack very interesting, I was noticing these in #4050 as well and was convinced I introduced them. :/

**Comment by AlexDBlack** [comment]
Confirmed fixed: https://github.com/deeplearning4j/nd4j/issues/2264
