### ISSUE TITLE
Exception in thread "UniGC thread 1 ..."  error

### ISSUE THREAD

**Issue by jwkimusa** [deeplearning4j/deeplearning4j#4300]
#### Issue Description
I have the following error ( Exception in thread "UniGC thread 1 ...) while training a CNN.
"Exception in thread "UniGC thread 2" Exception in thread "UniGC thread 4" Exception in thread "UniGC thread 1" Exception in thread "UniGC thread 3" Exception in thread "UniGC thread 0" Exception in thread "UniGC thread 5" org.nd4j.linalg.exception.ND4JException: CUDA exception happened. Terminating. Last op: [null]
	at org.nd4j.jita.allocator.pointers.cuda.cudaEvent_t.synchronize(cudaEvent_t.java:55)
....."

I used computationGraphi model with a "MergeVertex()" for two inputs (after convolution-maxpool-convolution-maxpool).  Image size is 40*40.
when I ran nvidia-smi.exe, I found that the program used (maximum) 8185MB of 8192MB (of my GPU memory).
I activated ND4J_DEBUG env variable to true and reran the program and had the following error. But, I found a strange thing. My GPU has 8G memory and my program used close to 8G memory to run. After running my program for a while (the computer was locked automatically). I typed my password word to unlock the computer. However, the monitor showed a black screen for seconds (like frozen screen) and finally showed my program . It seems that the program created the error whenever I tried to unlock the computer to check the status. I attached the error message after setting ND4J_DEBUG env variable to true
.https://gist.github.com/jwkimusa/4a295a9108a45374856f33ed51197a89

This one is the original error message before activating ND4J_DEBUG env variable to true . https://gist.github.com/jwkimusa/fb6d8c676cf6878c8f7be5b0d501ed07

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.9.1
* platform information (OS, etc): Windows 7
* CUDA version, if used: 8.0
* NVIDIA driver version, if in use: 21.21.13.7651

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
>  8185MB of 8192MB (

So yes, it sounds like sudden oom. 
Set both workspace mode to separate, that should reduce your memory footprint.
