### ISSUE TITLE
Cannot allocate memory after 100 epochs

### ISSUE THREAD

**Issue by papperwing** [deeplearning4j/deeplearning4j#4304]
I got Cannot allocate memory after 10 epochs.

Exception: https://gist.github.com/papperwing/e683dd6655e2141c5c1c7341314b4f51
Whole log: 
[debug.log_edited.txt](https://github.com/deeplearning4j/deeplearning4j/files/1474006/debug.log_edited.txt)

Here is my model: https://github.com/papperwing/image-net/blob/0.9.1_branch/modules/image-net-model-creator/src/main/java/cz/muni/fi/image/net/model/creator/ModelBuilderImpl.java
Here is my runner of network: https://github.com/papperwing/image-net/blob/0.9.1_branch/modules/image-net-core/src/main/java/cz/muni/fi/image/net/core/manager/ImageNetTrainer.java
Here is my whole repository: https://github.com/papperwing/image-net/tree/0.9.1_branch

I am using batch size of 5. Image size is 224x224x3 

I expected, that if it survived for first 3 epochs it should run without problem. I have no Idea what changed after end of 100th epoch. Also exception is saying that it wanted to use 15G.
GPU has only 8G vram and I set maxbytes and maxphysicalbytes to 20G and Xmx to 3G.

**Comment by papperwing** [comment]
Here is UI screen but I guess it doesn't matter in this problem.
![snimek obrazovky 25](https://user-images.githubusercontent.com/5627436/32828799-6a6fadc0-c9f0-11e7-9800-35d5aa6cbf34.png)

**Comment by liashchynskyi** [comment]
@papperwing Which backend do you use?

**Comment by papperwing** [comment]
I use CudaBackend

**Comment by liashchynskyi** [comment]
@papperwing  

Try to run your app with these VM options where MEM is half or more of your RAM in bytes

-Xms128m
-Xmx12G
-XX:ReservedCodeCacheSize=240m
-XX:+UseConcMarkSweepGC
-XX:SoftRefLRUPolicyMSPerMB=50
-ea
-Dsun.io.useCanonCaches=false
-Djava.net.preferIPv4Stack=true
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-Dorg.bytedeco.javacpp.maxbytes=MEM
-Dorg.bytedeco.javacpp.maxphysicalbytes=MEM

**Comment by raver119** [comment]
Usually this kind of problems are resolved by enabling workspaces for both inference & training.
