### ISSUE TITLE
Incompatible/obsolete library Canova on classpath.

### ISSUE THREAD

**Issue by ryanaleksander** [deeplearning4j/deeplearning4j#4305]
#### Issue Description
I tried to run the example in ParagraphVectorsClassifierExample.java and encountered this error:
` ERROR versioncheck.VersionCheck: Found incompatible/obsolete library Canova on classpath. ND4J is unlikely to function correctly with this library on the classpath. JVM will now exit.`

#### Version Information
* Deeplearning4j version: 0.9.1
* Windows 10

**Comment by AlexDBlack** [comment]
The examples by default (if unmodified) don't include Canova, and haven't for a *long* time.
For some reason, your classpath is messed up. Try a fresh clone of the examples, and try again.

**Comment by ryanaleksander** [comment]
I found this in the classpath and if I delete it, the program will run. But of course, it still comes back every time I refresh the dependencies.
![image](https://user-images.githubusercontent.com/10950709/32869677-27c1f82e-ca2d-11e7-8b96-5e8c9d039a04.png)

**Comment by agibsonccc** [comment]
@ryanaleksander Please listen to alex's advice. You've clearly modified the examples and added a 1 off old jar. That is not our responsibility. This is on you.  Every single time this happens it means someone ignored documentation and copied and pasted from some old blog post and then expects us to fix it. I am locking this thread.
