### ISSUE TITLE
Issues with devguide, minor typos

### ISSUE THREAD

**Issue by tomthetrainer** [deeplearning4j/deeplearning4j#4307]
Hi all,

I read web page https://deeplearning4j.org/devguide and found several bad links.

Part "Contributing Documentation: How the Websites Work"

- link "Markdown"

Part "DeepLearning4J: Some Things to Know"

- text "deeplearning4j-core:" - instead of "core" should be "nn" (links too)

- link "HistogramIterationListener"

Part "Adding New Layers to DL4J"

- two links "org.deeplearning4j...."

- two links "these classes"

- and several others

Part "How Backpropagation is Implemented in DL4J"

- several

Have a nice day

**Comment by ejunprung** [comment]
I've corrected all these issues.
