### ISSUE TITLE
Crash on simple configuration

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4308]
I'm getting a hard crash on 0.9.1 on the configuration below.
Not sure yet if it's an invalid configuration not being detected, or simply an edge case bug.

```Process finished with exit code -1073740940 (0xC0000374)``` with no error log.

https://gist.github.com/dionisole/4180216ca36f4131302a666b8daabd3b
https://files.gitter.im/deeplearning4j/deeplearning4j/tuninghelp/PpiH/protein_csv_test_all.txt
https://files.gitter.im/deeplearning4j/deeplearning4j/tuninghelp/fEb3/protein_csv_train_all.txt

**Comment by treo** [comment]
Related to https://github.com/deeplearning4j/nd4j/issues/2041?

**Comment by raver119** [comment]
Looks quite possible.

That bug was fixed on current master.

**Comment by AlexDBlack** [comment]
Confirmed - this runs fine on master. Closing this.
