### ISSUE TITLE
ConvolutionIterationListener OutOfBoundException when all conv layers are frozen

### ISSUE THREAD

**Issue by papperwing** [deeplearning4j/deeplearning4j#4313]
When using TransferLearningAPI I froze all conv. layers and it resulted in this exception:
https://gist.github.com/papperwing/e9fbfa71a4fc5c442d2329509df3efdc

Also Is it possible to visualize frozen conv. layers? It is because I still want to see what filters it wants to apply, even when its frozen.

DL4J version: 0.9.1

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/4326
