### ISSUE TITLE
Can't allocate [HOST] memory but availablePhysicalBytes etc. is High

### ISSUE THREAD

**Issue by davies46** [deeplearning4j/deeplearning4j#4314]
I wrote a little test program in the deeplearning4j-examples project:

```
    public static void main(String[] args) {
        List<INDArray> memList = new LinkedList<>();
        int x = 0;
        try {
            for (x = 0; x < 1000; x++) {
                INDArray arr = Nd4j.create(1024, 1024);
                memList.add(arr);
                if (x % 100 == 0)
                    System.out.println("totalPhysicalBytes " + totalPhysicalBytes() + ", maxBytes " + maxBytes() +
                        ", maxPhysicalBytes " + maxPhysicalBytes() + ", physicalBytes " + physicalBytes() +
                        ", availablePhysicalBytes " + availablePhysicalBytes()+", totalBytes "+ totalBytes());
            }
            System.out.println("Allocated all blocks");
        } catch (RuntimeException e) {
            System.out.println("Died after allocating 4M * " + x + " = " + (4 * x)+"MB");
            e.printStackTrace();
        }
    }
```
But despite using different VM options like -Xmx8G -Dorg.bytedeco.javacpp.maxbytes=8796093022208 -Dorg.bytedeco.javacpp.maxphysicalbytes=8796093022208

it always runs out of memory at around 4GB off-heap usage.
I would expect it to run to around 8G. It's the same 4GB even if I set the maxBytes/maxPhysicalBytes to 10G or 2G, suggesting these settings are being ignored or overwritten.

Any suggestions greatly appreciated!

Thanks,
Phil

Here's the output:

> o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
> o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 32
> o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Linux]
> o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [7.1GB];
> o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
> o.n.l.j.o.e.CudaExecutioner - Device name: [GeForce GTX 1070]; CC: [6.1]; Total/free memory: [8504868864]
> totalPhysicalBytes 25077288960, maxBytes 8796093022208, maxPhysicalBytes 8796093022208, physicalBytes 1002328064, availablePhysicalBytes 21775753216, totalBytes 33
> totalPhysicalBytes 25077288960, maxBytes 8796093022208, maxPhysicalBytes 8796093022208, physicalBytes 1424650240, availablePhysicalBytes 21339459584, totalBytes 1
> totalPhysicalBytes 25077288960, maxBytes 8796093022208, maxPhysicalBytes 8796093022208, physicalBytes 1844420608, availablePhysicalBytes 20905218048, totalBytes 1
> totalPhysicalBytes 25077288960, maxBytes 8796093022208, maxPhysicalBytes 8796093022208, physicalBytes 2263986176, availablePhysicalBytes 20471115776, totalBytes 1
> totalPhysicalBytes 25077288960, maxBytes 8796093022208, maxPhysicalBytes 8796093022208, physicalBytes 2683850752, availablePhysicalBytes 20036931584, totalBytes 1
> totalPhysicalBytes 25077288960, maxBytes 8796093022208, maxPhysicalBytes 8796093022208, physicalBytes 3103948800, availablePhysicalBytes 19594084352, totalBytes 1
> totalPhysicalBytes 25077288960, maxBytes 8796093022208, maxPhysicalBytes 8796093022208, physicalBytes 3523956736, availablePhysicalBytes 19160993792, totalBytes 1
> totalPhysicalBytes 25077288960, maxBytes 8796093022208, maxPhysicalBytes 8796093022208, physicalBytes 3943682048, availablePhysicalBytes 18726309888, totalBytes 1
> totalPhysicalBytes 25077288960, maxBytes 8796093022208, maxPhysicalBytes 8796093022208, physicalBytes 4362969088, availablePhysicalBytes 18292162560, totalBytes 1
> totalPhysicalBytes 25077288960, maxBytes 8796093022208, maxPhysicalBytes 8796093022208, physicalBytes 4782518272, availablePhysicalBytes 17858015232, totalBytes 1
> java.lang.RuntimeException: Can't allocate [HOST] memory: 4194304; threadId: 1
> 	at org.nd4j.jita.memory.impl.CudaDirectProvider.malloc(CudaDirectProvider.java:59)
> 	at org.nd4j.jita.memory.impl.CudaCachingZeroProvider.malloc(CudaCachingZeroProvider.java:113)
> 	at org.nd4j.jita.memory.impl.CudaFullCachingProvider.malloc(CudaFullCachingProvider.java:91)
> 	at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:237)
> 	at org.nd4j.jita.handler.impl.CudaZeroHandler.alloc(CudaZeroHandler.java:258)
> 	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:470)
> 	at org.nd4j.jita.allocator.impl.AtomicAllocator.allocateMemory(AtomicAllocator.java:396)
> 	at org.nd4j.linalg.jcublas.buffer.BaseCudaDataBuffer.<init>(BaseCudaDataBuffer.java:216)
> 	at org.nd4j.linalg.jcublas.buffer.CudaFloatDataBuffer.<init>(CudaFloatDataBuffer.java:60)
> 	at org.nd4j.linalg.jcublas.buffer.factory.CudaDataBufferFactory.createFloat(CudaDataBufferFactory.java:321)
> 	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1468)
> 	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1442)
> Died after allocating 4M * 995 = 3980MB
> 	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:247)
> 	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:284)
> 	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:566)
> 	at org.nd4j.linalg.jcublas.JCublasNDArray.<init>(JCublasNDArray.java:252)
> 	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.create(JCublasNDArrayFactory.java:238)
> 	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:5014)
> 	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4965)
> 	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4093)
> 	at org.deeplearning4j.examples.unsupervised.deepbelief.CudaTest.main(CudaTest.java:22)
> 

dl4j cloned from GitHub ~2 weeks ago, was working fine on older PC but after re-installing Ubuntu I'm seeing this problem. Same GPU.
Ubuntu 16.04 64bit
AMD Piledriver 8-core with 24GB RAM
CUDA 8.0 GA1 (tried most others!)
Cudnn7 (tried 6 too)
Nvidia-384.98 drivers (tried most others)
Nvidia GTX1070

**Comment by raver119** [comment]
Let me try to reproduce this locally.

**Comment by davies46** [comment]
Thanks! I also just tried starting a new dl4j example project from scratch, in case it was some corruption there, but after copying in the little test prog I got the same result.

**Comment by saudet** [comment]
I remember hearing about drivers with a bug like that. Are you certain you are tried the latest version available for your model?

**Comment by davies46** [comment]
Do you mean the Nvidia graphics card driver? 
I'm using 384.98, which from 2nd Nov 2017, but also tried 375.26 (Feb 2017), because these were good with last Ubuntu16.04/motherboard/CPU that didn't show this problem.

**Comment by raver119** [comment]
```
o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 32
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Linux]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [7.0GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
o.n.l.j.o.e.CudaExecutioner - Device name: [GeForce GTX 1070]; CC: [6.1]; Total/free memory: [8507752448]
o.n.l.j.o.e.CudaExecutioner - Device name: [GeForce GTX 1070]; CC: [6.1]; Total/free memory: [8508145664]
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 1596203008, availablePhysicalBytes 23421833216, totalBytes 152
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 2015772672, availablePhysicalBytes 22989918208, totalBytes 120
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 2436755456, availablePhysicalBytes 22559469568, totalBytes 120
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 2857467904, availablePhysicalBytes 22127542272, totalBytes 120
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 3278086144, availablePhysicalBytes 21695815680, totalBytes 120
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 3698728960, availablePhysicalBytes 21263626240, totalBytes 120
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 4119429120, availablePhysicalBytes 20832440320, totalBytes 120
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 4540071936, availablePhysicalBytes 20400640000, totalBytes 120
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 4960374784, availablePhysicalBytes 19996307456, totalBytes 120
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 5379891200, availablePhysicalBytes 19565563904, totalBytes 120
Allocated all blocks
```

**Comment by raver119** [comment]
Ubuntu 17.10, driver version 384.90

**Comment by raver119** [comment]
Also, according to your log, crash happens due to CUDA driver returns null pointer. So it happens out of our control.

**Comment by raver119** [comment]
Same with only 1 GPU:

```
o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 32
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Linux]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [7.0GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
o.n.l.j.o.e.CudaExecutioner - Device name: [GeForce GTX 1070]; CC: [6.1]; Total/free memory: [8507752448]
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 960098304, availablePhysicalBytes 24514535424, totalBytes 152
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 1379504128, availablePhysicalBytes 24081649664, totalBytes 120
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 1799356416, availablePhysicalBytes 23651852288, totalBytes 120
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 2219528192, availablePhysicalBytes 23221846016, totalBytes 120
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 2639228928, availablePhysicalBytes 22792142848, totalBytes 120
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 3058778112, availablePhysicalBytes 22362034176, totalBytes 120
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 3478462464, availablePhysicalBytes 21932261376, totalBytes 120
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 3898281984, availablePhysicalBytes 21502259200, totalBytes 120
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 4318687232, availablePhysicalBytes 21071855616, totalBytes 120
totalPhysicalBytes 33681121280, maxBytes 7486832640, maxPhysicalBytes 14973665280, physicalBytes 4738973696, availablePhysicalBytes 20641423360, totalBytes 120
Allocated all blocks
```

**Comment by davies46** [comment]
Thanks so much for looking into it. It seems that although it's possibly a long shot, I'm going to be installing Ubuntu 17.10 :)

**Comment by raver119** [comment]
OS version shouldn't affect that. CUDA driver can, though.

**Comment by davies46** [comment]
I installed from the metal up with 16.04 again and it's all passing fine now. Shame I never found what kind of random cruft caused the problem!

Thanks for all the help though :)

-Phil
