### ISSUE TITLE
ChineseTokenizer won't work under linux 

### ISSUE THREAD

**Issue by rayhuang** [deeplearning4j/deeplearning4j#4319]
I am using Mac for development  and  Linux for production (linux CentOS Linux release 7.3.1611 ). I am testing ChineseTokenizer by just running official [ChineseTokenizer test ](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nlp-parent/deeplearning4j-nlp-chinese/src/test/java/org/deeplearning4j/text/tokenization/tokenizer/ChineseTokenizerTest.java)
 
Under mac, everything runs ok. But when I deploy this test code to linux , it simply halt at middle of the running every time I run the test.

**Comment by raver119** [comment]
That's unexpected behavior. Please show full output log from console + show threads dump.  As gist, if possible, please.

**Comment by raver119** [comment]
Closed due to inactivity.
