### ISSUE TITLE
Spark dataframe input to the dl4j model 

### ISSUE THREAD

**Issue by amaltarghi** [deeplearning4j/deeplearning4j#4321]
How can I convert the Spark Dataframe to org.nd4j.linalg.dataset.api.DataSet so that I can input it into my dl4j model

**Comment by tomthetrainer** [comment]
Does the code example here provide any insight. 

https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-spark-examples/dl4j-spark/src/main/java/org/deeplearning4j/mlp/MnistMLPExample.java

Or perhaps here, 
https://github.com/deeplearning4j/dl4j-examples/blob/master/datavec-examples/src/main/java/org/datavec/transform/basic/BasicDataVecExample.java

They may not be examples of exactly the operation you are attempting, but they do provide examples involving RDD's and migrating to Dataset
