### ISSUE TITLE
How can create an NDArray from an ArrayList

### ISSUE THREAD

**Issue by TamouzeAssi** [deeplearning4j/deeplearning4j#4322]
Hello Sir @agibsonccc

How can create an NDArray from an ArrayList?
I  do the following:

```
[featuresVector_label = Nd4j.zeros(1,self.dim)
...
vector = self.jft.getVector(word)
print vector
nd = Nd4j.create(vector)
featuresVector_label.add(nd)
print featuresVector_label]
```

BUT:
`print vector gives:`
[-0.0014587658, -0.0013949136, -0.006120334, -0.008223078, -0.0059694024, -0.0067288126, 0.0010233098, -0.0026290412, -0.0049774502, -0.0024094887, 0.0035238408, 0.0042002248, 0.0042320145, -0.003931156, -9.322301E-4, -0.0071767876, -0.006452386, -0.008151883, 0.009058729, -0.0070402124, 0.0050425734, -0.0028446962, 0.0030186428, 0.0038732414, -0.0051755332, -0.0013397743, 0.004004812, 0.009391077, 0.008901587, -0.0028379087, -0.0040026414, 0.009847891, -0.007061394, 0.008926436, 0.0014983027, -0.0070138033, -0.007560715, -6.689926E-4, 0.0083675645, -0.0029253392, 0.0098012835, -0.0016338634, 0.008097622, -0.0035594231, -0.0024113157, -0.0012903735, 0.0073546194, -0.0035877456, -0.009842207, 0.007964195, 0.0029394685, -0.0012163925, 0.007647393, -0.005164961, -0.0067228572, -0.005379402, -0.003348721, 0.007864799, -0.009451625, 0.003228441, 6.55834E-4, 0.0016910284, 0.009780001, -0.0054355953, 2.0215829E-4, 0.0057495544, -0.0029569168, 0.009837251, -0.009682788, -0.007492299, -0.0069850185, -0.009233135, 0.0046177786, 0.006768117, 0.006586234, 2.3634032E-4, 0.0015899651, 0.00598463, -0.007967321, -0.008625083, -0.0031935594, 0.0062355204, 0.0062009706, -0.0014651772, 0.006335544, 0.0023335102, 0.0060914867, -0.0048604747, -0.009215203, 0.00437329, 8.1908656E-4, 0.0030824915, -0.0049903556, 0.008294948, 0.008590976, 0.0018638325, -2.3819473E-4, -0.008012838, -0.007405552, 0.0025951825]

And `print nd`:
[-0.00,  -0.00,  -0.01,  -0.01,  -0.01,  -0.01,  0.00,  -0.00,  -0.00,  -0.00,  0.00,  0.00,  0.00,  -0.00,  -0.00,  -0.01,  -0.01,  -0.01,  0.01,  -0.01,  0.01,  -0.00,  0.00,  0.00,  -0.01,  -0.00,  0.00,  0.01,  0.01,  -0.00,  -0.00,  0.01,  -0.01,  0.01,  0.00,  -0.01,  -0.01,  -0.00,  0.01,  -0.00,  0.01,  -0.00,  0.01,  -0.00,  -0.00,  -0.00,  0.01,  -0.00,  -0.01,  0.01,  0.00,  -0.00,  0.01,  -0.01,  -0.01,  -0.01,  -0.00,  0.01,  -0.01,  0.00,  0.00,  0.00,  0.01,  -0.01,  0.00,  0.01,  -0.00,  0.01,  -0.01,  -0.01,  -0.01,  -0.01,  0.00,  0.01,  0.01,  0.00,  0.00,  0.01,  -0.01,  -0.01,  -0.00,  0.01,  0.01,  -0.00,  0.01,  0.00,  0.01,  -0.00,  -0.01,  0.00,  0.00,  0.00,  -0.00,  0.01,  0.01,  0.00,  -0.00,  -0.01,  -0.01,  0.00]

But `print  featuresVector_label` gives:

[0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00]

So please why Why featuresVector_label is zeros?

Thank you

#### Issue Description

Please describe our issue, along with:
- expected behavior
- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
Nd4j.create(...) methods are suited for java arrays for that, not for lists. It's math library after all....
Sure, you can just create java array from your lists, but that'll be sequential loop anyway.

**Comment by saudet** [comment]
Duplicate of https://github.com/deeplearning4j/nd4j/issues/1991

Please continue the discussion there.

**Comment by TamouzeAssi** [comment]
Sorry Sir @raver119 ,
I think you should not close this issue.

I face the same problem also in pure java code:
public INDArray getWordVector(String word){
        float[] buffer = new float[model.getDim()];
        List<Float> vector = model.getVector(word);
        for(int i = 0;i < model.getDim() ;i++){
            buffer[i] = vector.get(i);
        }
        return Nd4j.create(buffer);
    }

Th returned vector round the number. If you notice, if the number is <=0.005...  in your buffer vector then when you call create we get 0.00, and when the number is >0.005 then we get 0.01.
