### ISSUE TITLE
Invalid link to dataset in the documentation

### ISSUE THREAD

**Issue by Davidovic** [deeplearning4j/deeplearning4j#4329]
#### Issue Description

I just wanted to download an image dataset and noticed that there is an invalid link on https://deeplearning4j.org/opendata to the STL-10 dataset:
https://web.stanford.edu/~acoates/stl10/  --> "Object not found!"

#### Contributing

The correct link is:
http://cs.stanford.edu/~acoates/stl10/

**Comment by chrisvnicholson** [comment]
fixed
