### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by sameerkhurana10** [deeplearning4j/deeplearning4j#433]
System Details:

Linux version: 2.6.32-431.23.3.el6.x86_64 (mockbuild@sl6.fnal.gov) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-3) (GCC) ) #1 SMP Tue Jul 29 11:12:56 CDT 2014

java version "1.7.0_79"

Apache Maven 3.3.3

Got the Following compilation Error:
https://gist.github.com/sameerkhurana10/e0cdff717b5c5812019a

Yes, I  ran a git clone on nd4j, Canova, deeplearning4j in that order and then I ran clean maven install -- mvn clean install -DskipTests -Dmaven.javadoc.skip=true -- in each of those three directories. 

I got the compilation error while running maven install command in deeplearning4j root directory.

**Comment by agibsonccc** [comment]
Which java version?

**Comment by sameerkhurana10** [comment]
java version "1.7.0_79"

**Comment by sameerkhurana10** [comment]
>> java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (rhel-2.5.5.1.el6_6-x86_64 u79-b14)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/deeplearning4j/commit/b334d1bcf3d599efd0d9bfc52133df7de2b6701e
