### ISSUE TITLE
Fix cuda test profiles

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4332]
The test-nd4j-cuda-8.0 profile is actually cuda 9 :/

Ideally we should have both test-nd4j-cuda-8.0 and test-nd4j-cuda-9.0 profiles, OR just standardize on cuda 9 for tests

https://github.com/deeplearning4j/deeplearning4j/blob/master/pom.xml#L352-L368

cc @huitseeker

**Comment by huitseeker** [comment]
That's really just a cache invalidation issue :)

No, seriously, we should have native and cuda, and *then* the versions of the effective pom dictate which version of the lib gets tested.
