### ISSUE TITLE
ModelGuesser with InputStream is not working

### ISSUE THREAD

**Issue by kepricon** [deeplearning4j/deeplearning4j#4338]
#### Issue Description
I tried to use `ModelGuesser.loadModelGuess(InputStream stream)`
like below that is slightly modified from https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/test/java/org/deeplearning4j/util/ModelGuesserTest.java#L39
```
@Test
    public void testModelGuessWithStream() throws Exception {
        ClassPathResource sequenceResource =
                new ClassPathResource("modelimport/keras/examples/mnist_mlp/mnist_mlp_tf_keras_1_model.h5");
        assertTrue(sequenceResource.exists());
        File f = getTempFile(sequenceResource);
        Model guess1 = ModelGuesser.loadModelGuess(f.getAbsolutePath());
        assumeNotNull(guess1);

        try (InputStream inputStream = new FileInputStream(f)) {
            Model guess3 = ModelGuesser.loadModelGuess(inputStream);
            assumeNotNull(guess3);
        }
    }
```

I got the error message like below

```
org.deeplearning4j.util.ModelGuesserException: Unable to load model from input stream (invalid model file not a known model type)

	at org.deeplearning4j.util.ModelGuesser.loadModelGuess(ModelGuesser.java:171)
	at org.deeplearning4j.util.ModelGuesserTest.testModelGuessWithStream(ModelGuesserTest.java:76)
	
```
I checked https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/util/ModelGuesser.java#L97 is using file internally.
I suspect there might be some issue on handling stream to make a temp file.

**Comment by kepricon** [comment]
looks like `FileUtils.copyInputStreamToFile()` is working
```
File tempModel = null;
        try (InputStream inputStream = new FileInputStream(f)) {
            tempModel = new File("temp.zip");
            FileUtils.copyInputStreamToFile(inputStream, tempModel);

            Model guess2 = ModelGuesser.loadModelGuess(tempModel.getAbsolutePath());
            assumeNotNull(guess2);
        } finally {
            if (tempModel != null) {
                tempModel.deleteOnExit();
            }
        }
```

**Comment by kepricon** [comment]
I just found similar work for ModelSerializer by @wmeddie 

@agibsonccc changed it with `IOUtils.copy()` tho
https://github.com/deeplearning4j/deeplearning4j/commit/85d6525e4b7cb15b3240251466746b1ac4707c30#diff-5266319e20a5220dbe13e308b7e4082dL266

what was the ioutils compatible issue?

**Comment by AlexDBlack** [comment]
IOUtils should be compatible, yes - there shouldn't be any reason at all for it to differ from compInputStreamToFile (which isn't to say that there *isn't* a difference, but merely that there *shouldn't be*)

**Comment by kepricon** [comment]
agreed 
it shouldn't be different.

looks like need to flush via `os.flush()`
I'll create a pr for this with the test code
please do a review it @AlexDBlack
