### ISSUE TITLE
Last commit causing compilation error

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#434]
Stack trace when trying to compile DL4J. ND4J was pulled in the last 5 min and compiled first before pulling DL4J and compiling.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project deeplearning4j-core: Compilation failure: Compilation failure:
[ERROR] /Users/merlin/Documents/skymind/skymind-core/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/updater/AdaDeltaUpdater.java:[23,5] missing return statement
[ERROR] /Users/merlin/Documents/skymind/skymind-core/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/updater/NesterovsUpdater.java:[24,25] constructor Nesterovs in class org.nd4j.linalg.learning.Nesterovs cannot be applied to given types;
[ERROR] required: no arguments
[ERROR] found: double
[ERROR] reason: actual and formal argument lists differ in length
[ERROR] /Users/merlin/Documents/skymind/skymind-core/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/updater/SgdUpdater.java:[20,33] cannot find symbol
[ERROR] symbol:   class SgdUpdater
[ERROR] location: package org.nd4j.linalg.learning
[ERROR] /Users/merlin/Documents/skymind/skymind-core/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/updater/SgdUpdater.java:[20,80] cannot find symbol
[ERROR] symbol:   class SgdUpdater
[ERROR] location: package org.nd4j.linalg.learning
[ERROR] /Users/merlin/Documents/skymind/skymind-core/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/updater/SgdUpdater.java:[22,51] cannot find symbol
[ERROR] symbol:   class SgdUpdater
[ERROR] location: package org.nd4j.linalg.learning
[ERROR] /Users/merlin/Documents/skymind/skymind-core/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/updater/AdamUpdater.java:[24,20] constructor Adam in class org.nd4j.linalg.learning.Adam cannot be applied to given types;
[ERROR] required: double,double,double,double,double,double
[ERROR] found: no arguments
[ERROR] reason: actual and formal argument lists differ in length
[ERROR] -> [Help 1]

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/435

**Comment by nyghtowl** [comment]
Just pulled latest update and still getting stack trace error on compile:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project deeplearning4j-core: Compilation failure: Compilation failure:
[ERROR] /Users/merlin/Documents/skymind/skymind-core/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/updater/NesterovsUpdater.java:[24,25] constructor Nesterovs in class org.nd4j.linalg.learning.Nesterovs cannot be applied to given types;
[ERROR] required: no arguments
[ERROR] found: double
[ERROR] reason: actual and formal argument lists differ in length
[ERROR] /Users/merlin/Documents/skymind/skymind-core/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/updater/SgdUpdater.java:[20,33] cannot find symbol
[ERROR] symbol:   class SgdUpdater
[ERROR] location: package org.nd4j.linalg.learning
[ERROR] /Users/merlin/Documents/skymind/skymind-core/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/updater/SgdUpdater.java:[20,80] cannot find symbol
[ERROR] symbol:   class SgdUpdater
[ERROR] location: package org.nd4j.linalg.learning
[ERROR] /Users/merlin/Documents/skymind/skymind-core/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/updater/SgdUpdater.java:[22,51] cannot find symbol
[ERROR] symbol:   class SgdUpdater
[ERROR] location: package org.nd4j.linalg.learning
[ERROR] /Users/merlin/Documents/skymind/skymind-core/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/updater/AdamUpdater.java:[24,20] constructor Adam in class org.nd4j.linalg.learning.Adam cannot be applied to given types;
[ERROR] required: double,double,double,double,double,double
[ERROR] found: no arguments
[ERROR] reason: actual and formal argument lists differ in length
[ERROR] -> [Help 1]
[ERROR]

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/commit/f50dbf8bf1178db96f4b45bc16c53f6b038de015
