### ISSUE TITLE
OutOfMemoryError when specify org.bytedeco.javacpp.maxbytes to the size of gpu memory

### ISSUE THREAD

**Issue by fancyerii** [deeplearning4j/deeplearning4j#4346]
#### Issue Description
my machine has 8 GB gpu memory, So I run it with java -Xmx2G -Dorg.bytedeco.javacpp.maxbytes=8G -Dorg.bytedeco.javacpp.maxphysicalbytes=8G
but it throws OOM excpetion. Detail information is in this gist: https://gist.github.com/fancyerii/0189ef6674f82e68d1bdf176c4961745

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version master branch, last commit 01cc41e4bb183d5e8302b2e2d4a98bc6c0167cc2
* platform information (OS, etc) Ubuntu 16.04
* CUDA version, if used 8.0
* NVIDIA driver version, if in use 

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by saudet** [comment]
Would you have a code snippet that we could use to replicate this?

**Comment by saudet** [comment]
Ah, I see from your gist that it happens with VideoClassificationExample. I'm getting a `java.lang.UnsupportedOperationException: TODO` when running that example though. How did you get it running?

**Comment by fancyerii** [comment]
I compile the examples with <nd4j.backend>nd4j-cuda-8.0-platform</nd4j.backend>
and run java  -Xmx2G -Dorg.bytedeco.javacpp.maxbytes=8G -Dorg.bytedeco.javacpp.maxphysicalbytes=8G -cp target/dl4j-examples-0.9.1-bin.jar  org.deeplearning4j.examples.recurrent.video.VideoClassificationExample

**Comment by saudet** [comment]
But how did you get around the `java.lang.UnsupportedOperationException: TODO`? What code did you actually use?

**Comment by saudet** [comment]
Nevermind, the exceptions happens with new changes to VideoClassificationExample. The old version still runs. Anyway, even without GPU, this example needs a lot of memory. You'll need to give it at least `-Xmx8G`, on either CPU or GPU.
