### ISSUE TITLE
feedForward produces non-deterministic output in inference mode.

### ISSUE THREAD

**Issue by mboyanov** [deeplearning4j/deeplearning4j#4347]
I've encountered some issues with non-deterministic results from `feedForward( inputs, false)`.
The computation graph consists of several inputs, but the problem seems to be with the `text -> embedding -> rnn` flow.

I'll describe two scenarios below.

### GIVEN
a computation graph
### WHEN
input is in c order
and feedForward is called
### THEN
Somehow the text input array is corrupted with indices out of range.
```
java.lang.IllegalStateException: Index can't be < 0 and >= 40000
	at org.nd4j.linalg.factory.Nd4j.pullRows(Nd4j.java:5693)
	at org.nd4j.linalg.factory.Nd4j.pullRows(Nd4j.java:5666)
``` 
Note that this does not occur every time.
### EXPECTED
Inputs should work in both `c` and `f` mode.

### GIVEN
A computation graph
### WHEN
Input is in `f` order
and feedForward is called
### THEN
Result from first call is different to result to subsequent calls
### EXPECTED
`feedForward` is deterministic.

## Code
The minimal code to reproduce the problem is here https://github.com/mboyanov/dl4j-problem-reproduce.

 
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 0.9.1
* platform information (OS, etc) Ubuntu 16.04 
* Nd4j native backend

**Comment by AlexDBlack** [comment]
Thanks for the issue and the project (which helped a lot to quickly reproduce and fix this issue).
Fixed here, will be merged soon: https://github.com/deeplearning4j/deeplearning4j/pull/4349

**Comment by mboyanov** [comment]
Thanks :) Keep up the good work!
I'm guessing it will be merged into master and I'll have to build from source?

**Comment by AlexDBlack** [comment]
Yeah, will be merged after review. Snapshots are currently broken, so building from source is your only option (well, other than waiting for the next release - which we are working towards, but still could be a couple of weeks in the worst case).

**Comment by mboyanov** [comment]
Sounds good, should I close this or does it stay open until merge?
