### ISSUE TITLE
MnistDataSetIterator allows batch size of 0

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4351]
Should be picked up as invalid in the constructor - not later at runtime due to an obscure ND4J exception...

**Comment by RobAltena** [comment]
Is this true just for the MninstDataSetIterator or for the base class BaseDatasetIterator too?
In other words: Should this issue be called: "BaseDatasetIterator allows batch size of 0"

THe fix looks as easy as throwing an IllegalArgumentException.
