### ISSUE TITLE
Jars of dependencies are very big even if only a very minor part is needed

### ISSUE THREAD

**Issue by valcazar** [deeplearning4j/deeplearning4j#4355]
I have been using a regular MLP for time series forecasting under Windows. It works very well, but the size of the jars containing the dependencies are huge, the javacpp libraries in particular. Since I am going to deploy the project on Windows machines only, I could get rid of the libraries for other platforms, although the jar remains quite big. Is it possible to further reduce the size of the jar if I'm only going to use MLPs trained on CPUs?

Additionally, I have the possibility to have a project that does the training and another one to be deployed that just uses the trained net. However, even for loading and running the net javacpp is still needed. Is there any alternative? I mean, computing the output of a nn is not that expensive when the net contains only hundreds of neurons.

**Comment by agibsonccc** [comment]
@valcazar you can reduce the size by using nd4j-native and the windows clasifier. Beyond that, try to review what parts of dl4j you need.

**Comment by saudet** [comment]
We can usually exclude a lot of artifacts. Tools like ProGuard can help
identifying them.
