### ISSUE TITLE
Get rid of deprecated WordVectorSerializer methods

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#4359]
#### Issue Description

Please describe our issue, along with:
- expected behavior
- encountered behavior

#### Version Information
It's really confusing to remember what's deprecated and what's not. It's been long enough now.
Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/4680
