### ISSUE TITLE
Deeplearning4j objects creation and allocations

### ISSUE THREAD

**Issue by GlebYarnykh** [deeplearning4j/deeplearning4j#4364]
Hi!

I am interested into prediction only stage, not fitting (learning stage) of the network.

How much objects do deeplearning4j allocate during prediction stage? For us it is the main concern into using it in Java, because our project is almost garbage free: 1) Objects are reused and stored so that minimal objects are created 2) We also use Azul Zing and all related optimizations 3) Our benchmark on object-to-answer time is about 50 microseconds

Thanks a lot!

**Comment by raver119** [comment]
For us problem is split into 2 parts at this moment:

1) Allocation of objects in JVM. We're yet to work on this part actually. 
2) Allocation of off-heap memory for NDArrays. This part is solved using workspaces: https://deeplearning4j.org/workspaces

**Comment by AlexDBlack** [comment]
I'd recommend profiling it for yourself. For on-heap, a very rough estimate is something on the order of 1-5 INDArrays per layer for forward pass (for say dense or conv, more for LSTM, maybe less if you are using CuDNN). We haven't attempted to make DL4J garbage free yet, though upcoming changes (samediff, native layers) should get us closer.
