### ISSUE TITLE
Bug in MultiLayerNetwork.rnnTimeStep

### ISSUE THREAD

**Issue by coreyauger** [deeplearning4j/deeplearning4j#4365]
#### Issue Description
Bug in `MultiLayerNetwork.rnnTimeStep`

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java#L2699

The input can not be 2d (rank 2) and have rank 3 ?
```
if (inputIs2d && input.rank() == 3 && layers[layers.length - 1].type() == Type.RECURRENT) {
           //Return 2d output with shape [miniBatchSize,nOut]
            // instead of 3d output with shape [miniBatchSize,nOut,1]
            return input.tensorAlongDimension(0, 1, 0);
}
```

#### Version Information
* Deeplearning4j version  0.9.1
* platform information: Linux
* CUDA version, Not used
* NVIDIA driver version, Not in use

#### Contributing

If this is indeed a bug I would be happy to submit a PR.  Please offer some guidance with this :)

**Comment by AlexDBlack** [comment]
No, this is fine. We are using the ```input``` INDArray arg to store intermediate results for forward pass.

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java#L2687-L2699
