### ISSUE TITLE
" corrupted size vs. prev_size" when working with YOLO

### ISSUE THREAD

**Issue by DaGump** [deeplearning4j/deeplearning4j#4371]
#### Issue Description
I am working on a TinyYOLO example combined with my facenet dataset.
To achieve this I used 2 examples: The [HouseNumberDetection](https://github.com/deeplearning4j/dl4j-examples/blob/99a2708b6d46927b1cb70d16bead3b3dbd020909/dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/objectdetection/HouseNumberDetection.java)  and the [RedBloodCellDetection](https://gist.githubusercontent.com/saudet/fb8a4d9544dc3c411b302ccd6bbf87e7/raw/98833523dadf04e6e541cca78d82c8ebcd8a9771/RedBloodCellDetection.java)  Examples.

Source Code is here: https://gist.github.com/DaGump/066994465913df12cad173deec2eb984

Please describe our issue, along with:
- During training the JVM breaks with: corrupted size vs. prev_size
- see entire Log here: https://gist.github.com/DaGump/147139f496fcc954d5a84de549ba47f9

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j 0.9.2-SNAPSHOT build on Dec 1st 2017
* nd4j 0.9.2-SNAPSHOT build on Dec 1st 2017
* platform information: 
- Distributor ID:	LinuxMint
- Description:	Linux Mint 18.2 Sonya
- Release:	18.2
- Codename:	sonya

* no CUDA
* NVIDIA driver version, if in use

#### Contributing
I've build together a set of data where it happens (locally I have 20mio faces, but with the small one it also happens in the second or third epoch of training)
https://www.dropbox.com/s/awfmqz3nu6un8q4/voc.zip?dl=1

**Comment by DaGump** [comment]
I have also tested the two original tests [HouseNumberDetection](https://github.com/deeplearning4j/dl4j-examples/blob/99a2708b6d46927b1cb70d16bead3b3dbd020909/dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/objectdetection/HouseNumberDetection.java)  and the [RedBloodCellDetection](https://gist.githubusercontent.com/saudet/fb8a4d9544dc3c411b302ccd6bbf87e7/raw/98833523dadf04e6e541cca78d82c8ebcd8a9771/RedBloodCellDetection.java) 

The result are the same errors.

**Comment by hy9be** [comment]
@DaGump How did you get 0.9.2-SNAPSHOT? Did you build it by yourself?

**Comment by AlexDBlack** [comment]
@hy9be snapshots are not working, so yes, building from source is the only option currently. In the future, please keep these questions (unrelated to the actual issue you are posting on) to the main DL4J gitter channel - https://gitter.im/deeplearning4j/deeplearning4j

**Comment by hy9be** [comment]
@AlexDBlack Thanks! I was about to, but the link on the main README is dead. Just figured out it is a spelling issue. Submitted a correction PR. https://github.com/deeplearning4j/deeplearning4j/compare/master...hy9be:patch-1

**Comment by AlexDBlack** [comment]
@hy9be huh, thanks. A PR to fix that would be great.

@DaGump FYI there have been a number of fixes/PRs that may have impacted this issue, since you last built the stack: https://github.com/deeplearning4j/deeplearning4j/pulls?q=is%3Apr+is%3Aclosed
I'd recommend rebuilding and checking again. (If it passes/doesn't crash with WorkspaceMode.NONE then it's quite possibly fixed already)

**Comment by saudet** [comment]
Yeah, this isn't happening here. @DaGump Try to reclone and rebuild everything.

**Comment by DaGump** [comment]
@AlexDBlack & @saudet 
Recloned, Rebuild, Retested => works perfect

Thank you all for the great work
