### ISSUE TITLE
Regression with Tanh  output can't converge when label is -1, 1

### ISSUE THREAD

**Issue by johnhuang-cn** [deeplearning4j/deeplearning4j#4375]
#### Issue Description

I train AlphaGo model, the regression output layer is tanh and the label is -1, 1 to indicate game lost/win. It can't converge. If I changed the train data label to -0.99, 0.99, then it works. I'm not sure if it is a bug. According to Deepmind AlphaGo paper, the model can be trained with -1, 1 and converged.

#### Version Information

* Deeplearning4j version: 0.9.1
* platform information (OS, etc): Windows 10
* CUDA version: 8.0

**Comment by AlexDBlack** [comment]
We'll need more information to go on than this.
At a minimum, the network configuration. 
UI screenshots would also help a lot. Something we can actually run to reproduce this would be even better...

**Comment by johnhuang-cn** [comment]
It can be reproduced in any regression network with tanh output and train data label are all 1, -1. 
My network arch is same as that described in AlphaGo paper:

input: 10 * 361, all are 0/1, the regression label of train data are all 1, -1.
layer1: 128 ConvolutionLayer.Builder(new int[]{5,5}, new int[]{1,1}, new int[]{2,2}).activation(Activation.RELU).nOut(128) 
layer2-11: ConvolutionLayer.Builder(new int[]{3,3}, new int[]{1,1}, new int[]{1,1}).activation(Activation.RELU).nOut(128)
layer12: ConvolutionLayer.Builder(new int[]{3,3}, new int[]{1,1}, new int[]{1,1}).activation(Activation.IDENTITY).nOut(1)
layer13: DenseLayer.Builder().activation(Activation.IDENTITY).nOut(256)
output layer: OutputLayer.Builder().lossFunction(LossFunctions.LossFunction.MSE).activation(Activation.TANH)              .nOut(1)

The score chart is a horizontal line around 6.5-6.8 after 10 thousand iterations, then I stop it. After changed 1, -1 to 0.99, -0.99, the same network can begin converge after about 1000 iterations.

If you need more details, please let me know. If you need the code and data to test, I can prepare it later.

**Comment by johnhuang-cn** [comment]
Update:
Seems won't occur when I decrease the filter to 64 and reduce the layers. May be caused by other problem. Close this issue at first.
