### ISSUE TITLE
Importing Conv net from keras1 to dl4j

### ISSUE THREAD

**Issue by emc5ud** [deeplearning4j/deeplearning4j#4381]
#### Issue Description
Hi, I've got a Unet i made in python with the following architecture

[model](https://gist.github.com/emc5ud/9f3dfffa38dde69da3a31e4a34418e50)

saved using

```python
model.save("mymodel")
```
loaded using 
```scala
val unet_model: ComputationGraph = KerasModelImport.importKerasModelAndWeights("mymodel")
```

Its my understanding that some elements of this architecture are not supported in 0.9.1 but have been committed within the last couple of months. However, after building 0.9.2 locally and running I get the following message:

Exception in thread "main" java.lang.IllegalStateException: Invalid input type (layer index = -1, layer name="convolution2d_19_loss"): expected FeedForward input type. Got: InputTypeConvolutional(h=160,w=160,d=10)

#### Version Information
keras: 1.2.2
dl4j:     0.9.2-SNAPSHOT

**Comment by maxpumperla** [comment]
what happened?

**Comment by emc5ud** [comment]
Sorry I shouldn't have closed this without an explanation. I switched to using 
```scala
val unet_model: ComputationGraph = KerasModelImport.importKerasModelAndWeights("mymodel_json", "mymodel_weights")
``` 
for the time being. But I have more fundamental issues with my 0.9.2-snapshot build that I posted [here](https://github.com/deeplearning4j/nd4j/issues/2360)
