### ISSUE TITLE
preTrainIterations(int preTrainIterations) in BasePretrainNetwork.Builder has no effect

### ISSUE THREAD

**Issue by yonibr** [deeplearning4j/deeplearning4j#4391]
#### Issue Description

The variable set by the method preTrainIterations(int preTrainIterations) in the class  BasePretrainNetwork.Builder is not used elsewhere.

#### Version Information

Dl4j 0.9.1

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/4394
