### ISSUE TITLE
Nd4j perfomance

### ISSUE THREAD

**Issue by gagatust** [deeplearning4j/deeplearning4j#4393]
I ran the test to compare the performance java vs nd4j with small N

Test https://github.com/deeplearning4j/libnd4j/issues/158
Log, N = 1000
```
double[]...
time: 38
NDArray...
time: 366
```
Log, N = 100
```
double[]...
time: 6
NDArray...
time: 377
```
Log, N = 10
```
double[]...
time: 2
NDArray...
time: 217
```

Win7 64 Pro, i5-3470, 16 Gb.
```xml
<dependency>
     <groupId>org.nd4j</groupId>
     <artifactId>nd4j-native-platform</artifactId>
     <version>0.9.1</version>
</dependency>

```

**Comment by raver119** [comment]
Problem is: when we're calling any reduce-to-number operation, we're creating NDArray for result. And in case of tiny arrays - array creation takes way more time then operation itself.

For N = 100, operation takes 18% of time. And the rest of time was spent on array creation/assign of initial value/ etc.

**Comment by raver119** [comment]
Another part of the problem (minor in this case, though) was in too low element & tad thresholds set by default. This is fixed now.
