### ISSUE TITLE
About Memory Configurations

### ISSUE THREAD

**Issue by billbargens** [deeplearning4j/deeplearning4j#4402]
What's the relationship or differences of the two ways of memory configuration?
Can anyone explains the working mechanism of them in detail?
- -Dorg.bytedeco.javacpp.maxbytes
- CudaEnvironment setMaximumDeviceCache(2L * 1024L * 1024L * 1024L)

**Comment by raver119** [comment]
First one defines physical limit, like JVM's Xmx option.
And second one sets how many memory can be cached for later reuse. I.e. you allocate array of 100 bytes, eventually release it, and if MaxDeviceCache value allows it - this chunk can be stored in cache for later reuse, to avoid free/malloc expenses.

However please note: cache isn't used with workspaces.

**Comment by billbargens** [comment]
So the first one is for CPU memory， the second is for GPU memory?

**Comment by raver119** [comment]
No, first one is honored for both CPU and CUDA.
Second one is solely for CUDA backend.

**Comment by billbargens** [comment]
So the second one should be small than the first one?

**Comment by raver119** [comment]
It should be smaller then your GPU memory. But in most cases the best solution is: keep defaults, and use workspaces.

https://deeplearning4j.org/workspaces

**Comment by billbargens** [comment]
If I set the first one to 8G and the second one to 2G, does that means in theory my application can occupy up to 10G gpu memory?

**Comment by raver119** [comment]
No.

**Comment by billbargens** [comment]
So can you give me some examples about:
    - when the memory assigned by "bytedeco.javacpp.maxbytes" will be used  
    - and when the memory assigned by "setMaximumDeviceCache" will be used 
in trainning or inference process?
I do appreciate for your help!

**Comment by raver119** [comment]
1) maxbytes is used during allocation, to determine if we still can allocate something. It's upper boundary for allocations.

2) device cache is used when you're freeing memory. If current cached amount < maximum, memory chunk will be stored for reuse. 

Simple as that.

**Comment by billbargens** [comment]
OK, I will make some experiments to verify my understands. 
That you so much for your
