### ISSUE TITLE
Unsupported keras layer type Convolution1D

### ISSUE THREAD

**Issue by sdeck51** [deeplearning4j/deeplearning4j#4412]
Hi,

I'm trying to import a keras model that has 1dConvolutions. The website shows that they are supposed to be supported but I'm getting an UnsupportedKerasConfigurationException:

org.deeplearning4j.nn.modelimport.keras.UnsupportedKerasConfigurationException: Unsupported keras layer type Convolution1D. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.

I'm using version 0.9.1 in a maven project on windows. Are these layers not supported yet or is there some tinkering I can do to get it importing correctly?

**Comment by maxpumperla** [comment]
they are on master only for now, not 0.9.1. There will be a release this month.
