### ISSUE TITLE
Tests-before-merge discussion

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#4425]
This isn't an issue really, but general discussion.

With libnd4j we have problem: often after PR is merged, we get issues with specific OSes/compilers. I.e. we use linux/macos for development, but issues can be discovered on android or windows msvc for example.

So, maybe it's time to bring back requirement for jenkins successful tests run before merge?

cc @agibsonccc @huitseeker @saudet @AlexDBlack @sshepel

**Comment by AlexDBlack** [comment]
I'm in favor of this. Breaking changes and non-compilation can certainly be a disruption, and it's not really feasible to get devs to test all platforms manually before each PR is merged.
Automatic testing of upstream repos (nd4j, dl4j, datavec) would be valuable too IMO.

However, testing isn't free (i.e., can slow development): thus I would suggest looking at clearly defined exceptions to this "test before merge" rule. For example, a PR that modifies (Java) tests only, or is simple/isolated enough to not cause problems, might be mergeable immediately.

**Comment by raver119** [comment]
oh yea, that should be clearly separable from libnd4j builds in lots of cases.

I.e. we could have a requirement - same branch name everywhere, if you're adding stuff into multiple repos. If branch name is found in libnd4j - rebuild it. If not - then not.

**Comment by raver119** [comment]
at the same time, libnd4j changes would be nice to test again nd4j tests as well.

**Comment by agibsonccc** [comment]
I agree with this as well..one thing I'm concerned about here that I'd like to fix is long running changes that cause heavy divergence. I'd like to have a way of keeping PRs small. Jenkins is part of that and will help but there's also a workflow discussion to have here.

**Comment by raver119** [comment]
Problem i'm often facing these days usually happens even with small PRs. 
I.e. @shyrma added few ops last week. Just ops, nothing ground breaking etc. But few hours later i was contacted by @sshepel - turned out that android build was broken. After fast investigation we've found out that std::tgamma and std::lgamma are missing in gcc 4.9 (which is a bug), but we were not aware of this before build was broken. Obviously, we've fixed that, but as you can see - even small PRs can cause a problem on various platforms.

**Comment by saudet** [comment]
I agree, the problem is just with getting CI working...

**Comment by huitseeker** [comment]
As far as I'm concerned, I 200% agree with test-pass-before-merge on all projects. I think the CI efforts deserve help and support increase by a good order of magnitude.

**Comment by agibsonccc** [comment]
So the other thing here is pull request management. Right now we're focused on new features and we to set some standards in place for stability as well. The CI will fix a lot of that but it's not the only issue.

The eclipse migration will help that somewhat, but there's definitely more to do yet.

**Comment by raver119** [comment]
Implemented for libnd4j, and will be implemented soon for monorepo
