### ISSUE TITLE
Problem on Debian 9 ("Stretch")

### ISSUE THREAD

**Issue by AleZonta** [deeplearning4j/deeplearning4j#4431]
#### Issue Description

I am using Evolutionary Algorithms to evolve the weights of some neural networks. The algorithm uses crossover and mutation to change the weights of the NN, then they are tested with some inputs and, if the output it is good, the network receives a fitness value proportional to how good is the output.
This requires the ability to extract and set the weights of the network under analysis.
To do this I am using the `setParameters(weights)` method and an LSTM network.
I am running the same program in five different environments (one laptop and two computers with MacOS, one cluster using CentOS 7.2 and another cluster using Debian 9).

The expected behavior of the method is:
[Gist.Github.com](https://gist.github.com/AleZonta/b41e3bd10c849f61fe211cfce2a26d74)

The encountered behavior of the method is:
[Gist.Github.com](https://gist.github.com/AleZonta/71a5e885665b141a5b2a779cb4698ce0)

As visible in the second gist, some values are changed to very small values or 0.0 and I can not understand why this is happening.
Having those values as weights of the NN, it generates a lot of `NaN` value as output.
I thought multithreading was the problem, but also running everything in a sequential way does not solve the problem. The funny fact is that only on Debian 9 is not working correctly. All the other environment I tried, have no problem.
Have you ever had a problem like this?
Consider that the cluster updated his operating system to Debian 9 from Debian 7 and with this update, I started to see this problem.
I had the same problem in the past but magically disappeared without doing anything...

#### Version Information

Please indicate relevant versions, including, if relevant:
* Deeplearning4j version
```
<dependency>
    <groupId>org.deeplearning4j</groupId>
    <artifactId>deeplearning4j-core</artifactId>
    <version>0.9.1</version>
</dependency>
<dependency>
    <groupId>org.deeplearning4j</groupId>
    <artifactId>rl4j-api</artifactId>
    <version>0.9.1</version>
</dependency>
<dependency>
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native-platform</artifactId>
    <version>0.9.1</version>
</dependency>
```

* platform information (OS, etc)
   - The systems where the program works correctly:

      > MacBook Pro (Retina, 15-inch, Mid 2015), 2,2 GHz Intel Core i7, 6 GB 1600 MHz DDR3 macOS Sierra Version 10.12.6 -> java version "1.8.0_92"

      > Mac Pro (Mid 2012), 2 x 3,06 GHz 6-Core Intel Xeon, 28 GB 1333 MHz DDR3 macOS Sierra Version 10.12.5 -> java version "1.8.0_102"

     > Mac Pro (Early 2008), 2 x 2,8 GHz Quad-Core Intel Xeon, 10 GB 800 MHz DDR2 FB-DIMM OS X EL Capitan Version 10.11.6 -> java version "1.8.0_77"

     > [DAS5](https://www.cs.vu.nl/das5/home.shtml): a node has a  dual 8-core 2.4 GHz,  64 GB Memory, CentOS 7.2. -> jdk-1.8.0

   - The system where the program does not work:

     > [LISA](https://userinfo.surfsara.nl/systems/lisa): a normal node has E5-2650L | 1.80 GHz, 32 GB QPI 8.00 GT/s, Debian 9 ->  java/1.8u40

* pom of the project
[Gist.Github.com pom](https://gist.github.com/AleZonta/dec853d5f0bf2454bbbd9983d96bf41d)

**Comment by raver119** [comment]
Can you set env variable ND4J_FALLBACK to `true`, and run on debian again? I wonder if that's somehow OpenBLAS-related

**Comment by raver119** [comment]
P.s. once you set that var and run nd4j, you should see fallback-related warning message.

**Comment by AleZonta** [comment]
With ND4J_FALLBACK to `true` the only different lines I see on the log file are:
```
17:51:46,948 INFO  ~ Loaded [CpuBackend] backend
17:51:47,445 INFO  ~ Number of threads used for NativeOps: 8
17:51:47,933 INFO  ~ Number of threads used for BLAS: 8
17:51:47,934 INFO  ~ Backend used: [CPU]; OS: [Linux]
17:51:47,934 INFO  ~ Cores: [16]; Memory: [7.0GB];
17:51:47,934 INFO  ~ Blas vendor: [MKL]
17:52:44,381 INFO  ~ Starting MultiLayerNetwork with WorkspaceModes set to [training: NONE; inference: SEPARATE]
```
And the problem is still there. 
The helpdesk of the cluster suggested me to try a different version of the java8 module but nothing changed.
Do you want me to run the program with all the properties set as a DEBUG mode in the `log4j.properties` file?

**Comment by raver119** [comment]
That just means fallback mode wasn't enabled :(

And no, ND4J_FALLBACK is expected to be environment variable, and it's printed out at info level at least....

**Comment by raver119** [comment]
Could you try OpenBLAS instead of MKL then?

**Comment by AleZonta** [comment]
But if the output from `System.out.println(Nd4j.isFallbackModeEnabled());` is `true`, doesn't mean the fallback mode is active?

How can I force to use OpenBLAS instead of MKL? I couldn't find anything online

**Comment by raver119** [comment]
Hm. If you see `true` there, it should be working then….

cc @saudet

**Comment by saudet** [comment]
It might be a threading problem, but inside ND4J or MKL. Try to set the OMP_NUM_THREADS=1 environment variable and see if that helps. There's a couple of other things as well as mentioned at https://deeplearning4j.org/native

**Comment by AleZonta** [comment]
Following this page [How to set good environment variables for the Intel MKL library](http://www.diracprogram.org/doc/release-12/installation/mkl.html) and your suggestion I set:
```
export MKL_NUM_THREADS=8
export MKL_DYNAMIC="FALSE"
export OMP_NUM_THREADS=1
```
and it works without problem.
The only downside is that the experiment is superslow. Instead of ending in 24 hours it ends in almost 120 hours.
The helpdesk of the cluster wrote me that multiple OpenBLAS versions are installed:

> damian@login1:\~$ module load eb
> damian@login1:~$ module av OpenBLAS && module av *blas*
> -------------------------------------------- /hpc/eb/Debian9/modulefiles/numlib --------------------------------------------
> OpenBLAS/0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1  OpenBLAS/0.2.20-GCC-6.4.0-2.28
> Default version for module blast will change to 2.4.0 on 23-12-2017
> ----------------------------------------- /hpc/sw/modules/modulefiles/applications -----------------------------------------
> blast/2.2.23  blast/2.2.24(default)  blast/2.2.26  blast/2.4.0  mpiblast/1.4.0(default)
> 
> ------------------------------------------ /hpc/sw/modules/modulefiles/libraries -------------------------------------------
> blas/gnu/2011-04-19(default)  blas/intel/2011-04-19(default)  cblas/intel(default)
> blas/intel(default)           cblas/gnu/2011-04-20(default)   cblas/intel/2011-04-20(default)

The app is always loading MKL instead OpenBLAS. Is there any way to force the loading of the other one? Right now the experiment is way too slow

**Comment by saudet** [comment]
@AleZonta Yes, just set the "java.library.path" system property to the empty string "":
https://deeplearning4j.org/quickstart#troubleshooting

**Comment by saudet** [comment]
I've also added the "org.bytedeco.javacpp.openblas.nomkl" system property to disable MKL when set to "true". You'll also need to add the latest version of openblas-platform (currently 0.2.20-1.4) to your dependencies, but that should be it:
https://github.com/bytedeco/javacpp-presets/tree/master/openblas
http://search.maven.org/#search%7Cga%7C1%7Copenblas
