### ISSUE TITLE
Keras model import with LSTM return_sequences=False output type is wrong

### ISSUE THREAD

**Issue by mboyanov** [deeplearning4j/deeplearning4j#4432]
#### Issue Description

I am importing a Keras LSTM where return_sequences = False. On master, this is currently supported by wrapping the LSTM in a LastTimeStep. However, calling the `getOutputType` method is wrong as it returns InputTypeRNN regardless of the value for the returnSequences field.

GIVEN:
LSTM layer with `return_sequences = False`
WHEN:
calling getOutputType
THEN:
should return InputTypeFeedForward
ACTUAL:
return InputTypeRNN

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - 0.9.2-SNAPSHOT

#### Contributing

I have patched this in https://github.com/mboyanov/deeplearning4j/commit/3b6fff721c2894bcfb22a18d9e4617a4c26812ac , but I have no idea how to test it against the whole dl4j stack.

**Comment by maxpumperla** [comment]
@mboyanov if I augment the test that you also touched like this:

```
        LSTM layer;
        LastTimeStep lts;
        if (rs) {
            KerasLstm kerasLstm = new KerasLstm(layerConfig);
            InputType outputType = kerasLstm.getOutputType(InputType.recurrent(1337));
            assertEquals(outputType, InputType.recurrent(N_OUT));
            layer = (LSTM) kerasLstm.getLSTMLayer();
        } else {
            KerasLstm kerasLts = new KerasLstm(layerConfig);
            lts = (LastTimeStep) kerasLts.getLSTMLayer();
            InputType outputType = kerasLts.getOutputType(InputType.recurrent(1337));
            assertEquals(outputType, InputType.feedForward(N_OUT));
            layer = (LSTM) lts.getUnderlying();
        }
```
it absolutely does work. Are you saying that if I add a preprocessor, it will fail? Can you please share how you test this?

**Comment by maxpumperla** [comment]
btw, in your code you should check if the preprocessor is `null`:
```
        if (!returnSequences && preProcessor != null) {
            return this.getLSTMLayer().getOutputType(-1, preProcessor.getOutputType(inputType[0]));
        }
```

**Comment by mboyanov** [comment]
My use case is that I'm importing a model where I'm concatenating the last time step with another two feedforward layers. Then, the merge vertex throws an exception, because you can't merge vertices with different output types.
The test does look better, I'll modify it and start a pull request tomorrow.

**Comment by mboyanov** [comment]
Started a pull request https://github.com/deeplearning4j/deeplearning4j/pull/4434 .

**Comment by maxpumperla** [comment]
thanks
