### ISSUE TITLE
Allow for 3D output in Embedding layers

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/deeplearning4j#4433]
#### Issue Description

Currently, our `Embedding` layers are of feedforward output type, take in one index as input and spit out a vector. It would be great to embed (mini-batches of) _sequences of indexes_ as well, i.e. map: 

input shape (mb, seq_length) to output shape (mb, seq_length, output_dim).

This might call for a layer wrapper for `Embedding`, as recently done for LSTMs. Apart from being convenient in general, this would also allow us to import more complex Keras models as well. In Keras the output of an embedding layer is always 3D and right now we have no means to properly map this. `seq_length` is the special case that works.

Pinging @AlexDBlack for ideas, I'm sure you have great suggestions. Happy to discuss and implement this.

**Comment by AlexDBlack** [comment]
Is this for RNNs?
If so, a time distributed layer wrapper could work here?

**Comment by maxpumperla** [comment]
closing this, turns out to be improper handling of preprocessors on my side.
