### ISSUE TITLE
Keras ReshapePreprocessor dynamic minibatch size is not dynamic

### ISSUE THREAD

**Issue by mboyanov** [deeplearning4j/deeplearning4j#4435]
#### Issue Description

I'm importing a Keras Model with Reshape layer. This gets translated into a `ReshapePreprocessor` . I'm then calling evaluate with a multidatasetiterator. However, the total number of examples is not divisible by the minibatch size. In this case, the preprocesser has cached the minibatch size and ignores the size of the last minibatch which is smaller, which leads to an exception.
For example, my regular minibatch shape is (256, 10) , but the last batch is (12, 10). 
```
@Override
    public INDArray preProcess(INDArray input, int miniBatchSize) {
        // the target shape read from a keras config does not have mini-batch size
        // included. We prepend it here dynamically.
        if (targetShape.length + 1 == input.shape().length) {
            targetShape = prependMiniBatchSize(targetShape, miniBatchSize);
            inputShape = prependMiniBatchSize(inputShape, miniBatchSize);
            this.hasMiniBatchDimension = true;
        }
        if (prod(input.shape()) == prod((targetShape))) {
            return input.reshape(this.targetShape);
        } else {
            throw new IllegalStateException("Input shape " + Arrays.toString(input.shape())
                    + " and output shape" + Arrays.toString(inputShape) + " do not match");
        }
    }
```
In this case  the `IllegalStateException` will be thrown because input.shape() = (12,10) and targetShape=(256,10).

## Given
A keras ReshapePreprocesser

## WHEN

preprocess is called with a different minibatch size than cached

## THEN

Reshapes the input.

## ACTUAL

throws an IllegalStateException

* Deeplearning4j version 0.9.2-SNAPSHOT

#### Contributing
I'm open to fixing it, but there are multiple solutions. One approach would be to actually do as the comment says and compute the batch shape dynamically:
```
// the target shape read from a keras config does not have mini-batch size
        // included. We prepend it here dynamically.
        int[] batchShape = targetShape;
        int[] batchInputShape = inputShape;
        if (targetShape.length + 1 == input.shape().length) {
            batchShape = prependMiniBatchSize(targetShape, miniBatchSize);
            batchInputShape = prependMiniBatchSize(inputShape, miniBatchSize);
            this.hasMiniBatchDimension = true;
        }
        if (prod(input.shape()) == prod((batchShape))) {
            return input.reshape(this.targetShape);
        } else {
            throw new IllegalStateException("Input shape " + Arrays.toString(input.shape())
                    + " and output shape" + Arrays.toString(inputShape) + " do not match");
        }
```
However, I'm not sure what this would entail for the `hasMiniBatchDimension` property.

**Comment by maxpumperla** [comment]
@mboyanov thanks for noting this, keep up this valuable feedback!

How about we introduce a field
```
private int miniBatchSize
```

and in `preProcess`, when a new `miniBatchSize` comes in we check for equality and update if necessary:
```
if (this.miniBatchSize != miniBatchSize) {
  setMiniBatchSize(miniBatchSize)  
  setTargetShape(miniBatchSize)
}
```

Would you feel comfortable to do a PR for this?

**Comment by mboyanov** [comment]
Started PR https://github.com/deeplearning4j/deeplearning4j/pull/4436

**Comment by maxpumperla** [comment]
@mboyanov I think we forgot to close this.
