### ISSUE TITLE
Add one-line creation of UI uber jar for remote serving

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#4439]
#### Issue Description

Currently, if we want to set up the UI to run as a remote server for something such as Spark, the user needs to create an empty project and compile their own uber jar. This is cumbersome and not friendly.

Adding the ability to generate a UI jar directly from the project would save time and make setup significantly faster.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version master

#### Contributing

Wait until client work is done, and I can do this.

**Comment by crockpotveggies** [comment]
Alternatively:

> No need to create a jar, just a submodule that depends on -ui with a three line main method.
or no main method at all, and a maven shade config.
we could have a version of UIServer that forks it's own Java process and downloads the necessary jar from somewhere else.

**Comment by crockpotveggies** [comment]
cc @wmeddie

**Comment by crockpotveggies** [comment]
Alternatively:

> could have a simple stand-alone runnable jar that builds mini UI project if required (assuming maven is installed)

via @AlexDBlack

**Comment by wmeddie** [comment]
See this example project:

https://github.com/wmeddie/dl4j-ui-server

**Comment by AlexDBlack** [comment]
We have the deeplearning4j-ui-standalone module now - which does exactly this (and is hosted on maven central :))
https://github.com/deeplearning4j/deeplearning4j/tree/master/deeplearning4j-ui-parent/deeplearning4j-ui-standalone
