### ISSUE TITLE
ROC curves not updated after merge

### ISSUE THREAD

**Issue by QAFabianHuch** [deeplearning4j/deeplearning4j#4442]
#### Issue Description

 - expected: after ``merge`` of two ``org.deeplearning4j.eval.ROC`` evaluations, roc/prc-curves are calculated for merged data
 - actual: curves are not re-calculated if they were already set (e.g. from previous calculation)

This causes evaluation metrics to be incorrect. The auc/auprc _is_ set to ``null``, but as the areas are re-calculated using the old curves, the next call of ``calculateAUC`` still returns old area

affects 0.9.1

**Comment by AlexDBlack** [comment]
Thanks for reporting this. Reproduced and fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/4443
