### ISSUE TITLE
Data & ETL Doc: NormalizerMinMaxScaler Error 

### ISSUE THREAD

**Issue by fulltopic** [deeplearning4j/deeplearning4j#4456]
#### Issue Description
https://deeplearning4j.org/etl-userguide

Please describe our issue, along with:
-  Doc: DL4J --> Data & ETL --> ETL User Guide --> Available ND4j Pre-Processor --> NormalizerMinMaxScaler should be "X_std = ((X - min)/(max-min)) (given_max - given_min) + given_mi"
- Got "X -> (X - min/(max-min)) * (given_max - given_min) + given_mi"

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing
Would you please help to assign to me although I have not yet had the doc repo forked? Thank you.

**Comment by tomthetrainer** [comment]
The docs are the gh-pages branch of the repo. 

Fork, switch to gh-pages branch, the page you are asking to edit is
etl-userguide.md

Is that enough to get you started?

**Comment by fulltopic** [comment]
Pull request #4464 created. Thank you very much

**Comment by tomthetrainer** [comment]
Thanks a lot for this,
