### ISSUE TITLE
keras model import issue

### ISSUE THREAD

**Issue by solracson** [deeplearning4j/deeplearning4j#4458]
#### Issue Description

unable to import keras model

#### Version Information

compile group: 'org.deeplearning4j', name: 'deeplearning4j-modelimport', version: '0.9.1'
    compile group: 'org.deeplearning4j', name: 'deeplearning4j-core', version: '0.9.1'
    compile group: 'org.datavec', name: 'datavec-api', version: '0.9.1'
    testCompile group: 'org.nd4j', name: 'nd4j-native-platform', version: '0.9.1'
[model_architecture.zip](https://github.com/deeplearning4j/deeplearning4j/files/1598536/model_architecture.zip)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by maxpumperla** [comment]
@solracson this is not a valid json, but just from the looks of it you should be fine if you build master.  Unlikely that this will run on 0.9.1.

If the problem persists (on master), reopen and add a proper model json, full stack trace with error message and ideally the h5 file. thanks

**Comment by raver119** [comment]
snapshots should be working now.

**Comment by solracson** [comment]
thanks ! just getting started for DL4J, are the snapshots available in maven repo or another repo

**Comment by AlexDBlack** [comment]
@solracson See this page for details on snapshots: https://deeplearning4j.org/snapshots
