### ISSUE TITLE
ROC.merge() fails with "mismatched lengths" error for large data sets

### ISSUE THREAD

**Issue by turambar** [deeplearning4j/deeplearning4j#4460]
#### Issue Description

`ROC.merge(...)` fails for larger data sets with a "mismatched lengths" ND4J error. This could easily arise when, e.g., doing distributed training of a binary classifier with a large training data set on Spark. The culprint is a call to NDArray.assign on [line 672](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/eval/ROC.java#L672):

```
newProbAndLabel.assign(probAndLabel.get(NDArrayIndex.interval(0, exampleCount), NDArrayIndex.all()));
```

when `exampleCount` and `newProbAndLabel.rows()` are not equal. You can replicate the error by tweaking the [testROCMerge](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/test/java/org/deeplearning4j/eval/ROCTest.java#L856) class in the ROC unit tests. See comments below for details.

#### Version Information

Please indicate relevant versions, including, if relevant:

* DL4J master

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/4459

**Comment by turambar** [comment]
Thanks!
