### ISSUE TITLE
overloaded method value zeros with alternatives

### ISSUE THREAD

**Issue by luolianhai** [deeplearning4j/deeplearning4j#447]
i have problems while compiling deeplearning4j:
[ERROR] /home/luolianhai/deeplearning4j/deeplearning4j-scaleout/spark/dl4j-spark-ml/src/main/scala/org/deeplearning4j/spark/ml/nn/TrainingStrategy.scala:79: overloaded method value zeros with alternatives:
  (x$1: <repeated...>[Int])org.nd4j.linalg.api.ndarray.INDArray <and>
  (x$1: Int)org.nd4j.linalg.api.ndarray.INDArray
 cannot be applied to (Array[Int])
[ERROR]        val accumulatedParams = sc.accumulator(Nd4j.zeros(networkParams.shape()))(INDArrayAccumulatorParam)
[ERROR]                                                    ^
[ERROR] /home/luolianhai/deeplearning4j/deeplearning4j-scaleout/spark/dl4j-spark-ml/src/main/scala/org/deeplearning4j/spark/ml/nn/TrainingStrategy.scala:103: overloaded method value zeros with alternatives:
  (x$1: <repeated...>[Int])org.nd4j.linalg.api.ndarray.INDArray <and>
  (x$1: Int)org.nd4j.linalg.api.ndarray.INDArray
 cannot be applied to (Array[Int])
[ERROR]   def zero(initialValue: INDArray): INDArray = Nd4j.zeros(initialValue.shape())
[ERROR]                                                     ^
[ERROR] two errors found
[INFO] ---------------------------------

line 79 and 103 of TrainingStrategy.scala are:
val accumulatedParams = sc.accumulator(Nd4j.zeros(networkParams.shape()))(INDArrayAccumulatorParam)
def zero(initialValue: INDArray): INDArray = Nd4j.zeros(initialValue.shape())

**Comment by agibsonccc** [comment]
Do a git pull. This  doesn't reflect current master which has the real syntax for unpack ints.
