### ISSUE TITLE
net training: java.lang.NumberFormatException: empty String

### ISSUE THREAD

**Issue by MrDallOca** [deeplearning4j/deeplearning4j#4470]
#### Issue Description

- expected behavior
A nice and well-trained neural net!

- encountered behavior
```
Exception in thread "ADSI prefetch thread" 
java.lang.RuntimeException: java.lang.NumberFormatException: empty String
at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$AsyncPrefetchThread.run(AsyncDataSetIterator.java:442)
Caused by: java.lang.NumberFormatException: empty String
at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
at java.lang.Double.parseDouble(Double.java:538)
at org.datavec.api.writable.Text.toDouble(Text.java:593)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritables(RecordReaderMultiDataSetIterator.java:419)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertFeaturesOrLabels(RecordReaderMultiDataSetIterator.java:271)
	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:240)
at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:177)
at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:306)
at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:393)
at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:51)
at org.deeplearning4j.datasets.iterator.AsyncDataSetIterator$AsyncPrefetchThread.run(AsyncDataSetIterator.java:423)
```
- code
```clojure
(defn do-yer-thing []
  (let [train-reader (CSVRecordReader. 0 \,)
        _ (.initialize train-reader
                       (NumberedFileInputSplit.
                        (str "resources/" all-path "part-%05d")
                        0 150))
        train-iterator (RecordReaderDataSetIterator. train-reader 1000 45 49 true)
        epochs 1
        ready-for-more false]
    (.init net)
    (doseq [n (range 0 epochs)]
      (.reset train-iterator)
      (.fit net train-iterator)) ;; exception
    (ModelSerializer/writeModel net (java.io.File. "enem-net") ready-for-more)))
```

Java equivalent:
```java
public void doYerThing (){
	CSVRecordReader train_reader = new CSVRecordReader(0, ',');
	train_reader.initialize(new NumberedFileInputSplit
					("resources/" + all_path + "part-%05d", 0, 150));
	RecordReaderDataSetIterator train_iterator =
		new RecordReaderDataSetIterator(train_reader, 1000, 45, 49, true);
		int epochs = 1;
	boolean ready_for_more = false;

	net.init();

	for (int i = 0; i < epochs; i++) {
		train_iterator.reset();
		net.fit(train_iterator); // exception 
	}

	ModelSerializer.writeModel(net, new java.io.File( "enem-net"), ready_for_more);
}
```

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
`0.9.1`

* platform information (OS, etc)
Ubuntu 16.04

* CUDA version, if used
Not used

* NVIDIA driver version, if in use
Not used

#### Contributing

I'm ok helping!

### Just one more thing

@raver119  suggested that the problem might be empty lines from csv files, but I'm confident that it's not.

Quoting the conversation:
> @MrDallOca: @raver119 I'm very sure it isnt blank lines
@raver119 : hm.
@MrDallOca: `find . -name "part*" | xargs -L1 grep -cvP '\S'`
@raver119 : i can't imagine any other reason for that exception
@MrDallOca:
 should return the count for each file with blank lines
I created an test file with empty lines and it worked
```find . -name "part*" | xargs -L1 grep -l -IUr "^M"```
return the name of the file which contains ^M
none of the files were returned except the test file
aaaaaand
I'm producing the files from spark in which I filter every line that doesnt have the exact amount of columns and values
```clojure
 (-> processed-data
                      (.map (WritablesToStringFunction. ","))
                      (.filter (reify org.apache.spark.api.java.function.Function
                                 (call [this x] 
                                   (let [v (clojure.string/split x #",")]
                                     (= labels-n (count v)))))))
```

I'm more than happy providing more details about the data I'm using if needed!

**Comment by MrDallOca** [comment]
The issue still stands for `0.9.2-SNAPSHOT` as well

**Comment by AlexDBlack** [comment]
By far the most likely cause for this is bad data - either blank lines, as mentioned, or data with empty values - such as "1,,3,,,5" etc
Everything you are using is thoroughly tested, so this is unlikely to be a bug.
If you can't work it out, we'll need either (a) the data you are using, or at least (b) a screenshot of an IDE with a breakpoint at the point of that exception (showing relevant fields for CSVRecordReader, etc)

**Comment by MrDallOca** [comment]
> By far the most likely cause for this is bad data - either blank lines, as mentioned, or data with empty values - such as "1,,3,,,5" etc

Yeah, right on target! Empty values ("1,,3,,,5").

Turns out the filtering function I was using was flawed.

Here's the updated and working version (if anyone is interested):
```clojure
(-> processed-data
    (.map (WritablesToStringFunction. ","))
    (.filter (reify org.apache.spark.api.java.function.Function
               (call [this x] 
                 (let [v (first (clojure.data.csv/read-csv x))]
                   (every? #(-> % empty? not) v))))))
```

Oh, maybe the exception could be more informative?

**Comment by AlexDBlack** [comment]
@MrDallOca yes, we can/should improve those exceptions... I've opened an issue for that here:
https://github.com/deeplearning4j/deeplearning4j/issues/4484
