### ISSUE TITLE
optimizing memory problem - if WorkspaceMode is not NONE

### ISSUE THREAD

**Issue by clavvis** [deeplearning4j/deeplearning4j#4476]
#### Issue Description

I create some optimizer for optimizing MultiLayerNetworks (MLN) parameters. It should optimize hundred and more MLN's.
I took code from Arbiter and modify it. Arbiter use randomness for input parameters and I don't like it.

If MLN had set inferenceWorkSpaceMode SEPARATE (and trainingWSM was NONE or SEPARATE) optimize use more and more memory and later was OutOfMemory exception.
If both WorkSpaceMode are NONE optimizer works good. Used memory size is almost stable and enough far from limit.

Problem is if I run one or two tasks too.

Here are main classes:
[https://gist.github.com/clavvis/727538cd6b0189fdebcce4d558bd0a2c](url)
[https://gist.github.com/clavvis/a43954dcd18bf8aafc93c83ccef13a89](url)
[https://gist.github.com/clavvis/af5eb5a59fd6b9fa8adbf8540714f625](url)

Meta configuration:
[https://gist.github.com/clavvis/b25f5eb01f09fcde679ace8603eb69d7](url)
#### Version Information

I use dl4j version 0.9.1, Windows 10, only CPU.

**Comment by clavvis** [comment]
Because of pretraning separation I use this class:

`class CustomI1MultiLayerNetwork extends MultiLayerNetwork {
	// I = Inhereted
	//
	private static final long serialVersionUID = 1L;
	//
	private Collection<TrainingListener> trainingListeners = new ArrayList<>();
	//
	private static final Logger log = LoggerFactory.getLogger(CustomI1MultiLayerNetwork.class);
	//
	
	
	public CustomI1MultiLayerNetwork(MultiLayerConfiguration conf) {
		super(conf);
	}
	//
	public CustomI1MultiLayerNetwork(MultiLayerConfiguration conf, INDArray params) {
		super(conf, params);
	}
	//
	public CustomI1MultiLayerNetwork(String conf, INDArray params) {
		super(conf, params);
	}
	
	
	@Override
	public void fit(DataSetIterator iterator) {
		// we're wrapping all iterators into AsyncDataSetIterator to provide background prefetch - where appropriate
		DataSetIterator iter;
		boolean destructable = false;
		if (iterator.asyncSupported()) {
			iter = new AsyncDataSetIterator(iterator, Math.min(Nd4j.getAffinityManager().getNumberOfDevices() * 2, 2),
							layerWiseConfigurations.getTrainingWorkspaceMode() != WorkspaceMode.NONE);
			destructable = true;
		} else {
			iter = iterator;
		}

		for (TrainingListener tl : trainingListeners) {
			tl.onEpochStart(this);
		}

		MemoryWorkspace workspace =
						layerWiseConfigurations.getTrainingWorkspaceMode() == WorkspaceMode.NONE ? new DummyWorkspace()
										: Nd4j.getWorkspaceManager().getWorkspaceForCurrentThread(
														workspaceConfigurationExternal, workspaceExternal);
		MemoryWorkspace cache =
						layerWiseConfigurations.getTrainingWorkspaceMode() == WorkspaceMode.NONE ? new DummyWorkspace()
										: Nd4j.getWorkspaceManager().getWorkspaceForCurrentThread(
														ComputationGraph.workspaceConfigurationCache,
														ComputationGraph.workspaceCache);

		if (layerWiseConfigurations.isBackprop()) {
			update(TaskUtils.buildTask(iter));
			if (!iter.hasNext() && iter.resetSupported()) {
				iter.reset();
			}
			long time1 = System.currentTimeMillis();
			while (iter.hasNext()) {

				DataSet next = iter.next();
				long time2 = System.currentTimeMillis();

				lastEtlTime.set((time2 - time1));

				if (next.getFeatureMatrix() == null || next.getLabels() == null)
					break;

			 //	TODO: basically we want to wrap internals of this loop into workspace

				boolean hasMaskArrays = next.hasMaskArrays();

				if (layerWiseConfigurations.getBackpropType() == BackpropType.TruncatedBPTT) {
					doTruncatedBPTT(next.getFeatureMatrix(), next.getLabels(), next.getFeaturesMaskArray(),
									next.getLabelsMaskArray());
				} else {
					if (hasMaskArrays)
						setLayerMaskArrays(next.getFeaturesMaskArray(), next.getLabelsMaskArray());

					setInput(next.getFeatureMatrix());
					setLabels(next.getLabels());

					if (solver == null) {
						try (MemoryWorkspace wsO = Nd4j.getMemoryManager().scopeOutOfWorkspaces()) {
							solver = new Solver.Builder().configure(conf()).listeners(getListeners()).model(this)
											.build();
						}
					}

					try (MemoryWorkspace wsCache = cache.notifyScopeEntered()) {
						try (MemoryWorkspace ws = workspace.notifyScopeEntered()) {
							solver.optimize();
						}
					}
				}

				if (hasMaskArrays)
					clearLayerMaskArrays();

				time1 = System.currentTimeMillis();
			}
		} else if (layerWiseConfigurations.isPretrain()) {
			log.warn("Warning: finetune is not applied.");
		}

		if (trainingListeners.size() > 0) {
			for (TrainingListener tl : trainingListeners) {
				tl.onEpochEnd(this);
			}
		}

		clearLayersStates();

		if (destructable)
			((AsyncDataSetIterator) iter).shutdown();

 //		incrementEpochCount();
		
		
		
	}

	
	
	public void pretrain(DataSetIterator iter) {

		if (flattenedGradients == null) {
			initGradientsView();
		}
		if (!layerWiseConfigurations.isPretrain())
			return;

		for (TrainingListener tl : trainingListeners) {
			tl.onEpochStart(this);
		}

		for (int i = 0; i < getnLayers(); i++) {
			pretrainLayer(i, iter);
		}
	}
	
	private void update(Task task) {
		if (!initDone) {
			initDone = true;
			Heartbeat heartbeat = Heartbeat.getInstance();
			task = ModelSerializer.taskByModel(this);
			Environment env = EnvironmentUtils.buildEnvironment();
			heartbeat.reportEvent(Event.STANDALONE, env, task);
		}
	}

	
	
	
}

`

**Comment by AlexDBlack** [comment]
Workspaces were overhauled (and memory use reduced) here: https://github.com/deeplearning4j/deeplearning4j/pull/4900
