### ISSUE TITLE
Reading fasttext .vec file gives error

### ISSUE THREAD

**Issue by mustafasari** [deeplearning4j/deeplearning4j#4477]
I want to read pretrained vec files and work with them, i found some examples with python but couldn't do it with dl4j. 

My Code Like this:
            File gModel = new File("./tr/tr.vec");
            WordVectors vec = WordVectorSerializer.loadStaticModel(gModel);
            InputStreamReader r = new InputStreamReader(System.in);
            BufferedReader br = new BufferedReader(r);
            System.out.print("Word: ");
            String word = "kelime";
            Collection<String> lst = vec.wordsNearest(word, 20);
            System.out.println(word + " -> " + lst);

Stack Trace:
java.lang.UnsupportedOperationException: Method isn't implemented. Please use usual Word2Vec implementation
	at org.deeplearning4j.models.word2vec.StaticWord2Vec.wordsNearest(StaticWord2Vec.java:255)
	at word2Vec.TrainingWithPreparedVec.readFromFile(TrainingWithPreparedVec.java:30)
	at word2Vec.Word2VecRawTextExample.main(Word2VecRawTextExample.java:43)

  Vec file list is:
https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md

**Comment by raver119** [comment]
Show example of your vec file please.

**Comment by mustafasari** [comment]
https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md
I'm trying the TR language:
https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.tr.zip

**Comment by raver119** [comment]
I'm sorry, but could you please put something _smaller_ than that?

**Comment by mustafasari** [comment]
But this is the fasttext file and, i didnt created them. If you know any .vec file smaller than this, appreciate for any example.

**Comment by agibsonccc** [comment]
@mustafasari train a small fast text vector we can look at first?

**Comment by balki7** [comment]
Same issue present in 1.0.0-beta

**Comment by alexanderst** [comment]
Fix was merged to master.
