### ISSUE TITLE
DataSetIterator numPossibleLabels

### ISSUE THREAD

**Issue by Olgidos** [deeplearning4j/deeplearning4j#4478]
#### Issue Description
Hellp
 i want to use deepLearing4J for a regression problem.
For the output, i've done it like here: https://deeplearning4j.org/logistic-regression.html
But i cant find anything for reading the data from an csv data.
I use:
`rrTest.initialize(new FileSplit(new File(data)));
        DataSetIterator trainIterTest = new RecordReaderDataSetIterator(rrTest, batchSize, 0,numPossibleLabels);`
but i am not able to set numPossibleLabels becouse regression got infinite possible Labels in an specific range. 
Is there an other way to import csv data?
greeting Hans

**Comment by saudet** [comment]
There are other constructors for regression, for example:
https://deeplearning4j.org/doc/org/deeplearning4j/datasets/datavec/RecordReaderDataSetIterator.html#RecordReaderDataSetIterator-org.datavec.api.records.reader.RecordReader-int-int-int-boolean-

**Comment by Olgidos** [comment]
thank you very much on this one.. can you give me an advise how to use float numbers for values and value labels?

**Comment by Olgidos** [comment]
ok got it =D
