### ISSUE TITLE
Android - freezes at fit method

### ISSUE THREAD

**Issue by FragileHeart007** [deeplearning4j/deeplearning4j#4479]
Hi,

I got the program freezing for long time when trying to run the example on https://deeplearning4j.org/android
The freezing happen on "fit" method.

This is the log:

`W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
E/HAL: PATH3 /odm/lib/hw/gralloc.qcom.so
E/HAL: PATH2 /vendor/lib/hw/gralloc.qcom.so
E/HAL: PATH1 /system/lib/hw/gralloc.qcom.so
E/HAL: PATH3 /odm/lib/hw/gralloc.msm8953.so
E/HAL: PATH2 /vendor/lib/hw/gralloc.msm8953.so
E/HAL: PATH1 /system/lib/hw/gralloc.msm8953.so
W/System.err: [AsyncTask #1] WARN org.reflections.Reflections - given scan urls are empty. set urls in the configuration
I/art: Do partial code cache collection, code=31KB, data=29KB
I/art: After code cache collection, code=29KB, data=29KB
I/art: Increasing code cache capacity to 128KB
W/System.err: [AsyncTask #1] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
W/linker: /data/app/com.example.user1.myapplication-2/lib/arm/libnd4jcpu.so: unused DT entry: type 0xf arg 0xa683
W/linker: /data/app/com.example.user1.myapplication-2/lib/arm/libjnind4jcpu.so: unused DT entry: type 0xf arg 0x15125
W/System.err: [AsyncTask #1] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 4
W/System.err: [AsyncTask #1] WARN org.reflections.Reflections - given scan urls are empty. set urls in the configuration
I/art: Do partial code cache collection, code=62KB, data=56KB
I/art: After code cache collection, code=59KB, data=55KB
I/art: Increasing code cache capacity to 256KB
W/linker: /data/app/com.example.user1.myapplication-2/lib/arm/libjniopenblas.so: unused DT entry: type 0xf arg 0xea58
W/System.err: [AsyncTask #1] INFO org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 4
W/System.err: [AsyncTask #1] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CPU]; OS: [Linux]
W/System.err: [AsyncTask #1] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [8]; Memory: [0.2GB];
W/System.err: [AsyncTask #1] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
W/System.err: [AsyncTask #1] WARN org.reflections.Reflections - given scan urls are empty. set urls in the configuration`

My gradle:

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.example.user1.myapplication"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/INDEX.LIST'
        exclude 'org/bytedeco/javacpp/windows-x86/msvcp120.dll'
        exclude 'org/bytedeco/javacpp/windows-x86_64/msvcp120.dll'
        exclude 'org/bytedeco/javacpp/windows-x86/msvcr120.dll'
        exclude 'org/bytedeco/javacpp/windows-x86_64/msvcr120.dll'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    compile ("org.deeplearning4j:deeplearning4j-core:0.8.0"){exclude group: 'junit', module: 'junit'}
    compile ("org.nd4j:nd4j-native:0.8.0"){exclude group: 'junit', module: 'junit'}
    compile ("org.nd4j:nd4j-native:0.8.0:android-x86"){exclude group: 'junit', module: 'junit'}
    compile ("org.nd4j:nd4j-native:0.8.0:android-arm"){exclude group: 'junit', module: 'junit'}
    compile 'org.bytedeco.javacpp-presets:openblas:0.2.19-1.3:android-x86'
    compile 'org.bytedeco.javacpp-presets:openblas:0.2.19-1.3:android-arm'

    compile "org.slf4j:slf4j-simple:1.7.25"
    compile "org.slf4j:slf4j-api:1.7.25"
    compile 'com.google.code.findbugs:annotations:3.0.1', {
        exclude module: 'jsr305'
        exclude module: 'jcip-annotations'
    }
    annotationProcessor 'org.projectlombok:lombok:1.16.10'

}
`
I'm using Android Studio 3.0.1 on Windows. jdk1.8.0_151 and deeplearning4j 0.8.0. I was using JDK 9 but got the same result so downgraded to 8. I tried also Android Studio 2.3.3 but nothing changed.

**Comment by raver119** [comment]
1) Freezes? Or takes eternity to train on phone? :)
2) Please consider using latest dl4j, that is 0.9.1
3) Please get threads dump using android dev tools.

Beyond that - serious training on phone isn't really good idea usually.

**Comment by FragileHeart007** [comment]
Thanks. I think there was no error. The iteration number was so high and I reduced it. It took 10 min for 60000 iterations to train the very simple data here https://deeplearning4j.org/android

**Comment by agibsonccc** [comment]
@FragileHeart007 we aren't going to support you trying to train on the phone. No framework tries to do this. Just because you "can" doesn't mean you "should". That's like complaining that a computer from 1980 is slower than a super computer with 56 gpus. A phone with a small amount of resources is naturally going to be slower. I'm closing this.
