### ISSUE TITLE
Best Way adding Java Data Model 

### ISSUE THREAD

**Issue by Olgidos** [deeplearning4j/deeplearning4j#4483]
Hello =)
I am not able to add new live Data from my Java Programm to my deepLearningModel.
I got an Array of Ints and the Label, how can i feed them.. i tried with to create a new INDArray but its abstract, tried to make a  new DataSet but DataSet Constructor is with INDArray.
Whats the best way to feed live Data into 'model.outpur(data, false)'
Greetings Carl

**Comment by AlexDBlack** [comment]
Closing this - yes, you want an INDArray.
Use the Nd4j.create() or similar methods.
https://nd4j.org/userguide
https://github.com/deeplearning4j/dl4j-examples/tree/master/nd4j-examples/src/main/java/org/nd4j/examples
