### ISSUE TITLE
Vocab Cache doesn't save total number of documents

### ISSUE THREAD

**Issue by thorbengold** [deeplearning4j/deeplearning4j#4486]
#### Issue Description

When loading a saved VocabCache and doing tfidf transformation it returns 0's because the vocab Cache doesn't save the total Number of documents which is needed for calculating idf. So in my case vocabCache.totalNumberOfDocs() = 0 instead of the actual number of documents. 

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.9.1
* platform information Windows 10

#### Coding

Creating, Saving and Loading the Vocab like this:

```
//Creation 
        TfidfVectorizer tfidfvec = new TfidfVectorizer.Builder()
                .setMinWordFrequency(minWordFreq)
                .setStopWords(stopWordsColl)
                .setTokenizerFactory(tokenizerFactory)
                .setIterator(iterator)
                .allowParallelTokenization(false)
                .build();

        tfidfvec.fit();
        
//Saving
        WordVectorSerializer.writeVocabCache(tfidfvec.getVocabCache(), new File(FileInMyDirectory));

//Restoration
        vocCacheLoad = WordVectorSerializer.readVocabCache(FileInMyDirectory);
        TfidfVectorizer tfidfvec1 = new TfidfVectorizer.Builder()
                .setVocab(vocCacheLoad)
                .setTokenizerFactory(tokenizerFactory)
                .build();
```
@raver119

**Comment by raver119** [comment]
Implemented/fixed in my branch. Will be merged soon.

Thanks for highlighting this issue.
