### ISSUE TITLE
Add UI server module to DL4J for easy deployment + script

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4503]
Basically this, but as a DL4J module: https://github.com/deeplearning4j/dl4j-ui-server

Then also add a simple script (.sh and .cmd for windows) that:
(a) checks local maven repo for the JAR, and uses that if available
(b) if not, pulls the JAR from maven central

The script could have args for version, port, etc too.

Goal: spin up a UI server (for remote, etc) in 1 line, on any machine.

**Comment by AlexDBlack** [comment]
No script yet, but the module was added here: https://github.com/deeplearning4j/deeplearning4j/pull/4508
Will keep this open until the script is done/available.

**Comment by raver119** [comment]
I guess this issue can be closed now.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j-docs/issues/50
