### ISSUE TITLE
make it possible to restore a previously stored WeightLookupTable

### ISSUE THREAD

**Issue by tteofili** [deeplearning4j/deeplearning4j#4506]
#### Issue Description

Please describe our issue, along with:
- given one could persist a *WeightLookupTable* to File, it should be possible to also restore it
- *WordVectorsSerializer* doesn't allow to restore a previously serialized *WeightLookupTable*

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version : 0.9.1
* platform information (OS, etc): Mac OSX 10.12.6, Java 8

#### Contributing

The restore method would look something like :
`public static <T extends SequenceElement> WeightLookupTable<T> readLookupTable(InputStream stream) throws IOException {
        WeightLookupTable<T> weightLookupTable = new InMemoryLookupTable<>();
        boolean headerRead = false;
        for (String line : IOUtils.readLines(stream)) {
            String[] tokens = line.split(" ");
            if (!headerRead) {
                // reading header as "NUM_WORDS VECTOR_SIZE NUM_DOCS"
                int numWords = Integer.parseInt(tokens[0]);
                int layerSize = Integer.parseInt(tokens[1]);
                int totalNumberOfDocs = Integer.parseInt(tokens[2]);
                log.debug("Reading header - words: {}, layerSize: {}, totalNumberOfDocs: {}", numWords, layerSize, totalNumberOfDocs);
                headerRead = true;
            } else {
                String label = decodeB64(tokens[0]);
                INDArray vector = Nd4j.create(tokens.length - 1);
                for (int i = 1; i < tokens.length; i++) {
                    vector.putScalar(i - 1, Double.parseDouble(tokens[i]));
                }
                weightLookupTable.putVector(label, vector);
            }
        }
        stream.close();
        return weightLookupTable;
    }`

**Comment by alexanderst** [comment]
Fixed and merged.
