### ISSUE TITLE
Utility class to convert TinyYOLO INDArray output to a more "easy to read" output 

### ISSUE THREAD

**Issue by jesuino** [deeplearning4j/deeplearning4j#4515]
#### Issue Description

There's a Zoo model for YOLO, which is great, however, the output (125, 14, 14) is known as being cumbersome (ref [1] ) and we still have to adjust the values according to the prior boxes (ref to [2]). It is error prone and users may have to develop this function with bugs - leading them to believe that there's problem with the neural net model.

This is a feature request to add some utility method that will convert the TinyYOLO zoo model to a more understandable output. An example can be found on this Python function sent by hristo-vrigazov on gitter [3]. Other example: [4] (I don't know if [3] or [4] applies to the DL4J output) 

[1] https://medium.com/diaryofawannapreneur/yolo-you-only-look-once-for-object-detection-explained-6f80ea7aaa1e
[2] http://christopher5106.github.io/object/detectors/2017/08/10/bounding-box-object-detectors-understanding-yolo.html
[3] https://github.com/hristo-vrigazov/CarND-Vehicle-Detection/blob/master/yolo_object_detector.py#L56
[4] https://github.com/allanzelener/YAD2K/blob/master/yad2k/models/keras_yolo.py#L126

#### Version Information

DL4J 0.9.2-SNAPSHOT.

**Comment by jesuino** [comment]
Samuel Audet pointed me to the following methods in YOLO output layer:

1) Get the output layer from the model

https://github.com/deeplearning4j/dl4j-examples/blob/sa_snapshot/dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/objectdetection/HouseNumberDetection.java#L181-L182

2) Use it to get the detected objects from the model output:

https://github.com/deeplearning4j/dl4j-examples/blob/sa_snapshot/dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/objectdetection/HouseNumberDetection.java#L190


This is a small example which I am using for test:

~~~
import java.io.IOException;
import java.net.URL;
import java.util.List;
import org.datavec.image.loader.NativeImageLoader;
import org.deeplearning4j.nn.graph.ComputationGraph;
import org.deeplearning4j.nn.layers.objdetect.DetectedObject;
import org.deeplearning4j.nn.layers.objdetect.Yolo2OutputLayer;
import org.deeplearning4j.zoo.PretrainedType;
import org.deeplearning4j.zoo.model.TinyYOLO;
import org.nd4j.linalg.api.ndarray.INDArray;

public class YOLOApp {

	private static final String URL = "<SOME_IMG_URL";
	private static final int IMG_W = 446;
	private static final int IMG_H = 446;

	private static final String[] CLASSES = { "aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat",
			"chair", "cow", "diningtable", "dog", "horse", "motorbike", "person", "pottedplant", "sheep", "sofa",
			"train", "tvmonitor" };

	public static void main(String[] args) throws IOException {
		TinyYOLO tinyYOLOZoo = new TinyYOLO();
		ComputationGraph yoloModel = (ComputationGraph) tinyYOLOZoo.initPretrained(PretrainedType.IMAGENET);
		INDArray loadedImage = loadImage();
		Yolo2OutputLayer outputLayer = (Yolo2OutputLayer) yoloModel.getOutputLayer(0);
		INDArray output = yoloModel.outputSingle(loadedImage);
		List<DetectedObject> predictedObjects = outputLayer.getPredictedObjects(output, 0.3f);
		for (DetectedObject detectedObject : predictedObjects) {
			String cl = CLASSES[detectedObject.getPredictedClass()];
			System.out.println(cl);
		}
	}

	private static INDArray loadImage() throws IOException {
		URL url = new URL(URL);
		NativeImageLoader imageLoader = new NativeImageLoader(IMG_W, IMG_H, 3);
		return imageLoader.asImageMatrix(url.openStream()).getImage();
	}

}
~~~

**Comment by saudet** [comment]
This is going to require some documentation as some point...

**Comment by saudet** [comment]
FYI, this is now available via the YoloUtils class, so should be clear enough: pull #4531
