### ISSUE TITLE
when I use modelimport to import a keras model,  It failed, How to solve?

### ISSUE THREAD

**Issue by liuyichaosoftware** [deeplearning4j/deeplearning4j#4518]
#### Issue Description

When I run

        KerasModelImport.importKerasModelAndWeights(js, path);
It failed, and  throw it

Exception in thread "main" java.lang.NoClassDefFoundError: org/nd4j/linalg/api/ops/RandomOp
	at org.deeplearning4j.nn.conf.layers.Layer$Builder.dropOut(Layer.java:289)
	at org.deeplearning4j.nn.modelimport.keras.layers.embeddings.KerasEmbedding.<init>(KerasEmbedding.java:85)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:224)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:190)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:158)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:92)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:115)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:197)
	at test.main(test.java:14)
Caused by: java.lang.ClassNotFoundException: org.nd4j.linalg.api.ops.RandomOp
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more

#### Version Information

master

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by maxpumperla** [comment]
@liuyichaosoftware are you sure you have matching versions of dl4j and nd4j? It seems that `org/nd4j/linalg/api/ops/RandomOp` cannot be found.

Please check this first. If there's really a problem with import, please share your json / h5 / whatever. OK? Thanks

**Comment by liuyichaosoftware** [comment]
when I not use enforceTrainingConfig=false, the problem ocored.

my json as follow.


{"class_name": "Model", "keras_version": "2.0.8", "config": {"layers": [{"class_name": "InputLayer", "config": {"dtype": "float32", "batch_input_shape": [null, 60], "name": "input_1", "sparse": false}, "inbound_nodes": [], "name": "input_1"}, {"class_name": "InputLayer", "config": {"dtype": "float32", "batch_input_shape": [null, 1], "name": "input_2", "sparse": false}, "inbound_nodes": [], "name": "input_2"}, {"class_name": "Embedding", "config": {"embeddings_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "name": "embedding_1", "dtype": "float32", "output_dim": 128, "trainable": true, "embeddings_regularizer": {"class_name": "L1L2", "config": {"l2": 9.999999747378752e-06, "l1": 0.0}}, "input_dim": 10001, "mask_zero": true, "embeddings_constraint": null, "batch_input_shape": [null, null], "activity_regularizer": null, "input_length": null}, "inbound_nodes": [[["input_1", 0, 0, {}]]], "name": "embedding_1"}, {"class_name": "Embedding", "config": {"embeddings_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "name": "embedding_2", "dtype": "float32", "output_dim": 32, "trainable": true, "embeddings_regularizer": {"class_name": "L1L2", "config": {"l2": 9.999999747378752e-06, "l1": 0.0}}, "input_dim": 24, "mask_zero": false, "embeddings_constraint": null, "batch_input_shape": [null, null], "activity_regularizer": null, "input_length": null}, "inbound_nodes": [[["input_2", 0, 0, {}]]], "name": "embedding_2"}, {"class_name": "LSTM", "config": {"recurrent_activation": "hard_sigmoid", "trainable": true, "recurrent_initializer": {"class_name": "Orthogonal", "config": {"seed": null, "gain": 1.0}}, "use_bias": true, "bias_regularizer": null, "return_state": false, "unroll": false, "activation": "tanh", "bias_initializer": {"class_name": "Zeros", "config": {}}, "units": 128, "unit_forget_bias": true, "activity_regularizer": null, "recurrent_dropout": 0.0, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "kernel_constraint": null, "dropout": 0.0, "stateful": false, "recurrent_regularizer": null, "name": "lstm_1", "bias_constraint": null, "go_backwards": false, "implementation": 0, "kernel_regularizer": null, "return_sequences": false, "recurrent_constraint": null}, "inbound_nodes": [[["embedding_1", 0, 0, {}]]], "name": "lstm_1"}, {"class_name": "Flatten", "config": {"trainable": true, "name": "flatten_1"}, "inbound_nodes": [[["embedding_2", 0, 0, {}]]], "name": "flatten_1"}, {"class_name": "Dense", "config": {"kernel_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "name": "dense_1", "kernel_constraint": null, "bias_regularizer": null, "bias_constraint": null, "activation": "relu", "trainable": true, "kernel_regularizer": {"class_name": "L1L2", "config": {"l2": 9.999999747378752e-06, "l1": 0.0}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "units": 64, "use_bias": true, "activity_regularizer": null}, "inbound_nodes": [[["lstm_1", 0, 0, {}]]], "name": "dense_1"}, {"class_name": "Dense", "config": {"kernel_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "name": "dense_2", "kernel_constraint": null, "bias_regularizer": null, "bias_constraint": null, "activation": "relu", "trainable": true, "kernel_regularizer": {"class_name": "L1L2", "config": {"l2": 9.999999747378752e-06, "l1": 0.0}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "units": 8, "use_bias": true, "activity_regularizer": null}, "inbound_nodes": [[["flatten_1", 0, 0, {}]]], "name": "dense_2"}, {"class_name": "Dropout", "config": {"rate": 0.1, "trainable": true, "name": "dropout_1"}, "inbound_nodes": [[["dense_1", 0, 0, {}]]], "name": "dropout_1"}, {"class_name": "Dropout", "config": {"rate": 0.1, "trainable": true, "name": "dropout_2"}, "inbound_nodes": [[["dense_2", 0, 0, {}]]], "name": "dropout_2"}, {"class_name": "Concatenate", "config": {"trainable": true, "name": "concatenate_1", "axis": -1}, "inbound_nodes": [[["dropout_1", 0, 0, {}], ["dropout_2", 0, 0, {}]]], "name": "concatenate_1"}, {"class_name": "Dense", "config": {"kernel_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "name": "dense_3", "kernel_constraint": null, "bias_regularizer": null, "bias_constraint": null, "activation": "softmax", "trainable": true, "kernel_regularizer": {"class_name": "L1L2", "config": {"l2": 9.999999747378752e-06, "l1": 0.0}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "units": 10001, "use_bias": true, "activity_regularizer": null}, "inbound_nodes": [[["concatenate_1", 0, 0, {}]]], "name": "dense_3"}], "input_layers": [["input_1", 0, 0], ["input_2", 0, 0]], "output_layers": [["dense_3", 0, 0]], "name": "model_1"}, "backend": "tensorflow"}

**Comment by liuyichaosoftware** [comment]
Ok, when 
<dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-api</artifactId>
            <version>0.9.1</version>
        </dependency>
,
not to use 0.9.2-snapshat, It's OK.

**Comment by liuyichaosoftware** [comment]
but when enforceTrainingConfig=false is not used, I got exception,

> Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Specifying different initialization for recurrent weights not supported.. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.layers.recurrent.KerasLstm.<init>(KerasLstm.java:134)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:195)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:190)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:158)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:92)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:115)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:197)

>

**Comment by maxpumperla** [comment]
@liuyichaosoftware can you please provide the _full_ stack trace as gist? From the snippet and the json I can guess that your `kernel_initializer` and `recurrent_initializer` differ. that is not allowed.

**Comment by liuyichaosoftware** [comment]
OK, thank you!
