### ISSUE TITLE
Labels have the same vectors

### ISSUE THREAD

**Issue by seemas2309** [deeplearning4j/deeplearning4j#452]
My file has the following format
label delimiter text.
There is one sentence per line. 

I used the following code to create my model :

 File f = new File("inputDoc2Vec4jtry.txt");
java.io.InputStream is = new FileInputStream(f);
String delim = ";";
LabelAwareSentenceIterator iter = new LabelAwareListSentenceIterator(is,delim,0, 1);
TokenizerFactory tokenizer = new DefaultTokenizerFactory();
ParagraphVectors vec = new ParagraphVectors.Builder()
              .minWordFrequency(1)
              .layerSize(layerSize)
              .iterations(iterations)
              .iterate(iter)
              .tokenizerFactory(tokenizer)
              .build();
vec.fit();

When I try to print the vector representations of the labels, they are all the same i.e. the vector representation of UNKNOWN 

 iter.reset();
 int a =0;

      while(iter.hasNext() && a<10){
        a++;
        iter.nextSentence();
        System.out.print("Label "+iter.currentLabel()+" ");
        for(int i=0; i<layerSize;i++){
         
          System.out.print(vec.getWordVector(iter.currentLabel())[i]+" ");
        }
        System.out.print("\n");  
      }

Thanks

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/453

**Comment by seemas2309** [comment]
Still facing the issue. Code is same as above. vec.getWordVector(iter.currentLabel()) does not return vector representation of label.

SAMPLE DATA:

SENT37;HttpOutputStream close Thread run
SENT38;EMDClient getStreamResponseForRequest Thread run
SENT39;PlainSocketImpl socketConnect HTTPConnection$EstablishConnection run
SENT42;ProcessBuilder start Thread run

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/464
