### ISSUE TITLE
File an issue with feedback when something may missing during video stream detection

### ISSUE THREAD

**Issue by klevis** [deeplearning4j/deeplearning4j#4548]
#### Issue Description

It will be nice to provide utilities that will enable users to file an issue on a missing/wrongly detection in a video stream or maybe even in more general predictions. 

#### Version Information

* Deeplearning4j version
0.9.2-SNAPSHOT

#### Contributing

I would like to contribute the feature , so any guidance is much appreciated.

**Comment by AlexDBlack** [comment]
I don't understand what this feature request is. Is this DL4J related?
What do you mean "video stream"? And "file an issue"?
