### ISSUE TITLE
"No CUDA devices were found in system" when trying to run examples from IntelliJ

### ISSUE THREAD

**Issue by anderseriksson** [deeplearning4j/deeplearning4j#4554]
#### Issue Description

Error message "No CUDA devices were found in system" when trying to run dl4j examples from IntelliJ with native platform driver. This is on a machine without actual CUDA GPU. I guess you will not notice this if you run on a machine which actually have the drivers and GPU installed.  

#### Version Information

* Deeplearning4j version (latest, git commit 49a85281a7cd1d75bef1ee9d2514b2dd706ed2e7 ) 
* platform information : MacOS Sierra 10.12.6
* CUDA version, if used - N/A
* NVIDIA driver version, if in use N/A

As reported in chat I learned the following: When running the dl4j-examples in line with your quickstart guidelines and then run the example out of IntelliJ on a machine without CUDA GPUs you can still get an error message about "No CUDA devices were found in system". The example I run was for example org.deeplearning4j.examples.feedforward.mnist.MLPMnistSingleLayerExample. 
 
This happens even if the root pom.xml defines the (non CUDA)native-platform jar. Specific snippet in root pom.xml

```
    <properties>
        <!-- Change the nd4j.backend property to nd4j-cuda-7.5-platform or nd4j-cuda-8.0-platform to use CUDA GPUs -->
        <nd4j.backend>nd4j-native-platform</nd4j.backend>
        <!--<nd4j.backend>nd4j-cuda-8.0-platform</nd4j.backend>-->
```

The reason is that IntelliJ somehow throws in all the dependencies in the classpath and then the CUDA-drivers get loaded even if the Maven classpath specifies it should NOT. I guess this can easily happen as users are creating the IntelliJ project themselves and it can become quite messy with classpath in multi module projects. 

A quick way workaround this is to run the examples using maven exec:java instead which of course respects the correct classpath as defined by maven. 

#### Contributing

This is not a major issue, but it could be a useful heads up to add to your quickstart guideline. Potentially you could provide ready made IntelliJ projects.

**Comment by RobAltena** [comment]
Moved to dl4-examples.
