### ISSUE TITLE
Masking exception

### ISSUE THREAD

**Issue by ekravi** [deeplearning4j/deeplearning4j#4561]
My goal is to predict the label of a set of sentences.
Therefore, the input for my problem is a set of sentences, masked and inserted to an LSTM (w/ shared parameters using StackVertex and UnstackVertex), the output is a label (not needed to be masked).

Here is a gist for the network - https://gist.github.com/ekravi/df1b9b4cfe03c5e8098cc0b81493eec9
I get the following exception: "Per output masking for MCXENT + softmax: not supported"

Following @agibsonccc suggestion tried to add a ReshapeVertex but got the exception: "Received mask array with shape [2, 25]; expected vector"

**Comment by AlexDBlack** [comment]
@ekravi can you provide the data pipeline - or (perhaps if it's easier) just the shapes of the features, labels, feature masks *and* label masks for the DataSet or MultiDataSet you are using for training.
I'll need that to reproduce this.

**Comment by AlexDBlack** [comment]
Your architectecture and array sizes don't look correct here.

> My goal is to predict the label of a set of sentences.

OK, so sequence classification. You have 3 options here:
1. Use time series labels (shape [minibatch, numClasses, maxLength]), and mask all but the last step with a label mask of shape [minibatch, maxLength]. LSTM + RnnOutputLayer architecture.
2. Use non time series labels, and:
   (a) LSTM + LastTimeStepVertex (or better: snapshot/master LastTimeStep layer wrapper) + OutputLayer. 2d labels [minibatch, numClasses] and no label masks
   (b) LSTM (optionally bi-directional) + pooling over time (GlobalPooling layer) + OutputLayer. 2d labels [minibatch, numClasses] and no label masks
   
I'd recommend options 2(a) or 2(b) in practice. Both require an input mask. As to which? I'd recommend testing both, but might expect 2(b) to work a bit better.

Avoid the use of ReshapeVertex, and just use .setInputType(InputType.recurrent(x))
