### ISSUE TITLE
Custom loss functions not directly implementing ILossFunction not found by reflections

### ISSUE THREAD

**Issue by yylonly** [deeplearning4j/deeplearning4j#4562]
I use self define loss in last "task" layer shown as following.
>         .addLayer("TASKS", new OutputLayer.Builder().activation(Activation.SIGMOID)
> 		                .lossFunction(new WeightedL2Loss(1))
> 		                .nIn(1000).nOut(157).build(), "HIDDEN")
It can successfully store into "deeppharm.zip" by 

>         File locationToSave = new File("DeepPharm.zip");       //Where to save the network. Note: the file is in .zip format - can be opened externally
>         boolean saveUpdater = true;                                             //Updater: i.e., the state for Momentum, RMSProp, Adagrad etc. Save this if you want to train your network more in the future
>         try {
> 			ModelSerializer.writeModel(net, locationToSave, saveUpdater);
> 		} catch (IOException e) {
> 			// TODO Auto-generated catch block
> 			e.printStackTrace();
> 		}

But it can not be succesfully restore because it is a un-know type of function ModelSerializer.restoreComputationGraph()

> Caused by: org.nd4j.shade.jackson.databind.JsonMappingException: Could not resolve type id 'WeightedL2Loss' into a subtype of [simple type, class org.nd4j.linalg.lossfunctions.ILossFunction]: known type ids = [BinaryXENT, CosineProximity, FMeasure, Hinge, ILossFunction, KLD, L1, L2, MAE, MAPE, MCXENT, MSE, MSLE, NegativeLogLikelihood, Poisson, SquaredHinge]

How could let the restoreComputationGraph() let know the new loss type? Thanks

**Comment by AlexDBlack** [comment]
This *should* occur automatically. The fact that it isn't picking it up suggests one of two things:
(a) the custom loss function simply isn't on the classpath when you are loading the network.
(b) there is an issue with the Reflections library that DL4J uses internally for custom layers etc.

So far the only real issue we've seen with reflections is on Android. What's your OS?

If we can't work out why this is happening, then you can try the following workaround:
https://github.com/deeplearning4j/deeplearning4j/issues/4504#issuecomment-357555845

**Comment by yylonly** [comment]
I use Mac OS 10.13.2 and DL4j 0.9.1, I will follow #4504 to see whether I can find the resolution.

**Comment by yylonly** [comment]
Btw, the new loss class is in the same package of my train and test main class, and I also try to add the class and jar into classpath, it does not help. for your (b), I did not use custom layers, only use custom cost function.

Thanks

**Comment by yylonly** [comment]
I think I found the bugs, the customer loss function required not only extend from pre-defined loss function, but also require implements the ILossFunction. But I checked the L2 loss function already implemented the interface ILossFunction. Why need explicit define the implements here?

> public class WeightedL2Loss extends LossL2 implements org.nd4j.linalg.lossfunctions.ILossFunction 

This will make save and load model correctly. but this will lead the error

> public class WeightedL2Loss extends LossL2

I think this issue can be closed right now.

**Comment by AlexDBlack** [comment]
Ah, thanks. I'll actually keep this issue open, to remind us to fix it and as a workaround for other users.

I'm pretty sure this is another issue with the reflections library (which we are going to remove) - it's very likely not picking up transitive interface implements...

i.e., you have two classes (A and B), where B extends A, where A implements X.... then we scan for classes implementing X (using Reflections library), and it'll only find A and not B - because B does not *directly* implement X.

**Comment by AlexDBlack** [comment]
Reflections library has been removed from DL4J entirely - addressed here: https://github.com/deeplearning4j/deeplearning4j/pull/4956 and https://github.com/deeplearning4j/deeplearning4j/pull/4950

This should no longer be an issue.
