### ISSUE TITLE
[Help]DL4J EmbeddingLayer includes bias but Keras Embedding does not

### ISSUE THREAD

**Issue by x831617** [deeplearning4j/deeplearning4j#4564]
#### Issue Description

I am working on importing the keras model into java by using the DL4J.
Unfortunately, I encounter the problem as below:

- WARN org.deeplearning4j.nn.modelimport.keras.layers.KerasEmbedding - DL4J EmbeddingLayer 
       includes bias but Keras Embedding does not.

How can I fix this problem.

My source code are as follows:

- MultiLayerNetwork network = 
          KerasModelImport.importKerasSequentialModelAndWeights(model_json, model_weight, false);

The code is very simple.

Thank you for any responses.

**Comment by tomthetrainer** [comment]
This issue is similar and it implies that bias is set to 0 in more recent versions of Keras Model Import

https://github.com/deeplearning4j/deeplearning4j/issues/4563


That said it is a warning not an error. 

Was the model able to load? 
Was the output proper? 
What version are you using?

**Comment by x831617** [comment]
Dear tomthetrainer,

When load the model, the warn message shows as I mentioned. Although it is a warn message, the subsequent code can not be executed. Hence, I post this issue.

I trained and tested the model in python and validated the performance properly. The dl4j version I employed is 0.9.1.

Now, I still have no idea how to fix it. So, I am going to transform the keras model into tensorflow model, and load the transformed model into java for solving this issue.

Thank you for quick response.

**Comment by saudet** [comment]
Could you try with 0.9.2-SNAPSHOT?

**Comment by x831617** [comment]
Dear Saudet,

The jar I downloaded is from the following website:
https://mvnrepository.com/artifact/org.deeplearning4j/deeplearning4j-core

There is no 0.9.2, so I used 0.9.1.

Could you please recommend any website that can download 0.9.2?

Thank you

**Comment by saudet** [comment]
Instructions here: https://deeplearning4j.org/snapshots

**Comment by maxpumperla** [comment]
@x831617 this works 100% with snapshots, will be in the next release. closing this, but let me know if you have other problems.
