### ISSUE TITLE
Intermittent test failure: EvalTest.testEvalSplittingCompGraph

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4594]
Most of the time when running this test: it passes.
Occasionally it will fail for the workspace cases - evaluation performance can sometimes slightly differ.

**Comment by raver119** [comment]
Is it reproducible with SCOPE_PANIC enabled?

**Comment by AlexDBlack** [comment]
Scope panic doesn't catch any issues here.

**Comment by raver119** [comment]
What about AsyncShieldDataSetIterator?

**Comment by AlexDBlack** [comment]
It's using ExistingDataSetIterator... so it's not async related.
https://github.com/deeplearning4j/deeplearning4j/blob/46065ee814e5d9f6e6a86178db69d3d58cf4c661/deeplearning4j-core/src/test/java/org/deeplearning4j/eval/EvalTest.java#L1054

(I did try it anyway, AsyncShieldDataSetIterator doesn't help)

**Comment by AlexDBlack** [comment]
Closing this as resolved - likely fixed in one of the previous workspace fix PRs recently.
I've run this test 1000x in a loop on both Windows and Linux, and I'm unable to reproduce a failure.
