### ISSUE TITLE
UIServer: plotVocab and TsneModule routes do not match up

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#4596]
For some reason the route that would accept a POST request has been replaced with a GET based route.

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-ui-parent/deeplearning4j-play/src/main/java/org/deeplearning4j/ui/module/tsne/TsneModule.java#L50
```java
//        Route r5 = new Route("/tsne/post/:sid", HttpMethod.POST, FunctionType.Function, this::postFile);
        Route r5 = new Route("/tsne/post/:sid", HttpMethod.GET, FunctionType.Function, this::postFile);
```

However, the InMemoryLookupTable.plotVocab method still tries to use the POST based version:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/inmemory/InMemoryLookupTable.java#L222

```java
String address = connectionInfo.getFirstPart() + "/tsne/post/" + connectionInfo.getSessionId();
 //            System.out.println("ADDRESS: " + address);
URI uri = new URI(address);

HttpURLConnection connection = (HttpURLConnection) uri.toURL().openConnection();
connection.setRequestMethod("POST");
```

@fenneclabs found the Bug, and it has shown itself with the following exception:
```
15:54:23.369 Trc [main ] BarnesHutTsne <> Error at iteration 99 is -176691.3168704078
RESPONSE CODE: 404
15:54:23.416 Std [main ] InMemoryLookupTable <> Error posting to remote UI at http://localhost:9000/tsne/post/08cd2dcb-f68a-4861-abd6-76ce86d186aa java.io.FileNotFoundException: http://localhost:9000/tsne/post/08cd2dcb-f68a-4861-abd6-76ce86d186aa
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
```

The bug affects both 0.9.1 and current master.

In Order to reproduce the bug, simply add the following to Word2VecRawTextExample after the `vec.fit()` call:
```
  BarnesHutTsne tsne = new BarnesHutTsne.Builder()
            .setMaxIter(1)
            .theta(0.5)
            .normalize(false)
            .learningRate(500)
            .useAdaGrad(false)
            .build();
        UIServer uiServer = UIServer.getInstance();
        StatsStorage statsStorage = new InMemoryStatsStorage();          
        uiServer.attach(statsStorage);

        vec.lookupTable().plotVocab(tsne, 42, new UiConnectionInfo.Builder()
            .setPort(uiServer.getPort())
            .build());
```

**Comment by melanietosik** [comment]
I'm new to DL4J and currently working with a recent clone of the [dl4j-examples](https://github.com/deeplearning4j/dl4j-examples) repo, where I ran into this issue as well. It looks like this should be fixed now, but hasn't been released yet (last release was December 8, 2017). Is there a workaround for this until the latest fixes do get released?

For example, is there a way to run t-SNE, write the results to a file, and then manually load them into the UI server? Or can I update Maven somehow to include the latest changes to the main repo? Sorry for being relatively vague, I'm a little out of my element here.

Any help would be appreciated!

Thanks!

**Comment by AlexDBlack** [comment]
As far as I know - the only workaround is to use our snapshot builds - see this page for details: https://deeplearning4j.org/snapshots

**Comment by melanietosik** [comment]
Great, thank you! Any chance you could you clarify where exactly I need to specify the snapshot version in the `pom.xml` file? I added the `<repositories></repositories>` snippet and tried to bump the `<version>` at the beginning of the file but that didn't seem to work.

**Comment by AlexDBlack** [comment]
It's the versions for all dependencies - DL4J, ND4J, DataVec etc.
Feel free to go here and post your pom.xml (in a gist - gist.github.com) if you can't work it out - https://gitter.im/deeplearning4j/deeplearning4j
