### ISSUE TITLE
Combining classification-regression problem

### ISSUE THREAD

**Issue by moberc** [deeplearning4j/deeplearning4j#4617]
Is there a way to set one model that outputs a probability of an event and a value associated with that event?
I am able to solve this by setting two models: the first one is a classification problem, the second - regression, but ideally I would like to have this in one model.
Any pointers much appreciated!

**Comment by AlexDBlack** [comment]
Yes, this is quite possible - and is discussed (with code snippet) here: https://deeplearning4j.org/compgraph#multitask
