### ISSUE TITLE
Failing TBPTT tests

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4619]
![image](https://user-images.githubusercontent.com/2360237/35852046-eb155a00-0b7d-11e8-9cae-81eb57043e27.png)

Tests both pass if workspaces are disabled.

**Comment by raver119** [comment]
TBPTT is kind of special case. Unlike regular training, there's additional workspace exist between EXTERNAL and LOOP_FF

**Comment by AlexDBlack** [comment]
Solution here is probably just to make TBPTT state not accessible to users - this (so far) appears to just be a scope issue...
