### ISSUE TITLE
"CUDA 8" maven profile is actually CUDA 9

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4639]
This should be renamed to avoid confusion. Perhaps a CUDA 8 profile should also be added, unless we standardize on CUDA 8 only?

https://github.com/deeplearning4j/deeplearning4j/blob/master/pom.xml#L383-L404

**Comment by saudet** [comment]
Or perhaps we should have the change-cuda-versions.sh script change the name of the profile as well?

**Comment by AlexDBlack** [comment]
That's... an interesting idea. A simple (similar) alternative is just changing it to say test-nd4j-cuda, and yeah, letting the change cuda version script do the switching. Single profile might make it simpler for CI if/when we test different CUDA versions, vs. "rename the profile"

**Comment by saudet** [comment]
Not sure it would make it simpler for CI to have no versions in the profile, @sshepel ? It'd certainly make it easier to test the wrong version of CUDA though.

**Comment by sshepel** [comment]
> Not sure it would make it simpler for CI to have no versions in the profile, @sshepel ? It'd certainly make it easier to test the wrong version of CUDA though.

@saudet you are right, I would say just to fix profile name and not remove the version in it, "Explicit is better than implicit."
