### ISSUE TITLE
Comment issue in YoloUtils.java

### ISSUE THREAD

**Issue by liweigu** [deeplearning4j/deeplearning4j#4640]
#### Issue Description

Please describe our issue, along with:
- expected behavior
I think 0 is 'least strict', 1 is 'most strict', because the less confThreshold is, the more DetectedObject(s) will be found.
- encountered behavior
In the code from https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/layers/objdetect/YoloUtils.java , At line 139, which is '@param confThreshold Detection threshold, in range 0 (most strict) to 1 (least strict).'

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
0.9.2_snapshot
2018-02-09
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by AlexDBlack** [comment]
Thanks for reporting this, you are correct - fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/4648
