### ISSUE TITLE
CUDA crash with ComputationGraph + Workspaces

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4641]
Does not occur without workspaces enabled. Does not occur on native/cpu. Does not trigger scope panic.

Network configuration: https://gist.github.com/AlexDBlack/bfea0f99e16c74034cf8edeaa8003e24

```
        ComputationGraph net = new ComputationGraph(conf);
        net.init();
        for(int i=0; i<10; i++ ){
            list.add(new DataSet(Nd4j.create(32,23,6), Nd4j.create(32,2)));
        }

        DataSetIterator iter2 = new ExistingDataSetIterator(list);
        net.fit(iter2);
````

Stack trace: https://gist.github.com/AlexDBlack/5ce416e638c4dfec7f6e11bed0c58f12

**Comment by AlexDBlack** [comment]
Looking at the stack trace, this may be the same issue as: https://github.com/deeplearning4j/nd4j/issues/2615

**Comment by raver119** [comment]
Looks like mistake in new migration methods tbh. In this case datasets are not attached, but "something is happening".
