### ISSUE TITLE
Implement SqueezeNet

### ISSUE THREAD

**Issue by tom-adsfund** [deeplearning4j/deeplearning4j#4645]
Compared to ResNet50, SqueezeNet can be much cheaper (smaller, ~3x faster to train), faster (~5x inference), and generally more efficient.

See: https://shuaiw.github.io/2017/03/09/smaller-faster-deep-learning-models.html
And for source code: https://github.com/rcmalli/keras-squeezenet/blob/master/keras_squeezenet/squeezenet.py

**Comment by saudet** [comment]
Darknet is also pretty small. Have you tried that one?

**Comment by raver119** [comment]
Where we are with this one?

**Comment by tom-adsfund** [comment]
@raver119 I don't know any progress on implementation, but as saudet says, Darknet is 'small'. I've suggested in another issue that the transfer learning example be moved to Darknet. Would be good to have variety, but obviously that depends on people finding the time to implement them.

**Comment by tom-adsfund** [comment]
This was added to the Zoo recently!
