### ISSUE TITLE
Spark streaming with deeplearning4j

### ISSUE THREAD

**Issue by anishsharma** [deeplearning4j/deeplearning4j#4657]
Hi,

My problem is that I need to **predict** on a **time series** data which is coming in **real time**. So, I was looking for any sort of tutorial on how to leverage spark streaming with **deeplearning4j**. To my disappointment, I was not able to find any. Can any one tell me if that is even possible with the latest release of **deeplearning4j**. Just to mention that I am asking about **spark streaming** and not **spark** as I know it supports **spark**. Any other ideas would be welcome. Please advice.

Thanks & Regards
Anish Sharma

**Comment by agibsonccc** [comment]
@anishsharma I don't even know where to begin with your question. You can do that just fine out of the box. You just need to set it up yourself. Sorry I'm closing this. The "support" you're asking for seems to be "build it for me" which we are not likely to do. It's not hard to embed a neural network in a map function. I'm closing this.
