### ISSUE TITLE
Removing node from VocabCache does not update word indexes

### ISSUE THREAD

**Issue by bholland** [deeplearning4j/deeplearning4j#4658]
#### Issue Description

I wanted to run a PCA on the vocab cache for a TfIdfVector object. Once I had the cache created, I removed all but the top 250 columns (columns are words, rows are documents). In the process of transforming text using the model (vec.transform()), VocabCache returned an index for a word that was larger than 250. 

Stepping through the code, it looks like VocabCache does not rebuild an internal index on delete and all rebuild methods are protected. 

I would expect that if I remove a node (a VocabWord in this case) that the VocabCache correctly returns the updated index if I call the "word to index" method. 

Currently, it will return a positive number if the word is still in the cache after the PCA but the index will be the index of the full dataset. 

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - Latest release. I think 3.*. 
* platform information (OS, etc) - Ubuntu 16.04. 
* CUDA version, if used - not used
* NVIDIA driver version, if in use - not used

#### Contributing

I might be able to contribute. I will have to check with my manager.

**Comment by raver119** [comment]
Fixed/implemented in my branch. Will be merged soon.

**Comment by bholland** [comment]
Oh cool. Thank you!
