### ISSUE TITLE
CPU and GPU results inconsistent in dl4j example

### ISSUE THREAD

**Issue by mikeorzel2** [deeplearning4j/deeplearning4j#466]
Hi,

I have run the following from dl4j-0.0.3.3-examples

java -cp target/deeplearning4j-examples-0.0.3.3.3-SNAPSHOT.jar org.deeplearning4j.multilayer.MLPBackpropIrisExample

with both jblas and jcublas and I am getting different results for each. 

Output below for GPU (jcublas-7.0)
```
o.d.m.MLPBackpropIrisExample - Load data....
o.d.m.MLPBackpropIrisExample - Build model....
o.d.m.MLPBackpropIrisExample - Train model....
o.d.o.l.ScoreIterationListener - Score at iteration 0 is NaN
o.d.o.l.ScoreIterationListener - Score at iteration 2 is NaN
o.d.o.l.ScoreIterationListener - Score at iteration 4 is NaN
o.d.o.l.ScoreIterationListener - Score at iteration 6 is NaN
o.d.o.l.ScoreIterationListener - Score at iteration 8 is NaN
o.d.m.MLPBackpropIrisExample - Evaluate weights....
o.d.m.MLPBackpropIrisExample - Weights: [[0.044790275394916534, -0.015389188192784786, 0.02930864691734314]
 [-0.12919463217258453, -0.10148998349905014, 0.03806814178824425]
  ,[0.2851211428642273, -0.15225690603256226, -0.10736142098903656]
  ,[0.08416268974542618, -0.1747085601091385, 0.10301872342824936]]

o.d.m.MLPBackpropIrisExample - Weights: [[0.03378085419535637, 0.07176550477743149]
 [0.021460145711898804, -0.16026374697685242]
  ,[-0.10972407460212708, 0.041113343089818954]]

o.d.m.MLPBackpropIrisExample - Weights: [[0.022954460233449936, 0.02385137230157852, 0.0259566493332386]
 [-0.17149312794208527, -0.1077493280172348, 0.08480585366487503]]

o.d.m.MLPBackpropIrisExample - Evaluate model....
o.d.m.MLPBackpropIrisExample - 

Actual Class 0 was predicted with Predicted 0 with count 49 times

Actual Class 0 was predicted with Predicted 2 with count 1 times

Actual Class 1 was predicted with Predicted 0 with count 9 times

Actual Class 1 was predicted with Predicted 1 with count 6 times

Actual Class 1 was predicted with Predicted 2 with count 35 times

Actual Class 2 was predicted with Predicted 2 with count 50 times

==========================Scores========================================
 Accuracy:  0.7472
 Precision: 0.8087
 Recall:    0.7
 F1 Score:  0.7504517912193047
===========================================================================
o.d.m.MLPBackpropIrisExample - ****************Example finished********************
```

Output from CPU (jblas below)
```
o.d.m.MLPBackpropIrisExample - Load data....
o.d.m.MLPBackpropIrisExample - Build model....
o.d.m.MLPBackpropIrisExample - Train model....
o.d.o.l.ScoreIterationListener - Score at iteration 0 is -2.999999870856603E-5
o.d.o.l.ScoreIterationListener - Score at iteration 2 is -2.999999870856603E-5
o.d.o.l.ScoreIterationListener - Score at iteration 4 is -2.999999870856603E-5
o.d.o.l.ScoreIterationListener - Score at iteration 6 is -2.999999870856603E-5
o.d.o.l.ScoreIterationListener - Score at iteration 8 is -2.999999870856603E-5
o.d.m.MLPBackpropIrisExample - Evaluate weights....
o.d.m.MLPBackpropIrisExample - Weights: [[0.04487064480781555, -0.015433232299983501, 0.029264062643051147]
 [-0.12931537628173828, -0.1017034575343132, 0.03829861059784889]
  ,[0.28522542119026184, -0.15214358270168304, -0.10748884826898575]
  ,[0.08427724987268448, -0.1748126745223999, 0.10295899957418442]]

o.d.m.MLPBackpropIrisExample - Weights: [[0.034003742039203644, 0.07052546739578247]
 [0.02141791395843029, -0.16206207871437073]
  ,[-0.10976751148700714, 0.03910006582736969]]

o.d.m.MLPBackpropIrisExample - Weights: [[0.02228448912501335, 0.02695128135383129, 0.02370724081993103]
 [-0.1713624745607376, -0.10537957400083542, 0.0840180367231369]]

o.d.m.MLPBackpropIrisExample - Evaluate model....
o.d.m.MLPBackpropIrisExample - 

Actual Class 0 was predicted with Predicted 1 with count 16 times

Actual Class 0 was predicted with Predicted 2 with count 34 times

Actual Class 1 was predicted with Predicted 2 with count 50 times

Actual Class 2 was predicted with Predicted 2 with count 50 times

==========================Scores========================================
 Accuracy:  0.4286
 Precision: 0.1244
 Recall:    0.3333
 F1 Score:  0.18115942028985507
===========================================================================
o.d.m.MLPBackpropIrisExample - ****************Example finished********************
-- org.jblas INFO Deleting /tmp/jblas6084490937497261076/libjblas_arch_flavor.so
-- org.jblas INFO Deleting /tmp/jblas6084490937497261076/libjblas.so
-- org.jblas INFO Deleting /tmp/jblas6084490937497261076
```

**Comment by mikeorzel2** [comment]
Sorry didnt mean to highlight the F1 score, it must have been something in the copy/paste from the output

**Comment by agibsonccc** [comment]
So it diverges in the first set score on the RBM, specifically:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/feedforward/rbm/RBM.java#L326-326

Everything is the same up to that point. (I mean weights/updates/EVERYTHING) so I'm wondering what would be causing the matrix multiply + add to be different.

The offset is zero so it's not a gpu issue and the matrix multiply tests I have on both pass just fine. I wonder if this could be related to precision on the GPU?

**Comment by mikeorzel2** [comment]
Hi Adam,

Thanks for the tip, bit more digging I have come up with this

CPU Run (3rd time we do a mmuli)

o.n.l.a.n.BaseNDArray - starting mmul input:[[0.036776475608348846, 0.015806151553988457]
 [0.02033056505024433, -0.12437079846858978]
  ,[-0.11003565788269043, 0.04167283698916435]]

o.n.l.a.n.BaseNDArray - mmul shape:[0.0, 0.0]

o.n.l.a.n.BaseNDArray - starting mmuli other:[[0.036776475608348846, 0.015806151553988457]
 [0.02033056505024433, -0.12437079846858978]
  ,[-0.11003565788269043, 0.04167283698916435]]

o.n.l.a.n.BaseNDArray - finishing calc mmuli resultArray:[-0.012643914669752121, 0.03470443934202194]
 
o.n.l.a.n.BaseNDArray - finishing mmul output: [-0.012643914669752121, 0.03470443934202194]

GPU Run (same mmuli, same input as can be seen below, different output)

o.n.l.a.n.BaseNDArray - starting mmul input:[[0.036776475608348846, 0.015806151553988457]
 [0.02033056505024433, -0.12437079846858978]
  ,[-0.11003565788269043, 0.04167283698916435]]

o.n.l.a.n.BaseNDArray - mmul shape:[0.0, 0.0]

o.n.l.a.n.BaseNDArray - starting mmuli other:[[0.036776475608348846, 0.015806151553988457]
 [0.02033056505024433, -0.12437079846858978]
  ,[-0.11003565788269043, 0.04167283698916435]]

o.n.l.a.n.BaseNDArray - finishing calc mmuli resultArray:[-0.012643914669752121, 0.03470444306731224]

o.n.l.a.n.BaseNDArray - finishing mmul output: [-0.012643914669752121, 0.03470444306731224]



Diff of results above (first divergence in mmuli)

< o.n.l.a.n.BaseNDArray - finishing calc mmuli resultArray:[-0.012643914669752121, 0.03470443934202194]
---
> o.n.l.a.n.BaseNDArray - finishing calc mmuli resultArray:[-0.012643914669752121, 0.03470444306731224]

Going to chase the tail down to lower layers, this is just based on some logging at the BaseNDArray.java level.

**Comment by agibsonccc** [comment]
JFYI:
We have a decent sized test suite for this stuff. You may want to look at the scenarios I enumerate:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-tests/src/test/java/org/nd4j/linalg/Nd4jTestsC.java#L396-396

https://github.com/deeplearning4j/nd4j/blob/master/nd4j-tests/src/test/java/org/nd4j/linalg/NDArrayTestsFortran.java

These tests get run for every backend via 
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-tests/src/test/java/org/nd4j/linalg/Nd4jTestSuite.java

You may want to increase your familiarity with BLAS as well. The core blas operations are:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-jcublas-parent/nd4j-jcublas-common/src/main/java/org/nd4j/linalg/jcublas/blas/JcublasLevel3.java#L36-35

https://github.com/deeplearning4j/nd4j/blob/master/nd4j-jblas/src/main/java/org/nd4j/linalg/jblas/blas/JblasLevel3.java#L30-30


You will notice they mostly follow the same path.

There's not much difference between the 2. Get on gitter:
https://gitter.im/deeplearning4j/deeplearning4j if you want help tracking those down

**Comment by agibsonccc** [comment]
Fixed.
