### ISSUE TITLE
 useExistingWordVectors() not setting vocabCache and lookupTable

### ISSUE THREAD

**Issue by jvence** [deeplearning4j/deeplearning4j#4665]
#### Issue Description
Using useExistingWordVectors() does not seem to work properly with some more basic models. You still need to manually set BOTH vocabCache and lookupTable as such:
new ParagraphVectors.Builder()
                .vocabCache(wordVectors.vocab())
                .lookupTable(wordVectors.lookupTable())

As useExistingWordVectors() expects a model that has the syn1/syn1Neg data, and since some basic word vectors don't have it, we run into this problem. 

Please describe our issue, along with:
We would expect  useExistingWordVectors() to automatically set these values

* Deeplearning4j version
0.9.1
* platform information (OS, etc)
Mac OS

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by alexanderst** [comment]
Not a bug, there are confirming tests. 
Incompatibility of existing model being passed to ParagraphVectors is handled properly. For example, when existing model was trained initially without HS and then passed to ParagraphVectors this exception is thrown:
"org.nd4j.linalg.exception.ND4JIllegalStateException: Model being passed as existing has no syn1/syn1Neg available"
