### ISSUE TITLE
The method humanReadableInt in StringUtils.java has a race condition.

### ISSUE THREAD

**Issue by cragkhit** [deeplearning4j/deeplearning4j#4692]
#### Issue Description

Hi. I found that the `humanReadableInt(long number)` method in the `deeplearning4j-nn/src/main/java/org/deeplearning4j/util/StringUtils.java` contains code which has a race condition as shown in Hadoop (issue tracking ID [HADOOP-9252](https://issues.apache.org/jira/browse/HADOOP-9252)). I couldn't find a call to the method anywhere else in the code. But it might be worth to fix.

#### Version Information

I looked at the latest version of the code.

#### Contributing

In Hadoop, they changed this method in their [StringUtils.java](https://github.com/apache/hadoop/blob/532bbf4602e418276961cfc4f6b5e3f70e9cedc0/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/StringUtils.java) to call `TraditionalBinaryPrefix.long2String(number, "", 1);` instead.
```java
  /**
   * Given an integer, return a string that is in an approximate, but human 
   * readable format. 
   * @param number the number to format
   * @return a human readable form of the integer
   *
   * @deprecated use {@link TraditionalBinaryPrefix#long2String(long, String, int)}.
   */
  @Deprecated
  public static String humanReadableInt(long number) {
    return TraditionalBinaryPrefix.long2String(number, "", 1);
  }
```

**Comment by saudet** [comment]
Sounds good! Please send a pull request if possible.

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/4725
