### ISSUE TITLE
IntelliJ build exception

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4702]
This *might* be an intellij issue, but it might be related to some of our maven plugins also? I am seeing this frequently on both Windows and Linux, and is quite disruptive. It also seems to result in some occasions on old code/dependencies being used when tests are run.

![image](https://user-images.githubusercontent.com/2360237/36588620-c8dbb8d2-18dc-11e8-9d5c-258683fadad8.png)

**Comment by raver119** [comment]
I think this issue is irrelevant now?

**Comment by raver119** [comment]
Fixed :)
