### ISSUE TITLE
Latest version of DeepLearning4j

### ISSUE THREAD

**Issue by ntaherkhani** [deeplearning4j/deeplearning4j#4731]
I need to do AutoEncoder using Conv net to detect anomaly . I need UpSampling layer from DeepLearning4j-nn. when do you think you can put jar file of latest version of DeepLearning4j in central repository? Or, from where can I get jar file of snapshot of latest version? Thanks.

**Comment by AlexDBlack** [comment]
The latest version on maven central (i.e., the last release) was 0.9.1. We will be doing another release as soon as we can - but only when it's ready.

You can find information on using snapshots in your project here: https://deeplearning4j.org/snapshots
Snaphots include upsampling layer (and deconvolutional layers), whereas 0.9.1 does not.
