### ISSUE TITLE
K-Means taking too long 

### ISSUE THREAD

**Issue by ParZaib** [deeplearning4j/deeplearning4j#4748]
I am trying thresholding with kmeans. For this i have an double array with 1500 values.
I always need to calculate 2 clusters for 0 +x values out of my double array.
for example :   cluster the first 2 values of my double array, then cluster the first 3 values and then the first 4..... till  end.
All the time i need the centroids of my clustering result.

This is my approach:

```
double doubleValues[] ={23.23,0.23454,0.123,......};  // 1500 values
INDArray result = Nd4j.create(doubleValues, new int[] { doubleValues.length, 1 });
List<Point> points = Point.toPoints(result);//created a list of Points  

List<List<Point>> listOfPointLists = new ArrayList<List<Point>>(); // list of point list
List<Point> points1 = new ArrayList<Point>();

// get the first 2 then 3, then 4.... and make a point list		
for(int i = 2;   i< = points.size(); i++) 
{  
   points1 = points.subList(0,i);
   listOfPointLists.add(points1);			 	 
}
//here i create my Kmeans instance and create a List of ClusterSet because i will have many clusters  
 KMeansClustering kMeansClusteringEuclidean = KMeansClustering.setup(2, 1000, "euclidean");  
 List<ClusterSet> listOfClusterSet = new ArrayList<ClusterSet>();
	  
      // here i go though the Points list list to apply kmeans
	    for(int i=0;i< listOfPointLists.size();i++)
	    {
	    	listOfClusterSet.add(kMeansClusteringEuclidean.applyTo(listOfPointLists.get(i)));
	    }

	    //and here i want to see my result
	    for(int i=0;i<  listOfPointLists.size();i++)
	    {
	      System.out.print(i+" "+listOfClusterSet.get(i).getClusters().get(0).getCenter().getArray().getDouble(0)+ " ");
	   	  System.out.println(i+" "+listOfClusterSet.get(i).getClusters().get(1).getCenter().getArray().getDouble(0));;
	    }


```
This takes already more then 5 min for 200 kmean calculations.
Need to apply KmeanPlusPlus? Or maybe i have used some wrong functions?

Thank you very much

#### Version Information

Using Windows and Eclipse

Version in Pom.xml
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-core</artifactId>
			<version>0.9.1</version>
		</dependency>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-native-platform</artifactId>
			<version>0.9.1</version>
		</dependency>

**Comment by saudet** [comment]
Could you give it a try with 0.9.2-SNAPSHOT just to make sure this is still an issue? Thanks!

**Comment by saudet** [comment]
https://deeplearning4j.org/snapshots

**Comment by ParZaib** [comment]
now my INDArray is giving me an

at machine.learning.kmeans.KmeansSetup.main(KmeansSetup.java:47)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException:
at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6425)
at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6293)
at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:206)
... 1 more
Caused by: java.lang.ClassNotFoundException:
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Unknown Source)
at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6347)
... 3 more



Gesendet von Outlook<http://aka.ms/weboutlook>
________________________________
Von: Samuel Audet <notifications@github.com>
Gesendet: Sonntag, 4. März 2018 09:58
An: deeplearning4j/deeplearning4j
Cc: Jahn Zaib Khan; Author
Betreff: Re: [deeplearning4j/deeplearning4j] K-Means taking too long (#4748)


https://deeplearning4j.org/snapshots

**Comment by saudet** [comment]
We've been having issues with snapshots today. Please try the same thing again tomorrow. Thanks!!

**Comment by alexanderst** [comment]
Performance fixed, merged.
