### ISSUE TITLE
Document things

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#4753]
#### Issue Description

A long time ago a plan was put together to document things. Today, this shall come to reality.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j master

#### Contributing

> I will pull the sword from the rock.

- King Arthur

**Comment by agibsonccc** [comment]
If you're King Arthur, I'm Mordred. I'm closing this :).

**Comment by crockpotveggies** [comment]
Hmm looks like I didn't set up closing automation.
