### ISSUE TITLE
Website version info for cuDNN

### ISSUE THREAD

**Issue by rawkintrevo** [deeplearning4j/deeplearning4j#4757]
#### Issue Description

[https://deeplearning4j.org/cudnn](https://deeplearning4j.org/cudnn) states:
`Note that only cuDNN 6.0 is supported.` however, [cuDNN](http://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html) only supports CUDA 0.9.1 starting in version 7.0.5. 

Supposing that this actually works- the website should be updated to something like:
`Note that only cuDNN 6.0+ is supported`. 

#### Version Information

* Deeplearning4j:  `0.9.1`
* cuDNN: `0.7.x `

#### Contributing

I'd like to start contributing, but not sure if website code is public.  Please advise.

**Comment by saudet** [comment]
Sure it is, check the `gh-pages` branch.

**Comment by crockpotveggies** [comment]
Thanks for bringing this to our attention. Like @saudet said, our docs are located at `gh-pages` and cudnn is here: https://github.com/deeplearning4j/deeplearning4j/blob/gh-pages/cudnn.md

Please feel free to hit the edit button and submit a pull request and I'll happily get it mergred.

**Comment by turambar** [comment]
@rawkintrevo let us know if you need any further assistance with the edit! We are awaiting your PR with bated breath.

**Comment by rawkintrevo** [comment]
hey there- wanted to test before I posted to website.  I'm not convinced this is true.  Spent the day messing with it- I can get CUDA-8.0+cuDNN-6.0 to work, CUDA-8.0+cuDNN-7.1 would _not_ work.  I think the 6.0 might be hardcoded in somewhere, but it was throwing an error, which I didn't write down, something similar to this https://github.com/deeplearning4j/deeplearning4j/issues/2879

At anyrate- can some one confirm that CUDA-8.0 + cuDNN-7.1 / CUDA-9.0 + cuDNN-7.1 _does_ work before I push this? pls/thanks- I'm in gitter, and will keep working the issue from my end.

**Comment by AlexDBlack** [comment]
NVIDIA releases versions of CUDNN for different CUDA versions... AFAIK any of the compatible versions should work - cc @saudet can you confirm?

https://developer.nvidia.com/rdp/cudnn-download
![image](https://user-images.githubusercontent.com/2360237/37066907-81c9cab0-21fb-11e8-88ea-f820ad7caac3.png)


And then there's the archived releases: https://developer.nvidia.com/rdp/cudnn-archive
![image](https://user-images.githubusercontent.com/2360237/37066917-90a134a6-21fb-11e8-8d84-39d59f7e99a7.png)

**Comment by saudet** [comment]
No, I haven't update the wrappers for CUDA 8.0 and cuDNN 7. Any reason for now using CUDA 9?

**Comment by rawkintrevo** [comment]
For me CUDA 9 + cuDNN 7.0 wasn't working, however i was having issues with SNAPSHOT, so it could have been spurious/unrelated.

CUDA 8.0 + cuDNN 7.1 also wasn't working- which is why I've decided to stand down on updating page. 

CUDA 8.0 + cuDNN 6.0 _is_ working on my machine.

**Comment by saudet** [comment]
Ok, please file issues you're having with 0.9.2-SNAPSHOT and CUDA 9!

**Comment by rawkintrevo** [comment]
hey all- finally sat down to to this- seems like website has moved to https://github.com/deeplearning4j/deeplearning4j-docs

My question is- should I open PR against that repo?  I don't see any issues or PRs but it seems this change over _just_ happened.

**Comment by rawkintrevo** [comment]
I'm closing issue if no further comments.

**Comment by agibsonccc** [comment]
Thanks Trevor!
