### ISSUE TITLE
Windows - CUDA gradient check failures

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4761]
Test platform: Windows, CUDA 9.0
Edit: Windows CUDA 9.1 fails with exact same symptoms.
Fails when run through intellij or maven

These tests fail on CUDA when all CNNGradientCheckTests are run, but pass:
(a) On CPU
(b) When run in isolation (i.e., one test at a time)
(c) on Linux, CUDA 9.1 (Kubuntu 17.10, GTX 970s)

![image](https://user-images.githubusercontent.com/2360237/37014124-9b42dfd0-2152-11e8-814a-a5c05e1e6057.png)

Note that it's inconsistent - different tests fail during different runs...
![image](https://user-images.githubusercontent.com/2360237/37014593-d5f1dc82-2155-11e8-862e-7883d6b28e67.png)

![image](https://user-images.githubusercontent.com/2360237/37014618-03d67d92-2156-11e8-9ea7-17b502bbefa4.png)

Results when run through maven: https://gist.github.com/AlexDBlack/ca782023187fa0786054b733c6e10960

Not sure what's going on here or why...

Edit: so far I've ruled out:
1. Workspaces (setting WorkspaceMode.NONE makes no difference)
2. RNG seeds (setting before each test - no difference)
3. Destroying workspaces before each gradient check is run

There seems to be some degree of randomness - and possibly multiple issues...
1. Some tests clearly fail due to subsampling layer backprop
2. Other tests fail with a single, very wrong gradient (see below)
3. Other tests just fail outright - all gradients fail, but other tests (very similar params/config) all pass
4. Some tests I can run for a thousand times, without any issues :/

```
o.d.g.GradientCheckUtil - Param 1812 (2_W) passed: grad= 0.04007660303681882, numericalGrad= 0.04007660303617655, relError= 8.01304140042311E-12
o.d.g.GradientCheckUtil - Param 1813 (2_W) FAILED: grad= 0.0034388891218970277, numericalGrad= 48836.31517098053, relError= 0.9999998591667342, scorePlus=0.693761944443137, scoreMinus= 0.5960893141011759
o.d.g.GradientCheckUtil - Param 1814 (2_W) passed: grad= -0.021406821076271437, numericalGrad= -0.021406821093528094, relError= 4.030644680906441E-10
```

**Comment by AlexDBlack** [comment]
Update here: this is still occuring on Windows, still passing consistently on Linux.
As an additional experiment, I've run testCnnSamePaddingModeStrided (so far) 84 times in a loop without any issues at all. :/

**Comment by raver119** [comment]
Quick update: this is definitely some kind of race condition. Bug isn't reproducible on Azure K80 gpu, and isn't reproducible in debug mode on my desktop.

**Comment by raver119** [comment]
Update:
- definitely not caused by workspace mode
- original idea that it might be caused by im2col/col2im/pooling2d ops wasn't confirmed :/
- layers themselves look ok.

**Comment by raver119** [comment]
Update:
- definitely might happen on FF or BP pass or both
- difference looks to be concentrated around Conv2D layer
- Conv2D layer produces different outputs given the same inputs.

**Comment by raver119** [comment]
<img width="1680" alt="screen shot 2018-03-28 at 20 12 02" src="https://user-images.githubusercontent.com/12250879/38069152-bfc41468-32c9-11e8-9624-c83603a9d7ab.png">

**Comment by AlexDBlack** [comment]
Confirmed fixed.
