### ISSUE TITLE
Not yet implemented  InMemoryLookupTable.plotVocab

### ISSUE THREAD

**Issue by romass12** [deeplearning4j/deeplearning4j#4770]
#### Issue Description
I am using TSNE for plotting vocabulary table for my word2vec model.
But , I used the below code for visualisation 
       UIServer server = UIServer.getInstance();        
        StatsStorage statsStorage = new InMemoryStatsStorage();          
        server.attach(statsStorage);
        BarnesHutTsne tsne = new BarnesHutTsne.Builder()
                .setMaxIter(1000)
                .stopLyingIteration(250)
                .learningRate(500)
                .useAdaGrad(false)
                .theta(0.5)
                .setMomentum(0.5)
                .normalize(true)
                .build();
      
        word2VecModel.lookupTable().plotVocab(tsne,1000, new UiConnectionInfo.Builder()
                .setPort(server.getPort())
                .build());

It gives this error : 
java.lang.UnsupportedOperationException: Not yet implemented at org.deeplearning4j.models.embeddings.inmemory.InMemoryLookupTable.plotVocab(InMemoryLookupTable.java:221)
	at com.technobium.dl4j_word2vec.App.main(App.java:153)

Deeplearning 4j version - 0.7.2

**Comment by agibsonccc** [comment]
We don't support old versions. 0.9.1 has been out for 6 months now. The 1.0 is coming soon. Please at least try recent versions first.

**Comment by romass12** [comment]
Thank u and sorry
