### ISSUE TITLE
CPU - sgemm deadlock?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4776]
Running snapshots (latest DL4J master) on this branch of examples: https://github.com/deeplearning4j/dl4j-examples/pull/589
Specifically GravesLSTMCharModellingExample

System: Windows 10 with MKL.

Output gets to here and just stops...
```
21:55:57,139 INFO  ~ Loaded [CpuBackend] backend
21:55:58,371 INFO  ~ Number of threads used for NativeOps: 8
21:56:16,944 INFO  ~ Number of threads used for BLAS: 8
21:56:16,966 INFO  ~ Backend used: [CPU]; OS: [Windows 10]
21:56:16,966 INFO  ~ Cores: [16]; Memory: [7.1GB];
21:56:16,966 INFO  ~ Blas vendor: [MKL]
21:56:17,734 INFO  ~ Starting MultiLayerNetwork with WorkspaceModes set to [training: SEPARATE; inference: SEPARATE]
Number of parameters in layer 0: 223000
Number of parameters in layer 1: 321400
Number of parameters in layer 2: 15477
Total number of network parameters: 559877
```

YourKit profiler picks this up as a deadlock:
![image](https://user-images.githubusercontent.com/2360237/37147696-e3351e5a-231b-11e8-9455-540ec63e681a.png)

Note that the 0.9.1 version runs fine... and a bunch of the other examples run fine also. I'm only seeing issues on this one (so far).

Edit: weirdly GravesLSTMCharModellingExample consistently deadlocks for me, but CompGraphLSTMExample runs fine...

**Comment by raver119** [comment]
cc @saudet

**Comment by saudet** [comment]
MKL? @agibsonccc has been having problems with it recently too. Does this happen when setting "org.bytedeco.javacpp.openblas.nomkl" to "true" (and making sure OpenBLAS gets used there)?

**Comment by AlexDBlack** [comment]
Confirmed - it runs fine with nomkl...
I'm currently running with MKL 2017.0.109 - Windows, obviously.

```
14:53:06,483 INFO  ~ Number of threads used for NativeOps: 8
14:53:07,062 INFO  ~ Number of threads used for BLAS: 8
14:53:07,068 INFO  ~ Backend used: [CPU]; OS: [Windows 10]
14:53:07,068 INFO  ~ Cores: [16]; Memory: [7.1GB];
14:53:07,068 INFO  ~ Blas vendor: [OPENBLAS]
14:53:07,436 INFO  ~ Starting MultiLayerNetwork with WorkspaceModes set to [training: SEPARATE; inference: SEPARATE]
Number of parameters in layer 0: 223000
Number of parameters in layer 1: 321400
Number of parameters in layer 2: 15477
Total number of network parameters: 559877
14:53:08,669 INFO  ~ Score at iteration 0 is 217.3094269104862
14:53:09,463 INFO  ~ Score at iteration 1 is 194.38822552481727
14:53:10,237 INFO  ~ Score at iteration 2 is 212.2022684814953
```

**Comment by AlexDBlack** [comment]
Yeah, 0.9.1 (examples master) + the same MKL works fine:
```
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
15:26:01,566 INFO  ~ Loaded [CpuBackend] backend
15:26:01,843 INFO  ~ Number of threads used for NativeOps: 8
15:26:02,187 INFO  ~ Number of threads used for BLAS: 8
15:26:02,189 INFO  ~ Backend used: [CPU]; OS: [Windows 10]
15:26:02,189 INFO  ~ Cores: [16]; Memory: [7.1GB];
15:26:02,189 INFO  ~ Blas vendor: [MKL]
15:26:02,433 INFO  ~ Starting MultiLayerNetwork with WorkspaceModes set to [training: NONE; inference: SEPARATE]
Number of parameters in layer 0: 223000
Number of parameters in layer 1: 321400
Number of parameters in layer 2: 15477
Total number of network parameters: 559877
15:26:03,350 INFO  ~ Score at iteration 0 is 217.3094269104862
``

**Comment by AlexDBlack** [comment]
And I can confirm that it occurs for both a local build, as well as when using (sonatype) snapshots...

**Comment by AlexDBlack** [comment]
So far: I've isolated it to 1 situation that deadlocks, and 3 that should be equivalent/identical that don't deadlock...

```
    @Test
    public void testMkl_Deadlocks(){

        INDArray a0 = Nd4j.create(new int[]{32,77,50}, 'f');
        INDArray a1 = a0.tensorAlongDimension(0, 1, 0);
        INDArray a2 = Nd4j.create(new int[]{77,800}, 'f');
        a1.mmul(a2);
        System.out.println("DONE");
    }

    @Test
    public void testMkl_NoDeadlock1(){

        INDArray a0 = Nd4j.create(new int[]{32,77,50}, 'f');
        INDArray a1 = a0.tensorAlongDimension(0, 1, 0);
        a1 = Nd4j.create(a1.shape(), a1.ordering());
        INDArray a2 = Nd4j.create(new int[]{77,800}, 'f');
        a1.mmul(a2);
        System.out.println("DONE");
    }

    @Test
    public void testMkl_NoDeadlock2(){
        INDArray a1 = Nd4j.create(new int[]{32,77}, 'f');
        INDArray a2 = Nd4j.create(new int[]{77,800}, 'f');
        a1.mmul(a2);
        System.out.println("DONE");
    }

    @Test
    public void testMkl_NoDeadlock3(){

        Nd4j.create(10,10).mmul(Nd4j.create(10,10));

        INDArray a0 = Nd4j.create(new int[]{32,77,50}, 'f');
        INDArray a1 = a0.tensorAlongDimension(0, 1, 0);
        INDArray a2 = Nd4j.create(new int[]{77,800}, 'f');
        a1.mmul(a2);
        System.out.println("DONE");
    }
```

**Comment by saudet** [comment]
This really sounds like issues with threading. I know OpenBLAS doesn't work well with OpenMP, so I'm building it without and using it's pthreads support instead. We can do the same with MKL:
https://software.intel.com/en-us/mkl-windows-developer-guide-calling-intel-mkl-functions-from-multi-threaded-applications
Maybe one of those work better...

**Comment by saudet** [comment]
Specifically, we can set MKL_THREADING_LAYER to "GNU" (Linux only?), "INTEL", "PGI", "TBB", or "SEQUENTIAL".

**Comment by AlexDBlack** [comment]
Well, *maybe* it's threading related. But why does it work totally fine for all subsequent calls - and not the first one? If it was threading related, shouldn't it happen all the time?

**Comment by AlexDBlack** [comment]
Looks like it's legitimately bad args (well, single bad *arg*)... fix incoming...

**Comment by AlexDBlack** [comment]
OK, so I was wrong. The arg issue was legitimate - but is *not* the cause of this deadlock.
However, the problem is stochastic (occurs sometimes, but not others - which is why I had *thought* I had fixed it...)

Anyway, this feels a lot like a race condition (probably with native library loading, somehow). Notably, the following Thread.sleep(500) on the first gemm call only is sufficient to fix it (tested 50 times, no deadlocks vs. about 50/50 chance without it).

https://github.com/deeplearning4j/nd4j/blob/98f129eadcea9d7f0af933f7aa9954ef1cc69d2a/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/linalg/cpu/nativecpu/blas/CpuLevel3.java#L52-L59

**Comment by saudet** [comment]
Did you also set the "org.bytedeco.javacpp.logger" system property to "slf4j"? We can get more information about what's happening with JavaCPP's loader that way.

**Comment by AlexDBlack** [comment]
Logs - for both deadlock and no-deadlock (with sleep):
https://gist.github.com/AlexDBlack/517569d9eb611f1efebfe5362b76a59b

**Comment by saudet** [comment]
Thanks! The only difference I can see between the 2 is that the deadlock one runs from an empty `~/.javacpp/cache`, while the OK one isn't extracting or copying anything..

**Comment by AlexDBlack** [comment]
Some additional details (partly from gitter)

> I haven't touched the javacpp cache (manually) during this testing yet

so in the deadlock one - the text "copy" and "extract" don't appear anywhere
in both the successful and deadlock cases - we have lots of this sort of thing, which looks suspicious...
```
o.b.j.Loader - Loading C:\Users\Alex\.javacpp\cache\compiler\libiomp5md.dll
o.b.j.Loader - Preloading C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.1.156\windows\redist\intel64_win\mkl\mkl_avx.dll
o.b.j.Loader - Locking C:\Users\Alex\.javacpp\cache to create symbolic link
o.b.j.Loader - Creating symbolic link C:\Users\Alex\.javacpp\cache\mkl\mkl_avx.dll to C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.1.156\windows\redist\intel64_win\mkl\mkl_avx.dll
o.b.j.Loader - Could not create symbolic link C:\Users\Alex\.javacpp\cache\mkl\mkl_avx.dll: java.nio.file.FileSystemException: C:\Users\Alex\.javacpp\cache\mkl\mkl_avx.dll: A required privilege is not held by the client.
```

-----
-----

Below: side by side comparison of the logs: successful (left) vs. deadlock (right)
that's the only thing that stands out as different (addresses/pointers aside)

https://files.gitter.im/deeplearning4j/dev_channel/LoNr/image.png

-----
-----

**Virus scanner**: I'm running Bitdefender Free - disabling it doesn't seem to make any difference (i.e., it still deadlocks)

**IntelliJ vs. "mvn clean test"**: Both ways of running deadlock still.

**Comment by saudet** [comment]
With the hacks out of the way (pull #2734), everything is working fine for me on Windows. I cannot cause any deadlocks with MKL 2018.1. Make sure that it's 2018.1 that actually gets loaded...

**Comment by AlexDBlack** [comment]
I'm still seeing deadlocks here the majority of the time (I'm quite sure it's using the specified PR and MKL 2018.1).

After clearing the cache, here's the output I'm getting:
https://gist.github.com/AlexDBlack/abfc8aed29a2442122c1236c72d2afa7

**Comment by saudet** [comment]
MKL has a tendency to ignore the libraries that we preload and tries to load them in surprising ways. Call MKL_Get_Version() and make sure it's the right version. Also, it might help to debug this by trying the recommended way of using the library, that is by executing mklvars.bat on the command line, and executing applications there.

**Comment by saudet** [comment]
There's also a couple of DLLs we're not copying into the cache (mainly `libimalloc.dll`, `mkl_sequential.dll`, and `mkl_tbb_thread.dll`), and maybe it's wanting to use one of those, but falls back on a suboptimal (and buggy) function for your chip architecture. Could you try to copy manually all DLLs from `C:/Program Files (x86)/IntelSWTools/compilers_and_libraries/windows/redist/intel64/mkl/` into `~/.javacpp/cache/mkl` and maybe the same for `.../compiler`, and see if that makes a difference?

**Comment by saudet** [comment]
In any case, let's get the pull request merge right away! Thanks

**Comment by AlexDBlack** [comment]
Re: merging the PR - I can't see any downside (other stuff runs fine, but it doesn't fix the issue here)

All tests: using sa_mkl branch

First test:
1. delete javaccp cache
2. "C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.1.156\windows\mkl\bin\mklvars.bat" intel64
3. Run via maven: java -cp dl4j-examples-0.9.1-bin.jar org.deeplearning4j.examples.MklTest

Result: same deadlock as before.

-----

Second test: (new cmd window, no mklvars.bat)
1. delete javaccp cache
2. run once (deadlocks), manually kill JVM
3. copy files: libimalloc.dll, mkl_sequential.dll, mkl_tbb_thread.dll (note: definitely not present originally)
   a. from: C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.1.156\windows\redist\intel64_win\mkl
   b. to: C:\Users\Alex\.javacpp\cache\mkl
4. Run via maven as above

Result: same deadlock as before
(note that running same thing with mklvars.bat also deadlocks)

-----

Now, as for MKL_Get_Version (run in intelij):
```
mkl_rt.MKLVersion v = new mkl_rt.MKLVersion();	//Exception here
org.bytedeco.javacpp.mkl_rt.MKL_Get_Version(v);
System.out.println("MKL VERSION: " + v);
```

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnimkl_rt in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1226)
	at org.bytedeco.javacpp.Loader.load(Loader.java:980)
	at org.bytedeco.javacpp.Loader.load(Loader.java:879)
	at org.bytedeco.javacpp.mkl_rt.<clinit>(mkl_rt.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:938)
	at org.bytedeco.javacpp.Loader.load(Loader.java:879)
	at org.bytedeco.javacpp.mkl_rt$MKLVersion.<clinit>(mkl_rt.java:140)
	at org.deeplearning4j.examples.MklTest.main(MklTest.java:14)
Caused by: java.lang.UnsatisfiedLinkError: no mkl_intel_lp64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1226)
	at org.bytedeco.javacpp.Loader.load(Loader.java:965)
	... 8 more
o.b.j.Loader - Failed to load for jnimkl_rt: java.lang.UnsatisfiedLinkError: no jnimkl_rt in java.library.path
```

**Comment by saudet** [comment]
Ah yes unless `nd4j-platform` is in the dependencies we need to add at least `mkl-platform`.

**Comment by saudet** [comment]
And please try to copy *all* the DLLs, because since it works when creating symlinks, it sounds like it might be after some DLLs that are found in the original directory...

**Comment by saudet** [comment]
Executing something from MKL like `MKLVersion()` before might also work around the issue...

**Comment by AlexDBlack** [comment]
OK, next round of tests (also on sa_mkl)

Using existing dependencies (no mkl-platform added for this test, no mklvars.bat)
1. Delete javacpp cache
2. Run once, deadlocks; kill
3. Copy entire directory contents:
    a. from: C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.1.156\windows\redist\intel64_win\mkl
    b. to: C:\Users\Alex.javacpp\cache\mkl
4. Run again

Result: still deadlocks

As for running MLK_Get_Version - it still doesn't work after copying the DLLs

-----

As for adding mkl-platform dependency: (I accidentally ran this with 2017 instead of 2018 - but I'll leave results here. 2018 results follow)
```
<dependency>
	<groupId>org.bytedeco.javacpp-presets</groupId>
	<artifactId>mkl-platform</artifactId>
	<version>2017.3-1.3</version>
</dependency>
```


Test 1:
1. Keep old javacpp cache from before
2. Add mkl-platform (MKL install still on path)
3. Run (intellij)
Result: deadlock


Test 2:
1. Delete javacpp cache
2. Add mkl-platform (MKL install still on path)
3. Run (intellij)
Result: deadlock

Test 3:
1. Delete javacpp cache
2. Add mkl-platform
3. Remove MKL install from path
4. Run in intellij
Result: runs with OPENBLAS, not MKL. See log output below (mkl-platform 2017 is definitely on classpath as you can see from first line)
https://gist.github.com/AlexDBlack/069af7a1595477fabf970f5ece51555e


-----

Same tests with 2018.1-1.4:

```
<dependency>
	<groupId>org.bytedeco.javacpp-presets</groupId>
	<artifactId>mkl-platform</artifactId>
	<version> 2018.1-1.4</version>
</dependency>
```


Test 1:
1. Delete javacpp cache
2. Add mkl-platform
3. Remove MKL install from path
4. Run in intellij
Result: runs with OPENBLAS, not MKL. See log output below (mkl-platform 2018 is definitely on classpath as you can see from first line)
https://gist.github.com/AlexDBlack/1b699a5b1149a6b4dc2f3db5713fbd9d


-----

> Executing something from MKL like MKLVersion() before might also work around the issue...

I'm not sure I'm following here - work around the UnsatisfiedLinkError? What specifically should I be running?

-----

Overall - to me, if feels like we are looking in the wrong direction...
if it was a problem with native library loading, why do other matrix dimensions work consistently and flawlessly for me? It seems like library loading wouldn't depend at all on input dimensionality - *unless* for some reason it had multiple gemm implementations in different DLLs, and was dynamically switching based on array order/size or something?

**Comment by saudet** [comment]
Yes, MKL is probably switching between implementations depending on the size of the problem. Maybe even loading mkl_sequential.dll for small matrices...

Wait, you're saying mkl-platform prevents ND4J from using MKL?? Let me check this out here

**Comment by AlexDBlack** [comment]
> Wait, you're saying mkl-platform prevents ND4J from using MKL?? Let me check this out here

That seems to be the case. I'm running our snapshots example branch in intellij, with mkl-platform added as a dependency. Happy to build an isolated/standalone project/pom if it helps...

**Comment by saudet** [comment]
Hum, that's not happening here. This might be caused by it loading a different set of DLLs than ND4J, ending up in a conflict. Just for reference, I'm adding the following to `dl4j-examples/nd4j-examples/pom.xml` (the sa_snapshot branch there):
```xml
<dependency>
	<groupId>org.bytedeco.javacpp-presets</groupId>
	<artifactId>mkl-platform</artifactId>
	<version> 2018.1-1.4</version>
</dependency>
```
And the following at the beginning of `main()` in `dl4j-examples/nd4j-examples/src/main/java/org/nd4j/examples/Nd4jEx1_INDArrayBasics.java`:
```
MKLVersion v = new MKLVersion();
MKL_Get_Version(v);
System.out.println("MKLVersion: " + v.MajorVersion() + "." + v.UpdateVersion());
```
Executing on the command line with the following command:
```
mvn -nsu clean compile exec:java -Dexec.mainClass=org.nd4j.examples.Nd4jEx1_INDArrayBasics
```

**Comment by AlexDBlack** [comment]
@saudet OK, so I've created a repo here:
https://github.com/AlexDBlack/mkl_debug

When run through intellij:
```
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 8
o.n.l.c.n.b.CpuBlas - Could not load MKL
java.lang.UnsatisfiedLinkError: no jnimkl_rt in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1226)
	at org.bytedeco.javacpp.Loader.load(Loader.java:980)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Alex\.javacpp\cache\mkl-2018.1-1.4-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jnimkl_rt.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
o.n.n.Nd4jBlas - Number of threads used for BLAS: 8
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [16]; Memory: [7.1GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
About to MMUL
DONE
```

When run through maven (./buildAndRun.sh):
```
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 8
o.n.n.Nd4jBlas - Number of threads used for BLAS: 8
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [16]; Memory: [7.1GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [MKL]
About to MMUL
```
(i.e., deadlocks)

**Comment by AlexDBlack** [comment]
@saudet so I guess re: the non-loading of MKL - this is an intellij-specific issue...
I guess we should look into this more? Want a separate issue (Nd4J? javacpp?)
Here's the intellij run with full logging (and a clean/deleted javacpp cache dir)
https://gist.github.com/AlexDBlack/aca12f6d0a5963875ce9137c2509382e

**Comment by saudet** [comment]
Hum, it's probably related. Let me see if I can't get the loading order of these DLLs straight.

**Comment by saudet** [comment]
I've fixed the loading order of the DLLs in https://github.com/bytedeco/javacpp-presets/commit/2cd4c2c9d9b17a5092f76678fcb9821c73d2fe95 and new binaries for OpenBLAS and MKL have been deployed to the snapshot server. With that I'm not getting any suspicious load failures in the log anymore. But does that make it work better on your end?

**Comment by AlexDBlack** [comment]
Re: IntelliJ MKL loading - unfortunately I'm not seeing any difference with the latest snapshots, when run in IntelliJ:
https://gist.github.com/AlexDBlack/e5160d8ab47771df5ab896d6ced07a0c

I'm pretty sure I'm using the new/correct snapshots - here's the versions from the intellij claspath :

C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\mkl-platform\2018.1-1.4.1-SNAPSHOT\mkl-platform-2018.1-1.4.1-20180317.014046-151.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\mkl\2018.1-1.4.1-SNAPSHOT\mkl-2018.1-1.4.1-20180317.014035-151.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\mkl\2018.1-1.4.1-SNAPSHOT\mkl-2018.1-1.4.1-20180310.210125-145-linux-x86.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\mkl\2018.1-1.4.1-SNAPSHOT\mkl-2018.1-1.4.1-20180310.235418-148-linux-x86_64.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\mkl\2018.1-1.4.1-SNAPSHOT\mkl-2018.1-1.4.1-20180317.010725-150-macosx-x86_64.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\mkl\2018.1-1.4.1-SNAPSHOT\mkl-2018.1-1.4.1-20180316.201239-149-windows-x86.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\mkl\2018.1-1.4.1-SNAPSHOT\mkl-2018.1-1.4.1-20180317.014035-151-windows-x86_64.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\openblas-platform\0.2.20-1.4.1-SNAPSHOT\openblas-platform-0.2.20-1.4.1-20180317.025119-318.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\openblas\0.2.20-1.4.1-SNAPSHOT\openblas-0.2.20-1.4.1-20180317.025105-370.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\openblas\0.2.20-1.4.1-SNAPSHOT\openblas-0.2.20-1.4.1-20180316.175853-361-android-arm.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\openblas\0.2.20-1.4.1-SNAPSHOT\openblas-0.2.20-1.4.1-20180316.184332-362-android-arm64.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\openblas\0.2.20-1.4.1-SNAPSHOT\openblas-0.2.20-1.4.1-20180316.194138-363-android-x86.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\openblas\0.2.20-1.4.1-SNAPSHOT\openblas-0.2.20-1.4.1-20180316.201431-364-android-x86_64.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\openblas\0.2.20-1.4.1-SNAPSHOT\openblas-0.2.20-1.4.1-20180316.210706-365-ios-arm64.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\openblas\0.2.20-1.4.1-SNAPSHOT\openblas-0.2.20-1.4.1-20180316.222156-368-ios-x86_64.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\openblas\0.2.20-1.4.1-SNAPSHOT\openblas-0.2.20-1.4.1-20180310.205816-357-linux-x86.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\openblas\0.2.20-1.4.1-SNAPSHOT\openblas-0.2.20-1.4.1-20180311.001102-360-linux-x86_64.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\openblas\0.2.20-1.4.1-SNAPSHOT\openblas-0.2.20-1.4.1-20180316.214112-367-linux-armhf.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\openblas\0.2.20-1.4.1-SNAPSHOT\openblas-0.2.20-1.4.1-20180316.222602-369-linux-ppc64le.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\openblas\0.2.20-1.4.1-SNAPSHOT\openblas-0.2.20-1.4.1-20180310.211502-358-macosx-x86_64.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\openblas\0.2.20-1.4.1-SNAPSHOT\openblas-0.2.20-1.4.1-20180316.210939-366-windows-x86.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp-presets\openblas\0.2.20-1.4.1-SNAPSHOT\openblas-0.2.20-1.4.1-20180317.025105-370-windows-x86_64.jar
C:\Users\Alex\.m2\repository\org\bytedeco\javacpp\1.4.1-SNAPSHOT\javacpp-1.4.1-20180316.174611-34.jar



Note: now I'm *also* having issues loading MKL (from snapshots) when running this from maven (again in my mkl_debug project via buildAndRun.sh - which I've also updated)
https://gist.github.com/AlexDBlack/fb7924884852e5eb0c33216214a0abd0

**Comment by saudet** [comment]
I'm going to need a way to reproduce this here. This isn't happening on my machine unfortunately.. This looks like there are old version of artifacts of nd4j, openblas, or mkl somewhere in the dependencies. Could you send me an uber JAR that fails and we'll be able to diagnose this more easily?

**Comment by saudet** [comment]
Actually, you definitely have a version of nd4j other than the one in sa_mkl, or an old version of openblas or mkl in your dependencies that is trying to load mkl_avx before mkl_core. You'll need to get rid of that...

**Comment by AlexDBlack** [comment]
Hm, it's possible. I'll rebuild ND4J on sa_mkl to be sure, and report back shortly...

**Comment by AlexDBlack** [comment]
OK, so I've double checked and fixed some things - now I'm sure that (a) I'm no sa_mkl, and (b) my path is correct.

Result: Both Intellij and maven/java -cp are loading MKL correctly.
Both are still deadlocking, however.

**Comment by saudet** [comment]
What happens if you clear the cache, and run with admin privileges?

**Comment by saudet** [comment]
I guess it's going to work because we know it works with symlinks... Could you instead run https://docs.microsoft.com/en-us/sysinternals/downloads/listdlls on the deadlocked java process and let's check that it loads all the DLLs from where we expect it to?

**Comment by AlexDBlack** [comment]
Process:
1. Run test in intellij (deadlocks)
2. Get process ID from task manager
3. ```listdlls64 <pid>```
4. ```listdlls64 -v <pid>```

Results here: https://gist.github.com/AlexDBlack/3af553b3602e08a08e8ddf81725874a7

I haven't looked at the results in detail, but I did notice that the MKL DLLs are listed twice

Also: One thing I didn't notice before is that the process is actually maxxing out one CPU core...
![image](https://user-images.githubusercontent.com/2360237/37553863-0f8580f8-2a24-11e8-8066-7f8909b3e32e.png)

**Comment by AlexDBlack** [comment]
@saudet let me see if I can reproduce this on my other windows machine (similar config - 5930k vs. 5960x for all the above results)... if so, I can probably give you access to that to reproduce/debug.

**Comment by saudet** [comment]
@AlexDBlack Thanks, but don't worry about spending more time on that for now. Loading the exact same DLLs twice in memory is probably causing problems. Windows isn't being helpful here. Let me try to rectify that in JavaCPP first...

**Comment by saudet** [comment]
Ok, this was caused by an old hack that used to work with MKL 2017 but doesn't anymore with MKL 2018, so I've modified it so it doesn't load the same DLL twice like that when making copies into cache. Run `mvn -U ...` to get the latest build of JavaCPP and let me know how that goes!

**Comment by AlexDBlack** [comment]
ok, so I've deleted cache + retried with (what should be) the latest javacpp (javacpp-1.4.1-20180319.083214-35)
Seems like it's only loading the one copy of the DLLs now (just from javacpp cache).
https://gist.github.com/AlexDBlack/51218a79e4fb8e2431e2b34beeb5d0d5

Unfortunately: it still deadlocks both in intellij and when run via java -cp :(

Do you want me to try reproducing it on this other machine I can give you access to?

**Comment by saudet** [comment]
`mkl_core.dll` get loaded twice though. Does this happen with only OpenBLAS? For example with https://github.com/bytedeco/javacpp-presets/tree/master/openblas#sample-usage

**Comment by AlexDBlack** [comment]
Ah, good catch.

Looks like it only loads it once, when just using openblas:
https://gist.github.com/AlexDBlack/fcf173916c451b9e81284c2fd4c2ebc0

**Comment by AlexDBlack** [comment]
ah, I did just realize I'm not on sa_mkl branch for the results of my earlier post - https://github.com/deeplearning4j/deeplearning4j/issues/4776#issuecomment-374148867

**Comment by AlexDBlack** [comment]
Success! Looks like it's only loading mkl_core.dll once
https://gist.github.com/AlexDBlack/6f95f9be21f9ef0e3e59cdb4f0d1d49a

I can confirm that we're no longer seeing deadlocks when run via intellij or java -cp (run 20 times each) . :tada: 👏 

> an old hack that used to work with MKL 2017 but doesn't anymore with MKL 2018

So - at this point, I guess the only remaining question is MKL 2017... do you want to do some testing there to make sure it still works as expected after your changes?

**Comment by saudet** [comment]
It most likely works. Copying everything into a new directory is the safer way, I wouldn't worry about it...
