### ISSUE TITLE
Improper handling of InterruptedExecption

### ISSUE THREAD

**Issue by jentfoo** [deeplearning4j/deeplearning4j#4781]
I noticed in `MultiThreadUtils` that you are catching an InterruptedException but not reseting the status.

https://github.com/deeplearning4j/deeplearning4j/blob/ec2ed9e71f82ccce1c4f16dba9f339c0b61a27f9/deeplearning4j-nearestneighbors-parent/nearestneighbor-core/src/main/java/org/deeplearning4j/clustering/util/MultiThreadUtils.java#L69

By catching the exception the status is cleared, you should re-interrupt the thread before throwing the wrapped exception so that other potentially blocking tasks wont block and prevent things like jvm shutdown.

You may want to reference `Don't swallow interrupts` here: https://www.ibm.com/developerworks/library/j-jtp05236/

**Comment by saudet** [comment]
Sounds good! Could you send a pull request to fix this?
