### ISSUE TITLE
MKL dlls with Anaconda

### ISSUE THREAD

**Issue by turgaybatbat** [deeplearning4j/deeplearning4j#4788]
#### Issue Description
dl4j causes MKL dll error when anaconda(python environment) installed in system. Anaconda is installing mkl dlls automatically but dl4j can't use that dlls correctly.  

#### Version Information

Windows 10 Pro Intel i7 7700

#### Contributing

May be system path added with anaconda (mkl dlls in ProgramData folder) can excluded from search.

**Comment by AlexDBlack** [comment]
@turgaybatbat can you please provide the following:
(a) the full error/exception stack trace that you are getting
(b) the version of DL4J (and ND4J etc) that you are using

@saudet this is something I think we've seen a few times before... any idea (a) why the Anaconda MKL DLLs are problematic compared to the "real" ones (via a manual install), and (b) if there's a quick and easy solution here like filtering/excluding them based on path they reside in?

**Comment by saudet** [comment]
That's most likely fixed. Please try again with 0.9.2-SNAPSHOT.

**Comment by AlexDBlack** [comment]
Closing this - @turgaybatbat we can re-open this if required, if you're still seeing it after upgrading the version.
