### ISSUE TITLE
MKL Error 

### ISSUE THREAD

**Issue by turgaybatbat** [deeplearning4j/deeplearning4j#4789]
#### Issue Description

mkl dll error has shown in usage in anaconda installed computer.

#### Version Information

windows 10 i7 7700

#### Contributing

I have to uninstall anaconda to run dl4j, maybe anaconda path can exclude from search path (programdata folder in windows)

**Comment by AlexDBlack** [comment]
Closing - duplicate of https://github.com/deeplearning4j/deeplearning4j/issues/4788
