### ISSUE TITLE
How to get labels from restored model

### ISSUE THREAD

**Issue by truonghoang** [deeplearning4j/deeplearning4j#4799]
#### Issue Description

 ```
MultiLayerNetwork network = ModelSerializer.restoreMultiLayerNetwork(new File(modelFile));
  network.init();
  INDArray labels = network.getLabels()
```

But I got labels = null

#### Version Information
* Deeplearning4j 0.9.1
* Window 10

#### Contributing
Please tell me how I can keep and get the labels from model which had saved after train

Thanks.

**Comment by saudet** [comment]
The labels are basically part of DataSet. We can reset them with setLabels(). But I agree this needs to be enhanced in one way or another.

**Comment by AlexDBlack** [comment]
Actually, I'm going to close this. The labels array (as in, getLabels()) is a transient field for a single minibatch that is modified/updated on every fit etc method. It's not something that should be persisted with the model in my opinion - I can't see a use case where it makes sense to save/restore the labels INDArray for a single minibatch.

**Comment by truonghoang** [comment]
Because i don't want got results which predict label is index 0 1 2 3 ... .or i must define labels array.
You know i got labels from path by BalancePathFilter. But i will clear data after.so i can't get label accuracy.

Thank

**Comment by saudet** [comment]
@AlexDBlack Sorry, got confused with RecordReader.getLabels(). That's the one we want to save... @truonghoang Please open an issue about that at https://github.com/deeplearning4j/datavec/issues

**Comment by truonghoang** [comment]
No problem.
I found a solution :
  + Train file:
```
 final List<String> allClassLabels = trainReader.getLabels();
 FileUtils.writeLines(new File(path, modelType + "_labels.txt"), allClassLabels);
```
   + Predict file :
`labels = FileUtils.readLines(new File(path, modelType  + "_labels.txt"));`

Thanks.

**Comment by saudet** [comment]
@truonghoang Please send a pull request with that against DataVec! :) Thanks
