### ISSUE TITLE
PreProcessor executed twice in SequenceRecordReaderDataSetIterator

### ISSUE THREAD

**Issue by elie-rachkidi** [deeplearning4j/deeplearning4j#4811]
#### Issue Description

There is an odd behaviour when loading data using `SequenceRecordReaderDataSetIterator` with a normalizer. It seems like the normalizer is applied twice on returned `DataSet` with the method `next()`.

After debugging, I found that the `SequenceRecordReaderDataSetIterator` method `next()` invokes the methods `next(int num)` and `mdsToDataSet(MultiDataSet mds)` in order to fetch data. However both have the following code snippet at lines 333 and 292 respectively:
```
if (preProcessor != null) {
    preProcessor.preProcess(ds);
}
```
I think the normalization operation is executed twice for `SequenceRecordReaderDataSetIterator` instances. I checked other classes which behaved as expected such as `RecordReaderDataSetIterator` and found that the method `next(int num)` does not have the previous code snippet.

#### Version Information

* Deeplearning4j version 0.9.1

#### Contributing

I think the code snippet:
```
if (preProcessor != null) {
    preProcessor.preProcess(ds);
}
```
at line 333 within the method `next(int num)`  in the class `SequenceRecordReaderDataSetIterator` should be removed

**Comment by AlexDBlack** [comment]
Thanks for the report, but this was identified and fixed some time ago:
See here for a workaround: https://deeplearning4j.org/releasenotes#zeronineone
