### ISSUE TITLE
Weight init creates an array with the size of the whole network

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#4815]
#### Issue Description
When training on a GPU, it is easily possible to create a network that _should_ fit into memory, but even just initializing it results in an out of memory state.

I've tracked the problem down to WeightInitUtil, which gets a parameters view, but instead of directly using it, it creates a new one, which is then copied into that view.

This results in the problem that model initialization requires twice as much memory, as is needed to just hold that model.

One could argue that if you don't have enough memory to hold the model twice, it is just too large anyway, but a 6GB model isn't trainable on an 11GB GPU, and that certainly shouldn't be an issue.

#### Version Information

* Deeplearning4j version: 0.9.2-SNAPSHOT
* Windows
* CUDA 8.0

#### Contributing

I've modified WeightInitUtil to use the param view directly like that (Xavier weight init):
```java
Nd4j.getExecutioner().exec(new GaussianDistribution(paramView), Nd4j.getRandom());
paramView.muli(FastMath.sqrt(2.0 / (fanIn + fanOut)));
return paramView.reshape(order, shape);
```

And it seems to work fine. So if there is no reason to keep creating a new array first, I can create a pull request that does the same for all weight init schemes.

**Comment by AlexDBlack** [comment]
> One could argue that if you don't have enough memory to hold the model twice, it is just too large anyway, 

I would definitely argue that :)
Mainly because to train a network, you have parameters + parameter gradients + updater state + activations + activations gradients + working memory
which is by definition greater than 2x parameter size (parameter gradients size == parameters size)

That said, I'm totally in favor of doing this in-place if possible.

**Comment by treo** [comment]
What would be the preferred way of doing this?
Should I create `Nd4j.rand` variants that take a target array, and then use them in WeightInitUtils?

**Comment by AlexDBlack** [comment]
Yeah, I think the cleanest way long term - would be to implement methods where the result array can be passed in/specified. Specifically:
(a) Nd4j.rand(INDArray), Nd4j.randn(INDArray) etc, and also
(b) Distribution.sample(INDArray)
