### ISSUE TITLE
New gradient check failures (CPU)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4818]
Everything was passing last week...

![image](https://user-images.githubusercontent.com/2360237/37635583-87826944-2c50-11e8-8d22-8732311149eb.png)

testLSTMWithSubset seems like non-issue (just over precision limit with small value). Same with YOLO.

However, testDeconvolution2D is a new and legitimate issue.

**Comment by AlexDBlack** [comment]
Looking at this again - I'm getting this printed during execution of testDeconvolution2D gradient check:

```
Error at [C:/DL4J/Git/libnd4j/include/ops/declarable/generic/convo/deconv2d.cpp:243:0]:
CUSTOM DECONV2D_BP OP: wrong shape of gradient_output (next epsilon) array !
```


Given the timing, this is likely due to the deconv2d.cpp changes here: https://github.com/deeplearning4j/libnd4j/pull/825

What specifically is the error in the libnd4j code? This output size calculation looks wrong to me:
https://github.com/deeplearning4j/libnd4j/blob/master/include/ops/declarable/generic/convo/deconv2d.cpp#L241

Here's the DL4J implementation of output size calculation for deconv:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/util/ConvolutionUtils.java#L50-L82
Which is quite different to the output size calculation for pooling/conv layers:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/util/ConvolutionUtils.java#L84-L130



Also - a couple of things I dislike about the current errors here:
1. Not informative enough: if validation/preconditions fail, then IMO the error should provide as much information as possible. In this case, the expected epsilon shape, and the actual epsilon shape should be in the error text
2. This error isn't actually propagated up to the ND4J level. The error occurs, gets logged from C++, and java execution continues on its merry way as if nothing is wrong. I'd much prefer to have an actual java exception occur as a result. But that may be another (larger) discussion

**Comment by maxpumperla** [comment]
@AlexDBlack I agree with both 1. and 2. and I find this discussion to be fairly important. A lot, if not most of the difficulty in debugging new SameDiff ops, for instance, come from this too.

**Comment by maxpumperla** [comment]
Shall we discuss this on basecamp?

**Comment by AlexDBlack** [comment]
Gitter first IMO, if we can't agree on something quickly then we'll move to basecamp.

**Comment by shyrma** [comment]
Hi, guys

Could you please point out where "testDeconvolution2D" is ?
I have to take a look. My first suspicion is that we use different isSameMode/isNCHW (but I can mistake of course)

Concerning 1: Ok, I'll provide corresponding code

Concerning 2: I think it would be better to involve raver into this discussion as well, since usually he how to interact with jave

**Comment by shyrma** [comment]
Hmm, Also I see you use old deconv version
We have to update deconv in master
New one is on my branch  "shyrma_data_format"

**Comment by AlexDBlack** [comment]
@shyrma https://github.com/deeplearning4j/deeplearning4j/search?utf8=%E2%9C%93&q=testDeconvolution2D&type=

It's a gradient check, and runs through multiple cases.
Note that it definitely was passing last week.

> I'll provide corresponding code

Thanks. As a general rule I try to have as much info as possible - my goal is (when possible) to give users/devs enough info so they don't have to run things in a debugger to identify the cause. I note that a number of the other checks/errors there are probably good enough in that respect.

> Also I see you use old deconv version
We have to update deconv in master

Well, if by "old" version you mean "as of a few days ago" then sure :)
The implementation/version before that was (as I noted) 


> My first suspicion is that we use different isSameMode/isNCHW (but I can mistake of course)

Based on the code I linked, it seemed like the problem was that the code uses the output size calculation for *convolutional* layers not *deconvolutional* layers.

**Comment by shyrma** [comment]
>Based on the code I linked, it seemed like the problem was that the code uses the output size >calculation for convolutional layers not deconvolutional layers. 

Yes, it is mistake. However as you may note we use correct calculation on my branch.
https://github.com/deeplearning4j/libnd4j/blob/c4d3a654e2b939aa3024fc86d7252a284b7118b2/include/ops/declarable/generic/convo/deconv2d.cpp#L99

We'll update master, once the remaining work (on conv ops) will be done.

**Comment by AlexDBlack** [comment]
> we use correct calculation on my branch.

Great, thanks. Mind re-running the testDeconvolution2D test and testSeparableConv2D (also seeing new issues there as of last couple of days) at some point to confirm it's fixed?
Or ping me when it's ready and I'll build using your branch and run, if that's easier...
https://github.com/deeplearning4j/deeplearning4j/blob/ff4d5192f33b2c96cdc2212749e023321b0f4e67/deeplearning4j-core/src/test/java/org/deeplearning4j/gradientcheck/CNNGradientCheckTest.java#L819-L957

**Comment by shyrma** [comment]
If you don't mind I would like to finish my work (currently I'm working on sconv) first, it will not take a lot of time. I will inform when it is ready.

**Comment by shyrma** [comment]
Now deconv/sconv are ready,  at least they passes through C++ tests (on Linux).

deconv - https://github.com/deeplearning4j/libnd4j/blob/shyrma_data_format/include/ops/declarable/generic/convo/deconv2d.cpp

sconv - https://github.com/deeplearning4j/libnd4j/blob/shyrma_data_format/include/ops/declarable/generic/convo/sconv2d.cpp

However corresponding pr is failed on Jenkins due to some (unrecognized so far) mistake in sconv2d_bp which reveals itself only on windows and ios (nan-s are produced O_o).
I'm going to find out what's happened tomorrow with more fresh head :-)

**Comment by shyrma** [comment]
Hi, Alex.
Now everything works well and new versions of sconv and deconv are in master branch.

**Comment by AlexDBlack** [comment]
To confirm: no more gemm-related crashes on separable and deconvolutional layers, after building the full stack (master branch) today.

However, I am still seeing some gradient check failures on deconv (again, they were passing before the recent round of changes - say a week or two ago).

```
Error at [C:/DL4J/Git/libnd4j/include/ops/declarable/generic/convo/deconv2d.cpp:161:0]:
CUSTOM DECONV2D_BP OP: wrong shape of gradient_output (next epsilon) array, expected is [1, 2, 10, 10], but got [1, 2, 18, 18] instead !
```

I will look into this more now and work out what's up.

**Comment by AlexDBlack** [comment]
Confirming this as fixed - the other gradient check failures aren't showing up any more (not sure what's up there, but they weren't real issues anyway).

As for Deconv2d: backprop was definitely using the wrong output size calculation still.
I have fixed that here: https://github.com/deeplearning4j/libnd4j/pull/838

**Comment by shyrma** [comment]
Thanks a lot.
I wonder how I missed to replace calcOutSizePool2D on calcOutSizeDeconv2D 
O_o
my apologies
