### ISSUE TITLE
Deeplearning4j vs Tensorflow performance

### ISSUE THREAD

**Issue by up-to-you** [deeplearning4j/deeplearning4j#4828]
Are there any relevant performance benchmarks for current year in comparison to Tensorflow framework ?

**Comment by strelec** [comment]
With the XTU compiler for tensorflow, the speed difference probably is somewhere in the range of 10x.

**Comment by raver119** [comment]
Could you please post actual model, and timing for it?

**Comment by raver119** [comment]
Also: what's XTU?

**Comment by strelec** [comment]
Sorry, meant XLA.

**Comment by raver119** [comment]
I see. Could you please post actual model, and timing for it, and hardware spec?

**Comment by crockpotveggies** [comment]
@strelec can you please post a tensorflow benchmark along with your model config, hardware, etc.? also, what DL4J numbers are you referencing?

**Comment by AlexDBlack** [comment]
I'm closing this.

@up-to-you I'm not aware of any exhaustive DL4J vs. TF benchmarks. Note that both frameworks can make use of CuDNN for the computationally demanding components of deep learning; consequently I wouldn't expect there to be a large difference in most ops, with a recent version of DL4J that is properly configured.
