### ISSUE TITLE
Lombok dependency should not be transitive

### ISSUE THREAD

**Issue by reckart** [deeplearning4j/deeplearning4j#4839]
#### Issue Description

According to https://github.com/rzwitserloot/lombok/issues/1629#issuecomment-376005025 the lombok dependency should not be leaked out as a transitive dependency to code which makes use of DL4J. 

The presence of lombok as a regular dependency exposes the lombok annotation processor to downstream builds which currently causes problems with Java 10. However, as stated in the comment linked above, the problem is more likely a misconfigured lombok dependency in DL4J than an true Java 10 problem.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.9.1

**Comment by agibsonccc** [comment]
We can fix this with the release this week. @saudet thoughts here?

**Comment by saudet** [comment]
@reckart We just need to specify `<optional>true</optional>` on the dependency, right? If that's the only thing, that sounds good to me.

**Comment by reckart** [comment]
@saudet according to @victorwss yes -- I guess it should do the trick, although https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html says that optional is not the best solution. The "provided" scope could be an alternative.

My understanding is that the lombok JAR provides some annotations that you need during the build process but not afterwards (i.e. the annotations probably are not retained at runtime?). It also includes the annotation processor used by the lombok Maven plugin. So if this is the case, then the dependency should not be transitive. "optional" and "provided" should both be means of achieving this.

**Comment by reckart** [comment]
You're welcome! Thanks for the fix!
