### ISSUE TITLE
Conv2D from keras support

### ISSUE THREAD

**Issue by bagolysz** [deeplearning4j/deeplearning4j#4843]
Hi there!

I'm trying to load a pre-trained keras model using DL4J and I get the below exception:
Unsupported keras layer type Conv2D. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.

I understood from previous issues (posted on March 2017 #3105), that Keras 2 was not supported back then. 

I would like to ask, will things change soon, or I better look for another option?

**Comment by agibsonccc** [comment]
Just use snapshots. http://deeplearning4j.org/snapshots (as it says in the other issue)
