### ISSUE TITLE
Backword compatibility of RNN regression is broken in 0.9.1 (compared to 0.7.2)

### ISSUE THREAD

**Issue by tartrout** [deeplearning4j/deeplearning4j#4844]
#### Issue Description

Prerequisites. Download the well known oreilly-book-dl4j-examples (https://github.com/deeplearning4j/oreilly-book-dl4j-examples/blob/master/dl4j-examples/)

Step 1. Build the oreilly-book-dl4j-examples (deeplearning4j Version 0.7.2 is stated in pom.xml). Run MultiTimestepRegressionExample example class. It works like a charm - the predicted data is very close to test one (see screenshot 2).

Step 2. Change version of deeplearning4j and nd4j to 0.9.1 in parent pom.xml. Run MultiTimestepRegressionExample example class. 

Expected: the same chart as on screenshot 1. 

Observed: The prediction is far from ideal (the predicted line looks horizontal, however the debugging shows that it's not exact constant but something very close, see screenshot 1) 

RNN regression seems to be broken in 0.9.1. I've found it initially in my own code - but now I see the examples code doesn't work as well. Good luck reproducing and fixing (and let me use this opportunity to say thank you for your great job).
![screenshot2](https://user-images.githubusercontent.com/31399884/37907612-4d0e649e-310e-11e8-92f7-45c286b6c8f1.png)
![screenshot1](https://user-images.githubusercontent.com/31399884/37907614-4d3387b0-310e-11e8-841d-75de73e08989.png)

#### Version Information

* Deeplearning4j version 0.9.1
* platform information (OS, etc) Windows 10, bare CPU
* CUDA version, if used - not used
* NVIDIA driver version, if in use - not used

**Comment by agibsonccc** [comment]
Closing this, I highly doubt this is actually a problem in practice. I can't even tell how to reproduce this (no code) You can try snapshots to see what it does, but beyond that we'd need more details. I highly doubt it's "broken" this seems really arbitrary given there's more than enough folks who have done fine with it even on 0.9.1
