### ISSUE TITLE
dl4j installation issues

### ISSUE THREAD

**Issue by sjaiswal25** [deeplearning4j/deeplearning4j#4845]
#### Issue Description
running the mvn clean install throws errors.

Please describe our issue, along with:
- expected behavior
![dl4j](https://user-images.githubusercontent.com/37173657/37908249-45df1a4e-3125-11e8-8ef7-b491c2fef865.png)

- encountered behavior

#### Version Information 

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 0.9.1
* platform information (OS, etc) ubuntu 17.04
* CUDA version, if used 9.0
* NVIDIA driver version, if in use 384.84

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!
I would like some assistance on how to fix the issue. I have also tried using intellij idea for running the same. I get the error as shown in screenshot "idea.png"
![idea](https://user-images.githubusercontent.com/37173657/37908514-2110f6dc-3126-11e8-9d73-735822b1b620.png)

**Comment by tomthetrainer** [comment]
Hi @sjaiswal25 , 

So you are doing an install of our examples, with no modification to the pom.xml ? 

Or did you modify the pom.xml for cuda use? 

What version of maven? 

Java 8?

**Comment by raver119** [comment]
Yes, for first screenshot - we need to know maven/java versions.

For second screenshot - project should imported into intellij as maven project.

**Comment by sjaiswal25** [comment]
I have done no modification to the pon.xml file. I have cuda 9.0 installed.

Regards
Shubham Jaiswal

**Comment by sjaiswal25** [comment]
I am using Java 9.0.4 and maven 3.5.0
I have used the instructions as told in the tutorials for using dl4j with
intellij. I imported the project as a maven project.

Regards,
Shubham Jaiswal

**Comment by raver119** [comment]
I see. Please try Java 8 instead.

**Comment by sjaiswal25** [comment]
Ok. For cuda 9.0 what modifications must I make?

Regards,
Shubham Jaiswal

**Comment by raver119** [comment]
Get it running on CPU first.

**Comment by sjaiswal25** [comment]
Here. Sure.Thanks a lot.

Regards
Shubham Jaiswal

**Comment by sjaiswal25** [comment]
It worked with Java 8. Thanks again.
 How to make it working with cuda 9?

Regards,
Shubham Jaiswal

**Comment by tomthetrainer** [comment]
To switch from CPU to GPU see this document, 

https://deeplearning4j.org/gpu

If that works, please close this issue. 

If not let us know the details.

**Comment by raver119** [comment]
Unfortunately you can't use CUDA 9 with dl4j 0.9.1. You'll have few options:
- Use snapshots, CUDA 9 and 9.1 are supported there
- Downgrade to CUDA 8 and use dl4j 0.9.1
- Wait for next release, which should be available soon

**Comment by sjaiswal25** [comment]
Thank you. I will try them.

Regards,
Shubham Jaiswal
