### ISSUE TITLE
exception when import CuDNNLSTM (keras) model to DL4J

### ISSUE THREAD

**Issue by veerapatyok** [deeplearning4j/deeplearning4j#4849]
I have exception when import CuDnnLSTM h5 and json file from keras into DL4J

> UnsupportedKerasConfigurationException: DL4J EmbeddingLayer includes bias but Keras Embedding does not

this is my code
```
val h5 = ".../model_CuDNNLSTM_test_opt.h5"
val json = .../model_CuDNNLSTM_test_opt.json"
val netword = KerasModelImport.importKerasSequentialModelAndWeights(json, h5)
```
DL4J version 0.9.1

**Comment by maxpumperla** [comment]
this has been fixed some time ago, you find this in 0.9.2-SNAPSHOT (we try to have a release this week as well)
