### ISSUE TITLE
Question for evaluation technique for RecurrentLSTMMnistExample

### ISSUE THREAD

**Issue by ckddyd777** [deeplearning4j/deeplearning4j#485]
Hi, I've done build all projects and run a RecurrentLSTMMnistExample.
But, I can't find how to evaluate this model. This model looks calculating score at each iterations.
Last of RecurrentLSTMMnistExample source code's comment is : "Generative model - unsupervised and its time series based which requires different evaluation technique". 
Is this comment means. "you have to implement part of evaluation"?

Thanks.

**Comment by agibsonccc** [comment]
This example has been deleted. Please use the shakespeare example (evaluate it visually)
