### ISSUE TITLE
Received mask array with shape [miniBatchSize, maxLength]; expected vector.

### ISSUE THREAD

**Issue by Ritaplfigueiredo** [deeplearning4j/deeplearning4j#4873]
#### Issue Description

Using the CnnSentenceDataSetIterator with data from http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz, trying to apply a CnnToRnnPreProcessor I get the following error:

- Received mask array with shape [miniBatchSize, maxLength]; expeced vector.

#### Version Information
* Deeplearning4j version: 0.9.1

**Comment by saraswat40** [comment]
Hello,

I ran this - CnnSentenceClassificationExample - with GoogleNews-vectors-negative300.bin.gz downloaded from here: https://drive.google.com/uc?id=0B7XkCwpI5KDYNlNUTTlSS21pQmM&export=download. If you are doing something else, could you please provide steps to reproduce this issue?

Thanks

**Comment by AlexDBlack** [comment]
Right, the unmodified example runs as expected. Furthermore, there isn't any reason to use a CnnToRnnPreProcessor with a CNN configuration. Unless the goal is to use it as input for a RNN instead (note the iterator was never designed for that).

Note that we have a RNN + Word2Vec example here:
https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/word2vecsentiment/Word2VecSentimentRNN.java

I'll close this for now - but if you are still stuck on this @Ritaplfigueiredo feel free to post more information and I'll re-open this issue.
