### ISSUE TITLE
Docs: fix links to iterator source after source reorganization

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4884]
Links here are broken due to recent reorganization:
https://deeplearning4j.org/quickref#data-iter-util

**Comment by crockpotveggies** [comment]
Thanks for submitting this issue. We've migrated our docs to its own separate repository at [deeplearning4j-docs](https://github.com/deeplearning4j/deeplearning4j-docs). I've already migrated your issue and you can find it at https://github.com/deeplearning4j/deeplearning4j-docs/issues/10. 

I'll be closing this, but feel free to comment and re-open if this is not what you intended.

*This was an automatically generated response.*
