### ISSUE TITLE
Restoring a model from the class path of an uberjar fails

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#4887]
I'm trying to load a model from the classpath of an uberjar, and I think https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/util/ModelSerializer.java#L825 is wrong, as the available() method always returns 0 there

Yet if I forcibly fill a BufferedInputStream (via calling the private fill method), if works fine. So this method of checking if data is readable isn't suited for this usecase I think.

That is with current snapshots.

**Comment by AlexDBlack** [comment]
Fixed here by removing the method for now: https://github.com/deeplearning4j/deeplearning4j/pull/4889
