### ISSUE TITLE
Convolution1DLayer looking for dimension 2 for rank 2 NDArray

### ISSUE THREAD

**Issue by topinju** [deeplearning4j/deeplearning4j#4892]
#### Issue Description
Hi, i am trying to use Convolution1DLayer and Subsampling1DLayer with a dataset.
The dataset is made from a CSV file with 100 rows (examples) and 40 columns, the last columns contain the label : 0 or 1.
The dataset is split in training data (80%) and test data(20%).

- encountered behavior : 
While using this layer :
                .layer(0, new Convolution1DLayer.Builder()
                		.nIn(1)
                		.nOut(1)
                		.kernelSize(3)
                        .stride(1)
                        .convolutionMode(ConvolutionMode.Same)
                        .activation(Activation.IDENTITY)
                        .build())
I get the following error : Invalid size: cannot get size of dimension 2 for rank 2 NDArray (array shape: [80, 40])

#### Version Information
* Deeplearning4j version : 0.9.1
* platform information : windows 7 ultimate 64 bits
* CUDA not use

I am new in machine learning, maybe i have done something wrong with the dataset.
Thanks for your help.

**Comment by raver119** [comment]
But Conv1D expects 3D input...

**Comment by topinju** [comment]
Thanks raver, i saw the other issue but it look like it was before the update with conv1d layer.
Have you got an example of a working Convolution1DLayer with a dataset ?
Should i try to transform my time series to a 3D input ?

**Comment by raver119** [comment]
There should be something in tests. And yes, you MUST feed conv1d with 3D input, that's what i've said above.
