### ISSUE TITLE
DL4J helper code for spark-ml only supports pre-spark 2.0 classes

### ISSUE THREAD

**Issue by idc101** [deeplearning4j/deeplearning4j#4893]
#### Issue
Overall goal is to train a model using a Spark DataFrame (i.e. data is in Hive)
To convert a Spark DataFrame to dl4j DataSet there are some helper methods in 
`org.deeplearning4j.spark.util.MLLibUtil`. Specifically these convert a `RDD<LabeledPoint>` to a DataSet.

However the `LabelledPoint`used is `org.apache.spark.mllib.regression.LabeledPoint` which is for Spark pre 1.x. In Spark 2.0+ this was moved to: `org.apache.spark.ml.feature.LabeledPoint`

#### Expected behaviour:
There is a `MLLibUtil2` (or maybe the entire `dl4j-spark` has a second version` referencing the Spark 2.0+ classes.

#### Version Information

* Deeplearning4j version - 0.9.1

Happy to post a small example to GitHub if that helps.

**Comment by saudet** [comment]
We can add a few more "facades" for that, like there is for DataFrame here:
https://github.com/deeplearning4j/DataVec/blob/master/datavec-spark/src/main/spark-1/org/datavec/spark/transform/DataRowsFacade.java
https://github.com/deeplearning4j/DataVec/blob/master/datavec-spark/src/main/spark-2/org/datavec/spark/transform/DataRowsFacade.java
What do you think?
