### ISSUE TITLE
Multi-GPU MNIST example issue with 2 GPUs and FP16 (no CuDNN)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4897]
Looks like I'm getting 0 scores, all values predicted as 0 on FP16.
FP32 is fine.

Test machine:
Kubuntu 17.10
GTX970 x2, CUDA 9.1
Verson: 1.0.0-alpha (RC)

Logs: https://gist.github.com/AlexDBlack/4055ed710f82ee1754865ed9a8259902

**Comment by raver119** [comment]
:/

**Comment by raver119** [comment]
Is it reproducible with 1 GPU as well?

**Comment by AlexDBlack** [comment]
Yeah. 0 scores if I do export ```CUDA_VISIBLE_DEVICES=0``` first.

**Comment by raver119** [comment]
Fixed quite a while ago.
