### ISSUE TITLE
Save/Restore does not persist ADAM updater correctly

### ISSUE THREAD

**Issue by SimpleBrainCell** [deeplearning4j/deeplearning4j#4898]
## Issue Description
1) Train network with Adam updater with 10000 examples
2) Save network with `ModelSerializer.writeMode(model, location, true)`
3) Load network and run some validation examples, learning happened, validation succeeds
4) Start again, train the network with the same 10000 examples but saving and restoring every 1000 examples
5) Load the network, run some validations, learning was very poor, the validation fails.

## Expected Behaviour
The network should end up the same when training 10000 examples in a row, or when training 1000, save, load, train another 1000, etc...

## Version and environment  Information
Deeplearning4J version 0.9.1
Network:
Layers: 7
Layers config: 7x14x14x14x14x5x1
Activations: Tanh, except last is Identity
Learning rate: 0.001

## Contributing

More than happy to fix this if provided some guidance on where to look for the bug

**Comment by SimpleBrainCell** [comment]
I also tried with version 1.0.0-alpha, with the same results.

**Comment by AlexDBlack** [comment]
Can you provide the exact code you are using, so we can reproduce this bug?
I *might* be able to code something up to reproduced it based on your description, but if it's specific to your data, environment, or the way you are using ModelSerializer etc that might not be sufficient to reproduce it.

**Comment by SimpleBrainCell** [comment]
Sure, no problem, I will work on the simplest piece of code that reproduces the problem.

**Comment by SimpleBrainCell** [comment]
Tried to reproduced the problem in a simple example, but could not, works as expected.

It must be an issue on my main code.

Thanks

**Comment by AlexDBlack** [comment]
No worries, thanks for letting us know.
If you do manage to reproduce it (especially with 1.0.0-alpha) I'd be happy to take a look.
