### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by Wangmoubo1993** [deeplearning4j/deeplearning4j#4902]
#### Issue Description

Recent I want to use dl4j to rebuild a Python Project in [https://github.com/chengstone/movie_recommender](url)
but I have a question , Whether I can control the input and output size of the matrix ? if I can ,I want to know in which way I can do it.

and another question is whether the product  of  `nIn()` and `nOut()` is the scale of NN.

Thanks.

**Comment by agibsonccc** [comment]
Please read the basic dl4j docs first and come back with a more concrete question. So far, all I'm seeing is lack of effort  here ;/
