### ISSUE TITLE
Various questions regarding new 1.0.0-alpha release

### ISSUE THREAD

**Issue by enragedginger** [deeplearning4j/deeplearning4j#4903]
Hello,

I'm very excited about the 1.0.0 release. I use DL4J from Clojure via [jutsu.ai](https://github.com/hswick/jutsu.ai) and decided to work on upgrading that library to support the 1.0 release. I ran into a few snags that I couldn't find documented in the release notes / migration guide. Any help would be appreciated.

1. Where did RBMs go? I found a commit that said "Remove RBMs" from back in November, but I don't know why they were removed or what I should use in their place.
2. What happened to the `iterations` (int) and `regularization` (boolean) on `NeuralNetConfiguration`?
3. Where did `biasLearningRate` go to? Is that part of the updaters now or possible the schedules?

-Stephen

**Comment by agibsonccc** [comment]
@enragedginger we got rid of RBMs because they weren't being maintained in the first place.

Iterations is gone because  it also wasn't being used anyways. People use for loops.
Regularization is also implicit now.

And yes, all of the learning rates got moved in to the updaters.

**Comment by enragedginger** [comment]
That's good to know. Some of the code I was updating had tests that were using RBMs so I'll just swap those out with VAEs. I really haven't used them myself. I was just curious what the alternative was these days. As for the iterations and regularization parameters, I figured that was the case. All of the DL4J examples I read were setting iterations to 1 anyways, and regularization felt like a silly parameter too.

Thanks for responding quickly.

-Stephen

**Comment by enragedginger** [comment]
@AlexDBlack Yeah, thanks for that. I had read through that whole page last night up until the Arbiter section. I was focused on / excited about so many of the changes there that I must have completely  missed the three lines that very clearly state `.iterations(int) method has been removed (was rarely used and confusing to users)` and `.regularization(boolean) config removed; functionality is now always equivalent to .regularization(true)` and still `RBM (Restricted Boltzmann Machine) layers have been removed entirely. Consider using VariationalAutoencoder layers as a replacement `
