### ISSUE TITLE
debug output too much log information of detail processes

### ISSUE THREAD

**Issue by mengmengmengmeng1234** [deeplearning4j/deeplearning4j#4907]
Hi:
Now, I have a question . Our project has been applied to your project. And when we debug the program, the debug output will print all detail processes of the program as show in the figure. 
![image](https://user-images.githubusercontent.com/26961818/38477305-721ebece-3be4-11e8-9769-3d50698105bc.png)
In the program, we just use parts of deepleaning4j for classify, as shown in yellow line. Did you do something about logger output in somewhere? If we want to don’t output the detail process,  how should we do ? Thanks.

deepleaning4j version:0.8.0
windows 7

**Comment by saudet** [comment]
The log level is a setting in *your* application. For example, dl4j-examples uses Logback and can be configured with this file: https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/resources/logback.xml
