### ISSUE TITLE
Inconsistent RecordReader listeners invocation

### ISSUE THREAD

**Issue by HDouss** [deeplearning4j/deeplearning4j#4909]
While trying to execute the `MnistImagePipelineExample`, I encountered some inconsistent behavior. The first time a record is read `DataSetIterator` delegates to `ImageRecordReader` to load a first record and then builds a `RecordReaderMultiDataSetIterator` that will be used for further readings. During that build, the `ImageRecordReader` is reset.

The problem appears when attaching a listener to the `ImageRecordReader`. The first time a record is read, the listeners are invoked, but this call is somehow useless because the `ImageRecordReader` is reset anyway. On further "batch" record readings, the listeners are not invoked at all.

Expected behavior is that the listeners are invoked when a record is actually and usefully read.
Encountered behavior is that:
* the listeners are invoked during the first record read that was not an actual data read but used only to build RecordReaderMultiDataSetIterator (`BaseImageRecordReader.next` method)
* the listeners are never invoked for further records "batch" readings (`BaseImageRecordReader.next(int num`) method)

Deeplearning4j version : 0.9.1

**Comment by saudet** [comment]
Does this still happen with 1.0.0-alpha?

**Comment by HDouss** [comment]
@saudet I did not tested it but judging by the code, it is still the case. Maybe this issue should have been opened in DataVec repo.

**Comment by saudet** [comment]
Yes, please reopen in the repo for DataVec, ideally as a pull request with a new unit test failing :) Thanks!
