### ISSUE TITLE
How to fine tune word embeddings as part of training 

### ISSUE THREAD

**Issue by mobiusinversion** [deeplearning4j/deeplearning4j#4910]
#### Help with the concept of fine tuning word embeddings

Hello, this question / request for clarification is motivated by a feature in keras, namely, how to fine tune word embeddings as part of training.  

For example, in python we might have something like this:
  
Get the GoogleNews word vector embedding:

    WORD2VEC_MODEL = "../data/GoogleNews-vectors-negative300.bin.gz"
    load word2vec model
    word2vec = KeyedVectors.load_word2vec_format(WORD2VEC_MODEL, binary=True)
    embedding_weights = np.zeros((vocab_sz, EMBED_SIZE))
    for word, index in word2index.items():
        embedding_weights[index, :] = word2vec[word]    

Then when we create our network, we can use the weights of the embedding and fine tune it for our task:

    model = Sequential()
    model.add(Embedding(vocab_sz, EMBED_SIZE, input_length=maxlen,
                    weights=[embedding_weights],
                    trainable=True))

How can something like this be accomplished in DL4J?

**Comment by AlexDBlack** [comment]
Assuming the vocab size is the same, it should be possible to do the following:

```
WordVectors wordVectors = WordVectorSerializer.readWord2VecModel(new File(WORD_VECTORS_PATH));
net.getLayer(0).getParam("W").assign(wordVectors.lookupTable().getWeights());
```
That's assuming a MultiLayerNetwork with an EmbeddingLayer as the first layer.

In theory you can then go the other way once you're done with training.

Eventually we'll add a way to do it in one step (without the extra memory overhead) but that should do what you want for now.

I'll close this - but we can re-open if you run into any issues.

**Comment by mobiusinversion** [comment]
Cool @AlexDBlack, I'll give this a shot and get back to you.  Thanks!
