### ISSUE TITLE
How to have a shared embedding layer?

### ISSUE THREAD

**Issue by mobiusinversion** [deeplearning4j/deeplearning4j#4914]
#### Issue Description

Question, how do we create shared weight embeddings in DL4J?  For example, in Keras we can do the following with the functional API:

    input_target = Input((1,))
    input_context = Input((1,))
    embedding = Embedding(vocab_size, embed_size, input_length=1, name='embedding')
    target = embedding(input_target)
    context = embedding(input_context)

This creates shared weights between the input and context layers (this is a word2vec style model).  Is there a way to do this in DL4j?  Thanks!

**Comment by AlexDBlack** [comment]
We do have plans to add parameter sharing for layers (with a nice/proper API) at some point in the future.
In the mean time, you can use a set of stack/unstack vertices, which should give you identical results to parameter sharing:
https://github.com/deeplearning4j/deeplearning4j/blob/6335b5e933f13d2bdb5c1f7e5896c45eb96839d7/deeplearning4j-core/src/test/java/org/deeplearning4j/nn/graph/graphnodes/TestGraphNodes.java#L295-L304

In that unit test, both inputs are passed through the same embedding layer.
That should be all you need (so I'll close this) but feel free to post again if you run into issues.
