### ISSUE TITLE
How to have an input_length for Embedding layers?

### ISSUE THREAD

**Issue by mobiusinversion** [deeplearning4j/deeplearning4j#4915]
#### Issue Description

Hello, I am studying DL4J embedding layers and I have a question about the length of input sequences.  In Keras (sorry for the cross-referencing), we can do this:

    inputs = Input(shape=(32, ))
    embedding = Embedding(max_features, 128, input_length=32)(inputs)

The output will be a 2D matrix with shape (32, 128).  How do we do this in DL4J?

**Comment by maxpumperla** [comment]
@mobiusinversion we don't support this (yet). I'll have a look at Embedding layers for import soon.

**Comment by AlexDBlack** [comment]
I should add that if you are using time series inputs (not sure if that's what you want here), you can do .setInputType(InputType.recurrent(x)) and it'll work in a time distributed manner.

**Comment by maxpumperla** [comment]
@AlexDBlack  @mobiusinversion exactly, so in principle we can already do this, but I have to tell our import module to translate Keras' `input_length` argument into a recurrent `InputType` with time series length equal to `input_length`.

**Comment by mobiusinversion** [comment]
Thanks much for having a lock @AlexDBlack @maxpumperla.  Recurrent, and time series.  My understanding is that recurrent implies hidden state. My understanding of [what is happening in Keras embeddings](https://github.com/keras-team/keras/issues/3110) is that these embeddings are IID, with no shared state between them.  In this way, an embedding of 5 integers with a max value of 40, into 2 dimensions, becomes a 5 x 40 one hot matrix which then is embedded into a 5 x 2 matrix, which can then be used by a CNN to do classification (without state between classifications, just a typical feedforward design).   Does this sound right to you?  Your thoughts?

**Comment by maxpumperla** [comment]
@mobiusinversion this is fixes now with #4899.

If you have input_length = x and minibatch size = mb then keras will embed an input of shape (mb, x) into (mb, output_dim, x) where the input entries are labels from a vocabulary of size input_dim.

**Comment by mobiusinversion** [comment]
Thanks @maxpumperla & @AlexDBlack!

**Comment by mobiusinversion** [comment]
@maxpumperla, however, I was wondering, can we do this directly in DL4J without Keras import?  That's what I was mainly interested in, plus supporting Keras 2.0 is fantastic.
