### ISSUE TITLE
Too much memory usage / inefficiency with doc2vec and large vocabularies

### ISSUE THREAD

**Issue by rothn** [deeplearning4j/deeplearning4j#4918]
#### Issue Description

Training doc2vec on a vocabulary of 202792035 words caused the dictionary-building (for word lookup) and huffman-code-building (for hierarchical softmax) to be way slower than they needed to. Most of the time was spent within the JVM unnecessarily copying things around in the most inefficient ways possible (e.g. initializing a cache with a for loop over dictionary keys without reserving capacity ahead of time, slowly building a HashMap (wrong data structure for large scale) with the JVM reallocating everything and doing massive GCs, etc.).

There should be some sort of optimized, off-heap implementation of these data structures. The stuff using INDArrays works fine, but that's not where the pain point is here (at least not anymore).

#### Version Information

* Deeplearning4j 0.9.1
* Windows 10
* Parallel dictionary building turned off
* No CUDA
* Vector size of 300

**Comment by apatzer** [comment]
Tend to agree here. With hierarchical softmax turned on, serialized `ParagraphVectors` are 2x larger than without...seems rather inefficient for Huffman codes.

**Comment by raver119** [comment]
I'm afraid original issue has nothing to do with the size of serialized model. Negative sampling and hierarchic softmax add additional matrix to model, with size of `numWords` x `layerSize`. So it's kind of expected to have bigger file if you use both options for some reason.
