### ISSUE TITLE
OOM on dl4j-benchmark

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#4925]
#### Issue Description

Attempting to run dl4j-benchmark using a VGG-16 model. It fails with the following OOM:

https://gist.github.com/crockpotveggies/3cb45360376e55fe87fe8fe5a75162e2

#### Version Information

Please indicate relevant versions, including, if relevant:

* v1.0.0-SNAPSHOT
* CUDA 9.1 Titan X GPU
* Using new profiels for `v100snapshot`,`cuda91`, and `cudnn91`

#### Contributing

@AlexDBlack related to recent workspace changes?

**Comment by saudet** [comment]
Is cuDNN running with NO_WORKSPACE?

**Comment by saudet** [comment]
That just means `deeplearning4j-cuda` isn't in the `pom.xml` file. 

@AlexDBlack is actually working on optimizing memory right now (see issue #4784). 
This issue should also get fixed after that's done.

**Comment by crockpotveggies** [comment]
It definitely seems to be there: https://github.com/deeplearning4j/dl4j-benchmark/blob/master/pom.xml

And confirmed I have the appropriate profiles enabled:
![screen shot 2018-04-13 at 11 50 13 am](https://user-images.githubusercontent.com/1445295/38752652-dab636b8-3f10-11e8-8fc1-7e6668dfe8f6.png)


@AlexDBlack these recent changes are yours, am I using them correctly?

**Comment by AlexDBlack** [comment]
Closing this, looks like a legitimate OOM. With some minibatch sizes it's certainly possible to get this.

And yes, I'm working to optimize memory now, nearly done: https://github.com/deeplearning4j/deeplearning4j/pull/4900
Not much point worrying about memory or OOMs until that's merged.
