### ISSUE TITLE
Implemented AlphaGo by using DL4j and performance issue

### ISSUE THREAD

**Issue by johnhuang-cn** [deeplearning4j/deeplearning4j#4928]
I implemented AlphaGo by using DL4j 0.9.1, https://github.com/johnhuang-cn/FancyBing. 

The performance is comparable to other DL framework, but still not good enough. Because of the memory(gc?) issue of DL4j, if I put network evaluation with MCTS search together, the evaluation performance would be very poor. So I separate policy network evaluation and MCTS search into 2 projects, then call network evaluate through RMI. Such architecture solve the network evaluation performance issue, but a little slow down the MCTS search speed.  

Another problem is if I attach UI during the training, the performance would gradually decrease after long time training.

I want to know if such issues solved in 1.0.0?

Thanks,
John Huang

**Comment by agibsonccc** [comment]
@johnhuang-cn that's great! Let's see what we can do to help you. Could you tell us in more detail what the actual problems are? What have you tried running on? What are "performance problems"?

**Comment by johnhuang-cn** [comment]
I remember someone have reported similar issue last year, but I can't find it now.

The problem is if network evaluation running in a project that with many objects creating and recycling, the network evaluation would be very poor. This issue was marked as GC issue before 0.9.0, I have commented to the issue, I will try finding it.

So, now I solved it by separate the network evaluation and other codes into 2 projects, that network and other codes would run in 2 separate JVMs, the network evaluation will be called through RMI. In such architecture, performance of each projects would be good enough. But the RMI call is through TCP/IP, it has some wastage of performance, it is about 20%.

I'm not sure if DL4j solved the GC issue in new version 1.0.0, I didn't find such description in the release notes. Or if exists other tips to solve it.

Thanks,
John Huang

**Comment by agibsonccc** [comment]
There's workspaces; http://deeplearning4j.org/workspaces - if that doesn't work, maybe consider giving us a profile dump on where time is spent. Workspaces have been available since 0.9.1 though..I would just consider double checking the basics first.

Thanks for checking with us John!

**Comment by raver119** [comment]
Also keep in mind - in 0.9.1 workspaces were not enabled by default. So you'll need to follow instructions available at the link Adam posted for you.

**Comment by johnhuang-cn** [comment]
I saw the article before and already trained it with workspace.single, see https://github.com/johnhuang-cn/FancyBing/blob/master/fancybing-train/src/main/java/net/xdevelop/go/train/ResNetwork.java#L60

Do you mean if the network is build with WorkspaceMode.SINGLE, it won't has GC issue when calling model.output()? But the article says "The only exclusion is the output() method that uses workspaces (if enabled) internally for the feed-forward loop. " Does it means it only solved the GC issue during the training phase, but not the evaluate phase in product env.
