### ISSUE TITLE
Add U-net to model zoo

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#4929]
#### Issue Description

https://lmb.informatik.uni-freiburg.de/people/ronneber/u-net/

Currently some weights appear to be available on OSS:

- https://github.com/ZFTurbo/ZF_UNET_224_Pretrained_Model GPL v3

#### Version Information

v1.0.0-SNAPSHOT

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by saudet** [comment]
Weights licensed under GPL??

**Comment by crockpotveggies** [comment]
Hmm I thought GPL v3 would be compatible but I'm wrong. I'll keep looking.

**Comment by holgerbrandl** [comment]
Is there a publicly available implementation of the unet using dl4j API?

**Comment by crockpotveggies** [comment]
Not currently aware of a DL4J model configuration, but I can probably whip this up. I'm making some adjustments to zoo API and may bundle in the work.

**Comment by holgerbrandl** [comment]
We have multiple research groups at my site working with (keras) u-nets, I'm sure some are willing to contribute weights weights under any license we like. But of what use are the weights if there is no dl4j-implementation to configure it with? Or would the `KerasModelImport` be ready as it is to read in the weights?

**Comment by maxpumperla** [comment]
@holgerbrandl this works in principle, although we have this issue to resolve first https://github.com/deeplearning4j/deeplearning4j/issues/4534, tldr: conv layer as last layer causes problems right now. will let you know once this is resolved.

**Comment by crockpotveggies** [comment]
Follow progress on this PR and commit here: https://github.com/deeplearning4j/deeplearning4j/pull/4985/commits/5cc1e5c422cf6341585be66b51691db7495cd66d

**Comment by crockpotveggies** [comment]
I trained my own version of U-Net on synthetic data on a slightly different configuration. Weights are available under the `PretrainedType.SEGMENT` enum. Hopefully that avoids any license issues. Closing this.
