### ISSUE TITLE
Possble workspace issue: ScaleVertex outputs zeros in ComputationGraph with 4D input

### ISSUE THREAD

**Issue by DrChainsaw** [deeplearning4j/deeplearning4j#4931]
#### Issue Description

As title says. Problem is encountered when calling ComputationGraph.output(INDArray... inputs) (or  outputSingle).

If any of the ComputationGraph.feedforward methods are called before calling output then results are as expected.

If workspace mode is set to NONE results are as expected (separate or single fails).

If 2D input is used results are as expected. 

Testcase which triggers the error:

        @Test
    public void scaleVertexGraphTest() {
        final double scaleFactor = 2;
        final double[] inputArr = IntStream.rangeClosed(-2, 2).mapToDouble(i -> i).toArray();
        final double[] expected = DoubleStream.of(inputArr).map(i -> i * scaleFactor).toArray();

        final INDArray input = getInputArray4d(inputArr); // Replacing this line with the line below is enough to make test pass
        //final INDArray input = Nd4j.create(new double[][]{inputArr});

        final String inputName = "input";
        final String outputName = "output";
        final String scaleName = "scale";
        final ComputationGraph graph = new ComputationGraph(new NeuralNetConfiguration.Builder()
                //.inferenceWorkspaceMode(WorkspaceMode.NONE) // Uncommenting this line is enough to make test pass
                .graphBuilder()
                .addInputs(inputName)
                .setOutputs(outputName)
                .setInputTypes(InputType.inferInputType(input))
                .addVertex(scaleName, new ScaleVertex(scaleFactor), inputName)
                .addLayer(outputName, new OutputLayer.Builder()
                        .activation(new ActivationIdentity())
                        .nOut(input.length())
                        .biasInit(0)
                        .build(), scaleName)
                .build());
        graph.init();

        //graph.fit(new DataSet(input, Nd4j.ones(input.length()))); // Does not help
        //graph.feedForward(new INDArray[] {input}, false); // Uncommenting this line is enough to make test pass

        //Hack output layer to be identity mapping
        graph.getOutputLayer(0).setParam("W", Nd4j.eye(input.length()));
        graph.getOutputLayer(0).setParam("b", Nd4j.zeros(input.length()));
        assertEquals("Incorrect output", Nd4j.create(expected), graph.outputSingle(input));
    }

    @NotNull
    private static INDArray getInputArray4d(double[] inputArr) {
        final INDArray input = Nd4j.create(1, 1, inputArr.length, 1);
        for (int i = 0; i < input.length(); i++) {
            input.putScalar(new int[]{0, 0, i, 0}, inputArr[i]);
        }
        return input;
    }

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-alpha
* platform information:  windows 10
* CUDA version: 8.0 
* NVIDIA driver version: 388.13

#### Contributing

Would love to help, but the workspace magic is outside of my comfort zone. If you think you can point me to something I'll give it a shot.

**Comment by AlexDBlack** [comment]
Thanks for reporting. FYI workspaces are getting overhauled here: https://github.com/deeplearning4j/deeplearning4j/pull/4900
I'll wait until that's complete (today or tomorrow) before looking into this.

**Comment by AlexDBlack** [comment]
I can confirm that I was able to reproduce this issue, and that it is fixed on the following (soon to be merged) PR: https://github.com/deeplearning4j/deeplearning4j/pull/4900
I've added your code as a new unit test to that branch, and will close this as resolved.
Thanks again for the issue.
