### ISSUE TITLE
Cannot train a model with a ParallelWrapper on a Linux machine.

### ISSUE THREAD

**Issue by localmaxima** [deeplearning4j/deeplearning4j#4932]
#### Issue Description
Using ParallelWrapper while training a model on a machine that has two Nvidia P6000 GPUs (http://www.pny.com/nvidia-quadro-p6000) results in the following Exception:
https://gist.github.com/localmaxima/3f50597c6a6c1d1afe16558b70469c46

Without ParallelWrapper it works fine on a single GPU.

#### Version Information
* Deeplearning4j version 0.9.1
* platform information : CentOS 6.8 ,GLIBC 2.14
* CUDA version: 8.0/9.0
* NVIDIA driver version: 384.81

#### Contributing
I have prepared a compressed file with example data that should help reproduce the error. Please extract it and follow instructions in readme.txt file. The instructions assume you will have CUDA and other needed software added to your environment Path.

Note: I should say that the issue is not reproducible on a windows machine.

Link to compressed file: 
https://drive.google.com/file/d/1KRgxS_Nqw8xoCzHlswvhGm5arUElCwWb/view?usp=sharing

**Comment by AlexDBlack** [comment]
Thanks for the issue and information. Is it possible for you to test this on 1.0.0-alpha (which was released recently)? There were a lot of bug fixes in that release, it's possible the underlying issue may have already been fixed.

**Comment by localmaxima** [comment]
What is the minimum version of GLIBC to run 1.0.0-alpha?

**Comment by saudet** [comment]
The version that comes with CentOS 6, which is glibc 2.12:
https://distrowatch.com/table.php?distribution=redhat

**Comment by localmaxima** [comment]
Thank you. It works.
