### ISSUE TITLE
Cannot build examples repo

### ISSUE THREAD

**Issue by ankmathur96** [deeplearning4j/deeplearning4j#4939]
#### Issue Description
Hi - I'm trying to run through the tutorial here and build the examples repo: https://deeplearning4j.org/quickstart

Expected Behavior:
Successful build.

Encountered Behavior:
I get the error here: https://gist.github.com/ankmathur96/345dbfe8f799b8b57cde0c65ede568b2

#### Version Information
MVN version = 3.5.3
Java version = 1.8.0_05
Git version: 2.17.0
OS: MacOS High Sierra 10.13.3

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by RobAltena** [comment]
PLease check ["known issues with javafx"](https://github.com/deeplearning4j/dl4j-examples#known-issues-with-javafx).
