### ISSUE TITLE
mvn clean install fails

### ISSUE THREAD

**Issue by Alireza-Chakeri** [deeplearning4j/deeplearning4j#4944]
### mvn clean install failes with the following error:

[INFO] DeepLearning4j Examples Parent ..................... SUCCESS [  2.620 s]
[INFO] DeepLearning4j Examples ............................ SUCCESS [24:49min]
[INFO] dl4j-spark-examples ................................ SUCCESS [  0.428 s]
[INFO] dl4j-spark ......................................... SUCCESS [02:09min]
[INFO] datavec-examples ................................... SUCCESS [ 28.361 s]
[INFO] DeepLearning4j CUDA special examples ............... FAILURE [  1.544 s]
[INFO] nd4j-examples ...................................... SKIPPED
[INFO] Reinforcement Learning4j Examples .................. SKIPPED
[INFO] lstm-hdfs .......................................... SKIPPED
[INFO] --------------------------------------------------------------------
----
[INFO] BUILD FAILURE
[INFO] --------------------------------------------------------------------
----
[INFO] Total time: 27:32 min
[INFO] Finished at: 2018-04-18T13:10:34-04:00
[INFO] Final Memory: 217M/1476M
[INFO] -----------------------------------------------------------------------

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plug
in:3.5.1:compile (default-compile) on project dl4j-cuda-specific-examples:
Compilation failure
[ERROR] /C:/dl4j-examples/dl4j-cuda-specific-
examples/src/main/java/org/deeplearning4j/examples/multigpu/vgg16/MultiGpuV
GG16TinyImageNetExample.java:[1,1] class, interface, or enum expected

**Comment by AlexDBlack** [comment]
Thanks for reporting. Fixed here: https://github.com/deeplearning4j/dl4j-examples/pull/672
