### ISSUE TITLE
Mismatched shapes after Subsampling1DLayer

### ISSUE THREAD

**Issue by topinju** [deeplearning4j/deeplearning4j#4947]
#### Issue Description
Hi, We are trying to use Convolution1DLayer and Subsampling1DLayer.
The NN is working well while we keep a stride equal to 1, wich is useless for a SubsamplingLayer.

#### Version Information
* Deeplearning4j version : 0.9.1
* platform information (win7)
* CUDA not use

#### Code
We modified the code of the UCISequenceClassificationExample.
As 1Dlayers need Rnn-like data we just add those layers in the network.
You can find our code attached.
The one provided is working, despite the low score, but if you change any stride parameters, it will fire an exepction. For example : "Mismatched shapes (shape = [150, 6], row vector shape =[300, 1])"
[Recurent1D.zip](https://github.com/deeplearning4j/deeplearning4j/files/1926956/Recurent1D.zip)

#### Contributing
Guess we have to reshape our data or something like that after the subsampling layer but we have no idea of how to perform this trick.
We do not need a Rnn output layer, a feedforward should be enought but we have the same issue.
We tried with different inputprocessor without any success.

**Comment by AlexDBlack** [comment]
Hard to be 100% sure without a full stack trace, but this should be fixed here:
https://github.com/deeplearning4j/deeplearning4j/pull/5942
