### ISSUE TITLE
Deep Auto Encoder Documentation is outdated

### ISSUE THREAD

**Issue by nalofir** [deeplearning4j/deeplearning4j#495]
The documentation concerning deep auto encoders [1] is outdated. The mentioned "DeepAutoEncoder object" is no longer available.

[1] http://deeplearning4j.org/deepautoencoder.html

**Comment by agibsonccc** [comment]
Thanks for flagging this. We need to update this with some of the newer
techniques (eg dropout and relu no pretrain) as well as new code.
