### ISSUE TITLE
AlexNet zoo model is wrong

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#4958]
Multiple errors:
https://github.com/deeplearning4j/deeplearning4j/blob/80260f8c86a47a2821b771a23465595d310c8a46/deeplearning4j-zoo/src/main/java/org/deeplearning4j/zoo/model/AlexNet.java#L119-L122

* Kernel 3, stride 7? Doesn't make sense
* nIn of 256 into the first dense layer? also is wrong and doesn't make sense.

Furthermore, with that configuration the calculated padding for the last subsampling layer is negative (which is also not possible - and with additional validation abotu to be merged, results in an exception).

Note that I've made some fixes to the benchmark repo version - but I'm not 100% confident even on that version (but at least the activation shapes are correct!)
https://github.com/deeplearning4j/dl4j-benchmark/commit/8baddba4ce4f67b3624081e6fa95e13395b69d2c

**Comment by crockpotveggies** [comment]
Is this fixed?

**Comment by AlexDBlack** [comment]
No. There's an updated version in the benchmarks repo (which is closer to being correct, but even that I'm not 100% sure on), but I haven't touched the zoo version.
