### ISSUE TITLE
Deadlock in `TfidfVectorizerTest#testTfIdfVectorizer`?

### ISSUE THREAD

**Issue by holgerbrandl** [deeplearning4j/deeplearning4j#4971]
The test `org.deeplearning4j.bagofwords.vectorizer.TfidfVectorizerTest#testTfIdfVectorizer` seems to have a threading/dead-lock issue: It’s running forever without any cpu usage. I’m using the current master cd84e69. I start it with `mvn -Dtest=TfidfVectorizerTest test -P testresources,test-nd4j-native`.

In particular, it seems stuck in https://github.com/holgerbrandl/deeplearning4j/blob/75601e77ecbc719d469b9ff547f744f0e18eb1a0/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/word2vec/wordstore/VocabConstructor.java#L221

The problem occurs under linux and macos.

A thread dump is available under https://gist.github.com/holgerbrandl/821313db8ecaf17134b2b3ce089eb111

**Comment by holgerbrandl** [comment]
Same problem in `NDArrayPublisherTests`. See https://gist.github.com/holgerbrandl/095c8eb7a486626676882c94269bc741 for thread dump.

**Comment by alexanderst** [comment]
Test fixed and merged.
