### ISSUE TITLE
Add additional methods to zoo interfaces to support benchmarking

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#4973]
#### Issue Description

Currently we hold separate copies of zoo models in benchmarks. However, now that there is a developed zoo a couple modifications prior to v1.0 release to APIs will allow us to import the models directly and benchmark them.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j v1.0.0.-snapshot

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by AlexDBlack** [comment]
From my (now closed) issue: Add builder (for convenience) plus ensure we have the ability to configure: (some of which we already have)
- Updater
- Workspace mode
- Cache mode
- Regularization (l1/l2)
- Number of label classes
- Gradient normalization (maybe?)
- Seed (maybe?)

The goal here is to ensure that we can use the models in the benchmark repo (which requires a bit more configuration, than might be required in other circumstances).

**Comment by crockpotveggies** [comment]
Builder is a good idea here. So many method parameters this will remove a lot of code.

**Comment by crockpotveggies** [comment]
Should we deprecate the original method so we can remove it in v1.1?

**Comment by AlexDBlack** [comment]
> Should we deprecate the original method so we can remove it in v1.1?

Sure, I'm in favor of that.

**Comment by crockpotveggies** [comment]
As also decided, we will be eliminating `ModelSelector` since no one seemed to use it anyways.

**Comment by saudet** [comment]
@yquemener You're not using it either, right?

**Comment by crockpotveggies** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/4985

**Comment by yquemener** [comment]
@saudet No, it is fine.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/4985
