### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by willsyo** [deeplearning4j/deeplearning4j#4980]
#### Issue Description

The code has worked, and classified the MNIST dataset, but is inconsistent after changing nothing. It will more often than not throw this error when using this Dl4j version. 

Fails before compilation is complete, and throws: "Error: Could not find or load main class net.traffixx.nickcnn.NickCnnTrainer"

#### Version Information

* Deeplearning4j version: 1.0.0-alpha
* platform information (OS, etc): Microsoft Windows 10 Pro; Version: 10.0.16299 Build 16299
* CUDA version: nd4j-cuda-9.1-platform
* NVIDIA driver version: 

#### Contributing

[NickCnnTrainer.txt](https://github.com/deeplearning4j/deeplearning4j/files/1948137/NickCnnTrainer.txt)

**Comment by raver119** [comment]
I'm sorry, but how is it related to dl4j? That sounds like generic java issue.

**Comment by willsyo** [comment]
The problem is correlated with the version of Dl4j being used. If I roll back my Dl4j version, it runs until it hits a compatibility issue.
