### ISSUE TITLE
Could not find or load main class.

### ISSUE THREAD

**Issue by willsyo** [deeplearning4j/deeplearning4j#4981]
Issue Description
The code has worked, and classified the MNIST dataset, but is inconsistent after changing nothing. It will more often than not throw this error when using this Dl4j version.

Problem is correlated with version of Dl4j being used. If I roll back my Dl4j version, the code runs until it hits a compatibility issue.

Fails before compilation is complete, and throws: "Error: Could not find or load main class net.traffixx.nickcnn.NickCnnTrainer"

Version Information
Deeplearning4j version: 1.0.0-alpha
platform information (OS, etc): Microsoft Windows 10 Pro; Version: 10.0.16299 Build 16299
CUDA version: nd4j-cuda-9.1-platform

**Comment by willsyo** [comment]
Do not close thread due to lack of understanding please!

**Comment by raver119** [comment]
I've closed this issue due to another reason. And you know which one.
