### ISSUE TITLE
Non-deterministic behavior with same inputs to simple NN

### ISSUE THREAD

**Issue by jef5ez** [deeplearning4j/deeplearning4j#4982]
#### Issue Description

Feeding the same input to a simple Conv2d -> DenseLayer network doesn't produce the same output every time.
https://gist.github.com/jef5ez/ebd4eee8e83266f2c3e55ddbe9c38bd2

#### Version Information

* Deeplearning4j version: 1.0.0-SNAPSHOT
latest jars in my m2 seem to be from around 20180425.122408
* platform information (OS, etc): Ubuntu 16.04
* CUDA version: 8.0
* NVIDIA driver version: 384.111

**Comment by raver119** [comment]
so that's cuda + cudnn used, right?

**Comment by jef5ez** [comment]
Correct, cudnn 6.0

**Comment by raver119** [comment]
Can you please disable cudnn dependency, and run without it? Just to see what happens

**Comment by jef5ez** [comment]
Same outputs, just with the cudnn missing warning. I can probably run on another machine in a few minutes as well.

**Comment by jef5ez** [comment]
So only appears to happen on my 750Ti and not on my Titan

https://gist.github.com/jef5ez/47cef22001be32e760d073f37696555d

**Comment by raver119** [comment]
Ok, i'll try to reproduce it on my box shortly

**Comment by jef5ez** [comment]
my cuda version is 8.0.44 on the 750Ti box but 8.0.61 on the titan. could be part of the problem

**Comment by raver119** [comment]
We’ll see shortly.

**Comment by jef5ez** [comment]
updated drivers to 390 and cuda to 8.0.61 but same result on the baby card

**Comment by RobAltena** [comment]
Does not reproduce with 1.0.0-alpha using <artifactId>nd4j-cuda-8.0</artifactId> on GTX 780. 
both native and cuda consistently give "-0.7103".

**Comment by RobAltena** [comment]
@raver119 
Here is a [java unit test](https://gist.github.com/RobAltena/8d1591cd6204cc7cb01b4872bde06802) for the issue. You can plug that in production (if this is an issue with the current build).

**Comment by raver119** [comment]
Yes, reproducible for me. Thank you.

**Comment by RobAltena** [comment]
Now that the test is in, it should be on the list to be fixed for future releases. Thanks for reporting the issue.

**Comment by raver119** [comment]
Test is yet to be decomposed down to nd4j level :)

**Comment by AlexDBlack** [comment]
Looks like an edge case issue. Fails for me for nOut=1, passes for nOut=2

**Comment by AlexDBlack** [comment]
Isolated here: https://github.com/deeplearning4j/nd4j/issues/2860
Will close this once the fix for that is confirmed in the context of DL4J output.

**Comment by raver119** [comment]
Issue fixed on current master.

Thanks for highlighting.
