### ISSUE TITLE
Word Vector lookupTable() returns wrong result

### ISSUE THREAD

**Issue by OmSao** [deeplearning4j/deeplearning4j#4988]
#### Issue Description

 I am trying to run processNews example.
When running https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/processnews/PrepareWordVector.java
I am getting wrong lookupTables for WordVectors
I guess, there is some issue in checkedin code
I expect output of WordVectorSerializer.writeWordVectors(vec.lookupTable(), classPathResource + "NewsWordVector.txt");

as:

<word> <100 dimension vector representation>

But I am getting:
First line I get is in NewsWordVector.txt is: "5091 100 7200"

<some encoded word like B64:adfibdk12 > <100 dimension vector representation>

Version using: latest as of today 26th April 2018

**Comment by raver119** [comment]
Sorry, but this isn’t a bug. First line in csv can be used as header. And
wordvectors use that header to store additional information: vector length,
number of words, total words count.
