### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by sameerkhurana10** [deeplearning4j/deeplearning4j#499]
OS : 2.6.32-504.16.2.el6.x86_64 GNU/Linux
Apache Maven 3.3.3
java version "1.7.0_85"

Followed the steps mentioned in the tutorial i.e. tried building nd4j, canova and deeplearning4j in that order. Got error while building deeplearning4j. Error here:

INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.978 s
[INFO] Finished at: 2015-07-21T22:14:25+01:00
[INFO] Final Memory: 32M/1603M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project deeplearning4j-core: Compilation failure: Compilation failure:
[ERROR] /amd/nfs/lammasu/disk/ptn199/vsm-nfs/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/BaseLayer.java:[36,37] cannot find symbol
[ERROR] symbol:   class LossCalculation
[ERROR] location: package org.nd4j.linalg.lossfunctions
[ERROR] /amd/nfs/lammasu/disk/ptn199/vsm-nfs/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/OutputLayer.java:[39,37] cannot find symbol
[ERROR] symbol:   class LossCalculation
[ERROR] location: package org.nd4j.linalg.lossfunctions
[ERROR] /amd/nfs/lammasu/disk/ptn199/vsm-nfs/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/feedforward/autoencoder/AutoEncoder.java:[30,37] cannot find symbol
[ERROR] symbol:   class LossCalculation
[ERROR] location: package org.nd4j.linalg.lossfunctions
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by agibsonccc** [comment]
This was fixed. Needed to merge a dependent PR on nd4j.
