### ISSUE TITLE
Add Xception, InceptionV4(?), and MobileNet to model zoo

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#4995]
#### Issue Description

Title says it all. Weights are also available on Keras applications: https://keras.io/applications/

#### Version Information

1.0.0-snapshot

**Comment by maxpumperla** [comment]
check keras import tests for reference.

**Comment by crockpotveggies** [comment]
Progress:

- [ ] Xception
- [ ] InceptionV3 (weights already converted)
- [ ] MobileNets (awaiting import fix)
