### ISSUE TITLE
Broken Keras import on Xception

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#4999]
#### Issue Description

When importing the config and weights for Xception, I get the following error:
```
org.deeplearning4j.exception.DL4JInvalidConfigException: Invalid configuration for layer (idx=-1, name=block1_conv1, type=ConvolutionLayer) for height dimension:  Invalid input configuration for kernel height. Require 0 < kH <= inHeight + 2*padH; got (kH=3, inHeight=0, padH=0)
Input type = InputTypeConvolutional(h=0,w=0,d=3), kernel = [3, 3], strides = [2, 2], padding = [0, 0], layer size (output depth) = 32, convolution mode = Truncate
```

I'm simply saving the config and weights as such:
```
model = Xception(weights='imagenet')
model.save("/opt/skil/xception.h5")
```

And then importing as such:
```
ComputationGraph model = KerasModelImport.importKerasModelAndWeights("/home/justin/Downloads/xception.h5");
ModelSerializer.writeModel(model, "/home/justin/Projects/xception_dl4j_inference.v1.zip", false);
```

#### Version Information

snapshot

**Comment by AlexDBlack** [comment]
From gitter:

> @AlexDBlack but yeah, it is a fully convolutional net
https://github.com/keras-team/keras/blob/master/keras/applications/xception.py#L226-L233
no CNN -> dense transition
(or rather it is, via pooling which handles variable input size)
which means its as much a DL4J input type issue as a keras import issue

**Comment by maxpumperla** [comment]
@crockpotveggies please let me know how this doesn't work for you.

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/test/java/org/deeplearning4j/nn/modelimport/keras/e2e/KerasModelEndToEndTest.java#L334-L338
