### ISSUE TITLE
H5 field import error on SqueezeNet

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#5004]
#### Issue Description

Attempted to import weights and config from here: https://github.com/rcmalli/keras-squeezenet/blob/master/keras_squeezenet/squeezenet.py

Saved via Keras as such:
```
model = SqueezeNet(include_top=True, weights='imagenet')
model.save("/opt/skil/squeezenet.h5")
```

Attempted to import but experienced failure with the following output: https://gist.github.com/b5e218a0ee2c0a59a382ebe62c9a77de

#### Version Information

snapshot

**Comment by crockpotveggies** [comment]
Ah now I remember, if a `/` is present in a layer name it confuses H5 and it thinks its a new storage group. Labelling this as wontfix and closing. Re-open if something can be done here.

**Comment by maxpumperla** [comment]
@crockpotveggies yeah, we have this exact squeezenet on master. (it was failing due to a bad regex checking naively for weight bearing layers, `relu_conv10` would have been one of them.)

**Comment by maxpumperla** [comment]
https://github.com/deeplearning4j/deeplearning4j/blob/9d782c260dfac22f8e6560cd66243080aba6e0d6/deeplearning4j-modelimport/src/test/java/org/deeplearning4j/nn/modelimport/keras/e2e/KerasModelEndToEndTest.java#L343
