### ISSUE TITLE
Unable to import Keras2 model

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#5006]
#### Issue Description

Attempted to import these weights, however I'm unsure if our KerasSequentialModel gives us a builder that returns a MultiLayerNetwork

https://github.com/oarriaga/face_classification/blob/master/trained_models/gender_models/simple_CNN.81-0.96.hdf5

#### Version Information

snapshot

**Comment by maxpumperla** [comment]
@crockpotveggies inspecting this h5 file, I'm fairly certain it is not produced by simply calling `save` on a keras model. We don't support such custom constructs (how would we?!).

If you can give me a "clean" version of this, we can add this to tests. Closing for now, but make sure to reopen if needed.
