### ISSUE TITLE
Acquiring Data for simple linear Regression

### ISSUE THREAD

**Issue by SuchtyTV** [deeplearning4j/deeplearning4j#5011]
Hey,

I created a test.csv file with the following dataset:

> 
> 1,2
> 3,4
> -1,0
> ...
> 

I created a simple NeuralNetwork which shall regress the function f(x) = x +1 

```
            MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                    .seed(123)
                    .learningRate(0.01)
                    .activation(Activation.IDENTITY)
                    .weightInit(WeightInit.XAVIER)
                    .list()
                    .layer(0, new DenseLayer.Builder().nIn(1).nOut(1)
                            .build())

                    .layer(1, new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD)
                            .activation(Activation.IDENTITY)
                            .nIn(1).nOut(1).build())
                    .backprop(true).pretrain(false)
                    .build();
```
Now I am searching for a way to train the model, I tried:
           

```
 System.out.println("Here");
            recordReader.initialize(new FileSplit(new ClassPathResource("test.csv").getFile()));
            DataSetIterator iterator = new RecordReaderDataSetIterator(recordReader,7);

            allData = iterator.next();
            allData.shuffle(42);
            DataNormalization normalizer = new NormalizerStandardize();
            normalizer.fit(allData);
            normalizer.transform(allData);
            SplitTestAndTrain testAndTrain = allData.splitTestAndTrain(0.65);
            DataSet trainingData = testAndTrain.getTrain();
            DataSet testData = testAndTrain.getTest();
            //the model here...
            INDArray output = model.output(testData.getFeatureMatrix());
            Evaluation eval = new Evaluation();
            eval.eval(testData.getLabels(), output);
```

But this seems working just for Classifiers...

This leads me to the question:

How to provide the data in this case?
And further, how to interpolate new data?

I am a absolute newbie and try my best following the tutorials on the Internet...

**Comment by raver119** [comment]
You don't want MCXENT/NEGLOG to be used for regression. 
And i'd suggest you to do some reading :)

**Comment by SuchtyTV** [comment]
That it is. Where can I find the real Noobreadings, It seems https://deeplearning4j.org/ giving not much away, if you are complete Noob...

**Comment by agibsonccc** [comment]
@SuchtyTV deeplearning4j.org is *not* meant to be an end to end deep learning reference. It's website for software. It has the basics covered on some high level topics, but it's not the website's job to teach you deep learning. If you want an end to end reference then read the book then: http://shop.oreilly.com/product/0636920035343.do - I am locking this. There are tons of references on the internet ranging from online classes to tutorials for very specific topics.
