### ISSUE TITLE
Transfer learning model serialize/deserialize - dl4j 1.0

### ISSUE THREAD

**Issue by tom-adsfund** [deeplearning4j/deeplearning4j#5022]
Using 1.0

Using this model: https://gist.github.com/tom-adsfund/e707eccaa7f9c0edcddbee9b117f1d4c
(Transfer learning Darknet)

I use ModelSerializer, but on load it says: "RuntimeException: Error deserializing JSON ComputationGraphConfiguration. Saved model JSON is not a valid ComputationGraphConfiguration"
```
at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:605)
at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:464)
```

Here's the serialized model/JSON:
https://gist.github.com/tom-adsfund/f41a5243eaf3bb3bf4cef9b9ac760375

**Comment by AlexDBlack** [comment]
I'll need the code for your custom loss function (TomLoss) also, to be able to help here.

**Comment by tom-adsfund** [comment]
Tom's Loss: https://gist.github.com/tom-adsfund/2f5fd5c9c09a052f806920967c072e67

**Comment by AlexDBlack** [comment]
First guess here: it could be an issue with reflections library, not being able to find it.
Note that reflections library has since been removed on master.

One easy thing you can try is this: https://github.com/deeplearning4j/deeplearning4j/issues/4504#issuecomment-357555845

**Comment by tom-adsfund** [comment]
Yes, this was the problem.

Thanks

**Comment by AlexDBlack** [comment]
Great, thanks for letting me know.
Note that as of the next release, this won't be a problem anymore (as the reflections library isn't used anymore on current master).
