### ISSUE TITLE
Add AMSGrad to optimizers

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#5023]
#### Issue Description

AMSGrad is a slight tweak to ADAM with resulting stronger updates. https://openreview.net/pdf?id=ryQu7f-RZ

#### Version Information

Likely for v1.1.0.

**Comment by AlexDBlack** [comment]
Mathematically, it's a simple change to the Adam updater, and shouldn't take long to implement - so I'll try to squeeze this into the upcoming release.

**Comment by AlexDBlack** [comment]
Implemented here: https://github.com/deeplearning4j/nd4j/pull/2887

**Comment by crockpotveggies** [comment]
Great work!

**Comment by AlexDBlack** [comment]
Merged: https://github.com/deeplearning4j/nd4j/pull/2887
