### ISSUE TITLE
Unable to load pre-trained weights on dl4j from keras

### ISSUE THREAD

**Issue by ahmed451** [deeplearning4j/deeplearning4j#5029]
#### Issue Description

I am trying to load pretrained wieghts from python on dl4j ComputationGraph org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:193)
here is the error:
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 0:
#000: H5A.c line 436 in H5Aopen(): unable to load attribute info from object header for attribute: 'weight_names'
major: Attribute
minor: Unable to initialize object
#001: H5Oattribute.c line 528 in H5O_attr_open_by_name(): can't locate attribute: 'weight_names'
major: Attribute
minor: Object not found

#### Version Information

* Deeplearning4j 1.0.0-alpha
* MacOS Sierra
* keras (2.1.4)
* TF(1.3.0)
* cpu

#### Contributing
       // loading the model 
        try{
           model = KerasModelImport.importKerasModelAndWeights(model_json, model_weights);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }

**Comment by maxpumperla** [comment]
@ahmed451 I need a model to reproduce this. can be keras code or a toy version of your h5.

**Comment by ahmed451** [comment]
Would that work if I provide you with the json file and the h5 ?

**Comment by ahmed451** [comment]
Completed. Both json and hdf5 are there.

**Comment by maxpumperla** [comment]
alright @ahmed451 I have the files, but can't make any promises when I get around to this

**Comment by ahmed451** [comment]
Sure, let me know if you need other things. I'll see if I can dig further in this in the meanwhile.

**Comment by maxpumperla** [comment]
@ahmed451 this was a legitimate issue, which has now been close. however, since we don't have time distributed layer support yet, your model still won't load. (we have a ticket for this already).
