### ISSUE TITLE
Numerous CNN gradient checks failing

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5032]
CNN gradient checks were all passing last I ran them (late last week I think?). 
Now I'm seeing a large number of failures... As far as I know, there have been no changes on the DL4J side that could explain this.

CPU:
![image](https://user-images.githubusercontent.com/2360237/39560179-2eb32d4c-4edf-11e8-82fa-482a90fc661e.png)

CUDA:
![image](https://user-images.githubusercontent.com/2360237/39560259-ed39a548-4edf-11e8-9fa4-b1ee634ae784.png)

So far only CNNs seem to be affected...
My initial guess was the recent im2col and col2im changes - but given the CUDA is also affected, maybe it's something else?

**Comment by maxpumperla** [comment]
As briefly mentioned in gitter, I've seen this too. For me the failures started yesterday morning

**Comment by AlexDBlack** [comment]
Fixed (via workaround) here: https://github.com/deeplearning4j/deeplearning4j/pull/5034
Due to: https://github.com/deeplearning4j/deeplearning4j/issues/5035
