### ISSUE TITLE
SpatialDropout1D not Supported in Keras Loader (1.0.0-alpha)

### ISSUE THREAD

**Issue by mobiusinversion** [deeplearning4j/deeplearning4j#5060]
Hello,

I have trained a model with the Keras layer `SpatialDropout1D` but it appears to be unsupported.  Is this because it is not part of the keras.io official documentation?

**Comment by maxpumperla** [comment]
@mobiusinversion thanks for reporting this. This won't make it into the next release, but we'll integrate it at some point.

**Comment by maxpumperla** [comment]
@mobiusinversion since we needed it for an application, this will make it into the next release after all.
