### ISSUE TITLE
GravesLSTM output gates deltas Array shapes mismatch 

### ISSUE THREAD

**Issue by drlebedev** [deeplearning4j/deeplearning4j#507]
Delta calculation arrays shapes do not match.

```{java}
			INDArray sigmahOfS = Nd4j.getExecutioner().execAndReturn(Nd4j.getOpFactory().createTransform(conf.getActivationFunction(), prevMemCellActivations.dup()));//	shape: [m,n^L]
			INDArray zo = ifogZs.slice(t, 2).get(NDArrayIndex.all(),interval(2*hiddenLayerSize,3*hiddenLayerSize));
			INDArray sigmaoPrimeOfZo = Nd4j.getExecutioner().execAndReturn(Nd4j.getOpFactory().createTransform("sigmoid", zo).derivative());//			shape: [m,n^L]
			INDArray deltao = nablaOut.mul(sigmahOfS).muli(sigmaoPrimeOfZo);
```

nablaOut.mul(sigmahOfS) requires both matrix to be [m,n^L] shape, but sigmaOfS is calculated from prevMemCellActivations, which is generated in line 109: 

```{java}
			INDArray prevMemCellActivations = (t==0 ? Nd4j.zeros(hiddenLayerSize, hiddenLayerSize) : memCellActivations.slice(t-1, 2) );	//Shape: [n^L, n^L]
```
It means that prevMemCellActivations shape is  [n^L, n^L]. This leads to element-wise multiplication error.

**Comment by AlexDBlack** [comment]
So FYI I wrote GravesLSTM. It's not exactly well tested at the moment.
prevMemCellActivations should have shape [m,n^L], not [n^L,n^L]. i.e., at each time point have one per mini-batch per LSTM unit/neuron. So looks like both my t=0 initialization and comment are wrong. Feel free to submit a PR with a fix or I'll get to it in a bit.
Also free to talk to me on gitter if you have any further questions/issues with it.

**Comment by AlexDBlack** [comment]
Fixed.
https://github.com/deeplearning4j/deeplearning4j/commit/74a85a0fa30c87a684f28ea022565d5f9ee7f22e
