### ISSUE TITLE
VPTree is not Serializable

### ISSUE THREAD

**Issue by mikegwf1** [deeplearning4j/deeplearning4j#5094]
#### Issue Description

I am building large VPTree's and I would like to save them to an object and reload them as needed.  However, they are not Serializable

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - 1.0.0-alpha
* platform information (OS, etc) - Windows
* CUDA version, if used - N/A
* NVIDIA driver version, if in use - N/A

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
Fixed/implemented in my branch. Will be merged once it's safe to.
