### ISSUE TITLE
Incorrect epoch logging and counting when using MultipleEpochsIterator for MultiLayerNetwork

### ISSUE THREAD

**Issue by holgerbrandl** [deeplearning4j/deeplearning4j#5110]
Example:
```kotlin
val model : MultiLayerNetwork = ...
val epochitTr = MultipleEpochsIterator(5, trainData)

model.addListeners(object: BaseTrainingListener(){
    override fun onEpochStart(model: Model?) = println("epoch has started")
})

model.fit(epochitTr)
println(model.epochCount)
```
Intuitively, I'd expect the callback to be invoked 5 times, and the `model.epochCount` to be 5 after `fit` has done its magic. However, currently the callback is called just once, and the final `epochCount` is only 1.

Not sure if there’s an easy fix, because MultiLayerNetwork#fit(DataSetIterator) is not aware of the epochy nature of its argument. I could certainly run the epoch-loop myself, but this would essentially make `MultipleEpochsIterator` obsolete.

Since epoch-training is a core technique when building DNNs, this part of the API should leave little doubt about its intent.  The better design might be to remove the `MultipleEpochsIterator` and to add an epoch argument to `fit`, so something along
```
fun MultiLayerNetwork.fit(dsi: DataSetIterator, numEpochs: Int) = repeat(numEpochs){ fit(dsi)}
```

**Comment by AlexDBlack** [comment]
Yeah, I think fit(DataSetIterator, int numEpochs) + deprecate MultipleEpochsIterator is the best way to go here.
As you say, there's no easy fix for MultipleEpochsIterator and I'm hesitant to change the iterator API just for this single class.

**Comment by holgerbrandl** [comment]
Thanks for the fix. :-)
