### ISSUE TITLE
Add ConvLSTM2D support

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j#5111]
#### Issue Description

In order to predict the next frame of a video sequence such as [this Keras example](https://github.com/keras-team/keras/blob/b0f1bb9c7c68e24137a9dc284dc210eb0050a6b4/examples/conv_lstm.py), we would need to add support for `ConvLSTM2D`.

#### Version Information

v1-snapshot

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by maxpumperla** [comment]
closing this one in favor of #3416
