### ISSUE TITLE
Tiny Darknet

### ISSUE THREAD

**Issue by tom-adsfund** [deeplearning4j/deeplearning4j#5129]
Turns out that a smaller network can be made than SqueezeNet, and it's Tiny Darknet.

The primary benefit being that it has a forward pass that's half the cost. It's also a little more accurate.

Details: https://pjreddie.com/darknet/tiny-darknet/

I wouldn't say this is high priority, but obviously would be an improvement.

**Comment by tom-adsfund** [comment]
Briefly looking at the config for the Tiny version, it looks like it uses the same structure as normal Darknet, and can use the same helper class.

As background: Tiny Darknet was a response within a month after the release of the SqueezeNet paper, and I guess because it wasn't in 'paper' form it didn't get covered well.

**Comment by tom-adsfund** [comment]
I think this should be it for the configuration: https://gist.github.com/tom-adsfund/d1a20569e7564e0ba1ec3c72f0753134

**Comment by crockpotveggies** [comment]
Forgive my brevity (haven't read the paper) but do we already have this in TinyYOLO? https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-zoo/src/main/java/org/deeplearning4j/zoo/model/TinyYOLO.java

**Comment by saudet** [comment]
TinyYOLO it actually based on the full original Darknet network, while YOLO is based on Darknet19. Tiny Darknet is smaller than the original Darknet. The guy's not the greatest when it comes to naming things :)

**Comment by tom-adsfund** [comment]
The tradeoffs are basically:

Darknet19 vs (Original) Darknet: trades away substantial amounts of speed for substantial gains in accuracy
Tiny Darknet vs others: basically substantially fewer weights for a slightly worse speed and accuracy performance against the original network

Tiny is useful for anything requiring faster transfer of weights. And I guess it might be faster to train (as that was the case with SqueezeNet).

**Comment by tom-adsfund** [comment]
@crockpotveggies That looks very interesting. More than twice the parameters of Tiny Darknet and SqueezeNet, but much better accuracy.

Well, at least the Zoo will live up to its name!

**Comment by tom-adsfund** [comment]
@crockpotveggies "0.50 MobileNet-160" is probably the most interesting of those, because of its extremely fast forward pass.

**Comment by crockpotveggies** [comment]
Primary issue for MobileNet, I'll make sure I find the 160 variant, thanks! https://github.com/deeplearning4j/deeplearning4j/issues/4995

**Comment by crockpotveggies** [comment]
If there's anything else you'd like to see in the zoo please open an issue, this is really helpful for us. 👍
