### ISSUE TITLE
Configuration not set for certain global parameters

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#513]
Some NN configuration parameters are not set if listed globally for the NN. Currently found for nIn and nOut. Following code leaves nIn and nOut as 0 in the Convolution configuration:

        NeuralNetConfiguration conf = new NeuralNetConfiguration.Builder()
                .layer(new ConvolutionLayer())
                .nIn(1)
                .nOut(2)
                .activationFunction("relu")
                .kernelSize(8, 8)
                .build();

In order to get the configuration to update with the new numbers, you have to use:

        NeuralNetConfiguration conf = new NeuralNetConfiguration.Builder()
                .activationFunction("relu")
                .layer(new ConvolutionLayer.Builder(new int[]{9, 9}, Convolution.Type.SAME).nIn(1).nOut(2).build())
                .build();

Note: If nIn and nOut is requried to be explicitly noted for each layer then hiddenLayerSizes is no longer needed and can be deprecated.
************
Update:

k is not being updated and only being set to 0 for contrastive divergence

**Comment by Lewuathe** [comment]
Current `Layer` interface does not support `nIn` and `nOut` in spite of all layer has input and output. 
So how about implement `setNIn(int n)` and `setNOut(int n)` in `Layer` interface so that `NeuralNetConfiguration` can pass `nIn` and `nOut` to each layer.

**Comment by agibsonccc** [comment]
Bad idea. The layer shouldn't be tied to the conf.

**Comment by EronWright** [comment]
This seems due to #535.
