### ISSUE TITLE
ParallelInference tests failing

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5141]
Passes on native backend ok.

Windows 10, Titan X, CUDA 9.1

![image](https://user-images.githubusercontent.com/2360237/39923296-6c6bd44e-5566-11e8-98cc-08bbbe9b4860.png)

**Comment by AlexDBlack** [comment]
Looks like: the testInferenceX tests are simply flaky - there's inherent randomness in terms of the disribution of tasks between threads, and sometimes the tests will randomly fail as a result.

The testInputMasking failure looks legitimate, however.

**Comment by AlexDBlack** [comment]
testInferenceX failures handled here: https://github.com/deeplearning4j/deeplearning4j/pull/5145

testInputMasking failure has a low probability of occurring, but the failure when it does occur looks like a bug.

**Comment by AlexDBlack** [comment]
So: It turns out that this doesn't have anything to do with parallel inference... this is sufficient to reproduce it:

```
    @Test
    public void batch1(){

        int nIn = 10;
        MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                .activation(Activation.TANH)
                .seed(12345)
                .list()
                .layer(new LSTM.Builder().nIn(nIn).nOut(5).build())
                .layer(new GlobalPoolingLayer(PoolingType.AVG))
                .layer(new OutputLayer.Builder().nIn(5).nOut(5).build())
                .build();

        MultiLayerNetwork net = new MultiLayerNetwork(conf);
        net.init();

        double[] d = new double[]{0.023977466, 0.021927578, 0.5638201, 0.4765249, 0.16738842, 0.998578, 0.7989319, 0.048469864, 0.04674433, 0.4631205, 0.055117667, 0.5074715, 0.6624276, 0.27351934, 0.23996872, 0.81527346, 0.37917703, 0.22173452, 0.05470153, 0.4437007, 0.542513, 0.6791057, 0.93314016, 0.7195189, 0.17417517, 0.8054955, 0.7770213, 0.44565812, 0.6900083, 0.38784736};
        INDArray arr = Nd4j.create(d, new int[]{3,10,1}, new int[]{1,3,30}, 0);

        INDArray outBatch = net.output(arr);
        for( int i=0; i<3; i++ ){
            INDArray inSingle = arr.get(NDArrayIndex.interval(i,i,true), NDArrayIndex.all(), NDArrayIndex.all());
            INDArray outSingle = net.output(inSingle);

            INDArray outBatchSubset = outBatch.get(NDArrayIndex.interval(i,i,true), NDArrayIndex.all());

            assertEquals(outSingle, outBatchSubset);
        }
    }
```

Maybe global pooling edge case?

**Comment by AlexDBlack** [comment]
Yep, definitely not related to ParallelInference at all... it's an ND4J reduction edge case:
```
    @Test
    public void testMeanEdgeCase(){
        INDArray arr = Nd4j.rand(new int[]{3,10,1}, 12345).dup('f');
        INDArray arr2 = arr.mean(2);

        INDArray exp = arr.get(NDArrayIndex.all(), NDArrayIndex.all(), NDArrayIndex.point(0));

        assertEquals(exp, arr2);
    }
```

**Comment by maxpumperla** [comment]
@AlexDBlack does that edge case impact global pooling? I'm seeing some prediction discrepancies for imported keras models in global pooling, maybe that's related?!

**Comment by AlexDBlack** [comment]
@maxpumperla yes, it was/is impacting global pooling - average pooling with sequence length == 1 and minibatch > 1

**Comment by AlexDBlack** [comment]
Confirmed fixed and passing.
