### ISSUE TITLE
ND4J: Add maven enforcer profile for test resources

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5143]
In DL4J: If you forget to enable ```test-nd4j-native``` or ```test-nd4j-cuda-X``` you get an immediate failure.

With ND4J tests: If you forget to enable the ```testresources``` profile, you end up running the tests for 40 minutes and then realizing at the end a bunch of the failures are just due to forgetting this :/

https://github.com/deeplearning4j/nd4j/blob/master/pom.xml#L51

**Comment by raver119** [comment]
Why not just make it real dependency with corresponding scope?

**Comment by AlexDBlack** [comment]
If we can - for sure.
Only thing that comes to mind here is if you want to install ND4J without the test resources installed... will maven realize that it's test scope and hence not finding the artefact is irrelevant? Or will it error out regaldless. Honestly not sure on that, but it's easy to test.

**Comment by AlexDBlack** [comment]
Unfortunately it was as I expected - adding it as a simple test scope dependency means you can't build ND4J without it (even with -DskipTests). So I'll use maven enforcer instead...

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/nd4j/pull/2899
