### ISSUE TITLE
modelType() and init() returns different types in VGG16 and VGG19

### ISSUE THREAD

**Issue by yquemener** [deeplearning4j/deeplearning4j#5148]
In both VGG16 and VGG19 `modelType()` returns `ComputationGraph.class` while `init()` returns a `MultiLayerNetwork`. I think that the correct type for both is MultiLayerNetwork.

**Comment by AlexDBlack** [comment]
If memory serves me, all of the pretrained models are computation graphs.
Hence for consistency, the standard (non-pretrained) model should be a computation graph too.

**Comment by agibsonccc** [comment]
No, they were MLNs. I already merged the PR for this.

**Comment by AlexDBlack** [comment]
No, the pretrained imagenet model is definitely a ComputationGraph:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-zoo/src/test/java/org/deeplearning4j/zoo/TestInstantiation.java#L90-L93
