### ISSUE TITLE
Memory Mapped Allocation not working in Windows 10

### ISSUE THREAD

**Issue by isearchxsolve** [deeplearning4j/deeplearning4j#5150]
#### Issue Description

I am trying to use memory mapped allocation mentioned in the documentation and I am using both nd4j-1.0.0-alpha and dl4j-1.0.0-alpha.My OS is Windows 10 64bit and processor i7 and RAM 16 GB and hdd 2TB.I am using the below code.
WorkspaceConfiguration mmap = WorkspaceConfiguration.builder().initialSize(10000000000l)
.policyLocation(LocationPolicy.MMAP).build();
MemoryWorkspace ws = Nd4j.getWorkspaceManager().getAndActivateWorkspace(mmap, "M2")
- expected behavior: 10 GB Memory should be allocated from HDD to be mapped to virtual address space and ws should be returned
- encountered behavior: However memory allocation fails saying 
Exception in thread "main" java.lang.RuntimeException: MMAP failed
at org.nd4j.linalg.cpu.nativecpu.workspace.CpuWorkspace.init(CpuWorkspace.java:61)
at org.nd4j.linalg.memory.abstracts.Nd4jWorkspace.<init>(Nd4jWorkspace.java:181)
at org.nd4j.linalg.cpu.nativecpu.workspace.CpuWorkspace.<init>(CpuWorkspace.java:33)
at org.nd4j.linalg.cpu.nativecpu.workspace.CpuWorkspaceManager.getWorkspaceForCurrentThread(CpuWorkspaceManager.java:72)
at org.nd4j.linalg.memory.provider.BasicWorkspaceManager.getAndActivateWorkspace(BasicWorkspaceManager.java:196)

#### Version Information

Please indicate relevant versions, including, if relevant:

* dl4j-1.0.0.0-alpha and nd4j-1.0.0-alpha
* Windows 10 64bit and processor i7 and RAM 16 GB and hdd 2TB,jdk1.8.0_144
* CUDA version, if used-N/A
* NVIDIA driver version, if in use-N/A

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
No man, it's not "MMAP not working". It's more like "MMAP fails to utilize 10GB file". That's different problem.

Please try to allocate, say, 3.5GB and confirm it works.

**Comment by raver119** [comment]
Ye, never mind, looks like value overflow on windows.

**Comment by isearchxsolve** [comment]
Just a suggestion...I know I am not expert enough for this...but we could look at the JDK 1.8 api for memory mapping it should also surely use some native C++ library for mmap...hopefully in jdk it works..thanks

**Comment by raver119** [comment]
If all you need is 2GB mmap (which is java limit), you can just use existing workspace mmap. But since you've tried 10GB, i assume 2GB won't be enough for you?

**Comment by raver119** [comment]
meh, in any way - we need real pointers. Some pointers which won't be moved by jvm eventually.

**Comment by raver119** [comment]
Hm. I'm sorry, but can you show me your full source code and show me your OS version including build number?

I've wrote simple test in C++, and as allocation perfectly worked for me. So, i wonder what's the difference there.

**Comment by isearchxsolve** [comment]
WorkspaceConfiguration mmap = WorkspaceConfiguration.builder()
                .initialSize(10000000000l)
                .policyLocation(LocationPolicy.MMAP)
                .build();
                
try (MemoryWorkspace ws = Nd4j.getWorkspaceManager().getAndActivateWorkspace(mmap, "M2")) {
    INDArray x = Nd4j.create(10000);
}
OS version and Build number attached
![image](https://user-images.githubusercontent.com/23405512/39985507-76874540-577c-11e8-8dd6-76c917932df8.png)

**Comment by isearchxsolve** [comment]
![image](https://user-images.githubusercontent.com/23405512/39986549-9d609290-577f-11e8-9c12-9c5fa838437a.png)

**Comment by raver119** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/5158

**Comment by raver119** [comment]
Basically we were using Win32 API for everything but open()/close() system calls. Now we use Win32 API for those calls as well.

**Comment by isearchxsolve** [comment]
will using win32 api for open()/close() fix this issue.Thanks

**Comment by raver119** [comment]
yes, it is. i'm waiting for jenkins to approve the pr, and i'll merge fix.

**Comment by isearchxsolve** [comment]
Thanks to all of you guys...you guys rock...great relief for me...it was fast

**Comment by raver119** [comment]
Fix merged. Once snapshot updates - it should work for you.
