### ISSUE TITLE
How did the getter implemented in NeuralNetworkConfiguration class

### ISSUE THREAD

**Issue by csehao** [deeplearning4j/deeplearning4j#517]
From time to time, my IntelliJ starts to report tons of issues for the NeuralNetConfiguration conf object in nearly all classes. For example, in org.deeplearning4j.nn.params.ConvolutionParamInitializer,  line 43, if(conf.getKernelSize().length < 2). I get error that getKernelSize can not be resolved. If we look into the NeuralNetConfiguration class, there is no getter for nay of the fields in this class. 

When I was lucky enough once or twice that there were no error, (usually when I first build the targets). Clicking on the method will jump to the class file in which the getters for all fields exists. I understand this might be done through reflect. But I'm kind of newbee for java, I tried for couple of hours but still failed to settle how this is done.

**Comment by AlexDBlack** [comment]
These sorts of issues usually occur if you import the full source code into an IDE without setting up Lombok. Lombok is a code generation tool that we use to generate getters/setters automatically.
Try setting up Lombok and see if the issue persists https://projectlombok.org/

**Comment by AlexDBlack** [comment]
Closing this. Feel free to talk to us on Gitter if you are still having problems with this.
