### ISSUE TITLE
DataVec: Add audio reading support

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5189]
For speech to text, anomaly detection, speaker identification, etc use cases.

See also: https://github.com/deeplearning4j/DataVec/issues/208

**Comment by arvindangelo** [comment]
Hello, I am using DL4J for some ASR/CAPT. I notice there is not much concerning reading audio files or Audio Labelling. I would like to know if anyone is working on this? I have currently built some code to read MFCCs from an Audio file and wondering if anyone has an implementation that can read a CSV dataset for the audio into DL4J, before I start on this. Dont want to be re-inventing the wheel here.

**Comment by agibsonccc** [comment]
@arvindangelo  We had it at one point but weren't maintaining it.  It mainly worked with wav files: https://github.com/deeplearning4j/deeplearning4j/tree/deeplearning4j-1.0.0-beta7/datavec/datavec-data/datavec-data-audio/src/main/java/org/datavec/audio Please post on the forums in the future: https://community.konduit.ai/ - I'm closing this to avoid further confusion.
