### ISSUE TITLE
Not able to split dataset while passing TransformProcessRecordReader instance to RecordReaderDataSetIterator 

### ISSUE THREAD

**Issue by rahul-raj** [deeplearning4j/deeplearning4j#5220]
Here is the complete data transformation code from my project:

```
Schema schema = new Schema.Builder()
                .addColumnsString("RowNumber")
                .addColumnInteger("CustomerId")
                .addColumnString("Surname")
                .addColumnInteger("CreditScore")
                .addColumnCategorical("Geography",Arrays.asList("France","Spain","Germany"))
                .addColumnCategorical("Gender",Arrays.asList("Male","Female"))
                .addColumnsInteger("Age","Tenure","Balance","NumOfProducts","HasCrCard","IsActiveMember","EstimatedSalary","Exited").build();
        TransformProcess transformProcess = new TransformProcess.Builder(schema)
                .removeColumns("RowNumber","Surname","CustomerId")
                .categoricalToInteger("Gender")
                .categoricalToOneHot("Geography").build();
        RecordReader reader = new CSVRecordReader(1,',');
        reader.initialize(new FileSplit(new ClassPathResource("Churn_Modelling.csv").getFile()));
        RecordReader transformProcessRecordReader = new TransformProcessRecordReader(reader,transformProcess);

        int labelIndex = 13;
        int numClasses = 2;
        int batchSize = 100;
        DataSetIterator iterator = new RecordReaderDataSetIterator(transformProcessRecordReader,labelIndex,numClasses,batchSize);
        Dataset dataSet = iterator.next(); //  Throws Exception in thread "main" java.lang.UnsupportedOperationException
```

> Exception in thread "main" java.lang.UnsupportedOperationException
> 	at org.datavec.api.records.reader.impl.transform.TransformProcessRecordReader.next(TransformProcessRecordReader.java:64)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:143)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:367)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:458)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:85)

Now I have no options left to split the data set since the execution fails at mentioned line on the above.
If I pass any other type of RecordReader instance **(For example: CSVRecordReader)** in place of `transformProcessRecordReader` everything works fine, but problem comes when I had to use transformed data.  `TransformProcessRecordReader` isnt working here.  Also figured out that `transformProcessRecordReader` itself behaves like an iterator so that I could do something like this:

```
while(transformProcessRecordReader.hasNext()){
       Sysout(transformProcessRecordReader.next());
} 

```
The **RecordReaderDataSetIterator** supposed to work irrespective of various implementations of **RecordReader** instance we're passing to. But that's not the case here with  `TransformProcessRecordReader`.

**Comment by rahul-raj** [comment]
In the master version of `TransformProcessRecordReader`, there is no parameterized constructor to accept `Transformprocess` as variable.
So how do I pass `TransformProcess` instance to `TransformProcessRecordReader` ?

**Comment by rahul-raj** [comment]
Fixed this by changing maven dependency to `nd4j-native` as per the snapshot guide here:
[https://deeplearning4j.org/snapshots
](https://deeplearning4j.org/snapshots
)

**Comment by saudet** [comment]
So, is everything working now? BTW, 1.0.0-beta has just been released!

**Comment by rahul-raj** [comment]
Hey, 
Alex was saying the fix will be released soon. I'm using snapshot version at the moment.
@AlexDBlack  Does this beta version has the fix for this?

**Comment by rahul-raj** [comment]
I'm using `1.0.0-beta` version now.
Tested it for the same code and now working without issues.
Cheers :+1:
