### ISSUE TITLE
All projects: Move all test resources to external repository (dl4j-test-resources)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5233]
To simplify IP issues with Eclipse transition we should move our remaining test resources to an external repository (i.e., dl4j-test-resources or equivalent)

- [x] DL4J https://github.com/deeplearning4j/dl4j-test-resources/pull/115
- [x] DataVec https://github.com/deeplearning4j/dl4j-test-resources/pull/115
- [x] Arbiter (none to move it seems )
- [x] RL4J (no resources to move)
- [ ] Libnd4j
- [x] ND4J (no resources to move)
- [x] ND4S (no resources to move)
- [x] ScalNet (no resources to move)
- [x] Jumpy (no resources to move)
- [x] gym-java-client  (no resources to move)

Update: remaining possible issues in DL4J, after this is merged: https://github.com/deeplearning4j/deeplearning4j/pull/5300
- deeplearning4j-core: iris.dat -> simply needs to be moved to downloader
- deeplearning4j-nlp: lots of main (runtime, not test) resources
- deeplearning4j-nlp-chinese: lots of runtime resources
- deeplearning4j-ui: 3rd party libraries (javascript, etc)
- deeplearning4j-ui-components: 3rd party libraries (javascript, etc)
- deeplearning4j-zoo: runtime resources (label files, etc)

In datavec:
- datavec-data-nlp: stopwords

In Arbiter:
- arbiter-ui: d3.js and similar

In ND4J:
- nd4j-api: onnxops.json, ops.proto

**Comment by saudet** [comment]
@raver119 This includes Google Test in libnd4j here: https://github.com/deeplearning4j/libnd4j/tree/master/tests_cpu/lib/googletest-release-1.8.0  Though we can just download that one from GitHub on build.

**Comment by AlexDBlack** [comment]
Another thing (adding a note so we don't forget): there's some large test files in the mono repo... these should be removed - and if possible (this may be challenging, however), also removed from git commit history:
```
remote: warning: File datavec/datavec-api/src/test/resources/mnist_svmlight.txt is 61.68 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File libnd4j/tests_cpu/resources/inception.fb is 51.97 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File tests_cpu/layers_tests/minifier is 51.69 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File tests_cpu/layers_tests/minifier.dSYM/Contents/Resources/DWARF/minifier is 57.98 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File nd4j-backends/nd4j-tests/src/test/resources/tf_graphs/tensorflow_inception_graph.pb is 51.39 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
```

**Comment by saudet** [comment]
This reminds me, we might have to clear all history of at least the master branch after changing the copyright to the Eclipse Foundation anyway, so let's hold on with those changes too.

**Comment by AlexDBlack** [comment]
Everything done except libnd4j; I'm not sure how or even if we would want to move the libnd4j resources to the test repo anyway.
