### ISSUE TITLE
Evaluating multi output network

### ISSUE THREAD

**Issue by pawel12** [deeplearning4j/deeplearning4j#5237]
Hi,

One question about multi-output setup. Is there some simple way of evaluating multi output network?
If I try to just use ComputationGraph.evaluate() I'm getting this exception: https://github.com/deeplearning4j/deeplearning4j/blob/1bceec00a6cc7b60d873c4179da49667b5d393c0/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/graph/ComputationGraph.java#L3738

**Comment by AlexDBlack** [comment]
We do need to add a convenience method for this...

In the mean time something along the lines of the following should suffice:
```
IEvaluation[] evals = new IEvaluation[]{new Evaluation(), ...};
while(testData.hasNext()){
	MultiDataSet next = testData.hasNext();
	INDArray[] output = graph.output(...);
	for( int i=0; output.length; i++ ){
		evals[i].eval(next.getLabels(i), output[i]);
	}
}
```

**Comment by pawel12** [comment]
Thanks you AlexDBlack
