### ISSUE TITLE
Importing Keras Model via h5 file on HDFS (Spark)

### ISSUE THREAD

**Issue by Saftophobia** [deeplearning4j/deeplearning4j#5241]
I imported an LSTM from a pretrained keras model
```scala
val lstmModel = new KerasSequentialModel().
      modelBuilder.
      modelJson(model_json). //json loaded by: sc.textFile("hdfs_path").collect.mkstring
      weightsHdf5Filename("hdfs_path?").
      enforceTrainingConfig(false).
      buildSequential.
      getMultiLayerNetwork
```
How can I load a model in a spark workflow, where the weightsHDF5 file is stored in HDFS?

**Comment by maxpumperla** [comment]
@Saftophobia of course, you can in principle load this from anywhere, provided it's configured correctly. Just note that you really don't have to. Your data should be on HDFS, your model you can load from local file system on master first, which gives you a `MultiLayerNetwork`, which you can then wrap into a respective `SparkDl4jMultiLayer` and run your model. I'd recommend this approach.
