### ISSUE TITLE
1dimensional DL4J CNN throwing an IllegalStateException: Invalid mask array 

### ISSUE THREAD

**Issue by reuschling** [deeplearning4j/deeplearning4j#5242]
#### Issue Description
I created a 1-dimensional CNN with the layers: `Convolution1DLayer,Subsampling1DLayer,DenseLayer,OutputLayer`. As input type, I use `InputType.recurrent(iTimeseriesLength, 1); I feed the same, working data as into a running LSTM scenario, batchsize 16,timeserieslength 23. My dl4j version is 1.0.0-alpha
Sadly, I recieve an exception:
```
java.lang.IllegalStateException: Invalid mask array: per-example masking should be a column vector, per output masking arrays should be the same shape as the output/labels arrays. Mask shape: [1, 23], output shape: [19, 8](layer name: layer3, layer index: 3, layer type: OutputLayer)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.applyMask(BaseOutputLayer.java:435)
	at org.deeplearning4j.nn.layers.BaseLayer.preOutput(BaseLayer.java:340)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.preOutput2d(BaseOutputLayer.java:421)
	at org.deeplearning4j.nn.layers.BaseOutputLayer.backpropGradient(BaseOutputLayer.java:148)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.calcBackpropGradients(MultiLayerNetwork.java:1414)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.backprop(MultiLayerNetwork.java:1364)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:2407)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:173)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:59)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:53)
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1922)```

Here is an according [Gist](https://gist.github.com/reuschling/b7c86ef9879ff75a6db313c57ab0efb5)

#### Version Information
* Deeplearning4j version: 1.0.0-alpha
* platform information Suse Linux Leap
* CUDA version: not used
* NVIDIA driver version: not used

#### Contributing

Again the [Gist](https://gist.github.com/reuschling/b7c86ef9879ff75a6db313c57ab0efb5)

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/5880

You can use snapshots to access the fix: https://deeplearning4j.org/snapshots

**Comment by reuschling** [comment]
I appreciate, maybe I missed something, but my gist throws the same error as before, with the current snapshot of today. Have you test it against it?
Here the link: [Gist](https://gist.github.com/reuschling/b7c86ef9879ff75a6db313c57ab0efb5)

**Comment by reuschling** [comment]
@AlexDBlack :+1: thanks a lot

**Comment by AlexDBlack** [comment]
Reopening until I've had time to confirm (or fix).

**Comment by AlexDBlack** [comment]
Thanks for the code. Finally had time to look at this.
The (remaining) problem here is a mismatch between the network configuration and data configuation.

For the network, you're using OutputLayer - which is OK.
But then for the data pipeline, you are using SequenceRecordReaderDataSetIterator. This iterator produces sequence data for both the features and the labels. You want non-sequence labels here for sequence classification.

Use instead:
- CSVSequenceRecordReader for the features
- CSVRecordReader for the labels
- Combine using RecordReaderMultiDataSetIterator (addSequenceReader and addReader methods respectively).

**Comment by reuschling** [comment]
@AlexDBlack Thanks again so much. It would took me ages to find this.

**Comment by reuschling** [comment]
Ah, and a last question for understanding: would a combination of SequenceRecordReaderDataSetIterator and RnnOutputLayer be possible?

**Comment by AlexDBlack** [comment]
One issue you might have when using downsampling in the network configuration is that it's hard to know how the labels align.
Put another way, it's effectively a sequence-to-sequence model: you have sequences of length X for features, and sequences of length Y<X for labels.
Add to that variable lengths for both, and it becomes challenging to get your data pipeline to align everything properly from the perspective of the network.

Anyway, if you have a legitimate use case that requires that sort of functionality, open another issue and I'll see if we can work out a way to implement this.
