### ISSUE TITLE
SameDiff: Look at code generation for SameDiff module

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5244]
The idea: with hundreds of ops, it would be better and more maintainable to generate at least some of the SameDiff methods from the ops.

One way we could do this for the static methods in Java (while maintaining the ability to easily add more custom/hand-written methods) is something like the following class structure:
```
SameDiffGeneratedMethods -> SameDiffExtraMethods1 -> SameDiffExtraMethods2 -> SameDiff
```

Aha! Link: https://skymindai.aha.io/features/ND4J-177

**Comment by saudet** [comment]
BTW, can we make use of anything generated by JavaCPP here?
https://raw.githubusercontent.com/deeplearning4j/nd4j/master/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/nativeblas/Nd4jCpu.java

**Comment by AlexDBlack** [comment]
For the SameDiff class - maybe not.
These are the sorts of methods that we would want to generate:
https://github.com/deeplearning4j/nd4j/blob/589d49a7156e0f056c979a66e8d28a26330a0d49/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/samediff/SameDiff.java#L2447-L2516

And on the DifferentialFunctionFactory side: it's all still just Java objects...
https://github.com/deeplearning4j/nd4j/blob/589d49a7156e0f056c979a66e8d28a26330a0d49/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/functions/DifferentialFunctionFactory.java#L165-L344

**Comment by raver119** [comment]
@AlexDBlack at some point we've discussed codegen with @saudet actually. i'm still sure  that's something JavaCPP can deal with just perfectly, with some tweaks on libnd4j side, sure.

**Comment by saudet** [comment]
Hum, `SDVariable` is a Java-land concept not present in C++, correct? I think we'll need something more than JavaCPP then. But at least we can write that generator in Java, unlike the TensorFlow team who decided to use C++ for code generation, for reasons that appear to me purely political in nature: https://github.com/tensorflow/tensorflow/issues/17390#issuecomment-382273058

**Comment by AlexDBlack** [comment]
Related issue: https://github.com/deeplearning4j/deeplearning4j/issues/5175
Same sort of problem... generate code (classes, in this case) from other Java code.
Not sure if there's a common solution/framework/approach for both...
