### ISSUE TITLE
RL4J: Unable to create Gym environment. Hard coded JSONObject not in JSON.

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5264]
_From @RobAltena on August 25, 2017 1:12_

#### Issue Description
Trying to generate the `FrozenLake-v0` environment in rl4j:
```
public static void main(String[] args){
        GymEnv<Box, Integer, DiscreteSpace> mdp = new GymEnv("FrozenLake-v0", false, false);
        mdp.close();
    }
```

fails with `org.json.JSONException: JSONObject["shape"] not found.`
[Here](https://github.com/deeplearning4j/gym-java-client/blob/master/src/main/java/org/deeplearning4j/rl4j/space/GymObservationSpace.java#L30) is the line that causes the exception:

When debugging the exception is correct: The JSON object indeed does not have a "shape":
{"name":"Discrete","n":16}

#### Version Information
0.9.1 

#### Contributing
Happy to try and figure out how to solve this. But the Rl4J code is still a bit mysterious to me.

_Copied from original issue: deeplearning4j/rl4j#59_

**Comment by AlexDBlack** [comment]
_From @saudet on August 25, 2017 1:35_

Right, we'll need to fix GymEnv to support other ObservationSpace than Box. Will end up creating at least a Discrete class I guess, and put that everywhere where Box is right now but as a choice available to the user.

**Comment by AlexDBlack** [comment]
_From @saudet on August 25, 2017 1:36_

This table might be useful:
https://github.com/openai/gym/issues/106#issuecomment-226675545

**Comment by AlexDBlack** [comment]
_From @RobAltena on August 29, 2017 5:17_

Maybe there is some issue with the OpenAI gym-http-api itself:
Based on the link you provided I build a little script listing all environments that can be build and reset successfully from Python:

    from gym import envs
    envall = envs.registry.all()

    res = "private String [] envIDs = {"
    for e in envall:
        try:
            env = e.make()
            env.reset()
        except:
            continue
    res += "\"" + e.id + "\", "
    res = res[0:-2] + "};"
    print(res)

However if I then create and reset those environments using the gym-http-api I get a "500 - internal server error" on the reset() about half the time. I am not even trying to get to that mysterious "Initial Observation" that might be in the JSON response for the "200-OK" responses.

    340570f4 Pendulum-v0 - 200
    1a04daa9 Reverse-v0 - 500
    9ea78450 DuplicatedInput-v0 - 500
    e836e955 Blackjack-v0 - 500
    168aa80b FrozenLake-v0 - 200
    648cf869 Acrobot-v1 - 200
    0052bba2 FrozenLake8x8-v0 - 200
    be47a3dc Copy-v0 - 500
    057edd1f ReversedAddition-v0 - 500
    0ea7054f OneRoundNondeterministicReward-v0 - 500
    a7a33ae4 TwoRoundNondeterministicReward-v0 - 500
    f53b0f57 PredictObsCartpole-v0 - 200
    b6e7a1d5 Roulette-v0 - 500
    fb1ef49d NChain-v0 - 500
    ef5d45f4 Taxi-v2 - 200
    dffc422c SemisuperPendulumDecay-v0 - 200
    fcaf40fa TwoRoundDeterministicReward-v0 - 500
    46117730 ReversedAddition3-v0 - 500
    c35f632f SemisuperPendulumRandom-v0 - 200
    f1de0859 OneRoundDeterministicReward-v0 - 500
    4477fc05 MountainCar-v0 - 200
    47f1cecf OffSwitchCartpoleProb-v0 - 500
    dc70695a OffSwitchCartpole-v0 - 500
    104124ab CartPole-v0 - 200
    8c3d8477 SemisuperPendulumNoise-v0 - 200
    ed311689 MountainCarContinuous-v0 - 200
    525cde0c CartPole-v1 - 200
    a765b8c6 HotterColder-v0 - 500
    67e87fbc RepeatCopy-v0 - 500
    60f9e285 GuessingGame-v0 - 500
    9a418d16 PredictActionsCartpole-v0 - 200

**Comment by AlexDBlack** [comment]
_From @saudet on August 29, 2017 14:4_

Ack, time to try to use Gym with Jython 2.7.1? :) It should work...
https://wiki.python.org/jython/InstallationInstructions

**Comment by AlexDBlack** [comment]
_From @RobAltena on September 17, 2017 5:52_

I am tempted to close this issue: OpenAI Gym is at best 'in transition'. The old openai.gym.com link now redirects to github. On the gitter openai/gym channel there is talk about a migration to Montreal.AI Gym.

**Comment by RobAltena** [comment]
Now that we are in the mono repo: We should think about deleting the gym-java-client directory. It seems out of place in deeplearning4j.

**Comment by saudet** [comment]
@RobAltena We'll leave it around for reference, but it will remain read-only.
