### ISSUE TITLE
RL4J: SyncLearning lacks necessary training control

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5267]
_From @viluon on October 9, 2017 22:56_

https://github.com/deeplearning4j/rl4j/blob/273564b2e35294a83893688b9033013fe24129b6/rl4j-core/src/main/java/org/deeplearning4j/rl4j/learning/sync/SyncLearning.java#L36

The step counter lacks setters, which makes all `Learning`-based classes practically unusable after the first `.train()` call.

* [`stepCounter` definition](https://github.com/deeplearning4j/rl4j/blob/273564b2e35294a83893688b9033013fe24129b6/rl4j-core/src/main/java/org/deeplearning4j/rl4j/learning/Learning.java#L34)

_Copied from original issue: deeplearning4j/rl4j#70_

**Comment by AlexDBlack** [comment]
_From @saudet on October 11, 2017 5:43_

We could recreate these objects, if that's the intention. Could you explain your use case?

**Comment by viluon** [comment]
@saudet continuous learning (improving the net while it is being used).

**Comment by saudet** [comment]
@viluon Sure, let's add a `@Setter` there or switch to `@Data`. Could you send a pull request?
