### ISSUE TITLE
RL4J: Please comment the code

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5269]
_From @ari62 on October 10, 2017 14:13_

Hi, Please add comments to the code. For example:
https://github.com/deeplearning4j/gym-java-client/blob/master/src/main/java/org/deeplearning4j/rl4j/space/ObservationSpace.java

I don't know what getHigh and getLow are supposed to return. Please specify what input parameters and output return values are supposed to represent for your functions.

Thank you

_Copied from original issue: deeplearning4j/rl4j#72_

**Comment by AlexDBlack** [comment]
_From @viluon on October 10, 2017 14:28_

Strictly speaking, that file is in a different repository. I must second the call for cleaner code, however. The lack of any documentation in itself wouldn't be *that* much of a problem if the purpose of different components was clear from the source code. Working on a RL4J-based project right now, it is a pain to contact @saudet about every minor interface that I have to implement to get reinforcement learning to work in my environment.

Sadly, it seems this library has been developed just enough to support the examples, but not much further. I'd appreciate if anyone could take it beyond completeness for showcase purposes.

**Comment by AlexDBlack** [comment]
_From @tomthetrainer on October 10, 2017 18:20_

Hi There, thanks for the feedback. 

I know you posted this because you are asking for help, and I will get to improving the comments as time allows. 

However, please remember we are open source and contributions are welcome, I know perhaps adding comments to the RL4J might be challenging, but we could use better commented code in more simple areas as well. 

Feel free to create a pull request with improved javadoc, or better comments on the stuff that you do understand. 

I assigned this to myself, and will get to this at some point.

**Comment by AlexDBlack** [comment]
_From @saudet on October 11, 2017 5:32_

I believe getHigh() and getLow() are not used for anything at the moment.

@rubenfiszel Could you let us know what was your intention with those attributes?

**Comment by AlexDBlack** [comment]
_From @rubenfiszel on October 11, 2017 16:18_

Hello,

I apologise if the code is not commented enough or if you feel it's not
well thought enough to be intuitive.

In this case, this is simply the lowest and highest value the observation
space can take. Being tensors, it's the tensor of the lowest and highest
possible values. It gives you the range and make it possible to normalize
in later steps.

Best,

**Comment by AlexDBlack** [comment]
_From @saudet on October 11, 2017 22:13_

@rubenfiszel Thanks for the reply! Yes that's what I thought they were for, but the values are not currently used anywhere...

**Comment by AlexDBlack** [comment]
See also: https://github.com/deeplearning4j/rl4j/issues/82

**Comment by rahul-raj** [comment]
I have the same concern as well, same as @ramsestom
