### ISSUE TITLE
RL4J: Allow QLearning training to terminate before maxEpochStep when training goal has been achieved

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5270]
_From @shanusmcshan on February 11, 2018 11:31_

Allow the MDP to signal to QLearning that training is complete so that QLearning may terminate before maxEpochStep reached as the training goal has been achieved.

In my case this is when a certain epoch reward has been achieved consistently over a certain number of epochs, however there are certainly other scenarios.

_Copied from original issue: deeplearning4j/rl4j#87_

**Comment by saudet** [comment]
With the changes in pull #5972, we can accomplish that by setting the `stepCounter` to some large value like `Integer.MAX_VALUE`, and training will stop.
