### ISSUE TITLE
poor performance of yolo model

### ISSUE THREAD

**Issue by holger-prause** [deeplearning4j/deeplearning4j#5285]
Hello,
I have some poor performance on the yolo model compared to native darknet yolo implementation.
My testing environment:

Graphic card:
Nividea GTX 1050 TI 4GB
OS: Windows7

Driver:
Nividea Cuda  9.0
Cudnn 7.0.5

Source code for reproducing
https://github.com/holger-prause/dl4j_yolo

output gist
https://gist.github.com/holger-prause/081fb0133a65986d79df8c4e26a167f0
The output is around 500 ms for the yolov2 model 

--------------------------------------------------------------------
For comparison with darknet yolo (same machine - yolov2 model -  but slightly newer driver -required for building)
Driver:
Nividea Cuda  9.2
Cudnn 7.1.4

darknet yolo
https://github.com/AlexeyAB

command used:
darknet.exe detector test data/coco.data cfg/yolov2.cfg yolov2.weights -i 0 -thresh 0.25 dog.jpg -ext_output

output from command line
Total BFLOPS 29.475
Loading weights from yolov2.weights...
 seen 32
Done!
dog.jpg: Predicted in 0.032002 seconds.
bicycle: 82%    (left: 119      top: 140        w: 451  h: 280)
dog: 82%        (left: 125      top: 205        w: 195  h: 328)
bicycle: 25%    (left: 132      top: 143        w: 121  h: 82)
truck: 74%      (left: 447      top: 84         w: 258  h: 90)

**Comment by saudet** [comment]
Run detect() a few times in a loop to warm up the JVM.

Also, the value printed out by darknet does not include loading time:
https://github.com/pjreddie/darknet/blob/master/examples/super.c#L91-L94

You'll need to compare the same thing to get meaningful results!

**Comment by holger-prause** [comment]
Uhm i was asked explicitly to create thich ticket, took my some time. 

* The answer with warming up was already tried out - as expected - no difference
* My program also does not included loading time - so comparing values is valid!

Anyway, thx for you help - i am regarding this as "solved" and will come back later on deeplearnnig4j.
The api looks very clean to me - i am only concerned about the performance (with some good reasons)

**Comment by AlexDBlack** [comment]
Yeah, I don't consider this closed, and intend to look into this more at some point.

**Comment by AlexDBlack** [comment]
@holger-prause That said, how *exactly* are you running this for DL4J?
What exact commands are you using to benchmark the DL4J code?

> The answer with warming up was already tried out - as expected - no difference
My program also does not included loading time - so comparing values is valid!

I'm not seeing any evidence of either in the codebase you have provided...

**Comment by saudet** [comment]
> The answer with warming up was already tried out - as expected - no difference

Thanks for pointing this out! It didn't seem to me that you had given this much thought, sorry about that.

**Comment by holger-prause** [comment]
@AlexDBlack 
I am not at home anymore but can provide the exact java command with the vm options used.
Il adoptes the code base(in my example) to warm up.

If i remember right - when i did testing i warmed up the model **before serializing**. So that could been an error.I run from within the idea ide(another error?) with vm arguments -Xms3500m -Xmx3500m
I can try build an uber jar and execute from commandline.

**Comment by holger-prause** [comment]
I will give it one more try - even when that means installaing 9.1 cuda again (sucks on windows )
Then i will execute from command line with maven without any other background program running.
I dont have big hopes anything changes but i will do it anyway as this is the correct way.
Will take me some time(1-2 days as i am not home) - and then update issue.

@saudet 
No problem i am happy for any help i can get
