### ISSUE TITLE
Performance regression in 1.0.0-beta vs 0.9.1

### ISSUE THREAD

**Issue by DrChainsaw** [deeplearning4j/deeplearning4j#5286]
I get substantially longer training and inference times with 1.0.0 beta vs 0.9.1. In particular training with Nesterovs updater (!) is up to 2.4 times slower compared to 0.9.1. 

OS: Windows
CUDA: Tested with CUDA 8.0 and cudnn 6.0 and with CUDA 9.0 and cudnn 7.0
GPU: GTX 980 TI

Test code:
https://gist.github.com/DrChainsaw/a1c22c289bbbbfa06cc5c568cd3c3759

Output 1.0.0-beta (CUDA 8.0):
https://gist.github.com/DrChainsaw/4c1e4d9c1f779a7b1c260296fa4bda04

Output 0.9.1:
https://gist.github.com/DrChainsaw/d25364d1eff1ba37995577cbd5d58370

**Comment by AlexDBlack** [comment]
Thanks for the report. I'll close this in favour of this issue: https://github.com/deeplearning4j/deeplearning4j/issues/5288
I do plan on running your configuration as part of these investigations, though note that I'm not seeing anywhere near the 2+x slower on the configurations I've benchmarked thus far.

**Comment by DrChainsaw** [comment]
Awesome! Figures in #5288 match what I see except for when Nesterovs updater is used. There's gotta be something fishy with it. Changing from adam to Nesterovs while keeping everything else intact gives me a factor 2 training slowdown in 1.0.0 beta.
