### ISSUE TITLE
ND4J: linearViewColumnOrder return wrong shape

### ISSUE THREAD

**Issue by frakc** [deeplearning4j/deeplearning4j#5294]
In javaDoc of linearViewColumnOrder() its stated
      Returns a linear view reference of shape
      1,length(ndarray)
http://joxi.ru/n2YQnnnuoeBGp2

When i used it
```kotlin
   log("sub ${sub.shapeInfoToString()}")
   val cView = sub.linearViewColumnOrder()
   log("cView ${cView.shapeInfoToString()}")
```
I recive following log messages
```
sub Rank: 2,Offset: 0
 Order: c Shape: [76,36],  stride: [36,1]
cView Rank: 2,Offset: 0
 Order: c Shape: [76,36],  stride: [36,1]
```
while according to docs it should be [1,2736]

version 0.91

**Comment by AlexDBlack** [comment]
These methods were deprecated on master recently.
We'll remove them entirely in a future release.
