### ISSUE TITLE
ND4J: unclear javadoc

### ISSUE THREAD

**Issue by frakc** [deeplearning4j/deeplearning4j#5295]
What is difference between those 2 methods? They have same description
http://joxi.ru/n2YQnnnuoeBGp2
```java
    /**
     * Returns a linear view reference of shape
     * 1,length(ndarray)
     *
     * @return the linear view of this ndarray
     */
    INDArray linearView();



    /**
     * Returns a linear view reference of shape
     * 1,length(ndarray)
     *
     * @return the linear view of this ndarray
     */
    INDArray linearViewColumnOrder();
```
version 0.91

**Comment by AlexDBlack** [comment]
I've decided to deprecate both methods here: https://github.com/deeplearning4j/deeplearning4j/pull/5623
They are (IMO) misleading: the methods will sometimes return a view, and sometimes not (instead, returning a copy), which is a usability trap for users.
