### ISSUE TITLE
DL4J/ND4J: Serialization (spark tests, maybe elsewhere) spamming serialization messages

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5297]
![image](https://user-images.githubusercontent.com/2360237/40400250-ab5c824e-5e84-11e8-86da-15f0aa092a28.png)

This is probably related to long shapes. However, as far as I can tell there is *not* any datatype issues here - i.e., it should all be double precision.

**Comment by saudet** [comment]
It's happening for me when deserializing "compressed" arrays. This isn't new though, it's been doing that before as well.

**Comment by AlexDBlack** [comment]
I can confirm that this is still happening on current master.
