### ISSUE TITLE
ND4J: add ClassPathResource "extract folder, recursively" method

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5298]
Thit would simplify many tests - for example, Spark tests.

**Comment by AlexDBlack** [comment]
Added here: https://github.com/deeplearning4j/deeplearning4j/pull/5300

**Comment by saudet** [comment]
That was already in JavaCPP with `Loader.extractResource()`...

**Comment by AlexDBlack** [comment]
@saudet Ah, looks pretty similar in how it works. Too late now though :)

**Comment by saudet** [comment]
Though there is a `Loader.cacheResource()` as well that extracts in `~/.javacpp/cache` by default, but doesn't delete, which saves time the next time we need the same resources.
