### ISSUE TITLE
libnd4j cpu build failing on Windows

### ISSUE THREAD

**Issue by farizrahman4u** [deeplearning4j/deeplearning4j#5316]
`./buildnativeoperations.sh` returns:

```bash
/bin/sh: /C/msys64/mingw64/bin/ar.exe: Argument list too long


make[2]: *** [blas/CMakeFiles/nd4jcpu.dir/build.make:10914: blas/libnd4jcpu.dll] Error                                                                                                                          126
make[2]: Leaving directory '/c/users/fariz/Documents/Github/deeplearning4j/libnd4j/bla                                                                                                                         sbuild/cpu'
make[1]: *** [CMakeFiles/Makefile2:89: blas/CMakeFiles/nd4jcpu.dir/all] Error 2
make[1]: Leaving directory '/c/users/fariz/Documents/Github/deeplearning4j/libnd4j/bla                                                                                                                         sbuild/cpu'
make: *** [Makefile:153: all] Error 2


```

cmake version 3.10.0-rc5

gcc 7.2.0

**Comment by treo** [comment]
Did you do anything special? I've built libnd4j several times on windows today, and I didn't have any problems at all.

**Comment by wmeddie** [comment]
I'm also getting it now:

```
egonz@XPS15 MINGW64 /c/Src/skymind/deeplearning4j/libnd4j
$ ./buildnativeoperations.sh -c cuda -cc 61 && ./buildnativeoperations.sh -a native -c cpu
eval cmake
Running windows
PACKAGING = none
BUILD = release
CHIP = cuda
ARCH = x86-64
CHIP_EXTENSION =
CHIP_VERSION =
GPU_COMPUTE_CAPABILITY = 61
EXPERIMENTAL = no
LIBRARY TYPE = dynamic
OPERATIONS = -DLIBND4J_ALL_OPS=true
MINIFIER = false
NAME = -DLIBND4J_NAME=nd4jcuda
/c/Src/skymind/deeplearning4j/libnd4j/blasbuild/cuda
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

```

**Comment by wmeddie** [comment]
Same terminal builds my previous libnd4j checkout just fine though.

**Comment by AlexDBlack** [comment]
@wmeddie yours looks different:
> CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

**Comment by AlexDBlack** [comment]
@wmeddie run this and try again:
> pacman -S mingw-w64-x86_64-ninja

**Comment by farizrahman4u** [comment]
@wmeddie You seem to be doing a cuda build, can you try cpu?

**Comment by wmeddie** [comment]
Oh, didn't notice the new requirement.  Cuda seems to be building now.  I'll check cpu.

**Comment by wmeddie** [comment]
CPU builds just fine for me.

**Comment by treo** [comment]
One thing that may be different between us: I've moved my dl4j build environment to something that isn't as deeply nested, after I noticed that `git gc` has problems with some files due to their too long absolute file names.

`/c/users/fariz/Documents/Github/deeplearning4j` may be a too long prefix,
`/c/Src/skymind/deeplearning4j` seems to work for @wmeddie 
`/F/dl4j-builds/deeplearning4j` is what I'm using. 

It probably isn't that, but it is something that you can try quickly.

**Comment by farizrahman4u** [comment]
Fixed. Closing.
