### ISSUE TITLE
ParameterAveragingTrainingMaster Builder has no collectTrainingStats property

### ISSUE THREAD

**Issue by turambar** [deeplearning4j/deeplearning4j#5320]
Whereas the SharedTrainingMaster builder class has a "collectTrainingStats" property ([line 992](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-scaleout/spark/dl4j-spark-parameterserver/src/main/java/org/deeplearning4j/spark/parameterserver/training/SharedTrainingMaster.java#L992)) which it passes along to the SharedTrainingMaster constructor ([line 1215](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-scaleout/spark/dl4j-spark-parameterserver/src/main/java/org/deeplearning4j/spark/parameterserver/training/SharedTrainingMaster.java#L1215)), it appears the ParameterAveragingTrainingMaster builder class does not ([lines 889-904](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-scaleout/spark/dl4j-spark/src/main/java/org/deeplearning4j/spark/impl/paramavg/ParameterAveragingTrainingMaster.java#L904)).

Is this intentional, or should we add one? For now, my workaround is to use the setCollectTrainingStats setter method in the TrainingMaster object to manually set it.

If confirmed the builder should have one, I can whip up a PR.

**Comment by turambar** [comment]
@raver119 @AlexDBlack

**Comment by AlexDBlack** [comment]
Sure, go ahead and add it if you want. :)
