### ISSUE TITLE
Mono repo maven build: libnd4j test run as part of normal build

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5337]
Currently, libnd4j tests are being run as part of a normal maven build with -DskipTests

Partial build log:
https://gist.github.com/AlexDBlack/6d89bf55db1d044175ed385be55a7a57

**Comment by saudet** [comment]
I guess the best way to fix this is to create a profile in the pom.xml file of libnd4j that activates on that property and skips the execution.

**Comment by AlexDBlack** [comment]
Yeah, we've got that mechanism here for ND4J test resources, shouldn't be hard to adapt it:
https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/pom.xml#L69-L91
