### ISSUE TITLE
Mono repo: fix maven project structure warnings

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5338]
First few lines of standard build:
https://gist.github.com/AlexDBlack/e71e062036e91655e076719f60c486e7

**Comment by saudet** [comment]
I guess the best way to fix this is to create a profile in the pom.xml file of libnd4j that activates on that property and skips the execution.

**Comment by saudet** [comment]
I'd say that is a duplicate of #5314 ...

**Comment by AlexDBlack** [comment]
Not really IMO. You could move all the dependency version properties and still not fix this :)
But yes, it would make sense to fix both simultaneously.

**Comment by saudet** [comment]
We need to update all the `<parent>` elements or they won't be able to pick up the versions from that pom.xml file!

**Comment by AlexDBlack** [comment]
Fixed a while ago.
