### ISSUE TITLE
Save Memory Cell activation as parameters for GravesLSTM Layer

### ISSUE THREAD

**Issue by drlebedev** [deeplearning4j/deeplearning4j#534]
Current GravesLSTM layer implementation do not keep memory cells state as parameters. It means that multiple fit calls does not make sense for GravesLSTM-based network. 

Saving last time series activations would allow to implement truncated BPTT with multiple time series (in case sizes of time series match).

**Comment by AlexDBlack** [comment]
See: https://github.com/deeplearning4j/deeplearning4j/issues/642
