### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by rahul-raj** [deeplearning4j/deeplearning4j#5344]
I had to add the below dependency in order to avoid the mentioned error on console:
```
<dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.25</version>
</dependency>
```

I see that `SLF4J` api is already added in external dependencies, but still getting: `"SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"` and hence logs are not displayed on console.
Once the above mentioned workaround (additional maven dependency on pom.xml) has been added, everything works properly.  Wondering why logger is not working even if dependency jars are present.

**Comment by AlexDBlack** [comment]
This is not related to DL4J.
slf4j is a widely use logging framework.
It needs a logging backend (logback, log4j, etc), which is configurable. You've added one.

Have a read: https://www.slf4j.org/
