### ISSUE TITLE
Create build/run script for libnd4j tests

### ISSUE THREAD

**Issue by sshepel** [deeplearning4j/deeplearning4j#5365]
While implementing logic for tests stage in CI pipeline, have been noticed that most of the test parameters for the scripts are not platform specific. Spent several days on debugging this with @raver119.

Ideally we need to have smth like `buildnativeoperations.sh` to build and run tests for specific platform.

**Comment by saudet** [comment]
I think it could it work by adding a couple of commands at the end of `buildnativeoperations.sh`?

**Comment by sshepel** [comment]
Could be an option too...
