### ISSUE TITLE
Libnd4j: Add reduction backprop ops

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5390]
Currently they are mostly (all?) of the SameDiff reduction op backprop logic is defined in Java, which is bad for a few reasons:
(a) worse performance (multiple vs. 1 op)
(b) less clear (we might have say 3 ops that are really just 1 op), harder to debug
(c) Some are problematic: like the "n" value here isn't dynamic but needs to be: https://github.com/deeplearning4j/deeplearning4j/blob/74bd70162979bace33cf28b160aeb61131e13bcc/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/accum/Mean.java#L86

In terms of priority for implementation
Initially: backprop for mean, sum, stdev, variance, prod (inc. reductions along dimension)
Second: Min, Max, Dot, Norm1/2/Max, cumsum, cumprod
Finally: the rest

**Comment by AlexDBlack** [comment]
Thanks for the work on implementing these ops @shugeo @shyrma @raver119 
I've merged some tests for the new reduction backprop ops here: https://github.com/deeplearning4j/deeplearning4j/pull/5513

Here's current status, for the tests that have been implemented thus far:

Passing:
* Full array reduce for mean and sum ops

Failing:
* Mean and sum along dimension 0 and 1
* Full array reduce for min/max/prod (looks like incorrect validation to me)

---
Tests:
https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/autodiff/opvalidation/ReductionOpValidationTests.java

testReduceSumAlongDim0
```
java.lang.AssertionError: expected null, but was:<Output 0 failed: INDArray equality failed:
Expected:
[[    1.0000,    2.0000,    3.0000,    4.0000], 
 [    1.0000,    2.0000,    3.0000,    4.0000], 
 [    1.0000,    2.0000,    3.0000,    4.0000]]
Actual:
[[         0,         0,         0,         0], 
 [         0,         0,         0,         0], 
 [         0,         0,         0,         0]]>
```

testReduceSumAlongDim1
```
java.lang.AssertionError: expected null, but was:<Output 0 failed: INDArray equality failed:
Expected:
[[    1.0000,    1.0000,    1.0000,    1.0000], 
 [    2.0000,    2.0000,    2.0000,    2.0000], 
 [    3.0000,    3.0000,    3.0000,    3.0000]]
Actual:
[[         0,         0,         0,         0], 
 [         0,         0,         0,         0], 
 [         0,         0,         0,         0]]>
```

testMeanAlongDim0
```
java.lang.AssertionError: expected null, but was:<Output 0 failed: INDArray equality failed:
Expected:
[[    0.3333,    0.6667,    1.0000,    1.3333], 
 [    0.3333,    0.6667,    1.0000,    1.3333], 
 [    0.3333,    0.6667,    1.0000,    1.3333]]
Actual:
[[    0.3333,    0.3333,    0.3333,    0.3333], 
 [    0.3333,    0.3333,    0.3333,    0.3333], 
 [    0.3333,    0.3333,    0.3333,    0.3333]]>
```

testMeanAlongDim1
```
Mismatched shape: [1, 3, 1, 0, 1, 99]
Shape requested: : {1, 1}
o.n.l.c.n.o.NativeOpExecutioner - Failed to execute op reduce_mean_bp. Attempted to execute with 2 inputs, 1 outputs, 0 targs and 2 iargs. Please see above message (printed out from c++) for a possible cause of error.
```

testMax/Min/Prod (same error for all)
```
Error at [C:/DL4J/Git/deeplearning4j/libnd4j/include/ops/declarable/generic/parity_ops/reduce_max.cpp:53:0]:
reduce_max_bp: The second param shape should be the same as result shape.
o.n.l.c.n.o.NativeOpExecutioner - Failed to execute op reduce_max_bp. Attempted to execute with 2 inputs, 1 outputs, 0 targs and 1 iargs. Please see above message (printed out from c++) for a possible cause of error.
```

**Comment by shyrma** [comment]
Thanks Alex for your check!
Should say @shugeo  merged file with function reduce_mean (written by my me) by mistake.
We have to remove file reduce_mean.cpp from master at all.
Functions mean, stdev, variance are currently in my branch shyrma_reduce_mean and they are correct for ff case and for bp case they need numbers to be checked with.

**Comment by shyrma** [comment]
Alex, seems like we have discrepancies in our formulas for variance and stdev derivatives.
Please find my corresponding letter sent on your mailbox. 
Please let me know your opinion concerning this.

**Comment by AlexDBlack** [comment]
@shyrma I have replied via email.

**Comment by shugeo** [comment]
norm1/2/max/squared backprops are ready to be used. After merging.

**Comment by shugeo** [comment]
Cumsum backprop op alredy done with PR #5573

**Comment by shugeo** [comment]
reduce_sum_bp, reduce_prod_bp, reduce_dot_bp, reduce_min_bp, reduce_max_bp, reduce_norm1_bp, reduce_norm2_bp, reduce_norm_max_bp, reduce_sqnorm_bp, cumsum_bp ops are implemented with libnd4j.

**Comment by AlexDBlack** [comment]
Thanks @shugeo and @shyrma 
Looks like everything except cumprod backprop is done, which is lower priority - I'll close this and add a note elsewhere about it.
