### ISSUE TITLE
MKL DNN

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#5394]
MKL DNN support to be added.

https://github.com/intel/mkl-dnn

**Comment by saudet** [comment]
Sure, we've got bindings for Java:
https://github.com/bytedeco/javacpp-presets/tree/master/mkl

**Comment by AlexDBlack** [comment]
From the mkl-dnn github readme:

> DNN functionality optimized for Intel architecture is also included in Intel(R) Math Kernel Library (Intel(R) MKL). API in this implementation is not compatible with Intel MKL-DNN and does not include certain new and experimental features.

So yes, the MKL binding do include some features - but we might be better off having it as a separate mkl-dnn dependency so we have better control over the versions?

**Comment by saudet** [comment]
These 2 libraries are incompatible, and as far as I could see, the APIs they implement have no overlap either. They appear completely unrelated. We should probably look closely at both and pick the one that works best.

**Comment by saudet** [comment]
Although it seems like everyone is using that one:

> Intel MKL-DNN is used in the the following software products:
> 
>     Caffe* Optimized for Intel Architecture
>     DeepBench
>     PaddlePaddle*
>     Tensorflow*
>     Microsoft* Cognitive Toolkit (CNTK)
>     Apache* MXNet
>     Intel(R) Computer Vision SDK
>     Intel(R) Nervana(TM) Graph
>
