### ISSUE TITLE
Deprecate DL4J Word2Vec for fastText?

### ISSUE THREAD

**Issue by tom-adsfund** [deeplearning4j/deeplearning4j#5395]
I've seen several people asking questions about w2v on chat, and there are many open issues, and I wonder whether you should deprecate w2v and point people in the direction of fastText.

fastText has many benefits above w2v: subword correlations, generate vectors for new words, generate vectors for sentences, extremely fast implementation.

Just seems pointless to continue supporting something that uses so much developer time.

**Comment by raver119** [comment]
You're welcome to send us PR.

Questions about w2v are usually not related to w2v itself, but memory and loaders related.

**Comment by tom-adsfund** [comment]
fastText produces word2vec style vector files, so it's more a documentation thing?

Beyond that it's something that keeps coming to mind that I wanted to share, rather than go further submitting pull requests etc.

**Comment by raver119** [comment]
Sorry, what do you mean by "documentation thing"?

How users are supposed to build their models, if they want specific model? They should be sent to facebook for generally the same skip-gram model called fastText? 

How exactly "documentation thing" is supposed to generate vectors for unseen-before words, without actual implementation code?

Sorry, i'm really not sure, what do you mean by "documentation thing" in this case.

**Comment by tom-adsfund** [comment]
fastText is a tool to create word vectors, but also sentence vectors, and many other things to do with word vectors.

The point is I suggest it's better to let fastText handle word vector generation, and just remove that functionality from dl4j. Because fastText does it to a much higher level -- because they specialize in it.

So the "documentation thing" is to deprecate the Word2Vec generation examples and code in DL4J, and say "see fastText [with link] for generation of word vectors".

**Comment by raver119** [comment]
Good point. I hope one day Google will get the same idea, and deprecate Android. 

Apple does it to a much higher level - because they specialize in it.

**Comment by tom-adsfund** [comment]
That analogy makes no sense.

Here's a better analogy: fastText vectors are superior to w2v vectors in the same way Darknet is superior to VGG.

(Android and iOS aren't comparable because they have different use cases.)

**Comment by tom-adsfund** [comment]
@AlexDBlack Please look at this, because @raver119 is still angry I said C wasn't a good language.

(Btw, C is a fine language, just not something I use much or personally gain much utility from.)

**Comment by raver119** [comment]
In any way - it's not a way of solving problems. Differences should drive competition. With this logic everything out there can be deprecated: dl4j, keras, chainer, pytorch - we should just all use TF and be happy.
 
Programming languages should be all deprecated too, in favor of C++.

**Comment by raver119** [comment]
> Please look at this, because @raver119 is still angry I said C wasn't a good language.

That's a bit of surprising statement. I don't even remember who you are.

**Comment by raver119** [comment]
P.s. sorry. Just too many people around.

**Comment by tom-adsfund** [comment]
@raver119 Things that are superceded *in their use case* should be deprecated.

And of course you remember me. It's not a big deal.

C and C++ are great. For their use case! Otherwise why wouldn't DL4J just use Java throughout?? Java doesn't give access to AVX for important matrix math... doesn't give access to many useful things. So Java is useless for that.

But w2v is worse than fastText. That I won't change my mind about!

**Comment by agibsonccc** [comment]
Hey folks - I'm locking this. @tom-adsfund I agree with @raver119 - the proper solution would be for us to add support for fast text, not "deprecate" word2vec.  We can definitely add it. As of right now it would have to be a pull request though. We can maybe look adding support for adding that file format. I'll keep this issue open as the point stands.

**Comment by AlexDBlack** [comment]
@tom-adsfund 
> @AlexDBlack Please look at this, because @raver119 is still angry I said C wasn't a good language.

Keep it professional or I won't hesitate to ban you from interacting with this repository.

Now, as for the question of FastText - that's an internal roadmap question and question of priorities. Deprecating W2V is a moot point until we have support for it. Even then, I don't see why we should deprecate something functional just because something better is around.
