### ISSUE TITLE
DL4J Zoo: Darknet Labels are wrong

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5398]
The DarkNet network has 1000 outputs, but the label files - imagenet.labels.list and imagenet.shortnames.list have 21,842 entries.

**Comment by saudet** [comment]
It's not a bug, it uses the first 1000 ones. If we were to implement YOLO 9000, for example, it would use the next 8000 as well.

**Comment by AlexDBlack** [comment]
Hm, not sure I like that. But OK, I'll implement a workaround for the validation.

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/5399
