### ISSUE TITLE
TrainingListener#onEpochStart and onEpochEnd not called from ComputationGraph

### ISSUE THREAD

**Issue by DrChainsaw** [deeplearning4j/deeplearning4j#5407]
As title says. They seem to be called from MultiLayerNetwork but not from ComputationGraph.

Tested in 1.0.0-SNAPSHOT and 1.0.0-beta.

**Comment by AlexDBlack** [comment]
Thanks for reporting: confirmed and fixed here, with test: https://github.com/deeplearning4j/deeplearning4j/pull/5414
