### ISSUE TITLE
Problem with Zoo Model : FaceNetNN4Small2, Dense Layer "bottleneck" number of Inputs invalid 

### ISSUE THREAD

**Issue by Haitamz** [deeplearning4j/deeplearning4j#5408]
The Dense Layer "bottleneck" on the zooModel FaceNetNN4Small2 expects and input size of 2944, while setting an image to the input shape of (96,96,3) configured in the class only gets 736 before entering the bottleneck Layer !!

**Comment by AlexDBlack** [comment]
Thanks for the issue. This has been fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/5414
