### ISSUE TITLE
Aeron MaxMessageLength limit

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#5416]
Aeron has own max message length limit, which prevents sending messages with length above some threshold (rather small actually)

https://github.com/deeplearning4j/dl4j-examples/issues/628

**Comment by AlexDBlack** [comment]
OK, so I ran into this while training on Spark, thought I would try to gain some insights here
We have a few issues here:

Global max message length is 16MB: https://github.com/real-logic/aeron/blob/ab56167dfa2b4ac939ff3c2ffc83a8d4d4208da7/aeron-client/src/main/java/io/aeron/logbuffer/FrameDescriptor.java#L53-L57

Below that, it's a function of the term buffer length

According to my testing and the link below, it's term buffer length / 8:
Term buffer of 32MB: max message 4MB.
https://github.com/real-logic/aeron/blob/ab56167dfa2b4ac939ff3c2ffc83a8d4d4208da7/aeron-client/src/main/java/io/aeron/logbuffer/FrameDescriptor.java#L109-L118


So the naive solution here is to increase term buffer length to give us a 16MB max message length (8*16=128 term buffer).
(Note that it must be exactly a power of 2: https://github.com/real-logic/Aeron/wiki/Configuration-Options)
However, memory requirements seem to be a multiple of the term buffer... I was seeing a single log buffer of around 400mb when set to 128mb; 800mb when set to 256mb: https://github.com/deeplearning4j/deeplearning4j/issues/5814
I can't find any details on hard requirements (I don't even know if this is depends on configuration, it probably does)
only thing close is a "12x term buffer memory requirement" for akka: https://github.com/akka/akka/issues/21923#issuecomment-264707476
If that generalizes (again, no idea if it does) we'd need 1.5GB.

On spark executors, /dev/shm is 16GB, I'm seeing 5.9GB to ~16GB free (driver vs worker) there with one worker per node.
Given that the driver shouldn't have much in the way of memory use, we seem to be looking at much more than 1.5GB in practice: at 128mb buffer size, the driver throws an exception, but the workers are fine.

**Comment by raver119** [comment]
As discussed in pm: 
during N-rank implementation, we could just implement chunked messaging, and in this case we won't need longer messages at all.

**Comment by AlexDBlack** [comment]
Chunked messaging add a while ago now.
