### ISSUE TITLE
SameDiff: many unit tests are inadequate

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5417]
https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/autodiff/samediff/SameDiffTests.java#L247-L446

There's a whole lot of unit tests here that merely check the shape of the output, not the actual values.

There is currently something on master that is breaking SameDiff forward pass, and these sorts of tests are passing - giving a false sense of security when things are actually very broken...

**Comment by agibsonccc** [comment]
Yeah the basic tests there were actually to test the different op types. Equality of the results and the individual ops needs its own op testing framework.  At the time those tests were written all that was being tested was getting the individual test flows working for different op types. I wasn't going to write a bunch of 1 off equality tests for hundreds of ops without writing something reusable.

**Comment by AlexDBlack** [comment]
Yeah, that's fair enough.
I just hit a situation where every literally single gradient check was broken by a recent PR merge (not mine), but the vast majority of the other tests were still passing.
But yet, I think we need some sort of (very basic but reusable) framework here, if only to op track test coverage.

**Comment by AlexDBlack** [comment]
I'll close this.
This PR adds op forward pass validation with op coverage collection, so we can at least know where we stand as far as test coverage: https://github.com/deeplearning4j/deeplearning4j/pull/5453

Example output (only a few of the existing tests have been updated to use the framework)
```
o.n.a.v.OpValidation - *****************************************************
o.n.a.v.OpValidation - Op Validation:        10 of 360 classes with adequate tests (2.78% coverage)
o.n.a.v.OpValidation - Forward pass tests:   10 of 360 classes (2.78% coverage)
o.n.a.v.OpValidation - Gradient check tests: 13 of 313 classes (4.15% coverage)
o.n.a.v.OpValidation - (47 ops excluded from gradient check coverage information)
o.n.a.v.OpValidation - *****************************************************
```
