### ISSUE TITLE
SameDiff: Cache not invalidated by in-place INDArray modifications, later outputs incorrect

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5419]
This started today, was fine yesterday.

First exec is OK, subsequent ones are returning values from the original execution.

```
    @Test
    public void testOutMultiple(){

        SameDiff sd = SameDiff.create();

        SDVariable var = sd.var("in", Nd4j.linspace(1,5,5));
        SDVariable out = var.add(10);

        INDArray result = sd.execAndEndResult();

        assertEquals(Nd4j.linspace(1,5,5).addi(10), result);

        INDArray origArr = var.getArr();
        origArr.addi(100.0);

        result = sd.execAndEndResult();

        assertEquals(Nd4j.linspace(1,5,5).addi(110), result); //Fails here
    }
```

```
java.lang.AssertionError:
Expected :[[  111.0000,  112.0000,  113.0000,  114.0000,  115.0000]]
Actual   :[[   11.0000,   12.0000,   13.0000,   14.0000,   15.0000]]
```

The most likely cause is the changes here: https://github.com/deeplearning4j/deeplearning4j/pull/5410
(Of course, I could just revert that, but it should be possible to execute without duping the whole samediff instance)

Aha! Link: https://skymindai.aha.io/features/ND4J-172

**Comment by raver119** [comment]
cc @farizrahman4u

**Comment by farizrahman4u** [comment]
On it.

**Comment by raver119** [comment]
> but it should be possible to execute without duping the whole samediff instance

It's exactly the idea, we've discussed that with @farizrahman4u few times. And problem here - we actually need that cache in some legit use cases. So we need to distinguish these cases somehow. And do that reliably. 

Is it time to bring Sessions in? :)

**Comment by AlexDBlack** [comment]
Confirmed cause: faf27a37c8959e7c21ee92f531f14829e1ae7270 (Merge pull request #5373 from deeplearning4j/fr_fix_double_spending)

**Comment by farizrahman4u** [comment]
This is the fix:
https://github.com/deeplearning4j/deeplearning4j/pull/5421

Issue is this brings back double spending issue when final op has multiple outputs.
Possible solution: instead of calling `eval()` on each output variable, do a single `sd.exec()` followed by `getArr()` on each of the output variables.

**Comment by AlexDBlack** [comment]
I guess the question is why we have the eval() method in the first place, and what the semantics should be there. The Javadoc is non-specific:
> Evaluate the result of this variable


I don't think tracking array value changes (without changing the INDArray object associated with a SDVariable) is a good solution here.

So yeah, I think removing SDVariable.exec(), and having users use getArr() is the better solution here.
If need-be we can add a method for efficient partial graph execution in the future.

**Comment by farizrahman4u** [comment]
Lets keep `SDVariable.eval()`, which is basically `sd.exec()` + `SDVariable.getArr()`. It makes sense for single output variables.

**Comment by raver119** [comment]
variable.eval() is basically mimic of TF syntax, so everyone out there will be demanding it. so yes, we need it.

**Comment by raver119** [comment]
p.s. no, i'm not fan of eval(). i just think users are.

**Comment by AlexDBlack** [comment]
What's the TF equivalent of this situation? How is it handled there?

**Comment by farizrahman4u** [comment]
TF graphs are different - they dont have a standing array-variable association.

**Comment by farizrahman4u** [comment]
oops. deleted by mistake.

**Comment by AlexDBlack** [comment]
(For reference: question was "What's the TF equivalent of this situation?")

So yeah... the alternative is keep double spending, and properly document it.
So SDVariable.exec() + getArr() would be used for multiple outputs, or SameDiff.exec() + getArr()

**Comment by farizrahman4u** [comment]
TF is different - you can't manipulate a tf.Variable from numpy space.

**Comment by AlexDBlack** [comment]
OK, so to summarize the options as I see them:

1. Rejected: Remove SDVariable.exec()
2. Keep double spending, document it. Have users use getArr() for all other outputs... Definitely a performance trap for users, but at least results are correct
3. Keep cache, require a manual "invalidate" step if you do getArr().someInplaceOp()... a usability trap for users, not great
4. Array change tracking: https://3.basecamp.com/3684163/buckets/3725554/messages/1106912583

@raver119 what would be the performance overhead using your counters/timer? I mean we already have that sort of thing for CUDA...

**Comment by AlexDBlack** [comment]
Outdated - no longer relevant.
