### ISSUE TITLE
DL4J - ParagraphVectors: get relation between labels and words

### ISSUE THREAD

**Issue by readerLu** [deeplearning4j/deeplearning4j#5422]
Hello,

I am using the ParagraphVectors for classification of documents as shown in this example:
https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/paragraphvectors/ParagraphVectorsClassifierExample.java

On the website (https://deeplearning4j.org/doc2vec), it is written that "Doc2vec is an extension of word2vec that learns to correlate labels and words". My question is:
**Once I have the ParagraphVectors trained, how do I get the relation between labels and words?** In other words, I would like to find the words that are most important for a given label (both positive and negative correlations).

**Comment by raver119** [comment]
Check out original paper please.

**Comment by binyata** [comment]
@raver119  where could I find the original paper?

**Comment by raver119** [comment]
in google and arxiv.org

**Comment by raver119** [comment]
i.e. try to google `doc2vec paper`
