### ISSUE TITLE
DL4J: Add something equivalent to Keras' Lambda layer using SameDiff

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5431]
As per title.

**Comment by raver119** [comment]
We already have this issue, and it's more of JIT magic rather then DL4J layer.

We're almost ready to provide simple version of this for CPU backend, but for GPU backend there will be more low-level solution involved.

**Comment by AlexDBlack** [comment]
> We already have this issue, and it's more of JIT magic rather then DL4J layer.

I'm not following. What I want is a simple one-method way to define a no-param layer in DL4J, using SameDiff.
