### ISSUE TITLE
Tests: conv_5 graph problem

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#5432]
Unfortunately, `conv_5` graph has no practical use in tests, and won't be passing in nearest future.

Reason is: there's normal random used within, so unless we have the same rng as TF - results will be never the same.

cc @eraly

**Comment by eraly** [comment]
It looks like a bug in TF freeze_graph. The random normal is used the same way as with weights to generate initial values. It should get converted to a constant the same way but isn't.
