### ISSUE TITLE
DataSetIteratorSplitter easily misunderstandable

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#5437]
The constructor of this iterator takes a parameter called totalExamples, however, it actually wants the number of batches in the underlying iterator.

There are two things that could be done to make using it a bit more intuitive:
1. Change the parameter name
2. Add a validation in TrainIterator.hasNext which checks whether the counter has reached its expected trainNum when the underlying iterator returns false on its hasNext check. In that case an exception should be thrown that the iterator is misconfigured.

**Comment by raver119** [comment]
Fixed by renaming totalExamples -> totalBatches
