### ISSUE TITLE
ComputationGraph#addListeners overwrites existing listeners

### ISSUE THREAD

**Issue by DrChainsaw** [deeplearning4j/deeplearning4j#5442]
Adding listeners to addListeners overwrites any existing listeners. Inspecting the method reveals the cause:

            this.trainingListeners = new ArrayList<>(this.trainingListeners);   //To avoid immutable list issues
            Collections.addAll(this.trainingListeners, listeners);
            setListeners(listeners);

That last line should most likely be replaced by
`setListeners(this.trainingListeners);`

I can make you a PR if you want, but I'm sure it's 0 work for you to just snuck this in with the next commit or so.

I made you a unit test at least <3

    /**
     * Test that addListeners and setListeners works as expected
     */
    @Test
    public void testAddListeners() {
        final ComputationGraph dummyGraph = new ComputationGraph(new NeuralNetConfiguration.Builder()
                .graphBuilder()
                .addLayer("dummy2", new OutputLayer.Builder()
                        .nIn(1)
                        .nOut(1)
                        .build(), "dummy")
                .addInputs("dummy")
                .setOutputs("dummy2")
                .build());

        final TrainingListener[] expectOverWritten = new TrainingListener[] {new DummyListener(), new DummyListener()};
        final TrainingListener[] expectAdded = new TrainingListener[] {new DummyListener(), new DummyListener(), new DummyListener(), new DummyListener()};

        dummyGraph.addListeners(expectOverWritten);
        // How else can we know they are removed?
        assertArrayEquals("Incorrect listeners", expectOverWritten, dummyGraph.getListeners().toArray(new TrainingListener[]{}));
        dummyGraph.setListeners(expectAdded[0]);
        dummyGraph.addListeners(expectAdded[1]);
        dummyGraph.addListeners(expectAdded[2], expectAdded[3]);
        assertArrayEquals("Incorrect listeners!", expectAdded, dummyGraph.getListeners().toArray(new TrainingListener[]{}));
    }
    
    private final static class DummyListener extends BaseTrainingListener {
        // Just for maintainability reasons in case BaseTrainingListener gets abstract methods
    }

**Comment by AlexDBlack** [comment]
Thanks for reporting. Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/5506
