### ISSUE TITLE
No Class to decode predictions of models Trained on VGGFACE dataset

### ISSUE THREAD

**Issue by Haitamz** [deeplearning4j/deeplearning4j#5444]
Need a VggFaceLabels Class to decode predictions of models loaded with VGGFACE Pretrained Weights, like the class ImageNetLabels ..

**Comment by AlexDBlack** [comment]
Please don't open multiple issues for the same thing.
Duplicate: https://github.com/deeplearning4j/deeplearning4j/issues/5366
