### ISSUE TITLE
Loading gensim model

### ISSUE THREAD

**Issue by tvanh** [deeplearning4j/deeplearning4j#5449]
I got a pretrained word2vec created by gensim
`model = gensim.models.Word2Vec(sents, size=vector_size, min_count=min_count,
                               negative=num_negative, 
                               window=window_size)

model.save('data/{}.bin'.format(lcode))

# Save to file
with codecs.open('data/{}.tsv'.format(lcode), 'w', 'utf-8') as fout:
    for i, word in enumerate(model.index2word):
        fout.write(u"{}\t{}\t{}\n".format(str(i), word.encode('utf8').decode('utf8'),
                                          np.array_str(model[word])
                                          ))`

The file is here: https://drive.google.com/open?id=0B0ZXk88koS2KUHZZZkVwd1RoVmc
When I tried to load it wiht dl4j using
Word2Vec w2v = WordVectorSerializer.readWord2VecModel(modelFile);
I got the following error
13:41:53.972 [main] DEBUG org.deeplearning4j.models.embeddings.loader.WordVectorSerializer - Trying binary model restoration...
Exception in thread "main" java.lang.RuntimeException: Unable to guess input file format. Please use corresponding loader directly
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2480)
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.readWord2VecModel(WordVectorSerializer.java:2266)
	at anhtv.test.TestGensimModel.main(TestGensimModel.java:109)

The file is obtained from: https://github.com/Kyubyong/wordvectors

**Comment by raver119** [comment]
Your format isn't csv and isn't tsv.

**Comment by raver119** [comment]
p.s. look yourself:

```
1	và	[-0.63341701 -0.40656999  1.23062897 -0.56028771  0.72915047  0.79233116
  1.40788984 -0.8356216   0.36956063 -0.12304994  0.17514196 -0.3632347
  0.51964331 -0.12914668 -0.83008844 -0.66582841 -0.14022683 -0.58663243
  0.09874202 -0.05401522  0.96332264  0.41797063  0.95773989  1.02976739
 -1.08402634  0.37820396  0.35107595  0.47447217  0.73743689 -0.14591673
 -0.15633082 -0.24253748  1.39746916  0.02613848  0.21398614 -0.24736243
  0.33572137 -0.24606355 -0.52054381  0.28603029  0.42328745  0.02301144
  0.40196636  0.44905403  0.830872    0.13334419 -0.16774446  0.40007642
  0.92401469  0.47711042  0.89622295 -0.09253586 -0.68106163  1.20237935
 -0.08867151 -0.34487924  0.49972817  0.21445541  0.97405374  0.96620393
  1.39514387 -0.05756908 -0.40720588  0.40908626 -0.80101657 -0.42940599
 -0.43531469 -0.17259666 -0.29064065 -0.59524918  0.2241341   0.2193881
  0.88892269  0.77936065  0.88105631 -0.31894112  1.7112869   0.20213187
 -0.9722507   0.71398622 -0.30237648  0.43330419  0.44733948 -0.60705709
 -0.19233869  0.14690804 -0.52751184  1.42901015 -0.18308811  0.20824298
 -0.165535   -0.49288437 -0.29215455  0.01269365 -0.40614563 -0.56246942
  0.0869348  -0.46784317 -0.74504602 -0.55639863]
```

That's just not a format at all.

**Comment by tvanh** [comment]
I reformat the tsv file and I can be load perfectly.
But I need to load the bin file to get the neg0 for use the w2v on paragraphVector.
How can I laod the bin file.

**Comment by raver119** [comment]
No ideas sorry. I don't know what format gensim uses there.

**Comment by tvanh** [comment]
OK thanks
