### ISSUE TITLE
AnimalsClassification Example Needs to be updated

### ISSUE THREAD

**Issue by rahul-raj** [deeplearning4j/deeplearning4j#5455]
Deprecated usages to be updated:
https://github.com/deeplearning4j/dl4j-examples/blob/22f61c5f45c8723baf71fde19caf3a2d64185dc4/dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/AnimalsClassification.java

MultipleEpochsIterator -> MultiLayerNetwork.fit()

**Comment by saudet** [comment]
This sounds good too. Please send it as part of a pull request as well!

**Comment by rahul-raj** [comment]
Just sent a pull request for this, thanks!
