### ISSUE TITLE
AnimalsClassification Example -> BalancedPathFilter takes BatchSize instead of MaxPathsPerLabel

### ISSUE THREAD

**Issue by rahul-raj** [deeplearning4j/deeplearning4j#5462]
Here in this example:
https://github.com/deeplearning4j/dl4j-examples/blob/22f61c5f45c8723baf71fde19caf3a2d64185dc4/dl4j-examples/src/main/java/org/deeplearning4j/examples/convolution/AnimalsClassification.java

At line 98, attribute name might need to change to `maxPathsPerLabel` from `batchSize` to avoid any misunderstanding.  Let's say we have 1000 images for each label and we're thinking of `batchSize` of 10 for datasets. While passing `batchSize` here will yield 10x4 -> 40 images in total from all the labels instead of 4000 images.

**Comment by saudet** [comment]
Sounds good. Please send a pull request!

**Comment by rahul-raj** [comment]
@saudet 
I sent a pull request with other changes in the same file. While it is being reviewed, I will do some testing and send another pull request for this one.  Thank you!
