### ISSUE TITLE
Crash when I try to get sample the dataset

### ISSUE THREAD

**Issue by ragnarok22** [deeplearning4j/deeplearning4j#5477]
Hi guys! I have an issue. after load an image dataset i'm trying to get a sample using this:
`data.sample(10, true)`
`data` is a DataSet. It throws me the next error:
`java.lang.IllegalStateException: Rank is 4 columns() call is not valid`
How can I fix it? I use 0.9.1 version

**Comment by ragnarok22** [comment]
As I can see in the `sample()` method implementation, the first line called `getfeatures().columns()`. It seems that the `columns()` method is not supported for image data set since it is of 4 dimensions

**Comment by ragnarok22** [comment]
I thinks that the columns in a image dataset is `width * height * channels`

**Comment by raver119** [comment]
It's just some legacy method, that was written with regular fully-connected networks in mind. 

So it just should be updated for features/labels >2D

**Comment by ragnarok22** [comment]
how can i do that?

**Comment by ragnarok22** [comment]
as far I can see, this method never work with replacement because `Set<Integer> added` are queried but never updated

**Comment by AlexDBlack** [comment]
We need to update the code to do that.
In the mean time, you can use the .asList() + randomly sample using standard java RNG/list ops + DataSet.merge

**Comment by ragnarok22** [comment]
Thanks. I will try to do that way. Can you label this to bug and assign it?

**Comment by AlexDBlack** [comment]
@ragnarok22 I don't think people without write access will be able to assign, but we can. Did you want this assigned to you? (i.e., are you planning on submitting a fix?)

**Comment by ragnarok22** [comment]
I would gladly do it, but at this moment I am doing my undergraduate thesis and I do not have much time. Very soon I will be able to help you :)
