### ISSUE TITLE
Missing artifacts since update to javacpp 1.4.2

### ISSUE THREAD

**Issue by tonyjayfunk** [deeplearning4j/deeplearning4j#5481]
I think the update to javacpp presets 1.4.2 had impact on various modules.
Impossible for me to build on macosx.

<img width="854" alt="screen shot 2018-06-05 at 23 22 10" src="https://user-images.githubusercontent.com/5512644/41005976-85b22aec-6917-11e8-8330-e5d6c890f025.png">

Thanks for your help

**Comment by saudet** [comment]
Just clear your cache and rebuild everything from scratch. That will clear these kinds of errors.
