### ISSUE TITLE
ND4J: Failing to load MKL on Windows

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5503]
Following on from here: https://github.com/deeplearning4j/deeplearning4j/pull/5404#issuecomment-394949997

After rebuilding the full stack today (in the last hour) I'm still having issues loading MKL:

Output of running simple Nd4j.create(1) with ```-Dorg.bytedeco.javacpp.logger.debug -Dorg.bytedeco.javacpp.logger=slf4j``` and logging set to trace; javacpp cache dir was deleted first:
https://gist.github.com/AlexDBlack/3a533d145c13970abeb0107fb03f750a

```
c:\>where mkl_rt.dll
C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.1.156\windows\redist\intel64_win\mkl\mkl_rt.dll
```

I should note that DL4J examples (1.0.0-beta) does load MKL correctly: (again, I deleted cache dir first)
https://gist.github.com/AlexDBlack/6564f793ea9addc8929612473ced4161

**Comment by saudet** [comment]
It looks like it's loading OpenBLAS in addition to MKL, hum..

**Comment by saudet** [comment]
I'm pretty sure this is now fixed with commit https://github.com/bytedeco/javacpp/commit/4fb67229f8230f45f9a7d7fd6c17cb8dad6f26c8.

**Comment by AlexDBlack** [comment]
Success - back to loading MKL on master, after rebuilding today. Thanks @saudet 
```
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 8
o.n.n.Nd4jBlas - Number of threads used for BLAS: 8
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [16]; Memory: [7.1GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [MKL]
```
