### ISSUE TITLE
ND4J: 1x1 result of mmul is always zero

### ISSUE THREAD

**Issue by hohl** [deeplearning4j/deeplearning4j#5508]
The following code snippet always produces `0.0` (instead of `6.0 = 1*0.5+2*2+3*0.5`) as a result. In fact the `mmul` seems to always return 0.0 as long as the result is a scalar. On the other hand, `mmul` seems to work fine, when the result is a matrix. For example `a.transpose().mmul(b)` returns a 3x3 matrix with the correct results.

```
val a = Nd4j.create(doubleArrayOf(1.0, 2.0, 3.0))
val b = Nd4j.create(doubleArrayOf(0.5, 2.0, 0.5))
val actual = a.mmul(b.transpose())
assertEquals(1, actual.shape()[0])
assertEquals(1, actual.shape()[1])
assertEquals(6.0, actual.getDouble(0))
```

<img width="976" alt="bildschirmfoto 2018-06-07 um 14 18 03" src="https://user-images.githubusercontent.com/744417/41099051-a33b937c-6a5d-11e8-9bf6-a873d3fc826d.png">

I already asked in the Gitter chat if that's a known issue, but oddly it seems that this behavior doesn't appear on other machines. So here is my setup:

**OS:** macOS 10.13.4
**Java:** 10.0.1 (but also tested with 9.0.1 -> same result)
**ND4J-Version:** 1.0.0-beta
**ND4J-Backend:** nd4j-native-platform

And that's the output logged to the console:
```
14:15:49.019 [main] INFO  org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
14:15:49.696 [main] INFO  org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 4
14:15:50.654 [main] INFO  org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 4
14:15:50.660 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Mac OS X]
14:15:50.661 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [4,0GB];
14:15:50.661 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [MKL]
```

**Comment by AlexDBlack** [comment]
Another data point here, for debugging: I ran the the same code (converted to java) on my machine (Windows 10) on both master and 1.0.0-beta and was getting the correct result.

**Comment by raver119** [comment]
MKL + macOS bug?

**Comment by AlexDBlack** [comment]
Possibly. @hohl Are you able to run this without MKL, and see if you get the correct result when OpenBLAS (the default when MKL isn't installed) is used instead?

**Comment by saudet** [comment]
@hohl Set the "org.bytedeco.javacpp.openblas.nomkl" system property to "true" to run without MKL.

**Comment by hohl** [comment]
@saudet @AlexDBlack When disabling MKL the log says `OPENBLAS` is used and I get the correct results.

**Comment by raver119** [comment]
Wow. So yes, MKL bug then? :)

**Comment by saudet** [comment]
Yes, looks like it. @hohl Try again with MKL 2018.3, if you're not already using that?

**Comment by hohl** [comment]
I'm on MKL 2017.2, so give me a few minutes and I'll try MKL2018.3.

**Comment by hohl** [comment]
I get the correct results with MKL2018.3. So it seems that the bug has been caused by my outdated MKL version.

**Comment by AlexDBlack** [comment]
Huh, that's surprising, but thanks for checking.
I'm not sure there's much we can do about this on our end - so should we close the issue?

**Comment by saudet** [comment]
I don't know, docs maybe? Bundle MKL?

**Comment by AlexDBlack** [comment]
Problem with docs: most affected people simply won't see it.

Bundling MKL would be great, we've had that discussion before. It's non-trivial though, and doesn't solve the problem if we discover an issue after we release a version.

A more general solution: check versions of native libraries (MKL, CUDA, OpenBLAS?), and log a warning if one with known issues is found/loaded.
