### ISSUE TITLE
Unclear methods totalExamples(), numExamples() in DataSetIterator

### ISSUE THREAD

**Issue by DonaldAlan** [deeplearning4j/deeplearning4j#5511]
In `DataSetIterator` there are these two methods:
```
    public int totalExamples();{ // Total examples in the iterator
    public int numExamples(); //Total number of examples in the dataset
```
I presume `totalExamples()` returns the number of examples available for an epoch (NOT the number of batches).  Then what's numExamples()? It's not the batchSize, apparently. I think that it's supposed to refer to the number of examples in the _current_ `DataSet`. (The iteration may be at the end of the final batch and there may be fewer than batchSize elements available.)   The documentation is unclear, and the method name `numExamples` is confusing.   Please consider updating the documentation, renaming the method, or deprecating it.   It's a bit odd that `numExamples()` is a method on `DataSetIterator`; it belongs in `DataSet`.

**Comment by raver119** [comment]
With best regards,
Vyacheslav K.

**Comment by raver119** [comment]
2 these methods are legacy, and not really supported.

Actually, as i remember we were going to remove them before 1.0 release? cc @AlexDBlack

**Comment by AlexDBlack** [comment]
I'm certainly tempted to remove them, and that may be the fix.
It isn't a great API given that a sizeable fraction of iterators don't (or can't, really) implement these methods (and there's know way to know at runtime other than 'try and see if an exception is thrown')
