### ISSUE TITLE
DL4J UI - play.api.UnexpectedException: Unexpected exception[InvocationTargetException: null]

### ISSUE THREAD

**Issue by rahul-raj** [deeplearning4j/deeplearning4j#5519]
I'm getting an exception while running the UI. 
Here's the code:
I just hit http://localhost:9000/  once after the port is opened & UI is started.
Selected the latest session where UI is running at the moment:
![image](https://user-images.githubusercontent.com/517415/41141834-135bd924-6b11-11e8-9b63-7513b0d5f395.png)
And I got these results:
https://gist.github.com/rahul-raj/e44859ec607a3641af98261546355f8f

![image](https://user-images.githubusercontent.com/517415/41141894-608bcb14-6b11-11e8-8e3e-e1937af722f7.png)

**Comment by AlexDBlack** [comment]
Turns out you didn't actually include any code (looks like you intended to?)
I'm unable to reproduce this without some code (I tried a couple of things based on the stack trace, but everything runs fine for me)

**Comment by rahul-raj** [comment]
Since it was giving me error, I removed those block of code to go ahead and execute my code with other changes. Here you can find actual code that has UI in it:
https://github.com/rahul-raj/Deeplearning4J/blob/f301784719dcfd7df84b14ece6ab13d5f6eb447c/src/main/java/DeepLearning4j.java

**Comment by AlexDBlack** [comment]
I still haven't been able to reproduce this. But looking at the stack trace again, the only thing this can be is a concurrent modification issue. I've implemented a check to avoid this here: https://github.com/deeplearning4j/deeplearning4j/pull/5947
