### ISSUE TITLE
Different accuracy for simple Iris model with GPU and CPU

### ISSUE THREAD

**Issue by mzattera** [deeplearning4j/deeplearning4j#5546]
Hi

As my first step into DL4J I wrote a very simple classifier example using the Iris dataset.

The classifier has 100% accuracy when the model is trained with CPU but only 83.3% when trained with GPU.

OS: Windows 10

JDK 1.8

DL4J downloaded from GirHub on June 9th, 2018:

GPU: GeForce GTX 1070 CUDA 9.0.176 cuDNN 7

**GPU Results:**

19:28:38.606 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
19:28:38.606 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [12]; Memory: [3.5GB];
19:28:38.606 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [CUBLAS]
19:28:38.606 [main] INFO org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner - Device Name: [GeForce GTX 1070]; CC: [6.1]; Total/free memory: [8589934592]

Evaluation Metrics
 Accuracy:        0.8333
 Precision:       0.8333
 Recall:          0.9074
 F1 Score:        0.8351

**CPU results:**

19:26:48.305 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
19:26:48.305 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [12]; Memory: [3.5GB];
19:26:48.305 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [OPENBLAS]

Evaluation Metrics
 Accuracy:        1.0000
 Precision:       1.0000
 Recall:          1.0000
 F1 Score:        1.0000

**Comment by raver119** [comment]
Could you please edit your issue and use https://gist.github.com for code? 
Also, could you please include your pom.xml?

**Comment by mzattera** [comment]
...maybe related to #4475

**Comment by mzattera** [comment]
Code and pom.xml is here (I hope):  https://gist.github.com/mzattera/6cac8b98ff30373b003fd3b5dccd27ff.js

**Comment by raver119** [comment]
pom.xml is fine, with just 1 note: <artifactId>deeplearning4j-cuda-9.1</artifactId>
You should use deeplearning-cuda-9.0 artifact, the same cuda version as your cuda backend.

however, in this case your model isn't using cudnn.

**Comment by mzattera** [comment]
Yes, i realized it when looking at the pom.xml and I changed it to 9.0 without any noticeable effect.

**Comment by raver119** [comment]
That’s fine, your model isn’t using cuDNN. Just a sanity note

With best regards,
Vyacheslav K.

**Comment by AlexDBlack** [comment]
Turns out this is due to the data pipeline, not actually anything due to network training - see this issue (the shuffle method is used in split test and train) - https://github.com/deeplearning4j/deeplearning4j/issues/5563

If I manually shuffle/split the data instead, I am getting identical results on both CPU and CUDA (and 100% accuracy).
https://gist.github.com/AlexDBlack/cd0790a0d10e34ec4c02e0c8b4dd84ad

Thanks for reporting - I'll close this in favor of the shuffle issue linked to earlier.
