### ISSUE TITLE
Spark, ComputationGraph and MultiDataSet

### ISSUE THREAD

**Issue by Godman-quake** [deeplearning4j/deeplearning4j#5552]
Have anybody try EncodeDecodeLSTM on spark cluster?

**Comment by raver119** [comment]
What's your actual problem there?

**Comment by Godman-quake** [comment]
private final List<List<Double>> corpus = new ArrayList<>();

    private static final int HIDDEN_LAYER_WIDTH = 512; // this is purely empirical, affects performance and VRAM requirement
    private static final int EMBEDDING_WIDTH = 128; // one-hot vectors will be embedded to more dense vectors with this width
    private static final String CORPUS_FILENAME = "movie_lines.txt"; // filename of data corpus to learn
    private static final String MODEL_FILENAME = "rnn_train_movie.zip"; // filename of the model
    private static final String BACKUP_MODEL_FILENAME = "rnn_train_movie.bak.zip"; // filename of the previous version of the model (backup)
    private static final Random RND = new Random(new Date().getTime());
    private static final int MAX_DICT = 20000; // this number of most frequent words will be used, unknown words (that are not in the
    // dictionary) are replaced with <unk> token
    private static final int TBPTT_SIZE = 25;
    private static final double LEARNING_RATE = 1e-1;
    private static final double RMS_DECAY = 0.95;
    private static final int ROW_SIZE = 40; // maximum line length in tokens

    public static void main(String[] args) throws Exception {
        new EncdecMovie().entryPoint(args);
    }

    protected void entryPoint(String[] args) throws Exception { 
//Handle command line arguments
        JCommander jcmdr = new JCommander(this);
        try {
            jcmdr.parse(args);
        } catch (ParameterException e) {
            //User provides invalid input -> print the usage info
            jcmdr.usage();
            try {
                Thread.sleep(500);
            } catch (Exception e2) {
            }
            throw e;
        }
        createDictionary();

        //-------------------------------------------------------------
        
        //Set up Spark configuration and context
        SparkConf sparkConf = new SparkConf();
        if (useSparkLocal) {
            sparkConf.setMaster("local[*]");
        }
        sparkConf.setAppName("seq2seq");
        JavaSparkContext sc = new JavaSparkContext(sparkConf);

        JavaRDD<MultiDataSet> trainingData = getTrainingData(sc);

        int examplesPerDataSetObject = 1;
        int averagingFrequency = 3;
        ParameterAveragingTrainingMaster tm = new ParameterAveragingTrainingMaster.Builder(examplesPerDataSetObject)
                .workerPrefetchNumBatches(0)
                .averagingFrequency(averagingFrequency)
                .batchSizePerWorker(batchSizePerWorker)
                .build();

        SparkComputationGraph sparkGraph;

        if (HDFSUtil.existHDFSFile(saveModelPath)) {
            System.out.println("Model is existed, restore it from " + saveModelPath);
            ComputationGraph graphNetwork = ModelSerializer.restoreComputationGraph(HDFSUtil.getFSDataInputStream(saveModelPath), true);
            //Create the Spark network
            sparkGraph = new SparkComputationGraph(sc, graphNetwork, tm);
        } else {
            ComputationGraphConfiguration conf = createComputationGraph();
            sparkGraph = new SparkComputationGraph(sc, conf, tm);
        }
        sparkGraph.setListeners(Collections.<IterationListener>singletonList(new ScoreIterationListener(1)));
        try {
            for (int i = 0; i < numEpochs; i++) {
                System.out.println("Epoch " + i);
                long lastRunTime = System.currentTimeMillis();
                int totalBatches = corpus.size() / exampleLength;
                System.out.println("********GMBot current epoch[" + i + "] has [" + totalBatches + "] batches********");
                int lastPerc = 0;
                ComputationGraph net = sparkGraph.fitMultiDataSet(trainingData);
                saveModel(net);
                test(net);
                System.out.println("Finish Epoch[" + i + "] cost " + (int) ((System.currentTimeMillis() - lastRunTime) / 1000) + " seconds!");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //Delete the temp training files, now that we are done with them
        tm.deleteTempFiles(sc);

        System.out.println("\n\nExample complete");
    }
    private ComputationGraphConfiguration createComputationGraph() {
        final NeuralNetConfiguration.Builder builder = new NeuralNetConfiguration.Builder()
                .iterations(1)
                .learningRate(LEARNING_RATE)
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                .miniBatch(true)
                .updater(Updater.RMSPROP)
                .weightInit(WeightInit.XAVIER)
                .gradientNormalization(GradientNormalization.RenormalizeL2PerLayer);

        final ComputationGraphConfiguration.GraphBuilder graphBuilder = builder.graphBuilder()
                .pretrain(false)
                .backprop(true)
                .backpropType(BackpropType.Standard)
                .tBPTTBackwardLength(TBPTT_SIZE)
                .tBPTTForwardLength(TBPTT_SIZE)
                .addInputs("inputLine", "decoderInput")
                .setInputTypes(InputType.recurrent(dict.size()), InputType.recurrent(dict.size()))
                .addLayer("embeddingEncoder",
                        new EmbeddingLayer.Builder()
                                .nIn(dict.size())
                                .nOut(EMBEDDING_WIDTH)
                                .build(),
                        "inputLine")
                .addLayer("encoder",
                        new GravesLSTM.Builder()
                                .nIn(EMBEDDING_WIDTH)
                                .nOut(HIDDEN_LAYER_WIDTH)
                                .activation(Activation.TANH)
                                .build(),
                        "embeddingEncoder")
                .addVertex("thoughtVector", new LastTimeStepVertex("inputLine"), "encoder")
                .addVertex("dup", new DuplicateToTimeSeriesVertex("decoderInput"), "thoughtVector")
                .addVertex("merge", new MergeVertex(), "decoderInput", "dup")
                .addLayer("decoder",
                        new GravesLSTM.Builder()
                                .nIn(dict.size() + HIDDEN_LAYER_WIDTH)
                                .nOut(HIDDEN_LAYER_WIDTH)
                                .activation(Activation.TANH)
                                .build(),
                        "merge")
                .addLayer("output",
                        new RnnOutputLayer.Builder()
                                .nIn(HIDDEN_LAYER_WIDTH)
                                .nOut(dict.size())
                                .activation(Activation.SOFTMAX)
                                .lossFunction(LossFunctions.LossFunction.MCXENT)
                                .build(),
                        "decoder")
                .setOutputs("output");
        return graphBuilder.build();
    }

    /**
     * Get the training data - a JavaRDD<MultiDataSet>
     * Note that this approach for getting training data is a special case for
     * this example (modelling characters), and should not be taken as best
     * practice for loading data (like CSV etc) in general.
     *
     * @param sc
     * @return
     * @throws java.io.IOException
     */
    public JavaRDD<MultiDataSet> getTrainingData(JavaSparkContext sc) throws IOException, Exception {
        List<List<List<Double>>> list = getCorpusAsList(exampleLength);
        JavaRDD<List<List<Double>>> rddData = sc.parallelize(list);
        Map<String, Integer> STR_TO_INT = new HashMap<>();
        STR_TO_INT.put("rowSize", ROW_SIZE);//rowSize
        STR_TO_INT.put("dictSize", dict.size());//dictSize
        log.info("rowSize=" + STR_TO_INT.get("rowSize") + ", dictSize=" + STR_TO_INT.get("dictSize"));
        Broadcast<Map<String, Integer>> bcStrToInt = sc.broadcast(STR_TO_INT);
        return rddData.map(new ListToMultiDataSetFn(bcStrToInt));
    }

    private static class ListToMultiDataSetFn implements Function<List<List<Double>>, MultiDataSet> {

        private final Broadcast<Map<String, Integer>> bcStrIntMap;

        private ListToMultiDataSetFn(Broadcast<Map<String, Integer>> strIntegerMap) {
           this.bcStrIntMap = strIntegerMap;
        }

        @Override
        public MultiDataSet call(List<List<Double>> part) throws Exception {
            Map<String, Integer> strIntMap = bcStrIntMap.getValue();
            int curr_rowSize = strIntMap.get("rowSize");
            int curr_dictSize = strIntMap.get("dictSize");
            int dSize = part.size() / 2;
            int i = 0;
            INDArray input = Nd4j.zeros(dSize, 1, curr_rowSize);
            INDArray prediction = Nd4j.zeros(dSize, curr_dictSize, curr_rowSize);
            INDArray decode = Nd4j.zeros(dSize, curr_dictSize, curr_rowSize);
            INDArray inputMask = Nd4j.zeros(dSize, curr_rowSize);
            // this mask is also used for the decoder input, the length is the same
            INDArray predictionMask = Nd4j.zeros(dSize, curr_rowSize);
            for (int j = 0; j < dSize; j++) {
                List<Double> rowIn = new ArrayList<>(part.get(i));
                Collections.reverse(rowIn);
                List<Double> rowPred = new ArrayList<>(part.get(i + 1));
                rowPred.add(1.0); // add <eos> token
                // replace the entire row in "input" using NDArrayIndex, it's faster than putScalar(); input is NOT made of one-hot vectors
                // because of the embedding layer that accepts token indexes directly
                input.put(new INDArrayIndex[]{NDArrayIndex.point(j), NDArrayIndex.point(0), NDArrayIndex.interval(0, rowIn.size())},
                        Nd4j.create(ArrayUtils.toPrimitive(rowIn.toArray(new Double[0]))));
                inputMask.put(new INDArrayIndex[]{NDArrayIndex.point(j), NDArrayIndex.interval(0, rowIn.size())}, Nd4j.ones(rowIn.size()));
                predictionMask.put(new INDArrayIndex[]{NDArrayIndex.point(j), NDArrayIndex.interval(0, rowPred.size())},
                        Nd4j.ones(rowPred.size()));
                // prediction (output) and decode ARE one-hots though, I couldn't add an embedding layer on top of the decoder and I'm not sure
                // it's a good idea either
                double predOneHot[][] = new double[curr_dictSize][rowPred.size()];
                double decodeOneHot[][] = new double[curr_dictSize][rowPred.size()];
                decodeOneHot[2][0] = 1; // <go> token
                int predIdx = 0;
                for (Double pred : rowPred) {
                    predOneHot[pred.intValue()][predIdx] = 1;
                    if (predIdx < rowPred.size() - 1) { // put the same vals to decode with +1 offset except the last token that is <eos>
                        decodeOneHot[pred.intValue()][predIdx + 1] = 1;
                    }
                    ++predIdx;
                }
                prediction.put(new INDArrayIndex[]{NDArrayIndex.point(j), NDArrayIndex.interval(0, curr_dictSize),
                    NDArrayIndex.interval(0, rowPred.size())}, Nd4j.create(predOneHot));
                decode.put(new INDArrayIndex[]{NDArrayIndex.point(j), NDArrayIndex.interval(0, curr_dictSize),
                    NDArrayIndex.interval(0, rowPred.size())}, Nd4j.create(decodeOneHot));
                ++i;
            }
            return new org.nd4j.linalg.dataset.MultiDataSet(new INDArray[]{input, decode}, new INDArray[]{prediction},
                    new INDArray[]{inputMask, predictionMask}, new INDArray[]{predictionMask});
        }
    }

    private void createDictionary() throws IOException, FileNotFoundException {
        double idx = 3.0;
        dict.put("<unk>", 0.0);
        revDict.put(0.0, "<unk>");
        dict.put("<eos>", 1.0);
        revDict.put(1.0, "<eos>");
        dict.put("<go>", 2.0);
        revDict.put(2.0, "<go>");
        for (char c : CHARS.toCharArray()) {
            if (!dict.containsKey(c)) {
                dict.put(String.valueOf(c), idx);
                revDict.put(idx, String.valueOf(c));
                ++idx;
            }
        }
        System.out.println("Building the dictionary...");
        CorpusProcessor corpusProcessor = new CorpusProcessor(getDataPath(CORPUS_FILENAME), ROW_SIZE, true);
        corpusProcessor.start();
        Map<String, Double> freqs = corpusProcessor.getFreq();
        Set<String> dictSet = new TreeSet<>(); // the tokens order is preserved for TreeSet
        Map<Double, Set<String>> freqMap = new TreeMap<>((Double o1, Double o2) -> (int) (o2 - o1));
        // tokens of the same frequency fall under the same key, the order is reversed so the most frequent tokens go first
        for (Map.Entry<String, Double> entry : freqs.entrySet()) {
            Set<String> set = freqMap.get(entry.getValue());
            if (set == null) {
                set = new TreeSet<>(); // tokens of the same frequency would be sorted alphabetically
                freqMap.put(entry.getValue(), set);
            }
            set.add(entry.getKey());
        }
        int cnt = 0;
        dictSet.addAll(dict.keySet());
        // get most frequent tokens and put them to dictSet
        for (Map.Entry<Double, Set<String>> entry : freqMap.entrySet()) {
            for (String val : entry.getValue()) {
                if (dictSet.add(val) && ++cnt >= MAX_DICT) {
                    break;
                }
            }
            if (cnt >= MAX_DICT) {
                break;
            }
        }
       
        System.out.println("Dictionary is ready, size is " + dictSet.size());
        // index the dictionary and build the reverse dictionary for lookups
        for (String word : dictSet) {
            if (!dict.containsKey(word)) {
                dict.put(word, idx);
                revDict.put(idx, word);
                ++idx;
            }
        }
        System.out.println("Total dictionary size is " + dict.size() + ". Processing the dataset...");
        corpusProcessor = new CorpusProcessor(getDataPath(CORPUS_FILENAME), ROW_SIZE, false) {
            @Override
            protected void processLine(String lastLine) {
                List<String> words = new ArrayList<>();
                tokenizeLine(lastLine, words, true);
                corpus.add(wordsToIndexes(words));
            }
        };
        corpusProcessor.setDict(dict);
        corpusProcessor.start();
        System.out.println("Done. Corpus size is " + corpus.size());
    }
    private List<List<List<Double>>> getCorpusAsList(int batchSize) {

        List<List<List<Double>>> total_list = new ArrayList<>();
        int length = corpusLength == 0 ? corpus.size() : corpusLength;
        System.out.println("******Corpus length for training: " + length + "******");
        int currIdx = 0;
        int in_batch = 0;
        List<List<Double>> corpus_part = new ArrayList<>();
        while (currIdx < length) {
            try {
                List<Double> line = corpus.get(currIdx);
                corpus_part.add(line);
                if (++in_batch == batchSize) {
                    total_list.add(corpus_part);
                    in_batch = 0;
                    corpus_part.clear();
                }
            } catch (Exception ex) {
                System.out.println(currIdx + " of " + length + " error: ");
                ex.printStackTrace();
            }
            ++currIdx;
        }
        if (corpus_part.size() > 0) {
            //The last batch
            total_list.add(corpus_part);
        }
        return total_list;
    }

**Comment by Godman-quake** [comment]
Other methods is not neccesary, so I avoid them.

**Comment by raver119** [comment]
gist == https://gist.github.com btw :)

**Comment by raver119** [comment]
Anyway. Can you please check executor mentioned in your stack trace, and post relevant part of its log? There should be something bad i think.

**Comment by Godman-quake** [comment]
OK. Please wait for a moment and thanks for you patience.

**Comment by Godman-quake** [comment]
This is the log on one worker:
18/06/11 11:12:30 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:30 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:30 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:30 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:30 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:30 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:30 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:31 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:31 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:31 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:31 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:31 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:31 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:31 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:31 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:31 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:32 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:32 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:32 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:32 ERROR yarn.ApplicationMaster: Failed to connect to driver at 192.168.0.103:37095, retrying ...
18/06/11 11:12:32 ERROR yarn.ApplicationMaster: Uncaught exception: 
org.apache.spark.SparkException: Failed to connect to driver!
	at org.apache.spark.deploy.yarn.ApplicationMaster.waitForSparkDriver(ApplicationMaster.scala:577)
	at org.apache.spark.deploy.yarn.ApplicationMaster.runExecutorLauncher(ApplicationMaster.scala:433)
	at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:256)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$main$1.apply$mcV$sp(ApplicationMaster.scala:764)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$2.run(SparkHadoopUtil.scala:67)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$2.run(SparkHadoopUtil.scala:66)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:66)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:762)
	at org.apache.spark.deploy.yarn.ExecutorLauncher$.main(ApplicationMaster.scala:785)
	at org.apache.spark.deploy.yarn.ExecutorLauncher.main(ApplicationMaster.scala)
18/06/11 11:12:32 INFO yarn.ApplicationMaster: Final app status: FAILED, exitCode: 10, (reason: Uncaught exception: org.apache.spark.SparkException: Failed to connect to driver!)

**Comment by raver119** [comment]
so, stop. 

Both logs refer to the same address: 192.168.0.103

Are you running on cluster? What's actual environment you have there?

**Comment by Godman-quake** [comment]
It sounds like my driver is down, but I am sure it's alive.
So I think, maybe the driver is too busy for response?

**Comment by raver119** [comment]
The question is: why driver and executor have the same IP?

**Comment by raver119** [comment]
Are you just running as standalone on cluster box? :)

**Comment by Godman-quake** [comment]
The environment is:
Spark yarn-client, 192.168.0.103 is the driver, and executors are on other machines.

**Comment by raver119** [comment]
Okay. Where first stack trace comes from?

**Comment by raver119** [comment]
If it comes from executor - bring driver logs (or console, if you've used spark-submit) in, and we'll see what happened on driver during your training run.

**Comment by Godman-quake** [comment]
Ok, let's run this program again, and I will paste the logs.

**Comment by Godman-quake** [comment]
18/06/11 00:00:29 INFO nativeblas.NativeOpsHolder: Number of threads used for NativeOps: 4
18/06/11 00:00:29 INFO reflections.Reflections: Reflections took 70 ms to scan 18 urls, producing 31 keys and 227 values 
18/06/11 00:00:31 INFO nativeblas.Nd4jBlas: Number of threads used for BLAS: 4
18/06/11 00:00:31 INFO executioner.DefaultOpExecutioner: Backend used: [CPU]; OS: [Linux]
18/06/11 00:00:31 INFO executioner.DefaultOpExecutioner: Cores: [4]; Memory: [2.7GB];
18/06/11 00:00:31 INFO executioner.DefaultOpExecutioner: Blas vendor: [OPENBLAS]
18/06/11 00:00:32 INFO reflections.Reflections: Reflections took 318 ms to scan 18 urls, producing 396 keys and 1573 values

**Comment by Godman-quake** [comment]
Start successfully

**Comment by raver119** [comment]
1) How exactly you're running your app?
2) Is that full output at the moment of cluster crash?

**Comment by Godman-quake** [comment]
Why I cannot upload an image?

**Comment by raver119** [comment]
How do i know?

**Comment by Godman-quake** [comment]
18/06/11 00:04:44 INFO memory.MemoryStore: Block broadcast_6 stored as values in memory (estimated size 12.3 KB, free 1237.4 MB)
18/06/11 00:04:44 INFO graph.ComputationGraph: Starting ComputationGraph with WorkspaceModes set to [training: NONE; inference: SEPARATE]
18/06/11 00:04:44 INFO graph.ComputationGraph: Starting ComputationGraph with WorkspaceModes set to [training: NONE; inference: SEPARATE]

// An executor reports this, and the crash isnot occur just now.

**Comment by Godman-quake** [comment]
The drvier machine just only has 4GB memory, and 350MB are free, is this the problem?

**Comment by raver119** [comment]
Let's not guess, and just wait for actual error message.

And yes, 4GB might be way too small for this kind of model.

**Comment by Godman-quake** [comment]
![default](https://user-images.githubusercontent.com/17811303/41212566-8523eb70-6d71-11e8-9ef5-45646fd62d76.png)

**Comment by Godman-quake** [comment]
An executor machine is dead

**Comment by Godman-quake** [comment]
![default](https://user-images.githubusercontent.com/17811303/41212609-c0727926-6d71-11e8-96e7-4ab1ebcc4310.png)

**Comment by raver119** [comment]
Cool. What's in logs of that machine? 192.168.0.108

**Comment by Godman-quake** [comment]
192.168.0.108 is halt now, let me reboot. But why?

**Comment by raver119** [comment]
I'm asking you for logs to find that out. We don't have to guess, remember? We can read real system logs and spark logs, and there probably we'll find some insights.

**Comment by Godman-quake** [comment]
OK, I get it

**Comment by Godman-quake** [comment]
![default](https://user-images.githubusercontent.com/17811303/41213122-bb877a84-6d75-11e8-8251-b93214bb5f35.png)
![default](https://user-images.githubusercontent.com/17811303/41213142-d835aa48-6d75-11e8-964c-08773841b515.png)
![default](https://user-images.githubusercontent.com/17811303/41213154-edffd8b2-6d75-11e8-9693-2b4df46fd133.png)

**Comment by Godman-quake** [comment]
.trainingWorkspaceMode(WorkspaceMode.SEPARATE)
----------------
//What's this meaning?

**Comment by raver119** [comment]
https://deeplearning4j.org/workspaces 

re: crash. i think your driver was busy swapping due to low ram.

**Comment by Godman-quake** [comment]
Ok, thanks.
Let me put the driver on another machine which have 8G memory, and try it again!

**Comment by raver119** [comment]
You’d better calculate actual requirements first.

**Comment by AlexDBlack** [comment]
I'll close this due to lack of activity.
If there is still an issue, we can re-open it.
