### ISSUE TITLE
SimpleRNN doesn't accept 2D input on rnnTimestep while LSTM does

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#5568]
We should either accept it on both or don't accept it on both.

**Comment by maxpumperla** [comment]
good point, I'll look into this (prob. adding to SimpleRNN)

**Comment by AlexDBlack** [comment]
The simpler solution might simply be to add the time dimension (of length 1) at the rnnTimeStep stage, then the RNNs only have to worry about 3d. Saves us having running into this every time we add an RNN layer :)
