### ISSUE TITLE
SimpleRNN.rnnTimeStep doesn't seem to work quite right

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#5570]
When running BasicRNNExample (Updater AMSGrad with LR 0.01) with LSTM it learns to perfectly recreate the input at a loss of about 6.5 (Epoch 68), SimpleRNN reaches that loss a lot sooner (Epoch 19), but when sampling, it produces just garbage. 

It looks like the problem is with rnnTimeStep, since I can get proper results by feeding the whole history into output for each step. 

This works and results in a perfect result with SimpleRNN at Epoch 16 (and works, albeit slowly, with LSTM, it also stays at epoch 68)
```java
            INDArray output;
            final val integers = new ArrayList<Integer>();
            integers.add(LEARNSTRING_CHARS_LIST.indexOf(LEARNSTRING[0]));
            for (char dummy : LEARNSTRING) {
                final val in = Nd4j.zeros(1, LEARNSTRING_CHARS_LIST.size(), integers.size());
                for (int i = 0; i < integers.size(); i++) {
                    in.putScalar(1, integers.get(i), i, 1);
                }
                final val out = net.output(in);
                output = out.get(all(), all(), point(out.size(2)-1));
                int sampledCharacterIdx = output.argMax(1).getInt(0);
                integers.add(sampledCharacterIdx);
                System.out.print(LEARNSTRING_CHARS_LIST.get(sampledCharacterIdx));

            }
```

And this only works with LSTM:
```java
            INDArray output = net.rnnTimeStep(testInit.reshape(1, LEARNSTRING_CHARS_LIST.size(), 1));
            for (char dummy : LEARNSTRING) {
                int sampledCharacterIdx = output.argMax(1).getInt(0);
                System.out.print(LEARNSTRING_CHARS_LIST.get(sampledCharacterIdx));
                INDArray nextInput = Nd4j.zeros(LEARNSTRING_CHARS_LIST.size());
                nextInput.putScalar(sampledCharacterIdx, 1);
                output = net.rnnTimeStep(nextInput.reshape(1, LEARNSTRING_CHARS_LIST.size(), 1));
            }
```

**Comment by ronniegward** [comment]
SimpleRnn.java is in package org.deeplearning4j.nn.layers.recurrent; whereas LSTM.java is in org.deeplearning4j.nn.layers; Why the difference?
In tracing the RNN_TIMESTEP method, I notice that: 
if (this.layers[i] instanceof RecurrentLayer) {
           input = ((RecurrentLayer)this.layers[i]).rnnTimeStep(input, mgr);//is executed for layers 0 and 1 in the example
} else if (this.layers[i] instanceof MultiLayerNetwork) {
           input = ((MultiLayerNetwork)this.layers[i]).rnnTimeStep(input);
} else {
           input = this.layers[i].activate(input, false, mgr);//is executed for layer 2 in the example
}
The net has 3 layers: 0, 1, and 2. Layers 0 and 1 are instances of RecurrentLayer, whereas Layer 2 is not.
The input at layer 0 is the supplied input; the input at layers 1 and 2 are the outputs of the previous layers.
The output of layer 2 returned by the call to activate() is generated from:
INDArray act2d = ((org.deeplearning4j.nn.conf.layers.RnnOutputLayer)this.layerConf()).getActivationFn().getActivation(input2d.mmul(W).addiRowVector(b), training);
    which appears to be the activations of the RnnOutputLayer.
These activation results appear to be very near the same for each successive call to the RnnOutputLayer, which gives rise to the program output of:
	TimeStep Method:*Dptbhtbhtbhtbhtbhtbhtbhtbhtbhtbhtbhtbhtbhtbhtbhtbhtbhtbhtbhtbhtbh 
	instead of 
	Original String:*Der Cottbuser Postkutscher putzt den Cottbuser Postkutschkasten.
	
	I would like to see this issue resolved.
	Thank you.

**Comment by AlexDBlack** [comment]
> SimpleRnn.java is in package org.deeplearning4j.nn.layers.recurrent; whereas LSTM.java is in org.deeplearning4j.nn.layers; Why the difference?

Because once apon a time we had only one or two RNN layers - now we have more hence have added an extra package for new RNN layers. We can't change the old location without breaking user imports between versions.

**Comment by treo** [comment]
@ronniegward since the SimpleRnn extends BaseRecurrentLayer it is also a RecurrentLayer. So there shouldn't be any difference to the LSTM case at that point.

**Comment by AlexDBlack** [comment]
Confirmed fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/5623

Output on BasicRNNExample with SimpleRnn, AMSGrad, LR=0.01:
https://gist.github.com/AlexDBlack/84cbd90379fe23902bef7a387cd433f5

**Comment by ronniegward** [comment]
Thank you Alex! Good work.
