### ISSUE TITLE
Conditional implementation for ListStringSplit iterator in LineRecordReader

### ISSUE THREAD

**Issue by ShamsUlAzeem** [deeplearning4j/deeplearning4j#5579]
If we initialize LineRecordReader with ListStringSplit then the iterator comes out to be null since there aren't any URI locations associated with ListStringSplit.

So, we might want to have an extra conditional implementation for the condition `inputSplit instanceof ListStringSplit` in the getIterator() method here: https://github.com/deeplearning4j/deeplearning4j/blob/79d4110eee96f6b7f331931f4775233c4264d999/datavec/datavec-api/src/main/java/org/datavec/api/records/reader/impl/LineRecordReader.java#L187-L210

**Comment by AlexDBlack** [comment]
After looking at this in more detail - I've decided that it doesn't really work with any of the readers.
ListStringSplit has data stored in the form of ```List<List<String>```. If it was ```List<String>``` (which is what I originally thought it was, based on the name) it would make sense to plug this into LineRecordReader. ```List<List<String>>``` kind of makes sense for CsvRecordReader, but it's not delimited, it's already split into tokens at that point.
So it doesn't make sense to me to plug this into the other readers - we'll keep it as a special case for ListStringRecordReader.
