### ISSUE TITLE
save model throws a NoClassDefFoundError

### ISSUE THREAD

**Issue by ragnarok22** [deeplearning4j/deeplearning4j#5583]
Hi! I have a little problem, when I try to save the model with `ModelSerializer.writeModel(MultiLayerNetwork, String, boolean)` and` MultiLayerNetwork.save(File, boolean)` methods this throw me this: `java.lang.NoClassDefFoundError: com/github/os72/protobuf351/MessageOrBuilder`. Why happend this?
This is the  [the full stacktrace in a gist](https://gist.github.com/ragnarok22/e578759a2b7035f11c41a4a871e414d8) and [the code used](https://gist.github.com/ragnarok22/9803f534aa70019d39aa48532a855d00)

**Comment by raver119** [comment]
Show your pom.xml too please

**Comment by ragnarok22** [comment]
This is my pom.xml:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>jclal-deeplearning</artifactId>

    <parent>
        <groupId>net.sf.jclal</groupId>
        <artifactId>jclal</artifactId>
        <version>1.1</version>
    </parent>

    <name>Deep Learning integration for JCLAL Framework</name>

    <properties>
        <nd4j.backend>nd4j-native-platform</nd4j.backend>
        <nd4j.version>1.0.0-beta</nd4j.version>
        <logback.version>1.1.7</logback.version>
        <java.version>1.8</java.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>${nd4j.backend}</artifactId>
                <version>${nd4j.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>net.sf.jclal</groupId>
            <artifactId>jclal-core</artifactId>
            <version>2.0</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.10</version>
        </dependency>
        
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>${nd4j.backend}</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-api</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-nlp</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-nn</artifactId>
            <version>${nd4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-zoo</artifactId>
            <version>${nd4j.version}</version>
        </dependency>

        
        <dependency>
            <artifactId>datavec-data-codec</artifactId>
            <groupId>org.datavec</groupId>
            <version>${nd4j.version}</version>
        </dependency>
    </dependencies>
</project>

**Comment by AlexDBlack** [comment]
@ragnarok22 I created a project from your code and pom.xml, and I can run it just fine - no saving issues at all.
I suspect 2 issues at this point:
(a) This is due to your IDE (are you using Eclipse, by any chance? Or Intellij but haven't rebuilt/reimported after changing versions and have auto-reimport disabled?)
(b) Something is being pulled in from the parent pom that is causing this

For (b), can you provide the output of ```mvn dependency:tree``` in a gist?

**Comment by ragnarok22** [comment]
I am using IDE intelliJ IDEA and the auto-reimport is enabled, this is my [`mvn dependency:tree`](https://gist.github.com/ragnarok22/bd59c8c1f266c555960217b3f2d1232b)

**Comment by raver119** [comment]
Just amazing, you've forgot to mention Spark module when posted pom.xml :)

So, you have casual versions conflict there. Caused probably by Hadoop.

**Comment by AlexDBlack** [comment]
I'm not seeing DL4J, ND4J OR DataVec anywhere in that "mvn dependency:tree" output... is this for the project that you are actually having trouble with? Or something else?

**Comment by ragnarok22** [comment]
but in version 0.9.1, it works perfectly, on the other hand, the jclal-spark module is completely separate

**Comment by ragnarok22** [comment]
sorry, every module has a pom.xml file, the showed is the core module, this is the [deeplearning pom.xml file](https://gist.github.com/ragnarok22/1bb7ad584f4010d51d10f8848abadcf5)

**Comment by AlexDBlack** [comment]
So this obviously stands out:
```
[WARNING] Invalid POM for org.nd4j:nd4j-native-platform:jar:1.0.0-beta, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for org.nd4j:nd4j-api:jar:1.0.0-beta, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for org.nd4j:nd4j-api:jar:1.0.0-beta, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for org.deeplearning4j:deeplearning4j-core:jar:1.0.0-beta, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for org.deeplearning4j:deeplearning4j-nlp:jar:1.0.0-beta, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for org.nd4j:nd4j-api:jar:1.0.0-beta, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for org.datavec:datavec-api:jar:1.0.0-beta, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for org.deeplearning4j:deeplearning4j-zoo:jar:1.0.0-beta, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for org.datavec:datavec-data-codec:jar:1.0.0-beta, transitive dependencies (if any) will not be available, enable debug logging for more details
```

My guess is that you somehow ended up with corrupted versios of the pom.xml files for these dependencies?
Only thing I can recommend is deleting org.deeplearning4j, org.nd4j and org.datavec in ```<user.home>/.m2/repository``` and trying to build again.

**Comment by AlexDBlack** [comment]
I'll close this as almost certainly corrupted pom.xml files.
We can re-open if required.
