### ISSUE TITLE
[Keras] support InputStream import in KerasModelImport

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/deeplearning4j#5594]
We have stubs here since forever:

https://github.com/deeplearning4j/deeplearning4j/blob/d06cc0b8d8e28eb5182bab3fb2d716dc3ef95380/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/KerasModelImport.java#L50-L90

completely fell off my radar, we should support this at some point.

**Comment by kobezorro** [comment]
when will it be implemented? we do need it! Thanks!
