### ISSUE TITLE
libnd4j cannot build CUDA libs on ubuntu 16.04 because of missing std=c++11 flag

### ISSUE THREAD

**Issue by emillynge** [deeplearning4j/deeplearning4j#5607]
Compile instructions for ubuntu 16.04 taken from Readme.md
```
sudo apt install cmake
sudo apt install nvidia-cuda-dev nvidia-cuda-toolkit nvidia-361
export TRICK_NVCC=YES
./buildnativeoperations.sh
./buildnativeoperations.sh -c cuda -сс YOUR_DEVICE_ARCH
```

Running these commands however does not seem to work. The compiler complains that the flag `--std=c++11` needs to be set.

in `blas/CMakeLists.txt` the `TRICK_NVCC=YES` is being handled by
```
        if ("${CMAKE_C_COMPILER_VERSION}" VERSION_GREATER 4.9 AND "$ENV{TRICK_NVCC}" STREQUAL "YES" AND CUDA_VERSION VERSION_LESS "8.0")
            set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D__GNUC__=4 -D__GNUC_MINOR__=9 -D_FORCE_INLINES -D_MWAITXINTRIN_H_INCLUDED")
            set (CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -Xcompiler -std=c++98 -Dnullptr=NULL")
            message("TRICKING CUDA INTO SUPPORTING GCC > 4.9 YOU ARE PROCEEDING AT YOUR OWN RISK")
        endif()
```

I would think the issue is that `-Xcompiler -std=c++98` is incorrect. Maybe some new fancy instructions found their way into the cuda code since this part of the readme was written?

**Comment by raver119** [comment]
What's your actual CUDA version, and your GCC version?

**Comment by raver119** [comment]
Hm. And yes, stdc 11 is required atm, thanks for highlighting.

**Comment by saudet** [comment]
I don't believe that the workarounds in `TRICK_NVCC` are useful anymore. We should probably remove that?

**Comment by raver119** [comment]
Well, it looks like there's one guy trying to use it right here. But ye, it's for CUDA 7.5 and we don't care anymore. 

P.s. c++11 change is applied in my current pr.

**Comment by emillynge** [comment]
My CUDA version is 7.5.
If that version is not supported, Maybelline The readme should reflect that.

I'm using a docker container for building. So it is easy to change the OS. Only I found that Ubuntu 18 links to glibc 2.27 which is not compatible with Ubuntu 16 where it needs to also run.

**Comment by agibsonccc** [comment]
@emillynge I don't think any frameworks even support 7.5 anymore.

**Comment by emillynge** [comment]
Well, the current readme gives the following instructions for Ubuntu 16.04 
```
sudo apt install cmake
sudo apt install nvidia-cuda-dev nvidia-cuda-toolkit nvidia-361
export TRICK_NVCC=YES
./buildnativeoperations.sh
./buildnativeoperations.sh -c cuda -сс YOUR_DEVICE_ARCH
```
This will install CUDA 7.5

I think the instructions for Ubuntu 15 has the same issue.

Maybe they should be updated or removed entirely?

**Comment by saudet** [comment]
@emillynge Probably, please file another issue and/or a pull request!
