### ISSUE TITLE
ND4J: Double check NativeOpExecutioner for rank 0 arrays

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5629]
Not sure if there are any actual bugs here yet or not, but I wouldn't be surprised.

NativeOpExecutioner uses ```ArrayUtil.prodLong(long[])```  in a number of places. However, for rank 0 arrays (i.e., scalars), shape is a length 0 long[] - for which prodLong returns 0.
In this case, for example, the memcpy would be incorrect:
https://github.com/deeplearning4j/deeplearning4j/blob/1fd9d5d29463a8e4ea947c527e37a62a9cdb2d59/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/linalg/cpu/nativecpu/ops/NativeOpExecutioner.java#L1961

**Comment by raver119** [comment]
Ye, clearly bug.

**Comment by raver119** [comment]
Fixed
