### ISSUE TITLE
Increased error rate , regularly hitting epsTerminationCondition while using cudnn

### ISSUE THREAD

**Issue by rahul-raj** [deeplearning4j/deeplearning4j#5630]
Here is the code with CNN config:
https://github.com/rahul-raj/Deeplearning4J/blob/master/src/main/java/AnimalClassifier.java 

(Note that I added `PerformanceListener` in code, but used `ScoreIterationListener` in my local to give you below snapshots. I also alter pom.xml changes between cpu<->gpu to compare results)

Now here is what I see when I run this code on a CPU (error rate seen on epochs are very less):
![image](https://user-images.githubusercontent.com/517415/41535179-0257906c-731f-11e8-9a7b-d2b358d8a256.png)

But when I execute the same code on `deeplearning4j-cuda`, I see this:
![image](https://user-images.githubusercontent.com/517415/41535303-773ce364-731f-11e8-912a-9caf1e48c453.png)
![image](https://user-images.githubusercontent.com/517415/41535320-81d4c800-731f-11e8-9362-55641e30f75e.png)
![image](https://user-images.githubusercontent.com/517415/41535334-8de24172-731f-11e8-9f2e-ad36220110dd.png)
![image](https://user-images.githubusercontent.com/517415/41535344-996017cc-731f-11e8-9c03-1c81c7a63b78.png)
![image](https://user-images.githubusercontent.com/517415/41535371-ad972ea6-731f-11e8-8508-d3c1ca632e1a.png)
![image](https://user-images.githubusercontent.com/517415/41535411-d46189f0-731f-11e8-963d-6926f9c15ef2.png)

As we could see error rate keeps increasing and keep hitting `epochsTermination` despite of many iterations. Would love to fix the NN config on my code, but wondering why its working on CPU and goes weird when I switch to GPU.

Here is the pom.xml if that helps:
https://github.com/rahul-raj/Deeplearning4J/blob/master/pom.xml

**Comment by AlexDBlack** [comment]
@rahul-raj What's your hardware, OS and do you have cudnn installed?
Can you also give us the output of ```nvcc --version```?

**Comment by rahul-raj** [comment]
Just wanted to post this snap:
![image](https://user-images.githubusercontent.com/517415/41536060-130a4afa-7322-11e8-91a0-07efc6d39698.png)

And here is the output of cuda version:
![image](https://user-images.githubusercontent.com/517415/41536094-3339e222-7322-11e8-8c35-c168c8be49ee.png)

OS -> Ubuntu 16.04

More hardware details:
![image](https://user-images.githubusercontent.com/517415/41536188-7a905ffc-7322-11e8-894c-88e8b46e835e.png)

**Comment by rahul-raj** [comment]
And yes, I have installed cudnn, this is what I followed:
https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#installlinux-tar

**Comment by AlexDBlack** [comment]
Thanks, I think that is all the info we need. I'll try to reproduce this tomorrow.

**Comment by rahul-raj** [comment]
Thank you @AlexDBlack 
I would like to report that I'm facing the same condition even on CPU, but only after say 50000 iterations.
![image](https://user-images.githubusercontent.com/517415/41538191-4f0c2bbc-7328-11e8-873d-87aa5f531154.png)
I will test them with less epochs and share results. Most likely it wont happen for training with less than 40k iterations. GPU testing fails right from beginning.

**Comment by rahul-raj** [comment]
Here is the result after changing epochs from 100 to 30 on CPU:
![image](https://user-images.githubusercontent.com/517415/41545719-752087a6-7339-11e8-8045-cf8731fd8f95.png)

When I increase epochs to 100 or near, `epochsTermination` will hit on CPU too.
In case of GPU, I see that right from beginning as I mentioned before. Epochs doesn't matter in the case of GPU execution.

**Comment by AlexDBlack** [comment]
I finally got to looking at this. I can confirm that the issue is reproducible also on master, using tiny imagenet and the provided configuration.

I will look into this more tomorrow.

**Comment by AlexDBlack** [comment]
I think I've tracked this down to an async iterator issue:
This fails on CUDA (at iteration 70), passes on native.

```
        int batchSize=10;
        DataSetIterator dataSetIterator = new EarlyTerminationDataSetIterator(new TinyImageNetDataSetIterator(batchSize, new int[]{30, 30}, DataSetType.TRAIN, null, 12345), 100);
        DataSetIterator iterWithAsync   = new EarlyTerminationDataSetIterator(new TinyImageNetDataSetIterator(batchSize, new int[]{30, 30}, DataSetType.TRAIN, null, 12345), 100);
        iterWithAsync = new AsyncDataSetIterator(iterWithAsync);


        int i=0;
//        while(dataSetIterator.hasNext()){ //Returns null if I do this?!?
        while(dataSetIterator.hasNext() && iterWithAsync.hasNext()){
            DataSet noAsync = dataSetIterator.next();
            DataSet withAsync = iterWithAsync.next();
            assertEquals(String.valueOf(i++), noAsync, withAsync);
        }
```

@rahul-raj as a workaround until we fix this properly: you should be able to use AsyncShieldDataSetIterator wrapper iterator to avoid this.

**Comment by rahul-raj** [comment]
@AlexDBlack 
Sure, I will try out this, thanks :)

**Comment by AlexDBlack** [comment]
@raver119 

With batch 1, it fails at iteration 696.
data is [1,3,30,30]+[1,200] = 2900 elements.
With FP32 precision, that's 8073600 bytes (vs. WS size 10MB). Unless I'm missing something (like temp working memory).

Now, this looks like an issue with the (host?) buffer not being reset, in conjunction with putScalar specifically.
When the failure occurs (iter 696, which I guess is after the reset), Nd4j.create has values taken from iteration 1 - which is the first iteration that the workspace is used (given config has ```.policyLearning(LearningPolicy.FIRST_LOOP)```.

Easy to see with:
```
    public static void main(String[] args) throws Exception {
        int batchSize=1;
        DataSetIterator dataSetIterator = new EarlyTerminationDataSetIterator(new TinyImageNetDataSetIterator(batchSize, new int[]{30, 30}, DataSetType.TRAIN, null, 12345), 1000);
        DataSetIterator iterWithAsync   = new EarlyTerminationDataSetIterator(new TinyImageNetDataSetIterator(batchSize, new int[]{30, 30}, DataSetType.TRAIN, null, 12345), 1000);
        iterWithAsync = new AsyncDataSetIterator(iterWithAsync);

        System.out.println(Nd4j.dataType());


        int i=0;
//        while(dataSetIterator.hasNext()){ //Returns null if I do this?!?
        while(dataSetIterator.hasNext() && iterWithAsync.hasNext()){
            System.out.println("---------");
            System.out.println("Iter: " + i);
            DataSet noAsync = dataSetIterator.next();
            DataSet withAsync = iterWithAsync.next();

            INDArray l = withAsync.getLabels();
            for( int j=0; j<l.length(); j++ ){
                if(l.getDouble(j) > 0){
                    System.out.println("Non-zero at label index: " + j + " (value: " + l.getDouble(j) + " - matches noAsync: " + (noAsync.getLabels().getDouble(j) > 0));
                }
            }

            assertEquals(String.valueOf(i), noAsync.getFeatures(), withAsync.getFeatures());
            assertEquals(String.valueOf(i), noAsync.getLabels(), withAsync.getLabels());

//            withAsync.getLabels().assign(i + 0.5);  //Makes ZERO difference

            for( int j=0; j<l.length(); j++ ){
                l.putScalar(j, i+0.5);      //PutScalar DOES break things
            }
            i++;
        }
    }
```

**Comment by AlexDBlack** [comment]
0.9.1 equivalent, which passes with CUDA 8:
```
    public static void main(String[] args) throws Exception {
        int batchSize=1;
//        DataSetIterator dataSetIterator = new EarlyTerminationDataSetIterator(new TinyImageNetDataSetIterator(batchSize, new int[]{30, 30}, DataSetType.TRAIN, null, 12345), 1000);
//        DataSetIterator iterWithAsync   = new EarlyTerminationDataSetIterator(new TinyImageNetDataSetIterator(batchSize, new int[]{30, 30}, DataSetType.TRAIN, null, 12345), 1000);
        ImageRecordReader rr = new ImageRecordReader(30, 30, 3, new ParentPathLabelGenerator());
        rr.initialize(new FileSplit(new File("C:\\Users\\Alex\\.deeplearning4j\\TINYIMAGENET_200\\train"), new String[]{"JPEG"}, new Random(12345)));
        ImageRecordReader rr2 = new ImageRecordReader(30, 30, 3, new ParentPathLabelGenerator());
        rr2.initialize(new FileSplit(new File("C:\\Users\\Alex\\.deeplearning4j\\TINYIMAGENET_200\\train"), new String[]{"JPEG"}, new Random(12345)));


        DataSetIterator dataSetIterator = new EarlyTerminationDataSetIterator(new RecordReaderDataSetIterator(rr, batchSize, 1, 200), 1000);
        DataSetIterator iterWithAsync   = new EarlyTerminationDataSetIterator(new RecordReaderDataSetIterator(rr2, batchSize, 1, 200), 1000);

        iterWithAsync = new AsyncDataSetIterator(iterWithAsync);

        System.out.println(Nd4j.dataType());


        int i=0;
        while(dataSetIterator.hasNext() && iterWithAsync.hasNext()){
            System.out.println("---------");
            System.out.println("Iter: " + i);
            DataSet noAsync = dataSetIterator.next();
            DataSet withAsync = iterWithAsync.next();

            INDArray l = withAsync.getLabels();
            for( int j=0; j<l.length(); j++ ){
                if(l.getDouble(j) > 0){
                    System.out.println("Non-zero at label index: " + j + " (value: " + l.getDouble(j) + " - matches noAsync: " + (noAsync.getLabels().getDouble(j) > 0));
                }
            }

            assertEquals(String.valueOf(i), noAsync.getFeatures(), withAsync.getFeatures());
            assertEquals(String.valueOf(i), noAsync.getLabels(), withAsync.getLabels());

//            withAsync.getLabels().assign(i + 0.5);  //Makes ZERO difference

            for( int j=0; j<l.length(); j++ ){
                l.putScalar(j, i+0.5);      //PutScalar DOES break things
            }
            i++;
        }
    }
```

**Comment by AlexDBlack** [comment]
Probably related, maybe the same issue: Workspaces + putScalar + CUDA - https://github.com/deeplearning4j/deeplearning4j/issues/5638

**Comment by raver119** [comment]
Fixed.

**Comment by rahul-raj** [comment]
What are the changes files so that I can copy them from master.
