### ISSUE TITLE
ComputationGraph.summary() throw exception when ComputationGraph have Bidirectional wrapper

### ISSUE THREAD

**Issue by rexlaw412** [deeplearning4j/deeplearning4j#5631]
**Issue Description**

An exception is thrown when calling ComputationGraph.summary(),when ComputationGraph have Bidirectional wrapper.

The following is the stack trace message:
```
java.lang.ClassCastException: org.deeplearning4j.nn.conf.layers.recurrent.Bidirectional cannot be cast to org.deeplearning4j.nn.conf.layers.FeedForwardLayer
	at org.deeplearning4j.nn.graph.ComputationGraph.summary(ComputationGraph.java:4086)
	at org.deeplearning4j.nn.graph.ComputationGraph.summary(ComputationGraph.java:4022)
	at Test.train(Test.java:266)
```

**Version Information**
- Deeplearning4j version (1.0.0-beta)
- platform information (Window 10)

**Comment by maxpumperla** [comment]
fixed here https://github.com/deeplearning4j/deeplearning4j/pull/5642
