### ISSUE TITLE
Zeppelin based tutorials still using 0.9.1 features

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#5640]
I've just noticed that the Zeppelin Notebook based tutorials still reference 0.9.1 based features like `.learningRate`. As those tutorials are a pretty good point for beginners to start, I think we should update them to 1.0.0-beta.

**Comment by crockpotveggies** [comment]
Thanks for submitting this issue. We've migrated our docs to its own separate repository at [deeplearning4j-docs](https://github.com/deeplearning4j/deeplearning4j-docs). I've already migrated your issue and you can find it at https://github.com/deeplearning4j/deeplearning4j-docs/issues/80. 

I'll be closing this, but feel free to comment and re-open if this is not what you intended.

*This was an automatically generated response.*
