### ISSUE TITLE
how to combine text analysis (word2vec) + other informations

### ISSUE THREAD

**Issue by newinai** [deeplearning4j/deeplearning4j#5651]
Hi,

My problem is explain in this gist link, with all the files and explanations:
https://gist.github.com/newinai/bf61183bf7ebce0d00af8dd3afa323ad

I have to analyse some columns of initial_file.csv: for example columns: 'age', ... and 'comment' and predict if each line is Positive OR Negative ('result' column).

There is no examples on DL4J examples to do this: Combine 'comment' text analysis with word2vec and then use others informations like 'age'.

Do you have an idea to do this ?

With the examples on DL4J, I found both problems separately:

CnnSentenceClassificationExample: To analyse 'comment' column.
BasicCSVClassifier: To analyse the others non text/sentence columns like 'age'.
So yesterday after speaking you create the "JoinMultiDataSetIterator" and i use it in my code but...

Now I can not adjust the ComputationGraphConfiguration.

Can you help me ? :)

(in the names of files i replace / char by _ char ).

Thank you all for the help :)

**Comment by AlexDBlack** [comment]
OK, so there's 2 aspects to this:
1. The network configuration
2. The data pipeline

With regard to the network configuration, it would be something like:
input_1 -> 1 or more LSTM layers -> global pooling -> dense -> output
input_2 -> dense -> output

Note that the "dense" and "output" layers in both branches refers to the same layers (i.e., "dense" has 2 inputs), and input_1 would be sequence data whereas input_2 is non-sequence data.

Now, as for the data pipeline: unfortunately there's not yet a single class that does this for you out of the box... it's going to require at least some custom data code.

Usually we discourage people from writing a custom DataSetIterator, but this might be an exception.
The basic idea:
1. Load your Word2Vec vectors in the custom DataSetIterator constructor for later use
2. in next() method:
   (a) create one array (3d) for the sequences (pretty much identical to what SentimentExampleIterator does in examples, it just pulls vectors from w2v) - see https://deeplearning4j.org/usingrnns#basics
   (b) create another features array for non-sequence data
   (c) create one-hot label array

**Comment by raver119** [comment]
Closing this issue, since it already has answer + topic started got additional answers in gitter.
