### ISSUE TITLE
SVD error :  fail to write core dump 

### ISSUE THREAD

**Issue by Liujish931** [deeplearning4j/deeplearning4j#5654]
A fatal error has been detected by the Java Runtime Environment:

 SIGSEGV (0xb) at pc=0x00007f3aef74d658, pid=28385, tid=0x00007f3b533bd700

 JRE version: OpenJDK Runtime Environment (8.0_171-b11) (build 1.8.0_171-8u171-b11-1~bpo8+1-b11)
 Java VM: OpenJDK 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [libopenblas.so.0+0x1f64658]  LAPACKE_sge_trans+0x78

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 workspace/hs_err_pid28385.log

 If you would like to submit a bug report, please visit:
  http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

========================================================

I got this problem when I try to do two SVD sequentially, the matrix A and B have the same shape : 5000*300

Nd4j.getBlasWrapper().lapack().gesvd(A, S1, U1, VT1);
Nd4j.getBlasWrapper().lapack().gesvd(B, S2, U2, VT2);

When I do only one SVD it works

**Comment by saudet** [comment]
Could you try with MKL? Maybe that's a bug in OpenBLAS...

**Comment by Liujish931** [comment]
How to do with MKL ?

**Comment by saudet** [comment]
Download and install https://software.intel.com/en-us/mkl. You might also need to set the "org.bytedeco.javacpp.openblas.load" system property to "mkl_rt".

**Comment by Liujish931** [comment]
thanks ! I will see that :)

**Comment by raver119** [comment]
Any news?

**Comment by saudet** [comment]
MKLML from MKL-DNN is used as default now, so we can close this.
