### ISSUE TITLE
remove bios boot entry password

### ISSUE THREAD

**Issue by yaponek** [deeplearning4j/deeplearning4j#5666]
my laptop has  bios boot entry password and i forget it please if there is any way of fixing this give me your solutions.
the bios that i am using the latest one and my laptop model is satellite  C55-B1064
i tried several ways including the cmos  battery Technics. but for some reason all of the turn out to be useless. and i prefer` free **ways of solving this**` since the major problem i have got is the price. 
i am looking forward for your suggestion,Thanks.

**Comment by AlexDBlack** [comment]
This is completely unrelated to DL4J. Please ask such questions elsewhere.
