### ISSUE TITLE
ND4J: javaShapeInformation migration not fully finished

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#5692]
While investigating some additional overhead while calling GEMM, we've found that most of it is from shape information calls across the JNI boundary.

> raver119 @raver119 19:40
but i think that's exactly the problem
and fix is trivial
investigate rows() call
just travel through it
migration to jvm shapeinfo wasn't finished
so we're still using jcpp accessing off-heap memory for shapeinfo in some places

>Paul Dubs @treo 19:42
gemmParams: 380,442 ± 6,226 ns/op
charForTranspose: 23,467 ± 0,867 ns/op

>Thats pretty much exactly those 400ns

>raver119 @raver119 19:42
https://github.com/deeplearning4j/deeplearning4j/blob/08eb42a3398980ad1a2c27228465b75c3843af2a/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L5336-L5356
and that's where those nanoseconds come from
i've introduced jvmshapeinfo field to get rid of jcpp calls
but hasn't finished migration

>we should just migrate all service methods to jvmShapeInformation

> raver119 @raver119 19:51
columns, rows, length,everything

**Comment by treo** [comment]
Solved by #5693 .

**Comment by saudet** [comment]
Note that this is not technically JavaCPP. There would be pretty much no overhead if we were using an Indexer: http://bytedeco.org/news/2014/12/23/third-release/
