### ISSUE TITLE
Candidate Executor missing 

### ISSUE THREAD

**Issue by okonechn** [deeplearning4j/deeplearning4j#5700]
Can't find CandidateExecutor<C,M,D,A> interface in Arbiter directory https://github.com/deeplearning4j/deeplearning4j/tree/master/arbiter. Does there exist some replacement of this interface, if so, where can I find it? 
Have you got some examples of running of IOptimizationRunning via Random Search?
Can I use Arbiter to run it on the non-network classifiers such as kNN, C4.5, AdaBoostM1, SMO, etc.?

**Comment by AlexDBlack** [comment]
You are looking for OptimizationRunner, I believe.

We have an example here, which uses random search: https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/arbiter/BasicHyperparameterOptimizationExample.java

Can you use arbiter for non-neural network optimization tasks? The short answer is no. The longer answer is "yes, with a reasonable amount of effort". You'd need to understand the internals, write some parameter spaces, and handle launching etc for those machine learning models.
Note that we don't have those classifiers in DL4J.
