### ISSUE TITLE
NativeImageLoader returns null when converting from Mat

### ISSUE THREAD

**Issue by Vigasto** [deeplearning4j/deeplearning4j#5709]
I'm currently trying to convert Mat images to INDArray as follows : 

```java
//Load image file
Mat srcImage = Imgcodecs.imread(args[0]);

//Rescale
Mat cvImage = new Mat(64,64,srcImage.type());
Imgproc.resize(srcImage,cvImage,cvImage.size(),0,0,Imgproc.INTER_CUBIC);

NativeImageLoader loader = new NativeImageLoader(64,64,1);
INDArray image = loader.asMatrix(cvImage);

MultiLayerNetwork model = KerasModelImport.importKerasSequentialModelAndWeights(args[1], false);
model.predict(image);
```

However, the ``INDArray image`` return null when loading either ``srcImage`` or its scaled down ``cvImage``. Both ``Mat`` return non-null value and displays correct images when saved.

**Comment by saudet** [comment]
NativeImageLoader doesn't support that Mat object, use the one given in the docs:
https://deeplearning4j.org/datavecdoc/org/datavec/image/loader/NativeImageLoader.html#asMatrix-org.bytedeco.javacpp.opencv_core.Mat-

**Comment by Vigasto** [comment]
Changing the Mat package from ``org.opencv`` to ``org.bytedeco.javacpp.opencv_core`` ones resolves the problem as said. Thank you!
