### ISSUE TITLE
NullPointerException when serializing Word2Vec model

### ISSUE THREAD

**Issue by TheKingDiamond** [deeplearning4j/deeplearning4j#5710]
(EDIT: I am using version 0.9.1 of DL4J, but have checked and this issue persists in 1.0.0-beta.)

If a Word2Vec model has useUnknown set to true and the vocabulary has been limited (to a size smaller than the number of unique words in the text corpus), then the writeWordVectors(WeightLookupTable<T> lookupTable, OutputStream stream) method of WordVectorSerializer throws a NullPointerException when it attempts to execute the last iteration of the for loop (specifically at line 418).

The UNK string will not generally have an index value contiguous with the words that have been included in the vocabulary - and thus in the idxMap. The index values are used as the keys in the idxMap and this is where the issue occurs. The following example should help to illustrate the issue:

If we have a vocabulary of restricted to a size of 2 (from an original size much larger than this) and are using UNK, then we may have something like the following in the idxMap (simplified):

Element [0]: Key = 0, Value = "the"
Element [1]: Key = 1, Value = "an"
Element [2]: Key = 11356, Value = "UNK"

The call to vocabCache.elementAtIndex(x) will execute successfully for the first two words. However, the for loop is configured to run a final time to get the UNK value. The issue is that  now x = 2, but the key for UNK is actually 11356. Thus, a NullPointerException is thrown as no element exists in the idxMap with a key of '2'.

**Comment by raver119** [comment]
Can you show source code please, that reproduces this problem?

**Comment by raver119** [comment]
Fixed. THanks for highlighting this problem

**Comment by TheKingDiamond** [comment]
Hi @raver119 , I'm taking a look at the changes in 1.0.0-beta2.

It seems that the case is now that all the indices for the words in the object returned from _iterator.nextSequence()_ (VocabConstructor, line 246) are -1. These indices are carried through the rest of the program, which leads to a totally new issue in that limiting the vocabulary size is no longer possible (as the removal of words works by removing elements with indices greater than the specified limit). Please let me know if I should create a new issue for this defect, or if we can use this one instead!

Many thanks!

**Comment by raver119** [comment]
Yes please, file an issue. It was quite a while ago, but i think -1 means "element not found in vocabulary".

**Comment by raver119** [comment]
Are you sure there's no delta between vocab and actual data fed into training pipeline?
