### ISSUE TITLE
Word2Vec and VectorsConfiguration parameter disparity

### ISSUE THREAD

**Issue by TheKingDiamond** [deeplearning4j/deeplearning4j#5720]
When configuring a Word2Vec object in Java, the call to build() of Word2Vec.Builder should set all of the variables in the Word2Vec object and also in the VectorsConfiguration object (which the Word2Vec contains within itself). When a parameter is set in Word2Vec, that value should be copied to the corresponding variable in the Vectors Configuration (if one exists). This is not the case for several parameters, which are left as their default values:
>- vocabLimit - 0 (this should reflect what the user has specified by limitVocabularySize() of Word2Vec.Builder)
>- trainElementsVectors - true
>- trainSequenceVectors - true (both of these cannot be true! For W2V, elements are used, not sequences)
>- elementsLearningAlgorithm - null (the default for W2V is SkipGram...)

This has been observed by examining the config.json file created when a Word2Vec model is serialized.
The VectorsConfiguration alone is used as the basis for this file, and so it is currently writing incorrect information, i.e. values that do _not_ reflect those used by the actual Word2Vec object during training.

It is possible to mitigate this issue by setting these values explicitly in a VectorsConfiguration and then passing this to the constructor of a Word2Vec.Builder, like so:
```
VectorsConfiguration vecConfig = new VectorsConfiguration();

vecConfig.setVocabSize(vocabSizeLimit);
// This is hard-coded to true by DL4J for Word2Vec
vecConfig.setTrainElementsVectors(true);
// This is hard-coded to false by DL4J for Word2Vec
vecConfig.setTrainSequenceVectors(false);
// The default algorithm used for Word2Vec calculations
vecConfig.setElementsLearningAlgorithm(SkipGram.class.getCanonicalName());

Word2Vec vec = new Word2Vec.Builder(vecConfig)...etc...build();
```
This introduces redundancy in the code though, as it is the necessary to set the vocabLimit in two places (in the VectorsConfiguration and in the Word2Vec.Builder), as setting the value in VectorsConfiguration doesn't then set the value in Word2Vec even though you have passed it in the Word2Vec.Builder constructor. The other values are set elsewhere in DL4J but are simply not copied into the VectorsConfiguration.

**Issue present in 0.9.1 and 1.0.0-beta.**

**Comment by raver119** [comment]
Fixed, will be merged soon.
