### ISSUE TITLE
Embedding Layer support with CNN layer

### ISSUE THREAD

**Issue by romass12** [deeplearning4j/deeplearning4j#5723]
I want to use Embedding layer as first layer then CNN layer. But since Embedding layer accepts inputs as integers, can you guide me as to how to go about it

This is my model config  --> https://gist.github.com/romass12/143a7e30e291c3936cb4317659e80b4d

Features and labels as  -->
https://gist.github.com/romass12/35650ecd1d168089b5e075e9699c894f

Error stack trace:
https://gist.github.com/romass12/2721ec9f1684f8f33a480408ae7bba51

**Comment by AlexDBlack** [comment]
After thinking about this for a while, and making some other changes recently (available on snapshots, not on 1.0.0-beta), here's what I would recommend.

EmbeddingSequenceLayer can be used to generate sequences of embeddings with shape [minibatch, vectorSize, sequenceLength]. It also supports masking/variable length inputs (as of snapshots/master). Data of this format can be used with both RNN layers and 1D CNN layers.

If you want to use that data with a 2d CNN layer, you could implement a custom preprocessor that reshapes from [minibatch, vectorSize, sequenceLength] to [minibatch, 1, vectorSize, sequenceLength].

We could in principle add embedding layer support for 4d inputs (which is what I was originally thinking here) for [mb, 1, 1, seqLength] or [mb, 1, seqLength, 1], however I don't see much benefit to that over the approaches mentioned above.
