### ISSUE TITLE
[ComputationGraph] Task Not Serializable on Spark

### ISSUE THREAD

**Issue by romibuzi** [deeplearning4j/deeplearning4j#5727]
There was a new class [GraphIndices](https://deeplearning4j.org/doc/org/deeplearning4j/nn/graph/util/GraphIndices.html) added alongside `ComputationGraph` in DL4J 1.0.0-beta which leads to a `NotSerializableException` when using a ComputationGraph model inside a Spark distributed environment as follow : 

```
Exception in thread "main" org.apache.spark.SparkException: Task not serializable
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:298)
	at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:288)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:108)
	at org.apache.spark.SparkContext.clean(SparkContext.scala:2101)
	at org.apache.spark.rdd.RDD$$anonfun$flatMap$1.apply(RDD.scala:379)
	at org.apache.spark.rdd.RDD$$anonfun$flatMap$1.apply(RDD.scala:378)
...

Caused by: java.io.NotSerializableException: org.deeplearning4j.nn.graph.util.GraphIndices
Serialization stack:
	- object not serializable (class: org.deeplearning4j.nn.graph.util.GraphIndices, value: GraphIndices(topologicalSortOrder=[0, 1, 2, 3, 4, 5, 6], nameToIdx={input_lstm=0, merge=4, second_dense=6, output_dense=8, third_dense=7, first_lstm_layer=2, lastTimeStep=3, dense=5, output_layer=6}, idxToName={0=input_lstm, 2=first_lstm_layer, 3=lastTimeStep, 4=merge, 5=dense, 6=second_dense, 7=third_dense, 8=output_dense, 9=output_layer}))
	- field (class: org.deeplearning4j.nn.graph.ComputationGraph, name: graphIndices, type: class org.deeplearning4j.nn.graph.util.GraphIndices)
	- object (class org.deeplearning4j.nn.graph.ComputationGraph, org.deeplearning4j.nn.graph.ComputationGraph@2d1dbf4f)
org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:295)
	... 14 more
```

This is due to the fact `GraphIndices` does not implement `Serializable` interface

**Comment by raver119** [comment]
Show your source code please.

**Comment by AlexDBlack** [comment]
Right, we'd need to see source code for this.
Note that we don't really recommend serializing the ComputationGraph (or MultiLayerNetwork) objects directly - for example, on spark training, we pass around the configuration + parameters then initialize the net from those.

**Comment by romibuzi** [comment]
I've tried to keep the minimum source code that leads to the problem : 

```
package org.romibuzi.dl4jtests.main

import org.apache.spark.sql.SparkSession
import org.deeplearning4j.util.ModelSerializer
import org.nd4j.linalg.api.ndarray.INDArray
import org.nd4j.linalg.factory.Nd4j

object PredictMain {
  def main(args: Array[String]): Unit = {
    implicit val sparkSession: SparkSession = SparkSession
      .builder()
      .appName("SparkSession for tests")
      .master("local[*]")
      .getOrCreate()

    val model = ModelSerializer.restoreComputationGraph("model.zip")

    val input = sparkSession.sparkContext.parallelize(Seq(
      FeaturesRow(day= "2018-01-01", features = Nd4j.ones(1, 2, 1)),
      FeaturesRow(day= "2018-01-02", features = Nd4j.ones(2, 2, 1)),
      FeaturesRow(day= "2018-01-03", features = Nd4j.ones(3, 2, 1))
    ))

    // Predicting
    val results = input.map { x =>
      model.output(x.features)(0).toFloatVector
    }

    results.foreach(println)
  }
}

case class FeaturesRow(day: String, features: INDArray)
```

As you can see It doesn't happen during the training phase but when I'm trying to do distributed predictions via an RDD. The model was already trained before and I'm restoring it with `ModelSerializer.restoreComputationGraph` method

**Comment by romibuzi** [comment]
I found that one workarround in Scala for that is to make the model a `lazy` variable, so it will be loaded on each executor during the prediction of each RDD partition. I don't know if there is this possibility in Java.
Otherwise it's loaded from the driver, and Spark is distributing it to executors on the network in a serialized version. 

As @AlexDBlack said, it may not be the best way to load a model to do distributed predictions, so I'm not sure if this issue is really relevant. But this problem was not happening on 1.0.0-alpha version.

**Comment by raver119** [comment]
I think i have better solution. Let me try something.

**Comment by raver119** [comment]
After discussion with @AlexDBlack we've merged fix to master. It won't be an issue anymore.

**Comment by raver119** [comment]
P.s. thanks for highlighting this issue

**Comment by romibuzi** [comment]
No problem, thank you for your quick reaction and follow up ;)

**Comment by AlexDBlack** [comment]
BTW, if you want to access the fix: you can use snapshots
https://deeplearning4j.org/snapshots
