### ISSUE TITLE
passing word2vec object to neural network for training

### ISSUE THREAD

**Issue by dearpriyankasa** [deeplearning4j/deeplearning4j#5732]
How do I pass the word2vec object "vec" to neural network i.e MultiLayerNetwork for training purpose? Shall I pass the object before using "vec.fit()" or after that?

**Comment by raver119** [comment]
Could you please be a bit more specific? At this moment your question is very vague. Generally speaking you don't pass w2v object into MultilayerNetwork, you use it in other ways. And actual use depends on your use case.

What exactly you're trying to do there?

**Comment by dearpriyankasa** [comment]
Hi, I am trying to build a chatbot. I have 2 text files. Questions and answers. I have tokenized and passed both the files to 2 different word2vec and trained them in vec1 and vec2. Now I need to train a NN on this data i.e supervised training telling the NN that vec1 is input data for which vec2 should be the output.

**Comment by raver119** [comment]
Okay. So, got desired nn architecture? Can you post it?

**Comment by dearpriyankasa** [comment]
No.. I haven't got the architecture.
I have done this until now. No idea how do I proceed further.

Scanner sc = new Scanner(System.in);
        String s = "C:\\Users\\1547787\\Documents\\questions.txt";
        String s1 = "C:\\Users\\1547787\\Documents\\answers.txt";

        log.info("Load & Vectorize Sentences for Questions file....");
        SentenceIterator iter = new BasicLineIterator(s);
        TokenizerFactory t = new DefaultTokenizerFactory();
        t.setTokenPreProcessor(new CommonPreprocessor());
        
        log.info("Load & Vectorize Sentences for Answers file....");
        SentenceIterator iter1 = new BasicLineIterator(s1);
        TokenizerFactory t1 = new DefaultTokenizerFactory();
        t1.setTokenPreProcessor(new CommonPreprocessor());

        log.info("Building model for Questions....");
        Word2Vec vec = new Word2Vec.Builder()
                .minWordFrequency(1)
                .iterations(1)
                .layerSize(100)
                .seed(42)
                .windowSize(5)
                .iterate(iter)
                .tokenizerFactory(t)
                .build();

        log.info("Fitting Word2Vec model for Questions....");
        vec.fit();
        
        log.info("Building model for answers....");
        Word2Vec vec1 = new Word2Vec.Builder()
                .minWordFrequency(1)
                .iterations(1)
                .layerSize(100)
                .seed(42)
                .windowSize(5)
                .iterate(iter1)
                .tokenizerFactory(t1)
                .build();

        log.info("Fitting Word2Vec model for answers....");
        vec1.fit();

**Comment by raver119** [comment]
Sorry, if you don't know what architecture you're building, what's the question then?

**Comment by dearpriyankasa** [comment]
I am asking you what should be my next step after the above mentioned code. How do I correlate my answers to the questions in the bot?

**Comment by raver119** [comment]
I see.

**Comment by raver119** [comment]
Unfortunately, we do not provide free NN designs. We provide support for our framework.
