### ISSUE TITLE
Chatbot using nlp in dl4j - PLEASE HELP!

### ISSUE THREAD

**Issue by dearpriyankasa** [deeplearning4j/deeplearning4j#5733]
Hi, I am trying to make a Chatbot using dl4j. I have a excel document with issues and solutions with 60,000 records. My aim is to make a chatbot that inputs issues and the bot outputs the solution based on that issue. I have separated the issues and solutions in 2 different text files. I want my bot to learn from this data and provide solutions to similar problems (even though they are not exact). For this I am using the concept of nlp. I am tokenizing the data and feeding it to word2vec to produce vectors for both issues and solutions separately. How do I train the NN so that it gets to know the output for the input? and also it should be self-learning so that it provides possible solutions to the similar problems. How do I implement it in dl4j?

**Comment by agibsonccc** [comment]
We do not architect solutions for you. Hire someone if you want that kind of help.
