### ISSUE TITLE
Chatbot in dl4j - PLEASE HELP!

### ISSUE THREAD

**Issue by dearpriyankasa** [deeplearning4j/deeplearning4j#5735]
Hello, I am trying to make a Self-learning ChatBot in dl4j. I have data in excel format where there is an issue and solution. My aim is to develop a bot that will be used for providing solution to the issues entered by the user by training on the given dataset which has 60,000 records.  Also, it should learn by itself and try to provide appropriate solutions on the issues which are similar in meaning to the previous issues. I am storing issues and solutions in separate text files each. Using nlp concepts to tokenize the data and using 2 different word2vec for issues and solutions respectively. How do I correlate the issues to solutions? And is my overall approach correct?

**Comment by maxpumperla** [comment]
seriously, still no. no need to open other tickets.
