### ISSUE TITLE
Remaining ND4J test failures

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5750]
Test failures I'm seeing on this branch/PR (which fixes a number of issues, and should be merged soon): https://github.com/deeplearning4j/deeplearning4j/pull/5712

![image](https://user-images.githubusercontent.com/2360237/42068196-e546c23c-7b8d-11e8-83db-c5da86edc804.png)

Some observations:
- testGatherNd: memory issue (RNG seed reset?). Passes when only ```org.nd4j.autodiff``` tests are run
- NormalizerStandardizeTest: probably just RNG-related (passes in isolation; no RNG seed set)

**Comment by AlexDBlack** [comment]
A bunch of these have been fixed. I'll open a new issue later for remaining (if any) failures.

**Comment by raver119** [comment]
Nono, let's keep "0 failures" on master please.

**Comment by raver119** [comment]
:)
