### ISSUE TITLE
Rename XwPlusB to Linear

### ISSUE THREAD

**Issue by wmeddie** [deeplearning4j/deeplearning4j#5753]
Other frameworks like PyTorch and Chainer use the term Linear to describe this operation.  If we are using it for something else maybe we can use the term dense instead?

**Comment by AlexDBlack** [comment]
I'm happy with calling in Linear...

**Comment by maxpumperla** [comment]
we can leave it as is for tf users and create a samediff alias.

**Comment by wmeddie** [comment]
👍 for an alias.  Though I think one big difference is that bias is optional for Linear but XwPlusB kind of implies B being a required thing.
