### ISSUE TITLE
SameDiff: Serialization (/loading flatbuffers in Java)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5759]
Use case: I want to save/serialize a SameDiff instance graph/op structure - without the arrays - and in a format that won't break on every version upgrade.

(Why: this would allow what I would call "true" lambda layers in DL4J: a neat but non-critical feature... defining no-params layers as a lambda class should be possible now (pending a PR merge) but the JSON serialization clearly won't work here. However, if I can write a custom JSON serializer that handles the SameDiff instance serialization, even in a binary format - that would be fine).

Currently, the only serialization format we support is FlatBuffers - via SameDiff.asFlatBuffers.
However, this is inadequate for the above use case for 2 reasons:
1. Arrays are always included
2. As far as I can see: there is no way to create a new SameDiff instance from a serialized FlatBuffers version.

**Comment by AlexDBlack** [comment]
Discussed in dev channel: adding support to load the FlatBuffers format we already have seems like a reasonable way forward here.

Adding support to not serialize the arrays should also be easy.

**Comment by raver119** [comment]
Arrays are always included mostly due to const existence. Arrays, which are not outputs of existing ops must be preserved.
