### ISSUE TITLE
Early stopping not working with ClassificationScoreCalculator and Accuracy evaluation metric

### ISSUE THREAD

**Issue by gorankarlic** [deeplearning4j/deeplearning4j#5760]
Using `EarlyStoppingTrainer` in combination with a `ClassificationScoreCalculator` and `Evaluation.Metric.ACCURACY` does not work.

This is because in `BaseEarlyStoppingTrainer` the better model `score` is expected to be lower - but when using accuracy as a score, the better model `score` is actually higher.

https://github.com/deeplearning4j/deeplearning4j/blob/74bd70162979bace33cf28b160aeb61131e13bcc/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/earlystopping/trainer/BaseEarlyStoppingTrainer.java#L204-L205

I am not sure how this is best fixed.

### Example configuration (selects the worst model)
```
ScoreCalculator<Model> scoreCalculator = new ClassificationScoreCalculator(Evaluation.Metric.ACCURACY, testDataSetIterator);
EarlyStoppingConfiguration.Builder<MultiLayerNetwork> earlyStoppingConfiguration = new EarlyStoppingConfiguration.Builder<>();
earlyStoppingConfiguration.scoreCalculator(scoreCalculator);
```

### Workaround (selects the best model)

For now the best workaround seems to be to override `ClassificationScoreCalculator` and reverse the score.

```
ScoreCalculator<Model> scoreCalculator = new ClassificationScoreCalculator(Evaluation.Metric.ACCURACY, testDataSetIterator)
{
    @Override
    public double calculateScore(Model network)
    {
        //Reverse the score
        return 1.0 - super.calculateScore(network);
    }            
};
```

**Comment by AlexDBlack** [comment]
Thanks for reporting. This was fixed recently.
I've added it as a known issue to the release notes: https://deeplearning4j.org/releasenotes#deelpearning4j-100-beta-known-issues
