### ISSUE TITLE
Keras imported model returns binary probabilities

### ISSUE THREAD

**Issue by Vigasto** [deeplearning4j/deeplearning4j#5780]
I'm currently trying to predict some images with keras models in DL4J : 

```java
NativeImageLoader loader = new NativeImageLoader(64,64,3);
INDArray image = loader.asMatrix(cvImage);

MultiLayerNetwork model = KerasModelImport.importKerasSequentialModelAndWeights("vggnet.hdf5", false);

INDArray output = model.output(image,false);
System.out.println(output);
```

and got output vectors with only either 0 or 1 such as : ```[[    1.0000,         0,         0,         0]]```

However, trying to reproduce back with python : 

```python
model = load_model('vggnet.hdf5')
probs = model.predict(img)
print(probs)
```
results in more acceptable probabilities ```[[  9.90583420e-01   1.32544708e-04   8.52192007e-03   7.62143754e-04]]```

I'll post the model somewhere else if needed

**Comment by maxpumperla** [comment]
@Vigasto yes, please provide your model as well and maybe the image you use for comparison. It could very well be that your preprocessing causes this. Might be worth simply trying to predict on artificial numpy and nd4j arrays first. The reason I'm skeptical about this is that we have gradient checks passing for imported models of similar type, e.g. this one:

https://github.com/deeplearning4j/deeplearning4j/blob/38138ca40cd05e62ec553bdbd07c9bad11495724/deeplearning4j/deeplearning4j-modelimport/src/test/java/org/deeplearning4j/nn/modelimport/keras/e2e/KerasModelEndToEndTest.java#L146

Also, which DL4J version do you use?

**Comment by Vigasto** [comment]
Sorry, it took a while for me to upload the files : 

[vggnet.hdf5](https://www.dropbox.com/s/lmf28t57gzyfcuq/vggnet.hdf5?dl=0)
[apple_scab.JPG](https://www.dropbox.com/s/u9vj8uvrqsak1z7/apple_scab.JPG?dl=0)

I also put my preprocessing below with OpenCV, just in case I missed something 

In Java 
```java
Mat srcImage = opencv_imgcodecs.imread(args[0]);
Mat cvImage = new Mat(64,64,srcImage.type());
opencv_imgproc.resize(srcImage,cvImage,cvImage.size(),0,0,opencv_imgproc.INTER_CUBIC);
NativeImageLoader loader = new NativeImageLoader(64,64,3);
INDArray image = loader.asMatrix(cvImage);
```
In Python
```python
im1 = cv2.imread(img_path)
img_res=cv2.resize(im1,dsize=(64,64),interpolation=cv2.INTER_CUBIC)
img=img_res.reshape((1,img_res.shape[0],img_res.shape[1],img_res.shape[2]))
img=img/255.0
```

I'm currently using 1.0.0-beta version

**Comment by maxpumperla** [comment]
meaning that in Python you divide channel data by 255 and in Java you don't?

**Comment by Vigasto** [comment]
My bad. I was able to reproduce the binary probabilities with no channel data division.

I'll be looking in ways to do it in Java, but it will be outbound from this issue. Sorry for the false alarm.

**Comment by agibsonccc** [comment]
Maybe use javacv or our built in image etl? That would work in java

**Comment by Vigasto** [comment]
Thank you. But simply adding 
```java
image.divi(255.0);
```
resolves my case.
