### ISSUE TITLE
Cannot turn off Word2Vec parallel tokenization

### ISSUE THREAD

**Issue by TheKingDiamond** [deeplearning4j/deeplearning4j#5784]
When calling fit() on a configured Word2Vec object in Java, it seems that the value set for allowParallelTokenization by the Word2Vec.Builder is not carried through to where it is needed in the code.

Specifically, the following should build a Word2Vec object that does _not_ use parallel threads during the tokenization stage:

```
Word2Vec vec = new Word2Vec.Builder()
                ...set some hyperparameters...
                .allowParallelTokenization(false)
                .build();
```

The call to build() creates a new SentenceTransformer object, which is used in the iterator, which correctly contains the value _false_ for the field _allowMultithreading_.

When fit() is called on the configured Word2Vec object, there is call to the SequenceVectors method buildVocab() - this creates a VocabConstructor object which is then used to construct the vocabulary from the text corpus. The initialization of this object (line 112 of SequenceVectors) is as follows:

```
VocabConstructor<T> constructor = new VocabConstructor.Builder<T>().addSource(iterator, minWordFrequency)
        .setTargetVocabCache(vocab).fetchLabels(trainSequenceVectors).setStopWords(stopWords)
        .enableScavenger(enableScavenger).setEntriesLimit(vocabLimit)
        .setUnk(useUnknown && unknownElement != null ? unknownElement : null).build();
```

This is missing a call to the _allowParallelTokenization_ of VocabConstructor.Builder, thus the default value of _true_ is always used and parallel tokenization is essentially always on!

**Version: 1.0.0-beta.**

**Comment by TheKingDiamond** [comment]
Thank you @raver119 !

**Comment by raver119** [comment]
Fixed. Thanks for highlighting this problem.

**Comment by raver119** [comment]
Yes, it's covered with tests. Got some output to show?

**Comment by raver119** [comment]
p.s. and threads dump please

**Comment by TheKingDiamond** [comment]
Hi @raver119 , sorry for the delay in my response! I've been away but I am back now.

I have isolated the root of the issue by pausing execution whilst my simple Java program is hanging (it gets stuck during the call to _fit()_ on a Word2Vec object). The program simply sets the parameters on a Word2Vec object and then calls the _fit()_ method, as described in my first post for this issue.

The cause of this issue is in the protected class _VocabRunnable_ within the VocabConstructor file. This class has an instance boolean variable _done_ which is never explicitly assigned a value. It therefore takes the default value of _false_; this value is never changed anywhere else in the code. This causes the following method (line 571, VocabConstructor$VocabRunnable) to enter an infinite loop, the VocabRunnable is waiting forever:

```
public void awaitDone() throws InterruptedException {
    synchronized (this) {
        while (! done) {
            this.wait();
        }
    }
}
```
This awatDone() method is called in the VocabConstructor method _buildJointVocabulary_, and is only accessed when _allowParallelBuilder_ is false. Thus, this infinite loop is only entered when calling _fit_ on a Word2Vec object where parallel tokenization has been disallowed.
