### ISSUE TITLE
SameDiff: Conv1D configuration incorrect?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5789]
Refers to data format as NWHC, and has isNHWC... yet conv1d should only have 3 dimensions for the input data?

https://github.com/deeplearning4j/deeplearning4j/blob/a2f6083968ef3fab2caff8e81c869edbe83dcb16/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/layers/convolution/config/Conv1DConfig.java#L22-L24

**Comment by maxpumperla** [comment]
yes, this is wrong. I'd suggest to go with `isNHC`, as this would also align with libnd4j:

```
    int isNCW      = block.getIArguments()->size() > 4 ? !INT_ARG(4) : 1;       // 0-NCH,  1-NHC
```
