### ISSUE TITLE
ND4J/Libnd4j: Reverse on all dimensions not working?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5795]
Not 100% sure on this one (need to compare behaviour vs. other libraries):

```
SameDiff sd = SameDiff.create();
SDVariable var = sd.var(Nd4j.create(new double[][]{{1,2,3},{4,5,6}}));
SDVariable out = sd.reverse(var, 0, 1);
```

```
[[         0,         0,         0], 
 [         0,         0,         0]]
```

Works fine for the dimension 0 and dimension 1 cases in isolation

**Comment by shugeo** [comment]
reverse has two ways to use: with 2 NDArrays with input (the input and axis) - in that case int param used as bool flag. In other case - int params used as axes.

**Comment by AlexDBlack** [comment]
I re-tested this - confirmed fixed. Thanks.
