### ISSUE TITLE
Time for training

### ISSUE THREAD

**Issue by dearpriyankasa** [deeplearning4j/deeplearning4j#5798]
I am executing the program EncoderDecoderLSTM.java from the examples in github. The model is getting trained since one and a half hour. What is the total time required for training the Neural network in the EncoderDecoderLSTM.java program in dl4j examples of github? Am I proceeding correctly?

**Comment by saudet** [comment]
Could you provide more information about your hardware and the pom.xml file you are using?

**Comment by raver119** [comment]
Sorry, it'll be impossible to answer your question. We just don't have such CPU, so we can't know how much time it'll take.

Just few facts:
- 6 year old cpu
- 2 cores
- no AVX2 support

So, i'd expect it to work, but work slow. Just make sure you don't disable workspaces, and try to not do anything else while network trains.
