### ISSUE TITLE
WordVectorSerializer.readParagraphVectors(file) didn't init the SourceLabel

### ISSUE THREAD

**Issue by tvanh** [deeplearning4j/deeplearning4j#5806]
The paragraph vector loaded using WordVectorSerializer.readParagraphVectors(file) has null label source.

Cause:
During reading paragraph vector, the list of label is read (and extracted by the ParagraphVectors.extractLabels()), but not pass to source label. 

Effect:
[1] ParagraphVectors.getLabelSource() is always null if the model is load from file.
[2] ParagraphVectors.predict(String text) will get error since 
        for (String s : labelsSource.getLabels()) {
will cause the NullPointerException error.

**Comment by raver119** [comment]
Fixed thanks for highlighting this one. However, mind telling how you're using your model? You shouldn't  need this object usually.
