### ISSUE TITLE
tests build issue

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#5823]
How CLion (or any other IDE) should be set up for tests environment these days?
I get this error on Windows now:
```
C:\msys64\mingw64\bin\g++.exe  -g -fPIC -std=c++11 -fassociative-math -funsafe-math-optimizations -fmax-errors=2 -DLIBND4J_ALL_OPS=true -fopenmp  -g -fPIC -std=c++11 -fassociative-math -funsafe-math-optimizations -fmax-errors=2   -Wl,--whole-archive CMakeFiles\runtests.dir/objects.a -Wl,--no-whole-archive  -o runtests.exe -Wl,--out-implib,libruntests.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\runtests.dir\linklibs.rsp
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lstatic
collect2.exe: error: ld returned 1 exit status
```

**Comment by crockpotveggies** [comment]
Thanks for submitting this issue. We've migrated our docs to its own separate repository at [deeplearning4j-docs](https://github.com/deeplearning4j/deeplearning4j-docs). I've already migrated your issue and you can find it at https://github.com/deeplearning4j/deeplearning4j-docs/issues/90. 

I'll be closing this, but feel free to comment and re-open if this is not what you intended.

*This was an automatically generated response.*

**Comment by saudet** [comment]
That's strange, I'm not seeing `-lstatic` anywhere in your command or in the files of libnd4j. Where is it coming from...

**Comment by saudet** [comment]
I've just tried `run_tests.sh` on Windows and there's nothing weird happening. It builds fine and the tests run OK. Are you having issues only in CLion? Or on the command line with MSYS2 as well?

**Comment by raver119** [comment]
CLion only. It tries to work with CMakeList and fails with that message at
last step.

**Comment by shyrma** [comment]
Hi guys!
I have a questions concerning script /deeplearning4j/libnd4j/tests_cpu/run_tests.sh:
1) if I don't want to run tests, and I want just to build, what option/flag should I use ?
2) if I don't want to build, and I want just to run all tests, what option/flag should I use ?
3) if I don't want to build, and I want just to run certain test/tests, what filter/option/flag should I use ?

Yes I'm aware about separate commands:

deeplearning4j/libnd4j/buildnativeoperations.sh -t -b debug   -> build only

deeplearning4j/libnd4j//blasbuild/cpu/tests_cpu/layers_tests/runtests --gtest_filter=DeclarableOpsTests9.* -> run certain tetsts

I ask you about this because, If I understand correctly, you decided to combine/unify  build and run options using that script.

**Comment by sshepel** [comment]
@shyrma as been discussed in slack I can provide logic for `gtets_filter` flag in `run_tests.sh`.
Also, just want to note, that part of changes in `buildnativeoperations.sh` and `run_tests.sh` @saudet didn't by my request, for CI.

**Comment by saudet** [comment]
It's not just for CI, it doesn't make sense to never run tests on the binary that we are actually releasing!

**Comment by raver119** [comment]
Re: original issue. That's easy fix, you just hadn't set any defaults for build. Once i propagate them as CMake variables - build runs fine.

But now there's another problem, and it's serious game breaker: build time sky rocketed. 
On windows i7 8700k + nvme ssd + 32GB ram - it's 16 minutes. 99% of the time spent on linking steps, for static library and for runtests. So, even after chaning 1 file - it takes 16 minutes to run tests.

This should be fixed asap, that's serious blocker :(

**Comment by raver119** [comment]
P.s. i'll send pr that fixes few issues though.

**Comment by raver119** [comment]
Linux compilation time almost tripled too, on the same machine it took 2m 20s to build stuff. Now it's 6m.

**Comment by raver119** [comment]
![libnd4j c__develop_deeplearning4j_libnd4j - _tests_cpu_layers_tests_declarableopstests7 cpp - clion 7_7_2018 13_26_24](https://user-images.githubusercontent.com/12250879/42414407-9975c26a-81e9-11e8-8673-f6db463e9d79.png)

Bottom left corner. 18 minutes 30 seconds.

**Comment by saudet** [comment]
Well, I've checked the build time of the main library just before that commit (https://github.com/deeplearning4j/deeplearning4j/commit/b43e7aaf54c035295ef307f7eccff80da1aef026) with CCACHE_DISABLE=1 and it's "slow":
```
real	8m18.141s
user	28m38.490s
sys	1m25.513s
```
So, we have 2 options:
1. We keep testing binaries that we are not actually shipping
2. We make faster the build of the library that we are actually shipping

**Comment by agibsonccc** [comment]
I agree, even if it's just for a subset of the framework.  The CI running tests is pretty useless when we have to wait hours just to run tests.  Blazing fast builds is a part of that.

**Comment by raver119** [comment]
It's not about CI right now, it's about developer spending hour just to compile minor change 3 times . I don't know why yet, but on windows it's really that bad. Linking takes 18 minutes even if you're just changed 1 file.

**Comment by agibsonccc** [comment]
I disagree. It's about both. The build affects CI times. We need this for both PRs as well as local development.

**Comment by raver119** [comment]
Ok, let me re-frame that as "it's not about CI ***for me*** right now" 😄 

I'm just scared of debugging process with this time.., Especially on Windows.

**Comment by saudet** [comment]
Well, revert the PR if you want and we'll get back to that when you guys
make your code build faster.

**Comment by saudet** [comment]
I'm pretty sure we can alleviate build time issues with ccache though. On Windows, install it by running `pacman -S mingw-w64-x86_64-ccache` and let's see if that's satisfactory. We also need the following patch:
```diff --git a/libnd4j/buildnativeoperations.sh b/libnd4j/buildnativeoperations.sh
index c9c621f27f..710e5fb0b3 100755
--- a/libnd4j/buildnativeoperations.sh
+++ b/libnd4j/buildnativeoperations.sh
@@ -284,8 +284,8 @@ case "$OS" in
         export MAKE_COMMAND="make"

         # Sam, do we really need this?
-        export CC=/mingw64/bin/gcc
-        export CXX=/mingw64/bin/g++
+        export CC="ccache gcc"
+        export CXX="ccache g++"
         PARALLEL="true"

     fi
```
With that, the first build takes about 10 minutes, but any subsequent build from scratch take less than 1 minute.

**Comment by raver119** [comment]
Issue is resolved long ago,  separate CMakeLists.txt added to tests_cpu/libnd4j_tests folder, and now all IDEs are quite happy as well as CI afaik
