### ISSUE TITLE
SIGSEGV for linux ppc64le platform with libnd4j CPU backend

### ISSUE THREAD

**Issue by sshepel** [deeplearning4j/deeplearning4j#5850]
Noticed strange error during test stage.
Error log and core dump could be found below.
Gist: https://gist.github.com/sshepel/f8c38c9b5dd068d2f5c5e42f597c61db

**Comment by saudet** [comment]
This just looks like corrupted memory... This should get picked up with AddressSanitizer. Let's just enable that and see, supposed to be supported on Power: https://github.com/google/sanitizers/wiki/AddressSanitizer

**Comment by raver119** [comment]
It’s fixed in my pr.

**Comment by sshepel** [comment]
Fixed by https://github.com/deeplearning4j/deeplearning4j/pull/5852, thanks @raver119
