### ISSUE TITLE
Slice method in GravesLSTM should be replaced to fix #282 in nd4j

### ISSUE THREAD

**Issue by drlebedev** [deeplearning4j/deeplearning4j#586]
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/recurrent/GravesLSTM.java#L341 is failing for me, when data shape is [1, 10, 100] (100 time point with 1 sample per time point and 10 values per sample). 

According to https://github.com/deeplearning4j/nd4j/issues/282 slice should not be used for such kind of tasks. 

Adam (@agibsonccc) said in gitter:

> Yes. We need to update that.
> There's 2 things we can do here
> We can also do indexing
> rather than slicing
> slice(0) is equivalent to get(NDArrayIndex.point(0))
> etc
> Everything is being routed through the indexing engine
> for both speed purposes as well as bug reduction

Slices should not be used for gates and activations as well.

jfyi @AlexDBlack

**Comment by AlexDBlack** [comment]
I'll take a look at this soon. I plan on spending some time doing numerical gradient checks and debugging on both GRU layer (WIP - branch https://github.com/deeplearning4j/deeplearning4j/tree/ab_grurnn) and GravesLSTM over the next few days.

**Comment by agibsonccc** [comment]
Thanks. Just worth mentioning as we finish these updates.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/596
