### ISSUE TITLE
Keras import test failures on master

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/deeplearning4j#5860]
Not sure what happened, but the following tests fail currently on master:

```
Results :

Failed tests: 
  KerasModelEndToEndTest.importCnnNoBiasTfKeras2:279->importEndModelTest:596->checkGradients:743 Gradient check failed
  KerasModelEndToEndTest.importMnistCnnTfKeras2:155->importEndModelTest:555->compareINDArrays:662
  KerasModelEndToEndTest.importMnistCnnThKeras1:148->importEndModelTest:555->compareINDArrays:662
  KerasModelEndToEndTest.importMnistMlpReshapeTfKeras1:131->importEndModelTest:555->compareINDArrays:662
  KerasModelEndToEndTest.importMnistMlpTfKeras1:110->importEndModelTest:555->compareINDArrays:662
  KerasModelEndToEndTest.importMnistMlpTfKeras2:124->importEndModelTest:555->compareINDArrays:662
  KerasModelEndToEndTest.importMnistMlpThKeras1:117->importEndModelTest:555->compareINDArrays:662

Tests run: 140, Failures: 7, Errors: 0, Skipped: 6
```

Those tests are output differences between DL4J and Keras on simple MLPs and CNNs. Afaict nothing has changed in Keras import that would cause this, but I need to further investigate this issue.

**Comment by maxpumperla** [comment]
after spending way too much time on this, that commit seems to be the issue: https://github.com/deeplearning4j/deeplearning4j/pull/5855/files

Changing back to 0.3.0 on master fixes tests

**Comment by saudet** [comment]
Yeah, should revert to 0.3.0 until 0.3.2 comes out it looks like:
https://github.com/xianyi/OpenBLAS/issues
