### ISSUE TITLE
DL4J: Add exception for non-thread-safe use of MLN/CG

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5862]
MLN/CG are not thread safe, but when users try to use it in a multithreaded environment, they may get obsure errors that are hard to identify.

Perhaps we could track which threads are being used in say output/fit methods, and if we detect concurrent use of the net, throw a useful exception.

**Comment by raver119** [comment]
As discussed in pm, we've decided to enforce sequential access to certain methods, like `fit()`, `output()` and `feedForward*()` instead of throwing exceptions
