### ISSUE TITLE
cumprod_bp op

### ISSUE THREAD

**Issue by shugeo** [deeplearning4j/deeplearning4j#5871]
Needed cumulative product backprop operation math.

**Comment by AlexDBlack** [comment]
I'm not 100% sure on the last 2, but I've derived the first 2 twice independently and got the same answer both times...

2 of 4 cases were covered here: https://github.com/deeplearning4j/deeplearning4j/blob/698a29ed068691b2cb9a29078f304b89cf52bad0/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/autodiff/opvalidation/ReductionBpOpValidation.java#L715-L725

Other 2 cases:

Forward, exclusive:
```
dL/dIn_i  = sum_j dL/dOut_j * dOut_j/dIn_i
          = sum_j dL/dOut_j * d(in_1 * ... * in_{j-1})/dIn_i
          = sum_j 1_{i>=j+1} dL/dOut_j * out_j / in_i
          = reverseCumSumExclusive(y/x_i * dL/dOut_j)
```

Reverse, exclusive:
By symmetry, it's probably: ```cumSumExclusive(y/x_i * dL/dOut_j)```

**Comment by shugeo** [comment]
It is very useful a test data for cumprod_bp.
