### ISSUE TITLE
Broken links and images on docs

### ISSUE THREAD

**Issue by rahul-raj** [deeplearning4j/deeplearning4j#5877]
Post: [https://skymind.ai/wiki/lstm.html](https://skymind.ai/wiki/lstm.html) has lots of broken images to fix for:
https://skymind.ai/wiki/img/lstm_gru.png
https://skymind.ai/wiki/img/feedforward_rumelhart.png
https://skymind.ai/wiki/img/gates_lstm.png
https://skymind.ai/wiki/img/recurrent_equation.png
https://skymind.ai/wiki/img/greff_lstm_diagram.png
https://skymind.ai/wiki/img/gers_lstm.png
https://skymind.ai/wiki/img/sigmoid_vanishing_gradient.png
https://skymind.ai/wiki/img/srn_elman.png

**Comment by saudet** [comment]
Thanks! Please post a pull request here if you can:
https://github.com/deeplearning4j/deeplearning4j-docs/pulls

**Comment by crockpotveggies** [comment]
Thanks for submitting this issue. We've migrated our docs to its own separate repository at [deeplearning4j-docs](https://github.com/deeplearning4j/deeplearning4j-docs). I've already migrated your issue and you can find it at https://github.com/deeplearning4j/deeplearning4j-docs/issues/95. 

I'll be closing this, but feel free to comment and re-open if this is not what you intended.

*This was an automatically generated response.*
