### ISSUE TITLE
back prop for clipbynorm, eye, diag

### ISSUE THREAD

**Issue by shyrma** [deeplearning4j/deeplearning4j#5883]
we have to provide proper backprop implementation for ops (clipbynorm, eye, diag) on c++ side since there are fails during gradient checks for these ops on java side

**Comment by AlexDBlack** [comment]
We don't need BP op for eye - no real-valued inputs hence there's nothing really to backprop. What's the failing test?

As for diag - backprop should simply be diag_part operation, which we have implemented at java level already.
https://github.com/deeplearning4j/deeplearning4j/blob/74bd70162979bace33cf28b160aeb61131e13bcc/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/shape/Diag.java#L39-L42

**Comment by raver119** [comment]
> o.n.a.o.TransformOpValidation - All failed transforms: [clipbynorm, cumsum, cumprod, diag, noop, match_condition_transform]

cumsum was fixed yesterday. 
diag apparently listed as failed on current master.

**Comment by raver119** [comment]
With clipbynorm implemented, i guess we can close this issue now?
