### ISSUE TITLE
DL4J: Convolution1DLayer getOutputType needs work

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5907]
https://github.com/deeplearning4j/deeplearning4j/blob/b79313eb832aea854831182e2401611788d42fe4/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/layers/Convolution1DLayer.java#L69-L70

Doesn't handle the "time series length is undefined" case.
And this doesn't look correct either:
```
InputType dummyConv = new InputType.InputTypeConvolutional(inputTsLength, inputTsLength, nOut);
```

**Comment by maxpumperla** [comment]
@AlexDBlack the second part is valid. remember that in our current impl conv1d is a special case of conv2d, so we mock up the input type to use conv2d utils.

**Comment by maxpumperla** [comment]
but I recently introduced 1D conv utils, so maybe this could be refactored
