### ISSUE TITLE
Incorrect import of MultiDataSet  in SparkComputationGraph class

### ISSUE THREAD

**Issue by NookLook2014** [deeplearning4j/deeplearning4j#5916]
imports in org.deeplearning4j.spark.impl.graph.SparkComputationGraph include:
....
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.dataset.api.MultiDataSet; (this is a interface)
....

Since i can only create org.nd4j.linalg.dataset.MultiDataSet instance, so error occurs when i use fitMultiDataSet(RDD[ org.nd4j.linalg.dataset.MultiDataSet]):

Error:(112, 16) overloaded method value fitMultiDataSet with alternatives:
  (x$1: String)org.deeplearning4j.nn.graph.ComputationGraph <and>
  (x$1: org.apache.spark.api.java.JavaRDD[org.nd4j.linalg.dataset.api.MultiDataSet])org.deeplearning4j.nn.graph.ComputationGraph <and>
  (x$1: org.apache.spark.rdd.RDD[org.nd4j.linalg.dataset.api.MultiDataSet])org.deeplearning4j.nn.graph.ComputationGraph
 cannot be applied to (org.apache.spark.rdd.RDD[org.nd4j.linalg.dataset.MultiDataSet])
      sparkNet.fitMultiDataSet(data)

**Comment by AlexDBlack** [comment]
This isn't an incorrect import. You could (and, arguably should) be fitting with ```JavaRDD<org.nd4j.linalg.dataset.api.MultiDataSet>``` instead.

That said, adding some overloads like ```fit(JavaRDD<org.nd4j.linalg.dataset.MultiDataSet>, ...)``` would be useful for users.

**Comment by NookLook2014** [comment]
I'm coding with Scala, and it works when called asInstanceOf[org.nd4j.linalg.dataset.MultiDataSet] before fit.
