### ISSUE TITLE
Merging 2 neural networks

### ISSUE THREAD

**Issue by dearpriyankasa** [deeplearning4j/deeplearning4j#5923]
best way to merge two different neural networks which are trained for the same tasks but on different datasets (we do not have the access to the datasets, but we have trained models). I have trained 2 models of neural nets on different PCs. Half data set on model 1 and other half on model 2. Both are doing the same task. how do i combine both the neoral nets to produce output using dl4j.

**Comment by AlexDBlack** [comment]
We don't have any examples for this specifically.
What you are looking for is usually called one (or more) of the following: mimic learning, model compression, knowledge distilation (and maybe some more I've forgotten).
If you had a specific approach you wanted to try (and a link to a paper) we could help more.

Alternatively you can use them as an ensemble. That's very simple: just do an (optionally weighted) average of the outputs of the two networks. You'll still have 2 nets, but one probability distribution.
