### ISSUE TITLE
Dl4j DEBUG

### ISSUE THREAD

**Issue by NisreenAlaas** [deeplearning4j/deeplearning4j#5927]
Debug in DL4j the machine [CPU]; OS: [Windows 8.1]
Cores: [4]; Memory: [1.3GB] using java in IntelliJ idea version 2017.3.4 Community Edition.snapshot for debug 
![capture](https://user-images.githubusercontent.com/16560173/42912364-b2328f56-8af7-11e8-9776-08a801ab148c.PNG) in the evaluate stage when fitting the dataset (net.fit(trainIter)). I need to classify 4 names written by hand in Arabic language. every name locates in one folder. The data spilite into training and testing folders.
![testing folder](https://user-images.githubusercontent.com/16560173/42912517-7497c12e-8af8-11e8-9569-093405665da5.PNG)
![training folder](https://user-images.githubusercontent.com/16560173/42912518-7519eab4-8af8-11e8-9b35-2d77202dea7e.PNG) here is a sample of the dataset 
![sampleofdataset](https://user-images.githubusercontent.com/16560173/42912599-e1285934-8af8-11e8-8409-cbeb7e9dd3a3.PNG). The code is MINST example and I modified some statement to justify my program. The objective of this program is to classify the name as in its folder. How can I solve this issue? More detail for code can go to GitHub in( https://github.com/NisreenAlaas/HandwritingReco.git).
thank you in advance

**Comment by NisreenAlaas** [comment]
I need your comments and solution or linking to help me to understand this debug

**Comment by agibsonccc** [comment]
I'm not even sure what your question is here. Please come in to gitter with a more concrete qustion: https://gitter.im/deeplearning4j/deeplearning4j
