### ISSUE TITLE
Add ability to read and write NDArrays in base64 numpy format.

### ISSUE THREAD

**Issue by wmeddie** [deeplearning4j/deeplearning4j#5928]
It would be nice from a convenience and performance standpoint in SKIL if Nd4jBase64.frameBase64 could automatically detect if the base64 string is in npy format and deserialize the NDArray using our numpy reading support.  Likewise it would be nice if we could also have a base64String(INDArray, String format) method that could serialize an NDArray in npy format for python clients.

**Comment by wmeddie** [comment]
Here's the spec for the numpy format which specifies the magic string we can detect: https://docs.scipy.org/doc/numpy/neps/npy-format.html

**Comment by AlexDBlack** [comment]
Looks like that link is dead. However, I did find this: https://github.com/numpy/numpy/blob/master/numpy/lib/format.py

**Comment by AlexDBlack** [comment]
Added recently.
