### ISSUE TITLE
testSubSampleLayerAvgBackprop issue in SubsamplingLayerTests

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#593]
reshapeEpsilon after col2im comes back as 2,2,4,4 when it should be 1,2,4,4 and order of results seems out of order but depends on shape:
[[[[0.25,0.25,0.00,0.00]
 [0.25,0.25,0.00,0.00]
 [0.50,0.50,0.00,0.00]
 [0.50,0.50,0.00,0.00]]
  [[0.75,0.75,0.00,0.00]
 [0.75,0.75,0.00,0.00]
 [1.00,1.00,0.00,0.00]
 [1.00,1.00,0.00,0.00]]]
   [[[1.25,1.25,0.00,0.00]
 [1.25,1.25,0.00,0.00]
 [1.50,1.50,0.00,0.00]
 [1.50,1.50,0.00,0.00]]
  [[1.75,1.75,0.00,0.00]
 [1.75,1.75,0.00,0.00]
 [2.00,2.00,0.00,0.00]
 [2.00,2.00,0.00,0.00]]]]

expected: 

[[[[ 0.25,  0.25,  0.5 ,  0.5 ],
[ 0.75,  0.75,  1.  ,  1.  ],
[ 0.25,  0.25,  0.5 ,  0.5 ],
[ 0.75,  0.75,  1.  ,  1.  ]],
[[ 1.25,  1.25,  1.5 ,  1.5 ],
[ 1.75,  1.75,  2.  ,  2.  ],
[ 1.25,  1.25,  1.5 ,  1.5 ],
 [ 1.75,  1.75,  2.  ,  2.  ]]]]

**Comment by agibsonccc** [comment]
JFYI, this declaration is invalid:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/test/java/org/deeplearning4j/nn/layers/convolution/SubsamplingLayerTest.java#L142-142

Buffer length is 23 prod(shape) == 32

**Comment by nyghtowl** [comment]
In the [test](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/test/java/org/deeplearning4j/nn/layers/convolution/SubsamplingLayerTest.java) it is having issues currently during initial epsilon.get:

- [epsilon.get](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/convolution/subsampling/SubsamplingLayer.java#L114) should return shape 1,2,1,1,2,2 vs 1,1,1,2,1,2,2 and the order is not correct. 

It should be: 
[[[[[[ 1.,  2.],
           [ 3.,  4.]]]],
        [[[[ 5.,  6.],
           [ 7.,  8.]]]]]])

but its returning
[[[[[[[1.00,2.00]
 [2.00,3.00]]]
   [[[5.00,6.00]
 [6.00,7.00]]]]]]]

- [tile result](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/convolution/subsampling/SubsamplingLayer.java#L115) has the correct shape (1,2,2,2,2) if the epsilon is reshaped correctly above. The expected result should be:
([[[[[[ 1.,  2.],
           [ 3.,  4.]],
          [[ 1.,  2.],
           [ 3.,  4.]]],
         [[[ 1.,  2.],
           [ 3.,  4.]],
          [[ 1.,  2.],
           [ 3.,  4.]]]],
        [[[[ 5.,  6.],
           [ 7.,  8.]],
          [[ 5.,  6.],
           [ 7.,  8.]]],
         [[[ 5.,  6.],
           [ 7.,  8.]],
          [[ 5.,  6.],
           [ 7.,  8.]]]]]])

-[col2im](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/convolution/subsampling/SubsamplingLayer.java#L116) has the correct shape (1,2,4,4) if the initial epsilon reshape is fixed. Expected result should be:
[[[[ 1.,  1.,  2.,  2.],
         [ 1.,  1.,  2.,  2.],
         [ 3.,  3.,  4.,  4.],
         [ 3.,  3.,  4.,  4.]],

        [[ 5.,  5.,  6.,  6.],
         [ 5.,  5.,  6.,  6.],
         [ 7.,  7.,  8.,  8.],
         [ 7.,  7.,  8.,  8.]]]])

- final result should be:
[[[[ 0.25,  0.25,  0.5 ,  0.5 ],
         [ 0.25,  0.25,  0.5 ,  0.5 ],
         [ 0.75,  0.75,  1.  ,  1.  ],
         [ 0.75,  0.75,  1.  ,  1.  ]],

        [[ 1.25,  1.25,  1.5 ,  1.5 ],
         [ 1.25,  1.25,  1.5 ,  1.5 ],
         [ 1.75,  1.75,  2.  ,  2.  ],
         [ 1.75,  1.75,  2.  ,  2.  ]]]])

**Comment by nyghtowl** [comment]
For reference on results checkout this [link](https://github.com/nyghtowl/Scratch-notes/blob/master/Test_CNN_Chainer.ipynb)

Start close to the bottom of that page and look for at 114 which is only a few rows up from the bottom.

**Comment by agibsonccc** [comment]
Tests pass and merged. https://github.com/deeplearning4j/deeplearning4j/commit/a07cc139751cbbcc696cd78a462763a80c61dc66
