### ISSUE TITLE
Ability to assign a specific workspace to the network / computation graph outputs

### ISSUE THREAD

**Issue by NicolasVidal** [deeplearning4j/deeplearning4j#5932]
#### Issue Description

When encountering system.gc() issues (nearly 100% CPU Time as we handle lots of objects simultaneously), we turned down periodic garbage collection as the documentation recommends : 
(https://deeplearning4j.org/workspaces#garbage-collector)

Then, we understood we had to use Workspaces in order to manually handle INDArrays allocations/deallocations. But we encountered an issue with INDArrays created by output() or evaluate() calls of our computation graph.

Indeed those calls should be made outside of a Workspace otherwise we got :
```
Exception in thread "main" org.nd4j.linalg.workspace.ND4JWorkspaceException: Expected no workspace active before call to outputOfLayersDetached - Open/active workspaces: [OOMPUTE_OUTPUT_WORKSPACE]
```
Thus, the INDArrays returned were detached from any workspace and their memory would not be claimed until next system.gc() (which we try to avoid at most).

You suggested on gitter that it would be possible to give a computation graph output() or evaluate() calls a Workspace reference in order to be able to manage INDArrays native memory lifetime in an efficient way. That would indeed solve the above issue.

The global aim of this modification is to be able to serve a computation graph model with very high throughput without relying on system.gc() in order to free any allocated memory.

Thanks a lot for you kind answers.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version : 1.0.0-beta
* platform information (OS, etc) : Windows 10
* CUDA version, if used : 9.0 and 9.1
* NVIDIA driver version, if in use : 398.36

**Comment by AlexDBlack** [comment]
Implemented here, will be merged soon: https://github.com/deeplearning4j/deeplearning4j/pull/5962
