### ISSUE TITLE
SameDiff.reverseArrayLookup causes severe memory leak

### ISSUE THREAD

**Issue by emillynge** [deeplearning4j/deeplearning4j#5934]
SameDiff uses a `IndentityHasMap` to resolve which `SDVariable` is bound to a given `INDArray`. This however, creates a permanent reference to the array which is never purged and hence, the arrays cannot be deallocated.

When training a network using the new and fancy `SameDiffLayer` (Hooray! such awesome), this causes a very fast buildup of off heap memory resulting in inevitable OOM exception.

I have tried using a `WeakHashMap` locally and that seems to have fixed the problem.
Since none of the concrete implementations of  `INDArray` overrides `Object.hashCode()`, this should be safe for now. But ideally we would use a [WeakIdentityHashMAp](https://avro.apache.org/docs/1.8.0/api/java/org/apache/avro/util/WeakIdentityHashMap.html).

**Comment by emillynge** [comment]
@AlexDBlack I would think this is an easy fix that some of the more frequent committer could just add to an existing PR. But I can also file a PR myself if preferable. 
But I would need to know whether we just want to use `WeakHashMap` and hope no one has overridden `hashCode` method in some weird subclass. Or if we want to implement/pull in dependency on   `WeakIdentityHashMap`

**Comment by AlexDBlack** [comment]
I was thinking a simpler solution is just to remove the arrays from the IdentityHashMap whenever we update the other maps holding the INDArrays.
Though I can't think of a lot of cases where this functionality is used in practice, so maybe we can remove the IdentityHashMap outright.

**Comment by AlexDBlack** [comment]
I ended up removing it here: https://github.com/deeplearning4j/deeplearning4j/pull/5940
It's not really used anywhere.
I'll close this issue once that PR is merged.

**Comment by emillynge** [comment]
Thank for the quick fix! @AlexDBlack

**Comment by AlexDBlack** [comment]
No problem - thanks for flagging the issue :)
