### ISSUE TITLE
Keras Model start to train automatically when import to Java

### ISSUE THREAD

**Issue by samitha9125** [deeplearning4j/deeplearning4j#5956]
I'm trying to import already trained keras model (ConvNet which classify images) to Java using Deeplearning4j library and I did use following code to import keras model (.h5) file and predict.

    File temp = new File(imagePath);
    MultiLayerNetwork model = KerasModelImport.importKerasSequentialModelAndWeights(modelPath,false);
    NativeImageLoader loader = new NativeImageLoader(74, 448, 3);
    INDArray image = loader.asMatrix(temp);
    DataNormalization scaler = new ImagePreProcessingScaler(0,1);
    scaler.transform(image);
    int[] list = model.predict(image);
But when I run this code, following output appears in Java console.    

    objc[58115]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8b2b4c90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x132548cd8). One of the two will be used. Which one is undefined.
    [ INFO] Unexpected end-of-input: was expecting closing '"' for name
    at [Source: {"config": [{"config": {"name": "zero_padding2d_1", "trainable": true, "batch_input_shape": [null, 74, 448, 3], "padding": [[374, 374], [0, 0]], "data_format": "channels_last", "dtype": "float32"}, "class_name": "ZeroPadding2D"}, {"config": {"activation": "relu", "name": "conv2d_1", "strides": [1, 1], "kernel_size": [3, 3], "data_format": "channels_last", "trainable": true, "kernel_constraint": null, "filters": 32, "use_bias": true, "kernel_regularizer": null, "activity_regularizer": null, "dilation_rate": [1, 1], "padding": "valid", "kernel_initializer": {"config": {"mode": "fan_avg", "distribution": "uniform", "seed": null, "scale": 1.0}, "class_name": "VarianceScaling"}, "bias_constraint": null, "bias_initializer": {"config": {}, "class_name": "Zeros"}, "bias_regularizer": null}, "class_name": "Conv2D"}, {"config": {"name": "max_pooling2d_1", "trainable": true, "pool_size": [2, 2], "strides": [2, 2], "padding": "valid", "data_format": "channels_last"}, "class_name": "MaxPooling2D"}, {"config": {"activation": "relu", "name": "conv2d_2", "strides": [1, 1], "kernel_size": [3, 3], "data_format": "channels_last", "trainable": true, "kernel_constraint": null, "filters": 32, "use_bias": true, "kernel_regularizer": null, "activity_regularizer": null, "dilation_rate": [1, 1], "padding": "valid", "kernel_initializer": {"config": {"mode": "fan_avg", "distribution": "uniform", "seed": null, "scale": 1.0}, "class_name": "VarianceScaling"}, "bias_constraint": null, "bias_initializer": {"config": {}, "class_name": "Zeros"}, "bias_regularizer": null}, "class_name": "Conv2D"}, {"config": {"name": "max_pooling2d_2", "trainable": true, "pool_size": [2, 2], "strides": [2, 2], "padding": "valid", "data_format": "channels_last"}, "class_name": "MaxPooling2D"}, {"config": {"name": "flatten_1", "trainable": true, "data_format": "channels_last"}, "class_name": "Flatten"}, {"config": {"activation": "relu", "name": "dense_1", "units": 128, "use_bias": true, "kernel_constraint": null, "trai; line: 1, column: 4001]
    [ INFO] Loaded [CpuBackend] backend
    [ INFO] Number of threads used for NativeOps: 2
    [ INFO] Number of threads used for BLAS: 2
    [ INFO] Backend used: [CPU]; OS: [Mac OS X]
    [ INFO] Cores: [4]; Memory: [1.8GB];
    [ INFO] Blas vendor: [OPENBLAS]
    [ INFO] Starting MultiLayerNetwork with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
    H: Index 0 [969408] must not be >= shape[718080].
    H: Index 0 [969408] must not be >= shape[718080].
    H: Index 0 [969408] must not be >= shape[718080].

Likewise `  H: Index 0 [969408] must not be >= shape[718080].` appears indefinitely and Java usage of my macbook increases to more than 300%. So I assume it start to train again. How can I just import the model and validate given image only? Without re-train already trained model?

**Comment by AlexDBlack** [comment]
Your conclusion about training is incorrect, that's not what is happening.

That said, there clearly is an issue here with some of the native ops.

However, without knowing your network configuration, it's virtually impossible for us to look into this. Is it possible for you to share it for debugging purposes (privately if necessary)?

An alternative is to try snapshots - they have some fixes related to keras import that did not make it into 1.0.0-beta (though, if you are using a version earlier than 1.0.0-beta, switch to that first).

https://deeplearning4j.org/snapshots

**Comment by maxpumperla** [comment]
@samitha9125 can you please give me your keras model?

**Comment by samitha9125** [comment]
Can I send it privately?

**Comment by maxpumperla** [comment]
send it to max at skymind io
