### ISSUE TITLE
ConvolutionLayer backpropGradient issues

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#597]
Line 108 in CNNLayer is returning shape 2,2,4,4 when is should be 1, 2, 2, 1, 4, 4

epsilon, biasGradient and weightGradients are off and it seems due to precision - rounding issues at this point. Need to consider how to handle this for improved performance if not now then at a later date.

Sigmoid derivative also is slightly off in comparison to some standard equations. Its similar to scipy derivative on expit. Highlighting it at least for future reference if this needs to be revisited for precision.

**Comment by agibsonccc** [comment]
Marked as non blocker (this is mainly due to precision issues that aren't of interest for this release.
