### ISSUE TITLE
Libnd4j: multiply_bp incorrect for broadcast case

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#5978]
The epsNext array (dL/dOut) doesn't seem to be used at all:
https://github.com/deeplearning4j/deeplearning4j/blob/451dd76b50355358dc176f2b704e98c43423c5b8/libnd4j/include/ops/declarable/generic/broadcastable/multiply.cpp#L119-L148

It's also failing gradient checks in ND4J

**Comment by raver119** [comment]
Fix was merged, and should be confirmed now

**Comment by AlexDBlack** [comment]
Test confirmed passing now - thanks.

**Comment by shyrma** [comment]
Corrected and merged into master
