### ISSUE TITLE
BigDecimalMath causes ArithmeticException with zero square root

### ISSUE THREAD

**Issue by gline9** [deeplearning4j/deeplearning4j#6007]
When calling the following code:

~~~~
BigDecimalMath.sqrt(BigDecimal.valueOf(0));
~~~~

An ArithmeticException with description Division undefined is thrown. The description of the square root method states that x is a non-negative argument. That means it should support 0 for square roots.

**Comment by raver119** [comment]
This issue makes me wonder: why we still have BigDecimalMath? It doesn't look like we're actually using it somewhere? I see 0 tests for it as well.

cc @agibsonccc

**Comment by AlexDBlack** [comment]
PR open to remove it here: https://github.com/deeplearning4j/deeplearning4j/pull/6009

**Comment by AlexDBlack** [comment]
@gline9 Thanks for the issue. We have removed BigDecimalMath - it was not properly maintained/tested, and not used anywhere within ND4J/DL4J. As of the next release, you'll need to find another library for big decimal math ops.
