### ISSUE TITLE
deeplearning4j getWordVector() getting different results compared to Gensim?

### ISSUE THREAD

**Issue by peidaqi** [deeplearning4j/deeplearning4j#6024]
I'm testing deeplearning4j word2vec and having some very strange results. The getWordVector() method gives me different results compared to gensim's KeyedVector. 

The word vector file used is Glove's 50D 6B pre-trained dataset, converted into Word2Vec binary format using Gensim.

In Scala:
val wv_model = WordVectorSerializer.readWord2VecModel("../word2vec/glove.6B.50d.w2v.bin")
wv_model.getWordVector("america")

res32: Array[Double] = Array(
  -0.02688949555158615,
  0.0953855961561203,
  -0.022375814616680145,
...

In Python:
wv_model = = KeyedVectors.load_word2vec_format('../word2vec/glove.6B.50d.w2v.bin', binary=True)
wv_model['america']
array([-0.13124  ,  0.46555  , -0.10921  ,  0.18759  ,  0.073319 ,
       -0.40072  , -1.1418   , -0.52592  ,  0.20455  ,  0.22532  ,
...

**Comment by raver119** [comment]
We had few issues like this before, you can search among closed issues here.

TL/DR: either it's encoding issue (non-printable characters), or non-unique words in vocabulary. No other options, sorry.

**Comment by peidaqi** [comment]
I went through the code. This actually has nothing to do with encoding/non-unique words in vocab.

The issue is with the implementation of readWord2VecModel, which calls readBinaryModel when the input is a word2vec bin file.

The readBinaryModel method has a parameter "normalize", which will take a L2 norm to the result vector. And the readWord2VecModel didn't correctly expose this. IMO, L2 norm should by default be disabled anyway to be compatible with most other libs. This will not affect similarity score much anyway and only adds overhead.

This can be confirmed by - in Python:
wv_model['america'] / np.linalg.norm(wv_model['america'], 2)

**Comment by raver119** [comment]
oh, sorry, you're right. third option is normalization applied.

**Comment by peidaqi** [comment]
By the way, cross checked with the current stable (0.9.1) and latest source in master, this problem has been fixed:

In 0.9.1, readWord2VecModel calls loadGoogleModel, which is:
return binary ? readBinaryModel(modelFile, lineBreaks, **true**) : fromPair(loadTxt(modelFile));

In latest source in master, readWord2VecModel directly calls readBinaryModel with normalize set to false. Also readBinaryModel has been set to public instead of private, which makes more sense.

Not sure how the maintainers deal with releases - I cannot find a release note anywhere on the deeplearning4j website. I guess it would be better that this kind of behavior change be highlighted.

**Comment by raver119** [comment]
Current stable is 1.0.0-beta.

**Comment by peidaqi** [comment]
Ok. Just checked the 1.0.0-beta source, the loadGoogleModel was removed but the normalization is not modified:

vec = readBinaryModel(file, true, **true**);

Guess we'll have to wait till the next build to fix this.

**Comment by raver119** [comment]
Huh, i just don't remember when i've fixed this, sorry.
You can use snapshots as well, they are updated daily.

There's also release going out pretty soon.
