### ISSUE TITLE
ND4J/Libnd4j: TruncatedNormalDistribution incorrect; may not return depending on args

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6036]
The second execution here seems to never return:
```
        log.info("Starting");
        INDArray arr = Nd4j.getExecutioner().exec(new TruncatedNormalDistribution(Nd4j.createUninitialized(new long[]{10,10}), 0, 1));
        log.info("Done random 1");
        arr = Nd4j.getExecutioner().exec(new TruncatedNormalDistribution(Nd4j.createUninitialized(new long[]{10,10}), 2, 1));
        log.info("Done random 2");
```

**Comment by AlexDBlack** [comment]
Actually: looks like the implementation is wrong too... here's the distribution produced by mean 1, stdev 1:
It should be clipping at 1 +/- 2 (i.e., -1, 3 - mean +/- 2 stdev) to match keras and TF...
![image](https://user-images.githubusercontent.com/2360237/43519349-6d27726a-95d2-11e8-9aed-8ec790c0d6a2.png)

https://www.tensorflow.org/versions/r1.0/api_docs/cc/class/tensorflow/ops/truncated-normal
https://keras.io/initializers/

**Comment by shugeo** [comment]
We use  RandomLauncher<.>::fillTruncatedNormal(...) instead.
May be create proper op with generic approach?

**Comment by AlexDBlack** [comment]
Fixed some time ago.
