### ISSUE TITLE
Libnd4j: broadcastable pairwise op gradient failing for edge case

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6037]
Passing for most cases, but failing for the following case:
Input 1 shape: [1,6]
Input 2 shape: [3,4,5,1]
Output shape: [3,4,5,6]
Failing ops: sub, div, rsub, rdiv

Test case in Java: (note all prior cases are passing)
https://github.com/deeplearning4j/deeplearning4j/blob/0c7d15e2cc3d2167672f6ea96dbe45dec92c1f0e/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/autodiff/opvalidation/MiscOpValidation.java#L258

https://gist.github.com/AlexDBlack/774d6a86757d0a246a28789bdd7da471

**Comment by shugeo** [comment]
there are subtract, reversesubtract, divide and reversedivide broadcastable ops.

**Comment by AlexDBlack** [comment]
Looking at the commit history - is this fixed by https://github.com/deeplearning4j/deeplearning4j/pull/6134 ?
Or is there more to do here?

**Comment by raver119** [comment]
Hypothetically should be fixed, at least c++ tests pass now.
Please confirm fix on your end.
