### ISSUE TITLE
libnd4j - new SoftMax Op overflows and results in NaN

### ISSUE THREAD

**Issue by emillynge** [deeplearning4j/deeplearning4j#6039]
#### Issue Description

Please describe your issue, along with:
- expected behavior
	- Use softmax in SameDiffLayer
    - Get values between 0 - 1
- encountered behavior
	- Use softmax in SameDiffLayer
    - Get nan values when input is very large

The problem is caused by the new helper function in `activations.cpp`

```
template <typename T>
void softmax(const NDArray<T>& input, NDArray<T>& output, const int dimension) {

    const int rank = input.rankOf();

    if(input.isVector()) {
        
        if(rank == 1 || input.sizeAt(dimension) != 1)
            softMaxForVector<T>(input, output);
        else
            output = 1.;
    }
    else {
        
        NDArray<T> exponents = const_cast<NDArray<T>&>(input).template transform<simdOps::Exp<T>>();
        NDArray<T> sumAlongDim = exponents.template reduceAlongDims<simdOps::Sum<T>>({dimension}, true);        
        output.assign(exponents / sumAlongDim);
    }
}
```
As seen, we are taking exp of the raw input which is likely to cause NaN values.

In SoftMaxOld this issue is handled by first subtracting the maximum value in each row.

This translation does not affect the result of the softmax function, but it prevents overflow in the exp computation.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 1.0.0-SNAPSHOT
* platform information (OS, etc): ubuntu 18
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

#### Contributing
If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

I could do a PR, but I suspect it would be faster for one of the core contributors to include this small change in another PR.

**Comment by emillynge** [comment]
Here is a code snippet that i would think fixes the issue:
```
        NDArray<T> maxAlongDim = const_cast<NDArray<T>&>(input).template reduceAlongDims<simdOps::Max<T>>({dimension}, true); 
        NDArray<T> translatedInput = exponents.template template applyBroadcast<simdOps::Subtract<T>>({const_cast<NDArray<T>&>(input)}, maxAlongDim);
        NDArray<T> exponents = translatedInput.template transform<simdOps::Exp<T>>();
        NDArray<T> sumAlongDim = exponents.template reduceAlongDims<simdOps::Sum<T>>({dimension}, true);        
        output.assign(exponents / sumAlongDim);
``

**Comment by shyrma** [comment]
Hi, emillynge

Thanks for your participating !
I'll take into account your code and change this operation appropriately

**Comment by emillynge** [comment]
@shyrma you may also want to revisit any other method that implements a variant of this op like LogSoftMax.
I should not think any derivate/bp methods needs to be changed as softmax should be invariant to translation.

**Comment by emillynge** [comment]
FYI, I can see that currently `LossBinaryXENT` has issues specifically because `LogSoftMax` produces NaN values. So right now, I have to prepend my `OutputLayer` with an `ActivationLayer` to stop `LossBinaryXENT` calling `LogSoftMax`

**Comment by shyrma** [comment]
Seems like we had such (epx(raw_input)) in softmaxCrossEntropyWithLogits as well. Fixed now

**Comment by raver119** [comment]
Issue should be fixed now i think. 

Thanks for highlighting this problem.
