### ISSUE TITLE
ExpReplay Dead Loop

### ISSUE THREAD

**Issue by fulltopic** [deeplearning4j/deeplearning4j#6050]
`
public ArrayList<Transition<A>> getBatch(int size) {

        Set<Integer> intSet = new HashSet<>();
        int storageSize = storage.size();
        while (intSet.size() < size) {
            int rd = random.nextInt(storageSize);
            intSet.add(rd);
        }
// ...
}
`
If (storageSize < size), then inSet.size() would never >= size

Should be
`
public ArrayList<Transition<A>> getBatch(int size) {

        Set<Integer> intSet = new HashSet<>();
        int storageSize = storage.size();
       int expSetSize = Math.min(storageSize, size);
        while (intSet.size() < expSetSize) {
            int rd = random.nextInt(storageSize);
            intSet.add(rd);
        }
`

Can I raise a patch in this way?

**Comment by agibsonccc** [comment]
Please send us a pull request. https://help.github.com/articles/creating-a-pull-request/

**Comment by fulltopic** [comment]
Pull request #6059
