### ISSUE TITLE
0.9.1 RecordReaderDataSetIterator regression true not reading whole file

### ISSUE THREAD

**Issue by bartailey** [deeplearning4j/deeplearning4j#6052]
I am running a unit test on version 0.9.1 where I am loading a file where the file I am loading is 100 examples of a 1024 bit string with the regression value is 1025. 

When run the RecordReaderDataSetIterator only reads 56 of the values. I have created a number of variations of the input file and the number is always incorrect. 

```
			DataSetIterator iterator = new RecordReaderDataSetIterator(recordReader, batchSize , 1024, 1024, true);
			
			while (iterator.hasNext()) {
				DataSet dataSet = iterator.next();
				
				//dataSet.normalize();  // TODO uncomment this line
				dataSetList.add(dataSet);
			}
```

The output is:

`INFO  com.bactevo.chemistry.hitsneuralnetwork.NeuralNetworkRegression readFingerprintFile:113 - numberExamples: 56`

and the file contains 100 examples
```
wc testFingerPrintRegression.txt
   100    100 410500 testFingerPrintRegression.txt
```
Is there a fix for this? 

I tried using the 1.0.0-beta and it passed the test but created several other issues.

**Comment by agibsonccc** [comment]
We don't support older versions. Please upgrade and tell us what your "other issues" are instead.
