### ISSUE TITLE
ND4J: add equivalent of numpy extract

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6053]
This would be useful as an op, and I don't believe we have something equivalent already
https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.extract.html

**Comment by raver119** [comment]
Actually we have few ops. Their names are Select, Where and Choose

**Comment by AlexDBlack** [comment]
Ah, cool. Choose looks like it's functionally the same thing. 👍
