### ISSUE TITLE
VersionCheck error reading property files

### ISSUE THREAD

**Issue by DrChainsaw** [deeplearning4j/deeplearning4j#6056]
Any program I run on my windows 10 machine has org.nd4j.versioncheck.VersionCheck printing a bunch or "error reading property files". This has been going on since 1.0.0 beta (now using snapshots). From what I can tell everything still works as normal so there does not seem to be any missing files.

Example POM file:
https://github.com/DrChainsaw/AmpControl/blob/dl4j-snapshot/pom.xml

Example program and output:
public static void main(String[] args) {
        System.out.println(Nd4j.create(1));
}

14:58:11.409 [main] INFO  org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
14:58:11.528 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/datavec/datavec-api/1.0.0-SNAPSHOT/datavec-api-1.0.0-20180802.081646-870.jar!/ai/skymind/org.datavec-datavec-api-git.properties
14:58:11.528 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/datavec/datavec-data-audio/1.0.0-SNAPSHOT/datavec-data-audio-1.0.0-20180802.081408-864.jar!/ai/skymind/org.datavec-datavec-data-audio-git.properties
14:58:11.528 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/datavec/datavec-data-image/1.0.0-SNAPSHOT/datavec-data-image-1.0.0-20180802.081649-872.jar!/ai/skymind/org.datavec-datavec-data-image-git.properties
14:58:11.528 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/deeplearning4j/deeplearning4j-common/1.0.0-SNAPSHOT/deeplearning4j-common-1.0.0-20180802.081438-622.jar!/ai/skymind/org.deeplearning4j-deeplearning4j-common-git.properties
14:58:11.529 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/deeplearning4j/deeplearning4j-core/1.0.0-SNAPSHOT/deeplearning4j-core-1.0.0-20180802.081700-1188.jar!/ai/skymind/org.deeplearning4j-deeplearning4j-core-git.properties
14:58:11.529 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/deeplearning4j/deeplearning4j-cuda-9.2/1.0.0-SNAPSHOT/deeplearning4j-cuda-9.2-1.0.0-20180801.104902-39.jar!/ai/skymind/org.deeplearning4j-deeplearning4j-cuda-9.2-git.properties
14:58:11.529 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/deeplearning4j/deeplearning4j-datasets/1.0.0-SNAPSHOT/deeplearning4j-datasets-1.0.0-20180802.081439-1167.jar!/ai/skymind/org.deeplearning4j-deeplearning4j-datasets-git.properties
14:58:11.529 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/deeplearning4j/deeplearning4j-datavec-iterators/1.0.0-SNAPSHOT/deeplearning4j-datavec-iterators-1.0.0-20180802.081603-1158.jar!/ai/skymind/org.deeplearning4j-deeplearning4j-datavec-iterators-git.properties
14:58:11.529 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/deeplearning4j/deeplearning4j-modelimport/1.0.0-SNAPSHOT/deeplearning4j-modelimport-1.0.0-20180802.081456-1185.jar!/ai/skymind/org.deeplearning4j-deeplearning4j-modelimport-git.properties
14:58:11.529 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/deeplearning4j/deeplearning4j-nlp/1.0.0-SNAPSHOT/deeplearning4j-nlp-1.0.0-20180802.081415-1182.jar!/ai/skymind/org.deeplearning4j-deeplearning4j-nlp-git.properties
14:58:11.530 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/deeplearning4j/deeplearning4j-nn/1.0.0-SNAPSHOT/deeplearning4j-nn-1.0.0-20180802.081543-1185.jar!/ai/skymind/org.deeplearning4j-deeplearning4j-nn-git.properties
14:58:11.530 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/deeplearning4j/deeplearning4j-play_2.11/1.0.0-SNAPSHOT/deeplearning4j-play_2.11-1.0.0-20180802.081442-650.jar!/ai/skymind/org.deeplearning4j-deeplearning4j-play_2.11-git.properties
14:58:11.530 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/deeplearning4j/deeplearning4j-tsne/1.0.0-SNAPSHOT/deeplearning4j-tsne-1.0.0-20180802.081411-1184.jar!/ai/skymind/org.deeplearning4j-deeplearning4j-tsne-git.properties
14:58:11.531 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/deeplearning4j/deeplearning4j-ui-components/1.0.0-SNAPSHOT/deeplearning4j-ui-components-1.0.0-20180802.081455-1098.jar!/ai/skymind/org.deeplearning4j-deeplearning4j-ui-components-git.properties
14:58:11.531 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/deeplearning4j/deeplearning4j-ui-model/1.0.0-SNAPSHOT/deeplearning4j-ui-model-1.0.0-20180802.081553-1187.jar!/ai/skymind/org.deeplearning4j-deeplearning4j-ui-model-git.properties
14:58:11.531 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/deeplearning4j/deeplearning4j-ui-resources/1.0.0-SNAPSHOT/deeplearning4j-ui-resources-1.0.0-20180802.081433-1060.jar!/ai/skymind/org.deeplearning4j-deeplearning4j-ui-resources-git.properties
14:58:11.531 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/deeplearning4j/deeplearning4j-ui_2.11/1.0.0-SNAPSHOT/deeplearning4j-ui_2.11-1.0.0-20180802.081421-660.jar!/ai/skymind/org.deeplearning4j-deeplearning4j-ui_2.11-git.properties
14:58:11.532 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/deeplearning4j/deeplearning4j-util/1.0.0-SNAPSHOT/deeplearning4j-util-1.0.0-20180802.081524-1143.jar!/ai/skymind/org.deeplearning4j-deeplearning4j-util-git.properties
14:58:11.532 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/deeplearning4j/deeplearning4j-utility-iterators/1.0.0-SNAPSHOT/deeplearning4j-utility-iterators-1.0.0-20180802.081452-1159.jar!/ai/skymind/org.deeplearning4j-deeplearning4j-utility-iterators-git.properties
14:58:11.532 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/deeplearning4j/nearestneighbor-core/1.0.0-SNAPSHOT/nearestneighbor-core-1.0.0-20180802.081605-1178.jar!/ai/skymind/org.deeplearning4j-nearestneighbor-core-git.properties
14:58:11.532 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/nd4j/jackson/1.0.0-SNAPSHOT/jackson-1.0.0-20180802.084823-6234.jar!/ai/skymind/org.nd4j-jackson-git.properties
14:58:11.532 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/nd4j/nd4j-api/1.0.0-SNAPSHOT/nd4j-api-1.0.0-20180802.084749-6081.jar!/ai/skymind/org.nd4j-nd4j-api-git.properties
14:58:11.532 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/nd4j/nd4j-base64/1.0.0-SNAPSHOT/nd4j-base64-1.0.0-20180802.084804-6261.jar!/ai/skymind/org.nd4j-nd4j-base64-git.properties
14:58:11.533 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/nd4j/nd4j-buffer/1.0.0-SNAPSHOT/nd4j-buffer-1.0.0-20180802.084825-6198.jar!/ai/skymind/org.nd4j-nd4j-buffer-git.properties
14:58:11.533 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/nd4j/nd4j-common/1.0.0-SNAPSHOT/nd4j-common-1.0.0-20180802.084737-6285.jar!/ai/skymind/org.nd4j-nd4j-common-git.properties
14:58:11.533 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/nd4j/nd4j-context/1.0.0-SNAPSHOT/nd4j-context-1.0.0-20180802.084740-6185.jar!/ai/skymind/org.nd4j-nd4j-context-git.properties
14:58:11.533 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/nd4j/nd4j-cuda-9.2/1.0.0-SNAPSHOT/nd4j-cuda-9.2-1.0.0-20180802.084741-139.jar!/ai/skymind/org.nd4j-nd4j-cuda-9.2-git.properties
14:58:11.533 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/nd4j/nd4j-jackson/1.0.0-SNAPSHOT/nd4j-jackson-1.0.0-20180802.084822-6119.jar!/ai/skymind/org.nd4j-nd4j-jackson-git.properties
14:58:11.534 [main] DEBUG org.nd4j.versioncheck.VersionCheck - Error reading property files for jar:file:///E:/Software%2520projects/java/maven_repo/org/nd4j/nd4j-native-api/1.0.0-SNAPSHOT/nd4j-native-api-1.0.0-20180802.084742-6094.jar!/ai/skymind/org.nd4j-nd4j-native-api-git.properties
14:58:13.191 [main] INFO  org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 32
14:58:13.706 [main] INFO  org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 0
14:58:13.711 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
14:58:13.711 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Cores: [12]; Memory: [7,1GB];
14:58:13.711 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
14:58:13.711 [main] INFO  o.n.l.j.o.e.CudaExecutioner - Device Name: [GeForce GTX 980 Ti]; CC: [5.2]; Total/free memory: [6442450944]
14:58:13.760 [main] DEBUG o.n.j.handler.impl.CudaZeroHandler - Creating bucketID: 4
14:58:13.771 [main] DEBUG o.n.j.handler.impl.CudaZeroHandler - Creating bucketID: 5
0

Process finished with exit code 0

**Comment by AlexDBlack** [comment]
> jar:file:///E:/Software%2520projects/

That looks very suspicious... given we haven't seen this before, I'm guessing there's some sort of issue with the space in the path.

Can you run the following in cmd, and post the result? (It'll be quicker to run outside of your project directory)
```
mvn help:evaluate -Dexpression=settings.localRepository
```

**Comment by DrChainsaw** [comment]
Sure thing! 

Here you go:

>mvn help:evaluate -Dexpression=settings.localRepository
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-help-plugin:3.0.1:evaluate (default-cli) @ standalone-pom ---
[INFO] No artifact parameter specified, using 'org.apache.maven:standalone-pom:pom:1' as project.
[INFO]
E:\Software projects\java\maven_repo
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.223 s
[INFO] Finished at: 2018-08-03T00:12:42+02:00
[INFO] Final Memory: 12M/491M
[INFO] ------------------------------------------------------------------------

**Comment by AlexDBlack** [comment]
Thanks. OK, so it's a standard space in the path, nothing special there... I'll see if I can reproduce this.
