### ISSUE TITLE
ND4J: add method to create random int in a range [a,b]

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/deeplearning4j#6065]
i.e. `Nd4j.getRandom().nextInt(a,b);`, currently we only have `Nd4j.getRandom().nextInt(b); and a is always 0. you can always add a, but for convenience this would be nice.

**Comment by AlexDBlack** [comment]
related: https://github.com/deeplearning4j/deeplearning4j/issues/5776

**Comment by raver119** [comment]
Implemented
