### ISSUE TITLE
Consider splitting up repo 

### ISSUE THREAD

**Issue by magick93** [deeplearning4j/deeplearning4j#6066]
Hello

When cloning this repo, I needed to pull down 560mb.

Im sure most users don't need everything in this repo, as it does cover a lot of different projects in one git repo.

**Comment by raver119** [comment]
No, split isn't an option really. But eventually we'll do yet another history cleanup.

**Comment by magick93** [comment]
Out of curiosity, why isnt slipping up this repo an option?

**Comment by agibsonccc** [comment]
@magick93 we spent the last 4 years like that. We know what it's like to 
"split the repo" - the mono repo was implemented to increase code quality and better PR management. We already have test dependencies split out. You can do a shallow clone just fine and have the download be faster. 1 github issue will not undo 4 years of frustrations with workflows trying to make several different projects work together :).

**Comment by magick93** [comment]
Using `git clone --depth 1 https://github.com/deeplearning4j/deeplearning4j.git` reduced the download to about 110mb. 

I am assuming that most first time users to this repo are interested in the examples. Im sure people would appreciate if even these were more easily accessible and lightweight.

Thanks for clarifying your reasoning.

**Comment by raver119** [comment]
Examples are in another repository. And you just don't need main repo unless you're going to mess with source code :)

**Comment by raver119** [comment]
https://github.com/deeplearning4j/dl4j-examples

**Comment by magick93** [comment]
> 'm not sure where in the docs you got the idea it was in the main dl4j repo (usually folks who do this have skipped reading our docs :) ).

Actually, its in your docs that I got that idea. See https://github.com/deeplearning4j/deeplearning4j/blob/master/README.md - last 2 lines.

**Comment by raver119** [comment]
Ouch. That's not what we mean by `examples` usually, and we should fix that.
