### ISSUE TITLE
libnd4j: reduce_dot_bp is wrong

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6069]
Dot op: ```out = sum_i x_i * y_i```
Therefore gradient has 3 inputs and 2 outputs.

The reduce_dop_bp implementation (and shape function) only have 1 output

https://github.com/deeplearning4j/deeplearning4j/blob/451dd76b50355358dc176f2b704e98c43423c5b8/libnd4j/include/ops/declarable/generic/parity_ops/reduce_dot.cpp

**Comment by shugeo** [comment]
Dot is Reduce3 reducable op.

**Comment by raver119** [comment]
Yes, it is reduce op. But since it takes 2 inputs for multiplication, it should provide 2 gradients. Not 1.

**Comment by raver119** [comment]
Should be fixed now i guess.
