### ISSUE TITLE
Improve default values for OutputLayer properties

### ISSUE THREAD

**Issue by EronWright** [deeplearning4j/deeplearning4j#607]
Most often the output layer is initialized with weightInit = ZERO, and activation = "softmax".   It is now easy to set those as the default values in the OutputLayer.Builder constructor.  This change would make the layer API more consistent with the old ClassifierOverride(1) approach (which used those values).

If we do nothing, the output layer inherits the default values from Layer, which are weightInit = VI, activation = "sigmoid".

**Comment by nyghtowl** [comment]
Address in base output layer
