### ISSUE TITLE
ND4J: arange and linspace should have stride/step arguments

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/deeplearning4j#6070]
Apparently in C++ linspace has step size, but it's inferred, and not exposed to Java .

Also, javadocs lie in this regard, a bit misleading:
https://github.com/deeplearning4j/deeplearning4j/blob/c29b84d58b85547a6cec5eadbad99f60938611bd/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java#L1824

having this for `arange` as well would be cool.

**Comment by alexanderst** [comment]
Fixed and merged.
