### ISSUE TITLE
libnd4j: need op equivalent to INDArray.size(int)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6079]
We can close this (https://github.com/deeplearning4j/deeplearning4j/issues/6078), and I'll do it in Java if I have this simple op that mimics INDArray.size(int).

Input: 1 NDArray arg, 1 integer 'dimension' arg.
Output: rank 0 NDArray, with value equivalent to INDArray.size(dimension)

Edit: needs to support negative values for dimension arg also.

**Comment by raver119** [comment]
Implemented and merged
