### ISSUE TITLE
javacpp.platform=linux-x86_64 should exclude all window's artifacts

### ISSUE THREAD

**Issue by sergmain** [deeplearning4j/deeplearning4j#6083]
I'm using Spring Boot to build uber-jar. To reduce size of this jar I use -Djavacpp.platform=linux-x86_64 JVM option and almost all jar for other platforms gone except few:
openblas-0.2.20-1.4.1-windows-x86_64.jar
nd4j-native-1.0.0-beta-windows-x86_64.jar

**Comment by agibsonccc** [comment]
@sergmain make sure to to use the -platform dependencies. If you want to exclude the jars for platform, then you'll have to set those up manually

**Comment by sergmain** [comment]
So, functionality of  -Djavacpp.platform=linux-x86_64 is broken and you won't fix it, right?

**Comment by agibsonccc** [comment]
No. Again, the whole point of the -platform dependencies is to include everything regardless of platfomr.

**Comment by agibsonccc** [comment]
@sergmain check my updated comment, I can't even reproduce your problem.

**Comment by saudet** [comment]
@sergmain It might not work well if you're using an old version of Maven. Make sure to use one of 3.3.x or 3.5.x.

**Comment by agibsonccc** [comment]
So I'd run this pom : https://gist.github.com/agibsonccc/b4e22b861070adcede859f523c172936

using:
mvn clean install -Pjavacpp-platform-custom -Pexclude-local -Djavacpp.platform=linux-x86_64

When you include exclude-local it will only include the jars you need for the specified OS.

**Comment by agibsonccc** [comment]
@sergmain this release will be going out this week. Thanks for reporting! If you have issues with the work around pom I posted for now, please let me know.

**Comment by saudet** [comment]
The fix has been merged. Thanks for reporting!
