### ISSUE TITLE
After removing “org/nd4j/linalg/api/complex/IComplexNDArray”, it cannot run in a gpu environment . throw "class not found" exception

### ISSUE THREAD

**Issue by longzhendong** [deeplearning4j/deeplearning4j#6085]
After removing “org/nd4j/linalg/api/complex/IComplexNDArray”, it cannot run in a gpu environment .
throw "class not found" exception

**Comment by agibsonccc** [comment]
Those 2 things are not correlated in any way. You have out of date snapshots. Force an update of every jar in the snapshots repo.

**Comment by sshepel** [comment]
@longzhendong it looks like you are using `cuda-9.1` snapshots, we dropped `cuda-9.1` several weeks ago, please update your env and snapshots artifacts version to `cuda-9.2`.

**Comment by agibsonccc** [comment]
@longzhendong yes check your cuda version as well. In general, the jars should be updated with mvn -U clean package if it isn't updating the jars.

**Comment by longzhendong** [comment]
@sshepel Will the 1.0 release no longer support cuda 9.1？

**Comment by saudet** [comment]
@longzhendong Yes, NVIDIA itself doesn't really support 9.1 anymore either.

**Comment by longzhendong** [comment]
@sshepel When will version 1.0.0 be released？

**Comment by AlexDBlack** [comment]
@longzhendong We don't have a date for 1.0.0. However, the most recent release - 1.0.0-beta2 - is out on maven central as of today.
