### ISSUE TITLE
java.lang.ClassNotFoundException : org.deeplearning4j.nn.layers.convolution.CudnnConvolutionHelper

### ISSUE THREAD

**Issue by rahul-raj** [deeplearning4j/deeplearning4j#6086]
I get this error everytime when I run the code against GPU. Found this when my last reported issue was resolved. Thought of opening another one for this and here it is.
![image](https://user-images.githubusercontent.com/517415/43686868-25fef74e-98ea-11e8-916b-ec3a3e25655d.png)

This is my source:
https://github.com/rahul-raj/Deeplearning4J/blob/master/src/main/java/examples/AnimalClassifier.java

And here is the pom.xml:
https://gist.github.com/rahul-raj/ba8e5bf68b792aa836233716a8583641

I just wanted to ensure whether this error can be ignored. If not, I could improve my GPU execution time once after resolving this. Thanks!

**Comment by agibsonccc** [comment]
It explains the nature of the stack trace right in the warning logs. Just include deeplearning4j-cuda with the right cuda version and it will work fine.

**Comment by rahul-raj** [comment]
Well, after adding the dependency, I get this error:
![image](https://user-images.githubusercontent.com/517415/43687198-dec6cd02-98ee-11e8-807a-52e6c499dfd1.png)

pom.xml:
https://gist.github.com/rahul-raj/ba8e5bf68b792aa836233716a8583641

**Comment by agibsonccc** [comment]
Still not relevant. It's just plain not an error. Cudnn needs to be installed.

**Comment by rahul-raj** [comment]
Okay, So now all are installed and errors are gone :)
![image](https://user-images.githubusercontent.com/517415/43687482-85ab3942-98f3-11e8-9def-02dde1d2c1fd.png)
But I do observe that there's no pretty much improvement in the execution time :(

**Comment by saudet** [comment]
cuDNN comes bundled with the "redist" artifacts so add them to your build as well:
https://github.com/bytedeco/javacpp-presets/tree/master/cuda

**Comment by rahul-raj** [comment]
@saudet 

Added below dependency as per my server architecture. Using cuda 9.2 and cuDNN 7.1
```
<dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>cuda-platform</artifactId>
            <version>9.2-7.1-1.4.2</version>
        </dependency>

        <!-- Additional dependencies to use bundled CUDA and cuDNN -->
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>cuda</artifactId>
            <version>9.2-7.1-1.4.2</version>
            <classifier>linux-x86_64-redist</classifier>
        </dependency>
```
I'm running snapshot version, so let me know if I'm okay adding just the above changes to my pom.xml.
Thanks.

**Comment by saudet** [comment]
Yes, that looks alright, so cuDNN will get used with that.

**Comment by rahul-raj** [comment]
@saudet 
I'm running the snapshot version, so do I have to change the version  from `9.2-7.1-1.4.2` to `9.2-7.1-1.4.2-SNAPSHOT` ?

**Comment by saudet** [comment]
No, it's fine without snapshots.
