### ISSUE TITLE
Add support for popular pre-tokenized input formats for NLP

### ISSUE THREAD

**Issue by wmeddie** [deeplearning4j/deeplearning4j#6088]
A lot of times when working with NLP data, you'll get inputs in pre-tokenized formats because the tokenization happens in another stage of the pipeline.  These formats usually similar to but are not proper CSV files.

One popular format is having one document per line with the token index separated by commas or spaces:

examples:

```
1 2 3 4
1 3 4 5 6
```
source: Data link from: https://github.com/jiweil/Hierarchical-Neural-Autoencoder (test.txt)

or:
```
1,2,3,4,5,6,7
1,2,3,4,5
1,2,3,4,5,6
1,2,3
```
source: https://github.com/MokkeMeguru/TestDataSetIterator/blob/master/resources/test_train.csv

Another similar style is one sentence/paragraph per line and a blank line to separate different documents like this:

```
63 10 239 32 16 8 381 7 529 437 3
10 8 381 253 16 3
10 29 7 1908 415 2 1144 15 320 26 368 37 124 9 2 101 775 3
41 2258 1955 38 1156 2609 5 7038 39 10 137 28 136 21 14

11 51 18 2 1 15 6 6597 235 62 75 1362 7 46 241 8609 669 498 3445 3
2 49 12 2 14 8 189 4
2 40 8 1001 41 309 473 18 2 95 87 39 3
8609 669 4
22 26 8 6 1014 2028 3
```

source: https://github.com/jiweil/Hierarchical-Neural-Autoencoder (train_source_permute_segment.txt)

While both of these examples had labels stored in separate files, it is quite normal to have the label be the first or last token in a sequence

**Comment by AlexDBlack** [comment]
For the first case, we have this (a recent addition):
https://github.com/deeplearning4j/deeplearning4j/blob/master/datavec/datavec-api/src/main/java/org/datavec/api/records/reader/impl/csv/CSVLineSequenceRecordReader.java

For the second case: that might be harder to support. I think the only thing we can support for now is to concatenate them (i.e., one big long single-column sequence), and split sequences on the empty line...

**Comment by AlexDBlack** [comment]
Actually: let's add 3 modes for the second case: {CONCAT, EQUAL_LENGTH, PAD}
CONCAT mode would output a univariate sequence
EQUAL_LENGTH mode would require each sequence to have same number of columns (lines) and same number of tokens in each.
PAD mode would require same number of columns (lines) but pad with a user-specified Writable.

That should cover most cases that we can currently support.
