### ISSUE TITLE
NativeImageLoader asMatrix() returning 0

### ISSUE THREAD

**Issue by WendelHime** [deeplearning4j/deeplearning4j#6096]
I'm trying to load an image using NativeImageLoader on Android using the function asMatrix which receives a File, opencv_core.Mat, InputStream, etc. I've tested asMatrix with a grayscale image, RGB and BGR but the values are always 0, the same code on linux and it works perfectly!

I'm using deeplearning4j on version 1.0.0-beta

Here is the code:

```java
               NativeImageLoader loader = new NativeImageLoader(height, width, channels);
               INDArray image = loader.asMatrix(image_mat);
               opencv_core.Mat roi = loader.asMat(image);
               int[] shape = image.shape();
               for (int some : shape) {
                   Log.i("shape", some + "");
               }
               for (int k = 0; k < shape[1]; k++) {
                   for (int i = 0; i < shape[2]; i++) {
                       for (int j = 0; j < shape[3]; j++) {
                           Log.i("before_norm_" + k + "_" + i + "_" + j, image.getDouble(1, k, i, j) + "");
                       }
                   }
               }
```

Observation: The image exists, I've checked!
Observation 2: I've used another loaders, such as  ImageLoader, AndroidNativeImageLoader and still doesn't work

**Comment by saudet** [comment]
That's been fixed, use 1.0.0-SNAPSHOT: https://deeplearning4j.org/android

**Comment by WendelHime** [comment]
1.0.0-SNAPSHOT is available for android development? I've followed this tutorial of [Using deep learning and neural network in applications android](https://deeplearning4j.org/android) and [Using snapshots...](https://deeplearning4j.org/snapshots) and it have some failures on build time

```
Failed to resolve: org.deeplearning4j:deeplearning4j-modelimport:1.0.0-SNAPSHOT
Open File
Show in Project Structure dialog


Failed to resolve: org.deeplearning4j:deeplearning4j-nn:1.0.0-SNAPSHOT
Open File
Show in Project Structure dialog


Failed to resolve: org.nd4j:nd4j-api:1.0.0-SNAPSHOT
Open File
Show in Project Structure dialog


Failed to resolve: org.nd4j:nd4j-native:1.0.0-SNAPSHOT
Open File
Show in Project Structure dialog

```

**Comment by saudet** [comment]
Try to run `mvn -U compile` before building your project.

**Comment by WendelHime** [comment]
I've execute the command above and build again build.gradle file, it works, but now the project doesn't see opencv packages

**Comment by saudet** [comment]
It's probably looking for the opencv artifact with version 3.4.2-1.4.2.
