### ISSUE TITLE
Reopen of #601 - Word2Vec.wordsNearest returning single word repeated

### ISSUE THREAD

**Issue by dkincaid** [deeplearning4j/deeplearning4j#610]
Creating a new issue since I can't seem to reopen #601. Still seeing the same behavior after `git pull` and `mvn install`. Interestingly, the results are a bit different though. It's returning different words for the same model than it did previously:

```clojure
(.wordsNearest model "snap" 5)
["sid*" "sid*" "sid*" "sid*" "sid*"]

(.wordsNearest model "rabies" 5)
["snyder," "snyder," "snyder," "snyder," "snyder,"]
```

**Comment by agibsonccc** [comment]
So we're not seeing that on our datasets. I'll need to know a bit more about your problem..

**Comment by nyghtowl** [comment]
Word2Vec has gone through major changes since this issue. Closing and if this appears again please reopen
