### ISSUE TITLE
enabling import of trained darknet weights to dl4j

### ISSUE THREAD

**Issue by androuino** [deeplearning4j/deeplearning4j#6105]
I would like to work on importing the trained darknet weights to dl4j to be used with java. Perhaps someone could help me in doing this. I have heard using JNI and C Dynamic Link Library to implement this but I'm not sure yet if that is the most acceptable solution to try. Thanks in advance. Cheers!

**Comment by AlexDBlack** [comment]
We have a pretrained darknet19 model available here (with details on how it was imported): https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-zoo/src/main/java/org/deeplearning4j/zoo/model/Darknet19.java#L42-L53

Is that what you are looking for? Or is there some other variant you want to import?

**Comment by androuino** [comment]
Oh, maybe I will try to look for this first. I thought it wasn't implemented yet. Thanks...

**Comment by AlexDBlack** [comment]
Ok, I'll close this issue for now. If you can't use that version (or the same import approach can't be used), we can re-open.
