### ISSUE TITLE
K Fold Iterator tries to index past end of INDArray.

### ISSUE THREAD

**Issue by nlawrence2** [deeplearning4j/deeplearning4j#6117]
Using a kFoldIterator on a dataset of length 8964 fails with k=10. It seems to be only for values of k that do not divide evenly into 8964. 
![image](https://user-images.githubusercontent.com/42251850/43922091-4ea5d8ce-9be3-11e8-8658-974e21d8929e.png)

**Comment by AlexDBlack** [comment]
Thanks for reporting, but this was fixed in 1.0.0-beta2 which is already avaliable on maven central (as of about 24 hours ago)
