### ISSUE TITLE
DeConv3D impl

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#6122]
We need deconvolution3d operation to be implemented

**Comment by raver119** [comment]
Where we are with this?

**Comment by AlexDBlack** [comment]
Looks like it's already implemneted in libnd4j: https://github.com/deeplearning4j/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/convo/deconv3d.cpp

Though not mapped or tested at the java level, as far as I can tell...

**Comment by maxpumperla** [comment]
shall we close this then? this is for the libnd4j part. layer impl + keras mapping are on my plate

**Comment by AlexDBlack** [comment]
Well, I was going to add classes + tests on the SameDiff, forgot about the Keras part. Might as well keep this issue open until those are done too IMO, rather than closing this and opening another issue that's almost identical :)

**Comment by maxpumperla** [comment]
:) just a matter of scope. I thought those tags we're adding here had some meaning.

@AlexDBlack so you're saying you'll be implementing a proper SameDiff layer for deconv3d?

**Comment by AlexDBlack** [comment]
> I thought those tags we're adding here had some meaning.

Nothing in issues are immutable :)

> So you're saying you'll be implementing a proper SameDiff layer for deconv3d?

Well the java class for the op and some methods on the SameDiff class, yes. Though it's not an immediate priority for me.

**Comment by AlexDBlack** [comment]
SameDiff/op classes for deconv3d op and also gradient checks were added here: https://github.com/deeplearning4j/deeplearning4j/pull/7145

**Comment by maxpumperla** [comment]
@AlexDBlack huh, that was fast... I really want to know what an immediate priority would look like then :D same day delivery? awesome!

Keras ticket is here btw https://github.com/deeplearning4j/deeplearning4j/issues/6124

**Comment by AlexDBlack** [comment]
Yeah, I had a SameDiff PR open and some time while I was waiting for things to run/compile, figured I'd do it quickly. :)

Given there's already a Keras issue open (didn't realize there was one), I'll close this in favor of that then...
