### ISSUE TITLE
DataBuffer.length() does not reflect how much contiguous memory is allocated to parent array

### ISSUE THREAD

**Issue by emillynge** [deeplearning4j/deeplearning4j#6133]
In the method `public static boolean isContiguousInBuffer(INDArray in)` created by @AlexDBlack back in 2015, the first check to see if an array is contiguous is to compare `array.length()`with `data.length()` : 
```
/** Are the elements in the buffer contiguous for this NDArray? */
public static boolean isContiguousInBuffer(INDArray in) {
    int length = in.length();
    int dLength = in.data().length();
    if( length == dLength ) return true;    //full buffer, can't not be contiguous
...
```

This leads me to believe that the __original__ idea behind `DataBuffer.length()` is to determine how much memory a matrix is depending on in native memory.

But at the moment, the array factories are set up to __always__ set `array.length() == data.length()`. This cause multiple problems:

 - It becomes more cumbersome to figure out whether an array is contiguous.
 - Serializing an array by serializing `DataBuffer` risk copying the wrong part of memory
 - It is difficult to figure out whether an array is attempting to access an element beyond it's underlying buffer since the indexer routinely reads elements at indices way above `DataBuffer.length`

I had this discussion related to another issue, but I would like to resolve whether or not this is intended behaviour or not, so I am now filing this separate issue. 

Since the number of elements in an array is already saved as a field in `NDArray`, i see no reason for the databuffer to save this same exact value. Instead I think it makes alot of sense that `DataBuffer.length()` tells me how much underlying memory is tied up with the parent array.

**Comment by emillynge** [comment]
@AlexDBlack, can you tell me what the intended behaviour for `DataBuffer.length()` is/was supposed to be?

I'm basing this issue mostly on code you committed 2-3 years ago, so if I have misunderstood it's intentions, then this issue is moot.

The code I'm referring to is this: https://github.com/deeplearning4j/deeplearning4j/commit/45b470325f00de13572243a00f5ddd51f9e1a0b4#diff-7cfd9d445226329cc274799cbfe8452fR1457

By the way, the method `isContiguousInBuffer(INDArray in)` is broken atm. since `in.length() == in.data().length()` is **always** true. Although it is only being used in one other method in the code base.

**Comment by AlexDBlack** [comment]
> the method isContiguousInBuffer(INDArray in) is broken atm

No, it's not broken - ```in.length() == in.data().length()``` is not usually true for views

**Comment by AlexDBlack** [comment]
As for the other issues - I'm not seeing a problem here...

> the original idea behind DataBuffer.length() is to determine how much memory a matrix is depending on in native memory

it's just the number of elements of whatever type in the data buffer


> It becomes more cumbersome to figure out whether an array is contiguous

We have helper methods for that, as you have found. If users need to know it, and existing methods aren't suitable - let's add an INDArray.isContiguous() or something?

> Serializing an array by serializing DataBuffer risk copying the wrong part of memory

We use view checks + check if contiguous before serializing. It's an implementation issue that shouldn't be impacting users - users shouldn't normally be touching the databuffers directly for serialization (though if they do, a simple "dup" will make it safe to use).

> It is difficult to figure out whether an array is attempting to access an element beyond it's underlying buffer since the indexer routinely reads elements at indices way above DataBuffer.length

We have bounds checking on all ops like putScalar AFAIK. Can you actually point to a place where we don't?

**Comment by emillynge** [comment]
> No, it's not broken - in.length() == in.data().length() is not usually true for views

It is true for views that requires a subbuffer. i.e views that does not include the very first element.
Some example code of this happenning:
```
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.factory.Nd4j;

public class DataBufferLengthIssueShowcase
{
    public static void printArrayAndBuffer(INDArray arr, String title){
        if (title != null){
            int leftPad = 20 - title.length() / 2;
            int rightPad = 40 - leftPad + title.length();
            for (int i = 0; i++ < leftPad;) System.out.print("=");
            System.out.print(" " + title + " ");
            for (int i = 0; i++ < rightPad;) System.out.print("=");
            System.out.print("\n");
        }
        System.out.println(arr.shapeInfoToString());
        System.out.println(String.format("length of array: %d, length of databuffer: %d", arr.length(), arr.data().length()));
        System.out.println(String.format("offset of first element: %d\tindex of last element: %d", arr.offset(), offsetOfLastElement(arr)));
    }

    public static long offsetOfLastElement(INDArray arr){
        long offset = arr.offset();
        for (int i = 0; i < arr.rank(); ++i){
            offset += arr.stride(i) * (arr.shape()[i] - 1);
        }
        return offset;
    }

    public static void main(String[] argv){
        INDArray m = Nd4j.linspace(0,99,100).reshape(10,10);
        printArrayAndBuffer(m, "Initial array");

        printArrayAndBuffer(m.getRow(0), "first row");
        printArrayAndBuffer(m.getColumn(0), "first column");

        printArrayAndBuffer(m.getRow(5), "mid row");
        printArrayAndBuffer(m.getColumn(5), "mid column");

    }
}

OUTPUT:

============== Initial array =======================================
Rank: 2,Offset: 0
 Order: c Shape: [10,10],  stride: [10,1]
length of array: 100, length of databuffer: 100
offset of first element: 0	index of last element: 99
================ first row =================================
Rank: 2,Offset: 0
 Order: c Shape: [1,10],  stride: [1,1]
length of array: 10, length of databuffer: 100
offset of first element: 0	index of last element: 9
============== first column ======================================
Rank: 2,Offset: 0
 Order: c Shape: [10,1],  stride: [10,1]
length of array: 10, length of databuffer: 100
offset of first element: 0	index of last element: 90
================= mid row ==============================
Rank: 2,Offset: 0
 Order: c Shape: [1,10],  stride: [1,1]
length of array: 10, length of databuffer: 10
offset of first element: 50	index of last element: 59
=============== mid column ===================================
Rank: 2,Offset: 0
 Order: c Shape: [10,1],  stride: [10,1]
length of array: 10, length of databuffer: 10
offset of first element: 5	index of last element: 95

Process finished with exit code 0
```

As you can see, the view of the mid column suffers from this issue. length of both array and databuffer is 10, but in reality, the last element of the vector is positioned at offset 95. As far as DataBuffer is concerned, position 95 **should** be out of bounds.

This issue comes from this peice of code in `BaseNDArray`
```
    public BaseNDArray(DataBuffer buffer, int[] shape, int[] stride, long offset, char ordering) {
        this.compressed = false;
        this.data = offset > 0L ? Nd4j.createBuffer(buffer, offset, ArrayUtil.prodLong(shape)) : buffer;
        this.setShapeInformation(Nd4j.getShapeInfoProvider().createShapeInformation(shape, stride, offset, Shape.elementWiseStride(shape, stride, ordering == 'f'), ordering));
        this.init(shape, stride);
    }
```

As you can see, if a subarray has `offset > 0` then the length of the buffer is set **explicitly** to ArrayUtil.prodLong(shape), i.e. the length of the array without taking stride into account.

This mid column would be considered contiguous by `isContiguousInBuffer(INDArray in)` even though it clearly is not.

> > It becomes more cumbersome to figure out whether an array is contiguous
> 
> We have helper methods for that, as you have found

My point is only valid under the assumption that `isContiguousInBuffer`is in fact broken. By cumbersome, I mean that for this method to work reliably atm. we would have to do something creative, because a simple comparison between array length and buffer length cannot be trusted.

> > Serializing an array by serializing DataBuffer risk copying the wrong part of memory
> 
> We use view checks + check if contiguous before serializing. It's an implementation issue that shouldn't be impacting users - users shouldn't normally be touching the databuffers directly for serialization (though if they do, a simple "dup" will make it safe to use).

Always calling dup to be safe is bad for memory and performance, and a lot of users will prefer not to do this. A cannot point to a specific example right now, but I *have* found serializers in other deeplearning4j modules that uses databuffers for serialization directly where this issue *will* serialize something wrong if it is a subarray with offset > 0.

I think the main problem is that it is **really** intuitive for users that serializing the databuffer should at least give you the data you need, albeit possible a little more. 


> > It is difficult to figure out whether an array is attempting to access an element beyond it's underlying buffer since the indexer routinely reads elements at indices way above DataBuffer.length
> 
> We have bounds checking on all ops like putScalar AFAIK. Can you actually point to a place where we don't?

I cannot, but I really think that this is a bug waiting to happen. Right now the indexer owned by a databuffer could very well be accessing parts of that databuffer that is intuitively out of bounds. Either developers will think something has gone wrong, or they will learn to ignore what seems to be out of bounds access.

**Comment by emillynge** [comment]
> > isContiguousInBuffer is in fact broken.
>
> It's not - assuming we fix the data buffer length issue.

We agree :)


The reason for this statement was, that  in another issue i had filed, I was more or less told that the `databuffer.length()` behaviour in mid column was *intended*.

If that was true, then `isContiguousInBuffer` would in fact be considered broken. 

But since you agree that there is a bug in how `databuffer.length` is set for views, then `isContiguousInBuffer` is correct, even though it is sometimes being let down by other parts of the system.

>  I'd like to see specifics here. We only have a handful of serialization methods, and AFAIK all of them check for views, non-standard strides, etc before touching the buffer, which would catch this.
A few extra test for this condition would be a good idea, however.

Not a serialization, but this modified version of my script calls `INDArray.convertToDoubles` and throws an `IndexOutOfBoundsException`  when trying to print the resulting array: 
https://gist.github.com/emillynge/86369a51d92d2032ef53c9350f458c4e 

I did get an answer on this specific example:

> Sorry, this is the INDArray method that’s not supposed to be used on views.
There’s should be duo called if this.isView()

**Comment by AlexDBlack** [comment]
> Sorry, this is the INDArray method that’s not supposed to be used on views.
There’s should be duo called if this.isView()

I disagree with that statement, users shouldn't need to care if it's a view for standard ops like that. :)
Fixing the underlying buffer length issue will hopefully also fix that - but we should make that case a unit test to be sure...

**Comment by emillynge** [comment]
> That data buffer length is definitely wrong, should be length = prod_i(shape[i] * stride[i]) I think.

almost,  I think the correct code would be `prod_i((shape[i] - 1) * stride[i]) - offset`

**Comment by emillynge** [comment]
Thanks for fixing it! :)  it's been bugging me for some time now.
