### ISSUE TITLE
Didn't find class "org.bytedeco.javacpp.hdf5"

### ISSUE THREAD

**Issue by fstern97** [deeplearning4j/deeplearning4j#6146]
I want to use org.deeplearning4j.nn.modelimport.keras.KerasModelImport to import a pre-trained Keras Model in Android. However, whenever I run KerasModelImport.importKerasSequentialModelAndWeights I get the error message 

`E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.bytedeco.javacpp.hdf5"`

Digging into the code, org.bytedeco.javacpp does not even contain a hdf5 class, but org.bytedeco.javacpp-presets does. Possible bug in org.deeplearning4j.nn.modelimport.keras.KerasModelImport ?

**Comment by agibsonccc** [comment]
If this was a bug you would not have been the first person to find it. Please follow this blog post: https://medium.com/@bgweber/deploying-keras-deep-learning-models-with-java-62d80464f34a This is someone who just recently worked with it who isn't one of the contributors. This integration is widely used at this point.

**Comment by saudet** [comment]
HDF5 doesn't support Android. You'll need to import the model on the desktop.

**Comment by fstern97** [comment]
@saudet  Sorry, I am not really sure what you mean by "You'll need to import the model on the desktop". It is not possible to use "importKerasSequentialModelAndWeights" due to lacking HDF5 support ? Does that mean that there is no way to import a pre-trained Keras model using deeplearning4j an Android ?

**Comment by saudet** [comment]
Yes, that's correct, we need to import it on Linux, Mac, or Windows, and then load it in DL4J format on mobile platforms like Android or iOS.
