### ISSUE TITLE
Libnd4j: boolean_and/or op crash

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6158]
Both boolean_and and boolean_or ops are crashing on the following:

```
    @Test
    public void testBooleanAnd(){
        INDArray arr1 = Nd4j.create(new long[]{3,4});
        INDArray arr2 = Nd4j.create(new long[]{3,4});
        INDArray out = Nd4j.create(new long[]{3,4});

        DynamicCustomOp op = DynamicCustomOp.builder("boolean_and")
                .addInputs(arr1, arr2)
                .addOutputs(out)
                .build();
        Nd4j.getExecutioner().exec(op);
    }
```

Crash log:
https://gist.github.com/AlexDBlack/c82ccfbf6cd7febd298b22e950fa82d9

(Happens for both float and double precision)

Edit, unrelated: this line looks wrong (wrong op) for both ops:
https://github.com/deeplearning4j/deeplearning4j/blob/d01f7ddb25a8ba12d19622edd363ce92d78e5313/libnd4j/include/ops/declarable/generic/broadcastable/boolean_or.cpp#L22

**Comment by AlexDBlack** [comment]
Oh, and we don't have a ```boolean_xor``` op. Need this one too as a broadcastable op.

**Comment by raver119** [comment]
Hm. Good catch.

**Comment by raver119** [comment]
Fixed now, and xor + not were added as well.

**Comment by AlexDBlack** [comment]
Confirmed fixed - thanks!
