### ISSUE TITLE
LossFunction not propagating through layers

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#616]
Stepping through the MLP example MLPMNISTCMGS it appears that global lossFunction SquaredLoss is not updating on the layers. It shows as MCXENT.

**Comment by EronWright** [comment]
It could be due to #535.    Enum values aren't handled right in the layer API.    Let's re-test after the PR is merged.

**Comment by nyghtowl** [comment]
Confirmed closed
