### ISSUE TITLE
Keras Import of HDF5 MobileNet Fails

### ISSUE THREAD

**Issue by TobiasGoerke** [deeplearning4j/deeplearning4j#6161]
I have obtained a Keras .h5 model from [here](https://github.com/JonathanCMitchell/mobilenet_v2_keras/releases) (You will find a specific model attached).

When importing it via the inbuilt mechanism:

`KerasModelImport.importKerasModelAndWeights(pathToFile);
// or
KerasModelImport.importKerasSequentialModelAndWeights(pathToFile);`

 I am getting the following error: 

`java.lang.RuntimeException: org.deeplearning4j.nn.modelimport.keras.exceptions.InvalidKerasConfigurationException: Model configuration attribute missing from myfile.h5 archive.. For more information, see http://deeplearning4j.org/model-import-keras.`

I have very briefly tried to look into the file and it seems the definition is included (I am not sure though). Any way to fix this?

[mobilenet_v2_weights_tf_dim_ordering_tf_kernels_0.75_128.zip](https://github.com/deeplearning4j/deeplearning4j/files/2287056/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_0.75_128.zip)

**Comment by maxpumperla** [comment]
@TobiasGoerke not sure what's going on there, but it seems the file is corrupted. We have a test for mobile net on master:

https://github.com/deeplearning4j/deeplearning4j/blob/451dd76b50355358dc176f2b704e98c43423c5b8/deeplearning4j/deeplearning4j-modelimport/src/test/java/org/deeplearning4j/nn/modelimport/keras/e2e/KerasModelEndToEndTest.java#L407-L408

maybe you want to try this one instead?

**Comment by TobiasGoerke** [comment]
Thanks, this model now gets loaded without errors.
However, it throws an exception when being executed.

Following code should work (I suppose):
`
    public static void main(String[] args) throws Exception {
        String filePath = FileReader.resourceToFile("mobilenet_tf_keras_2.h5").getPath();
        ComputationGraph model = KerasModelImport.importKerasModelAndWeights(filePath);

        BufferedImage bufferedImage = FileReader.readResourceImage("dog.jpg");
        INDArray indArray = new Java2DNativeImageLoader().asMatrix(bufferedImage);

        model.output(false, indArray);
    }
`
Throws following error: 

`Exception in thread "main" org.deeplearning4j.exception.DL4JInvalidInputException: Got rank 3 array as input to ConvolutionLayer (layer name = conv_preds, layer index = 99) with shape [1, 1, 1024]. Expected rank 4 array with shape [minibatchSize, layerInputDepth, inputHeight, inputWidth]. (layer name: conv_preds, layer index: 99, layer type: ConvolutionLayer)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.validateInputRank(ConvolutionLayer.java:262)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.preOutput(ConvolutionLayer.java:293)
	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.activate(ConvolutionLayer.java:411)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:110)
	at org.deeplearning4j.nn.graph.ComputationGraph.outputOfLayersDetached(ComputationGraph.java:2287)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1698)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1648)
	at org.deeplearning4j.nn.graph.ComputationGraph.output(ComputationGraph.java:1629)
	...`

I am new to the DL4J framework so this could be an error on my side. Nonetheless, this does not look like an error due to missing preprocessing or whatever but more like a faulty model. Is that possible?

If you want me to, I'll create a new issue with this. 
Thanks! 

(Model attached)

**Comment by AlexDBlack** [comment]
@TobiasGoerke No, that's definitely not a bad model. That's an issue with the data pipeline.

Try with NativeImageLoader instead of Java2DNativeImageLoader

**Comment by TobiasGoerke** [comment]
@AlexDBlack I have tried both without success. I have also tried loading the image as a byte array and directly from file, among others.

**Comment by TobiasGoerke** [comment]
First off, excuse me for pushing this thread again. 
While looking for a solution, I stumbled upon a similar issue submitted on GitHub (see [here](https://github.com/deeplearning4j/deeplearning4j/issues/5393)).

The model provided by its author does not throw any error when called. Is it possible the dl4j-test-resources model is corrupted?

**Comment by maxpumperla** [comment]
@TobiasGoerke thanks for being persistent, that's very helpful. Would you mind creating a PR against test resources with that model?

I'm currently neck deep in something else, but can go back to keras import issues a littler quicker soon.
