### ISSUE TITLE
SameDiff: Need import support for TF assertions

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6181]
https://www.tensorflow.org/versions/r1.8/api_docs/python/tf/Assert
https://www.tensorflow.org/versions/r1.8/api_docs/python/tf/assert_equal

The behaviour we'd need to properly support this:
* Importing of the various ops
* Printing the specified max number of values if the assertion fails
* Throwing an exception at the java level, if the assertion fails (for both java/c++ execution model)

I'm running into this trying to import confusion matrix op...

@raver119 IIRC you mentioned looking at (or at least running into) this recently?

**Comment by raver119** [comment]
Yes, it's wip and will be implemented after spark is done

**Comment by AlexDBlack** [comment]
This is essentially fixed here: https://github.com/deeplearning4j/deeplearning4j/issues/6181

Two things remain:
1. Error messages are constants feeding into Assert nodes. They are String constants, so can't be properly supported until dtype changes are merged
2. We need to properly throw exceptions when assertions fail (currently only a message is printed in c++)
