### ISSUE TITLE
ND4J: Add convenience method for where_np op

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6184]
We have it, but users have to interact with the op directly, allocate output shapes
https://github.com/deeplearning4j/deeplearning4j/blob/451dd76b50355358dc176f2b704e98c43423c5b8/libnd4j/include/ops/declarable/generic/boolean/where_np.cpp
https://github.com/deeplearning4j/deeplearning4j/blob/451dd76b50355358dc176f2b704e98c43423c5b8/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/controlflow/WhereNumpy.java

So, something like Nd4j.where(...)

For anyone reading this - wokraround is using this, plus Nd4j.getExecutioner().calculateOutputShapes(op):
https://github.com/deeplearning4j/dl4j-examples/blob/049b072a8a082012e5f813269884e8ed524a484d/nd4j-examples/src/main/java/org/nd4j/examples/CustomOpsExamples.java

**Comment by tzolov** [comment]
The second snippets points to a `Nd4j.getExecutioner().exec(op)` not `Nd4j.getExecutioner().calculateOutputShapes(op)` example? 

From the [WhereNumpy  test code](https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/indexing/BooleanIndexingTest.java#L572) it is not clear how to return the element indexes (which is the np.where behavior) and not the values? Do i need to preinitialize the `put` array with the indexes? 
Are there some more elaborate `WhereNumpy` examples?

**Comment by tzolov** [comment]
For example, is it possible to use `WhereNumpy` for implementing the following np.where(...) like logic:
```java
private INDArray getIndexWhere(INDArray input, Predicate<Double> predicate) {
   // expects only vector or scalar !
   List<Integer> indexes = new ArrayList<>();
   for (int i = 0; i < input.size(0); i++) {
      if (predicate.test(input.getDouble(i))) 
         indexes.add(i);
   }

   return CollectionUtils.isEmpty(indexes) ?
      Nd4j.empty(DataBuffer.Type.FLOAT) : return Nd4j.create(outputList);
}
```

**Comment by AlexDBlack** [comment]
OK, so looking at this again:

One usage of where_np op takes 3 input variables, condition, x, y
and 1 output variable
Condition is a 0 or 1 valued array of the same shape as x/y

For the single input variable case (i.e., only "condition" array specified): it seems we return a 2d array of coordinates instead of a tuple of 1d coordinates
https://github.com/deeplearning4j/deeplearning4j/blob/451dd76b50355358dc176f2b704e98c43423c5b8/libnd4j/include/ops/declarable/generic/boolean/where_np.cpp#L86-L113

So, to answer your question: essentially, yes, but (same as numpy) input is an array post applicaiton of the predicate, not predicate as an argument.

That said, it seems the where_np shape function is wrong:
https://github.com/deeplearning4j/deeplearning4j/blob/451dd76b50355358dc176f2b704e98c43423c5b8/libnd4j/include/ops/declarable/generic/boolean/where_np.cpp#L121-L145

A workaround for now is simply calculating the number of matches yourself - for example:
```
int count = Nd4j.getExecutioner().exec(new MatchCondition(cg.params(), Conditions.equals(0))).z().getInt(0);
```
