### ISSUE TITLE
libnd4j: Need set of nd scatter ops

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6185]
Ops:
* scatter_nd
* scatter_nd_add
* scatter_nd_sub
* scatter_nd_update

https://www.tensorflow.org/api_docs/python/tf/scatter_nd_add

We'll need to be able to import these ops.

The TF docs/description for these ops is quite poor IMO, but these ops are related to (but different from) ops like scatter_add, scatter_update etc.
The key difference seems to be how the indexing is done and the ranks of the ref/indices/updates array.

(Note also that scatter_nd seems to be equivalent to scatter_nd_update but with "ref" being hard-coded to zeros(shape))

**Comment by shyrma** [comment]
Done!

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/6272
