### ISSUE TITLE
Workspace documentation refer to deprecated modes of operation

### ISSUE THREAD

**Issue by DrChainsaw** [deeplearning4j/deeplearning4j#6198]
Hi,

I just happened to see that the documentation for workspaces in the link below describes the now deprecated modes SEPARATE and SINGLE. From what I understand, the only supported modes now is ENABLED (more or less same as SEPARATE) and NONE.

https://deeplearning4j.org/docs/latest/deeplearning4j-config-workspaces

As a side note: SINGLE seemed to have almost 100% speedup over SEPARATE for architectures with many layers (e.g. inception or resnets) in some cases so the difference might have been more than "slight" in some cases. I posted some more info in #5288 in case this might be of interest to you.

**Comment by raver119** [comment]
Yes, it's documentation issue. 

Thanks for highlighting

**Comment by crockpotveggies** [comment]
Thanks for submitting this issue. We've migrated our docs to its own separate repository at [deeplearning4j-docs](https://github.com/deeplearning4j/deeplearning4j-docs). I've already migrated your issue and you can find it at https://github.com/deeplearning4j/deeplearning4j-docs/issues/124. 

I'll be closing this, but feel free to comment and re-open if this is not what you intended.

*This was an automatically generated response.*
