### ISSUE TITLE
Support for Keras layer type Conv2D

### ISSUE THREAD

**Issue by akazer2** [deeplearning4j/deeplearning4j#6199]
`Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.UnsupportedKerasConfigurationException: Unsupported keras layer type Conv2D.`

Would be great to get support for Conv2D in dl4j

**Comment by maxpumperla** [comment]
you must be on 0.9.1 or earlier, i.e. over a year of releases behind. upgrade your dl4j version!
