### ISSUE TITLE
Nd4j/Libnd4j: CI issue with TF import argmax test

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6210]
Test: "reductions/argmax3,4,5_-1" - passes locally on both of my machines (Windows 10, Kubunu 17.10). However is failing (timing out, 10 seconds - it should take <<10ms to execute) on multiple CI machines, for mac CPU, Linux AVX2, Linux AVX 512, Linux ppc64.

The other argmax tests (same shape, different axis) are OK.
Need to reproduce/isolate this before we can look into it more...

**Comment by raver119** [comment]
Hypothetically #6209 fixes this issue.

**Comment by AlexDBlack** [comment]
Ah, cool, I missed that one :)

**Comment by raver119** [comment]
Hm, looks like no luck. Will keep looking.

**Comment by raver119** [comment]
Issue resolved
