### ISSUE TITLE
Attempting to permute dimensions other thanspatial dimensions (height and width) in Permute layer

### ISSUE THREAD

**Issue by xiptos** [deeplearning4j/deeplearning4j#6213]
When importing a Keras model, I get the following exception:
[main] INFO org.deeplearning4j.nn.modelimport.keras.Hdf5Archive - Unexpected end-of-input: expected close marker for ARRAY (from [Source: {"class_name": "Model", "config": {"layers": [{"class_name": "InputLayer", "config": {"dtype": "float32", "batch_input_shape": [null, 48, 48, 3], "name": "input_1", "sparse": false}, "inbound_nodes": [], "name": "input_1"}, {"class_name": "Conv2D", "config": {"kernel_constraint": null, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "name": "conv1", "bias_regularizer": null, "bias_constraint": null, "activation": "linear", "trainable": true, "data_format": "channels_last", "padding": "valid", "strides": [1, 1], "dilation_rate": [1, 1], "kernel_regularizer": null, "filters": 32, "bias_initializer": {"class_name": "Zeros", "config": {}}, "use_bias": true, "activity_regularizer": null, "kernel_size": [3, 3]}, "inbound_nodes": [[["input_1", 0, 0, {}]]], "name": "conv1"}, {"class_name": "PReLU", "config": {"name": "prelu1", "alpha_constraint": null, "trainable": true, "alpha_regularizer": null, "alpha_initializer": {"class_name": "Zeros", "config": {}}, "shared_axes": [1, 2]}, "inbound_nodes": [[["conv1", 0, 0, {}]]], "name": "prelu1"}, {"class_name": "MaxPooling2D", "config": {"name": "max_pooling2d_1", "trainable": true, "data_format": "channels_last", "pool_size": [3, 3], "padding": "same", "strides": [2, 2]}, "inbound_nodes": [[["prelu1", 0, 0, {}]]], "name": "max_pooling2d_1"}, {"class_name": "Conv2D", "config": {"kernel_constraint": null, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "name": "conv2", "bias_regularizer": null, "bias_constraint": null, "activation": "linear", "trainable": true, "data_format": "channels_last", "padding": "valid", "strides": [1, 1], "dilation_rate": [1, 1], "kernel_regularizer": null, "filters": 64, "bias_initializer": {"class_name": "Zeros", "config": {}}, "use_bias": true, "activity_regularizer": null, "kernel_size": [3, 3]}, "inbound_nodes": [[; line: 1, column: 1999])
 at [Source: {"class_name": "Model", "config": {"layers": [{"class_name": "InputLayer", "config": {"dtype": "float32", "batch_input_shape": [null, 48, 48, 3], "name": "input_1", "sparse": false}, "inbound_nodes": [], "name": "input_1"}, {"class_name": "Conv2D", "config": {"kernel_constraint": null, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "name": "conv1", "bias_regularizer": null, "bias_constraint": null, "activation": "linear", "trainable": true, "data_format": "channels_last", "padding": "valid", "strides": [1, 1], "dilation_rate": [1, 1], "kernel_regularizer": null, "filters": 32, "bias_initializer": {"class_name": "Zeros", "config": {}}, "use_bias": true, "activity_regularizer": null, "kernel_size": [3, 3]}, "inbound_nodes": [[["input_1", 0, 0, {}]]], "name": "conv1"}, {"class_name": "PReLU", "config": {"name": "prelu1", "alpha_constraint": null, "trainable": true, "alpha_regularizer": null, "alpha_initializer": {"class_name": "Zeros", "config": {}}, "shared_axes": [1, 2]}, "inbound_nodes": [[["conv1", 0, 0, {}]]], "name": "prelu1"}, {"class_name": "MaxPooling2D", "config": {"name": "max_pooling2d_1", "trainable": true, "data_format": "channels_last", "pool_size": [3, 3], "padding": "same", "strides": [2, 2]}, "inbound_nodes": [[["prelu1", 0, 0, {}]]], "name": "max_pooling2d_1"}, {"class_name": "Conv2D", "config": {"kernel_constraint": null, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "name": "conv2", "bias_regularizer": null, "bias_constraint": null, "activation": "linear", "trainable": true, "data_format": "channels_last", "padding": "valid", "strides": [1, 1], "dilation_rate": [1, 1], "kernel_regularizer": null, "filters": 64, "bias_initializer": {"class_name": "Zeros", "config": {}}, "use_bias": true, "activity_regularizer": null, "kernel_size": [3, 3]}, "inbound_nodes": [[; line: 1, column: 4001]
[main] INFO org.deeplearning4j.nn.modelimport.keras.Hdf5Archive - Unexpected end-of-input within/between OBJECT entries
 at [Source: {"class_name": "Model", "config": {"layers": [{"class_name": "InputLayer", "config": {"dtype": "float32", "batch_input_shape": [null, 48, 48, 3], "name": "input_1", "sparse": false}, "inbound_nodes": [], "name": "input_1"}, {"class_name": "Conv2D", "config": {"kernel_constraint": null, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "name": "conv1", "bias_regularizer": null, "bias_constraint": null, "activation": "linear", "trainable": true, "data_format": "channels_last", "padding": "valid", "strides": [1, 1], "dilation_rate": [1, 1], "kernel_regularizer": null, "filters": 32, "bias_initializer": {"class_name": "Zeros", "config": {}}, "use_bias": true, "activity_regularizer": null, "kernel_size": [3, 3]}, "inbound_nodes": [[["input_1", 0, 0, {}]]], "name": "conv1"}, {"class_name": "PReLU", "config": {"name": "prelu1", "alpha_constraint": null, "trainable": true, "alpha_regularizer": null, "alpha_initializer": {"class_name": "Zeros", "config": {}}, "shared_axes": [1, 2]}, "inbound_nodes": [[["conv1", 0, 0, {}]]], "name": "prelu1"}, {"class_name": "MaxPooling2D", "config": {"name": "max_pooling2d_1", "trainable": true, "data_format": "channels_last", "pool_size": [3, 3], "padding": "same", "strides": [2, 2]}, "inbound_nodes": [[["prelu1", 0, 0, {}]]], "name": "max_pooling2d_1"}, {"class_name": "Conv2D", "config": {"kernel_constraint": null, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "name": "conv2", "bias_regularizer": null, "bias_constraint": null, "activation": "linear", "trainable": true, "data_format": "channels_last", "padding": "valid", "strides": [1, 1], "dilation_rate": [1, 1], "kernel_regularizer": null, "filters": 64, "bias_initializer": {"class_name": "Zeros", "config": {}}, "use_bias": true, "activity_regularizer": null, "kernel_size": [3, 3]}, "inbound_nodes": [[["max_pooling2d_1", 0, 0, {}]]], "name": "conv2"}, {"class_name": "PReLU", "config": {"name": "prelu2", "alpha_constraint": null, "trainable": true, "alpha_regularizer": null, "alpha_initializer": {"class_name": "Zeros", "config": {}}, "shared_axes": [1, 2]}, "inbound_nodes": [[["conv2", 0, 0, {}]]], "name": "prelu2"}, {"class_name": "MaxPooling2D", "config": {"name": "max_pooling2d_2", "trainable": true, "data_format": "channels_last", "pool_size": [3, 3], "padding": "valid", "strides": [2, 2]}, "inbound_nodes": [[["prelu2", 0, 0, {}]]], "name": "max_pooling2d_2"}, {"class_name": "Conv2D", "config": {"kernel_constraint": null, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "name": "conv3", "bias_regularizer": null, "bias_constraint": null, "activation": "linear", "trainable": true, "data_format": "channels_last", "padding": "valid", "strides": [1, 1], "dilation_rate": [1, 1], "kernel_regularizer": null, "filters": 64, "bias_initializer": {"class_name": "Zeros", "config": {}}, "use_bias": true, "activity_regularizer": null, "kernel_size": [3, 3]}, "inbound_nodes": [[["max_pooling2d_2", 0, 0, {}]]], "name": "conv3"}, {"class_name": "PReLU", "config": {"name": "prelu3", "alpha_constraint": null, "trainable": true, "alpha_regularizer": null, "alpha_initializer": {"class_name": "Zeros", "config": {}}, "shared_axes": [1, 2]}, "inbound_nodes": [[["conv3", 0, 0, {}]]], "name": "prelu3"}, {"class_name": "MaxPooling2D", "config": {"name": "max_pooling2d_3", "trainable": true, "data_format": "channels_last", "pool_size": [2, 2], "padding": "valid", "strides": [2, 2]}, "inbound_nodes": [[["prelu3", 0, 0, {}]]], "name": "max_pooling2d_3"}, {"class_name": "Conv2D", "config": {"kernel_constraint": null, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "name": "conv4", "bias_regularizer": null,; line: 1, column: 8001]
[main] INFO org.deeplearning4j.nn.modelimport.keras.Hdf5Archive - Unexpected end-of-input: was expecting closing '"' for name
 at [Source: {"class_name": "Model", "config": {"layers": [{"class_name": "InputLayer", "config": {"dtype": "float32", "batch_input_shape": [null, 48, 48, 3], "name": "input_1", "sparse": false}, "inbound_nodes": [], "name": "input_1"}, {"class_name": "Conv2D", "config": {"kernel_constraint": null, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "name": "conv1", "bias_regularizer": null, "bias_constraint": null, "activation": "linear", "trainable": true, "data_format": "channels_last", "padding": "valid", "strides": [1, 1], "dilation_rate": [1, 1], "kernel_regularizer": null, "filters": 32, "bias_initializer": {"class_name": "Zeros", "config": {}}, "use_bias": true, "activity_regularizer": null, "kernel_size": [3, 3]}, "inbound_nodes": [[["input_1", 0, 0, {}]]], "name": "conv1"}, {"class_name": "PReLU", "config": {"name": "prelu1", "alpha_constraint": null, "trainable": true, "alpha_regularizer": null, "alpha_initializer": {"class_name": "Zeros", "config": {}}, "shared_axes": [1, 2]}, "inbound_nodes": [[["conv1", 0, 0, {}]]], "name": "prelu1"}, {"class_name": "MaxPooling2D", "config": {"name": "max_pooling2d_1", "trainable": true, "data_format": "channels_last", "pool_size": [3, 3], "padding": "same", "strides": [2, 2]}, "inbound_nodes": [[["prelu1", 0, 0, {}]]], "name": "max_pooling2d_1"}, {"class_name": "Conv2D", "config": {"kernel_constraint": null, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "name": "conv2", "bias_regularizer": null, "bias_constraint": null, "activation": "linear", "trainable": true, "data_format": "channels_last", "padding": "valid", "strides": [1, 1], "dilation_rate": [1, 1], "kernel_regularizer": null, "filters": 64, "bias_initializer": {"class_name": "Zeros", "config": {}}, "use_bias": true, "activity_regularizer": null, "kernel_size": [3, 3]}, "inbound_nodes": [[["max_pooling2d_1", 0, 0, {}]]], "name": "conv2"}, {"class_name": "PReLU", "config": {"name": "prelu2", "alpha_constraint": null, "trainable": true, "alpha_regularizer": null, "alpha_initializer": {"class_name": "Zeros", "config": {}}, "shared_axes": [1, 2]}, "inbound_nodes": [[["conv2", 0, 0, {}]]], "name": "prelu2"}, {"class_name": "MaxPooling2D", "config": {"name": "max_pooling2d_2", "trainable": true, "data_format": "channels_last", "pool_size": [3, 3], "padding": "valid", "strides": [2, 2]}, "inbound_nodes": [[["prelu2", 0, 0, {}]]], "name": "max_pooling2d_2"}, {"class_name": "Conv2D", "config": {"kernel_constraint": null, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "name": "conv3", "bias_regularizer": null, "bias_constraint": null, "activation": "linear", "trainable": true, "data_format": "channels_last", "padding": "valid", "strides": [1, 1], "dilation_rate": [1, 1], "kernel_regularizer": null, "filters": 64, "bias_initializer": {"class_name": "Zeros", "config": {}}, "use_bias": true, "activity_regularizer": null, "kernel_size": [3, 3]}, "inbound_nodes": [[["max_pooling2d_2", 0, 0, {}]]], "name": "conv3"}, {"class_name": "PReLU", "config": {"name": "prelu3", "alpha_constraint": null, "trainable": true, "alpha_regularizer": null, "alpha_initializer": {"class_name": "Zeros", "config": {}}, "shared_axes": [1, 2]}, "inbound_nodes": [[["conv3", 0, 0, {}]]], "name": "prelu3"}, {"class_name": "MaxPooling2D", "config": {"name": "max_pooling2d_3", "trainable": true, "data_format": "channels_last", "pool_size": [2, 2], "padding": "valid", "strides": [2, 2]}, "inbound_nodes": [[["prelu3", 0, 0, {}]]], "name": "max_pooling2d_3"}, {"class_name": "Conv2D", "config": {"kernel_constraint": null, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "name": "conv4", "bias_regularizer": null, "bias_constraint": null, "activation": "linear", "trainable": true, "data_format": "channels_last", "padding": "valid", "strides": [1, 1], "dilation_rate": [1, 1], "kernel_regularizer": null, "filters": 128, "bias_initializer": {"class_name": "Zeros", "config": {}}, "use_bias": true, "activity_regularizer": null, "kernel_size": [2, 2]}, "inbound_nodes": [[["max_pooling2d_3", 0, 0, {}]]], "name": "conv4"}, {"class_name": "PReLU", "config": {"name": "prelu4", "alpha_constraint": null, "trainable": true, "alpha_regularizer": null, "alpha_initializer": {"class_name": "Zeros", "config": {}}, "shared_axes": [1, 2]}, "inbound_nodes": [[["conv4", 0, 0, {}]]], "name": "prelu4"}, {"class_name": "Permute", "config": {"dims": [3, 2, 1], "trainable": true, "name": "permute_1"}, "inbound_nodes": [[["prelu4", 0, 0, {}]]], "name": "permute_1"}, {"class_name": "Flatten", "config": {"trainable": true, "name": "flatten_1", "data_format": "channels_last"}, "inbound_nodes": [[["permute_1", 0, 0, {}]]], "name": "flatten_1"}, {"class_name": "Dense", "config": {"kernel_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "name": "conv5", "kernel_constraint": null, "bias_regularizer": null, "bias_constraint": null, "activation": "linear", "trainable": true, "kernel_regularizer": null, "bias_initializer": {"class_name": "Zeros", "config": {}}, "units": 256, "use_bias": true, "activity_regularizer": null}, "inbound_nodes": [[["flatten_1", 0, 0, {}]]], "name": "conv5"}, {"class_name": "PReLU", "config": {"name": "prelu5", "alpha_constraint": null, "trainable": true, "alpha_regularizer": null, "alpha_initializer": {"class_name": "Zeros", "config": {}}, "shared_axes": null}, "inbound_nodes": [[["conv5", 0, 0, {}]]], "name": "prelu5"}, {"class_name": "Dense", "config": {"kernel_initializer": {"class_name": "VarianceScaling", "config": {"distribution": "uniform", "scale": 1.0, "seed": null, "mode": "fan_avg"}}, "nam; line: 1, column: 12001]
[main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
[main] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 2
[main] INFO org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 2
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CPU]; OS: [Mac OS X]
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [4]; Memory: [1.8GB];
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [MKL]
Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.InvalidKerasConfigurationException: Attempting to permute dimensions other thanspatial dimensions (height and width) in Permute layer, got [3, 2, 1]. For more information, see http://deeplearning4j.org/model-import-keras.
	at org.deeplearning4j.nn.modelimport.keras.layers.core.KerasPermute.getInputPreprocessor(KerasPermute.java:115)
	at org.deeplearning4j.nn.modelimport.keras.layers.core.KerasPermute.getOutputType(KerasPermute.java:143)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.inferOutputTypes(KerasModel.java:306)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:181)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:98)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:305)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:127)
	at pt.ipb.face.Mtcnn2Dl4j.main(Mtcnn2Dl4j.java:15)

The source code in in attach, as well as the keras model file. The operating system is macOS High Sierra 10.13.6, with 
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

Is the problem related to the keras model or some problem with keras_import?

[48net_complete.h5.zip](https://github.com/deeplearning4j/deeplearning4j/files/2301895/48net_complete.h5.zip)

[Mtcnn2Dl4j.java.zip](https://github.com/deeplearning4j/deeplearning4j/files/2301896/Mtcnn2Dl4j.java.zip)

**Comment by maxpumperla** [comment]
@xiptos can you explain what your model is supposed to do? So you want to flip the input completely from (1,2,3) to (3,2,1)? We have some safeguards in DL4J to prevent users from doing stuff that is allowed in keras.

**Comment by xiptos** [comment]
I'm trying to implement (by importing) the MTCNN approach to detect human faces, from the python project https://github.com/xiangrufan/keras-mtcnn/blob/master/MTCNN.py and based on the paper https://kpzhang93.github.io/papers/spl.pdf
There are two more models, and I'm also having some exceptions importing them.

**Comment by Arkariian** [comment]
i discover the same problem on conv2D model imported from keras but my model charge and predict bad.


0 [main] INFO org.deeplearning4j.nn.modelimport.keras.Hdf5Archive  - Unexpected end-of-input: was expecting closing '"' for name
 at [Source: {"class_name": "Sequential", "config": [{"class_name": "Conv2D", "config": {"padding": "same", "batch_input_shape": [null, 64, 85, 1], "bias_regularizer": null, "strides": [1, 1], "kernel_regularizer": null, "bias_initializer": {"class_name": "Zeros", "config": {}}, "activation": "relu", "kernel_initializer": {"class_name": "VarianceScaling", "config": {"mode": "fan_avg", "scale": 1.0, "seed": null, "distribution": "uniform"}}, "kernel_constraint": null, "name": "conv2d_1", "data_format": "channels_last", "bias_constraint": null, "dilation_rate": [1, 1], "use_bias": true, "trainable": true, "dtype": "float32", "filters": 32, "kernel_size": [5, 5], "activity_regularizer": null}}, {"class_name": "MaxPooling2D", "config": {"padding": "valid", "data_format": "channels_last", "strides": [2, 2], "pool_size": [2, 2], "name": "max_pooling2d_1", "trainable": true}}, {"class_name": "Conv2D", "config": {"padding": "same", "kernel_regularizer": null, "trainable": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"mode": "fan_avg", "scale": 1.0, "seed": null, "distribution": "uniform"}}, "strides": [1, 1], "bias_initializer": {"class_name": "Zeros", "config": {}}, "activation": "relu", "bias_regularizer": null, "kernel_constraint": null, "name": "conv2d_2", "data_format": "channels_last", "bias_constraint": null, "dilation_rate": [1, 1], "use_bias": true, "filters": 64, "kernel_size": [3, 3], "activity_regularizer": null}}, {"class_name": "MaxPooling2D", "config": {"padding": "valid", "data_format": "channels_last", "strides": [2, 2], "pool_size": [2, 2], "name": "max_pooling2d_2", "trainable": true}}, {"class_name": "Conv2D", "config": {"padding": "same", "kernel_regularizer": null, "trainable": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"mode": "fan_avg", "scale": 1.0, "seed": null, "distribution": "uniform"}}, "strides": [1, 1], "bias_initializer": {"class_name": "Zeros", "config": {}}, "activation": "relu", "bias_regulariz; line: 1, column: 4001]
46 [main] INFO org.deeplearning4j.nn.modelimport.keras.Hdf5Archive  - Unexpected end-of-input: was expecting closing '"' for name
 at [Source: {"class_name": "Sequential", "config": [{"class_name": "Conv2D", "config": {"padding": "same", "batch_input_shape": [null, 64, 85, 1], "bias_regularizer": null, "strides": [1, 1], "kernel_regularizer": null, "bias_initializer": {"class_name": "Zeros", "config": {}}, "activation": "relu", "kernel_initializer": {"class_name": "VarianceScaling", "config": {"mode": "fan_avg", "scale": 1.0, "seed": null, "distribution": "uniform"}}, "kernel_constraint": null, "name": "conv2d_1", "data_format": "channels_last", "bias_constraint": null, "dilation_rate": [1, 1], "use_bias": true, "trainable": true, "dtype": "float32", "filters": 32, "kernel_size": [5, 5], "activity_regularizer": null}}, {"class_name": "MaxPooling2D", "config": {"padding": "valid", "data_format": "channels_last", "strides": [2, 2], "pool_size": [2, 2], "name": "max_pooling2d_1", "trainable": true}}, {"class_name": "Conv2D", "config": {"padding": "same", "kernel_regularizer": null, "trainable": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"mode": "fan_avg", "scale": 1.0, "seed": null, "distribution": "uniform"}}, "strides": [1, 1], "bias_initializer": {"class_name": "Zeros", "config": {}}, "activation": "relu", "bias_regularizer": null, "kernel_constraint": null, "name": "conv2d_2", "data_format": "channels_last", "bias_constraint": null, "dilation_rate": [1, 1], "use_bias": true, "filters": 64, "kernel_size": [3, 3], "activity_regularizer": null}}, {"class_name": "MaxPooling2D", "config": {"padding": "valid", "data_format": "channels_last", "strides": [2, 2], "pool_size": [2, 2], "name": "max_pooling2d_2", "trainable": true}}, {"class_name": "Conv2D", "config": {"padding": "same", "kernel_regularizer": null, "trainable": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"mode": "fan_avg", "scale": 1.0, "seed": null, "distribution": "uniform"}}, "strides": [1, 1], "bias_initializer": {"class_name": "Zeros", "config": {}}, "activation": "relu", "bias_regularizer": null, "kernel_constraint": null, "name": "conv2d_3", "data_format": "channels_last", "bias_constraint": null, "dilation_rate": [1, 1], "use_bias": true, "filters": 128, "kernel_size": [3, 3], "activity_regularizer": null}}, {"class_name": "MaxPooling2D", "config": {"padding": "valid", "data_format": "channels_last", "strides": [2, 2], "pool_size": [2, 2], "name": "max_pooling2d_3", "trainable": true}}, {"class_name": "Flatten", "config": {"name": "flatten_1", "data_format": "channels_last", "trainable": true}}, {"class_name": "Dropout", "config": {"name": "dropout_1", "noise_shape": null, "trainable": true, "seed": null, "rate": 0.5}}, {"class_name": "Dense", "config": {"bias_regularizer": null, "kernel_regularizer": null, "trainable": true, "bias_initializer": {"class_name": "Zeros", "config": {}}, "activation": "relu", "kernel_initializer": {"class_name": "VarianceScaling", "config": {"mode": "fan_avg", "scale": 1.0, "seed": null, "distribution": "uniform"}}, "units": 512, "kernel_constraint": null, "bias_constraint": null, "use_bias": true, "name": "dense_1", "activity_regularizer": null}}, {"class_name": "BatchNormalization", "config": {"beta_constraint": null, "beta_initializer": {"class_name": "Zeros", "config": {}}, "moving_variance_initializer": {"class_name": "Ones", "config": {}}, "trainable": true, "moving_mean_initializer": {"class_name": "Zeros", "config": {}}, "beta_regularizer": null, "center": true, "scale": true, "gamma_initializer": {"class_name": "Ones", "config": {}}, "momentum": 0.99, "name": "batch_normalization_1", "gamma_regularizer": null, "axis": -1, "gamma_constraint": null, "epsilon": 0.001}}, {"class_name": "Dropout", "config": {"name": "dropout_2", "noise_shape": null, "trainable": true, "seed": null, "rate": 0.5}}, {"class_name": "Dense", "config": {"bias_regularizer": null, "kernel_regularizer": null, "trainable": true, "bias_initializer": {"class_name": "Zeros", "config": {}}, "activation": "linear", "kernel_initializer": {"clas; line: 1, column: 8001]

**Comment by maxpumperla** [comment]
@xiptos thanks for the reference. I'll check it out. in principle there's nothing preventing us from relaxing the restrictions, I just want to understand it better first.

@Arkariian please open another issue for your stuff, and include all relevant data (your model, dl4j version, full(!) stack trace). doesn't help to throw this into another, only slightly similar issue. :)

**Comment by maxpumperla** [comment]
@xiptos maybe you can help me out here. what's the supposed effect of permuting right before a flatten layer?

**Comment by xiptos** [comment]
I may be wrong, but I believe it has something to do with the optimisation of learning of symmetric or symmetry invariant situations.
