### ISSUE TITLE
libnd4j: where_np shape function needs proper implementation

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6226]
https://github.com/deeplearning4j/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/boolean/where_np.cpp#L121-L145

Currently hard-coded to [10,10] output.
I believe it should have shape [numMatches, rank(input)], where numMatches is the number of non-zero elements.

**Comment by shugeo** [comment]
Numpy behave the next way:
- if only one param used (condition matrix), then output shape copied from it;
- if two params uses - error occurs (ValueError: either both or neither of x and y should be given).
So, we should simply copy shape from the condition, when no other params were given.

**Comment by shugeo** [comment]
The TF behave as follow:
> A Tensor with the same type and shape as x, y if they are non-None. A Tensor with shape (num_true, dim_size(condition)).

the Where op behave as TF.

**Comment by AlexDBlack** [comment]
Right, that was my conclusion. The op implementation seems correct, but the shape function is wrong.
