### ISSUE TITLE
`batchSize` setting is confusing since it doesn't set minibatch size

### ISSUE THREAD

**Issue by tmbo** [deeplearning4j/deeplearning4j#623]
Having a look at the API I thought `batchSize(30)` will set the minibatch size to `30` but that is not the case. Batch size needs to be explicitly enforced by partitioning the data into several minibatch sized datasets.

I find that rather confusing since that setting is used for the size of the minibatch in a lot of frameworks.

I would propose to rename that setting and add javadoc to clarify its use. Furthermore, there should be documentation on how to set minibatches (since this is different to other frameworks which handle that internally whereas in DL4j this needs to be done explicitly).

**Comment by AlexDBlack** [comment]
.batchSize(...) option for configuration has been removed as of version 0.4-rc3.7
