### ISSUE TITLE
IterationListener are not working if the networks iterations setting is small

### ISSUE THREAD

**Issue by tmbo** [deeplearning4j/deeplearning4j#624]
Since `IterationListener` are getting passed the current iteration for the given batch, this number never exceeds the networks `iterations` setting.

This poses problems if the iterations setting is rather small eg. 5 and one want's to attach a listener `new LossPlotterIterationListener(iterations=10)` this listener will never do a thing. 

I am not sure if this is the intended behaviour. Either, the listeners should get the global iteration count passed or there should be a warning if one of the default listeners is setup with an iteration greater than the networks iteration setting.

**Comment by agibsonccc** [comment]
Basically, you need to set it to 1 in those situations. There's a reason the user can specify the number of iterations ;).
