### ISSUE TITLE
SameDiff: Sub-graph execution

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6246]
Sub-graph execution would be useful for both SameDiff and NativeGraphExecutioner execution.
Essentially, this comes down to a way to say "give me the arrays for these variables only" (and where appropriate, we only execute part of the graph.

We kind of have this with OutputMode.EXPLICIT for NativeGraphExecutioner - which is described as returning "only declared output fields". But at present, there's no way (AFAIK) to declare a variable as an "output".

**Comment by raver119** [comment]
As discussed in slack: something like optional SameDiff.setOutputs()/getOutputs() method which defines which variables will be returned (and their order) after execution.

**Comment by AlexDBlack** [comment]
It may be worthwhile doing a similar thing for losses - i.e., we could tag variables as losses, which might be useful for plotting and the like (for models with multiple components to the total graph loss)

**Comment by AlexDBlack** [comment]
This is now available with the recent execution rewrite.
