### ISSUE TITLE
Deconvolution2DLayer calculations are very slow

### ISSUE THREAD

**Issue by longzhendong** [deeplearning4j/deeplearning4j#6248]
What's the reason that Deconvolution2DLayer calculations are so slow? I found the following code to be slow. At the same time, I find it slower in a gpu environment

className :  NativeOpExecutioner
 OpStatus status = OpStatus.byNumber(loop.execCustomOpFloat(null, hash, inputBuffers, inputShapes, op.numInputArguments(), outputBuffers, outputShapes, op.numOutputArguments(), tArgs, op.numTArguments(), iArgs, op.numIArguments(), op.isInplaceCall()));

**Comment by raver119** [comment]
This operation isn't using GPU yet. Some operations added recently exist only for CPU right now, and GPU support is yet to be introduced.

**Comment by longzhendong** [comment]
@raver119 Will Deconvolution2DLayer support GPU computing?

**Comment by AlexDBlack** [comment]
@longzhendong yes, it will definitely be added in the future - all ops will have GPU support.
As for when Deconvolution2D will be implemented on GPU: we don't have an exact date. But more than a few weeks, less than a few months.
