### ISSUE TITLE
VGG16ImagePreProcessor.VGG_MEAN_OFFSET_BGR is in wrong order

### ISSUE THREAD

**Issue by monktastic** [deeplearning4j/deeplearning4j#6252]
The values should be {103.939, 116.779, 123.68}. They're backwards.

**Comment by saudet** [comment]
I think you're right, please send a pull request!

**Comment by monktastic** [comment]
Right-o: https://github.com/deeplearning4j/deeplearning4j/pull/6254

**Comment by AlexDBlack** [comment]
Thanks for flagging this, and for the PR!
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/6254
