### ISSUE TITLE
Setup Environment.

### ISSUE THREAD

**Issue by vishavdhanjal** [deeplearning4j/deeplearning4j#6256]
Kindly list all gradle dependencies (if possible) for deep learning in java and compatible java version for desktop application
.

**Comment by agibsonccc** [comment]
Our quick start guide covers this: https://deeplearning4j.org/docs/latest/deeplearning4j-quickstart There is not 1 set of dependencies for dl4j. There are just different combinations for different sets of dependencies like spark, ui,.. I'm not sure what you think dl4j does, but if you want the minimum, for running a neural net, check the quickstart and the examples for the miinimum and dl4j under different scenarios.

**Comment by vishavdhanjal** [comment]
CORRECT GRADLE DEPENDECIES WITH beta1 AND beta2
implementation 'org.deeplearning4j:deeplearning4j-core:1.0.0-beta2'
implementation 'org.nd4j:nd4j-native-platform:1.0.0-beta2'
implementation 'org.datavec:datavec-api:1.0.0-beta2'
implementation 'org.slf4j:slf4j-simple:1.7.25'
