### ISSUE TITLE
Shapes must be equal during backprop 

### ISSUE THREAD

**Issue by mxiao08** [deeplearning4j/deeplearning4j#6267]
The arch looks like this: 
Input (3, 1, 8) => EmbeddingSequenceLayer (3, 5, 8) => DenseLayer with RnnToFeedforwardPreprocessor (3*8, 5) 
=> RecurrentLayer with FeedforardToRnnPreprocessor (3, 5, 8)

The issue is: 
Shapes must be equal during backprop:  in.shape{} = [24, 5, 1], epsilon.shape() = [3, 5, 8]

version: 1.0.0.beta2 

Any suggestions?

**Comment by AlexDBlack** [comment]
If you are using EmbeddingSequenceLayer, you shouldn't be adding a preprocessor.
Just set the input type as InputType.recurrent(1) and you should be fine.

If that doesn't work - post the actual configuration code you have.

**Comment by mxiao08** [comment]
Thanks! It turns out I did both of setInputTyoe and add Preprocessors.
