### ISSUE TITLE
Question about Dropout with cuDNN

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#6270]
Run this small test code(with cuDNN),
	  Dropout d = new Dropout(0.5);
	  
	  INDArray in = Nd4j.ones(5, 3);
	  INDArray ret = Nd4j.rand(5, 3);	  
	  System.out.println(d.applyDropout(in, ret, 0, 0, LayerWorkspaceMgr.noWorkspaces()));

The result is not okay!

o.n.l.j.o.e.CudaExecutioner - Device Name: [GeForce GTX 1080 Ti]; CC: [6.1]; Total/free memory: [11811160064]
[[    0.4274,    0.1721,    0.6848], 
 [    0.2383,    0.4880,    0.5311], 
 [    0.2080,    0.2972,    0.2040], 
 [    0.1080,    0.1994,    0.6660], 
 [    0.3111,    0.8181,    0.7645]]

**Comment by Charele** [comment]
But run with CUDA(mean, not cuDNN), 
or with CPU Backend,
The result is good

o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 4
o.n.n.Nd4jBlas - Number of threads used for BLAS: 4
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 7]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [3.5GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [MKL]
[[         0,         0,         0], 
 [    2.0000,    2.0000,    2.0000], 
 [    2.0000,    2.0000,    2.0000], 
 [    2.0000,    2.0000,         0], 
 [    2.0000,    2.0000,    2.0000]]

**Comment by Charele** [comment]
See the Dropout.java, 

if(helper != null){
            helper.applyDropout(inputActivations, output, p);
            return output;
        }

        mask = workspaceMgr.createUninitialized(ArrayType.INPUT, output.shape(), output.ordering()).assign(1.0);
        Nd4j.getExecutioner().exec(new DropOutInverted(mask, mask, currP));
        Nd4j.getExecutioner().exec(new OldMulOp(inputActivations, mask, output));
        return output;

When enable cuDNN, the "helper" is not null, so execute by CudnnDropoutHelper class,
so I think the question in CudnnDropoutHelper.java

**Comment by AlexDBlack** [comment]
Looks like this is just a device/host stream synchronization issue
i.e., the op is executed asynchronously and it's showing the host (RAM) side array before it's completed and has been updated from GPU memory.
If you uncomment either of the lines in the test below, we get the expected results printed
So training should be totally fine

```
    @Test
    public void test(){
        Dropout d = new Dropout(0.5);

        INDArray in = Nd4j.ones(5, 3);
        INDArray ret = Nd4j.rand(5, 3);

        INDArray out = d.applyDropout(in, ret, 0, 0, LayerWorkspaceMgr.noWorkspaces());
//        Nd4j.getExecutioner().commit();
//        out.addi(0.0);
        System.out.println(out);
    }
```

@raver119 thoughts on the best way to handle this?
