### ISSUE TITLE
Error deserializing JSON ComputationGraphConfiguration

### ISSUE THREAD

**Issue by xiptos** [deeplearning4j/deeplearning4j#6271]
Hi!

I'm having this error when loading a saved model:
https://gist.github.com/xiptos/6d8eaaefe0a0500bd8ba28c9dac202bd

The model and source code are in attach.
[24net_complete.h5.zip](https://github.com/deeplearning4j/deeplearning4j/files/2318615/24net_complete.h5.zip)
[Mtcnn2Dl4j.java.zip](https://github.com/deeplearning4j/deeplearning4j/files/2318617/Mtcnn2Dl4j.java.zip)

**Comment by maxpumperla** [comment]
I'll have a look soon. thanks for reporting

**Comment by AlexDBlack** [comment]
Fixed a while ago here: https://github.com/deeplearning4j/deeplearning4j/pull/6504
Just needed JSON annotations on the constructor.
