### ISSUE TITLE
DL4J: Output Layers - validate incompatible loss/activation function combinations

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6280]
Common mistakes we should detect + warn users about:
* Softmax + nOut=1
* Softmax + XENT
* Sigmoid + MCXENT
* Non 0-1 activation fns (identity/tanh/relu etc) + XENT or MCXENT (or others that expect probabilities)

A warning would be a good start - an exception (that can be disabled via ```outputValidation(false)``` or something) might be even better - lower risk of users missing the warning.

**Comment by Charele** [comment]
Why dont' throw exception directly?

**Comment by AlexDBlack** [comment]
@Charele 
> Why dont' throw exception directly?

Why no exception at present? Because we just haven't implemented that.
Why no exception in the future? I'm proposing to do exactly that, but allow users to disable the exception manually. There's often edge cases we can't anticipate.
