### ISSUE TITLE
Why comment out the full connection layer for VGG16

### ISSUE THREAD

**Issue by crazymxm** [deeplearning4j/deeplearning4j#6284]
Full connection layers are commented out ,is this a bug?
```
 //                .layer(18, new DenseLayer.Builder().nOut(4096).dropOut(0.5)
 //                        .build())
//                .layer(19, new DenseLayer.Builder().nOut(4096).dropOut(0.5)
 //                        .build())
```

**Comment by saudet** [comment]
Maybe, it's been like that every since @crockpotveggies added them in commit 636f278e453e3dcf69a414c564d170963505ab1e, @crockpotveggies ?

BTW, sending a pull request for this would be more efficient to get feedback. Thanks!

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/6348
