### ISSUE TITLE
Libnd4j: Add histogram function for TF import

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6285]
https://www.tensorflow.org/api_docs/python/tf/histogram_fixed_width

We have an existing histogram function, but it's a TransformOp, and can't be used for import here, due to some slight op differences.
Histogram.java takes a single input, and min/max as extra args.
TF histogram takes 3 input arrays: values, min/max, and nBins.

**Comment by shyrma** [comment]
Done!
https://github.com/deeplearning4j/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/transforms/histogram_fixed_width.cpp

**Comment by AlexDBlack** [comment]
Mapped on java side and confirmed working. Thanks!
