### ISSUE TITLE
DL4J: Remove pretrain(boolean)/backprop(boolean) args

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6292]
cc @treo 

Since 1.0.0-alpha the various fit(DataSet), fit(DataSetIterator) etc methods have not performed layerwise pretraining. The motivation for this change is that the type of pretraining was 
i.e., it did 1 iteration/epoch of unsupervised training on each layer, and then 1 iteration/epoch of supervised backprop. This is not how stacked layerwise pretraining should be done.

What we actually want: N epochs on each layer, followed by M epochs backprop.

The end result is that currently we have backprop(boolean) and pretrain(boolean) on MultiLayerConfiguration/ComputationGraphConfiguration, which don't really do much any more.
These should be removed to simplify things for users, and avoid confusion.

**Comment by treo** [comment]
I propose we deprecate it now, and remove them later on when people had enough time to fix their stuff.

**Comment by AlexDBlack** [comment]
Now deprecated. Will be removed at a later date.
