### ISSUE TITLE
Allow to start RL4J learning from a saved policy file.

### ISSUE THREAD

**Issue by borkox** [deeplearning4j/deeplearning4j#6304]
Hi,
I want to propose 2 easy enhancements for RL4J framework:
1) Give possibility to change field "policy" from class A3CDiscrete, for example make second constructor, where I can give policy from outside.
2) Give possibility to set to ACPolicy instance the field "rd" which is the Random.

Real case scenario for this, is when I make learn process and I want to continue from save policy file, there is no possibility now. When I load policy from file, it has no Random object , and I cannot inject it.

**Comment by saudet** [comment]
Pretty sure that's fixed with pull #5988, what's missing?

**Comment by borkox** [comment]
Yes, I managed to get this working without reflection. Sorry for spamming. :)

**Comment by saudet** [comment]
Great! If there's any specific enhancements that would still be useful though, please send them over a pull request.
