### ISSUE TITLE
libn4dj: add reduce_any, reduce_all ops

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6314]
These are simple ops: boolean and/or reduction
I'm pretty sure we don't have these (we have pairwise, but not reduction cases).

https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/reduce_any

Should be quick/simple to implement.
For floating point inputs, the obvious solution treat 0 as false, non-zero as true

**Comment by raver119** [comment]
I was pretty sure we have those.

**Comment by raver119** [comment]
https://github.com/deeplearning4j/deeplearning4j/blob/55eac637e27af6991bc38219fb550522d29c0c99/libnd4j/include/loops/legacy_ops.h#L247-L248

**Comment by AlexDBlack** [comment]
Yeah, I literally just found those. Thanks :)
