### ISSUE TITLE
Configurable GraphServer builds

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#6332]
At this moment GraphServer is built for avx/avx2. Probably it would make sense to provide few Dockerfiles, targeting different CPU instruction sets based on basic Dockerfile? So we could include FMA3/FMA4 and AVX512 instruction sets.

**Comment by raver119** [comment]
cc @saudet @sshepel

**Comment by saudet** [comment]
That's not something we can test with Docker or VMs for that matter.

**Comment by raver119** [comment]
Right, but we can provide building options, and couple of alternative Dockerfiles?

So if someone wants AVX-512+MKL-DNN version - he picks one Dockerfile. If he want to run generic AVX2 stuff on AMD box - he picks other one.

Simple but should work i think

**Comment by saudet** [comment]
Yeah, but we don't need Docker just for that
