### ISSUE TITLE
width and height switched

### ISSUE THREAD

**Issue by mrroots** [deeplearning4j/deeplearning4j#634]
class: FeedForwardToCnnPreProcessor
method: preProcess

last line:  return input.reshape(input.size(0),numChannels,inputHeight,inputWidth);

inputHeight and inputWidth are switched

**Comment by nyghtowl** [comment]
That's the correct order. The order that we are working towards is height, width and that is the same as rows, columns.

**Comment by mrroots** [comment]
ok fine with that. But just as a remark: I really have the feeling that *somewhere* width/cols and height/rows are switched (just in case you realize it somewhere / play around with non-rectangular images)...

**Comment by agibsonccc** [comment]
It's usually in terms of rows/cols rather than width/height. If that make sense.
