### ISSUE TITLE
Word2Vec: vec.wordsNearest just returns "</s>" not any other words

### ISSUE THREAD

**Issue by firojalam** [deeplearning4j/deeplearning4j#635]
Not sure whether it is a bug or i am missing something.
File model = new File("/data/../w2v_models/GoogleNews-vectors-negative300.bin.gz");
Word2Vec vec = WordVectorSerializer.loadGoogleModel(model, true);
Collection<String> wordNearest = vec.wordsNearest("day", 20);

**Comment by agibsonccc** [comment]
Guessing not a problem anymore.
