### ISSUE TITLE
ND4J: The Tensorflow GraphRunner doesn't support models with boolean input Tensors

### ISSUE THREAD

**Issue by tzolov** [deeplearning4j/deeplearning4j#6357]
GraphRunner doesn't work with TF models that expect boolean input feed. For example an attempt to infer the [facenet](https://gist.github.com/tzolov/f227797fcd5f68cb2dfde2f625f35b54) pre-trained model yields error when trying to substitute boolean by 0/1 floats: 
```
Exception in thread "main" java.lang.RuntimeException: ERROR: Unable to run session Expects arg[1] to be bool but float is provided
    at org.nd4j.tensorflow.conversion.graphrunner.GraphRunner.run(GraphRunner.java:266)
```
The `GraphRunner#run` takes a `INDArray` input feed, which doesn't support native boolean types. Attempt to use 0/1 instead doesn't work either.

**Comment by agibsonccc** [comment]
@tzolov 

Could you post your input graph so we can add that to our test cases. We're careful to prioritize things with real use cases with both this and our model import.

Beyond that,we'll document that. Nd4j itself needs to support strings and booleans yet. 
We may consider also doing that conversion internally. 

Basically, we're doing the memory management internally. For now, if you can convert it to float (0/1)s and it should work as a workaround. We'll make sure to update the docs. @raver119 is working on the last part of this to make it work.

**Comment by AlexDBlack** [comment]
Previously (as of 1.0.0-beta2) we weren't able to load boolean arrays. Now we do via conversion to 0/1 values, which I've used for numerous tests on master/snapshots.

Are you testing this on 1.0.0-beta2 or snapshots?

**Comment by tzolov** [comment]
@AlexDBlack , yes i'm using ND4J:1.0.0-beta2 and javacpp/Tensorflow: 1.9.0-1.4.2

@agibsonccc i'm using the pre-trained [CASIA-WebFace](https://drive.google.com/open?id=1R77HmFADxe87GmoLwzfgMu_HY0IhcyBz) facenet  model from: https://github.com/davidsandberg/facenet#pre-trained-models

I've tried passing a float ND4j value (e.g `Nd4j.scalar(0.0f)` and `Nd4j.create(new float[] {0.0f})`? )  with no luck (` Unable to run session Expects arg[1] to be bool but float is provided`)

Because Nd4j doesn't support boolean types and therefore there is no clean way to convert a Nd4j value into boolean tensor, for the experiment, i've tried to extend the GraphRunner with `run(Map<String, TF_Tensor>)` and create a boolean TF_Tensor directly like this: 
```java
int TF_BOOLEAN_TYPE = 10;
BoolPointer bp = new BoolPointer(1);
bp.put(false);
tensorflow.TF_Tensor booleanTensor = tensorflow.TF_Tensor.newTensor(TF_BOOLEAN_TYPE, new long[] { 1L }, bp);```
But this is likely incorrect either as it yields another error.

**Comment by agibsonccc** [comment]
@tzolov right you'd have to convert the graph input type itself to float is what I was saying. We might have to change the graph runner to intercept it. If we can map the input types, it shouldn't be hard to do a conversion internally for unsupported types like that. 
Something like:
allocate float/int -> run as boolean -> use something like tf_cast internally to make it boolean.

After that it should work fine.That's what I'd like to try with the graph runner when I get some time.

Nd4j itself is mainly used for the memory management part (think easy to use api for cpu/gpu with some zero copy) then after that it is graph runner + c api. Some small shims for easy use cases wouldn't be that hard to deal with.

**Comment by raver119** [comment]
This issue should be resolved now, since multiple data types support was merged quite a while ago + tests say that import/execution of such models works fine.
