### ISSUE TITLE
ND4J broadcast validation exception for broadcast multiply

### ISSUE THREAD

**Issue by gordoncaleb** [deeplearning4j/deeplearning4j#6364]
I upgraded to ND4J 1.0.0-beta2 today and an old issue with broadcast multiplying that I had a work around for before no longer works.

In Numpy for example:
```
a = np.array([1, 2, 3, 4]).reshape(2, 2, 1, 1)
b = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(2, 2, 2, 1)
c = np.multiply(b, a)
print(c)
```
I get:
```
[[[[ 1]
   [ 2]]

  [[ 6]
   [ 8]]]


 [[[15]
   [18]]

  [[28]
   [32]]]]
```

but with ND4J 1.0.0-beta2:

```
INDArray a = Nd4j.create(new double[]{1, 2, 3, 4}, new int[]{2, 2, 1, 1});
INDArray b = Nd4j.create(new double[]{1, 2, 3, 4, 5, 6, 7, 8}, new int[]{2, 2, 2, 1});
INDArray c = b.mul(a);
System.out.println(c);
```

I now get:
```
java.lang.IllegalStateException: Dimensions mismatch on dimension 1: x shape [1, 2, 2, 2], y shape [1, 1, 2, 2]

	at org.nd4j.base.Preconditions.throwStateEx(Preconditions.java:626)
	at org.nd4j.base.Preconditions.checkState(Preconditions.java:361)
	at org.nd4j.linalg.factory.Broadcast.validateBroadcastDims(Broadcast.java:274)
	at org.nd4j.linalg.api.ops.BaseBroadcastOp.<init>(BaseBroadcastOp.java:147)
	at org.nd4j.linalg.api.ops.impl.broadcast.BroadcastMulOp.<init>(BroadcastMulOp.java:31)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.muli(BaseNDArray.java:3825)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.mul(BaseNDArray.java:3548)
```

In 1.0.0-beta I was able to create the BroadcastMulOp manually and specify different dimensions to execute along. Now the BroadcastMulOp constructor has a shape check that seems to disallow the example above.

Good work on beta2 btw. The int to long shape migration must have been a beast.
Thanks!

Aha! Link: https://skymindai.aha.io/features/ND4J-160

**Comment by AlexDBlack** [comment]
Right, we don't have proper auto broadcasting implemented (yet) at the level of ND4J.
That will happen in the next release or 2.

In the mean time, you can manually broadcast using:
https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Broadcast.java

So something like:
```
INDArray result = Nd4j.create(Shape.broadcastOutputShape(a.shape(), b.shape());
Broadcast.mul(a,b,result, 0, 1, 3);   // [2,2,1,1] and [2,2,2,1] have matching shapes on dims 0, 1 and 3
```

**Comment by raver119** [comment]
Implemented in CUDA pr, will be merged later today.
