### ISSUE TITLE
3D CNN throwing ND4JIllegalStateException

### ISSUE THREAD

**Issue by HGuillemet** [deeplearning4j/deeplearning4j#6366]
Here is a standalone test class that throws:
ND4JIllegalStateException: X, Y and Z arguments should have the same length for PairwiseTransform. x: length 1024, shape [32, 32]; y: 28672, shape [28, 32, 32]; z: 1024, shape [32, 32]

[gist](https://gist.github.com/HGuillemet/7806b31234b84f475aebc4833edea79d#file-gistfile1-txt)

It uses a dummy custom RecordReader that returns 10 3D records filled with 0 and with label 0.

**Comment by AlexDBlack** [comment]
So, looking at this: there's a couple of issues - one on your side, and one on ours.

First, 3D CNN data/activations have 5 dimensions, not 3. See this for more details:
https://github.com/deeplearning4j/deeplearning4j/blob/0294e884659c05dc8cdbb9aef5cce0ff10e420e2/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/layers/Convolution3D.java#L48-L56
For single examples, your leading dimension should be 1

Second: RecordReaderMultiDataSetIterator hadn't been set up for 5D data via NDArrayWritables.
This PR adds support for that: https://github.com/deeplearning4j/deeplearning4j/pull/6370
After it has been merged, you can switch to snapshots to access the fix: https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots
It usually takes a few hours after a pull request has been merged for the snapshots to become available.

**Comment by HGuillemet** [comment]
Thanks.
I added 
.dataFormat(Convolution3D.DataFormat.NCDHW)
to my Convolution3D layer (first layer only, I guess it's enough. BTW any reason why this setting is not available for SubSampling3D Layer ?)
And changed the shape of my data brick to [1, 1, nZ, nY, X] 
Now I get:
java.lang.RuntimeException: Unexpected rank: 5
Waiting for your merge.
I'm trying to switch to snapshot but am struggling with an UnsatisfiedLinkError : libjnind4jcpu.so not finding libmkldnn.so...

**Comment by HGuillemet** [comment]
Found a workaround for the UnsatisfiedLinkError by manually creating a missing symlink to libmkldnn.so.0. 
Jenkins cannot build your commit, apparently.
