### ISSUE TITLE
pretrainLayer in MultiLayerNetwork

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#6368]
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java

line 344:
if(numEpochs > 1 && iter.resetSupported())
            throw new IllegalStateException("Cannot fit multiple epochs (" + numEpochs + ") on an iterator that doesn't support resetting");

I think is it should be "&& !iter.resetSupported())" ?

**Comment by AlexDBlack** [comment]
Yes, it definitely should be. Thanks, I'll push up a fix today.
Workaround is to use a for loop over epochs + pretrainLayer(DataSetIterator)

**Comment by Charele** [comment]
Okay.
Another question, I think should add a map method to INDArray? it can handle every element of this INDArray for special request

For example: 
all positive number need add 10, 
negative number if less than -15, will be set -15, other negative number keep.

I think it likes this:
public INDArray map(java.util.function.Function<Double, Double> fun1) {
        // internal handle...
       return this;
 }

INDArray nd1 = ...
Function<Double, Double> fun1 =
	new Function<Double, Double>() {
		@Override
		public Double apply(Double t) {
			if (t > 0) return t + 10;
			if (t < -15) return -15.0;
			return t;					
		}			
	};

nd1.map(fun1) :-)

**Comment by AlexDBlack** [comment]
@Charele that's a seperate issue. We have some functionality for these sorts of operations (see BooleanIndexing class and examples).
Generally you want to avoid those sorts of pure-java solutions, as they are usually 10x or more (potentially hundreds of times for GPU backend) slower than an optimized native (c++) implementation with GPU/AVX etc support.

**Comment by Charele** [comment]
@AlexDBlack 
Yes, BooleanIndexing is powerful!

But I supplement two point
1> Add this function to INDArray self, can implement "functional program", 
ind1.map(func1).map(func2)...

2> BooleanIndexing use Google Function, 
if use Java8 Function, we can use Lambda, I think it's very convenient for coder :-)

ind1.map(x -> 2 * x)
