### ISSUE TITLE
Dead link on GitHub repo page

### ISSUE THREAD

**Issue by Haugum** [deeplearning4j/deeplearning4j#6376]
On the page for the repository, https://github.com/deeplearning4j/deeplearning4j, at the bottom there is a link for tutorials, which is currently dead and produces a 404 error:

https://github.com/deeplearning4j/deeplearning4j/tree/master/deeplearning4j/dl4j-examples/tutorials

**Comment by Charele** [comment]
Yes, you are right:-)

**Comment by AlexDBlack** [comment]
Thanks, fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/6381
