### ISSUE TITLE
MMulTranspose not working correctly

### ISSUE THREAD

**Issue by RSBat** [deeplearning4j/deeplearning4j#6378]
`mmul ` with MMulTranspose argument gives wrong result if `transposeResult` is set to `true`
I think the problem is here (this block looks strange anyways):
https://github.com/deeplearning4j/deeplearning4j/blob/1c0fda4ceaf7ed9c1d174bb111779fcb1692ee33/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/blas/params/MMulTranspose.java#L53-L64

EDIT: I also noticed that there is extra output in `mmul` function: https://github.com/deeplearning4j/deeplearning4j/blob/1c0fda4ceaf7ed9c1d174bb111779fcb1692ee33/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L3418-L3419

I think I can make a pull request with fix if you want

**Comment by Charele** [comment]
Hi,I take a test, but My result is good, so it has no problem.
code:
  val mmt1 = MMulTranspose.builder().transposeResult(true).build()
  val op1 = new Mmul(x1, x2, x3, mmt1)
  Nd4j.getExecutioner().exec(op1)
  println(x3)
  println(x1.mmul(x2).transpose())

  println("\nNext is not same:")  
  println(x1.mmul(x2))

result:
[[    5.0000,    4.0000,   -4.0000], 
 [  -14.0000,  -18.0000,  -33.0000], 
 [    8.0000,   17.0000,   15.0000]]
[[    5.0000,    4.0000,   -4.0000], 
 [  -14.0000,  -18.0000,  -33.0000], 
 [    8.0000,   17.0000,   15.0000]]

Next is not same:
[[    5.0000,  -14.0000,    8.0000], 
 [    4.0000,  -18.0000,   17.0000], 
 [   -4.0000,  -33.0000,   15.0000]]

**Comment by Charele** [comment]
Hmm, I think the mistake is in mmul() implement method of BaseNDArray.java
(MMulTranspose.java is good),

the detail:
@Override
    public INDArray mmul(INDArray other, MMulTranspose mMulTranspose) {
        MMulTranspose mMulTranspose1 = MMulTranspose.builder()
                .a(this)
                .b(other)
                .transposeA(mMulTranspose.isTransposeA())
                .transposeB(mMulTranspose.isTransposeB())
                .transposeResult(mMulTranspose.isTransposeResult())
                .build();
        System.out.println(mMulTranspose1.getA()); // why println here? typo ?
        System.out.println(mMulTranspose1.getB());
        return mMulTranspose1.getA().mmul(mMulTranspose1.getB());
    }

When it return result, it don't consider "isTransposeResult", so the you get the bad result,
It should be fix like here:

    public INDArray mmul(INDArray other, MMulTranspose mMulTranspose) {
        MMulTranspose mMulTranspose1 = MMulTranspose.builder()
                .a(this)
                .b(other)
                .transposeA(mMulTranspose.isTransposeA())
                .transposeB(mMulTranspose.isTransposeB())
                .transposeResult(mMulTranspose.isTransposeResult())
                .build();       
        
        INDArray ret = 
        		mMulTranspose1.getA().mmul(mMulTranspose1.getB());
        
        return mMulTranspose1.isTransposeResult() ? ret.transpose() : ret;
    }

**Comment by saudet** [comment]
@Charele Good catch, please send a pull request!

**Comment by RSBat** [comment]
@saudet did you look at the code I highlighted?
Here's what is wrong: `this.transposeA` is set to some value, then this value is overwritten inside `if`, then this value is overwritten again outside `if` making that `if` almost useless. That is definitely not the way code should be written

**Comment by saudet** [comment]
@RSBat No, I didn't write that code. If you have a suggestion though, please do send it as a pull request yes. It will make it easier to have it reviewed by the right person.

**Comment by saudet** [comment]
@agibsonccc @maxpumperla Could you take a look at this?

**Comment by maxpumperla** [comment]
alright, I'll have a look. thanks
