### ISSUE TITLE
Problem with input data

### ISSUE THREAD

**Issue by jakonn** [deeplearning4j/deeplearning4j#638]
I need to put data into https://gist.github.com/jakonn/258fed6f8fe46e463d67 ... 
That data are time series (stock values) , 12 features each row ... The problem is that i am unable to set properly my data because i don't know how lables works here.

sample of my data 
2247.23,2247.23,2182.34,2185.83,-0.28,4137278,58.5,58.93,58.05,58.35,0.1738545
2249.27,2257.91,2228.47,2249.67,0.02061391,58.25,58.87,57.67,58.25,0.0024093
2282.98,2288.47,2244.3,2244.63,-0.18,626331,58.79,59.63,57.58,58.25,-0.92,77282
2300.1,2303.66,2281.13,2285.03,-0.06,4116069,59,59.48,58.22,58.79,-0.36,90533
2264.61,2298.54,2259.34,2298.54,0.18,988114,59.1,59.59,58.83,59,0.85,77827
2262.78,2264.17,2240.78,2257.62,-0.01748051,59.5,60.09,58.2,58.5,-1.68,60803
2269.4,2270.06,2247.96,2259.98,-0.04951920,59.5,60.38,58.54,59.5,0.7102099
2275.22,2289.16,2263.44,2269,-0.01,2731410,59.98,60,59.08,59.08,-1.48,53276
2244.68,2279.19,2240.97,2270.84,0.18,2890592,59.89,60.5,59.18,59.97.03,237053

That is each row for each day. There are no labels, because i don't know how can i use it for my example. I have stock values and i need to get fot example close stock value for end. I don't know what value I should set on label or what should it be. There is no examplehow to put data with iterator from file too for such floats data and use it in DBN for example or enything else.

**Comment by agibsonccc** [comment]
Adapt this. Notice you specify the attribute label index. https://github.com/deeplearning4j/dl4j-0.4-examples/blob/master/src/main/java/org/deeplearning4j/examples/csv/CSVExample.java

**Comment by jakonn** [comment]
dont u think that it is still for classification. I mean even i add my own labels etc it will be still lables and classification how change classification to regression. Only by changing last layer ouput to linear regression?
