### ISSUE TITLE
Libnd4j: add way to disable MKL-DNN

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6384]
We now have MKL-DNN thanks to @saudet :tada:

However, MKL-DNN is hardcoded as enabled:
https://github.com/deeplearning4j/deeplearning4j/blob/master/libnd4j/include/graph/ContextPrototype.h#L43

It would be useful (mainly for testing/debugging purposes) to be able to disable it, ideally at runtime (or at least enable/disable on initialization).

**Comment by raver119** [comment]
Related: #6337
