### ISSUE TITLE
IllegalArgumentException: Invalid size: cannot get size of dimension

### ISSUE THREAD

**Issue by Tshimanga** [deeplearning4j/deeplearning4j#6399]
I've successfully loaded the following biLSTM Keras model into DL4J:

```
model = Sequential()
model.add(Bidirectional(LSTM(50, return_sequences=True), merge_mode='concat', input_shape=(None, 100)))
model.add(Bidirectional(LSTM(50, return_sequences=True), merge_mode='concat'))
model.add(Bidirectional(LSTM(1, return_sequences=True, activation='sigmoid'), merge_mode='mul'))  #this is to work around lack of TimeDistributed wrapper support in DL4J
model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['acc'])
```

But in a unit test I'm failing to get a prediction out of the model. The following error is being thrown:

```
java.lang.IllegalArgumentException: Invalid size: cannot get size of dimension 2 for rank 2 NDArray (array shape: [5,100])
    
        at org.nd4j.linalg.api.ndarray.BaseNDArray.size(BaseNDArray.java:5247)
```

When trying to produce an output from the following steps:
```
String SENTENCE = "This is a sentence.";
double[][] array = replaceTokensWithVectorEmbeddings(SENTENCE);
INDArray indArray = Nd4j.create(array);

return model.output(indArray);
```

What am I doing wrong? Help appreciated 👋

**Comment by AlexDBlack** [comment]
@Tshimanga So the first thing: you're feeding a 2d NDArray into a RNN model. DL4J uses 3d NDArrays for RNNs.
https://deeplearning4j.org/docs/latest/deeplearning4j-nn-recurrent

Probably the simplest way is just to add a ```.reshape(1, arrays.length, array[0].length)``` (though it's not clear to me which way you've got the double[][] data formatted)

Also, though it's probably not relevant now given the issue above - we need full stack traces when debugging. We can't tell much from just those 2 lines.

**Comment by Tshimanga** [comment]
Ah I see. So basically batchsize is hardcoded in the implementation. No worries then
