### ISSUE TITLE
Some issues with autoencoder docs relative to 0.4-rc0

### ISSUE THREAD

**Issue by sanity** [deeplearning4j/deeplearning4j#640]
Trying the code sample here: http://deeplearning4j.org/deepautoencoder.html

A few issues:

Variables batchSize, numSamples, seed, and iterations are undefined before being used.

`                .updater(Updater.ADAGRAD)`

Cannot resolve symbol ADAGRAD

`                .weightInit(WeightInit.DISTRIBUTION).dist(new NormalDistribution(0,0.01))`

Cannot resolve method weightInit()

**Comment by sanity** [comment]
visibleUnit() also doesn't seem to be defined on NeuralNetConfiguration

**Comment by agibsonccc** [comment]
As I mentioned in the other one, please import the updated examples to mess
around.

Thanks!

https://github.com/deeplearning4j/dl4j-0.4-examples
ᐧ
