### ISSUE TITLE
ND4j: transposei is not inplace

### ISSUE THREAD

**Issue by Xfel** [deeplearning4j/deeplearning4j#6401]
This is documented in [NDArrayBase](https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L4490), but very counterintuitive. 

The transpose method is implemented using `permute`, and the inplace variant `permutei` seems to be working just fine.

**Comment by raver119** [comment]
Hm, i vaguelly recall there was a reason for that but can't recally why. In c++ we definitely have inplace transpose permit.

So we should update java too. But that'll require check of existing usage of this method

**Comment by AlexDBlack** [comment]
It was in-place at one point.
Looks like switching from permute to permutei (and copying current permutei to permute op) seems like it would work - i.e., I'm not seeing a reason why we can't have in-place transpose if we have in-place permute.
