### ISSUE TITLE
Get rid of string use of for validation

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#6405]
Some ops use shape -> string conversion for equality checks. This should be fixed/removed after additional datatypes pr merged.

**Comment by AlexDBlack** [comment]
For reference/comparison, on the java side we have this: https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-common/src/main/java/org/nd4j/base/Preconditions.java

The motivation is the same - 1 line checks, but no object creation (in most cases) unless the condition actually fails - i.e., error message formatting is only when required.

**Comment by shyrma** [comment]
Done
