### ISSUE TITLE
 Issue with training SparkComputationGraph with newer versions of Spark?

### ISSUE THREAD

**Issue by sandgrules** [deeplearning4j/deeplearning4j#6407]
#### Issue Description

This is an issue I see when trying to train a SparkComputationGraph by performing model.fitMultiDataSet on an RDD of MultiDataSets (first with org.nd4j.linalg.dataset.MultiDataSet, but then when that didn't work, casting them as org.nd4j.linalg.dataset.api.MultiDataSet): 
...
18/09/07 11:52:45 INFO Executor: Running task 1.0 in stage 5.0 (TID 44)
18/09/07 11:52:45 INFO ShuffleBlockFetcherIterator: Getting 0 non-empty blocks out of 8 blocks
18/09/07 11:52:45 INFO ShuffleBlockFetcherIterator: Getting 0 non-empty blocks out of 8 blocks
18/09/07 11:52:45 INFO ShuffleBlockFetcherIterator: Getting 1 non-empty blocks out of 8 blocks
18/09/07 11:52:45 INFO ShuffleBlockFetcherIterator: Getting 0 non-empty blocks out of 8 blocks
18/09/07 11:52:45 INFO ShuffleBlockFetcherIterator: Getting 5 non-empty blocks out of 8 blocks
18/09/07 11:52:45 INFO ShuffleBlockFetcherIterator: Getting 0 non-empty blocks out of 8 blocks
18/09/07 11:52:45 INFO ShuffleBlockFetcherIterator: Getting 0 non-empty blocks out of 8 blocks
18/09/07 11:52:45 INFO ShuffleBlockFetcherIterator: Getting 3 non-empty blocks out of 8 blocks
18/09/07 11:52:45 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 16 ms
18/09/07 11:52:45 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 16 ms
18/09/07 11:52:45 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 17 ms
18/09/07 11:52:45 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 9 ms
18/09/07 11:52:45 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 14 ms
18/09/07 11:52:45 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 19 ms
18/09/07 11:52:45 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 19 ms
18/09/07 11:52:45 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 18 ms
18/09/07 11:52:45 ERROR Executor: Exception in task 5.0 in stage 5.0 (TID 41)
java.lang.AbstractMethodError: org.deeplearning4j.spark.api.worker.ExecuteWorkerPathMDSFlatMap.call(Ljava/lang/Object;)Ljava/util/Iterator;

#### Version Information
I see this error when running:
* Deeplearning4j version  1.0.0-beta2
* Ubuntu 18.04
* CPU backend
* Spark v 2.3.1
* Scala v 2.11.12

If I march the spark version back to 1.6.x and Scala v back to 10.5 this error goes away, and the model trains fine. If someone suspects this may be just a case of user error, please let me know...

**Comment by AlexDBlack** [comment]
This sort of error is usually due to mixed spark versions.
How exactly are you running this? Locally in an IDE? Locally via maven shade? On a cluster via spark submit?

A copy of your pom.xml (in a gist or similar - https://gist.github.com/) - or the output of "mvn dependency:tree" would help diagnose this.

**Comment by sandgrules** [comment]
@AlexDBlack :+1: 
I found my issue - I had misunderstood the difference of the 1.0.0-beta2_spark_1/2 split (though it probably should have been obvious). Thanks for the tip!
