### ISSUE TITLE
DeepWalk - struggling to match the results of the reference implementation

### ISSUE THREAD

**Issue by mneedham** [deeplearning4j/deeplearning4j#6410]
Hi,

My question is a bit general but maybe somebody can guide me in the right direction as to how to debug it. I'm trying to reproduce the results from the reference implementation of the DeepWalk algorithm (https://github.com/phanein/deepwalk) with the Dl4j implementation (https://github.com/neo4j-graph-analytics/ml-models/blob/deepwalk/src/main/java/embedding/DeepWalkProc.java#L260).

(using all the same parameters as they do...)

With the reference one it's taking ~ 25 minutes to train but I'm getting f1 scores of:
Micro - 0.4296
Macro - 0.2916

With the dl4j it's taking 3-4 minutes to train with f1 scores of:
Micro - 0.1678
Macro - 0.027

This is on a multi label classification problem. Presumably I'm doing something stupid but I'm not sure how to narrow down what it is so any pointers would be great.

Thanks!

Aha! Link: https://skymindai.aha.io/features/DL4J-65

**Comment by jexp** [comment]
Ping @AlexDBlack any update on this?

**Comment by simonmekit** [comment]
@AlexDBlack
