### ISSUE TITLE
RELU_layer threshold configuration

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#6411]
At this moment relu_layer op doesn't allow threshold configuration, and legacy RELU op allows that.
We should add configuration option to relu_layer.

**Comment by avinningo** [comment]
Hi I am new to open source, I was wondering if I could pick up this issue

**Comment by saudet** [comment]
Please go ahead @avinningo. Start by sending a pull request starting with "[WIP]" in its name so @raver119 can review it more easily as you write it. Thanks!

**Comment by avinningo** [comment]
Yes sure

**Comment by shap3e** [comment]
Welcome all

**Comment by jaythedon** [comment]
Is this issue still opened?

**Comment by agibsonccc** [comment]
@jaythedon  I'm closing this. This issue is a few years old and out of date. Open a new issue if you have a specific request.
