### ISSUE TITLE
libnd4j: mkl-dnn - handle non-standard strides case

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6419]
This PR only allows mkl-dnn to execute on arrays with 'standard' c-order strides for weights/input etc.
https://github.com/deeplearning4j/deeplearning4j/pull/6412

(The weight layout issue was a blocker for me hence I opted to get this merged rather than waiting for a fix for mkl-dnn to fully support the other layouts)

mkl-dnn seems to support arbitrary strides when configured properly - we just need to add (and test) that.

**Comment by saudet** [comment]
@shyrma Right, ok, but what is failing exactly? Did you add a new unit test that isn't working?

**Comment by shyrma** [comment]
Hi, Sam

Failing tests are:
1) 
https://github.com/deeplearning4j/deeplearning4j/blob/45c84e1a04ae3f1a525eba24fb3e8cb17ec66faf/libnd4j/tests_cpu/layers_tests/ConvolutionTests.cpp#L1312
2) https://github.com/deeplearning4j/deeplearning4j/blob/45c84e1a04ae3f1a525eba24fb3e8cb17ec66faf/libnd4j/tests_cpu/layers_tests/ConvolutionTests.cpp#L51
3) https://github.com/deeplearning4j/deeplearning4j/blob/45c84e1a04ae3f1a525eba24fb3e8cb17ec66faf/libnd4j/tests_cpu/layers_tests/ConvolutionTests.cpp#L468

as you may note all of them use permuted weights
