### ISSUE TITLE
Add efficient forward pass for RNNs

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#642]
Basic problem: Suppose I want to use an already-trained RNN for prediction (forward pass). Further, suppose I need predictions one (or a few) steps at a time (i.e., I need output predictions before I have the full time series)
- At present: Can’t do this. Need to do full forward pass every time, from t=0.
- Worst case: I want to get the next time step only. For example I want to predict the next character in a document, sample from that prediction, and feed the sample back into the input to generate another sample. Having to do full forward pass from the beginning (maybe hundreds or thousands of steps) just to get a single output is impractical.

**Proposed design**: allow users to do one (or more) time steps from a RNN using stored previous state, including with mini-batches.
RNN state is stored as a map: need for example both previous output activations and previous memory state in GravesLSTM. If no previous RNN state exists: initialize with zeros, as before. State at last time step is automatically stored for later use.

**MultiLayerNetwork**
Methods: (all prefixed by 'rnn' to emphasize use with RNNs only)
- ```INDArray rnnTimeStep(INDArray input)```
  - Input: 2d (single time step) OR 3d (multiple time steps). Shape [miniBatchSize,nIn] or [miniBatchSize,nIn,numTimeSteps]
  - Output: final activations. Same as input. So 2d out if 2d in, 3d out if 3d in.
- ```void rnnResetState()```: resets state of all rnn layers (if any)
- ```Map<String,INDArray> rnnGetPreviousState( int layer )```
- ```void rnnSetPreviousState( int layer, Map<String,INDArary> state )```
- ```void rnnCleanPreviousState()```

**RNN layers**
- Current feed forward methods (used in training, etc) are unchanged
- Introduce BaseRnnLayer (extends BaseLayer)
  - all RNN layers (GravesLSTM, GRU) extend this
  - add get/set/clear previous state methods as with MultiLayerNetwork
  - add ```Map<String,INDArray> stateMap``` field (stores previous time step activations etc)
  - add ```rnnTimeStep(INDArray prevLayerActivations)``` - basically same as feed forward methods but use stored state instead of zero initialization for previous RNN state/activations
- GravesLSTM and GRU: add public static final String keys for state

**Comment by drlebedev** [comment]
Hey Alex. I really like the approach  you proposed. The only problem I see in stateful  layers is a memory footprint. Proposed architecture would be really ineffective memory-wise in case of long time-series. The worst case would be indefinite stream of data (e.g. temperature from sensor). Would you consider to add layer config param that would limit the number of time steps RNN layer would remember. This would naturally lead to truncated BPTT implementation.  

I think something like this:
```{java}
  .stepsToRemember(int n)
```
in a RNN layer builder would be really helpful. Also we can consider -1 as indefinite and would have regular BPTT in that case.

Also it is not clear how this would work with non-RNN layers? Could for example output from RNN layer be send to RBM layer for dimension reduction? It would be really good if rnnTimeStep activation would activate non-RNN layers properly.

The final nice to have feature is to be able to get RNN activations (state) together with params in one call in MultilayerNetwork (like we have for params right now). This feature would help a lot for state transfer/persist in multinode environment (e.g. Spark).

**Comment by AlexDBlack** [comment]
So the layer only needs to remember activations for a single time step. This is what I've implemented.
Note that this issue discusses forward pass only at test time; forward pass methods used during training training are (functionally) unchanged.
This will also work with non-RNN layers. Non-RNN layers don't have state so the standard feed-forward/activate methods are used there.
Truncated BPTT could certainly make use of the forward pass modifications implemented for this feature, but I'm considering that a separate feature.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/658
