### ISSUE TITLE
Libnd4j: Update deconv2d_tf to single weight format

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6421]
Looks like this one needs to be updated also:
https://github.com/deeplearning4j/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/convo/deconv2d_tf.cpp

TF uses ```[height, width, output_channels, in_channels]``` always for the weights.

**Comment by shyrma** [comment]
Done
