### ISSUE TITLE
DL4J: SimpleRnnParamInitializer does not respect biasInit configuration

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#6431]
Let's see the init() method of SimpleRnnParamInitializer:

... ...
INDArray rw = WeightInitUtil.initWeights(nOut, nOut, new long[]{nOut, nOut}, rwInit, rwDist, 'f', m.get(RECURRENT_WEIGHT_KEY));
            m.put(RECURRENT_WEIGHT_KEY, rw);
        } else {
            m = getSubsets(paramsView, nIn, nOut, true);
        }

        conf.addVariable(WEIGHT_KEY);
        conf.addVariable(RECURRENT_WEIGHT_KEY);
        conf.addVariable(BIAS_KEY);

        return m;
    }

It initialize the "W" and "RW",  forget the init of parameter "b"(will keep default 0)
It's a lost? or bias 0 value is helpful for RNN?

**Comment by AlexDBlack** [comment]
Thanks for reporting. Looks like yes, SimpleRNN does dave a biasInit config option but it doesn't use that in the weight initializer.
