### ISSUE TITLE
ND4J: array creation methods should validate array order arg

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#6442]
We know we have a order option('f','c') when operating INDArray, it's related with internal storage.
I find I can use any char,,,
  val shape = Array(5, 3)
  val a1 = Nd4j.rand('c', shape)
  val a2 = Nd4j.rand('f', shape)
  val a3 = Nd4j.rand('x', shape)
  
  println(a1.shapeInfoToString())
  println(a2.shapeInfoToString())
  println(a3.shapeInfoToString())

Rank: 2,Offset: 0
 Order: c Shape: [5,3],  stride: [3,1]
Rank: 2,Offset: 0
 Order: f Shape: [5,3],  stride: [1,5]
Rank: 2,Offset: 0
 Order: x Shape: [5,3],  stride: [3,1]

I'm so chaotic until I see it:
public static int[] getStrides(int[] shape, char order) {
        if (order == NDArrayFactory.FORTRAN)
            return ArrayUtil.calcStridesFortran(shape);
        return ArrayUtil.calcStrides(shape);
    }

My question is, why don't restrict the character in API?

PS: I see some code in Shape.java
...
} else if (order == 'a') {
            return true;
        } else {
            throw new RuntimeException("Invalid order: not c or f (is: " + order + ")");
        }
Is the 'a' another special option?

**Comment by AlexDBlack** [comment]
So it's just a lack of validation then. The only valid values for that method (and those like it) is 'c' or 'f'.
Feel free to send us a pull request to add that validation.

**Comment by Charele** [comment]
Hi Alex, You mean I send this topic to "Pull Request" box again?

I have another doubt(only my doubt,not bug/error), In LSTMHelpers.java, activateHelper() method

![qq](https://user-images.githubusercontent.com/42658390/45547938-180c7280-b855-11e8-90c4-11f594b97ff5.png)

Is the "training" necessary?
My understand, when "forBackprop" is true, I think "training" must be true,is it?

**Comment by AlexDBlack** [comment]
> Hi Alex, You mean I send this topic to "Pull Request" box again?

No, I mean you can - if you want - implement a fix and submit it via a pull requests: https://help.github.com/articles/about-pull-requests/

> My understand, when "forBackprop" is true, I think "training" must be true,is it?

Backprop == true implies training == true, yes. It's not a big deal, but it could be cleaned up.
FYI The converse doesn't always hold though: i.e., training==true but backprop == false - the API allows for 'train' flag to be set to true outside of training. That can be useful in some cases.

**Comment by Charele** [comment]
THANKS:-O
