### ISSUE TITLE
The images are missing on the nd4j-overview page

### ISSUE THREAD

**Issue by satheeshakkinepally** [deeplearning4j/deeplearning4j#6445]
https://deeplearning4j.org/docs/latest/nd4j-overview
For instance, in the section NDArrays: How Are They Stored in Memory? the image C vs F. Order is missing. And here is the link to the image that gives 404
https://deeplearning4j.org/images/guide/c_vs_f_order.png

Likewise, several other images are missing on that page

Thank You so much for the awesome library you guys built. Its amazing

**Comment by treo** [comment]
There is an issue on the docs repository that tracks this:
https://github.com/deeplearning4j/deeplearning4j-docs/issues/129

Thanks for reporting that we didn't catch all of it.
