### ISSUE TITLE
I have multiple gpu, how to specify only one gpu for example setGPU(1), the index 1 gpu?

### ISSUE THREAD

**Issue by whaozl** [deeplearning4j/deeplearning4j#6446]

**Comment by raver119** [comment]
Best way - use CUDA environment variable. CUDA_VISIBLE_DEVICES

**Comment by raver119** [comment]
Other way - CudaEnvironment configuration bean

**Comment by whaozl** [comment]
@raver119 
```java
        CudaEnvironment.getInstance().getConfiguration.allowMultiGPU(false)
         .setMaximumDeviceCacheableLength(1024 * 1024 * 1024L)
        .setMaximumDeviceCache(3L * 1024 * 1024 * 1024L)
        .setMaximumHostCacheableLength(1024 * 1024 * 1024L)
        .setMaximumHostCache(3L * 1024 * 1024 * 1024L);
```
I loaded the keras model through dl4j.
How do I let dl4j dynamically allocate memory on demand?

this can set CUDA_VISIBLE_DEVICES by CudaEnvironment? How? Thank you.

**Comment by raver119** [comment]
Generally speaking you don’t need to touch that bean at all. Memory will be allocated anyway.

All you need is to set environment variable I’ve mentioned above
