### ISSUE TITLE
libnd4j: depthwise_conv2d op bug

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6448]
I'm seeing failures on TF import for this op. But here's a simple stand-alone test case that shows the op must be incorrect:

```
    @Test
    public void testDepthwiseConv(){
        INDArray inNHWC = Nd4j.linspace(1,3*3*2, 3*3*2).reshape('c', 1,3,3,2);  //NHWC
        INDArray w = Nd4j.ones(2,2,2,1);    //[kH,kW,cIn,depthMultiplier]
        //No bias

        INDArray out = Nd4j.create(1,3,3,2);

        DynamicCustomOp op = DynamicCustomOp.builder("depthwise_conv2d")
                .addInputs(inNHWC, w)
                .addOutputs(out)
                .addIntegerArguments(
                        2,2,  //Kernel
                        1,1,  //Stride
                        0,0,  //Padding
                        1,1,  //Dilation
                        1,      //Same
                        1       //1=NHWC
                ).build();

        Nd4j.getExecutioner().exec(op);
        System.out.println(out);
    }
```

Output:
```
[[[[   20.0000,   24.0000], 
   [   32.0000,   18.0000], 
   [   48.0000,   56.0000]], 

  [[   30.0000,   30.0000], 
   [   34.0000,   18.0000], 
   [         0,         0]], 

  [[         0,         0], 
   [         0,         0], 
   [         0,         0]]]]
```

Note that with positive weights, and positive input (all > 0 for both arrays) it is not possible to get value of 0 in the output.

I can calculate and provide expected results if required.

**Comment by Charele** [comment]
Hi, Mr Alex,what's the libnd4j?
I know Nd4j,but where I find libnd4j?

**Comment by AlexDBlack** [comment]
@Charele From now on, please ask general questions like in the gitter channel, not on issues, unless it directly pertains to the issue itself.
Libnd4j is in the repository with everything else, i.e., here: https://github.com/deeplearning4j/deeplearning4j/tree/master/libnd4j - it's the c++ code that underlies ND4J and by extension DL4J

**Comment by AlexDBlack** [comment]
@shyrma Thanks! I can confirm that I'm getting sensible results for that test now 👍
