### ISSUE TITLE
Code snippets in documentation don't compile against 0.4-rc0

### ISSUE THREAD

**Issue by sanity** [deeplearning4j/deeplearning4j#646]
Many code samples don't compile against the current version of deplearning4j.  This is unfortunate as it is a real disincentive for new users to get started with the library.

For example, the code sample on this page: http://deeplearning4j.org/restrictedboltzmannmachine.html

A few issues:

* new RBM.Builder(HiddenUnit.RECTIFIED, VisibleUnit.GAUSSIAN, 1) constructor doesn't exist
* .weightInit() doesn't exist
* .dist() doesn't exist
* lossFunction() doesn't exist
* The import for Layer is ambiguous, needs to be found by trial and error (one of them doesn't have a .setListeners() method)

Then, when I've muddled through to try to get it to work, here is the output: https://gist.github.com/sanity/fa073128fa7ad802fcbb

As a newbie this is really discouraging when trying to get started with a complex new library :/

**Comment by agibsonccc** [comment]
Sorry we are in the middle of a release. Please get on gitter.

Also, please just import the examples:
https://github.com/deeplearning4j/dl4j-0.4-examples

Happy to help:

https://gitter.im/deeplearning4j/deeplearning4j
ᐧ
