### ISSUE TITLE
libnd4j: avgpool2d op incorrect values - 3x3 kernel + same mode

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6462]
I've got a ton of tests passing for average pooling 2d (most 2x2) but this is one pulled from a TF import test that is failing.

(Do double check the args in the test below, but I'm pretty sure they are correct).

I've also implemented manual calculation for avg pool 2d op, the results of which matches the TF expected values exactly.

Of note: some values are passing, others differ by a multiple of 1.3333 exactly (see image below code - i.e., tfValue / libnd4jValue = 1.3333). So my guess is that this is due to an issue with the divisor value for "exclude padding from count" mode.

Test data used in the issue:
[test_data.zip](https://github.com/deeplearning4j/deeplearning4j/files/2395665/test_data.zip)

Code to reproduce: https://gist.github.com/AlexDBlack/66c8166ff7b128e5efbaeb5c0d8fd85f

**Comment by AlexDBlack** [comment]
On a clean (master) build on Linux: I'm getting the exact same failure as on Windows... so it doesn't look to be OS-specific.
However, it's odd that @shyrma is unable to reproduce this when executed with what should be an identical test in c++.

**Comment by AlexDBlack** [comment]
Must have been fixed at some point - test in confirmed passing now.

**Comment by saudet** [comment]
Maybe that's MKL-DNN?

**Comment by AlexDBlack** [comment]
@saudet Good catch, I didn't think of that.
Passes with MKL-DNN, fails when it's disabled. I've edited the original issue code for this.

**Comment by raver119** [comment]
Fixed some time ago
