### ISSUE TITLE
Libnd4j graph execution failing tests

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6465]
These were disabled a while ago (when we wanted to get an "all passing baseline") and then forgotten about.

They all pass for SameDiff execution, but not libnd4j execution

https://github.com/deeplearning4j/deeplearning4j/blob/2c32b5ca8b9f6189a07faabd2c7da0f19510675c/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/imports/TFGraphs/TFGraphTestAllLibnd4j.java#L70-L94

**Comment by AlexDBlack** [comment]
See also: https://github.com/deeplearning4j/deeplearning4j/issues/6223

**Comment by AlexDBlack** [comment]
I suspect I'm running into the reductions cases in FB import.
As far as I can tell, the problem with reductions is that the flatbuffers export (and hence libnd4j execution) doesn't have a concept of the keepDims and newFormat args. These 2 args don't impact the shape/length of the buffer, but do impact the shape of the arrays (i.e., there's some extra 1s in the shape).

**Comment by raver119** [comment]
Ye, it's a known bug and is a wip.

**Comment by AlexDBlack** [comment]
Closing this - the majority are now fixed, rest are being worked on.
https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/imports/TFGraphs/TFGraphTestAllLibnd4j.java#L70-L94
