### ISSUE TITLE
VocabConstructor not limiting size of VocabCache

### ISSUE THREAD

**Issue by Valuimnee** [deeplearning4j/deeplearning4j#6468]
org.deeplearning4j.models.word2vec.wordstore.VocabConstructor
version 1.0.0-beta2

public VocabCache<T> buildJointVocabulary(boolean resetCounters, boolean buildHuffmanTree) {
...

    if (buildHuffmanTree) {
            if (limit > 0) {
                // we want to sort labels before truncating them, so we'll keep most important words
                val words = new ArrayList<T>(cache.vocabWords());
                Collections.sort(words);

                // now rolling through them
                for (val element : words) {
                    if (element.getIndex() > limit && !element.isSpecial() && !element.isLabel())
                        cache.removeElement(element.getLabel());
                }
            }

            // and now we're building Huffman tree
            val huffman = new Huffman(cache.vocabWords());
            huffman.build();
            huffman.applyIndexes(cache);
        }
...
}

As one can see, first cache (variable words ) is filtered, at this time all indexes set to default value -1, so none of the words is removed. 
Only then, in method

    huffman.applyIndexes(cache);

indexes is initialized.

Can anyone just switch places of these two blocks of code to get it work?

Or does anyone know other methods to limit vocabulary size. Any ideas of how to limit vocabulary size for Word2Vec would be appreciable.

**Comment by TheKingDiamond** [comment]
Thanks for raising this issue, it's something that I noticed a while back and mentioned here https://github.com/deeplearning4j/deeplearning4j/issues/5710. @raver119

**Comment by raver119** [comment]
fixed, will be merged later
