### ISSUE TITLE
My think of computeGradientAndScore()

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#6471]
In computeGradientAndScore() meth of MultiLayerNetwork,

public void computeGradientAndScore() {
   ...
   many codes include calc ForwardPass
   ...
   //Calculate score
   if (!(getOutputLayer() instanceof IOutputLayer)) {
      throw new DL4JException("Cannot calculate gradient and score with respect to labels: final layer is not an IOutputLayer");
    }
   ...
}

Here it throw exception if the last layer is not a IOutputLayer class,it means that all pre-step(include calc ForwardPass) will be invalid.
My question, why don't place this "if() {throw...}" to begin of this methon?

**Comment by AlexDBlack** [comment]
Sure, it's not a big deal, but it would be better to throw that exception earlier in the method.

**Comment by AlexDBlack** [comment]
Was fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/6470
