### ISSUE TITLE
Do dl4j-examples have version for 0.7.2 sdk 

### ISSUE THREAD

**Issue by aabbcc23** [deeplearning4j/deeplearning4j#6473]
up

**Comment by agibsonccc** [comment]
We do not support old versions.

**Comment by aabbcc23** [comment]
but new version examples lot bugs

**Comment by agibsonccc** [comment]
Sorry your response here is plain spam. We are not supporting a 1.5 year old version of the software. Frankly, you're whining and on top of that you're not even describing what "bugs" you have. 
We are not in any shape or form going to humor this request. I am locking further comments.
If you want to give us *concrete* problems we are happy to look at them.
