### ISSUE TITLE
Nd4J: add INDArray.isInfinite(), INDArray.isNaN() etc for boolean masks

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6475]
We have INDArray.gt(Number), .lte(Number) etc. But nothing for NaN/Infinite.
Perhaps a general INDArray.matches(Condition) method would de useful too?

**Comment by raver119** [comment]
We have c++ ops for that, in both legacy and new ops. IsInf, IsNan, IsFinite.

**Comment by AlexDBlack** [comment]
Right, it's just convenience methods we need.
I don't think we have anything easier for users than this:
```
Nd4j.getExecutioner().execAndReturn(new MatchConditionTransform(arr, Conditions.isNan()));
```

**Comment by AlexDBlack** [comment]
Was added here: https://github.com/deeplearning4j/deeplearning4j/pull/6858
