### ISSUE TITLE
Nd4j vstack with single col in rank 2 matrix mixes views on buffer(s) when using CUDA

### ISSUE THREAD

**Issue by sascha08-15** [deeplearning4j/deeplearning4j#6479]
When I try to vstack 3 matrixes
[[1], [1]]
[[0]]
and 
[[3], [3]]

I am receiving [[1],[1],[0],[0],[3]] as result. In a larger context, the 2nd matrix seems to override parts of the resulting matrix (just outside observation, did not debug into Nd4j internals)

The following snippet provides a unit test for the problem.
https://gist.github.com/sascha08-15/e1f1eedad55cc1b8bff5b58ba1f1c963

**Comment by sascha08-15** [comment]
Applies for both, 1.0.0-beta2 and 1.0.0-SNAPSHOT

**Comment by sascha08-15** [comment]
Seems to be a problem that just occurs with the GPU backend.
Running on Windows 10 with a GT 730 to develop with Java 10, tried Java 8 as well.
Problem also occurs on a 1050 GTX, Win 10, Java 8.

**Comment by treo** [comment]
Can confirm that it happens on my system as well.

CPU version works fine. CUDA version seems to be bugged.
/cc @raver119

**Comment by sascha08-15** [comment]
Seems not to be a driver issue. Happens for Nvidia driver version is 399.24 and 411.63 (latest as of Sept. 24, '18) possibly others.

**Comment by sascha08-15** [comment]
Any ETA for that bug to be fixed?

**Comment by sascha08-15** [comment]
Can confirm the bug with Unix (Ubuntu 18.04) and Cuda 10.0 on RTX 2080ti

**Comment by AlexDBlack** [comment]
Looks like this one got missed/forgotten. We should fix this as part of our current QA efforts.

There's actually 2 bugs here:
First, the vstack wrong results (reproducible in test below).
Second: the lack of rank validation (change *second* to shape [1] and it doesn't complain about mismatched rank; it should IMO).


```
    @Test
    public void testVstack(){
        INDArray first = Nd4j.zeros(DataType.DOUBLE, new long[]{2,1});
        INDArray second = Nd4j.ones(DataType.DOUBLE, new long[]{1,1});
        INDArray third = Nd4j.valueArrayOf(new long[]{2,1}, 2, DataType.DOUBLE);

        INDArray expected = Nd4j.createFromArray(new double[][]{{0},{0},{1},{2},{2}});

        INDArray out = Nd4j.vstack(first, second, third);

        System.out.println(out);
        assertEquals(expected, out);
    }
```

![image](https://user-images.githubusercontent.com/2360237/55923449-f6d3ff00-5c48-11e9-9497-e1a495b5f479.png)

**Comment by sascha08-15** [comment]
@AlexDBlack true, I guess the 2nd scenario you described is then showing as `java.lang.RuntimeException:` `cudaEventSynchronize(...)` failed see https://github.com/deeplearning4j/deeplearning4j/issues/6663 - I tried reconstructing #6663. Only occurs with shape[1] indeed.

**Comment by raver119** [comment]
Fixed.
