### ISSUE TITLE
Trying DBNMnistFullExample.java, but scores are all NaN

### ISSUE THREAD

**Issue by sanity** [deeplearning4j/deeplearning4j#648]
Trying [this example code](https://github.com/deeplearning4j/dl4j-0.4-examples/blob/master/src/main/java/org/deeplearning4j/examples/deepbelief/DBNMnistFullExample.java), the scores all seem to be NaN, [here](https://gist.github.com/sanity/0b7c28b6802304119fc7) is the full output.

I've seen something similar with other example code.  I tried "Nd4j.ENFORCE_NUMERICAL_STABILITY = true" but this didn't help.

**Comment by agibsonccc** [comment]
Fixed in the examples.
