### ISSUE TITLE
Evaluate counter question on LSTM

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#6491]
I make a simple LSTM model:
val dataLen = 200
	val timeLen = 5
	
	val x1 = Nd4j.create(dataLen, 6, timeLen)
	val x2 = Nd4j.create(dataLen, 2, timeLen)
	val data =
		new ListDataSetIterator(new DataSet(x1, x2).asList(), 20)	

 	val lstmOut = 10
    val lstm =
 		new LSTM.Builder().nIn(6).nOut(lstmOut).build();    
 	
 	val routput =
 		new RnnOutputLayer.Builder()
 			.activation(Activation.SOFTMAX)
 			.nIn(lstmOut)
 			.nOut(2)
 			.build();
 	
 	val conf = new NeuralNetConfiguration.Builder()        
        .list()
        .layer(lstm)
        .layer(routput)
        .build();

 	val net = new MultiLayerNetwork(conf);
    net.init();

        
    System.out.println(net.evaluate(data).stats())

I make some fake data to run the model, I don't care accuracy,precision...
The result:
... ...

=========================Confusion Matrix=========================
   0   1
---------
1000   0 | 0 = 0
   0   0 | 1 = 1

My question is: Why the total counter of data is 1000?
It likes it's 200(real data lenght) X 5(timeLen).
I think it should be 200 here.

**Comment by AlexDBlack** [comment]
> My question is: Why the total counter of data is 1000?
It likes it's 200(real data lenght) X 5(timeLen).
I think it should be 200 here.

RNNs generate predictions at every single time step. Which means there are 1000 predictions being made by the network (200 examples x 5 time steps per example).
Hence the figure of 1000 is correct/expected.
If you want to do sequence classification (one prediction per sequence, not one prediction per time step), you either need a different architecture (like RNN -> global pooling -> OutputLayer) or you need to use masking: https://deeplearning4j.org/docs/latest/deeplearning4j-nn-recurrent

**Comment by Charele** [comment]
@AlexDBlack Okay!
