### ISSUE TITLE
DL4J is super slow on GoogleNews-vectors file

### ISSUE THREAD

**Issue by xnuter** [deeplearning4j/deeplearning4j#650]
I tried to execute the following example on DL4J (loading pre-trained vectors file):

```
File gModel = new File("./GoogleNews-vectors-negative300.bin.gz");

Word2Vec vec = WordVectorSerializer.loadGoogleModel(gModel, true);

InputStreamReader r = new InputStreamReader(System.in);

BufferedReader br = new BufferedReader(r);

for (; ; ) {
    System.out.print("Word: ");
    String word = br.readLine();

    if ("EXIT".equals(word)) break;

    Collection<String> lst = vec.wordsNearest(word, 20);

    System.out.println(word + " -> " + lst);
}
```

But it is super slow (taking ~10 minutes to calculate the nearest words, though they are correct).

There is enough memory (`-Xms20g -Xmx20g`).

When I run the same Word2Vec example from https://code.google.com/p/word2vec/

it gives the nearest words very quickly. 

DL4J uses ND4J which claims to be twice as fast as Numpy: http://nd4j.org/benchmarking

Is anything wrong with my code?

It is based on https://github.com/deeplearning4j/dl4j-0.4-examples.git (I didn't touch any dependencies, just tried to read the Google pre-trained vectors file). Word2VecRawTextExample works just fine (but the data size is relatively small), I only replaced the main method with the code above.

**Comment by agibsonccc** [comment]
How much ram did you give the jvm?

**Comment by xnuter** [comment]
20g (it gives OOM on 10g, it works with 12g I tried to give 20 to see if it helped).

**Comment by xnuter** [comment]
I have a full set up on EC2 server, though it's down now. But I can start it and give you access to it, if you cannot reproduce that locally.

**Comment by agibsonccc** [comment]
K just making sure it wasn't an oom. We can look in to it a bit more. Make
sure you are using rc0.

Thanks!

**Comment by xnuter** [comment]
As I said earlier I just pulled https://github.com/deeplearning4j/dl4j-0.4-examples.git  without touching any dependencies (and it's 0.4-rc0). BTW, while it calculates the nearest words the CPU is ~100% (on a single core). So it's busy.

**Comment by agibsonccc** [comment]
Oh sorry about that. Replying via email didn't see the whole thing ;) We
can take a look then.

**Comment by firojalam** [comment]
Is there any update for this problem?

**Comment by agibsonccc** [comment]
We haven't looked in to this yet. We've been focused on other optimizations.

**Comment by dkmisra** [comment]
Has this been resolved?

**Comment by agibsonccc** [comment]
Oh thank sfor flagging this. @raver119 fix this.

**Comment by shivi28** [comment]
sir can u tell how to train the data of dl4j i don't want to use google news doc model i have my owndataset, how to use it in training

**Comment by raver119** [comment]
Please check examples https://github.com/deeplearning4j/dl4j-0.4-examples/

**Comment by wiseman** [comment]
It takes me 1294 seconds to load `GoogleNews-vectors-negative300.bin` using `nd4j-cuda-7.5 0.4-rc3.10`.  This is on a Macbook Pro with a 2.5 GHz Intel Core i7 and an NVIDIA GeForce GT 750M 2048 MB, with a 12 GB JVM heap.

There's no detail on why this issue was closed--was there a fix committed?

**Comment by raver119** [comment]
Yes, somewhere around November there was fixes commited.  Regarding you 1294 seconds - please link exact macbook model name.

**Comment by wiseman** [comment]
It's a MacBookPro11,3 with 16 GB RAM.

**Comment by wiseman** [comment]
And for comparison, using `nd4j-native 0.4-rc3.10 macosx-x86_64` only takes 114 seconds to load the same model.

**Comment by raver119** [comment]
Please, give me full model name for your laptop.

**Comment by wiseman** [comment]
Sorry, I'm not sure what other information you're asking for.  It's a MacBook Pro, the model ID is MacBookPro11,3--you can google that and find every spec, e.g. [here](https://support.apple.com/en-us/HT201300).
```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	MBP112.0138.B17
```

**Comment by raver119** [comment]
So, that's ME294 model, with 512GB SSD, right? And you're using dl4j 3.10 as well, right?

**Comment by raver119** [comment]
RIght. problem is pretty clear. That's one more place where putScalar happens, which is _really_ bad for CUDA.

**Comment by wiseman** [comment]
I think it's MGXC2xx/A, 15.4”/2.5 Quad-core i7/16GB but upgraded with 1 TB SSD. Using deeplearning4j-nlp 0.4-rc3.10.

**Comment by raver119** [comment]
Ok. That's not putScalar. Issue will be investigated.

Thanks for flagging this once again.

**Comment by agibsonccc** [comment]
Update on this?

**Comment by mani9229** [comment]
Hi,
 I have saved the trained model of word2vecSentimentRNN and when i load the word2vecSentimentRNN , I see a performance issue. It takes 10mins+ to load the googlenews-vector-negative.bin file..
Why the googlenews-vector-negative.bin takes too much time to load. This creates a performance issue ryt..?? Is this issue resolved..?? Please help me to fix this..

**Comment by agibsonccc** [comment]
We've already seen this. It's heap spaced related. Increase it.
