### ISSUE TITLE
Using Aeron With DL4J in order to integrate into a mobile app for Distributed training and processing/running applications

### ISSUE THREAD

**Issue by AlphaMufasaOmega** [deeplearning4j/deeplearning4j#6503]
I want to check on the progress of distributed training/hadoop/Aeron/ Putting Distributed DL4J into an android app. If this is possible let me know I am interested here is an article on the matter:`https://blog.skymind.ai/interview-with-adam-gibson-creator-of-dl4j-why-aeron-matters/`

**Comment by agibsonccc** [comment]
Aeron is for servers not mobile phones.

**Comment by AlphaMufasaOmega** [comment]
so there is no way to integrate DL4J or any similar Machine learning framework into an android application for distributed system for mass data processing?
