### ISSUE TITLE
"NoClassDefFoundError: com/github/os72/protobuf351/MessageOrBuilder" while saving

### ISSUE THREAD

**Issue by MoritzTaylor** [deeplearning4j/deeplearning4j#6506]
Hi, when I try to save a model I get a "NoClassDefFoundError" like in this issue #5583
The error code is the same.
I deleted org.deeplearning4j, org.nd4j and org.datavec in <user.home>/.m2/repository and tried to build again as recommended, but after that the same error occurs.

In the issue is reported that maybe the IDE (=Eclipse) could be the problem.

This is my pom.xml:
`
<properties>
		<nd4j.version>1.0.0-beta2</nd4j.version>
		<dl4j.version>1.0.0-beta2</dl4j.version>
	</properties>

	<build>
		<sourceDirectory>main</sourceDirectory>
		<testSourceDirectory>test</testSourceDirectory>
		<resources>
			<resource>
				<directory>main</directory>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
			</resource>
			<resource>
				<directory>resources</directory>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.7.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>

		
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-native-platform</artifactId>
			<version>1.0.0-beta2</version>
		</dependency>

		
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>25.1-jre</version>
		</dependency>
		<dependency>
			<groupId>com.google.googlejavaformat</groupId>
			<artifactId>google-java-format</artifactId>
			<version>1.6</version>
		</dependency>

		
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>

		
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.11.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.11.0</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>1.7.12</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.25</version>
		</dependency>

		
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-core</artifactId>
			<version>1.0.0-beta2</version>
		</dependency>

		
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-math3</artifactId>
			<version>3.6.1</version>
		</dependency>

	</dependencies>
`

**Comment by agibsonccc** [comment]
Yeah this is likely eclipse related. We never run in to this with intellij. I bet if you build from command line it will work fine.

**Comment by MoritzTaylor** [comment]
I get the same error on command line through and in IntelliJ.

**Comment by MoritzTaylor** [comment]
I have found the solution and it is pretty easy (like the most things):
You do not have to delete org.deeplearning4j, org.nd4j and org.datavec from <user.home>/.m2/repository only, but also com.github.os72 (the dep of the missing class).

Thanks for the help.
