### ISSUE TITLE
Feature request: Partially connected neural networks

### ISSUE THREAD

**Issue by gowthamnatarajan** [deeplearning4j/deeplearning4j#651]
Currently the implementation supports fully connected neural networks only. There are many use cases where all the nodes in one layer does not connect to all the nodes in the next layer.
It would be helpful if its possible to construct such architectures.
One example of such an architecture is:
![image](https://cloud.githubusercontent.com/assets/5133248/9565140/b1510b9a-4e72-11e5-8a16-fac986aac77c.png)

**Comment by agibsonccc** [comment]
Is this implemented with the computation graph?

**Comment by AlexDBlack** [comment]
Essentially, yes. ComputationGraph allows you to do subsets (activations in a range - A to B as a subset of total activations). Given there is no real ordering due to random weight init, it is functionally equivalent to the above.
