### ISSUE TITLE
ND4J: Large number of workspace deallocator threads

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6513]
Something I noticed while debugging an unrelated test issue: During tests (nd4j-tests on CPU specifically), there's a ton of "Workspace deallocator thread" threads running (well, "waiting")... 2721 threads of 2746 total. They seem to be long lived, not being cleaned up - perhaps they are outliving the threads that they were originally associated with?

Not sure yet if this can happen in non-test environments also.

Aha! Link: https://skymindai.aha.io/features/ND4J-154

**Comment by cpoerschke** [comment]
#5902 might be the other issue?

**Comment by raver119** [comment]
Implemented. Now fixed number of deallocators serve everything: workspaces, CUDA NDArrays, whatever
