### ISSUE TITLE
Dl4j - cuda stuck waiting at org.nd4j.nativeblas.Nd4jCuda$NativeOps.streamSynchronize

### ISSUE THREAD

**Issue by bhorkar** [deeplearning4j/deeplearning4j#6518]
I have attached jstack output. 
[dump_thread.log](https://github.com/deeplearning4j/deeplearning4j/files/2443242/dump_thread.log)
[pom.xml.txt](https://github.com/deeplearning4j/deeplearning4j/files/2443251/pom.xml.txt)
[LSTMPrediction .java.txt](https://github.com/deeplearning4j/deeplearning4j/files/2443258/LSTMPrediction.java.txt)

Scenario when this issue was observed: 
1) RDD as exported to a directory (dataset_%.bin files) 
2) FileDatasetiterator is used to iterate the data (attached in above .java file). 
3) .fit is operation stuck waiting or the input.  
4) Use cuda -9.0 (issue also observed with cuda 9.2). However, no issue with nd4j-native. 

Platform:
$ uname -a
Linux sr-mlgpu05 4.15.0-29-generic #31-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

**Comment by raver119** [comment]
Also, what's your GPU model name?

**Comment by bhorkar** [comment]
I tried using same pom.xml file and MnistClassifier.java example on the this machine. Same issue.  So nothing to do with spark/etc. Mostly with GPU? 

GPU: V-100. 
nvidia-smi
Wed Oct  3 11:46:41 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.48                 Driver Version: 390.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   35C    P0    43W / 250W |   1653MiB / 32510MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000000:D8:00.0 Off |                    0 |
| N/A   34C    P0    35W / 250W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     17704      C   java                                        1642MiB |

**Comment by raver119** [comment]
Try different initial weights distribution please, and tell me what happens.

**Comment by bhorkar** [comment]
Hello,

I tried weightInit.ZERO. It is working!. Some weights work, some dont. Is
there any specific weights I should avoid?

Weight initialization might affect the accuracy, hence the question.

Abhijeet

**Comment by raver119** [comment]
I'm afraid that's a bug which was considered fixed... Probably still not.

**Comment by bhorkar** [comment]
Thanks!.
Does the bug affect all initialization weights?
Do you have previous bug#.

**Comment by raver119** [comment]
Bug affects one rng op and V100 devices.

**Comment by raver119** [comment]
Hm. That's not the same bug.

**Comment by raver119** [comment]
You've been using simple XAVIER as weight init, right?

**Comment by bhorkar** [comment]
Yes. I had used XAVIER as weight.


Abhijeet

**Comment by raver119** [comment]
Thanks for highlighting this problem, issue was fixed.
