### ISSUE TITLE
no cuda in java library path

### ISSUE THREAD

**Issue by fradino** [deeplearning4j/deeplearning4j#6567]
I can run this jar in my local windows device,
![default](https://user-images.githubusercontent.com/31378961/46841765-7d279980-cdfc-11e8-9f87-5232180e7e00.png)
![default](https://user-images.githubusercontent.com/31378961/46841818-bc55ea80-cdfc-11e8-9773-a3a0a22f35a7.png)
but i cannot run this in docker with ubuntu16.4 and the same cuda
![tim 20181012084722](https://user-images.githubusercontent.com/31378961/46841678-0e4a4080-cdfc-11e8-9842-6fa7a75ea0be.png)
![tim 20181012085234](https://user-images.githubusercontent.com/31378961/46841712-30dc5980-cdfc-11e8-80e2-5a0ba8f39f03.png)
and i  has
 `<nd4j.backend>nd4j-cuda-9.0</nd4j.backend>`
`<dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>${nd4j.backend}</artifactId>
            <version>${nd4j.version}</version>
        </dependency>`
in pom.xml.
i need some help, thank you

**Comment by saudet** [comment]
Use nd4j-cuda-9.0-platform as dependency, it will fix this.
