### ISSUE TITLE
take numChannels into account

### ISSUE THREAD

**Issue by mrroots** [deeplearning4j/deeplearning4j#657]
class: FeedForwardToCnnPreProcessor
method: preProcess
change
 if(input.columns() != inputWidth * inputHeight)
to
if(input.columns() != inputWidth * inputHeight * numChannels)

**Comment by agibsonccc** [comment]
Good find. https://github.com/deeplearning4j/deeplearning4j/commit/01f36cd92af7a831dbcf467045e75bab7f0371ff
