### ISSUE TITLE
ND4J: Add instructions for AVX artifacts

### ISSUE THREAD

**Issue by saudet** [deeplearning4j/deeplearning4j#6574]
The instructions to use AVX binaries on the following page isn't available in the new docs:
https://github.com/deeplearning4j/nd4j/blob/gh-pages/getstarted.md

**Comment by crockpotveggies** [comment]
Thanks for submitting this issue. We've migrated our docs to its own separate repository at [deeplearning4j-docs](https://github.com/deeplearning4j/deeplearning4j-docs). I've already migrated your issue and you can find it at https://github.com/deeplearning4j/deeplearning4j-docs/issues/139. 

I'll be closing this, but feel free to comment and re-open if this is not what you intended.

*This was an automatically generated response.*
