### ISSUE TITLE
DL4J: JVM crash on iterator unit test for CUDA

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6583]
Got this JVM crash after a clean build today, running deeplearning4j-core unit tests:
https://gist.github.com/AlexDBlack/42dabfac562f23de10b827909ffc6d16

Edit: CUDA 9.2, GTX 970, Windows 10

I haven't been able to isolate this to a single test - seems like it only happens as part of the suite...
Reproduciable running all tests in org.deeplearning4j.iterator 

![image](https://user-images.githubusercontent.com/2360237/46933196-bf700580-d09e-11e8-8e38-417d58e88c1c.png)

Running on CUDA in isolation (CPU passes)
![image](https://user-images.githubusercontent.com/2360237/46933212-d0b91200-d09e-11e8-8c5b-e8ad4136d788.png)

**Comment by raver119** [comment]
Fixed
