### ISSUE TITLE
Missing constructors

### ISSUE THREAD

**Issue by GeorgeNash** [deeplearning4j/deeplearning4j#6589]
Hi guys, just upgraded to `compile 'org.nd4j:nd4j-native-platform:1.0.0-beta2'`.

I've noticed a missing constructor following the change of type of the shape of a tensor from `int` to `long`.

In `INDArray.java`:

```
int getInt(int... indices);
```

needs a:

```
int getInt(long... indices);
```

The second one is to do with creating tensors.

We currently have this constructor in: `DataBufferFactory.java`

```
DataBuffer createDouble(int[] data);
```

Can we add a: 

```
DataBuffer createDouble(long[] data);
```

Thanks guys!!

George

**Comment by raver119** [comment]
It'll be a bit different. We're adding additional data types right now, and after stuff is merged, jvm data types will be equal to INDArray data type by default. And signatures you're mentioning will be added as well.

Here's PR if you're interested: https://github.com/deeplearning4j/deeplearning4j/pull/6350
