### ISSUE TITLE
CI issues and failing tests on Master

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6591]
Known issue: linux-x86_64 avx2 and avx512 can hard crash at some points :(

nd4j-native, ppc64le and macosx-x86_64 avx2 and windows x86_64
```
Failed tests: 
  ReductionOpValidation.testReductionGradients2:669 Failed: [sum - Gradient check failed] expected:<0> but was:<1>
  NormalizerStandardizeLabelsTest.testTransform:143

  RandomTests.testCrossBackendEquality1:97 expected:<[[    0.3201,    1.5718,    2.3576,    0.0110,   -1.6849,    0.0548,   -0.3641,   -0.0468,   -0.7358,    1.3591,    0.6588,    0.1335]]> but was:<[[    1.4715,   -1.7311,   -0.7697,   -1.8070,    0.4986,    1.1626,   -0.6386,   -0.2227,    2.2285,    3.3376,   -1.6103,    0.2355]]>

Tests run: 3554, Failures: 3, Errors: 0, Skipped: 613
```

**Comment by saudet** [comment]
That's not a new issue I think, @sshepel?

**Comment by AlexDBlack** [comment]
The random one is probably due to Raver's recent RNG changes (for V100).
NormalizerStandardize not sure on.
The last one looks familiar though.

**Comment by sshepel** [comment]
@saudet nope, I haven't seen this before...
As for `RandomTests` it should fail, checked with @raver119 regarding this.

**Comment by raver119** [comment]
yes. to fix problems on V100 devices i had to modify implementation. so, values stored in that test aren't viable anymore. Just should be updated with new values.
