### ISSUE TITLE
On android device, Nd4j causes memory overflow, do I need to call api "cleanup()" to release memory??

### ISSUE THREAD

**Issue by ronyuzhang** [deeplearning4j/deeplearning4j#6598]

**Comment by raver119** [comment]
Stick to workspaces instead.

**Comment by AlexDBlack** [comment]
No, you don't need to manually release memory.
Have a read of these pages:
https://deeplearning4j.org/docs/latest/deeplearning4j-config-memory
https://deeplearning4j.org/docs/latest/deeplearning4j-config-workspaces

You can also reduce your minibatch size if required for training/inference to reduce memory requirements.

With properly configured memory settings, you shouldn't be hitting out of memory issues - unless of course the network/inference simply doesn't fit in the available memory (which is possible with some large nets on android devices). Hard to say more without knowing the specifics of what you are doing.
