### ISSUE TITLE
Variables have zero gradients when using logSoftmax in the network

### ISSUE THREAD

**Issue by nadheesh** [deeplearning4j/deeplearning4j#6605]
I noticed that when using logSoftmax of SameDiff library to compute the loss, the gradients of the variables are always zero. However, if we implement logSoftmax by taking the sd.log of sd.softmax, we seem to get the correct gradients (correctness is assumed based on the convergence of the model). 

Is it the expected behavior of logSoftmax or this is due to the approximation of the log Softmax?

 ```
SameDiff sd = SameDiff.create();
SDVariable var = sd.var(Nd4j.randn(5, 3));
SDVariable logp = sd.logSoftmax(var);

SDVariable logpAvg = logp.mean(); // mean is not necessary. just to output a single value
sd.exec();
System.out.println(logp.getArr().toString());
sd.execBackwards();

System.out.println(var.getGradient().getArr().toString()); // always zero gradients 

sd = SameDiff.create();
var = sd.var(Nd4j.randn(5, 3));
SDVariable p = sd.log(sd.softmax(var));

SDVariable pAvg = p.mean(); // mean is not necessary. just to output a single value
sd.exec();
System.out.println(p.getArr().toString());
sd.execBackwards();
System.out.println(var.getGradient().getArr().toString()); //non-zero gradients 
```

**Comment by AlexDBlack** [comment]
Hm... we do have forward pass checks and gradient checks for logSoftmax op here:
https://github.com/deeplearning4j/deeplearning4j/blob/27360a7e29681bb90ee994892cd302614bb9b952/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/autodiff/opvalidation/TransformOpValidation.java#L731-L735

If memory serves me, I have run into this before, where the math does work out that way for "equal gradients at output" when using mean op after softmax (which you get with mean or sum ops). Try with stdev as the final op instead?
You can gradient check a SameDiff instance using the OpValidation tools - here's a randomly selected test case that does that: https://github.com/deeplearning4j/deeplearning4j/blob/27360a7e29681bb90ee994892cd302614bb9b952/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/autodiff/opvalidation/TransformOpValidation.java#L215-L241

I'll close this - but if it doesn't work for stdev, I'll look into it further.
You can also validate it - change an input, and see if the final output (i.e., score) changes.
