### ISSUE TITLE
ND4J: SimpleFileVisitor not available on Android?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6609]
Not sure why we've never seen this before, but it might be worth looknig into this...
From stack trace here: https://github.com/deeplearning4j/deeplearning4j/issues/6608

```
Rejecting re-init on previously-failed class java.lang.Class<org.nd4j.versioncheck.VersionCheck$1>: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/SimpleFileVisitor;
at void org.nd4j.versioncheck.VersionCheck.checkVersions() (VersionCheck.java:89)
at void org.nd4j.linalg.factory.Nd4j.initWithBackend(org.nd4j.linalg.factory.Nd4jBackend) (Nd4j.java:5458)
at void org.nd4j.linalg.factory.Nd4j.initContext() (Nd4j.java:5447)
```

**Comment by saudet** [comment]
It's available from Android 8.0 onwards so I wouldn't worry about it too much:
https://developer.android.com/reference/java/nio/file/SimpleFileVisitor

**Comment by AlexDBlack** [comment]
Android 8.0 was is only 13 months old (general availability) according to my quick search - is that really enough for backward compatibility?
https://en.wikipedia.org/wiki/Android_Oreo
8.0 minimum cuts out the majority of users, if this is to be believed... https://developer.android.com/about/dashboards/

**Comment by saudet** [comment]
Wait, that's in the version check? Did you change that recently?

**Comment by AlexDBlack** [comment]
Nope, no changes recently...
https://github.com/deeplearning4j/deeplearning4j/commits/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/versioncheck/VersionCheck.java

**Comment by saudet** [comment]
Strange, I guess we should at least add a catch block there and not fail in the event that this class doesn't load.
