### ISSUE TITLE
JDBCRecordReader is throwing a java.lang.ClassCastException when reading REAL columns on a sqlite database

### ISSUE THREAD

**Issue by aboulang2002** [deeplearning4j/deeplearning4j#6615]
With SQLite, REAL type maps to java.lang.Double. But **JdbcWritableConverter** tries to map them to java.lang.Float:
```javascript
switch (columnType) {
[. . .]
    case Types.FLOAT:
    case Types.REAL:
        return new FloatWritable((float) columnValue);

[. . .]
}
```

A simple fix would be:
```javascript

case Types.FLOAT:
    return new FloatWritable((float) columnValue);

case Types.REAL:
    return columnValue instanceOf Float ? new FloatWritable((float) columnValue) : new DoubleWritable((double) columnValue);

```

**Comment by AlexDBlack** [comment]
Thanks for reporting. Feel free to send us a pull request with a fix, if you like.
Another possible solution would be to cast it to Number and use Number.doubleValue() etc

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/6617

**Comment by chrisvnicholson** [comment]
@aboulang2002 - please email me at chris at skymind dot ai. i'm curious to hear more about what you're working on.
