### ISSUE TITLE
DL4J: Workspace exception on bad array shape assignment

### ISSUE THREAD

**Issue by tvanh** [deeplearning4j/deeplearning4j#6637]
Main

`package anhtv.ai.dl.computervision;

import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.TimeUnit;

import javax.imageio.ImageIO;

import org.bytedeco.javacpp.opencv_core.Mat;
import org.bytedeco.javacpp.opencv_imgproc;
import org.datavec.image.data.ImageWritable;
import org.datavec.image.loader.NativeImageLoader;
import org.datavec.image.transform.ColorConversionTransform;
import org.datavec.image.transform.RandomCropTransform;
import org.datavec.image.transform.ScaleImageTransform;
import org.deeplearning4j.earlystopping.EarlyStoppingConfiguration;
import org.deeplearning4j.earlystopping.EarlyStoppingModelSaver;
import org.deeplearning4j.earlystopping.EarlyStoppingResult;
import org.deeplearning4j.earlystopping.saver.LocalFileGraphSaver;
import org.deeplearning4j.earlystopping.scorecalc.DataSetLossCalculator;
import org.deeplearning4j.earlystopping.termination.BestScoreEpochTerminationCondition;
import org.deeplearning4j.earlystopping.termination.MaxEpochsTerminationCondition;
import org.deeplearning4j.earlystopping.termination.MaxTimeIterationTerminationCondition;
import org.deeplearning4j.earlystopping.trainer.EarlyStoppingGraphTrainer;
import org.deeplearning4j.nn.api.OptimizationAlgorithm;
import org.deeplearning4j.nn.conf.CacheMode;
import org.deeplearning4j.nn.conf.ComputationGraphConfiguration;
import org.deeplearning4j.nn.conf.ConvolutionMode;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.WorkspaceMode;
import org.deeplearning4j.nn.conf.distribution.TruncatedNormalDistribution;
import org.deeplearning4j.nn.conf.graph.ElementWiseVertex;
import org.deeplearning4j.nn.conf.inputs.InputType;
import org.deeplearning4j.nn.conf.layers.ActivationLayer;
import org.deeplearning4j.nn.conf.layers.CnnLossLayer;
import org.deeplearning4j.nn.conf.layers.ConvolutionLayer;
import org.deeplearning4j.nn.conf.layers.Deconvolution2D;
import org.deeplearning4j.nn.graph.ComputationGraph;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.optimize.listeners.ScoreIterationListener;
import org.junit.Test;
import org.nd4j.linalg.activations.Activation;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.dataset.api.preprocessor.ImagePreProcessingScaler;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.linalg.indexing.NDArrayIndex;
import org.nd4j.linalg.learning.config.AdaDelta;
import org.nd4j.linalg.learning.config.Adam;
import org.nd4j.linalg.learning.config.IUpdater;
import org.nd4j.linalg.lossfunctions.LossFunctions;
import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;
import org.opencv.imgcodecs.Imgcodecs;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import anhtv.common.Commons;

public class SuperImageResolution {
    private static final Logger log = LoggerFactory.getLogger(SuperImageResolution.class);

	private int seed = 2806, h, w, d = 1;
	private SRIIteration train, test; 

	private String dataPath;
	
    ComputationGraph model = null;

	public void loadData(String dataPath){
		this.dataPath = dataPath;
		train = new SRIIteration(w, h, 1, dataPath + "/train/", null);
		test  = new SRIIteration(w, h, 1, dataPath + "/test/", null);
	}
	
    public SuperImageResolution(int w, int h){
    	this.h = h;
    	this.w = w;
    }
    
	public ComputationGraphConfiguration EEDS(){
		ConvolutionLayer.AlgoMode cudnnAlgoMode = ConvolutionLayer.AlgoMode.NO_WORKSPACE;
        IUpdater updater = new Adam(0.01);
        ComputationGraphConfiguration.GraphBuilder graph = new NeuralNetConfiguration.Builder()
            .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
            .updater(updater)
//            .weightInit(weightInit)
            .dist(new TruncatedNormalDistribution(0.0, 0.5))
            .l2(5e-5)
            .miniBatch(true)
//            .cacheMode(cacheMode)
//            .trainingWorkspaceMode(workspaceMode)
//            .inferenceWorkspaceMode(workspaceMode)
            .graphBuilder();

        return
            graph.addInputs("input").setInputTypes(InputType.convolutional(h/2, w/2, d))

                //feature extraction
                .addLayer("fe-conv-1", new ConvolutionLayer.Builder(3, 3).stride(1, 1).nOut(64)
                    .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                    .activation(Activation.RELU).build(), "input")
                .addLayer("fe-conv-2", new ConvolutionLayer.Builder(3, 3).stride(1, 1).nOut(64)
                    .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                    .activation(Activation.RELU).build(), "fe-conv-1")
                .addLayer("fe-conv-3", new ConvolutionLayer.Builder(3, 3).stride(1, 1).nOut(64)
                    .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                    .activation(Activation.IDENTITY).build(), "fe-conv-2")
                .addVertex("fe-add-vertex", new ElementWiseVertex(ElementWiseVertex.Op.Add), "fe-conv-1", "fe-conv-3") // add layer 1 and 3
                .addLayer("fe-relu", new ActivationLayer.Builder().activation(Activation.RELU).build(), "fe-add-vertex")
                //Upsampling
                .addLayer("up-conv-1", new ConvolutionLayer.Builder(1, 1).stride(1, 1).nOut(4)
                    .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                    .activation(Activation.RELU).build(), "fe-relu")
                .addLayer("up-deconv-1", new Deconvolution2D.Builder(14, 14).stride(2, 2).padding(6, 6).nOut(4)
                    .convolutionMode(ConvolutionMode.Strict).cudnnAlgoMode(cudnnAlgoMode)
                    .activation(Activation.RELU).build(), "up-conv-1")
                .addLayer("up-conv-2", new ConvolutionLayer.Builder(1, 1).stride(1, 1).nOut(64)
                    .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                    .activation(Activation.RELU).build(), "up-deconv-1")
                //Multi-scale Reconstruction
                //recontruct-block-1
                .addLayer("recon-conv-1-1", new ConvolutionLayer.Builder(3, 3).stride(1, 1).nOut(64)
                    .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                    .activation(Activation.RELU).build(), "up-conv-2")
                .addLayer("recon-conv-1-2", new ConvolutionLayer.Builder(3, 3).stride(1, 1).nOut(64)
                    .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                    .activation(Activation.IDENTITY).build(), "recon-conv-1-1")
                .addVertex("recon-add-vertex-1", new ElementWiseVertex(ElementWiseVertex.Op.Add), "up-conv-2", "recon-conv-1-2") // add layer 1 and 3
                .addLayer("recon-relu-1", new ActivationLayer.Builder().activation(Activation.RELU).build(), "recon-add-vertex-1")
                //recontruct-block-2
                .addLayer("recon-conv-2-1", new ConvolutionLayer.Builder(3, 3).stride(1, 1).nOut(64)
                    .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                    .activation(Activation.RELU).build(), "recon-relu-1")
                .addLayer("recon-conv-2-2", new ConvolutionLayer.Builder(3, 3).stride(1, 1).nOut(64)
                    .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                    .activation(Activation.IDENTITY).build(), "recon-conv-2-1")
                .addVertex("recon-add-vertex-2", new ElementWiseVertex(ElementWiseVertex.Op.Add), "recon-relu-1", "recon-conv-2-2") // add layer 1 and 3
                .addLayer("recon-relu-2", new ActivationLayer.Builder().activation(Activation.RELU).build(), "recon-add-vertex-2")
                //multi-scale
                .addLayer("scale-conv-1", new ConvolutionLayer.Builder(1, 1).stride(1, 1).nOut(16)
                    .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                    .activation(Activation.RELU).build(), "recon-relu-2")
                .addLayer("scale-conv-2-1", new ConvolutionLayer.Builder(7, 7).stride(1, 1).nOut(16)
                    .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                    .activation(Activation.RELU).build(), "scale-conv-1")
                .addLayer("scale-conv-2-2", new ConvolutionLayer.Builder(5, 5).stride(1, 1).nOut(16)
                    .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                    .activation(Activation.RELU).build(), "scale-conv-2-1")
                .addLayer("scale-conv-2-3", new ConvolutionLayer.Builder(3, 3).stride(1, 1).nOut(16)
                    .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                    .activation(Activation.RELU).build(), "scale-conv-2-2")
                .addLayer("scale-conv-2-4", new ConvolutionLayer.Builder(1, 1).stride(1, 1).nOut(16)
                    .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                    .activation(Activation.RELU).build(), "scale-conv-2-3")
                .addLayer("scale-conv-3", new ConvolutionLayer.Builder(1, 1).stride(1, 1).nOut(d)
                    .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                    .activation(Activation.RELU).build(), "scale-conv-2-4")

                //Shallow network
                .addLayer("shallow-1", new ConvolutionLayer.Builder(3, 3).stride(1, 1).nOut(4)
                    .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                    .activation(Activation.RELU).build(), "input")
                .addLayer("shallow-2", new Deconvolution2D.Builder(14, 14).stride(2, 2).padding(6, 6).nOut(8)
                    .convolutionMode(ConvolutionMode.Strict).cudnnAlgoMode(cudnnAlgoMode)
                    .activation(Activation.RELU).build(), "shallow-1")
                //smooth
                .addLayer("shallow-3-1", new ConvolutionLayer.Builder(3, 3).stride(1, 1).nOut(8)
                        .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                        .activation(Activation.RELU).build(), "shallow-2")
                .addLayer("shallow-3-2", new ConvolutionLayer.Builder(1, 1).stride(1, 1).nOut(8)
                        .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                        .activation(Activation.RELU).build(), "shallow-3-1")
                .addLayer("shallow-3-3", new ConvolutionLayer.Builder(1, 1).stride(1, 1).nOut(d)
                        .convolutionMode(ConvolutionMode.Same).cudnnAlgoMode(cudnnAlgoMode)
                        .activation(Activation.RELU).build(), "shallow-3-2")

                //combine
                .addVertex("combine", new ElementWiseVertex(ElementWiseVertex.Op.Add), "scale-conv-3", "shallow-3-3") // combine deep and shallow
                //output
                .addLayer("output", new CnnLossLayer.Builder(LossFunctions.LossFunction.L1).activation(Activation.IDENTITY).build(), "combine")
                .setOutputs("output")
                //build
                .build();
        
	}
	
	public void train() throws IOException{
		if (model == null){
			model = new ComputationGraph(EEDS());
		}
		model.init();
		System.out.println(model.summary());
		//Log.info(model.summary(InputType.convolutional(h, w, 3)));
		
    	EarlyStoppingModelSaver<ComputationGraph> saver = new LocalFileGraphSaver(dataPath);
        EarlyStoppingConfiguration<ComputationGraph> esConf = new EarlyStoppingConfiguration.Builder<ComputationGraph>()
                .epochTerminationConditions(new MaxEpochsTerminationCondition(500), new BestScoreEpochTerminationCondition(10)) 
                .evaluateEveryNEpochs(1)
                .iterationTerminationConditions(new MaxTimeIterationTerminationCondition(18, TimeUnit.HOURS)) //Max of 120 minutes
                .scoreCalculator(new DataSetLossCalculator(test, true)) 
                .modelSaver(saver)
                .build();
        		
    	EarlyStoppingGraphTrainer trainer = new EarlyStoppingGraphTrainer(esConf, model, train);
        EarlyStoppingResult<ComputationGraph> result = trainer.fit();
        model = result.getBestModel();
        model.save(new File(dataPath + "/bestModel.bin"), true);
		
	}
	
	public void restore(String path) throws IOException{
		File file = new File(path);
		if (file.exists()){
			model = ComputationGraph.load(file, true);
		}
	}
	
	public void train(int epochs) throws IOException{
		model = new ComputationGraph(EEDS());
		model.addListeners(new ScoreIterationListener(1));
		for (int i=0; i < epochs; i++){	
			log.info("Epoch <ID> started.".replace("<ID>", Integer.toString(i)));
			model.fit(train);
			log.info("Epoch <ID> completed.".replace("<ID>", Integer.toString(i)));
		}
        model.save(new File(dataPath + "/bestModel.bin"), true);
	}
	
	@Test
	private void test() throws IOException{
		int i = 0;
		while (test.hasNext()){
			DataSet ds = test.next();
			INDArray output = model.outputSingle(ds.getFeatures());
			test.revert(output);
			test.revert(ds.getLabels());
			test.revert(ds.getFeatures());
	    	ImageIO.write(test.toImage(32, 32, ds.getFeatures()), "jpg", new File(dataPath + "/result/<ID>.in.jpg".replace("<ID>", Integer.toString(i))));
	    	ImageIO.write(test.toImage(64, 64, output), "jpg", new File(dataPath + "/result/<ID>.out.jpg".replace("<ID>", Integer.toString(i))));
	    	ImageIO.write(test.toImage(64, 64, ds.getLabels()), "jpg", new File(dataPath + "/result/<ID>.gt.jpg".replace("<ID>", Integer.toString(i))));
			i++;
		}
	}

	public INDArray predict(File file) throws IOException{
        NativeImageLoader imageLoader = new NativeImageLoader(0, 0, 3);
        
        RandomCropTransform crop = new RandomCropTransform(seed, w, h);
        ScaleImageTransform scaleDown = new ScaleImageTransform(-w/2, -h/2);
        ScaleImageTransform scaleUp = new ScaleImageTransform(w/2, h/2);
        ColorConversionTransform color = new ColorConversionTransform(36); //BGR to YCrBr (luma - chroma)

        ImageWritable wi = imageLoader.asWritable(file);
        
        ImageWritable srImage = crop.transform(wi);
        srImage = color.transform(srImage);
        //lr
        ImageWritable lrImage = scaleDown.transform(srImage);
        
        //output
        ImageWritable outImage = scaleUp.transform(lrImage);
        
        INDArray input = imageLoader.asMatrix(lrImage);
        imageLoader.asMatrix(srImage);
        INDArray ret = imageLoader.asMatrix(outImage);
        
        INDArray pred = model.outputSingle(input.get(NDArrayIndex.all(), NDArrayIndex.all(), NDArrayIndex.point(0)));
        ret.get(NDArrayIndex.all(), NDArrayIndex.all(), NDArrayIndex.point(0)).assign(pred);
        
		return ret;
	}
	
	
	@Test
	private void test(String path) throws IOException{
		List<File> files = Commons.getFiles(path + "/test/", null);
        NativeImageLoader imageLoader = new NativeImageLoader(0, 0, 3);
        NativeImageLoader imageLoaderOutput = new NativeImageLoader(w, h, 3);
        NativeImageLoader imageLoaderInput = new NativeImageLoader(w/2, h/2, 3);
        
        RandomCropTransform crop = new RandomCropTransform(seed, w, h);
        ScaleImageTransform scaleDown = new ScaleImageTransform(-w/2, -h/2);
        ScaleImageTransform scaleUp = new ScaleImageTransform(w/2, h/2);
        ColorConversionTransform color = new ColorConversionTransform(36); //BGR to YCrBr (luma - chroma)
        new ColorConversionTransform(38);
        int index = 0;
        ImagePreProcessingScaler ipps = new ImagePreProcessingScaler(0, 1, 8);		
        for (File file: files){

	        ImageWritable wi = imageLoader.asWritable(file);
	        
	        ImageWritable cropImage = crop.transform(wi);
	        ImageWritable srImage = color.transform(cropImage);
	        //lr
	        ImageWritable lrImage = scaleDown.transform(srImage);
	        
	        //output
	        ImageWritable outImage = scaleUp.transform(lrImage);
	        
	        INDArray input = imageLoader.asMatrix(lrImage);
	        INDArray output = imageLoader.asMatrix(srImage);
	        INDArray ret = imageLoader.asMatrix(outImage);
	        
	        ipps.transform(input);
	        ipps.transform(output);
	        ipps.transform(ret);

	        INDArray feed = Nd4j.create(new int[]{1, 1, w/2, h/2});
	        feed.get(NDArrayIndex.point(0), NDArrayIndex.point(0), NDArrayIndex.all(), NDArrayIndex.all()).assign(input.get(NDArrayIndex.point(0), NDArrayIndex.point(0), NDArrayIndex.all(), NDArrayIndex.all()));
	        INDArray pred = model.outputSingle(feed);
	        ret.get(NDArrayIndex.point(0), NDArrayIndex.point(0), NDArrayIndex.all(), NDArrayIndex.all()).assign(pred);
	        
	        Mat inputMat = imageLoaderInput.asMat(input);
	        opencv_imgproc.cvtColor(imageLoaderInput.asMat(input), inputMat, 38);
	        INDArray inputImg = imageLoaderOutput.asMatrix(inputMat);
	        ipps.revertFeatures(inputImg);
	    	ImageIO.write(test.toImage(32, 32, inputImg), "jpg", new File(dataPath + "/result/<ID>.in.jpg".replace("<ID>", Integer.toString(index))));

	        Mat retMat = imageLoaderOutput.asMat(ret);
	        opencv_imgproc.cvtColor(imageLoaderOutput.asMat(ret), retMat, 38);
	        INDArray retImg = imageLoaderOutput.asMatrix(retMat);
	        ipps.revertFeatures(retImg);
	    	ImageIO.write(test.toImage(64, 64, retImg), "jpg", new File(dataPath + "/result/<ID>.out.jpg".replace("<ID>", Integer.toString(index))));

	        Mat outputMat = imageLoaderOutput.asMat(output);
	        opencv_imgproc.cvtColor(imageLoaderOutput.asMat(output), outputMat, 38);
	        INDArray outputImg = imageLoaderOutput.asMatrix(outputMat);
	        ipps.revertFeatures(outputImg);
	    	ImageIO.write(test.toImage(64, 64, outputImg), "jpg", new File(dataPath + "/result/<ID>.gt.jpg".replace("<ID>", Integer.toString(index))));
	    	index++;
		}
	}
	
    public static void main(String[] args) throws java.lang.Exception {
    	SuperImageResolution sir = new SuperImageResolution(64, 64);
    	sir.loadData("D:/data/image/SR_Image");
    	sir.restore("D:/data/image/SR_Image/bestModel.bin");
    	//sir.test();
    	//sir.train();
    	sir.test("D:/data/image/SR_Image");
    }

    	
}
`

Data pipeline
`package anhtv.ai.dl.computervision;

import java.awt.image.BufferedImage;
import java.awt.image.WritableRaster;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Random;

import javax.swing.JFrame;

import org.bytedeco.javacv.CanvasFrame;
import org.bytedeco.javacv.Frame;
import org.datavec.image.data.ImageWritable;
import org.datavec.image.loader.Java2DNativeImageLoader;
import org.datavec.image.loader.NativeImageLoader;
import org.datavec.image.transform.BoxImageTransform;
import org.datavec.image.transform.ColorConversionTransform;
import org.datavec.image.transform.CropImageTransform;
import org.datavec.image.transform.RandomCropTransform;
import org.datavec.image.transform.ScaleImageTransform;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.dataset.api.DataSetPreProcessor;
import org.nd4j.linalg.dataset.api.iterator.DataSetIterator;
import org.nd4j.linalg.dataset.api.preprocessor.ImagePreProcessingScaler;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.linalg.indexing.NDArrayIndex;

import anhtv.common.Commons;

public class SRIIteration implements DataSetIterator {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private NativeImageLoader imageLoader;
	private List<File> files;
	private int w, h, cursor;
	private Random rng = new Random();
	
	private RandomCropTransform crop;
	private ColorConversionTransform color;
	private ScaleImageTransform scaleDown;
	
	private int batchSize = 1;
	private ImagePreProcessingScaler ipps = new ImagePreProcessingScaler(0, 1, 8);
	private DataSet[] ds;
	
	public INDArray file2YCB(File file) throws IOException{
		ImageWritable wi = imageLoader.asWritable(file);
		color.transform(wi);
		
		crop.transform(wi);
		return null;
	}
	
	public BufferedImage toImage(int h, int w, INDArray matrix) {
		/*
        BufferedImage img = new BufferedImage(w, h, BufferedImage.TYPE_BYTE_GRAY);
        WritableRaster r = img.getRaster();
        byte[] equiv = new byte[(int) matrix.length()];
        for (int i = 0; i < equiv.length; i++) {
            equiv[i] = (byte) matrix.getDouble(i);
        }

        r.setDataElements(0, 0, w, h, equiv);
        return img;
        */
		Java2DNativeImageLoader j2ni = new Java2DNativeImageLoader(h, w);
		return j2ni.asBufferedImage(matrix);
    }
	
	public SRIIteration(int w, int h, int batchSize, String dataPath, List<String> formats){
		this.w = w;
		this.h = h;
		this.batchSize = 1; // fix batch size
		files = Commons.getFiles(dataPath, formats);
		
        imageLoader = new NativeImageLoader(0, 0, 3);
        
		crop = new RandomCropTransform(rng, 2806, w, h);
        scaleDown = new ScaleImageTransform(-w/2, -h/2);
        color = new ColorConversionTransform(rng, 36);
        
		cursor = 0;
		ds = new DataSet[files.size()];
	}

	public void revert(INDArray features){
		ipps.revertFeatures(features);
	}
	
	public void showImage(int h, int ww, INDArray features){
		NativeImageLoader imageLoader = new NativeImageLoader(h, w, 3);
		Frame frame = imageLoader.asFrame(features);
	    CanvasFrame canvas = new CanvasFrame("Title", 1.0);
        canvas.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        canvas.setCanvasSize(frame.imageWidth, frame.imageHeight);
        canvas.showImage(frame);
        try {
            canvas.waitKey(3000);
        } catch (InterruptedException ex) {
            // reset interrupt to be nice
            Thread.currentThread().interrupt();
        }
	}
	
	@Override
	public boolean hasNext() {
		return cursor < files.size();
	}

	private DataSet toDS(ImageWritable wi) throws IOException{
        //sr
        ImageWritable srImage = crop.transform(wi);
        srImage = color.transform(srImage);
        //lr
        ImageWritable lrImage = scaleDown.transform(srImage);
        
        INDArray input = imageLoader.asMatrix(lrImage);
        INDArray output = imageLoader.asMatrix(srImage);
        
        ipps.transform(input);
        ipps.transform(output);
        //System.out.println(input.shapeInfoToString());
        //System.out.println(output.shapeInfoToString());
        
        INDArray in = Nd4j.create(new int[]{1, 1, w/2, h/2});
        in.get(NDArrayIndex.point(0), NDArrayIndex.point(0), NDArrayIndex.all(), NDArrayIndex.all()).assign(input.get(NDArrayIndex.point(0), NDArrayIndex.point(0), NDArrayIndex.all(), NDArrayIndex.all()));
        INDArray out = Nd4j.create(new int[]{1, 1, w, h});
        out.get(NDArrayIndex.point(0), NDArrayIndex.point(0), NDArrayIndex.all(), NDArrayIndex.all()).assign(output.get(NDArrayIndex.point(0), NDArrayIndex.point(0), NDArrayIndex.all(), NDArrayIndex.all()));
    	return new DataSet(in, out);			
	}
	
	@Override
	public DataSet next() {
		if (ds[cursor] == null){
			next(0);
		}
		return ds[cursor++];
	}

	@Override
	public DataSet next(int num) {
		try {
			File file = files.get(cursor);
			
	        ImageWritable wi = imageLoader.asWritable(file);
	        ds[cursor] = toDS(wi); 
	        return ds[cursor];
		} catch (IOException  e) {
			e.printStackTrace();
			return null;
		}

		/*
		try {
			File file = files.get(cursor);
			cursor++;
			
			BoxImageTransform crop = new BoxImageTransform(rng, w, h);
	        ScaleImageTransform scaleUp = new ScaleImageTransform(w/2, h/2);
	        ScaleImageTransform scaleDown = new ScaleImageTransform(-w/2, -h/2);
	        			        
	        NativeImageLoader imageLoader = new NativeImageLoader(0, 0, 3);
	        ImageWritable wi = imageLoader.asWritable(file);
	        //sr
	        ImageWritable srImage = crop.transform(wi);
	        //lr
	        ImageWritable doubleImage = scaleDown.transform(srImage);
	        INDArray doubleMat = imageLoader.asMatrix(doubleImage);
	        
	        ImageWritable lrImage = scaleUp.transform(doubleImage);
	        INDArray input = imageLoader.asMatrix(lrImage);
	        INDArray output = imageLoader.asMatrix(srImage);
	        
	        System.out.print(input.shapeInfoToString());
	        System.out.print(output.shapeInfoToString());
	        
	        ImageIO.write(toImage(w, h, input), "jpg", new File("D:/data/image/<fn>.in.jpg".replace("<fn>", Integer.toString(cursor)) ));
	        ImageIO.write(toImage(w, h, output), "jpg", new File("D:/data/image/<fn>.out.jpg".replace("<fn>", Integer.toString(cursor))));
	        
	    	return new DataSet(input, output);	
		} catch (IOException  e) {
			e.printStackTrace();
			return null;
		}
		*/
    }

	@Override
	public int inputColumns() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int totalOutcomes() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public boolean resetSupported() {
		return true;
	}

	@Override
	public boolean asyncSupported() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public void reset() {
		cursor = 0;
	}

	@Override
	public int batch() {
		return batchSize;
	}

	@Override
	public void setPreProcessor(DataSetPreProcessor preProcessor) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public DataSetPreProcessor getPreProcessor() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List<String> getLabels() {
		// TODO Auto-generated method stub
		return null;
	}
}
`
Wrong code (test(String) function)
`	@Test
	private void test(String path) throws IOException{
		List<File> files = Commons.getFiles(path + "/test/", null);
        NativeImageLoader imageLoader = new NativeImageLoader(0, 0, 3);
        NativeImageLoader imageLoaderOutput = new NativeImageLoader(w, h, 3);
        
        RandomCropTransform crop = new RandomCropTransform(seed, w, h);
        ScaleImageTransform scaleDown = new ScaleImageTransform(-w/2, -h/2);
        ScaleImageTransform scaleUp = new ScaleImageTransform(w/2, h/2);
        ColorConversionTransform color = new ColorConversionTransform(36); //GRB to YCrBr (luma - chroma)
        ColorConversionTransform colorRevert = new ColorConversionTransform(38); //revert
        int index = 0;
		for (File file: files){

	        ImageWritable wi = imageLoader.asWritable(file);
	        
	        ImageWritable cropImage = crop.transform(wi);
	        ImageWritable srImage = color.transform(cropImage);
	        //lr
	        ImageWritable lrImage = scaleDown.transform(srImage);
	        
	        //output
	        ImageWritable outImage = scaleUp.transform(lrImage);
	        
	        INDArray input = imageLoader.asMatrix(lrImage);
	        INDArray output = imageLoader.asMatrix(srImage);
	        INDArray ret = imageLoader.asMatrix(outImage);
	        
	        INDArray feed = Nd4j.create(new int[]{1, w, h, 1});
	        feed.get(NDArrayIndex.point(0), NDArrayIndex.all(), NDArrayIndex.all(), NDArrayIndex.point(0)).assign(input.get(NDArrayIndex.all(), NDArrayIndex.all(), NDArrayIndex.point(0)));
	        INDArray pred = model.outputSingle(feed);
	        ret.get(NDArrayIndex.all(), NDArrayIndex.all(), NDArrayIndex.point(0)).assign(pred);
	        
	        Mat inputMat = imageLoaderOutput.asMat(input);
	        opencv_imgproc.cvtColor(imageLoaderOutput.asMat(input), inputMat, 38);
	        INDArray inputImg = imageLoaderOutput.asMatrix(inputMat);
	    	ImageIO.write(test.toImage(32, 32, inputImg), "jpg", new File(dataPath + "/result/<ID>.in.jpg".replace("<ID>", Integer.toString(index))));

	        imageLoaderOutput.asFrame(ret);
		}
	}`

Instead of throws out exception of bad shape/bad assignment, dl4j gives error about unclosed work space.

**Comment by AlexDBlack** [comment]
Thanks for the issue and code, but I'm unable to reproduce this using either 10.0.-beta2 or current master/snapshots.
In both cases, I get correct errors about shapes not matching. Are you sure you are on 1.0.0-beta2?

I'm happy to reopen this and take another look, but I can't do anything until I can reproduce this.
