### ISSUE TITLE
ND4J: Can NDArrays be backed by shorts?

### ISSUE THREAD

**Issue by trentonfaris** [deeplearning4j/deeplearning4j#6640]
I have some 16-bit images I need to process, but I couldn't find any method for creating an NDArray with short data. Am I missing this functionality, or does it not exist?

**Comment by raver119** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/6350

Shorts, bytes, unsigned bytes, booleans and strings are all there, in that PR.

**Comment by raver119** [comment]
P.s. before it's merged - just go with floats or halfs (if you're on CUDA)
