### ISSUE TITLE
RL4J:  A2C Implementation

### ISSUE THREAD

**Issue by ecthx** [deeplearning4j/deeplearning4j#6642]
It would be nice to see A2C implemented in the future. It's basically simpler (synchronous) version of A3C so very little code modification would be required. Because of its design, it would help with GPU utilization during training. 
https://danieltakeshi.github.io/2018/06/28/a2c-a3c/
https://github.com/openai/baselines/tree/master/baselines/a2c

**Comment by saudet** [comment]
Yes, that would be a great addition. Would you be able to propose the necessary modifications and send a pull request?

**Comment by ecthx** [comment]
I have some questions regarding A2C implementation as there is no official paper and most of my 
insight comes from various Reddit posts.
There seem to be two ways of updating the global actor-critic model. Each worker-thread can calculate
the gradients based on its own experience-rollout and then send calculated gradients to the global model. I guess we would need some coordinator that would average collected gradients and apply them.
The second approach would be to simply collect experiences from each worker thread, stack them and
compute gradients all at once.
My understanding is that the second approach is better for the GPU but does it really make a difference?
When using native nd4j backend can we calculate gradients from all the workers on a single thread or is it better to leave it as it is now and let each worker-thread to calculate its own gradients.
How would I average gradients calculated by each worker?

This is one of the threads that explain how A2C works:
https://www.reddit.com/r/reinforcementlearning/comments/7eljkx/understanding_a2c_and_a3c_multiple_actors/

**Comment by saudet** [comment]
I think it would be worthwhile implementing [IMPALA](https://arxiv.org/pdf/1802.01561.pdf) instead, what do you think? There is even what looks like a well documented implementation here: https://ray.readthedocs.io/en/latest/rllib-algorithms.html

**Comment by ecthx** [comment]
I agree. IMPALA looks promising and it would probably be even easier to implement than A2C. 
However, I'm not interested in A2C because it offers better performance than A3C, but because it's very easy to go from A2C to PPO. I might be wrong but I think that OpenAI still uses PPO as their default algorithm.

**Comment by saudet** [comment]
PPO sounds good, let's do that then?

**Comment by ecthx** [comment]
Sure. PPO seems simpler to implement, although it would be great to see IMPALA in rl4j eventually :-)
