### ISSUE TITLE
Unable to run detections on multiple threads

### ISSUE THREAD

**Issue by sjaiswal25** [deeplearning4j/deeplearning4j#6649]
I am trying to run detections on two images in parallel using yolov2. on GTX 1050Ti. I spawned 2 threads for the same. Both the threads call the same function for loading the pre trained model. I assume it has something to do with both the threads trying to access the model. Below is a subset of the error log, which I think specifies the root cause. The detailed error log is attached in the file below:
[hs_err_pid7506.log](https://github.com/deeplearning4j/deeplearning4j/files/2528770/hs_err_pid7506.log)

 13:55:09.988 [Thread-0] INFO org.deeplearning4j.nn.modelimport.keras.Hdf5Archive - Unexpected end-of-input: was expecting closing '"' for name at [Source: java.io.StringReader@583425c9; line: 1, column: 40001] # A fatal error has been detected by the Java Runtime Environment: #  SIGSEGV (0xb) at pc=0x00007f8fdddfaffc, pid=7506, tid=0x00007f8fde40c700  # JRE version: Java(TM) SE Runtime Environment (8.0_162-b12) (build 1.8.0_162-b12) # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.162-b12 mixed mode linux-amd64 compressed oops) # Problematic frame: # C  [libhdf5.so.101+0x8effc]  H5C_unprotect+0x29c Failed to write core dump. Core dumps have been disabled. 

Kindly help me resolve the issue.

**Comment by agibsonccc** [comment]
Use ParallelInference please. https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/inference/ParallelInferenceExample.java

**Comment by agibsonccc** [comment]
@sjaiswal25 saw gitter..from @AlexDBlack I'll leave this open, but in general we don't support ndarrays being thread safe.  Could you please post the hs_pid error.log from this too?

**Comment by raver119** [comment]
Load model once, in one thread and then use ParallelInference.

**Comment by raver119** [comment]
I mean - this crash happens in HDF5 reader, that's a bit too far from actual ND4J/DL4J code base. So probably something isn't thread safe there as well. So do what you've been told: load model in one thread, and then use ParallelInference.

**Comment by sjaiswal25** [comment]
In https://gitter.im/deeplearning4j/deeplearning4j/archives/2018/01/18, Marcus Klang
@marcusklang mentions that he has used multi threading for achieving detections in parallel and then switched to PI for a better implementaion.So, I was curious to try it out. Anyways, I will try using PI, but could you please point me to an example of using PI in such a scenario(if there exists one) or someplace to make a head start.  Thanks.

**Comment by AlexDBlack** [comment]
Right, I'm thinking if this is a just a threading issue in HDF5 code (i.e., not our code) then we'll just put a lock/synchronized method around loading and call it a day.

@sjaiswal25 As for an example: there's not much to it... https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/inference/ParallelInferenceExample.java

**Comment by sjaiswal25** [comment]
(y)

**Comment by sjaiswal25** [comment]
Will try it :)

**Comment by AlexDBlack** [comment]
I was able to reproduce this. It look like yes, the HDF5 library we use simply isn't thread safe.
