### ISSUE TITLE
Incorrect behaviour of getColumn in 1.0.0-beta2

### ISSUE THREAD

**Issue by boing102** [deeplearning4j/deeplearning4j#6651]
Hi,

I came across unexpected and incorrect behaviour of getColumn function:
``` Java
INDArray m1 = Nd4j.rand(3,2);
// [[    0.2381,    0.7925], 
// [    0.1248,    0.7269], 
// [    0.0443,    0.7036]]
m1.getColumn(0)
// [0.2381, 
// 0.7925, 
// 0.1248]
```
It does not return the first column, but first N values after the column beginning, where N is column length (probably how the values are stored in memory).

The same issue appears when using the more generic get() method.

It works as expected in version 0.9.1.

#### Version Information
* nd4j-native-platform - 1.0.0-beta2
* OS - Ubuntu 18.04.1 LTS

**Comment by AlexDBlack** [comment]
Thanks for the issue. This was flagged earlier here: https://github.com/deeplearning4j/deeplearning4j/issues/6131
I can confirm it has been fixed on master/snapshots: https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots
