### ISSUE TITLE
Why is jackson being shadowed?

### ISSUE THREAD

**Issue by davidebasilio** [deeplearning4j/deeplearning4j#6652]
Why are the jackson dependencies being shadowed into `org.nd4j.shade.jackson`?
The jackson bits in there are affected by CVEs and the shadowing makes it impossible to upgrade on our side.

Would it be possible to not shadow those packages and just depend on them normally?

**Comment by agibsonccc** [comment]
No. We integrate with god knows how many libraries all with their own versions of jackson. About 3 to 4 years of code > `1 million lines of code is the reason for that.  If you're *that* concerned, we have to navigate backwards compatibility and the like. We're happy to upgrade. We're going to do it when the ROI is there and done pragmatically though.

**Comment by davidebasilio** [comment]
Thanks @agibsonccc for your quick reply.

I think that anyone who cares about the security of their sofware at a minimal level will be that concerned and depending on nd4j will not be an option for them if it's complicated to upgrade 4th party dependencies in case of CVEs.

> We're going to do it when the ROI is there and done pragmatically though.

I don't think I understand what you mean with that, would you be so kind and explain?

Thanks!

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/6655

I agree that this is something we should revisit. But Adam has alluded to, upgrading the version is not a trivial task, requiring testing and changes across multiple libraries.

**Comment by davidebasilio** [comment]
Thank you @AlexDBlack
