### ISSUE TITLE
Does it make sense to not require a scorer for EarlyStoppingConfiguration?

### ISSUE THREAD

**Issue by daw3rd** [deeplearning4j/deeplearning4j#6654]
Just a thought, but perhaps it would be useful to allow an early stopping condition only on time and/or number of epochs.  I tried only on a number of epochs and was told that a scorer must be provided.  

I'm using 1.0.0 beta2 from maven.

**Comment by AlexDBlack** [comment]
In principle, we could add this.
But I don't think we should: early stopping is basically a regularization approach - it's used to find the optimal number of number of epochs based on some metric you want to optimize (accuracy, etc).
If you don't have a score you are optimizing, you aren't really doing early stopping, just terminating training at some point.

For terminating at a specific number of epochs, just use the methods like ```fit(DataSetIterator, int numEpochs)```
