### ISSUE TITLE
Why cannot compile the deeplearning4j-master ?

### ISSUE THREAD

**Issue by Herjoey** [deeplearning4j/deeplearning4j#666]
I had tried to git clone the library,but it is too large, which spent my 3 hours get 87% and I gave up.Then I tried to download the deeplearning4j-master.zip from github, which is much smaller .However, when I tried to complie the deeplearning4j via maven , I failed , the error message is that can't find nd4j-x86 0.4-r1-snapshot jar. I try many solutions, but it still doesn't work. 

Is it necessary to git clone the whole large deeplearning4j ?

**Comment by agibsonccc** [comment]
@Herjoey, please clone the  https://github.com/deeplearning4j/dl4j-0.4-examples and avoid compiling from source. Thanks!
