### ISSUE TITLE
ND4J IEvaluation not found in DL4J Scala project using Sonatype snapshots

### ISSUE THREAD

**Issue by bugfoot** [deeplearning4j/deeplearning4j#6664]
Perhaps this is not the right place to describe the issue but [DL4J Gitter channel](https://gitter.im/deeplearning4j/deeplearning4j) is down for me with "404. This is not the chat you're looking for. Sorry. :(" message.

In a Scala project using DL4J aiming to import a Keras model, my SBT contains the below to DL4J and ND4J dependencies from Sonatype snapshots. I am using Sonatype snapshots and not Maven due to [DL4J Keras Import: 2.2.x/2.3.x compatibility](https://github.com/deeplearning4j/deeplearning4j/issues/6550) issue.

```
resolvers += Resolver.sonatypeRepo("snapshots")

libraryDependencies ++= Seq(
  // https://mvnrepository.com/artifact/org.deeplearning4j/deeplearning4j-core
  "org.deeplearning4j" % "deeplearning4j-core" % "1.0.0-SNAPSHOT",
  // https://mvnrepository.com/artifact/org.deeplearning4j/deeplearning4j-nn
  "org.deeplearning4j" % "deeplearning4j-nn" % "1.0.0-SNAPSHOT",
  // https://mvnrepository.com/artifact/org.deeplearning4j/deeplearning4j-modelimport
  "org.deeplearning4j" % "deeplearning4j-modelimport" % "1.0.0-SNAPSHOT",
  // https://mvnrepository.com/artifact/org.nd4j/nd4j-cuda-9.0
  "org.nd4j" % "nd4j-cuda-9.0" % "1.0.0-SNAPSHOT",
  // https://mvnrepository.com/artifact/org.nd4j/nd4j-cuda-9.0-platform
  "org.nd4j" % "nd4j-cuda-9.0-platform" % "1.0.0-SNAPSHOT",
  // https://mvnrepository.com/artifact/org.nd4j/nd4j-api
  "org.nd4j" % "nd4j-api" % "1.0.0-SNAPSHOT"
)
```

Then to the below code snippet:

```
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork
import org.deeplearning4j.nn.modelimport.keras.KerasModelImport

val model = KerasModelImport.importKerasSequentialModelAndWeights(
  """{Valid path to a working Keras model saved as an H5 file}""",
  true
)
```

I get a

```
Class org.nd4j.evaluation.IEvaluation not found - continuing with a stub.
val model = KerasModelImport.importKerasSequentialModelAndWeights(
```

error. Even though I see `import org.nd4j.evaluation.IEvaluation;` used [many times](https://github.com/search?q=org%3Adeeplearning4j%20IEvaluation&type=Code) in DL4J GitHub repositories, I don't know what to import to make it available.

**Comment by agibsonccc** [comment]
@bugfoot could you try forcing an update? It should already be up there.

**Comment by bugfoot** [comment]
@agibsonccc I get a `sync failed` "dump project structure from sbt" error while trying to import the SBT project:

```
[info] Resolving org.scala-sbt#logging;0.13.13 ...
[trace] Stack trace suppressed: run 'last *:ssExtractDependencies' for the full output.
[trace] Stack trace suppressed: run 'last *:update' for the full output.
[error] (*:ssExtractDependencies) sbt.ResolveException: download failed: org.nd4j#nd4j-cuda-9.0;1.0.0-SNAPSHOT!nd4j-cuda-9.0.jar
[error] (*:update) sbt.ResolveException: download failed: org.nd4j#nd4j-cuda-9.0;1.0.0-SNAPSHOT!nd4j-cuda-9.0.jar
[error] Total time: 31 s, completed Nov 3, 2018 10:11:32 AM
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384M; support was removed in 8.0
```

Maybe it is an SBT issue or perhaps I declared one of the snapshots incorrectly.

**Comment by agibsonccc** [comment]
@bugfoot we don't support cuda 9 in the new release. Please upgrade to 9.2 or 10.0. Beyond that..not sure what to tell you.

**Comment by bugfoot** [comment]
@agibsonccc I will try around, but I still can't figure out where `org.nd4j.evaluation.IEvaluation` is. Is it in nd4j-api?

**Comment by saudet** [comment]
CUDA 9.0 is still supported, this is just a case of sbt not being able to download the snapshots by itself. Try to use Maven as explained here to download the artifacts: http://bytedeco.org/builds/

**Comment by bugfoot** [comment]
@saudet It is in fact the SBT failing to download not only ND4J snapshots from Sonatype but standard ND4J and JavaCPP Maven artifacts. This time I went for native ND4J to avoid CUDA compatibility problems, however

```
libraryDependencies ++= Seq(
  "org.deeplearning4j" % "deeplearning4j-core" % "1.0.0-beta2",
  "org.deeplearning4j" % "deeplearning4j-nn" % "1.0.0-beta2",
  "org.deeplearning4j" % "deeplearning4j-modelimport" % "1.0.0-beta2",
  "org.nd4j" % "nd4j-native" % "1.0.0-beta2" classifier "$platform",
  "org.nd4j" % "nd4j-native" % "1.0.0-beta2"
)
```

gave

```
[error] (*:ssExtractDependencies) sbt.ResolveException: download failed: org.nd4j#nd4j-native;1.0.0-beta2!nd4j-native.jar
[error] download failed: org.bytedeco.javacpp-presets#openblas;0.3.0-1.4.2!openblas.jar
[error] (*:update) sbt.ResolveException: download failed: org.nd4j#nd4j-native;1.0.0-beta2!nd4j-native.jar
[error] download failed: org.bytedeco.javacpp-presets#openblas;0.3.0-1.4.2!openblas.jar
[error] Total time: 5 s, completed Nov 3, 2018 7:45:21 PM
```

Could this be an SBT issue / bug? Previously I had no problem getting other Maven artifacts. 
How is it possible to use SBT in a Scala project for DL4J and its dependencies? [Others](https://stackoverflow.com/questions/39104184/how-to-setup-scala-sbt-project-for-nd4j-and-deeplearning4j) have also faced difficulties. Is there an up-to-date-ish SBT sample that works with DL4J Keras model import? 
Should I just abandon SBT and use Maven exclusively for my entire project or can SBT and Maven co-exist? (OK, I'll check it somewhere)

**Comment by saudet** [comment]
Those artifacts have been released, they are not snapshots, and are clearly available here:
http://repo2.maven.org/maven2/org/bytedeco/javacpp-presets/cuda/9.2-7.1-1.4.2/
sbt did not used to have issues like that, so this looks like a regression of sbt. Please report upstream.
