### ISSUE TITLE
isRowVector returns false even though the number of row is 1

### ISSUE THREAD

**Issue by nadheesh** [deeplearning4j/deeplearning4j#6670]
I was trying to initiate a `GradientUpdater` for a variable with shape (1, 1) as shown below.

`rmsPropOptimizer.instantiate(Nd4j.create(1, rmsPropOptimizer.stateSize(1)), true);`

During the GradientUpdater initialization using RmsProp optimizer, it checks if the `viewArray` (initial state) `isRowVector` and it returns false. However, when I check the method comments and it says "**Returns true if the number of rows is 1**". 

```
   /**
     * Returns true if the number of rows is 1
     *
     * @return true if the number of rows is 1
     */
    boolean isRowVector();
```
The following executions returns false even though number of rows is 1.
**Execution:**
```
Nd4j.create(1).isRowVector()
Nd4j.create(1).rows()
Nd4j.create(1, 1).isRowVector()
Nd4j.create(1, 1).rows()

```

**Outputs:** 
```
false
1
false
1
```
Why does the `isRowVector` behaves different from the described behavior by the comments. However, I notice that there is anther method call `isRowVectorOrScalar`, which returns `true` for the above scenarios. I assume that this should be used instead of isRowVector to validate if an NDArray object has single row. 

**Then, why are we using isRowVector in GradientUpdater?** Then it is impossible to perform single variable optimizations using certain optimizers. Why can't we update variables with shape [1, 1] using RmsProp optimizer?

**Comment by agibsonccc** [comment]
This is more of a java doc update thing. You are actually specifying a scalar. Beyond that...no one trains neural nets with 1 parameter anyways. Use isScalarOrVector() if you want this.

**Comment by agibsonccc** [comment]
Correct version of the issue opened here: https://github.com/deeplearning4j/deeplearning4j/issues/6671 @AlexDBlack
