### ISSUE TITLE
Unable to load Keras Model org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type Sequential

### ISSUE THREAD

**Issue by HRKpython** [deeplearning4j/deeplearning4j#6692]
I have ConvNets model built with Keras 2.1.2 and tensorflow backend of 1.2.1.  I save the model and try to load the model following deeplearning4j documentation  and I get this error:

Unable to load Keras Model org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type Sequential

my model.summary is as follows:

Layer (type)                 Output Shape              Param #
=================================================================
zero_padding2d_1 (ZeroPaddin (None, 3, 226, 226)       0
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 64, 224, 224)      1792
_________________________________________________________________
zero_padding2d_2 (ZeroPaddin (None, 64, 226, 226)      0
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 64, 224, 224)      36928
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 64, 112, 112)      0
_________________________________________________________________
zero_padding2d_3 (ZeroPaddin (None, 64, 114, 114)      0
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 128, 112, 112)     73856
_________________________________________________________________
zero_padding2d_4 (ZeroPaddin (None, 128, 114, 114)     0
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 128, 112, 112)     147584
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 128, 56, 56)       0
_________________________________________________________________
zero_padding2d_5 (ZeroPaddin (None, 128, 58, 58)       0
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 256, 56, 56)       295168
_________________________________________________________________
zero_padding2d_6 (ZeroPaddin (None, 256, 58, 58)       0
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 256, 56, 56)       590080
_________________________________________________________________
zero_padding2d_7 (ZeroPaddin (None, 256, 58, 58)       0
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 256, 56, 56)       590080
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 256, 28, 28)       0
_________________________________________________________________
zero_padding2d_8 (ZeroPaddin (None, 256, 30, 30)       0
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 512, 28, 28)       1180160
_________________________________________________________________
zero_padding2d_9 (ZeroPaddin (None, 512, 30, 30)       0
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 512, 28, 28)       2359808
_________________________________________________________________
zero_padding2d_10 (ZeroPaddi (None, 512, 30, 30)       0
_________________________________________________________________
conv2d_10 (Conv2D)           (None, 512, 28, 28)       2359808
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 512, 14, 14)       0
_________________________________________________________________
zero_padding2d_11 (ZeroPaddi (None, 512, 16, 16)       0
_________________________________________________________________
conv2d_11 (Conv2D)           (None, 512, 14, 14)       2359808
_________________________________________________________________
zero_padding2d_12 (ZeroPaddi (None, 512, 16, 16)       0
_________________________________________________________________
conv2d_12 (Conv2D)           (None, 512, 14, 14)       2359808
_________________________________________________________________
zero_padding2d_13 (ZeroPaddi (None, 512, 16, 16)       0
_________________________________________________________________
conv2d_13 (Conv2D)           (None, 512, 14, 14)       2359808
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 512, 7, 7)         0
_________________________________________________________________
sequential_2 (Sequential)    (None, 4)                 6423812

I think it has an issue with my last Sequential layer.

**Comment by maxpumperla** [comment]
@HRKpython, this is a known issue, have a look at this: https://github.com/deeplearning4j/deeplearning4j/issues/4922 (closing as duplicate)

**Comment by HRKpython** [comment]
The work around solution link  provided in #4922 is dead.  Can you please update the link?  This is how I built the model -  I poped last couple of layers of vgg and then added my sequential model on top and fined tuned my top model with couple of conv layers in Vgg conv layers.   So Should I divide/save the model to two parts and then try to load it?   if yes, do you know how to do it with keras save method?

**Comment by maxpumperla** [comment]
@HRKpython I updated the link, but if I understand correctly this won't help you. We don't support adding `Sequential` on top of existing models. This kind of model-in-model isn't easy to support because of the issues mentioned in #4922.

Can you define the same model using only the functional API (or only a single Sequential)? It's still the same layers, so setting weights to the new model wouldn't be hard. could be a workaround, if you need one quickly.
