### ISSUE TITLE
NativeOpExecutioner exception restoring model/ initialising Nd4J

### ISSUE THREAD

**Issue by rsantoso** [deeplearning4j/deeplearning4j#6693]
Hi there,

I'm on 1.0.0-beta.

I'm getting the below exception when running:
      val net: ComputationGraph = ModelSerializer.restoreComputationGraph(netFile)

I trained and saved the model on windows, and the exception occurs when executing above line on a linux box. Running this on windows does not result in this exception, the model loads/ performs fine. 

CPU info of linux box
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    2
Core(s) per socket:    16
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz
Stepping:              1
CPU MHz:               2101.000
BogoMIPS:              4199.42
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              40960K
NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62
NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63

Any chance of some pointers for explaining below please ?

java.lang.ExceptionInInitializerError at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:56) at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:423) at java.lang.Class.newInstance(Class.java:442) at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6405) at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6300) at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:210) at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:564) at org.deeplearning4j.util.ModelSerializer.restoreComputationGraph(ModelSerializer.java:476) at rice.genesis.ir.workflow.quotation.model.tradeparser.model.RnnModel$.dl4jModelFromDisk(RnnModel.scala:55) at rice.genesis.ir.workflow.quotation.model.tradeparser.model.RnnModel$.$anonfun$getModel$2(RnnModel.scala:34) at scala.Option.flatMap(Option.scala:171) at rice.genesis.ir.workflow.quotation.model.tradeparser.model.RnnModel$.getModel(RnnModel.scala:34) at rice.genesis.ir.workflow.quotation.model.tradeparser.TradeParserModels$.$anonfun$getAll$1(TradeParser.scala:113) at 

regards
Richard

**Comment by AlexDBlack** [comment]
Can you share your pom.xml (or dependency management config for other tools)?
Plus we'll need the full output/stack trace here, not just the last few lines of the stack trace.

**Comment by rsantoso** [comment]
Thanks for the hint.... there were missing linux dependencies for nd4j & openblas which has fixed the issue.
