### ISSUE TITLE
ModelSerializer saving in a format that cannot be read by restoreMultiLayerNetwork (Android)

### ISSUE THREAD

**Issue by Barend13** [deeplearning4j/deeplearning4j#6698]
When using the example trained network zip provided in the examples: [link](https://github.com/deeplearning4j/dl4j-examples/blob/master/android/DL4JImageRecognitionDemo/app/src/main/res/raw/trained_mnist_model.zip) 
ModelSerializer.restoreMultiLayerNetwork() works correctly. However when immediately using ModelSerializer.writeModel() and then attempting to restore from this new model an exception is thrown. Below is the code executed, the error message and the two model files (trained_model.zip: before resaving and trained_model_2.zip: after resaving). The configuration.json file inside the zip file differs, so I think the format that writeModel uses is different to the one that restoreMultiLayerNetwork can read, although I could be wrong. This was done in android.

Code:
 ```
dir = new File(dl4j_path + "/trained_model.zip");
model = ModelSerializer.restoreMultiLayerNetwork(dir);
File locationToSave = new File(dl4j_path + "/trained_model_2.zip");
ModelSerializer.writeModel(model, locationToSave, false);
model = ModelSerializer.restoreMultiLayerNetwork(locationToSave);
```

Error
> `  java.lang.RuntimeException: java.lang.IllegalArgumentException: 6 is not a constant in org.nd4j.linalg.api.buffer.DataBuffer$Type
        at org.nd4j.linalg.api.buffer.BaseDataBuffer.read(BaseDataBuffer.java:1490)
        at org.nd4j.linalg.compression.CompressedDataBuffer.readUnknown(CompressedDataBuffer.java:97)
        at org.nd4j.linalg.factory.Nd4j.read(Nd4j.java:2435)
        at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:254)
        at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(ModelSerializer.java:203)`

[trained_model.zip](https://github.com/deeplearning4j/deeplearning4j/files/2570432/trained_model.zip)
[trained_model_2.zip](https://github.com/deeplearning4j/deeplearning4j/files/2570423/trained_model_2.zip)

It would be much appreciated if someone could look into this issue. Thanks.

**Comment by agibsonccc** [comment]
@Barend13 please specify the versions you are using and something a bit more complete we can reproduce. That will help us help you :) Thanks!

**Comment by raver119** [comment]
This bug was fixed in recent version, please use 1.0.0-beta3, and resave your model. (trained_model_2.zip)

**Comment by saudet** [comment]
@Barend13 I've updated the examples to 1.0.0-beta3 in commit https://github.com/deeplearning4j/dl4j-examples/commit/a25741f2a3763a668afd8b2a938cb2e98fb53cf7. Please try this update, and let us know if you still have problems with that version, thanks!

**Comment by Barend13** [comment]
Sorry I was using the '1.0.0-SNAPSHOT' version but I had not updated the maven repository, I swapped to the 1.0.0-beta3 version and it seems to be working correctly. Thank you!
