### ISSUE TITLE
Fatal Crash using Convolution3D layers

### ISSUE THREAD

**Issue by mckunkel** [deeplearning4j/deeplearning4j#6708]
Greetings, I attempted to convert one of my models that use ConvolutionLayer to a model that uses Convolution3D layers. The new model loads and does a few iterations before a fatal crash happens.
Here is some information
ConsoleOuput
https://gist.github.com/mckunkel/2b80ab259cdefb0a1c303f992f7583ae#file-consoleoutput-txt
LogFile:
https://gist.github.com/mckunkel/2b80ab259cdefb0a1c303f992f7583ae#file-logfile
PomFile:
https://gist.github.com/mckunkel/2b80ab259cdefb0a1c303f992f7583ae#file-pom-xml
Model:
https://gist.github.com/mckunkel/2b80ab259cdefb0a1c303f992f7583ae#file-modelfactory-java

**Comment by AlexDBlack** [comment]
Thanks for the issue. I'm unable to reproduce this.
Here's my attempt to do so from your code (which runs fine): https://gist.github.com/AlexDBlack/a4b19dd66712adcc348a578f1e7e481c
I also tried feeding in the wrong format data, but that was caught by validation and correctly threw an exception.

I note you are on 1.0.0-beta - please upgrade to 1.0.0-beta3 and try again.
If it still persists, please provide me with a complete example I can run to reproduce this. The configuration alone is a good start, but as I noted, that not enough.

**Comment by mckunkel** [comment]
Greetings, 
After trying to make a MWE, to post, I realized that Alex's solution of upgrading to
1.0.0-beta3
is the solution.
However I am confused about the Convolution3D.DataFormat, but I will ask this in Gitter.
Thanks for the solution.

**Comment by raver119** [comment]
That's position of channel dimension in tensor. Like NCHW/NHWC for 2d convolutions

**Comment by mckunkel** [comment]
Thanks raver119, I understand that. But when I put this into practice such that (posted in gitter already)
I have an input INDArray with
Rank: 5,Offset: 0 Order: c Shape: [1,3,6,112,1], stride: [2016,672,112,1,1].
As seen the depth of the array is 3 and the number of channels is 1 as in the Convolution3D.DataFormat.NDHWC format. But when I pass this into the model with
.setInputType(InputType.convolutional3D(Convolution3D.DataFormat.NDHWC, 3, height, width, 1)).build();
I get the error
Cannot do forward pass in Convolution3D layer (layer name = layer0, layer index = 0): number of input array channels does not match CNN layer configuration (data input channels = 3, dataFormat=NCDHW, [minibatch, inputChannels, depth, height, width]=[1, 3, 6, 112, 1]; expected input channels = 1) (layer name: layer0, layer index: 0, layer type: Convolution3DLayer)

**Comment by raver119** [comment]
> does not match CNN layer configuration (data input channels = 3, dataFormat=NCDHW,

**Comment by mckunkel** [comment]
The documentation says that 
 public static InputType convolutional3D(Convolution3D.DataFormat dataFormat, long depth, long height, long width, long channels)
see depth is second and channels is last.

**Comment by AlexDBlack** [comment]
@mckunkel Did you set the actual layer data format in your network configuration for the conv3d layers?
If not, set it there: https://github.com/deeplearning4j/deeplearning4j/blob/d56bf78d2183cd0af06278bee7e50817e825c3fd/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/layers/Convolution3D.java#L230-L233

Given the error message you are getting, this is probably the cause.
```
Cannot do forward pass in Convolution3D layer (layer name = layer0, layer index = 0): number of input array channels does not match CNN layer configuration (data input channels = 3, dataFormat=NCDHW, [minibatch, inputChannels, depth, height, width]=[1, 3, 6, 112, 1]; expected input channels = 1) (layer name: layer0, layer index: 0, layer type: Convolution3DLayer)
```
