### ISSUE TITLE
only one ImageLoader

### ISSUE THREAD

**Issue by mrroots** [deeplearning4j/deeplearning4j#672]
use org.canova.image.loader.ImageLoader
instead of duplicate ImageLoader from org.deeplearning4j.util.ImageLoader
(or the other way, however, the one from canova has more functionality)

**Comment by agibsonccc** [comment]
I've added this in canova now. https://github.com/deeplearning4j/Canova/commit/645c747b6d9b7666fb9ef0372935724ddd84cdab Will be out with next rc.
