### ISSUE TITLE
How to build the project?

### ISSUE THREAD

**Issue by Sebastian-0** [deeplearning4j/deeplearning4j#6731]
Sorry for this simple question but I can't get the project to compile properly and your [page on building](https://deeplearning4j.org/docs/latest/deeplearning4j-build-from-source) seems to be partially outdated. I have installed all the prerequisites but the build scripts you are referring to do not exist anymore.

Looking at the main readme in the repository there are some examples of commands but there is no explanation for exactly what they do and how they should be used. Should I run the `change-xxx-versions.sh` scripts and with which values? I don't have a dedicated graphics card so I can't even use CUDA and I don't have the Scala compiler installed, what settings should be used in that case? The same goes for the maven command, i.e. what is `libnd4j.compute`? OpenCL? What version number should I write there?

I tried to omit the CUDA-parameter (since I can't use it anyway) but it still tries to compile the CUDA-subprojects which subsequently fail. I can append my entire error log if you want but the important bit is the following:

> [INFO] g++ -I/home/shj/IdeaProjects/deeplearning4j/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda/../../../../libnd4j//blas -I/home/shj/IdeaProjects/deeplearning4j/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda/../../../../libnd4j//include -I/home/shj/IdeaProjects/deeplearning4j/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda/../../../../libnd4j//include/helpers -I/home/shj/IdeaProjects/deeplearning4j/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda/../../../../libnd4j//include/array -I/home/shj/IdeaProjects/deeplearning4j/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda/../../../../libnd4j//include/memory -I/home/shj/IdeaProjects/deeplearning4j/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda/../../../../libnd4j//include/graph -I/home/shj/IdeaProjects/deeplearning4j/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda/../../../../libnd4j//include/cnpy -I/home/shj/IdeaProjects/deeplearning4j/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda/../../../../libnd4j//include/indexing -I/usr/lib/jvm/java-11-openjdk-amd64/include -I/usr/lib/jvm/java-11-openjdk-amd64/include/linux /home/shj/IdeaProjects/deeplearning4j/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda/target/classes/org/nd4j/nativeblas/jnind4jcuda.cpp /home/shj/IdeaProjects/deeplearning4j/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda/target/classes/jnijavacpp.cpp -march=x86-64 -m64 -O3 -s -std=c++11 -w -Wl,-rpath,$ORIGIN/ -Wl,-z,noexecstack -Wl,-Bsymbolic -Wall -fPIC -shared -o libjnind4jcuda.so -L/home/shj/IdeaProjects/deeplearning4j/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda/../../../../libnd4j//blasbuild/cuda/blas -Wl,-rpath,/home/shj/IdeaProjects/deeplearning4j/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda/../../../../libnd4j//blasbuild/cuda/blas -lnd4jcuda
> /usr/bin/ld: cannot find -lnd4jcuda

This happens when Maven tries to build `nd4j-cuda` which seems to indicate that some library is missing or that some environment path is incorrectly set? I also tried to force Maven to skip the CUDA subprojects but that also fails.

Thanks in advance for your help!

**Comment by raver119** [comment]
“mvn install -DskipTests=true” in root folder should be enough i think
вс, 18 нояб. 2018 г. в 19:49, Sebastian Hjelm <notifications@github.com>:

**Comment by raver119** [comment]
if you don’t have CUDA - you should just exclude corresponding backend. And
no, old guides are still viable.
вс, 18 нояб. 2018 г. в 19:54, raver real <raver119@gmail.com>:

**Comment by raver119** [comment]
Yes, because "mvn install" is enough to build "full stack" now.

To exclude backend you should use regulat maven syntax `-pl ....`. Or, you could just build stuff manually, step by step: libnd4j -> nd4j -> datavec -> dl4j.

By the way, why are you trying to build from sources? We provide daily snapshots for early testing purposes.

**Comment by Sebastian-0** [comment]
I've tried using the `-pl ...` syntax, e.g. `-pl \!nd4j-cuda,\!nd4j-cuda-platform` but that doesn't work. Maven says that it can't find the projects by those names, stripping away `nd4j-` doesn't work either. However I'm not that familiar with maven so I could be doing something wrong here.

I'm trying to rebuild the project since we need access to some hidden state in the dl4j-nlp package (specifically the `lookupTable` in `BasicModelUtils`). We tried creating our own subclass and injecting it when we created our word2vec models. However that only works for our models, when we tried to import the google news word2vec model this fails. We are unsure how to use the `extendedModel` version of `WordVectorSerializer.readWord2VecModel()` when we only have the weights for the model.

Since we are only building a prototype we thought it would be easier to just to make the lookup table public and rebuild it.

**Comment by sshepel** [comment]
@Sebastian-0 try following syntax, please:
```
-pl '!nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda,!nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda-platform,!deeplearning4j/deeplearning4j-cuda'
```

**Comment by raver119** [comment]
It sounds like you're heading the wrong way. Once you have Word2Vec model you can just ModelUtils impl you'd want, so you shouldn't have to rebuild dl4j for that

**Comment by agibsonccc** [comment]
@Sebastian-0 as @raver119 said, you don't need to build all of dl4j just for that. Another way, could be: Send us a PR with the changes you want done and use snapshots maybe?  That way you get the version you want, we maintain it, and you don't worry about a fork. You can use snapshots without building from source and just make the change to dl4j you want.

**Comment by Sebastian-0** [comment]
@sshepel that worked, thank you! I didn't know that you had to specify the full maven path when using that flag.

@raver119 you are right, in fact there is an even better way to solve our problem. Apparently there already exists a getter function for what we wanted (albeit through another class), I have no idea how we missed that last week.

@agibsonccc that could work, given that our changes would be something you want to include. However the point is moot since it turns out there is another way to accomplish what we want.

Anyway, thanks for your quick responses! Even though it turned out I didn't need to rebuild DL4J I still learned something along the way. You might still want to update the build docs though.
