### ISSUE TITLE
How to rebuild project for android?

### ISSUE THREAD

**Issue by zhangy10** [deeplearning4j/deeplearning4j#6739]
Hey guys,

I have some questions about how to rebuild the project for android use. And I have read through the link for the local build ```https://deeplearning4j.org/docs/latest/deeplearning4j-build-from-source```, but I am not sure whether it can work for Android. So, can I double check whether the rebuilding process can work for android? If it works, how should I add the dependencies into the Gradle file? And will the Gradle file be the same as the Android example or just simply add ```repositories {mavenLocal()}```? 

Actually, the reason why rebuilding is that I need to access the states of each hidden layers and get the output of them, then do some updating stuff(sort of statistics stuff), and finally put the updates back to the hidden layers. And I am not sure whether the extended base classes should work for this purpose. If there is an existing way to access those states, can you please let me know which parts of codes I should to rewrite? Many thanks for that.

Cheers

**Comment by saudet** [comment]
The only thing that's different for Android is libnd4j:
https://github.com/deeplearning4j/deeplearning4j/tree/master/libnd4j#android
The rest is just Java, so we can build it the same as the rest:
https://github.com/deeplearning4j/deeplearning4j

**Comment by zhangy10** [comment]
@saudet Thanks so much for the fast response and will have a try. Cheers
