### ISSUE TITLE
Update layers to utilize ND4J mmul-with-transpose methods

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#676]
Once implemented, update DL4J layers to utilize the methods from the following:
https://github.com/deeplearning4j/nd4j/issues/367

Layers that need to be updated:
- BaseOutputLayer
- BaseLayer
- GravesLSTM
and quite possibly some others (feel free to edit this to add more)

Also check other locations that might utilize this (optimizers? gradient updaters?)

**Comment by agibsonccc** [comment]
This was done recently with the optimization pass closing.
