### ISSUE TITLE
Support 3D model importing from keras

### ISSUE THREAD

**Issue by SidneyLann** [deeplearning4j/deeplearning4j#6760]
I have a i3d keras model, it accept frame sequence as input, so the input has 4 dimensions T x H x W x C, when import, below exception exist: 
  org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Inputs with 4 dimensions not supported. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.layers.KerasInput.<init>(KerasInput.java:68)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:263)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:218)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:164)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:96)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:307)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:144)
	at com.pcng.atrain.common.dl4j.ActionRecognition.main(ActionRecognition.java:28)

**Comment by raver119** [comment]
Add some more details please.

**Comment by maxpumperla** [comment]
@SidneyLann @raver119 thanks, I think I understand what's going on. let me have a look.

**Comment by SidneyLann** [comment]
uploaded model for your reference, need to rename to .z01,.z02,.z03,.z04 and combine with first zip file.

[i3d_imagenet_and_kinetics_rgb_all.zip](https://github.com/deeplearning4j/deeplearning4j/files/2614117/i3d_imagenet_and_kinetics_rgb_all.zip)
[i3d_imagenet_and_kinetics_rgb_all.z01.zip](https://github.com/deeplearning4j/deeplearning4j/files/2614125/i3d_imagenet_and_kinetics_rgb_all.z01.zip)
[i3d_imagenet_and_kinetics_rgb_all.z02.zip](https://github.com/deeplearning4j/deeplearning4j/files/2614126/i3d_imagenet_and_kinetics_rgb_all.z02.zip)
[i3d_imagenet_and_kinetics_rgb_all.z03.zip](https://github.com/deeplearning4j/deeplearning4j/files/2614127/i3d_imagenet_and_kinetics_rgb_all.z03.zip)
[i3d_imagenet_and_kinetics_rgb_all.z04.zip](https://github.com/deeplearning4j/deeplearning4j/files/2614128/i3d_imagenet_and_kinetics_rgb_all.z04.zip)

**Comment by maxpumperla** [comment]
@SidneyLann any chance you could just give me reproducible, minimal Keras example instead?

**Comment by SidneyLann** [comment]
yes

**Comment by SidneyLann** [comment]
you should unzip the zip files to generate h5   first, do you know how to do?

**Comment by SidneyLann** [comment]
We must have a h5 file to import, right?

**Comment by maxpumperla** [comment]
I'd like an hdf5 file, without having to unpack and reassemble stuff first. :)

**Comment by SidneyLann** [comment]
give me your email please, only 10m is allowed to upload here.

**Comment by SidneyLann** [comment]
sent

**Comment by SidneyLann** [comment]
the email is rejected

**Comment by maxpumperla** [comment]
just arrived, thanks

**Comment by SidneyLann** [comment]
I fixed it. need my amended src?

**Comment by maxpumperla** [comment]
@SidneyLann how about a quick PR? Otherwise, sure, send me what you have and I can take it from there.

**Comment by SidneyLann** [comment]
I don't know how to new a PR. how to choose master, compare, etc?

**Comment by maxpumperla** [comment]
@SidneyLann don't worry, shoot me an email then. thanks

**Comment by maxpumperla** [comment]
@SidneyLann you're good to go, thanks. should be in SNAPSHOTs soon.

**Comment by SidneyLann** [comment]
ok
