### ISSUE TITLE
DataTypes Branch - Known issues and burndown list

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6767]
This page: Issues for the datatype changes branch (r119_dtypes).
A couple of these issues/improvements might also impact master.

---

### ND4J:

**Bugs/Known Issues**
* ~~Nd4j.create(Nd4j.createBuffer)) can have wrong shape info option flag set https://gist.github.com/AlexDBlack/50739f82c905e187ea75c0e4e49a2aeb~~
* CUDA: INDArray.shapeDescriptor() can return null - https://gist.github.com/AlexDBlack/8d33ee328ff9850d5f69b23eb5e83e77
* Nd4j.createBuffer creates wrong type for anything other than int/long/half/double/float
* Not op can give incorrect results (fail to execute?) under some circumstances: https://gist.github.com/AlexDBlack/968ea33b914ef0e42a2a1ccfadc4e402
    * Seems completely broken now? https://gist.github.com/AlexDBlack/52ab9618525b72e2f871ce6508952f26
* sconv2d_bp op can give inconsistent/random results for dilation 2: (stochastic, different gradients fail on different runs, sometimes identical for a few runs) https://gist.github.com/AlexDBlack/80abb763c54a136fdf99cafac026c3af
* ~~Empty arrays and type casting empty arrays (see Nd4jTestsC.testEmptyCasting())~~
    * Fixed other than "empty arrays have length 1" issue
* RNG failures: RngValidationTests.validateRngDistributions() (tested on CPU only)
    - truncated normal (min less than mean-2*std)
    - DistributionUniform, RandomBernoulli, RandomNormal, RandomStandardNormal (not repeatable when using setSeed)
    - Choice (always selecting the last element from source array)
    - AlphaDropout (need to double check test values)
    - ProbabilisticMerge (sometimes giving NaNs)
    - RandomExponential (Giving 0s and 1s only - output looks like bernoulli, not exponential distribution)
* ~~Can't execute op mergemaxindex with any data type for output array? https://gist.github.com/AlexDBlack/19d075fc28b6fc20607f373a37d57d54~~
* Nd4j.getOpFactory().createTransform("leakyrelu",...) - ClassCastException

**Usability/Enhancements**
* Nd4j.create(double[], DataType) and .create(double[][], DataType) overloads
* Nd4j.arange(float) etc overload?
* INDArray.putScalar(boolean, long...)? (i.e., boolean arg overload for putScalar)
* Improve exceptions for mismatched datatypes
* Add an Nd4j.create method with values coming from long[]
* Usability trap: ```Nd4j.getExecutioner().execAndReturn(new Not(boolArr, boolArr, 0.0))``` - doesn't do what people expect (treat 0.0 same as false)

**Optimizations**
* (Also on master): BaseNDArray has a bunch of methods like: ```rdiv: dup().rdivi(other)```
* Convolution.im2Col: allow executing (input double, output float) etc - might sometimes save a cast in DL4J

**Decisions/Cleanup**
* Now seems as good a time as any to rename JCublasNDArray (and org.nd4j.linalg.jcublas package etc) to something more accuracy, like CudaNDArray
* DataBuffers - have a bunch of no longer used/relevant "copy" args.

---
---

### DL4J

**Bugs/Known Issues**
* ParallelExistingMiniBatchDataSetIteratorTest test timeout

**Usability/Enhancements**
* Allow user to configure datatypes (double vs. float) explicitly for parameters (only for the entire network)

**Design Decisions**
* Activations etc: don't use global DTYPE - use float always? (Q: what about float16? Q: how to control this behaviour? Allow users to configure this?)
* Mask arrays: support both bool and float/double types?

**Optimizations**
* BaseLayer: input.castTo(...) - can this be avoided? Also BaseOutputLayer input.castTo

**Failing Tests**

All tests passing for modules:
* deeplearning4j-graph
* nearestneigbors-(model,client,server,core)
* deeplearning4j-zoo
* deeplearning4j-ui-* (though some tests are ignored/manual here, not yet run)
* deeplearning4j-modelimport
* deeplearning4j-nlp-chinese/japanese/korean
* deeplearning4j-parallel-wrapper, parallelwrapper-server

*deeplearning4j-core* - 3 failing tests
* CNNGradientCheckTest.testSeparableConv2D - due to sconv2d_bp issue logged above
* GradientCheckTestsComputationGraph.testBasicIrisWithElementWiseNode/testBasicIrisWithElementWiseNodeInputSizeGreaterThanTwo - failing due to mergemaxindex issue noted above

*deeplearning4j-nlp*
* Multiple test failures (some also on master?)

*deeplearning4j-slp-uima*
* Multiple test failures (some also on master?)

*dl4j-spark-parameterserver*
* GradientSharingTrainingTest x3 (also failing on master)

---
---

### DataVec

**Optimizations**
* Switch to uint8 for images, non-float ]for one-hot labels?, etc

**Comment by raver119** [comment]
re: bool operands. i'd prohibit boolean left operands in most of ops.

**Comment by AlexDBlack** [comment]
Obsolete at this point.
