### ISSUE TITLE
"latest" API documentation is for beta2, not beta3

### ISSUE THREAD

**Issue by huonw** [deeplearning4j/deeplearning4j#6773]
Visiting https://deeplearning4j.org/api/latest/ seems to show the documentation for beta2, not beta3, e.g. https://deeplearning4j.org/api/latest/org/deeplearning4j/eval/Evaluation.html shows [the documentation at 1.0.0-beta2](https://github.com/deeplearning4j/deeplearning4j/blob/deeplearning4j-1.0.0-beta2/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/eval/Evaluation.java#L45-L77), not [the beta3 state](https://github.com/deeplearning4j/deeplearning4j/blob/deeplearning4j-1.0.0-beta3/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/eval/Evaluation.java#L29) (deprecation).

(Also, https://deeplearning4j.org/api/1.0.0-beta2 works, but https://deeplearning4j.org/api/1.0.0-beta3 does not.)

**Comment by AlexDBlack** [comment]
This issue was moved to deeplearning4j/deeplearning4j-docs#159

**Comment by AlexDBlack** [comment]
Thanks for reporting, this definitely needs to be updated. I've moved this issue to the deeplearning4j-docs repo.
