### ISSUE TITLE
ND4J: Add Conditions.isFinite() and Conditions.notFinite()

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6775]
https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/conditions/Conditions.java

Low priority, but something to add eventually.

isFinite: !(isNaN(x) || isInfinite(x))
notFinite: isNaN(x) || isInfinite(x)

Note that we already have IsFinite, IsInf, IsNaN etc - but these are elementwise transforms... I was looking for something I could use in MatchCondition

**Comment by raver119** [comment]
Added in my branch #6350

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/6350
