### ISSUE TITLE
Is there CRF model in dl4j just like BiLSTM_CRF model in tensorflow?

### ISSUE THREAD

**Issue by Daniells8910** [deeplearning4j/deeplearning4j#6783]

**Comment by AlexDBlack** [comment]
No, DL4J doesn't implement CRF models.
However we do support tensorflow import in SameDiff (SameDiff is our automatic differentiation library built on top of ND4J. See for example https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/modelimport/tensorflow/LoadTensorFlowMNISTMLP.java
