### ISSUE TITLE
Move BagodWords vectorizer from dl4j to canova

### ISSUE THREAD

**Issue by gowthamnatarajan** [deeplearning4j/deeplearning4j#679]
Canova is the place for vectorizers. It already has TfIdf vectorizer. But, the bag of words vectorizer is present in the dl4j package
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/bagofwords/vectorizer/BagOfWordsVectorizer.java

It has to be moved to Canova inside the nlp package
https://github.com/deeplearning4j/Canova/tree/master/canova-data/canova-data-nlp/src/main/java/org/canova/nlp/vectorizer

**Comment by agibsonccc** [comment]
This has been done.
