### ISSUE TITLE
Doc Issue: Out of date code on tutorial: http://deeplearning4j.org/iris-flower-dataset-tutorial.html

### ISSUE THREAD

**Issue by ramboze** [deeplearning4j/deeplearning4j#681]
Chaps,

Out of date code is used in tutorial:

http://deeplearning4j.org/iris-flower-dataset-tutorial.html

Cheers.

**Comment by chrisvnicholson** [comment]
updated

**Comment by ramboze** [comment]
Chris,

The commentary is also out of date, i.e. 

"
.layer(new RBM()) 

Line 3 sets the layer type to RBM, or restricted Boltzmann machine, which is the shallow, building-block layer that is stacked to become a deep-belief network.
"

This may be quite confusing.
