### ISSUE TITLE
Add a Word2Vec deterministic parallel tokenizer

### ISSUE THREAD

**Issue by wmeddie** [deeplearning4j/deeplearning4j#6814]
When you enable parallel tokenization, the order of sequences that are fed into word2vec is non-deterministic, but fast.  The non-determinism is a problem when you really want both reproducible results and more stability when training downstream models. Disabling parallel tokenization is one way to get deterministic training, but the performance penalty is painful.

If we can allow the parallel tokenization feature to work in an lmax disrupter multi-producer style the consumer can pull out the sequences in order once they are ready.

**Comment by raver119** [comment]
Implemented will be merged later today.
