### ISSUE TITLE
Nd4j.tile fails for arrays initialized by numpy

### ISSUE THREAD

**Issue by farizrahman4u** [deeplearning4j/deeplearning4j#6822]
This returns with `jnius.JavaException: JVM exception occurred: 0` :

```python
import jumpy as jp

import numpy as np

from jumpy import Nd4j

np_array = np.random.random((3,2))

ind_array = jp.array(np_array).array

Nd4j.tile(ind_array, 2, 3)  # jnius.JavaException: JVM exception occurred: 0
```

While this works:

```python
import jumpy as jp

import numpy as np

from jumpy import Nd4j

ind_array = Nd4j.zeros(3,2)
Nd4j.tile(ind_array, 2, 3)

```

**Comment by raver119** [comment]
> # jnius.JavaException: JVM exception occurred: 0

Is that all we have there?

**Comment by AlexDBlack** [comment]
@farizrahman4u Can you print the shape information of the ND4J INDArray? (in Java, that would be INDArray.shapeInfoToString() plus INDArray.dataType()). The Numpy datatype would be useful here (I'm assuming it's c order). Let's check it's converted first with the appropriate DataType field and shape buffer dtype flags...

**Comment by farizrahman4u** [comment]
>Is that all we have there?

I will try and somehow reproduce this from java.

@AlexDBlack The dtype/shape info is handled properly. In fact I can get the numpy array back from the ind array.

**Comment by farizrahman4u** [comment]
Fixed in jumpy.


For future reference:
Issue was solved by setting pointer limit to array.size().
