### ISSUE TITLE
import keras model, start application throw .javacpp/...jar/... no such file.

### ISSUE THREAD

**Issue by levou** [deeplearning4j/deeplearning4j#6836]
hi,
   my project dependency dl4j 1.0.0.beta3,  start application on linux, throw exception info:
   javacpp/cache/openblas-0.3.0-1.4.2-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjniopenblas_nolapack.so: libopenblas_nolapack.so.0: cannot open shared object file: No such file or directory
i will try 1.0.0.beat and 1.0.0.beat2, throw like same.
but mac is well for all dl4j version.
    thanks.

**Comment by levou** [comment]
just 1.0.0.beta2 and 3 have problem.

**Comment by saudet** [comment]
Duplicate of #6132.

That's a known issue with old versions of Spring Boot.

**Comment by levou** [comment]
add softlink: ln -s libjniopenblas_nolapack.so libopenblas_nolapack.so.0 ,then resolve this problem.
