### ISSUE TITLE
dl4j-scaleout produces unusable models

### ISSUE THREAD

**Issue by EronWright** [deeplearning4j/deeplearning4j#685]
In the scaleout implementations of dl4j (dl4j-spark-ml, dl4j-hadoop, and dl4j-spark), the dataset is broken down into batches, a model is trained for each batch (in parallel), then the model parameters of each batch are aggregated by averaging them.    I find that, while the model produced by a given batch is usable, the model becomes useless post-aggregation.   Using nd4j-x86 backend (haven't tried others).

Speculating on root cause, perhaps the averaging technique is not applicable for all models, or perhaps more determinism is required (e.g. careful control of the seed).

The best workaround I've found is to constrain the parallelism to 1.  In the Spark case, one would use:
```
MASTER=local[1] spark-submit ...
```

**Comment by agibsonccc** [comment]
The root cause appears to be flatmap and setting of the parameters. We had
a conversation about this in gitter. The problem is supposedly related to
the parameter setting.

**Comment by EronWright** [comment]
@agibsonccc would you elaborate?

**Comment by agibsonccc** [comment]
setParameters in the model appears to be setting the coeffiecents of the
model wrong. Would need to confirm though. I'd suggest 1 or 2 unit tests
around setParameters() and params() to ensure that the model's state is
being persisted across workers properly.
ᐧ

**Comment by agibsonccc** [comment]
Has this been tested with the most recent changes?

**Comment by EronWright** [comment]
Yep , seems good now thanks
