### ISSUE TITLE
Specific order of conflicting dependency in pom.xml prevents loading UI Language files if executed from Eclipse

### ISSUE THREAD

**Issue by printomi** [deeplearning4j/deeplearning4j#6852]
# Steps to reproduce the error
1. Create a maven project in Eclipse IDE (Oxygen version, with m2e plugin, Java 8)
2. Add a JAR file as dependency, which contains the Java class file of an old version of `org.apache.commons.io.IOUtils`. Add the minimal dependencies of the userInterface example (`deeplearning4j-ui_2.10` or `deeplearning4j-ui_2.11` and `nd4j-native-platform`). *Order of dependencies* is important: the conflicting JAR file should be before deeplearning4j-ui.
    - You can use my stripped down `conflicting.jar` file for this: [crafted_jar.zip](https://github.com/deeplearning4j/deeplearning4j/files/2677932/crafted_jar.zip). (The zip file also contains conflicting_full.jar, which contains the whole commons-io package, not only the conflicting class.)
3. Copy the packages of the userInterface examples ([org.deeplearning4j.examples.userInterface and org.deeplearning4j.examples.userInterface.util](https://github.com/deeplearning4j/dl4j-examples/tree/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/userInterface)) into the project source directory.
4. Run org.deeplearning4j.examples.userInterface.UIExample (in Eclipse).

This will trigger this error:
```
ERROR o.d.ui.play.PlayUIServer - Error loading UI Language (Internationalization) data: no language resource data files werefound on the classpath. This usually occurs when running DL4J's UI from an uber-jar, which was built incorrectly (without language resource files). See https://deeplearning4j.org/visualization#issuesfor more details
```
which comes from the following line of PlayUIServer:
https://github.com/deeplearning4j/deeplearning4j/blob/373e837f98b2e05febc7888c6f13e8e7b32ee9bb/deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-play/src/main/java/org/deeplearning4j/ui/play/PlayUIServer.java#L129

# Explanation
deeplearning4j-ui is dependent on org.apache.commons.commons-io (version 2.5), which contains org.apache.commons.io.IOUtils class. This dependency is replaced by the old version of the class from the conflicting JAR file.

# Solution
If we change the order of dependencies from this:
```xml
<dependencies>
    <dependency>
        <groupId>some.old</groupId>
        <artifactId>artifact</artifactId>
        <scope>system</scope>
        <version>old</version>
        <systemPath>path/to/old/conflicting.jar</systemPath>
    </dependency>
    <dependency>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>deeplearning4j-ui_2.10</artifactId>
        <version>1.0.0-beta3</version>
    </dependency>
    
    <dependency>
        <groupId>org.nd4j</groupId>
        <artifactId>nd4j-native-platform</artifactId>
        <version>1.0.0-beta3</version>
    </dependency>
</dependencies>
```
to this (now the conflicting dependency is after deeplearning4j-ui):
```xml
<dependencies>
    <dependency>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>deeplearning4j-ui_2.10</artifactId>
        <version>1.0.0-beta3</version>
    </dependency>
    <dependency>
        <groupId>some.old</groupId>
        <artifactId>artifact</artifactId>
        <scope>system</scope>
        <version>old</version>
        <systemPath>path/to/old/conflicting.jar</systemPath>
    </dependency>
    
    <dependency>
        <groupId>org.nd4j</groupId>
        <artifactId>nd4j-native-platform</artifactId>
        <version>1.0.0-beta3</version>
    </dependency>
</dependencies>
```
then the error will not occur.

# Workaround:
Interestingly, if you execute the example from the command line (not in Eclipse), the error does not occur. I used the following command (maven version is 3.5.2):
```
mvn exec:java -Dexec.mainClass="org.deeplearning4j.examples.userInterface.UIExample"
```

**Comment by saudet** [comment]
That's a pretty common issue, but I'm afraid it's not related to Deeplearning4j. What do you want us to do about it?

**Comment by AlexDBlack** [comment]
Seems like the error is misleading in this case, which should be cleaned up.
i.e., we should throw the original dependency-related exception, not complain about leading UI resources.
