### ISSUE TITLE
VocabConstructor.VocabRunnable hangs if ParallelTokenization == false

### ISSUE THREAD

**Issue by twhitmorenz** [deeplearning4j/deeplearning4j#6870]
Word2Vec vocabulary construction hangs if allowParallelTokenization(false) is set on the builder. This is because VocabConstructor.VocabRunnable never sets the 'done' flag, which the 'ParallelTokenization == false' path waits for. 

Example:
```
        Word2Vec.Builder vb = new Word2Vec.Builder()
                .minWordFrequency(5)
                .stopWords( stopWords)
                .layerSize(100)
                .seed(42)
                .windowSize(5)
                .epochs( epochs)
                .iterate(iter)
                .useUnknown( true)
                .tokenizerFactory( tokenizerF)
                .allowParallelTokenization(false)   // causes hang
                .workers(1);
                
        Word2Vec vec = vb.build();   // hangs
```

The easiest fix for this is to set 'done' & notify all in the finally block of VocabConstructor.run().

**Comment by twhitmorenz** [comment]
This issue was also mentioned at the tail of https://github.com/deeplearning4j/deeplearning4j/issues/5784. In comment https://github.com/deeplearning4j/deeplearning4j/issues/5784#issuecomment-431063161.

**Comment by twhitmorenz** [comment]
I might try and create a PR to fix this. Have cloned dl4j & got dl4j-test-resources, working on a unit-test to demonstrate this.

**Comment by twhitmorenz** [comment]
Created a pull request with fix & unit test:  https://github.com/deeplearning4j/deeplearning4j/pull/6888

**Comment by raver119** [comment]
Fixed/merged
