### ISSUE TITLE
Libnd4j: multiple bugs/issues

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6873]
I'll use this issue to consolidate multiple smaller issues.

---
~~**Issue 1: Fill op shape validation bug: (also occurs during execution)**~~
Confirmed fixed. Original: https://gist.github.com/AlexDBlack/76e8b0339125d0e281e20e38861757b1

---

~~**Issue 2: Libnd4j/SameDiff: multiply_bp edge case bug**~~
Confirmed fixed. Original: https://gist.github.com/AlexDBlack/94608aa7f4e30a94b50f35532ebc8978

---
~~**Issue 3: reduce_norm2_bp scalar case - "Not implemented yet"**~~
Fixed.

---

~~**Issue 4: SpaceToBatch/BatchToSpace crashes**~~
Probably fixed in recent PR - can't reproduce now.
Original: https://gist.github.com/AlexDBlack/81594fbccf667bde9b01cd4e5f5b3ad7

---

~~**Issue 5: confusion_matrix should support int dtypes for output**~~
Fixed. Original: https://gist.github.com/AlexDBlack/7afa15f2f9e830c9209aada6e68b6406

---

~~**Issue 6: hinge loss issue / output shape validation issue~~**
Both issues now fixed.
Original: https://gist.github.com/AlexDBlack/7cc1ce87e2e9525f33a9c5b2a3c57e0a

---

~~**Issue 7: im2col_bp JVM crash**~~

Confirmed fixed. Original: https://gist.github.com/AlexDBlack/7b32de9247e191a4d772dfae12b3f4da

---

~~**Issue 8: change in assumptions/behaviour for reshape**~~

https://gist.github.com/AlexDBlack/4bf655ad01f97445458b43ec6c334b0f

---
~~**Issue 9: batched_gemm shape function (datatype) is wrong, doesn't validate output array types**~~
If I pass Float result arrays with double inputs, I get a JVM crash - not an exception/error.

https://gist.github.com/AlexDBlack/ceb8dec288e97780c98a8338133d048a

---

~~**Issue 10: divide_bp op is broken (edit: also reversedivide_bp)**~~
https://gist.github.com/AlexDBlack/d70fdcade139e878f43b589ef5b8f708

---

~~**Issue 11: slice_bp (and strided slice bp?) don't zero 'non subset' elements**~~
This also appears to be present on 1.0.0-beta3. The "non subset" elements (i.e., those outside of the subset/slice region for forward pass) should always be zeroed.
https://gist.github.com/AlexDBlack/b1ad04da34befcfef28b2f552c73b0c2

---

~~**Issue 12: Confusion matrix doesn't zero other elements**~~
Also present on 1.0.0-beta3.
Values that aren't set based on the labels/predictions array contents should be set to 0.
https://gist.github.com/AlexDBlack/a9328587c3db2522c05d75a3cbb2a84f

Edit: sequence_mask op also doesn't zero other elements.

---

~~**Issue 13: maximum_bp, minimum_bp not reimplemented**~~

https://github.com/deeplearning4j/deeplearning4j/blob/af7155d61dc810d3e7139f15f98810e0255b2e17/libnd4j/include/ops/declarable/generic/broadcastable/maximum.cpp#L58-L137

https://github.com/deeplearning4j/deeplearning4j/blob/af7155d61dc810d3e7139f15f98810e0255b2e17/libnd4j/include/ops/declarable/generic/broadcastable/minimum.cpp#L57-L64

---

**Issue 14: OR/AND/XOR ops broken**

https://gist.github.com/AlexDBlack/da5ecdb06582e62cda58c33a55ce71a0

2019/01/07: Confirmed all 3 are still failing.

---

**Issue 15: Range op should return empty when start == limit**
Output should be exclusive of limit. Currently it's returning a scalar for this case.
https://gist.github.com/AlexDBlack/3bc0819095ec29756f3380c06e04aefe

2019/01/07: Confirmed still failing.

---
**Issue 16: We need a pairwise pow op that supports broadcasting**

Needed to import TF pow. The docs don't say it supports broadcasting, but according to my tests it does.
https://www.tensorflow.org/api_docs/python/tf/math/pow

---
~~**Issue 17: depthwise_conv2d is broken**~~

https://gist.github.com/AlexDBlack/037449c2d94d0bcd3954823cd37781c2

---
**Issue 18: listdiff op can (rarely) crash with some inputs**

Behaviour here is a bit odd... sometimes it'll run for 10,000 iterations without issue.
Other times it'll crash after very few iterations (not sure exactly how many required).
No JVM crash log seems to be produced here.

https://gist.github.com/AlexDBlack/6b27acf5dd1248eb5e17ff55a1cbe056

2019/01/07: Confirmed still failing.

**Comment by AlexDBlack** [comment]
I've edited/updated the above list today. A bunch of stuff has been fixed (thanks!) but there's still a few left:
* 14: or/and/xor
* 15: Range op should return empty
* 16: pairwise pow op (not sure if this has been implemented)
* 18: listdiff crash

**Comment by raver119** [comment]
or/and/xor pass in c++ tests, so it must be something at java side

**Comment by AlexDBlack** [comment]
Thanks - I'll close this, and follow up with or/and/xor shortly on java side.
