### ISSUE TITLE
Nd4J: writeAsNumpy javadoc inadequate

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6890]
There's zero information on the actual format (npy? npz? text? pickled), and how to load it in Python.
https://github.com/deeplearning4j/deeplearning4j/blob/952c55a22c8acb1a7ae0ade9db5f2fc7d6468707/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java#L6549-L6578

**Comment by agibsonccc** [comment]
@AlexDBlack sorry that's npy only. @farizrahman4u is adding npz support now. We had separate write text methods for handling the text representation.

**Comment by AlexDBlack** [comment]
@agibsonccc Thanks. I don't need it (and I was pretty sure it was npy), I just happened to notice when someone asked about it in gitter. It's an easy fix.
