### ISSUE TITLE
DepthwiseConv2D weights shape with initializeParams == false

### ISSUE THREAD

**Issue by sorech** [deeplearning4j/deeplearning4j#6911]
#### Issue Description
Certain codepaths (initializeParams == false) initializes DepthwiseConv2D weights with the wrong shape
shape := {depthMultiplier, layerConf.getNIn(), kernel[0], kernel[1]}
instead of 
shape := {kernel[0], kernel[1], inputDepth, depthMultiplier}

https://github.com/deeplearning4j/deeplearning4j/blob/6bef4d587da9471e885a1616eb3f13239d91face/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/params/DepthwiseConvolutionParamInitializer.java#L192-L211

( previous discussion: https://github.com/deeplearning4j/deeplearning4j/pull/6885#issuecomment-447880648)

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/6912
