### ISSUE TITLE
ParallelInference has no api to get output layer

### ISSUE THREAD

**Issue by SidneyLann** [deeplearning4j/deeplearning4j#6916]
In 1.0.0-beta3, ParallelInference has no api to get output layer. Such then it can't get prediction result like:
Yolo2OutputLayer yoloLayer = (Yolo2OutputLayer) model.getOutputLayer(0);
List<DetectedObject> detectedObjects = yoloLayer.getPredictedObjects(results, detectionThreshold);

**Comment by raver119** [comment]
Right, we can't expose output layers on shared models. But we must extend ParallelInference API to allow use of custom models.

**Comment by raver119** [comment]
Proposed solution is ModelAdapter abstraction, and sample implementation YoloModelAdapter. 
ParallelInference will support it in InlineInferenceMode only, because on-the-fly batching doesn't have too much sense for typical use cases like Yolo and Seq2Seq

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/7426
