### ISSUE TITLE
Implementation of neural ODE 

### ISSUE THREAD

**Issue by DrChainsaw** [deeplearning4j/deeplearning4j#6922]
#### Issue Description

I took a stab at implementing neural ODEs described in this paper:
https://arxiv.org/pdf/1806.07366.pdf

I'm having some issues which I think is due to the fact that to implement the method, one must make multiple (as in sometimes very many) consecutive forward and backward passes through a block of layers and this messes up the workspace handling. Without any special action, the memory consumption of the workspaces used by the computation graph seems to increase with each forward/backward pass through the same set of layers.

I was hoping you might be able to provide some advice for how to do this in the best way (e.g. something in between "it should just work afaik" and "forget it, it will never work").

To avoid too much duplication, I basically wrapped a separate ComputationGraph inside an OdeVertex. The graph is never called directly (as I quickly realized it closes the workspaces which the outer graph assumes to be open), but it is used to maintain the topological ordering and the configuration/building of the OdeVertex. Forward and backward passes is done by code which is essentially duplicated from the CG though (sans modified workspace handling).

I guess SameDiff would have been more appropriate to use for this, but as I understand, it does not support the CUDA backend yet and I also could not find any documentation of it. 

Code can be found in the following repo: https://github.com/DrChainsaw/neuralODE4j and the main issue so far is https://github.com/DrChainsaw/neuralODE4j/issues/5.

I would ofc be more than happy to merge the code into dl4j if you want it (and I if can get it to work)

#### Version Information

Please indicate relevant versions, including, if relevant:

* 1.0.0-beta3
* Windows
* CUDA 10
* NVIDIA driver version 411.31

#### Contributing

As I said, I can submit a PR with the code once I get it to work if you want it

**Comment by raver119** [comment]
re: CUDA SameDiff. It's WIP right now, and we're advancing pretty fast there.

**Comment by raver119** [comment]
Our usual rules apply: any code that runs on CPU, will run on CUDA once we finish. Like with regular ND4J stuff. So there will be almost nothing special i hope. Besides of possibility for manual multi-gpu assignments for graph nodes.

**Comment by raver119** [comment]
Oh, and one more thing that will be there, is that you'll be able to manually enforce given graph nodes to run on CPU, or vice versa. At least that's planned.

**Comment by DrChainsaw** [comment]
Forgot to close this issue. 

Doing multiple forward and backwards passes through a ComputationGraph within a ComputationGraph did not work as the "inner" graph would close a workspace which the "outer" graph assumes to be open. 

Just ripping out the forward and backwards pass logic and using a LayerWorkspaceMgr which uses different workspace names than the ones used by ComputationGraph worked.
