### ISSUE TITLE
Libnd4j failed tests

### ISSUE THREAD

**Issue by ShamsUlAzeem** [deeplearning4j/deeplearning4j#6927]
#### Issue Description
Getting test errors in libnd4j. Here is the gist: https://gist.github.com/ShamsUlAzeem/4d2b72d670260b07abde3a402b65b050

My command was: `mvn clean test -Dlibnd4j.cuda=10.0 -Dlibnd4j.compute=61 -Dlibnd4j.platform=windows-x86_64 -Djavacpp.platform=windows-x86_64 -P testresources,test-nd4j-native`

Please describe our issue, along with:
- expected behavior
All passing tests
- encountered behavior
https://gist.github.com/ShamsUlAzeem/4d2b72d670260b07abde3a402b65b050

#### Version Information

* Deeplearning4j version: `1.0.0-SNAPSHOT (master - 30/12/2018)`
* platform information (OS, etc): `windows-x86_64`
* CUDA version, if used: `10.0`
* NVIDIA driver version, if in use: `417.35`

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by ShamsUlAzeem** [comment]
Reopened this issue as it wasn't supposed to fail with the previous command as well

**Comment by AlexDBlack** [comment]
@raver119 is this still relevant? Or can we close as outdated?

**Comment by raver119** [comment]
I think so, but let me test current master on windows.

**Comment by raver119** [comment]
```
[----------] Global test environment tear-down
[==========] 2719 tests from 120 test cases ran. (16678 ms total)
[  PASSED  ] 2719 tests.
```

Clearly fine. Checked both linux & windows
