### ISSUE TITLE
Use different trigger properties for avx2/avx512 extension profiles?

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#6933]
While trying to figure out https://github.com/deeplearning4j/deeplearning4j/pull/6932 I've come across this:

https://github.com/deeplearning4j/deeplearning4j/blob/d5465b015fd4bf9c6c13ac50a0cb51e1e8698f22/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/pom.xml#L331-L339

So we are using `javacpp.extension` here to trigger `javacpp.platform.extension`. This resulted in a bit of confusion on my side. Since we have to set `libnd4j.extension` anyway for this case, why not trigger the profile on it and skip using the javacpp namespace for that property?

/cc @saudet

**Comment by saudet** [comment]
I probably meant to set libnd4j.extension to javacpp.extension here:
https://github.com/deeplearning4j/deeplearning4j/blob/master/libnd4j/pom.xml#L69
We'd just need to set javacpp.extension and both would get set.

**Comment by treo** [comment]
My biggest problem with using the name `javacpp.extension` is that it insinuates that we are using a javacpp feature *directly*. When I came across it first, I started looking for documentation for javacpp.

Also the line that you've linked would result in a slightly incompatible way of setting extensions, if I got that correctly.

When building libnd4j we set `-Dlibnd4j.extension=avx2`, but when using `javacpp.platform.extension` it is usually set as `-Djavacpp.platform.extension=-avx2`.

**Comment by saudet** [comment]
Yes, we are using JavaCPP directly:
https://github.com/deeplearning4j/deeplearning4j/blob/master/libnd4j/pom.xml#L127
https://github.com/deeplearning4j/deeplearning4j/blob/master/libnd4j/buildnativeoperations.sh#L461-L483

**Comment by saudet** [comment]
Anda Java typically includes the `.`, `-` or whatever in the prefixes or suffixes, just continuing the tradition here :)

**Comment by treo** [comment]
It is just that there are several very similarly named things that do just slightly different stuff accepting just slightly different options which aren't documented and should in my opinion not even exist as separate options

**Comment by saudet** [comment]
Sure, feel free to change this however you like. The way it is right now is close enough to how the presets work, but if you wish to maintain Deeplearning4j yourself in a different way, go for it!

**Comment by treo** [comment]
As far as I can tell none of the presets are using a `javacpp.extension` property, instead they use `javacpp.platform.extension`. 

If possible I'd love to have just `javacpp.platform.extension` and do away with all other methods of setting the extension.

**Comment by sshepel** [comment]
As an option maybe we can unify these two pros to just `platform.extension`?
And underneaths set appropriate properties for specific module...

**Comment by saudet** [comment]
@sshepel That's what it's already doing now, but @treo wants to remove that.

@treo We could do that, making sure the build script accepts an extension both with and without hyphen. I think it already does though.

**Comment by sshepel** [comment]
@saudet I think you misunderstood @treo comments...
ATM we need to provide both `javacpp.extension` and `libnd4j.extension` to build `nd4j-native` with specific extension... which is a bit confusing for end users... and as it turned out not documented well...

How about to move this conversation to internal chat...
