### ISSUE TITLE
Put with NDArrayIndex.empty() fails

### ISSUE THREAD

**Issue by DrChainsaw** [deeplearning4j/deeplearning4j#6940]
#### Issue Description

The following two test cases fail:

    /**
     * Try to set none of the elements to 0
     */
    @Test
    public void putWithEmpty1D() {
        final INDArray test = Nd4j.ones(4).reshape(4);
        final INDArray expected = test.dup();
        assertEquals(expected, test.put(new INDArrayIndex[] {NDArrayIndex.empty()}, 0));
    }

    /**
     * Try to set all columns in none of the rows to zero
     */
    @Test
    public void putWithEmpty2D() {
        final INDArray test = Nd4j.ones(4).reshape(2,2);
        final INDArray expected = test.dup();
        assertEquals(expected, test.put(new INDArrayIndex[] {NDArrayIndex.empty(), NDArrayIndex.all()}, 0));
    }

The first crashes with the following exception:
java.lang.ArrayIndexOutOfBoundsException: 1

	at org.nd4j.linalg.api.ndarray.BaseNDArray.stride(BaseNDArray.java:3152)
	at org.nd4j.linalg.indexing.ShapeOffsetResolution.exec(ShapeOffsetResolution.java:513)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:4998)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.put(BaseNDArray.java:2533)
	at util.preproc.ShiftDimTest.putWithEmpty1D(ShiftDimTest.java:117)

and the second sets all elements to 0 (expect none to be set).

Btw, issue surfaced in code which tried to be clever by putting an element of an INDArrayIndex array to empty to create a no-op at a later stage. It was obviously easy to work around.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta3
* platform information (OS, etc): Windows 10
* CUDA version, if used: CUDA 10, but same error with native

#### Contributing

Given this is an error and not just misunderstanding of the empty INDArrayIndex, I can take a stab at it if you don't have time. I guess it is at least possible to work around by just checking if any element is the empty element.

**Comment by AlexDBlack** [comment]
Hm... I didn't realize we even had an NDArrayIndex.empty()

I see two possible options here:
1. Remove empty() entirely (I can't think of a use case for it tbh)
2. Make any indexing operations with an empty() always be a no-op (except *maybe* for 0d scalars, though a length 0 NDArrayIndex[] would work for that too)

Thoughts? Unless there's a reasonable use case here, I'm in favor of just removing it.

**Comment by AlexDBlack** [comment]
We do already support empty INDArrays (Nd4j.empty() and Nd4j.empty(DataType) on master) - not necessarily because we think it's necessarily a good idea, but rather because we mainly need it for tensorflow import compatibility. That said, empty arrays do have a few use cases (for ops like 'put all elements matching condition X into a new array' where no elements match the condition). However, indexing operations (get/set ops) on empty arrays doesn't really make sense.

**Comment by DrChainsaw** [comment]
No strong opinion from me on that. The "use case" might look something like this:

```
//INDArrayIndex[] indexes and long dim is input 
long nrToInclude = determineNrToInclude(Based on, Some thing);
if(nrToInclude == 0) {
     indexes[dim] = NDArrayIndex.empty()
} else {
     indexes[dim] = NDArrayIndex.interval(0, nrToInclude)
}
return indexes;
```

**Comment by AlexDBlack** [comment]
I thought about this more, and decided that there's not much justification for having NDArrayIndex.empty() - I just can't see a pracitcal use case ("return an empty array" is only a weak argument for it).
Removed here: https://github.com/deeplearning4j/deeplearning4j/pull/7026
