### ISSUE TITLE
BaseDatasetIterator#next does not apply preprocessing

### ISSUE THREAD

**Issue by DrChainsaw** [deeplearning4j/deeplearning4j#6941]
#### Issue Description

Method next() does not apply preprocessor. The method next(int num) does however.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta3

#### Contributing

Probably quicker for you to do since it is trivial.

**Comment by AlexDBlack** [comment]
Confirmed, still present on master - https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/api/iterator/BaseDatasetIterator.java#L124-L125
