### ISSUE TITLE
ND4J: Remove Op.isExecSpecial, Op.exec

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#6963]
Having a "java execution override" option doesn't seem like a good idea, given our libnd4j graph execution - i.e., if we need an override, then it won't work for libnd4j exec anyway.

In some cases (like LogSoftmax) it's not being used anyway.

https://github.com/deeplearning4j/deeplearning4j/blob/af7155d61dc810d3e7139f15f98810e0255b2e17/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/transforms/strict/LogSoftMax.java#L104-L116

**Comment by agibsonccc** [comment]
That's mostly left over from the java execution days. We h ad "exec special" for ops that didn't fit in to the old formula of "x,y,z op" being one of "reduce, linear transform",.. I'd say getting rid of it is fine.

**Comment by raver119** [comment]
It shouldn't be used anywhere these days.
