### ISSUE TITLE
vstack stacking horizontally

### ISSUE THREAD

**Issue by WendelHime** [deeplearning4j/deeplearning4j#6985]
#### Issue Description

I'm trying to vertically stack an list of INDArray, but actually they're being concatenated.

#### Version Information

* Deeplearning4j version: 1.0.0-SNAPSHOT
* platform information (OS, etc): Android

INDArray list:

![image](https://user-images.githubusercontent.com/6754291/51058823-2e42f900-15d1-11e9-9826-30e044a66fa0.png)

hstacked (when should be vstack) INDArray list (when they're vstacked there is `\n` chars):

```
windows = {NDArray@7877} "[ 2359.0000,   42.0000, 2394.0000,   77.0000,    0.8850, 1422.0000,  116.0000, 1457.0000,  151.0000,    0.8694, 1427.0000,  113.0000, 1462.0000,  148.0000,    0.9999, 2618.0000,  127.0000, 2653.0000,  162.0000,    0.9994, 1257.0000,  156.0000, 1292.0000,  191.0000,    0.9995,  598.0000,  240.0000,  633.0000,  275.0000,    0.9997,  806.0000,  232.0000,  841.0000,  267.0000,    0.7433, 2650.0000,  227.0000, 2685.0000,  262.0000,    0.6376,  420.0000,  282.0000,  455.0000,  317.0000,    0.9921,  423.0000,  287.0000,  458.0000,  322.0000,    0.9759,  724.0000,  289.0000,  759.0000,  324.0000,    1.0000, 1184.0000,  301.0000, 1219.0000,  336.0000,    0.9990, 1188.0000,  298.0000, 1223.0000,  333.0000,    0.9947, 1744.0000,  371.0000, 1779.0000,  406.0000,    0.8501, 1818.0000,  384.0000, 1853.0000,  419.0000,    0.9957, 1123.0000,  430.0000, 1158.0000,  465.0000,    0.8428, 1125.0000,  429.0000, 1160.0000,  464.0000,    0.8573, 1649.0000,  409.0000, 1684.0000,  444.0000,    0.9999, 1122.000"
```

**Comment by AlexDBlack** [comment]
Based on the formatting I'm guessing these are rank 1 arrays.
vstack is basically concat(0), which given there's only one dimension, would explain what you are seeing.

For the rank 1 input case, I think we should change it so that vstack of N rank 1 arrays give [N, size] out.
