### ISSUE TITLE
Failing to infere input type for RNN layer when loading Keras model

### ISSUE THREAD

**Issue by kolarto** [deeplearning4j/deeplearning4j#6995]
#### Issue Description

Hi, I am are trying to load model with weights from keras.
When I try to load the model config using the function KerasModelImport.importKerasModelConfiguration(jsonFilePath) and than weights separately, there is an exception "Invalid input for RNN layer (layer name = "value_encoder"): input type is null". (first included json file)
The same thing happens when exporting the model in HDF5 file with weights and model configuration together. Keras is able to load and infere this model without a problem both separate and as one HDF5 file.

I also tried to include all the shapes i was able to define in the configuration (second included json), as I thought the problem could be caused by inability of DL4j to infer the shapes, but the same error was still present.
I was not able to force include output shapes in Keras, but those should not be required.

#### Version Information

* Deeplearning4j version - 1.0.0 beta3 with native backend
* platform information - windows 10

[config_json.zip](https://github.com/deeplearning4j/deeplearning4j/files/2754693/config_json.zip)

**Comment by farizrahman4u** [comment]
Fixed #7502
