### ISSUE TITLE
Nd4j.create(double[]) does not create a 1D vector but 2D array

### ISSUE THREAD

**Issue by aladjov** [deeplearning4j/deeplearning4j#7000]
#### Issue Description

When creating a vector form Java double[] array 
double[] DATA_VECTOR = new double[]{
            1.074588775634765600E0, -8.605123758316040000E-1,
            -6.148217201232910000E0, 4.660042822360992400E-1,
            -9.252894401550293000E0, 2.353585213422775300E-1};
Nd4j.create(DATA_VECTOR, 'c')
- **expected behavior**
   System.out.println(test.rank());
  create 1D vector which should have **rank 1**
- **encountered behavior**
   System.out.println(test.rank());
   instead we get 2D vector with **rank 2**. Dimensions of the 2D vector are  [1,6] which is close but not exactly what we expect

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
1.0.0-beta3
* platform information (OS, etc)
nd4j-native-platform
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing
I would be happy to help with the fixing but will need some guidance with the procedure

**Comment by raver119** [comment]
That's long story. Originally Nd4j had no 0D/1D support. Now it's there.

In latest beta there's Nd4j.trueVector() method for that.
In upcoming release (and in current snapshots) there's whole pack of corresponding signatures, like Nd4j.createFromArray() that honour dimensions.
