### ISSUE TITLE
Libnd4j: Add a 'reductionShape' op

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7003]
This is required for one solution to: https://github.com/deeplearning4j/deeplearning4j/issues/7001
An alternative solution to the above problem could use this, but a 'reduction shape' op could be useful in other contexts: https://github.com/deeplearning4j/deeplearning4j/issues/6723

The idea: Calculate the post-reduction reduction shape as an op (with dynamic args).
i.e., the shape you would get out of a sum (etc) along dimension given an input shape.

Input is always rank 1 int or long representing input shape
Output is always rank 1 int or long array representing shape - unless empty

Example 1: [a,b,c].reduce(1) with keepDims=false:
reductionShape([a,b,c],[1],keepDims=false) -> rank 1 with values (a,c)

Example 2: [a,b,c].reduce(1) with keepDims=true:
reductionShape([a,b,c],[1],keepDims=false) -> rank 1 with values (a,1,c)

Example 3: [a,b,c].reduce(0,1,2) with keepDims=false:
reductionShape([a,b,c],[0,1,2],keepDims=false) -> empty array (i.e., 'shape of 0d scalar')

**Comment by raver119** [comment]
Implemented in my branch, will be merged later
