### ISSUE TITLE
Can`t continue training IDQN

### ISSUE THREAD

**Issue by gkozyryatskyy** [deeplearning4j/deeplearning4j#7005]
#### Issue Description

Hello guys!

Im running the example from here https://github.com/deeplearning4j/dl4j-examples/blob/master/rl4j-examples/src/main/java/org/deeplearning4j/examples/rl4j/Malmo.java
with small changes:
1. train with 1500 steps
2. save model
3. load model
4. continue training 

And looks like with second training (after loading the NET), training start from the "beginning", but not "continues", because the NET behaves as in the start of first training, but not like in the end of it.
I understand that this is a rather abstract statement, so I will add some logging, maybe it will help to understand the problem (**check the rewards**):

**1st training start** 

> o.d.r.l.s.SyncLearning - Epoch: 1, reward: -102.0
> o.d.m.MalmoEnv - Waiting for the mission to start
> o.d.m.MalmoEnv - Mission ended
> o.d.r.l.s.SyncLearning - Epoch: 2, reward: -101.0
> o.d.m.MalmoEnv - Waiting for the mission to start
> o.d.m.MalmoEnv - Mission ended
> o.d.r.l.s.SyncLearning - Epoch: 3, reward: -101.0
> o.d.m.MalmoEnv - Waiting for the mission to start
> o.d.m.MalmoEnv - Mission ended

**1st training end** 

> o.d.r.l.s.SyncLearning - Epoch: 213, reward: -121.0
> o.d.m.MalmoEnv - Waiting for the mission to start
> o.d.r.l.s.q.QLearning - Update target network
> o.d.m.MalmoEnv - Mission ended
> o.d.r.l.s.SyncLearning - Epoch: 214, reward: -146.0
> o.d.m.MalmoEnv - Waiting for the mission to start
> o.d.r.l.s.q.QLearning - Update target network
> o.d.r.p.EpsGreedy - EP: 0.15 1501
> o.d.m.MalmoEnv - Mission ended
> o.d.r.l.s.SyncLearning - Epoch: 215, reward: -141.0

**2nd training strat** 

> o.d.r.l.s.SyncLearning - Epoch: 1, reward: -102.0
> o.d.m.MalmoEnv - Waiting for the mission to start
> o.d.m.MalmoEnv - Mission ended
> o.d.r.l.s.SyncLearning - Epoch: 2, reward: -101.0
> o.d.m.MalmoEnv - Waiting for the mission to start
> o.d.m.MalmoEnv - Mission ended
> o.d.r.l.s.SyncLearning - Epoch: 3, reward: -101.0
> o.d.m.MalmoEnv - Waiting for the mission to start
> o.d.m.MalmoEnv - Mission ended

Here is my code, with the changes. All changes marked with `//TODO <<<<-------------` comment

<details>
  <summary>Click to expand the code</summary>

```
package org.deeplearning4j.examples.rl4j;

import org.deeplearning4j.rl4j.learning.sync.qlearning.QLearning;
import org.deeplearning4j.rl4j.learning.sync.qlearning.discrete.QLearningDiscreteDense;
import org.deeplearning4j.rl4j.network.dqn.DQNFactoryStdDense;
import org.deeplearning4j.rl4j.policy.DQNPolicy;
import org.deeplearning4j.rl4j.util.DataManager;

import org.deeplearning4j.malmo.MalmoBox;
import org.deeplearning4j.malmo.MalmoActionSpaceDiscrete;
import org.deeplearning4j.malmo.MalmoConnectionError;
import org.deeplearning4j.malmo.MalmoDescretePositionPolicy;
import org.deeplearning4j.malmo.MalmoEnv;
import org.deeplearning4j.malmo.MalmoObservationSpace;
import org.deeplearning4j.malmo.MalmoObservationSpacePosition;
import org.nd4j.linalg.learning.config.Adam;

import java.io.File;
import java.io.IOException;
import java.util.logging.Logger;

/**
 * Simple example for Malmo DQN w/ x,y,z position as input
 * @author howard-abrams (howard.abrams@ca.com) on 1/12/17.
 */
public class Malmo {
    public static QLearning.QLConfiguration MALMO_QL = new QLearning.QLConfiguration(123, // Random seed
            200, // Max step By epoch
            1500, // Max step //TODO <<<<-------------
            200000, // Max size of experience replay
            32, // size of batches
            50, // target update (hard)
            10, // num step noop warmup
            0.01, // reward scaling
            0.99, // gamma
            1.0, // td-error clipping
            0.15f, // min epsilon
            1000, // num step for eps greedy anneal
            true // double DQN
    );

    public static DQNFactoryStdDense.Configuration MALMO_NET = DQNFactoryStdDense.Configuration.builder().l2(0.00)
            .updater(new Adam(0.001)).numHiddenNodes(50).numLayer(3).build();

    public static void main(String[] args) throws IOException {
        try {
            malmoCliffWalk();
            // loadMalmoCliffWalk(); //TODO <<<<-------------
        } catch (MalmoConnectionError e) {
            System.out.println(
                    "To run this example, download and start Project Malmo found at https://github.com/Microsoft/malmo.");
        }
    }

    private static MalmoEnv createMDP() {
        // Create action space comprised of just discrete north, south, east and west
        MalmoActionSpaceDiscrete actionSpace = new MalmoActionSpaceDiscrete("movenorth 1", "movesouth 1", "movewest 1",
                "moveeast 1");
        actionSpace.setRandomSeed(123);

        // Create a basic observation space that simply contains the x, y, z world position
        MalmoObservationSpace observationSpace = new MalmoObservationSpacePosition();

        // Create a simple policy that just ensures the agent has moved and there is a reward
        MalmoDescretePositionPolicy obsPolicy = new MalmoDescretePositionPolicy();

        // Create the MDP with the above arguments, and load a mission using an XML file
        return new MalmoEnv("cliff_walking_rl4j.xml", actionSpace, observationSpace, obsPolicy);
    }

    public static void malmoCliffWalk() throws MalmoConnectionError, IOException {
        // record the training data in rl4j-data in a new folder (save)
        DataManager manager = new DataManager(true);

        // Create the MDP complete with a Malmo mission
        MalmoEnv mdp = createMDP();

        // define the training
        // TODO <<<<------------- loading the NET in the next few lines
        QLearningDiscreteDense<MalmoBox> dql = null;
        if (new File("cliffwalk.policy").exists()) {
            System.out.println("---------------- Loading NET ----------------");
            dql = new QLearningDiscreteDense<MalmoBox>(mdp, DQNPolicy.load("cliffwalk.policy").getNeuralNet(), MALMO_QL,
                    manager);
        } else {
            System.out.println("---------------- New NET ----------------");
            dql = new QLearningDiscreteDense<MalmoBox>(mdp, MALMO_NET, MALMO_QL, manager);
        }
        // TODO <<<<------------- NET loaded

        // train
        dql.train();

        // get the final policy
        DQNPolicy<MalmoBox> pol = dql.getPolicy();

        // serialize and save (serialization showcase, but not required)
        pol.save("cliffwalk.policy");

        // close the mdp
        mdp.close();
    }

    // showcase serialization by using the trained agent on a new similar mdp
    public static void loadMalmoCliffWalk() throws MalmoConnectionError, IOException {
        // Create the MDP complete with a Malmo mission
        MalmoEnv mdp = createMDP();

        // load the previous agent
        DQNPolicy<MalmoBox> pol = DQNPolicy.load("cliffwalk.policy");

        // evaluate the agent 10 times
        double rewards = 0;
        for (int i = 0; i < 10; i++) {
            double reward = pol.play(mdp);
            rewards += reward;
            Logger.getAnonymousLogger().info("Reward: " + reward);
        }

        // Clean up
        mdp.close();

        // Print average reward over 10 runs
        Logger.getAnonymousLogger().info("average: " + rewards / 10);
    }
}
```
</details>

Am I doing something wrong? Any help is appreciated!

- Expected behavior: Continue training
- Encountered behavior: Training starts from the beginning

#### Version Information

* Deeplearning4j version: **1.0.0-beta3**
* platform information:  **OSX**

**Comment by saudet** [comment]
We would need to save the buffer used for experience replay for that to work, and there might also be other bugs preventing that from working. Anyway, contributions welcome :)

**Comment by gkozyryatskyy** [comment]
@saudet So this kind of NET`s can be trained only with the 1st try (1st training session)? Isn't this critical to production use?

Anyway, thank you for the reply.

P.S. Maybe in some time I will have a time to contribute. But it is totally not now =( sorry for that =( I still own you some javacv contribution =)
