### ISSUE TITLE
Keras import's supported features are not clear on the website

### ISSUE THREAD

**Issue by Isa-rentacs** [deeplearning4j/deeplearning4j#7019]
#### Issue Description
On https://deeplearning4j.org/docs/latest/keras-import-supported-features, there are features listed without links. For instance, GRU doesn't have a link and it's not supported as of now, while most of losses are without links but it seems they are implemented [here](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/utils/KerasLossUtils.java)

According to [#5590](https://github.com/deeplearning4j/deeplearning4j/issues/5590), there were check-boxes but it has gone while overhauling the web pages.

#### Version Information
N/A

**Comment by maxpumperla** [comment]
thanks, I already did that for you a few days ago :) 

https://github.com/deeplearning4j/deeplearning4j-docs/issues/167

**Comment by Isa-rentacs** [comment]
Ah I didn't notice there was a separated repo for that, thanks!

**Comment by maxpumperla** [comment]
yeah, I know it's not obvious. hence the help. thanks again for reporting this, very helpful for us!
