### ISSUE TITLE
Nd4j 1.0.0 official release 

### ISSUE THREAD

**Issue by nadheesh** [deeplearning4j/deeplearning4j#7023]
Nd4j is an amazing library for Numpy like operations in Java. I personally found it very useful for numerical array operations in Java projects. I'm interested in knowing when you guys are planing to do the release of Nd4j 1.0.0. 

Can you please let me know the due date of Nd4j 1.0.0 official release. Will it happen soon?

**Comment by AlexDBlack** [comment]
We generally don't comment on our release schedule for OSS, as things can (and often do) slip if the codebase doesn't pass all pre-release QA or we need to add new features for some reason (like a customer).
We will likely have 1 or 2 more releases before a formal 1.0.0 release - they will likely be release candidate ("RC"), when the API is essentially stable but we have a little more to do.
All that said, I can say the next release is not not in the next few weeks. :) Best guess for the next release is somewhere in the order of 1-3 months, but that could change.

**Comment by nadheesh** [comment]
Thanks for the prompt response @AlexDBlack. This gives me enough information to plan my work.

**Comment by AlexDBlack** [comment]
No problem. We do have snapshots as well, which are updated daily - https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots
If you need a recent addition or bug fix, that's an option.

**Comment by nadheesh** [comment]
@AlexDBlack thanks for pointing them out.  That will be definitely useful.
