### ISSUE TITLE
ND4J: JVM crash with workspaces + ND4J ops (pullRows, sum)

### ISSUE THREAD

**Issue by Geokats** [deeplearning4j/deeplearning4j#7049]
#### Issue Description

When trying to fit a computation graph using a custom DataSetIterator I am getting a fatal error caused by pullRowsGeneric called by reverseTimeSeries inside a bidirectional LSTM layer.

Here is a gist containing code to reproduce the error along with the error log I get:
https://gist.github.com/Geokats/327a808ab8c6d08690eb966633620678 

#### Version Information

I am using the snapshot version on Ubuntu 16.04.5 LTS 64-bit system.

**Comment by AlexDBlack** [comment]
I'm not able to reproduce this. I ran your network and data pipeline code for over 5000 iterations, and did not run into any issues.
Can you pull the latest snapshots ("mvn -U package -DskipTests``` or similar) and try again?

**Comment by Geokats** [comment]
It persists even after updating to the latest snapshots.

I don't know if it is of any help, but I have noticed that the error only occurs when the batch given to the graph is of odd size. (in my code this happens on the last batch which is of size 5)
Also if the labels are removed from the DataSet the error disappears.

**Comment by AlexDBlack** [comment]
OK, I've been able to reproduce this on Linux (Kubunti 17.10 to be precise) using nd4j-native backend. It still runs perfectly fine on Windows.
I'll see if I can isolate it further.

**Comment by saudet** [comment]
Looks like a bug in GCC:
> // Some platforms will occasionally send nonstandard spurious SI_KERNEL codes.
> // One way to get this is via unaligned SIMD loads.
- https://reviews.llvm.org/D12659

Unaligned memory access easily happens with views, but I suppose it's the compiler's job to make sure that doesn't happen when we're not calling any intrinsics manually.

**Comment by raver119** [comment]
@Geokats what's your CPU model name?

**Comment by raver119** [comment]
@AlexDBlack what happens if you use avx2 nd4j-native? Does the problem still persist?

**Comment by saudet** [comment]
The CPU is "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz"

**Comment by raver119** [comment]
Aha, same question then: what happens with avx2 binary? These CPUs should be fine with unaligned accesses

**Comment by saudet** [comment]
Sure, they all have instructions to deal with it, as long as the compiler figures it out.

**Comment by raver119** [comment]
Right, and avx2 compilation mode should force the compiler to use those when applicable.

**Comment by AlexDBlack** [comment]
This appears to be workspace related somehow; disabling workspaces and this works (though possibly the workspace is just changing data alignment enough to trigger this...).

This is basically what is happening internally, the crash happens on the pullRows (but isn't reproducible using this code)
```
            INDArray in = Nd4j.create(DataType.FLOAT, new long[]{5, 50, 13}, 'f');
            INDArray reshape = in.reshape('f', 250, 13);
            int[] idx = new int[13];
            for (int i = 0; i < idx.length; i++) {
                idx[i] = 12 - i;  //Gives values 12, ..., 0
            }

            INDArray out = Nd4j.create(DataType.FLOAT, new long[]{250, 13}, 'f');
            INDArray pullRows = Nd4j.pullRows(reshape, out, 0, idx);
            pullRows.dup();
```

**Comment by raver119** [comment]
Easy fix then.

**Comment by AlexDBlack** [comment]
I'm seeing what I assume is the exact same issue, this time with sum op:
Same symptoms, the 1 byte array creation + workspaces is required to reproduce.
This time however it's reproducible for me on Windows (native).
```
    @Test
    public void test(){
        WorkspaceConfiguration initialConfig = WorkspaceConfiguration.builder().initialSize(10 * 1024L * 1024L)
                .policyAllocation(AllocationPolicy.STRICT).policyLearning(LearningPolicy.NONE).build();
        MemoryWorkspace workspace = Nd4j.getWorkspaceManager().getAndActivateWorkspace(initialConfig, "WS");

        for( int j=0; j<100; j++ ){

            try(MemoryWorkspace ws = workspace.notifyScopeEntered()) {

                for (int x = 0; x < 10; x++) {
                    System.out.println("Start iteration (" + j + "," + x + ")");
                    INDArray arr = Nd4j.linspace(1,10,10, DataType.DOUBLE).reshape(1,10);
                    INDArray sum = arr.sum(true, 1);
                    Nd4j.create(DataType.BOOL, x+1);        //NOTE: no crash if set to FLOAT/HALF, No crash if removed entirely; same crash for BOOL/UBYTE
                    System.out.println("End iteration (" + j + "," + x + ")");
                }
            }
        }
    }
```

https://gist.github.com/AlexDBlack/147a7cb6b61c3fe010790b4a94921dff

**Comment by AlexDBlack** [comment]
@Geokats Fix has been merged, it should be available on snapshots in a few hours.
Thanks for reporting.

**Comment by Geokats** [comment]
Works like a charm now.
Thank you everyone for your help!
