### ISSUE TITLE
Memory leaks when training MultiLayerNetwork using StatsListener

### ISSUE THREAD

**Issue by printomi** [deeplearning4j/deeplearning4j#7064]
#### Issue Description

Memory leaked when training `MultiLayerNetwork` using `StatsListener`. One does not have to attach-detach `StatsStorage` on UIServer to reproduce this leak. free Java heap space starts to decrease.
~~I have experienced memory leaking in UIServer: if I sequentially train a model and attach-detach StatsStorage on UIServer (either InMemoryStatsStorage or FileStatsStorage) one after another, free Java heap space starts to decrease.~~

I get this error at the end:
```
Exception in thread "ADSI prefetch thread" java.lang.OutOfMemoryError: Java heap space
```

Here is a [gist](https://gist.github.com/printomi/c50cb1d19288345b7346d268b8972196) with simplified code and output.
~~Here is a [gist](https://gist.github.com/printomi/ef291dfe6feada80479d581934e3704d) with minimal code and output.~~
Running manually `testStatsListener()` with VM parameters `-ea -Xms128M -Xmx256M -Dorg.bytedeco.javacpp.maxbytes=256M -Dorg.bytedeco.javacpp.maxphysicalbytes=512M` an OOM error happened around epoch 472.

#### Version Information

* Deeplearning4j version: 1.0.0-SNAPSHOT
* platform information: Windows, Java 8
* backend: CPU

#### Contributing

Any ideas, how can I track down this issue?

Edited after https://github.com/deeplearning4j/deeplearning4j/issues/7064#issuecomment-471546792

Aha! Link: https://skymindai.aha.io/features/ND4J-92

**Comment by printomi** [comment]
For me, it seems that #7085 did not solve the memory leak. 
In fact, getDefaultSession() here https://github.com/deeplearning4j/deeplearning4j/blob/1e0c048be849de2c6c77dbe7f1e6ac0f4d967d31/deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-play/src/main/java/org/deeplearning4j/ui/module/train/TrainModule.java#L193
should be after the next for loop, if I understand well.
Then, I would make `currentSessionID` and `currentWorkerIdx` volatile in `TrainModule`.
And last but not least, there was a `NullPointerException` from the second attached stats storage, that I could avoid by using the following lines in `getOverviewData()`, `getModelData(String str)`, and `getSystemData()`:
```java
        Long lastUpdate;
        if (lastUpdateForSession != null && currentSessionID != null) {
            lastUpdate = lastUpdateForSession.get(currentSessionID);
        } else {
            lastUpdate = -1L;
        }
```

Sadly, these changes only fixed the new errors, but did not help with the memory leak.

**Comment by AlexDBlack** [comment]
I was able to reproduce the leak and (after implementing fixes) confirm that all instances of TrainModule were correctly cleaned up once they were removed from the UIServer and all local references were removed. This was using JVM heap dumps (plus some System.gc() calls after removal) so I'm quite certain it's fixed (I also confirmed FileStatsStorage was cleaned up on your code using the same JVM heap dump approach).

However, looking at the profiler memory dump on your code, I am seeing greater than expected - and growing - memory use. It's not caused by incorrectly retained references to the StatsStorage instances, however. I'm still looking into it.

> should be after the next for loop, if I understand well.

Yes, looks like you're right about that, thanks, I'll fix that.

**Comment by printomi** [comment]
Similar to this issue #7125 , I saw that `LongBuffer` instances fill my heap after several training sessions attached to `UIServer`. I created heap dumps with jmap, and analyzed them with Eclipse MAT.

**Comment by printomi** [comment]
I saw circular references similar to the ones described by @SchmaR in #7125 . It seems, that it is not the sequential attach-detach of StatsStorage to UIServer that causes the memory leak. I [simplified my example](https://gist.github.com/printomi/c50cb1d19288345b7346d268b8972196), and I suspect that using `StatsListener` with `MultiLayerNetwork` causes the leak.

**Comment by printomi** [comment]
I close this issue, because #7316 seems to have fixed this. This issue is likely to be a duplicate of #7125 .
I checked this fix by running the code that previously failed with OOM, but now passes the test: [code, previous and current output](https://gist.github.com/printomi/c50cb1d19288345b7346d268b8972196).
