### ISSUE TITLE
Evaluation.accuracy formula

### ISSUE THREAD

**Issue by madhs53** [deeplearning4j/deeplearning4j#7067]
Looking at class org.nd4j.evaluation.classification.Evaluation.

The accuracy() method states it is using this formula:

     * Accuracy:
     * (TP + TN) / (P + N)

That is correct going by the accuracy formula stated here: https://en.wikipedia.org/wiki/Confusion_matrix

However, the code written for that method actually uses this formula:

TP / total_records_evaluated

This isn't the same thing.
Here's an example confusion matrix:

```
 0 1 2 3 4 5 6 7 8
-------------------
 6 0 0 0 0 0 2 0 0 | 0 
 0 0 1 2 0 0 0 0 0 | 1 
 0 3 1 0 0 0 2 0 0 | 2 
 0 7 1 0 0 0 0 2 0 | 3 
 0 5 0 0 7 0 0 0 0 | 4 
 2 2 0 0 1 1 0 0 0 | 5 
 0 0 1 0 0 4 0 0 0 | 6 
 0 0 0 0 0 0 0 0 0 | 7 
 0 0 0 0 0 0 0 0 0 | 8 
```

The accuracy according to the formula (TP + TN) / (P + N) = 84% (remember TN is quite high)
The accuracy produced by the code is 30%

I was wondering what your thoughts on this?

**Comment by AlexDBlack** [comment]
The code uses the sum of correct predictions divided by the number of total predictions.
That's a generalization of the binary accuracy (TP + TN) / (P + N) to the multi-class case (you'll note that even in this binary situation, accuracy is the sum along the diagonal of the confusion matrix divided by total number of predictions).

Your accuracy calculation for the provide confusion matrix is wrong.
The number of correct predictions is 15 (sum along the diagonal), the number of total predictions is 50. Therefore accuracy is 15/50 = 0.3.

FWIW our evaluation unit tests are here - all implementation are thoroughly tested and (in most cases) validated against both manual calculations and other libraries.
https://github.com/deeplearning4j/deeplearning4j/tree/master/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/evaluation

**Comment by madhs53** [comment]
Thanks.

My understanding is the diagonal on the confusion matrix is only true positives, not (true positives + true negatives).

For example, running an evaluation in DL4J, when I ran eval.trueNegatives().get(0), the answer is 40, and when I ran eval.truePositives().get(0), the answer is 6.

In the confusion matrix printed out by eval.confusionMatrix() , 6 is on the diagnal for label 0 (so true positive count), 40 is not represented in the confusion matrix diagonal.

 (TP + TN) / (P + N) overall for the evaluation is all True Positives + all True Negatives over all True & False Positives + all True and False Negatives.

**Comment by AlexDBlack** [comment]
"True negatives" is a binary evaluation metric. Strictly speaking, it does not apply for the multi-class case.
So what is actually being reported here is the true negatives of the 1 vs. N binarization of the multi-class case.
So truePositives().get(x) is the "correctly predicted X for examples with class X count"
and trueNegatives().get(x) is the "correctly predicted anything other than X for examples that are anything other than X"

**Comment by madhs53** [comment]
Thanks Alex, this is making sense to me now.
