### ISSUE TITLE
libnd4j: NDArray(*NDArray,...) constructor can be called unexpectedly

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#7069]
It is possible to have the following code:

```cpp
NDArray foo = bar(); // where bar() returns *NDArray
```

This will compile without any problems, but it will not do what you expect it to do, as it actually calls a constructor that is meant to create an empty array like the one that is given:

https://github.com/deeplearning4j/deeplearning4j/blob/master/libnd4j/blas/cpu/NDArray.cpp#L235-L241

This is possible due to that constructor having default values for all of its other parameters.

**Comment by raver119** [comment]
Misleading API ^^^

**Comment by shyrma** [comment]
Hi Paul

Thanks
problem has been solved
