### ISSUE TITLE
DeepLerning4j If the output classes are more than 18 we see an error:

### ISSUE THREAD

**Issue by Alexandr1111111** [deeplearning4j/deeplearning4j#7071]
If the output classes are more than 18 we see an error:
A fatal error has been detected by the Java Runtime Environment:
 EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe2390440b, pid=6024, tid=0x00000000000043e8 JRE version: Java(TM) SE Runtime Environment (8.0_201-b09) (build 1.8.0_201-b09) Java VM: Java HotSpot(TM) 64-Bit Server VM (25.201-b09 mixed mode windows-amd64 compressed oops)
Problematic frame:
 C  [msvcrt.dll+0x7440b]
Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
 An error report file with more information is saved as:
 D:\DeepLerning4j\dl4j-examples-master\hs_err_pid6024.log
Code:
`File trainData = new File(DATA_PATH.toString());

FileSplit train = new FileSplit(trainData, NativeImageLoader.ALLOWED_FORMATS, randNumGen);

ParentPathLabelGenerator labelMaker = new ParentPathLabelGenerator();

ImageRecordReader recordReader = new ImageRecordReader(height, width, channels, labelMaker); 
  
recordReader.initialize(train);
             
DataSetIterator dataIter = new RecordReaderDataSetIterator(recordReader, batchSize, 1, outputNum);
`
How can I fix it?

**Comment by raver119** [comment]
post that hs_err_pid6024.log please

**Comment by raver119** [comment]
cc @saudet ^^^

**Comment by saudet** [comment]
Please try with 1.0.0-SNAPSHOT, there are some thread-safety issues with OpenCV that have been worked around since the release of 1.0.0-beta3.

**Comment by Alexandr1111111** [comment]
I'm sorry. Create jar?

**Comment by AlexDBlack** [comment]
@Alexandr1111111  read this for information on how to use snapshots: https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots

**Comment by raver119** [comment]
Any time :)
