### ISSUE TITLE
textToWordSequence in KerasTokenizer fails with UnsupportedOperationException

### ISSUE THREAD

**Issue by aladjov** [deeplearning4j/deeplearning4j#7073]
#### Issue Description
Run-time error when processing text like this: "KINSHASA: Opposition leader Felix Tshisekedi"
The problem is triggered by the ":" because of the following two lines:  
      `  List<String> seqList = Arrays.asList(sequences);`
Arrays.asList creates an unmodifiable list which contains an empty element ""
       ` seqList.removeAll(Arrays.asList("", null));`
This line tries to modify the fixed list and throws UnsupportedOperationException

Please describe our issue, along with:
- expected behavior
 ["kinshasa", "opposition", "leader", "felix", "tshisekedi"]
- encountered behavior
UnsupportedOperationException

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
1.0.0-BETA3
* platform information (OS, etc)
Ubuntu 18
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

Easy fix would be to initialize the seqList like this: 
   `         List<String> seqList = new ArrayList<String>(Arrays.asList(sequences));`
Is there any contributing guidance or I should make Pull request directly. I did spotted some other bugs in the same module which I can try to fix and add some unit tests

**Comment by maxpumperla** [comment]
@aladjov thanks for spotting this. yeah, by all means go ahead and create a pull request. Ping me once you're ready, I'm happy to help and review.

**Comment by farizrahman4u** [comment]
Fixed #7500

**Comment by agibsonccc** [comment]
@farizrahman4u https://github.com/deeplearning4j/deeplearning4j/blob/fc116f9e08a8b264c60c45cbba981c144a962120/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/preprocessing/text/KerasTokenizer.java#L165 same issue here. Arrays.asList can't have things removed from it in general.
