### ISSUE TITLE
SameDiff/Libnd4j: Add summary statistics / debugging op

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7078]
Use case: inpecting/evaluating/debugging network state.
Suppose I have some issue in my network (NaNs, infinities, all zeros, weird loss value etc) and I don't know why.

Knowing the following values for each array (parameters, activations) would be useful:

- Min, max, mean, standard deviation
- Count zero, count positive, count negative, count inf, count NaN

Of course, each of these can easily be calculated as separate ops. However, my thinking is that having these implemented as a single op would be many times faster (depending on how it was implemented at the c++ level) than running 9 individual ops on every array.

Aha! Link: https://skymindai.aha.io/features/ND4J-48

**Comment by raver119** [comment]
This stuff was implemented, and available as Nd4j.getExecutioner().inspectArray();
