### ISSUE TITLE
DL4J UI: Add multi-session support

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7110]
Following on from this discussion: https://github.com/deeplearning4j/deeplearning4j/issues/7103#issuecomment-460228925
@printomi

> @AlexDBlack Yes, I want to work on this, and I would be happy to contribute to DL4J with this. My primary goal is not only training multiple models attached to the same UI, but also loading historical training results with given session ID.
> I would do this by:

> 1. Modifying TrainModule so that it holds multiple StatsStorage instances mapped to session IDs. (Session ID can be set with StatsListener.setSessionID() before training, that is how I give unique IDs to my training statistics.)

This is already supported: 
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-play/src/main/java/org/deeplearning4j/ui/module/train/TrainModule.java#L89

i.e., all attached StatsStorage instances are present in that map. Key is the session ID, value is the StatsStorage instance that contains data for that session ID. Each StatsStorage instance can contain data for more than one session.

> 2. Adding PlayUIServer a custom StatsStorage loader. This would handle session IDs not already loaded.

Currently, the way to make data available to the UI is to attach it (UIServer.getInstance().attach()). Is the idea here to allow loading of stats storage directly from the UI?
i.e., point it to a file, and do the attach internally? If so, sounds good to me :+1:
We'd need some way to detach though. Longer-lived servers may require some sort of auto detach (based on time/usage) to avoid memory leaks (i.e., if user forgets to detach their session).

> 3. Making an option for hiding session selector dropdown from Java code, to separate users.

I think that would require more substantial changes on the backend. It's singleton/single user design pretty much everywhere.
If we can work out a way to do this, I'd be happy to add it, as long as the current single user type design is retained (as that's what most users need - don't want to make that less user friendly).

> 4. If these work properly, I would insert user authentication somehow, to get a truly multi-user UI server.

This should probably be a separate PR, maybe even with a (brief) written proposal posted first to make sure it's OK before you go through the effort of implementing it.
I'm not opposed to having it in principle, but would want to think carefully about the design first if we're going to be responsible for maintaining it :)

**Comment by printomi** [comment]
Thanks @AlexDBlack for opening this issue. I will create an alternative to `PlayUIServer`, inheriting as much as possible.

Following your advice, I would rewrite URL-s to include session ID like `/train/overview` to `/train/overview/:sessionId`. The multi-user variant of `TrainModule` would know the session ID from the URL, not from the static `currentSessionID` field. I would copy and modify some .js and .html resources to rewrite URLs. (Copy-paste "inheritance" is not so nice here, so I would like to find a better solution.)

>> 1. Modifying TrainModule so that it holds multiple StatsStorage instances mapped to session IDs...

> This is already supported:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-play/src/main/java/org/deeplearning4j/ui/module/train/TrainModule.java#L89

OK, I was wrong. This point is not needed.

>> 2. Adding PlayUIServer a custom StatsStorage loader. This would handle session IDs not already loaded.

>Currently, the way to make data available to the UI is to attach it (UIServer.getInstance().attach()). Is the idea here to allow loading of stats storage directly from the UI?
i.e., point it to a file, and do the attach internally? If so, sounds good to me 👍

I think of an `interface` that would be called to get the `StatsStorage` from my storage system of choice (e.g. database, filesystem). Classes implementing this interface can load `StatsStorage` by session ID.

> We'd need some way to detach though. Longer-lived servers may require some sort of auto detach (based on time/usage) to avoid memory leaks (i.e., if user forgets to detach their session).

Yes, unloading (detaching) a session could be automatic, if the user has closed the browser tab for a defined time.

>> 3. Making an option for hiding session selector dropdown from Java code, to separate users.

>I think that would require more substantial changes on the backend. It's singleton/single user design pretty much everywhere.
If we can work out a way to do this, I'd be happy to add it, as long as the current single user type design is retained (as that's what most users need - don't want to make that less user friendly).

Yes, I would only extend the current `PlayUIServer`, retaining the current single user type design. 
In train.js, we have this: https://github.com/deeplearning4j/deeplearning4j/blob/344bdde4d40205c7e489d4f8e20d5327e6f966bc/deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-play/src/main/resources/deeplearning4jUiAssets/js/train/train.js#L39
A quick solution would be to send only the current session at `/train/:sessionId/sessions/info`. (After rewriting the URL-s, this is easy.)

**Comment by printomi** [comment]
I dived into the code, made progress, but I have some questions.
1. There are routes that are not used anywhere in the code:
    - /train/sessions/all (in `TrainModule`)
    - /train/workers/currentByIdx (in `TrainModule`)
    - /lang/getCurrent (in `PlayUIServer`)
May I remove them?

2. I would like to fix the link with `class="brand"` in TrainingModel.scala.html and in TrainingSystem.scala.html, but I could not generate scala page templates. I followed the instruction here https://github.com/deeplearning4j/deeplearning4j/blob/b8693d188afbc9d1664d9635f26cb711bd7994f7/deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-play/pom.xml#L59
Running `mvn compile` did not re-generate the template files.

3. I would synchronize all functions of TrainModule, that are called by the router. My reasons are the following: TrainModule has some fields, that needs synchronization, and I think that method-level sync is appropriate here. According to JavaDoc of Collections.synchronizedMap, "It is imperative that the user manually synchronize on the returned map when iterating over any of its collection views". 
Is this OK?

**Comment by printomi** [comment]
I would change this point:
> 3. Making an option for hiding session selector dropdown from Java code, to separate users.

To this:
3. Hiding session selector dropdown in multi-session mode, to separate users.

In multi-session mode, i would always hide the session selector dropdown. I have already implemented this by sending only the selected session's info to the front-end, if in multi-session mode.

About language setting in multi-session mode:
If I don't change the current implementation, the language setting will remain global, so changing language in one session affects the other sessions. It would be more elegant to have separate language setting for each session. I would add a session-to-language map to `I18NProvider` that would be used in multi-session mode.

I fixed an error that prevented page load with "uk" language, that does not have any language files. Now, it falls back to `FALLBACK_LANGUAGE`, without any error. Shall this language (uk) remain in the scala.html template code?

**Comment by AlexDBlack** [comment]
Apologies for the delay in replying.

> I will create an alternative to `PlayUIServer`, inheriting as much as possible.
> I would copy and modify some .js and .html resources to rewrite URLs. (Copy-paste "inheritance" is not so nice here, so I would like to find a better solution.)

That's definitely not an approach I am in support of, for a number of reasons:
(a) It's unnecessary: I don't see why we need to duplicate and slightly modify the existing classes. I would much prefer a UI design that is suitable for both use cases.
(b) It increases the maintenance burden: any changes to one UI needs to be ported to another
(c) It's confusing for users: we'll have 2 UIs - and users will need to understand the (minor) differences between each

Can we look at how to support multiple sessions whilst having only a single UI?

> I think of an `interface` that would be called to get the `StatsStorage` from my storage system of choice (e.g. database, filesystem). Classes implementing this interface can load `StatsStorage` by session ID.

That sounds reasonable. Some sort of "load StatsStorage" request coming from the front-end that loads the appropriate type + file.


> Yes, unloading (detaching) a session could be automatic, if the user has closed the browser tab for a defined time.

:+1:


---

> There are routes that are not used anywhere in the code:
> * /train/sessions/all (in `TrainModule`)
> * /train/workers/currentByIdx (in `TrainModule`)
> * /lang/getCurrent (in `PlayUIServer`)
>  May I remove them?

I don't see any harm in removing these, given they aren't currently used.




> 2. I could not generate scala page templates

Read this: https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-ui-parent/deeplearning4j-play/developerReadme.md
The profile is not enabled by default, to avoid regenerating the templates on every single compile.

> 3. I would synchronize all functions of TrainModule, that are called by the router.

That will essentially make the backend single-threaded, which is likely to become a performance bottleneck especially given the point here is to support multiple sessions.
If we need to add synchronization, finer grained synchronization would be better (shared read locks, exclusive write locks etc)


---


> If I don't change the current implementation, the language setting will remain global,

Yes, that will of course need to change also.

> I fixed an error that prevented page load with "uk" language, that does not have any language files.

FYI those are ISO639 language codes - "uk" being Ukranian. Looks like we never got around to implementing that, so yes, it can be removed as an option.

**Comment by printomi** [comment]
Thanks for the response.

>> I will create an alternative to `PlayUIServer`, inheriting as much as possible. ...

> That's definitely not an approach I am in support of, for a number of reasons: ...

Yes, I agree. I dropped this idea, and I managed to enable multi-session mode within `PlayUIServer`. There would be a command-line option `--multiSession true` which would activate this mode. However, I have only enabled multi-session in `TrainModule` and `DefaultModule`, until now. I guess, that the selected mode (single/multi-session) should be used in `ConvolutionalListenerModule` also?

>> I think of an `interface` that would be called to get the `StatsStorage` from my storage system of choice (e.g. database, filesystem). Classes implementing this interface can load `StatsStorage` by session ID.

> That sounds reasonable. Some sort of "load StatsStorage" request coming from the front-end that loads the appropriate type + file.

I think, we don't understand each other. I think of a session ID passed in the URL as usual, but the StatsStorage not yet loaded in the UI. Then comes the user's `StatsStorageProvider`, that would load a the StatsStorage that contains the given session ID. The UI server will then try to attach this StatsStorage, and the users get their historical training statistics instantly, only by visiting an URL like `/train/:sessionId/overview`. Do you accept this solution?

> Yes, unloading (detaching) a session could be automatic, if the user has closed the browser tab for a defined time.

I did not build automatic detaching functionality into `PlayUIServer`, based on last browser activity, as I planned. Instead, I created a test code with a `StatsStorageProvider` that would detach the to-be-loaded StatsStorage from the UI, after a given time interval. With "instant auto-attach", this would be an acceptable solution for me, but tell me, if you think that this functionality should be an easy to use option of `PlayUIServer`. I could implement that functionality, even with browser activity tracking.

>>3. I would synchronize all functions of TrainModule, that are called by the router.

> That will essentially make the backend single-threaded, which is likely to become a performance bottleneck especially given the point here is to support multiple sessions.
If we need to add synchronization, finer grained synchronization would be better (shared read locks, exclusive write locks etc)

Yes, method-level synchronization would make HTTP calls run serial, which can be a bottleneck. But, without synchronization, undefined behavior can occur when there are overlapping writes. Maybe, locks would be the best solution here, I haven't used them, yet. I would suggest using synchronized blocks, synchronized on the specific fields, e.g. `TrainModule.knownSessionIDs`.

**Comment by printomi** [comment]
To help decision about synchronization in `TrainModule`, here are the fields that are accessed concurrently, and:
- are written without synchronization: 
    - `currentSessionID` (in `setSession`): I would make this field `volatile`.
    - `currentWorkerIdx` (in `setSession(String newSessionID)` and `setWorkerByIdx`): I would make this field `volatile`.
- are written with field-level synchronization:
    - `knownSessionIDs` (in `reportStorageEvents`, `onAttach`, `onDetach`)
    - `lastUpdateForSession` (in `reportStorageEvents`, `onDetach`)
    - `workerIdxToName` (in `onDetach`, `getWorkerIdForIndex` (called from `getOverviewDataForSession`))
    - `workerIdxCount` (in `onDetach`, `getWorkerIdForIndex` (called from `getOverviewDataForSession`))

**Comment by printomi** [comment]
Tomorrow, I would summarize the proposed changes in a [WIP] PR so that you can review the code, and we can talk about the remaining arguments.

**Comment by printomi** [comment]
Here is the PR: #7185 I think, it is ready.
@AlexDBlack please, review.
