### ISSUE TITLE
DL4J: RNN masks sometimes not being applied?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7115]
As reported in gitter by @C4N4D4M4N

> @AlexDBlack I made a test model for the issue I posted earlier where RNN model ignored the masks. It's quite configurable, and works with multiple inputs/labels. Here's the Gist: https://gist.github.com/C4N4D4M4N/7c0596bb751c2144df246d8b375d8334.
> The results of the first two tests are identical, but test #1 has no masked data and test #2 has all masked data. Test #3 is with all values masked, and all values set to 0, and it shows that the value of the data, masked or not, is still being considered by the training algorithm.
> These tests were done in both beta-2 and beta-3.

**Comment by AlexDBlack** [comment]
@C4N4D4M4N Turns out that yes there was an issue here with LastTimeStep layer and masks
I've done two things:
(a) reproduced and fixed the issue
(b) I'de also added a check for the "all masked out" case - an exception will now be thrown if mask is all 0s for a layer (I think that's the only reasonable approach here - there is no last time step if there is no non-masked input data)

Fix is here and will be merged soon: https://github.com/deeplearning4j/deeplearning4j/pull/7169

**Comment by C4N4D4M4N** [comment]
@AlexDBlack Awesome, thanks a lot for looking into this. How will I know when the fix is applied, will it just be whenever the next DL4J version is released?

**Comment by AlexDBlack** [comment]
Once merged, the fix will be available on snapshots (it usually takes a few hours to build and upload).
https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots

Otherwise yes, it will be in the next release (not sure on the date yet, but more than a few weeks for that most likely).
