### ISSUE TITLE
ND4j: Memory leak if calling INDArray.getRow()

### ISSUE THREAD

**Issue by SchmaR** [deeplearning4j/deeplearning4j#7125]
#### Issue Description

Hi,
I'm working on the current snapshot build of DL4J/ND4J. If I call INDArray.getRow() this creates LongBuffer, AtomicBoolean and ArrayList instances which the garbage collector can't discard. This behavior leads finally to an OutOfMemoryException in the heap space. I encounter this problem if running a CpuBackend.

This error is not happening in Beta3. I have not tested if it is present on CUDA.

You can find minimal example code for reproduction here: https://gist.github.com/SchmaR/5291bf21d812ac020307251eb4cdcf97

While I was investigating the problem, I noticed that it might be linked to a reference in DirectShapeInfoProvider.longCache, which seems to hold the last existing reference to the LongBuffer objects. Attached you find screenshots showing the reference chain as well as the stack trace of the initialitation of the LongBuffer objects.

##### Backend Configuration Log
```
16:29:34.633 [main] INFO  org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
16:29:35.346 [main] INFO  org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 4
16:29:35.608 [main] INFO  org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 4
16:29:35.616 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Linux]
16:29:35.617 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [1.8GB];
16:29:35.617 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [MKL]
```

![basendbufferstacktrace](https://user-images.githubusercontent.com/1245103/52423362-3753b700-2af8-11e9-976d-6b1847b08c7a.png)

![longbufferrefferingobjects](https://user-images.githubusercontent.com/1245103/52423395-4dfa0e00-2af8-11e9-9a39-041bfb4b1726.png)

![longbufferprofiler](https://user-images.githubusercontent.com/1245103/52423430-6833ec00-2af8-11e9-9e37-6df8882f74ab.png)

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 1.0.0 SNAPSHOT build: nd4j-api-1.0.0-20190207.151315-14704.jar
* platform information: Ubuntu 18.10, 64 Bit, Intel I7
* ~CUDA version, if used~
* ~NVIDIA driver version, if in use~

#### Contributing

If I can help to figure out what's going wrong let me know.

Aha! Link: https://skymindai.aha.io/features/ND4J-57

**Comment by raver119** [comment]
Not a bug.

Shape buffers are cached, reused. And never released. And since they are very small, you have to do something VERY unusual to make a problem out of that.

**Comment by raver119** [comment]
So, please tell us what you're doing there in order to help you.

**Comment by raver119** [comment]
Or, you mean that cache is broken somehow?

**Comment by raver119** [comment]
No, i've checked with debugger - after 100k iterations there's only 4 shapes in cache, and they are perfectly reused.

**Comment by raver119** [comment]
![nomachine - dev box 2_7_2019 19_38_57](https://user-images.githubusercontent.com/12250879/52426931-08493f80-2b10-11e9-9173-f932515f47dc.png)

**Comment by SchmaR** [comment]
Hmm, if I run the code in the gist on my machine I end up with a large amount of LongBuffers which are consuming all of my heap memory. I don't face the behavior on beta3 but in the current snapshot. 

Is there any information I could provide which could help to figure out what's going wrong?

**Comment by raver119** [comment]
Where exactly you see those LongBuffers?

**Comment by SchmaR** [comment]
If I either use Visual JVM or the Memory profiling view in IntelliJ. According to Visual JVM the buffers are consuming the most of my memory. If I trigger a garbage collection step in Visual JVM none of the LongBuffers are cleaned up. (in the snapshot build) If I do the same on beta3 the LongBuffers get discarded and I don't run out of heap memory while iterating over `indArray.getRow(i % 3)`.

**Comment by raver119** [comment]
Obviously, i'm using snapshots too, and i can't reproduce behavior you're describing. Maybe you're running some different code?

**Comment by AlexDBlack** [comment]
This is what I'm seeing (Snapshots, master, windows 10, native):
https://gist.github.com/AlexDBlack/83041fa0511954f97cd85e9a6544f6cb
![image](https://user-images.githubusercontent.com/2360237/52449246-b85b8e80-2b8a-11e9-8393-e045c289ba48.png)

---
---

Here's the same thing slightly modified to add GC. The memory snapshot was collected after "DONE GC" was printed in the code.

https://gist.github.com/AlexDBlack/db9b37bd041628f6c32b4acb64c7a1b2

![image](https://user-images.githubusercontent.com/2360237/52449512-be9e3a80-2b8b-11e9-8391-32205a8b4caa.png)

**Comment by raver119** [comment]
Hmmm.... wrappedBuffer abused somewhere?
