### ISSUE TITLE
Guava jar conflict with Hadoop

### ISSUE THREAD

**Issue by jpatanooga** [deeplearning4j/deeplearning4j#713]
Given our proclivity for running on spark and Hadoop, we need to address the situation where our bundled version of the Guava jar is conflicting with the one in cdh / hdp.

CDH5: guava-11.0.2.jar

DL4J: guava-18.jar

I think @agibsonccc suggested a fix here, but I just wanted to get this officially on the list so we can figure out the best way to triage it. Need to get this in before the 0.4 big release goes out.

**Comment by smarthi** [comment]
This is a standard problem I had seen across several projects, the guava
version conflict - no idea as to why the hadoop vendors had never upgraded
their guava jars in years.

One solution is to shade out the jars.

**Comment by EronWright** [comment]
To elaborate on the shading idea - [docs](https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html),  [example 1](https://github.com/jsevellec/cassandra-unit/blob/master/cassandra-unit-shaded/pom.xml), [example 2](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-hbase-1.0/pom.xml).   Some libraries aren't friendly to shading, but most are.

**Comment by jpatanooga** [comment]
Good stuff. Who wants to do the pom surgery? =)

**Comment by jpatanooga** [comment]
I'm gonna give this a test on my local app project, and see how my uber jar looks. Will report back soon. thanks for that example @EronWright

**Comment by EronWright** [comment]
@jpatanooga It occurs to me that one cannot shade a dependency that is part of the public API of a given library.    Guava might be an implementation detail within dl4j or might be visible; you'll need to check.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/718
https://github.com/deeplearning4j/nd4j/pull/391

Test these and see what comes up.

**Comment by agibsonccc** [comment]
![screenshot-7](https://cloud.githubusercontent.com/assets/1144306/9879137/fb0e3a64-5c00-11e5-805d-f5496bbdafa0.png)

**Comment by agibsonccc** [comment]
![screenshot-8](https://cloud.githubusercontent.com/assets/1144306/9879178/2851647e-5c01-11e5-80f8-abe286abe7b1.png)


Also looks clean

**Comment by agibsonccc** [comment]
Here's hadoop
![screenshot-9](https://cloud.githubusercontent.com/assets/1144306/9879213/598463a2-5c01-11e5-9ade-14e8168a9b0d.png)

**Comment by agibsonccc** [comment]
#718

**Comment by EronWright** [comment]
@jpatanooga what specific issue did you see in CDH5?    

Downgrading to Guava 11 is proving to be a problem in other respects, e.g. with dropwizard.   Shading it is also proving difficult because Guava types are on the public API of ND4J and DL4J.

**Comment by jpatanooga** [comment]
You can't use a different version of guava w a Hadoop application.
Confirmed this w Cloudera engineering team.

Adam downgraded guava to get around it
