### ISSUE TITLE
DL4J/SameDiff: Add GELU activation function (+ derivative)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7131]
Used in BERT:
https://arxiv.org/pdf/1810.04805.pdf
> We use a gelu activation (Hendrycks and Gimpel, 2016) rather than the standard relu, following OpenAI GPT

GELU is defined in:
https://arxiv.org/pdf/1606.08415.pdf
> We can approximate the GELU with
> ```0.5x(1 + tanh[sqrt(2/π)(x + 0.044715x^3)])```
> or
> ```x*sigmoid(1.702*x)```

The sigmoid version is faster but apparently less accurate: https://github.com/hendrycks/GELUs
The paper uses the former for experiments, but I would suggest we implement the latter (sigmoid version) as it is faster to compute and likely accurate enough.

![image](https://user-images.githubusercontent.com/2360237/52515908-1b761f80-2c76-11e9-8131-a91f5920948f.png)

Edit: note that this doesn't seem to be required for TF import of BERT. I assume they have implemented the op naively from multiple ops in that version, rather than implementing it as one discrete operation.

**Comment by raver119** [comment]
Implemented
