### ISSUE TITLE
Question regarding OOM, maxPhysicalBytes, and ND4J GC, on multi-GPU

### ISSUE THREAD

**Issue by madhs53** [deeplearning4j/deeplearning4j#7138]
Hi all,

I'm running on 4 GPUs. Details below:

```
Number of GPUs Detected                 4
  Name                           CC                Total Memory              Used Memory              Free Memory
  Tesla P100-SXM2-16GB           6.0     15.90 GB (17071734784)     6.65 GB (7135559680)     9.25 GB (9936175104)
  Tesla P100-SXM2-16GB           6.0     15.90 GB (17071734784)     6.00 GB (6447693824)    9.89 GB (10624040960)
  Tesla P100-SXM2-16GB           6.0     15.90 GB (17071734784)     6.64 GB (7131365376)     9.26 GB (9940369408)
  Tesla P100-SXM2-16GB           6.0     15.90 GB (17071734784)     6.29 GB (6753878016)    9.61 GB (10317856768)

```

**Question 1:**
My understanding was that -Dorg.bytedeco.javacpp.maxbytes should be set no larger than the amount of GPU memory available. Is this for a single GPU or all of them combined?

**Question 2:**
If we set Nd4j.getMemoryManager().togglePeriodicGc(false);, will a GC be triggered "as needed"? Or is there the potential of memory errors due to memory not get collected?

**Question 3:**
I've attached a memory crash dump. Based on our environment described in the dump, what would be an advisable setting for -Dorg.bytedeco.javacpp.maxbytes to make full use of our 4 GPUs at 15.9 GB each?

[dl4j-memory-crash-dump-1549798444976_1723.txt](https://github.com/deeplearning4j/deeplearning4j/files/2849570/dl4j-memory-crash-dump-1549798444976_1723.txt)

Thanks.

**Comment by AlexDBlack** [comment]
We mirror memory on the host and device, so for multiple GPUs you'll need to have N x single-GPU memory set as javacpp max bytes if you want to be able to max them all out simultaneously. (i.e., set javacpp maxbytes equal to the sum of device memories).

With togglePeriodicGC(false) - as long as you're using workspaces (which are enabled by default in DL4J), you should be OK. However, to be safe (especially if you have custom DL4J/ND4J code not using workspaces, or are using methods such as output that return detached arrays) I'd recommend setting it somewhere between 10 and 30 seconds.

**Comment by madhs53** [comment]
Thanks Alex.

Quick question. If I extend BaseDatasetIterator and use a custom extension of BaseDataFetcher, which performs ND4J.create(double[]), will this utilize the workspace configuration (ie. re-use the INDArrays each batch or epoch?). Or do we need to use specific iterators (like RecordReaderDataSetIterator)?

We are trying to avoid using GC where possible as we've seen quite a slow down when it's enabled at regular intervals.

**Comment by AlexDBlack** [comment]
I wouldn't recommend extending BaseDatasetIterator/BaseDataFetcher - it's only still around for legacy things like MNIST.

More generally, AsyncDataSetIterator (which is used by default in MultiLayerNetwork/ComputationGraph  whenever you call fit) uses its own internal workspace (a type of cyclical workspace, a bit different to the standard ones). If you implement your own iterator, you get the benefit of workspaces without having to worry about manually managing workspaces/memory. The only thing to be aware of there is that if you have long-lived arrays (stored in a field or whatever) you'll need to make sure those are detached/scoped out (otherwise you'll get a workspace exception.

**Comment by madhs53** [comment]
Thanks Alex.

We are seeing really good training speeds with our custom BaseDatasetIterator & Fetcher implementations. In contrast when we tried using a custom RecordReader with RecordReaderDataSetIterator it was much slower. Likely we didn't implement correctly or optimally though (for next(int) we were returning lists of DoubleWritable).

For example for the same dataset and batch size, with our iterator we were doing a single iteration of 128 examples every 50ms, whereas with the recordreader it was about 20 seconds. Not sure what we did wrong with the recordreader but we are happy with the performance of the custom iterator. You mentioned it's not recommended - are there any issues with using this? Could this abstraction be deprecated in future?

**Comment by madhs53** [comment]
Hi Alex, we are also using an EarlyStoppingTrainer, which doesn't seem to use an AsyncDataSetIterator to fetch datasets from the datasetiterator prior to calling network.fit(dataset). I guess for EarlyStoppingTrainers we need to wrap our own iterator with the AsyncDataSetIterator?
