### ISSUE TITLE
Datavec: ImageLoader.scalingIfNeed may missing channel scale when size is right

### ISSUE THREAD

**Issue by chentao106** [deeplearning4j/deeplearning4j#7149]
#### Issue Description

Please describe our issue, along with:
- ImageLoader may scale channel when width and height is suitable. 
- Channel was not scaled when width and height been -1 or suitable.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta2, also in 1.0.0-beta3
* platform information (OS, etc): Windows 10
* CUDA version, if used: None
* NVIDIA driver version, if in use: None

#### Contributing
In function:
org.datavec.image.loader.ImageLoader#scalingIfNeed(java.awt.image.BufferedImage, long, long, boolean)
This code:
```java
if (image.getType() == BufferedImage.TYPE_4BYTE_ABGR || image.getType() == BufferedImage.TYPE_3BYTE_BGR)
```
should change to:
```java
if (channels == image.getType())
```

**Comment by saudet** [comment]
Could you send a pull request with the proposed changes? Thanks!
