### ISSUE TITLE
extract_image_patches seems to be wrong

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#7150]
CPU implementation of extract_image_patches seems to be wrong.
For the input patches shape of `[3, 3, 4, 3, 12, 3, 1, 16384, -1, 99]` I see generated coords like `[2, 4, 1]` which is obviously wrong.

**Comment by raver119** [comment]
Actually not an issue.

**Comment by AlexDBlack** [comment]
Actually, I did just remember this: https://github.com/deeplearning4j/deeplearning4j/issues/6958
Issue 18, our extract image patches implementation doesn't match TF output. Might be a separate issue to what you flagged here, however.

**Comment by raver119** [comment]
cc @shugeo

**Comment by shugeo** [comment]
There was an issue with indexing with 3D tensor.

**Comment by raver119** [comment]
Should've been fixed now.
