### ISSUE TITLE
ND4j: Is sparse matrix ops not supported for the snapshot 1.0.0 version?

### ISSUE THREAD

**Issue by zhangy10** [deeplearning4j/deeplearning4j#7153]
Hey, I am just wondering whether the sparse matrix operations is available in the current ND4j snapshot 1.0.0 version?  I found there was a ```BaseSparseNDArray``` available under the ```ndarry``` package, but it seems that the code has been completed. 

I am actually looking for a kind of sparse INDArray to keep big sparse weight matrix of hidden layers during training, and but I am not sure whether it is supported by DN4j. So, please any advice for that? Many thanks.

**Comment by raver119** [comment]
There's partial support for those. Usable with BLAS only. 

However, full sparse matrices support is the next big step in our roadmap for next iteration.
