### ISSUE TITLE
ND4J: Create empty arrays only once in Nd4j.empty(DataType)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7168]
Empty arrays are immutable. There's no point creating them more than once per datatype.
So let's have ND4J.empty(DataType) create them only one and return the same object for subsequent calls.

Aha! Link: https://skymindai.aha.io/features/ND4J-126

**Comment by raver119** [comment]
Hm, but technically that's exactly what happens:
1) data buffer isn't created
2) shapeInfo buffer is created/filled only once per data type. Subsequent calls will use the same shapeinfo

So, we obviously can make it work in a factory way, but it won't bring us too much performance gains.
