### ISSUE TITLE
MultiLayerNetwork.predict(DataSet) always throws IllegalStateException

### ISSUE THREAD

**Issue by chentao106** [deeplearning4j/deeplearning4j#7172]
#### Issue Description
MultiLayerNetwork.predict(DataSet) always throws IllegalStateException,
Detail method:
org.deeplearning4j.nn.multilayer.MultiLayerNetwork#predict(org.nd4j.linalg.dataset.api.DataSet)
Detail code:
```java
ret.add(i, dataSet.getLabelName(intRet[i]));
```
dataSet.labelNames is empty.
It seems dataSet.labelNames never add any label names.

Please describe our issue, along with:
- expected behavior: Return label names of test data.
- encountered behavior: Throws IllegalStateException

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta2, may also exists in 1.0.0-beta3(By compare code)
* platform information (OS, etc): Windows 10 Home China, 64-bit
* CUDA version, if used: With cuda9.2 but not used.
* NVIDIA driver version, if in use: 418.81 but not used.

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by AlexDBlack** [comment]
This behaviour is expected: If the DataSet does not contain a labels name list, it's not possible to return the predictions as one of the label name Strings.
https://github.com/deeplearning4j/deeplearning4j/blob/e5d14861fc70df8a7c5d99ace816146d0bb1412f/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.java#L2137

```
Preconditions.checkState(dataSet.getLabelNamesList() != null, "This method can only be used when the DataSet contains a label name list");
```

You can set the labels on the DataSet before calling this method, or use one of the other output/predict methods.
I'll close this as there is nothing to fix here.
