### ISSUE TITLE
SameDiff: add TF import support for (user defined functions?) in pb

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7178]
Here's an odd section from GPT-2 117M parameter model protobuf (text format):
```
library {
  function {
    signature {
      name: "convert_gradient_to_tensor_8rf1PQaJCP4"
      input_arg {
        name: "x_0"
        type: DT_FLOAT
      }
      output_arg {
        name: "x"
        type: DT_FLOAT
      }
      description: "Force gradient to be a dense tensor.\n\n    It\'s often faster to do dense embedding gradient on GPU than sparse on CPU.\n    "
    }
    ret {
      key: "x"
      value: "x_0"
    }
  }
}
```

Model is from https://github.com/openai/gpt-2 - download_model.sh and then manually frozen.

I'm not exactly sure what's going on here, but as far as I can tell from looking at the model, it's basically an identity operation other than the fact that it presumably changes array location from CPU to GPU?

If that's the case, then we can probably just add a mechanism like we have for Keras import in DL4J: the user specifies how the UDF should be handled (what it should be mapped to).

**Comment by treo** [comment]
Isn't this just a call to https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor?

I'd guess it comes from https://github.com/openai/gpt-2/blob/master/src/model.py#L135-L139
