### ISSUE TITLE
About DataType class

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#7182]
I use newest dl4j-beta3, and run a CNN example,

Load data....
Build model....
o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 32
o.n.n.Nd4jBlas - Number of threads used for BLAS: 0
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 7]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [3.5GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
o.n.l.j.o.e.CudaExecutioner - Device Name: [GeForce GTX 1080 Ti]; CC: [6.1]; Total/free memory: [11811160064]
o.d.n.m.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
o.d.n.l.c.ConvolutionLayer - Could not initialize CudnnConvolutionHelper
java.lang.Error: Unresolved compilation problems: 
	The import org.nd4j.linalg.api.buffer.DataType cannot be resolved
	DataType cannot be resolved to a variable
	DataType cannot be resolved to a variable
	DataType cannot be resolved to a variable
	DataType cannot be resolved to a variable
	DataType cannot be resolved to a type
	DOUBLE cannot be resolved to a variable
	FLOAT cannot be resolved to a variable
	INT cannot be resolved to a variable
	HALF cannot be resolved to a variable

The result is okay,
but my question is:
I can't find org.nd4j.linalg.api.buffer.DataType class in my all jar files, 
do we need this class???

**Comment by raver119** [comment]
You're mixing nd4j versions somewhere. beta3 and snapshot to be precise. Don't do that, and you'll be fine.

**Comment by raver119** [comment]
As in: either use 1.0.0-beta3 or 1.0.0-SNAPSHOT, but not both at the same project.

**Comment by raver119** [comment]
Hm. Why there's no version control messages present in the output log?

cc @AlexDBlack

**Comment by AlexDBlack** [comment]
> Hm. Why there's no version control messages present in the output log?

I can't say conclusively that there aren't based on that :)
In principle though sometimes it doesn't show due to:
(a) bad JAR construction (version info files not included in uber-jar)
(b) Environments where classpath scanning isn't possible/reliable
