### ISSUE TITLE
GloVe pre-trained model loading

### ISSUE THREAD

**Issue by RXminuS** [deeplearning4j/deeplearning4j#719]
Filing issue after some discussion on Gitter. Basically there needs to be some additional documentation/methods for loading (and saving) GloVe models in a similar fashion to the word2vec. Preferably works out of the box with http://nlp.stanford.edu/projects/glove/

Had some look at the WordVectorSerializer and it seems that it's simply a variation on the loadGoogleModel.

**Comment by mapf0000** [comment]
WordVectors wordVectors = WordVectorSerializer.loadTxtVectors(new File("glove.6B.50d.txt"));

seems to work for me, didn't do extensive testing tough

**Comment by agibsonccc** [comment]
I believe this has been fixed in the recent release.@RXminuS could you confirm? If this is the case, I will close this.

**Comment by chrisvnicholson** [comment]
added note to http://deeplearning4j.org/word2vec.html#glove

**Comment by silentsnooc** [comment]
@chrisvnicholson This example appears to be outdated. 

```java
WordVectors wordVectors = WordVectorSerializer.loadTxtVectors(new File("glove.6B.50d.txt"));
```
leads to a deprecation warning that recommends to use `readWord2VecModel()` or `loadStaticModel()` instead which is not able to "guess" the correct input file format:

```

Exception in thread "main" java.lang.RuntimeException: Unable to guess input file format
	at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadStaticModel(WordVectorSerializer.java:2456)
	at org.ema.server.core.App.main(App.java:29
```

**Comment by tomthetrainer** [comment]
I think our NLP docs can all be updated, I will see if I have an open ticket on that, if not I will add one

**Comment by tomthetrainer** [comment]
There it is.. #2701

**Comment by bjonnh** [comment]
loadTxtVectors say: " Please, consider using readWord2VecModel() or loadStaticModel() method instead" 

Does that work with Glove too?

**Comment by raver119** [comment]
Yep, should work. 

With best regards,
Vyacheslav K.
