### ISSUE TITLE
fitHelper() method

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#7194]
In fitHelper() method of MultiLayerNetwork:

if (iterator.asyncSupported()) {
            iter = new AsyncDataSetIterator(......            
        } else {
            iter = iterator;
        }

Hmm,I think it can add a condition:
if (iterator.asyncSupported() && !(iterator instanceof AsyncDataSetIterator)) {	
   ...

**Comment by AlexDBlack** [comment]
Thanks for the suggestion, but your condition is identical to what is already implemented - asyncSupported() returns fals for all AsyncDataSetIterator instances.
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-data/deeplearning4j-utility-iterators/src/main/java/org/deeplearning4j/datasets/iterator/AsyncDataSetIterator.java#L187-L203

**Comment by Charele** [comment]
Okay,I see.
