### ISSUE TITLE
Extreme slow at treeAggregate at ParameterAveragingTrainingMaster.java:801

### ISSUE THREAD

**Issue by gaoli1990** [deeplearning4j/deeplearning4j#7195]
#### Issue Description

Spark application UI found below:
![image](https://user-images.githubusercontent.com/13748117/52998338-03648400-345e-11e9-9081-c581d1eeac7b.png)

the Executors information is:
![image](https://user-images.githubusercontent.com/13748117/52995531-e461f400-3455-11e9-8377-fee1983b82e3.png)

the main code found below:
`ComputationGraphConfiguration` can be found in [https://github.com/HongZhaoHua/jstarcraft-recommendation-1.0/blob/master/src/main/java/com/jstarcraft/recommendation/recommender/collaborative/ranking/DeepFMRecommender.java#L85](url)
, with the parameters we used for input is:
`Array((10, 4, 9, 2, 7, 21, 2, 6, 5, 8, 15, 12, 6, 60, 6, 12, 6, 21, 6, 5, 8, 66, 11, 51, 12, 51, 11, 51, 11, 51, 502, 502, 502, 8, 57, 8, 51, 502, 97, 101, 99, 99, 97, 99, 101, 101, 101, 82, 99, 101, 101, 101, 101, 24, 101, 101, 101, 101, 101, 101, 56, 101, 101, 101, 97, 86, 101, 101, 9, 101, 5, 101, 101, 48, 101, 72, 42, 101, 101, 13, 13, 101, 101, 101, 101, 101, 101, 101, 101, 9, 101, 71, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 4, 101, 14, 101, 101, 72, 73, 101, 101, 101, 101, 48, 45, 7, 5, 39, 101, 71, 5, 101, 42, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 99, 101, 8, 101, 101, 101, 101, 101, 101, 101, 62, 101, 101, 101, 101, 101, 67, 101, 101, 101, 101, 48, 101, 101, 101, 101, 101, 96, 101, 101, 101, 101, 101, 101, 101, 101, 95, 101, 101, 101, 101, 31, 101, 101, 94, 101, 101, 101, 101, 101, 101, 101, 98, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 99, 101, 101, 101, 101, 101, 101, 101, 101, 101, 50, 101, 47, 101, 101, 100, 101, 13, 101, 9, 28, 72, 71, 12, 17, 97, 89, 3, 13, 10, 33, 19, 15, 101, 101, 97, 101, 101, 89, 2, 77, 77, 77, 101, 101, 101, 101, 101, 12, 19, 2, 101, 101, 43, 101, 86, 101, 95, 36, 101, 101, 39, 3, 20, 12, 4, 4, 13, 2, 101, 4, 18, 6, 22, 101, 101, 101, 101, 39, 3, 69, 16, 101, 77, 101, 101, 101, 6, 9, 101, 9, 9, 9, 15, 101, 101, 101, 13, 101, 101, 13, 101, 101, 101, 82, 101, 97, 101, 101, 26, 12, 71, 50, 29, 26, 19, 14, 82, 3, 101, 3, 54, 17, 77, 37, 20, 90, 45, 101, 100, 89, 101, 95, 101, 101, 79, 101, 101, 96, 84, 85, 19, 53, 85, 101, 31, 13, 16, 28, 61, 12, 16, 101, 101, 16, 8, 96, 24, 38, 11, 48, 6, 28, 8, 77, 7, 42, 85, 38, 30, 100, 81, 37, 57, 2, 35, 53, 56, 36, 67, 57, 44, 34, 14, 51, 60, 100, 48, 59, 22, 35, 95, 65, 26, 8, 38, 34, 101, 80, 81, 100, 27, 57, 15, 61, 24, 35, 71, 101, 33, 50, 65, 95, 29, 92, 11, 13, 9, 45, 9, 40, 4, 4, 13, 32, 75, 75, 9, 9, 10, 91, 67, 24, 5, 5, 8, 24, 75, 84, 23, 58, 70, 86, 92, 43, 65, 101, 78, 88, 67, 101, 66, 78, 47, 18, 43, 24, 99, 96, 26, 60, 27, 2, 4, 85, 99, 70, 22, 61, 75, 81, 59, 100, 84, 101, 82, 50, 5, 68, 58, 52, 88, 57, 76, 52, 82, 81, 58, 82, 90, 35, 67, 64, 5, 78, 71, 101, 61, 76, 68, 41, 38, 43, 17, 57, 54, 42, 21, 29, 31, 99, 61, 68, 61, 35, 22, 72, 33, 63, 11, 17, 57, 61, 56, 96, 45, 57, 59, 16, 53, 3, 3, 27, 14, 24, 2, 6, 6, 97, 54, 6, 34, 26, 35, 96, 39, 14, 37, 29, 29, 85, 99, 99, 47, 20, 9, 77, 37, 25, 33, 25, 13, 91, 15, 35, 40, 80, 44, 13, 9, 25, 30, 57, 54, 47, 24, 31, 33, 6, 34, 5, 55, 22, 13, 33, 10, 32, 13, 22, 36, 10, 71, 11, 17, 7, 7, 9, 23, 10, 19, 32, 10, 22, 6, 13, 11, 25, 6, 12, 84, 32, 6, 44, 33, 18, 17, 13, 101, 57, 22, 6, 12, 101, 18, 4, 85, 35, 6, 16, 6, 6, 10, 9, 15, 9, 19, 44, 11, 17, 10, 10, 93, 12, 3, 14, 18, 47, 19, 96, 89, 20, 11, 15, 39, 33, 20, 9, 80, 101, 22, 11, 15, 32, 10, 16, 10, 27, 17, 100, 12, 11, 22, 16, 30, 52, 58, 58, 36, 84, 41, 101, 44, 80, 92, 99, 81, 101, 51, 40, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 24, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 100, 101, 101, 101, 101, 30, 30, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 99, 89, 101, 61, 101, 100, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 94, 101, 101, 101, 101, 101, 100, 101, 101, 101, 101, 99, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 98, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 100, 101, 100, 101, 101, 101, 101, 101, 89, 101, 101, 101, 98, 101, 101, 101, 101, 101, 98, 101, 99, 99, 101, 101, 101, 101, 101, 3, 101, 101, 85, 101, 100, 101, 99, 100, 101, 101, 80, 22, 2, 2, 21, 6, 2, 101, 101, 101, 99, 101, 101, 101, 101, 100, 8, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 101, 19, 83, 101, 101, 101, 95, 101, 7, 98, 70, 101, 101, 101, 101, 101, 101, 101, 56, 101, 98, 101, 54, 101, 81, 63, 101, 83, 93, 68, 73, 88, 101, 16, 2, 21, 1945, 2, 3, 3, 10, 3, 9, 39, 4, 7, 4, 3, 5, 6))`

`SparkComputationGraph` is obtained by:

    val trainingMaster = new ParameterAveragingTrainingMaster.Builder(1)
      .averagingFrequency(10)
      .workerPrefetchNumBatches(0)
      .batchSizePerWorker(5000)
      .rddTrainingApproach(RDDTrainingApproach.Direct)
      .saveUpdater(true)
      .repartionData(Repartition.Always)
      .build()

    val sparkNet: SparkComputationGraph = new SparkComputationGraph(sc, config, trainingMaster)
    sparkNet.setCollectTrainingStats(false)
    sparkNet

`the training data` (about 80w records) is processed as:
<pre>val trainingData = rawData
      .repartition(1000)
      .mapPartitions(iter => {
        iter
          .grouped(batchSize)
          .map(group => {
            val grouped = group
              .map(row => {
                val (inputStr, scoreStr) = row
                val input = inputStr.trim.split(",").map(e => e.toDouble)
                val score = scoreStr.toDouble
                (input, score)
              })
              .toArray

            val numberOfExamples = grouped.length
            val inputData: Array[INDArray] = new Array[INDArray](dimensionSizes.length + 1)
            inputData(dimensionSizes.length) = Nd4j.zeros(numberOfExamples, dimensionSizes.length)
            for(index <- dimensionSizes.indices) {
              inputData(index) = inputData(dimensionSizes.length).getColumn(index)
            }
            val outputData: INDArray = Nd4j.zeros(numberOfExamples, 1)

            for(i <- 0 until numberOfExamples) {
              val (input, score) = grouped.apply(i)
              for(dimension <- dimensionSizes.indices) {
                inputData(dimensionSizes.length).putScalar(i, dimension, input.apply(dimension))
              }
              outputData.put(i, 0, score)
            }

            val dataSet = new MultiDataSet(inputData, Array(outputData))
            dataSet.asInstanceOf[org.nd4j.linalg.dataset.api.MultiDataSet]
          })
      }) </pre>

and then fit the training data `sparkNet.fitMultiDataSet(trainingData)`

the version information is:
<nd4j.version>0.9.1</nd4j.version>
        <dl4j.version>0.9.1</dl4j.version>
        <dl4j.spark.version>0.9.1_spark_2</dl4j.spark.version>

        <nd4j.backend>nd4j-native-platform</nd4j.backend>
        <nd4j.backend.native>nd4j-native</nd4j.backend.native>

Thanks for your reply!

Aha! Link: https://skymindai.aha.io/features/ND4J-112

**Comment by treo** [comment]
The very first thing you should do, is update to 1.0.0-beta3, as 0.9.1 is now over a year old.

**Comment by gaoli1990** [comment]
> The very first thing you should do, is update to 1.0.0-beta3, as 0.9.1 is now over a year old.

Thanks. At Spark application UI, we click `treeAggregate at ParameterAveragingTrainingMaster.java:801`, we see that  
![image](https://user-images.githubusercontent.com/13748117/53067008-40d41a80-350d-11e9-830a-34fe8836af43.png)

Is it caused by the data skew or something?
