### ISSUE TITLE
Regarding Support of pre-learnt word embedding in Word2Ve

### ISSUE THREAD

**Issue by rsravan91** [deeplearning4j/deeplearning4j#7201]
Hi,
I am currently on MAC High Sierra (version 10.13.6) using dl4j version 0.9.1
I was wondering if dl4j supports pre-learnt word vectors to be plugged into Word2Vec models. More specifically I was looking at feature like the one provided in gensim intersect_word2vec_format wherein i can provide the option of locking merged vectors. 

https://tedboy.github.io/nlps/generated/generated/gensim.models.Word2Vec.intersect_word2vec_format.html

Please help if this functionality already exists.

**Comment by raver119** [comment]
As I've told you in email, we do have merge support, but do not have "locking" feature implemented yet.

**Comment by raver119** [comment]
Implemented/merged
