### ISSUE TITLE
Not able to import Keras model - HDF5-DIAG: Error detected in HDF5 (1.10.2)

### ISSUE THREAD

**Issue by maryam-k** [deeplearning4j/deeplearning4j#7206]
I have a saved Keras model that I can only read it as input stream. As KerasModelImport does not support reading HDF5 files from InputStream, I saved my input stream in a temporary file and then pass it to KerasModelImport. However, I get the following error:

HDF5-DIAG: Error detected in HDF5 (1.10.2) thread 0:
  #000: H5F.c line 511 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1604 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: H5Fsuper.c line 630 in H5F__super_read(): truncated file: eof = 212992, sblock->base_addr = 0, stored_eof = 216840
    major: File accessibilty
    minor: File has been truncated

java.lang.RuntimeException: H5Fopen failed

Can someone guide me what would be a potential solution to my issue?

**Comment by AlexDBlack** [comment]
First: what version of DL4J are you using?
Can you share the code you are using to export the stream and then read the file?

**Comment by maryam-k** [comment]
I am using 1.0.0-beta2 version.

byte[] bytes = modelResource.getData();
InputStream targetStream = new ByteArrayInputStream(bytes);
File targetFile = File.createTempFile("loadLSTMModel", ".h5");
targetFile.deleteOnExit();
OutputStream os = new BufferedOutputStream(new FileOutputStream(targetFile));
IOUtils.copy(targetStream, os);
 model = KerasModelImport.importKerasSequentialModelAndWeights
(targetFile.getAbsolutePath());

Thanks for your help!

**Comment by AlexDBlack** [comment]
Ok, a couple of things here.
First, try using 1.0.0-beta3. It's possible there was a bug that was fixed in that version relating to this.
Second: Make sure you close your output stream before reading the file. It's possible you simply haven't written all of the relevant data to the file before reading.

**Comment by maryam-k** [comment]
Thanks Alex,
This issue has been resolved by closing my output stream before reading the file.

**Comment by AlexDBlack** [comment]
Ok, great. Easy fix :)
