### ISSUE TITLE
BLAS for tests & GraphRunner

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#7210]
Since GraphRunner and dev tests run without java, we should provide compile-time linkage to any external BLAS library, to make sure we don't do anything stupid to non-tested code in libnd4j.

**Comment by raver119** [comment]
^^ does NOT apply to general libnd4j builds or CI. There is external BLAS provided.

**Comment by saudet** [comment]
I would like it if we could do it the same way as I've done it for MKL-DNN currently. JavaCPP manages the libraries within its cache. It doesn't need Java to build or run, but it expects libraries to be in `~/.javacpp/cache`. However, if we really need to not use Java even as a package manager, we'll have to either build everything from source or come up with some other way of managing native libraries than Maven and JavaCPP.

**Comment by raver119** [comment]
Implemented & discussed in slack.
