### ISSUE TITLE
Possible to force CPU / GPU nd4j backend for model train?

### ISSUE THREAD

**Issue by jentfoo** [deeplearning4j/deeplearning4j#7215]
Is it possible to use multiple backends used at the same time?

I have a case where GPU and CPU performance is basically equal.  I am curious if I could get more performance by using both at the same time, either by having both be used for computing a single model, or by having multiple network instance / net configuration which are trained parallel (but with different backends).

It seems that once cuda is loaded everything goes to cuda though, and the CPU remains relatively idle.

**Comment by AlexDBlack** [comment]
This is not possible at present.
The ND4J backend depetrmines where all ops are executed - so if CUDA backend is loaded, all ops are executed on the GPU.
We will be adding this functionality eventually, but it's not an immediate priority for us, and we don't have a timeline for it yet.
