### ISSUE TITLE
Remove scala-tools repo

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7216]
https://github.com/deeplearning4j/deeplearning4j/search?utf8=%E2%9C%93&q=scala-tools&type=

Apparently this isn't required - https://stackoverflow.com/a/41763576
Though I'm not sure if we'll need to upgrade versions for scala-maven plugin too.

**Comment by saudet** [comment]
scala-maven-plugin from net.alchim31.maven? The version that we're using (3.3.1) is on Maven Central, so I say let's just remove it.
