### ISSUE TITLE
Odd quoted statistics (console output) in the IRIS-flower tutorial

### ISSUE THREAD

**Issue by dersmon** [deeplearning4j/deeplearning4j#722]
Towards the end of the IRIS tuturial, there is a console printout showing the statistics for the results:

>Actual Class 0 was predicted with Predicted 0 with count 50 times
>
>Actual Class 1 was predicted with Predicted 1 with count 2 times
>
>Actual Class 1 was predicted with Predicted 2 with count 48 times
>
>Actual Class 2 was predicted with Predicted 2 with count 50 times
>
>==========================Scores=================================
> Accuracy:  0.6667
> Precision: 0.4906
> Recall:    0.6667
> F1 Score:  0.5652272213429799
>=================================================================`

In the beginning it is said that the IRIS dataset consists of only 150 flowers, 50 for each species. So either there is something I did not get or there can't be 150 flowers in the evaluation statistics, because the testset can only be a fraction of the overall dataset. 

No matter which of those two is true, I think there should be some clarification in the tutorial text. 

My output:

>Actual Class 0 was predicted with Predicted 0 with count 13 times
>
>Actual Class 1 was predicted with Predicted 0 with count 6 times
>
>Actual Class 1 was predicted with Predicted 2 with count 4 times
>
>Actual Class 2 was predicted with Predicted 2 with count 7 times
>
>==========================Scores========================================
> Accuracy:  0.6667
> Precision: 0.6603
> Recall:    1
> F1 Score:  0.7953890489913544
>==========================Scores========================================

**Comment by chrisvnicholson** [comment]
thanks!
