### ISSUE TITLE
Bug in org.deeplearning4j.nn.conf.graph.L2NormalizeVertex equals implementation

### ISSUE THREAD

**Issue by LGougerot** [deeplearning4j/deeplearning4j#7225]
Found on tag 1.0.0-beta3 but appears to be present on more branches.

The `equals` implem checks for `int[]` equality with `==` operator. This should probably be replaced by `Arrays.equals`.

Furthermore, the `hashcode` method is constant and ignores both fields of the class. Is this intended ?

Aha! Link: https://skymindai.aha.io/features/DL4J-10

**Comment by AlexDBlack** [comment]
Yes, both are clearly bugs, thanks for flagging. The equals and hashcode methods should simply be removed; it's suffirient to use the methods generated by the lombok ```@Data``` method already on the class.
Feel free to send us a PR if you want - or I'll look to fix it at some point this week.
