### ISSUE TITLE
Deserializing Torch models

### ISSUE THREAD

**Issue by br1985** [deeplearning4j/deeplearning4j#723]
It would be really nice to have an option to automatically deserialize pretrained Torch models.

Let me briefly describe our use case for this feature. I believe many organizations may be in a similar position.

We're currently using Torch for some research. It works really fine for ad hoc experiments. The problem is with deploying our findings into production. 

Most of our production apps run on Java. We're currently evaluating multiple approaches:

1) embedding Lua (with Torch libraries) into JVM
2) having a separate service for predictions and remotely calling it from Java
3) manually deserializing Torch model in "pure" Java and rewriting whole prediction logic
4) rewriting whole experiment (including learning part) from Torch to tools like DL4J
5) giving up on Torch and moving to DL4J with all the research

(1) and (2) are doable, but introduce extra complexity. (3) and (4) require programming effort every time we want to try a new model in production. (5) does not seem practical as our reseach team is already very used to Torch and don't find Java (or even Scala) as attractive as Lua. At least for ad hoc research, at least for now...

Having an option to automatically deserialize pretrained Torch models to DL4J would be really helpful for us. We'll be able to continue research in tools we're familiar with and quickly deploy our findings to the production enviroment.

I'm not very familiar with DL4J architecture, but I believe automatically deserializing most common Torch models to DL4J equivalents should be pretty straightforward.

Here's our wish list for supported Troch modules (all in 'nn' package):
- Sequential
- LookupTable
- Reshape
- ParallelTable
- Identity
- JoinTable
- Linear
- Tanh
- ReLU
- LogSoftMax
- ...

I'm really curious about your thoughts on this!

**Comment by jpatanooga** [comment]
We have some caffe integration and Torch makes sense as well. definitely +1
on getting this rolling.

Your exact issue of "needing java in prod" is one of the major reasons we
went w the JVM from the start for DL4J.

**Comment by bogdan-maksak** [comment]
Would be really useful to have Torch integration. I would add torch nngraph
package to the list of  modules to be considered.

On Wednesday, 16 September 2015, Josh Patterson <notifications@github.com>
wrote:

> We have some caffe integration and Torch makes sense as well. definitely +1
> on getting this rolling.
>
> Your exact issue of "needing java in prod" is one of the major reasons we
> went w the JVM from the start for DL4J.
>
> On Wed, Sep 16, 2015 at 8:04 AM, br1985 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > It would be really nice to have an option to automatically deserialize
> > pretrained Torch models.
> >
> > Let me briefly describe our use case for this feature. I believe many
> > organizations may be in a similar position.
> >
> > We're currently using Torch for some research. It works really fine for
> ad
> > hoc experiments. The problem is with deploying our findings into
> > production.
> >
> > Most of our production apps run on Java. We're currently evaluating
> > multiple approaches:
> >
> > 1) embedding Lua (with Torch libraries) into JVM
> > 2) having a separate service for predictions and remotely calling it from
> > Java
> > 3) manually deserializing Torch model in "pure" Java and rewriting whole
> > prediction logic
> > 4) rewriting whole experiment (including learning part) from Torch to
> > tools like DL4J
> > 5) giving up on Torch and moving to DL4J with all the research
> >
> > (1) and (2) are doable, but introduce extra complexity. (3) and (4)
> > require programming effort every time we want to try a new model in
> > production. (5) does not seem practical as our reseach team is already
> very
> > used to Torch and don't find Java (or even Scala) as attractive as Lua.
> At
> > least for ad hoc research, at least for now...
> >
> > Having an option to automatically deserialize pretrained Torch models to
> > DL4J would be really helpful for us. We'll be able to continue research
> in
> > tools we're familiar with and quickly deploy our findings to the
> production
> > enviroment.
> >
> > I'm not very familiar with DL4J architecture, but I believe automatically
> > deserializing most common Torch models to DL4J equivalents should be
> pretty
> > straightforward.
> >
> > Here's our wish list for supported Troch modules (all in 'nn' package):
> >
> > - Sequential
> > - LookupTable
> > - Reshape
> > - ParallelTable
> > - Identity
> > - JoinTable
> > - Linear
> > - Tanh
> > - ReLU
> > - LogSoftMax
> > - ...
> >
> > I'm really curious your thought about this!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/deeplearning4j/deeplearning4j/issues/723>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deeplearning4j/deeplearning4j/issues/723#issuecomment-140746701>
> .
>


-- 
*Bogdan Maksak · Head of Product Development*
*FinGenius *- Artificial Intelligence For The Finance Industry.

Level 42, One Canada Square, London, E14 5AB, UK.

T.: +44 20 7788 7588

M.: +44 74 533 21 665



46th Floor, 7 World Trade Center, New York, NY 10007, USA T.: +1 (212)
266-0090


E.: bogdan.maksak@fingenius.com

W.: www.fingenius.com
<https://t.yesware.com/tl/e728b996ce2ef5eb718721667b85b4ce5e84c267/ef8bcea1299ca0701e4f0048750de0ef/3bd22b8e3ef951a79c8b6a3e157b42d3?ytl=http%3A%2F%2Fwww.fingenius.com>


This message is for the designated recipient only and may contain
privileged, proprietary, or otherwise private information. If you have
received it in error, please notify the sender immediately and delete the
original. Any other use of the e-mail by you is prohibited.

FinGenius stands for Fingenius Limited (registered number 08870625),
registered in England and Wales with registered address at Level 42, 1
Canada Square, London, E14 5AB.

**Comment by agibsonccc** [comment]
Great! We have caffe about almost done. We'll look at torch next.

**Comment by bogdan-maksak** [comment]
Thanks!

**Comment by agibsonccc** [comment]
This should be covered by keras import now. torch -> keras -> dl4j
