### ISSUE TITLE
On Device Training (Android)

### ISSUE THREAD

**Issue by vijay033** [deeplearning4j/deeplearning4j#7231]
#### Issue Description
For securing user privacy (a) collection of data (b) training and (c) prediction must take place on mobile device itself i.e. On Device ML. 
Deeplearning4J is likely suitable option currently and experimenting with mentioned topology.

Please describe our issue, along with:
-  Android Beta Version Testing On Mobile Device
-  Got two issues 
     (a) Base64 compatability issue - solved overriding library functions. 
     (b) VectorCalculati - observed ANR on 2GB RAM Devices. Works fine on 4GB RAM.
- Require new release for android version for (a) android compatibility and (b) function well for low end devices also.
- Detailed experiments are mentioned here : https://github.com/vijay033/Deeplearning4j

#### Version Information
1.0.0-beta3

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing
Word2Vec
https://github.com/vijay033/Deeplearning4j
Sentiment Analysis
https://github.com/vijay033/OnDevice_Sentiment-Analysis

**Comment by raver119** [comment]
It sounds like you're speaking about Word2Vec. Try that on latest snapshot, there was overhaul which introduced workspaces, predictable tokenization etc.

**Comment by saudet** [comment]
Thanks for the contribution! Could you send a pull request for those to
https://github.com/deeplearning4j/dl4j-examples/?

**Comment by vijay033** [comment]
Only goal here is to test deep learning framework on andriod. Took word2vec and sentiment analysis example for training the model on mobile device.
Used existing java code and libraries mentioned in android beta version.
1. First issue found during training was ANR    while thread handling for low ram devices (2GB) but training went well for high ram devices(4GB).
Training must work for low ram and hardware configuration devices also.
Check build.gradle and training files
2. Other problem was writing and reading the model file after model.fit. Case was android and java capability for BASE64. For solving this overridden all read and write apis related to the problem (text) . Also modified Base64 encoding /decoding for compatibility.

**Comment by vijay033** [comment]
Android Version Repo :-
https://github.com/vijay033/OnDevice_Word2Vector
https://github.com/vijay033/SentimentAnalysis_Android

**Comment by agibsonccc** [comment]
@vijay033 if you're not going to contribute to the examples, I'm closing this. There's nothing more to add. This is not a contribution or anything related to the core framework but just how it's used.
