### ISSUE TITLE
FilterRenderer seems to render solid patches instead of patterns

### ISSUE THREAD

**Issue by zlieber** [deeplearning4j/deeplearning4j#724]
I was playing around with RBMs and MNIST data; using 0.4-rc1.2, and now rc2.2. I plotted filters using NeuralNetPlotterIterationListener, and it rendered solid patches (instead of expected patterns). There seems to be a problem in FilterRenderer.java:370 on master where it takes column.getDouble(0) every time.

**Comment by agibsonccc** [comment]
We don't use this anymore.
