### ISSUE TITLE
Type inconsistency

### ISSUE THREAD

**Issue by hanbaoan123** [deeplearning4j/deeplearning4j#7247]
#### Issue Description
I am using rldj for some experiments, but I found type inconsistency between rl4j and nd4j. The return type of INDArray's shape() is long[]，but the parameter type Learning.makeShape() needed is int[].

#### Version Information
Rl4j and nd4j are all 1.0.0-SNAPSHOT.

![360 20190305090135007](https://user-images.githubusercontent.com/32160782/53773659-3f9be800-3f26-11e9-9785-9961c82177e4.jpg)
![360 20190305090512291](https://user-images.githubusercontent.com/32160782/53773664-462a5f80-3f26-11e9-9f74-724aa63128a9.jpg)

Aha! Link: https://skymindai.aha.io/features/ND4J-43

**Comment by saudet** [comment]
Please feel free to update it to long[] and send a pull request! Thanks for reporting

**Comment by hanbaoan123** [comment]
In other words, this is a bug?

**Comment by hanbaoan123** [comment]
> Please feel free to update it to long[] and send a pull request! Thanks for reporting

In other words, this is a bug?

**Comment by saudet** [comment]
Yes, in the sense that we could in theory need to have dimensions larger than Integer.MAX_VALUE.

**Comment by hanbaoan123** [comment]
> Yes, in the sense that we could in theory need to have dimensions larger than Integer.MAX_VALUE.

I got it and will send a pull request later.
