### ISSUE TITLE
no jnind4jcpu in java.library.path

### ISSUE THREAD

**Issue by hanbaoan123** [deeplearning4j/deeplearning4j#7254]
Issue Description

This is the error. "Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Administrator.javacpp\cache\nd4j-native-1.0.0-SNAPSHOT-windows-x86_64.jar\org\nd4j\nativeblas\windows-x86_64\jnind4jcpu.dll: Can't find dependent libraries". But I have this file in my path.

Version Information

Please indicate relevant versions, including, if relevant:

rl4j-1.0.0-SNAPSHOT
![360 20190306171547981](https://user-images.githubusercontent.com/32160782/53869968-38630000-4034-11e9-804c-fcb212c529d7.jpg)

**Comment by raver119** [comment]
Which CUDA version you have installed?

**Comment by hanbaoan123** [comment]
> Which CUDA version you have installed?

I have no GPU. I just ran a programm  on cpu.

**Comment by raver119** [comment]
So don't use CUDA backend then.

Use nd4j-native-platform instead of CUDA one.

**Comment by hanbaoan123** [comment]
> So don't use CUDA backend then.
> 
> Use nd4j-native-platform instead of CUDA one.

I have already used nd4j-native-platform.
![360 20190306172840029](https://user-images.githubusercontent.com/32160782/53870739-c12e6b80-4035-11e9-8926-44afd0f1e0d4.jpg)

**Comment by saudet** [comment]
@hanbaoan123 Please use the Dependencies tool to find which DLLs is missing from your system:
https://github.com/lucasg/Dependencies

**Comment by hanbaoan123** [comment]
> @hanbaoan123 Please use the Dependencies tool to find which DLL is missing from your system:
> https://github.com/lucasg/Dependencies

There is not error when using rl4j-1.0.0-alpha,but why for 1.0.0-SNAPSHOT?

**Comment by saudet** [comment]
Probably something related to MKL-DNN. If your system has an AMD CPU, for example, it's possible (though not probable) that MKL does not want to load.

**Comment by hanbaoan123** [comment]
> Probably something related to MKL-DNN. If your system has an AMD CPU, for example, it's possible (though not probable) that MKL does not want to load.
I think there is nothing wrong with the dll file.

![_20190308094245](https://user-images.githubusercontent.com/32160782/54001465-60fb0f00-4186-11e9-9ff1-4e46796982bd.png)

**Comment by saudet** [comment]
Could you set the "org.bytedeco.javacpp.logger.debug" system property to "true" and show me what is displays on the console?

**Comment by hanbaoan123** [comment]
> org.bytedeco



> Could you set the "org.bytedeco.javacpp.logger.debug" system property to "true" and show me what it displays on the console?

Everything is OK now. I used the wrong javacpp version. Thank you!
