### ISSUE TITLE
Tensor mmul returns incorrect shape

### ISSUE THREAD

**Issue by gordoncaleb** [deeplearning4j/deeplearning4j#7262]
#### Issue Description

ND4J tensorMmul returns incorrect shape given a length 1 vector and a rank 3 tensor.

```
INDArray a = Nd4j.create(new double[]{2}).reshape(1);
INDArray b = Nd4j.create(new double[]{1, 2, 3, 4}).reshape(2, 1, 2);
INDArray c = Nd4j.tensorMmul(a, b, new int[][]{new int[]{0}, new int[]{1}});
System.out.println(Arrays.toString(c.shape()));
```
Prints:

```
[1, 2, 2]
```

Where as it should be [2, 2] as numpy shows:

```
import numpy as np
a = np.array([2]).reshape(1)
b = np.array([1,2,3,4]).reshape(2,1,2)
c = np.tensordot(a,b,axes=([0],[1]))
print(c.shape)
```
Prints:

```
(2,2)
```
#### Version Information

Please indicate relevant versions, including, if relevant:

* ND4J version: 1.0.0-beta3
* platform information (OS, etc): MacOS
* CUDA version, if used: NA
* NVIDIA driver version, if in use: NA

#### Contributing

Looks like line 902 and 919 in Nd4j.class do not allow for all dimensions of a tensor to be used in the axes argument without forcing the result shape to have an extra dimension. I would assume those lines should set the shapes to `new long[0]` instead of `new long[]{1}`. This might be related to avoiding rank 0 and rank 1, which some of the ND4J operations seem to prefer. I could raise a PR if you guys would prefer that?

Aha! Link: https://skymindai.aha.io/features/ND4J-63

**Comment by AlexDBlack** [comment]
Confirmed. Numpy behaviour for this case matches TensorFlow.
Unfortunately the custom op implementation (that I was going to switch Nd4j.tensorMmul to) also has this same bug - logged here (issue 20) - https://github.com/deeplearning4j/deeplearning4j/issues/6958

**Comment by AlexDBlack** [comment]
Confirmed fixed on current master.
