### ISSUE TITLE
Incorrect result when multiplying a INDArray view with a scalar

### ISSUE THREAD

**Issue by DrChainsaw** [deeplearning4j/deeplearning4j#7263]
#### Issue Description

The following testcase fails using dl4j beta3 and using CPU backend (CUDA 10 backend passes)

    /**
     *  Create an array of zeros, set columns 3 and 4 to one, then get a view of columns 0 and 1, check that it only
     *  contains zeros and multiply the view with 2. Expectation is that the result of the multiplication is still zeros
     */
    @Test
    public void multiplyScalarRange() {
        final INDArray all = Nd4j.zeros(new long[] {3, 4});

        // Assign second half of columns to 1
        all.get(NDArrayIndex.point(0), NDArrayIndex.interval(2, 4)).assign(Nd4j.ones(1,2));

        // Get a view on the first half of columns
        final INDArray firstHalf = all.get(NDArrayIndex.all(), NDArrayIndex.interval(0, 2));

        System.out.println("firstHalf: \n" + firstHalf);
        assertEquals("First half shall be zeros!", Nd4j.zeros(firstHalf.shape()), firstHalf);

        final INDArray result = firstHalf.mul(2);

        System.out.println("result: \n" + result);
        assertEquals("Result shall still be zeros!", Nd4j.zeros(result.shape()), result);

    }

Program output:

firstHalf: 
[[         0,         0], 
 [         0,         0], 
 [         0,         0]]
result: 
[[         0,         0], 
 [    2.0000,    2.0000], 
 [         0,         0]]

junit.framework.AssertionFailedError: Result shall still be zeros!  <Click to see difference>

Using put instead of get yeilds the same result.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0 beta3
* platform information (OS, etc) Windows 10
* CUDA version, if used N/A (works with CUDA 10 backend)
* NVIDIA driver version, if in use

#### Contributing

Don't mind helping out, but I my mind is not well tuned to thinking about multiple dimensions in terms of strides and whatnot.

**Comment by AlexDBlack** [comment]
Looks like this has already been fixed: test passes on current master on CPU.
```
firstHalf: 
[[         0,         0], 
 [         0,         0], 
 [         0,         0]]
result: 
[[         0,         0], 
 [         0,         0], 
 [         0,         0]]
```
