### ISSUE TITLE
Missing SRCNN

### ISSUE THREAD

**Issue by linkerlin** [deeplearning4j/deeplearning4j#727]
I find out a simple impl. at https://github.com/mrkn/chainer-srcnn/blob/master/srcnn.py  .
Anyone can reimpl it in dl4j?

**Comment by agibsonccc** [comment]
Sure we can do this.

**Comment by linkerlin** [comment]
Paper: http://research.microsoft.com/en-us/um/people/kahe/publications/eccv14srcnn.pdf

**Comment by nkwoh01** [comment]
this looks resolved
