### ISSUE TITLE
libnd4j: Wrap OpenMP pragma directives in macros for more flexibility

### ISSUE THREAD

**Issue by saudet** [deeplearning4j/deeplearning4j#7273]
Right now, all OpenMP directives are hard coded with `#pragma` making it almost impossible to support multiple architectures efficiently. Instead, we should use the `_Pragma` operator and wrap those in macros:
https://gcc.gnu.org/onlinedocs/cpp/Pragmas.html

We need to be able to disable OpenMP entirely for some blocks depending on the kind of directive, so I think we should wrap everything in 1 main macro per line, and come up with multiple submacros to implement the kinds of arguments we need. We will know exactly what we end up with only after converting all the directives, but I think something like the following should work:
```cpp
#define OMP_STRINGIFY(args) #args
#define OMP_IF(args) if(args)
#define OMP_SCHEDULE(args) schedule(args)
#define OMP_SUMT sumT
#define OMP_REDUCTION(args) reduction(args)
#define PRAGMA_OMP_CRITICAL _Pragma(OMP_STRINGIFY(omp critical))
#define PRAGMA_OMP_SIMD(args) _Pragma(OMP_STRINGIFY(omp simd args))
#define PRAGMA_OMP_PARALLEL(args) _Pragma(OMP_STRINGIFY(omp parallel args))
#define PRAGMA_OMP_PARALLEL_FOR(args) _Pragma(OMP_STRINGIFY(omp parallel for args))
#define PRAGMA_OMP_PARALLEL_FOR_SIMD(args) _Pragma(OMP_STRINGIFY(omp parallel for simd args))
// ...

    int sum = 0;
    PRAGMA_OMP_PARALLEL_FOR(OMP_SCHEDULE(static) OMP_REDUCTION(OMP_SUMT:sum))
    for (...) {
        // ...
    }
```

Also, some compilers do not support function calls in the `for` statement, so while we're at it, let's also convert all statements such as `for (Nd4jLong e = 0; e < this->lengthOf(); e++)` to something like:
```cpp
Nd4jLong n = this->lengthOf();
PRAGMA_OMP_PARALLEL_FOR(/* ... */)
for (Nd4jLong e = 0; e < n; e++) {
    // ...
}
```

Aha! Link: https://skymindai.aha.io/features/ND4J-86

**Comment by raver119** [comment]
Implemented
