### ISSUE TITLE
Cannot execute meshgrid with double arrays

### ISSUE THREAD

**Issue by nicoulaj** [deeplearning4j/deeplearning4j#7275]
#### Issue Description
This test:

    @Test
    public void testBugMeshgridOnDoubleArray() {
        Nd4j.meshgrid(Nd4j.create(new double[] { 1, 2, 3 }), Nd4j.create(new double[] { 4, 5, 6 }));
    }

throws:
```
Validation error at /home/jenkins/workspace/deeplearning4j-master-linux-x86_64-centos6-cpu/libnd4j/include/ops/declarable/impl/DeclarableOp.cpp:423 code=34() "this->validateDataTypes(*block)"
12:04:23.779 [ERROR] Failed to execute op meshgrid. Attempted to execute with 2 inputs, 2 outputs, 0 targs and 0 iargs. Inputs: [(DOUBLE,[3],c), (DOUBLE,[3],c)]. Outputs: [(FLOAT,[3,3],c), (FLOAT,[3,3],c)]. tArgs: -. iArgs: -. Op own name: "fda0a5c5-f0e7-4933-b8c0-2c154260e15f" - Please see above message (printed out from c++) for a possible cause of error.
FAILED: testBugMeshgridOnDoubleArray
org.nd4j.linalg.exception.ND4JIllegalStateException: Failed to execute op [meshgrid] with error code [ND4J_STATUS_VALIDATION]
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1701)
	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.execAndReturn(DefaultOpExecutioner.java:604)
	at org.nd4j.linalg.factory.Nd4j.meshgrid(Nd4j.java:2142)
```

It seems meshgrid only works with float arrays as input.

#### Version Information

* Deeplearning4j version: sonatype repo 1.0.0 snapshot: 1.0.0-20190308.084722-15882
* platform information (OS, etc): linux x86_64
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

Aha! Link: https://skymindai.aha.io/features/ND4J-88

**Comment by raver119** [comment]
Yes, it's a bug, not it's not related to "float output only".

It's failing because output arrays are created without respect to input data types, default dtype is used.
