### ISSUE TITLE
Nd4j.setDataType(DataBuffer.Type.FLOAT) is not setting preferred array type globally

### ISSUE THREAD

**Issue by divyakoyy** [deeplearning4j/deeplearning4j#7280]
#### Issue Description

Per documentation, I should be able to globally set up the preferred data type for arrays via:
`Nd4j.setDataType(DataBuffer.Type.FLOAT); `

However, using `Nd4j.createFromNpyFile(File file)`, the arrays I'm loading from .npy files are creating both `DOUBLE` and `FLOAT` arrays, causing the following error when I try to add row vectors. 

org.xml.sax.SAXException: org.nd4j.linalg.exception.ND4JIllegalStateException: op.Y dataType is [DOUBLE] instead of expected [FLOAT]

Code:

```     
Nd4j.setDataType(DataBuffer.Type.FLOAT);
this.mModelWeights = Nd4j.createFromNpyFile(weightFile);
// Just getting the first dimension from this npy file for the model biases
INDArray tempArray = Nd4j.createFromNpyFile(biasFile);
this.mModelBias = tempArray.getRow(0);

// input is a one-hot vector created by using Nd4j.create()
INDArray temp = input.mmul(this.mModelWeights);
inputEmbeddings = temp.addiRowVector(this.mModelBias);
```

The exception is thrown on the line `inputEmbeddings = temp.addiRowVector(this.mModelBias)`

Please let me know if you need any more information!

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j:  0.9.1
* platform information: macOS 10.13.6
* CUDA version: n/a
* NVIDIA driver version: n/a

**Comment by raver119** [comment]
Please update to 1.0.0-beta3. And keep in mind, in current master (and upcoming release) there's support for additional data types added.

**Comment by divyakoyy** [comment]
I updated to 1.0.0-beta3 and the same error was thrown.
