### ISSUE TITLE
Libnd4j: conv2d_bp crash with size 1 kernel edge case

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7281]
See below for a case that crashes with:
(a) Float datatype (I've seen similar failures with double precision, but can't reproduce in isolation)
(b) When MKL-DNN is *not* used (passes with MKL-DNN)

I suspect the kernel width of 1 combined with the input width of 1 is the problem here. Other cases (without this size 1 edge case for the kernel/input width) run fine and provide correct output.

No JVM crash log is produced; the only output is the JVM crash exit code:
```
Process finished with exit code -1073740940 (0xC0000374)
```

```
    @Test
    public void debugConv(){
        Nd4j.setDataType(DataType.FLOAT);
        Nd4jCpu.Environment.getInstance().setUseMKLDNN(false);


        INDArray in = Nd4j.create(1,2,7,1);     //NCHW
        INDArray w = Nd4j.create(2,1,2,3);      //kH, kW, iC, oC
        INDArray b = Nd4j.create(1,3);
        INDArray g = Nd4j.create(1,3,7,1);      //NCHW

        INDArray og = in.like();                //gradient at input - NCHW
        INDArray wg = w.like();                 //Weight gradient
        INDArray bg = b.like();


        DynamicCustomOp op = DynamicCustomOp.builder("conv2d_bp")
                .addInputs(in, w, b, g)
                .addOutputs(og, wg, bg)
                .addIntegerArguments(
                        2,1,   //kernel
                        1,1,    //stride
                        0,0,    //Pad
                        1,1,    //Dilation
                        1,      //Same
                        0       //0 = NCHW
                )
                .build();

        Nd4j.exec(op);
    }
```

Aha! Link: https://skymindai.aha.io/features/ND4J-96

**Comment by raver119** [comment]
Is it reproducible on linux?

**Comment by AlexDBlack** [comment]
I haven't checked yet. Can reboot soon and check.

**Comment by shyrma** [comment]
Hi, Alex
Problem has been solved, it had to do to with wrong reshape of permuted arrays that have unity-dimensions. Corresponding pr is merged

**Comment by AlexDBlack** [comment]
Confirmed passing now - thanks!
