### ISSUE TITLE
Suggestion: Add option to fail on reshape if a view could not be created 

### ISSUE THREAD

**Issue by DrChainsaw** [deeplearning4j/deeplearning4j#7292]
#### Issue Description

INDArray#reshape often but not always returns a view of the reshaped array and this makes it is easy to introduce hard to find bugs, especially since the method purpose is so clear the user might not read the javadoc.

Would it be helpful to have a method (or maybe flag) which indicates that the user prefers an exception over a copy if a view can not be created?

I understand this adds to an already huge API so I won't cry if you don't add it. If not ,what is a good way to check that you actually get a view? INDArray#isView()?

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 1.0.0-beta3

Aha! Link: https://skymindai.aha.io/features/ND4J-108

**Comment by AlexDBlack** [comment]
I'm in favor of adding this. We already have this functionality anyway, but it's hidden from an API perspective:
https://github.com/deeplearning4j/deeplearning4j/blob/eb6faca4b49456fd5c8b5f77d75a8daedbc0dca5/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/shape/Shape.java#L1938-L1951

**Comment by AlexDBlack** [comment]
Thanks for the suggestion. Implemented here, will be merged soon: https://github.com/deeplearning4j/deeplearning4j/pull/7293

**Comment by DrChainsaw** [comment]
Awesome! Thanks alot!
