### ISSUE TITLE
DL4j OOM Exception for ResNet50 Inference at Batchsize 512 with the latest snapshots

### ISSUE THREAD

**Issue by dollarHome** [deeplearning4j/deeplearning4j#7297]
#### Issue Description
I am using pretrained ResNet50 ComputationGraph. I am on the latest snapshot (as of 3/14/2019). I am able to run the inference for batch sizes 32/64/128/256 (surprisingly more or less same performance numbers even with increase in batchsize - was expecting increased performance).  But at a batchsize of 512, the app is crashing with "java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes (59453M) > maxPhysicalBytes (59392M)". I created the gist here https://gist.github.com/dollarHome/9cc5238854707f5557f3ca15edde3833. I am running this workload with -Xms29g -Xmx29g -XX:+UseG1GC -XX:ParallelGCThreads=1 . On beta3 this same code used to run without issues even for batchsize 512. I increased the heapsize upto 128GB and the app crashes nevertheless. I did not see this issue with beta3, i was even able to run the same code for batch size 1024.

**Expected behavior:**
1) The app should run without issues even for batchsize > 256 even upto 1024 possibly
2) The app should show some increase in performance with increase in batch size until it tapers off or before it hits contention.

**Encountered behavior:**
1) The app crashes for batchsize 512
2) With increase in batchsize, the performance marginally decreases or remains same
3) During a run, there were couple of batches with higher numbers than the average batch execution time even with the following tuning parameters set:

**DL4J Snapshot (MKL+MKL-DNN) Stack:**
**System details:**
ResNet50 on 24 Cores Xeon(JVM pinned to 1 socket-24c)
Heap size: 29GB
System set to Performance mode
Hyperthreading ON
Total imagenet images used in inference: 2476

**Tuning parameters used:**
KMP_BLOCK_TIME=0
OMP_WAIT_POLICY=PASSIVE
MKL_THREADING_LAYER=GNU
MKL_NUM_THREADS=24
OMP_DISPLAY_ENV=VERBOSE
OMP_NUM_THREADS=24
**JVM Options:**
-XX:ParallelGCThreads=1
-XX:+UseG1GC
 -Xms29g -Xmx29g

#### Version Information
DL4J Snapshot as of 3/14/2019

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: DL4J Snapshot as of 3/14/2019
* platform information (OS, etc): Ubuntu 18.04 on 24c Xeon
* Test code: https://github.com/deeplearning4j/deeplearning4j/issues/7271
#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

Aha! Link: https://skymindai.aha.io/features/DL4J-2

**Comment by saudet** [comment]
I don't think MKL-DNN gets used yet for anything else than BLAS so there shouldn't be any difference from 1.0.0-beta3 @AlexDBlack ?

**Comment by AlexDBlack** [comment]
MKL-DNN support (conv/pool/bn layers) was merged recently.
I wouldn't have expected MKL-DNN to use more memory than the built-in implementation (or current snapshots to use more than beta3 generally), but I haven't actually profiled this yet (which is why I asked for an issue so I can look into it at some point).

**Comment by dollarHome** [comment]
Hi Alex @AlexDBlack, any update on this that I can try? Please note, with increase in batchsize 32 ->64->128->256->512, the performance actually drops though by few milliseconds, and finally crashes at batchsize of 512.

**Comment by AlexDBlack** [comment]
Sorry, I haven't looked at it yet, haven't had much time in the last few weeks for looking at issues.
