### ISSUE TITLE
Compilation error with sm75 arch on cuda 10

### ISSUE THREAD

**Issue by shugeo** [deeplearning4j/deeplearning4j#7302]
#### Issue Description

There is a build error when using cc 75 compilation param on buildnativeoperations.sh script.
I.e.
./buildnativeoperations.sh -b debug -c cuda -cc 75 -t -j 8
fails with error

#### Version Information

* Deeplearning4j version: 1.0.0
* GNU/Linux x64 (Ubuntu 18.04)
* 10.0
* 410.104-0ubuntu1

Aha! Link: https://skymindai.aha.io/features/ND4J-124

**Comment by raver119** [comment]
Fixes were applied.
