### ISSUE TITLE
ModelZoo中的TextGenerationLSTM出现bug

### ISSUE THREAD

**Issue by pengtaomach** [deeplearning4j/deeplearning4j#7318]
#### Issue Description

在创建TextGenerationLSTM网络模型时，出现空指针异常（NullPointerException）
如下图所示
![image](https://user-images.githubusercontent.com/38904475/54665757-dcfc3c00-4b22-11e9-9ec1-ea267847b1b3.png)
![image](https://user-images.githubusercontent.com/38904475/54665772-e9809480-4b22-11e9-9f7b-d12dfb89b7f3.png)

#### Version Information
* Deeplearning4j ：deeplearning4j-zoo-1.0.0-beta3

#### Contributing
跟踪源码发现TextGenerationLSTM的属性字段inputShape忘记添加@Builder.Default，如下图所示
![image](https://user-images.githubusercontent.com/38904475/54665868-37959800-4b23-11e9-8c26-d19ec41012e6.png)
导致在创建超参数的时候，使用inputShape属性时出现空指针异常
![image](https://user-images.githubusercontent.com/38904475/54665912-5eec6500-4b23-11e9-83d1-8130035c4b88.png)

**Comment by wangfeng-skymind** [comment]
@pengtaomach the example is wroten by you? or you can show example link?

**Comment by pengtaomach** [comment]
@wangfeng-skymind 例子是我自己写的，就是简单的调用源码包的API接口，代码如下
  val textGenerationLSTM = TextGenerationLSTM.builder().build()
    textGenerationLSTM.init()

**Comment by wangfeng-skymind** [comment]
@pengtaomach hm,maybe you have misunderstood it,because inputting dataset need collect by you and dealing with ETL, and then put them in network,so input datasets cannot be defaulted

**Comment by wangfeng-skymind** [comment]
@pengtaomach  you must set maxLength and totalUniqueCharacters value by yourself ,it isn't a bug

**Comment by pengtaomach** [comment]
@wangfeng-skymind  maxLength and totalUniqueCharacters不是有默认值吗，为什么不能使用默认值楠

**Comment by wangfeng-skymind** [comment]
@pengtaomach plz show your code through gists that will be best way

**Comment by wangfeng-skymind** [comment]
@pengtaomach at the same, you can jump to here https://gitter.im/deeplearning4j/deeplearning4j/deeplearning4j-cn
