### ISSUE TITLE
LFW Data Fetcher Fixes

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/deeplearning4j#733]
Dl4j LFW examples throwing shape errors if anything used that is not 28x28x1:

- Change hard coded size values from 28 x 28 to allow for dynamic size (LFWDataSetIterator, LFWDataFetcher, LFWLoader) especially since original data set is 250x250
- Track down variance in shape between labels and examples (probably due to hard coded shape values) when stepping through example
- Confirm channel should be 3 for color and determine where that issue is coming from

**Comment by agibsonccc** [comment]
We should just use canova for this. It does everything. It has the same folder structure as canova expects anyways.

**Comment by nyghtowl** [comment]
Reopening since there is still code in use in Dl4j and users have been trying to use it.

Note part of this issue/enhancement should be to move this to Canova
