### ISSUE TITLE
The import org.deeplearning4j.datasets.datavec cannot be resolved

### ISSUE THREAD

**Issue by rahabwairimu05** [deeplearning4j/deeplearning4j#7337]
#### Issue Description
The deepLearning4J dependencies  included in my maven project  does not seem to work. This is because when I try to import `import org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator;` to my project space so that I can use RecordReaderDataSetIterator in my code,  the import gets highlighted in red, and and get the error : The import org.deeplearning4j.datasets.datavec cannot be resolved.
Other import such as `import org.datavec.api.records.reader.RecordReader;` and `import org.nd4j.linalg.dataset.api.iterator.DataSetIterator;` are working very well. Only imports regarding org.deeplearning4j which are not working.

Please describe our issue, along with:
- expected behavior
Having the required dependencies in the pom.xml file, the import should work and be able to create an object of type ` RecordReaderDataSetIterator`. Below are my dependecies in pom.xml
`  <dependency>
      <groupId>org.deeplearning4j</groupId>
      <artifactId>deeplearning4j-core</artifactId>
      <version>1.0.0-beta3</version>
  </dependency>`
`  <dependency>
      <groupId>org.deeplearning4j</groupId>
      <artifactId>deeplearning4j-nlp</artifactId>
      <version>1.0.0-beta3</version>
  </dependency>`
`  <dependency>
      <groupId>org.deeplearning4j</groupId>
      <artifactId>deeplearning4j-zoo</artifactId>
      <version>1.0.0-beta3</version>
  </dependency>`
- encountered behavior
Errors highlighting the import as well as the line of code where I call  `RecordReaderDataSetIterator`

`import org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator;`
` DataSetIterator iterator = new RecordReaderDataSetIterator(irisRecordReader,flowerBatchSize,numExplanatoryVariables,numFlowerClasses);
      `

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version : 1.0.0-beta3
* platform information (OS, etc) : Windows 7, 64 bit , Using Eclipse IDE, Java 10, using Maven
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by AlexDBlack** [comment]
Commented in gitter:
> Using Eclipse IDE

> this is almost certainly caused by eclipse's bad maven support, nothing to do with DL4J in any way
basically, if you import a maven project, then change the pom.xml dependencies, the eclipse project will not be updated
> i.e., eclipse imports the pom.xml to its own project format when you set up the project, but there's no link with the pom.xml thereafter
you can confirm this by building your project using maven command line tool - it should build fine there
importing your project from scratch into eclipse should fix it (as would using the same project in intellij, which has proper maven support)

I'll close this for now. If this is not the case, we can re-open the issue.
