### ISSUE TITLE
Not an Isuue, a question on how one can join Gitter

### ISSUE THREAD

**Issue by rahabwairimu05** [deeplearning4j/deeplearning4j#7338]
I have been trying to Join the gitter chat, Mostly to ask questions on the challenges that I am going through using this library.  I am able to join, but I cannot ask a question or contribute since github users can join the room . "Only GitHub users can join this room."

I already in github, How do I solve this? Attached is the screenshot of how the gitter looks from my end
![GitterIssue](https://user-images.githubusercontent.com/7096353/54833016-f25d9b80-4cc5-11e9-83a8-c09802d9dc04.PNG)

**Comment by raver119** [comment]
Log in to gitter by using your github id, not a twitter.
