### ISSUE TITLE
Example For Paragraph2vec.

### ISSUE THREAD

**Issue by liushiqi9** [deeplearning4j/deeplearning4j#734]
Need a Example for paragraph2vec. 
Too hard to make it work based on java API page.
Help!!!!

**Comment by sanity** [comment]
I second this request

**Comment by agibsonccc** [comment]
Right now we have the unit tests. I'd be happy to get help building it.Otherwise this is lower on my priority list. I need to traige some of this stuff. Lotta other things on the table here.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/test/java/org/deeplearning4j/models/paragraphvectors/ParagraphVectorsTest.java#L63-63 This can get you started.

**Comment by sanity** [comment]
Thanks for the reply @agibsonccc .

As an example, what does .labels() do in the Builder?  What are these labels used for?  Are they required?

The JavaDoc doesn't really communicate anything that can't be inferred from the method signature.

I understand that this might not be the highest priority, but I think 5 minutes of documentation work could make a big difference to a lot of people.

For context:

I have a dataset consisting of about 5,000 descriptions of software startups, each is several sentences.  Right now I'm just averaging word2vec vectors of the top 3 words according to TF/IDF to get a single vector for the description, then using PCA to reduce it down to 2 dimensions and plotting.   This isn't working very well, so I'm hoping that I can use paragraph2vec to produce vectors that more effectively capture the meaning of each description.

Also, I'm curious as to whether paragraph2vec can be used in reverse, so given a vector, it would produce a paragraph.  I realize it won't be high-quality English, but it might be sufficient to get the gist of what the vector represents.

Would appreciate any thoughts you might have.

- Ian

**Comment by sonalgupta** [comment]
+1 -- would be great to have an implementation example.

**Comment by agibsonccc** [comment]
Yes the labels are required. The whole point of doc2vec is associating
arbitrary documents with labels. Doc2vec is an extension of word2vec that
learns to correlate labels and words rather than words with other words.
ᐧ

**Comment by sanity** [comment]
@agibsonccc My understanding is that the point of doc2vec is to come up with a vector that represents the "meaning" of a document.  

This can subsequently be used as input to a supervised machine learning algo to associate with labels, but this isn't necessarily the case.  Is that your understanding?

**Comment by chrisvnicholson** [comment]
let me know how we can improve this: http://deeplearning4j.org/doc2vec.html

**Comment by sanity** [comment]
@chrisvnicholson I guess I didn't receive a good response to my previous comment.  @agibsonccc argues that the whole point of doc2vec is associating arbitrary documents with labels.  I don't agree, that is just one use.  

The point of doc2vec is to associate a document with a vector, which represents the meaning of the document, in some sense.  Those vectors might be used as input to a supervised learning algorithm, but they might be used in other ways (eg. document similarity as part of a search application).

**Comment by dfisla** [comment]
You hit the nail on the head, document similarity is another important usage!

**Comment by sanity** [comment]
Since writing this I think I might have misunderstood.  It appears that they're using the label mechanism as a way to give every line of input its own label.  I'm not sure exactly why, but I don't think it's what I originally thought (that they were assuming doc2vec was being used for supervised learning).
