### ISSUE TITLE
SameDiff: stack/unstack is very slow

### ISSUE THREAD

**Issue by rnett** [deeplearning4j/deeplearning4j#7344]
#### Issue Description

Using stack, unstack and concat from SameDiff cause large memory use.

Specifically, I have two lambda layers intended to function sort of like Keras's TimeDistributed by distributing the target dimension across the batch, and then reforming it.

It would look something like (10, 3, 75, 128) -> (30, 75, 128) -> (10, 3, 75, 128) targeting dimension 1 (the 0th is the batch size) .

To do this I use:
```kotlin
val splits = SD.unstack(input, dimension)

return SD.concat(0, *splits)
```
and
```kotlin

// size is the size of the dimension that was removed
// .chunked() splits the list into lists of that size

SD.unstack(input, 0).toList().chunked(size).map {
    SD.stack(dimension, *it.toTypedArray())
}.let {
    SD.stack(0, *it.toTypedArray())
}
```
to reverse it.

`SD` is the `SameDiff` object and `input` is the `layerInput` (I'm using a few custom Kotlin wrappers).

To test it I'm using the MNIST example w/ a batch size of 64, so there's not a lot of data.

Running this slowly eats up ~7 GB of RAM before I have to kill it, barely touching my GPU.

I'm fairly sure the issue is in the reversal (the second one).

#### Version Information
* Deeplearning4j version: 1.0.0.-beta3
* platform information (OS, etc): Windows, NVIDIA 1070
* CUDA version, if used: 10.0
* NVIDIA driver version, if in use: 411.31

**Comment by raver119** [comment]
Unfortunately we do not provide GPU implementations for SameDiff yet. It'll take 3-4 more weeks.

**Comment by AlexDBlack** [comment]
I'm tempted to reopen this due to the memory use.
@rnett What's your memory configuration here? Have you changed ND4J GC settings at all (and if so, what are you using?)

**Comment by rnett** [comment]
@AlexDBlack not that I know of.

I've been able to run other SameDiff layers using the GPU backend, do they just run on the CPU?

Also, the issue still happens using the CPU backend (although it seems to cap at 4GB RAM, I've waited 10m for one epoch of MNIST and haven't gotten anything).

**Comment by raver119** [comment]
@rnett yes, ops within graph that do not have GPU implementation (yet) just use CPU.

**Comment by AlexDBlack** [comment]
Hm, yeah, on second thought this looks like a really inefficient implementation... if you want reshaping, use reshape ops - don't extract sub-arrays and recombine like that.

**Comment by rnett** [comment]
Yeah, that's kind of what I thought it was.

Is there a way to set the reshape order w/ SameDiff?

**Comment by AlexDBlack** [comment]
It defaults to C order, regardless of the input order. If you want different behaviour, permuting before reshaping is one option.
Reshape ops will also handle that variable minibatch size (if implemented using [-1, 75, 128] and [-1, 3, 75, 128] shapes)
