### ISSUE TITLE
Train model from streams

### ISSUE THREAD

**Issue by LuZhenHuan** [deeplearning4j/deeplearning4j#7351]
#### Use stream to  train model

I am currently working on a predictive task of unequal sequences(many to many),which will save many files in a folder. Now some requirements require the use of streams to build datasets(i.e Others pass me some streams, I use these streams to train the model without saving the file locally)

how do you build a dataset and store it in HDFS without saving local files? Alex said he would support this.

thanks a lot

**Comment by AlexDBlack** [comment]
Thanks for the issue. Functionality to support this is being added here: https://github.com/deeplearning4j/deeplearning4j/pull/7340
Keep an eye on that pull request; after it has been merged, the functionality will be available on snapshots: https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots

I will provide an example (in the form of a unit test) before that is merged.

**Comment by AlexDBlack** [comment]
Update: functionality is done, but PR is not yet merged. It should get merged later today or tomorrow at the latest.
For HDFS (or similar) there are two parts:
(a) List your URIs, and pass them to StreamInputSplit constructor
(b) Make your own ```Function<URI,InputStream>``` to open the streams for a given URI.

https://github.com/deeplearning4j/deeplearning4j/blob/169bf67354100233fa5db80a009ca1d93b4e7306/datavec/datavec-api/src/test/java/org/datavec/api/split/TestStreamInputSplit.java

For opening streams from HDFS, you can use this as a reference:
https://github.com/deeplearning4j/deeplearning4j/blob/master/datavec/datavec-spark/src/main/java/org/datavec/spark/transform/utils/SparkUtils.java#L130-L131

**Comment by LuZhenHuan** [comment]
Alex You are very professional, thanks a lot!
