### ISSUE TITLE
Failures in nd4j unit tests

### ISSUE THREAD

**Issue by alexanderst** [deeplearning4j/deeplearning4j#7360]
.1 nd4j-native
tests:
  TFGraphTestAllLibnd4j.test:170 output: 1 values exceed maxRelError=0.001 with minAbsError=1.0E-5; largest observed relError=0.0023089356254786253 expected:<0> but was:<1>
  TFGraphTestAllLibnd4j.test:170 Predictions do not match on nth_element/rank2_n3_reverse, node NthElement
  TFGraphTestAllLibnd4j.test:170 Predictions do not match on nth_element/rank2_n4, node NthElement
  TFGraphTestAllLibnd4j.test:170 Predictions do not match on nth_element/rank3_n2, node NthElement
  TFGraphTestAllSameDiff.testOutputOnly:178 Predictions do not match on cond/cond_true, node cond/Merge
  TFGraphTestAllSameDiff.testOutputOnly:178 output: 1 values exceed maxRelError=0.001 with minAbsError=1.0E-5; largest observed relError=0.0023089356254786253 expected:<0> but was:<1>
  TFGraphTestAllSameDiff.testOutputOnly:178 Predictions do not match on nth_element/rank2_n3_reverse, node NthElement
  TFGraphTestAllSameDiff.testOutputOnly:178 Predictions do not match on nth_element/rank2_n4, node NthElement
  TFGraphTestAllSameDiff.testOutputOnly:178 Predictions do not match on nth_element/rank3_n2, node NthElement
  OpExecutionerTests.testSum6d2:643 expected:<1160.0> but was:<392.0>

Tests run: 4066, Failures: 10, Errors: 0, Skipped: 326Failed 

2.2 nd4j-tests-tensorflow
Results :

Tests in error:
  GraphRunnerTest.testGraphRunner:46 » FileNotFound tf_graphs/nd4j_convert/simpl...
  GraphRunnerTest.testGraphRunnerFilePath:56 » FileNotFound tf_graphs/nd4j_conve...
  GraphRunnerTest.testGraphRunnerSavedModel:123 » IllegalState Resource 'tf_save...
  GraphRunnerTest.testInputOutputResolution:65 » FileNotFound tf_graphs/lenet_fr...
  TensorflowConversionTest.testConversionFromNdArray:56 » NoClassDefFound Could ...
  TensorflowConversionTest.testCudaIfAvailable:70 » NoClassDefFound Could not in...
  TensorflowConversionTest.testNullArray »  Unexpected exception, expected<java....
  TensorflowConversionTest.testStringConversion:89 » NoClassDefFound Could not i...
  TensorflowConversionTest.testView:38 » UnsatisfiedLink no jnitensorflow in jav...

Tests run: 10, Failures: 0, Errors: 9, Skipped: 1

**Comment by AlexDBlack** [comment]
New failures in ND4J, that started in the last few days: (happening on both Windows and Linux, native backend)
* DataSetTest.testGetRangeMask (looks like max along dimension?)
* MultiNormalizerHybridTest - testGlobalNormalization, testSpecificInputOutputNormalization, testMasking
* OpExecutionerTests.testSum6d2
* CrashTest.testEWSViews2 (JVM crash) - https://gist.github.com/AlexDBlack/1f944a215b9b20a848dd686c99d77fd4

**Comment by AlexDBlack** [comment]
One issue isolated DataSetTest.testGetRangeMask:
```
    @Test
    public void testCreateF(){
        Nd4j.factory().setOrder('f');

        INDArray arr = Nd4j.createFromArray(new double[][]{{1,2,3},{4,5,6}});

        INDArray exp = Nd4j.create(2,3);
        exp.putScalar(0,0, 1.0);
        exp.putScalar(0,1, 2.0);
        exp.putScalar(0,2, 3.0);
        exp.putScalar(1,0, 4.0);
        exp.putScalar(1,1, 5.0);
        exp.putScalar(1,2, 6.0);

        assertEquals(exp, arr);
    }
```
![image](https://user-images.githubusercontent.com/2360237/55129003-a26d5180-5169-11e9-8246-47254f6625f6.png)

**Comment by AlexDBlack** [comment]
Another test isolated from MultiNormalizerHybridTest: issue seems specific to F order views - failing on max(1) (whereas max(0) is fine here).

```
    @Test
    public void testMaxViewF(){

        INDArray arr = Nd4j.create(DataType.DOUBLE, new long[]{8,2}, 'f').assign(999);

        INDArray view = arr.get(NDArrayIndex.interval(3,5), NDArrayIndex.all());
        view.assign(Nd4j.createFromArray(new double[][]{{1,2},{3,4}}));

        System.out.println(view);

        System.out.println("Max 0: " + view.max(0));
        System.out.println("Max 1: " + view.max(1));

        assertEquals(Nd4j.create(new double[]{3,4}), view.max(0));
        assertEquals(Nd4j.create(new double[]{2,4}), view.max(1));
    }
```

```
[[    1.0000,    2.0000], 
 [    3.0000,    4.0000]]
Max 0: [    3.0000,    4.0000]
Max 1: [  999.0000,  999.0000]

java.lang.AssertionError: 
Expected :[    2.0000,    4.0000]
Actual   :[  999.0000,  999.0000]
```

**Comment by AlexDBlack** [comment]
OpExecutionerTests.testSum6d2 looks like bad test - a better version of the test passes:
https://gist.github.com/AlexDBlack/75eafe61e7105105e36adb685e584199

**Comment by AlexDBlack** [comment]
2 more:

OneHot: https://gist.github.com/AlexDBlack/132fa70279694b26d2efb21f3c21b287

Broadcast methods:
```
    @Test
    public void testAutoBroadcast(){
        INDArray x = Nd4j.create(DataType.DOUBLE, 4);
        INDArray y = Nd4j.create(DataType.DOUBLE, 1,4);

        Nd4j.exec(DynamicCustomOp.builder("add")
                .addInputs(x,y)
                .addOutputs(Nd4j.create(1,4))
                .build());
    }
```

```
o.n.l.c.n.o.NativeOpExecutioner - Failed to execute op add. Attempted to execute with 2 inputs, 1 outputs, 0 targs and 0 iargs. Inputs: [(DOUBLE,[4],c), (DOUBLE,[1,4],c)]. Outputs: [(FLOAT,[1,4],c)]. tArgs: -. iArgs: -. Op own name: "ad5a160d-b33f-423a-9610-bfa53c3855ad" - Please see above message (printed out from c++) for a possible cause of error.

java.lang.RuntimeException: NDArray::applyTrueBroadcast method: the shape or type of target array is wrong !
```

**Comment by AlexDBlack** [comment]
nd4j-native tests fixed.
I've opened an issue for nd4j-tests-tensorflow here: https://github.com/deeplearning4j/deeplearning4j/issues/7524
