### ISSUE TITLE
Migrate dl4j model 

### ISSUE THREAD

**Issue by rosanomax** [deeplearning4j/deeplearning4j#7363]
#### Issue Description

I’m building a feedforward model on Knime using DL4J extension.
I need to migrate my model to another programming languange (C).
Basically, I would like to access to a visualization, or get the values of my parameters (weights and biais).
When I export the DL4J model in knime, it give me `coefficients.bin` ( hexa decimal file) inside a zip folder. According to a Knime support, this one contains the weights in binary format. 
My question is how can I convert this file ? Or more generally, once I get my DL4J model, how can  I export him to easily reuse it.

#### Version Information

I'm using DL4J Extension on Knime 3.6

#### Contributing

Here the beginning of the `coefficients.bin`.

`=0007 4a41 5641 4350 5000 0000 0800 0349
4e54 0000 0002 0000 0001 0000 014b 0000
0001 0000 0001 0000 0000 0000 0001 0000
0063 0007 4a41 5641 4350 5000 0001 4b00
0546 4c4f 4154 bd2b 4912 3f72 4720 be73
5912 c09c 40fe 407c f8f8 bfbe ec04 beda
5db4 4018 a80d 3ffc d860 be15 8ba0 bf12
8a33 be00 24ef c1d9 d46b beee 24c4 3f6b
c3f4 c02c 1591 3dd2 904e 3dc4 59a6 3e9f
72ec bc18 7716 c054 a6da 3ee1 e3fa 3ff2`

And the whole .zip
[test.zip](https://github.com/deeplearning4j/deeplearning4j/files/3008640/test.zip)

**Comment by raver119** [comment]
p.s. We're not authors of that extension. And we're not aware of their file format.

**Comment by rosanomax** [comment]
I already did.
They told me: "This is in turn another .zip file containing the model config (layers, params, etc.) and a coefficients.bin file. This one contains the weights in binary format. To find out about the actual specification of the .bin file you would have to do some research on the DL4J/ND4J websites (ND4J is the matrix library DL4J is using)."

To see the entire topic:
https://forum.knime.com/t/migrate-dl4j-model-to-external-sources/14559

**Comment by rosanomax** [comment]
They are already saying that they have not the hand on the model format 

"Hi @rosanom,

unfortunately DL4J saves their models in their own format. As far as I know, there is no easy way to convert the format."

**Comment by raver119** [comment]
ah, so those files within your zip file are our saved models! 
Okay.

In our model archive you'll see 2-3 files usually.
1) coefficients.bin - that's INDArray with weights learned during training
2) configuration.json - JSON file describing your neural network.
3) updaterState.bin - if your network uses paramtrized updater - it's parameters will be saved separately.

**Comment by rosanomax** [comment]
Perfect, that's exactly what I get.
So in my case I just want to look at the coefficients.bin
I'll try to deal with this INDArray file then, I'm not very comfortable with Java.
Thanks!

**Comment by raver119** [comment]
But what you’re actually trying to do?

**Comment by rosanomax** [comment]
Sorry I'm a beginner.
My coefficients.bin is currently unreadable. I can't directly access the weights leared as this file is just HexaDecimal.

> 
0007 4a41 5641 4350 5000 0000 0800 0349
4e54 0000 0002 0000 0001 0000 014b 0000
0001 0000 0001 0000 0000 0000 0001 0000
0063 0007 4a41 5641 4350 5000 0001 4b00
0546 4c4f 4154 bd2b 4912 3f72 4720 be73
...
> 

So I would like an easy way to read it.

**Comment by raver119** [comment]
Right, that’s binary form of Float array. Please explain what you’re trying to do, and I’ll try to guide you. What’s the goal?

**Comment by rosanomax** [comment]
Ok, I'll try to clarify.
My initial purpose is to implement my DJ4L model on a C application (I used knime to train my neural network with DJ4L extension, and I'll now code it on C).
I didn't find an easy way to export the model like PMML, so I was wondering to retrieve my weight matrices, to code it manually.

**Comment by raver119** [comment]
Aha. I see. One one hand that's definitely possible. In c++ we have Graph concept that you can use to build neural network, so you won't need to write actual operations yourself from scratches.

On other hand, that'll involve some coding in Java: your nn parameters come in one file, all layers within your nn use different regions of that matrix.

**Comment by raver119** [comment]
To read your weights from file there's one method: 
`INDArray array = Nd4j.readBinary(file);`

**Comment by AlexDBlack** [comment]
The coefficients.bin file is a (usually float) array of the parameters in row vector format - all parameters for the network concatenated together. Using that directly isn't recommended - as to do so, you'll need to reshape the parameters in exactly the right way to recover the matrices. That's difficult an unnecessary.

Instead, I'd suggest loading the model using MultiLayerNetwork.load(File) or ComputationGraph.load(File) (depending on the format) and then using paramTable().
Parameters are keyed as follows:
* For MultiLayerNetwork: "3_W" for weights ("W") of layer 3 ("3_")
* For ComputationGraph: "MyLayer_W" for weights ("W") of the specified layer name ("MyLayer")

To export to C in C array order, I would recommend doing the following:
```myNetwork.paramTable().get("0_W").dup('c').data().asFloat()```. That will give you a float[] array you can export for use in c++. The shape of the array is given by ```myNetwork.paramTable().get("0_W").shape()```
