### ISSUE TITLE
Non-SDVariable invertPermutation

### ISSUE THREAD

**Issue by rnett** [deeplearning4j/deeplearning4j#7364]
There is a quite nice `invertPermutation` method in SameDiff, but it only applies for SDVariable permute sequences.  It would be nice to have a utility `invertPermutation` method for int and long arrays, probably not in `SameDiff` (it is also useful for NDArray permutations, etc.).

I can implement and PR this if someone tells me where to put it.

**Comment by AlexDBlack** [comment]
Sure, PR for this would be good.
I think this would be an appropriate place: https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-common/src/main/java/org/nd4j/linalg/util/ArrayUtil.java

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/7371
