### ISSUE TITLE
Libnd4j buildnativeoperations.sh fails

### ISSUE THREAD

**Issue by rnett** [deeplearning4j/deeplearning4j#7365]
#### Issue Description

I tried to build Nd4j with WSL Ubuntu installed, which failed.  Presumably that was because of the paths, so I uninstalled WSL Ubuntu.

Now, when building from maven, I get a few blank lines of output, then the build fails with:
```
[ERROR] Failed to execute goal org.bytedeco:javacpp:1.4.4:build (javacpp.cppbuild.compile) on project libnd4j: Execution javacpp.cppbuild.compile of goal org.bytedeco:javacpp:1.4.4:build failed: Process exited with an error: -1
```

The last thing ran was:
```
[INFO] --- javacpp:1.4.4:build (javacpp.cppbuild.compile) @ libnd4j ---
[INFO] Detected platform "windows-x86_64"
[INFO] Building for platform "windows-x86_64"
[INFO] bash "C:\...\deeplearning4j\libnd4j/buildnativeoperations.sh" --build-type release --chip cpu --platform windows-x86_64 --chip-extension "" --chip-version 10.0 --compute "" "" 
 
 
 
 [INFO] ------------------------------------------------------------------------
```

If I go and try to run the script manually from MinGW bash, I get:
```
C:\...\deeplearning4j\libnd4j/buildnativeoperations.sh: line 22: cd: too many arguments
```

I'm guessing this is because of spaces in the path.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-SNAPSHOT
* platform information (OS, etc): Windows 10

**Comment by saudet** [comment]
What happens if you change that line to `cd "$DIR"`?

**Comment by rnett** [comment]
I suspect that fixes it.  Apparently I'm missing a few dependencies, although maven still fails silently, I can run the script from mingw.

Closing as it seems to be fixed.
