### ISSUE TITLE
Have SDVariable use Kotlin operator method names

### ISSUE THREAD

**Issue by rnett** [deeplearning4j/deeplearning4j#7367]
SDVariable has quite a few methods that Kotlin will provide operators for if named correctly, like the plus, multiply, ect.  However, most of them are named wrong to automatically have operators.

We can either change the names or create overloads.  Imo changing is cleaner, although it will break stuff.

 * `add` to `plus`
 * `sub` to `minus`
 * `mul` to `times`

If the `addi` type methods overwrite the current variable (e.g. `this.addi(other)` stores the result in `this`) they could be changed to `plusAssign` type methods, but those names are less clean and not as used, so they are probably fine.

Can make a PR if/when the best way to do it is decided.

**Comment by treo** [comment]
Another way to deal with this may be to just create a kotlin helper library, that has those overloads as extension functions.

**Comment by rnett** [comment]
Yeah, I've done that and it works, but it a bit clunky and I don't see much of a downside to just changing the names.

**Comment by treo** [comment]
DL4J is used by quite a lot of people, breaking their code sounds like a lot of downside to me

**Comment by AlexDBlack** [comment]
Yeah, I'm opposed to renaming them, as we want SDVariable to match INDArray as much as possible to minimize the learning/switching costs. Plus breaking API changes are something we try to avoid unless there's a very good reason (and I'm not sure this is good enough).

Another option that that might work is adding overloads: so keep SDVariable.add, but introduce an SDVariable.plus method that is an alias - i.e., just calls add internally.

**Comment by rnett** [comment]
Yeah, I brought that up in the OP, for exactly that reason.  Although it still clutters things up a bit.

Would it be worth marking the originals as deprecated and having them call the new ops instead?

**Comment by AlexDBlack** [comment]
> Would it be worth marking the originals as deprecated and having them call the new ops instead?

No, I'm opposed to deprecating add etc, for the same reassons I outlined earlier. Unless we change INDArray to match (and we're not doing that) it just creates additional cognitive load for most users, just so Kotlin users can have a slightly easier time. :)

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/7371
