### ISSUE TITLE
Add reshape, permute and other common SameDiff operations to SDVariable

### ISSUE THREAD

**Issue by rnett** [deeplearning4j/deeplearning4j#7368]
There are a number of common unary operations that only exist in SameDiff.  In particular, reshape and permute.

You could make a case for moving reverse, repeat, sum, max, etc, but I don't think they are used frequently enough for it to be necessary, where I think reshape and permute are.

I can implement this if approved.

**Comment by AlexDBlack** [comment]
We have reshape(SDVariable) already, we should add a reshape(long...) IMO. I'm in favor of adding permute (that's very common) and dot methods too.

Sum, max etc are staying. They are very common.
Repeat and reverse - there's no SDVariable repeat/reverse methods. We don't need them on SDVariable IMO.

**Comment by rnett** [comment]
Ah, I don't know how I missed that max etc were already there.

I will definitely add reshape and permute for int... and long..., and a permute for SDVariable, and dot.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/7371
