### ISSUE TITLE
nd4j build uses bash to call script, errors on windows with WSL

### ISSUE THREAD

**Issue by rnett** [deeplearning4j/deeplearning4j#7372]
The nd4j build calls bash from maven to call the `buildnativeoperations.sh` script.

On windows with WSL installed, this will error, either because you have no subsystems, or most of the time the subsystem won't support the given path (its a windows path).

**Comment by printomi** [comment]
Have you tried to build from MSYS2 shell?
FYI, the documentation is work-in-progress in #6835 that you can read [here](https://github.com/deeplearning4j/deeplearning4j/blob/2dc9b416b05eeaeae8e3798ee0c1955450e5b6fb/docs/deeplearning4j/templates/build-from-source.md). 
If you still have trouble building DL4J (or any of it's prerequisites, like ND4J), please report it under #6835 .

**Comment by rnett** [comment]
Msys2 works, once WSL is disabled.  The issue is that WSL overwrites Msys2's bash path entry.

**Comment by raver119** [comment]
Issue was fixed afaik.
