### ISSUE TITLE
DL4j doesn't work with Java 9 module-info.java System due to split package issue

### ISSUE THREAD

**Issue by HPComputing** [deeplearning4j/deeplearning4j#7377]
#### Issue Description

- encountered behavior: 100 errors due to split package issue of Java 9 Module System when using module-info.java.
 
Error:java: module nd4j.native.platform reads package org.nd4j.linalg.factory from both nd4j.api and nd4j.context
Error:java: module nd4j.native reads package org.nd4j.linalg.factory from both nd4j.api and nd4j.context
Error:java: module nd4j.native.api reads package org.nd4j.linalg.factory from both nd4j.api and nd4j.context

#### Version Information

* Deeplearning4j version: 1.0.0-beta3
* platform information: Windows 10

#### Contributing

Don't use module-info.java will avoid this issue, but this will disable Java 9 Module System. 
Is there a solution to make DL4j work with Java 9 Module System?

**Comment by saudet** [comment]
We'll need to do a bit of refactoring for that eventually. For now, it's not a high priority because it would also mean figuring out a way to deal with dependencies that at not compliant, which is pretty much all of them.

**Comment by cowwoc** [comment]
On a related note, you will need to rename the `dl4j-native` module because currently it triggers the following error at load-time:

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for C:\Users\Gili\.m2\repository\org\nd4j\nd4j-native\1.0.0-beta6\nd4j-native-1.0.0-beta6.jar
Caused by: java.lang.IllegalArgumentException: nd4j.native: Invalid module name: 'native' is not a Java identifier
```

**Comment by cowwoc** [comment]
A year later, what is the state of your dependencies? Are most of them compliant with Java Modules? It would help if you could provide a list so we could chase down any stragglers.

**Comment by saudet** [comment]
Not much changed, not many places seem to adopt JPMS. BTW, OSGi also doesn't support split packages, so please follow up with these guys too, see issue #3022.

**Comment by AlexDBlack** [comment]
FYI full list of split packages here: https://github.com/eclipse/deeplearning4j/issues/8870

**Comment by AlexDBlack** [comment]
FYI I have merged this PR that resolves all split package issues: https://github.com/KonduitAI/deeplearning4j/pull/411
https://github.com/eclipse/deeplearning4j/issues/8870

It will be available on eclipse/deeplearning4j within a day or so of this comment.
Note this is a breaking change for some packages/imports.

**Comment by ennioVisco** [comment]
Any updates on this?

**Comment by agibsonccc** [comment]
@ennioVisco  I'm closing this. We've had java 9 support for a while now. Please open a new issue with something concrete and I'd be happy to address it if you are having issues with M2.1+. Thanks!
