### ISSUE TITLE
Capsnet layers

### ISSUE THREAD

**Issue by rnett** [deeplearning4j/deeplearning4j#7386]
I'm most of the way through implementing CapsNet layers w/ SameDiff for some of my stuff.  Once I have them working I can make a PR.

Atm, they are rather slow, although I haven't been able to test them on CUDA yet b/c of bugs, and I'm not sure how much of that is my implementation and how much is just capsules being capsules.

What I've been using as references:
[The original paper](http://papers.nips.cc/paper/6975-dynamic-routing-between-capsules.pdf)
[A tensorflow implementation](https://github.com/naturomics/CapsNet-Tensorflow)
[A notebook for text processing](https://www.kaggle.com/fizzbuzz/beginner-s-guide-to-capsule-networks/notebook)

I currently have the SameDiff implementation that runs, although I can't say how well yet.  Assuming it does work I will most likely make a PR tomorrow.

**Comment by rnett** [comment]
Also, if there is a way to freeze gradients on a SDVariable, you can apparently freeze them when doing the routing.  I don't know if there's any major improvements, but it wouldn't hurt.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/7391
