### ISSUE TITLE
SameDiff: Improve SDVariable.get() tests

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7394]
At present, we've only got 1 test, and it's not a good one due to zeros for the expected array...
https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/autodiff/samediff/SameDiffTests.java#L2257-L2282

**Comment by rnett** [comment]
That is remarkably useless, I didn't even notice that.

Changed it to `Nd4j.linspace(1, 100, 100).reshape(10L, 10L)` in #7392.
