### ISSUE TITLE
SameDiff mean w/ dimensions gradient is incorrect

### ISSUE THREAD

**Issue by rnett** [deeplearning4j/deeplearning4j#7405]
#### Issue Description

The gradient of the `SameDiff.mean` is always the gradient as if it is calculated over all dimensions, even if dimensions are specified.

See the tensorflow equivalent calculations [here](https://gist.github.com/rnett/179c75740774c807dc0761ec5060188c#file-mean-gradient-test-ipynb).

The DL4J equivilant looks like:
```java
@Test
public void test1() {
    SameDiff SD = SameDiff.create();
    SDVariable a = SD.reshape("a", SD.linspace("at", 1, 15, 15), 3, 5);//.add(1);
    SDVariable b = SD.one("b", 3, 5);//.add(3);

    SDVariable out = a.mul(b).mean(1);

    //System.out.println(Arrays.toString(out.eval().shape()));
    out.eval();

    SD.execBackwards(null, Lists.asList("a", new String[]{}));
    //System.out.println(out.eval());
    System.out.println(SD.grad("a").eval());
}

@Test
public void test2() {
    SameDiff SD = SameDiff.create();
    SDVariable a = SD.reshape("a", SD.linspace("at", 1, 15, 15), 3, 5);//.add(1);
    SDVariable b = SD.one("b", 3, 5);//.add(3);

    SDVariable out = a.mul(b).mean(0, 1);

    //System.out.println(Arrays.toString(out.eval().shape()));
    out.eval();

    SD.execBackwards(null, Lists.asList("a", new String[]{}));
    //System.out.println(out.eval());
    System.out.println(SD.grad("a").eval());
}
```
and prints
```java
[[    0.0667,    0.0667,    0.0667,    0.0667,    0.0667], 
 [    0.0667,    0.0667,    0.0667,    0.0667,    0.0667], 
 [    0.0667,    0.0667,    0.0667,    0.0667,    0.0667]]
```
for both tests.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-SNAPSHOT
* platform information (OS, etc): Windows 10
* CPU Backend

**Comment by AlexDBlack** [comment]
I'm not sure the tests are equivalent.

https://www.tensorflow.org/versions/r1.9/api_docs/python/tf/gradients?hl=en
> gradients() adds ops to the graph to output the derivatives of ys with respect to xs. It returns a list of Tensor of length len(xs) where each tensor is the sum(dy/dx) for y in ys.

So, ```grad = tf.gradients(mean, [a])[0]``` results in grad = dMean/da, if I am understanding the TF docs correctly.
For samediff, you are comparing it to dL/da, where L = out.sum().  Though frankly the "non-scalar output should be treated as L=out.sum()" case isn't well tested.
The fact that the two cases are equal is cause for concern, however.
