### ISSUE TITLE
DL4J: MaskZeroLayer - JSON deserialization issue

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7409]
https://github.com/deeplearning4j/deeplearning4j/issues/3979#issuecomment-478420395

> Will support be addded ? I'm using SNAPSHOTS and its able to convert the model but not read it again -
> Caused by: java.lang.RuntimeException: org.nd4j.shade.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class org.deeplearning4j.nn.conf.layers.util.MaskZeroLayer]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)

**Comment by Anriod** [comment]
Is there a workaround for this ?

**Comment by AlexDBlack** [comment]
@Anriod I'll try to reproduce this and fix it soon.
I only became aware of it as an issue just now.

**Comment by AlexDBlack** [comment]
Reproduced and fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/7415
That PR should be merged soon; the fix will be available on snapshots after that.

**Comment by Anriod** [comment]
Sounds Good!

**Comment by Anriod** [comment]
When will the fix be in snapshots?

**Comment by saudet** [comment]
Should in there already. Still not fixed?

**Comment by Anriod** [comment]
It wasn't there a day or two back I think, but I got the latest SNAPSHOTS just now and it's fixed. Thanks!
