### ISSUE TITLE
ND4J : INDArray.slice() produces wrong shape (order is modified)

### ISSUE THREAD

**Issue by alexanderst** [deeplearning4j/deeplearning4j#7447]
#### Issue Description
There's INDArray matrix filled with doubles and shape [2,1,2,1,1,16384,1,99]
Method matrix.slice(0) produces INDArray with shape [2,1,2,1,1,16384,1,102].

In example below - second column of vector is lost due to changed order.

double[] data = new double[]{15.0, 16.0};
INDArray vector = Nd4j.createFromArray(data.reshape(1,2));
INDArray slice = matrix.slice(0);

**Comment by AlexDBlack** [comment]
Looks like it's this special case for vectors that is the problem:
https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L4116-L4119

I think we can remove that...
