### ISSUE TITLE
ND4J: Multiple JVM Crashes on CPU (master)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7453]
Windows 10, CPU, master.

This must be new in a recent PR, I didn't see it before.
To reproduce, tests under org.nd4j.autodiff.

Reproducible in isolation when running just this test: LayerOpValidation.testXwPlusB: https://gist.github.com/AlexDBlack/afd7c6fb95bde87917674a01d10baa2f

**Comment by AlexDBlack** [comment]
Same thing for LayerOpValidation.ReluLayer...

**Comment by raver119** [comment]
Fixed.
