### ISSUE TITLE
FileRecordWriter might return wrong value

### ISSUE THREAD

**Issue by helt** [deeplearning4j/deeplearning4j#7456]
Hi,

stumbled across this line in `1.0.0-beta3` datavec

https://github.com/deeplearning4j/deeplearning4j/blob/41f220fbc2410efe71d535f8344f74e11ea8a44a/datavec/datavec-api/src/main/java/org/datavec/api/records/writer/impl/FileRecordWriter.java#L99

Is it possible, that this line should be

```
        return PartitionMetaData.builder().numRecordsUpdated(batch.size()).build();
```

**Comment by saudet** [comment]
I would say you're right. Could you send a pull request to have this reviewed by @AlexDBlack along with a new unit test that fails without this patch? Thanks!

**Comment by AlexDBlack** [comment]
Thanks for flagging. But it looks like this was fixed some time ago on master. I've checked other writers too, they seem correct also.
