### ISSUE TITLE
LSTMCharModellingExample crashing on latest snapshot

### ISSUE THREAD

**Issue by tschut** [deeplearning4j/deeplearning4j#7463]
#### Issue Description
When running LSTMCharModellingExample (unmodified) on the latest snapshot, it crashes in native code: https://gist.github.com/tschut/1aa6f3916abdffe86f4e3786b0fc991f.

#### Version Information

Please indicate relevant versions, including, if relevant:
* Latest snapshot build of dl4j
* Running on CPU only, no CUDA

**Comment by raver119** [comment]
Can you please upload this file as well: `C:\Users\tschu\IdeaProjects\WhatsAppTextRNN\hs_err_pid29744.log`

**Comment by tschut** [comment]
[hs_err_pid22120.log](https://github.com/deeplearning4j/deeplearning4j/files/3050606/hs_err_pid22120.log)

NB it's a different log, but the same crash.

**Comment by raver119** [comment]
Sorry, this issue was already fixed yesterday eveining. You just need to wait for next snapshots build.
