### ISSUE TITLE
Libnd4j: layer_norm (broadcasting?) fails with mixed orders

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7473]
layer_norm op provides different output when the result array is not the same order as the input array.

This appears to be the underlying cause of this issue: https://github.com/deeplearning4j/deeplearning4j/issues/7443

Given layer norm is a simple op, it can only be standardize or broadcasting that is the problem here...

The C in, C out case is fine. As is the F in, F out case. But C in, F out fails, as does F in, C out.

```
    @Test
    public void testLayerNormMixedOrders(){
        Nd4j.getRandom().setSeed(12345);
        INDArray input = Nd4j.rand(DataType.DOUBLE, 3, 8).dup('f');
        INDArray gain = Nd4j.rand(DataType.DOUBLE, 1, 8).dup('f');
        INDArray bias = Nd4j.rand(DataType.DOUBLE, 1, 8).dup('f');

        INDArray outFF = Nd4j.create(DataType.DOUBLE, new long[]{3,8}, 'f');
        INDArray outCC = Nd4j.create(DataType.DOUBLE, new long[]{3,8}, 'c');
        INDArray outFC = Nd4j.create(DataType.DOUBLE, new long[]{3,8}, 'c');
        INDArray outCF = Nd4j.create(DataType.DOUBLE, new long[]{3,8}, 'f');

        //F in, F out case
        Nd4j.exec(DynamicCustomOp.builder("layer_norm")
                .addInputs(input, gain, bias)
                .addOutputs(outFF)
                .addIntegerArguments(1) //Axis
                .build());

        //C in, C out case
        Nd4j.exec(DynamicCustomOp.builder("layer_norm")
                .addInputs(input.dup('c'), gain.dup('c'), bias.dup('c'))
                .addOutputs(outCC)
                .addIntegerArguments(1) //Axis
                .build());

        assertEquals(outFF, outCC);       //OK

        //C in, F out case
        outFF.assign(0);
        Nd4j.exec(DynamicCustomOp.builder("layer_norm")
                .addInputs(input.dup('c'), gain.dup('c'), bias.dup('c'))
                .addOutputs(outCF)
                .addIntegerArguments(1) //Axis
                .build());
        assertEquals(outCC, outCF);       //Fails here

        //F in, C out case
        outFF.assign(0);
        Nd4j.exec(DynamicCustomOp.builder("layer_norm")
                .addInputs(input, gain, bias)
                .addOutputs(outFC)
                .addIntegerArguments(1) //Axis
                .build());
        assertEquals(outCC, outFC);       //Fails here
    }
```

First failure (CF case):
![image](https://user-images.githubusercontent.com/2360237/55713256-a172d480-5a33-11e9-84bd-9340be244c22.png)

Second failure (FC case):
![image](https://user-images.githubusercontent.com/2360237/55713287-b5b6d180-5a33-11e9-9d1a-15fce5a3ded6.png)

**Comment by treo** [comment]
I've narrowed it down to applyTrueBroadcast with a given output target. 

The following test (in cpp) fails:
```
TEST_F(DeclarableOpsTests15, Test_apply_true_scalar_1) {
    auto x = NDArrayFactory::create<double>('f', {2, 3}, {1., 2., 3., 4., 5., 6.});
    auto y = NDArrayFactory::create<double>('f', {2, 3}, {5., 4., 3., 2., 1., 0.});
    auto z = NDArrayFactory::create<double>('c', {2, 3});

    auto exp = x - y;

    x.applyTrueBroadcast(nd4j::BroadcastOpsTuple::Subtract(), &y, &z, true);

    ASSERT_EQ(exp, z);
}
```

**Comment by shyrma** [comment]
Hi, Paul

Thanks for problem narrowing.
Initially it has been assumed that broadcast op should not be applied to arrays with same shape.
However since such situations occur in your tests we simply provided redirection in broadcast op to pairwise op in corresponding cases. Changes are already in master.

**Comment by treo** [comment]
Hi @shyrma 

It looks like I overcooked the test while trying to simplify it.

```cpp
TEST_F(DeclarableOpsTests15, Test_apply_broadcast_2) {
    auto x = NDArrayFactory::create<double>('f', {2, 3}, {1., 2., 3., 4., 5., 6.});
    auto y = NDArrayFactory::create<double>('f', {1, 3}, {5., 4., 3.});
    auto z = NDArrayFactory::create<double>('c', {2, 3});

    auto exp = x - y;
    x.applyTrueBroadcast(nd4j::BroadcastOpsTuple::Subtract(), &y, &z, true);

    ASSERT_EQ(exp, z);
}
```

This test uses shapes which do require broadcasting, and it does still fail.

**Comment by shyrma** [comment]
Hi, Paul
Yes, that was bug in NDArray::applyBroadcast - we gave same input tad-shapeInfo both for input and output arrays, ant it was wrong, now 2 shapeInfos are given: input tad-shapeInfo for input array and output tad-shapeInfo for output array.
Thanks for catching this.
Corresponding pr is already merged.

**Comment by AlexDBlack** [comment]
Original layer norm issue is now confirmed passing, thanks @shyrma @treo
