### ISSUE TITLE
UnsupportedKerasConfigurationException: Unsupported keras layer type Lambda.

### ISSUE THREAD

**Issue by vmichalak** [deeplearning4j/deeplearning4j#7478]
#### Issue Description

Hello, 
I attempt to load this model https://www.dropbox.com/s/mlmr4qj9der7wdw/saved_model.h5?dl=0 with deeplearning4j but i get this issue:

> Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type Lambda. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:318)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:218)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:164)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:96)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:307)
	at com.vmichalak.derush.business.machinelearning.PogChampModel.<init>(PogChampModel.kt:17)
	at com.vmichalak.derush.business.machinelearning.PogChampModelKt.main(PogChampModel.kt:26)
	at com.vmichalak.derush.business.machinelearning.PogChampModelKt.main(PogChampModel.kt)

My code is in Kotlin:

```
class PogChampModel {
    private val path = ClassPathResource("pogchamp_model.h5").file.path
    private val model: ComputationGraph

    constructor() {
        model = KerasModel()
            .modelBuilder()
            .modelHdf5Filename(path)
            .enforceTrainingConfig(false)
            .buildModel()
            .computationGraph
    }
}
```

#### Version Information

My Gradle file

```
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.3.21'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

    compile "org.deeplearning4j:deeplearning4j-core:1.0.0-beta3"
    compile "org.deeplearning4j:deeplearning4j-modelimport:1.0.0-beta3"
    compile "org.nd4j:nd4j-native-platform:1.0.0-beta3"

    compile "org.mongodb:mongo-java-driver:3.10.1"

    testCompile "junit:junit:$junit_version"
    testCompile "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
    testCompile "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

#### Contributing

If i can help you to correct this issue, don't hesitate to ask me.
Thanks in advance, 
Valentin

**Comment by AlexDBlack** [comment]
Lambda layers are supported, but you'll need to define them (we can't import arbitrary python code) - so I think this is more of a docs issue than anything...
You'll need to register and define the lambda in java as per these unit tests: https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-modelimport/src/test/java/org/deeplearning4j/nn/modelimport/keras/e2e/KerasLambdaTest.java

**Comment by AlexDBlack** [comment]
I'll close this one in favor of this issue: https://github.com/deeplearning4j/deeplearning4j/issues/7479
