### ISSUE TITLE
ND4J and DL4J: CUDA test failures

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7482]
**Issues List (ND4J)**
- TFGraphTestAllLibnd4j
- TFGraphTestAllSameDiff
- TFGraphTestZooModels
- HeirarchicSoftmaxTests (passes when run in isolation)
- LapackTests.testCholeskyL, .testCholeskyU
- BERTGraphTest.testBert - https://github.com/deeplearning4j/deeplearning4j/issues/7523
- BooleanIndexingTest.testEpsStuff_1 - passes in isolation, fails as part of full test suite - https://gist.github.com/AlexDBlack/cc1f88c8e794589a2848d2e3d4676927

**Comment by raver119** [comment]
WeightInitUtilTest.testXavierLegacy
CompareTrainingImplementations.testCompareMlpTrainingIris 

both pass for me at this moment. please confirm you still can reproduce it.

**Comment by AlexDBlack** [comment]
Closing in favor of issue with more recent tests: https://github.com/deeplearning4j/deeplearning4j/issues/7602
