### ISSUE TITLE
DL4J: Nearest Neighbor test failures

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7489]
I'm seeing the following tests fail on CPU on current master:

**deeplearning4j-nearestneighbor-server**

- NearestNeighborTest.testNearestNeighbor (expected 1, actual 0)

**deeplearning4j-nearestneighbors-core**

- KMeansTest: Most (all?) tests are crashing JVM
- rPUtilsTest.testDistancesComputeBatch

**Comment by alexanderst** [comment]
NearestNeighborTest.testNearestNeighbor - method behavior looks correct to me, so test was corrected and enhanced.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/blob/e830986ec156ebbb21828193770b921abc9c4af1/deeplearning4j/deeplearning4j-nearestneighbors-parent/deeplearning4j-nearestneighbor-server/src/test/java/org/deeplearning4j/nearestneighbor/server/NearestNeighborTest.java#L54-L59

@alexanderst My understanding of this is that we want the 2 nearest arrays to index 0 - _excluding index 0_. Obviously an array is always nearest to itself, by definition - but that isn't very useful...
(@raver119 can you confirm?)

**Comment by alexanderst** [comment]
I've corrected code to exclude target point from resulting array.

**Comment by alexanderst** [comment]
Fixed and merged.
