### ISSUE TITLE
nd4j matrix calculate is so so so slower than for? Why?

### ISSUE THREAD

**Issue by whaozl** [deeplearning4j/deeplearning4j#7498]
```
package test;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.factory.Nd4j;

public class Test01_Nd4j {
    public static void main(String[] args) {
        float[] a=new float[]{1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f, 1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f,
                1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f, 1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f,
                1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f, 1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f,
                1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f, 1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f,
                1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f, 1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f,
                1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f, 1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f,
                1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f, 1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f,
                1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f, 1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f,
                1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f, 1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f,
                1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f, 1.0f,2.0f,3.0f,4.0f,5.0f,6.0f,7.0f,8.0f,9.0f,0.0f
        };
        float[] b=a;

        long time1 = System.nanoTime();
        float[] c=new float[200];
        for(int i=0, len=200; i<len; i++){
            c[i]=a[i] * b[i];
        }
        long time2 = System.nanoTime();
        System.out.println("for : "+(time2-time1));

        INDArray A=Nd4j.create(a, new int[]{1,200});
        INDArray B=Nd4j.create(b, new int[]{1,200});
        time1 = System.nanoTime();
        INDArray C=A.mul(B);
        time2 = System.nanoTime();
        System.out.println("nd4j : "+(time2-time1));
    }
}
```
this is the result:
```
for : 4812
nd4j : 82936655
```

pom.xml version is:
```
            <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>nd4j-native-platform</artifactId>
                <version>1.0.0-beta3</version>
            </dependency>
```

**Comment by raver119** [comment]
Because of:
1) `INDArray C=A.mul(B); ` this code also creates array C. That includes memory allocation, which isn't the same as taking float[200] from java heap.
2) First call to native library also invokes shared library load. Which is very expensive.
3) Your code has just 1 loop. No checks for anything, so literally 0 "framework expenses".  If you're 100% sure you won't ever need validation, you should never use any frameworks, and just code loops like you did with this test.

**Comment by raver119** [comment]
P.s. by framework expenses i mean basically pack of validations applied on various steps through the op execution:
1) data types validation
2) arrays length/shape validation
3) arrays existence validation
4) checks for op profiler configuration
5) arrays order/strides checks in search of better application


P.s. you've also forgot to add avx2 classifier to your pom.xml, i suppose you're testing on recent enough PC.

**Comment by AlexDBlack** [comment]
Beyond what Raver mentioned, this makes a number of common benchmark mistakes.
We have a whole page on running benchmarks properly, I would encourage you to read that: https://deeplearning4j.org/docs/latest/deeplearning4j-benchmark

**Comment by whaozl** [comment]
@raver119 @AlexDBlack But numpy for python is very fast, I think it should be a balance between performance and security, such as numpy. At present, this speed is 17235 times worse. This is terrible.

**Comment by AlexDBlack** [comment]
@whaozl You completely ignored what I said.
Your benchmark timing isn't valid. There's no point discussing your performance until you implement a non-flawed benchmark. Please read the link I posted earlier before commenting here again.

**Comment by saudet** [comment]
@whaozl ND4J has a higher initialization cost than NumPy, in part because of Java, that's what you're measuring here.

**Comment by whaozl** [comment]
Maybe the way I said is not quite right. In fact, I am doing matrix operations in the same environment, because I have a large number of such matrix repeat operations. In fact, I want to be a Java scientific computing library, just like numpy.
