### ISSUE TITLE
DL4J: Add way to load/convert models to specific datatype

### ISSUE THREAD

**Issue by dollarHome** [deeplearning4j/deeplearning4j#7520]
#### Issue Description
I was looking for a way to load a pretrained FP16 Resnet50 model and run on CPUs. There is no direct way to do that but a round about way as suggested by @raver119 on gitter chat (4/10/2019)

@raver119 suggested:
"to get resnet on fp16 right now you'll probably have to cast params to fp16, and assign these params to your model
but i think we should improve that
cc @AlexDBlack ^^^
there's also support for bfloat16 planned
it's already available in c++, just wasn't introduced to java yet
but params of your nn is just INDArray
but you'd better file an issue
and we'll provide convenient method to do that
we'll need to do that for quantized types anyway"

* Deeplearning4j version - snapshots
* platform information (OS, etc): Linux, Ubuntu18.04, 28c SKX Xeon system

**Comment by AlexDBlack** [comment]
Yes, we will want this functionality.

I man thinking we could have an API like:
* MultiLayerNetwork.load(File, DataType) - "load as FP16 regardless of what the model is saved as"
* MultiLayerNetwork.convertTo(DataType) - "recreate the network with the specified data type"

Of course we'll want to add the equivalent methods for ComputationGraph.
We should think about this for SameDiff also, though conversion might be on a per variable basis there...
