### ISSUE TITLE
ND4J Unit tests - unexpectedly large memory use, not released?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7522]
Here's something I observed when running tests on CUDA (GTX970, Windows 10):

Earlier tests look like this:
```
Ending org.nd4j.autodiff.opvalidation.LayerOpValidation; Physical bytes after: 4227174400; Max: 11453595648
```

Later tests all look like this:
```
Ending org.nd4j.linalg.workspace.BasicWorkspaceTests; Physical bytes after: 12390559744; Max: 11453595648
```

Though sometimes some memory is released in later tests (physical bytes gets down to 10gb in a few places) but it still remains higher than expected/necessary. And I'm seeing GPU OOMs in a few tests (I don't think it's just large allocations in the tests themselves).

Not sure why, but it may indicate a problem. First guess is maybe workspaces not being cleaned up (adding that to tests should be easy).

**Comment by raver119** [comment]
right now periodic gc is disabled (not intentionally), and we're (@alexanderst and me) working on getting rid of it right now.

**Comment by raver119** [comment]
Should be fixed now, since gc changes were merged

**Comment by raver119** [comment]
+ leak in c++ fixed. better now?

**Comment by AlexDBlack** [comment]
Closing this as fixed and/or outdated.
I've been running lots of tests on CI recently, and haven't seen any issues there.
