### ISSUE TITLE
ND4J: Maven unit tests - TFGraphTest* unit tests skipped?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7525]
https://github.com/deeplearning4j/deeplearning4j/tree/master/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/imports/TFGraphs
The following tests not executing for some reason:

- TFGraphTestAllLibnd4j.java
- TFGraphTestAllSameDiff.java
- TFGraphTestZooModels.java

Commands:
```
cd nd4j-tests
mvn clean test -Pnd4j-tests-cpu,testresources
```

These run fine in IntelliJ, but for some reason aren't executing when run via mvn clean test.
They don't appear at all in the output (no errors, no logging, etc), for some reason.

The total number of tests are off too: We have around 1000 tests in these TFGraphTest* tests alone...
```
Tests run: 432, Failures: 0, Errors: 0, Skipped: 19
```

Reproduced on 2 separate windows machines, both with Maven 3.3.9

So far I've ruled out:
* Some config skipping them (Other tests in same dir run OK)
* Test resources not available (other tests needing resources pass, and removing the profile causes them to fail)
* The parameterized tests returning nothing to run (test parameters are never called/generated in first place)

**Comment by saudet** [comment]
By default, maven-surefire-plugin only includes classes that start or end with "Test" and a few variations as given here: https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html

**Comment by AlexDBlack** [comment]
Yep, that'll be it. Thanks.
https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/pom.xml#L150
That config is why it used to work - we recently changed to profiles in nd4j-tests instead of specifying test source directory...

**Comment by AlexDBlack** [comment]
Or, maybe not - looks like it should already be configured correctly:
https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-tests/pom.xml#L171-L213

**Comment by AlexDBlack** [comment]
Fixed: Turns out we need `<include>**/*.java</include>` not just `<include>*.java</include>` in the maven surefire config.
