### ISSUE TITLE
Duplicated code in org.deeplearning4j.models.word2vec.Huffman

### ISSUE THREAD

**Issue by sanity** [deeplearning4j/deeplearning4j#753]
Lines 67-78 are immediately repeated afterwards.

If this is deliberate I'd recommend moving this code into it's own method, since duplicated code is a code smell.

**Comment by agibsonccc** [comment]
Definitely!
Thanks for poking around.

**Comment by sanity** [comment]
Doh, Idea lied, they're not exactly identical.  Probably still belong in a method though.

**Comment by nyghtowl** [comment]
Code has gone through several changes since this issue was posted. If there are further code fix recommendations please submit a new issue.
