### ISSUE TITLE
DL4J: Update/replace UI theme

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7537]
See discussion here: https://github.com/deeplearning4j/deeplearning4j/issues/6907#issuecomment-481983566

**Comment by saudet** [comment]
@ejunprung Would you be able to find us a nice open source theme for this? Doesn't need to be that nice either :)

**Comment by ejunprung** [comment]
@AlexDBlack @saudet Dang...lemme Google around and get back to you.

**Comment by ejunprung** [comment]
@AlexDBlack @saudet Sorry for the delay.

I had a question. The theme that I had purchased previously ("Metro Dashboard") is now called CoreUI. 
https://github.com/coreui/coreui-free-bootstrap-admin-template

Would the Eclipse Foundation allow us to offer the DL4J training using this theme provided that we obtain a "Standard License"? Here are CoreUI's terms: "Use, by you or your one client, in a single end product which end users are not charged for.". 

I imagine most of the new template code is similar to our old template so I assume it would be a lot easier to swap out.

**Comment by saudet** [comment]
Thanks for the info! That doesn't sound like a license we could use easily as part of Eclipse, unfortunately, "single end product" is probably not going to fly... We kind of expect all members of Eclipse to use Deeplearning4j in many end user products.

**Comment by ejunprung** [comment]
Ah, gotcha. One last thing.

I see that CoreUI offers both an open-source and "Pro" version. The files in the open-source version contain "Licensed under MIT" in the header. Here's an example: https://github.com/coreui/coreui-free-bootstrap-admin-template/blob/master/src/css/style.css.

I've taken a quick look, and I'm pretty confident the open-source version contains all the components (e.g. charts, buttons, tables, and other elements) that we'd need to re-do our UI. The "Pro" version, which requires the "Standard License" mentioned above, contains additional components that we don't need.

Would this be a viable option? If not, what kind of licensing should I look out for when evaluating new templates?

**Comment by saudet** [comment]
If all the files we need are under the MIT license, that would work, yes. It seems they are available as WebJars as well: https://search.maven.org/search?q=coreui @AlexDBlack ?

**Comment by treo** [comment]
The coreui package, as available via webjars, is imported from npm, and it is listed there to have an MIT license. 

In the readme they go a bit further:
> copyright 2018 creativeLabs Łukasz Holeczek. Code released under the MIT license. There is only one limitation you can't can’t re-distribute the CoreUI as stock. You can’t do this if you modify the CoreUI. In past we faced some problems with persons who tried to sell CoreUI based templates.

As far as I can tell, it is probably the best idea to get it via webjars.

**Comment by ejunprung** [comment]
Awesome! Sounds like this is viable. Tell me if you need help replacing the theme.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/7683 - fix available on branch dev_20190506 - will be merged to master soon.
