### ISSUE TITLE
Nd4j: Jackson RowVector(De)Serializer doesn't maintain shape or datatype

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7561]
https://github.com/deeplearning4j/deeplearning4j/tree/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/lossfunctions/serde

This simply hasn't been updated for dtypes and rank 0/1 support.
The only real challenge for fixing this is maintaining backward compatibility.

This is used for weighted loss functions and a few other places.

**Comment by raver119** [comment]
I've spotted similar ptoblem with Nd4j.writeTxt - we do not store datatype there. Should be fixed as well.
