### ISSUE TITLE
DL4J Keras: Unit tests failing on master

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7562]
![image](https://user-images.githubusercontent.com/2360237/56269917-41b5b100-6138-11e9-8caa-c10cd98ca765.png)

Both appear to be the same issue.
```
UnsupportedKerasConfigurationException: No SameDiff Lambda layer found for Lambdalayer space_to_depth_x2.
```

**Comment by maxpumperla** [comment]
@farizrahman4u I think your last PR broke those tests. https://github.com/deeplearning4j/deeplearning4j/pull/7535/files

Please just add the `&& !lambdaLayers.isEmpty()` condition back in, that should suffice. Keras tests run quick enough to run them at least once before merging a PR.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/7568
