### ISSUE TITLE
ND4J/Libnd4j: JVM crash on avg/maxpool2d_bp FP16 (native backend)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7574]
No crash log - only output I've ever gotten is:
```Process finished with exit code -1073741819 (0xC0000005)```

To reproduce: Run DTypeTests.testDtypesModelVsGlobalDtypeCnn()
https://github.com/deeplearning4j/deeplearning4j/blob/0ff3ced27d454a527ecf13aba03c7c0d3e4d882a/deeplearning4j/deeplearning4j-core/src/test/java/org/deeplearning4j/nn/dtypes/DTypeTests.java#L366-L367
Global dtype doesn't matter (including when set to half); only network dtype does (only crashes when set to half, float/double are fine).

I've spent quite a bit of time trying to isolate this, but I haven't been able to.
All inputs/outputs look correct. The crash doesn't always happen - sometimes it's first iteration, sometimes like the 6th iteration.

As far as I can tell, it's not related to:
* Workspaces (fails with/without them enabled)
* Memory alignment (allocating a random number of bytes in a workspace before creating input/output doesn't help)
* Incorrect input/args

Only thing it does depend on: MKL-DNN being enabled/disabled. If MKL-DNN is disabled (via `Nd4jCpu.Environment.getInstance().setUseMKLDNN(false);`) it always runs fine.

Here's something that should be equivalent to what it's crashing on (but this runs fine):
https://gist.github.com/AlexDBlack/3466a3f654e1320a63c9b4d2f71a044b

**Comment by saudet** [comment]
MKL-DNN doesn't support half floats, or double floats for that matter, it shouldn't even be initialized. That's weird.

**Comment by shyrma** [comment]
Hi, guys

We've checked max/avgpool2d_bp and have to say following:
1) crash is absent on c++ side
2) when type is double or float16 then our stuff works and results are ok
3) when type is float then mkl-dnn works and results are wrong, for example for this test
https://github.com/deeplearning4j/deeplearning4j/blob/dc7fdcb6708d7609370f3f5d5c29c40d547b9f46/libnd4j/tests_cpu/layers_tests/DeclarableOpsTests7.cpp#L3215
expected vs output are as follows 
https://gist.github.com/shyrma/3d55dc630d3af1f8d7a2ba6d2c6f730f

also below I attached corresponding  raver's print-screen

<img width="1920" alt="dddd" src="https://user-images.githubusercontent.com/30350590/56382995-66398800-6221-11e9-90bc-bc5d0d070f89.png">

**Comment by saudet** [comment]
I've started looking at this in my branch (sa_mkldnn) by creating test instances for that, and indeed 2 tests fail with MKL-DNN:
```
[==========] 2770 tests from 124 test cases ran. (30206 ms total)
[  PASSED  ] 2768 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] TypedDeclarableOpsTests7/1.avgpool2d_bp_test3, where TypeParam = float
[  FAILED  ] TypedDeclarableOpsTests7/1.avgpool2d_bp_test4, where TypeParam = float
```

**Comment by saudet** [comment]
However, no tests for avgpool3d_bp fail with MKL-DNN and, in the case of MKL-DNN, there is essentially no difference with the code for avgpool2d_bp, so I'm inclined to think that the results for the non-MKL-DNN are wrong. @shyrma Is there an easy way to check that the tests are correct?

**Comment by raver119** [comment]
Fix merged.

**Comment by raver119** [comment]
Let's discuss mkldnn/non-mkldnn in serparate issue. I'll open new one.

**Comment by shyrma** [comment]
Hi @saudet 

 >I'm inclined to think that the results for the non-MKL-DNN are wrong. 
 >@shyrma Is there an easy way to check that the tests are correct?

 Usually we get actual(expected) numbers for our tests by means of corresponding ops from tf/torch/chainer if such are present of course.
 In case of TypedDeclarableOpsTests7/1.avgpool2d_bp_test4 we used following tf code, numbers produced exactly in this tf test are quoted in our c++ test

 ```
import numpy as np
import tensorflow as tf
from tensorflow.python.ops import gen_nn_ops
from tensorflow.python.ops import nn_ops
from tensorflow.python.ops import nn_grad

bS=2; iH=4;iW=3;  iC=3;  kH=3;kW=2;  sH=1;sW=1;  pH=0;pW=0;  
oH=2;oW=2;

inp   = tf.Variable(np.linspace(1., bS*iC*iH*iW, bS*iC*iH*iW, dtype=np.float32).reshape([bS, iH, iW, iC]))		
gradO = tf.Variable(np.float32(np.linspace(0.1, bS*iC*oH*oW*0.1, bS*iC*oH*oW).reshape([bS, oH, oW, iC])))
kern  = [kH,kW]
strid = [sH,sW]
dilat = [1,1]

output = tf.nn.pool(inp, window_shape = kern, pooling_type="AVG", padding="VALID", dilation_rate=dilat, strides= strid, name="opp", data_format = 'NHWC')
op = tf.get_default_graph().get_operation_by_name('opp')
gradI = nn_grad._AvgPoolGrad(op, gradO)  

sess = tf.Session()
init =tf.global_variables_initializer()
sess.run(init)
np.set_printoptions(precision=5, suppress=True)
print(np.array2string(sess.run(gradI), separator=', '))
print(gradI.shape)
```
