### ISSUE TITLE
MKL-DNN/non-MKL-DNN pooling backprop results disparity

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#7581]
Hi, guys

We've checked max/avgpool2d_bp and have to say following:

when type is float then mkl-dnn works and results are wrong, for example for this test
deeplearning4j/libnd4j/tests_cpu/layers_tests/DeclarableOpsTests7.cpp
Line 3215 in dc7fdcb
 TEST_F(DeclarableOpsTests7, avgpool2d_bp_test4) { 

expected vs output are as follows
https://gist.github.com/shyrma/3d55dc630d3af1f8d7a2ba6d2c6f730f

cc @shyrma @saudet

**Comment by shyrma** [comment]
Hi @saudet 

 >I'm inclined to think that the results for the non-MKL-DNN are wrong. 
 >@shyrma Is there an easy way to check that the tests are correct?

 Usually we get actual(expected) numbers for our tests by means of corresponding ops from tf/torch/chainer if such are present of course.
 In case of TypedDeclarableOpsTests7/1.avgpool2d_bp_test4 we used following tf code, numbers produced exactly in this tf test are quoted in our c++ test

 ```
import numpy as np
import tensorflow as tf
from tensorflow.python.ops import gen_nn_ops
from tensorflow.python.ops import nn_ops
from tensorflow.python.ops import nn_grad

bS=2; iH=4;iW=3;  iC=3;  kH=3;kW=2;  sH=1;sW=1;  pH=0;pW=0;  
oH=2;oW=2;

inp   = tf.Variable(np.linspace(1., bS*iC*iH*iW, bS*iC*iH*iW, dtype=np.float32).reshape([bS, iH, iW, iC]))		
gradO = tf.Variable(np.float32(np.linspace(0.1, bS*iC*oH*oW*0.1, bS*iC*oH*oW).reshape([bS, oH, oW, iC])))
kern  = [kH,kW]
strid = [sH,sW]
dilat = [1,1]

output = tf.nn.pool(inp, window_shape = kern, pooling_type="AVG", padding="VALID", dilation_rate=dilat, strides= strid, name="opp", data_format = 'NHWC')
op = tf.get_default_graph().get_operation_by_name('opp')
gradI = nn_grad._AvgPoolGrad(op, gradO)  

sess = tf.Session()
init =tf.global_variables_initializer()
sess.run(init)
np.set_printoptions(precision=5, suppress=True)
print(np.array2string(sess.run(gradI), separator=', '))
print(gradI.shape)
```
