### ISSUE TITLE
DL4J/ND4J: Final test issues

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7602]
**ND4J, CPU**: Only 1 failing test remaining...
nd4j-parameter-server-client:
	RemoteParameterServerClientTests.remoteTests - failing on Windows (connection/localhost IP issue?)

**ND4J, CUDA**:
* TFGraphTestAllSameDiff: 1 test cases failing: (conv_4) looks like numerical precision issue, safe to ignore
* TFGraphTestAllLibnd4j: As per TFGraphTestAllSameDiff
* LapackTest.TestCholeskyL/U (known issue, already discussed)

----------

**DL4J:**
**deeplearning4j-core**
CPU: All passing.
CUDA: (Need to re-run to confirm all passing)

**deeplearning4j-nn:**
```
CPU/CUDA: SmartFancyBlockingQueueTest.testSFBQ_3:184->Object.wait:-2 ۠TestTimedOut test...
CUDA: SmartFancyBlockingQueueTest.testSFBQ_5:347 expected:<79548> but was:<79721>
```

**deeplearning4j-nearestneighbor-server**
* NearestNeighborTest.testNearestNeighbor - failing test, results are back to including requested index instead of excluding it

**deeplearning4j-nlp**
~~Tests in error: 
TestBertIterator.testBertSequenceClassification:64 » TestTimedOut test timed o...
TestBertIterator.testBertUnsupervised:140 » TestTimedOut test timed out after ...
TestBertIterator.testLengthHandling:168 » TestTimedOut test timed out after 20...
TestBertIterator.testMinibatchPadding:237 » TestTimedOut test timed out after ...
InMemoryLookupTableTest.testConsumeOnNonEqualVocabs:136 » Runtime java.lang.Il...
VocabConstructorTest.testMergedVocabWithLabels1:313 » Runtime java.lang.Illega...
FileLabelAwareIteratorTest.testExtractLabelFromPath1:47 » Runtime java.lang.Il...
FileLabelAwareIteratorTest.testExtractLabelFromPath2:77 » Runtime java.lang.Il...
FilenamesLabelAwareIteratorTest.testNextDocument:49 » Runtime java.lang.Illega...~~

All of these deeplearning4j-nlp tests are passing in Intellij... Not sure what's up here, but probably safe to ignore.
Full test output: https://gist.github.com/AlexDBlack/8539c85cfd111a54c2c3b0a0ee5f7d10
Only BERT ones are failing on CUDA (same timeout)

**dl4j-spark-nlp-java8**
~~1 failure on CUDA:
`SparkWord2VecTest.testStringsTokenization1:86 » Runtime java.lang.RuntimeExcep...`~~
Passing when run via IntelliJ, can't reproduce, probably safe to ignore?

**dl4j-spark-parameterserver**
Both CPU and GPU:
```
  GradientSharingTrainingTest>BaseSparkTest.before:70->BaseSparkTest.getBasicSparkDataSet:106 ۠IllegalState
  GradientSharingTrainingTest>BaseSparkTest.before:70->BaseSparkTest.getBasicSparkDataSet:106 ۠IllegalState
  GradientSharingTrainingTest>BaseSparkTest.before:70->BaseSparkTest.getBasicSparkDataSet:106 ۠IllegalState
```
All 3 are same NPE: https://gist.github.com/AlexDBlack/4c1378d7ea99ca3a321d9186fe69399d

**Comment by alexanderst** [comment]
nearest-neighbour core requires test fixes - caused by adding dimensions in nd4j.

**Comment by alexanderst** [comment]
Fixes for nearest-neighbour were merged.

**Comment by raver119** [comment]
All context-related issues should be resolved now

**Comment by alexanderst** [comment]
VPTree has parallel mode issues which affect nd4j-nn tests. Will be addressed in
https://github.com/deeplearning4j/deeplearning4j/issues/7628

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/issues/7657
