### ISSUE TITLE
DL4J: problems in VPTree and TSNE implementations 

### ISSUE THREAD

**Issue by alexanderst** [deeplearning4j/deeplearning4j#7628]
1. Current implementation of VPTree in parallel mode has race conditions and its output is unstable.
This test fails sporadically when output of similar tree woith different workers count in this test org.deeplearning4j.clustering.vptree.VPTreeNodeTest##testParallel().

2.org.deeplearning4j.clustering.vptree.BarnesHutTsne - output is unstable and IllegalStateException can be thrown in some cases sporadically. Probably it is related to VPTree issues.

**Comment by raver119** [comment]
Should be resolved by now i suppose?

**Comment by alexanderst** [comment]
Already fixed.
