### ISSUE TITLE
Squeezenet fromZoo model error with shapes not equal backprop

### ISSUE THREAD

**Issue by dembanakh** [deeplearning4j/deeplearning4j#7638]
I got 
`java.lang.IllegalStateException: Shapes must be equal during backprop: in.shape{} = [1, 256, 13, 13], epsilon.shape() = [1, 64, 13, 13]`
on layer "fire8_expand1x1", while not expecting it and don't see the reason.
The code I use is exactly the same as [https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/styletransfer/NeuralStyleTransfer.java], just model changed from vgg16 to squeezenet and ALL_LAYERS changed with
`public static final String[] ALL_LAYERS = new String[]{
            "input_5",
            "conv1",
            "relu1",
            "pool1",
            "fire2_squeeze1x1",
            "fire2_relu_squeeze1x1",
            "fire2_expand1x1",
            "fire2_expand3x3",
            "fire2_relu_expand1x1",
            "fire2_relu_expand3x3",
            "fire3_squeeze1x1",
            "fire3_relu_squeeze1x1",
            "fire3_expand1x1",
            "fire3_expand3x3",
            "fire3_relu_expand1x1",
            "fire3_relu_expand3x3",
            "pool3",
            "fire4_squeeze1x1",
            "fire4_relu_squeeze1x1",
            "fire4_expand1x1",
            "fire4_expand3x3",
            "fire4_relu_expand1x1",
            "fire4_relu_expand3x3",
            "fire5_squeeze1x1",
            "fire5_relu_squeeze1x1",
            "fire5_expand1x1",
            "fire5_expand3x3",
            "fire5_relu_expand1x1",
            "fire5_relu_expand3x3",
            "pool5",
            "fire6_squeeze1x1",
            "fire6_relu_squeeze1x1",
            "fire6_expand1x1",
            "fire6_expand3x3",
            "fire6_relu_expand1x1",
            "fire6_relu_expand3x3",
            "fire7_squeeze1x1",
            "fire7_relu_squeeze1x1",
            "fire7_expand1x1",
            "fire7_expand3x3",
            "fire7_relu_expand1x1",
            "fire7_relu_expand3x3",
            "fire8_squeeze1x1",
            "fire8_relu_squeeze1x1",
            "fire8_expand1x1",
            "fire8_expand3x3",
            "fire8_relu_expand1x1",
            "fire8_relu_expand3x3",
            "fire9_squeeze1x1",
            "fire9_relu_squeeze1x1",
            "fire9_expand1x1",
            "fire9_expand3x3",
            "fire9_relu_expand1x1",
            "fire9_relu_expand3x3",
            "drop9",
            "conv10",
            "relu10",
            "global_average_pooling2d_5",
            "loss"
    };`
So here is the point 
```
private INDArray backPropagate(ComputationGraph graph, INDArray dLdA, int startIndex) {
        for (int i = startIndex; i > 0; i--) {
            Layer layer = graph.getLayer(ALL_LAYERS[i]);
            dLdA = layer.backpropGradient(dLdA, LayerWorkspaceMgr.noWorkspaces()).getSecond(); 
        }
        return dLdA;
    }
```
backPropGradient(dLdA, Workspace) says the shapes differ...

**Comment by AlexDBlack** [comment]
Can you give us a way to reproduce this - i.e., a runnable minimal example?
Also, what version of DL4J is this with?

**Comment by dembanakh** [comment]
> Can you give us a way to reproduce this - i.e., a runnable minimal example?
> Also, what version of DL4J is this with?

1.0.0-beta3 as well as zoo and nd4j-native
i suspect the reason is that merge layers are nulls if we try to graph.getLayer("fire4_concat") e.g and thus we need to "deconcat" them ourselves

I don't quite understand what do you mean by example. Well here is how I execute generation:
```
public BaseGenerationRepo(Image contentImage, Image styleImage) {
        initHyperParams();
        INITIAL_HEIGHT = (int) contentImage.getHeight();
        INITIAL_WIDTH = (int) contentImage.getWidth();
        try {
            this.contentImage = toMatrix(contentImage);
            this.styleImage = toMatrix(styleImage);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
----------------------
ComputationGraph Graph = loadModel(false);
            INDArray generatedImage = initGeneratedImage();
            Map<String, INDArray> contentActivation = Graph.feedForward(new INDArray[] {contentImage}, true, false);
            Map<String, INDArray> styleActivation = Graph.feedForward(new INDArray[] {styleImage}, true, false);
            HashMap<String, INDArray> styleActivationGram = initStyleGramMap(styleActivation);
            AdamUpdater optim = createAdamUpdater();
            for (int i = 0; i < ITERATIONS; i++) {
                if (i % 5 == 0) log.info("iteration " + i);
                Map<String, INDArray> forwardActivation = Graph.feedForward(new INDArray[] { generatedImage }, true, false);

                INDArray styleGrad = backPropStyles(Graph, styleActivationGram, new HashMap<>(forwardActivation));
                forwardActivation = Graph.feedForward(new INDArray[] { generatedImage }, true, false);
                INDArray contentGrad = backPropContent(Graph, contentActivation, forwardActivation);
                INDArray totalGrad = contentGrad.muli(ALPHA).addi(styleGrad.muli(BETA));
                optim.applyUpdater(totalGrad, i, 0);
                generatedImage.subi(totalGrad);
            }

            return fromMatrix(generatedImage);
----------------
all the rest code is the same as in StyleTransfer.java from dl4j-examples github
```
Also it is worth mentioning that in ALL_LAYERS I removed all MergeLayers because, as I said, they are nulls and cannot backprop

**Comment by dembanakh** [comment]
I resolved the problem.
