### ISSUE TITLE
Training UI Total Parameter Updates

### ISSUE THREAD

**Issue by DWDHS** [deeplearning4j/deeplearning4j#7639]
When looking at the UI overview screen, the total parameter updates figure is not what I anticipated. 

I have a model with 20,000 training instances which I split into mini-batches of size 200 and ran for 100 epochs. My understanding is that parameter updates occur at the end of each mini-batch and so the total, in this case, should have been 10,000. On completion of all 100 epochs, the UI shows 9,991 updates. 

Is this my misunderstanding or am I missing updates during training?

**Comment by AlexDBlack** [comment]
> On completion of all 100 epochs, the UI shows 9,991 updates.

By default, the StatsListener is set to collect information every 10 iterations. So by far the most likely explanation here is that the listener just didn't report on the very last iteration.

You can check the iteration and epoch count using MultiLayerNetwork/ComputationGraph.getIterationCount()/getEpochCount() - those should show the correct values. If not, we can re-open and look into this further.
