### ISSUE TITLE
scatter_nd.cpp: not working for targets with more than one dimension.

### ISSUE THREAD

**Issue by Ucomania** [deeplearning4j/deeplearning4j#7640]
Due to the line below, scatter_nd cannot be used to scatter input values in tensors of dimension > 1.
https://github.com/deeplearning4j/deeplearning4j/blob/effce52f2afd7eeb53c5bcca699fcd90bd06822f/libnd4j/include/ops/declarable/generic/parity_ops/scatter_nd.cpp#L43
The correct comparison in this check would be `indices->sizeAt(-1) <= shapeLen`. 
`shapeRank` will always be 1, as correctly checked in the line above. I suppose this error was produced by implementing the mistake in the Tensorflow description of the same function (https://www.tensorflow.org/api_docs/python/tf/scatter_nd), where the statement that 'indices.shape[-1] <= shape.rank` should be true is just wrong.

**Comment by shyrma** [comment]
Hi, Ucomania 

Thank you for attentive look at our code.
Looks like tensorflow condition indices.shape[-1] <= shape.rank is correct because following code doesn't pass input validation 

```
shape   = tf.Variable(np.reshape([5,4], (2))) 
indices = tf.Variable(np.reshape([0,1,2], (3)))  # !!!
updates = tf.Variable(np.linspace(1., 12., 12).reshape([3,4]), dtype=tf.float64)
out = tf.scatter_nd(indices, updates, shape)
```

and this one does
```
shape   = tf.Variable(np.reshape([5,4], (2))) 
indices = tf.Variable(np.reshape([0,1,2], (3,1)))  # !!!
updates = tf.Variable(np.linspace(1., 12., 12).reshape([3,4]), dtype=tf.float64)
out = tf.scatter_nd(indices, updates, shape)
```

**Comment by Ucomania** [comment]
Hi Shyrma,

The code makes complete sense and works as I would expect it - the length of the last dimension of `indices` cannot be larger than the length (!!!) of the single dimension in `shape`. 
The confusion here is that `shape` must always have rank 1, the length of this single dimension is equal to the rank of the matrix it describes and this value must be larger or equal to the last dimension of `indices`. But comparing `shape.rank` with the size of the last dimension in indices doesn't make sense (as it must always be 1).
Summarizing, the condition should be:
`indices.shape[-1] <= shape.shape[0] == out.rank`
(for example in a 3D tensor, a 3-tuple is a full description of one position in the tensor. A 4-tuple cannot be interpreted here)
Tensorflow seems to have a correct implementation, but its documentation has an error.

**Comment by shyrma** [comment]
Hi, Ucomania

Now I see you are right, I've fixed this. Corrected version is already in master branch.
