### ISSUE TITLE
Transforms.max and min does not work when datatypes are not the same

### ISSUE THREAD

**Issue by DrChainsaw** [deeplearning4j/deeplearning4j#7675]
#### Issue Description

The following testcases throw exceptions:

    @Test
    public void maxDifferentTypes() {
        assertEquals("Incorrect max value!", 13, Transforms.max(Nd4j.scalar(13), Nd4j.scalar(1.23)).getInt(0));
    }

    @Test
    public void minDifferentTypes() {
        assertEquals("Incorrect min value!", 1, Transforms.min(Nd4j.scalar(13.3), Nd4j.scalar(1)).getInt(0));
    }

output: 
```
java.lang.IllegalArgumentException: Op.X type must be the same as Op.Y type: x.datatype=INT, y.datatype=DOUBLE for op class org.nd4j.linalg.api.ops.impl.transforms.comparison.OldMin

	at org.nd4j.base.Preconditions.throwEx(Preconditions.java:636)
	at org.nd4j.base.Preconditions.checkArgument(Preconditions.java:173)
	at org.nd4j.linalg.api.ops.BaseTransformSameOp.validateDataTypes(BaseTransformSameOp.java:98)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.invoke(CudaExecutioner.java:1339)
	at org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner.exec(CudaExecutioner.java:635)
	at org.nd4j.linalg.ops.transforms.Transforms.exec(Transforms.java:1125)
	at org.nd4j.linalg.ops.transforms.Transforms.min(Transforms.java:908)
	at org.nd4j.linalg.ops.transforms.Transforms.min(Transforms.java:919)
```

Maybe there is a good reason why. Or is there a NewMin one should use instead of OldMin?

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta4
* platform information (OS, etc): Windows 10
* CUDA version, if used: 10
* NVIDIA driver version, if in use: CBA to check, shouldn't matter

**Comment by AlexDBlack** [comment]
This is intentional, due to restrictions at the c++ (libnd4j) level.
i.e., max(A,B) supporting different datatypes for A and B means we need to add a lot of extra signatures, which means larger compilation time and larger binaries.

One option would be to cast things at the java level - so that max(int,float) = float, sort of thing.

This is also covered in the release notes: https://deeplearning4j.org/release-notes.html - first section on datatypes changes.

**Comment by raver119** [comment]
@DrChainsaw if you want, you can build "experimental" version of libnd4j/nd4j, which allows operations with mixed data types of operands. To do that you just need to add `-x yes` option to `./buildnativeoperations.sh` script.
