### ISSUE TITLE
ClassCastException using AnalyzeSpark

### ISSUE THREAD

**Issue by dennislloydjr** [deeplearning4j/deeplearning4j#7680]
#### Issue Description

I'm executing the following method:
`val dataAnalysis = AnalyzeSpark.analyze(mySchema, myRdd, maxHistogramBuckets)`
where the first column is a String data type. 

When this executes, I receive:
```
java.lang.ClassCastException: org.datavec.spark.transform.analysis.string.StringAnalysisCounter cannot be cast to org.datavec.api.transform.analysis.counter.StringAnalysisCounter
	at org.datavec.api.transform.analysis.DataVecAnalysisUtils.convertCounters(DataVecAnalysisUtils.java:73) ~[datavec-api-1.0.0-beta3.jar:?]
	at org.datavec.spark.transform.AnalyzeSpark.analyze(AnalyzeSpark.java:145) ~[datavec-spark_2.11-1.0.0-beta3_spark_2.jar:?]
```

It appears there was an effort to refactor out some of the counter conversion code to make is usable by both spark and local executions. This looks like the place where the trouble is at:

https://github.com/deeplearning4j/deeplearning4j/blob/master/datavec/datavec-api/src/main/java/org/datavec/api/transform/analysis/DataVecAnalysisUtils.java#L73

#### Version Information
I'm using version org.datavec:datavec-spark_2.11:1.0.0-beta3_spark_2

**Comment by AlexDBlack** [comment]
Thanks for reporting this - fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/7724

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/7792
