### ISSUE TITLE
BertWordPieceTokenizer throws on unknown character

### ISSUE THREAD

**Issue by tschut** [deeplearning4j/deeplearning4j#7684]
#### Issue Description
When using the BertWordPieceTokenizer, it throw NoSuchElementException when trying to tokenize a character that's not in the vocab (for instance, unicode `&ndash;`).

Ideally the behaviour should be configurable. Either ignore the unknown character or return some `[UNK]` or something.

#### Version Information
beta4

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by AlexDBlack** [comment]
Related: https://github.com/deeplearning4j/deeplearning4j/issues/7678

I think we'd probably just add a preprocessing step to remove
WordPiece is (effectively) supposed to fall back on character-level for unknown words, so there shouldn't be many characters in practice that this is a problem for.

**Comment by AlexDBlack** [comment]
Fixed a while ago here: https://github.com/deeplearning4j/deeplearning4j/pull/7774
