### ISSUE TITLE
About SameDiffTrainingExample

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#7704]
This app, I can get the result on cpu quickly,
why I can't on Gpu-backend?it's very very slow...

others, if I build two SDVariable with same name, 
		SDVariable x1 = sd.placeHolder("input", DataType.FLOAT, 5, 3); 
		SDVariable x2 = sd.placeHolder("input", DataType.FLOAT, 5, 3); 
It uses a Map to store them, it will lost the first,
so I think it should throw a exception here.

**Comment by AlexDBlack** [comment]
> SDVariable x1 = sd.placeHolder("input", DataType.FLOAT, 5, 3);
> SDVariable x2 = sd.placeHolder("input", DataType.FLOAT, 5, 3);

Duplicate names like this should not even be allowed. We are supposed to already have validation for that. https://github.com/deeplearning4j/deeplearning4j/issues/7705

As for GPU:

https://deeplearning4j.org/release-notes.html
> ND4J: Known Issues
> Most CustomOperation operations (such as those used in SameDiff) are CPU only until next release. GPU support was not completed in time for 1.0.0-beta4 release.

GPU support for all of these ops is in the final stages, will be merged to master soon.

**Comment by Charele** [comment]
The TSNEStandardExample test has same question, 
I can't get result on cpu, But I can't on Gpu.
It do not depdends on SameDiff...

**Comment by AlexDBlack** [comment]
You mean - TSNE performance on GPU is slower than expected?

**Comment by raver119** [comment]
There are known issues with TSNE, and we're finishing overhaul there right now.

**Comment by Charele** [comment]
Okay:-)
