### ISSUE TITLE
Libnd4j: Pad op bug (uninitialized values / not setting all values to constant)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7707]
Reproducible on both Linux and Windows.
Took a long time to isolate, but this is responsible for all of the `nasnet_mobile_2018_04_27` failures on master mentioned here: https://github.com/deeplearning4j/deeplearning4j/issues/7657

Looks like some values in the array aren't properly set to the padding value for constant mode - i.e., the original output array values are never overwritten.
Seems to be size dependent somehow; non-written entries seem to be only at end of the array, as far as I can tell.

```
    @Test
    public void testPadOp() throws Exception {

        INDArray i0 = Nd4j.ones(DataType.FLOAT, 1, 111, 111, 32);
        INDArray i1 = Nd4j.createFromArray(new int[][]{{0,0},{0,1},{0,1},{0,0}});

        INDArray out = Nd4j.create(DataType.FLOAT, 1, 112, 112, 32);
        out.assign(Double.NaN);

        DynamicCustomOp op = DynamicCustomOp.builder("pad")
                .addInputs(i0, i1)
                .addOutputs(out)
                .addIntegerArguments(0) //Constant mode
                .addFloatingPointArguments(0.0)
                .build();

        Nd4j.exec(op);
        double sum = out.sumNumber().doubleValue();
        double exp = ArrayUtil.prod(i0.shape());
        assertEquals(exp, sum, 0.0);
    }
```

```
java.lang.AssertionError: 
Expected :394272.0
Actual   :NaN
```

**Comment by shyrma** [comment]
Hi Alex
Thanks a lot for your hard work on isolation of this bug, we appreciate that.
I fixed it and correct version is merged into developer branch.
If you still have some issues please let me know

**Comment by AlexDBlack** [comment]
Thanks @shyrma 
I'll re-run to confirm it is fixed soon

**Comment by AlexDBlack** [comment]
Confirmed fixed (along with nasnet_mobile, which is now passing)
