### ISSUE TITLE
DataSet.splitTestAndTrain(..) Does not utilize the random parameter

### ISSUE THREAD

**Issue by MikeDepies** [deeplearning4j/deeplearning4j#771]
The implementation of DataSet.splitTestAndTest suggests it should use the rng parameter to shuffle the data, but in fact does nothing with it.

**Comment by Lukas-Razz** [comment]
Could be the problem that DataSet.splitTestAndTest is using java.util.Random, but it should use org.nd4j.linalg.api.rng.Random instead? As in function DataSet.sample.

**Comment by nyghtowl** [comment]
Issue is in nd4j and listed: https://github.com/deeplearning4j/nd4j/issues/574; thus closing this.
