### ISSUE TITLE
Cannot import keras model from h5 file

### ISSUE THREAD

**Issue by jamesohamp** [deeplearning4j/deeplearning4j#7725]
I am trying to import a (compiled and trained) model from keras (1), saved to an h5 file using model.save().

However, when trying to import the h5 file in deeplearning4j I get the following error:

HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:
  #000: C:\autotest\HDF5110ReleaseRWDITAR\src\H5G.c line 474 in H5Gopen2(): unable to open group
    major: Symbol table
    minor: Can't open object
  #001: C:\autotest\HDF5110ReleaseRWDITAR\src\H5Gint.c line 289 in H5G__open_name(): group not found
    major: Symbol table
    minor: Object not found
  #002: C:\autotest\HDF5110ReleaseRWDITAR\src\H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: C:\autotest\HDF5110ReleaseRWDITAR\src\H5Gtraverse.c line 869 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: C:\autotest\HDF5110ReleaseRWDITAR\src\H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: C:\autotest\HDF5110ReleaseRWDITAR\src\H5Gloc.c line 385 in H5G_loc_find_cb(): object 'dense_1_Wdense_1_b' doesn't exist
    major: Symbol table
    minor: Object not found

Importing the model from the h5 file in python with keras.models.load_model() works fine.

What might I be doing wrong?

I am using Keras version 1.2.2 and deeplearning4j version 0.9.1.

Thank you.

**Comment by AlexDBlack** [comment]
DL4J 0.9.1 was released 1 year, 9 months ago. We've had 5 releases since then.
Please upgrade to the latest version - 1.0.0-beta4.
There's a very high chance that the issue you are seeing has been fixed.
If not - post here again and we can re-open the issue to look into it further.

**Comment by jamesohamp** [comment]
Thank you for your help. 

I upgraded to 1.0.0-beta4. This has been partly successful, but I now have a different issue importing the model as-is, namely

> org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type ELU. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.

I can see the release for 1.0.0-alpha mentions [here](https://deeplearning4j.org/release-notes#onezerozeroalpha-dl4jkeras) that ELU is supported for model import, but I find no mention of sequential. Are ELU layers indeed not supported when importing sequential models, and if so, is there a straightforward way around this?

Thank you in advance

**Comment by maxpumperla** [comment]
@jamesoliverh you can use an `Activation` layer with `elu`, see here:

https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/utils/KerasActivationUtils.java#L56
