### ISSUE TITLE
ND4J: Wrong ordering when init with double array, shape and ordering info

### ISSUE THREAD

**Issue by sascha08-15** [deeplearning4j/deeplearning4j#7735]
The following test case is supposed to pass, but does not.
```
  @Test
    public void isThisABug(){
        double[] input1 = {1.0, 2.0};
        INDArray in1 = Nd4j.create(input1, new int[]{1, input1.length, 1},'f');
        assertEquals('f',in1.ordering());
    }
```

- expected behavior: return 'f' as ordering
- encountered behavior: one has to explicitly assign the order after construction again with in1.setOrder('f'), which also can be applied as a workaround, i.e. this way, it passes:
```    @Test
    public void thisWorks(){
        double[] input1 = {1.0, 2.0};
        INDArray in1 = Nd4j.create(input1, new int[]{1, input1.length, 1},'f');
        in1.setOrder('f');
        assertEquals('f',in1.ordering());
    }
```

*Version Information:*
* Deeplearning4j version: Beta4
* platform information: Ubuntu 19.04
* CUDA: 10.1 with cnn
* NVIDIA driver: latest

*Contributing*
First want to confirm that it's a bug, can look a bit closer into that, but may need some guidance.

**Comment by raver119** [comment]
Obviously that's a bug.

https://github.com/deeplearning4j/deeplearning4j/blob/91587dc0e3d0adbf46360f07d5e902a73298137c/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda/src/main/java/org/nd4j/linalg/jcublas/JCublasNDArrayFactory.java#L1620

That's the line where `Nd4j.order()` should be replaced with `order`

**Comment by raver119** [comment]
Fixed in my CUDA branch,
