### ISSUE TITLE
About preOutputWithPreNorm() method of BaseLayer

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#7736]
In this method, it will calculate the "preNorm", and return,
INDArray preNorm = ret;
        if (hasLayerNorm()) {
               preNorm = (forBackprop ? ret.dup(ret.ordering()) : ret);
               Nd4j.getExecutioner().exec(new LayerNorm(preNorm, g, ret, 1));
        }
......
return new Pair<>(ret, preNorm);

Some method, likes backpropGradient(), needs it.
Whereas other method, preOutput(), doesn't need it.(it only need first part of return Pair<>)
So I think add another parameter "needPreNorm",

preOutputWithPreNorm(..., boolean needPreNorm) {

   INDArray g = needPreNorm && hasLayerNorm() ? getParam(DefaultParamInitializer.GAIN_KEY) : null;
   ...
   INDArray preNorm = ret;
        if (needPreNorm && hasLayerNorm()) {
               preNorm = (forBackprop ? ret.dup(ret.ordering()) : ret);
               Nd4j.getExecutioner().exec(new LayerNorm(preNorm, g, ret, 1));
        }

It will save the process time if enable the layer normalization.

**Comment by AlexDBlack** [comment]
In the no layer norm case, code block looks fine - it returns same thing twice.

In the with layer norm case: we already have the "for backprop" arg.
If that's false (as in preOutput) then we end up returning the same thing twice.
Seems to me like we already implement the sort of optimization you are thinking about.

**Comment by Charele** [comment]
INDArray preNorm = ret;
        if(hasLayerNorm()){
            preNorm = (forBackprop ? ret.dup(ret.ordering()) : ret);
            Nd4j.getExecutioner().exec(new LayerNorm(preNorm, g, ret, 1));
        }

Here, any preNorm value(true or false),
it always execute "Nd4j.getExecutioner().exec(new LayerNorm(preNorm, g, ret, 1));"

You mean, where exec this Op(LayerNorm),
if preNorm == ret, it will return directly?

**Comment by AlexDBlack** [comment]
> Here, any "forBackprop" value(true or false),
> it always execute "Nd4j.getExecutioner().exec(new LayerNorm(preNorm, g, ret, 1));"

Yes, of course it will, we have to apply layer norm if layer norm is enabled!
And if it isn't enabled, we skip the op.
