### ISSUE TITLE
SequenceRecordReaderDataSetIterator.next() not able to open file 

### ISSUE THREAD

**Issue by jamesoliverh** [deeplearning4j/deeplearning4j#7739]
I am trying to read in files for input to an LSTM using SequenceRecordReaderDataSetIterator().

I am following the instructions in the [documentation](https://deeplearning4j.org/docs/latest/deeplearning4j-nn-recurrent#data). Namely, I begin by declaring CSVSequenceRecordReaders for the features and labels:
`SequenceRecordReader featureReader = new CSVSequenceRecordReader(1,",");`
`SequenceRecordReader targetReader = new CSVSequenceRecordReader(1,",");`
which I then initialise:
`featureReader.initialize(new NumberedFileInputSplit("C:/path_to_files/example_%d.csv", 0, NUM_FILES));`
`targetReader.initialize(new NumberedFileInputSplit("C:/path_to_files/target_%d.csv", 0, NUM_FILES));`
and feed to a SequenceRecordReaderDataSetIterator:
`DataSetIterator iter = new SequenceRecordReaderDataSetIterator(featureReader, targetReader, BATCH_SIZE, 1);`.

However, when I call .next() on the above, `DataSet data = iter.next();`, I get the following error:

> java.lang.IllegalStateException: Attempting to open URI that is not a File URI; for other stream types, you must use an appropriate stream loader function. URI: C:/path_to_files/example_0.csv

The file mentioned in the error message exists; I am able to create `File file = new File("C:/path_to_files/example_0.csv");` and call `file.toURI().getScheme()` which returns `file`. Looking at the source code [here](https://github.com/deeplearning4j/deeplearning4j/blob/633f9c79ebf1345b81d8157491643f4fb95d36b2/datavec/datavec-api/src/main/java/org/datavec/api/split/streams/FileStreamCreatorFunction.java), it seems that this triggering the error.

What am I doing wrong?

I am using dl4j version 1.0.0-beta4.

Thank you.

**Comment by AlexDBlack** [comment]
Hm... that certainly looks OK to me (assuming the file does indeed exist).
Can you post the fullstack trace?

I suspect a workaround here will be to simply add file URI scheme to the start - i.e., use "file://C:/path_to_files/example_%d.csv"

**Comment by Charele** [comment]
Change the "C:/path_to_files/example_%d.csv" to "C:\\path_to_files\\example_%d.csv",
"C:/path_to_files/target_%d.csv" to "C:\\path_to_files\\target_%d.csv"

**Comment by jamesoliverh** [comment]
@AlexDBlack @Charele Thank you. Both of these workarounds work.

A colleague helpfully pointed out that the issue is caused by
https://github.com/deeplearning4j/deeplearning4j/blob/master/datavec/datavec-api/src/main/java/org/datavec/api/split/NumberedFileInputSplit.java#L125
i.e. `if(baseString.matches(".*:/.*")) {`. 

"C:/path_to_files/example_0.csv" matches this regex.

Perhaps the regex (or the documentation) could be updated in light of this?

Thanks

In case it is useful, the stack trace is:
> java.lang.IllegalStateException: Attempting to open URI that is not a File URI; for other stream types, you must use an appropriate stream loader function. URI: C:/path_to_files/example_0.csv
	at org.nd4j.base.Preconditions.throwStateEx(Preconditions.java:641)
	at org.nd4j.base.Preconditions.checkState(Preconditions.java:304)
	at org.datavec.api.split.streams.FileStreamCreatorFunction.apply(FileStreamCreatorFunction.java:29)
	at org.datavec.api.split.streams.FileStreamCreatorFunction.apply(FileStreamCreatorFunction.java:25)
	at org.datavec.api.records.reader.impl.csv.CSVSequenceRecordReader.nextSequence(CSVSequenceRecordReader.java:79)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.initializeUnderlyingFromReader(SequenceRecordReaderDataSetIterator.java:167)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.hasNext(SequenceRecordReaderDataSetIterator.java:337)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.next(SequenceRecordReaderDataSetIterator.java:358)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.next(SequenceRecordReaderDataSetIterator.java:344)
	at org.deeplearning4j.datasets.datavec.SequenceRecordReaderDataSetIterator.next(SequenceRecordReaderDataSetIterator.java:48)

**Comment by AlexDBlack** [comment]
Yeah, I'd say this is a bug in the regex (for detecting presence/absence of scheme) that should be fixed.
Thanks for testing the workarounds.

**Comment by jamesoliverh** [comment]
Proposed modification to regex, pull request here:
https://github.com/deeplearning4j/deeplearning4j/pull/7742

Proposed change means that 
`"C:/path/" `
no longer matches, whilst
`"file:/C:/path"` and `"file:/path" `
still match.
Additionally, `":/path"` which used to match no longer matches, which I assume is desired behaviour.

Comments and/or suggestions welcome. Thanks

**Comment by AlexDBlack** [comment]
Fixed there: https://github.com/deeplearning4j/deeplearning4j/pull/7742
