### ISSUE TITLE
Different vectors returned for the same model.

### ISSUE THREAD

**Issue by sirtow** [deeplearning4j/deeplearning4j#7745]
#### Issue Description
I'm testing two google word2vec model :
GoogleNews-vectors-negative300.bin.gz and trimed down version https://github.com/eyaler/word2vec-slim

I'm using the following code to load the model `WordVectorSerializer.loadGoogleModelNonNormalized(File(modelFile), true, false)`

The vector returned by `model.getWordVectorMatrix("hello")` is different between the models. 
I tested both models in Gensim and the vectors returned for both models are the same.

I'm using CPU-backend
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
0.9.1
* platform information (OS, etc)
Windows 10
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
Please upgrade to 1.0.0-beta4. Version you're using was released almost 2 years ago.

**Comment by raver119** [comment]
p.s. feel free to reopen if issue is still there, however i highly doubt that.

**Comment by sirtow** [comment]
I upgraded to  1.0.0-beta4 but the problem remains. The new code to load the model is `WordVectorSerializer.readBinaryModel(File(modelFile), false, false)`
The vector for `model.getWordVectorMatrix("neighbor").data()` is :
normal model       : `0.1171875,-0.11230469,0.099609375,-0.014099121,0.106933594,...`
slim model            : `0.0394007,-0.037759006,0.033490594,-0.004740397,0.035953138,...`
The Gensim vector for both models: 0.0394007005, -0.0377590060,  0.0334905945, -0.00474039698

**Comment by raver119** [comment]
1) show your source code please in both gensim and java. as gist please
2) what's your system locale/encoding. any chance you're not on UTF-8?

**Comment by Charele** [comment]
loadGoogleModelNonNormalized()?
Why don't I have this method in my WordVectorSerializer?

**Comment by sirtow** [comment]
Sorry for late response, unfortunately i needed to move away from using w2v embedding. i will close the issue.
