### ISSUE TITLE
DL4J: ComputationGraph - setInputType validation

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7750]
Using 2 inputs but only 1 input type: this should throw a useful exception
```
.addInputs("in1", "in2")
.setInputTypes(InputType.convolutional(height, width, channels))
```

**Comment by cpoerschke** [comment]
Hello. I took the liberty of having a go at this though perhaps picked the wrong code/test areas for it in #7752 PR?

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/7752
