### ISSUE TITLE
About castTo() method

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#7753]
@Override
    public INDArray castTo(DataType dataType) {
        if(isEmpty()){
            if(dataType == dataType())
                return this;
            return Nd4j.empty(dataType);
        }
        val result = Nd4j.createUninitialized(dataType, this.shape(), this.ordering());
        result.assign(this);
        return result;
    }

If this data type is equal with the target's, must we create other instance?
I mean:

@Override
    public INDArray castTo(DataType dataType) {
        if(dataType == dataType())
                return this;
        ... ...

**Comment by AlexDBlack** [comment]
What's the question here?

The code is right there, you can see what it does.
Empty arrays are immutable (no data) so we can return the same object.

And in future, just link the code directly, don't copy/paste with bad formatting.
https://github.com/deeplearning4j/deeplearning4j/blob/64a17b596eff14820c06cdaf4cc5f84dd0990568/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L6496-L6506

**Comment by Charele** [comment]
(Force on no-empty),
I mean if their data type are equal, can return "this" directly,
we don't must create another object,"val result...; return result"

**Comment by AlexDBlack** [comment]
Yes, that's the way it is supposed to work - and (until now) the way I thought it already did.
That was (incorrectly) changed at some point.
https://github.com/deeplearning4j/deeplearning4j/issues/7754
