### ISSUE TITLE
dimension problem ITK

### ISSUE THREAD

**Issue by safamath** [deeplearning4j/deeplearning4j#7755]
i can’t upload the segmentation image with the main image 
i got the segmented image  after the treatment (output test )
 where the dimensions of main image and segmented are not the same
but I want to combine main image with segmented image
any solution please to match the segmentated image with the main image !!!
whene i tried to match the message displayed is "the size of segmentation image does not match with main image images must have the same dimensions"

**Comment by AlexDBlack** [comment]
This is completely the wrong place for such questions. Github issues on this repo should be used for Deeplearning4J, ND4J, RL4J, DataVec etc only.

We have nothing to do with ITK. We don't use it, and don't develop it.
