### ISSUE TITLE
java.lang.IllegalStateException: Pretrained model file failed checksum.

### ISSUE THREAD

**Issue by 11aleksandrmd11** [deeplearning4j/deeplearning4j#7767]
#### Issue Description
Good day!

I have deflated the model from http://blob.deeplearning4j.org/models/yolo2_dl4j_inference.v3.zip

When you download it
ComputationGraph pretrained = (ComputationGraph) YOLO2.builder().build().initPretrained();
an exception occurs:

07:28:24.243 [main] INFO  org.deeplearning4j.zoo.ZooModel - Using cached model at C:\Users\Denisov1-AM\.deeplearning4j\models\yolo2\yolo2_dl4j_inference.v3.zip
07:28:24.259 [main] INFO  org.deeplearning4j.zoo.ZooModel - Verifying download...
07:28:24.461 [main] INFO  org.deeplearning4j.zoo.ZooModel - Checksum local is 389647992, expecting 3658373840
07:28:24.461 [main] ERROR org.deeplearning4j.zoo.ZooModel - Checksums do not match. Cleaning up files and failing...
Exception in thread "main" java.lang.IllegalStateException: Pretrained model file failed checksum. If this error persists, please open an issue at https://github.com/deeplearning4j/deeplearning4j.
       at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:93)
       at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:54)
       at ru.neural.dl4j.training.ExecutionYOLO2.getModel2(ExecutionYOLO2.java:215)
       at ru.neural.dl4j.training.ExecutionYOLO2.train(ExecutionYOLO2.java:164)
       at ru.neural.dl4j.training.ExecutionYOLO2.train(ExecutionYOLO2.java:112)
       at ru.neural.dl4j.training.Main.main(Main.java:15)
please tell me what it can be connected with.

Please describe our issue, along with:
- expected behavior
expectedChecksum == localChecksum
- encountered behavior
expectedChecksum != localChecksum

#### Version Information

Please indicate relevant versions, including, if relevant:
```
          <dependency>
             <groupId>org.deeplearning4j</groupId>
             <artifactId>deeplearning4j-zoo</artifactId>
             <version>1.0.0-beta3</version>
             <type>jar</type>
           </dependency>
             <dependency>
             <groupId>org.deeplearning4j</groupId>
             <artifactId>deeplearning4j-core</artifactId>
             <version>1.0.0-beta3</version>
             <type>jar</type>
           </dependency>
           <dependency>
             <groupId>org.nd4j</groupId>
             <artifactId>nd4j-native-platform</artifactId>
             <version>1.0.0-beta3</version>
             <type>jar</type>
           </dependency>
            <dependency>
             <groupId>org.deeplearning4j</groupId>
             <artifactId>deeplearning4j-modelimport</artifactId>
             <version>1.0.0-beta3</version>
             <type>jar</type>
           </dependency>
           <dependency>
             <groupId>org.deeplearning4j</groupId>
             <artifactId>deeplearning4j-ui_2.11</artifactId>
             <version>1.0.0-beta3</version>
             <type>jar</type>
           </dependency>
           <dependency>
             <groupId>org.bytedeco.javacpp-presets</groupId>
             <artifactId>opencv-platform</artifactId>
             <version>3.4.3-1.4.3</version>
           </dependency>
```

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

ComputationGraph pretrained = (ComputationGraph) YOLO2.builder().build().initPretrained();

**Comment by AlexDBlack** [comment]
Thanks for reporting. Try with the recently released 1.0.0-beta4.
I've confirmed it works OK for me with that version:
```
o.d.z.ZooModel - Downloading model to C:\Users\Alex\.deeplearning4j\models\yolo2\yolo2_dl4j_inference.v3.zip
o.d.z.ZooModel - Verifying download...
o.d.z.ZooModel - Checksum local is 3658373840, expecting 3658373840
```

There's also a small chance you ran into a download issue (though if you've tried it multiple times, maybe there was an issue in beta3 that has since been fixed).

If you still run into problems with beta4, we can re-open the issue and look into it further.

**Comment by 11aleksandrmd11** [comment]
Thanks for the answer!
I would expect to add libraries to our repository.

**Comment by suyashcjoshi** [comment]
I'm running into this issue with beta4

**Comment by AlexDBlack** [comment]
@suyashjoshi Try again with 1.0.0-beta6. If that still doesn't work, can you please open a new Github issue, and let us know exactly which pretrained model you are trying to use?
There are no known issues with pretrained models in beta6, all tests for downloading (and checking hashes etc) are passing.
