### ISSUE TITLE
Convert http -> https for prebuilt models

### ISSUE THREAD

**Issue by tballison** [deeplearning4j/deeplearning4j#7779]
#### Issue Description
It looks like the remoteUrl for vgg16_dl4j_inference.zip at least is http, not https: ``http://blob.deeplearning4j.org/models/vgg16_dl4j_inference.zip``

![image](https://user-images.githubusercontent.com/6739646/58258175-41649300-7d40-11e9-9558-d4cdf98f713f.png)

Would you be willing to convert http -> https for models and any other remote resources?

#### Version Information
1.0.0-beta4

**Comment by AlexDBlack** [comment]
Yes, thanks for flagging.
For the model zoo models, this should be trivial to change - all of the resource URLs are constructed from this base URL:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-common/src/main/java/org/deeplearning4j/common/resources/DL4JResources.java#L47

However a more thorough review (for any other instances of this) would be advisable also.

Note also there's a system property to override that base URL too - that should be a workaround for you, if you want https before waiting for the next release (or switching to snapshots).
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-common/src/main/java/org/deeplearning4j/config/DL4JSystemProperties.java#L45-L54

**Comment by Charele** [comment]
I always download them manually by download tool, and put it into homologous folder.

I find it's very very slow if use "FileUtils.copyURLToFile(..." of ZooModel.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/7792
