### ISSUE TITLE
why omit the dimension?

### ISSUE THREAD

**Issue by Charele** [deeplearning4j/deeplearning4j#7796]
Look this example:
  val x = Nd4j.rand(Array(10, 12, 12, 13))
  val x1 = x.get(all(), point(0), all(), all())
  val x2 = x.get(all(), all(), point(0), all())

  println(x1.shapeInfoToString())
  println(x2.shapeInfoToString())
output:
Rank: 3, DataType: FLOAT, Offset: 0, Order: c, Shape: [10,12,13],  Stride: [1872,13,1]
Rank: 3, DataType: FLOAT, Offset: 0, Order: c, Shape: [10,12,13],  Stride: [1872,156,1]
I think it should not omit the dimension, x1 should have shape[10, 1, 12, 13], and x2 should have [10, 12, 1, 13].
now they have same shape, maybe this ambiguity will be a question sometime.

others, Yolo2OutputLayer should add a method with the "nmsThreshold" parameter.
it only has the method without "nmsThreshold".

**Comment by AlexDBlack** [comment]
This is intentional - it is by design. Point indices reduce the rank of the array by 1.
If you want to keep the size 1 dimension, you can use interval(x,x+1).
We'll add a point(int, boolean keepDim) option in the future (there's already an issue for that).

**Comment by Charele** [comment]
Yes, I understand, I get it by using "interval(0, 1)" or "indices(0)".

what about the second? I mean getPredictedObjects() method

**Comment by AlexDBlack** [comment]
It's available on YoloUtils - I'm inclined to leave it there, though I guess a method on the layer that just uses YoloUtils wouldn't hurt...
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/layers/objdetect/YoloUtils.java
