### ISSUE TITLE
Arbiter: EvaluationScoreFunction uses deprecated DL4J Evaluation.Metric (only) not ND4J version

### ISSUE THREAD

**Issue by minutolc** [deeplearning4j/deeplearning4j#7804]
Hello ,

I want to implement the example of BasicHyperparameterOptimization but i have some trouble :
When i use OptimizationConfiguration i have to put an scoreFunction and in the tutorial they create it with ScoreFunction scoreFunction = new EvaluationScoreFunction(Evaluation.Metric.ACCURACY);

The problem is that Evaluation.Metric is Deprecated so i have an error when i use it. They advise to use instead ND4J Evaluation class, which has the same interface but i can't find a way to get a scoreFunction with ND4J.

Can someome help me please ?

**Comment by AlexDBlack** [comment]
Looks like this got missed when Evaluation was moved to ND4J:
https://github.com/deeplearning4j/deeplearning4j/blob/master/arbiter/arbiter-deeplearning4j/src/main/java/org/deeplearning4j/arbiter/scoring/impl/EvaluationScoreFunction.java#L40-L45

The deeplearning4j Evaluation.Metric should still work fine, and give you exactly the same result as the Nd4j Evaluation.Metric.

Thanks for flagging this, we'll make sure to fix this.

**Comment by minutolc** [comment]
Thank for your quick answer !

**Comment by AlexDBlack** [comment]
Fixed here, will be merged to master soon: https://github.com/deeplearning4j/deeplearning4j/pull/7807
Thanks for reporting this.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/7792
