### ISSUE TITLE
RL4J - A3C throws java.lang.RuntimeException while training [ND4J issue]

### ISSUE THREAD

**Issue by rahul-raj** [deeplearning4j/deeplearning4j#7806]
#### Issue Description

**Expected behavior**
Application should run without any exceptions provided all dependencies/configurations are setup properly. 

 **Encountered behavior**
Refer to [gist](https://gist.github.com/rahul-raj/4cfddf24abf261946ae31193133f65a8) for full exception log.
Example used for testing -> https://github.com/deeplearning4j/dl4j-examples/blob/master/rl4j-examples/src/main/java/org/deeplearning4j/examples/rl4j/A3CALE.java

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version -> **1.0.0-beta4**
* platform information (OS, etc) -> **Windows 10**
* CUDA version, if used -> **NA**
* NVIDIA driver version, if in use -> **NA**

#### Contributing

pong.bin file used -> https://github.com/NeuroCSUT/DeepMind-Atari-Deep-Q-Learner-2Player/blob/master/roms/pong.bin

**Comment by saudet** [comment]
@raver119 How should we be replacing that?

**Comment by rahul-raj** [comment]
@saudet 
In fact, the below example also have this issue:
https://github.com/deeplearning4j/dl4j-examples/blob/master/rl4j-examples/src/main/java/org/deeplearning4j/examples/rl4j/ALE.java
log -> https://gist.github.com/rahul-raj/7c06d543ddaa72e6710086f49a604b3a

**Comment by raver119** [comment]
As we've already discussed in Slack, compression isn't needed anymore, since UINT8 is a regular data type now, so all we need is a casual INDArray.castTo(UINT8) as you move data into history/replays storage, and INDArray.castTo(YourFloatingPointDataType) as you extract data out of it.
