### ISSUE TITLE
problem on reloading saved network with saved parameters

### ISSUE THREAD

**Issue by Shima32** [deeplearning4j/deeplearning4j#782]
in DBNIrisExample.java when save the model and again reload the model as savedNetwork, in the line that print Original network params and savedNetwork parameters, why savedNetwork parameter are all zero? shouldn't be as same as original network params?
i think the problem is with function setParameters..

**Comment by AlexDBlack** [comment]
should be solved as of https://github.com/deeplearning4j/nd4j/pull/468
