### ISSUE TITLE
Multidimensional Sequence Data

### ISSUE THREAD

**Issue by phsieh** [deeplearning4j/deeplearning4j#783]
I have a classification dataset.  It consists of 9000 sequences.  Each sequence has 20 time steps.  Each timestep has 5 features.  I've setup a network of LSTM nodes; however, I am having some issues figuring out how to create an iterator for this type of data.  I was hoping someone might be able to point me in the right direction.  Thanks for the help.

**Comment by agibsonccc** [comment]
https://gitter.im/deeplearning4j/deeplearning4j
