### ISSUE TITLE
Checking INDArray Bounds

### ISSUE THREAD

**Issue by dkmisra** [deeplearning4j/deeplearning4j#784]
## Error: 

If there is an INDArray arr of size pxqxr then it is possible to access an element as
`arr.getDouble(new int[]{0,q+1,0});`

even though this element does not exist. No error is thrown and a double is returned
successfully. 

## Suggestion: 
INDArray access should have a bound check for handling these scenarios and an error
must be returned if bounds are violated.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/api/shape/Shape.java#L495
