### ISSUE TITLE
DL4J - FastText - UX, JavaDoc and .vec format support

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#7857]
Looks like JFastText can only load .bin files, not the text .vec files
First thing I did when trying to use FastText:
1. Download English .vec files here: https://fasttext.cc/docs/en/english-vectors.html
2. Try to load them using `new FastText(File)`
3. Hit a confusing exception: `Exception in thread "main" java.lang.IllegalArgumentException: Model file's format is not compatible with this JFastText version!`

I didn't initially realize FastText had 2 separate formats (binary .bin and text .vec) and that JFastText only loads one of them.
This is bad UX, and I'm sure other people will run into exactly the same exception.
We need to do 2 things:
1. In the short term, detect if .vec file, and throw a useful exception (basically: "Only supports FastText .bin format binary files")
2. See if it's possible to add loading .vec files in JFastText (or javacpp bindings) and if possible send a PR to add this. Then detect which format and load.

While we are at it, we also need to add JavaDoc to the FastText class and methods:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/fasttext/FastText.java

**Comment by alexanderst** [comment]
JFastText has poor API, it doesn't support multiple features of fasttext. However there's possibility to use fasttext command line with any available option (JFastText.runCmd()) and I'm using it to load pretrained vectors.

**Comment by AlexDBlack** [comment]
Right, I imagined we'd need to improve JFastText. If that means sending a PR upstream for the fixes/improvements we need, then I'm totally fine with us spending time on that. :)

**Comment by saudet** [comment]
Or would we be better off with the original C++ API?

**Comment by raver119** [comment]
As discussed in Slack, that's natural limitation, and it can't be solved in any way. Vec files do not have subword information and do not have algo configuration defined. So there's no way to make .bin out of .vec. We'll provide fallback to w2v-mode in such cases, and notify user about limited functionality.
