### ISSUE TITLE
get output of the i-th layer 

### ISSUE THREAD

**Issue by DonBeo** [deeplearning4j/deeplearning4j#788]
In a multilayer neural network.  In order to get the output of the 2-th layer I have to use the following code:

`val scores = model.activate(2, model.activate(1, model.activate(0,x)))`  where `x` is the input data used to train the network.  

It would be useful to have a way to automate this process and be able to use a command like

`val scores = model.getOutputOfLayerIth(2, x)`

**Comment by AlexDBlack** [comment]
You can use model.feedForward(input).get(i) to get the activations of the ith layer. Note that the input is included (i.e., .get(0) is the network input)

**Comment by agibsonccc** [comment]
We shouldn't have to do feed forward all the way though. This has a reason
for needing to exist.

**Comment by AlexDBlack** [comment]
See MultiLayerNetwork.feedForwardToLayer() methods
https://github.com/deeplearning4j/deeplearning4j/pull/894

**Comment by raver119** [comment]
There's also activateSelected layers method, so you can choose which layers should be activated. say, 0-2 layers only. But i dont remember, was it included in 3.6 or 3.7
