### ISSUE TITLE
DL4J need a roadmap

### ISSUE THREAD

**Issue by linkerlin** [deeplearning4j/deeplearning4j#789]
A road map will give us a target and a hope.

**Comment by agibsonccc** [comment]
Come on gitter and send us a PR!

We'd be happy to discuss it.

Right now/0.4:
Benchmarks/speed for this release Major focus is on cuda kernels
Refinements of spark and spark.ml
Benchmarking image net
FInalize api

Next release:
Flink
Opencl
Sparse


The project roadmap is pretty simple really. If you were in gitter or would
check it day to day, you'd more or less know where we're at. I"m closing
this as we have our active community members already in the chat.
ᐧ
