### ISSUE TITLE
UI (HistogramIterationListener) not stable with large networks

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#801]
When learning a network with a large number of parameters (for example, tested on network with 4.7M parameters + Chrome browser), the UI page itself frequently crashes. Network learning etc. continues OK however.
Refreshing the page after a crash does work (i.e., UI shows again) however this is a temporary solution.

Edit: probably due to size of JSON being generated for histograms.

**Comment by raver119** [comment]
Fixed https://github.com/deeplearning4j/deeplearning4j/pull/1089
