### ISSUE TITLE
Update ConvolutionLayerSetup to support setup with RNN layers

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#804]
ConvolutionLayerSetup does not currently support setting up of RNN layers yet.
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/conf/layers/setup/ConvolutionLayerSetup.java

Specifically, it should take advantage of the recently added CnnToRnn and RnnToCnnPreProcessor classes.

**Comment by agibsonccc** [comment]
This is done I believe?
