### ISSUE TITLE
Matrix inverse inconsistence with cuda arch 75

### ISSUE THREAD

**Issue by shugeo** [deeplearning4j/deeplearning4j#8141]
#### Issue Description

There is wrong behavior of matrix_inverse op with cuda platform on arch 7.5 (RTX20XX and so on) with usage of data type double.
e.g. for matrix 
 [[                  4.,   0.,  0.,  0.,  0.,
                     4.,   2.,  0.,  0.,  0.,
                    30.,   2.,  1.,  0.,  0.,
                     8.,   6.,  4.,  2.,  0.,
                    15.,  12.,  9.,  6.,  3.]]

Expected : 
[[0.250000, 0.000000, 0.000000, 0.000000, 0.000000]
 [-0.500000, 0.500000, 0.000000, 0.000000, 0.000000]
 [-6.500000, -1.000000, 1.000000, 0.000000, 0.000000]
 [13.500000, 0.500000, -2.000000, 0.500000, 0.000000]
 [-6.750000, 0.000000, 1.000000, -1.000000, 0.333333]]
Output : 
[[0.250000, 0.000000, 0.000000, 0.000000, 0.000000]
 [-0.500000, 0.500000, 0.000000, 0.000000, 0.000000]
 [-6.500000, -1.000000, 1.000000, 0.000000, 0.000000]
 [13.500000, 0.500000, -2.000000, 0.500000, 0.000000]
 [20.250000, 0.000000, 1.000000, -1.000000, 0.333333]]
#### Version Information
Detected both for linux cuda and windows cuda platform with datatype double 
architecture nvidia 7.5 (Pascal)

* 1.0.0-beta?
* Windows/Linux
* 10.1 (arch 7.5)
* 430

**Comment by raver119** [comment]
Turing.

**Comment by rcorbish** [comment]
I looked at this, and cannot repeat with the latest code.
1.0.0-beta4, Linux, cuda 10.1 (arch 75), GTX 2080

```
        INDArray A = Nd4j.create(new double[] { 
            4., 0., 0., 0., 0.,
            4., 2., 0., 0., 0.,
            30., 2., 1., 0., 0.,
            8., 6., 4., 2., 0.,
            15., 12., 9., 6., 3. } );
        A = A.reshape('c', 5, 5);
        INDArray O = Nd4j.create(A.dataType(), A.shape());
        Nd4j.copy(A, O);
        
        InvertMatrix.invert( A, true ) ;

        A.mmuli( O );
        A.subi( Nd4j.eye( 5 ) ) ;

        DataBuffer db = A.data();
        boolean rc = true ;
        for (int i = 0; i < db.length(); i++) {
            rc &= Math.abs( db.getFloat(i) ) < 1e-5 ;
        }
        return rc ;

```
