### ISSUE TITLE
Get similar words with WordVectors.wordsNearest(INDArray, int) not working

### ISSUE THREAD

**Issue by BenjaminZ** [deeplearning4j/deeplearning4j#818]
When I try to use `public Collection<String> wordsNearest(INDArray words, int top)`, I get
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
    at org.nd4j.linalg.api.shape.Shape.getOffset(Shape.java:498)
    at org.nd4j.linalg.api.shape.Shape.getDouble(Shape.java:249)
    at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:1440)
    at org.nd4j.linalg.api.ndarray.BaseNDArray.getInt(BaseNDArray.java:1428)
    at org.deeplearning4j.models.embeddings.wordvectors.WordVectorsImpl.wordsNearest(WordVectorsImpl.java:198)
    at translation.NNReader.main(NNReader.java:45)

```
I tested the method `wordsNearest(java.lang.String word, int n)`, it works. But when I tried the `wordsNearest(org.nd4j.linalg.api.ndarray.INDArray words, int top)` with the same word, only the `INDArray` I used is the word's `INDArray` in the WordVector, it showed me the exception. I used both `getWordVectorMatrixNormalized(java.lang.String word)` and `getWordVectorMatrix(java.lang.String word)` to get the `INDArray`, the Array I got are different, but both of them showed the exception.

Here's my test code:
```

public static void main(String[] args) {
        try {
            WordVectors sourceModel = WordVectorSerializer.loadTxtVectors(new File("/Users/Benjamin/IdeaProjects/TriangulationTranslation/data/model/fbis/source.txt"));
            INDArray vector = sourceModel.getWordVectorMatrix("我");
            System.out.println(vector.getRow(0));
            Collection<String> words = sourceModel.wordsNearest(vector, 5);
            for (String word : words) {
                System.out.println(word);
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

    }

```

**Comment by carschno** [comment]
This is related to #821. Trying to fix that.

**Comment by carschno** [comment]
I can confirm that, trying to fix it.

**Comment by carschno** [comment]
I can confirm this, but I am currently unable to fix it because I think it is caused by a bug in Nd4j (see the issue I have referenced).

**Comment by BenjaminZ** [comment]
Luckily I can retrieve the information from the stored txt file😄.

**Comment by niloygupta** [comment]
Facing same issue. Is there is any quick work around?

**Comment by raver119** [comment]
Fixed ages ago
