### ISSUE TITLE
WordVectorsImpl#wordsNearest returns wrong results

### ISSUE THREAD

**Issue by carschno** [deeplearning4j/deeplearning4j#821]
When calling `wordsNearest(String word, int n)` with n=1, the result set is empty.

After some initial analysis the problem is the following: at first, the n nearest neighbours are looked up and sorted by similarity score in `WordVectorsImpl#getTopN(INDArray vec, int n)`. If there is just one word being looked up, `vec` is this word's word vector. Hence, the one nearest neighbour is the word itself.
In the next step of `wordsNearest(Collection<String> positive, Collection<String> negative, int top)`, the word is removed because the word itself should not be returned as a nearest neighbour to itself, naturally. This leaves the result set empty.

**Comment by carschno** [comment]
BTW, this regression error could have been prevented by finally using unit testing... :(

**Comment by agibsonccc** [comment]
This is fixed with the rewrite.
