### ISSUE TITLE
TanhDerivative missing single INDArray constructor

### ISSUE THREAD

**Issue by RobAltena** [deeplearning4j/deeplearning4j#8252]
#### Issue Description
The old, deprecated TanhDerivative has a  [constructor that takes one INDArray](https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/transforms/strict/TanhDerivative.java#L45)

The [suggested replacement class](https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/transforms/gradient/TanhDerivative.java) does not have a constructor with a single INDArray. 

This makes replacing deprecated code hard. At least we should provide some documentation.
( I gave up after 20 minutes and raised this issue instead).

**Comment by AlexDBlack** [comment]
The old TanhDerivative was `dOut/dIn` from `In`
The new TanhDerivative is `dL/dIn` from `dL/dOut` and `In`

But yes, we really need proper javadoc here...
