### ISSUE TITLE
Import Keras Model : difference between DL4J and Keras results

### ISSUE THREAD

**Issue by montardon** [deeplearning4j/deeplearning4j#8258]
#### Issue Description
I'm importing a .h5 model with KerasImportModel.importKerasModelAndWeights.
When I predict input with it, the results are different from the ones I have with Keras, using
the same input. 
[0.9728909, 0.027109064] vs [0.01448847 0.98551154]
Here is the model.
[model.txt](https://github.com/eclipse/deeplearning4j/files/3675226/model.txt)
and input test image.
![testBlack](https://user-images.githubusercontent.com/238749/65948129-eb180700-e439-11e9-8d26-57b13704e321.png)
Usage :
https://gist.github.com/montardon/e141a46f2b40bfa728ec84b921e3c577
The model is too big for dropping it there (192Mb).
Is there a way to share it ?

#### Version Information

* Deeplearning4j version 1.0-beta5
* Platform information (OS, etc) Ubuntu 18.04.3
* CUDA version, if used 10.1
* NVIDIA driver version, if in use 430.26

#### Additional Information
I previously had other models that were working fine with DL4J (for inference).
Is there something new with this one ?

**Comment by eraly** [comment]
You can upload the .json, i.e only the architecture of the model and that should be enough for debug.
Do you see the same issue with CPU or is it only with GPU?
What was the last version of dl4j that gave you matching results with import for this particular architecture?

**Comment by montardon** [comment]
Here is the architecture of the model in JSON format.
I checked that every layer is supported.

I am currently using beta-5 and was using beta-4 before.
Results are different with same input (DL4J vs Keras/Python, see black image example)

[model.json.txt](https://github.com/eclipse/deeplearning4j/files/3696065/model.json.txt)

I'll check without GPU and post comment today.

**Comment by montardon** [comment]
Result are different with CPU only mode too.

**Comment by eraly** [comment]
I have not been able to reproduce this behaviour in beta5 on CPU. I have not tried GPU. But changes that affect keras import between beta4 and beta5 are minimal. There was a bug related to imported training configurations. But nothing that I see that should affect your model...

Here is the code in Keras:
```
import keras
from keras.models import model_from_json
import numpy
json_file = open('/Users/susaneraly/Downloads/model.json.txt', 'r')
loaded_model_json = json_file.read()
loaded_model = model_from_json(loaded_model_json)
in1 = np.full([1,224,224,3],-1)
loaded_model.predict([in1])
loaded_model.save('full_model.h5')
```

And in DL4J:
```
ComputationGraph model = KerasModelImport.importKerasModelAndWeights("full_model.h5");
INDArray input1 = Nd4j.zeros(1, 3, 224, 224).addi(-1);
System.out.println(model.output(input1)[0]); 
```

**Comment by montardon** [comment]
If think you are creating a model without trained weights. 
Predicting any image with this model will give a [0.5 0.5] answer.

Using GPU (GeForce RTX 2080 Ti) I get :
[[0.49996665 0.5000334 ]] for Keras, which is what I expect to see with this untrained model.

When importing this untrained model in DL4J there is an error because "weight_names" is not found.
---
Using my trained model (with trained weights), I'm getting slightly different result with or without GPU.
[[    0.9231,    0.0769]] for DL4J with GPU backend
[[    0.9173,    0.0827]] for DL4J with CPU backend

( I'm now using CUDA 10.1 update 2 to be up to date. I was previously using CUDA 10.1 update 1.)

I know this model has a lot of layers. I'd like to know if numerical errors might happen. 
Just comparing GPU vs CPU on this model , we have a 10e-3 difference in results.
---
If I'm using a png file as test, what is the recommended loader ?
I'm currently using this method in DL4J to load .png as INDrray
BufferedImage image = ImageIO.read(new File(pathToImage));
NativeImageLoader loader = new NativeImageLoader(224,224,224);
INDArray input1 = loader.asMatrix(image);
input1 = input1.divi(127.5f).subi(1.f);
input1 = input1.reshape(1,3,224,224);
System.out.println(model.output(input1)[0])

while in Keras, I'm using this
mg = cv2.imread(pathToImage)
img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
img = img.reshape(1,224,224,3)
# normalize  between [-1,1]
img = img/127.5-1.

print(model.predict( [img ]))

**Comment by raver119** [comment]
```
[[ 0.9231, 0.0769]] for DL4J with GPU backend
[[ 0.9173, 0.0827]] for DL4J with CPU backend
```

This difference can be explained by cuDNN use probably. Show your pom.xml please

**Comment by saudet** [comment]
> img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

You'll need to do the same in Java. One way to do it:
```java
NativeImageLoader loader = new NativeImageLoader(224, 224, 3, new ColorConversionTransform(COLOR_BGR2RGB));
```
https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-zoo/src/test/java/org/deeplearning4j/zoo/TestImageNet.java#L96

**Comment by montardon** [comment]
Here is my pom.xml
https://gist.github.com/montardon/68c4167ce1f5d11890bf254a5419bc23

**Comment by montardon** [comment]
Using the ColorConversionTransform, I'm still far from Keras result.
[[    0.25672656 0.74327344 ]] for Keras
[[    0.3168,        0.6832         ]] for DL4J
My code is so simple that I wonder where to check.
https://gist.github.com/montardon/160722d038d365600059a14265fcccd6

**Comment by montardon** [comment]
When using a different model (with less layers) and (32,32,3) inputs, 
[model.zip](https://github.com/eclipse/deeplearning4j/files/3712921/model.zip)
I am getting the same values both in DL4J and Keras.
[0.31666294 0.65267104 0.03066603]] for Keras
[0.3166629   0.65267104 0.030666048] for DL4J

**Comment by montardon** [comment]
..with this random image
![random32](https://user-images.githubusercontent.com/238749/66575655-96316a80-eb76-11e9-90d0-36be129b1788.png)

**Comment by montardon** [comment]
I can give you my model to help reproducing. 
It's a file of 192 758 864 bytes.
What is the better way to give you access to it?

**Comment by eraly** [comment]
Google drive?
Also what OS and what versions of Keras are you using?

**Comment by montardon** [comment]
https://drive.google.com/file/d/1MrFWPH4a2LiBfmV5y8UwEMvpcQWtBOJw/view?usp=sharing

**Comment by montardon** [comment]
I'm working with Ubuntu 18.04.3 for development but final target will be Windows 7.
Keras is 2.2.4

**Comment by eraly** [comment]
Thanks for uploading the h5. The output of this model is not (None, 2) like indicated in your earlier comments. It is (None, 91). Maybe this is not the model you intended to upload? [Here](https://gist.github.com/eraly/24b7550fa8bebe9d994851ba66c8ff35) is the full summary from this model.

**Comment by montardon** [comment]
Sorry, I sent to you another model. 
Here is the link to the one I described.
https://drive.google.com/file/d/1Vom3kdKhhwg0bYOJSQKHGQ5iw2mucT1X/view?usp=sharing

**Comment by eraly** [comment]
Thanks for uploading the model. So I took a look and still can't reproduce on my mac+CPU. Results look the same with keras and dl4j... We'll take a look on the other platforms and GPUs.

**Comment by raver119** [comment]
I've just used @eraly repository, and model provided here.

Here's the code:

```
 public static void main(String[] args) throws UnsupportedKerasConfigurationException, IOException, InvalidKerasConfigurationException {

        final String MODEL_PATH = "/home/raver119/Downloads/mymodel.h5";
        final String IMAGE_PATH = new ClassPathResource("random.jpg").getFile().getAbsolutePath();
        ComputationGraph model = KerasModelImport.importKerasModelAndWeights(MODEL_PATH);

        BufferedImage image = ImageIO.read(new File(IMAGE_PATH));
        NativeImageLoader loader = new NativeImageLoader(224,224,3, new ColorConversionTransform(COLOR_BGR2RGB));
        INDArray input1 = loader.asMatrix(image);
        input1 = input1.divi(127.5f).subi(1.f);
        input1 = input1.reshape(1,3,224,224);

        System.out.println(model.output(input1)[0]);
    }
```


Here's output:
```
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for OpenMP: 4
o.n.n.Nd4jBlas - Number of threads used for OpenMP BLAS: 4
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Linux]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [7.8GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [MKL]
o.d.n.g.ComputationGraph - Starting ComputationGraph with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
[[    0.9967,    0.0033]]
```

**Comment by raver119** [comment]
P.s. Ubuntu 18.04

**Comment by montardon** [comment]
Thank you for testing.
You are using .jpeg file ? I added a .png one. Can you give your random.jpg ?
It looks like you have a different result too. Right ?

**Comment by raver119** [comment]
This. https://github.com/eraly/keras-test-import
I'm gettint the result @eraly got in keras. jpg is available in resources folder within that repo

**Comment by montardon** [comment]
```
with Keras on this data : [ 0.9967253    0.00327461 ]
with DL4J on this data :  [ 0.99672544,  0.0032745837 ] with CPU Backend
with DL4J on this data :  [ 0.9936167,   0.006383335 ] with GPU [JCublasBackend] backend
```

So Keras and DL4J CPU are quite the same. It's fine.

The error is 3.10e-3 with DL4J GPU. It looks a bit large even for float.

Is it hardware related ?
I'm using a NVIDIA RTX 2080 Ti (11Gb).

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:65:00.0  On |                  N/A |
| 27%   30C    P8    25W / 250W |    692MiB / 11011MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+

```

**Comment by raver119** [comment]
GPU: is it with cudnn or without it?

**Comment by montardon** [comment]
With cudnn. I put it in /usr/local/cuda-101./lib64.
How can I be sure, DL4J is using it ?

**Comment by raver119** [comment]
It’ll use it if you have deeplearning4j-cuda dependency in your pom.xml. There’ll be some additional output in your console saying that as well.

**Comment by montardon** [comment]
3:59:57.752 [main] DEBUG org.deeplearning4j.nn.layers.normalization.BatchNormalization - CudnnBatchNormalizationHelper successfully initialized
So cudnn is used

**Comment by raver119** [comment]
Great. Disable it, by removing deeplearning4j-cuda dependency, and tell us how your output will change.

**Comment by montardon** [comment]
```
> 14:07:21.524 [main] INFO org.deeplearning4j.nn.layers.convolution.ConvolutionLayer - cuDNN not found: use cuDNN for better GPU performance by including the deeplearning4j-cuda module. For more information, please refer to: https://deeplearning4j.org/docs/latest/deeplearning4j-config-cudnn
> java.lang.ClassNotFoundException: org.deeplearning4j.nn.layers.convolution.CudnnConvolutionHelper
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:264)
> 	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.initializeHelper(ConvolutionLayer.java:76)
> 	at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.<init>(ConvolutionLayer.java:68)
> 	at org.deeplearning4j.nn.conf.layers.ConvolutionLayer.instantiate(ConvolutionLayer.java:168)
> 	at org.deeplearning4j.nn.conf.graph.LayerVertex.instantiate(LayerVertex.java:107)
> 	at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:573)
> 	at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:440)
> 	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraph(KerasModel.java:416)
> 	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraph(KerasModel.java:404)
> 	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:173)
> 	at com.total.syraco.ImportKerasModel.main(ImportKerasModel.java:59)
> [[    0.9967,    0.0033]]
> [0.9967253, 0.003274596]
> 

with Keras on this data : [ 0.9967253    0.00327461 ]
```

So without cudnn, the results are the same as Keras

**Comment by montardon** [comment]
So a workaround is to disable cudnn.
I guess this will have effects on performance. Right ?

With cudnn, the difference with Keras is quite significant. 
Is it a difference in the order of calls to cudnn or in order of data ?
 
I guess if the computations do not have the same order or data is not organized as in Keras (for performance reason), we may not expect the same results.

**Comment by raver119** [comment]
cudnn uses bunch of different algorithms, and in some modes it doesn’t even guarantees reproducibility.
16 окт. 2019 г., 22:37 +0300, raguenets <notifications@github.com>, писал:

**Comment by montardon** [comment]
Are we using such modes ?

In fact, having different results should not be a problem as long as predicted class are the same on my classification problem.

Can we do something with cudnn to minimize the difference ?

**Comment by montardon** [comment]
I have another model with 91 classes.
https://drive.google.com/file/d/1SIMHLk8mVU6778iBVtmWyLh66xlnFMPH/view?usp=sharing
This one is more sensitive to numerical error.
Using this model and the same image random.jpg I get a difference, even without cudnn or with CPU/
Keras : 
[2.65195013e-07 2.83667850e-06 1.49390598e-05 3.77721250e-07
  4.30094559e-07 1.72675336e-05 9.82970887e-05 8.03016961e-01
  2.04671360e-05 2.67947848e-06 1.14034989e-03 1.06829371e-04
  2.97917635e-03 1.75108187e-06 2.25894155e-06 2.03046857e-05
  1.39354825e-05 3.31887782e-06 5.53666963e-04 7.28338279e-08
  1.15690946e-05 1.43283451e-05 4.52526535e-07 1.75516263e-01
  8.04932509e-03 4.99166641e-03 1.91663776e-06 3.65780317e-09
  4.40650001e-06 1.26380910e-05 2.63322789e-07 5.75021240e-08
  5.44792329e-07 5.08889229e-07 2.67648261e-06 7.48904483e-07
  1.65401082e-06 1.21935543e-07 3.44123208e-07 1.52493158e-07
  7.30079307e-07 2.63164974e-08 1.86632940e-04 4.46185113e-05
  1.19623121e-06 2.22342783e-06 2.62019694e-05 8.58597468e-06
  2.30384423e-08 3.50907249e-06 8.36666381e-09 3.14311315e-08
  5.15535203e-06 5.54898043e-06 1.47584738e-04 8.32510614e-06
  7.23823250e-05 2.55992944e-07 7.95811648e-05 7.58394165e-08
  7.40804462e-05 1.31093429e-08 6.44416831e-09 8.93194374e-06
  2.13800263e-06 1.54102608e-09 1.16033361e-09 2.44569965e-03
  9.21850244e-07 5.42192176e-08 1.65679339e-05 1.91269737e-06
  2.48654466e-08 1.14090246e-04 4.03719440e-07 7.53188800e-08
  1.08553093e-06 7.06589773e-08 1.31201011e-06 6.56535558e-05
  3.99938835e-06 9.77924017e-08 2.23954473e-07 1.94951717e-05
  6.26678457e-07 1.63322402e-05 3.39668804e-06 8.89255807e-06
  8.22108814e-06 6.52241852e-07 6.44761349e-06]
DL4J : 
[2.5292178E-7, 2.742751E-6, 1.3690365E-5, 3.4232585E-7, 4.0093425E-7, 1.6315209E-5, 9.093951E-5, 0.8335153, 1.8959123E-5, 2.5161698E-6, 0.0010757704, 1.0405863E-4, 0.002697534, 1.7189349E-6, 2.1105304E-6, 1.857004E-5, 1.3158829E-5, 3.080307E-6, 4.945854E-4, 6.8934725E-8, 1.1050852E-5, 1.3541143E-5, 4.1684243E-7, 0.14584747, 0.007942164, 0.0050273724, 1.7329238E-6, 3.4104588E-9, 4.0695904E-6, 1.1279884E-5, 2.4067032E-7, 5.166618E-8, 4.8790224E-7, 4.7539112E-7, 2.4428732E-6, 6.928368E-7, 1.5016857E-6, 1.08740664E-7, 3.2130856E-7, 1.3811956E-7, 6.3851473E-7, 2.3729784E-8, 1.7297968E-4, 4.143586E-5, 1.0555073E-6, 2.0412722E-6, 2.4763465E-5, 7.794147E-6, 2.0685171E-8, 3.1706454E-6, 8.048284E-9, 2.915903E-8, 4.7160643E-6, 4.872083E-6, 1.3799497E-4, 7.5772837E-6, 6.569508E-5, 2.371423E-7, 6.957336E-5, 6.9124056E-8, 6.913465E-5, 1.2019272E-8, 5.83105E-9, 8.081083E-6, 1.9414624E-6, 1.4140105E-9, 1.0984424E-9, 0.0021883736, 8.6928304E-7, 5.1143296E-8, 1.5105344E-5, 1.881107E-6, 2.2526422E-8, 1.054259E-4, 3.6506592E-7, 6.9482276E-8, 1.0501698E-6, 6.5658654E-8, 1.2214383E-6, 5.954672E-5, 3.7462194E-6, 9.157782E-8, 2.1115162E-7, 1.8151062E-5, 5.877529E-7, 1.5047572E-5, 3.238813E-6, 8.947605E-6, 7.628451E-6, 5.9469363E-7, 6.2808963E-6]
Largest value  Keras 0.803 (index 7)
Largers value DL4J : 0.833 (index 7)

**Comment by saudet** [comment]
@montardon We can try manually to use a different algorithm from cuDNN:
https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/layers/ConvolutionLayer.java

**Comment by montardon** [comment]
How can I use these options ? There are 2 ConvolutionLayer classes.
I read my ComputationalGraph from .h5. I tried to use model.getLayer(idx) and compare to  org.deeplearning4j.nn.conf.layers.ConvolutionLayer without success.

**Comment by AlexDBlack** [comment]
@montardon See this:
```
MultiLayerNetwork net = ...;
int layerIdx = ...;
((ConvolutionLayer)net.getLayerWiseConfigurations().getConf(layerIdx).getLayer()).setCudnnAlgoMode(ConvolutionLayer.AlgoMode.PREFER_FASTEST);
```

Admittedly not the easiest thing ever (not typically designed to be changed after network initialization) but that should work ok.

**Comment by montardon** [comment]
Sorry, I have a ComputationGraph from importKerasModelAndWeights, not a MultiLayerNetwork.

**Comment by AlexDBlack** [comment]
@montardon 
```
ComputationGraph graph = ...
ConvolutionLayer layer = (ConvolutionLayer) graph.getLayer("myLayer").getConfig();
layer.setCudnnAlgoMode(ConvolutionLayer.AlgoMode.PREFER_FASTEST);
```

**Comment by montardon** [comment]
Thank you.
I used environment variables 
CUDNN_LOGINFO_DBG=1
CUDNN_LOGDEST_DBG=stdout
It looks like ConvolutionalFwdAlgo are not the same in Keras/Python and in DL4J. 
Keras/Python is using FWD_ALGO_IMPLICIT_GEMM.
I will try to use the same algorithm.
