### ISSUE TITLE
ndarray.getDouble returns wrong value for index

### ISSUE THREAD

**Issue by evolutionsoftswiss** [deeplearning4j/deeplearning4j#8259]
Unfeortunately I can't reproduce it in an extracted Unit Test

#### Issue Description
* NDArray floatBufferData [3.0,3.0,3.0,3.0,0.0,3.0,3.0,3.0,0.0] returns 3.0 for getDouble(0,4)
* Should be 0.0

#### Version Information

Please indicate relevant versions, including, if relevant:

* dl4-1.0.0-beta5
* Ubuntu 18.04.x, Inside Eclipse Photon with Java8 Oracle
* No Cuda, Native
* -

#### Eclipse Debug output

getDouble() returned	3.0	
this	NDArray  (id=82)	
	compressed	false	
	data	FloatBuffer  (id=94)	
		allocationMode	DataBuffer$AllocationMode  (id=103)	
		attached	false	
		constant	false	
		elementSize	4	
		indexer	FloatRawIndexer  (id=108)	
		length	9	
		offset	40662	
		originalBuffer	FloatBuffer  (id=112)	
		originalOffset	40662	
		parentWorkspace	null	
		pointer	FloatPointer  (id=113)	
		referenced	AtomicBoolean  (id=116)	
		released	false	
		trackingPoint	null	
		type	DataType  (id=119)	
		underlyingLength	40680	
		workspaceGenerationId	0	
		wrappedDataBuffer	FloatBuffer  (id=112)	
	jvmShapeInfo	JvmShapeInfo  (id=98)	
	released	false	
	shapeInformation	LongBuffer  (id=100)	
indices	(id=88)	
	[0]	0	
	[1]	4	

Where applicable, please also provide:
log
´´´
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for OpenMP: 4
o.n.n.Nd4jBlas - Number of threads used for OpenMP BLAS: 4
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Linux]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [4]; Memory: [1.7GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [MKL]
c.e.e.d.t.f.FeedForwardCommon - Build model ...
o.d.n.m.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
c.e.e.d.t.f.FeedForwardTwoLayerMain - 

LayerName (LayerType)   nIn,nOut   TotalParams   ParamsShape         

layer0 (DenseLayer)     9,161      1,610         W:{9,161}, b:{1,161}
layer1 (OutputLayer)    161,9      1,458         W:{161,9}, b:{1,9}  

            Total Parameters:  3,068
        Trainable Parameters:  3,068
           Frozen Parameters:  0

c.e.e.d.t.f.FeedForwardCommon - Generate adapted net input and labels ...
´´´

**Comment by raver119** [comment]
No, it's not necessary true. It depends on order of your INDArray. Show full code that reproduces this problem, however I'm highly skeptic - there's tons of tests for indexing.

**Comment by raver119** [comment]
... and since it's not reproducible alone - that means you're trying to reproduce it with INDArray in default order, which is 'C', but you face "problem" with `F` ordered arrays.

**Comment by evolutionsoftswiss** [comment]
[    3.0000,    3.0000,    3.0000,    3.0000,         0,    3.0000,    3.0000,    3.0000,         0]
I've got the situation in such an array created by Nd4j.zeros(1, 9);
And then set the 3.00 values by setScalar()

Then getDouble returns 3.00 at the following code for at least the middle index 4 of currentResult
```java
   else if (equalsEpsilon(currentPlayground.getDouble(0, arrayIndex), EMPTY_FIELD_VALUE,
             DOUBLE_COMPARISON_EPSILON) &&
             SMALLEST_MAX_WIN <= currentResult.getDouble(0, arrayIndex)) {
      // ...
   }
```

For the full code you may refer to https://github.com/evolutionsoftswiss/dl4j/tree/develop/neural-net-game/src/main/java/ch/evolutionsoft/net/game

**Comment by evolutionsoftswiss** [comment]
I'll check the behavior at the same place with some other versions.

**Comment by evolutionsoftswiss** [comment]
Definitively different behavior with beta3, I had to use that version to not make additional changes because of the INDArrayDataSetIterator.
