### ISSUE TITLE
Word2Vec exessive memory usage

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#826]
I've noticed that modelling w2v, has exessive memory usage.
Model description:
3GB of text
42 millions sentences.
3.1 millions of words in Vocab.

JVM settings:
-Xms20G -Xmx20G

Versions used: 
nd4j 0.4-rc3.5
dl4j 0.4-rc3.4

Code:
To reproduce this i've used Word2Vec example provided at dl4j-0.4-examples, with following params:
.minWordFrequency(10)
.iterations(3)
.layerSize(200).

Exsessive memory usage exists in two calculation phases:
1. initial Vocab buildiing
2. w2v calulations

# initial Vocab building

Here's memory sampling screenshot taken at first phase:
http://www.image123.net/v3eemxn70hsjpic.html

And here's memory sampling screenshot taken right at the end of first phase:
http://www.image123.net/nkqffiex4v21pic.html

Here's overall graphs of JVisualVM:
http://www.image123.net/mmk7rrznu9zypic.html

It looks like all raw content is stored untill the end of this phase, it feels like if you want to vectorize 100M lines, you'll have to store everything in RAM. And this will effectively prevent building models from large corpus.

# w2v calculations

Here's overall graphs that confirm memory release after Vocab is build in first phase:
http://www.image123.net/uq2qgep64gkmpic.html

After Vocab is build, memory usage drops down, so it looks like GC is not an issue here. As calculations go through words, memory usage starts growing, and grows up to OOM at 20G RAM used.

GC overhead/OOM stack traces:
https://gist.github.com/raver119/9048ef361aef5e409896
https://gist.github.com/raver119/225cd1e4908cf25d2d44

Overall graph right before OOM:
http://www.image123.net/k4rw5ph7y9r1pic.html

Memory sampling right before OOM:
http://www.image123.net/yj5j7gtjyir8pic.html

**Comment by raver119** [comment]
One more thing: nd4j-x86 backend was used, under Ubuntu 15.10, native blas libs installed.

**Comment by linkerlin** [comment]
I recommend you to split dataset to smaller pieces and invent a method for combine diff-vector spaces.
For short, a Map-Reduce for word2vec .

**Comment by raver119** [comment]
i doubt its a good idea, since at least the first part of this problem - vocab building - can be done "on the fly", without storiing everything in RAM. So, it doesn't needs any magic with vector-space.

Second part of this problem, that comes from overall memory usage at w2v calculations: this model in any circumstances will use (2 * vocab size * vector dimensions * data type size) memory. So no way any vector-space magic will reduce memory usage below this basic line. So, the task here is to find the way to stick to this basic memory usage, and stay as close to it as possible. Though, no idea how to make it so far :(

**Comment by raver119** [comment]
For example: i want to build rich language model, from 1TB of files. Vocab can be built on the fly, so as for me it is not an issue. Only the question "how long will it take to rewrite it?".

But on the next step, memory efficiency is strictly dependant on vocab size, not the number of lines. To solve it you need to use "another" RAM. Will it be some cloud based buffer, or external storage - its up to you. But i think there's no way Map-Reduce will help you to avoid actual RAM restrictions caused by model behind w2v.

**Comment by agibsonccc** [comment]
PR merged.
