### ISSUE TITLE
Unused methods in IActivation interface

### ISSUE THREAD

**Issue by RobAltena** [deeplearning4j/deeplearning4j#8260]
#### Issue Description
The [following methods ](https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/activations/IActivation.java#L62-L68)in IActivations are unused.

    void setParametersViewArray(INDArray viewArray, boolean initialize);

    INDArray getParametersViewArray();

    void setGradientViewArray(INDArray viewArray);

    INDArray getGradientViewArray();

Would it be ok to remove them as a part of the ongoing cleanup?

**Comment by AlexDBlack** [comment]
Long ago the plan was to allow activation functions with learnable parameters. That never happened, and it's not on the DL4J roadmap either. SameDiff would use a different mechanism also.

In short: yes, feel free to remove that.
