### ISSUE TITLE
cuDNN causes NaN scores during the training

### ISSUE THREAD

**Issue by Morozov2012** [deeplearning4j/deeplearning4j#8264]
I have found that an example does not operate under Deeplearning4j Beta5, CUDA 10.1, cuDNN 7.6.3. Last year, this example worked fine under Deeplearning4j Beta2, CUDA 9.2, cuDNN 7.3.1. The problem is in that the program generates NaN scores during the training of plain Darknet19:

C:\ceur3>java -Xmx330000000k -jar main.jar
modelType: Darknet19
[main] INFO examples.THzImageClassification21 - Load data....
mainPath: C:\ceur3\thz_images
numExamples: 13553
numLabels: 2
trainData.length(): 9173
testData.length(): 2293
[main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
ND4J CUDA build version: 10.1.243
CUDA device 0: [GeForce GTX 1080 Ti]; cc: [6.1]; Total memory: [11811160064];
[main] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for OpenMP: 32
[main] INFO org.nd4j.nativeblas.Nd4jBlas - Number of threads used for OpenMP BLAS: 0
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [8]; Memory: [314,7GB];
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [CUBLAS]
[main] INFO org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner - Device Name: [GeForce GTX 1080 Ti]; CC: [6.1]; Total/free memory: [11811160064]
[main] INFO examples.THzImageClassification21 - Build model....
[main] INFO org.deeplearning4j.nn.graph.ComputationGraph - Starting ComputationGraph with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
[main] INFO examples.THzImageClassification21 - Train model....
[main] INFO org.datavec.image.recordreader.BaseImageRecordReader - ImageRecordReader: 2 label classes inferred using label generator ParentPathLabelGenerator
epochs: 30
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 0 is 0.8208270329116607
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 1 is NaN
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 2 is NaN
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 3 is NaN
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 4 is NaN
...

I found that the cause of this problem is in cuDNN. I just have deleted the deeplearning4j-cuda-10.1-1.0.0-beta5.jar library. After that, the program generates proper scores:

C:\ceur3>java -Xmx330000000k -jar main.jar
modelType: Darknet19
[main] INFO examples.THzImageClassification21 - Load data....
mainPath: C:\ceur3\thz_images
numExamples: 13553
numLabels: 2
trainData.length(): 9173
testData.length(): 2293
[main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
ND4J CUDA build version: 10.1.243
CUDA device 0: [GeForce GTX 1080 Ti]; cc: [6.1]; Total memory: [11811160064];
[main] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for OpenMP: 32
[main] INFO org.nd4j.nativeblas.Nd4jBlas - Number of threads used for OpenMP BLAS: 0
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [8]; Memory: [314,7GB];
[main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [CUBLAS]
[main] INFO org.nd4j.linalg.jcublas.ops.executioner.CudaExecutioner - Device Name: [GeForce GTX 1080 Ti]; CC: [6.1]; Total/free memory: [11811160064]
[main] INFO examples.THzImageClassification21 - Build model....
[main] INFO org.deeplearning4j.nn.graph.ComputationGraph - Starting ComputationGraph with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
[main] INFO org.deeplearning4j.nn.layers.convolution.ConvolutionLayer - cuDNN not found: use cuDNN for better GPU performance by including the deeplearning4j-cuda module. For more information, please refer to: https://deeplearning4j.org/docs/latest/deeplearning4j-config-cudnn
java.lang.ClassNotFoundException: org.deeplearning4j.nn.layers.convolution.CudnnConvolutionHelper
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:332)
        at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.initializeHelper(ConvolutionLayer.java:76)
        at org.deeplearning4j.nn.layers.convolution.ConvolutionLayer.<init>(ConvolutionLayer.java:68)
        at org.deeplearning4j.nn.conf.layers.ConvolutionLayer.instantiate(ConvolutionLayer.java:168)
        at org.deeplearning4j.nn.conf.graph.LayerVertex.instantiate(LayerVertex.java:107)
        at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:573)
        at org.deeplearning4j.nn.graph.ComputationGraph.init(ComputationGraph.java:440)
        at org.deeplearning4j.zoo.model.Darknet19.init(Darknet19.java:165)
        at org.deeplearning4j.zoo.model.Darknet19.init(Darknet19.java:56)
        at examples.THzImageClassification21.run(THzImageClassification21.java:245)
        at examples.THzImageClassification21.main(THzImageClassification21.java:323)
[main] INFO examples.THzImageClassification21 - Train model....
[main] INFO org.datavec.image.recordreader.BaseImageRecordReader - ImageRecordReader: 2 label classes inferred using label generator ParentPathLabelGenerator
epochs: 30
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 0 is 0.82082688032377
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 1 is 0.8003847536618222
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 2 is 0.7493798095660948
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 3 is 0.740649952832581
[main] INFO org.deeplearning4j.optimize.listeners.ScoreIterationListener - Score at iteration 4 is 0.6762632844918425
...

#### Version Information

* Deeplearning4j version

Beta5

* Platform information (OS, etc)

Windows 10

* CUDA version, if used

cuda_10.1.243_426.00_win10.exe
cudnn-10.1-windows10-x64-v7.6.3.30.zip

* NVIDIA driver version, if in use

426.00

#### Additional Information

Please help me to fix this bug.

**Comment by raver119** [comment]
Which example is this?

**Comment by Morozov2012** [comment]
This one: https://yadi.sk/d/-M0Sobt5exDjTg

**Comment by Morozov2012** [comment]
// 2019 (c) Alexei A. Morozov

package examples;

import java.io.FileFilter;

import org.deeplearning4j.nn.graph.ComputationGraph;
import org.deeplearning4j.zoo.ZooModel;
import org.deeplearning4j.zoo.model.*;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.deeplearning4j.zoo.util.imagenet.ImageNetLabels;

import org.apache.commons.io.FilenameUtils;
import org.datavec.api.io.filters.BalancedPathFilter;
import org.datavec.api.io.labels.ParentPathLabelGenerator;
import org.datavec.api.split.FileSplit;
import org.datavec.api.split.InputSplit;
import org.datavec.image.loader.NativeImageLoader;
import org.datavec.image.recordreader.ImageRecordReader;
import org.datavec.image.transform.FlipImageTransform;
import org.datavec.image.transform.ImageTransform;
import org.datavec.image.transform.PipelineImageTransform;
import org.datavec.image.transform.WarpImageTransform;
import org.deeplearning4j.api.storage.StatsStorage;
import org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator;
import org.deeplearning4j.eval.Evaluation;
import org.deeplearning4j.nn.conf.GradientNormalization;
import org.deeplearning4j.nn.conf.MultiLayerConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.distribution.Distribution;
import org.deeplearning4j.nn.conf.distribution.GaussianDistribution;
import org.deeplearning4j.nn.conf.distribution.NormalDistribution;
import org.deeplearning4j.nn.conf.inputs.InputType;
import org.deeplearning4j.nn.conf.inputs.InvalidInputTypeException;
import org.deeplearning4j.nn.conf.layers.*;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.deeplearning4j.nn.weights.WeightInit;
import org.deeplearning4j.optimize.listeners.ScoreIterationListener;
import org.deeplearning4j.util.ModelSerializer;
import org.nd4j.linalg.activations.Activation;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.dataset.api.iterator.DataSetIterator;
import org.nd4j.linalg.dataset.api.preprocessor.DataNormalization;
import org.nd4j.linalg.dataset.api.preprocessor.ImagePreProcessingScaler;
import org.nd4j.linalg.learning.config.Nesterovs;
import org.nd4j.linalg.lossfunctions.LossFunctions;
import org.nd4j.linalg.primitives.Pair;
import org.nd4j.linalg.schedule.ScheduleType;
import org.nd4j.linalg.schedule.StepSchedule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.nd4j.linalg.factory.Nd4j;
import org.datavec.image.loader.ImageLoader;
import java.awt.image.BufferedImage;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JLabel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.Graphics;
import java.awt.Dimension;
import java.awt.Color;
import java.util.concurrent.atomic.AtomicReference;

import java.io.File;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

public class THzImageClassification21 {
	//
	protected static final Logger log= LoggerFactory.getLogger(THzImageClassification21.class);
	//
	protected static int height= 224;
	protected static int width= 224;
	protected static int channels= 3;
	protected static int batchSize= 50;
	//
	protected static long seed= 42;
	protected static Random rng= new Random(seed);
	protected static int epochs= 30;
	protected static double splitTrainTest= 0.8;
	protected static boolean save= true;
	protected static int maxPathsPerLabel= 0;
	protected static int listenerFreq= 1;
	//
	protected static String modelType= "Darknet19";
	//
	private int numLabels;
	//
	public THzImageClassification21() {
	}
	//
	public void run(String[] args) throws Exception {
		System.out.printf("modelType: %s\n",modelType);
		/////////////////////////////////////////////////////////////////////
		log.info("Load data....");
		ParentPathLabelGenerator labelMaker= new ParentPathLabelGenerator();
		File mainPath= new File(System.getProperty("user.dir"),"/thz_images/");
		System.out.printf("mainPath: %s\n",mainPath);
		FileSplit fileSplit= new FileSplit(mainPath,NativeImageLoader.ALLOWED_FORMATS,rng);
		int numExamples= toIntExact(fileSplit.length());
		System.out.printf("numExamples: %s\n",numExamples);
		numLabels= fileSplit.getRootDir().listFiles(new DirectoryFileFilter()).length;
		System.out.printf("numLabels: %s\n",numLabels);
		BalancedPathFilter pathFilter= new BalancedPathFilter(rng,labelMaker,numExamples,numLabels,maxPathsPerLabel);
		InputSplit[] inputSplit= fileSplit.sample(pathFilter,splitTrainTest,1-splitTrainTest);
		InputSplit trainData= inputSplit[0];
		InputSplit testData= inputSplit[1];
		System.out.printf("trainData.length(): %s\n",trainData.length());
		System.out.printf("testData.length(): %s\n",testData.length());
		/////////////////////////////////////////////////////////////////////
		ImageTransform flipTransform1= new FlipImageTransform(rng);
		ImageTransform flipTransform2= new FlipImageTransform(new Random(123));
		ImageTransform warpTransform= new WarpImageTransform(rng,42);
		boolean shuffle= false;
		List<Pair<ImageTransform,Double>> pipeline= Arrays.asList(
			new Pair<>(flipTransform1,0.9),
			new Pair<>(flipTransform2,0.8),
			new Pair<>(warpTransform,0.5));
		ImageTransform transform= new PipelineImageTransform(pipeline,shuffle);
		DataNormalization scaler= new ImagePreProcessingScaler(0,1);
		/////////////////////////////////////////////////////////////////////
		log.info("Build model....");
		ZooModel zooModel;
		switch (modelType) {
			case "AlexNet":
				zooModel= AlexNet.builder().numClasses(numLabels).seed(seed).build();
				break;
			case "Darknet19":
				zooModel= Darknet19.builder().numClasses(numLabels).seed(seed).build();
				// zooModel= Darknet19.builder().numClasses(numLabels).seed(seed).cudnnAlgoMode(ConvolutionLayer.AlgoMode.NO_WORKSPACE).build();
				// zooModel= Darknet19.builder().numClasses(numLabels).seed(seed).cudnnAlgoMode(ConvolutionLayer.AlgoMode.PREFER_FASTEST).build();
				break;
			case "FaceNetNN4Small2":
				zooModel= FaceNetNN4Small2.builder().numClasses(numLabels).seed(seed).build();
				break;
			case "InceptionResNetV1":
				zooModel= InceptionResNetV1.builder().numClasses(numLabels).seed(seed).build();
				break;
			case "LeNet":
				zooModel= LeNet.builder().numClasses(numLabels).seed(seed).build();
				break;
			case "NASNet":
				zooModel= NASNet.builder().numClasses(numLabels).seed(seed).build();
				break;
			case "ResNet50":
				zooModel= ResNet50.builder().numClasses(numLabels).seed(seed).build();
				break;
			case "SimpleCNN":
				zooModel= SimpleCNN.builder().numClasses(numLabels).seed(seed).build();
				break;
			case "SqueezeNet":
				zooModel= SqueezeNet.builder().numClasses(numLabels).seed(seed).build();
				break;
			case "TextGenerationLSTM":
				zooModel= TextGenerationLSTM.builder().seed(seed).build();
				break;
			case "TinyYOLO":
				zooModel= TinyYOLO.builder().numClasses(numLabels).seed(seed).build();
				break;
			case "UNet":
				zooModel= UNet.builder().numClasses(numLabels).seed(seed).build();
				break;
			case "VGG16":
				zooModel= VGG16.builder().numClasses(numLabels).seed(seed).build();
				break;
			case "VGG19":
				zooModel= VGG19.builder().numClasses(numLabels).seed(seed).build();
				break;
			case "Xception":
				zooModel= Xception.builder().numClasses(numLabels).seed(seed).build();
				break;
			case "YOLO2":
				zooModel= YOLO2.builder().numClasses(numLabels).seed(seed).build();
				break;
			default:
				throw new InvalidInputTypeException("Incorrect model provided.");
		};
		zooModel.setInputShape(new int[][]{{channels,width,height}});
		ComputationGraph network= zooModel.init();
		network.setListeners(new ScoreIterationListener(listenerFreq));
		/////////////////////////////////////////////////////////////////////
		ImageRecordReader recordReader= new ImageRecordReader(height,width,channels,labelMaker);
		DataSetIterator dataIter;
		/////////////////////////////////////////////////////////////////////
		long t1= System.currentTimeMillis();
		/////////////////////////////////////////////////////////////////////
		log.info("Train model....");
		recordReader.initialize(trainData,null);
		dataIter= new RecordReaderDataSetIterator(recordReader,batchSize,1,numLabels);
		scaler.fit(dataIter);
		dataIter.setPreProcessor(scaler);
		System.out.printf("epochs: %s\n",epochs);
		network.fit(dataIter,epochs);
		/////////////////////////////////////////////////////////////////////
		recordReader.initialize(trainData,transform);
		dataIter= new RecordReaderDataSetIterator(recordReader,batchSize,1,numLabels);
		scaler.fit(dataIter);
		dataIter.setPreProcessor(scaler);
		System.out.printf("epochs: %s\n",epochs);
		network.fit(dataIter,epochs);
		/////////////////////////////////////////////////////////////////////
		long t2= System.currentTimeMillis();
		long delta= t2 - t1;
		double seconds= delta / 1000.0;
		double minutes= seconds / 60.0;
		System.out.printf("Elapsed time: %s [seconds]\n",seconds);
		System.out.printf("Elapsed time: %s [minutes]\n",minutes);
		/////////////////////////////////////////////////////////////////////
		log.info("Evaluate model....");
		recordReader.initialize(testData);
		dataIter= new RecordReaderDataSetIterator(recordReader,batchSize,1,numLabels);
		scaler.fit(dataIter);
		dataIter.setPreProcessor(scaler);
		Evaluation eval= network.evaluate(dataIter);
		log.info(eval.stats(false));
		/////////////////////////////////////////////////////////////////////
		if (save) {
			log.info("Save model....");
			ModelSerializer.writeModel(network,"model-"+modelType+".bin",true);
		};
		/////////////////////////////////////////////////////////////////////
		log.info("Thank you!");
	}
	public static int toIntExact(long value) {
		if ((int)value != value) {
			throw new ArithmeticException("integer overflow");
		}
		return (int)value;
	}
	public int[] computePredictions(INDArray output) {
		int length= toIntExact(output.size(0));
		int[] ret= new int[length];
		for (int n=0; n < length; n++) {
			ret[n]= Nd4j.getBlasWrapper().iamax(output.getRow(n));
		};
		return ret;
	}
	public static void main(String[] args) throws Exception {
		THzImageClassification21 c= new THzImageClassification21();
		c.run(args);
	}
}

class DirectoryFileFilter implements FileFilter {
	public DirectoryFileFilter() {
	}
	public boolean accept(File pathname) {
		return pathname.isDirectory();
	}
}
// 2019 (c) Alexei A. Morozov

package examples;

import org.datavec.api.split.BaseInputSplit;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;

public class SingleInputSplit extends BaseInputSplit {
	public SingleInputSplit(String path) {
		uriStrings= new ArrayList<>(1);
		// String uri= "file:///" + path;
		// System.err.printf(">>>%s<<<\n",uri);
		uriStrings.add(path);
	}
	@Override
	public void updateSplitLocations(boolean reset) {
	}
	@Override
	public boolean needsBootstrapForWrite() {
		return false;
	}
	@Override
	public void bootStrapForWrite() {
	}
	@Override
	public OutputStream openOutputStreamFor(String location) throws Exception {
		return null;
	}
	@Override
	public InputStream openInputStreamFor(String location) throws Exception {
		return null;
	}
	@Override
	public long length() {
		return uriStrings.size();
	}
	@Override
	public void reset() {
		// No op
	}
	@Override
	public boolean resetSupported() {
		return true;
	}
}

**Comment by thhart** [comment]
I have observed the same with a convolution network like in HouseNumberDetection from examples. GPU and CPU learning work well, while enabled cuDNN support fails giving NaN scores from 1. iteration on.

Version: 1.0.0-beta6
libcudnn7_7.6.5.32-1+cuda10.1
inux seal 5.4.0-9-generic #12-Ubuntu SMP Mon Dec 16 22:34:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

o.n.n.Nd4jBlas - Number of threads used for OpenMP BLAS: 0
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Linux]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [16]; Memory: [13.9GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
o.n.l.j.JCublasBackend - ND4J CUDA build version: 10.1.243
o.n.l.j.JCublasBackend - CUDA device 0: [GeForce GTX 1650]; cc: [7.5]; Total memory [4101898240]

**Comment by saudet** [comment]
Could you please give it a try with the snapshots as well?
https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots
