### ISSUE TITLE
I need WordVectors only

### ISSUE THREAD

**Issue by nixondevph** [deeplearning4j/deeplearning4j#8269]
how do I use WordVector without downloading the whole project?

**Comment by raver119** [comment]
in this case you need only two dependences: deeplearning4j-nlp and nd4j-native-platform 

With best regards,
Vyacheslav K.

**Comment by nixondevph** [comment]
> in this case you need only two dependences: deeplearning4j-nlp and nd4j-native-platform With best regards, Vyacheslav K.
> […](#)
> 5 окт. 2019 г., в 17:43, Dinesh Chugtai ***@***.***> написал(а): ﻿ how do I use WordVector without downloading the whole project? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

is there a JAR that i can download? :)

**Comment by raver119** [comment]
Yes, on maven central. But i’d recommend you to use build system like maven or gradle instead.
