### ISSUE TITLE
deeplearning4j prints to standard output

### ISSUE THREAD

**Issue by lpaatero** [deeplearning4j/deeplearning4j#8270]
#### Issue Description

When using deeplearning4j in linux command line program, no additional output should be present on program standard output. Any additional output will interfere with expected output of the program. 

In beta5 version deeplearning4j prints 2 lines to standard output

> ND4J CUDA build version: 10.0.130
> CUDA device 0: [GeForce GTX 1070]; cc: [6.1]; Total memory: [8510832640];

There does not seem to be any easy way to prevent this output.

#### Version Information

beta5 in linux using CUDA.

#### Correction

Preferably make this kind of printout to follow java logging settings. If not possible, make printout optional.

**Comment by AlexDBlack** [comment]
That's a fair request.
It's coming from c++ here: https://github.com/eclipse/deeplearning4j/blob/b7226bdd7a020bdeff253d0f23e9110753ad7c1e/libnd4j/blas/Environment.cpp#L73-L87

**Comment by AlexDBlack** [comment]
Thanks for reporting this. Fixed here: https://github.com/KonduitAI/deeplearning4j/pull/12
This will be merged back to the Eclipse repo shortly, and the fix will be available on snapshots some time next week.

Now all initialization logging (including the CUDA logging flagged in the issue) can be disabled by either setting the system property (see link below) or by configuring your logging backend for ND4J (to error level or higher for org.nd4j loggers).
https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-common/src/main/java/org/nd4j/config/ND4JSystemProperties.java#L27-L33
