### ISSUE TITLE
Transfer learning

### ISSUE THREAD

**Issue by abdougrinzou** [deeplearning4j/deeplearning4j#8272]
How do I load Alexnet pretraind model in python, and how and where do I know the layer that I should stop to inject the feature map to an Svm classifier.. I'm doing a transfert learning in python with Keras and TensorFlow 😔?

**Comment by yptheangel** [comment]
@abdougrinzou can you breakdown the problem that you are facing?

If your main goal is to run on python, you would not need dl4j for that. You will need Eclipse DL4J if you want to do transfer learning on Java /JVM.

E.g. You can train a keras/tf model and import your model into DL4J and do transfer learning from there on, but it will be in Java

**Comment by AlexDBlack** [comment]
Closing as unrelated to DL4J/ND4J/SameDiff etc
