### ISSUE TITLE
UnsatisfiedLinkError: isMinimalRequirementsMet()

### ISSUE THREAD

**Issue by michaelmalak** [deeplearning4j/deeplearning4j#8277]
#### Issue Description

Build error:

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.401 sec <<< FAILURE!
org.nd4j.jdbc.hsql.HSqlLoaderTest  Time elapsed: 1.4 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: 'boolean org.nd4j.nativeblas.Nd4jCpu.isMinimalRequirementsMet()'
	at org.nd4j.nativeblas.Nd4jCpu.isMinimalRequirementsMet(Native Method)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createBlas(CpuNDArrayFactory.java:95)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.blas(BaseNDArrayFactory.java:71)

#### Version Information

Please indicate relevant versions, including, if relevant:

2019-10-08 git version 50b13fadc81a780b3f062c8db7fb6d78ec3ff3c7 branch master
Ubuntu 19.04
OpenJDK 11.0.4
Maven 3.6.0
gcc 8.3.0

mvn clean package -P testresources

**Comment by raver119** [comment]
It says that you hadn’t built libnd4j, so ND4j can’t find the method it expects to be available.

**Comment by michaelmalak** [comment]
libnd4j is built in libnd4j/target/libnd4j-1.0.0-SNAPSHOT-linux-x86_64.zip

Is there a manual step I need to perform to have that library installed so that the rest of the build can succeed?

**Comment by AlexDBlack** [comment]
Probably outdated snapshots, this isn't a build issue.
New snapshots are online, so this shouldn't be a problem anymore.
