### ISSUE TITLE
libnd4j: biasadd_bp doesn't have isNCHW arg, wrong for NHWC case?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8280]
https://github.com/eclipse/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/parity_ops/bias_add.cpp#L83-L86

The bias gradient (via sum) is basically epsilonNext.sum(0, 2, 3) which is correct for the NCHW case but not the NHWC case (which should be .sum(0, 1, 2))

**Comment by shyrma** [comment]
corrected!
