### ISSUE TITLE
What happened to the test resources?

### ISSUE THREAD

**Issue by nwinkler** [deeplearning4j/deeplearning4j#8281]
#### Issue Description

I forked/cloned this repo to potentially add some features to the Datavec module. Compiling through Maven without test case execution worked fine, but when I try to run the test cases, I ran into all kinds of errors (`mvn clean install`).

When looking into the test errors for the `datavec-api` module, I noticed that the `src/test/resources` folder was not migrated when the project was moved into the monorepo.

The test resources can be found in the archived repo: https://github.com/deeplearning4j/DataVec/tree/master/datavec-api/src/test/resources

But they are not here: https://github.com/eclipse/deeplearning4j/tree/master/datavec/datavec-api/src

What happened to the test resources? Without them, none of the unit tests work...

Any instructions on how to run the unit tests? Without the tests, I don't feel comfortable to make changes...

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-SNAPSHOT (master branch)
* Platform information (OS, etc): macOS 10.13.6
* CUDA version, if used
* NVIDIA driver version, if in use

#### Additional Information

Where applicable, please also provide:

```
Running org.datavec.api.records.reader.impl.SVMLightRecordReaderTest
Tests run: 15, Failures: 0, Errors: 15, Skipped: 0, Time elapsed: 0.176 sec <<< FAILURE! - in org.datavec.api.records.reader.impl.SVMLightRecordReaderTest
testNextRecord(org.datavec.api.records.reader.impl.SVMLightRecordReaderTest)  Time elapsed: 0.135 sec  <<< ERROR!
java.io.FileNotFoundException: datavec-api/svmlight/basic.txt cannot be opened because it does not exist
	at org.datavec.api.records.reader.impl.SVMLightRecordReaderTest.testNextRecord(SVMLightRecordReaderTest.java:347)

testBasicRecord(org.datavec.api.records.reader.impl.SVMLightRecordReaderTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.io.FileNotFoundException: datavec-api/svmlight/basic.txt cannot be opened because it does not exist
	at org.datavec.api.records.reader.impl.SVMLightRecordReaderTest.testBasicRecord(SVMLightRecordReaderTest.java:76)
```

#### Contributing

Would love to provide some additional functional, e.g. more supported date formats in `StringToTimeTransformation`, but can't do that without working unit tests...

**Comment by AlexDBlack** [comment]
Clone this repo and install: https://github.com/deeplearning4j/dl4j-test-resources
Then enable 2 profiles: testresources and test-nd4j-native
https://github.com/eclipse/deeplearning4j/blob/master/pom.xml#L679
https://github.com/eclipse/deeplearning4j/blob/master/datavec/pom.xml#L350

**Comment by nwinkler** [comment]
Thanks for the instructions - is that documented anywhere?
