### ISSUE TITLE
libnd4j: concat op - add "last input is axis" support

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8285]
Required for TF import.
Currently we pull out the axis during import, which will work most of the time, but will fail if axis is ever dynamic. Also modifying graph structure (to remove input from an op) during op import isn't exactly a clean design...

Here's an example TF node in graph, note the last input:
```
node {
  name: "output"
  op: "ConcatV2"
  input: "Variable/read"
  input: "Variable_1/read"
  input: "Variable_2/read"
  input: "Variable_3/read"
  input: "output/axis"
  attr {
    key: "N"
    value {
      i: 4
    }
  }
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
}
```

**Comment by shyrma** [comment]
added!
