### ISSUE TITLE
Multiple Channel and Sizes of Image

### ISSUE THREAD

**Issue by titubeta** [deeplearning4j/deeplearning4j#829]
Currently, we have to provide whether the image has 1 (grayscale) channel or 3 (RGB); however we can have both grayscale and RGB images together. In such case it will be useful to have the facility to use both the options automatically, depending upon the image we are reading.

Also the size of different images can also be variable for e.g. in CNN, therefore we should not restrict the user provide a fix size for all the images.

**Comment by agibsonccc** [comment]
The very premise of machine learning is everything being the same dimensions. We would instead have to pad with < channels with zeros or something else ;/. I agree that there needs to be a way of detecting that.
