### ISSUE TITLE
DL4J/SameDiff: Map new LSTM op

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8299]
After the new LSTM ops have been implemented, we need to make them available in DL4J (with MKL-DNN support) and SameDiff.

https://github.com/eclipse/deeplearning4j/issues/8070

**Comment by raver119** [comment]
Keep in mind, cuDNN support is still missing at SameDiff level.

**Comment by AlexDBlack** [comment]
Blocked on: https://github.com/eclipse/deeplearning4j/issues/8331

**Comment by AlexDBlack** [comment]
Recently added. Backprop Java mapping is marked here: https://github.com/eclipse/deeplearning4j/issues/8812#issuecomment-613223463
