### ISSUE TITLE
ND4S Build issue

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8302]
Seen on current Konduit master (not sure if present on eclipse master also)
https://gist.github.com/AlexDBlack/bdb0555c3d48ef14e6950ea27891471c

**Comment by raver119** [comment]
Hm, I've thought it was fixed by Alexander earlier. Maybe fix was applied in non merged branch, thus should be fixed in master now?

With best regards,
raver119
19 окт. 2019 г., 13:48 +0300, Alex Black <notifications@github.com>, писал:

**Comment by raver119** [comment]
Alexander applied one more fix. Should be ok now.

With best regards,
raver119
19 окт. 2019 г., 13:48 +0300, Alex Black <notifications@github.com>, писал:

**Comment by AlexDBlack** [comment]
Confirmed fixed, thanks.
