### ISSUE TITLE
SIGSEV on Raspberry PI + Raspbian 10 + Deeplearning4j

### ISSUE THREAD

**Issue by ticofab** [deeplearning4j/deeplearning4j#8322]
* Raspberry PI 4 / 4GB + Raspbian 10
* JDK 11
* Deeplearning4j 1.0.0-beta4

When trying to train a model on a Raspberry PI + Raspbian 10, a fatal error occurs. I already opened this issue in the AdoptOpenJDK repo as I am unsure where it comes from. 

https://github.com/AdoptOpenJDK/openjdk-build/issues/1355

Apologies for the double posting, happy to close one as soon as I have more information.

**Comment by saudet** [comment]
Thanks for the heads-up! It does look like an issue in OpenJDK though.

**Comment by saudet** [comment]
BTW, OpenJDK doesn't support ARM all that well, yet, anyway.
You'll have better luck with others like Oracle JDK, Amazon Corretto, or Liberica:
https://www.oracle.com/technetwork/java/javase/downloads/jdk8-arm-downloads-2187472.html
https://aws.amazon.com/corretto/
https://bell-sw.com/

**Comment by ticofab** [comment]
I would like to try again soon with the latest version. Will update this issue accordingly.

**Comment by ticofab** [comment]
I tried again and the issue I reported seems to have gone! 🎉
Unfortunately I stumbled upon another issue, which seems simpler to fix:

```
Caused by: java.lang.UnsatisfiedLinkError: /home/pi/.javacpp/cache/nd4j-native-1.0.0-beta6-linux-armhf.jar/org/nd4j/nativeblas/linux-armhf/libjnind4jcpu.so: /home/pi/.javacpp/cache/opencv-4.1.2-1.5.2-linux-armhf.jar/org/bytedeco/opencv/linux-armhf/libgomp.so.1: version `GOMP_4.0' not found (required by /home/pi/.javacpp/cache/nd4j-native-1.0.0-beta6-linux-armhf.jar/org/nd4j/nativeblas/linux-armhf/libnd4jcpu.so)
```

I will close this issue and open another one.
