### ISSUE TITLE
InvalidProtocolBufferException while reading array from onnx model

### ISSUE THREAD

**Issue by ghost** [deeplearning4j/deeplearning4j#8323]
#### Issue Description

The onnx related classes inside nd4j-api jar cannot read onnx model completely. Below are the commands/codes to generate readable data from onnx model.

#### (1) python using onnx: sample is from https://github.com/onnx/keras-onnx/blob/master/README.md
```
from keras.applications.resnet50 import ResNet50
import keras2onnx
import onnx

model = ResNet50(include_top=True, weights='imagenet')
onnx_model = keras2onnx.convert_keras(model, model.name)
onnx_model_file = 'ResNet50_model.onnx'
onnx.save_model(onnx_model, onnx_model_file)
with open('ResNet50_model.json', 'w') as f:
    print(onnx_model, file=f)
```
expected output from `ResNet50_model.json` (each float data in kernel is readable):
```
  initializer {
    dims: 64
    dims: 3
    dims: 7
    dims: 7
    data_type: 1
    float_data: 0.028252627700567245
    float_data: 0.018187232315540314
    ...
    float_data: -0.003368888981640339
    float_data: 0.001299845753237605
    name: "conv1/kernel:0"
  }
```

#### (2)  java using nd4j: array read by GraphProto in nd4j-api-1.0.0-beta5.jar
```
InputStream inputStream =
    new FileInputStream(new File("ResNet50_model.onnx"));
onnx.Onnx.GraphProto model =
    onnx.Onnx.GraphProto.parseFrom(inputStream);
File outputFile = new File("ResNet50_nd4j_beta5_parsed.txt");
String outputString = 
    org.nd4j.shade.protobuf.TextFormat.printToString(model.getUnknownFields());
FileUtils.writeStringToFile(
    outputFile, outputString, Charset.defaultCharset());

```

actual output from `ResNet50_nd4j_beta5_parsed.txt` (no float values for kernel being printed, instead, the parser throws InvalidProtocolBufferException and print unreadable data)
```
  5: {
    1: 64
    1: 3
    1: 7
    1: 7
    2: 1
    4: "\016r\347<d\375\224<\..."
    8: "conv1/kernel:0"
  }
```

#### (3)  java using nd4j: array read by nd4j OnnxGraphMapper in nd4j-api-1.0.0-beta5.jar
```
File onnxInputFile = new File("ResNet50_model.onnx");
File dumpOutputFile = new File("ResNet50_model_mapper_dump.txt");
org.nd4j.imports.graphmapper.onnx.OnnxGraphMapper mapper =
    new org.nd4j.imports.graphmapper.onnx.OnnxGraphMapper();
mapper.dumpBinaryProtoAsText(onnxInputFile, dumpOutputFile);
```

output from `ResNet50_model_mapper_dump.txt` (no any kernel data being printed out)

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j 1.0.0-beta5
* Platform information MacOSX Catalina

#### Additional Information

Where applicable, please also provide:
* pom.xml file or similar (also in a Gist):
```
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native-platform</artifactId>
            <version>1.0.0-beta5</version>
        </dependency>
```

**Comment by AlexDBlack** [comment]
Thanks for the report. But ONNX support is unfortunately not ready for general use (it's still in early development at this point).
TensorFlow import on the other hand is very well tested and supported including in beta 5.
