### ISSUE TITLE
DL4J: failed test ValidateMKLDNN

### ISSUE THREAD

**Issue by alexanderst** [deeplearning4j/deeplearning4j#8325]
Detected test failure in master for ValidateMKLDNN (Either validateBatchNorm or validateConvSubsampling are failing depending on environment):

java.lang.AssertionError: MAX, mb=3, cm=Same, kernel=[2, 2], stride=[1, 1] - Gradients are not equal: 0_W - highest relative error = 1.0 > max relative error = 1.0E-5

### Output below is from Window 10 machine, libnd4j was built with -a avx2 -h mkldnn.

https://gist.github.com/alexanderst/8fd93e83b72143ea2b9020c522657574

**Comment by AlexDBlack** [comment]
For the batch norm failures, very likely the same issue as this: https://github.com/eclipse/deeplearning4j/issues/8335
