### ISSUE TITLE
lstmLayer op: Add backprop implementation

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8331]
lstmLayer op was recently added here: https://github.com/KonduitAI/deeplearning4j/pull/4

We need backprop for this op (i.e., lstmLayer_bp), as well as MKLDNN support.

**Comment by raver119** [comment]
сс @shyrma

**Comment by AlexDBlack** [comment]
https://github.com/KonduitAI/deeplearning4j/pull/370
