### ISSUE TITLE
libnd4j: strided_slice_bp bug

### ISSUE THREAD

**Issue by zdl010** [deeplearning4j/deeplearning4j#8342]
Please indicate relevant versions, including, if relevant:

* Deeplearning4j version :1.0.0-beta5
* Platform information ：win10

public class LN4 {

	public static void main(String[] args) {

		

		SameDiff sd = SameDiff.create();

		SDVariable input = sd.var("input", DataType.FLOAT, 1, 2);

		SDVariable label = sd.var("label", DataType.FLOAT, 1, 2);

		INDArray inputArr = Nd4j.linspace(2, 3, 2).reshape(new int[] { 1,2 });
		INDArray labelArr = Nd4j.linspace(1, 4, 2).reshape(new int[] { 1,2 });
		
		
		SDVariable a= input.get(SDIndex.all(),SDIndex.point(0));
		SDVariable b= input.get(SDIndex.all(),SDIndex.point(1));

		SDVariable c=sd.stack("stack", 1, a,b);
	
		SDVariable m= sd.math().pow(c.sub(label), 2) ;
		sd.setLossVariables(m);
		
		System.out.println(sd.summary());
		
		for(int i=0;i<5;i++){
			sd.associateArrayWithVariable(inputArr, input);
			sd.associateArrayWithVariable(labelArr, label);
			sd.execBackwards(null,Operation.INFERENCE);
			System.out.println(input.getGradient().getArr());
			System.out.println(c.getGradient().getArr());
			System.out.println("==============");
			sd.clearPlaceholders(true);
	        sd.clearOpInputs();
		}
	}

}

Result：

[[         0,         0]]
[[    2.0000,   -2.0000]]
==============
[[    2.0000,    2.0000]]
[[    2.0000,   -2.0000]]
==============
[[    2.0000,    2.0000]]
[[    2.0000,   -2.0000]]
==============
[[         0,         0]]
[[    2.0000,   -2.0000]]
==============
[[   -2.0000,   -2.0000]]
[[    2.0000,   -2.0000]]
==============

**Comment by zdl010** [comment]
@AlexDBlack

**Comment by zdl010** [comment]
@AlexDBlack The differential value of c and input should be the same！

**Comment by zdl010** [comment]
@AlexDBlack Do you have time to look at this issue？

**Comment by AlexDBlack** [comment]
Thanks for reporting.

This is a bug in strided slice backprop - reproducible with the following test case:
https://gist.github.com/AlexDBlack/a2e9f87e46dc20dbc5eadcab39a8a993

I have checked the array shapes and iargs, that looks reasonable to me, so it is likely a bug in the implementation.

**Comment by zdl010** [comment]
@AlexDBlack I want to implement BPTT with samediff, which will slice the input in time steps and then stack it into a new tensor to calculate the gradient. Can I calculate the gradient of loss to the input?

**Comment by AlexDBlack** [comment]
@longzhendong on the current master (and snapshots, as soon as they are back up) you could use SameDiff.calculateGradients method and specify that you want the input gradient returned.

Another way to implement TBPTT would be to have placeholders for both the initial RNN state and the normal input... split it externally, using INDArray.get instead of internally using SDVariable.get.
Your outputs are the activations and the RNN last time step (which you can store to feed in as placeholders for the next step)

**Comment by AlexDBlack** [comment]
Confirmed fixed and merged to eclipse master also
Thanks for reporting @longzhendong, and for the fix @shugeo
