### ISSUE TITLE
Can't load keras model (Unsupported keras layer type DenseFeatures)

### ISSUE THREAD

**Issue by 54uso** [deeplearning4j/deeplearning4j#8344]
#### Issue Description
I'm trying to import keras model， but get the error:

org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: **Unsupported keras layer type DenseFeatures**

#### Version Information

* Deeplearning4j version 1.0.0-beta5
* Linux x86_64
* no CUDA

**Comment by AlexDBlack** [comment]
Can you provide model details - such as the model file, and the code used to produce it?
What Keras version are you using?

**Comment by 54uso** [comment]
[hdf5.zip](https://github.com/eclipse/deeplearning4j/files/3802574/hdf5.zip)
#### used tensorflow to produce it
```python
       feature_layer = tf.keras.layers.DenseFeatures(feature_columns)
       model = tf.keras.Sequential([
            feature_layer,
            layers.Dense(1, activation='sigmoid')
        ])
        model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
```
#### Version Information
python 3.7
tensorflow 2.0.0
keras 2.3.1

**Comment by AlexDBlack** [comment]
Thanks for reporting this. Looks like tf.keras has some format differences to the "standard"/non-TF keras saved models.
I'll close this in favor of this general issue, keep an eye on it for progress: https://github.com/eclipse/deeplearning4j/issues/8348
