### ISSUE TITLE
Unable to compile rl4j

### ISSUE THREAD

**Issue by varunembar** [deeplearning4j/deeplearning4j#8346]
#### Issue Description
Build rl4j fails to compile with the following error
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project rl4j-core: Compilation failure: Compilation failure

#### Version Information

Please indicate relevant versions, including, if relevant:

deeplearning4j-1.0.0-SNAPSHOT
On linux
No CUDA

#### Additional Information
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project rl4j-core: Compilation failure: Compilation failure:
[ERROR] /scratch/vembar/strucutre_learning/deeprl/deeplearning4j/rl4j/rl4j-core/src/test/java/org/deeplearning4j/rl4j/support/MockMDP.java:[31,48] constructor DiscreteSpace in class org.deeplearning4j.rl4j.space.DiscreteSpace cannot be applied to given types;
[ERROR]   required: int
[ERROR]   found: int,org.nd4j.linalg.api.rng.Random
[ERROR]   reason: actual and formal argument lists differ in length
[ERROR] /scratch/vembar/strucutre_learning/deeprl/deeplearning4j/rl4j/rl4j-core/src/test/java/org/deeplearning4j/rl4j/support/MockMDP.java:[39,51] constructor DiscreteSpace in class org.deeplearning4j.rl4j.space.DiscreteSpace cannot be applied to given types;
[ERROR]   required: int
[ERROR]   found: int,org.nd4j.linalg.api.rng.Random
[ERROR]   reason: actual and formal argument lists differ in length

**Comment by AlexDBlack** [comment]
Are you sure you are up to date with the current eclipse master?
I just tried a build and test run on rl4j, and both are fine

**Comment by AlexDBlack** [comment]
Hypothetically outdated snapshots with the latest eclipse master could do this also.
Unfortunately it looks like not all snapshots are being updated at present - so until that fixed - if you're building, you'll need to build the whole stack (not just some modules).

**Comment by varunembar** [comment]
I was following the instructions here https://gist.github.com/anis016/0f9c759e57dd641cd18e67516475dbed.
Turns out I had built the following modules libnd4j, nd4j, DataVec, deeplearning4, but had not built gym-java-client, arbiter.

It works fine now.
