### ISSUE TITLE
pydl4j: use mvnw if user doesn't have docker or mvn

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/deeplearning4j#8353]
`konduit-serving` makes effective use of `mvnw` to make it easy for python users to install dependencies. we should leverage the same for `pydl4j`, and later on use `pydl4j` itself to manage all upstream konduit dependencies for Python users.

**Comment by AlexDBlack** [comment]
Note that if we use it, mvnw scripts/jars can't go in the eclipse/deeplearning4j repo itself though, due to Eclipse's limitations on 3rd party content. A script to download it might work, however.

**Comment by maxpumperla** [comment]
thanks, very good reminder. not a problem though
