### ISSUE TITLE
Any news for OpenCL support for AMD and mobile gpus ?

### ISSUE THREAD

**Issue by eix128** [deeplearning4j/deeplearning4j#8361]
Hi , when can we use dl4j with opencl support ?
any news for that ?
which version of dl4j will support amd and embedded gpus ?
With robovm support and ios also metal 2 .

if you make the interface , i can help you on apple ( ios and osx ) side 
https://github.com/dehesa/Metal
for bulk multiplication etc...

and opencl side i try my best.
But need interface what to do.
For big bulk calculations.

**Comment by AlexDBlack** [comment]
OpenCL support won't be added any time soon, it would be literally thousands of hours of work to implement.
We are looking at other options that could provide AMD GPU support amongst other things (LLVM and Intel One API / data parallel C) but have nothing to announce at this time.

CoreML (which uses Metal internally) is on the roadmap for 2020, but will still be a very large task.

Integrated GPUs - Intel MKLDNN (now DNNL as of version 1.1) has support for Intel integrated graphics - but we haven't tested it. In theory we should get that "for free"
https://github.com/intel/mkl-dnn
Upgrading to MKLDNN/DNNL 1.1 is already planned, keep an eye on this issue: https://github.com/eclipse/deeplearning4j/issues/8316

**Comment by s-bernard** [comment]
@AlexDBlack Have you consider porting the CUDA code to [HIP](https://github.com/ROCm-Developer-Tools/HIP)?

It *shouldn't* be too time consuming with the HIPIFY tools (which can automatically convert source from CUDA to HIP) and the result source code could be compiled to run on both NVIDIA or AMD GPUs.

**Comment by AlexDBlack** [comment]
@s-bernard We have looked at a few of these options a while back.
Given the size of our codebase, our expectation is that such tools will never work quite as well as advertised - i.e., will still need manual post-processing. And even if they do work (in terms of providing correct output), it's unlikely they will be optimized as well as we can do so manually.

There's a _lot_ more to adding AMD support than merely running CUDA code through a converter (java side, CI, any changes to memory management, not to mention a ton of QA/testing).

All that said, still want to look at AMD support and looking at it in 2020 is a possibility. But we haven't made a commitment to do so yet.

**Comment by saudet** [comment]
@AlexDBlack BTW, Intel oneAPI also offers something similar these days:
https://software.intel.com/en-us/oneapi/dpc-compiler

**Comment by AlexDBlack** [comment]
Yep, we're aware of that OneAPI has a similar CUDA code conversion tool.
We haven't evaluated OneAPI in depth yet, but it's an option worth considering. to expand our hardware support

**Comment by s-bernard** [comment]
Thanks a lot @AlexDBlack for your detailed answers. I hope I don't bother you with my questions.

I've recently come across [TornadoVM](https://github.com/beehive-lab/TornadoVM), a *plug-in to OpenJDK and GraalVM that allows programmers to automatically run Java programs on heterogeneous hardware* aka CPUs, GPUs, and FPGAs.

Have you heard about it? What do you think?

**Comment by raver119** [comment]
All these simplified tools are great if all you need is element-wise operations. Once you need anything slightly more complex, anything  that can’t be expressed as elementary operation along some dimension, or require platform-specific algorithms/tweaks  - you have to get back to old good C.

**Comment by cyberbeat** [comment]
Another possibility: SYCL
https://github.com/illuhad/hipSYCL

**Comment by agibsonccc** [comment]
@cyberbeat  @quickwritereader  is experimenting with hip to see if the tooling there is any good. @saudet  is also experimenting with TVM support which would allow at least inference.
