### ISSUE TITLE
apparent memory leak in nd4j/dl4j 

### ISSUE THREAD

**Issue by stubbi59** [deeplearning4j/deeplearning4j#8365]
I am running a "demo" application for GAN networks, and this keeps failing with Out Of memry error

the app is "io.skymind.example.App", it is possible that the application is plain wrong, but this also looks like a memory reclaim/GC issue.

the run file is what I use to run the application, the pom.xml and one log file are also attached.

the "run" file is used to modify memory parameters for this current run of the program.
I have tried 2-4gb "Xms", 2-6GB for "Xmx" and maxbytes 6-10GB ( in the run file)

see attached files. 

please note, the extensions are wrong for run and pol.xml

[pom.xml.txt](https://github.com/eclipse/deeplearning4j/files/3818936/pom.xml.txt)
[run.txt](https://github.com/eclipse/deeplearning4j/files/3818937/run.txt)

[dl4j-memory-crash-dump-1572786838992_32.txt](https://github.com/eclipse/deeplearning4j/files/3818932/dl4j-memory-crash-dump-1572786838992_32.txt)

**Comment by raver119** [comment]
Show your source code please

**Comment by stubbi59** [comment]
not my code, this is something we found. :)

[dl4j-gans-master.zip](https://github.com/eclipse/deeplearning4j/files/3819249/dl4j-gans-master.zip)

**Comment by stubbi59** [comment]
closed by mistake ..

**Comment by raver119** [comment]
Apparently, there's no leak. 

1) According to the source code you've provided - that's pretty typical conv/deconv model. They are implemented in C++, not in java.
2) OOM message you're referring to is JVM OOM message, caused by insufficient heap size. Increase Xmx.
