### ISSUE TITLE
Are sparse matrix or model pruning available in the latest release? 

### ISSUE THREAD

**Issue by zhangy10** [deeplearning4j/deeplearning4j#8366]
I am just wondering whether the sparse matrix for the INDArray is available in the beta5 release? And does DL4J have any APIs for model pruning?

Actually, I am trying to apply some of model pruning approaches to a trained model in order to speed up the model inference or make it smaller, but I am not sure whether the latest version can support it. 

If not, do you have any advice to manage an INDArray to be sparse in the version?

One basic idea for model pruning is to remove some cells from an INDArray or update some cells as 0. So, is that possible to physically remove some units from an INDArray? And if just updating some units as 0 to be sparse, will the memory size of an INDArray be smaller?

Thanks for that.

**Comment by AlexDBlack** [comment]
Unfortunately no, sparse arrays are not available in the current version of ND4J/DL4J.
Sparse arrays are on the roadmap, and we expect to add it some time in 2020.

As for model pruning - nothing built in unfortunately.
You can of course set some weights to zero, but you won't get a size/performance benefit from doing so - the same operations and matrix multiplications will still happen internally (with the same number of actual floating point operations). So the only benefit from that you'll get is maybe a regularization effect, and maybe reduced saved model size (we use zip format for models in DL4J -> lots of zeros -> smaller zip file). No difference in memory use though once loaded.

**Comment by zhangy10** [comment]
@AlexDBlack All right, thanks for that. And hope the function can be added soon!

**Comment by seinecle** [comment]
Any ETA on the sparse matrix and vectors? Already landed maybe? Thx!

**Comment by agibsonccc** [comment]
@seinecle  there really  hasn't been enough demand and we had other priorities surface. If you'd like to help contribute to the finished sparse matrices support we'd be happy to support it. We have parts of it done, but removed most of the interfaces to it since it wasn't polished yet.
