### ISSUE TITLE
No output shapes for adjust_contrast, bitcast, draw_bounding_boxes operations (libnd4j)

### ISSUE THREAD

**Issue by alexanderst** [deeplearning4j/deeplearning4j#8374]
Error message:
Failed to calculate output shapes for op adjust_contrast_v2 (adjust_contrast) - no shapes were returned by calculateOutputShape()

Failing test case:
```
@Test
    public void testAdjustContrastShape(){
        DynamicCustomOp op = DynamicCustomOp.builder("adjust_contrast_v2")
                .addInputs(Nd4j.create(DataType.FLOAT, 256, 256,3), Nd4j.scalar(0.5f))
                .build();
        List<LongShapeDescriptor> lsd = op.calculateOutputShape();
        assertEquals(1, lsd.size());
        assertArrayEquals(new long[]{256, 256, 3}, lsd.get(0).getShape());
    }
```

**Comment by alexanderst** [comment]
The same issue for BitCast operation.

**Comment by alexanderst** [comment]
The same issue for DrawBoundingBoxes operation.

**Comment by AlexDBlack** [comment]
@alexanderst bitcast does have a shape function - can you add some unit tests (expected/actual like you did for adjust contrast)?
draw_bounding_boxes doesn't have a shape function by the looks of it.

**Comment by alexanderst** [comment]
Added in branch asto_samediff_coverage
https://github.com/KonduitAI/deeplearning4j/blob/761bb0cadbd099e2773009b1174cf42bae898fbe/nd4j/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/custom/CustomOpsTests.java#L880

**Comment by raver119** [comment]
@shugeo adjust_contrast_v2 should accept scale factor as input argument rather than T. Please fix it.

**Comment by raver119** [comment]
@alexanderst can you please show me test for bitcast failure? I see test in Java, and it passes.

**Comment by raver119** [comment]
@alexanderst DrawBoundingBoxes op - please show me corresponding Python code. Your test makes no sense to me:

>  assertArrayEquals(new long[]{1,10}, lsd.get(0).getShape());

You expect output shape to be [1, 10], but TF doc clearly says that output has the same dimensionality as input.

**Comment by raver119** [comment]
adjust_contrast_v2 issue fixed in my branch. Other two issues are not bugs.
