### ISSUE TITLE
Input that is not a matrix; expected matrix (rank 2), got rank 1 array

### ISSUE THREAD

**Issue by jahu** [deeplearning4j/deeplearning4j#8376]
#### Issue description
Cannot run keras model due to an error:

`Caused by: org.deeplearning4j.exception.DL4JInvalidInputException: Input that is not a matrix; expected matrix (rank 2), got rank 1 array with shape [40]. Missing preprocessor or wrong input type? (layer name: dense, layer index: 0, layer type: DenseLayer)
`

Model had been implemented in python, exported and imported with following code:

```
        MultiLayerNetwork model = KerasModelImport.
                importKerasSequentialModelAndWeights("model");
```

Model seems to be loaded properly as `model.summary()` returns:

```
LayerName (LayerType)      nIn,nOut   TotalParams   ParamsShape        
=======================================================================
dense (DenseLayer)         40,40      1,640         W:{40,40}, b:{1,40}
dense_1 (DenseLayer)       40,24      984           W:{40,24}, b:{1,24}
dense_2 (DenseLayer)       24,5       125           W:{24,5}, b:{1,5}  
dense_2_loss (LossLayer)   -,-        0             -                  
-----------------------------------------------------------------------
            Total Parameters:  2,749
        Trainable Parameters:  2,749
           Frozen Parameters:  0
```

It seems like even though my model expects 1d array of 40 features the deeplearning4j library forces input to be 2d. Code I am using for testing the model:

```
for (int i=0; i<inputs; i++)
    features.putScalar(new int[] {i}, Math.random() < 0.5 ? 0 : 1);

System.out.println(model.output(features));
```

Please advise how can I overcome this issue.

#### Version Information
    compile group: 'org.deeplearning4j', name: 'deeplearning4j-core', version: '1.0.0-beta5'
    compile group: 'org.deeplearning4j', name: 'deeplearning4j-modelimport', version: '1.0.0-beta5'
    compile group: 'org.nd4j', name: 'nd4j-native-platform', version: '1.0.0-beta5'

OS: Windows x64 & Ubuntu x64, no CUDA

**Comment by AlexDBlack** [comment]
DL4J (MLP) models always use 2d input, with a leading minibatch dimension - shape `[minibatch, nIn]`
For a single example, pass in an array with shape `[1, nIn]`
