### ISSUE TITLE
libnd4j/nd4j/dl4j Jetson builds

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#8378]
As discussed with @agibsonccc: Let's set up build pipeline for Jetson devices family. Basically ARM-targeted cross-compilation + 1 cc per device.

**Comment by raver119** [comment]
cc @sshepel @saudet

**Comment by saudet** [comment]
BTW, Travis CI now supports ARM64 and the hardware apparently comes from here:
https://www.packet.com/cloud/servers/

**Comment by AlexDBlack** [comment]
Not sure if useful here, but Huawei Cloud also has ARM servers.
https://www.huaweicloud.com/en-us/product/ecs.html
"Kunpeng General Computing-plus KC1 ECS"
https://en.wikichip.org/wiki/hisilicon/kunpeng/920-6426

**Comment by kwatters** [comment]
If I remember, from getting nd4j working with cuda on the jetson nano, it only supported Cuda 10.0 ... Also, there was no support for Intel MKL...  I'm not sure if nVidia has updated support for the nano to cuda 10.1 yet...   (jetson was cuda CC 5.3 ) ...   my jetson nano has been collecting dust for the past few months... maybe it's time to dig it out again..  (I need to build against 1.0.0.-beta5 anyway for myrobotlab)

**Comment by saudet** [comment]
Yeah, CUDA on ARM is a mess, but they are supposed to fix this soon: https://nvidianews.nvidia.com/news/nvidia-brings-cuda-to-arm-enabling-new-path-to-exascale-supercomputing
Maybe we should wait for that to happen...

**Comment by kwatters** [comment]
yeah, last i checked, latest version of jetpack for the jetson nano was 4.2 something and that included only cuda 10.0 ... so yeah, i agree, we should wait for a new release of cuda that hopefully is consistent across all platforms ( arm and x86 ) .. at that point it'll be easier to maintain.

**Comment by sshepel** [comment]
Jetson build pipeline has been added to CI, artifacts (snapshots) can be found at maven central.
