### ISSUE TITLE
DL4J Keras Import: Seamless/automatic lambda support

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8381]
With SameDiff and TF import, we should be able to find a way to automatically map lambda layers to DL4J SameDiff layers, without any user intervention.

**Comment by agibsonccc** [comment]
Closing this, it's not really relevant. Lambdas can take parameters and have too many edge cases. Documentation wise, keras pushes custom classes. We'll instead focus on custom layers support working really well and just teaching people how to code lambda layers.
