### ISSUE TITLE
MKL use in ND4J

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#8394]
@saudet what should we do to make sure we use MKL instead of OpenBLAS where it's possible?

And, actually, what MKL supports these days? Linux x86/64, Windows, macOS? Or anything else as well?

**Comment by saudet** [comment]
Linux, Mac, Windows, yes, that hasn't changed. You'll need to add dependencies on [those artifacts](https://github.com/bytedeco/javacpp-presets/tree/master/mkl#the-pomxml-build-file) and replace references of "mklml" to "mkl_rt" in the code that you've already removed, so you'll need to add that back if you want that.

**Comment by raver119** [comment]
Awesome, thank you.

Ye, I'll get those back today. Just tried to fix snapshots ASAP.

With best regards,
raver119
15 нояб. 2019 г., 04:02 +0300, Samuel Audet <notifications@github.com>, писал:

**Comment by saudet** [comment]
But MKL is like 200 MB per platform, so maybe we can let everything use OpenBLAS by default, and see how that goes? It would probably work smoother with Eclipse policies too...

**Comment by raver119** [comment]
Ugh... 200MB per platform means 600MB for nd4j-native-platform... That will make uber java what, 1.5GB total? :(

@AlexDBlack what's your thoughts about this?

**Comment by saudet** [comment]
And isn't playing nice with AMD either...

**Comment by AlexDBlack** [comment]
200MB per platform is a sizable cost to pay, especially for a default.
And AMD shenanigans are another reason to not have it as the default...

So I'm definitely leaning towards openblas default, and making it easy for users to switch to MKL.
Which is essentially still "install MKL locally" or "add MKL javacpp preset to project", right? (and optionally exclude openblas preset)

At which point only question is whether we bother doing some sort of logging message (like we do for no cuDNN, but shorter)

**Comment by raver119** [comment]
Another thought. With our use of MKL-DNN, most of relevant DL4J layers are already covered with MKL-DNN rather than gemm. Last one is probably trivial Dense layer, aka XWplusB. So, DL4J users won't even use OpenBLAS/MKL in any way - MKL-DNN uses its personal sgemm for these ops as i remember.
