### ISSUE TITLE
Arguments list mismatch for zeros_like op between libnd4j and TF

### ISSUE THREAD

**Issue by alexanderst** [deeplearning4j/deeplearning4j#8398]
zeros_like in TF has dtype argument, needed to add libnd4j implementation and nd4j wrapper.

tf.zeros_like(
    input,
    dtype=None,
    name=None
)

**Comment by raver119** [comment]
as discussed with @AlexDBlack in slack - we're going to address this after beta6 release, since there's more than one op that should get proper dtype configuration options.

**Comment by raver119** [comment]
Fixed
