### ISSUE TITLE
crop_and_resize operation - output shape mismatch between TF and libnd4j

### ISSUE THREAD

**Issue by alexanderst** [deeplearning4j/deeplearning4j#8399]
Output shape mismatch detected - TF [2, 2, 1, 1] vs SD: [1, 2, 1, 1]. ND4J test is below.

 @Test
    public void testCropAndResize() {
        INDArray image = Nd4j.createUninitialized(DataType.FLOAT, 1, 2, 2, 1);
        INDArray boxes = Nd4j.createFromArray(new float[]{1,2,3,4}).reshape(1,4);
        INDArray box_indices = Nd4j.createFromArray(new int[]{1});
        INDArray crop_size = Nd4j.createFromArray(new int[]{1,2}).reshape(1,2);

        //Output shape mismatch - TF [2, 2, 1, 1] vs SD: [1, 2, 1, 1]
        INDArray output = Nd4j.create(DataType.FLOAT, 2,2,1,1);

        Nd4j.exec(new CropAndResize(image, boxes, box_indices, crop_size, CropAndResize.Method.BILINEAR, 0.5,
                 output));
    }

**Comment by shugeo** [comment]
>>> import tensorflow as tf
>>> x = tf.constant((1,2,3,4), shape=( 1, 2, 2, 1), dtype=tf.float32)
>>> boxes = tf.constant((1,2,3,4), shape=(1,4))
>>> boxes = tf.constant((1,2,3,4), shape=(1,4), dtype=tf.float32)
>>> indices= tf.constant((1,))
>>> cropSize= tf.constant((1,2))
>>> z = tf.image.crop_and_resize(x,boxes,indices, cropSize, 'bilinear')
z
<tf.Tensor 'CropAndResize_1:0' shape=(1, 1, 2, 1) dtype=float32>
cropSize should be 1D

**Comment by raver119** [comment]
Fixed and merged, Thanks to @shugeo
