### ISSUE TITLE
KerasModelImport problem

### ISSUE THREAD

**Issue by LuizFilipeAS** [deeplearning4j/deeplearning4j#8424]
Im having problems to import a keras model with dl4j and i cant find a solution, Im getting this errors and warnings:

log4j:WARN No appenders could be found for logger (org.nd4j.linalg.factory.Nd4jBackend).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.NoClassDefFoundError: org/nd4j/linalg/exception/ND4JOpProfilerException
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5856)
at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5766)
at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:202)
at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.readDataSet(Hdf5Archive.java:300)
at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.readDataSet(Hdf5Archive.java:114)
at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.importWeights(KerasModelUtils.java:286)
at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:150)
at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:58)
at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:322)
at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:223)
at teste.ImportConv1D.main(ImportConv1D.java:15)
Caused by: java.lang.ClassNotFoundException: org.nd4j.linalg.exception.ND4JOpProfilerException
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
... 13 more

#### Version Information
dl4j v 1.0.0-beta 5

**Comment by AlexDBlack** [comment]
Based on that stack trace, the problem (and warnings) your are hitting isn't related to Keras import, it's general dependency issues.

How are you managing your dependencies? Using Maven, Gradle, or SBT etc?
If so - can you post your pom.xml file (or equivalent for whatever build tool you are using)?

**Comment by LuizFilipeAS** [comment]
Using Maven.
There is my dependencies:
 <dependencies>
      <dependency>
          <groupId>junit</groupId>
          <artifactId>junit</artifactId>
          <version>4.11</version>
          <scope>test</scope>
      </dependency>
      <dependency>
          <groupId>org.nd4j</groupId>
          <artifactId>nd4j-native-platform</artifactId>
          <version>1.0.0-beta5</version>
      </dependency>
      <dependency>
          <groupId>org.deeplearning4j</groupId>
          <artifactId>deeplearning4j-core</artifactId>
          <version>1.0.0-beta5</version>
      </dependency>
      <dependency>
          <groupId>org.deeplearning4j</groupId>
          <artifactId>deeplearning4j-modelimport</artifactId>
          <version>1.0.0-beta5/version>
      </dependency>
      <dependency>
          <groupId>log4j</groupId>
          <artifactId>log4j</artifactId>
          <version>1.2.17</version>
      </dependency>
  </dependencies>

**Comment by AlexDBlack** [comment]
Please just post the full pom.xml
also what IDE (if any) are you using? Are you running through IDE or building an uber-jar/fat-jar and running that?

**Comment by LuizFilipeAS** [comment]
Im using IntelliJ IDEA.

https://gist.github.com/LuizFilipeAS/5ca1e26a9c91831a0e6cee00aa1e37e5


I dont know how i can put a preview of the code here....

**Comment by agibsonccc** [comment]
@LuizFilipeAS please use https://gist.github.com/ from now on. It's a fairly standard tool in the industry.

**Comment by LuizFilipeAS** [comment]
```
 
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>teste</groupId>
  <artifactId>CNN</artifactId>
  <version>1.0-SNAPSHOT</version>

  <name>CNN</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
  </properties>

  <dependencies>
      <dependency>
          <groupId>junit</groupId>
          <artifactId>junit</artifactId>
          <version>4.11</version>
          <scope>test</scope>
      </dependency>
      <dependency>
          <groupId>org.nd4j</groupId>
          <artifactId>nd4j-native-platform</artifactId>
          <version>1.0.0-beta5</version>
      </dependency>
      <dependency>
          <groupId>org.deeplearning4j</groupId>
          <artifactId>deeplearning4j-core</artifactId>
          <version>1.0.0-beta5</version>
      </dependency>
      <dependency>
          <groupId>org.deeplearning4j</groupId>
          <artifactId>deeplearning4j-modelimport</artifactId>
          <version>1.0.0-beta5/version>
      </dependency>
      <dependency>
          <groupId>log4j</groupId>
          <artifactId>log4j</artifactId>
          <version>1.2.17</version>
      </dependency>
  </dependencies>

  <build>
    <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
      <plugins>
        <!-- clean lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#clean_Lifecycle -->
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        <!-- default lifecycle, jar packaging: see https://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
        <!-- site lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#site_Lifecycle -->
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
```

**Comment by saudet** [comment]
@LuizFilipeAS Does this also happen on the command line with a command like `mvn clean install`? Or does it happen only within IntelliJ IDEA?

**Comment by AlexDBlack** [comment]
Yeah, I can't see any problems with those dependencies, they look OK.
My only guess here is yeah, some sort of IDE issue (try command line as mentioned, see also this: https://github.com/eclipse/deeplearning4j-examples/blob/master/standalone-sample-project/pom.xml#L99-L148 )
Or _maybe_ some sort of corrupted JAR during download.

That class should be available by default, given the dependencies you are using.

**Comment by LuizFilipeAS** [comment]
@saudet i found the error thanks to that command line. Thank you!
