### ISSUE TITLE
Implement Empty operation in libnd4j and nd4j

### ISSUE THREAD

**Issue by alexanderst** [deeplearning4j/deeplearning4j#8425]
Empty op constructor should have arguments:
- shape
- init - boolean
It should should operate identically to Nd4j.create vs. Nd4j.createUninitialized, depending on whether init arg is true/false.

**Comment by raver119** [comment]
there should be dtype argument as well.

and what init option does?

**Comment by raver119** [comment]
I mean: in case of empty array - there's no buffer - hence nothing to initialize

**Comment by AlexDBlack** [comment]
It's "numpy" empty, not ND4J "empty"

https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html

> It should should operate identically to Nd4j.create vs. Nd4j.createUninitialized, depending on whether init arg is true/false.

^ This is what we need.

We should probably call it something else to avoid confusion though, "Empty" op is what TF calls it

**Comment by AlexDBlack** [comment]
Or equivalent to fill op, but options are 0 vs. uninitialized
for uninitialized case, exec should be a no-op

Edit: and yes, it needs a dtype argument, for output datatype.

**Comment by raver119** [comment]
Implemented.
