### ISSUE TITLE
ResizeBillinear op returns results different from TF by values

### ISSUE THREAD

**Issue by alexanderst** [deeplearning4j/deeplearning4j#8428]
Test to reproduce in nd4j:

```@Test
    public void resizeBilinear() {
        INDArray in = Nd4j.createFromArray(new float[]{0.7788f,    0.8012f,    0.7244f,
        0.2309f,    0.7271f,    0.1804f,
        0.5056f,    0.8925f,    0.5461f,
        0.9234f,    0.0856f,    0.7938f,
        0.6591f,    0.5555f,    0.1596f,
       0.3087f,    0.1548f,    0.4695f,
       0.9939f,    0.6113f,    0.6765f,
       0.1800f,    0.6750f,    0.2246f,
       0.0509f,    0.4601f,    0.8284f,
       0.2354f,    0.9752f,    0.8361f,
       0.2585f,    0.4189f,    0.7028f,
       0.7679f,    0.5373f,    0.7234f,
       0.2690f,    0.0062f,    0.0327f,
        0.0644f,    0.8428f,    0.7494f,
       0.0755f,    0.6245f,    0.3491f,
       0.5793f,    0.5730f,    0.1822f,
        0.6420f,    0.9143f,    0.3019f,
       0.3574f,    0.1704f,    0.8395f,
        0.5468f,    0.0744f,    0.9011f,
        0.6574f,    0.4124f,    0.2445f,
        0.4248f,    0.5219f,    0.6952f,
       0.4900f,    0.2158f,    0.9549f,
       0.1386f,    0.1544f,    0.5365f,
       0.0134f,    0.4163f,    0.1456f,
       0.4109f,    0.2484f,    0.3330f,
      0.2974f,    0.6636f,    0.3808f,
       0.8664f,    0.1896f,    0.7530f,
       0.7215f,    0.6612f,    0.7270f,
       0.5704f,    0.2666f,    0.7453f,
       0.0444f,    0.3024f,    0.4850f,
       0.7982f,    0.0965f,    0.7843f,
       0.5075f,    0.0844f,    0.8370f,
       0.6103f,    0.4604f,    0.6087f,
       0.8594f,    0.4599f,    0.6714f,
       0.2744f,    0.1981f,    0.4143f,
       0.7821f,    0.3505f,    0.5040f,
       0.1180f,    0.8307f,    0.1817f,
       0.8442f,    0.5074f,    0.4471f,
       0.5105f,    0.6666f,    0.2576f,
       0.2341f,    0.6801f,    0.2652f,
       0.5394f,    0.4690f,    0.6146f,
       0.1210f,    0.2576f,    0.0769f,
       0.4643f,    0.1628f,    0.2026f,
       0.3774f,    0.0506f,    0.3462f,
       0.5720f,    0.0838f,    0.4228f,
      0.0588f,    0.5362f,    0.4756f,
       0.2530f,    0.1778f,    0.0751f,
       0.8977f,    0.3648f,    0.3065f,
       0.4739f,    0.7014f,    0.4473f,
       0.5171f,    0.1744f,    0.3487f}).reshape(2, 5, 5, 3);
        INDArray out = Nd4j.createUninitialized(2,9,9,3);
        ResizeBilinear op = new ResizeBilinear(in, out, 9, 9, false);
        val res = Nd4j.exec(op);
    }

**Comment by alexanderst** [comment]
Predictions mismatch:

TF: [[[[    0.7788,    0.8012,    0.7244], 
   [    0.5048,    0.7642,    0.4524], 
   [    0.2309,    0.7271,    0.1804], 
   [    0.3683,    0.8098,    0.3633], 
   [    0.5056,    0.8925,    0.5461], 
   [    0.7145,    0.4890,    0.6700], 
   [    0.9234,    0.0856,    0.7938], 
   [    0.7912,    0.3205,    0.4767], 
   [    0.6591,    0.5555,    0.1596]], 

  [[    0.5438,    0.4780,    0.5970], 
   [    0.5781,    0.5736,    0.5127], 
   [    0.6124,    0.6692,    0.4284], 
   [    0.4776,    0.7265,    0.4069], 
   [    0.3428,    0.7837,    0.3854], 
   [    0.4150,    0.5283,    0.5982], 
   [    0.4871,    0.2728,    0.8111], 
   [    0.4672,    0.5191,    0.6545], 
   [    0.4472,    0.7654,    0.4979]], 

  [[    0.3087,    0.1548,    0.4695], 
   [    0.6513,    0.3830,    0.5730], 
   [    0.9939,    0.6113,    0.6765], 
   [    0.5869,    0.6431,    0.4505], 
   [    0.1800,    0.6750,    0.2246], 
   [    0.1155,    0.5675,    0.5265], 
   [    0.0509,    0.4601,    0.8284], 
   [    0.1432,    0.7176,    0.8323], 
   [    0.2354,    0.9752,    0.8361]], 

  [[    0.2836,    0.2868,    0.5862], 
   [    0.5823,    0.4305,    0.6430], 
   [    0.8809,    0.5743,    0.6999], 
   [    0.5527,    0.4574,    0.4143], 
   [    0.2245,    0.3406,    0.1286], 
   [    0.1411,    0.4960,    0.4588], 
   [    0.0577,    0.6514,    0.7889], 
   [    0.1065,    0.7257,    0.6907], 
   [    0.1554,    0.7999,    0.5926]], 

  [[    0.2585,    0.4189,    0.7028], 
   [    0.5132,    0.4781,    0.7131], 
   [    0.7679,    0.5373,    0.7234], 
   [    0.5185,    0.2717,    0.3780], 
   [    0.2690,    0.0062,    0.0327], 
   [    0.1667,    0.4245,    0.3910], 
   [    0.0644,    0.8428,    0.7494], 
   [    0.0699,    0.7337,    0.5492], 
   [    0.0755,    0.6245,    0.3491]], 

  [[    0.4189,    0.4959,    0.4425], 
   [    0.5619,    0.6109,    0.4776], 
   [    0.7050,    0.7258,    0.5127], 
   [    0.5091,    0.4070,    0.4744], 
   [    0.3132,    0.0883,    0.4361], 
   [    0.3094,    0.2734,    0.6306], 
   [    0.3056,    0.4586,    0.8252], 
   [    0.3360,    0.4885,    0.5610], 
   [    0.3665,    0.5184,    0.2968]], 

  [[    0.5793,    0.5730,    0.1822], 
   [    0.6107,    0.7436,    0.2421], 
   [    0.6420,    0.9143,    0.3019], 
   [    0.4997,    0.5424,    0.5707], 
   [    0.3574,    0.1704,    0.8395], 
   [    0.4521,    0.1224,    0.8703], 
   [    0.5468,    0.0744,    0.9011], 
   [    0.6021,    0.2434,    0.5728], 
   [    0.6574,    0.4124,    0.2445]], 

  [[    0.5020,    0.5474,    0.4387], 
   [    0.5340,    0.5562,    0.5336], 
   [    0.5660,    0.5651,    0.6284], 
   [    0.4070,    0.3637,    0.6582], 
   [    0.2480,    0.1624,    0.6880], 
   [    0.2640,    0.2039,    0.6057], 
   [    0.2801,    0.2454,    0.5234], 
   [    0.4071,    0.2879,    0.4061], 
   [    0.5342,    0.3304,    0.2887]], 

  [[    0.4248,    0.5219,    0.6952], 
   [    0.4574,    0.3688,    0.8251], 
   [    0.4900,    0.2158,    0.9549], 
   [    0.3143,    0.1851,    0.7457], 
   [    0.1386,    0.1544,    0.5365], 
   [    0.0760,    0.2854,    0.3411], 
   [    0.0134,    0.4163,    0.1456], 
   [    0.2121,    0.3324,    0.2393], 
   [    0.4109,    0.2484,    0.3330]]], 


 [[[    0.2974,    0.6636,    0.3808], 
   [    0.5819,    0.4266,    0.5669], 
   [    0.8664,    0.1896,    0.7530], 
   [    0.7939,    0.4254,    0.7400], 
   [    0.7215,    0.6612,    0.7270], 
   [    0.6459,    0.4639,    0.7362], 
   [    0.5704,    0.2666,    0.7453], 
   [    0.3074,    0.2845,    0.6152], 
   [    0.0444,    0.3024,    0.4850]], 

  [[    0.5478,    0.3801,    0.5826], 
   [    0.6174,    0.2585,    0.6888], 
   [    0.6870,    0.1370,    0.7950], 
   [    0.6764,    0.3489,    0.7314], 
   [    0.6659,    0.5608,    0.6679], 
   [    0.6904,    0.4620,    0.6881], 
   [    0.7149,    0.3632,    0.7084], 
   [    0.4372,    0.3067,    0.5790], 
   [    0.1594,    0.2502,    0.4497]], 

  [[    0.7982,    0.0965,    0.7843], 
   [    0.6528,    0.0905,    0.8106], 
   [    0.5075,    0.0844,    0.8370], 
   [    0.5589,    0.2724,    0.7229], 
   [    0.6103,    0.4604,    0.6087], 
   [    0.7348,    0.4601,    0.6401], 
   [    0.8594,    0.4599,    0.6714], 
   [    0.5669,    0.3290,    0.5428], 
   [    0.2744,    0.1981,    0.4143]], 

  [[    0.7902,    0.2235,    0.6442], 
   [    0.5515,    0.3405,    0.5767], 
   [    0.3127,    0.4576,    0.5093], 
   [    0.5200,    0.4707,    0.5186], 
   [    0.7272,    0.4839,    0.5279], 
   [    0.7061,    0.5236,    0.4962], 
   [    0.6850,    0.5632,    0.4645], 
   [    0.4696,    0.5012,    0.4021], 
   [    0.2542,    0.4391,    0.3397]], 

  [[    0.7821,    0.3505,    0.5040], 
   [    0.4501,    0.5906,    0.3429], 
   [    0.1180,    0.8307,    0.1817], 
   [    0.4811,    0.6691,    0.3144], 
   [    0.8442,    0.5074,    0.4471], 
   [    0.6774,    0.5870,    0.3524], 
   [    0.5105,    0.6666,    0.2576], 
   [    0.3723,    0.6734,    0.2614], 
   [    0.2341,    0.6801,    0.2652]], 

  [[    0.6608,    0.4097,    0.5593], 
   [    0.3901,    0.4769,    0.3443], 
   [    0.1195,    0.5442,    0.1293], 
   [    0.3869,    0.4396,    0.2271], 
   [    0.6542,    0.3351,    0.3249], 
   [    0.5491,    0.3468,    0.3134], 
   [    0.4439,    0.3586,    0.3019], 
   [    0.4235,    0.3703,    0.3229], 
   [    0.4030,    0.3820,    0.3440]], 

  [[    0.5394,    0.4690,    0.6146], 
   [    0.3302,    0.3633,    0.3458], 
   [    0.1210,    0.2576,    0.0769], 
   [    0.2927,    0.2102,    0.1398], 
   [    0.4643,    0.1628,    0.2026], 
   [    0.4208,    0.1067,    0.2744], 
   [    0.3774,    0.0506,    0.3462], 
   [    0.4747,    0.0672,    0.3845], 
   [    0.5720,    0.0838,    0.4228]], 

  [[    0.2991,    0.5026,    0.5451], 
   [    0.2431,    0.3601,    0.3106], 
   [    0.1870,    0.2177,    0.0760], 
   [    0.4340,    0.2407,    0.1653], 
   [    0.6810,    0.2638,    0.2545], 
   [    0.5533,    0.3199,    0.3256], 
   [    0.4256,    0.3760,    0.3967], 
   [    0.4851,    0.2526,    0.3913], 
   [    0.5446,    0.1291,    0.3858]], 

  [[    0.0588,    0.5362,    0.4756], 
   [    0.1559,    0.3570,    0.2753], 
   [    0.2530,    0.1778,    0.0751], 
   [    0.5754,    0.2713,    0.1908], 
   [    0.8977,    0.3648,    0.3065], 
   [    0.6858,    0.5331,    0.3769], 
   [    0.4739,    0.7014,    0.4473], 
   [    0.4955,    0.4379,    0.3980], 
   [    0.5171,    0.1744,    0.3487]]]]
SD: [[[[    0.7788,    0.8012,    0.7244], 
   [    0.5048,    0.7642,    0.4524], 
   [    0.2309,    0.7271,    0.1804], 
   [    0.3683,    0.8098,    0.3633], 
   [    0.5056,    0.8925,    0.5461], 
   [    0.7145,    0.4890,    0.6700], 
   [    0.9234,    0.0856,    0.7938], 
   [    0.7912,    0.3205,    0.4767], 
   [    0.6591,    0.5555,    0.1596]], 

  [[    0.5438,    0.4780,    0.5970], 
   [    0.5781,    0.5736,    0.5127], 
   [    0.6124,    0.6692,    0.4284], 
   [    0.4776,    0.7265,    0.4069], 
   [    0.3428,    0.7837,    0.3854], 
   [    0.4150,    0.5283,    0.5982], 
   [    0.4871,    0.2728,    0.8111], 
   [    0.4672,    0.5191,    0.6545], 
   [    0.4472,    0.7654,    0.4979]], 

  [[    0.3087,    0.1548,    0.4695], 
   [    0.6513,    0.3830,    0.5730], 
   [    0.9939,    0.6113,    0.6765], 
   [    0.5869,    0.6431,    0.4505], 
   [    0.1800,    0.6750,    0.2246], 
   [    0.1155,    0.5675,    0.5265], 
   [    0.0509,    0.4601,    0.8284], 
   [    0.1432,    0.7176,    0.8323], 
   [    0.2354,    0.9752,    0.8361]], 

  [[    0.2836,    0.2868,    0.5862], 
   [    0.5823,    0.4305,    0.6430], 
   [    0.8809,    0.5743,    0.6999], 
   [    0.5527,    0.4574,    0.4143], 
   [    0.2245,    0.3406,    0.1286], 
   [    0.1411,    0.4960,    0.4588], 
   [    0.0577,    0.6514,    0.7889], 
   [    0.1065,    0.7257,    0.6907], 
   [    0.1554,    0.7999,    0.5926]], 

  [[    0.2585,    0.4189,    0.7028], 
   [    0.5132,    0.4781,    0.7131], 
   [    0.7679,    0.5373,    0.7234], 
   [    0.5185,    0.2717,    0.3780], 
   [    0.2690,    0.0062,    0.0327], 
   [    0.1667,    0.4245,    0.3910], 
   [    0.0644,    0.8428,    0.7494], 
   [    0.0699,    0.7337,    0.5492], 
   [    0.0755,    0.6245,    0.3491]], 

  [[    0.4189,    0.4959,    0.4425], 
   [    0.5619,    0.6109,    0.4776], 
   [    0.7050,    0.7258,    0.5127], 
   [    0.5091,    0.4070,    0.4744], 
   [    0.3132,    0.0883,    0.4361], 
   [    0.3094,    0.2734,    0.6306], 
   [    0.3056,    0.4586,    0.8252], 
   [    0.3360,    0.4885,    0.5610], 
   [    0.3665,    0.5184,    0.2968]], 

  [[    0.5394,    0.4690,    0.6146], 
   [    0.3302,    0.3633,    0.3458], 
   [    0.1210,    0.2576,    0.0769], 
   [    0.2927,    0.2102,    0.1398], 
   [    0.4643,    0.1628,    0.2026], 
   [    0.4208,    0.1067,    0.2744], 
   [    0.3774,    0.0506,    0.3462], 
   [    0.4747,    0.0672,    0.3845], 
   [    0.5720,    0.0838,    0.4228]], 

  [[    0.2991,    0.5026,    0.5451], 
   [    0.2431,    0.3601,    0.3106], 
   [    0.1870,    0.2177,    0.0760], 
   [    0.4340,    0.2407,    0.1653], 
   [    0.6810,    0.2638,    0.2545], 
   [    0.5533,    0.3199,    0.3256], 
   [    0.4256,    0.3760,    0.3967], 
   [    0.4851,    0.2526,    0.3913], 
   [    0.5446,    0.1291,    0.3858]], 

  [[    0.0588,    0.5362,    0.4756], 
   [    0.1559,    0.3570,    0.2753], 
   [    0.2530,    0.1778,    0.0751], 
   [    0.5754,    0.2713,    0.1908], 
   [    0.8977,    0.3648,    0.3065], 
   [    0.6858,    0.5331,    0.3769], 
   [    0.4739,    0.7014,    0.4473], 
   [    0.4955,    0.4379,    0.3980], 
   [    0.5171,    0.1744,    0.3487]]], 


 [[[    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000]], 

  [[    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000]], 

  [[    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000]], 

  [[    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,1.7347e-18]], 

  [[8.9812e-40,2.9843e-15,9.1785e-43], 
   [ 5.8943e12,9.1785e-43,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    0.5162], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000]], 

  [[    1.0000,    0.0719,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    0.0154], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000]], 

  [[    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000]], 

  [[    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    0.2283], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    1.0000], 
   [    1.0000,    1.0000,    0.4072], 
   [    0.9974,3.8519e-34,8.9821e-40], 
   [ 5.8353e12,9.1785e-43,3.0574e-15]], 

  [[9.1785e-43,    0.7702,    0.3673], 
   [    0.6442,    0.7702,    0.3673], 
   [    0.7955,    0.0226,    0.9186], 
   [    0.7955,    0.0226,    0.9186], 
   [    0.9498,    0.9715,    0.4916], 
   [    0.9498,    0.9715,    0.4916], 
   [    0.5309,    0.0362,    0.9577], 
   [    0.5309,    0.0362,    0.9577], 
   [    0.5603,    0.6266,    0.5296]]]]

**Comment by shugeo** [comment]
I've got follow from TF:
[0.7788     0.8012     0.7244     0.4744111  0.7600333  0.42217776
 0.26142225 0.7454778  0.22103335 0.41403335 0.8373667  0.42420003
 0.59844446 0.71318877 0.6011445  0.83055556 0.264911   0.7387556
 0.83529997 0.2422334  0.5823999  0.6884666  0.5032889  0.23006654
 0.6591     0.5555     0.1596     0.5176333  0.44208887 0.5827889
 0.5938309  0.5646876  0.5123568  0.61811364 0.6748667  0.44617534
 0.43473703 0.7353667  0.3969963  0.35003704 0.6654419  0.46649635
 0.41335183 0.39988017 0.7140149  0.43368888 0.45865932 0.72049254
 0.42537406 0.73366547 0.5662765  0.42371112 0.78866667 0.53543335
 0.30312222 0.18414445 0.49542224 0.67293704 0.4168852  0.59891605
 0.8822444  0.60281235 0.62855184 0.4495222  0.6014852  0.36275554
 0.15933579 0.5788963  0.34024328 0.08295307 0.52441484 0.6826569
 0.10747781 0.64715934 0.80707777 0.19927411 0.8880544  0.7861703
 0.21763334 0.9362333  0.78198886 0.27523333 0.3308667  0.6250333
 0.5907889  0.45925558 0.6709963  0.7761333  0.5249852  0.63986665
 0.4406333  0.34007773 0.3003666  0.19945924 0.33715558 0.24757043
 0.09977405 0.60721123 0.6248297  0.08286668 0.7239556  0.6876333
 0.12114445 0.73849255 0.54079986 0.12879999 0.74139994 0.51143324
 0.32978892 0.45314446 0.58711106 0.5576408  0.5464408  0.6107901
 0.68978024 0.55681235 0.5833172  0.43907034 0.23548517 0.35123706
 0.26263458 0.18254575 0.33890504 0.1976099  0.5321877  0.65619516
 0.18267044 0.6404851  0.63069254 0.20112106 0.58788633 0.37666163
 0.20481117 0.57736665 0.32585555 0.50801116 0.5387556  0.29788882
 0.59799266 0.7008482  0.35215425 0.6330642  0.753121   0.42497158
 0.44849625 0.36611477 0.5719964  0.36038768 0.1586321  0.70625067
 0.416968   0.22043455 0.82134944 0.4690964  0.31661478 0.6675073
 0.5182569  0.4357136  0.33437145 0.528089   0.4595333  0.26774442
 0.52779996 0.5559667  0.35320008 0.5630963  0.62568885 0.44562602
 0.557237   0.62408876 0.5438927  0.3867555  0.3371999  0.6655223
 0.30325183 0.17024446 0.71867025 0.35021478 0.18318895 0.6690962
 0.4377444  0.24482228 0.5241777  0.5523185  0.33891484 0.3156962
 0.5752333  0.3577333  0.27400002 0.44196665 0.52757776 0.6382001
 0.47803456 0.3974851  0.7738359  0.4686691  0.27816284 0.8476581
 0.2775703  0.20192216 0.6742259  0.14285672 0.20554078 0.4944727
 0.0927209  0.32894826 0.30523813 0.19454071 0.3410815  0.26075178
 0.3976642  0.27903205 0.31276423 0.43828884 0.2666222  0.32316667
 0.4248     0.5219     0.6952     0.46102223 0.35184443 0.8394778
 0.45095554 0.20897777 0.9084111  0.2557333  0.17486666 0.6759666
 0.11077777 0.21260004 0.44963327 0.04122221 0.35810006 0.23246664
 0.14590007 0.36033332 0.2080667  0.3667334  0.2670555  0.31217784
 0.4109     0.2484     0.333      0.2974     0.6636     0.3808
 0.6135111  0.40026665 0.5875778  0.8503     0.24200003 0.7501111
 0.76979995 0.50400007 0.7356667  0.6879222  0.57351106 0.73106664
 0.60397774 0.35428885 0.74123335 0.39506656 0.27853334 0.6585333
 0.10284433 0.29842222 0.5139222  0.0444     0.3024     0.485
 0.5756222  0.34854442 0.6049667  0.6263938  0.22777282 0.71313334
 0.66620123 0.17765433 0.78429013 0.6621518  0.41014817 0.7074074
 0.67555183 0.51060987 0.6708259  0.7151259  0.41302344 0.6946963
 0.5446962  0.33081108 0.6180703  0.23426408 0.25884813 0.4744469
 0.17217779 0.24445555 0.44572222 0.7964111  0.12472223 0.7531556
 0.6118617  0.1483889  0.75928515 0.4833407  0.2004667  0.7449173
 0.57893336 0.3661889  0.6485592  0.6772543  0.46945432 0.5984506
 0.7796679  0.47903457 0.617716   0.63706285 0.40579626 0.54952586
 0.33111224 0.27734566 0.42303205 0.26992223 0.25165558 0.39773333
 0.7874667  0.26583335 0.5974333  0.4876703  0.44144446 0.48782218
 0.30543333 0.57191116 0.41133702 0.5934334  0.5218     0.46735552
 0.73524815 0.5152815  0.47753704 0.6577852  0.5741519  0.41896293
 0.50037766 0.57161117 0.3686555  0.28967398 0.5281297  0.3238592
 0.24753332 0.5194334  0.31489998 0.72816664 0.37683335 0.5285778
 0.3895555  0.5582283  0.32292962 0.18990126 0.6730641  0.18445063
 0.5460741  0.5216629  0.31464812 0.6978098  0.45279747 0.36710492
 0.5428901  0.5077358  0.30295062 0.42367774 0.53567034 0.28493333
 0.32827038 0.54560244 0.2976741  0.30918893 0.5475888  0.30022222
 0.5933333  0.44266668 0.59002227 0.3305555  0.4106049  0.31789258
 0.16793211 0.36878017 0.11760493 0.40592593 0.28790364 0.20468517
 0.5172234  0.22784683 0.27239504 0.4384765  0.19901967 0.3110494
 0.43695557 0.19709623 0.34693336 0.4869186  0.21310854 0.38097042
 0.49691117 0.21631104 0.3877778  0.37919992 0.4914     0.56826663
 0.26019996 0.34673333 0.29495183 0.21430746 0.23090371 0.09418149
 0.46084452 0.23042224 0.1835889  0.56450003 0.23844449 0.26893705
 0.45383334 0.2592223  0.34819633 0.45761114 0.21635559 0.38596666
 0.5376852  0.13105926 0.39607778 0.55370003 0.11400001 0.3981
 0.11219993 0.5287333  0.49104443 0.18227404 0.3386963  0.26007527
 0.30624574 0.20396544 0.09970618 0.6458075  0.2904593  0.22173704
 0.7636852  0.40607417 0.32631359 0.549037   0.5653705  0.40470868
 0.4831852  0.47417036 0.40968886 0.5165309  0.21597281 0.3657259
 0.5232     0.16433334 0.3569333  0.0588     0.5362     0.4756
 0.16668889 0.33708888 0.25309998 0.32463336 0.19857779 0.10081112
 0.68280005 0.3024667  0.22936666 0.80352217 0.43960005 0.33778888
 0.5680777  0.6266     0.41601112 0.4883     0.52573323 0.4144333
 0.5123     0.23295549 0.35965553 0.5171     0.1744     0.3487    ]
And this full conforms with our output.

**Comment by raver119** [comment]
Fixed.
