### ISSUE TITLE
Word2Vec - Example Run Fails

### ISSUE THREAD

**Issue by newterminator** [deeplearning4j/deeplearning4j#843]
I tried to run the example included in the [dl4j-0.4-examples](https://github.com/deeplearning4j/dl4j-0.4-examples)

![w2v_error](https://cloud.githubusercontent.com/assets/5087437/10986739/a96c4846-83fa-11e5-9e7e-9e53a1b3d627.png)

I got the DBNIrisExample.java to work as explained in the [Quick Start Guide](http://deeplearning4j.org/quickstart.html), but as seen above the word2vec example fails to execute.

**Comment by AlexDBlack** [comment]
Looking at the stack trace + doing a quick google search suggests that it might not like space in the path. Maybe try it in a different path, see if that helps.

**Comment by newterminator** [comment]
@AlexDBlack , your suggestion worked. Thanks for the quick jet reply.
