### ISSUE TITLE
Allow to override the 1:1 ratio between Xmx & off-heap amount?

### ISSUE THREAD

**Issue by maxime-michel** [deeplearning4j/deeplearning4j#8435]
#### Issue Description

We ship DL4J in a web application deployed by our users on instances of various sizes.

Also, our application uses the library minimally, the 1:1 ratio between Xmx and `Dorg.bytedeco.javacpp.maxbytes` is excessive.

> If you don’t specify off-heap memory limit, the JVM heap limit (Xmx) will be used by default.

An instance's usage of the library depends however on the application's number of users. So, we might allocate 512MB for a 4GB instance with 5 concurrent users, but that number would have to grow linearly for an Xmx of 16GB.

Instead of us providing documentation about example scenarios to every single system administrator, we would rather be able to pass a parameter that would define which ratio of Xmx DLF4J should use across the board. For instance, 0.1.

#### Contributing

We are happy to work on this should the feature make sense to you.

**Comment by saudet** [comment]
It should be easy enough to add something for that around here: https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/Pointer.java#L455-L477
Maybe something like "org.bytedeco.javacpp.maxMemoryRatio"? In any case, please do send a pull request with modifications that satisfy your requirements! Thank you

**Comment by saudet** [comment]
Done! Thanks for the contribution and for hanging in there to narrow down the requirements.

**Comment by maxime-michel** [comment]
Thanks for your patient help and input!
