### ISSUE TITLE
 (Low Priority) Recurrent Neural Network; special case of empty sequence causes crash

### ISSUE THREAD

**Issue by dkmisra** [deeplearning4j/deeplearning4j#844]
##  Background
Recurrent Neural Network take as input a time-series data of size pxqxr where p is the number of examples, q is the dimensionality of each node in the time series and r is the number of nodes in the time series. 

## Error
Now if we have r=0 then we get  Arithmetic exception and the application crashes. 

## Expected
Recurrent neural network take h0 as an input, which is generally kept as default. Network should return this value when the sequence is empty as h0 represents the encoding of an empty sequence. If not then atleast a custom exception must be thrown.

**Comment by AlexDBlack** [comment]
To be honest, I'm not inclined to fix this.
A time series of length 0 isn't a time series, it's essentially null input. Input in that case will have shape [p,q,0] which isn't even a valid NDArray in the first place.

**Comment by dkmisra** [comment]
Sure but some exception should be thrown. I just came to know that its not a valid NDArray and its strange that my code was able to create such an NDArray. Cause otherwise deep down during feedForward I get an arithmetic exception. Maybe this thing can be mentioned in a doc somewhere.

**Comment by agibsonccc** [comment]
I agree with @dkmisra I've actually had places where me throwing excepetions has found bugs.

**Comment by AlexDBlack** [comment]
Sure. I'll put in some input validation on the MultiLayerNetwork.fit() methods to check for things like 0 examples or zero time series length (for RNNs).

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/pull/888
