### ISSUE TITLE
Is temporal convolution available in beta5.0 

### ISSUE THREAD

**Issue by zhangy10** [deeplearning4j/deeplearning4j#8444]
I am wondering if the temporal convolution network (TCN) for convolution 1d support is available in the beta5.0 or snapshots version? 

I saw this post and it seems that the updates have been added in:
https://github.com/eclipse/deeplearning4j/issues/7629#event-2575545499

So, can you please double-check the availability for TCN? Thanks.

**Comment by AlexDBlack** [comment]
Not yet, unfortunately. I've been meaning to look at this again (and missed your previous comment), thanks for the reminder.
Keep an eye on the other issue, there's a small chance we can squeeze it into the upcoming release, but no promises...

**Comment by zhangy10** [comment]
Thanks for that. And hope it will be added in the next version. cheers.
