### ISSUE TITLE
libnd4j: AdjustHue - add support for delta config via array

### ISSUE THREAD

**Issue by alexanderst** [deeplearning4j/deeplearning4j#8458]
According to ops.proto - delta should be scalar INDArray. TF documentation is misleading here.

op {
  name: "AdjustHue"
  input_arg {
    name: "images"
    type: DT_FLOAT
  }
  input_arg {
    name: "delta"
    type: DT_FLOAT
  }
  output_arg {
    name: "output"
    type: DT_FLOAT
  }
}

**Comment by AlexDBlack** [comment]
Delta via targ is fine for our internal use, so we want the option to also provide it via the second input array.
We have a number of ops that support both.

**Comment by raver119** [comment]
Ye, that's an easy fix. We'll sort it out today

**Comment by alexanderst** [comment]
@raver119 Tests for adjust_hue are passing.

**Comment by raver119** [comment]
Thanks.
