### ISSUE TITLE
Operation adjust_contrast in libnd4j should be able to handle empty arrays without validation error

### ISSUE THREAD

**Issue by alexanderst** [deeplearning4j/deeplearning4j#8465]
For TF compatibility  - operation adjust_contrast in libnd4j should be able to handle empty arrays without validation error. Otherwise TF import tests with empty inputs are failing with exception like this
 ADJUST_CONTRAST_V2: operation expects image with 3 channels (R, G, B), but got 0 instead

Validation is correct, the issue is just TF compatibility.

**Comment by raver119** [comment]
Fixed in my branch, will be merged later today
