### ISSUE TITLE
Confusion on Canova page

### ISSUE THREAD

**Issue by lance95** [deeplearning4j/deeplearning4j#847]
Hey,
I got confused but it was my bad i think, on this page : http://deeplearning4j.org/canova.html
I did not understand that all  the beginning was basically explaining how the  initialize() method worked and i thought i had to "Run Canova From the Command Line".
If I had scrolled down to "Reading Records, Iterating Over Data" I would have understood but sadly i did not and I tried to do all the things that canova offers by myself

**Comment by ncleaver** [comment]
Strong formatted "read entire page"
