### ISSUE TITLE
Question: The method getTrainIterator() from the type DataSetIteratorSplitter is deprecated

### ISSUE THREAD

**Issue by DanielMartensson** [deeplearning4j/deeplearning4j#8473]
Why is the method getTrainIterator() from the type DataSetIteratorSplitter is deprecated?

https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-data/deeplearning4j-utility-iterators/src/main/java/org/deeplearning4j/datasets/iterator/DataSetIteratorSplitter.java

What else can I use instead if I need to split my data to train and eval data?

**Comment by raver119** [comment]
Logic was changed. Original implementation was able to "split" your underlying iterator in two parts. Now there can be way more than just 2 iterators. 

Use `getIterators()` method.

**Comment by DanielMartensson** [comment]
> Logic was changed. Original implementation was able to "split" your underlying iterator in two parts. Now there can be way more than just 2 iterators.
> 
> Use `getIterators()` method.

So getIterators() gives be first train and then eval iterator?

**Comment by raver119** [comment]
Yes. Say, if you split your underlying iterator into 3 parts, you can use your first iterator as train iterator, second as test iterator, and third as validation iterator. That's up to you how to use this split.
