### ISSUE TITLE
URISyntaxException in LuceneInvertedIndex on Windows 8.1 (word2vec example)

### ISSUE THREAD

**Issue by andreasschrade** [deeplearning4j/deeplearning4j#848]
Hello all,

first of all, many thanks for providing such an outstanding deep learning library for Java.
Also thanks for the awesome documentation on your website. I really appreciate this!

I just tried the [Word2VecRawText example](https://github.com/deeplearning4j/dl4j-0.4-examples/blob/master/src/main/java/org/deeplearning4j/examples/word2vec/Word2VecRawTextExample.java) and got the following error:

> Exception in thread "main" java.lang.IllegalArgumentException: **Illegal character in opaque part at index 7: file:G:\projekt\sandbox\word2vec-index**
>	at java.net.URI.create(URI.java:859)
>org.deeplearning4j.text.invertedindex.LuceneInvertedIndex.ensureDirExists(LuceneInvertedIndex.java:540)
>org.deeplearning4j.text.invertedindex.LuceneInvertedIndex.initReader(LuceneInvertedIndex.java:278)
> ...
> Caused by: java.net.URISyntaxException: **Illegal character in opaque part at index 7: file:G:\projekt\sandbox\word2vec-index**
>	at java.net.URI$Parser.fail(URI.java:2829)
>	at java.net.URI$Parser.checkChars(URI.java:3002)
> ...
[see full stacktrace](https://gist.github.com/andreasschrade/13aaceba60d12d87d0c1)

I tried it multiple times and can "fix" this bug temporarily via debugger if I change the line

> this.dir = FSDirectory.open(Paths.get(URI.create("file:" + directory.getAbsolutePath())));

into

> this.dir = FSDirectory.open(Paths.get(URI.create("file:**/**" + directory.getAbsolutePath()**.replace("\\\","/")**)));

Original path: file:G:\projekt\sandbox\word2vec-index
Working path: file:/G:/projekt/sandbox/word2vec-index

I am using version 0.4-rc3.6 for deeplearning4j-ui, deeplearning4j-nlp and nd4j-jblas.
My environment: Windows 8.1 Pro (I'm sorry for using windows), Java JDK 1.7.0_71, IntelliJIdea 14

Any help would be really great!

Thank you.

Regards,
Andreas

**Comment by jsteggink** [comment]
Hi Andreas,

You are right, I had the same problem. URI.create only works for legal URIs (RFC 2396). 
Something like this should work:
dir = FSDirectory.open(Paths.get(directory.toURI()));

Cheers,
Jeroen

**Comment by jsteggink** [comment]
I have added a Pull request for the bugfix.
https://github.com/deeplearning4j/deeplearning4j/pull/866

**Comment by saphir100** [comment]
how to change? this file is lock.

**Comment by raver119** [comment]
You don't need to change anything. Lucene use was removed from w2v, it just doesn't uses it anymore, so original issue isn't relevant anymore.

**Comment by saphir100** [comment]
thank's
