### ISSUE TITLE
RecordReaderDataSetIterator Single Target Regression

### ISSUE THREAD

**Issue by Meerer** [deeplearning4j/deeplearning4j#8494]
#### Issue Description

Please describe our issue, along with:
- expected behavior
When using a RecordreaderDataSetIterator for a regression task it should remove the label column from the feature set
- encountered behavior
The label column is still present in the feature set making the whole regression task pointless

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta5
* Platform information: Windows 10

#### Contributing
My DataSetIterator:

`DataSetIterator iterator = new RecordReaderDataSetIterator(recordReader, batchSize, labelIndex, labelIndex, true);
`
alternative way to intialize I tried:

```
DataSetIterator iterator = new RecordReaderDataSetIterator.Builder(recordReader, batchSize)
                .regression(labelIndex)
                .build();

```
When I want to input the Dataset to my network it now has exactly the same feature dimensionality as before and I can still access the label in the DataSet (this may be intended?)

If I use the iterator with labelIndex+1 it successfully removes the label column but now has multiple targets, which I don't want.

**Comment by AlexDBlack** [comment]
I'm unable to reproduce this.
The behaviour I'm seeing looks correct, for both the constructor and the builder way of creating the iterator.

I have also tested the first position (index 0), last position (index size-1), and a position in-between (index 1).

https://gist.github.com/AlexDBlack/208096a802ac7c2f672c111f0fe8161f

**Comment by Meerer** [comment]
Yeah this was my bad I saved my dataset wrong and this added an extra column. Sorry for troubling you :*
