### ISSUE TITLE
resize_bicubic in libnd4j - should support all types listed in ops.proto

### ISSUE THREAD

**Issue by alexanderst** [deeplearning4j/deeplearning4j#8507]
It is impossible to call resize_bicubic from libnd4j with input of non-floating type:
**Op [resize_bicubic] failed check for input [0], DataType: [INT32]**

Description is:
op {
  name: "ResizeBicubic"
  input_arg {
    name: "images"
    type_attr: "T"
  }
  input_arg {
    name: "size"
    type: DT_INT32
  }
  output_arg {
    name: "resized_images"
    type: DT_FLOAT
  }
  attr {
    name: "T"
    type: "type"
    **allowed_values {
      list {
        type: DT_INT8
        type: DT_UINT8
        type: DT_INT16
        type: DT_UINT16
        type: DT_INT32
        type: DT_INT64
        type: DT_HALF
        type: DT_FLOAT
        type: DT_DOUBLE
      }
    }**

**Comment by raver119** [comment]
Implemented, but it seems there's an issue with double dtype. There's separate issue open for that.
