### ISSUE TITLE
libnd4j: HSVtoRGB and RGBtoHSV

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#8514]
We need two operations implemented: HSVtoRGB and RGBtoHSV.
We have primitive function for conversion used in adjust_hue/adjust_saturation operations, but now we need this functionality exposed as standalone operations.

**Comment by raver119** [comment]
cc @quickwritereader ^^^

**Comment by raver119** [comment]
https://github.com/KonduitAI/deeplearning4j/blob/763a225c6a069e2f88f5f069c5fa7d5116874b6a/libnd4j/include/ops/declarable/helpers/adjust_hue.h#L68

**Comment by raver119** [comment]
This op was added in `qwr_clean` branch, now we need Java/SameDiff wrappers for this op. 
cc @alexanderst

**Comment by raver119** [comment]
@alexanderst C++ implementations were merged to master today, so feel free to provide wrappers in your own branch.

**Comment by alexanderst** [comment]
@raver119  Wrappers added in my branch. There's mismatch with TF, for example rgb_to_hsv for float32 input

```
TF: [[[    0.215289578,    0.095885336,    0.801197767], 
  [    0.317938268,    0.751917899,    0.727141261]]]
SD: [[[  184.715530396,   38.642787933,   36.721866608], 
  [   45.999633789,   12.680121422,   12.551403046]]]

**Comment by quickwritereader** [comment]
you mean precision wise?

**Comment by alexanderst** [comment]
No, there's significant mismatch between results. First elements returned from tf.image,rgb_to_hsv is
0.215289578 and SameDiff (calling libnd4j) is 184.715530396.

**Comment by quickwritereader** [comment]
yes we return ~[0;360]~ wait I will recheck

**Comment by quickwritereader** [comment]
well even normalized they are not equal. it seems values re flipped. could you be sure that orders and dimensions match
0.21 not eq 184/360

**Comment by quickwritereader** [comment]
I checked tf.  our rgbs are not normalized as well. I followed internal rgb hsv convertors.
but first, let's find why they don't even match after normalization.

**Comment by alexanderst** [comment]
Simple test:

```
    @Test
    public void testHsvToRgb_1() {
        INDArray image = Nd4j.createFromArray(new float[]{0.7788f,    0.8012f,    0.7244f}).
                reshape(1,1,3);
        HsvToRgb op = new HsvToRgb(image);
        INDArray[] ret = Nd4j.exec(op);
        INDArray expected = Nd4j.createFromArray(new float[]{0.53442812f,0.144007295f,0.724374652f}).reshape(1,1,3);
        assertEquals(expected, ret[0]);
    }
}

**Comment by alexanderst** [comment]
Python code for expected result calculation is:
tf.image.hsv_to_rgb(input)

where input is uniformly distributed array of float32 with [1,1,3] shape.

**Comment by quickwritereader** [comment]
I want the first case you posted above. Want to confirm that if it is just normalization problem. 
Above code certainly not expected input. Think we need to change to tf ranges

**Comment by alexanderst** [comment]
Test for data I've posted earlier:
```
@Test
    public void testRgbToHsv_1() {
        INDArray image = Nd4j.createFromArray(new float[]{0.7788f,0.8012f,0.7244f,
                    0.2309f,0.7271f,0.1804f}).reshape(1,2,3);
        RgbToHsv op = new RgbToHsv(image);
        INDArray[] ret = Nd4j.exec(op);
        INDArray expected = Nd4j.createFromArray(new float[]{0.215289578f,    0.095885336f,    0.801197767f,
                0.317938268f,    0.751917899f,    0.727141261f}).reshape(1,2,3);
        assertEquals(expected, ret[0]);
    }

**Comment by quickwritereader** [comment]
OK I confirm that it is internal implementation ~~problem~~ that targets h [0,360] s [0,1] v [0,1]
and also rgb [0,255] instead of **tf ranges**
but the question is how you got   38.642787933,   36.721866608 and other values that is not in range [0,1]
```
TF: [[[    0.215289578,    0.095885336,    0.801197767], 
  [    0.317938268,    0.751917899,    0.727141261]]]
SD: [[[  184.715530396,   38.642787933,   36.721866608], 
  [   45.999633789,   12.680121422,   12.551403046]]]
```
it should not happen even with this range thing

as for values
```
[0.7788f,0.8012f,0.7244f ,0.2309f,0.7271f,0.1804f] * 255
rgbs : [198.594009, 204.306000, 184.722000, 58.879501, 185.410507, 46.001999]
I got HSV : [77.499969 #/360, 0.095856, 0.801200, 114.457657 #/360, 0.751891, 0.727100]

```

**Comment by alexanderst** [comment]
This is exact output from Java test testRgbToHsv_1.  Input shape is [1,2,3].  Java code just calls operation from libnd4j, nothing else. 

[[[  184.7220,   38.6438,   36.7227], 
  [   46.0020,   12.6827,   12.5539]]]

But Java doesn't support any integer arguments according to TF prototype. I mean this code:
            const int arg_size = block.getIArguments()->size();
            const int dimC = arg_size > 0 ? (INT_ARG(0) >= 0 ? INT_ARG(0) : INT_ARG(0) + rank) : rank - 1;

**Comment by quickwritereader** [comment]
yes I found just name call problem
instead of rgb to hsv we are getting hsv to rgb,

so there are two issues:
1) wrong name call
2) different range than tf range

**Comment by quickwritereader** [comment]
for the first issue I need to re-check to confirm if its form C++ side

**Comment by alexanderst** [comment]
Fixed wrong name locally, now output is
 
[[[   77.504241943,    0.095885336,    0.003141952], 
  [  114.457771301,    0.751917899,    0.002851534]]]

**Comment by quickwritereader** [comment]
Yes now only range problem left. To match to tf you need to multiplly all input to 255 and with the result the first one shoul be divided by 360.
But we have to match  exactly tf side we need to solve it. I will discuss it tomorrow to see

**Comment by alexanderst** [comment]
Confirming fix in master. Tests are passing.

**Comment by raver119** [comment]
tyvm!
