### ISSUE TITLE
libnd4j: pad op - re-add long/int64 pad array support

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8517]
`Op [pad] failed check for input [1], DataType: [INT64]`

Reproduce with: TransformOpValidation.testPad

We'll need long/int64 support for the pad array (second input) for TF import.
Note we also saw some compiler issues with CUDA 10.2 on this op with long datatype.

**Comment by raver119** [comment]
Plus, there's a difference: TF documentation says that op accepts int32 paddings only, but looks like ops.proto says that it's int32/int64

**Comment by raver119** [comment]
Re-implemented
