### ISSUE TITLE
Model Files cannot be downloaded

### ISSUE THREAD

**Issue by christian83182** [deeplearning4j/deeplearning4j#8522]
#### Issue Description
Pretrained zoo models cannot be downloaded automatically or manually. 
Issue arose when calling `zooModel.initPretrained(PretrainedType.IMAGENET)` on a VGG16 zoo model as described in the transfer training documentation available at https://deeplearning4j.org/docs/latest/deeplearning4j-nn-transfer-learning. The error specifies that the local file's checksum does not match the expected file's checksum. Furthermore, the download URL (http://blob.deeplearning4j.org/models/vgg16_dl4j_inference.zip) cannot be accessed manually. 

Normally, this should download the pretrained model. 

#### Version Information
DL4J Version: 1.0.0-beta4
Platform Information: Windows 10 64 bit
CUDA version: 10.0
NVIDIA driver version: 441.22
Java Version: 1.8.0_231

#### Additional Information
Stack trace:  https://gist.github.com/christian83182/51115cc9137fec40d60df2909f1d6796
pom.xml: https://gist.github.com/christian83182/8113a04cc2365fa99505aa4fb96d4e65

**Comment by AlexDBlack** [comment]
this should work fine in beta5 still (I just checked with vgg16)
Note also that 1.0.0-beta6 will be out in the next 24-48 hours.

One workaround (if you really can't upgrade) is to set the `org.deeplearning4j.resources.baseurl` system property to `https://dl4jdata.blob.core.windows.net/`
https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-common/src/main/java/org/deeplearning4j/config/DL4JSystemProperties.java#L45-L53
