### ISSUE TITLE
libnd4j: RgbToGrayscale op

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#8536]
We need to add implementation of TF RgbToGrayscale op

**Comment by olegsemeniv** [comment]
Please reassign it back to me, my mistake.

**Comment by olegsemeniv** [comment]
Thanks

**Comment by raver119** [comment]
@alexanderst PR is up,  can you please add Java wrapper for this op + tests?

**Comment by raver119** [comment]
P.s. https://github.com/KonduitAI/deeplearning4j/pull/138

**Comment by raver119** [comment]
Implemented
