### ISSUE TITLE
Consider changing the menu link for documentation.html from "Site map" to "Documentation"

### ISSUE THREAD

**Issue by wiku** [deeplearning4j/deeplearning4j#854]
Hi,

As discussed with @agibsonccc in gitter:

@agibsonccc one suggestion would be to change the menu button for documentation.html from "Site map" to "Documentation". There's a lot of valuable information there, but when I was first looking for docs I only found the "Get started" and "Quickstart", and assumed you have nothing more since one of them pointed to gitter.. I think that's probably the reason why many people end up here asking silly questions and you have to send them links to docs..

@wiku Great! File a documentation issue and we'll get it on @chrisvnicholson todo list
If it doesn't get posted as an issue it doesn't get done

**Comment by agibsonccc** [comment]
I think we should consider what to do here. Maybe a bit of a site reorg consolidating some sections to make things? 

Getting Started/Quick start
Setup
Developer setup
Tutorials

@wiku thoughts here?

**Comment by wiku** [comment]
Uhhh, ok.. first of all, below I gave a lot of personal feeling and of course these opinions they might not reflect the average opinion of you target users, so few words about me and my experience: I'm not an expert on layouts. I'm currently a corporate java developer with some past project management and (not very successful, but still) startuping experience. I'm using dl4j for a private project. If I have good feelings about it, so perhaps I will propose it one day for some enterprise purpose if I find one (can't promise that, but I think I would at least consider it when it gets a little bit more mature). For me setting up the basic environment (in eclipse) was easy, just had some issues to figure out which backend is actually running and which one is the preferred one. However, in the beginning I found a little bit lost between two different setup guides and totally missed the documentation.html page, so I assumed there is nothing more there to read and went straight to the gitter scrolling it and reading and finally asking questions which have been already answered in the tutorials. 

In my opinion if you want the biggest bang-for-a-buck change just change the "Site map" to "Documentation" or "Tutorials". If you want to do more, consider merging "Quickstart" "Getting started" into one site (first impression: what a mess? which one should I follow and what is the difference?), with proper sections for 1) "Setup" the environment including backends 2) Running examples. 3) At the end of this section please clearly point to the Documentation/Tutorials (documentation.html) as a next step.

If you wanna do some simple reorganization, as a user I would probably like to have something like this: Getting started, Tutorials, Javadoc (optional, but should be linked somewhere). 

Now.. some more complicated things.. One suggestion would be to make sure that instructions for developers don't mix up with instructions for users. Users should just use maven dependency - I think you don't want them cloning the repositories etc. Developer instructions can be well hidden, perhaps as an article in the documentation page. If somebody is smart enough to consider cloning the repo and developing your framework, he will probably be smart enough to read the docs first and have dl4j running already for some time. And perhaps he/she will get in touch with you first, right? 

Finally, just a thing to consider: Sooner or later you will be overloaded with support requests and all kinds of "silly questions", so you will have to think of redirecting the flow of your users from home->get started->gitter to home ->get started->docs->gitter. Currently you mention the gitter in the very beginning of "Getting started guide", because you want to help potential users with setup and avoid loosing them on one of the basic steps. I don't know whether these users are really your target users or non-target users, or whether you have enough resources to do this kind of "babysitting" instead of focusing on real work. I really don't know that, it's up to you consider. If you think it really supports your growth model, you can keep it.

**Comment by chrisvnicholson** [comment]
New top menu: Home Quickstart Spark Documentation Word2Vec Javadoc About

We'll just link to the Get Started page's more detailed installation instructions from the Quickstart.

**Comment by wiku** [comment]
Thanks, I've already noticed the change. Good job :+1: hope it will benefit everyone!
