### ISSUE TITLE
linspace in beta6.

### ISSUE THREAD

**Issue by RobAltena** [deeplearning4j/deeplearning4j#8550]
The following sniplet: 

INDArray x = Nd4j.linspace(1,10,1);
System.out.println(x);

prints  `[�]`  and seems to show a random uninitialized INDArray in the debugger.

#### Version Information
beta6 cpu, cuda.

**Comment by AlexDBlack** [comment]
I suspect this is just NaN from: `out[i] = lower + i * (upper-lower)/(num-1)` giving `1 + 0 * 9 / 0`
For the length 1 case, we should return the lower value.

**Comment by raver119** [comment]
Fixed
