### ISSUE TITLE
Request to support many-to-one scenario for LSTM

### ISSUE THREAD

**Issue by wiku** [deeplearning4j/deeplearning4j#856]
Hi, as discussed with @AlexDBlack, currently LSTM only supports many-to-many use case, which means a label has to be provided for each sample in the input sequence and the output values are also predicted for each and every time step (both features and labels have the same sequence length). So if I just want to classify the whole sequence it doesn't train very well. Although there are ways to achieve many-to-one with the current implementation (either by using zero output values or adding additional labels for classification) this is still quite troublesome, and probably also has a negative impact on the training performance. If this is not a big problem for you, please consider adding such functionality in a future release. 

![image](https://cloud.githubusercontent.com/assets/2360237/11089982/59f72430-88c2-11e5-9393-9d453ecead65.png)

**Comment by AlexDBlack** [comment]
Still a WIP, but FYI: https://github.com/deeplearning4j/deeplearning4j/pull/952

**Comment by AlexDBlack** [comment]
This is now supported: https://github.com/deeplearning4j/deeplearning4j/pull/952

I'll be working on some more examples and documentation soon. In the mean time, talk to me on gitter if you want to use this functionality.

**Comment by wiku** [comment]
Great, I was waiting for it! Big thanks!
