### ISSUE TITLE
libnd4j CPU optimization: Add DNNL (MKLDNN) concat helper

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8569]
I don't believe we have this implemented already...
https://intel.github.io/mkl-dnn/dev_guide_concat.html

Given the importance of the concat operation in CNNs like inception, it would be good to use the MKLDNN implementation.

Not sure if MKLDNN softmax is also worth adding...
https://intel.github.io/mkl-dnn/dev_guide_softmax.html

**Comment by shyrma** [comment]
done!
