### ISSUE TITLE
MatMul with empty inputs

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#8577]
At this moment we don't have tests for MatMul with empty inputs, and apparently we'll see couple of minor issues there. So, we need to add corresponding import tests and, presumably, fixes.

**Comment by raver119** [comment]
@alexanderst i've applied fixes in your branch, but have you added additional tests?

**Comment by alexanderst** [comment]
Added locally, but resources not in pr yet.

**Comment by raver119** [comment]
Turns out it's already merged.
