### ISSUE TITLE
Recurrent Neural Network is not cloneable

### ISSUE THREAD

**Issue by dkmisra** [deeplearning4j/deeplearning4j#858]
## Bug and Reproducibility 

If you try to clone a MLP with a recurrent layer then you get 

`Exception in thread "main" java.lang.IllegalStateException: Unable to cloe network`

## Expected Output
Network should be cloned.

**Comment by AlexDBlack** [comment]
Fixed: https://github.com/deeplearning4j/deeplearning4j/pull/887
