### ISSUE TITLE
Nd4J: need UInt32 and UInt64 indexers

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8582]
https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java#L578-L587

Unsurprisingly, this overflows for large values in toString, and is also returning incorrect values in getDouble, getInt etc
```
    @Test
    public void testUint32(){
        INDArray arr = Nd4j.create(DataType.UINT32, 10);
        arr.assign(1024);
        System.out.println(arr);
        arr.assign(Integer.MAX_VALUE);
        System.out.println(arr);
        System.out.println(arr.getDouble(0));
        System.out.println(arr.getInt(0));
    }

[      1024,      1024,      1024,      1024,      1024,      1024,      1024,      1024,      1024,      1024]
[        -1,        -1,        -1,        -1,        -1,        -1,        -1,        -1,        -1,        -1]
-1.0
-1
```

These indexers would need to go in JavaCPP though

https://github.com/bytedeco/javacpp/tree/master/src/main/java/org/bytedeco/javacpp/indexer

**Comment by agibsonccc** [comment]
@saudet

**Comment by saudet** [comment]
I've added a `UIntIndexer` for that in commit https://github.com/bytedeco/javacpp/commit/11e20d81c657a0155a43a6a90a482cd83d9d24b2 as well as a `ULongIndexer` in commit https://github.com/bytedeco/javacpp/commit/b1f29bec7bed3c30a9ebe63f8fed1f83acace59c.
