### ISSUE TITLE
Object Detection using Darknet19

### ISSUE THREAD

**Issue by Paranormaly** [deeplearning4j/deeplearning4j#8587]
I used DL4J Yolo and TinyYolo examples for object detection using opencv it works fine
But When I first used Darknet19 I saw that there is no way to get the detected object boundaries
Yolo has Yolo2OutputLayer but Darknet19 has loss output layer and there is no way to get boundaries.
I checked documentation/examples/tests but couldn't find a way.
Is there any guide or documentation for such an issue?

**Comment by saudet** [comment]
Darknet doesn't do object detection on its own. That's what the Yolo layers do.
