### ISSUE TITLE
How to load model from hdfs on flink taskmanger?

### ISSUE THREAD

**Issue by SelfEvoAI** [deeplearning4j/deeplearning4j#8589]
there is many LSTM model (lstmmodel.h5) stored in hdfs.  

## How to load the model from hdfs?

And I find the issure #5241 , but it did not worked for me.

I am try the two function, but get out errors.

```
Exception in thread "main" java.io.FileNotFoundException: File with name hdfs://10.10.10.10:8020/tmp/model.h5 does not exist.

```

```
  def modelLoad(modelPath: String): MultiLayerNetwork = {
    val simpleMlp = new ClassPathResource(modelPath, classload).getURL.getFile
    val model: MultiLayerNetwork =   KerasModelImport.importKerasSequentialModelAndWeights(simpleMlp)

    model
  }
  
  def modelLoadFromHDFS(modelHDFSPath: String): MultiLayerNetwork = {
    val Model = new KerasSequentialModel().
      modelBuilder.
      weightsHdf5Filename(modelHDFSPath).
      enforceTrainingConfig(false).
      buildSequential.
      getMultiLayerNetwork
    Model
  }

  def main(args: Array[String]): Unit = {
    val path = "hdfs://10.10.10.10:8020/tmp/model.h5"
    val model = modelLoadFromHDFS(path)
    println(model.getConfig.getGradientNormalization)
  }
```

when I input a local path (D:\project\opsDataWarehouse\model\mutiTimestepsLstm.h5), it worked.

How shoud I do to load model from hdfs? 

Thanks.

**Comment by AlexDBlack** [comment]
You can't use ClassPathResource to load from a remote location.
ClassPathResource, by definition, is for loading things that are on the class path - i.e., local, and within the JVM's class path. Basically it's only useful for things within JARs (or in some cases your project directories).

To load from HDFS, you'll need to use input streams. DL4J models and Keras import has methods for it.
I'm not familiar enough with Flink's APIs to provide the exact code, but here's the code for Spark:
https://deeplearning4j.org/docs/latest/deeplearning4j-scaleout-howto#saveload
There should be something similar available for Flink
