### ISSUE TITLE
libnd4j: autovectorizer validation

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#8598]
We want to rely on autovectorization in our legacy ops loops, so it would be awesome to validate it actually works as intended. And, probably, fix it, if some loops are not vectorizer properly.

In order to do this we need:
- Add an option for build script that will enable missed vectorization reporting in file
- Python script that will parse vectorizer log and give us human-readable representation of current autovectorizer results
- Fix whatever is possible to fix in there.

Target compiler for now is GCC only. Other compilers will be investigated once GCC vectorizer output validated

**Comment by quickwritereader** [comment]
I checked gcc. we can use `-fopt-info-*` flag options for checked cpp files. it can save its output but it is overwritten for each trasnlation unit so its advised to use stderr output. 
gcc also has `-fsave-optimization-record ` json output. but its experimental
[gcc-Developer-Options](https://gcc.gnu.org/onlinedocs/gcc/Developer-Options.html#Developer-Options)

but it seems clangs-llvm is more mature on this topic and already has html viewer.
[generating-compiler-optimization-remarks-llvm](https://developer.ibm.com/linuxonpower/2018/07/02/generating-compiler-optimization-remarks-llvm/)
[llvm-opt-viewer](https://github.com/llvm-mirror/llvm/blob/master/tools/opt-viewer/opt-viewer.py)

**Comment by raver119** [comment]
Implemented.
