### ISSUE TITLE
ND4J: TensorFlowConversion doesn't support many ND4J datatypes

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8599]
Essentially it hasn't kept up with our new datatype additions:

https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-tensorflow/src/main/java/org/nd4j/tensorflow/conversion/TensorflowConversion.java#L109-L129

For example missing unsigned, bfloat16, etc.
We should also test these.

**Comment by farizrahman4u** [comment]
[184](https://github.com/KonduitAI/deeplearning4j/pull/284)

**Comment by farizrahman4u** [comment]
[284](https://github.com/KonduitAI/deeplearning4j/pull/284)

**Comment by AlexDBlack** [comment]
https://github.com/KonduitAI/deeplearning4j/pull/284
