### ISSUE TITLE
libnd4j: ones_as / ones_like and zeros_as / zeros_like needs output dtype arg

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8605]
https://www.tensorflow.org/api_docs/python/tf/ones_like?hl=en
https://www.tensorflow.org/api_docs/python/tf/zeros_like?version=stable

Note the dtype arg. In our ops, if not set, we should use the input datatype.

https://github.com/eclipse/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/parity_ops/ones_as.cpp
https://github.com/eclipse/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/parity_ops/zeros_as.cpp

**Comment by raver119** [comment]
Implemented
