### ISSUE TITLE
libnd4j: range op needs to support output dtype arg

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8606]
Similar to https://github.com/eclipse/deeplearning4j/issues/8605

https://www.tensorflow.org/api_docs/python/tf/range?version=stable
https://github.com/eclipse/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/parity_ops/range.cpp

**Comment by raver119** [comment]
Implemented
