### ISSUE TITLE
StringUtils for utf convertor

### ISSUE THREAD

**Issue by olegsemeniv** [deeplearning4j/deeplearning4j#8613]
Methods:
as inputs int8_t*, unsigned char*, void* calculate buffer length
UTF8 <-> UTF16
UTF8 <-> UTF32 
UTF16 <-> UTF32

**Comment by raver119** [comment]
Huh?

**Comment by olegsemeniv** [comment]
Hi @raver119 , 

I opened this one to systematizy info for the new task, but seems I do not have rights to add watchers and assign. So, you can open new (or update this) and assign it to me. Maybe, you also have any corrections to description.

Thanks

**Comment by raver119** [comment]
Implemented and merged.
