### ISSUE TITLE
BarnesHutTsne does not produce expected output

### ISSUE THREAD

**Issue by thofer** [deeplearning4j/deeplearning4j#8616]
#### Issue Description

I’m using BarnesHutTsne, but the result does not look like as expected. I tried MNist data and expected a typical clustering similar to https://lvdmaaten.github.io/tsne/examples/mnist_tsne.jpg.

The output of BarnesHutTsne (and Tsne) looks like a donut with randomly arranged points that is really untypical.

#### Version Information

I'm using Deeplearning4j version 1.0.0-beta4.

**Comment by raver119** [comment]
Can you please try the latest version, which is beta6 and if the problem is reproducible there - post your code of both Tsne and BarnesHutTsne?

With best regards,
raver119
15 янв. 2020 г., 00:11 +0800, thofer <notifications@github.com>, писал:

**Comment by thofer** [comment]
This is my code for BarnesHutTsne: https://gist.github.com/thofer/e038f747862d3d2e2a3172b9e4a216cb

I updated to beta6, but I cannot tell you yet, whether it runs or not, because it code takes forever to complete (i7-6567U CPU @ 3.30GHz). Compared to t-SNE implementation of Leif Jonsson, that runs within a few minutes for the same data.

mnist-25.csv is 25% of the full MNIST data.

**Comment by thofer** [comment]
I could verify that BarnesHutTsne does not run on beta6. The linked code above leads to a final vector of `NaN` values only.

**Comment by thofer** [comment]
Plain t-SNE fails with

`16:07:52.718 DEBUG org.deeplearning4j.plot.Tsne - Y:Shape is = [6000, 2]`
`16:07:52.855 DEBUG org.deeplearning4j.plot.Tsne - sumX shape: [6000]`
`16:07:52.997 DEBUG org.deeplearning4j.plot.Tsne - times shape: [6000, 6000]`
`16:07:53.015 DEBUG org.deeplearning4j.plot.Tsne - prodSum shape: [6000, 6000]`
`Exception in thread "main" java.lang.IllegalStateException: Can't transpose array with rank < 2: array shape [6000]`
`at org.nd4j.base.Preconditions.throwStateEx(Preconditions.java:641)`
`	at org.nd4j.base.Preconditions.checkState(Preconditions.java:304)`
`	at org.nd4j.linalg.api.ndarray.BaseNDArray.transpose(BaseNDArray.java:3663)`
`	at org.deeplearning4j.plot.Tsne.x2p(Tsne.java:278)`
`	at org.deeplearning4j.plot.Tsne.calculate(Tsne.java:120)`

Find my code at https://gist.github.com/thofer/7d537c2448d82086348f5ffa7b9cc42b.

**Comment by raver119** [comment]
Thank you very much, we’ll investigate that

With best regards,
raver119
16 янв. 2020 г., 18:00 +0300, thofer <notifications@github.com>, писал:
