### ISSUE TITLE
INDArray[CpuBackend] has significant performance differences with double[] on similar operations

### ISSUE THREAD

**Issue by chentao106** [deeplearning4j/deeplearning4j#8617]
#### Issue Description

Please describe our issue, along with:
- expected behavior
- encountered behavior
INDArray[CpuBackend] has significant performance differences with double[] on similar operations, such as:
INDArray[512].sum1,000,000 times cost 14697ms
double[512] sum1,000,000 times cost 36ms

ClusterUtils.computeSquareDistancesFromNearestCluster call with 1 cluster and 10000 points 100 times cost 15812ms
euclideanDistance between10000 double[] and one double[] cost 601ms

KMeansClustering classifies 50000 points into 50 clusters costs more than two days.
Apache Commons Math KMeansPlusPlusClusterer classifies 50000 points into 50 clusters takes about 3 minutes.

All of above test case test on same dataset many times with warm code.
I have tested the same dataset on a GPU Server(NVIDIA P100 cloud server), with CUDA9 backend, KMeansClustering costs dozens hours to classifies 50000 points into 50 clusters.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta6
* Platform information (OS, etc) Windows 10(64bit), JDK8
* CUDA version, if used: None
* NVIDIA driver version, if in use: None

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

I think the cause of the problem is in
 org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner#exec(org.nd4j.linalg.api.ops.ReduceOp)
It is so abstract and too complicate than just a for loop.

I'd like to find a best clustering algorithm on JVM for millions dataset, and I wrote a MiniBatchKMeans by kotlin(refer to sklearn MiniBatchKMeans) base on Apache Commons Math.
MiniBatchKMeans is real fast, 1823ms on classfies 50000 points(512 dimensions) into 50 clusters, and the result has very small difference with KMeansPlusPlusClusterer on convex dataset, but big difference on discrete data.
I'd like to rewrite it into a popular JVM project, but the INDArray performance is really a big problem.

**Comment by raver119** [comment]
1) Unfortunately you vastly undervalue what "framework expenses" are.
When you create array of doubles and rolling through it - you're basically doing a loop over primitives that perfectly fit into CPU cache. Just a plain loop. 

In case of framework use - you have to check everything - array lengths. Calculate output array length. Allocate output array. Make sure input array & output array have the same data type. Make sure you support strided arrays. Make sure you support reduction along axis. Make sure different orders (i.e. for euclidean distance) produce proper result. 

That stuff doesn't come for free, and has runtime costs.

Sure, if all you need is a loop over some small array - loop over primitive is always going to be faster, so you can just use it. 

2) As for KMeansClustering performance - can I see some code that reproduces this behaviour?

**Comment by chentao106** [comment]
> 1. As for KMeansClustering performance - can I see some code that reproduces this behaviour?

```scale
    // kotlin code
    val data = Nd4j.createFromNpyFile(File("all_feat.npy"))
    println(data.shape()[0])
    println(data.shape()[1])
    val points = Point.toPoints(data)
    val kMeansClustering = KMeansClustering.setup(50, Distance.EUCLIDEAN, false, true)
    val clusterSet = kMeansClustering.applyTo(points)
    val sorted = clusterSet.getMostPopulatedClusters(50)
    print(sorted.first().points.size)
    print(sorted.last().points.size)
```
The "all_feat.npy" can be downloaded from: http://pigkit.com/all_feat.npy
"Apache Commons Math ML" and Python sklearn cost few minutes on this dataset, but dl4j costs days.
The huge performance differences means the "KMeansClustering" is unavailable for a Actual Usage.

**Comment by agibsonccc** [comment]
Closing, the KMeans package has been deprecated.
