### ISSUE TITLE
Drop in model F1 score across all classes after upgrading from Beta-2 to Beta

### ISSUE THREAD

**Issue by nimishatandon** [deeplearning4j/deeplearning4j#8618]
#### Issue Description

We are observing a drop in our model performance after upgrading from Beta-2 to beta5 with the exact same dataset.

#### Version Information

1.0.0-beta5

**Comment by AlexDBlack** [comment]
Hard to say without more details, such as the model configuration.
Only thing that comes to mind is a fix in 1.0.0-beta3 regarding l2 regularization.
See release notes: "Fixed an issue where L1/L2 and updaters..."- https://deeplearning4j.org/release-notes.html#onezerozerobeta3-dl4j

Try reducing the learning rate and L2 regularization when training.
For inference, things should be the same (we have regression tests for inference, that ensure that predictions are the same going back to version 0.5.0).
