### ISSUE TITLE
Failure to choose compatible binaries when both generic and AVX2 are on the classpath

### ISSUE THREAD

**Issue by reckart** [deeplearning4j/deeplearning4j#8621]
#### Issue Description

I want to be able to build an application which uses DL4J and is able to run on CPUs supporting AVX2 and on CPUs which do not support it. I am adding both binaries to the classpath / both dependencies to the POM.

I expect that DL4J is able to automatically determine if the CPU supports AVX2 or not. If AVX2 is supported, I expect it to load the AVX2 binaries, otherwise I expect it to load the generic binaries.

The observed behavior is that DL4J during loading locates both, the AVX2 and generic binaries and then tries to load the AVX2 binaries despite the CPU not supporting AVX2. This leads to a VM crash because an illegal opcode is found.

`org.bytedeco.javacpp.Loader` is able to deal is problems related to unsatisfied links, but not with checking if a binary is adequate for a particular CPU platform.

DL4J is able to display a message when the generic CPU binaries are used on an AVX2-capable system, so I would expect automatically using the AVX2 binaries on should also be possible.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta6
* Platform information (OS, etc): Linux (Debian/Ubuntu)

#### Additional Information

<details>
<summary>Crash log</summary>
<pre>
Loading .../.javacpp/cache/nd4j-native-1.0.0-beta6-linux-x86_64-avx2.jar/org/nd4j/nativeblas/linux-x86_64-avx2/libnd4jcpu.so
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007f7e71e50ae9, pid=2216, tid=0x00007f7eb26b9700
#
# JRE version: OpenJDK Runtime Environment (8.0_232-b09) (build 1.8.0_232-8u232-b09-0ubuntu1~18.04.1-b09)
# Java VM: OpenJDK 64-Bit Server VM (25.232-b09 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libnd4jcpu.so+0x52c0ae9]  nd4j::OpTracker::getInstance()+0x29
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# .../hs_err_pid2216.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
</pre>
</details>

<details>
<summary>Except from .../hs_err_pid2216.log</summary>
<pre>
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007f7e71e50ae9, pid=2216, tid=0x00007f7eb26b9700
#
# JRE version: OpenJDK Runtime Environment (8.0_232-b09) (build 1.8.0_232-8u232-b09-0ubuntu1~18.04.1-b09)
# Java VM: OpenJDK 64-Bit Server VM (25.232-b09 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libnd4jcpu.so+0x52c0ae9]  nd4j::OpTracker::getInstance()+0x29
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
</pre>
</details>

**Comment by saudet** [comment]
See https://github.com/eclipse/deeplearning4j/issues/7834#issuecomment-498170278 for some discussion.

**Comment by agibsonccc** [comment]
Closing due to: https://github.com/eclipse/deeplearning4j/issues/7834#issuecomment-498170278
