### ISSUE TITLE
Unexpected result when training (vs same Keras model)

### ISSUE THREAD

**Issue by montardon** [deeplearning4j/deeplearning4j#8625]
#### Issue Description
I have a Keras/Python model as .hdf5.
I build what I think is a same version using DL4J.

Learning curves looks good. Result is bad.
I can not explain it.
Here is the DL4J model : https://gist.github.com/montardon/2f0637c3ee038363109325eb62ce5d47
Here is the .hdf5 model : https://drive.google.com/open?id=1hsrPy1uflNlDrPiBF4AeSrtuxpFWY4-6

Anything wrong with the DL4J model ?

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version : 1.0.0-beta6
* Platform information (OS, etc) ; Ubuntu 18.04.3
* CUDA version, if used 10.1
* NVIDIA driver version, if in use 430.50

**Comment by agibsonccc** [comment]
Closing. For future readers, please post these kinds of issues to the forums: https://community.konduit.ai
