### ISSUE TITLE
Is Node2vec functional?

### ISSUE THREAD

**Issue by daanvdn** [deeplearning4j/deeplearning4j#8627]
#### Issue Description

hi could somebody tell me if `org.deeplearning4j.models.node2vec.Node2Vec` is usable? Already there seems to be a lot of implementation code, but it's been marked as 'under construction' (and also `@deprecated`)  for quite a few releases. Does anybody have an idea to what extent  `Node2Vec` can already be used? Or are parts of the implementation missing that make it completely unusable at this point? If so, is a functional dl4j implementation of Node2vec is underway?

#### Version Information

Deeplearning4j version: `1.0.0-beta6`

**Comment by agibsonccc** [comment]
@daanvdn this was tabled for now. For now, we're focusing in the near term on model import, inference, python execution, and running on ARM devices.
