### ISSUE TITLE
SameDiff: Add DType arg for ZerosLike, OnesLike, OneHot ops

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8656]
Supported now at the libnd4j level:
https://github.com/eclipse/deeplearning4j/issues/8605
https://github.com/eclipse/deeplearning4j/issues/8607

We should update SDBaseOps zeros/ones like methods to have an extra overload with dtype arg:
https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/samediff/ops/SDBaseOps.java#L3085-L3107

And also the class constructors, for example:
https://github.com/KonduitAI/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/shape/ZerosLike.java

**Comment by AlexDBlack** [comment]
Also range op - @alexanderst 
https://github.com/eclipse/deeplearning4j/issues/8606#issuecomment-580622993

**Comment by alexanderst** [comment]
Implemented.
I assume Range op was implemented earlier:
```
public SDVariable range(double from, double to, double step, DataType dataType) {
        return new Range(sameDiff(), from, to, step, dataType).outputVariable();
    }
```

**Comment by AlexDBlack** [comment]
Yes, all look OK on current master.
@alexanderst feel free to close issues (you should have rights like in this case?) when resolved.
