### ISSUE TITLE
Configuration Issue: Seq Classification LSTM into Dense

### ISSUE THREAD

**Issue by sachag678** [deeplearning4j/deeplearning4j#8658]
#### Issue Description

I want to take the output of two LSTMs that are classifying two sequences by using the output from the final timestep, and put them into a Dense layer and then get a combined classification. I currently have the following model:

```
val conf = new NeuralNetConfiguration.Builder()
      .seed(123) //Random number generator seed for improved repeatability. Optional.
      .updater(new Nadam(0.00001))
      .weightInit(WeightInit.XAVIER)
      .graphBuilder()
      .addInputs("input1", "input2")
      .addLayer("input1Layer", new LSTM.Builder().activation(Activation.TANH).nIn(1).nOut(3).build(), "input1")
      .addLayer("input2Layer", new LSTM.Builder().activation(Activation.TANH).nIn(1).nOut(3).build(), "input2")
      .addVertex("merge", new MergeVertex(), "input1Layer", "input2Layer")
      .inputPreProcessor("hidden", new RnnToFeedForwardPreProcessor())
      .addLayer("hidden", new DenseLayer.Builder().activation(Activation.TANH).nIn(3 + 3).nOut(100).build(), "merge")
      .addLayer("out", new OutputLayer.Builder().activation(Activation.IDENTITY).nIn(100).nOut(3).build(), "hidden")
      .setOutputs("out")
      .build();
```
The shape of input1 = [1, 1, 100] and input2 = [1, 1, 100]. 

I know that the RNNtoFeedForwardPreProcessor() squashes the entire output of the lstm instead of only taking the output from the final timestep so the data going into the dense layer is not what I need. I thought of using adding a LabelMask into the input, but does the network know to add them to the LSTM layer given they are not outputLayers. If I use rnnOutputLayers after the LSTM and before the merge, there seems to be an issue with learning as there seems to be a flag to ignore storing gradients on output layers so the fit fails when doing backprop. 

I'm not sure how to go about setting up this design. 

#### Version Information

libraryDependencies += "org.deeplearning4j" % "deeplearning4j-core" % "1.0.0-alpha"
libraryDependencies  += "org.nd4j" % "nd4j-native" % "1.0.0-alpha"
libraryDependencies += "org.nd4j" % "nd4j-api" % "1.0.0-alpha"
libraryDependencies += "org.nd4j" % "nd4j-native-platform" % "1.0.0-alpha"
libraryDependencies += "org.bytedeco.javacpp-presets" % "openblas" % "0.2.20-1.4.1" classifier "" classifier "linux-x86_64

**Comment by AlexDBlack** [comment]
Ok, couple of things here
First - upgrade to 1.0.0-beta6, you're using a pretty old version there.
Second - you can use LastTimeStep wrapper layer to get the last time step activations
https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/layers/recurrent/LastTimeStep.java#L30-L39

Like this:
```
.addLayer("input1Layer", new LastTimeStep(new LSTM.Builder().activation(Activation.TANH).nIn(1).nOut(3).build()), "input1")
```

That also works as you'd expect with (or without) mask arrays, so if you have variable length time series in a minibatch, it'll look at the mask to work out which positions in the array represent the last time step for each example.

**Comment by AlexDBlack** [comment]
I'll add that another option for sequence classification (sometimes it's better, especially if you don't want the network paying attention to more recent time steps) is to use a global pooling layer.
So LSTM1 -> GlobalPooling -> merge

https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/layers/GlobalPoolingLayer.java#L36-L60
