### ISSUE TITLE
Questions about Convolution1D Example for Multi-channel Use Case

### ISSUE THREAD

**Issue by zhangy10** [deeplearning4j/deeplearning4j#8662]
Hey Team,

I am just wondering do you have Convolution1D example available for multi-channel use cases, like for multi-channel sensing data. If not, can you please advise how to make the Convolution1D to fit the multi-channel cases? 

Many thanks.

**Comment by AlexDBlack** [comment]
No conv1d examples specifically that I'm aware of.
In terms of data pipelines though, DL4J's conv1d are basically the same as RNN layers. i.e., both types of layers use NCW - [minibatch, channels, width] / [minibatch, size, sequenceLength]

Was there something specifically you're stuck on? Constructing the net configuration? Building the data pipeline for a specific type of data?

**Comment by zhangy10** [comment]
Hi Alex, thanks. 
My case is that I would like to make a simple CNN model fit a bunch of acceleration sensing data but with multi-channel to classify user behavior. So, I am wondering how to construct a [minibatch, channels, width] net by using conv1d layer. For example, I have the input shape for [16, 8, 128] which refers to the NCW, how should I make the configuration by using conv1d layers to do so?

**Comment by zhangy10** [comment]
Should I do like this, taking the LeNet as an example, and input shape: [batch 16, height 1, width 128, depth 8]?

```
MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder().seed(1234)
                                           .activation(Activation.RELU)
                                           .weightInit(new NormalDistribution(0.0, 1.0))
                                           .updater(new Adam(0.0001))
                                           .convolutionMode(ConvolutionMode.Same)
                                           .list()
                                           // block 1
                                           .layer(new Convolution1DLayer.Builder()
                                                      .name("cnn1")
                                                      .kernelSize(1, 5)
                                                      .stride(1, 1)
                                                      .nIn(8)
                                                      .nOut(20)
                                                      .activation(Activation.RELU)
                                                      .build())
                                           .layer(new SubsamplingLayer.Builder(SubsamplingLayer.PoolingType.MAX)
                                                      .name("maxpool1")
                                                      .kernelSize(1, 2)
                                                      .stride(1, 2)
                                                      .build())
                                           // block 2
                                           .layer(new Convolution1DLayer.Builder()
                                                      .name("cnn2")
                                                      .kernelSize(1, 5)
                                                      .stride(1, 1)
                                                      .nOut(50)
                                                      .activation(Activation.RELU).build())
                                           .layer(new SubsamplingLayer.Builder(SubsamplingLayer.PoolingType.MAX)
                                                      .name("maxpool2")
                                                      .kernelSize(1, 2)
                                                      .stride(1, 2)
                                                      .build())
                                           // fully connected
                                           .layer(new DenseLayer.Builder()
                                                      .name("ffn1")
                                                      .activation(Activation.RELU)
                                                      .nOut(500)
                                                      .build())
                                           // output
                                           .layer(new OutputLayer.Builder(LossFunctions.LossFunction.MCXENT)
                                                      .name("output")
                                                      .nOut(10)
                                                      .activation(Activation.SOFTMAX) // radial basis function required
                                                      .build())
                                           .setInputType(InputType.convolutional(1, 128, 8))
                                           .build();
```

I am not sure if it works. If it works, It seems that we just need to replace the standard ConvolutionLayer to Convolution1DLayer, and update all height to be 1, right?

**Comment by zhangy10** [comment]
Also, if I would like to make an RNN model for the multi-channel case, how should I configure the net? It's like we have 8 lstm layers parallelly to fit the 8 channel time-series data and each channel should parallelly go through each lstm layer and flat the outputs before the final output layer. 

In this case, the net structure looks like a standard CNN with 3 channel image data pipeline, but replace the input to multi-channel time-series data.

**Comment by zhangy10** [comment]
@AlexDBlack I just found an old post to deal with the multivariate time series   https://github.com/eclipse/deeplearning4j/issues/2821.

In this code https://gist.github.com/turambar/b0e1f7eba07e2f0964e2849912093946#file-temporalconvolutionregressionexample-java-L122, it uses a standard ConvolutionLayer and sets the height as 1 to treat a multivariate time series with L timesteps and P variables as an L x P x 1 image (L rows high, P columns wide, 1, channel deep). It does make sense. 

But, can we use Convolution1D to do the same thing? I mean how to make the net configuration if using Convolution1D. And what if we use LSTM layers with NCW pipeline to treat the multivariate time series?

**Comment by AlexDBlack** [comment]
> So, I am wondering how to construct a [minibatch, channels, width] net by using conv1d layer.

Other than the data pipeline, you don't construct it - that's just what the conv1d uses.

> Should I do like this, taking the LeNet as an example, and input shape: [batch 16, height 1, width 128, depth 8]?

There's a few things wrong with this configuration
First, you are mixing conv1d layers and 2d subsampling layers (SubsamplingLayer).
if you use conv1d, and you want pooling, you should use Subsampling1DLayer instead

second, your input type is wrong - `.setInputType(InputType.convolutional(1, 128, 8))`
that, again, is for 2D convolutions
use InputType.recurrent instead (that should be taken to mean "sequence" or "time series")

Third, if you want sequence classification - use a global pooling layer followed by an output layer
so conv1d -> subsampling1d -> ... -> global pooling (max) -> outputlayer


> Also, if I would like to make an RNN model for the multi-channel case, how should I configure the net?

Exactly the same way, but replace your conv1d and subsampling1d layers with RNN layers like LSTM


> In this code https://gist.github.com/turambar/b0e1f7eba07e2f0964e2849912093946#file-temporalconvolutionregressionexample-java-L122, it uses a standard ConvolutionLayer and sets the height as 1 to treat a multivariate time series with L timesteps and P variables as an L x P x 1 image (L rows high, P columns wide, 1, channel deep). It does make sense.

Don't refer to that, it's from a 3 year old issue from before we had convolution1d support.
Use what I suggested instead.

**Comment by zhangy10** [comment]
@AlexDBlack Thanks for that.

I checked the ``` InputType recurrent(long size, long timeSeriesLength)```, but it seems that I cannot put the channel in this form because I need to process multivariate time series data which usually has more than 3 channels. So, how to config the net for the case? And, I didn't find any InputType that I could set the number for channels for conv1d or LSTM.

**Comment by AlexDBlack** [comment]
> it seems that I cannot put the channel in this form because I need to process multivariate time series data which usually has more than 3 channels.

Using InputType.recurrent has no such restriction to 3 channels or anything.
Note the size parameter - that's the number of channels for input. So if you have say 10 time series (10 channels), you set size=10

**Comment by zhangy10** [comment]
@AlexDBlack All right, I see. Thanks for that. I will have a try.

**Comment by AlexDBlack** [comment]
I'l close this as resolved - if you need more help, we can re-open the issue

**Comment by zhangy10** [comment]
@AlexDBlack I found a confusing question when using the ```InputType.recurrent``` to Convolution1DLayer.

For example, I have a conv layer, and the output shape is [16, 72, 3] represents [batch, channel, length]. And the output will be flatted as expected [16, 216] to a full layer. However, the output will be modified as [48, 72] by the ```RnnToFeedForwardPreProcessor``` when using ```InputType.recurrent``` as the input type. 

I double-check the source code of ```RnnToFeedForwardPreProcessor```, and here we have the implementation as below:

```
 public INDArray preProcess(INDArray input, int miniBatchSize, LayerWorkspaceMgr workspaceMgr) {
        //Need to reshape RNN activations (3d) activations to 2d (for input into feed forward layer)
        if (input.rank() != 3)
            throw new IllegalArgumentException(
                            "Invalid input: expect NDArray with rank 3 (i.e., activations for RNN layer)");

        if (input.ordering() != 'f' || !Shape.hasDefaultStridesForShape(input))
            input = workspaceMgr.dup(ArrayType.ACTIVATIONS, input, 'f');

        val shape = input.shape();
        INDArray ret;
        if (shape[0] == 1) {
            ret = input.tensorAlongDimension(0, 1, 2).permutei(1, 0); //Edge case: miniBatchSize==1
        } else if (shape[2] == 1) {
            ret = input.tensorAlongDimension(0, 1, 0); //Edge case: timeSeriesLength=1
        } else {
            INDArray permuted = input.permute(0, 2, 1); //Permute, so we get correct order after reshaping
            ret = permuted.reshape('f', shape[0] * shape[2], shape[1]);
        }
        return workspaceMgr.leverageTo(ArrayType.ACTIVATIONS, ret);
    }

```

Taking the example, we give [16, 72, 3] as the input, and we expect to flat the input to be [16, 216], but I am confused about why the code applies ```input.permute(0, 2, 1); ``` here? What does it mean? And the result is changed to be [16 *3=48, 72]. Why do we need to update the batch number here? 

As a result, I got an error here, because the label shape is [16, class], and the output [48, class] doesn't match the shape. 

I believe the ```shape[0]``` is the batch number in most of the cases, but why do we 'Permute' the order here? I think it should be ```ret = permuted.reshape('f', shape[0], shape[2] * shape[1]);```. Then, the output shape will match the label shape.

**Comment by zhangy10** [comment]
@AlexDBlack  I print both of using 1D cnn and 2D cnn with the same dataset as examples. The model is LeNet with 2 conv layers, 2 pooling layers, and 1 full layer.

```Using conv1D with the InputType.recurrent(8, 20):

input = [16, 8, 20] -> [batch, channel, length]

================================================================================
LayerName (LayerType)           nIn,nOut   TotalParams   ParamsShape            
================================================================================
cnn1 (Convolution1DLayer)       8,36       900           b:{1,36}, W:{36,8,3,1} 
maxpool1 (Subsampling1DLayer)   -,-        0             -                      
cnn2 (Convolution1DLayer)       36,72      7,848         b:{1,72}, W:{72,36,3,1}
maxpool2 (Subsampling1DLayer)   -,-        0             -                      
ffn1 (DenseLayer)               72,300     21,900        W:{72,300}, b:{1,300}  
output (OutputLayer)            300,6      1,806         W:{300,6}, b:{1,6}     
--------------------------------------------------------------------------------
            Total Parameters:  32,454
        Trainable Parameters:  32,454
           Frozen Parameters:  0
================================================================================
```


```Using conv2D with the InputType.convolutional(1, 20, 8):

input = [16, 8, 1, 20] -> [batch, channel, height, width]

==============================================================================
LayerName (LayerType)         nIn,nOut   TotalParams   ParamsShape            
==============================================================================
cnn1 (ConvolutionLayer)       8,36       900           b:{1,36}, W:{36,8,1,3} 
maxpool1 (SubsamplingLayer)   -,-        0             -                      
cnn2 (ConvolutionLayer)       36,72      7,848         b:{1,72}, W:{72,36,1,3}
maxpool2 (SubsamplingLayer)   -,-        0             -                      
ffn1 (DenseLayer)             216,300    65,100        W:{216,300}, b:{1,300} 
output (OutputLayer)          300,6      1,806         W:{300,6}, b:{1,6}     
------------------------------------------------------------------------------
            Total Parameters:  75,654
        Trainable Parameters:  75,654
           Frozen Parameters:  0
==============================================================================
```

As we can see, the major difference is the number of ffn1 nIn, 72 for conv1d and 216 for conv2d (expected). And it's because of using ```RnnToFeedForwardPreProcessor``` in the DenseLayer mentioned above. So, I am wondering, does it mean we cannot add DenseLayer after conv1d? If we use ```InputType.recurrent``` for conv1d, then ```RnnToFeedForwardPreProcessor``` will be selected. So, the error will be out there.

**Comment by zhangy10** [comment]
@AlexDBlack I double-check other LSTM examples again. I found the ```RnnToFeedForwardPreProcessor``` was consistently used through these examples. So, it is fine. I got a mistake about how to use conv1d or LSTM. And the way how I put the data into the models was incorrect. 

For example, I put [16, 8, 1, 20] as input and [16, 6] (batch, class) as labels into conv2d model, and it works fine. But I copy to put [16, 8, 20] and [16, 6] into conv1d model. And I didn't realize the shape of the labels should be the same with input's, which should be rank 3. That's why I got an error when computing the loss function. 

I think models in DL4j are really sensitive to input data shape, especially for time-series data like processing IMU, EMG, EEG data. I recommend that some good examples of these should be added to the project to help people quickly understand how different models work.

Anyways, thanks for your support.

**Comment by AlexDBlack** [comment]
So, to be clear: the RnnToFeedForwardPreProcessor does exactly one thing: it stacks time steps along the batch dimension, so that we can have time-distributed dense/CNN layers. You seem to expect it to do something else, closer to what I've described below?

Depending on the task, you have a couple of options.

For squence classification (time series in, single prediction for the whole time series out): Use your Conv1d/subsampling1d layers and flatten to 2d format, in one of two ways:
1. Use a global pooling layer - max or average pooling
2. For _fixed length time series cases only_ you can use a reshape preprocessor (input to your dense layer then has shape [minibatch, numSteps * sizePerStep]
the final layer is an OutputLayer

For time series classification (time series in, time series of predictions - one for each time step - out):
Use a RnnOutputLayer instead of an OutputLayer, as that one handles sequences

cc @treo re: examples request (also need to review the examples re: use of manual preprocessors, we should rely on setInputType whenever possible)

**Comment by zhangy10** [comment]
@AlexDBlack Thanks for that. I double-check conv1d and rnn models again. I found only change the label shape cannot work for models. 

After checking the source code, I think the first parameter of ```InputType.recurrent``` doesn't refer to 'channel', and it refers to the number of classes. For example, If I put [16, 8, 20] as input, the label shape should be the same as [16, 8, 20] to fit the pipeline. But in the case, 8 is not the number of classes, and it should be 6. If I put [16, 6] to rnn-based pipelines, I will get an error when computing loss function. Because the given label shape rank is not 3. The ``` RnnToFeedForwardPreProcessor``` does change the input shape of Outputlayer from 3d to 2d as mentioned above, and the label will also need to be changed from 3d to 2d to match the input in the loss function. I think this transform and using ``` InputType.recurrent``` in conv1d or rnn models are fine for single-channel time-series data like audio, texts, but it doesn't work for multi-channel time-series data. So, I think there is a misunderstanding about the multivariate time series.

In my case, for example, the IMU data is multi-channel time-series data, and each sequence of sensing data should be parallelly processed by models. The way is similar to process 3-channel image data. So, it's not the case that 'one for each time step'. It's like the input will have multiple dimensions and each of them is a sequence by time. It's like an image but its height is 1 with more than 3 channels.

I tried to use conv2d, and it works fine. But I intend to use TCN to process, and it has to use conv1d. The conv1d seems to be limit to multi-channel time-series data. So, I am stuck here. 

For example, I have [16, 8, 20] (batch size, channel size, width of sequence) as input, and the label should be 2d [16, 6] (batch size, number of classes). Honestly, I don't think ```InputType.recurrent``` could work, and LSTM could not work as well, but I might be wrong. So, can you please advise me how to use conv1d or LSTM for this case? Thanks again.

**Comment by zhangy10** [comment]
@AlexDBlack I think we can use ``` convolutionMode(ConvolutionMode.Causal) ``` even for conv2D, right? Can we just set height as 1 to logically make conv2d to conv1d, and set the ``` dilation(d) ``` to make it as TCN? And the order of INDArray should be 'c' based on conv2d, right? 

If so, that would be much easier to run the data.

**Comment by zhangy10** [comment]
@AlexDBlack I just test and the causal convolution mode can only be used with conv1d in the beta6. I thought it could work because I saw there were similar causal codes in the conv2d. So, it hasn't been tested? Or not finished to support conv2d?
