### ISSUE TITLE
Is pretrain() unsupervised and how does it work?

### ISSUE THREAD

**Issue by MarvinBertin** [deeplearning4j/deeplearning4j#867]
How does pretrain() work and in what context is it the most useful?

**Comment by AlexDBlack** [comment]
For these sorts of questions, please ask on gitter: https://gitter.im/deeplearning4j/deeplearning4j
You'll get a much faster response there
see also http://deeplearning4j.org/documentation.html which should answer many of your questions
if you are new to deep learning, start here: http://deeplearning4j.org/deeplearningpapers.html
