### ISSUE TITLE
libnd4j: upgrade mkldnn version

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#8673]
We should upgrade mkldnn version to 1.2 and start using its new MatMul primitive as gemm replacement for F32/F16/BF16/I8/U8 data types

**Comment by saudet** [comment]
Let's be careful not to rely on MKL-DNN/DNNL too much.
It might never support, for example, ARM: https://github.com/intel/mkl-dnn/issues/27

**Comment by raver119** [comment]
absolutely agreed!

With best regards,
raver119
5 февр. 2020 г., 08:49 +0300, Samuel Audet <notifications@github.com>, писал:

**Comment by raver119** [comment]
Implemented and merged
