### ISSUE TITLE
Operation sequence_mask in libnd4j doesn't support arbitrary output types

### ISSUE THREAD

**Issue by alexanderst** [deeplearning4j/deeplearning4j#8674]
Currently sequence_mask supports only boolean output types, though there's data type argument.
Tensorflow version supports any data types, including floating.

```
import tensorflow as tf
sess = tf.InteractiveSession() 
res = tf.sequence_mask([1, 3, 2], 5, tf.dtypes.float32)
res.eval()
```

Result is:
array([[1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0.]], dtype=float32)

Also consider changing data type argument type from INT_ARG to D_ARG if feasible.

**Comment by raver119** [comment]
@shyrma @shugeo ^^^
