### ISSUE TITLE
libnd4j: unsorted_segment_sqrt_n fails for certain inputs

### ISSUE THREAD

**Issue by alexanderst** [deeplearning4j/deeplearning4j#8676]
When running Java test got this error:
unsorted_segment_sqrt_n: segment indices should be in range [0, 1), but -458538736 > 1

Failing test : 
```
@Test
    public void testSqrtN() {
        INDArray segments = Nd4j.create(new double[]{0,0,0,1,2,2,3,3}, new long[]{8}).castTo(DataType.INT);
        INDArray data = Nd4j.create(new double[]{5,1,7,2,3,4,1,3}, new long[]{8});
        INDArray[] ret = Nd4j.exec(new UnsortedSegmentSqrtN(data,segments,1));
    }

**Comment by AlexDBlack** [comment]
This looks like a bad test to me, coupled with a simple formatting error message for legitimate validation.
`new UnsortedSegmentSqrtN(data,segments,1)` - that constructor is:
`public UnsortedSegmentSqrtN(SameDiff sameDiff, SDVariable data, SDVariable segmentIds, int numSegments) {`
https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/transforms/segment/UnsortedSegmentSqrtN.java

i.e., numSegments = 1 in the test, but clearly the indices have values 0, 1, 2 and 3.
numSegments must be at least 4 for this test to make sense.

**Comment by shugeo** [comment]
TF says follows on the test above:
File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: segment_ids[3] = 1 is out of range [0, 1) [Op:UnsortedSegmentSum]
But when num_of_segments is 4 (for unsorted_segments_* this arg is mandatory), then result is
<tf.Tensor: id=26, shape=(4,), dtype=float32, numpy=array([7.5055537, 2.       , 4.9497476, 2.828427 ], dtype=float32)>

**Comment by shugeo** [comment]
So, only error message should be fixed?

**Comment by AlexDBlack** [comment]
So yes, it's a bad test, specifically numSegments = 1 is wrong. I'll close this then.

**Comment by AlexDBlack** [comment]
@shugeo yes, let's improve error message though

**Comment by shugeo** [comment]
I've fixed error messages for all unsorted segments as fix for this bug.
