### ISSUE TITLE
PyErr_Print not outputting anything

### ISSUE THREAD

**Issue by tobq** [deeplearning4j/deeplearning4j#8686]
#### Issue Description

From the `GymEnv#checkPythonError()`, nothing is outputted to the console when an error occurs

#### Additional Information

* Platform: Windows
* pom.xml: https://gist.github.com/tobq/6e5bff34cab3c2d226cea0bc26e86990

**Comment by saudet** [comment]
If you could, please ask upstream whether it's possible to do that or not. It would be helpful! Thanks

**Comment by saudet** [comment]
@farizrahman4u In the end, have you found a way around that?

**Comment by tobq** [comment]
> If you could, please ask upstream whether it's possible to do that or not. It would be helpful! Thanks

Who are you referring to when you mention "upstream"? Are they the author(s) of the CPython library you're using?

**Comment by tobq** [comment]
It seems this was an issue with intellij (when "running project"). Ive I build and execute my project outside of intellij I start getting python logs. I don't know why this happens though

**Comment by tobq** [comment]
For some reason, instead of continuous logs from python (like when i run outside of intellij), i get massive bursts of logs, 2 minutes or so apart, in intellij. This is probably why I'm seeing no python error logs, because the program crashes before it gets the chance to relay the logs. My logs are currently being spammed with this:
`[2009615739]
[2009615739]
[2009615739]
[2009615739]
[2009615739]
[2009615739]
[2009615739]
[2009615739]
[2009615739]
[2009615739]
[2009615739]
[2009615739]
[2009615739]
[2009615739]`

I suspect this is coming from env.reset() but I'm not explicitly logging anything. Its very annoying, is it possible to suppress this?

**Comment by saudet** [comment]
Yes, I'm talking about CPython: 
https://www.python.org/community/lists/
https://docs.python.org/3/bugs.html

**Comment by saudet** [comment]
If this looks like a problem with IntelliJ IDEA, then "upstream" means there:
https://youtrack.jetbrains.com/issues/IDEA
