### ISSUE TITLE
Lack of functional environments

### ISSUE THREAD

**Issue by tobq** [deeplearning4j/deeplearning4j#8688]
#### Issue Description
I opened an issue earlier regarding the pendulum task not working (which is because it has a continuous action-space).

From the classic control section of the available tasks, the working tasks are
* Acrobot-v1,
* CartPole-v1
* and MountainCar-v0

MountainCarContinuous-v0 and Pendulum-v0 (for now) expectedly don't work, due to their continuous action-spaces.

However, from my experiments, no other tasks (outside of "classic control") work. So from the large range of tasks provided by OpenAi's platform, only 3 are working within rl4j-gym...

I don't know if the other's aren't working due to dependency issues (the ones I tried have discrete action spaces), because there's no information passed regarding the python errors occurring, only information on the fact that a python _has occurred_.

#### Additional Information

* Platform: Windows
* pom.xml: https://gist.github.com/tobq/6e5bff34cab3c2d226cea0bc26e86990

**Comment by saudet** [comment]
The ones listed here use continuous actions, so they won't work: https://github.com/eclipse/deeplearning4j/issues/5264#issuecomment-390607276
Apart from those, which ones exactly are not working?

**Comment by tobq** [comment]
For bipedal walker i get the error: `AttributeError: module 'gym.envs.box2d' has no attribute 'BipedalWalker'`

**Comment by saudet** [comment]
BipedalWalker has continuous actions.

**Comment by tobq** [comment]
Same for `LunarLander-v2`, which has a discrete action space

**Comment by tobq** [comment]
@saudet I've checked around and this is seems to be a dependency issue - box2d-py missing. Is the gym supposed to have this set up?

**Comment by saudet** [comment]
LunarLander also needs continuous actions. If you find any environment that doesn't use continuous actions and does not work, then, yes, please let me know.

**Comment by tobq** [comment]
@saudet It uses (4) discrete actions.

**Comment by saudet** [comment]
I see, we need an additional dependency on Box2D for this to work...

**Comment by tobq** [comment]
@saudet I ended up implementing my own "gym4j" with box(any-dimensional)/discrete actions and box2d tasks working https://github.com/tobq/gym4j

**Comment by saudet** [comment]
That's cool. We can do the same with JavaCPP and it's going to be a lot more efficient. If you'd like to make a contribution, you're more than welcome!

**Comment by tobq** [comment]
That'll be good to see

**Comment by saudet** [comment]
For me, after calling `pip3.7 install --user gym[box2d]`, RL4J works just fine with `LunarLander-v2`. If you're installing these libraries in a non-standard location though, I've added a `Py_AddPath()` helper method for those cases in pull #8717. We can call it like this before initializing RL4J:
```java
org.bytedeco.cpython.helper.python.Py_AddPath("/path/containing/Box2D");
env = new GymEnv("LunarLander-v2", false, false, 123);
```
Still, for a more user-friendly experience, we could obviously bundle Box2D and anything else as part of the JavaCPP Presets... As usual, contributions are welcome!

@farizrahman4u We should also change those `Py_SetPath()` calls to `Py_AddPath()` in DataVec. That will provide more flexibility for users since CPython apparently ignores `PYTHONPATH` when we call `Py_SetPath()`.
