### ISSUE TITLE
Java: conv2d - add support for weights format arg (for cuDNN)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8690]
Currently we hardcode YXIO (kH, kW, iC, oC) format.

For efficient cuDNN execution, I believe we need OIYX and OYXI formats for conv2d weights.

We also need to check:
* Other operations for cuDNN - conv3d, depthwise, etc etc
* Operations for MKLDNN (DNNL) - presumably there's a preferred

**Comment by shyrma** [comment]
done!

**Comment by AlexDBlack** [comment]
Thanks @shyrma 
I'll leave this issue open for the Java side update that also needs to be done...

**Comment by raver119** [comment]
Any news guys?

**Comment by AlexDBlack** [comment]
Basically done here - https://github.com/KonduitAI/deeplearning4j/pull/356
Initial tests are passing.

**Comment by AlexDBlack** [comment]
Merged here: https://github.com/KonduitAI/deeplearning4j/pull/367
New tests are confirmed passing
