### ISSUE TITLE
FineTune failed by SameDiffLayer's UnsupportedOperationException

### ISSUE THREAD

**Issue by liweigu** [deeplearning4j/deeplearning4j#8691]
#### Issue Description

Please describe our issue, along with:
- expected behavior
1) define a graph model with **RecurrentAttentionLayer**, the layer is added by the code like
`graphBuilder.addLayer("attension1", new RecurrentAttentionLayer.Builder().activation(Activation.SOFTSIGN)
		.updater(new Adam(learningRateSchedule)).nHeads(5).headSize(40).nIn(nIn).nOut(nOut).build()
		, "lstm1");`
2) train the model, and save it to file.
3) load the saved model, and do finetuning by the code like
`model = graphBuilder
		.removeVertexAndConnections("output")
		.addLayer("newOutput", outputLayer , "dense2")
		.setOutputs(outputNames)
		.build();`
this code only replace the outputLayer, so that the model layers are changed.
4) train the new model, expected to run without Exception.

- encountered behavior
4) train the new model, and get UnsupportedOperationException from org.deeplearning4j.nn.layers.samediff.SameDiffLayer.setParams(),
which is from org.deeplearning4j.nn.transferlearning.TransferLearning.build() at line 990:
https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/transferlearning/TransferLearning.java#L990

By rewrite the org.deeplearning4j.nn.layers.samediff.SameDiffLayer.setParams() method to omit the code `throw new UnsupportedOperationException("Not supported");` , the finetuned model can run training.
I think other layers extended from SameDiffLayer would produce the same exception.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
1.0.0-beta6
* Platform information (OS, etc)
ubuntu 16.04
* CUDA version, if used
* NVIDIA driver version, if in use

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by AlexDBlack** [comment]
Thanks for reporting this, I'll take a look and report here once I have something to share.
