### ISSUE TITLE
Documentation: Details on parameter tuning,weight initialization, etc

### ISSUE THREAD

**Issue by MarvinBertin** [deeplearning4j/deeplearning4j#870]
Some issues that could be better explained in DL4J documentation:
- What are general guidelines for parameter tuning (L1, L2, batchSize, learningRate, dropOut). Is grid search feasible?
- How does pretrain() work and in what context is it the most useful?
- What kind of initialization is XAVIER?
- What does ScoreIterationListener do and what are its parameters?

[Edited by Alex]

**Comment by agibsonccc** [comment]
Please change these in to doc issues. Sorry this was a communication issue
on my part.

**Comment by chrisvnicholson** [comment]
Xavier is now documented. http://deeplearning4j.org/glossary.html#xavier h/t Alex Black.

**Comment by tomthetrainer** [comment]
I am creating a new issue for the Listeners.

**Comment by tomthetrainer** [comment]
I believe this is adequately covered in the docs, although I would agree perhaps not in an orderly fashion.  

See here: https://deeplearning4j.org/troubleshootingneuralnets

And pretrain was also recently documented

Open a specific ticket on a specific issue if you find we missed something.
