### ISSUE TITLE
Libnd4j fails to compile on armv8 jetson nano

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#8714]
#### Issue Description

LIbnd4j fails to compile due to the attached screenshot
![IMG_20200217_141125](https://user-images.githubusercontent.com/1144306/74627008-e52a8480-5194-11ea-8aff-061bf01c538b.jpg)

Please describe our issue, along with:
- expected behavior
Compiles
- encountered behavior
Does not compile
#### Version Information
Snapshots
Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
Snapshot
* Platform information (OS, etc)
Jetson nano Jetpack 4.3.
* CUDA version, if used
10.0
* NVIDIA driver version, if in use

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
Workaround merged.

**Comment by agibsonccc** [comment]
Confirmed compiles.
