### ISSUE TITLE
DL4J FastText - wordsNearest and similar methods

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8720]
Currently, if we do .wordsNearest(word, n) on a FastText binary model, we get a NullPointerException, due to the modelUtils field being null.

```
java.lang.NullPointerException
	at org.deeplearning4j.models.fasttext.FastText.wordsNearest(FastText.java:445)
	at org.deeplearning4j.models.fasttext.FastTextTest.testPredict(FastTextTest.java:123)
```

We need one of 2 things here:
1. If FastText binary models _can_ support words nearest, we should make it work, OR
2. If we can't support words nearest, we should throw a useful exception (explaining to the user why it's not possible, and their options, if any)

**Comment by aliakhtar** [comment]
Alternatively, since there's a `setModelUtils` method on `FastText.java`, perhaps there's a way to provide a modelUtils using the binary model (or one could be created automatically when the binary model is passed in)?

**Comment by alexanderst** [comment]
Meaningful exception added. Complete functionality for binary models can't be implemented for now due to fastText API restrictions.

**Comment by AlexDBlack** [comment]
Right, internally we're using the C++ FastText API. So short of implementing our own (from scratch - which might happen one day) version of FastText, we're limited to what they provide.
