### ISSUE TITLE
Unable to import Many-to-one LSTM Keras model

### ISSUE THREAD

**Issue by YusufuShehu** [deeplearning4j/deeplearning4j#8722]
#### Issue Description

Importing an LSTM model using Keras (Functional API) v2.3.1 with Tensorflow v2.1.0. I am using the configuration return_sequences=False for my LSTM layer. I am importing the model using:

ComputationGraph graph = KerasModelImport.importKerasModelAndWeights(model,true);

I get the following stack trace:

https://gist.github.com/YusufuShehu/19cf57ccc908ccd69e6969d9e471cfc4

I have seen in previous [issues](https://github.com/eclipse/deeplearning4j/issues/4295) that this may have been resolved. Also in 1.0.0-alpha, it is explicitly said this bug is fixed. 

How can I fix this issue?

#### Version Information

* Deeplearning4j 1.0.0-beta6
* Platform information OSX

#### Additional Information

POM: https://gist.github.com/YusufuShehu/24cf252b5dde5049223ccb979af2b932

**Comment by agibsonccc** [comment]
Closing since we support tf.keras now. Open a new issue if something similar comes up.
