### ISSUE TITLE
The Cartpole example can't converge

### ISSUE THREAD

**Issue by hanbaoan123** [deeplearning4j/deeplearning4j#8727]
#### Issue Description

When I run the example cartpole with the default parameters, it can not converge to the max reward 200, I wonder what went wrong.
![360截图20200224095510956](https://user-images.githubusercontent.com/32160782/75124829-a2186600-56ec-11ea-88da-b648bb1530a4.jpg)

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version beta6
* Platform information (OS, etc) windows 10
* CUDA version, if used CUDA 10.0
* NVIDIA driver version, if in use 431.40

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

**Comment by saudet** [comment]
@RobAltena

**Comment by RobAltena** [comment]
There is an updated cartpole example here: https://github.com/RobAltena/cartpole

But it uses the daily snapshots for now.

**Comment by hanbaoan123** [comment]
> There is an updated cartpole example here: https://github.com/RobAltena/cartpole
> 
> But it uses the daily snapshots for now.

So what's going on? Are the parameters inappropriate？

**Comment by RobAltena** [comment]
I do not know what exactly was wrong with the old example. But the new one uses an entirely different neural network. I has more nodes and we use a different optimizer.
