### ISSUE TITLE
Download of zoo models not possible

### ISSUE THREAD

**Issue by DanielRaapDev** [deeplearning4j/deeplearning4j#8728]
#### Issue Description

I wanted to use a pretrained network from the zoo (YOLO2). But the download of the data failed:
```
java.io.IOException: Server returned HTTP response code: 403 for URL: https://deeplearning4jblob.blob.core.windows.net/models/yolo2_dl4j_inference.v3.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1913)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at java.base/java.net.URL.openStream(URL.java:1117)
	at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1456)
	at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:77)
	at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:54)[...]
```
When calling the URL with a browser the result is the following XML:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Error>
    <Code>AccountIsDisabled</Code>
    <Message>The specified account is disabled.
RequestId:14c517dc-701e-005f-2ee0-eae7c8000000
Time:2020-02-24T07:03:15.0854682Z</Message>
</Error>
```
This error seems not specific to that file. It is also displayed for https://deeplearning4jblob.blob.core.windows.net/models/

#### Version Information

Deeplearning4j version:
I used 1.0.0-beta5, but in master the file [DL4JResources.java](https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-common/src/main/java/org/deeplearning4j/common/resources/DL4JResources.java) also contains that URL.

#### Additional Information

Code that yields the exception:
```java
Model pretrained = YOLO2.builder()
	.build()
	.initPretrained();
```

**Comment by treo** [comment]
I think your eyes played a trick on you there, the url on [master](https://github.com/eclipse/deeplearning4j/blob/47d19908f46239f44c381059fa5608eb0d6218ac/deeplearning4j/deeplearning4j-common/src/main/java/org/deeplearning4j/common/resources/DL4JResources.java#L47), and [beta6](https://github.com/eclipse/deeplearning4j/blob/deeplearning4j-1.0.0-beta6/deeplearning4j/deeplearning4j-common/src/main/java/org/deeplearning4j/common/resources/DL4JResources.java#L47), is `https://dl4jdata.blob.core.windows.net/` and *not* `https://deeplearning4jblob.blob.core.windows.net/`.

So just updating to beta6 should solve your issue.

**Comment by DanielRaapDev** [comment]
Thx. Haven't seen that difference. I just read dl4j...blob....windows.net :/
