### ISSUE TITLE
UnsupportedKerasConfigurationException: Unsupported keras layer type TokenEmbedding. 

### ISSUE THREAD

**Issue by FelipeQuirce** [deeplearning4j/deeplearning4j#8730]
#### Issue Description

Please describe our issue, along with:
I'm trying to import keras model (BERT), and I'm getting the following exception.
org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type TokenEmbedding

#### Version Information
 1.0.0-beta6

#### Additional Information

Where applicable, please also provide:
[exception stacktrace](https://gist.github.com/FelipeQuirce/44aac4845db818087328c7e3192fd341)
#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by AlexDBlack** [comment]
Is this a TensorFlow 2.0 Keras model? TF 2.0 Keras model format is incompatible with the original "multi-backend" Keras model format that DL4J supports (you'd very likery run into an issue if you went from tf.keras to multi-backend keras too).

TF 2.0 Keras model format support is being worked on, but it's a know issue for 1.0.0-beta6.
https://github.com/eclipse/deeplearning4j/issues/8348

**Comment by agibsonccc** [comment]
This is a custom layer: https://github.com/CyberZHG/keras-bert/blob/master/keras_bert/layers/embedding.py I'm closing this. You can register custom layers with our keras import, more here: https://deeplearning4j.konduit.ai/keras-import/overview
