### ISSUE TITLE
restoreMultiLayerNetwork() needlessly writes temp-file

### ISSUE THREAD

**Issue by horschi** [deeplearning4j/deeplearning4j#8735]
#### Issue Description
restoreMultiLayerNetwork(InputStream is, boolean loadUpdater) internally writes a temporary ZIP file and then reads it.
My expectation would be that the InputStream is directly read using a ZipInputStream.

This would be faster, more robust and does not rely on the fact that there is write-access on the temp folder. 

#### Version Information
* Deeplearning4j version: 1.0.0-beta6
* Platform information (OS, etc): Linux

#### Contributing
Here is how I would imagine restoreMultiLayerNetwork() to read the state: 
```
			try (final ZipInputStream zis = new ZipInputStream(is))
			{
				while (true)
				{
					final ZipEntry zipEntry = zis.getNextEntry();
					if (zipEntry == null)
						break;
					.... TODO: if/else that checks for filename ...
					zis.closeEntry();
				}
			}
```
I could create a patch file with the necessary changes if it helps.

**Comment by raver119** [comment]
Great! Send us PR please!

**Comment by horschi** [comment]
@raver119 Sorry, I had to make a typo fix.

I am currently testing the ModelSerializer with my application.

**Comment by horschi** [comment]
@raver119 I merged my changes into my local dl4j beta6 and tested successfully with my application. I was able to write/read my models from and to streams.

The reason why i stumbled on this was because of a weird performance issue, where the model load would take up to 3 minutes. This behaviour is now gone. Unfortunetaly I was not able to exactly pin point the root cause of the delay.

**Comment by raver119** [comment]
great! is your pr ready for review/testing?

**Comment by horschi** [comment]
@raver119 Yes. Are there any automated tests that cover this? I only tested the serialization from my application. Could anyone run the automated tests? The DL4j project does not compile properly on my machine.

**Comment by raver119** [comment]
Yep, that's trivial. However, you also need to sign eclipse contributor agreement there

**Comment by horschi** [comment]
@raver119 I squashed and signed. Is that what you had in mind?

**Comment by raver119** [comment]
I mean this thing: https://www.eclipse.org/legal/ECA.php

**Comment by raver119** [comment]
https://accounts.eclipse.org/user/eca

**Comment by horschi** [comment]
@raver119 Signed.

**Comment by raver119** [comment]
:+1: now we're waiting for jenkins then

**Comment by horschi** [comment]
@raver119 Thanks for all your help, also on stackoverflow ;-)
