### ISSUE TITLE
Dl4j InvalidKerasConfigurationException during model import "Failed to set weights for parameter W"

### ISSUE THREAD

**Issue by aaronalbin** [deeplearning4j/deeplearning4j#8741]
#### Issue Description
I am attempting to load a pre-trained Keras model (with TF backend) from python into Dl4j. I have successfully done this with simple feed-forward models, but I am having various issues loading more complex models built with the Keras functional API.

Please let me know if there are any work-arounds that can be done in the python code to conform to the Dl4j library.

A potentially related issue: https://github.com/eclipse/deeplearning4j/issues/8620

* Expected behavior: ComputationGraph model loads and can be used for inference via model.output(...)
* Encountered behavior: Exception thrown when calling KerasModelImport.importKerasModelAndWeights: `org.deeplearning4j.nn.modelimport.keras.exceptions.InvalidKerasConfigurationException: Cannot assign arrays: arrays must both be scalars, both vectors, or shapes must be equal other than size 1 dimensions. Attempting to do x.assign(y) with x.shape=[256, 50, 1, 1] and y.shape=[256, 33, 1, 1]`

#### Version Information
* Dl4j: 1.0.0-beta6
* Nd4j: 1.0.0-beta6
* OS: MacOS Majave 10.14.6
* Python: 3.7.6
* Keras: 2.3.1
* Tensorflow (as backend): 2.1.0
* CUDA: N/A
* NVIDIA driver: N/A

#### Additional Information
This gist contains the model summary, python / Java code, and stack trace:
https://gist.github.com/aaronalbin/0d100e6df56651c8c99cedd48f82db1d

Update (June 7, 2020): I tried the same model import with Dl4j 1.0.0-beta7 since I saw the release notes mention potentially relevant bug fixes, namely "improvements to Keras import for reshape, permute, etc operations due to NHWC and NWC support in DL4J". However, it still throws the same exception message.

#### Contributing
I am open to contributing. Any guidance in this regard is welcome.

**Comment by agibsonccc** [comment]
@aaronalbin  I did a pass on keras import recently and we're going to squash all the keras issues before release.  I think it was related to NWHC/NCHW. I fixed that. I'm closing this assuming that's the case. Happy to re test if an issue comes up though.
