### ISSUE TITLE
Kotlin support for ND4J

### ISSUE THREAD

**Issue by LifeIsStrange** [deeplearning4j/deeplearning4j#8749]
Can the Ndarray (ND4J) be used in kotlin code? 
I was reading somewhere that Kotlin hasn't ndarrays, but if we can seamlessly use ND4J in kotlin, then Kotlin has first class support for Ndarrays.

**Comment by raver119** [comment]
Yes it is possible.

We even have examples for that: https://github.com/eclipse/deeplearning4j-examples/tree/master/dl4j-examples/src/main/kotlin/org/deeplearning4j/examples/feedforward/mnist

**Comment by vidheyoza** [comment]
This link seems broken. Can anyone point me to the fixed version?

**Comment by agibsonccc** [comment]
@vidheyoza https://github.com/eclipse/deeplearning4j-examples/tree/master/dl4j-examples/src/main/kotlin

For further queries, feel free to go to https://community.konduit.ai/

**Comment by vidheyoza** [comment]
Got it. Thanks a lot!
