### ISSUE TITLE
Documentation: Details on Iterative Averaging of Model Parameters

### ISSUE THREAD

**Issue by sberajaw** [deeplearning4j/deeplearning4j#875]
I've seen references to this in a couple of places (Deeplearning4j on Spark page and Training Tricks), but really interested in the details on Iterative Averaging. For example, when employing data parallelism, does it matter how many partitions the dataset has? For each partition, should SGD being performed (one step/iteration) and then the resulting model sent to the master to be averaged with other models? To minimize network overhead, would it make more sense to perform a few steps/iterations of SGD on each partition and then average the results? Should a certain number of training examples be in each partition on average? Would Iterative Averaging work well for training most/all neural nets? 

I'm trying to compare an averaging approach with one where Hogwild SGD is used and hoping to get accuracy that's close and a reasonable speed up. 

I personally have not seen acceptable results with the averaging approach. When I have fewer partitions (~5) the accuracy seems close, but as I increase the number of partitions and parallelize more computation, the accuracy goes down for some reason.

Any guidance would be much appreciated.

**Comment by agibsonccc** [comment]
http://deeplearning4j.org/spark
