### ISSUE TITLE
How to use GPU to accelerate?

### ISSUE THREAD

**Issue by unkper** [deeplearning4j/deeplearning4j#8756]
#### Issue Description

I am a senior and currently using RL4J for reinforcement learning.However, I don't know how RL4J USES GPU acceleration. Can anyone recommend me some documents on this?Thank you very much!

**Comment by treo** [comment]
RL4J uses the same backend mechanisms as DL4J. 
Take a look at https://deeplearning4j.org/docs/latest/deeplearning4j-config-gpu-cpu
