### ISSUE TITLE
libnd4j: CUDA - pairwise boolean transforms: wrong datatype for shape calculation

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8758]
https://gist.github.com/AlexDBlack/a5fb62467afc5eaf92cb0b00122ba1c6

CPU is correct (bool type). CUDA is wrong (float type).
Seems to impact all boolean ops - greater_equal, greater, not_equals, etc

```
DynamicCustomOp op = DynamicCustomOp.builder("greater_equal")
        .addInputs(Nd4j.create(DataType.FLOAT, 3), Nd4j.create(DataType.FLOAT, 3))
        .build();
List<LongShapeDescriptor> l = op.calculateOutputShape();
```

CPU:
```
[1,3,1,524288,1,c]
```

CUDA:
```
[1,3,1,8192,1,c]
```

**Comment by raver119** [comment]
It must be Java then.

**Comment by AlexDBlack** [comment]
I've stepped through this carefully in the debugger, I'm quite sure it's not a java side problem.
As far as I can tell the shape pointer returned from C++ definitely contains the wrong datatype for the output shape on CUDA only.

https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-cuda/src/main/java/org/nd4j/linalg/jcublas/ops/executioner/CudaExecutioner.java#L1946-L1960

https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/linalg/cpu/nativecpu/ops/NativeOpExecutioner.java#L1772

**Comment by raver119** [comment]
Yes, it's "same dtype" thing. But I'm sure nd4j CPU overrides this option for this op group.

**Comment by AlexDBlack** [comment]
There's no overriding on CPU on the Java side that I can see:
NativeOpExecutioner.getShapeFromPointer has extras arg 524288 right out of c++ - there's no overriding of that between the loop.calculateOutputShapes2 call in NativeOpExecutioner an the LongPointer.get(int) call in getShapeFromPointer to extract shape info values

CudaExecutioner.getShapeFromPointer has extra arg 8192 right out of the pointer.

**Comment by raver119** [comment]
Hmmmmm....

**Comment by raver119** [comment]
Fixed/implemented in my branch. Will merge later.
