### ISSUE TITLE
libnd4j: sequence_mask op should zero mask 0 entries

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8760]
Tested on CPU backend.

```
    @Test
    public void testSeqMask(){
        INDArray arr = Nd4j.createFromArray(1,2,3);
        INDArray maxLen = Nd4j.scalar(4);

        INDArray out = Nd4j.create(DataType.INT32, 3, 4);
        out.assign(Integer.MAX_VALUE);

        Nd4j.exec(DynamicCustomOp.builder("sequence_mask")
                .addInputs(arr, maxLen)
                .addOutputs(out)
                .build()
        );

        INDArray exp = Nd4j.createFromArray(new int[][]{
                {1, 0, 0, 0},
                {1, 1, 0, 0},
                {1, 1, 1, 0}});

        assertEquals(exp, out);
    }
```

![image](https://user-images.githubusercontent.com/2360237/76043297-31eec780-5fab-11ea-9ebd-4386fc5ae506.png)

**Comment by raver119** [comment]
That's easy fix, i.e. NDArray::nullify called on outputs. But it also overlaps with the other thing we're looking into now: general outputs nullification issue. Some ops do need nullified outputs, others - don't. So we need to draw a line, and nullify outputs in ops that require nullification, and do not nullify outputs in other ops. That will also improve Graph execution performance.

**Comment by AlexDBlack** [comment]
Confirmed fixed - thanks
