### ISSUE TITLE
Keras Model Import 

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/deeplearning4j#8762]
beta6 - checked on CPU only

1) Incorrect return type for bidirectional LSTM with a preprocessor present. Fixed [here](https://github.com/KonduitAI/deeplearning4j/pull/293)

2) Incorrect return size when importing time distributed layers. Looks like it should have been fixed [here](https://github.com/KonduitAI/deeplearning4j/pull/76) for dense but is unmerged. However there are issues with time distributed embedding, conv-1d, max-pooling and flatten layers as well.

3) Keras allows an embedding layer to be wrapped into a time distributed layer and therefore accepts a rank 3 input. We however expect a rank 2 input or a rank 3 input with middle dimension == 1. Missing a preprocessor here. 

Tests [here](https://github.com/eraly/keras-test-import/blob/master/src/main/java/org/deeplearning4j/NERTests.java)

**Comment by treo** [comment]
@eraly can you check whether this is fixed with Snapshots?

**Comment by agibsonccc** [comment]
Closing, out of date.
