### ISSUE TITLE
ND4J off the heap memory enhancement

### ISSUE THREAD

**Issue by LifeIsStrange** [deeplearning4j/deeplearning4j#8767]
Hi! 
Here you explain that ND4J is stored off the heap: https://deeplearning4j.org/docs/latest/nd4j-overview#inmemory
It happen that Java 14 will be released in a few weeks and introduce (finally!)
a complete API for accessing, storing and managing off the heap memory.

https://openjdk.java.net/jeps/370
I wonder what kind of improvements it could bring to ND4J?
More performance? Fewer leaks/ram use? A better api for end users? Less complex internal code?

**Comment by agibsonccc** [comment]
@LifeIsStrange can you move this question to https://community.konduit.ai/ ?
