### ISSUE TITLE
Keras and deeplearning4j compatibility policy

### ISSUE THREAD

**Issue by fspillner** [deeplearning4j/deeplearning4j#8775]
#### Keras and deeplearning4j compatibility policy

Is there a documentation / policy, which defines the version of Keras is guaranteed to be compatible with deeplearning4j? 

We train the model with the python library Keras and import the model in our Scala infrastructure. We had a case that deeplearning4j couldn't import the Keras model due to newer version of Keras. (we still have old version of deeplearning4j running - it would fix if we upgrade the deeplearning4j, but we need to check if the deeplearning4j is still able to import the other models being built by older Keras version.).

**Comment by agibsonccc** [comment]
@fspillner this has been fixed already with beta7. The "official" support can be documented here:  https://deeplearning4j.konduit.ai/keras-import/overview
