### ISSUE TITLE
ND4J CUDA: Nd4j.getAffinityManager().ensureLocation for external pointers

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8783]
When executing on CUDA (CPU is fine) Nd4j.getAffinityManager().ensureLocation can change the address of the data pointer (i.e., it does a copy)

This this may be reasonable behaviour, given we need to be able to reallocate arrays at c++ level, which we can't do for just any arbitrary external pointer.

This is used in DataVec python exec - assuming that we can modify host buffers inplace.
We are wrapping a BytePointer buffer in an INDArray, then passing that to Python.

```
    @Test
    public void testEnsureLocation2(){
        Nd4j.create(1);

        DirectBuffer bb = (DirectBuffer) ByteBuffer.allocateDirect(5);

        Pointer ptr = NativeOpsHolder.getInstance().getDeviceNativeOps().pointerForAddress(bb.address());
        DataBuffer buff = Nd4j.createBuffer(ptr, 20, DataType.BYTE);


        INDArray arr2 = Nd4j.create(buff, new long[]{5}, new long[]{1}, 1L, 'c', DataType.BYTE);
        System.out.println("Address before: " + arr2.data().pointer().address());
        Nd4j.getAffinityManager().ensureLocation(arr2, AffinityManager.Location.HOST);
        System.out.println("Address after: " + arr2.data().pointer().address());
    }
```

```
Address before: 2696745531984
Address after:  2697241867184
```

**Comment by raver119** [comment]
Fixed here: https://github.com/KonduitAI/deeplearning4j/pull/322
