### ISSUE TITLE
datavec-data-image: CUDA JVM crash in tests

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8785]
See gist (this was on master after doing a full install... also happens when running all modules)
https://gist.github.com/AlexDBlack/8d21de6b2507355c4f1e2eb836deae53

CPU is fine. Only tested on Windows.

org.datavec.image.loader.TestNativeImageLoader

**Comment by raver119** [comment]
So ye:

- crash only reproducible on Windows + CUDA, not reproducible in Linux
- crash happens only for multidim TIF files
- crash happens upon reading PIX (after it's converted to Mat)
- crash happens only on "sub-images", and only second one and above. First "sub-image" is ok 
- crash happens even if you don't write data to INDArray.  It's enough to try to read "sub-image".

**Comment by AlexDBlack** [comment]
Confirmed crashing on eclipse/deeplearning4j master too, not just KonduitAI/deeplearning4j

**Comment by saudet** [comment]
So it's probably not reading the PIX data properly...
@BioinfoTongLI Could you double check that there are no logical errors in that code?
