### ISSUE TITLE
INDArray.get(INDArray) not working for 1D arrays.

### ISSUE THREAD

**Issue by RobAltena** [deeplearning4j/deeplearning4j#8789]
#### Issue Description
See unit tests below:

     @Test
    void test1Dget() {
        INDArray data = Nd4j.linspace(1, 10, 10);  // Some random data.
        INDArray index = Nd4j.rand(3).muli(10).castTo(DataType.INT32); // pick 3 random indices. Same is ok.
        INDArray dataAtIndex = data.get(index); // get the data for our random picks.
        // java.lang.IllegalArgumentException: getColumn() can be called on 2D arrays only.

        assertEquals(dataAtIndex, index.add(1)); //May need reshaping and/or datatype casting.
    }

    @Test
    void test2Dget() {
        INDArray data = Nd4j.linspace(1, 10, 10).reshape(10, 1);  // Some random data. shaped to 2D
        INDArray index = Nd4j.rand(3).muli(10).castTo(DataType.INT32); // pick 3 random indices. Same is ok.
        INDArray dataAtIndex = data.get(index); // get the data for our random picks.
        // No errors here. Test passes.
        assertEquals(dataAtIndex.reshape(3).castTo(DataType.INT32), index.add(1));
    }

Expect both tests to pass. But the 1D fails with: "java.lang.IllegalArgumentException: getColumn() can be called on 2D arrays only."

#### Version Information
* Deeplearning4j version: Konduit fork master.
* Platform information (OS, etc) Win10

**Comment by raver119** [comment]
Fixed in my branch, will be merged later.
