### ISSUE TITLE
Reinforcement learning with AnyLogic

### ISSUE THREAD

**Issue by unkper** [deeplearning4j/deeplearning4j#8791]
#### Issue Description

I am a senior student. Currently I am training in reinforcement learning under AnyLogic, and I use a jar package prepared by SkyMind specially for training under AnyLogic —— rl4j-uber-1.0.0-beta3.jar. I want to use the GPU for acceleration during training, but I don’t know how to configure it. Does the configuration method also use POM?

#### Version Information
* rl4j-uber-1.0.0-beta3.jar
* Windows10，AnyLogic 8.5.2

**Comment by treo** [comment]
Please open a thread on https://community.konduit.ai/.

But in short, you are currently using something that is known as an "uberjar" that is built from a pom file. We can help you build your own uberjar, with the current version (beta6) on the forums.
