### ISSUE TITLE
F1 score not equals the result of the formula

### ISSUE THREAD

**Issue by SidneyLann** [deeplearning4j/deeplearning4j#8798]
in beta6, F1 score not equals the result of the formula
`F1 != 2*Precision*Recall/(Precision+Recall)`

 Accuracy:        0.9434
 Precision:       0.6258
 Recall:          0.5170
 F1 Score:        0.5451

 Accuracy:        0.9438
 Precision:       0.5964
 Recall:          0.5138
 F1 Score:        0.5381

 Accuracy:        0.9424
 Precision:       0.6036
 Recall:          0.5222
 F1 Score:        0.5471

**Comment by treo** [comment]
This formula is only relevant if you only have two classes. If you have more than 2 classes, F1 is calculated differently. See the javadoc here: 
https://deeplearning4j.org/api/latest/org/nd4j/evaluation/classification/Evaluation.html

Unfortunately, you didn't provide us with enough information to be able to say what exactly is happening in your case.

**Comment by SidneyLann** [comment]
Thanks. There are 12 classes here in nlp task using lstm. most examples are in 2 classes and a bit examples are in other 10 classes.

**Comment by treo** [comment]
Then you are definitively in the "more than 2 classes" camp. And that means the formula you suggested above does not apply to your case, but instead this applies: 

> For multi-class classification, binary metric methods such as f1(), precision(), recall() will report macro-average (of the one-vs-all) binary metrics. Note that you can specify micro vs. macro averaging using f1(EvaluationAveraging) and similar methods
