### ISSUE TITLE
libnd4j: cuDNN packaging

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8799]
Libnd4j (and hence SameDiff) now has cuDNN support.
Building with cuDNN is optional, however.

The question here is releasing nd4j-cuda with vs. without cuDNN.
Clearly, for deep learning use cases, we want cuDNN by default. But for users who need ND4J only (no SameDiff, no DL4J) they will not want the size overhead of cuDNN - i.e., it should be an optional component.

We should be able to to release one binary and dynamically link if cuDNN is available - but there are some questions about how to do this for Windows.

Ideally this would be resolved before release.

**Comment by saudet** [comment]
cuDNN is like 10 times smaller than the rest of CUDA. Why are we even worried about this?

**Comment by raver119** [comment]
It's 200MB compressed for Linux.

**Comment by AlexDBlack** [comment]
yeah, it's been rapidly getting bigger with each new release
on windows (uncompressed), cudnn 5 was like 80mb... latest cudnn (7.6.5) is 436mb

**Comment by saudet** [comment]
And the rest of CUDA is like 700 MB compressed, so what's the point?
