### ISSUE TITLE
nd4j not compatibel with java 7

### ISSUE THREAD

**Issue by mheck136** [deeplearning4j/deeplearning4j#8806]
#### Issue Description

The official description of nd4j states that it is compatible with java 7. We are running on a quite old tech stack and updating to a newer java version is an ongoing process which will take a few additional months from now. If it is possible to reintroduce compatibility with java 7, we'd really appreciate that. 

##### Expected behavior:

The following code snippet runs on java 7 without exceptions:
`INDArray x = Nd4j.zeros(3,4);`

##### Actual behavior:

An exception is thrown. See gist: https://gist.github.com/mheck136/91e2e10ba61a7db77b7b96055bf9bec1

#### Version Information

* nd4j version: 1.0.0-beta6
* Platform information: Windows Server 2016, Oracle Java 1.7 Update 80

#### Additional information:

I already opened a thread here: https://community.konduit.ai/t/java-7-compatibility-issues/306

**Comment by saudet** [comment]
I think it would be nice to get some snapshots out with this fixed and tested before the release.

@treo Do you know exactly where to fix this in the pom.xml files?

**Comment by mheck136** [comment]
@saudet I think the particular class referenced in the stacktrace is _CpuBackend_ which is located in the _nd4j-native_ module. The pom of that module specifies source and target version as 8 ([link to the very pom](https://github.com/eclipse/deeplearning4j/blob/cd0e62ffaf4579207c6e57915ad7a20a1208f95b/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/pom.xml#L233))
What I'm not sure about is whether other modules need to be adjusted as well.

**Comment by saudet** [comment]
@mheck136 Great! If you could send a pull request for that one at least, we'll get this tested, and you'll also get snapshots to try out once merged: https://deeplearning4j.konduit.ai/config/config-snapshots

**Comment by mheck136** [comment]
Sorry for the mess. I took me some time to create a correctly signed commit.

**Comment by mheck136** [comment]
Thanks for solving this that fast!

**Comment by saudet** [comment]
@mheck136 No problem! Let us know if you encounter any other such issues with 1.0.0-SNAPSHOT.
