### ISSUE TITLE
libnd4j: confusion_matrix op: switch output dtype config from iarg to darg

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8807]
https://github.com/eclipse/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/parity_ops/confusion_matrix.cpp#L69-L76

ATM can't configure dtype without _also_ configuring the number of classes.
If the datatype was set via a darg instead of an iarg, this wouldn't be a problem.

**Comment by raver119** [comment]
Implemented in my branch. Will be merged later.
