### ISSUE TITLE
`getPercentile` method returns wrong result

### ISSUE THREAD

**Issue by TramsWang** [deeplearning4j/deeplearning4j#8810]
Code in `getPercentile` method is incorrect. When the length sorted array is 2 and quantile is 75, this method will raise an exception as follows:
```
java.lang.IllegalArgumentException: Unable to get linear index 2: values is greater than length(2)
```
Actually, for any sorted array with length n, a large enough percentile will get it out of index.

My current version is `1.0.0-beta6`

To fix the problem, `getPercentile` method should be implemented like follows:
```java
protected double getPercentile(double percentile, ArrayList<Double> sorted) {
    /* In here we assume that quantile is in [0, 100] and array 'sorted' is sorted in ascending order */
    if (1 == sorted.size()) {
        /* This is a boundary case */
        /* The only value should be returned without any doubt */
        return sorted.get(0);
    }
    else if (100 == percentile) {
        /* Another boundary case */
        return sorted.get(sorted.size() - 1);
    }
    else {
        /* I just fixed based on original code, which adopted linear interpolation method */
        /* I also referred to 'percentile' method in 'numpy'. They implemented 5 difference method of interpolation */
        double pos_d = percentile / 100.0 * (sorted.size() - 1);
        double pos_floor = FastMath.floor(pos_d);
        int pos = (int) pos_floor;
        double lower = sorted.get(pos);
        double upper = sorted.get(pos + 1);
        return lower + (pos_d - pos_floor) * (upper - lower);
    }
}
```

**Comment by raver119** [comment]
Unfortunately it's not that simple.

We implement algorithm that matches Apache Commons Math, and percentile in edge cases (like like case you've highlighted here) do differ indeed. http://commons.apache.org/proper/commons-math/javadocs/api-3.5/org/apache/commons/math3/stat/descriptive/rank/Percentile.html

But at the same time there was missing condition there. I've fixed it, so thanks for highlighting this problem.
