### ISSUE TITLE
INDArray Shannon Entropy function returns negative values

### ISSUE THREAD

**Issue by strolling-coder** [deeplearning4j/deeplearning4j#8818]
Several INDArrays with 2D shape get negative values when the function `shannonEntropyNumber()` is called and **NaN** when the function `logEntropyNumber()` is called.
Checked a sample using the entropy function in Octave and the same data returned a different (positive) value.

Deeplearning4j version: 1.0.0-beta5
Platform: Linux OpenSuSe 15.0 and Linux Debian Stretch

Gist with one matrix example:
https://gist.github.com/strolling-coder/ae0469b67164627f79d22a5fdc04a0da

**Comment by AlexDBlack** [comment]
Thanks for the report, but I don't believe your data is valid for this operation.

Shannon entropy is defined as:
```
- sum_i( p_i log2(p_i) )
```
where p_i is the probability of a given symbol/random variable.
See for example: http://bearcave.com/misl/misl_tech/wavelets/compression/shannon.html

Given that, we are restricted to:
* 0 <= p_i <= 1 for all i, and
* sum_i(p_i) = 1

In the case of your test data, neither condition holds - most values are greater than 1.0, and the sum doesn't equal 1.0.
