### ISSUE TITLE
JVMM crashes when the Java variable is assigned and called for printing before and after the sub-matrix evaluation of NDArray

### ISSUE THREAD

**Issue by Eljah** [deeplearning4j/deeplearning4j#8823]
#### Issue Description

Hello @agibsonccc , i'm getting some jvm crash under specific conditions. I believe I should report it

```
    INDArray feature = asMatrix(image).get(NDArrayIndex.point(1), NDArrayIndex.all());
    System.out.println("Feature shape " + Arrays.toString(feature.shape()));  //todo crashes when unkommented
    feature = asMatrix(image).get(NDArrayIndex.point(1), NDArrayIndex.all());
    System.out.println("Feature shape " + Arrays.toString(feature.shape()));

```
leads to crash like this

#

```
A fatal error has been detected by the Java Runtime Environment:
#

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000051c79c6b, pid=8960, tid=11112
#

JRE version: Java(TM) SE Runtime Environment (8.0_65-b17) (build 1.8.0_65-b17)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.65-b01 mixed mode windows-amd64 compressed oops)
Problematic frame:
C [libnd4jcpu.dll+0x56b9c6b]
#

Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#

An error report file with more information is saved as:
D:\Java\projects\worsecodeever\hs_err_pid8960.log
#

If you would like to submit a bug report, please visit:
http://bugreport.java.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.
#
```

note that the output of the system out will have the same shapes, not the reduced one that is expected at the first system out

```
Feature shape [1, 60, 200]
Feature shape [1, 60, 200]\

```
while my expectation is to have 

`Feature shape [1, 1, 60, 200] `

at the first row

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* Platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

 ```
 <nd4j.version>1.0.0-beta6</nd4j.version>
    <dl4j.version>1.0.0-beta6</dl4j.version>
    <datavec.version>1.0.0-beta6</datavec.version>
    <nd4j.backend>nd4j-native-platform</nd4j.backend>

```
Windows 10 version 1803 build 171134.1304

no cuda and nvidia

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

https://gist.github.com/Eljah/9803e9512439ad0c613e73a09c3f5c22

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
Can you post the source code that actually reproduces the problem please? Including `asMatrix(String)` method.

**Comment by Eljah** [comment]
@raver119 it is already in the gist attached

**Comment by raver119** [comment]
Nope, I can't see `asMatrix(String)` there.

**Comment by Eljah** [comment]
@raver119 https://gist.githubusercontent.com/Eljah/9803e9512439ad0c613e73a09c3f5c22/raw/f5090a6dc2ac5660832ebfb9ad1b89c0d5590ae0/CaptchaLoader.java lines 170,172

**Comment by treo** [comment]
@Eljah 
What he means is that your gist doesn't include the *definition* of that method. 

In order to figure out what exactly is wrong in your case, we have to be able to run your project.

**Comment by raver119** [comment]
I've got that - he just extends our class, so definition is ours.

**Comment by treo** [comment]
I see, I missed that.

**Comment by raver119** [comment]
Same :)

**Comment by raver119** [comment]
Your issue looks like a problem in your code + lack of validation on our end.

Your original image has shape of [1, 60, 200].
You're getting subarray with indexes equal to { NDArrayIndex.point(1), all(), all().}

Which is a mistake. Point index must be 0. And in beta6 validation misses this. In current snapshots, I see exception that prevents view creation here.

**Comment by Eljah** [comment]
Ok, got it. So will you raise an issue for your side validation on this? In case of index being inserted programmatically, and even it is wrong I'd like to handle java exceptions, what is impossible if the JVM crashes.

**Comment by treo** [comment]
> In current snapshots, I see exception that prevents view creation here.

So on snapshots it should already throw an exception.
