### ISSUE TITLE
ImportKerasSequentialModel  -  NullPointerException

### ISSUE THREAD

**Issue by cyrusdobbs** [deeplearning4j/deeplearning4j#8827]
#### Issue Description

Attempting to import a model built in google colab with tf.keras to my java8 project.

I encounter a NullPointException.

#### Version Information

* Deeplearning4j version: 1.0.0-beta6
* Platform information (OS, etc): Windows 10

#### Additional Information

* [Stack trace](https://gist.github.com/CyrusDobbs/58ef5b36bf2fd099f9f656b2701ac283)
* [build.gradle](https://gist.github.com/CyrusDobbs/d255481d3380f121404202564f46c653)

**Comment by treo** [comment]
At the moment `tf.keras` import is not supported. Only regular Keras. 

This issues tracks the progress: https://github.com/eclipse/deeplearning4j/issues/8348.

**Comment by cyrusdobbs** [comment]
Keras Version: 2.2.5
Tensorflow Version: 1.15.2
Keras backend: tensorflow

However, I am still having the same issue when importing to DL4J. 

#8348 mentions that using non-tf keras should be a workaround. Am I doing something wrong?

**Comment by treo** [comment]
Please share the non tf.keras version of your model file, and we'll take a look.

**Comment by cyrusdobbs** [comment]
I created and saved the model using Keras 2.2.5. Is that the information you need?
Thanks!

**Comment by treo** [comment]
We need the actual model file you are trying to import to see why it doesn't import like it should.

The stacktrace you've provided doesn't make a lot of sense, as it can only happen if your input config isn't present at all in it.

**Comment by cyrusdobbs** [comment]
[Here's the model.](https://github.com/eclipse/deeplearning4j/files/4445565/model.zip)

**Comment by treo** [comment]
I see, your first layer is a `Flatten` layer, which be definition doesn't have any input size. 

That isn't a supported model configuration for import. You should be able to remove that layer without any ill effects. From the Keras documentation on Dense Layers:
> Note: if the input to the layer has a rank greater than 2, then it is flattened prior to the initial dot product with kernel.

@AlexDBlack should this ever be a supported configuration?

**Comment by cyrusdobbs** [comment]
When I remove the Flatten layer I now get this error when trying to fit:
> ValueError: Error when checking target: expected dense_3 to have 3 dimensions, but got array with shape (1155000, 1)

EDIT: I assume that a model of only fully connected layers isn't supported?
