### ISSUE TITLE
Transfer learning not working with LSTM model

### ISSUE THREAD

**Issue by data-llectual** [deeplearning4j/deeplearning4j#8829]
I am trying to use transfer learning with LSTM. 
It appears as if transfer learning does not work with LSTM models in dl4j, not sure if I am doing something wrong. Is there a working example that someone can share with me. 

Would appreciate your help.

Thanks

**Comment by treo** [comment]
Please keep questions in one place.

https://community.konduit.ai/t/transfer-learning-with-lstm/393/2
