### ISSUE TITLE
libnd4j: Add clipbyavgnorm_bp operation

### ISSUE THREAD

**Issue by atuzhykov** [deeplearning4j/deeplearning4j#8832]
During mapping some cpp ops to Java classes and testing them was noticed that [clipbyavgnorm](https://github.com/eclipse/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/transforms/clip_by_averaged_norm.cpp) op doesn't have a backprop operation, like clipbynorm has.

**Comment by shyrma** [comment]
done!
