### ISSUE TITLE
libnd4j:  helper::resizeFunctor: Non implemented yet.

### ISSUE THREAD

**Issue by atuzhykov** [deeplearning4j/deeplearning4j#8833]
During maping cpp op image_resize to Java class was noticed, that for following methods
1. ResizeLanczos5
2. ResizeMitchelcubic
3. ResizeArea

occured exception `java.lang.RuntimeException: helper::resizeFunctor: Non implemented yet.`
[full stacktrace
](https://gist.github.com/atuzhykov/31db95eedf7443072e4f2068e497794f
)

**Comment by raver119** [comment]
This is not a bug. These resize methods do not exist in TF < 2.

https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/image/resize_images

vs

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/image/resize


We'll add those though.
