### ISSUE TITLE
DL4J: CUDA test failure in dl4j-spark-parameterserver

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8834]
https://jenkins.konduit.ai/blue/organizations/jenkins/konduitai%2Fdeeplearning4j/detail/PR-374/1/pipeline/673

Relevant part of logs:
https://gist.github.com/AlexDBlack/48e5153d9ac48d89d2891ebec3fac52c

**Comment by raver119** [comment]
Fixed
