### ISSUE TITLE
Is datavec-data-audio available on Android platform?

### ISSUE THREAD

**Issue by qq12cvhj** [deeplearning4j/deeplearning4j#8852]
is datavec a pure java library?I'm trying to use it on Android platform.
But when I declare the lib in build.gradle,I fount it that the fft is based on Jtransforms library.What interested me is that,the Jtransforms lib is based on org.apache.commons.math3,which also supports the datavec-data-audio library.So how can I deal with this problem?

**Comment by saudet** [comment]
No, it's not pure Java, but it works just fine with Android. What error are you getting?

**Comment by qq12cvhj** [comment]
Datavec-audio-data.jar. It is based on apache.commons.math3 and a library named Jtransforms.However,Jtransforms is also based on the math3 library.So on Android platform it makes the duplicated problem.

**Comment by saudet** [comment]
I'm pretty sure Apache Commons Math 3 works fine on Android. Please clarify the issue.

**Comment by qq12cvhj** [comment]
I'm sorry.But now I've solved this problem on android platform.There used to be some problems about dependencies.I solved it by like below:
 `implementation(group: 'com.github.wendykierp', name: 'JTransforms', version: '3.1') {
        exclude(group: 'org.apache', module: 'commons-math3')
    }`
Similiar,the datavec imported by this way:
`implementation('org.datavec:datavec-data-audio:1.0.0-beta6'){
        exclude(group: 'com.github.wendykierp',module:'JTransforms')
    }`

Thanks.

**Comment by AlexDBlack** [comment]
Sounds like a dependency version problem?
I'll close this as resolved unless there's anything left to do here.
