### ISSUE TITLE
ALE example failed

### ISSUE THREAD

**Issue by hanbaoan123** [deeplearning4j/deeplearning4j#8855]
#### Issue Description

When I run the ALE example, the following error wa thrown:

Exception in thread "main" org.deeplearning4j.exception.DL4JInvalidInputException: Got rank 3 array as input to ConvolutionLayer (layer name = layer0, layer index = 0) with shape [4, 84, 84]. Expected rank 4 array with shape [minibatchSize, layerInputDepth, inputHeight, inputWidth]. (layer name: layer0, layer index: 0, layer type: ConvolutionLayer)

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 1.0.0-beta6
* Platform information (OS, etc) win10
* CUDA version, if used CUDA10.1

**Comment by saudet** [comment]
This has been fixed. Please try with 1.0.0-SNAPSHOT:
https://deeplearning4j.konduit.ai/config/config-snapshots

**Comment by hanbaoan123** [comment]
> This has been fixed. Please try with 1.0.0-SNAPSHOT:
> https://deeplearning4j.konduit.ai/config/config-snapshots

But when I try with 1.0.0-SNAPSHOT, the jar file can not be downloaded as follows.

[INFO] Downloading from : https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/protobuf/1.0.0-SNAPSHOT/protobuf-1.0.0-20200424.012726-5483.jar

**Comment by AlexDBlack** [comment]
@hanbaoan123 The file you mentioned is definitely online: https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/protobuf/1.0.0-SNAPSHOT/

Try rebuilding, perhaps with `mvn -U`

**Comment by hanbaoan123** [comment]
> @hanbaoan123 The file you mentioned is definitely online: https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/protobuf/1.0.0-SNAPSHOT/
> 
> Try rebuilding, perhaps with `mvn -U`

I can not find this class org.deeplearning4j.rl4j.network.configuration.ActorCriticNetworkConfiguration.ActorCriticNetworkConfigurationBuilder in rl4j-core-1.0.0-SNAPSHOT

**Comment by agibsonccc** [comment]
Closing this. Guessing just a local issue.
