### ISSUE TITLE
[Question] Does DL4J works fine on NVidia Jetson ?

### ISSUE THREAD

**Issue by Paranormaly** [deeplearning4j/deeplearning4j#8862]
Just asking in case anyone tried it on NVidia Jetson because I'm planing to buy one for DL4J training process but I want to be sure before. Thanks

**Comment by raver119** [comment]
сс @sshepel @agibsonccc

**Comment by sshepel** [comment]
Build on nano is fine, snapshots on maven central, so it should work :)

**Comment by Paranormaly** [comment]
@sshepel Great. so I don't have to rebuild it? I just do the normal project and run it on Jetson Nano?

Your comment is enough for me so I ordered Jetson Nano and when I got it I may get back here if I faced any problem.
Thankx

**Comment by sshepel** [comment]
@Paranormaly right, just add artifact as dependency and try to run :)
Also, we do have docker container with all things that are required to build dl4j (javacpp too) in docker on Jetson, just in case...
```
docker pull konduit/jenkins-agent:arm64-ubuntu18.04-nano-l4t32.2.1-jetpack4.2.2-cuda10.0-cudnn7
```

**Comment by Paranormaly** [comment]
That's great. 
I'm gonna close this and get back when I finish testing DL4J on Jetson.
Thank you so much.
