### ISSUE TITLE
JVM crash when allocating more memory than initial MMAP size

### ISSUE THREAD

**Issue by lukaszbachman** [deeplearning4j/deeplearning4j#8864]
JVM will crash when calling libnd4jcpu.so under following circumstances:

- Memory Workspace is used
- policy is set to: `LocationPolicy.MMAP`
- initial size is set to X
- one tries to create an `INDArray` which would consume more memory than  X (won't fit into the MMAP)

I also tried setting `maxSize()` but that doesn't seem to help - MMAP doesn't grow and JVM still crashes. I could tell that in case of a crash the entire MMAP is filled with data, so I'm guessing that the problem is about adding those extra numbers which won't fit.

You can try that out by running the code below - depending on the value of `addMoreFloats` the allocation will succeed (`false`) or fail (`true`) due to this overlfow.

```
public static void main(String[] args) {
    WorkspaceConfiguration mmap = WorkspaceConfiguration.builder()
      .initialSize(200 * 1024L * 1024L) // 200mbs
      .tempFilePath("/tmp/my.mmap")
      .policyLocation(LocationPolicy.MMAP)
      .build();
    try (MemoryWorkspace ws = Nd4j.getWorkspaceManager().getAndActivateWorkspace(mmap, "M2")) {
      int twoHundredMbsOfFloats = 52428800; // 200mbs % 4
      boolean addMoreFloats = true;
      if (addMoreFloats) {
        twoHundredMbsOfFloats += 1_000;
      }
      INDArray x = Nd4j.rand(DataType.FLOAT, twoHundredMbsOfFloats);
      }
}

```
#### Version Information

* ND4J version: 1.0.0-beta6 (latest), CPU backend
* Ubuntu 19.10 (I saw similar problems on Windows too, albeit error was different)

#### Additional Information

https://gist.github.com/lukaszbachman/c413fb5edf20891a0269fc7a6f85f323

**Comment by raver119** [comment]
Memory-mapped file shouldn't grow. But there shouldn't be crash as well.

**Comment by lukaszbachman** [comment]
@raver119 , so you mean to say that by design MMAP will only be as big as the value defined in `initialSize()`? I could implement a routine which retries the operation with a bigger MMAP. In such case it would be very handy to know how much data did not fit into the map. I can try to make that calculations myself, but maybe the library already knows that?

**Comment by raver119** [comment]
Yes it's design limitation. Try `man mmap`.

**Comment by raver119** [comment]
Fixed the crash. But keep in mind, in this particular case proper behavior will be "spill", so your array will be allocated in RAM, since it'll be considered a spilled array.

**Comment by lukaszbachman** [comment]
Sorry for asking, but where can I see this commit?

**Comment by raver119** [comment]
https://github.com/KonduitAI/deeplearning4j/commit/78260efe54b331a74e68db96cf0f46609a257dd6

**Comment by lukaszbachman** [comment]
Thanks!
