### ISSUE TITLE
Dead lock in case of exception on 'hasNext()' of the iterator in ReaderThread

### ISSUE THREAD

**Issue by alek-w** [deeplearning4j/deeplearning4j#8866]
#### Issue Description

Please describe our issue, along with:
- expected behavior: gracefully stop
- encountered behavior: infinite wait on 'buffer.take();' in  org.deeplearning4j.parallelism.AsyncIterator#hasNext()  (the buffer is LinkedBlockingQueue).
ReaderThread runs in a parallel thread and would be terminated in case of any exception (except InterruptedException). At the same time AsyncIterator would continue to wait for the next element from LinkedBlockingQueue. But nothing will put anything into LinkedBlockingQueue.

#### Version Information

* Deeplearning4j version: 0.9.1
it is applicable for newer versions.

#### Additional Information

Where applicable, please also provide:

**Comment by AlexDBlack** [comment]
Can you try again with the latest release - 1.0.0-beta6?
0.9.1 was released 12/08/2017. Lots of fixes (including a few for AsyncIterator IIRC) since then.

If it's still occurring, happy to take a look, but some code to reproduce the problem would help a lot. Thanks.

**Comment by alek-w** [comment]
i have checked on 1.0.0-beta6 
it is not reproduced @AlexDBlack

**Comment by raver119** [comment]
Great. Thanks for checking.

**Comment by alek-w** [comment]
@raver119 @AlexDBlack could you tell, please
what is your plan about non-beta release?

**Comment by raver119** [comment]
We hope after beta7 we'll release 1.0. However, it's just naming convention. For you as end-user every subsequent version must be more stable, faster and so on.
