### ISSUE TITLE
Memory Workspace cannot allocate MMAP (fails with "java.lang.RuntimeException: MMAP failed") when path to the mmap file is longer than 71 characters

### ISSUE THREAD

**Issue by lukaszbachman** [deeplearning4j/deeplearning4j#8867]
On Windows creating Memory Workspace with `LocationPolicy.MMAP` will fail if the `tempFileLocation` path is longer than 71 characters.

To reproduce:
```
WorkspaceConfiguration mmap = WorkspaceConfiguration.builder()
				  .initialSize(100 * 1024L * 1024L) // 1 GB
				  .policyLocation(LocationPolicy.MMAP)
				  .tempFilePath("D:\\xxxxxxxx\\yyyyyyy\\zzzzzzzzzzz\\xxxxxxxx\\target\\temp\\123456789ABCDE.mmap")
				  .build();
try (MemoryWorkspace ws = Nd4j.getWorkspaceManager().getAndActivateWorkspace(mmap, "M2")) {
// Not important...
}
```

Error:
```
java.lang.RuntimeException: MMAP failed
	at org.nd4j.linalg.cpu.nativecpu.workspace.CpuWorkspace.init(CpuWorkspace.java:107)
(...)
```

Note that this paths' length is exactly 72 characters. If you drop one character from the name of the file, for example renaming it to `123456789ABCD.mmap` mmap will be created fine.

#### Version Information
* ND4J 1.0.0-beta6, CPU backend
* Windows 10

#### Additional Information

https://gist.github.com/lukaszbachman/5b786f7e60c10f74bc7d5163811d5e93

**Comment by raver119** [comment]
I'm not 100% sure atm, but for me it sounds like a legacy WinAPI limitation of I/O api. There's couple of limitations like that exist in WinAPI.

I will check it out.

**Comment by lukaszbachman** [comment]
I suspected something along those lines. Any chance to get more meaningful error message from the native libs and pass it back to Java? Would definitely help to troubleshoot sooner.
Thanks for a quick response!

**Comment by raver119** [comment]
I'm not sure it's worth the hassle, it might be easier to adopt (or at least try to adopt) newer file API, since WIndows 10 family is the only version that must be supported these days

**Comment by raver119** [comment]
Fixed. Now limitation matches Java one.

**Comment by lukaszbachman** [comment]
That is awesome news! Where can I get snapshots of ND4J? Couldn't find that in the documentation.

**Comment by raver119** [comment]
https://deeplearning4j.konduit.ai/config/config-snapshots

But since this change is fairly recent one, it's not in snapshots yet.

**Comment by lukaszbachman** [comment]
Ok, clear
