### ISSUE TITLE
libnd4j: reverse_bp op is incorrect

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8874]
```
    @Test
    public void testReverseBp(){

        INDArray x = Nd4j.createFromArray(new double[][]{{1,2,3},{4,5,6}});

        INDArray outFwd = x.like();

        DynamicCustomOp op = DynamicCustomOp.builder("reverse")
                .addInputs(x)
                .addOutputs(outFwd)
                .addIntegerArguments(1)
                .build();

        Nd4j.exec(op);

        System.out.println("in:");
        System.out.println(x);
        System.out.println("outFwd: ");
        System.out.println(outFwd);

        System.out.println("/////////////////////////////////////////////////////////");

        INDArray shouldBeUnused = x.ulike().assign(Double.NaN);
        INDArray outBwd = x.ulike();

        DynamicCustomOp op2 = DynamicCustomOp.builder("reverse_bp")
                .addInputs(shouldBeUnused, outFwd)
                .addOutputs(outBwd)
                .addIntegerArguments(1)
                .build();

        Nd4j.exec(op2);

        assertEquals(x, outBwd);   //Fails here
    }
```

![image](https://user-images.githubusercontent.com/2360237/80207416-6f013d00-8671-11ea-9c1f-d4eb4f6a3fd2.png)

Cause seems to be this line:
https://github.com/eclipse/deeplearning4j/blob/master/libnd4j/include/ops/declarable/helpers/cpu/reverse.cpp#L199

I'm not following the logic here.
If forward pass reverses the input along axis X, then backprop should simply reverse the gradient along axis X also?

**Comment by AlexDBlack** [comment]
We can easily work around this by changing this flag to false:
https://github.com/eclipse/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/transforms/reverse.cpp#L88

I've done that in this PR: https://github.com/KonduitAI/deeplearning4j/pull/392

So fixing this (well, cleaning up the unneeded backprop arg) isn't an immediate priority.

**Comment by shyrma** [comment]
cleaned up!
