### ISSUE TITLE
SameDiff mergeAvg/mergeAdd gives nan when training

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/deeplearning4j#8875]
I am testing examples on snapshots and the mergeAvg [here](https://github.com/eclipse/deeplearning4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/samediff/dl4j/layers/MergeLambdaVertex.java#L29) gives nans.

Changing that to 
```
        SDVariable average = input1.add(input2).mul(0.5);
```
and everything is fine.

Tried doing mergeAdd and hard coding the div by 2 and that gives nans too..

**Comment by AlexDBlack** [comment]
I'm not able to reproduce this - CPU and CUDA both run fine.
Latest master, built locally.
Here's the output of running Ex3LambdaVertex on branch ab_snapshots (just pushed up): https://gist.github.com/AlexDBlack/469faa0deb97dc50414005a959a04ee7

The example isn't exactly well tuned (note the no-op updated - equivalent to SGD with LR 1.0), but if that was the cause it should fail everywhere...

**Comment by eraly** [comment]
I was running beta6 and not snapshots. We can close this. Sorry about that.
