### ISSUE TITLE
ND4J: snapshots Nd4j.gemm performance regression since beta6 (CPU)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#8877]
gemm args:

x: [2,32,2097152,2097152,1,8192,1,99]
y: [2,32,1000,1000,1,8192,1,99]
z: [2,2097152,1000,1,2097152,8192,1,102]

tA = true
tB = false
a = 1.0
b = 0.0

```
    public static void main(String[] args) {

        INDArray x = Nd4j.create(DataType.FLOAT, 32,2097152);
        INDArray y = Nd4j.create(DataType.FLOAT, 32,1000);
        INDArray z = Nd4j.create(DataType.FLOAT, new long[]{2097152,1000}, 'f');

        System.out.println(x.shapeInfoToString());
        System.out.println(y.shapeInfoToString());
        System.out.println(z.shapeInfoToString());

        for( int i=0; i<5; i++ ){
            long start = System.currentTimeMillis();
            Nd4j.gemm(x, y, z, true, false, 1.0, 0.0);
            long end = System.currentTimeMillis();
            System.out.println(i + " - " + (end - start));
        }
    }
```

**5930k**

1.0.0-beta6:
```
0 - 1117
1 - 1053
2 - 1028
3 - 934
4 - 1010
```

master:
```
0 - 37556
1 - 39345
2 - 37811
3 - 37805
4 - 37494
```

**3990x**
1.0.0-beta6:
```
0 - 570
1 - 570
2 - 570
3 - 561
4 - 573
```

master:
```
0 - 15349
1 - 15061
2 - 15101
3 - 15056
4 - 15125
```

**Comment by saudet** [comment]
It's not using BLAS anymore, right?

**Comment by AlexDBlack** [comment]
It's built manually with OpenBLAS (and mkldnn). Performance when the result array is C order looks fine. F order result arrays looks bad. I'll post more results shortly.

**Comment by AlexDBlack** [comment]
Confirmed - seems like there's a problem only when the result array is F order

3990x results: https://gist.github.com/AlexDBlack/231a642ec37adaa5dc6552859874b7c3
5930k results: https://gist.github.com/AlexDBlack/56efc8acd12baf0617715aa15c7eb9dd

Note that in beta6, we didn't support Z/result array being C order in Nd4j.gemm, now we support both C and F for any array in Nd4j.gemm.

**Comment by raver119** [comment]
So, in other words - mkldnn totally hates F order? Strange...

**Comment by raver119** [comment]
Okay, it's not mkldnn. It's something on our end by the looks of it.

**Comment by raver119** [comment]
Issue resolved by skipping mkldnn if 2D output array has F order, or any 3D input/output array has non-C order.
