### ISSUE TITLE
return index of element if it exists in INDArray

### ISSUE THREAD

**Issue by ashfaq92** [deeplearning4j/deeplearning4j#8889]
how to get index of an element (just like position of element in matrix in terms of row and columns) that if it exists in INDArray?
I tried:
`myArr.getWhere(someValue, Conditions.equals(1));`
But it does not return index. It returns element if condition fulfills (which is useless in this case)

in numpy:

```
import numpy as np
myArr = np.array()
index = np.where(myArr == someValue)
```

**Comment by raver119** [comment]
BooleanIndexing.firstIndex(INDArray, Condition) is what you're looking for I think.
