### ISSUE TITLE
NDArrayUtil.toNDArray rectangular array invalid conversion

### ISSUE THREAD

**Issue by msinev** [deeplearning4j/deeplearning4j#8895]
#### Issue Description

Bug during rectangular array conversion in 
https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/util/NDArrayUtil.java

Opposite array sizes applied
 e.g. in Scala

`  Create array & print

    val y = 2

    val h = 3

    val ret = Array.ofDim[Int](y, h)
    for (i <- 0 until y) {
      for (j <- 0 until h) {
        ret(i)(j) = ((j+1)*100)+i
      }
    }
    // convert & print
    val f1 = NDArrayUtil.toNDArray(ret)
    println(f1.toString())
`
- expected behavior
[[  100.0000,  200.0000,  300.0000], 
 [  101.0000,  201.0000,  301.0000]]

- encountered behavior
[[  100.0000,  200.0000], 
 [  300.0000,  101.0000], 
 [  201.0000,  301.0000]]

#### Version Information

* Deeplearning4j 1.0.0-beta6 

#### Additional Information
N/A
#### Contributing

CURRENT CODE Line31 
[https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/util/NDArrayUtil.java
](url)

    public static INDArray toNDArray(int[][] nums) {
        if (Nd4j.dataType() == DataType.DOUBLE) {
            double[] doubles = ArrayUtil.toDoubles(nums);
            INDArray create = Nd4j.create(doubles, new int[] {nums[0].length, nums.length});
            return create;
        } else {
            float[] doubles = ArrayUtil.toFloats(nums);
            INDArray create = Nd4j.create(doubles, new int[] {nums[0].length, nums.length});
            return create;
        }
    }

CORRECTED VERSION

        public static INDArray toNDArray(int[][] nums) {
            if (Nd4j.dataType() == DataType.DOUBLE) {
                double[] doubles = ArrayUtil.toDoubles(nums);
                INDArray create = Nd4j.create(doubles, new int[] {nums.length, nums[0].length});
                return create;
            } else {
                float[] floats = ArrayUtil.toFloats(nums);
                INDArray create = Nd4j.create(floats, new int[] {nums.length, nums[0].length});
                return create;
            }

        }

**Comment by raver119** [comment]
This method will be deprecated and shouldn't be used.

Please use Nd4j.createFromArray(...). It generates result you'd expect.

**Comment by msinev** [comment]
Nice
