### ISSUE TITLE
Confusing Documentation with its actual implementation

### ISSUE THREAD

**Issue by shwetaagrawal1** [deeplearning4j/deeplearning4j#890]
Hi,
I have started working on dl4j project. As I was a new user and unknown to these things, I started with its documentation and I found that documenattion of dl4j is really different from the code implementation. I have worked on word2vec and canova in which I followed the documentation but the file that they mentioned are not in the code. I canova example the command is wrutten in documentation ./bin/canova vectorize -conf [my_conf_file]  but after downloading canova there is no bin folder in this.
So please proper documentation so that I can follow that start working.

Thanks
Shweta

**Comment by agibsonccc** [comment]
We should shorten the getting started to just importing the examples. Explain the different components of the project (canova - load data,nd4j - matrix ops, dl4j algorithms) then let people import the examples and ask questions. Afterwards moe on to "what next?" which would then be designing a problem.

**Comment by shwetaagrawal1** [comment]
Yes, this is good idea.you should also provide user the type of input.
