### ISSUE TITLE
java.lang.UnsatisfiedLinkError: 'org.nd4j.nativeblas.OpaqueDataBuffer (Raspberry Pi 4, 1.0.0-SNAPSHOT)

### ISSUE THREAD

**Issue by FredericKayser** [deeplearning4j/deeplearning4j#8900]
#### Issue Description

By calling the method init() of the MultiLayerNetwork class on my Raspberry Pi 4 I am getting an exception(see below). Testing the program on my computer(macOS Catalina) doesn't cause any issues.

#### Version Information

Please indicate relevant versions, including, if relevant:

* DL4J Version: 1.0.0-SNAPSHOT
* Raspbian GNU/Linux 10 (buster)
* OpenJDK version "11.0.7" 2020-04-14

#### Additional Information

Error Message: https://gist.github.com/FredericKayser/dc7235ec779ebec5867de443de4616ea

I am using 1.0.0-SNAPSHOT, because before I got this error I had the problem mentioned in this issue: https://github.com/eclipse/deeplearning4j/issues/8744

**Comment by raver119** [comment]
Typically that’s the sign of versions clash. Share your pom.xml please

**Comment by FredericKayser** [comment]
This is my pom.xml:

https://gist.github.com/FredericKayser/b147b75a47a11909c0905dbb63e5bb63

EDIT: Here should be mentioned that I package the project on the Raspberry Pi with Maven to follow your advise(https://deeplearning4j.konduit.ai/config/config-snapshots) and use 'nd4j-native' and not 'nd4j-native-platform'.

**Comment by treo** [comment]
Can you re-pull the snapshots (using -U parameter when calling mvn)? It doesn't happen often, but you might have gotten Snapshots that were in between updates.

**Comment by FredericKayser** [comment]
So I've re-pulled the snapshots a few minutes ago, I got the same exception. I used the -U parameter before too, so probably this isn't the problem.

**Comment by raver119** [comment]
@sshepel are we sure arm binaries are successfully built in CI/CD?

**Comment by sshepel** [comment]
Well from the build log, I can see that at least gcc was picked right...

Latest artifact that I can see on sonatypenexus is: `nd4j-native-1.0.0-20200501.092107-18222-linux-armhf.jar`

**Comment by raver119** [comment]
I'm not quite sure how it's possible. OpaqueDataBuffer class is platform-independent. It's pure java.

**Comment by treo** [comment]
@FredericKayser 
Can you share the output of your mvn build with us? And ideally also the names of the nd4j related jar files in your maven cache. 

The missing file should be in nd4j-native-api-1.0.0-20200501.125842-27039.jar and that file should have an md5sum of `4f6f502137f6b91e89d2cccbb699a828`

**Comment by FredericKayser** [comment]
Well, it took me a while too find the correct files, but here are my nd4j related jar files:

#### nd4j-api
nd4j-api-1.0.0-20200501.102357-27416.jar
nd4j-api-1.0.0-20200501.123354-27417.jar
nd4j-api-1.0.0-20200501.125856-27418.jar
nd4j-api-1.0.0-SNAPSHOT.jar

#### nd4j-common
nd4j-common-1.0.0-20200501.102121-26713.jar
nd4j-common-1.0.0-20200501.123230-26714.jar
nd4j-common-1.0.0-20200501.125813-26715.jar
nd4j-common-1.0.0-SNAPSHOT.jar

#### nd4j-native-api
nd4j-native-api-1.0.0-20200501.102335-27037.jar
nd4j-native-api-1.0.0-20200501.123340-27038.jar

_nd4j-native-api-1.0.0-20200501.125842-27039.jar - md5sum: 4f6f502137f6b91e89d2cccbb699a828_

nd4j-native-api-1.0.0-SNAPSHOT.jar

#### nd4j-native-platform
nd4j-native-platform-1.0.0-20200501.092801-2431.jar 
nd4j-native-platform-1.0.0-SNAPSHOT.jar



So I think with maven build you want my packaged jar? If I did not understand your question correctly, please write it ;)

So if it was correct, here can you download it: https://workupload.com/file/5sfMsC8kpDA 

And sorry for taking so long to answer, I was a bit overwhelmed.

**Comment by saudet** [comment]
What does `mvn dependency:tree` look like?

**Comment by saudet** [comment]
It looks like `libgomp.so.1` isn't getting bundled, and it's probably what we're going to find in the log somewhere.

@sshepel Please add the directory containing that file to `java.library.path` when calling `mvn`, something like this: https://github.com/bytedeco/javacpp-presets/blob/master/ci/install-travis.sh#L188

**Comment by FredericKayser** [comment]
Here is the dependency tree: https://gist.github.com/FredericKayser/1e6c461d48af45df7f30822ff96f4963

**Comment by saudet** [comment]
@FredericKayser Thanks! If you install `libgomp.so.1` on the system, it will most likely work.

**Comment by FredericKayser** [comment]
Thank you very, very much! It is now working!
