### ISSUE TITLE
Nd4j.getMemoryManager().memcpy does not check buffer type

### ISSUE THREAD

**Issue by sascha08-15** [deeplearning4j/deeplearning4j#8909]
#### Issue Description

Migration of an INDArray to a workspaces by invoking `migrate()` ends up with wrong values. Traced the issue to the way how memcpy dealing with type information, i.e. it is ignoring the type info on INDArrays. But that also may be a design question.
**In any case:** 
- expected behavior: When I do migrate to another workspace, expecation is to end up with the same values.
- encountered behavior: Original values where not present and it seemed like a memcpy problem.
Two test cases attached whereas

* `testMigrateToWorkspace` IMHO should pass.
* `testMemcpy` maybe an exception is sufficient.

#### Version Information
1.0.0-beta6

#### Additional Information

```
    @Test
    public void testMigrateToWorkspace(){
        var src = Nd4j.createFromArray (1L,2L);
        var wsConf = new WorkspaceConfiguration().builder().build();
        Nd4j.getWorkspaceManager().createNewWorkspace(wsConf,"testWS");
        Nd4j.getWorkspaceManager().getAndActivateWorkspace("testWS");
        src = src.migrate();
        assertEquals(1L,src.getLong(0));
    }
```

Traced the migration issue back to a memcpy call in
BaseNDArray.java method: public INDArray migrate(boolean detachOnNoWs)

Wrote a test case for this
``` 
   @Test
    public void testMemcpy(){
        var src = Nd4j.createFromArray (1L,2L);
        var dst = Nd4j.createBuffer(new float[2]);
        Nd4j.getMemoryManager().memcpy(dst,src.data());
        log.info("Src: " + src.toStringFull());
        log.info("Dst: " + dst.toString());
        assertEquals(1L,dst.getLong(0));
    }
```
Clearly, one can argue if a low level memory operation should actually check types.

However, the migrate() should be type aware: when duplicating the array in BaseNDArray.java
`public INDArray migrate(boolean detachOnNoWs)` the line 
`DataBuffer buffer = Nd4j.createBuffer(this.length(), false);`
 does not check any types, eventually ending up with the wrong type.

#### Contributing
See above - I guess the changes are more or less trivial.

**Comment by raver119** [comment]
Yes, clearly a bug. But not related to memcpy.

Thanks for flagging this issue

**Comment by raver119** [comment]
Fixed. Will be merged once CI happy.
