### ISSUE TITLE
Word2Vec issues and suggested roadmap

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#891]
After all my planned fixes applied, there's still something to do with w2v.
1. Uptraining is implemented in very limited way: it's possible to train old model on new corpus, but no words can be added to vocabulary. So, it's generally "weights update".
   There's at least 3 ways to implement this feature properly, with new words in vocabulary, so i think i'll offer solution on this issue, if nobody will overtake me on this.
2. AdaptiveGradients are NOT applied properly at this moment. Model built with useAdaGrad == true will be unusable. My previous thoughts that it's based on negativeSampling being used were false, it's overall AdaGrad failure on standalone w2v. This needs to be investigated and fixed. 
3. Whole w2v internals should be moved onto current dl4j codebase, since it's just nn after all, and it would be nice if it will be using all the same internal stuff like all other dl4j classes; Potentially this could solve adaGrad issue as well.

**Comment by agibsonccc** [comment]
Not relevant anymore
