### ISSUE TITLE
SameDiff: random_poisson and random_gamma ops need output datatype config

### ISSUE THREAD

**Issue by atuzhykov** [deeplearning4j/deeplearning4j#8921]
During TF import testing the following issues was noticed

1. no int32/64 support for output datatype
2. libnd4j c++ op is restricted to have same datatype as input(1) array - tensorflow doesn't have this restriction (so: our op needs dtype arg for setting type of output array)
https://www.tensorflow.org/api_docs/python/tf/random/poisson

stacktrace 
https://gist.github.com/atuzhykov/0715ae81541ccb765b8491d1110bd668

**Comment by AlexDBlack** [comment]
Also random gamma:
https://github.com/eclipse/deeplearning4j/blob/9f523d6811243db673eba1d8930232bbbb3e92cc/libnd4j/include/ops/declarable/generic/random/gamma.cpp#L66

https://www.tensorflow.org/api_docs/python/tf/random/gamma
