### ISSUE TITLE
MatMul Op only supports float typed inputs

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#8926]
#### Issue Description
In principle there is no reason why integer inputs shouldn't be supported as well. 

```java
Nd4j.exec(DynamicCustomOp.builder("mmul")
                .addInputs(Nd4j.rand(3, 4).castTo(DataType.INT32), Nd4j.rand(4, 5).castTo(DataType.INT32))
                .addBooleanArguments(false, false, false)
                .build())[0]
```
This fails with:
```
Op [matmul] failed check for input [0], DataType: [INT32]
```

I think this is due to a restriction on just float data types here:
https://github.com/KonduitAI/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/blas/matmul.cpp#L139-L144

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-SNAPSHOT

Originally surfaced in https://community.konduit.ai/t/working-with-indarrays-using-integer-datatype/491

**Comment by AlexDBlack** [comment]
Also: We need to add java-side tests for this :)

**Comment by raver119** [comment]
https://github.com/KonduitAI/deeplearning4j/pull/436

**Comment by raver119** [comment]
Should be fixed now. However, more tests never hurt.
