### ISSUE TITLE
libnd4j: compare_and_bitpack returns incorrect shapes

### ISSUE THREAD

**Issue by atuzhykov** [deeplearning4j/deeplearning4j#8940]
compare_and_bitpack op we expect returned shape divided by 8 but got without dividing
for INT64 datatype input of shape [16] we are getting shape [8] output instead of shape [2] output
stacktrace:
https://gist.github.com/atuzhykov/d7101ef23c5a086deaacfc3f800dd7b4
op description
https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/compare-and-bitpack

**Comment by quickwritereader** [comment]
#9196
