### ISSUE TITLE
libnd4j: max_pool_with_argmax operation needs to support integer types (for TF import)

### ISSUE THREAD

**Issue by atuzhykov** [deeplearning4j/deeplearning4j#8943]
The max_pool_with_argmax operation supports the following datatypes in tensorflow:
https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/resources/ops.proto#L17816
```
  attr {
    name: "T"
    type: "type"
    allowed_values {
      list {
        type: DT_FLOAT
        type: DT_DOUBLE
        type: DT_INT32
        type: DT_UINT8
        type: DT_INT16
        type: DT_INT8
        type: DT_INT64
        type: DT_BFLOAT16
        type: DT_UINT16
        type: DT_HALF
        type: DT_UINT32
        type: DT_UINT64
      }
    }
  }
```
Our implementation does not seem to support integer datatypes.
For INT32 and INT64 dtypes of INPUT_VARIABLE  we have exception
Isolated test and stacktrace:
https://gist.github.com/atuzhykov/ed892efe472f00721aecb98b291027b1

**Comment by raver119** [comment]
Fixed in my branch, will be merged later.
