### ISSUE TITLE
Android Studio :  load word2vec model error 

### ISSUE THREAD

**Issue by LunaMK** [deeplearning4j/deeplearning4j#8952]
### so I try to load own model by:

File model = new File("model.bin");
Word2Vec vec = WordVectorSerializer.readWord2VecModel(model);

##### so i get this error:

java.lang.NoClassDefFoundError: Failed resolution of: Lorg/slf4j/LoggerFactory;
at org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.<clinit>(WordVectorSerializer.java:155)

##### go to error I get :
library source does not match the bytecode for class WordVectorSerializer

* Deeplearning4j version :1.0.0-beta6

**Comment by hosuaby** [comment]
Hm. Looks like your classpath simply missing `slf4j-api`. Try solution from here: https://stackoverflow.com/questions/61015394/android-java-lang-noclassdeffounderror-failed-resolution-of-lorg-slf4j-logge
