### ISSUE TITLE
libnd4j: Mod operation sometimes failing on float32/64 

### ISSUE THREAD

**Issue by atuzhykov** [deeplearning4j/deeplearning4j#8954]
During TF import tests was noticed mod op failing on floating point dtypes 
[Isolated test and stacktrace](https://gist.github.com/atuzhykov/ee768184d7c274b0dbddd5ea216af39c)

upd.
odd observation
this code fragment passed test
```
INDArray x = Nd4j.createFromArray(new double[]{1.5,2});
INDArray y = Nd4j.createFromArray(new double[]{1,2});
DynamicCustomOp op = DynamicCustomOp.builder("mod")
        .addInputs(x,y)
        .build();
```
this not
```
INDArray x = Nd4j.rand(DataType.DOUBLE, 2);
INDArray y = Nd4j.rand(DataType.DOUBLE, 2);
DynamicCustomOp op = DynamicCustomOp.builder("mod")
        .addInputs(x,y)
        .build();
```

**Comment by raver119** [comment]
Exception comes from integer division by zero.

That was a legacy consideration: Mod op was integer mod. FMod was separate floating-point implementation. Now mod works in the same way as FMod, and accepts both integer and floating point arguments. However, division by zero is still a bad idea for integer data types.
