### ISSUE TITLE
Suggestion: Silhouette Coefficient calculation on GPU

### ISSUE THREAD

**Issue by madhs53** [deeplearning4j/deeplearning4j#8958]
Hi DL4J team,

Just wondering if it would be possible to increase performance of calculating the silhouette coefficient (ie. on a ClusterSet) by running these operations GPU. Calculating this score is very computationally expensive. On experiments we've run it can take 3 times as long to compute this score as it takes to generate the ClusterSet.

**Comment by agibsonccc** [comment]
@madhs53  this is unfortunately not as much of a priority, but we would be supportive of helping port some of this work over
