### ISSUE TITLE
Failed to execute goal org.bytedeco:javacpp:1.5.3:build (javacpp-cppbuild-compile) on project libnd4j

### ISSUE THREAD

**Issue by nitin2212** [deeplearning4j/deeplearning4j#8959]
#### Issue Description

Please describe our issue, along with:
Executing mvn clean install throw this error

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version : 4
* Platform information (OS - Linux)
* CUDA version, if used- No
* NVIDIA driver version, if in use - No

#### Additional Information

Where applicable, please also provide:

Failed to execute goal org.bytedeco:javacpp:1.5.3:build (javacpp-cppbuild-compile) on project libnd4j: Execution javacpp-cppbuild-compile of goal org.bytedeco:javacpp:1.5.3:build failed: Process exited with an error: 1 -> [Help 1]

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by treo** [comment]
As a normal user, you don't have to build Deeplearning4j to use it. You can use it directly by specifying it as a dependency in your build tool.

Overall, we can't help you with the provided information. Please share a bit more about what you have tried doing, the full build log and why you are trying to build from source in the first place.

Also, there is no Deeplearning4J 4.
