### ISSUE TITLE
Output dimension not checked during training

### ISSUE THREAD

**Issue by adkafka** [deeplearning4j/deeplearning4j#896]
I made a mistake and my dataset label matrix was the wrong size (200x1x2 instead of 200x2). However, no errors were displayed and the network seemed to train and test, but the behaviour was unexpected. The fitness scores were very high and mostly random. 

Also, this caused another issue with the iteration listener that references to this bug.

It would have saved me many hours if the library reported this error instead of behaving erratically.

**Comment by agibsonccc** [comment]
To be fair, this is what we have people bug us on gitter for. We can't have the neural network make that assumption JFYI. We have datasets with multi dimensinoal arrays such as images (3d+). Other libraries besides us do this as well. I'm going to close this. Bother us on gitter if there's an issue like this.
