### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by Ben-Epstein** [deeplearning4j/deeplearning4j#8965]
#### Issue Description

Documentation [here](https://deeplearning4j.konduit.ai/samediff/importing-tensorflow#finding-the-model-input-outputs-and-running-inference) states that you pass in a `List<String>, INDArray` for the `input` and `output` functions, but when I tried that I get the error 
```error: no suitable method found for input(List<String>,INDArray)```

Looking at the docs [here](https://deeplearning4j.org/api/latest/org/nd4j/autodiff/samediff/config/BatchOutputConfig.html#input-java.lang.String-org.nd4j.linalg.api.ndarray.INDArray-) it looks like the input needs a String, not a List<String>

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j 1.0.0-beta7
* Platform information Ubuntu

#### Additional Information

Where applicable, please also provide:

* pom.xml file or similar (also in a Gist)
```
<dependencies>
<dependency>
 <groupId>org.nd4j</groupId>
 <artifactId>nd4j-native</artifactId>
 <version>1.0.0-beta7</version>
</dependency>
<dependency>
<groupId>org.nd4j</groupId>
   <artifactId>nd4j-native</artifactId>
   <version>1.0.0-beta7</version>
   <classifier>linux-x86_64-avx2</classifier>
 </dependency>
 <dependency>
    <groupId>org.deeplearning4j</groupId>
    <artifactId>deeplearning4j-modelimport</artifactId>
    <version>1.0.0-beta7</version>
</dependency>
 <dependency>
    <groupId>org.deeplearning4j</groupId>
    <artifactId>deeplearning4j-core</artifactId>
    <version>1.0.0-beta7</version>
</dependency>
</dependencies>
```

**Comment by treo** [comment]
You are right, the documentation was misleading at that point. It shouldn't be reusing the `inputs` variable that was defined above. I changed it to state `.input(inputName, inputArray)` instead.
