### ISSUE TITLE
LSTM failing on GPU with cudaMalloc failed runtime exception

### ISSUE THREAD

**Issue by nimishatandon** [deeplearning4j/deeplearning4j#8969]
#### Issue Description
Am training an LSTM classifier ( which worked perfectly well on CPU) on a GPU server and it is failing with a run-time exception for cudaMalloc failed.

#### Version Information
Cuda with Cudnn version 10.0
Dl4j and Nd4j version - Beta6

* Platform - Linux 
* NVIDIA driver version, if in use

#### Additional Information

Where applicable, please also provide : attached a snapshot of the stack trace.

Also was able to train with a batch size of 256 on CPU reduced to batch size of 32 now. Still not working.

**Comment by nimishatandon** [comment]
#
![IMG_20200520_181621](https://user-images.githubusercontent.com/56741349/82513349-99ef7d00-9ac7-11ea-84b2-883ff177e7a9.jpg)

**Comment by sascha08-15** [comment]
1) you know, you can take "actual" screenshots on almost any OS, or?  ;)
2) It all depends on the memory configuration - so if anyone here should be able to help you, you need to provide those details. RAM of CPU used. VRAM of your GPU. The preferences for JavaCPP is also helpful as far as I saw in other issue descriptions.

I had a similar problem and constantly experiencing some memory - let's say "limitations" when I use GPU training and LSTM. So maybe, I can help you if you provide above details for me.

And your used workspace setup would be also helpful (if any).

Hope it brings us closer to a solution. Cheers!

**Comment by sascha08-15** [comment]
And btw. you may use nvidia-smi to actually monitor your GPU (incl. memory allocation). What I assume, it would have shown then, is, that you GPU memory was almost full such that the malloc of that exception above fails.

**Comment by raver119** [comment]
1. Please try the latest dl4j/nd4j version, which is 1.0.0-beta7
2. If the problem is reproducible there - please show us all the output you'll get there. You can do that by copying it into service like https://gist.github.com/

**Comment by raver119** [comment]
@sascha08-15 got any news?

**Comment by nimishatandon** [comment]
Thanks guys for your inputs. I was calling the datasetloss calculator to calculate score on the train and test data set after every epoch which was causing it to go out of memory . Which then resulted in this error. 

Getting rid of that in my loop helped me get rid of the error.
