### ISSUE TITLE
windows rl4j example gym errors

### ISSUE THREAD

**Issue by cagneymoreau** [deeplearning4j/deeplearning4j#8978]
Below is an error and a solution to running the gym in a windows machine. 

When trying to use the cartpole example I encountered this error.
https://github.com/eclipse/deeplearning4j/issues/6275

I followed the thread advice and loaded python 2.7 along side my python 3.7.
The cartpole example would work but it would not render and crashed after training when the visualizations are set to occur using python 2.7

Error is as follows:
Caused by: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]

Interesting enough if I tried to run cartpole example a second time without closing the interpreter I would get a new error in my python window as follows: ImportError: cannot import name gl_info
I tried updating pyglet and discovered through error messages that the newest version of pyglet is not compatable with python 2.7.

I tried reinstalling the -r requirements.txt file through my python 3.7.4 interpreter and encountered an error when installing the numpy version. The file asks for numpy==1.11.1rc1 but I tried installing 1.11.1 instead.

This worked and now I am running the server through via my 3.7.4 python interpreter and the cartpole example trains and will visualize.

**Comment by saudet** [comment]
Please try with 1.0.0-beta7 or 1.0.0-SNAPSHOT. CPython now gets bundled, so
no need to worry about what is installed on your machine.

**Comment by cagneymoreau** [comment]
thanks!

**Comment by cagneymoreau** [comment]
gym server for python 3.* and tensorflow 2.*
https://github.com/cagneymoreau/gym-http-api
