### ISSUE TITLE
Per-sample weights using masks

### ISSUE THREAD

**Issue by cacophany53** [deeplearning4j/deeplearning4j#8997]
Hi DL4J community.

Is it currently possible to specify per-sample weights by using mask values other than 0 or 1? (ie. 0.5 for half the weight of a normal sample, 2 for twice the weight). Alternatively could samples be weighted by applying a non-integer to a label value? I haven't been able to find any DL4J documentation on per-sample weights.

**Comment by cacophany53** [comment]
Does anyone have any insights into this?

**Comment by agibsonccc** [comment]
Closing this. For future readers, please use our forums for these kinds of questions. The issue tracker is for  bugs. As of now, only per label weights are supported.
