### ISSUE TITLE
Unable to start standalone UI server at version 1.0.0-beta7 

### ISSUE THREAD

**Issue by aeiplatform** [deeplearning4j/deeplearning4j#9001]
#### Issue Description
After upgrading the deeplearning library, I can't start the UI server.
Server is in the separated Spring Boot module configured as:
`UIServer.getInstance().enableRemoteListener();`

Project is using Spring Cloud.
Both Spring Boot initializations are identical except after **Started Application** the UI server is stopped.

##### 1.0.0-beta6
**build.gradle.kts**
```
dependencies {
    implementation("org.deeplearning4j:deeplearning4j-ui:1.0.0-beta6")
}
```
**Output**
```
[ntloop-thread-0] org.deeplearning4j.ui.VertxUIServer      : Deeplearning4j UI server started at: http://localhost:9000
[  restartedMain] org.deeplearning4j.ui.VertxUIServer      : StatsStorage instance attached to UI: InMemoryStatsStorage(uid=f26e0290)
.
.
.
... : Started Application in ...
```

##### 1.0.0-beta7
**build.gradle.kts**
```
dependencies {
    implementation("org.deeplearning4j:deeplearning4j-ui:1.0.0-beta7")
}
```
**Output**
```
[ntloop-thread-0] org.deeplearning4j.ui.VertxUIServer      : Deeplearning4j UI server started at: http://localhost:9000
[  restartedMain] org.deeplearning4j.ui.VertxUIServer      : StatsStorage instance attached to UI: InMemoryStatsStorage(uid=1dae6192)
.
.
.
... : Started Application in ...
[      Thread-11] org.deeplearning4j.ui.VertxUIServer      : Deeplearning4j UI server is auto-stopping after thread (name: restartedMain) died.
[ntloop-thread-0] org.deeplearning4j.ui.VertxUIServer      : Deeplearning4j UI server stopped.
```

**Comment by treo** [comment]
In beta7 the UI server is automatically stopped when its starting thread is stopped, in order to not keep an application running when it is actually finished.

I guess the remote option hasn't been considered in this case. 

@printomi you've implemented that feature, any ideas?

**Comment by aeiplatform** [comment]
@printomi if you want to handle some operations at the shutdown point, please use a shutdown hook instead of a dirty thread joining.

`Runtime.getRuntime().addShutdownHook(new Thread(() -> System.out.println("Termination.")));`

**Comment by printomi** [comment]
@aeiplatform thank you for pointing out that using a shutdown hook would be better than a dirty `Thread.join()`. Please, check out my PR with this implementation: https://github.com/eclipse/deeplearning4j/pull/9005
