### ISSUE TITLE
KerasUpsampling3D Layer isn't correctly imported

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#9004]
#### Issue Description
Originally reported at https://community.konduit.ai/t/unsupported-keras-layer-type-upsampling3d/564/7

We actually implement the layer here: https://github.com/eclipse/deeplearning4j/blob/b06fb670a420050f1edcdc398f11fe76fadf1538/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/layers/convolutional/KerasUpsampling3D.java

But during import we don't check for it:
https://github.com/eclipse/deeplearning4j/blob/b06fb670a420050f1edcdc398f11fe76fadf1538/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/utils/KerasLayerUtils.java#L296-L299

As a workaround the following **should** work (haven't tested it yet though):
```
KerasLayer.registerCustomLayer("UpSampling3D", KerasUpsampling3D.class);
```

#### Version Information
Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta7
* Platform information (OS, etc): all
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

**Comment by agibsonccc** [comment]
@treo is this still the case?

**Comment by agibsonccc** [comment]
Fixed in https://github.com/eclipse/deeplearning4j/pull/9165/commits/2d1376afaaf1340d03e8f7221efbf9fb40c95278
