### ISSUE TITLE
Change WordVectorSerializer Serializer to Avoid vStack Bug

### ISSUE THREAD

**Issue by mdavis95** [deeplearning4j/deeplearning4j#9006]
Because of #8961 (which has a workaround) loading Word2Vec fails on a CPU without the workaround.  The workaround is fine, however, it took me a long time to figure out what was going on.  In the end I pulled out the code and debugged it and finally realized it was the vstack that was failing after 8 hours for my input file (2GB word vector file).  Simply counting the words and detecting the vector size in the do while loop (in loadTxt for example) enabled the vstack to be changed to:
```
INDArray syn = Nd4j.create(words, layerSize);
int r = 0;
for (INDArray array : arrays) {
	syn.putRow(r++, array);
}
```
which works beautifully at least on CPU and takes less that 30 seconds.  Can this change or a similar change be made to make vectors to be loaded out of the box?

Full Example:
https://gist.github.com/mdavis95/30ac3b92a7477d0ff0247a48e8928a6e

**Comment by treo** [comment]
The fix should be already in Snapshots, so adding another workaround is unlikely to help, don't you think so too?

**Comment by mdavis95** [comment]
Oh I misread the ticket.  It seemed to me that the fix was Nd4j.getEnvironment().allowHelpers(false); (no comments or anything were referenced).    If the real issue was fixed that is great to here and this can be closed.

**Comment by treo** [comment]
It was originally reported on the forum: https://community.konduit.ai/t/beta-7-glove-word-vector/540

The issue then only talked about the actual underlying problem in order to focus on the bug, instead of the symptoms around it.

**Comment by mdavis95** [comment]
Perfect, thanks for linking that here. I should have searched the forum first instead of just the tickets.
