### ISSUE TITLE
apache TVM support ?

### ISSUE THREAD

**Issue by eix128** [deeplearning4j/deeplearning4j#9007]
Can we use DL4J with apache TVM ?
Or is there anything you plan in future ?
https://tvm.apache.org

**Comment by agibsonccc** [comment]
Commenting for future google search results. We're interested in doing this for integration with our samediff library. Happy to take a pull request if we don't get to this in the mean time.

**Comment by agibsonccc** [comment]
There is now an nd4j-tvm. We have more to do yet, but that will allow you to run tvm models. For something more specific, please consider opening another issue as a feature request.
