### ISSUE TITLE
Brokn link: Importing TensorFlow models -> Import Validation

### ISSUE THREAD

**Issue by hmf** [deeplearning4j/deeplearning4j#9013]
Broken link in section:

https://deeplearning4j.konduit.ai/samediff/importing-tensorflow#import-validation

Import Validation
We have a TensorFlow graph analyzing utility which will report any missing operations (operations that still need to be implemented) here

Link is:

https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/imports/TensorFlow/TensorFlowImportValidator.java

**Comment by hmf** [comment]
More broken links:

https://samediff/samediff/exampes
https://samediff/samediff/ops

in

https://deeplearning4j.konduit.ai/samediff/variables

**Comment by agibsonccc** [comment]
@treo was this ever fixed?

**Comment by agibsonccc** [comment]
Closing this due to pending docs rewrite for M1.
