### ISSUE TITLE
time series prediction - multivariate

### ISSUE THREAD

**Issue by andrewcz** [deeplearning4j/deeplearning4j#903]
is there a multivariate time series prediction application in this package.
Many thanks,
Andrew

**Comment by AlexDBlack** [comment]
Do you mean VARMA and VARIMA type models? No, we are a deep learning library. :)
If you mean recurrent neural networks - we have the LSTM model.

**Comment by andrewcz** [comment]
yer i was thinking predict vector y  with an NxN matrix. using an multivariate lstm, the literature is very light on these for temporal series. so you have an array of time series vectors, then do dimensionality reduction and predict y using the array. 
Many thanks,
Andrew

**Comment by AlexDBlack** [comment]
So yes, LSTM with multiple inputs/outputs is definitely supported. I'm going to close this.
If you have any other questions, feel free to ask on gitter.
