### ISSUE TITLE
SameDiff: tensorMmul still uses java based doDiff

### ISSUE THREAD

**Issue by treo** [deeplearning4j/deeplearning4j#9031]
#### Issue Description
tensorMmul uses a java based doDiff implementation, and in it is uses a few samediff anti patterns, like evaling variables.

It should be changed to using the c++ based implementation.

#### Version Information

* Deeplearning4j version: beta7

**Comment by Dris101** [comment]
Adding link to gist showing where java based doDiff is throwing an NPE when used with a permuted input tensor
 
https://gist.github.com/Dris101/c2663600f3d35733cef2b9331d424ec7

**Comment by agibsonccc** [comment]
@quickwritereader  could you update the op to use the nd4j c++ implementation?

**Comment by agibsonccc** [comment]
Closing: https://github.com/eclipse/deeplearning4j/issues/9031
