### ISSUE TITLE
Document Microsoft Visual C++ Redestributable dependencies in jnind4jcuda.dll

### ISSUE THREAD

**Issue by Dris101** [deeplearning4j/deeplearning4j#9033]
#### Version Information

1.0.0-beta7
Windows 10
CUDA 10.2

#### Additional Information

After installing beta 7 I ran into errors caused by missing Microsoft Visual C++ Redestributable dlls.
According to Dependencies (https://github.com/lucasg/Dependencies), jnind4jcuda.dll has dependencies on:-

- C:\WINDOWS\system32\VCRUNTIME140.dll
- C:\WINDOWS\system32\VCRUNTIME140_1.dll

I didn't have C:\WINDOWS\system32\VCRUNTIME140_1.dll installed and had to go and get it from Microsoft. I only found that out by using Dependencies to check. It might be useful to document that dependency somewhere.

Possible issue seen in https://github.com/eclipse/deeplearning4j/issues/9003 ?

**Comment by saudet** [comment]
Fixed in commit https://github.com/bytedeco/javacpp/commit/524c8ec9f08c84f4fbb0bd843d5b6a5ee3f7ddd8.
