### ISSUE TITLE
Reduce apk size using nd4j

### ISSUE THREAD

**Issue by mattiaachilli** [deeplearning4j/deeplearning4j#9040]
#### Issue Description

Hi everyone, i have an android application that use nd4j, my problem is that the apk size is too big (almost 500MB).
build.gradle: https://pastebin.com/LJDkNYzk

How can i reduce the apk size? My app needs mainly INDArray, OpenCV and NativeImageLoader.

**Comment by saudet** [comment]
Please read https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies

**Comment by mattiaachilli** [comment]
Yes i have already read that but how, can yuu help me? If you can see my build.gradle...

**Comment by agibsonccc** [comment]
This was discussed on the community forum: https://community.konduit.ai/ closing in favor of that.
