### ISSUE TITLE
Docs in the monorepo

### ISSUE THREAD

**Issue by dariuszzbyrad** [deeplearning4j/deeplearning4j#9045]
In the main doc repo (https://github.com/eclipse/deeplearning4j-docs) I see the warning:

> Warning: DO NOT edit the user guide directly in this repository. Commits will be reverted. Please make changes to the main repository here, run the autogeneration process, and open a pull request.

Where the 'here' is https://github.com/eclipse/deeplearning4j/tree/master/docs which doesn't exist.

In the mono repo I can't find any docs. Where can I find it?

**Comment by agibsonccc** [comment]
Hi, you can find the published docs here:
https://deeplearning4j.konduit.ai/

**Comment by dariuszzbyrad** [comment]
Thanks for answer, but where I can find source for contributing (PR for https://github.com/eclipse/deeplearning4j-docs is prohibited)?

**Comment by agibsonccc** [comment]
Ah, I see. Thanks for offering!  Our docs are hosted on gitbook now. It's not the most friendly for outsiders right now... @treo  would know better than me about the whole process there. I'll reopen this to document this.

**Comment by agibsonccc** [comment]
@dariuszzbyrad  here, send PRs to this github repo. Thanks! https://github.com/KonduitAI/deeplearning4j-gitbook-sync/
