### ISSUE TITLE
CUSTOM_OP_IMPL(tensormmul_bp) errors for inputs of different ranks

### ISSUE THREAD

**Issue by Dris101** [deeplearning4j/deeplearning4j#9048]
#### Issue Description

When called with tensors of different ranks the LIBND4J C++ ```tensormmul_bp```
custom op in ```dl4j\deeplearning4j\libnd4j\include\ops\declarable\generic\blas\tensormmul.cpp``` throws a runtime error
from ```ShapeUtils::evalShapeForTensorDot``` in ```include\helpers\impl\MmulHelper.cpp```

#### Version Information

* 1.0.0-beta7
* Windows 10

#### Additional Information

See https://community.konduit.ai/t/error-using-tensormmul-on-permuted-tensor/675

Test code in https://gist.github.com/Dris101/9983f0aedaa78d9477b4d3a1c8770bd0

(only CPU tested)

**Comment by quickwritereader** [comment]
@Dris101 thanks for the reporting issue.
could you show minimal reproducible example (here: array shapes and input) related to your issue so that I can directly check it on C++?
thanks

**Comment by quickwritereader** [comment]
I improved the op gist by adding derivative against the cost function and also generating libnd4j test case
[tensormmul_gradient_libnd4j_test-py](https://gist.github.com/quickwritereader/ef612c913a0521be22805eddc82385ba#file-tensormmul_gradient_libnd4j_test-py)

**Comment by quickwritereader** [comment]
if we manually expand the shape with 1s, we get the correct results.
it seems we just need to fix shape mismatch and thats all
