### ISSUE TITLE
LocallyConnected2D NullPointerException array values at LocallyConnected2D.java:216

### ISSUE THREAD

**Issue by jljljl** [deeplearning4j/deeplearning4j#9050]
At LocallyConnected2D.class inputArray contains null values when using padding and/or when using ConvolutionMode.Truncate with uneven fit.

Null values causes NullPointerException. SDValidation object is trying to invoke method dataType() of null SDVariable.
```
SDVariable[] inputArray = new SDVariable[outH * outW];
        for (int i = 0; i < outH; i++) {
            for (int j = 0; j < outW; j++) {
                SDVariable slice = layerInput.get(SDIndex.all(), // miniBatch
                                SDIndex.all(), // nIn
                                SDIndex.interval(i * sH, i * sH + kH), // kernel height
                                SDIndex.interval(j * sW, j * sW + kW) // kernel width
                );
                
                //argument array contains null values
                inputArray[i * outH + j] = sameDiff.reshape(slice, 1, miniBatch, featureDim);
            }
        }
        SDVariable concatOutput = sameDiff.concat(0, inputArray); // (outH * outW, miniBatch, featureDim)
```

```
java.lang.NullPointerException
	at org.nd4j.autodiff.samediff.ops.SDValidation.isSameType(SDValidation.java:230)
	at org.nd4j.autodiff.samediff.ops.SDBaseOps.concat(SDBaseOps.java:418)
	at org.deeplearning4j.nn.conf.layers.LocallyConnected2D.defineLayer(LocallyConnected2D.java:216)
	at org.deeplearning4j.nn.layers.samediff.SameDiffLayer.doInit(SameDiffLayer.java:316)
	at org.deeplearning4j.nn.layers.samediff.SameDiffLayer.activate(SameDiffLayer.java:90)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doForward(LayerVertex.java:111)
	at org.deeplearning4j.nn.graph.ComputationGraph.outputOfLayersDetached(ComputationGraph.java:2380)
...
```

**Comment by jljljl** [comment]
Found fourth bug when using uneven width/height. I guess to leave a comment instead of adding new ticked cause the problem is in not only one for this class. Got ArrayIndexOutOfBoundsException with outH = 10, outW = 2 on third iteration
```
java.lang.ArrayIndexOutOfBoundsException: 20
	at org.deeplearning4j.nn.conf.layers.LocallyConnected2D.defineLayer(LocallyConnected2D.java:213)
```
The line is:
`inputArray[i * outH + j] = sameDiff.reshape(slice, 1, miniBatch, featureDim);`
i guess it should be 
` inputArray[i * outW + j] = sameDiff.reshape(slice, 1, miniBatch, featureDim);`
or
` inputArray[j * outH + i] = sameDiff.reshape(slice, 1, miniBatch, featureDim);`

At least indexing at images is used with index = x + width * y. But here i is vertical and j is horizontal parameters so it's looks like index = x + height * y.

**Comment by jljljl** [comment]
I've fixed some bugs i posted. How can i commit fixes?

**Comment by agibsonccc** [comment]
Hi, submit a PR to https://github.com/eclipse/deeplearning4j and we'll take a look. Thanks!

**Comment by jljljl** [comment]
> Hi, submit a PR to https://github.com/eclipse/deeplearning4j and we'll take a look. Thanks!

Got exception on push: cannot connect to URI... git-receive-pack not permitted on url...

**Comment by agibsonccc** [comment]
@jljljl  sorry not sure what  issue you're having, that sounds strange. Could you try again? Sorry still catching up on backlog here. Take a look at github's docs here: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request If you're having issues, try using the github desktop app.

**Comment by agibsonccc** [comment]
@jljljl  just revisiting backlog again, I take it you're not interested in pursuing this? If not, I'll just flag it for now and see if we can get to it later.

**Comment by jljljl** [comment]
@agibsonccc Sorry for being offline. I've been focused on other things. Seems i don't have permissions for it repository. Please check pull request
