### ISSUE TITLE
Transformer with multihead attention

### ISSUE THREAD

**Issue by data-llectual** [deeplearning4j/deeplearning4j#9052]
Hi,

I am opening this as issue here as I have not got any response to my earlier query: 
https://community.konduit.ai/t/transformer-attention-nlp/740

I am trying to build text classification using transformer block with multihead attention in dl4j.
Would greatly appreciate help in this regard.

Thanks

**Comment by agibsonccc** [comment]
Hi, the forum does not have a guaranteed response time. Opening an issue pointing this out is just spam. I'm closing this.
