### ISSUE TITLE
Nd4jBackend using wrong ClassLoader

### ISSUE THREAD

**Issue by novog** [deeplearning4j/deeplearning4j#9058]
I have nd4j working in my Maven Kotlin project when run from a packaged jar file. However, when I try calling some nd4j functions in the IntelliJ REPL under the context of the same project, I get an `Nd4jBackend$NoAvailableBackendException`. It would vastly improve productivity when trying to explore data or new algorithms if nd4j could be used from the REPL. Example code that results in this error:

    val a = zeros(1000, 1000)

The problem happens in `Nd4jBackend.load`, where the attempt to load `Nd4jBackend` using `ServiceLoader` provides an empty iterator, apparently because the default `ClassLoader` in this context does not include the relevant .jar files, such as nd4j-api-1.0.0-beta7.jar, nd4j-cuda-10.2-1.0.0-beta7.jar, and nd4j-cuda-10.2-1.0.0-beta7-windows-x86_64.jar.

I tried replacing the current thread's `ClassLoader` with an augmented loader that does include those paths prior to calling any nd4j code. When doing so, the resulting iterator how has a result, but calling `next()` on it results in:

> java.util.ServiceConfigurationError: org.nd4j.linalg.factory.Nd4jBackend: Provider org.nd4j.linalg.jcublas.JCublasBackend not a subtype

So the `JCublasBackend` class has apparently already been loaded at this point. Replacing the current thread's default `ClassLoader` with that of `JCublasBackend` does appear to be a workaround. The following code produces no errors:

    Thread.currentThread().contextClassLoader = JCublasBackend::class.java.classLoader
    val a = Nd4j.zeros(1000, 1000)

One possible fix would be for `Nd4jBackend` to check for already-loaded subclasses, and if any are found, use their `ClassLoader` instead of the default.

This issue may be related to #8972. I originally posted it at the [old repo](https://github.com/deeplearning4j/nd4j/issues/2926).

***

Deeplearning4j version - 1.0.0-beta7, both with nd4j-cuda-10.2 and nd4j-cuda-10.2-platform.
platform information (OS, etc) - Windows 10
CUDA version - 10.2
cuDNN version - 7.6.5
NVIDIA driver version - 451.67

Excerpt from .pom:

```
<dependencies>
    <dependency>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-stdlib-jdk8</artifactId>
        <version>1.3.72</version>
    </dependency>
    <dependency>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-reflect</artifactId>
        <version>1.3.72}</version>
    </dependency>
    <dependency>
        <groupId>org.nd4j</groupId>
        <artifactId>nd4j-cuda-10.2</artifactId>
        <version>1.0.0-beta7</version>
    </dependency>
    <dependency>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>deeplearning4j-cuda-10.2</artifactId>
        <version>1.0.0-beta7</version>
    </dependency>
    <dependency>
        <groupId>org.deeplearning4j</groupId>
        <artifactId>deeplearning4j-ui</artifactId>
        <version>1.0.0-beta7</version>
    </dependency>
    <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>1.16.20</version>
    </dependency>
</dependencies>
```
...
```
<build>
    <plugins>
        <plugin>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-maven-plugin</artifactId>
            <version>${kotlin.version}</version>
            <configuration>
                <jvmTarget>1.8</jvmTarget>
            </configuration>
            <executions>
                <execution>
                    <id>compile</id>
                    <goals><goal>compile</goal></goals>
                    <configuration>
                        <sourceDirs>
                            <sourceDir>${project.basedir}/src/main/kotlin</sourceDir>
                            <sourceDir>${project.basedir}/src/main/java</sourceDir>
                        </sourceDirs>
                    </configuration>
                </execution>
            </executions>
        </plugin>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-jar-plugin</artifactId>
            <version>3.2.0</version>
            <configuration>
                <archive>
                    <manifest>
                        <addClasspath>true</addClasspath>
                        <mainClass>com.my.project.Main</mainClass>
                    </manifest>
                </archive>
            </configuration>
        </plugin>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>3.2.0</version>
            <executions>
                <execution>
                    <goals>
                        <goal>shade</goal>
                    </goals>
                    <configuration>
                        <filters>
                            <filter>
                                <artifact>org.eclipse*</artifact>
                                <excludes>
                                    <exclude>META-INF/*.SF</exclude>
                                    <exclude>META-INF/*.DSA</exclude>
                                    <exclude>META-INF/*.RSA</exclude>
                                </excludes>
                            </filter>
                        </filters>
                        <transformers>
                            <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
                        </transformers>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
```

**Comment by agibsonccc** [comment]
@novog there's some progress on #8972 afterwards we can just over ride it. Thanks for flagging!
