### ISSUE TITLE
DL4JInvalidConfigException when trying to import Keras pretrained model

### ISSUE THREAD

**Issue by marcoromelli** [deeplearning4j/deeplearning4j#9061]
#### Issue Description

When trying to import a Keras model saved with the `.save()` method an exception is thrown.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j 1.0.0-beta7
* Windows 10
* No CUDA
* tesnorflow-gpu 1.14.0
* Keras 2.3.1

#### Additional Information

Stacktrace: https://gist.github.com/marcoromelli/1ce708d929fd280b8c060353fbd996bc

Python code:
```Python
from keras.applications.resnet50 import ResNet50

model = ResNet50(weights='imagenet', include_top=False)
model.save('D:\\resnet50.hdf5')
```

Java code:
```Java
ComputationGraph model = KerasModelImport.
                importKerasModelAndWeights("D:\\resnet50.hdf5", false);
```

**Comment by agibsonccc** [comment]
Confirmed. Let me look in to this, thanks!

**Comment by agibsonccc** [comment]
@marcoromelli I fixed this here: https://github.com/KonduitAI/deeplearning4j/pull/521 Keep an eye out for an eclipse merge to master soon.
