### ISSUE TITLE
Incorrect calculate LU decomposition

### ISSUE THREAD

**Issue by dariuszzbyrad** [deeplearning4j/deeplearning4j#9069]
#### Issue Description
`SameDiff sameDiff = SameDiff.create();

        SDVariable sdInput = sameDiff.var(Nd4j.createFromArray(new double[]{
                5., 3., 2., 1., 2., 0., 3., 0., 4.
        }).reshape(3,3));

        SDVariable out = sameDiff.linalg().lu("lu", sdInput);

        System.out.println(out + "\n\n" + out.eval());`

Result:
SDVariable(name="lu",variableType=ARRAY,dtype=DOUBLE)

[[    5.0000,    3.0000,    2.0000], 
 [    0.6000,   -1.8000,    2.8000], 
 [    0.2000,   -0.7778,    1.7778]]

The correct decomposition is
![image](https://user-images.githubusercontent.com/6116322/90610161-53640880-e205-11ea-80cd-84894d04a334.png)

Or maybe 'lu' is not LU decomposition, but only the name is misleading?

#### Version Information

1.0.0-beta7

**Comment by mjw99** [comment]
The result here is that L and U have been merged into one; please see [here](https://biswajitsahoo1111.github.io/post/doing-linear-algebra-using-tensorflow-2/#lu) for more details. This, I think, can be closed.
