### ISSUE TITLE
Support batch-size-agnostic ReshapeVertex

### ISSUE THREAD

**Issue by novog** [deeplearning4j/deeplearning4j#9074]
I propose that `ReshapeVertex` should be enhanced to allow it to be used without specifying the batch size. Many layer types can be used freely with inputs of any batch size. This freedom allows us to easily do things like train a model using larger batches, then perform inference on smaller batches of varying size, depending on what is required by the end application.

`ReshapeVertex`, on the other hand, seems to require that the actual batch size is included in the output dimensions. For example, if individual inputs are vectors of length 100 and I want to transform them to 10x10 matrices, I can’t use `ReshapeVertex(10, 10)`, but rather must use `ReshapeVertex(n, 10, 10)`, where `n` is the batch size.

**Comment by agibsonccc** [comment]
Just make the shape -1 on what you want to be dynamic and it will work (mainly for future readers)
