### ISSUE TITLE
New Generation HopeField & Transform Networks Support

### ISSUE THREAD

**Issue by eix128** [deeplearning4j/deeplearning4j#9087]
Hi , there is a new type network named Transform.
It beats LSTM at all costs.
Now many people migrating to Transform on Keras and Python
Currently , seems like DL4J doesnt have Transform Network support
Also with new Transform Network , we can use new generation HopeField network that seems  usable.

Here is :
Hopfield Networks is All You Need (Paper Explained)
https://www.youtube.com/watch?v=nv6oFDp6rNQ

Illustrated Guide to Transformers Neural Network: A step by step explanation:
https://www.youtube.com/watch?v=4Bdc55j80l8

Hope to see these libraries as , easy to use on DL4J

**Comment by eix128** [comment]
I have found one of them also java wrapper
https://github.com/zhihu/cuBERT

https://github.com/zhihu/cuBERT/blob/master/java/src/test/java/com/zhihu/cubert/ModelTest.java

**Comment by eix128** [comment]
Also there is TurboTransformers Library on C++
https://github.com/Tencent/TurboTransformers
maybe implemented or add to DL4J can be good choice!

**Comment by agibsonccc** [comment]
@eix128 you should be able to run transformer models using our tensorflow import and samediff.
https://deeplearning4j.konduit.ai/samediff/importing-tensorflow
  more here: https://github.com/eclipse/deeplearning4j-examples/blob/master/tensorflow-keras-import-examples/README.md
