### ISSUE TITLE
Java docs should mention whether Nd4j operation creates a new copy or not

### ISSUE THREAD

**Issue by dkmisra** [deeplearning4j/deeplearning4j#909]
## Issue

There are certain Nd4j operations which do not create a new copy of INDArray and its difficult to tell from the java docs. Example, 

`INDArray transformed  = Nd4j.zeros(100);`
`INDArray nonLinear = Nd4j.getExecutioner().execAndReturn(new HardTanh(transformed));`

`nonLinear` and `transformed` reference the same memory region. This can lead to unexpected behavior and waste lots of time, if the programmer makes the wrong assumption. 
## Suggestion

Java docs or a list on the website would solve this. Crafty naming styles can also solve this as well. INDArray does this pretty well already (`muli` vs `mul`) where `i` can be read as in-place operation.

**Comment by tomthetrainer** [comment]
adding the string javadoc, so I can search this easy

**Comment by tomthetrainer** [comment]
@agibsonccc Is this issue relevant? 

Is there confusion on what operation is in place, and what creates a copy?

**Comment by eraly** [comment]
getRow, transpose and .get return views. getRows interestingly does not give back a view. 
 Nd4j.getExecutioner().execAndReturn(some transform) if this is called with a single array as an argument it will be an in place operation and what it returns will be the same array it was given. That is what the original poster is referring to here.
INDArray nonLinear = Nd4j.getExecutioner().execAndReturn(new HardTanh(transformed));
For it not be in place it would have to be
INDArray nonLinear = Nd4j.getExecutioner().execAndReturn(new HardTanh(transformed.dup()));

The way around getting a non-view is .dup() and the way to check if something is a view .isView()
A lot of the stuff is pretty well documented in the user guide http://nd4j.org/userguide#views and also in the examples. They are both pretty thorough, though the user guide maybe a little difficult to navigate with so much information.

**Comment by agibsonccc** [comment]
Reshape can sometimes return a copy.

**Comment by AlexDBlack** [comment]
@eraly covered most of it.
tensorAlongDimension always returns a view.

There's also the Transforms class: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/ops/transforms/Transforms.java
They have copy (boolean arg) overloads, default is true.

Reduction ops (sum, mean, etc along dimension) always return new arrays, don't modify the inputs (results are usually smaller size)

Re: reshape - can be a copy if it's not contiguous in memory (i.e., reshaping a view might not be possible without a copy)

**Comment by nkwoh01** [comment]
this looks resolved
