### ISSUE TITLE
Save weights of MultiLayerNetwork for importing in other models 

### ISSUE THREAD

**Issue by utri092** [deeplearning4j/deeplearning4j#9105]
#### Issue Description

Is there a way to just save the weights in a text file in the form of an array after training? I've imported a KerasModel and would like to save its weights in the form of a java equivalent NumPy array in a text file. 

The context is I would like to prune my model for other hardware platforms like GPUs, ARM devices and FPGAs and retrain it a number of times before deploying

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - 1.0.0-beta7

**Comment by agibsonccc** [comment]
@utri092 you can access the weights with model.params(). From there, you can use any of nd4j's methods. Please use https://community.konduit.ai for further questions of this nature.
