### ISSUE TITLE
Calling update(Gradient gradient) on a model that hasn't had it's gradient initialized throws a NullPointerException

### ISSUE THREAD

**Issue by sachag678** [deeplearning4j/deeplearning4j#9107]
## Issue
I'm building a distributed setup where a model is cloned and used to gather the gradients which are then passed back to the main model. The issue is that the main model cannot use the update(Gradient gradient) method without having it's gradient initialized in the manner shown below within the //REQUIRED block. If the update method is called without doing this, the gradient is set to null, so we get a NullPointerException during the update() method call. 

Would it make sense to have a function to initialize the gradient to zero for all the weights?

## Code

    val model = new MultiLayerNetwork(generateConf())
    model.init()

    val temp = model.clone()
    
    // REQUIRED
    val tempx = Nd4j.create(Array(0.0, 0.0), Array(1,2))
    val tempy = Nd4j.create(Array(0.0), Array(1,1))
    model.setInput(tempx)
    model.setLabels(tempy)
    model.computeGradientAndScore()
    //REQUIRED

    println(model.gradient())

    val x = Nd4j.create(Array(0.5, 0.5), Array(1,2))
    val y = Nd4j.create(Array(2.0), Array(1,1))
    temp.setInput(x)
    temp.setLabels(y)
    temp.computeGradientAndScore()

    val grad = temp.gradient()
    model.update(grad)

    def generateConf(): MultiLayerConfiguration = {
    val numNodes = List(2, 3, 1)

    new NeuralNetConfiguration.Builder()
      .seed(42)
      .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
      .updater(new Sgd(0.001)) // alpha
      .list()
      // input of the raw features
      .layer(0, new DenseLayer.Builder().nIn(numNodes.head).nOut(numNodes(1))
        .weightInit(WeightInit.XAVIER)
        .activation(Activation.TANH)
        .build())
      .layer(1, new OutputLayer.Builder(LossFunction.MSE)
        .weightInit(WeightInit.XAVIER)
        .activation(Activation.IDENTITY)
        .nIn(numNodes(1)).nOut(numNodes(2)).build())
      .build()
    }

    Exception in thread "main" java.lang.NullPointerException 
    at  
    org.deeplearning4j.nn.multilayer.MultiLayerNetwork.update
    (MultiLayerNetwork.java:3064)

### Version
libraryDependencies +=  "org.deeplearning4j" % "deeplearning4j-core" % "1.0.0-beta7"
libraryDependencies +=   "org.nd4j" % "nd4j-native-platform" % "1.0.0-beta7"

**Comment by agibsonccc** [comment]
@sachag678  I think what I'll do is just add a pre init method that checks if gradient is null and if it is initializes it to zeros to start.

**Comment by jljljl** [comment]
@sachag678 have you call `temp.init()`?

**Comment by jljljl** [comment]
Also check if `grad` is not null.

**Comment by agibsonccc** [comment]
Fixed long ago, forgot to close.
