### ISSUE TITLE
KerasModelImport: Error when loading a functional model with a 3D input for a flatten layer

### ISSUE THREAD

**Issue by AlexLukasT** [deeplearning4j/deeplearning4j#9109]
#### Issue Description

Trying to load a Keras functional model with a 3D input for a flatten layer results in an UnsupportedKerasConfigurationException:  
```python
inp = layers.Input(shape=(10, 10, 1))  # works
inp = layers.Input(shape=(10, 10, 10, 1))  # does not work
x = layers.Flatten()(inp)
out = layers.Dense(10)(x)
```

```java
ComputationGraph model = KerasModelImport.importKerasModelAndWeights(configPath, weigthsPath);
```

```
org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Layer flatten could not be mapped to Layer, Vertex, or InputPreProcessor. Please file an issue at https://github.com/eclipse/deeplearning4j/issues.
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraphConfiguration(KerasModel.java:379)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraph(KerasModel.java:415)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraph(KerasModel.java:404)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:263)
	at Main.main(Main.java:10)
```

#### Version Information

* Deeplearning4j version: 1.0.0-beta7
* Platform information: Ubuntu 20.04.1 LTS
* CUDA version: 11.0
* NVIDIA driver version: 450.66

#### Additional Information

I created a gist with all information and a minimal example:
 https://gist.github.com/AlexLukasT/56325eae892d3e517c9c6ba362c00dbe

**Comment by agibsonccc** [comment]
@AlexLukasT  JFYI I'll look at this before the release in the next few weeks here. Sorry finishing our new model import setup for TF and Onnx and still need to catch up on backlog.

**Comment by agibsonccc** [comment]
Fixed in https://github.com/eclipse/deeplearning4j/commit/d978dc986b7e86f5db3349af2c7bf00938946694
