### ISSUE TITLE
Distributed Training with Spark on Raspberry pi 4 Fails

### ISSUE THREAD

**Issue by utri092** [deeplearning4j/deeplearning4j#9110]
#### Issue Description
I was able to use local mode successfully and then attempted to try distributed training. I use hadoop HDFS for reading csv files.
I ran a spark-submit with the Logger Level set to WARN to time the training period and encountered the error below.

![image](https://user-images.githubusercontent.com/41176826/95690415-1ef45200-0c74-11eb-9387-8bf82b58eed7.png)
 
I thought this was a hadoop issue but was able to successfully run distributed inference. Writes and reads to the Hadoop HDFS do not fail.

I ran the uber-jar file separately using `java -cp <jar file> <class-pname>` below to see all the logs and encountered the issue below. Looks like a RDD and Scala complaint from the program.

![image](https://user-images.githubusercontent.com/41176826/95690480-a9d54c80-0c74-11eb-923b-b53d99a613a1.png)
![image](https://user-images.githubusercontent.com/41176826/95690485-b194f100-0c74-11eb-89a3-ae912ff671a2.png)
![image](https://user-images.githubusercontent.com/41176826/95690756-6da2eb80-0c76-11eb-87d1-ceabd6bdbed4.png)

I followed the benchmarks guide and ran 3 cases. The dataset I used was a very small CSV of 20 MB. I tried with 1 to 3 executors with executor memory set to 2Gb as well as 1Gb.

Case 1:
**Epochs:** 50.
**Result:**  I was able to print the number of epochs. It failed straight after.

Case 2:
**Epochs:** 1.
**Result:**  It fails on a single fit

Example Code for case 2: 

![image](https://user-images.githubusercontent.com/41176826/95690665-c58d2280-0c75-11eb-855c-0cec5bd3110d.png)

#### Additonal-Files
Pom.xml:  https://gist.github.com/utri092/91a262979b531fc59222c84793b7cbfc
Code-File: https://gist.github.com/utri092/fed884436ded22710fb076f5a177d4b2

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - 1.0.0-beta-7
* Platform information = Raspbian 10 (buster) 32 bit
* Hadoop version : azure.hadoop 2.7.4
* Apache-Spark: 2.4.5

**Comment by agibsonccc** [comment]
@utri092  this looks like a problem with the training data not being distributed properly. Did you manage to ever debug your HDFS setup here? Did the files actually exist?  Sorry for the late reply, just catching up on backlog before release.

**Comment by utri092** [comment]
@agibsonccc . Thanks for the reply. Yes. I used the same files for inference and save the predictions in a text file.

**Comment by agibsonccc** [comment]
@utri092  again still working on backlog yet. ARM should work a lot better after the release here. I'll make sure to take a look at this as part of the QA.

**Comment by agibsonccc** [comment]
Closing this. You were using older versions of some datavec spark modules. I'm not sure what tutorial this was pulled from, but never mix versions of dl4j/datavec. See here: https://gist.github.com/utri092/91a262979b531fc59222c84793b7cbfc#file-pom-xml-L93
