### ISSUE TITLE
NoClassDefFoundError - BasicNDArrayCompressor

### ISSUE THREAD

**Issue by lavajaw** [deeplearning4j/deeplearning4j#9118]
#### Issue Description

Description is provided here:
https://community.konduit.ai/t/noclassdeffounderror-basicndarraycompressor/944?u=lavajaw

#### Version Information

Relevant versions:
Version beta6 and beta7.

**Comment by hosuaby** [comment]
I can't garantie that this is a probleme, but for me it looks like a classloading issue. In current snaphsot, I added features to specify classloaders for ND4J and DL4j: https://github.com/eclipse/deeplearning4j/pull/9115

You can give it a try.
