### ISSUE TITLE
Restoring model fails: InputStream.available() = 0

### ISSUE THREAD

**Issue by PossessedC0bra** [deeplearning4j/deeplearning4j#9124]
#### Issue Description

I am trying to load a model from a stream i received from a REST Api. Every time i try to load it the method https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/util/ModelSerializer.java#L956-L971 throws an error as the available() function on the input stream always returns 0.

The method is also annotated with a comment referencing another issue: https://github.com/eclipse/deeplearning4j/issues/4887. In the issue thread there is a commit commenting out the method. It looks like this change has been reverted by the migration to this repository.

**Comment by agibsonccc** [comment]
@PossessedC0bra  do you have the model? That sounds like a corrupt zip file.

**Comment by PossessedC0bra** [comment]
@agibsonccc Yes i do have it. It is clean though, i have already checked that. 
Funny thing is when running the application locally it works perfectly fine. Also when attaching a remote debugger and placing a breakpoint at the location, where inputStream.available() is called prevents the error from ever happening. As soon as i remove the breakpoint the remote application runs into the same InputStream.available = 0 error every single time. 

Might this have something to do with latency over the network or something?

**Comment by miterial** [comment]
I restore model from Spring GridFS and have the same problem with InputStream.available() = 0

**Comment by agibsonccc** [comment]
Sorry just doing clean up here. There wasn't really a lot to go on here. I'm guessing this wasn't a bug. For future issues like this please post on the forums: https://community.konduit.ai - if we don't respond please feel free to ping (not excessively of course :) ) - thanks!
