### ISSUE TITLE
SD_FORBID_HELPERS not doing anything

### ISSUE THREAD

**Issue by Ulrhol** [deeplearning4j/deeplearning4j#9125]
#### Issue Description

Ran into some problem with DNN on an old AMD Turion processor so wanted to test without the native mkldnn helper. Tried various way to set SD_FORBID_HELPERS to disable the helper but couldn't get it to work.

#### Version Information

Running deeplearning4j-1.0.0-beta7

#### Additional Information

I found in libnd4j/include/legacy/impl/Environment.cpp what looks like a typo in the check. It pulls in the environment variable into a local variable and then performs a check against another local variable. 

```
        /**
         * If this env var is defined - we'll disallow use of platform-specific helpers (mkldnn, cudnn, etc)
         */
        const char* forbid_helpers = std::getenv("SD_FORBID_HELPERS");
        if (max_master_threads != nullptr) {
            _allowHelpers = false;
        }

```

The forbid_helpers variable is not checked anywhere else in the code.

**Comment by saudet** [comment]
Try to set SD_MASTER_THREADS then and see if that makes a difference :) 

Also try to set ND4J_FALLBACK, ND4J_MKL_FALLBACK=true, and SD_BLAS_FALLBACK.

**Comment by Ulrhol** [comment]
Pro tip! :)

I already did as I found missing check in the code. And it worked. Now it's a lot slower on the DNN operations but it hasn't crashed yet. I'll keep watching it but previous record was 13h now it already passed 25h so looks promising.

**Comment by saudet** [comment]
Awesome! Please send a pull request with the fix if possible. Thanks!

**Comment by Ulrhol** [comment]
You got it. I created PR #9126 but need to get the ECA signed.

**Comment by Ulrhol** [comment]
Created PR #9127 instead. Looks like the signoff worked this time.
