### ISSUE TITLE
Destroy Neural Network completely (Memory Leak)

### ISSUE THREAD

**Issue by 1Demo** [deeplearning4j/deeplearning4j#9131]
I am writing a genetic algorithm which generates several neural networks and calculates their fitness. After that the neural network is not needed anymore and can be removed. However, they seem to stay alive in the off-heap memory and thus leading to a memory leak after a while. How can I destroy / remove the neural network completely after receiving the fitness value (evaluation)?

**Comment by agibsonccc** [comment]
@1Demo  you're looking likely at workspaces. https://deeplearning4j.konduit.ai/config/config-memory/config-workspaces

Since you asked about this on the forum (https://community.konduit.ai/t/destroy-neural-network-completely-memory-leak/1009/3) I'm closing this.
