### ISSUE TITLE
How do I use a MNIST model to verify a number image?

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [deeplearning4j/deeplearning4j#9134]
#### Issue Description
- expected behavior:Mnist model is obtained from DL4J
- encountered behavior:How do I load the model?

#### Version Information
* Deeplearning4j version: 1.0.0 beta7
* Platform information (OS, etc): deepin20
* CUDA version, if used: none
* NVIDIA driver version, if in use: none

**Comment by agibsonccc** [comment]
@Conmi-WhiteJoker  please elaborate your question more and move support questions to the forums: https://community.konduit.ai/ thanks!

**Comment by Conmi-WhiteJoker** [comment]
Thanks for helping

> @Conmi-WhiteJoker please elaborate your question more and move support questions to the forums: https://community.konduit.ai/ thanks!

Thanks for helping！
