### ISSUE TITLE
Rl4j - Async Learning single global lock

### ISSUE THREAD

**Issue by pmichele** [deeplearning4j/deeplearning4j#9135]
#### Issue Description

How does the new AsyncGlobal work? I see AsyncGlobal.applyGradient() acquires the single lock before updating. AsyncGlobal.getTarget() also acquires the lock before returning a reference but releases it immediately, which means another thread can acquire the lock and perform applyGradient(). In the meanwhile the first thread could copy() the parameters or perform any read operation concurrently. This happens for instance in AsyncThreadDiscrete.trainSubEpoch(). Is my understanding incorrect?

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version:  1.0.0-beta7
#### Contributing

Maybe change `current.copy(getAsyncGlobal().getTarget());` to

```
getAsyncGlobal().getUpdateLock().lock();
current.copy(getAsyncGlobal().getTarget());
getAsyncGlobal().getUpdateLock().unlock();
```

in AsyncThreadDiscrete.trainSubEpoch()

**Comment by agibsonccc** [comment]
Closing, not supporting rl4j anymore.
