### ISSUE TITLE
SameDiff intermediate results

### ISSUE THREAD

**Issue by MotoCommando** [deeplearning4j/deeplearning4j#9139]
Hi, I have loaded my cnn tensorflow model and I would like to get intermediate results for chosen layer. I have seen [this ](https://deeplearning4j.org/api/latest/org/deeplearning4j/nn/multilayer/MultiLayerNetwork.html#activateSelectedLayers-int-int-org.nd4j.linalg.api.ndarray.INDArray-)method in MultiLayerNetwork class. I haven't found similar method with SameDiff. 

Is there a way to transfer SameDiff to MultiLayerNetwork? Will SameDiff support getting intermediate results?

**Comment by agibsonccc** [comment]
@MotoCommando  please try to use https://community.konduit.ai for user questions like this. Here's an example that shows variables in samediff: https://github.com/eclipse/deeplearning4j-examples/blob/master/samediff-examples/src/main/java/org/nd4j/examples/samediff/quickstart/basics/Ex1_SameDiff_Basics.java
A SameDiff instance can output intermediate results. outputAll is what you want:
https://github.com/eclipse/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/samediff/SameDiff.java#L2475

**Comment by MotoCommando** [comment]
@agibsonccc Thanks for reply. Ok next time I will with qestions there.
