### ISSUE TITLE
Cannot build android-examples

### ISSUE THREAD

**Issue by yzq986** [deeplearning4j/deeplearning4j#9140]
Issue Description
Hello, I am new to deeplearning4j, and when I try to build the android example, it shows that:
Could not find nd4j-native-1.0.0-SNAPSHOT-android-arm.jar (org.nd4j:nd4j-native:1.0.0-SNAPSHOT:20201215.045005-20693).
Searched in the following locations:
https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/nd4j-native/1.0.0-SNAPSHOT/nd4j-native-1.0.0-20201215.045005-20693-android-arm.jar

But after I search for the directory "https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/nd4j-native/1.0.0-SNAPSHOT/", it shows that there's no android jar at all. What should I do to download this jar?

I also follow the code on README to download by mvn. But it also gives the error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:get (default-cli) on project standalone-pom: Couldn't download artifact: Missing:
[ERROR] ----------
[ERROR] 1) org.nd4j:nd4j-native:jar:android-arm:1.0.0-SNAPSHOT
[ERROR]
[ERROR] Try downloading the file manually from the project website.
[ERROR]
[ERROR] Then, install it using the command:
[ERROR] mvn install:install-file -DgroupId=org.nd4j -DartifactId=nd4j-native -Dversion=1.0.0-SNAPSHOT -Dclassifier=android-arm -Dpackaging=jar -Dfile=/path/to/file
[ERROR]
[ERROR] Alternatively, if you host your own repository you can deploy the file there:
[ERROR] mvn deploy:deploy-file -DgroupId=org.nd4j -DartifactId=nd4j-native -Dversion=1.0.0-SNAPSHOT -Dclassifier=android-arm -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR]
[ERROR] Path to dependency:
[ERROR] 1) org.apache.maven.plugins:maven-downloader-plugin:jar:1.0
[ERROR] 2) org.nd4j:nd4j-native:jar:android-arm:1.0.0-SNAPSHOT
[ERROR]
[ERROR] ----------
[ERROR] 1 required artifact is missing.
[ERROR]
[ERROR] for artifact:
[ERROR] org.apache.maven.plugins:maven-downloader-plugin:jar:1.0
[ERROR]
[ERROR] from the specified remote repositories:
[ERROR] central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false),
[ERROR] snapshots (https://oss.sonatype.org/content/repositories/snapshots, releases=true, snapshots=true)
[ERROR]

**Comment by agibsonccc** [comment]
@yzq986  we disabled android builds temporarily due to CI slow downs. We'll do a release soon that will allow you to use the android examples. I'm closing this due to the pending release.
