### ISSUE TITLE
after I use DataSet.shuffle method all the data set change to zero.

### ISSUE THREAD

**Issue by jahan-afrouz** [deeplearning4j/deeplearning4j#9142]
I am using nd4j-cuda-10.2.platform 1.0.0-beta7. but after I shuffle the data set it is set to all zeros.

**Comment by jahan-afrouz** [comment]
this is IrisClassifier example Dataset before and after shuffle. after shuffle OUTPUT segment are all zeros
[https://github.com/eclipse/deeplearning4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/quickstart/modeling/feedforward/classification/IrisClassifier.java](url) 
befor shuffling:
`===========INPUT===================`
`[[    5.1000,    3.5000,    1.4000,    0.2000], 
 [    4.9000,    3.0000,    1.4000,    0.2000], 
 [    4.7000,    3.2000,    1.3000,    0.2000], 
 [    4.6000,    3.1000,    1.5000,    0.2000], 
 [    5.0000,    3.6000,    1.4000,    0.2000], 
 [    5.4000,    3.9000,    1.7000,    0.4000], 
 [    4.6000,    3.4000,    1.4000,    0.3000], 
 [    5.0000,    3.4000,    1.5000,    0.2000], 
 [    4.4000,    2.9000,    1.4000,    0.2000], 
 [    4.9000,    3.1000,    1.5000,    0.1000], 
 [    5.4000,    3.7000,    1.5000,    0.2000], 
 [    4.8000,    3.4000,    1.6000,    0.2000], 
 [    4.8000,    3.0000,    1.4000,    0.1000], 
 [    4.3000,    3.0000,    1.1000,    0.1000], 
 [    5.8000,    4.0000,    1.2000,    0.2000], 
 [    5.7000,    4.4000,    1.5000,    0.4000], 
 [    5.4000,    3.9000,    1.3000,    0.4000], 
 [    5.1000,    3.5000,    1.4000,    0.3000], 
 [    5.7000,    3.8000,    1.7000,    0.3000], 
 [    5.1000,    3.8000,    1.5000,    0.3000], 
 [    5.4000,    3.4000,    1.7000,    0.2000], 
 [    5.1000,    3.7000,    1.5000,    0.4000], 
 [    4.6000,    3.6000,    1.0000,    0.2000], 
 [    5.1000,    3.3000,    1.7000,    0.5000], 
 [    4.8000,    3.4000,    1.9000,    0.2000], 
 [    5.0000,    3.0000,    1.6000,    0.2000], 
 [    5.0000,    3.4000,    1.6000,    0.4000], 
 [    5.2000,    3.5000,    1.5000,    0.2000], 
 [    5.2000,    3.4000,    1.4000,    0.2000], 
 [    4.7000,    3.2000,    1.6000,    0.2000], 
 [    4.8000,    3.1000,    1.6000,    0.2000], 
 [    5.4000,    3.4000,    1.5000,    0.4000], 
 [    5.2000,    4.1000,    1.5000,    0.1000], 
 [    5.5000,    4.2000,    1.4000,    0.2000], 
 [    4.9000,    3.1000,    1.5000,    0.1000], 
 [    5.0000,    3.2000,    1.2000,    0.2000], 
 [    5.5000,    3.5000,    1.3000,    0.2000], 
 [    4.9000,    3.1000,    1.5000,    0.1000], 
 [    4.4000,    3.0000,    1.3000,    0.2000], 
 [    5.1000,    3.4000,    1.5000,    0.2000], 
 [    5.0000,    3.5000,    1.3000,    0.3000], 
 [    4.5000,    2.3000,    1.3000,    0.3000], 
 [    4.4000,    3.2000,    1.3000,    0.2000], 
 [    5.0000,    3.5000,    1.6000,    0.6000], 
 [    5.1000,    3.8000,    1.9000,    0.4000], 
 [    4.8000,    3.0000,    1.4000,    0.3000], 
 [    5.1000,    3.8000,    1.6000,    0.2000], 
 [    4.6000,    3.2000,    1.4000,    0.2000], 
 [    5.3000,    3.7000,    1.5000,    0.2000], 
 [    5.0000,    3.3000,    1.4000,    0.2000], 
 [    7.0000,    3.2000,    4.7000,    1.4000], 
 [    6.4000,    3.2000,    4.5000,    1.5000], 
 [    6.9000,    3.1000,    4.9000,    1.5000], 
 [    5.5000,    2.3000,    4.0000,    1.3000], 
 [    6.5000,    2.8000,    4.6000,    1.5000], 
 [    5.7000,    2.8000,    4.5000,    1.3000], 
 [    6.3000,    3.3000,    4.7000,    1.6000], 
 [    4.9000,    2.4000,    3.3000,    1.0000], 
 [    6.6000,    2.9000,    4.6000,    1.3000], 
 [    5.2000,    2.7000,    3.9000,    1.4000], 
 [    5.0000,    2.0000,    3.5000,    1.0000], 
 [    5.9000,    3.0000,    4.2000,    1.5000], 
 [    6.0000,    2.2000,    4.0000,    1.0000], 
 [    6.1000,    2.9000,    4.7000,    1.4000], 
 [    5.6000,    2.9000,    3.6000,    1.3000], 
 [    6.7000,    3.1000,    4.4000,    1.4000], 
 [    5.6000,    3.0000,    4.5000,    1.5000], 
 [    5.8000,    2.7000,    4.1000,    1.0000], 
 [    6.2000,    2.2000,    4.5000,    1.5000], 
 [    5.6000,    2.5000,    3.9000,    1.1000], 
 [    5.9000,    3.2000,    4.8000,    1.8000], 
 [    6.1000,    2.8000,    4.0000,    1.3000], 
 [    6.3000,    2.5000,    4.9000,    1.5000], 
 [    6.1000,    2.8000,    4.7000,    1.2000], 
 [    6.4000,    2.9000,    4.3000,    1.3000], 
 [    6.6000,    3.0000,    4.4000,    1.4000], 
 [    6.8000,    2.8000,    4.8000,    1.4000], 
 [    6.7000,    3.0000,    5.0000,    1.7000], 
 [    6.0000,    2.9000,    4.5000,    1.5000], 
 [    5.7000,    2.6000,    3.5000,    1.0000], 
 [    5.5000,    2.4000,    3.8000,    1.1000], 
 [    5.5000,    2.4000,    3.7000,    1.0000], 
 [    5.8000,    2.7000,    3.9000,    1.2000], 
 [    6.0000,    2.7000,    5.1000,    1.6000], 
 [    5.4000,    3.0000,    4.5000,    1.5000], 
 [    6.0000,    3.4000,    4.5000,    1.6000], 
 [    6.7000,    3.1000,    4.7000,    1.5000], 
 [    6.3000,    2.3000,    4.4000,    1.3000], 
 [    5.6000,    3.0000,    4.1000,    1.3000], 
 [    5.5000,    2.5000,    4.0000,    1.3000], 
 [    5.5000,    2.6000,    4.4000,    1.2000], 
 [    6.1000,    3.0000,    4.6000,    1.4000], 
 [    5.8000,    2.6000,    4.0000,    1.2000], 
 [    5.0000,    2.3000,    3.3000,    1.0000], 
 [    5.6000,    2.7000,    4.2000,    1.3000], 
 [    5.7000,    3.0000,    4.2000,    1.2000], 
 [    5.7000,    2.9000,    4.2000,    1.3000], 
 [    6.2000,    2.9000,    4.3000,    1.3000], 
 [    5.1000,    2.5000,    3.0000,    1.1000], 
 [    5.7000,    2.8000,    4.1000,    1.3000], 
 [    6.3000,    3.3000,    6.0000,    2.5000], 
 [    5.8000,    2.7000,    5.1000,    1.9000], 
 [    7.1000,    3.0000,    5.9000,    2.1000], 
 [    6.3000,    2.9000,    5.6000,    1.8000], 
 [    6.5000,    3.0000,    5.8000,    2.2000], 
 [    7.6000,    3.0000,    6.6000,    2.1000], 
 [    4.9000,    2.5000,    4.5000,    1.7000], 
 [    7.3000,    2.9000,    6.3000,    1.8000], 
 [    6.7000,    2.5000,    5.8000,    1.8000], 
 [    7.2000,    3.6000,    6.1000,    2.5000], 
 [    6.5000,    3.2000,    5.1000,    2.0000], 
 [    6.4000,    2.7000,    5.3000,    1.9000], 
 [    6.8000,    3.0000,    5.5000,    2.1000], 
 [    5.7000,    2.5000,    5.0000,    2.0000], 
 [    5.8000,    2.8000,    5.1000,    2.4000], 
 [    6.4000,    3.2000,    5.3000,    2.3000], 
 [    6.5000,    3.0000,    5.5000,    1.8000], 
 [    7.7000,    3.8000,    6.7000,    2.2000], 
 [    7.7000,    2.6000,    6.9000,    2.3000], 
 [    6.0000,    2.2000,    5.0000,    1.5000], 
 [    6.9000,    3.2000,    5.7000,    2.3000], 
 [    5.6000,    2.8000,    4.9000,    2.0000], 
 [    7.7000,    2.8000,    6.7000,    2.0000], 
 [    6.3000,    2.7000,    4.9000,    1.8000], 
 [    6.7000,    3.3000,    5.7000,    2.1000], 
 [    7.2000,    3.2000,    6.0000,    1.8000], 
 [    6.2000,    2.8000,    4.8000,    1.8000], 
 [    6.1000,    3.0000,    4.9000,    1.8000], 
 [    6.4000,    2.8000,    5.6000,    2.1000], 
 [    7.2000,    3.0000,    5.8000,    1.6000], 
 [    7.4000,    2.8000,    6.1000,    1.9000], 
 [    7.9000,    3.8000,    6.4000,    2.0000], 
 [    6.4000,    2.8000,    5.6000,    2.2000], 
 [    6.3000,    2.8000,    5.1000,    1.5000], 
 [    6.1000,    2.6000,    5.6000,    1.4000], 
 [    7.7000,    3.0000,    6.1000,    2.3000], 
 [    6.3000,    3.4000,    5.6000,    2.4000], 
 [    6.4000,    3.1000,    5.5000,    1.8000], 
 [    6.0000,    3.0000,    4.8000,    1.8000], 
 [    6.9000,    3.1000,    5.4000,    2.1000], 
 [    6.7000,    3.1000,    5.6000,    2.4000], 
 [    6.9000,    3.1000,    5.1000,    2.3000], 
 [    5.8000,    2.7000,    5.1000,    1.9000], 
 [    6.8000,    3.2000,    5.9000,    2.3000], 
 [    6.7000,    3.3000,    5.7000,    2.5000], 
 [    6.7000,    3.0000,    5.2000,    2.3000], 
 [    6.3000,    2.5000,    5.0000,    1.9000], 
 [    6.5000,    3.0000,    5.2000,    2.0000], 
 [    6.2000,    3.4000,    5.4000,    2.3000], 
 [    5.9000,    3.0000,    5.1000,    1.8000]]`
`=================OUTPUT==================`
`[[    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [    1.0000,         0,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,    1.0000,         0], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000], 
 [         0,         0,    1.0000]]`

after:

`===========INPUT===================`
`[[    5.5000,    4.2000,    1.4000,    0.2000], 
 [    6.0000,    3.0000,    4.8000,    1.8000], 
 [    7.6000,    3.0000,    6.6000,    2.1000], 
 [    6.9000,    3.1000,    4.9000,    1.5000], 
 [    6.3000,    2.7000,    4.9000,    1.8000], 
 [    6.7000,    3.1000,    5.6000,    2.4000], 
 [    7.7000,    3.0000,    6.1000,    2.3000], 
 [    5.8000,    2.7000,    5.1000,    1.9000], 
 [    5.8000,    2.7000,    5.1000,    1.9000], 
 [    7.7000,    2.6000,    6.9000,    2.3000], 
 [    6.2000,    2.9000,    4.3000,    1.3000], 
 [    5.1000,    3.8000,    1.9000,    0.4000], 
 [    5.7000,    2.8000,    4.1000,    1.3000], 
 [    5.6000,    3.0000,    4.1000,    1.3000], 
 [    4.7000,    3.2000,    1.6000,    0.2000], 
 [    6.8000,    3.0000,    5.5000,    2.1000], 
 [    5.0000,    3.5000,    1.6000,    0.6000], 
 [    5.8000,    2.6000,    4.0000,    1.2000], 
 [    4.9000,    3.1000,    1.5000,    0.1000], 
 [    4.9000,    3.1000,    1.5000,    0.1000], 
 [    7.2000,    3.6000,    6.1000,    2.5000], 
 [    5.2000,    4.1000,    1.5000,    0.1000], 
 [    5.7000,    2.5000,    5.0000,    2.0000], 
 [    5.6000,    2.9000,    3.6000,    1.3000], 
 [    6.1000,    3.0000,    4.6000,    1.4000], 
 [    4.9000,    2.5000,    4.5000,    1.7000], 
 [    5.0000,    3.3000,    1.4000,    0.2000], 
 [    6.8000,    2.8000,    4.8000,    1.4000], 
 [    6.4000,    3.2000,    5.3000,    2.3000], 
 [    5.8000,    4.0000,    1.2000,    0.2000], 
 [    6.4000,    2.7000,    5.3000,    1.9000], 
 [    6.5000,    3.2000,    5.1000,    2.0000], 
 [    5.1000,    3.7000,    1.5000,    0.4000], 
 [    5.1000,    3.5000,    1.4000,    0.2000], 
 [    5.1000,    3.8000,    1.5000,    0.3000], 
 [    5.5000,    2.4000,    3.8000,    1.1000], 
 [    4.8000,    3.0000,    1.4000,    0.3000], 
 [    5.7000,    3.8000,    1.7000,    0.3000], 
 [    5.8000,    2.7000,    4.1000,    1.0000], 
 [    6.4000,    2.8000,    5.6000,    2.2000], 
 [    6.8000,    3.2000,    5.9000,    2.3000], 
 [    6.0000,    2.2000,    4.0000,    1.0000], 
 [    6.1000,    2.8000,    4.0000,    1.3000], 
 [    5.4000,    3.9000,    1.3000,    0.4000], 
 [    4.8000,    3.4000,    1.6000,    0.2000], 
 [    5.5000,    3.5000,    1.3000,    0.2000], 
 [    5.6000,    2.5000,    3.9000,    1.1000], 
 [    5.9000,    3.2000,    4.8000,    1.8000], 
 [    5.5000,    2.5000,    4.0000,    1.3000], 
 [    5.0000,    3.4000,    1.6000,    0.4000], 
 [    5.6000,    2.8000,    4.9000,    2.0000], 
 [    7.7000,    2.8000,    6.7000,    2.0000], 
 [    4.6000,    3.1000,    1.5000,    0.2000], 
 [    5.6000,    3.0000,    4.5000,    1.5000], 
 [    6.3000,    2.3000,    4.4000,    1.3000], 
 [    6.7000,    3.1000,    4.7000,    1.5000], 
 [    7.7000,    3.8000,    6.7000,    2.2000], 
 [    6.5000,    3.0000,    5.8000,    2.2000], 
 [    6.6000,    3.0000,    4.4000,    1.4000], 
 [    6.3000,    3.4000,    5.6000,    2.4000], 
 [    5.7000,    2.6000,    3.5000,    1.0000], 
 [    7.4000,    2.8000,    6.1000,    1.9000], 
 [    4.5000,    2.3000,    1.3000,    0.3000], 
 [    7.1000,    3.0000,    5.9000,    2.1000], 
 [    5.1000,    3.3000,    1.7000,    0.5000], 
 [    6.3000,    2.5000,    5.0000,    1.9000], 
 [    5.5000,    2.3000,    4.0000,    1.3000], 
 [    4.4000,    3.0000,    1.3000,    0.2000], 
 [    6.1000,    2.8000,    4.7000,    1.2000], 
 [    5.1000,    3.8000,    1.6000,    0.2000], 
 [    4.6000,    3.2000,    1.4000,    0.2000], 
 [    4.4000,    3.2000,    1.3000,    0.2000], 
 [    5.0000,    2.3000,    3.3000,    1.0000], 
 [    6.2000,    2.2000,    4.5000,    1.5000], 
 [    6.5000,    3.0000,    5.2000,    2.0000], 
 [    6.6000,    2.9000,    4.6000,    1.3000], 
 [    5.2000,    3.5000,    1.5000,    0.2000], 
 [    5.1000,    2.5000,    3.0000,    1.1000], 
 [    6.4000,    3.1000,    5.5000,    1.8000], 
 [    5.0000,    2.0000,    3.5000,    1.0000], 
 [    5.0000,    3.2000,    1.2000,    0.2000], 
 [    6.7000,    3.3000,    5.7000,    2.5000], 
 [    6.7000,    3.0000,    5.2000,    2.3000], 
 [    6.2000,    3.4000,    5.4000,    2.3000], 
 [    5.7000,    3.0000,    4.2000,    1.2000], 
 [    6.5000,    3.0000,    5.5000,    1.8000], 
 [    5.7000,    2.8000,    4.5000,    1.3000], 
 [    6.5000,    2.8000,    4.6000,    1.5000], 
 [    4.3000,    3.0000,    1.1000,    0.1000], 
 [    5.3000,    3.7000,    1.5000,    0.2000], 
 [    6.0000,    2.2000,    5.0000,    1.5000], 
 [    4.8000,    3.4000,    1.9000,    0.2000], 
 [    5.1000,    3.5000,    1.4000,    0.3000], 
 [    6.3000,    2.5000,    4.9000,    1.5000], 
 [    7.9000,    3.8000,    6.4000,    2.0000], 
 [    5.4000,    3.0000,    4.5000,    1.5000], 
 [    6.9000,    3.1000,    5.1000,    2.3000], 
 [    5.4000,    3.7000,    1.5000,    0.2000], 
 [    6.7000,    3.0000,    5.0000,    1.7000], 
 [    4.8000,    3.0000,    1.4000,    0.1000], 
 [    7.3000,    2.9000,    6.3000,    1.8000], 
 [    4.4000,    2.9000,    1.4000,    0.2000], 
 [    6.1000,    2.9000,    4.7000,    1.4000], 
 [    6.7000,    2.5000,    5.8000,    1.8000], 
 [    4.9000,    2.4000,    3.3000,    1.0000], 
 [    4.7000,    3.2000,    1.3000,    0.2000], 
 [    5.0000,    3.0000,    1.6000,    0.2000], 
 [    6.3000,    3.3000,    6.0000,    2.5000], 
 [    6.3000,    2.9000,    5.6000,    1.8000], 
 [    5.4000,    3.4000,    1.7000,    0.2000], 
 [    5.4000,    3.4000,    1.5000,    0.4000], 
 [    4.8000,    3.1000,    1.6000,    0.2000], 
 [    5.7000,    4.4000,    1.5000,    0.4000], 
 [    4.6000,    3.6000,    1.0000,    0.2000], 
 [    7.2000,    3.2000,    6.0000,    1.8000], 
 [    5.2000,    3.4000,    1.4000,    0.2000], 
 [    6.0000,    3.4000,    4.5000,    1.6000], 
 [    6.3000,    3.3000,    4.7000,    1.6000], 
 [    4.9000,    3.1000,    1.5000,    0.1000], 
 [    5.5000,    2.6000,    4.4000,    1.2000], 
 [    7.2000,    3.0000,    5.8000,    1.6000], 
 [    7.0000,    3.2000,    4.7000,    1.4000], 
 [    6.4000,    3.2000,    4.5000,    1.5000], 
 [    5.0000,    3.6000,    1.4000,    0.2000], 
 [    6.9000,    3.1000,    5.4000,    2.1000], 
 [    5.8000,    2.8000,    5.1000,    2.4000], 
 [    6.1000,    3.0000,    4.9000,    1.8000], 
 [    6.2000,    2.8000,    4.8000,    1.8000], 
 [    5.9000,    3.0000,    5.1000,    1.8000], 
 [    6.9000,    3.2000,    5.7000,    2.3000], 
 [    5.9000,    3.0000,    4.2000,    1.5000], 
 [    5.6000,    2.7000,    4.2000,    1.3000], 
 [    5.1000,    3.4000,    1.5000,    0.2000], 
 [    6.1000,    2.6000,    5.6000,    1.4000], 
 [    6.3000,    2.8000,    5.1000,    1.5000], 
 [    4.6000,    3.4000,    1.4000,    0.3000], 
 [    5.2000,    2.7000,    3.9000,    1.4000], 
 [    6.0000,    2.9000,    4.5000,    1.5000], 
 [    4.9000,    3.0000,    1.4000,    0.2000], 
 [    6.7000,    3.3000,    5.7000,    2.1000], 
 [    5.4000,    3.9000,    1.7000,    0.4000], 
 [    5.7000,    2.9000,    4.2000,    1.3000], 
 [    5.0000,    3.4000,    1.5000,    0.2000], 
 [    5.0000,    3.5000,    1.3000,    0.3000], 
 [    5.5000,    2.4000,    3.7000,    1.0000], 
 [    5.8000,    2.7000,    3.9000,    1.2000], 
 [    6.7000,    3.1000,    4.4000,    1.4000], 
 [    6.4000,    2.9000,    4.3000,    1.3000], 
 [    6.0000,    2.7000,    5.1000,    1.6000], 
 [    6.4000,    2.8000,    5.6000,    2.1000]]`
`=================OUTPUT==================`
`[[         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0], 
 [         0,         0,         0]]`

**Comment by agibsonccc** [comment]
@jahan-afrouz that appears to be a bug with the gpu backend specifically. The best thing I can tell you is shuffle with the cpu backend (all you do is include a different backend) then load it with the gpu backend pre saved.

See: https://deeplearning4j.konduit.ai/config/backends


 That should work as a work around for now. Datasets have a save and load method you can use.
Also, you can look at using Nd4j.shuffle directly:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/ShufflesTests.java

Let me know if you have any similar issues.

**Comment by rossmessing** [comment]
For what it's worth, randomization is generally not a great GPU-side operation - tends to slow things down a bunch, and historically had implementation issues.

**Comment by agibsonccc** [comment]
@rossmessing  yes agreed. That's why I just suggested for now to do it on cpu. I would always save compute for gpu anyways. You can presaved the shuffled datasets then load them on cpu for faster training/loading.

**Comment by quickwritereader** [comment]
#9472
