### ISSUE TITLE
Keras import issue: Maximum Merge Layer Unsupported

### ISSUE THREAD

**Issue by rossmessing** [deeplearning4j/deeplearning4j#9143]
#### Issue Description

Tried to import an otherwise-importable keras model with a Maximum layer.

Got error `InvocationTargetException: Unsupported keras layer type Maximum`.  

While Maximum is clearly listed as supported [here](https://deeplearning4j.konduit.ai/keras-import/supported-features), it actually seems to be missing from the set of supported layers [here](https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/utils/KerasLayerUtils.java#L269-L282)

Other layers also appear unsupported (in particular, Minimum doesn't even appear to be supported in the places where Maximum is, like the [merge](https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/layers/core/KerasMerge.java) source or supported layer [constants](https://github.com/eclipse/deeplearning4j/blob/95ca39bd2185e005671889e3a2114a30dc4c0281/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/config/KerasLayerConfiguration.java#L30)

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 1.0.0 beta 6 (but looking at the source it's still clearly present in beta7)
* Platform information (OS, etc) Running on macos and linux

#### Additional Information

I'm not in a good position to provide a minimal example, but since Maximum clearly isn't in the list of supported layers, just adding a Maximum layer to any keras model should render it un-importable.

**Comment by agibsonccc** [comment]
@rossmessing  Do you have a model I could use for this? A test case would help a lot. Thanks!

**Comment by rossmessing** [comment]
The following keras code produces `MaximumUnsupported.h5`:
```
from tensorflow.keras.layers import Input, Maximum, Multiply
from tensorflow.keras.models import Model

input_layer = Input(shape=(1))
squared_layer = Multiply()([input_layer, input_layer])
output_layer = Maximum()([input_layer, squared_layer])
keras_model = Model(inputs=[input_layer], outputs=[output_layer])
keras_model.save(filepath="MaximumUnsupported.h5", overwrite=True)
```

Loading it in DL4J with 
```
org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights
```
yields:
```
Caused by: org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type Maximum. Please file an issue at https://github.com/eclipse/deeplearning4j/issues.
```

**Comment by rossmessing** [comment]
If it's useful, here's a zip of the serialized network, so you can test this without keras.
[MaximumUnsupported.h5.zip](https://github.com/eclipse/deeplearning4j/files/5832926/MaximumUnsupported.h5.zip)

**Comment by rossmessing** [comment]
Note that this issue does not apply to any other merge layer in the supported list.  If you replace the Maximum in my example with another supported merge layer, it works fine.

**Comment by rossmessing** [comment]
Wrote up a super brief PR that *might* fix the issue.  I can't really test it (can't build stuff from source).
