### ISSUE TITLE
Loaded SameDiff model can't do evaluation

### ISSUE THREAD

**Issue by SidneyLann** [deeplearning4j/deeplearning4j#9147]
#### Issue Description

Please describe our issue, along with:
- expected behavior
show evaluation stats when load SameDiff model but not trainning like below logic:
     sameDiff = CheckpointListener.loadCheckpoint(new File(modelFolder), i, true);
      EvaluationRecord evaluationRecord = sameDiff.evaluate().data(testDataIter).evaluate("out", 0, new Evaluation()).exec();
      System.out.println(evaluationRecord.evaluation("out").stats());

- encountered behavior
Error at [D:/jenkins/ws/dl4j-deeplearning4j-1.0.0-beta7-windows-x86_64-cpu/libnd4j/include/ops/declarable/generic/nn/recurrent/lstmLayer.cpp:188:0]:
LSTM_LAYER operation: wrong shape of input weights, expected is [128, 24], but got [768, 24] instead !
ERROR org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner - Failed to execute op lstmLayer. Attempted to execute with 5 inputs, 3 outputs, 1 targs,8 bargs and 5 iargs. Inputs: [(FLOAT,[8,768,128],c), (FLOAT,[768,24],c), (FLOAT,[6,24],c), (FLOAT,[24],c), (FLOAT,[18],c)]. Outputs: [(FLOAT,[8,768,6],c), (FLOAT,[8,6],c), (FLOAT,[8,6],c)]. tArgs: [0.0]. iArgs: [1, 0, 2, 0, 0]. bArgs: [true, false, false, false, true, true, true, true]. Input var names: [in, weights, rWeights, bias, inputPeepholeWeights]. Output var names: [lstm1, lstm2, lstm3] - Please see above message (printed out from c++) for a possible cause of error.
java.lang.RuntimeException: Op validation failed
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1924)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6575)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.doExec(InferenceSession.java:495)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getOutputs(InferenceSession.java:222)
	at org.nd4j.autodiff.samediff.internal.InferenceSession.getOutputs(InferenceSession.java:68)
	at org.nd4j.autodiff.samediff.internal.AbstractSession.output(AbstractSession.java:391)
	at org.nd4j.autodiff.samediff.SameDiff.directExecHelper(SameDiff.java:2579)
	at org.nd4j.autodiff.samediff.SameDiff.evaluateHelper(SameDiff.java:2163)
	at org.nd4j.autodiff.samediff.SameDiff.evaluate(SameDiff.java:2073)
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: beta7
* Platform information (OS, etc): win7
* CUDA version, if used: No
* NVIDIA driver version, if in used: No

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)
Evaluation stats can be shown when training in below logic:
      for (int i = 0; i < nEpochs; i++) {
        sameDiff.fit().train(trainDataIter, nEpochs).validate(validDataIter, evalFrequency).exec();
        trainDataIter.reset();
        if (i % 10 == 0) {
          EvaluationRecord evaluationRecord = sameDiff.evaluate().data(validDataIter).evaluate("out", 0, new Evaluation()).exec();
          System.out.println(evaluationRecord.evaluation("out").stats());
          validDataIter.reset();
        }
      }
#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by SidneyLann** [comment]
Evaluation stats can be shown when trainning. but can't show when only loading model but not trainning.

**Comment by agibsonccc** [comment]
It's been quite a while. A lot's happened to the training code since this was raised. Closing.
