### ISSUE TITLE
Doc issue: Update quickstart guide

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#915]
http://deeplearning4j.org/quickstart.html

"This Quick Start guide assumes that you have the following already installed: Java 7" -> maybe better to say "Java 7 or later"

"For an easier install, Windows users should replace nd4j-x86 with nd4j-java in the dependencies. Additional Windows instructions are available here." -> nd4j-java has been deprecated/removed in latest version

"Please do not use the SNAPSHOT examples." -> snapshot examples are no longer available (private repo now)

"The nd4j-java backend will look something like this:..." -> remove nd4j-java section

**Comment by chrisvnicholson** [comment]
fixed. thanks alex.
