### ISSUE TITLE
org.deeplearning4j.ui.port property have no effect

### ISSUE THREAD

**Issue by lopezmt** [deeplearning4j/deeplearning4j#9150]
#### Issue Description

I am trying to use deeplearning4j-ui to check my model architecture but I have a service on my PC already listening to the port 9000. When I set the system property org.deeplearning4j.ui.port to 9001, I get an error telling me that the server failed to listen to the port 9000:

java.lang.RuntimeException: Deeplearning4j UI server failed to listen on port 9000

I tried printing the system property before launching the server using:
System.out.println("Port : "+System.getProperty("org.deeplearning4j.ui.port"));

And I get 9001 as expected.

I don't know for sure that port 9001 is available on my machine and can't check that easily as I don't have admin rights but the error should at least tell me that he failed to listen to port 9001.

#### Version Information

* Deeplearning4j version : 1.0.0-beta7
* Platform information Windows 10

**Comment by lopezmt** [comment]
By looking at the code a little bit, I noticed in VertxUIServer class that a System.getenv command is used to get the port. Is this expected? 
If it is, the documentation should be updated to inform that an environment variable should be used, if not, System.getProperty should be used instead of System.getenv

**Comment by SidneyLann** [comment]
String port = System.getProperty("port"); 
VertxUIServer uiServer = VertxUIServer.getInstance(Integer.valueOf(port), false, null);
uiServer.start();

**Comment by ShamsUlAzeem** [comment]
Issue is being fixed here: https://github.com/eclipse/deeplearning4j/pull/9162
