### ISSUE TITLE
InvalidKerasConfigurationException: Expected model class name Model (found Functional)

### ISSUE THREAD

**Issue by ghost** [deeplearning4j/deeplearning4j#9151]
I'm training my keras (functional) model in python. Now I want to deploy this in java using deeplearning4j. Unfortunately it doesn't work because deeplearning4j doesn't know the Functional Class. I get this error: 

org.deeplearning4j.nn.modelimport.keras.exceptions.InvalidKerasConfigurationException: Expected model class name Model (found Functional).

So somehow he's expecting class_name: "Model" in stead of class_name: "Functional", i guess? But im finding no way to to either save my model with class_name: "Model" or letting deeplearning4j accept a "Functional" class. Anyone knows a solution for this problem? Thanks in advance for taking a look!

* Deeplearning4j version: 1.0.0-beta7

This is the model I'm trying to save:

# Model
```
strategy = tf.distribute.MirroredStrategy()
print('Number of devices: {}'.format(strategy.num_replicas_in_sync))
```

```
class lstm_bottleneck(tf.keras.layers.Layer):
    def __init__(self, lstm_units, time_steps, **kwargs):
        self.lstm_units = lstm_units
        self.time_steps = time_steps
        self.lstm_layer = Bidirectional(LSTM(lstm_units, return_sequences=False))
        self.repeat_layer = RepeatVector(time_steps)
        super(lstm_bottleneck, self).__init__(**kwargs)
    
    def call(self, inputs):
        # just call the two initialized layers
        return self.repeat_layer(self.lstm_layer(inputs))
    
    def compute_mask(self, inputs, mask=None):
        # return the input_mask directly
        return mask

    def get_config(self):
        cfg = super().get_config()
        return cfg
```
```
with strategy.scope():
    
  inp1 = Input(shape=(timesteps, 7), name="inp1")
  mask1 = Masking(mask_value=-1.)(inp1)

  enc = Bidirectional(LSTM(55, activation = 'tanh', return_sequences = True, dropout = 0.1, kernel_regularizer=l2(0.01)))(mask1)
  enc = Dropout(0.2)(enc)
  enc = Bidirectional(LSTM(50, activation = 'tanh', return_sequences = True, kernel_regularizer=l2(0.01)))(enc)
  enc = Dropout(0.1)(enc)

  enc = Bidirectional(LSTM(45, return_sequences=False))(enc)
  decode = RepeatVector(timesteps)(enc)

  #decode = lstm_bottleneck(lstm_units=45, time_steps=timesteps)(enc)

  decode = Bidirectional(LSTM(50, activation = 'tanh', return_sequences = True, kernel_regularizer=l2(0.01)))(decode)
  decode = Dropout(0.2)(decode)
  decode = Bidirectional(LSTM(55, activation = 'tanh', return_sequences = True, kernel_regularizer=l2(0.01)))(decode)
  decode = TimeDistributed(Dense(6, activation="softmax"), name="dec1")(decode)
      
  new_model = Model(inputs=inp1, outputs = decode)
  new_model.compile(loss= 'categorical_crossentropy', optimizer= tf.keras.optimizers.Adam(lr=0.0005), metrics=['categorical_accuracy'])
  plot_model(new_model, to_file='model.png')
  new_model.summary()
```

**Comment by treo** [comment]
Have you tried reading the documentation?
https://deeplearning4j.konduit.ai/keras-import/model-functional#getting-started-with-importing-keras-functional-models

**Comment by ghost** [comment]
@treo Yes i did. This is how i save the model (just like in the documentation):
```
model.save('test.h5')
```
This is the code in Java:
```
String fullModel = new ClassPathResource("test.h5").getFile().getPath();
ComputationGraph thisModel = KerasModelImport.importKerasModelAndWeights(fullModel);
```
Anything I'm doing wrong?

**Comment by ghost** [comment]
@treo is there a change you were able to give it a look?

**Comment by treo** [comment]
What version of Keras are you using? I wonder whether they've changed file formats again.

**Comment by ghost** [comment]
Keras version 2.4.3

**Comment by ghost** [comment]
@treo I also thought it might be something like that! To which version should I downgrade to?

**Comment by ghost** [comment]
@treo in the beginning of the h5-file there is like this "tensorflow{"class_name": "Functional"" line, and i suppose D4J has problems with that?

**Comment by ghost** [comment]
Problem was solved with downgrading tensorflow!

**Comment by treo** [comment]
@agibsonccc Tagging you so you're aware of this for your model import re-work.

**Comment by hessam94** [comment]
i have same problem which version to downgrade the tensorflow??? better solution please

**Comment by DimasDMM** [comment]
I have the same problem. I suppose that this issue should be fixed.

**Comment by agibsonccc** [comment]
@DimasDMM  if you have a specific model, I would be happy to take a look at it. I'm a bit backlogged, but will be ready to take a look at models soon for the release.

**Comment by DimasDMM** [comment]
@agibsonccc Actually it is not about a specific model. The problem is that I cannot load the model with DeepLearning4Java if I train&save the model with TensorFlow v2.4.0. However, if I downgrade the version to v2.2.0, then I can load and evaluate it without any problem.

I am not sure if there are more differences, but I can see that the people of Tensorflow changed `class_name=Model` to `class_name=Functional`, so DeepLearning4Java fails to load the model when it is not sequential.

For example, a very simple model (input, hidden layer, and output layer):
```python
from tensorflow import keras

x_input = keras.layers.Input(shape=(X_train.shape[-1],))
x = x_input
x = keras.layers.Dense(512, activation='relu')(x)
x = keras.layers.Dropout(0.2)(x)
x = keras.layers.Dense(1, activation='sigmoid')(x)

model = keras.Model(inputs=x_input, outputs=x)
model.compile(optimizer=keras.optimizers.Adam(1e-2), loss='binary_crossentropy')

# And save it
model.save('mymodel.h5')
```

I leave the links to download the sample model using different Tensorflow versions:
- v2.4.1: https://drive.google.com/file/d/1uwTBjjRcdVMPSAd2HKHRIpCgQuj7GEoo/view?usp=sharing
- v2.2.0: https://drive.google.com/file/d/1CdWsv_SfRQe2l3pMuYn-o2wIc61_3ngK/view?usp=sharing
