### ISSUE TITLE
Maven cannot resolve dependency "org.bytedeco:hdf5:1.12.0-1.5.3" for "DL4J-Core 1.0.0-beta7"

### ISSUE THREAD

**Issue by mikemikezhu** [deeplearning4j/deeplearning4j#9157]
### Issue Description

**GIVEN** using Maven to install DL4J-Core dependency in the Spring Boot application
**WHEN** synchronizing Maven dependencies
**THEN** we have the issue that "Cannot resolve org.bytedeco:hdf5:1.12.0-1.5.3"

**Expected behaviour:** DL4J-Core shall be installed successfully

### Version Information

* Java version: `1.8`
* Deeplearning4j version: `deeplearning4j-core 1.0.0-beta7`
* Maven version: `3.6.3`

### Investigation

(1) In `pom.xml` we defined DL4J-Core 1.0.0-beta7:
```xml
<dependency>
    <groupId>org.deeplearning4j</groupId>
    <artifactId>deeplearning4j-core</artifactId>
    <version>1.0.0-beta7</version>
</dependency>
```
(2) When synchronizing Maven dependencies, we found out Maven could not resolve dependency `deeplearning4j-modelimport 1.0.0-beta7`
<img width="564" alt="Screen Shot 2021-01-20 at 3 41 08 PM" src="https://user-images.githubusercontent.com/7867571/105142806-f95dcb00-5b35-11eb-9c89-ad2c42b9a5f5.png">

(3) Then inside `deeplearning4j-modelimport 1.0.0-beta7`, Maven could not resolve dependency `org.bytedeco:hdf5:1.12.0-1.5.3`
<img width="501" alt="Screen Shot 2021-01-20 at 3 51 45 PM" src="https://user-images.githubusercontent.com/7867571/105143969-89e8db00-5b37-11eb-96b1-ffa6e1f83f29.png">

(4) The issue seems to be caused by `hdf5-platform 1.12.0-1.5.3` dependency, which cannot resolve dependency `linux-ppc64le:1.12.0-1.5.3`

(5) However, if we import the latest version of `hdf5-platform` **1.12.0-1.5.4** before importing `DL4J-Core`, then the issue is gone, because Maven will recognize the duplicate dependency and `hdf5-platform` **1.12.0-1.5.4** will replace the buggy one. Therefore, we could tell after upgrading `hdf5-platform` to the latest version **1.12.0-1.5.4** in `deeplearning4j-modelimport 1.0.0-beta7`, then we could resolve the dependency successfully

```xml
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>hdf5-platform</artifactId>
    <version>1.12.0-1.5.4</version> // ------------> This latest version will replace the buggy one
</dependency>
<dependency>
    <groupId>org.deeplearning4j</groupId>
    <artifactId>deeplearning4j-core</artifactId>
    <version>1.0.0-beta7</version>
</dependency>
```

<img width="659" alt="Screen Shot 2021-01-20 at 4 30 26 PM" src="https://user-images.githubusercontent.com/7867571/105148025-dd115c80-5b3c-11eb-9238-f767a24766ef.png">

### Contribution
I would like to help to further investigate and upgrade the `hdf5-platform` version if necessary

**Comment by agibsonccc** [comment]
@mikemikezhu don't worry about this, this is missing a platform specific classifier that you probably aren't using (IBM power pc)  - I'm closing this.
