### ISSUE TITLE
Manually building libnd4j compiles OK but links error

### ISSUE THREAD

**Issue by terU3760** [deeplearning4j/deeplearning4j#9158]
#### Issue Description

Please describe our issue, along with:
- Sucessfully build libnd4j.dll
- Compiles OK but links error

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - current newest version
* Platform information (OS, etc) - Windows 10
* CUDA version, -  CUDA Driver Version / Runtime Version - 11.1 / 10.2

#### Additional Information

run the command in Msys2 Mingw64:

 ./buildnativeoperations.sh clean true

Error output:

......
......
[100%] Linking CXX shared library libnd4jcpu.dll
cd /F/libnd4j/blasbuild/cpu/blas && /D/msys64/mingw64/bin/cmake.exe -E rm -f CMakeFiles/nd4jcpu.dir/objects.a
cd /F/libnd4j/blasbuild/cpu/blas && /D/msys64/mingw64/bin/ar.exe cr CMakeFiles/nd4jcpu.dir/objects.a @CMakeFiles/nd4jcpu.dir/objects1.rsp
cd /F/libnd4j/blasbuild/cpu/blas && /D/msys64/mingw64/bin/g++.exe  -D_RELEASE=true -Wl,-rpath,RIGIN/ -DLIBND4J_ALL_OPS=true -march=x86-64 -mtune=x86-64 -fPIC -fopenmp -static  -O3 -std=c++11 -fassociative-math -funsafe-math-optimizations -shared -o libnd4jcpu.dll -Wl,--out-implib,libnd4jcpu.dll.a -Wl,--major-image-version,0,--minor-image-version,0 -Wl,--whole-archive CMakeFiles/nd4jcpu.dir/objects.a -Wl,--no-whole-archive  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZN4nd4j7NDArrayIfE22varianceAlongDimensionIN7simdOps20SummaryStatsVarianceIfEEEEvPKS1_bRKSt16initializer_listIiE[_ZN4nd4j7NDArrayIfE22varianceAlongDimensionIN7simdOps20SummaryStatsVarianceIfEEEEvPKS1_bRKSt16initializer_listIiE]+0x10f): undefined reference to `float functions::summarystats::SummaryStatsReduce<float>::execScalar<simdOps::SummaryStatsVariance<float> >(bool, float*, long long*, float*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZN4nd4j7NDArrayIfE22varianceAlongDimensionIN7simdOps29SummaryStatsStandardDeviationIfEEEEvPKS1_bRKSt16initializer_listIiE[_ZN4nd4j7NDArrayIfE22varianceAlongDimensionIN7simdOps29SummaryStatsStandardDeviationIfEEEEvPKS1_bRKSt16initializer_listIiE]+0x10f): undefined reference to `float functions::summarystats::SummaryStatsReduce<float>::execScalar<simdOps::SummaryStatsStandardDeviation<float> >(bool, float*, long long*, float*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZN4nd4j7NDArrayI7float16E22varianceAlongDimensionIN7simdOps20SummaryStatsVarianceIS1_EEEEvPKS2_bRKSt16initializer_listIiE[_ZN4nd4j7NDArrayI7float16E22varianceAlongDimensionIN7simdOps20SummaryStatsVarianceIS1_EEEEvPKS2_bRKSt16initializer_listIiE]+0x10f): undefined reference to `float16 functions::summarystats::SummaryStatsReduce<float16>::execScalar<simdOps::SummaryStatsVariance<float16> >(bool, float16*, long long*, float16*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZN4nd4j7NDArrayI7float16E22varianceAlongDimensionIN7simdOps29SummaryStatsStandardDeviationIS1_EEEEvPKS2_bRKSt16initializer_listIiE[_ZN4nd4j7NDArrayI7float16E22varianceAlongDimensionIN7simdOps29SummaryStatsStandardDeviationIS1_EEEEvPKS2_bRKSt16initializer_listIiE]+0x10f): undefined reference to `float16 functions::summarystats::SummaryStatsReduce<float16>::execScalar<simdOps::SummaryStatsStandardDeviation<float16> >(bool, float16*, long long*, float16*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZN4nd4j7NDArrayIdE22varianceAlongDimensionIN7simdOps20SummaryStatsVarianceIdEEEEvPKS1_bRKSt16initializer_listIiE[_ZN4nd4j7NDArrayIdE22varianceAlongDimensionIN7simdOps20SummaryStatsVarianceIdEEEEvPKS1_bRKSt16initializer_listIiE]+0x10f): undefined reference to `double functions::summarystats::SummaryStatsReduce<double>::execScalar<simdOps::SummaryStatsVariance<double> >(bool, double*, long long*, double*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZN4nd4j7NDArrayIdE22varianceAlongDimensionIN7simdOps29SummaryStatsStandardDeviationIdEEEEvPKS1_bRKSt16initializer_listIiE[_ZN4nd4j7NDArrayIdE22varianceAlongDimensionIN7simdOps29SummaryStatsStandardDeviationIdEEEEvPKS1_bRKSt16initializer_listIiE]+0x10f): undefined reference to `double functions::summarystats::SummaryStatsReduce<double>::execScalar<simdOps::SummaryStatsStandardDeviation<double> >(bool, double*, long long*, double*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZN4nd4j7NDArrayIfE22varianceAlongDimensionIN7simdOps20SummaryStatsVarianceIfEEEEvPKS1_bRKSt6vectorIiSaIiEE[_ZN4nd4j7NDArrayIfE22varianceAlongDimensionIN7simdOps20SummaryStatsVarianceIfEEEEvPKS1_bRKSt6vectorIiSaIiEE]+0xec): undefined reference to `float functions::summarystats::SummaryStatsReduce<float>::execScalar<simdOps::SummaryStatsVariance<float> >(bool, float*, long long*, float*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZN4nd4j7NDArrayIfE22varianceAlongDimensionIN7simdOps29SummaryStatsStandardDeviationIfEEEEvPKS1_bRKSt6vectorIiSaIiEE[_ZN4nd4j7NDArrayIfE22varianceAlongDimensionIN7simdOps29SummaryStatsStandardDeviationIfEEEEvPKS1_bRKSt6vectorIiSaIiEE]+0xec): undefined reference to `float functions::summarystats::SummaryStatsReduce<float>::execScalar<simdOps::SummaryStatsStandardDeviation<float> >(bool, float*, long long*, float*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZN4nd4j7NDArrayI7float16E22varianceAlongDimensionIN7simdOps20SummaryStatsVarianceIS1_EEEEvPKS2_bRKSt6vectorIiSaIiEE[_ZN4nd4j7NDArrayI7float16E22varianceAlongDimensionIN7simdOps20SummaryStatsVarianceIS1_EEEEvPKS2_bRKSt6vectorIiSaIiEE]+0xec): undefined reference to `float16 functions::summarystats::SummaryStatsReduce<float16>::execScalar<simdOps::SummaryStatsVariance<float16> >(bool, float16*, long long*, float16*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZN4nd4j7NDArrayI7float16E22varianceAlongDimensionIN7simdOps29SummaryStatsStandardDeviationIS1_EEEEvPKS2_bRKSt6vectorIiSaIiEE[_ZN4nd4j7NDArrayI7float16E22varianceAlongDimensionIN7simdOps29SummaryStatsStandardDeviationIS1_EEEEvPKS2_bRKSt6vectorIiSaIiEE]+0xec): undefined reference to `float16 functions::summarystats::SummaryStatsReduce<float16>::execScalar<simdOps::SummaryStatsStandardDeviation<float16> >(bool, float16*, long long*, float16*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZN4nd4j7NDArrayIdE22varianceAlongDimensionIN7simdOps20SummaryStatsVarianceIdEEEEvPKS1_bRKSt6vectorIiSaIiEE[_ZN4nd4j7NDArrayIdE22varianceAlongDimensionIN7simdOps20SummaryStatsVarianceIdEEEEvPKS1_bRKSt6vectorIiSaIiEE]+0xec): undefined reference to `double functions::summarystats::SummaryStatsReduce<double>::execScalar<simdOps::SummaryStatsVariance<double> >(bool, double*, long long*, double*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZN4nd4j7NDArrayIdE22varianceAlongDimensionIN7simdOps29SummaryStatsStandardDeviationIdEEEEvPKS1_bRKSt6vectorIiSaIiEE[_ZN4nd4j7NDArrayIdE22varianceAlongDimensionIN7simdOps29SummaryStatsStandardDeviationIdEEEEvPKS1_bRKSt6vectorIiSaIiEE]+0xec): undefined reference to `double functions::summarystats::SummaryStatsReduce<double>::execScalar<simdOps::SummaryStatsStandardDeviation<double> >(bool, double*, long long*, double*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZN4nd4j7NDArrayIfE14varianceNumberIN7simdOps20SummaryStatsVarianceIfEEEEfb[_ZN4nd4j7NDArrayIfE14varianceNumberIN7simdOps20SummaryStatsVarianceIfEEEEfb]+0x16): undefined reference to `float functions::summarystats::SummaryStatsReduce<float>::execScalar<simdOps::SummaryStatsVariance<float> >(bool, float*, long long*, float*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZN4nd4j7NDArrayIfE14varianceNumberIN7simdOps29SummaryStatsStandardDeviationIfEEEEfb[_ZN4nd4j7NDArrayIfE14varianceNumberIN7simdOps29SummaryStatsStandardDeviationIfEEEEfb]+0x16): undefined reference to `float functions::summarystats::SummaryStatsReduce<float>::execScalar<simdOps::SummaryStatsStandardDeviation<float> >(bool, float*, long long*, float*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZN4nd4j7NDArrayI7float16E14varianceNumberIN7simdOps20SummaryStatsVarianceIS1_EEEES1_b[_ZN4nd4j7NDArrayI7float16E14varianceNumberIN7simdOps20SummaryStatsVarianceIS1_EEEES1_b]+0x16): undefined reference to `float16 functions::summarystats::SummaryStatsReduce<float16>::execScalar<simdOps::SummaryStatsVariance<float16> >(bool, float16*, long long*, float16*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZN4nd4j7NDArrayI7float16E14varianceNumberIN7simdOps29SummaryStatsStandardDeviationIS1_EEEES1_b[_ZN4nd4j7NDArrayI7float16E14varianceNumberIN7simdOps29SummaryStatsStandardDeviationIS1_EEEES1_b]+0x16): undefined reference to `float16 functions::summarystats::SummaryStatsReduce<float16>::execScalar<simdOps::SummaryStatsStandardDeviation<float16> >(bool, float16*, long long*, float16*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZN4nd4j7NDArrayIdE14varianceNumberIN7simdOps20SummaryStatsVarianceIdEEEEdb[_ZN4nd4j7NDArrayIdE14varianceNumberIN7simdOps20SummaryStatsVarianceIdEEEEdb]+0x16): undefined reference to `double functions::summarystats::SummaryStatsReduce<double>::execScalar<simdOps::SummaryStatsVariance<double> >(bool, double*, long long*, double*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZN4nd4j7NDArrayIdE14varianceNumberIN7simdOps29SummaryStatsStandardDeviationIdEEEEdb[_ZN4nd4j7NDArrayIdE14varianceNumberIN7simdOps29SummaryStatsStandardDeviationIdEEEEdb]+0x16): undefined reference to `double functions::summarystats::SummaryStatsReduce<double>::execScalar<simdOps::SummaryStatsStandardDeviation<double> >(bool, double*, long long*, double*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZNK4nd4j7NDArrayIfE22varianceAlongDimensionIN7simdOps20SummaryStatsVarianceIfEEEEPS1_bRKSt6vectorIiSaIiEE[_ZNK4nd4j7NDArrayIfE22varianceAlongDimensionIN7simdOps20SummaryStatsVarianceIfEEEEPS1_bRKSt6vectorIiSaIiEE]+0x16f): undefined reference to `float functions::summarystats::SummaryStatsReduce<float>::execScalar<simdOps::SummaryStatsVariance<float> >(bool, float*, long long*, float*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZNK4nd4j7NDArrayIfE22varianceAlongDimensionIN7simdOps29SummaryStatsStandardDeviationIfEEEEPS1_bRKSt6vectorIiSaIiEE[_ZNK4nd4j7NDArrayIfE22varianceAlongDimensionIN7simdOps29SummaryStatsStandardDeviationIfEEEEPS1_bRKSt6vectorIiSaIiEE]+0x16f): undefined reference to `float functions::summarystats::SummaryStatsReduce<float>::execScalar<simdOps::SummaryStatsStandardDeviation<float> >(bool, float*, long long*, float*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZNK4nd4j7NDArrayI7float16E22varianceAlongDimensionIN7simdOps20SummaryStatsVarianceIS1_EEEEPS2_bRKSt6vectorIiSaIiEE[_ZNK4nd4j7NDArrayI7float16E22varianceAlongDimensionIN7simdOps20SummaryStatsVarianceIS1_EEEEPS2_bRKSt6vectorIiSaIiEE]+0x16f): undefined reference to `float16 functions::summarystats::SummaryStatsReduce<float16>::execScalar<simdOps::SummaryStatsVariance<float16> >(bool, float16*, long long*, float16*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZNK4nd4j7NDArrayI7float16E22varianceAlongDimensionIN7simdOps29SummaryStatsStandardDeviationIS1_EEEEPS2_bRKSt6vectorIiSaIiEE[_ZNK4nd4j7NDArrayI7float16E22varianceAlongDimensionIN7simdOps29SummaryStatsStandardDeviationIS1_EEEEPS2_bRKSt6vectorIiSaIiEE]+0x16f): undefined reference to `float16 functions::summarystats::SummaryStatsReduce<float16>::execScalar<simdOps::SummaryStatsStandardDeviation<float16> >(bool, float16*, long long*, float16*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZNK4nd4j7NDArrayIdE22varianceAlongDimensionIN7simdOps20SummaryStatsVarianceIdEEEEPS1_bRKSt6vectorIiSaIiEE[_ZNK4nd4j7NDArrayIdE22varianceAlongDimensionIN7simdOps20SummaryStatsVarianceIdEEEEPS1_bRKSt6vectorIiSaIiEE]+0x16f): undefined reference to `double functions::summarystats::SummaryStatsReduce<double>::execScalar<simdOps::SummaryStatsVariance<double> >(bool, double*, long long*, double*)'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(NDArray.cpp.obj):NDArray.cpp:(.text$_ZNK4nd4j7NDArrayIdE22varianceAlongDimensionIN7simdOps29SummaryStatsStandardDeviationIdEEEEPS1_bRKSt6vectorIiSaIiEE[_ZNK4nd4j7NDArrayIdE22varianceAlongDimensionIN7simdOps29SummaryStatsStandardDeviationIdEEEEPS1_bRKSt6vectorIiSaIiEE]+0x16f): undefined reference to `double functions::summarystats::SummaryStatsReduce<double>::execScalar<simdOps::SummaryStatsStandardDeviation<double> >(bool, double*, long long*, double*)'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [blas/CMakeFiles/nd4jcpu.dir/build.make:6348: blas/libnd4jcpu.dll] Error 1
make[2]: Leaving directory '/f/libnd4j/blasbuild/cpu'
make[1]: *** [CMakeFiles/Makefile2:116: blas/CMakeFiles/nd4jcpu.dir/all] Error 2
make[1]: Leaving directory '/f/libnd4j/blasbuild/cpu'
make: *** [Makefile:174: all] Error 2

**Comment by agibsonccc** [comment]
@terU3760  is this based on the latest master? Try my current branch: https://github.com/eclipse/deeplearning4j/pull/9165 -if you're having issues here it should be fixed in this PR

**Comment by terU3760** [comment]
OK. I checkout 2d1376afaaf1340d03e8f7221efbf9fb40c95278 and the error does not appear again.
This problem is solved!

**Comment by agibsonccc** [comment]
Thanks @terU3760  - we'll be merging this within next day or 2. Just working on resolving some smaller issues.
