### ISSUE TITLE
Manually building libnd4jcuda by following instructions but reported some naive error

### ISSUE THREAD

**Issue by terU3760** [deeplearning4j/deeplearning4j#9175]
#### Issue Description

Please describe our issue, along with:
- Sucessfully build libnd4jcuda.dll
- Followed instrcutions step by step but reported some naive error

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version - current newest version
* Platform information (OS, etc) - Windows 10
* CUDA version, -  CUDA Driver Version / Runtime Version - 11.1 / 10.2

#### Additional Information

Have followed the instructions step by step in https://github.com/eclipse/deeplearning4j/blob/master/libnd4j/windows.md

Have run the following command in cmd window of Windows 10 to start Msys2:

set SET_FULL_PATH=true
"D:\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvars64.bat"
D:\msys64\msys2_shell.cmd -mingw64 -mintty

Have run the command in Msys2 Mingw64:

pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-extra-cmake-modules make pkg-config grep sed gzip tar mingw64/mingw-w64-x86_64-openblas mingw-w64-x86_64-lz4 mingw-w64-x86_64-gdb mingw-w64-x86_64-make mingw-w64-x86_64-ninja

also have set environment variables:

export CC=/d/msys64/mingw64/bin/gcc.exe
export CXX=/d/msys64/mingw64/bin/g++.exe
export CMAKE_C_COMPILER=/d/msys64/mingw64/bin/gcc.exe
export CMAKE_CXX_COMPILER=/d/msys64/mingw64/bin/g++.exe

run the command in Msys2 Mingw64:

./buildnativeoperations.sh -c cuda clean true

Error output:

eval cmake
Running windows
Could not find OpenBLAS, please make sure to run the build with Maven or set the OPENBLAS_PATH variable
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                                                           !!
!!                                                                                                           !!
!!                                                                                                           !!
!!                                                                                                           !!
!!                                                 WARNING!                                                  !!
!!                                      No helper packages configured!                                       !!
!!                          You can specify helper by using -h key. I.e. <-h mkldnn>                         !!
!!                                                                                                           !!
!!                                                                                                           !!
!!                                                                                                           !!
!!                                                                                                           !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
PACKAGING = none
BUILD = release
CHIP = cuda
ARCH = x86-64
CHIP_EXTENSION =
CHIP_VERSION =
GPU_COMPUTE_CAPABILITY = all
EXPERIMENTAL = no
LIBRARY TYPE = dynamic
OPERATIONS = -DSD_ALL_OPS=true
MINIFIER = -DSD_BUILD_MINIFIER=false
TESTS = -DSD_BUILD_TESTS=OFF
NAME = -DSD_LIBRARY_NAME=nd4jcuda
OPENBLAS_PATH =
CHECK_VECTORIZATION = OFF
HELPERS =
Removing blasbuild
/f/deeplearning4j/libnd4j/blasbuild/cuda
CMake Error at D:/msys64/mingw64/share/cmake-3.18/Modules/CMakeDetermineCCompiler.cmake:49 (message):
  Could not find compiler set in environment variable CC:

  cl.exe.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "F:/deeplearning4j/libnd4j/blasbuild/cuda/CMakeFiles/CMakeOutput.log".

The content in F:/deeplearning4j/libnd4j/blasbuild/cuda/CMakeFiles/CMakeOutput.log is:
The system is: Windows - 10.0.19042 - AMD64

**Comment by saudet** [comment]
That means you haven't installed Visual Studio. Please do follow the build instructions!

**Comment by terU3760** [comment]
@saudet  I have run all the commands in the instructions here https://deeplearning4j.konduit.ai/getting-started/build-from-source and here https://github.com/eclipse/deeplearning4j/blob/master/libnd4j/windows.md ,
The error is still there!

**Comment by saudet** [comment]
Even this?
> Additionally, you need to open the mingw64.ini in your msys64 installation folder and add the command: MSYS2_PATH_TYPE=inherit.

**Comment by terU3760** [comment]
@saudet  Yes. The file mingw64.ini is in the folder D:\msys64 and I have changed its content to:

#MSYS=winsymlinks:nativestrict
#MSYS=error_start:mingw64/bin/qtcreator.exe|-debug|<process-id>
#CHERE_INVOKING=1
MSYS2_PATH_TYPE=inherit
MSYSTEM=MINGW64

**Comment by saudet** [comment]
Ok, so, why is cl.exe not in your PATH?

**Comment by terU3760** [comment]
@saudet I have no idea. When I type:
echo $PATH

I got the following result:
/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

**Comment by terU3760** [comment]
@saudet And the very intresting thing is that I can build the CPU version of libnd4j without any error at all!

**Comment by saudet** [comment]
Well, you'll need to figure out what's wrong with your installation of Visual Studio! It's a requirement for CUDA.

**Comment by terU3760** [comment]
@saudet  Hey, saudet! I have installed VS2019 in this directory: D:\Microsoft Visual Studio\2019\Professional .  Perhaps you have found the cause:
When the command is run in the CMD window in Windows 10, when I typed:
echo %PATH%

The output is:
D:\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64;D:\Microsoft Visual Studio\2019\Professional\Common7\IDE\VC\VCPackages;D:\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow;D:\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;D:\Microsoft Visual Studio\2019\Professional\MSBuild\Current\bin\Roslyn;D:\Microsoft Visual Studio\2019\Professional\Team Tools\Performance Tools\x64;D:\Microsoft Visual Studio\2019\Professional\Team Tools\Performance Tools;D:\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;D:\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\HTML Help Workshop;D:\Windows Kits\10\bin\10.0.19041.0\x64;D:\Windows Kits\10\bin\x64;D:\Microsoft Visual Studio\2019\Professional\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;D:\Microsoft Visual Studio\2019\Professional\Common7\IDE\;D:\Microsoft Visual Studio\2019\Professional\Common7\Tools\;D:\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64;D:\Microsoft Visual Studio\2019\Professional\Common7\IDE\VC\VCPackages;D:\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow;D:\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;D:\Microsoft Visual Studio\2019\Professional\MSBuild\Current\bin\Roslyn;D:\Microsoft Visual Studio\2019\Professional\Team Tools\Performance Tools\x64;D:\Microsoft Visual Studio\2019\Professional\Team Tools\Performance Tools;D:\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;D:\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\HTML Help Workshop;D:\Windows Kits\10\bin\10.0.19041.0\x64;D:\Windows Kits\10\bin\x64;D:\Microsoft Visual Studio\2019\Professional\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;D:\Microsoft Visual Studio\2019\Professional\Common7\IDE\;D:\Microsoft Visual Studio\2019\Professional\Common7\Tools\;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;D:\Anaconda3;D:\Anaconda3\Library\mingw-w64\bin;D:\Anaconda3\Library\usr\bin;D:\Anaconda3\Library\bin;D:\Anaconda3\Scripts;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;D:\msys64\mingw64\bin;D:\TensorRT-7.2.1.6\lib;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;C:\Users\Skymind\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\Skymind\AppData\Local\Programs\Python\Python38\;C:\Users\Skymind\AppData\Local\Microsoft\WindowsApps;C:\Users\Skymind\.dotnet\tools;D:\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\x64\bin;D:\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;D:\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;D:\Microsoft Visual Studio\2019\Professional\Common7\IDE\VC\Linux\bin\ConnectionManagerExe;D:\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\x64\bin;D:\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;D:\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;D:\Microsoft Visual Studio\2019\Professional\Common7\IDE\VC\Linux\bin\ConnectionManagerExe

But after run the command:
D:\msys64\msys2_shell.cmd -mingw64 -mintty

to start the msys2 window and in this window type:
echo $PATH

The output is:
/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

@saudet Do you think it is the cause? If so, how to correct it?

**Comment by saudet** [comment]
It's going to do that if you don't follow the instructions about the INI file there. If you follow the instructions, it should work.

**Comment by terU3760** [comment]
@saudet 
I really have edited the .ini file. The file is in the directory: D:\msys64. And it's content is:
#MSYS=winsymlinks:nativestrict
#MSYS=error_start:mingw64/bin/qtcreator.exe|-debug|<process-id>
#CHERE_INVOKING=1
MSYS2_PATH_TYPE=inherit
MSYSTEM=MINGW64

Do you think the content of the file is right or not? What's the problem can you please explain it for me?

**Comment by saudet** [comment]
It doesn't look like you're using the usual launcher. If you prefer to use a different one than "mingw64", you're on your own.

**Comment by terU3760** [comment]
@saudet  Hey! What do you mean by the usual launcher? I'm not familiar with the mechanism of msys2? Could you please provide me a little information about the launch? Do you mean I should change MINGW64 to something else and only doing this will solve my problem here?

**Comment by saudet** [comment]
No, I mean instead of msys2_shell.cmd try to use mingw64.exe as shown in the instructions. Like I said before, if you do not follow the instructions, you're on your own.

**Comment by terU3760** [comment]
@saudet OK. Thanks a lot! After I start the msys2 window by mingw64.exe, the error disappeared!
