### ISSUE TITLE
Document how to set specific CPU backend

### ISSUE THREAD

**Issue by LifeIsStrange** [deeplearning4j/deeplearning4j#9176]
https://deeplearning4j.konduit.ai/config/backends
From the doc it is unclear which cpu backend does nd4j-native use by default.
Also it is undocumented how we can change it and which ones are currently supported. 
E.g OpenBLAS, MKL, others?

BTW thanks for developing ND4J, it is a foundational JVM library!

**Comment by saudet** [comment]
MKL used to get loaded by default, but I think that changed back to OpenBLAS with beta7.
To get MKL called again, follow the instructions here:
https://github.com/bytedeco/javacpp-presets/tree/master/openblas#documentation

**Comment by LifeIsStrange** [comment]
Would be nice to document it / link the instructions from the nd4j doc but you have answered me so feel free to close this issue :)
