### ISSUE TITLE
Beta-7 different outputs on GPU and CPU regression

### ISSUE THREAD

**Issue by ghost** [deeplearning4j/deeplearning4j#9199]
OS: Windows
DL4J: deeplearning4j 1.0.0-beta7
CUDA: 10.2
cuDNN: 7.6
Issue: The results of regression (eg. BostonHousePricePrediction.java) running on GPU are not same as results running on CPU. Attached are the screenshot of the results.
Original Issue from: https://github.com/CertifaiAI/TrainingLabs/issues/124 

CPU:
Using CPU as backend:
![image](https://user-images.githubusercontent.com/63772006/109612802-3ec8db80-7b6b-11eb-8ed3-c24a483f1155.png)

Result running on CPU backend:
![image](https://user-images.githubusercontent.com/63772006/109612820-44262600-7b6b-11eb-8124-23d924ee9320.png)

GPU:
Using GPU as backend:
![image](https://user-images.githubusercontent.com/63772006/109612897-5dc76d80-7b6b-11eb-98b6-8b4551e1d8b4.png)

Result running on GPU backend:
![image](https://user-images.githubusercontent.com/63772006/109612908-64ee7b80-7b6b-11eb-8e20-3d0b8e5cf56b.png)

**Comment by agibsonccc** [comment]
Closing as duplicate in favor of: https://github.com/eclipse/deeplearning4j/issues/9142 for a workaround please pre save the data on cpu and avoid shuffle operations on gpu. This will be added as a known issue so people know what the work around is.

**Comment by quickwritereader** [comment]
#9472
