### ISSUE TITLE
Size of unigram table in InMemoryLookupTable should be larger than vocab size

### ISSUE THREAD

**Issue by rajeev3983** [deeplearning4j/deeplearning4j#920]
In initNegative method of InMemoryLookupTable, the table size should be larger than the vocabSize for negative sampling to work properly. The current size (10000) is too small. The C implementation makes sure that the table size is atleast 5 times larger than the vocabSize.

**Comment by raver119** [comment]
No, table size has fixed in original w2v, however it's bigger then dl4j.
syn1Neg is exact size of syn0/syn1, and table has fixed size. It can be safely increased, though :)
