### ISSUE TITLE
Error loading dimension of pooling layer

### ISSUE THREAD

**Issue by anonNo2** [deeplearning4j/deeplearning4j#9200]
#### Issue Description
Hi~

i found a problem When I use deeplearning4j(beta7) to load the Keras-trained model(keras version:2.4.3),

this is my model structure：

| Layer (type)                 | Output Shape    | Param   |
| ---------------------------- | --------------- | ------- |
| embedding (Embedding)        | (None, 32, 200) | 2000000 |
| global_average_pooling1d (Gl | (None, 200)     | 0       |
| dense (Dense)                | (None, 128)     | 25728   |
| dense_1 (Dense)              | (None, 10)      | 1290    |

global_average_pooling1d has an arguments named data_format:

```python
    data_format: A string,
      one of `channels_last` (default) or `channels_first`.
      The ordering of the dimensions in the inputs.
      `channels_last` corresponds to inputs with shape
      `(batch, steps, features)` while `channels_first`
      corresponds to inputs with shape
      `(batch, features, steps)`.

  Call arguments:
    inputs: A 3D tensor.
    mask: Binary tensor of shape `(batch_size, steps)` indicating whether
      a given step should be masked (excluded from the average).

  Input shape:
    - If `data_format='channels_last'`:
      3D tensor with shape:
      `(batch_size, steps, features)`
    - If `data_format='channels_first'`:
      3D tensor with shape:
      `(batch_size, features, steps)`
```

But when i load this model by deeplearning4j, D4J ignores this argument:

org.deeplearning4j.nn.modelimport.keras.layers.pooling.KerasPoolingUtils

```java
/**
     * Map Keras pooling layers to DL4J pooling dimensions.
     *
     * @param className name of the Keras pooling class
     * @return pooling dimensions as int array
     * @throws UnsupportedKerasConfigurationException Unsupported Keras config
     */
    public static int[] mapGlobalPoolingDimensions(String className, KerasLayerConfiguration conf)
            throws UnsupportedKerasConfigurationException {
        int[] dimensions;
        if (className.equals(conf.getLAYER_CLASS_NAME_GLOBAL_MAX_POOLING_1D()) ||
                className.equals(conf.getLAYER_CLASS_NAME_GLOBAL_AVERAGE_POOLING_1D())) {
            dimensions = new int[]{2};
        } else if (className.equals(conf.getLAYER_CLASS_NAME_GLOBAL_MAX_POOLING_2D()) ||
                className.equals(conf.getLAYER_CLASS_NAME_GLOBAL_AVERAGE_POOLING_2D())) {
            dimensions = new int[]{2, 3};
        } else if (className.equals(conf.getLAYER_CLASS_NAME_GLOBAL_MAX_POOLING_3D()) ||
            className.equals(conf.getLAYER_CLASS_NAME_GLOBAL_AVERAGE_POOLING_3D())) {
        dimensions = new int[]{2, 3, 4};
    }  else {
            throw new UnsupportedKerasConfigurationException("Unsupported Keras pooling layer " + className);
        }
        return dimensions;
    }


```

The dimensions are simply specified based on the type of the pooling layer.

So I got the wrong dimension when I loaded it.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j : beta7
* Platform information  : MacOS
* Keras version : 2.4.3
* Tensorflow version : 2.4.1

**Comment by agibsonccc** [comment]
@anonNo2  could you please try with snapshots?  Channels/last first was fixed a while back. New release is coming out soon. https://deeplearning4j.konduit.ai/config/config-snapshots

**Comment by anonNo2** [comment]
OK~ Thanks~
