### ISSUE TITLE
DL4J Build for RHEL 7 (devtoolset-7)

### ISSUE THREAD

**Issue by madhs53** [deeplearning4j/deeplearning4j#9217]
Hi all.

I've been trying to run DL4J beta-6 (CUDA 10.1) on RHEL 7 PPC64.

We used to run DL4J beta-2 and had to build from source due to CXXABI_1.3.8 not being available on our version of RHEL (we only had CXXABI_1.3.7). We built from source as per [this thread](https://github.com/eclipse/deeplearning4j/issues/6805), which worked.

We now want to upgrade to DL4J beta-6, and have followed steps to build from source again. The build was successful, however when we run with the built artifacts we get this error:

162791 [pool-6-thread-1] WARN org.nd4j.linalg.factory.Nd4jBackend - Skipped [JCublasBackend] backend (unavailable): java.lang.UnsatisfiedLinkError: /home/omp394/.javacpp/cache/DL4J_MINSKY-1.0.0-beta6-cuda101.jar/org/bytedeco/cuda/linux-ppc64le/libjnicudart.so: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/omp394/.javacpp/cache/DL4J_MINSKY-1.0.0-beta6-cuda101.jar/org/bytedeco/cuda/linux-ppc64le/libjnicudart.so)

Is this because we need to build bytedeco cuda from source as well?

**Comment by agibsonccc** [comment]
@madhs53 mind DMing me on the forums at https://community.konduit.ai with more specifics? We're not supporting older builds publicly, but we'd be happy to work with you on an arrangement that makes sense. It's a lot of work to support an older release alongside backports and the like.

**Comment by madhs53** [comment]
Thanks Adam. All good, managed to get it working by building javacpp cuda from source (along with nd4j) and shading the new artifacts along with other beta6 artifacts.

**Comment by agibsonccc** [comment]
@madhs53  just note we don't typically support older releases. Beta6 is VERY old at this point. (1 year at least). We'll be releasing 1.0 soon with a lot of new features and bug fixes including support model import for onnx. Drop me a message about how we can get that updated.
