### ISSUE TITLE
SequenceRecordReaderDataSetIterator for Regression

### ISSUE THREAD

**Issue by Julian-Theis** [deeplearning4j/deeplearning4j#923]
Hi,

I want to create an RNN which predicts the next numerical value trained on a dataset. I am trying to create an appropriate SequenceRecordReaderDataSetIterator by using following code snippet:

> File f = new File("dl4j_input.csv");
File f2 = new File("dl4j_output.csv");
SequenceRecordReader input = new CSVSequenceRecordReader();
SequenceRecordReader target = new CSVSequenceRecordReader();
input.initialize(new FileSplit(f));
target.initialize(new FileSplit(f2));
SequenceRecordReaderDataSetIterator seqIter = new SequenceRecordReaderDataSetIterator(input, target, 1, 0, true);
DataSetIterator trainIter = seqIter;

If I want to output the next entry of trainIter, I get the IllegalArgumentException "Index [1] must not be >= shape[d]".

I've attached the two csv-datasets. dl4j_input.csv contains simple +1 steps from 1 to 10. dl4j_output.csv contains the same data as input, but with an +1 offset, as it represents the next value which should be predicted.
Due to supported file formats, I've changed the names to __.csv.txt.

[dl4j_input.csv.txt](https://github.com/deeplearning4j/deeplearning4j/files/49567/dl4j_input.csv.txt)
[dl4j_output.csv.txt](https://github.com/deeplearning4j/deeplearning4j/files/49568/dl4j_output.csv.txt)

**Comment by AlexDBlack** [comment]
Turns out this was a bug in SequenceRecordReaderDataSetIterator for regression.
Fixed: https://github.com/deeplearning4j/deeplearning4j/pull/926
