### ISSUE TITLE
Broken releasenotes url

### ISSUE THREAD

**Issue by srvvrma** [deeplearning4j/deeplearning4j#9239]
#### Issue Description

Please describe our issue, along with:
- broken link. The mentioned URL is getting redirected to the same URL.
 URL: https://deeplearning4j.org/releasenotes

**Comment by agibsonccc** [comment]
@vrmasrv  here's the proper url: https://deeplearning4j.konduit.ai/getting-started/release-notes
Note we don't use deeplearning4j.org anymore. If you have issues finding something, please do let us know and we'll make sure you're redirected.
