### ISSUE TITLE
Please provide an example of LSTM Network for Anomaly Detection

### ISSUE THREAD

**Issue by chenbekor** [deeplearning4j/deeplearning4j#925]
currently there is only one example for lstm showing word prediction. since LSTM has unique memory capabilities it will be nice to understand how to utilize it for anomaly detection in time series data.

**Comment by tomthetrainer** [comment]
Anyone have any advice on reasonably sized sample data for this, or data I can download in the example so as not to bloat the examples?

**Comment by AlexDBlack** [comment]
One of the data sets from this paper might be viable: (though I haven't looked into them) https://www.elen.ucl.ac.be/Proceedings/esann/esannpdf/es2015-56.pdf
