### ISSUE TITLE
Deeplearning4j in Azure App Service generates NoClassDefFoundError

### ISSUE THREAD

**Issue by AlexandruPDA** [deeplearning4j/deeplearning4j#9261]
## Issue Description

I integrated Deeplearning4j into a Spring Boot application, in order to:
* import a previously trained Keras model
* call the model with the passed data for obtaining the prediction, during a POST request. 

Running the app with IntelliJ returns the expected predictions. Also, running the app within the JAR generated by Spring works correctly, using: ```java -jar app.jar```

However, after deploying the app into an Azure App Service and calling the POST endpoint, is thrown the following: 
```
Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.nd4j.linalg.factory.Nd4j
with root cause
java.lang.NoClassDefFoundError: Could not initialize class org.nd4j.linalg.factory.Nd4jat org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.readDataSet

~[deeplearning4j-modelimport-1.0.0-beta7.jar!/:na]at org.deeplearning4j.nn.modelimport.keras.Hdf5Archive.readDataSet(Hdf5Archive.java:114) 
~[deeplearning4j-modelimport-1.0.0-beta7.jar!/:na]at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.importWeights(KerasModelUtils.java:285) 
~[deeplearning4j-modelimport-1.0.0-beta7.jar!/:na]at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:149) 
~[deeplearning4j-modelimport-1.0.0-beta7.jar!/:na]at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:57) 
~[deeplearning4j-modelimport-1.0.0-beta7.jar!/:na]at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:322) 
~[deeplearning4j-modelimport-1.0.0-beta7.jar!/:na]at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:223) 
~[deeplearning4j-modelimport-1.0.0-beta7.jar!/:na]at com.ml.mlserver.controller.MachineLearningModelController.predictFeedback(MachineLearningModelController.java:52)
```

What I have tried for testing the app, in local environments:
* running the JAR on another Windows 10 computer and on Ubuntu Virtual Machine (_runs correctly in all_)
* generated uber-jar with all dependencies encapsulated

What I have tried in Azure:
* besides the original endpoint, I implemented another POST endpoint with hardcoded return. Then, using Postman to perform the request, is returned the correct value. _**However, when calling the "real" endpoint is thrown the above error.**_ 
* tested the app into Windows and Ubuntu App Services, by deploying using following methods: 
   * GitHub Actions (_to build and deploy the app_)
   * FTP connection with **_web.config_** file (_to upload directly the local JARs, because I thought that some dependencies cannot be seen during build phase from GitHub actions_)

## Version Information
* Deeplearning4j version: _**1.0.0-beta7**_
* Platform information: _**Windows and Ubuntu, 64-bit**_
* CUDA version: _**not used**_
* NVIDIA driver version: _**not used**_

## Additional Information
Logs for running app locally, with endpoint call: https://gist.github.com/AlexandruPDA/2a3ebc05a3a0e078d22c9db574e1a3c4
**I expected to run in the same way in Azure.**

_**POM.xml**_ : https://gist.github.com/AlexandruPDA/dfb28c162c05bb461828c30e55c4bb66

**Importing the Keras model using:**
```
import org.deeplearning4j.nn.modelimport.keras.KerasModelImport;
import org.deeplearning4j.nn.modelimport.keras.exceptions.InvalidKerasConfigurationException;
import org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.nd4j.common.io.ClassPathResource;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.factory.Nd4j;

...
String pathModel = new ClassPathResource("machine_learning_model.h5").getFile().getPath();
MultiLayerNetwork model = KerasModelImport.importKerasSequentialModelAndWeights(pathModel);

...
INDArray outputProbability = model.output(array);   // equivalent to model.predict(array)
```

I would appreciate if you could give me any advice for solving the error.

Best regards.

**Comment by treo** [comment]
Even though it will probably not solve your problem (as I guess that it will probably fail just a little bit later), I'd like to note here, that importing models in production isn't exactly best practice. Instead we suggest that you import the model and then save it as a DL4J model.

**Comment by AlexandruPDA** [comment]
Alright, I understand. Thank you very much for the suggestion.

**Comment by agibsonccc** [comment]
@AlexandruPDA  only thing I could guess is an underlying native error with hdf5 somewhere... I'll highlight this for @saudet  if he has more context, otherwise Paul's suggestion would be the most straightforward.

**Comment by saudet** [comment]
To get more information about loading issues like that, make sure that the “org.bytedeco.javacpp.logger.debug” system property is set to “true” or the “org.bytedeco.javacpp.logger” one is set to “slf4j” with your logger set to its debug level.
