### ISSUE TITLE
build fails on AArch64, Fedora 33 for libnd4j 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [deeplearning4j/deeplearning4j#9265]
[jw@cn05 libnd4j]$ ./buildnativeoperations.sh
...
[  1%] Building CXX object blas/CMakeFiles/samediff_obj.dir/__/include/legacy/impl/cnpy.cpp.o
cd /data/jw/deeplearning4j/libnd4j/blasbuild/cpu/blas && /usr/bin/c++ -DCPU_FEATURES=true -DDNNL_ENABLE_CONCURRENT_EXEC=true -D__CPUBLAS__=true -D__EXTERNAL_BLAS__=true -I/data/jw/deeplearning4j/libnd4j/blasbuild/cpu/cpu_features-src/include -I/data/jw/deeplearning4j/libnd4j/blasbuild/cpu/flatbuffers-src/include -I/data/jw/deeplearning4j/libnd4j/blasbuild/cpu/include -I/data/jw/deeplearning4j/libnd4j/include -DSD_ARM_BUILD=true -DSD_ALL_OPS=true -DF_X64=true -march=x86-64 -mtune=generic -fmax-errors=2  -fopenmp -O3 -fPIC -D_RELEASE=true -std=gnu++11 -o CMakeFiles/samediff_obj.dir/__/include/legacy/cpu/NativeOpExecutioner.cpp.o -c /data/jw/deeplearning4j/libnd4j/include/legacy/cpu/NativeOpExecutioner.cpp
cd /data/jw/deeplearning4j/libnd4j/blasbuild/cpu/blas && /usr/bin/c++ -DCPU_FEATURES=true -DDNNL_ENABLE_CONCURRENT_EXEC=true -D__CPUBLAS__=true -D__EXTERNAL_BLAS__=true -I/data/jw/deeplearning4j/libnd4j/blasbuild/cpu/cpu_features-src/include -I/data/jw/deeplearning4j/libnd4j/blasbuild/cpu/flatbuffers-src/include -I/data/jw/deeplearning4j/libnd4j/blasbuild/cpu/include -I/data/jw/deeplearning4j/libnd4j/include -DSD_ARM_BUILD=true -DSD_ALL_OPS=true -DF_X64=true -march=x86-64 -mtune=generic -fmax-errors=2  -fopenmp -O3 -fPIC -D_RELEASE=true -std=gnu++11 -o CMakeFiles/samediff_obj.dir/__/include/legacy/cpu/NativeOps.cpp.o -c /data/jw/deeplearning4j/libnd4j/include/legacy/cpu/NativeOps.cpp
cd /data/jw/deeplearning4j/libnd4j/blasbuild/cpu/blas && /usr/bin/c++ -DCPU_FEATURES=true -DDNNL_ENABLE_CONCURRENT_EXEC=true -D__CPUBLAS__=true -D__EXTERNAL_BLAS__=true -I/data/jw/deeplearning4j/libnd4j/blasbuild/cpu/cpu_features-src/include -I/data/jw/deeplearning4j/libnd4j/blasbuild/cpu/flatbuffers-src/include -I/data/jw/deeplearning4j/libnd4j/blasbuild/cpu/include -I/data/jw/deeplearning4j/libnd4j/include -DSD_ARM_BUILD=true -DSD_ALL_OPS=true -DF_X64=true -march=x86-64 -mtune=generic -fmax-errors=2  -fopenmp -O3 -fPIC -D_RELEASE=true -std=gnu++11 -o CMakeFiles/samediff_obj.dir/__/include/legacy/impl/Environment.cpp.o -c /data/jw/deeplearning4j/libnd4j/include/legacy/impl/Environment.cpp
cd /data/jw/deeplearning4j/libnd4j/blasbuild/cpu/blas && /usr/bin/c++ -DCPU_FEATURES=true -DDNNL_ENABLE_CONCURRENT_EXEC=true -D__CPUBLAS__=true -D__EXTERNAL_BLAS__=true -I/data/jw/deeplearning4j/libnd4j/blasbuild/cpu/cpu_features-src/include -I/data/jw/deeplearning4j/libnd4j/blasbuild/cpu/flatbuffers-src/include -I/data/jw/deeplearning4j/libnd4j/blasbuild/cpu/include -I/data/jw/deeplearning4j/libnd4j/include -DSD_ARM_BUILD=true -DSD_ALL_OPS=true -DF_X64=true -march=x86-64 -mtune=generic -fmax-errors=2  -fopenmp -O3 -fPIC -D_RELEASE=true -std=gnu++11 -o CMakeFiles/samediff_obj.dir/__/include/legacy/impl/cnpy.cpp.o -c /data/jw/deeplearning4j/libnd4j/include/legacy/impl/cnpy.cpp
cc1plus: error: unknown value 'x86-64' for '-march'
cc1plus: error: unknown value 'x86-64' for '-march'
cc1plus: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a native
cc1plus: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a native
cc1plus: error: unknown value 'x86-64' for '-march'
cc1plus: error: unknown value 'x86-64' for '-march'
cc1plus: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a native
cc1plus: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a native
make[2]: *** [blas/CMakeFiles/samediff_obj.dir/build.make:108: blas/CMakeFiles/samediff_obj.dir/__/include/legacy/impl/Environment.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [blas/CMakeFiles/samediff_obj.dir/build.make:82: blas/CMakeFiles/samediff_obj.dir/__/include/legacy/cpu/NativeOpExecutioner.cpp.o] Error 1
make[2]: *** [blas/CMakeFiles/samediff_obj.dir/build.make:121: blas/CMakeFiles/samediff_obj.dir/__/include/legacy/impl/cnpy.cpp.o] Error 1
make[2]: *** [blas/CMakeFiles/samediff_obj.dir/build.make:95: blas/CMakeFiles/samediff_obj.dir/__/include/legacy/cpu/NativeOps.cpp.o] Error 1
make[2]: Leaving directory '/data/jw/deeplearning4j/libnd4j/blasbuild/cpu'
make[1]: *** [CMakeFiles/Makefile2:355: blas/CMakeFiles/samediff_obj.dir/all] Error 2
make[1]: Leaving directory '/data/jw/deeplearning4j/libnd4j/blasbuild/cpu'
make: *** [Makefile:174: all] Error 2
[jw@cn05 libnd4j]$

**Comment by treo** [comment]
have you tried calling it with the `-a native` parameter? Not quite sure why it picks up `-march=x86-64` here.

**Comment by agibsonccc** [comment]
@LutzWeischerFujitsu you can try snapshots which has linux-aarch64 builds. https://deeplearning4j.konduit.ai/config/config-snapshots

The pre compiled libnd4j binaries if you just want those are here:
https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/libnd4j/1.0.0-SNAPSHOT/
Again, ctrl + f linux-arm64

You can also see how the build happens here:
https://github.com/eclipse/deeplearning4j/blob/master/.github/workflows/build-deploy-linux-arm64.yml#L66
 The key script is the build_pi.sh

If you want to just use snapshots, you can see them here:
https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/nd4j-native/1.0.0-SNAPSHOT/
Ctrl + f linux-arm64

I'm closing this because I know the builds work. If you have further concerns, please feel free to ask for further help on the forums:
https://community.konduit.ai

Thanks!

**Comment by LutzWeischerFujitsu** [comment]
Using '-a native': 

...
In file included from /data/jw/deeplearning4j/libnd4j/include/legacy/cpu/NativeOps.cpp:83:
/data/jw/deeplearning4j/libnd4j/blasbuild/cpu/cpu_features-src/include/cpuinfo_x86.h:205:2: error: #error "Including cpuinfo_x86.h from a non-x86 target."
  205 | #error "Including cpuinfo_x86.h from a non-x86 target."
      |  ^~~~~
...

**Comment by agibsonccc** [comment]
@LutzWeischerFujitsu  thanks again for trying to compile libnd4j on aarch64. Could you try the script I mentioned? I know for a fact your problem is already solved. Were  you missing something? Is there something in specific that's not working for you?

**Comment by LutzWeischerFujitsu** [comment]
pi_build.sh is downloading from Arm a x86-64 GCC cross compiler version. The script fails on OpenBLAS, which is installed. 
Besides having the benefits of individual, specific snapshots, my intention is to compile the GitHub master version to be able to take advantage of different hardware, but using the same source code.

**Comment by agibsonccc** [comment]
@quickwritereader  can comment further here since he maintains the script. buildnativeoperations.sh can/should compile natively find on arm. It just invokes cmake. I'm still leaving this issue closed since I know we have binaries that work fine for aarch64. We'll update the docs in the mean time to make sure it's more straightforward to do this.

**Comment by quickwritereader** [comment]
1. compiling  arm libnd4j libs on native platform
```
 #export OPENBLAS_PATH="path to the openblas lib" 
 ./buildnativeoperations.sh -o linux-arm64 -j 4 -t
```

2.   cross compile for arm64 on linux x86 host
```
./pi_build.sh -a arm64
```

**Comment by LutzWeischerFujitsu** [comment]
Thanks, that helped. I noticed another problem: 
[jw@cn05 deeplearning4j]$ mvn -B -V -U install -pl '!jumpy,!pydatavec,!pydl4j' -Dlibnd4j.platform=linux-aarch64 -Djavacpp.platform=linux-aarch64 -Dmaven.test.skip=true
Apache Maven 3.6.3 (Red Hat 3.6.3-5)
Maven home: /usr/share/maven
Java version: 11.0.10, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.10.0.9-0.fc33.aarch64
Default locale: en_US, platform encoding: ISO-8859-1
OS name: "linux", version: "5.8.6-301.fc33.aarch64", arch: "aarch64", family: "unix"
[INFO] Scanning for projects...
[ERROR] [ERROR] Could not find the selected project in the reactor: jumpy @
[ERROR] Could not find the selected project in the reactor: jumpy -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
[jw@cn05 deeplearning4j]$

**Comment by treo** [comment]
Good catch. We've mothballed some of the sub-projects. 

I think you can just drop those exclusions now, i.e. try `mvn -B -V -U install -Dlibnd4j.platform=linux-aarch64 -Djavacpp.platform=linux-aarch64 -Dmaven.test.skip=true`

**Comment by LutzWeischerFujitsu** [comment]
Than I get: 

...
[ERROR] Failed to execute goal org.bytedeco:javacpp:1.5.5:build (javacpp-cppbuild-validate) on project libnd4j: Execution javacpp-cppbuild-validate of goal org.bytedeco:javacpp:1.5.5:build failed: Plugin org.bytedeco:javacpp:1.5.5 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.bytedeco:javacpp:jar:linux-aarch64:1.5.5, org.bytedeco:openblas:jar:linux-aarch64:0.3.13-1.5.5: Could not find artifact org.bytedeco:javacpp:jar:linux-aarch64:1.5.5 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
...

**Comment by agibsonccc** [comment]
@LutzWeischerFujitsu set it to linux-arm64 not linux-arch64. Sorry for the confusion. See: https://repo1.maven.org/maven2/org/bytedeco/openblas/0.3.13-1.5.5/ for the available classifiers.

**Comment by LutzWeischerFujitsu** [comment]
After a while I get for 'nd4j-native': 

(base) [jw@cn05 deeplearning4j]$ mvn -B -V -U install -Dlibnd4j.platform=linux-arm64 -Djavacpp.platform=linux-arm64 -Dmaven.test.skip=true
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  45:23 min
[INFO] Finished at: 2021-04-20T09:24:00+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.bytedeco:javacpp:1.5.5:build (javacpp-compiler) on project nd4j-native: Failed to execute JavaCPP Builder: Cannot run program "aarch64-linux-gnu-g++" (in directory "/data/jw/deeplearning4j/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/linux-arm64"): error=2, No such file or directory -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :nd4j-native
(base) [jw@cn05 deeplearning4j]$
