### ISSUE TITLE
Workspace "WS_LAYER_WORKING_MEM" for array type FF_WORKING_MEM is not open

### ISSUE THREAD

**Issue by HGuillemet** [deeplearning4j/deeplearning4j#9268]
#### Issue Description

See [this forum post](https://community.konduit.ai/t/workspace-ws-layer-working-mem-for-array-type-ff-working-mem-is-not-open/1317/5)

#### Version Information

DL4J 1.0.0 beta 7
Cuda 10.2
Linux

#### Additional Information

https://gist.github.com/HGuillemet/a5acb56ac9d86fae74ca8bd1ce24f3b7

**Comment by agibsonccc** [comment]
@HGuillemet I'm beginning work on post bug fix releases for M2. Could you see if M1 fixes this issue? Otherwise, I'll get a quick round of fixes in for these kinds of things. Thanks!

**Comment by agibsonccc** [comment]
@HGuillemet fix was pretty simple: https://github.com/eclipse/deeplearning4j/pull/9341 just needed to add a workspace notify enter during the scoring process. The feed forward process was detached while the rest of the scoring was not. Thanks for reporting.

**Comment by HGuillemet** [comment]
Thanks for spending time on this issue !
