### ISSUE TITLE
Unsupported keras layer type Conv3DTranspose

### ISSUE THREAD

**Issue by Acander** [deeplearning4j/deeplearning4j#9270]
HI! I cannot load my keras CVAE model to java since I am getting the following error: “Unsupported keras layer type Conv3DTranspose”. Why is it not possible to load Conv3DTranspose layers with DL4J? What do I need to do mitigate this problem?

**Comment by agibsonccc** [comment]
Fixed here: https://github.com/eclipse/deeplearning4j/commit/75899208427bb755f8629d6a17d594162a078fa4
