### ISSUE TITLE
Is function for subsampling of frequent  words in word2vec correct?

### ISSUE THREAD

**Issue by rajeev3983** [deeplearning4j/deeplearning4j#928]
The addWords function of Word2Vec which subsamples frequent words seems to be incorrect. 
```
 double ran = (Math.sqrt(word.getWordFrequency() / (sample * numDocs)) + 1)
                        * (sample * numDocs) / word.getWordFrequency();
```
The C implementation uses totalNumberOfWords in Doc instead of numDocs for the calculation of ran.

**Comment by raver119** [comment]
Yes, it's the same for d2v, since that's the same codebase after all. I've already fixed that, and will push to master later today with other stuff.

**Comment by raver119** [comment]
+ right now subsampling is disabled for w2v, i'll enable it in the same commit, sure

**Comment by raver119** [comment]
Fixed, committed, merged.
