### ISSUE TITLE
Question: jetson documentation

### ISSUE THREAD

**Issue by ramarro123** [deeplearning4j/deeplearning4j#9289]
hello,

there is any guide on jetson nano from nvidia?
i checked here:
https://deeplearning4j.konduit.ai/config/backends

but i don't fully understand how to enble cuda & cuDNN on that platform.

the linux image prepared by nvidia already have driver for cuDNN & cuda standing to the SDK docs, but i don't understand how to enable adding the correct pom/dependencies/config

thanks

**Comment by treo** [comment]
Questions like that are best asked on the community forums (https://community.konduit.ai/).

But in general, you enable it like on any other platform. Make sure that you use the same cuda version as the one that is installed.
