### ISSUE TITLE
Word2Vec similarity issue

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#929]
Word2Vec words similarity measurement is broken atm, it can return values > 1.0 and < 0
Unit test produces the following results:

o.d.m.w.Word2VecTests - [week, night, year, game, season, time, while, years, off, house]
o.d.m.w.Word2VecTests - Day/night similarity: 1.249921441078186

**Comment by raver119** [comment]
It looks like there's issue with Nd4j dot() method: 

Consider the following code: https://gist.github.com/raver119/1b88e95944066ba87204

Produces the following result:
Arrays 1/2 cosineSim: 0.3324026100827507
Arrays 2/3 cosineSim: 0.3362467127679651

**Comment by AlexDBlack** [comment]
is this on nd4j master? there were some issues due to changes to accumulation ops recently, may have been fixed in recent PRs.

**Comment by AlexDBlack** [comment]
Just run your unit test on latest nd4j; results seem sensible now.

**Comment by raver119** [comment]
yes, it was on yesterday current master, but right now it's ok. ty.
