### ISSUE TITLE
Add option for abstract sequence data features extraction via Word2Vec

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/deeplearning4j#930]
Since Word2Vec features learning method could be applied to virtually any sequences of data, maybe it's worth to make dl4j nlp/sentences word2vec implementation just a special clause of abstract unsupervised feature extraction using skip-gram or cbow?

Since all that SG relies on is unique object count + Huffman encoding derived on that counts. If user can provide class that contains counter, and proper equals/hashCode - it doesn't matter for w2v, if there's any strings actually involved.

There's DeepWalk was added into dl4j spark, and it shares very close idea. So maybe we could do it   available for abstract sequences?

**Comment by AlexDBlack** [comment]
The basic idea, from my perspective:
- Abstract out vector models like w2v, deepwalk, prod2vec (https://labs.yahoo.com/publications/8480/e-commerce-your-inbox-product-recommendations-scale), protvec (http://arxiv.org/abs/1503.05140) and others
- i.e., have a common base class for the above, that implements hierarchical softmax, negative sampling, skipgram/cbow, adagrad, etc
- Not sure on the best design here
  - One option: have a base (abstract) model with most of the implementation, then extend for each implementation
  - Alternatively: make the base model concrete, and just provide different data sources, vocabulary creation objects, etc as required
- Overall: we don't want to implement and maintain separate implementations of huffman trees, HS, negative sampling etc for each type of model

Also: We should pay special attention to Spark and distributed learning here. Having all such models supporting spark out of the box would be fantastic.
Obviously there are complications around the eventual parameter server, but hopefully we can abstract that out for when we do implement the parameter server.

**Comment by raver119** [comment]
I've suggested that for standalone version, since for me it's easier to play with it on standalone, and standalone won't require distributed memory mechanics right now :)

But sure, as soon as standalone is working, there should be no problems porting it into Spark version.

And yes, i don't see additional code or separate implementations for each type of model, since all we need is unique objects with their frequencies known in advance.

I think that could be done with a small bit of refactoring. In example it could be done just making WeightLookupTable accepting not a VocabWords as arguments like it's now, but abstract SequenceElement, that requires existance and override of basic methods: equals, hashCode, getWordFrequency, nothing else. And this should already give the abitlity to go for sg/hs/huffman/whatever.

So, user will be able to write his own extension over abstract SequenceElement (he'll have VocabWord as example), and provide iterator for training Sequences. Nothing else should be required to make this work.

**Comment by agibsonccc** [comment]
I'd like to generalize this to deepwalk as well. Wec can have a concept of a "sequence" and a "sequence walker" that allows us to update embeddings wrt any context beyond words. I'd like to put that in to deeplearning4j-core. Let's start with the standalone version first.

**Comment by raver119** [comment]
Awesome, i'll take care of it then.

**Comment by raver119** [comment]
Implemented in current master, planned to be released with 3.8.
