### ISSUE TITLE
Is CUDA 11.0 supported?

### ISSUE THREAD

**Issue by jljljl** [deeplearning4j/deeplearning4j#9306]
Just a question if CUDA 11.0 supported. I saw it was with the 9.x, 10.0, 10.1, 10.2 i also saw 11.0 somewhere but can't find that now. Here is also CUDA 11.0 im pom.xml available. Does it works?

**Comment by treo** [comment]
At this moment, you can only use it with Snapshots. But it will be generally supported in the upcoming release. 

To see how to enable snapshots, see here: https://deeplearning4j.konduit.ai/config/config-snapshots

**Comment by jljljl** [comment]
@treo Thank you for your answer. Is here any chat/forum to talk about this project? I found some stuff to fix, implement and optimize, but if would be hard to post here.

**Comment by treo** [comment]
In general you should be asking questions like this here: https://community.konduit.ai/
