### ISSUE TITLE
Slow NN training with JavaFX

### ISSUE THREAD

**Issue by ChristopherGriswold** [deeplearning4j/deeplearning4j#9320]
#### Issue Description
When integrating dl4j into a JavaFX application, training a neural net is extremely slow when run on a non FX Application thread. Specifically when working with the TrainNews Text Classification example with a larger data set. I've tried using Executors.newSingleThreadExecutor() and a regular Runnable Thread. A PerformanceListener does indicate that there is a somewhat regular ETL of about 20ms.  I assume there is some kind of caching issue going on. Is there something I'm missing when it comes to having this run on a separate thread?

#### Version Information

* Deeplearning4j version : 1.0.0-beta7
* Native CPU
* Platform information (OS, etc) : Ubuntu 20.04.2 LTS
* OpenJDK 16
* JavaFX 16

#### Additional Information
FX Application thread: Minibatch=50 : 150 Samples/Sec
FX Application thread: Minibatch=500 : 250 Samples/Sec
Separate Thread: Minibatch=50 : 10 Samples/Sec
Separate Thread: Minibatch=500 : 60 Samples/Sec

- Tested with OpenJDK 11 and JavaFX 11 with same result.

**Comment by agibsonccc** [comment]
Maybe @johanvos has comments here. I would need more information to know what the deal could be. One thing you could try is using paralellwrapper which handles multi threaded neural network training and should handle the off thread cases as well. Depending on whether you're using cpu or gpu, OMP_NUM_THREADS environment variable can/should be set to 1 for multi threading.

**Comment by ChristopherGriswold** [comment]
@agibsonccc thanks for the reply. I am using CPU and have tried setting OMP_NUM_THREADS to 1 but didn't see any difference. Everything that I'm trying to do with dl4j is on a single thread. It's just that it runs fine on the JavaFX thread but slow on it's own separate thread. Using ParallelWrapper helped a lot. Thanks!

**Comment by johanvos** [comment]
That's interesting, and it seems counterintuitive. The JavaFX Application Thread is used for a number of things related to rendering, but can also be used for other work. Hence, I would expect that a dedicated thread is at least equally fast, and probably much faster.
One of the reasons might be that your thread somehow calls into the Scenegraph, which then requires access to the JavaFX Application Thread, and it might be waiting to get hold of that Thread. When you're running on the JavaFX Appthread already, you don't need to wait to get on that thread. It's fine if this happens every now and then, but it should not happen e.g. 100 times per second. 
It would be good to get some profile info about what that seperate thread is doing (e.g. is it mainly waiting for a lock, or is it using CPU/GPU?)

**Comment by agibsonccc** [comment]
@Iceybones  I'll close this if I don't see  a response in a week or so. There's nothing I can really do based on @johanvos 's comment. It appears we would just need to profile this individually. It's likely not an actual dl4j issue. Thanks @johanvos  for commenting as I don't have the background in javafx to know where to start guessing the problem.

**Comment by ChristopherGriswold** [comment]
I was doing one call to the JavaFX thread at the end of every iteration to post the score to the GUI but that's all. CPU usage stayed at 100%. My project is on a tight deadline and is to the point now now where it is working with ParallelWrapper and performing decently so I don't really want to revert it back to profile it further at the moment. I appreciate your guys help and quick responses. You can certainly close this issue as you see fit. Once I get some more time to dig deeper into the underlying issue, if I come up with any new information, I'll get back with you. Thanks again @johanvos and @agibsonccc .
