### ISSUE TITLE
Depthwise and separable convolutions almost do not work

### ISSUE THREAD

**Issue by jljljl** [deeplearning4j/deeplearning4j#9329]
Depthwise and separable convolutions are very slow on CUDA. Tested on multiple systems and looks like they are not optimized at all or maybe not implemented. Calculations with same shape may take 20 times more time in comparison to normal convolution.

Tested on dl4j examples MNIST convolution example by changing layers. Also tested on almost single layer neural network.

I guess they should take a lot less time than normal convolution.

**Comment by agibsonccc** [comment]
I'm closing this. Nothing is really reproducible here. If you can claim something more specific, like "here are some performance graphs, I think it should run xyz faster" or "here's some code that reproduces an edge case" that is actionable and worth discussing. This is too vague for us to do anything with.
