### ISSUE TITLE
NaN at meanNumber() for FLOAT16

### ISSUE THREAD

**Issue by jljljl** [deeplearning4j/deeplearning4j#9334]
Big arrays get NaN meanNumber(). Max size of array NaN happens is around 10000.

```
import org.nd4j.linalg.api.buffer.DataType;
import org.nd4j.linalg.factory.Nd4j;

public class NanTest
{

	public static void main(final String[ ] args)
	{
		final DataType dataType = DataType.FLOAT16;
		System.out.println(Nd4j.ones(dataType, 16, 1, 1, 1).meanNumber());
		System.out.println(Nd4j.ones(dataType, 16, 1, 100, 100).meanNumber());
		System.out.println(Nd4j.ones(dataType, 16, 1, 1000, 1000).meanNumber());
	}

}
```

Output is

```
1.0
NaN
NaN
```
Version
```
		<dl4j-master.version>1.0.0-M1</dl4j-master.version>
		<nd4j.backend>nd4j-cuda-11.2</nd4j.backend>
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>cuda-platform-redist</artifactId>
			<version>11.2-8.1-1.5.5</version>
		</dependency>
```

**Comment by quickwritereader** [comment]
I confirm this. reduce_mean handled by ordinary sum()/n [Mean impl](https://github.com/eclipse/deeplearning4j/blob/master/libnd4j/include/ops/ops.h#L3000-L3026). not a numerical_stable one.
afaik we have a better alternative [summary stats](https://github.com/eclipse/deeplearning4j/blob/fc735d30023981ebbb0fafa55ea9520ec44292e0/libnd4j/include/loops/summarystatsreduce.h#L230-L269) but it's used for variance. We can implement mean the same way by using summary stats. Or we can re-write mean (as summary stats intended to get variance and std_deviation).
(@agibsonccc  Besides, I optimized summary stats' variance and std_deviation ~~for auto-vectorization~~ but it never was merged )
 
bfloat16 behaved a lot better in this test case

**Comment by agibsonccc** [comment]
@quickwritereader mind resubmitting a cleaned up draft of that?

**Comment by quickwritereader** [comment]
ok so instead of re-implementing the mean with a running average algo that could give the precise result especially in this case I just used float type for aggregation to solve these types of overflow/accuracy errors in float16, as there are other similar reduction operations. so it is a quick proper fix for now.

**Comment by quickwritereader** [comment]
#9380
