### ISSUE TITLE
Missing information and broken links for visualization documentation

### ISSUE THREAD

**Issue by lonerzzz** [deeplearning4j/deeplearning4j#9337]
#### Issue Description

The documentation for using the UI is missing information and has broken links. The following page:

https://deeplearning4j.konduit.ai/tuning-and-training/visualization

refers to net.setListeners in the example code for visualization but does not define the "net" object or provide a reference to setting it up

Below the example code, the link in the following text both have broken links to github:

Example: See a UI example here
The full set of UI examples are available here.

**Comment by agibsonccc** [comment]
Addressed here: https://github.com/KonduitAI/deeplearning4j-gitbook-sync/commit/9a7bc621c1d1ad22efe6cd32be82393b8b9135b6

**Comment by lonerzzz** [comment]
Thanks for the first part of the fix. I had also mentioned the broken links above:

"Below the example code, the link in the following text both have broken links to github:

Example: See a UI example here
The full set of UI examples are available here."
