### ISSUE TITLE
Optimized Dimensionality Reduction Libraries for DL4J direct use

### ISSUE THREAD

**Issue by eix128** [deeplearning4j/deeplearning4j#9339]
Hi , it would be good to add Dimensionaly Reduction Library set for DL4J
Here is TSNE:
https://www.codota.com/web/assistant/code/rs/5c66cb581095a50001e12f6e#L99

UMAP can be get from:
https://github.com/haifengl/smile

These could be optimized for Cuda on DL4J with help ND4j

Manifold Learning: IsoMap, LLE, Laplacian Eigenmap, t-SNE, UMAP, PCA, Kernel PCA, Probabilistic PCA, GHA, Random Projection, ICA.

**Comment by agibsonccc** [comment]
@eix128  actually we did have this for years and we decided it was better to just focus the library and scope it down.  You're welcome to help maintain a 3rd party version of this if you like, but we only have so much bandwidth. Just supporting the interop from different frameworks and optimizing our packaging/c++ is enough of our time.
