### ISSUE TITLE
Please add explanation of bottom left visualization overview details

### ISSUE THREAD

**Issue by lonerzzz** [deeplearning4j/deeplearning4j#9345]
#### Issue Description

For the visulization overview section (page https://deeplearning4j.konduit.ai/tuning-and-training/visualization#deeplearning-4-j-ui-the-overview-page), the four sections of the page are listed.

Unfortunately, for the entry "Bottom left: Ratio of parameters to updates (by layer) for all network weights vs. iteration", the meaning of the information is not explained. I have attempted to look at what this means but have seen no details in other documentation to allow me to interpret what I see on the chart.

- Please add information on what this chart means and what upward and downward trends of the plots mean.

**Comment by printomi** [comment]
Hi @lonerzzz ,
Let me explain that.
Training updates the parameters from iteration to iteration. "Ratio of parameters to updates (by layer)" tells how much the parameters of each layer change during training.
Parameters are expected to converge to an optimal set of values, decreasing the parameter update ratio meaning a downward trend of the plot.
An upward trend means that the training accelerates, the parameters change more and more. An overall upward trend is unwanted, and calls for hyperparameter tuning.

**Comment by printomi** [comment]
What I wrote is not specific to DL4J, it is just how neural networks work. If you have more questions, please, use the community forum instead of GH issues:
https://community.konduit.ai/
