### ISSUE TITLE
M1: Parameters of Keras MaxPooling1D layer are incorrectly read

### ISSUE THREAD

**Issue by DavidHuebner** [deeplearning4j/deeplearning4j#9349]
#### Issue Description

I trained a model using Tensorflow/Keras version 2.4.1 in Python. This model contains a MaxPooling1D layer. I then saved the model as the (default) .hdf5 file. Loading this file in Keras and saving its config as json, reveals the following layer:

``` json
{
  "class_name": "MaxPooling1D",
  "config": {
      "name": "max_pooling1d_3",
      "trainable": true,
      "dtype": "float32",
      "strides": [
          836
      ],
      "pool_size": [
          836
      ],
      "padding": "valid",
      "data_format": "channels_last"
  },
  "name": "max_pooling1d_3",
  "inbound_nodes": [
      [
          [
              "conv1d_3",
              0,
              0,
              {}
          ]
      ]
  ]
},
```
Please note that the **data_format** is set to "channels_last" which is the default value in Keras. This corresponds to NHWC. The stride is loaded as `(836,)` in Keras - a 1-tuple holding only the value (836). 

If I now load the model in 1.0.0-M1 using `importKerasModelAndWeights()`, this specific layer is loaded as a `Subsampling1DLayer`. Unfortunately, the parameter values are incorrectly parsed. The `Cnn2dDataFormat` is set to `NCHW`. The stride is loaded as `[836,2]` which leads to incorrect dimensions in the following layer. I believe that `[836,1]` is the correct value for the stride.

When I overwrite these two parameter values in my loaded network, then everything runs as expected.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-M1
* Tensorflow version 2.4.1 (same error exists for models trained in Tensorflow 1.14)
* Platform information: Ubuntu 20.04

**Comment by agibsonccc** [comment]
@DavidHuebner this looks like it'll be a simple fix. Do you mind if I get a complete configuration from you? Ideally it's something I can just import and run. What will happen then, is I will run and reproduce this, figure out a general fix and if anything else is applicable, create a test case out of this to prevent regressions and publish a fix.

**Comment by DavidHuebner** [comment]
Thanks for the prompt reply. I attached a very simple model.hdf5 in the attached [model.zip](https://github.com/eclipse/deeplearning4j/files/6610401/model.zip) with a single MaxPooling1D layer. The stride is now 5 (not 836 as above). Below is the code to load the model and extract the relevant parameters.

``` java
package de.averbis.textanalysis.resources.dl4jdocumentclassifierresource;

import java.io.IOException;

import org.deeplearning4j.nn.api.Layer;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.layers.Subsampling1DLayer;
import org.deeplearning4j.nn.graph.ComputationGraph;
import org.deeplearning4j.nn.modelimport.keras.KerasModelImport;
import org.deeplearning4j.nn.modelimport.keras.exceptions.InvalidKerasConfigurationException;
import org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException;

public class MaxpoolLoadingTest {

	public static void main(String[] args) throws IOException,
			UnsupportedKerasConfigurationException, InvalidKerasConfigurationException {

		ComputationGraph model = KerasModelImport
				.importKerasModelAndWeights("src/itest/resources/model.hdf5");
		for (Layer layer : model.getLayers()) {
			NeuralNetConfiguration conf = layer.conf();
			if (conf != null) {
				org.deeplearning4j.nn.conf.layers.Layer confLayer = conf.getLayer();
				if (confLayer instanceof Subsampling1DLayer) {
					Subsampling1DLayer maxPoolLayer = (Subsampling1DLayer) confLayer;
					System.out.println(maxPoolLayer.getCnn2dDataFormat()); // Is NCHW, should be NHWC
					int[] stride = maxPoolLayer.getStride();
					System.out.println(stride[1]); // Should be 1, not 2
				}
			}
		}
	}
}


```

**Comment by agibsonccc** [comment]
@DavidHuebner thanks for the quick test case, here's the PR https://github.com/eclipse/deeplearning4j/pull/9353 - it was a quick fix. Just  missing propagation of the 1d version of this to the 2d. This was missed when doing the NWHC update. We actually didn't support configuration of the channels till a little while ago.
