### ISSUE TITLE
Huber Loss only works with double

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#9375]
#### Issue Description
Huber Loss Grad applies tArg wrong causing:
```
NDArray::applyScalarArr BoolOps: this dtype: [5]; scalar dtype: [6]
o.n.l.c.n.o.NativeOpExecutioner - Failed to execute op huber_loss_grad. Attempted to execute with 3 inputs, 3 outputs, 1 targs,0 bargs and 1 iargs. Inputs: [(FLOAT,[1,2],c), (FLOAT,[],c), (FLOAT,[1,2],c)]. Outputs: [(FLOAT,[1,2],c), (FLOAT,[],c), (FLOAT,[1,2],c)]. tArgs: [1.0]. iArgs: [3]. bArgs: -. Input var names: [layerInput, sd_var, labels]. Output var names: [layerInput-grad, sd_var-grad, labels-grad] - Please see above message (printed out from c++) for a possible cause of error.

```
referencing
https://community.konduit.ai/t/huber-loss-function-not-working/1445/6

A data type cast needs to happen for the tArg when a float data type is used (which is the default in dl4j)

Please describe our issue, along with:
- expected behavior
- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version Snapshots
* Platform information (OS, etc) any
* CUDA version, if used
* NVIDIA driver version, if in use

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by quickwritereader** [comment]
#9385
