### ISSUE TITLE
A simple bug in org.deeplearning4j.earlystopping.scorecalc.ROCScoreCalculator.ROCScoreCalculator.

### ISSUE THREAD

**Issue by baedaron** [deeplearning4j/deeplearning4j#9391]
#### Issue Description

    @Override
    protected double finalScore(IEvaluation eval) {
        switch (type){
            case ROC:
                ROC r = (ROC)eval;
                return metric == Metric.AUC ? r.calculateAUC() : r.calculateAUCPR();
            case BINARY:
                ROCBinary r2 = (ROCBinary) eval;
               //*** I am new in dl4j and deep learning but think below code line is a bug.
              //*** it should be 
              //*** return metric == Metric.AUC ? r2.calculateAverageAuc() : r2.calculateAverageAUCPR();
              //*** Am I right?
                return metric == Metric.AUC ? r2.calculateAverageAuc() : r2.calculateAverageAuc();
            case MULTICLASS:
                ROCMultiClass r3 = (ROCMultiClass)eval;
                return metric == Metric.AUC ? r3.calculateAverageAUC() : r3.calculateAverageAUCPR();
            default:
                throw new IllegalStateException("Unknown type: " + type);
        }
    }

#### Version Information

current snapshot

**Comment by agibsonccc** [comment]
@baedaron fixed here: https://github.com/eclipse/deeplearning4j/pull/9401 great find! pending review this will be merged and pushed to snapshots. Thanks for the report!
