### ISSUE TITLE
INDArray.match(Number, Condition) not returning expected results. 

### ISSUE THREAD

**Issue by wcneill** [deeplearning4j/deeplearning4j#9393]
**Expected behavior:**
`array.match(n, Conditions.equals())` should return a mask such that each entry `mask.get(i)` is `array[i] == n`

**Encountered behavior:**

the mask contains incorrect booleans for anything but `n=0`. 

#### Version Information

Please indicate relevant versions, including, if relevant:

* nd4j version beta 7. 
* Platform information (OS, etc): Windows 10 Enterprise

#### To reproduce: 

The following code will reproduce the error for `i > 0`:

        int[] assignments = {0,0,0,1,0,2,2};
        int[] indexes     = {0,1,2,3,4,5,7};

        INDArray asarray = Nd4j.createFromArray(assignments);
        INDArray idxarray = Nd4j.createFromArray(indexes);

        int i = 1; 
        INDArray mask = asarray.match(i, Conditions.equals());

- `i=1` results in the mask ` [ false, false, false, true, false, true, true]`
- `i=2` results in the mask ` [ false, false, false, false, false, false, false]`

There seem to be similar problems with `notEquals()` and `notEquals(someNumber)`. Everything is inverted or totally incorrect. 

#### Contributing

I would love to contribute, but might need guidance.

**Comment by agibsonccc** [comment]
@wcneill fixed the issue here:
https://github.com/eclipse/deeplearning4j/pull/9400
, thanks for reporting:.
