### ISSUE TITLE
Issues importing Keras Model from python to Java due to Conv3DTranspose layer

### ISSUE THREAD

**Issue by KhioneusNevula** [deeplearning4j/deeplearning4j#9397]
#### Issue Description
I was attempting to import a model I had saved from Python using Keras into DL4J in Java.

Expected Behavior: 
KerasModelImport.importKerasSequentialModelAndWeights would appropriately import my saved model which I previously wrote and saved in python without issues.

Encountered Behavior:
The method ended up throwing an error because it did not recognize the "Conv3DTranspose" layer. Conv3DTranspose is the python Keras name for a Transposed Convolution or Deconvolution layer.

#### Version Information

* Deeplearning4j version: deeplearning4j-core:1.0.0-beta7
* Platform information (OS, etc): Minecraft Windows 10 Home

#### Additional Information

https://gist.github.com/KhioneusNevula/c90d2c1684cd82a0f01f7cbce9e488a8 (crash report)

**Comment by marquies** [comment]
Hi, have you tried with version 1.0.0-M1.1 ?

**Comment by KhioneusNevula** [comment]
No, I have not. Can you tell me how to do a gradle download for it?

**Comment by agibsonccc** [comment]
@marquies Conv3DTranspose is not in the new release unfortunately, we will have to implement it. For now only a custom layer will work.  We'll get this in to the next release and have snapshots

@KhioneusNevula  just change your version to 1.0.0-M1.1

**Comment by KhioneusNevula** [comment]
@agibsonccc There's an existing Deconvolution3D layer for DL4J. Is there any way to make a custom layer that just uses the Deconvolution3D layer's functionality? Deconvolution3D is I believe equivalent to Conv3DTranspose

**Comment by agibsonccc** [comment]
@KhioneusNevula indeed there is.  Let me clarify something:
Generally if you need to implement a custom layer, you would do that with samediff. It has automatic differentiation and would allow you to just map ops line by line from an existing implementation.

In order to use the dl4j version,  when I say "implement" it basically means creating a KerasLayer. You can see those here:
https://github.com/eclipse/deeplearning4j/tree/master/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/layers/convolutional


We'll have to do something similar with this to make it work. It wouldn't be that bad to do, it will take a bit to properly test though. That's why I think we can get it in the next release pretty quick. If you would like to take a shot at this and supply a test case + help with feedback, I'd be happy to guide you through the process.

**Comment by KhioneusNevula** [comment]
Thank you!

**Comment by agibsonccc** [comment]
@KhioneusNevula  I'm taking a look at this, do you have a reproducer model for me so I can double check the results?
Edit: I added the work in progress pull request here: https://github.com/eclipse/deeplearning4j/pull/9399 this handles the basic ingredients needed to get import in there. I just need your test case and I'll make sure it works against different use cases.

**Comment by KhioneusNevula** [comment]
@agibsoncc I'm very new to using machine learning and GitHub so I'm not super familiar with what a "reproducer model" is.

**Comment by agibsonccc** [comment]
@KhioneusNevula a reproducer in software (especially open source) helps a library author reproduce the conditions under which something isn't working properly.

A model is just a machine learning model, in this case an exact configuration + some weights you save.
This could be anything that you create in keras and call save(..) on.

Usually to go with that I would want a sample numpy array that you would put in to the model for predict(..) - the reason I want this specifically from the issue author is to ensure that everything is resolved as expected and the issue author gets what they need out of the fix.

Hopefully that makes sense!

**Comment by KhioneusNevula** [comment]
Hi,
I am the issue author; I tried storing the model in various ways.
I used both json (I'll send as zip) and h5.
[h5 file](https://drive.google.com/file/d/1a4hb7cqygzotErIpjmmwwYIBX9M58v4Q/view?usp=sharing)
[json file with h5 weights file in zip folder](https://drive.google.com/file/d/1jyaBZAvU9Hy8oEK5u4ZQHuGDytprUkd2/view?usp=sharing)

**Comment by agibsonccc** [comment]
@KhioneusNevula yes I'm aware :) I was speaking in general terms so you understood that this was a standard practice for any library you probably report an issue to. I appreciate you getting back to me and I will take a look with this. Thanks!

**Comment by agibsonccc** [comment]
@KhioneusNevula how exactly did you save your model? I keep getting errors when trying to load it. I'm using tf.keras 2.5.0.

**Comment by KhioneusNevula** [comment]
I used keras 2.4.3 and called the "save" function on the model

**Comment by agibsonccc** [comment]
@KhioneusNevula just confirming I was able to load the model with your given configuration. I just need to add a test for NCDHW format in addition to your test case which is channels last to ensure we cover all valid cases and we should be good to go. Thanks for the test case!

**Comment by KhioneusNevula** [comment]
Thank you so much for your help!

**Comment by KhioneusNevula** [comment]
@agibsonccc How would I access the changes you made?

**Comment by agibsonccc** [comment]
@KhioneusNevula it should be available on snapshots https://deeplearning4j.konduit.ai/multi-project/explanation/snapshots
