### ISSUE TITLE
ParagraphVectors loosing labels when they occur in trained text

### ISSUE THREAD

**Issue by robert-E** [deeplearning4j/deeplearning4j#9404]
#### Issue Description

I train a ParagraphVectors with LabelledDocuments and a SimpleLabelAwareIterator. Each document has one of the following labels: sport, tech, business. So after training the ParagraphVectors i would expect that calling vector.getLabelsSource().getLabels() returns a list containing those 3 labels - and most of the time it does.
But if ParagraphVectors sees a document containing one of those labels within its content before it saw that label as a document's label the returned list will not contain that label.
E.g. the first document to learn is labelled with 'business' and contains the word 'tech' ==> 'tech' will not be marked as label and therefore will not be in the returned list.

I guess the problem is caused by line 204 in method org.deeplearning4j.models.word2vec.wordstore.VocabConstructor.processDocument(AbstractCache<T>, Sequence<T>, AtomicLong, AtomicLong) where label.markAsLabel(true) is not called if the label is already part of the cache.

#### Version Information

* Deeplearning4j version: 1.0.0-M1 (as well as 1.0.0-beta7)
* Platform information: Windows 10, Intel I5 CPU, Java 8

**Comment by agibsonccc** [comment]
@robert-E sorry prepping for the next release and just getting to some issues. If you don't hear from me, please reping me in the future.  Ideally, we could either guide you on a pull request or you could give us some end to end code to run to make this easier. Sometimes we look at issues, but don't respond if they're not very actionable. Apologies for that. If you can get us a sample project, we can take a look at a fix. Thanks!

**Comment by robert-E** [comment]
Sorry for my late reply but i could not respond earlier to your request.

I have now written a small JUnit 5 test that will show the problem. Note that in the 'failingData' each text contains the label of one of the other text, e.g. the text for label 'business' contains the string 'sport' which is the label of another text.

I have attached that test file here (i needed to change its extension from '.java' to '.txt' otherwise adding the file was not allowed).

[ParagraphVectorsTest.txt](https://github.com/eclipse/deeplearning4j/files/7070252/ParagraphVectorsTest.txt)

br,
Robert.

**Comment by agibsonccc** [comment]
Checked this with the latest version. Doesn't appear to be a problem as of M2.1. Closing.
