### ISSUE TITLE
Canova support for CSV with double quotes

### ISSUE THREAD

**Issue by HermanBovens** [deeplearning4j/deeplearning4j#941]
In CSV (or TSV) files, when a value may contain the delimiter character, the value is often surrounded by double quotes.

Canova currently splits the input line even if the delimiter appears within a double quoted value.  

Use cases are nominal values containing commas, and numeric values with commas as thousands separator.

**Comment by raver119** [comment]
Could you please provide more info? Which loader you're using?

**Comment by HermanBovens** [comment]
I'm using LineInputFormat as in the example at
https://github.com/deeplearning4j/Canova/wiki/Vectorizing-CSV-Data-With-Canova-and-the-CLI.
As in the example, the schema uses a comma as delimiter.  A value like
"65,536" is treated as 2 columns.

Is any other info needed?

**Comment by mkocikowski** [comment]
Hey, since this is a Canova issue, I 'moved' it there: https://github.com/deeplearning4j/Canova/issues/101  Let's continue the conversation there, if need be.
