### ISSUE TITLE
Removed author tag

### ISSUE THREAD

**Issue by ionspin** [deeplearning4j/deeplearning4j#9414]
#### Issue Description

Author tag removed from my contribution.

#### Version Information

Please indicate relevant versions, including, if relevant:

Version with attribution:
https://github.com/eclipse/deeplearning4j/blob/65c6a9a42e4e14fe98ccb99a3015d74b7072ae50/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/layers/FrozenLayerWithBackprop.java

Version without attribution:
https://github.com/eclipse/deeplearning4j/blob/4766032444de8e0c2c3389270576bb6e7c466211/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/layers/FrozenLayerWithBackprop.java

#### Additional Information

I think the author tag was removed by mistake when updating copyright notices, and since I was quite proud of this little contribution to DL4J, I'd like to have it back.

**Comment by agibsonccc** [comment]
@ionspin please feel free to submit a pull request and we'll be happy to get it back in there. Apologies for the mistake there.

**Comment by agibsonccc** [comment]
@ionspin just a ping here, still happy to accept the pull request. Thanks again for mentioning this!
