### ISSUE TITLE
Is clustering package removed from  1.0.0-M1.1 ?

### ISSUE THREAD

**Issue by catapop84** [deeplearning4j/deeplearning4j#9415]
Please describe our issue, along with:
I'm trying to use `KMeansClustering` but it looks like it was removed from `deeplearning4j-core` ,version 1.0.0-M1.1
Was it moved somewhere else?

**Comment by agibsonccc** [comment]
@catapop84 yes it was. None of those packages were really being maintained and were not core to the framework. The release notes are here:  https://deeplearning4j.konduit.ai/v/en-1.0.0-m1.1/release-notes Check both M1 and M1.1 - the decision was made to remove old code to ease maintenance and to avoid confusing users about which modules are or are not maintained.

That contribution was done quite a few years ago and was relatively well done, but it wasn't touched by the core committers much over the years. Anything without dedicated maintenance was removed.

If you would like to continue to use that package, please feel free to continue to use the old version. You can find the branch for that here: https://github.com/eclipse/deeplearning4j/tree/release/1.0.0-beta7
