### ISSUE TITLE
Cudnn layer helper missing during inference

### ISSUE THREAD

**Issue by abcxys** [deeplearning4j/deeplearning4j#9424]
#### Issue Description

Import a python-keras trained UNet model, do the inference with dl4j, using CUDA backend
- use cudnn by default
- cudnn helpers not initialized

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-M1.1
* Platform information (OS, etc): Windows 10
* CUDA version, if used: 11.2
* NVIDIA driver version, if in use: NVIDIA 461.40

##### Test code in dl4j-examples project:
`String modelPath = "D:\\unet_0803.h5";`
`ComputationGraph model = KerasModelImport.importKerasModelAndWeights(modelPath, false);`

`BufferedImage testTiffImg = ImageIO.read(Files.newInputStream(Paths.get("D:\\input0.tiff")));`
`BufferedImage testTiffImgType5 = new BufferedImage(testTiffImg.getWidth(), testTiffImg.getHeight(), BufferedImage.TYPE_3BYTE_BGR);`
`Graphics2D g = testTiffImgType5.createGraphics();`
`g.drawImage(testTiffImg, 0, 0, testTiffImg.getWidth(), testTiffImg.getHeight(), null);`
`g.dispose();`
`NativeImageLoader loader = new NativeImageLoader(512, 512, 3);`
`INDArray imageNative = loader.asMatrix(testTiffImgType5).permute(0,2,3,1);`
			
`imageNative = imageNative.divi(255f);`
`INDArray[] output = model.output(imageNative);`
`LayerHelper h = model.getLayer(0).getHelper();`
`System.out.println("Layer helper: " + (h == null ? null : h.getClass().getName()));`

Log:
o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for linear algebra: 32
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [16]; Memory: [30.0GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
o.n.l.j.JCublasBackend - ND4J CUDA build version: 11.2.142
o.n.l.j.JCublasBackend - CUDA device 0: [GeForce RTX 3070]; cc: [8.6]; Total memory: [8589934592]
o.n.l.j.JCublasBackend - Backend build information:
 MSVC: 192930038
STD version: 201703L
CUDA: 11.2.142
DEFAULT_ENGINE: samediff::ENGINE_CUDA
HAVE_FLATBUFFERS
o.d.n.g.ComputationGraph - Starting ComputationGraph with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]

Layer helper: null

**Comment by quickwritereader** [comment]
your log shows that you are not using Cudnn as it does not utput HAVE_CUDNN.
besides, the system picks cudnn underhood when it meets the op requirements. we are going to add proper debug logs for that.
I believe pom  classifier should be linux-x86_64-cuda-11.2-cudnn

**Comment by agibsonccc** [comment]
@abcxys we don't have cudnn by default. You have to add a cudnn specific dependency. Please see: https://deeplearning4j.konduit.ai/v/en-1.0.0-m1/multi-project-multi-project/explanation/configuration/backends/cudnn

Sometimes people prefer not to have cudnn due to binary size, so we let users make the trade off.

**Comment by abcxys** [comment]
> your log shows that you are not using Cudnn as it does not utput HAVE_CUDNN.
> besides, the system picks cudnn underhood when it meets the op requirements. we are going to add proper debug logs for that.
> I believe pom classifier should be linux-x86_64-cuda-11.2-cudnn

Thanks for your reply! I actually did add that dependency in maven, but the there is still no "HAVE_CUDNN" nor "CudnnConvolutionHelper" printed. I post the pom.xml file here, do you have any idea on what's wrong?
[pom.xml.txt](https://github.com/eclipse/deeplearning4j/files/6996421/pom.xml.txt)

**Comment by abcxys** [comment]
I got the backend to load CUDNN finally. But the imported models still could not initialize cudnn helpers in convolution layers.
The backend log now reads:
` MSVC: 192930038`
`STD version: 201703L`
`CUDA: 11.2.142`
`DEFAULT_ENGINE: samediff::ENGINE_CUDA`
`HAVE_FLATBUFFERS`
`HAVE_CUDNN`

I read into the code of `org.deeplearning4j.nn.layers.convolution` and noticed that the layer would initialize helper with `HelperUtils.createHelper`. So I looked into `org.deeplearning4j.nn.layers.HelperUtils`. 

### First issue is at line 58 of `HelperUtils`
with `org.deeplearning4j.common.config.DL4JSystemProperties.HELPER_DISABLE_DEFAULT_VALUE = 'true'`, that `if` would never pass through. So I changed that system property manually to `false`.

### Second issue at line 67 of `HelperUtils`
the utils tries to `createNewInstance("org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper", class<T> org.deeplearning4j.nn.layers.convolution.ConvolutionHelper, new Object[]{DataType.FLOAT}`


This attempt fails with following exception:
`java.lang.NoSuchMethodException: org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper.<init>([Ljava.lang.Object;)`
	`at java.base/java.lang.Class.getConstructor0(Class.java:3427)`
	`at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2631)`
	`at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:108)`
	`at org.deeplearning4j.common.config.DL4JClassLoading.createNewInstance(DL4JClassLoading.java:94)`
	`at org.deeplearning4j.nn.layers.HelperUtils.createHelper(HelperUtils.java:67)`

So what should I do the get through the `createNewInstance` part? @agibsonccc @quickwritereader 
My understanding for this focus on `line 107` of `org.deeplearning4j.common.config.DL4JClassLoading`, **`org.deeplearning4j.cuda.convolution.CudnnConvolutionHelper`** is casted to **`org.deeplearning4j.nn.layers.convolution.ConvolutionHelper`,** that is a **class** casted to **interface,** which counters the purpose of `asSubclass` and also that interface does not have a declared constructor.
