### ISSUE TITLE
CpuNativeRandom is not quite random

### ISSUE THREAD

**Issue by akhodakivskiy** [deeplearning4j/deeplearning4j#9429]
The following code `Nd4j.getRandomFactory.getNewRandomInstance(seed).nextInt(limit)` does not seem to generate all possible numbers less than or equal to `limit` for some values of `limit`, e.g. 320. Consider the following Scala code

``` Scala
    val rnd = Nd4j.getRandomFactory.getNewRandomInstance(123)

    val limit = 320 // argument for nextInt
    val m = 1000000 // how many times to call nextInt(n)

    // here we generate `m` random Integers under `limit`
    val samples: Seq[Int] = Range(0, m).map { _ =>
      rnd.nextInt(limit)
    }.distinct.sorted

    // turns out there are only 225 distinct values, whereas expecting 320
    print(samples.size) // 225
```

If we generate 1000000 random numbers under `limit=320` we will find out that there are only 225 distinct values. Other values of `limit` don't exhibit this behavior. E.g. with `limit=321` there will be 321 distinct numbers generated.

Here are more values for `limit` that exhibit this behavior:

```
limit, number of distinct random numbers returned by nextInt(limit)
192, 135
320, 225
384, 192
448, 315
576, 405
640, 320
704, 495
768, 384
832, 585
896, 448
960, 675
```

It appears that this bug originates in [libnd4j's helper_generator.h](https://github.com/eclipse/deeplearning4j/blob/master/libnd4j/include/helpers/helper_generator.h#L201-L232)

This bug affects some of the code related to drawing random samples from a set. [In particular `rl4j`'s experience replay implementation](https://github.com/eclipse/deeplearning4j/blob/master/rl4j/rl4j-core/src/main/java/org/deeplearning4j/rl4j/learning/sync/ExpReplay.java#L54-L60) where it gets stuck in infinite loop trying to draw 300 (the batch size) samples from initial set of 320:

* Deeplearning4j versions 1.0.0-M1 & 1.0.0-M1.1
* Ubuntu 20, MacOS (CPU-independent)

**Comment by quickwritereader** [comment]
I confirm the issue

**Comment by quickwritereader** [comment]
thanks for the reproduce code. I wrote in java and printed output numbers:
more details of the issue :
https://gist.github.com/quickwritereader/94f6c261ad285817fa85e9fe3f41e687

**Comment by quickwritereader** [comment]
another workaround was just making seed value even

**Comment by quickwritereader** [comment]
### Workaround 1:
use ` org.nd4j.linalg.api.rng.DefaultRandom`  when initializing other classes that expect Random
### Workaround 2:
set default random generator to `"DefaultRandom"` **before any calls**
`System.setProperty("random", org.nd4j.linalg.api.rng.DefaultRandom.class.getName());`
### Workaround 3:
set seed value to even number. `seed & -2`
### Workaround 4 if you are calling it:
`rnd.nextInt(rndLimit | 1) % rndLimit`

**Comment by quickwritereader** [comment]
#9459  fixes this problem as well
