### ISSUE TITLE
Cannot reproduce counts in confusion matrix

### ISSUE THREAD

**Issue by moberc** [deeplearning4j/deeplearning4j#9438]
#### Issue Description

I have created a simple RNN for binary classification.
After training I compute confusion matrix:
        net.fit(trainDataIter, nEpochs);
        Evaluation eval = net.evaluate(testDataIter);
        LOGGER.info(eval.stats());

Then I compute predicted values using testIter and re-compute confusion matrix in Excel.
My Excel results are close, but they do not match dl4j confusion matrix.
I have debugged your code - predicted vectors do not match mine.
I am doing something wrong?

My computations:
        //Init rrnTimeStemp with train data and predict test data
        trainDataIter.reset();
        net.rnnClearPreviousState();
        while (trainDataIter.hasNext()) {
            DataSet t = trainDataIter.next();
            net.rnnTimeStep(t.getFeatures());
        }

        // predictions using test data
        int batch = 0;
        double[] results = new double[testSize];
        testDataIter.reset();
        while (testDataIter.hasNext()) {

        	DataSet t = testDataIter.next();
        	INDArray predicted  = net.rnnTimeStep(t.getFeatures());   
        	for (int i=0; i<batchSize; i++) {
        		results[batch*batchSize + i] =  predicted.getDouble(i, 0, numberOfTimesteps-1); 
        	}
        	batch++;
         }

#### Version Information
1.0.0-M1.1
Windows 10
no graphics card

* Deeplearning4j version
* Platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by agibsonccc** [comment]
@moberc could you please direct this over to the forums? https://community.konduit.ai - when you post there please post an end to end reproducible example, including a neural net with associated input. Thanks!

**Comment by moberc** [comment]
Hi,

I do have a reproduceable test case.
I have just logged in to konduit , but I do not see an easy way to attach my source code and a small data file.
What’s the best way to do that?

Thanks,
  Margaret
