### ISSUE TITLE
object contents redundancy issue

### ISSUE THREAD

**Issue by anonymousemberxxx** [deeplearning4j/deeplearning4j#9439]
Hello,

I'm building a Java object contents redundancy profiler. By testing deeplearning4j source code with my profiler, I found a code snippet that involved with object contents redundancy (ArrayOptionsHelper.java):

```
public static ArrayType arrayType(long[] shapeInfo) {
        val opt = Shape.options(shapeInfo);

        if (hasBitSet(opt, ATYPE_SPARSE_BIT))
            return ArrayType.SPARSE;
        else if (hasBitSet(opt, ATYPE_COMPRESSED_BIT))
            return ArrayType.COMPRESSED;
        else if (hasBitSet(opt, ATYPE_EMPTY_BIT))
            return ArrayType.EMPTY;
        else
            return ArrayType.DENSE;
    }
```
In above code, my profiler detected that the method `arrayType` is called in iterations and array `shapeInfo`'s contents (every element in this array) often keep the same as the last iteration. Do you consider to reuse the array `shapeInfo` in iterations if it's unchanged? Then the method `arrayType` might just return the same ArrayType as the last iteration.

**Comment by agibsonccc** [comment]
@anonymousemberxxx this just translates what is largely an int in a long array to an enum. We've ported most of this code to c++, so it's not really worth optimizing this particular case. Closing.
