### ISSUE TITLE
Concurrently moving inference results to JVM eats up device memory?

### ISSUE THREAD

**Issue by Fredrik-M** [deeplearning4j/deeplearning4j#9458]
When I run inference and delegate processing of the results to a threadpool executor, I notice that GPU memory usage scales with the number of threads. I can reproduce this by running the following code:
```
        ThreadPoolExecutor pool = (ThreadPoolExecutor) Executors.newFixedThreadPool(400);
        INDArray in = Nd4j.rand(1, shape[0], shape[1], shape[2]);

        while(true) {
            INDArray[] out = network.output(in);
            pool.submit(
                    () -> out[0].toFloatVector()
            );
        }
```
This makes my GPU memory usage go to 99%, whereas calling `toFloatVector()` directly in the same thread does not use any more memory than just running inference. Reducing the number of threads in the pool reduces the the memory usage.

I'm having trouble understanding exactly what is going on here, perhaps someone can shed some light on this?

#### Version Information

```
<dependency>
      <groupId>org.nd4j</groupId>
      <artifactId>nd4j-cuda-11.0</artifactId>
      <version>1.0.0-M1.1</version>
      <scope>runtime</scope>
</dependency>
<dependency>
      <groupId>org.nd4j</groupId>
      <artifactId>nd4j-cuda-11.0</artifactId>
      <version>1.0.0-M1.1</version>
      <classifier>windows-x86_64-cudnn</classifier>
      <scope>runtime</scope>
</dependency>
<dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>cuda-platform-redist</artifactId>
      <version>11.0-8.0-1.5.4</version>
</dependency>
```

**Comment by agibsonccc** [comment]
@Fredrik-M  I would consider using parallelinference or parallelwrapper:
https://deeplearning4j.konduit.ai/multi-project/explanation/configuration/memory/workspaces#parallelwrapper-and-parallelinference

 which implements this threadpool concept for you.  For gpus,  understand 2 things: https://deeplearning4j.konduit.ai/multi-project/explanation/configuration/memory/workspaces#what-are-workspaces

and the fact that we allocate memory on both cpu and gpu simultaneously and keep the buffers in sync transparently.
Regarding your memory management, depending on your model, you can increase the frequency of which you trigger GC: https://deeplearning4j.konduit.ai/multi-project/explanation/configuration/memory/workspaces#garbage-collector

If this doesn't solve your issue, please post over on the community forums: https://community.konduit.ai - we try to keep the issue tracker for bugs.
