### ISSUE TITLE
Memory leak when running CUDA back-end

### ISSUE THREAD

**Issue by gareththegeek** [deeplearning4j/deeplearning4j#946]
I am getting a memory leak when using `nd4j-jcublas-7.5` as the back-end.  The problem is not present when using the `n4dj-java` library.

I am running `v0.4-rc3.4` of deeplearning4j and `v0.4-rc3.5` of nd4j on Windows x64 using 64bit Java 1.8.

The Java managed heap size consistently remains less than 700mb, but memory usage of javaw.exe rapidly grows until all system memory is consumed (32Gb in 30 minutes).

This issue is reproducable when using the Iris example.

I am unable to verify if this issue is present in the latest version as it complains about the `bash` command when running on Windows.

**Comment by raver119** [comment]
Please consider using [LATEST] for dl4j and nd4j for quite some time in future.
nd4j-java is deprecated now, nd4j-x86 should be used for CPU-powered computations.

As for cuda - starting nd4j 3.7 it's under major rewrite, and i'd suggest you to wait for rc3.8 release to test it.

**Comment by gareththegeek** [comment]
Thanks for the update, any idea when rc3.8 is likely to be available?

**Comment by raver119** [comment]
I can only guess, since major keystone is cuda :)

**Comment by nyghtowl** [comment]
Cuda is getting overhauled and release expected soon. Memory leaks being handled in other issues. Please reopen if experiencing issues after next release.
