### ISSUE TITLE
Word2Vec.wordsNearest on Google news model does not work with Java 1.7

### ISSUE THREAD

**Issue by mikegwf1** [deeplearning4j/deeplearning4j#947]
When running with Java 1.7, the Word2Vec.wordsNearest call never returns and generates 32,795 threads.  The code sequence is as follows:

	        File gModel = new File("d:/downloads/dlj4/GoogleNews-vectors-negative300.bin.gz");
	        Word2Vec vec = (Word2Vec) WordVectorSerializer.loadGoogleModel(gModel, true);
	        Collection<String> similar = vec.wordsNearest("day", 10);
	        writeToConsole("Similar words to 'day' : " + similar);

When running with Java 1.8, this call returns in about 7 seconds  on a computer with Xeon 2.4 Ghz cores with the result:
20151209_115017: Similar words to 'day' : [week, days, morning, month, hours, afternoon, hour, evening, weekend, time]

**Comment by raver119** [comment]
I was exploring this issue, and tests under j8 shown nothing - everything runs fine and smooth, both on windows and linux.

Will investigate it on j7

**Comment by raver119** [comment]
And one more thing: there's no threads creation within wordsNearest methods. Maybe somewhere deeper, but definitely not in WordVectorsImpl.

**Comment by vasants** [comment]
I can confirm this behavior.

Thread dumps and CPU profile info attached.
https://gist.github.com/vasants/1463fdca01b2767089ae

**Comment by raver119** [comment]
Thanks, that helps a lot

**Comment by raver119** [comment]
Bug is confirmed in rc3.7 and current master for java 7.
Java 8 is ok in both cases.

**Comment by raver119** [comment]
Fixed on current master.
