### ISSUE TITLE
the Word2Vec Trainning  words take a  Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 300

### ISSUE THREAD

**Issue by GitCod-Man** [deeplearning4j/deeplearning4j#949]
i think it's becaus the layerSize,but i update it ,it get exception again! code here.
![git1](https://cloud.githubusercontent.com/assets/16233416/11708257/318fc51e-9f48-11e5-8351-ed927a176c23.png)
![git2](https://cloud.githubusercontent.com/assets/16233416/11708263/3636f074-9f48-11e5-92f4-273c071c6049.png)

**Comment by raver119** [comment]
I'm afrad that your issue is caused by wrong training file. There's message that vocab size after truncation is 0, and only 5 before truncation.


P.s. you shouldn't use suche a big number of iterations for w2v. keep it around 1.

**Comment by GitCod-Man** [comment]
@raver119 
I TEST two files.  and fileEncoding all are utf-8 
 the  text is chinese texts. 
the result  is  one is ok,and the other is that problem!
which one is ok its text  like this:
城市商品
市商品
商品
烟酒类城市商
酒类城市商
类城市商
城市商
市商
烟酒类城市
酒类城市
类城市
the other one goes wrong,its texts like this:
中国好人民中国解放军未来的天下一统江山，人民有望得到好的幸福未来,终于坚持到了最后
听说今天雾霾严重,怎么解决这个问题呢？下面就让小编我给您出个绝招!
出门之前穿上厚厚的大衣,带上防毒面具即口罩,带上墨镜
I also try a text full with en-words,also catch this problem

**Comment by raver119** [comment]
You need proper Chinese tokenizer for this. DefaultTokenizer you're using isn't intended for Chineese. It's just a whitespace tokenizer.
