### ISSUE TITLE
Dead link on the DL4J Word2Vec page, section "A Working Example"

### ISSUE THREAD

**Issue by astoyan** [deeplearning4j/deeplearning4j#950]
See:
http://deeplearning4j.org/word2vec.html#a-namecodea-working-examplea

The "one example" link is dead.

**Comment by AlexDBlack** [comment]
Another dead link to fix while you are at it: "Additional Windows instructions are available here."
http://deeplearning4j.org/quickstart.html

Also: can we get a link to this http://cs231n.github.io/neural-networks-3/#baby on the visualization page (http://deeplearning4j.org/visualization.html)? Thanks

**Comment by chrisvnicholson** [comment]
Guys - those links are working for me.

Alex - your first one ought to lead here. Can you double check?
http://deeplearning4j.org/gettingstarted.html#windows

**Comment by ncleaver** [comment]
Babysittting link was added, others appear to be fine - will check broken links on site as whole this weekend
