### ISSUE TITLE
Refactor duplicate headers

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/deeplearning4j#9504]
#### Issue Description
Right now in libnd4j we have many definitions that are redundant. This makes it harder to read the code base and creates unnecessary complexity for newer people.
 We should consolidate the headers in to 1 place.

An example being mathdef in platformmath.h and _CUDA_HD  in op_boilerplate.h
Please describe our issue, along with:
- expected behavior
- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* Platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by quickwritereader** [comment]
it was handled in recent changes.
