### ISSUE TITLE
1.0.0-M1 "No available backend" despite having backend, when dl4j is loaded from another jar.

### ISSUE THREAD

**Issue by joehot200** [deeplearning4j/deeplearning4j#9506]
There is supposedly "no available backend" despite a backend being present. This occurs in 1.0.0-M1, but did not occur when I used 0.9.11. I am using Windows 8 (64 bit) but have duplicated the issue on other operating systems.

Pom.xml dependencies:

```
<dependencies>
		<dependency>
			<groupId>org.reflections</groupId>
			<artifactId>reflections</artifactId>
			<version>0.10.2</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${slf4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-native</artifactId>
			<version>1.0.0-M1.1</version>
		</dependency>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-native-platform</artifactId>
			<version>1.0.0-M1.1</version>
		</dependency>
		<dependency>
			<groupId>org.datavec</groupId>
			<artifactId>datavec-api</artifactId>
			<version>${dl4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>deeplearning4j-core</artifactId>
			<version>${dl4j.version}</version>
		</dependency>
	</dependencies>
```

Exception when exported to jar:

```
[17:16:24 ERROR]: Error occurred while enabling Deeplearning4j
java.lang.ExceptionInInitializerError
        at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetworkHelpe
r(ModelSerializer.java:282) ~[?:?]
        at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(Mode
lSerializer.java:237) ~[?:?]
        at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(Mode
lSerializer.java:221) ~[?:?]
        at org.deeplearning4j.util.ModelSerializer.restoreMultiLayerNetwork(Mode
lSerializer.java:207) ~[?:?]
        at com.joehot200.KillauraMLT.KillauraMLT.loadNetwork(KillauraMLT.java:30
0) ~[?:?]
        at com.joehot200.KillauraMLT.KillauraMLT.doMachineLearning(KillauraMLT.j
ava:154) ~[?:?]
        at com.joehot200.KillauraMLT.KillauraMLLoader.onEnable(KillauraMLLoader.
java:28) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[p
atched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.jav
a:359) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.
java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:4
08) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:3
72) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:3
27) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.jav
a:267) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:563) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.base/java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.RuntimeException: org.nd4j.linalg.factory.Nd4jBackend$NoAva
ilableBackendException: Please ensure that you have an nd4j backend on your clas
spath. Please see: https://deeplearning4j.konduit.ai/nd4j/backend
        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5095) ~[?:?]
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:270) ~[?:?]
        ... 18 more
Caused by: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Plea
se ensure that you have an nd4j backend on your classpath. Please see: https://d
eeplearning4j.konduit.ai/nd4j/backend
        at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:196) ~[?:?]

        at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5092) ~[?:?]
        at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:270) ~[?:?]
        ... 18 more
```

All required libraries are extracted into the generated jar using eclipse:
![image](https://user-images.githubusercontent.com/6872507/139595042-21d6604d-bf41-459f-ade8-1c78f997a8b8.png)

Again I will stress that my setup worked fine with version 0.9.11, but when upgraded the exact same setup gave this error.

**Comment by agibsonccc** [comment]
@joehot200 it's hard to tell just from your initial setup here...could you try setting the system property:
org.bytedeco.javacpp.logger.debug to true

either through -D or via System.setProperty(..) and tell me what it prints? This points to either being a problem with the uber jar or a problem with your native dependencies somewhere.

**Comment by joehot200** [comment]
> @joehot200 it's hard to tell just from your initial setup here...could you try setting the system property: org.bytedeco.javacpp.logger.debug to true
> 
> either through -D or via System.setProperty(..) and tell me what it prints? This points to either being a problem with the uber jar or a problem with your native dependencies somewhere.

Well umm slight problem - it is also failing to load the logger too...
`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.`

**Comment by joehot200** [comment]
> @joehot200 it's hard to tell just from your initial setup here...could you try setting the system property: org.bytedeco.javacpp.logger.debug to true
> 
> either through -D or via System.setProperty(..) and tell me what it prints? This points to either being a problem with the uber jar or a problem with your native dependencies somewhere.

Setting the system property has no difference. Is this because dl4j also cannot find the logger?
`
```
[20:00:43 WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"
.

[20:00:43 WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation

[20:00:43 WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder f
or further details.
```
`

However, the program is now working when I run it inside eclipse, but not when I export it. Why is there a difference?

**Comment by agibsonccc** [comment]
@joehot200 the debugger was intended to see why it has issues loading the particular artifact. The debug logger also has nothing to do with slf4j. It's wholly separate. Could you show how you set the property? Did you set it via cli? Also, did you declare it before nd4j was initialized?

**Comment by joehot200** [comment]
> @joehot200 the debugger was intended to see why it has issues loading the particular artifact. The debug logger also has nothing to do with slf4j. It's wholly separate. Could you show how you set the property? Did you set it via cli? Also, did you declare it before nd4j was initialized?

I used the command line:

```
java -Dorg.bytedeco.javacpp.logger.debug="true" -jar spigot.jar
PAUSE
```

I hope I did it right, let me know if I`m being an idiot somewhere. I really dont want to accidentally waste your time if I am doing something stupid :(

So I have been doing some more testing in regards to the error. Version 1.0.0-alpha and below of Deeplearning4j will work perfectly fine. But versions higher (e.g. 1.0.0-beta2) will throw the error caused above. The ONLY thing changing in my setup or code is:
`<dl4j.version>VERSION_HERE</dl4j.version> <!--Either 1.0.0-alpha (works) or 1.0.0-beta2 (doesnt work) or 1.0.0-M1.1 (doesnt work)`
and absolutely nothing else.

**Comment by joehot200** [comment]
And I know this sounds like the weirdest thing ever, but the `-Dorg.bytedeco.javacpp.logger.debug="true"` flag will work if I export with 1.0.0-alpha

`[21:44:52 INFO]: Registering org.bytedeco.javacpp.FloatPointer[address=0x846f25d
aa0,position=0,limit=10,capacity=10,deallocator=org.bytedeco.javacpp.Pointer$Nat
iveDeallocator[ownerAddress=0x846f25daa0,deallocatorAddress=0x66b1ffa0]]`


 but not 1.0.0-beta. When using alpha, debug messages appear as expected informing me which classes are loaded. When using beta, I see nothing.

**Comment by agibsonccc** [comment]
@joehot200 hmm..again though this is not an slf4j issue. It should just be logging to standard out. Javacpp does provide a way to use slf4j though. Are you redirecting standard out or doing something special preventing normal System.out.println from working properly? 

From what I'm seeing in your messages actually the old version isn't working either and therefore should be dismissed. You should see messages related to loading libraries.

**Comment by saudet** [comment]
Please try `-Dorg.bytedeco.javacpp.logger.debug=true`, not `-Dorg.bytedeco.javacpp.logger.debug="true"`.

**Comment by joehot200** [comment]
> From what I'm seeing in your messages actually the old version isn't working either and therefore should be dismissed. You should see messages related to loading libraries.

I believe that the issue may be that I am loading my program from another jar. That jar also has it`s own logger that it uses.

Unfortunately this is a necessity on my end as the program I am writing is in fact a plugin for another program, and so therefore must be loaded by it.

The old (dl4j-alpha and below) version definitely works as I am using it in production (so tested and used by at least 50 users) - I can create networks, evaluate them and match examples against them, as well as load a saved network. 

Code that loads the megajar containing dl4j libraries:
```
Class<?> jarClass;
            try {
                jarClass = Class.forName(description.getMain(), true, this);
            } catch (ClassNotFoundException ex) {
                throw new InvalidPluginException("Cannot find main class `" + description.getMain() , ex);
            }

            Class<? extends JavaPlugin> pluginClass;
            try {
                pluginClass = jarClass.asSubclass(JavaPlugin.class);
            } catch (ClassCastException ex) {
                throw new InvalidPluginException("main class " + description.getMain() + "' does not extend JavaPlugin", ex);
            }

            plugin = pluginClass.newInstance();
```

@saudet Thanks for the suggestion, it didn`t make a difference though! Also tried System.setProperty().

**Comment by whimxiqal** [comment]
Hi @joehot200 ! I'm also trying to build deeplearning4j into a Minecraft plugin. I'm coming across the exact same issue where the server doesn't find the backend in the uber-jar plugin. My pom.xml looks basically the same and everything... Please let me know when you figure it out!

**Comment by agibsonccc** [comment]
@pietelite @joehot200  can you post over on our forums? It's just a bit hard to take action on this if we can't reproduce it. Have you tried just building a jar with all the needed dependencies using the maven shade plugin? Beyond that, do note that you can override the classloader. It's hard for me to see this as any sort of a bug, because this seems rather one off. If we knew more about the environment, we could fix the problem. 

Edit: @pietelite @joehott200 please try the maven way of doing things rather than exporting from eclipse. This is known to work and is standard across any IDE: https://github.com/eclipse/deeplearning4j-examples/blob/master/dl4j-examples/pom.xml#L250

**Comment by whimxiqal** [comment]
> @pietelite @joehot200 can you post over on our forums? It's just a bit hard to take action on this if we can't reproduce it. Have you tried just building a jar with all the needed dependencies using the maven shade plugin? Beyond that, do note that you can override the classloader. It's hard for me to see this as any sort of a bug, because this seems rather one off. If we knew more about the environment, we could fix the problem.

Thank you for responding @agibsonccc I'll make a post on the forums tomorrow, sure. In my case, I followed all of these steps for [backend troubleshooting](https://deeplearning4j.konduit.ai/multi-project/explanation/configuration/backends#troubleshooting) and I verified that I'm not having one of the listed common mistakes.

And just fyi, [this is my pom.xml](https://pastebin.com/Q97kTq3F). It's also just the latest version of many tries (I installed CUDA and tried to specify that as a backend and also tried messing around more with the configuration of the shade plugin).

More information about the environment:
The `spigot.jar` file is run to start the server and the various plugin jars are in the `plugins` subdirectory of the server project folder. Each plugin is loaded dynamically on server runtime. The methodology of this loading process is unknown to me but this might be the cause of the issue somehow... Also, I'm running Java 16 on Windows 10.

> please try the maven way of doing things rather than exporting from eclipse. 

I use IntelliJ IDEA. Wrapping back around to that troubleshooting page, I decompiled my uberjar and indeed found the `org.nd4j.linalg.factory.Nd4jBackend` file, so I'm not sure if this is what you are referring to, but the compilation process seems to work fine, it's just that the server jar can't find the library on runtime.

**Comment by joehot200** [comment]
SOLVED. Please see https://community.konduit.ai/t/deeplearning4j-for-minecraft-plugins-doesnt-work-due-to-different-entry-point/1719/13

> add this to your plugin and it will work:

  `ND4JClassLoading.setNd4jClassloader(this.getClassLoader());`

While this solution was found for Minecraft, it is likely to work on other similar implementations. Minecraft code example below:

    `public class DL4jMinecraft extends JavaPlugin  {
    @Override
    public InputStream getResource(String filename) {
        return super.getResource(filename);
    }

    @Override
    public void onEnable() {
        super.onEnable();
        System.setProperty("org.bytedeco.javacpp.logger.debug","true");
        ND4JClassLoading.setNd4jClassloader(this.getClassLoader());
        INDArray arr = Nd4j.ones(1);
        System.out.println("Created ndarray");
    }
    }`

Thanks again to the dl4j devs for being really helpful!
