### ISSUE TITLE
Segfault in BaseNDArray.assign(Number)

### ISSUE THREAD

**Issue by pza94** [deeplearning4j/deeplearning4j#9534]
#### Issue Description

Got a segfault when assigning 0.0f to an NDArray:

`probVector.get(NDArrayIndex.interval(realI, probVector.length())).assign(0.0);`
probVector is an INDArray.

relevant stack frames:

```
Stack: [0x00007fb3a85ca000,0x00007fb3a86cb000],  sp=0x00007fb3a86c9078,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libnd4jcpu.so+0x2782b40]  samediff::Ticket::acquiredThreads(unsigned int)+0x0

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 14821  org.nd4j.nativeblas.Nd4jCpu.execTransformAny(Lorg/bytedeco/javacpp/PointerPointer;ILorg/nd4j/nativeblas/OpaqueDataBuffer;Lorg/bytedeco/javacpp/LongPointer;Lorg/bytedeco/javacpp/LongPointer;Lorg/nd4j/nativeblas/OpaqueDataBuffer;Lorg/bytedeco/javacpp/LongPointer;Lorg/bytedeco/javacpp/LongPointer;Lorg/bytedeco/javacpp/Pointer;)V (0 bytes) @ 0x00007fb4de396a67 [0x00007fb4de396980+0xe7]
J 30487 C2 org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(Lorg/nd4j/linalg/api/ops/TransformOp;Lorg/nd4j/linalg/api/ops/OpContext;)V (1276 bytes) @ 0x00007fb4e18a6248 [0x00007fb4e18a5880+0x9c8]
J 28174 C2 org.nd4j.linalg.api.ndarray.BaseNDArray.assign(Lorg/nd4j/linalg/api/ndarray/INDArray;)Lorg/nd4j/linalg/api/ndarray/INDArray; (105 bytes) @ 0x00007fb4e1484504 [0x00007fb4e1483ce0+0x824]
```

#### Version Information

nd4j version: 1.0.0-M1.1
CPU on linux-x86-64, Ubuntu 16.

#### Contributing

my best guess is that the issue is within the `ThreadPool::tryAcquire` method's `t = _tickets.front();` line. There is no check whether `_tickets` is empty or not before polling.

**Comment by pza94** [comment]
possibly also relevant information: I set OMP_NUM_THREADS=15 while having only 3(*2) cores/threads available.

**Comment by agibsonccc** [comment]
@pza94 I'll have @quickwritereader take a look. My initial guess is OMP_NUM_THREADS + multi threading. For now try setting it to 1.
 Thanks!

**Comment by quickwritereader** [comment]
hi @pza94.

could you post your example? I would like to replicate the issue

thanks

**Comment by pza94** [comment]
Hi, it has only happened to us once. I was trying to reproduce it but without success.
My example is in our production code, it is rather long, wouldn't make much sense (also I don't think I'm allowed) to share it here.
I couldn't pinpoint how and when exactly it ran into the segfault.

Now I'm also thinking (maybe) the application was shutting down at the point it got segfaulted. Are there some shutdown hooks in the C++ backend (does it subscribe to SIGINT/SIGTERM and start deallocating things)? That could explain it maybe.

**Comment by agibsonccc** [comment]
@pza94 @quickwritereader and I talked about this and still can't really reproduce it.  I'll close this for now, but feel free to open this if you think you can reproduce it. Libnd4j doesn't really have any shutdown hooks like that. It could have been a race condition maybe with javacpp shutting down or something.

If you want to experiment and come up with a reproducer I'd be happy to reopen this.

**Comment by pza94** [comment]
ok, makes sense. 
If it keeps happening and got some actual data, I'll get back to you.

Thanks for looking into it!

**Comment by pza94** [comment]
Hi,

this issue had kept happening for some time, so we made some further investigation (though still could not reproduce the issue at will).
Here is what we found:

In `Ticket.cpp`:
```
    void Ticket::waitAndRelease() {
        for (uint32_t e = 0; e < this->_acquiredThreads; e++) {
            // block until finished
            _interfaces[e]->waitForCompletion();

            // mark available
            _interfaces[e]->markAvailable();

            // increment availability counter
            ThreadPool::getInstance().release();
        }

        // return this ticket back to the pool
        ThreadPool::getInstance().release(this);
    }
```
note that availability counter is increased BEFORE the ticket is put back in the queue, and there is no lock taken, ie. these actions are not atomic. 

And comparing this with a snippet from `ThreadPool.cpp#tryAcquire`:
```
...

            // we lock before checking availability
            std::unique_lock<std::mutex> lock(_lock);
            if (_available >= numThreads) {
                threaded = true;
                _available -= numThreads;

                // getting a ticket from the queue
                t = _tickets.front();
                _tickets.pop();
...
```
We check for `_available >= numThreads`. In an unlucky scenario this can be true AND the ticket not being put back on the queue if  `std::unique_lock<std::mutex> lock(_lock)`  happens between the two critical lines pointed out above.
