### ISSUE TITLE
SpecifiedIndex and put(): changes not reflected (1.0.0M1)

### ISSUE THREAD

**Issue by tkorach** [deeplearning4j/deeplearning4j#9536]
#### Issue Description

Please describe your issue, along with:
- expected behavior
When setting a value using `INDArray.put(SpecifiedIndex, element)`, the changes should be reflected in the original array as well as the returned array. 
- encountered behavior
Changes are not reflected in the array (and hence neither in the returned array).

#### Version Information
1.0.0-M1.1
Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
nd4j-native 1.0.0-M1.1
* platform information (OS, etc)
Linux
* CUDA version, if used
None
* NVIDIA driver version, if in use
#N/A

#### Contributing
Happy to fix it - let me know what approaches have been attempted/considered previously.

In BaseNDArray:

```
@Override 
public INDArray put(INDArrayIndex[] indices, Number element) { 
    Nd4j.getCompressor().autoDecompress(this); 
    INDArray get = get(indices); 
    for (int i = 0; i < get.length(); i++) get.putScalar(i, element.doubleValue()); 
    return this; 
}
```
Here, the get is not a view but a detached copy, and therefore the changes done in `get.putScalar` is not propagated to the original array.

Using
```
INDArray original = ...; 
original.put(INDArrayIndex[] indices, INDArray element)
```
does solve the issue by copying item-by-item from the element array to the original array, but requires element to be of the same size as the original array - which could waste RAM. 

Test case (Kotlin):
```
val a1 = Nd4j.arange(12.0).reshape(2L, 3, 2).castTo(DataType.INT16); 
println("Original");
println(a1); 
val indices = arrayOf(all(), indices(0, 2), point(1));
a1.put(indices, Nd4j.onesLike(a1).muli(-1).castTo(DataType.INT16)); 
println("a1.put(arrayOf(all(), indices(0,2), point(1)), Nd4j.onesLike(a1).muli(-1).castTo(DataType.INT16))"); 
println(a1);
```

Is there a better solution?

First reported in https://github.com/deeplearning4j/nd4j/issues/611

**Comment by agibsonccc** [comment]
@tkorach thanks for volunteering to look in to this. From what I could tell this is due to the SpecifiedIndex not returning a view while other get methods do. I think just returning get instead would work. Do you mind opening a pull request? That way we can get you credit for finding this. An accompanying test case would be nice as well. If you want other help let me know.
