### ISSUE TITLE
IUpdater vs OptimizationAlgorithm

### ISSUE THREAD

**Issue by singam-sanjay** [deeplearning4j/deeplearning4j#9539]
#### Issue Description

I am new to DL4J and trying to understand the framework. What is the difference between IUpdater class and OptimizationAlgorithm class? I saw the [definition of the NeuralNetworkConfiguration class](https://github.com/eclipse/deeplearning4j/blob/1.0.0-M1.1/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/NeuralNetConfiguration.java) which had SGD as both the default IUpdater and default OptimizationAlgorithm. Do the classes have any parallels with the optimizers in [torch.optim](https://pytorch.org/docs/stable/optim.html)?

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: M 1.0.0-M1.1
* Platform information (OS, etc): Linux ARM64

**Comment by agibsonccc** [comment]
@singam-sanjay please post questions to the forums. The issues are only for bugs. https://community.konduit.ai/  - just focus on updaters. OptimizationAlgorithms are the old interpretation.

**Comment by singam-sanjay** [comment]
Thank You!
