### ISSUE TITLE
Dead links at the DL4J pages "Single-layer neural network" and "Creating deep-learning networks"

### ISSUE THREAD

**Issue by Ingwar** [deeplearning4j/deeplearning4j#954]
The link to the "BaseNeuralNetwork" at the page [Single-layer neural network](http://deeplearning4j.org/singlelayernetwork.html) (near the end of the page) is dead.

The link to the "BaseMultiLayerNetwork" at the page [Creating deep-learning networks](http://deeplearning4j.org/multinetwork.html) (also near end of the page) is also dead.

**Comment by chrisvnicholson** [comment]
fixed
