### ISSUE TITLE
Creation of scalar of type String not supported but needed

### ISSUE THREAD

**Issue by cbr-bsi** [deeplearning4j/deeplearning4j#9540]
#### Issue Description

Nd4j currently does not support the creation of a String scalar, a.k.a. UTF-8, via the org.nd4j.linalg.factory.Nd4j#create(org.nd4j.linalg.api.buffer.DataType, long[], char) method. Particularly, the case of `shape.length == 0`, which is handled for numeric data types using `return Nd4j.scalar(dataType, 0.0);` will also be entered if the `dataType` is UTF-8. But for obvious reasons the called `org.nd4j.linalg.factory.Nd4j#scalar(org.nd4j.linalg.api.buffer.DataType, java.lang.Number)` does not support UTF-8 (as it is intended for numerical types), thus resulting in an UnsupportedOperationException when trying to do so.

#### Additional Information

We ran into the issue after fine-tuning a BERT model based on a pre-trained frozen graph on a multi-GPU system, where the code in question was called loading the values from one GPU device to the other (even though we had set `ND4J_CUDA_FORCE_SINGLE_GPU=true`, interestingly...), when it tried to do this with an UTF-8 type data structure with `shape.length == 0`.

```
java.lang.UnsupportedOperationException: Unsupported data type used: UTF8
org.nd4j.linalg.factory.Nd4j.scalar(Nd4j.java:4977)
org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:4279)
org.nd4j.linalg.util.DeviceLocalNDArray.get(DeviceLocalNDArray.java:68)
org.nd4j.autodiff.samediff.array.ThreadSafeArrayHolder.getArray(ThreadSafeArrayHolder.java:53)
org.nd4j.autodiff.samediff.SameDiff.getArrForVarName(SameDiff.java:742)
org.nd4j.autodiff.samediff.SDVariable.getArr(SDVariable.java:138)
org.nd4j.autodiff.samediff.SDVariable.getArr(SDVariable.java:120)
org.nd4j.autodiff.samediff.SameDiff.asFlatBuffers(SameDiff.java:4803)
org.nd4j.autodiff.samediff.SameDiff.asFlatBuffers(SameDiff.java:4773)
org.nd4j.autodiff.samediff.SameDiff.asFlatBuffers(SameDiff.java:4995)
org.nd4j.autodiff.samediff.SameDiff.asFlatFile(SameDiff.java:5109)
org.nd4j.autodiff.samediff.SameDiff.save(SameDiff.java:5009)
org.nd4j.autodiff.samediff.SameDiff.save(SameDiff.java:5029)
com.bsiag.ml.cortex.learn.classification.bert.BertClassifierCortex.modelToStream(BertClassifierCortex.java:333)
com.bsiag.ml.engine.mindset.CortexMindset.exportModel(CortexMindset.java:376)
```

#### Version Information

* Deeplearning4j/Nd4j version: 1.0.0-M1
* Platform information: Ubuntu 18.04.6 LTS
* CUDA version: 11.5
* NVIDIA driver version: 495.29.05

**Comment by agibsonccc** [comment]
@cbr-bsi could you confirm that this only happens on cuda backend? With cpu, I'm seeing:
```

    @Test
    fun nd4jScalarString() {
        Nd4j.scalar("hello")
    }

```

This works fine as is. Also note that v1.0-M1.1 came out recently. See if an upgrade fixes it.

**Comment by cbr-bsi** [comment]
@agibsonccc I guess, I was mislead here, you're right... looking closely, that part seems fine.

Anyway, the case we're seing problems is actually an empty data structure of DataType UTF8. In `org.nd4j.linalg.factory.Nd4j#create(org.nd4j.linalg.api.buffer.DataType, long[], long[], char)`, there is a handling for such structures which can deal with numerical values but in case of `dataType == DataType.UTF8` this fails with the described exception.

```
    public static INDArray create(DataType dataType, @NonNull long[] shape, long[] strides, char ordering) {
        if(shape.length == 0)
            return Nd4j.scalar(dataType, 0.0); //if dataType is UTF8, this will still be called but cannot work

        checkShapeValues(shape);
        return INSTANCE.create(dataType, shape, strides, ordering, Nd4j.getMemoryManager().getCurrentWorkspace());
    }
```

We can try with the new version. But I quickly checked the `Nd4j` and `DeviceLocalNDArray` classes concerning differences of v1.0-M1.1 compared to our version and it seems these are still the same. So, it is very likely this problem still occurs even with the most recent release.

**Comment by agibsonccc** [comment]
@cbr-bsi that sounds about right.  Could you come up with a minimal test case for this in samediff? It could be something like just creating a single samediff graph with an empty UTF8 variable. Anything that could get us to a quick test/fix would be appreciated.

**Comment by agibsonccc** [comment]
@cbr-bsi I just tried this on master as well:
```
    @ParameterizedTest
    @MethodSource("org.nd4j.linalg.BaseNd4jTestWithBackends#configs")
    public void testEmptyStringScalar(Nd4jBackend backend) {
        INDArray arr = Nd4j.empty(DataType.UTF8);
    }

```

This passes fine. Could you clarify what else you might be running in to?

**Comment by cbr-bsi** [comment]
@agibsonccc the issue seems a bit more comlex as it looked initially. I'll get back to you about the simple reproducer, still looking into that.

As your test clearly shows, it's not that an emtpy UTF-8 scalar wouldn't be generally supported by Nd4j. It looks to me, that key to this the `create(org.nd4j.linalg.api.buffer.DataType, long[], long[], char)` method in the `Nd4j` class.

In our case, that method is used by `org.nd4j.linalg.util.DeviceLocalNDArray#get()` when the situation occurs, that the array is to be transferred from one device to another (`sourceId != deviceId`).

```
    public static INDArray create(DataType dataType, @NonNull long[] shape, long[] strides, char ordering) {
        if(shape.length == 0)
            return Nd4j.scalar(dataType, 0.0);

        checkShapeValues(shape);
        return INSTANCE.create(dataType, shape, strides, ordering, Nd4j.getMemoryManager().getCurrentWorkspace());
    }
```

There's two questions coming up, when I look at this code:

1. I would understand `shape.length == 0` to stand for an empty object. Why does it initialize a scalar with a value of 0 in that case? Why is it not `Nd4j.empty(dataType);` here?
1. If the implementation for numerical values here is correct, what would the correct call be for UTF-8 in this `create` method? `Nd4j.empty(DataType.UTF8)` as in your test method? Or rather something like the `scalar` method of `Nd4j` but which accepts a `String` instead of `number`?

**Comment by cbr-bsi** [comment]
This test method is the real minimal reproducer for the problem we are running into.

```
  @Test
  public void testCreateUtf8EmptyArray() {
    long[] shape = {};
    Nd4j.create(DataType.UTF8, shape, null /*irrelevant*/, 'x' /*irrelevant*/);
  }
```

Obviously the things leading up to here, including the Multi-GPU setting, is not covered by this reproduction. But possibly, that's ultimately not so relevant.

The method called in this test is one of many, which probably could cause the same issue (some clearly will if called with `dataType = DataType.UTF8`, but some get their data type from a context). Basically all which use the following code snippet: 

```
        if(shape.length == 0)
            return Nd4j.scalar(dataType, 0.0);
```

**Comment by agibsonccc** [comment]
@cbr-bsi ok fixed thanks. I just redirected that to our more generic Nd4j.empty(dataType); call. I think this method just predates that.

**Comment by cbr-bsi** [comment]
@agibsonccc thank you for the quick response fixing this!

I quickly had a look at the code change. Wouldn't it make sense to change the other methods as well, where `Nd4j.scalar([dataTypeFromVariableOrMethod], 0.0)` is returned in case `shape.length == 0`? I assume, these may lead to the same issue in different contexts.

**Comment by cbr-bsi** [comment]
Created follow-up issue https://github.com/eclipse/deeplearning4j/issues/9561 as I cannot re-open this one.
