### ISSUE TITLE
nullpointer

### ISSUE THREAD

**Issue by rogerlee24** [deeplearning4j/deeplearning4j#9558]
#### Issue Description

Why is the dependency imported by pom different from the official code?

#### Version Information
it is error.
![image](https://user-images.githubusercontent.com/57137841/144598600-dd8b2c4a-526f-4255-aa2d-b77e3259f3fe.png)

This is my pom file.
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.lee</groupId>
    <artifactId>keras_dl4j</artifactId>
    <version>1.0-SNAPSHOT</version>

    
    <properties>
        <dl4j-master.version>1.0.0-M1.1</dl4j-master.version>
        <logback.version>1.2.3</logback.version>
        <java.version>1.8</java.version>
        <maven-shade-plugin.version>2.4.3</maven-shade-plugin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>${dl4j-master.version}</version>
        </dependency>

        
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native</artifactId>
            <version>${dl4j-master.version}</version>
        </dependency>

        
        

        
        

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>

            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>${maven-shade-plugin.version}</version>
                <configuration>
                    <shadedArtifactAttached>true</shadedArtifactAttached>
                    <shadedClassifierName>bin</shadedClassifierName>
                    <createDependencyReducedPom>true</createDependencyReducedPom>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>org/datanucleus/**</exclude>
                                <exclude>META-INF/*.SF</exclude>
                                <exclude>META-INF/*.DSA</exclude>
                                <exclude>META-INF/*.RSA</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>

                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>reference.conf</resource>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>`
![image](https://user-images.githubusercontent.com/57137841/144598317-bb1211ef-5d23-458a-a939-23087f902c45.png)

This is official code.
![image](https://user-images.githubusercontent.com/57137841/144601129-ab419047-ccd5-4a39-8667-94f5744016fb.png)
![image](https://user-images.githubusercontent.com/57137841/144601165-419c4821-545d-44c0-a038-86dc3efb2c22.png)

I don't understand why these two codes are different，i think it is the reason for error.

i am so sorry for my poor English.
Can tou help me?

**Comment by agibsonccc** [comment]
@rogerlee24 this is likely just out of date snapshots you have cached locally. This isn't a bug. Master is by definition going to have newer code than 1.0.0-M1.1. Just use snapshots if you want that or clone that module locally and install it then configure the snapshot version if you want to use the newer version.

**Comment by rogerlee24** [comment]
@agibsonccc  Thanks. now i use 1.0.0-M1,but encounter a new problem
![image](https://user-images.githubusercontent.com/57137841/144612488-b9741ad7-0d6f-4a73-b299-aa204ddef247.png)
same as #6697,Is this bug fixed?

**Comment by agibsonccc** [comment]
Yes this has already been fixed on master. Please follow my previous advice.

**Comment by rogerlee24** [comment]
@agibsonccc  well, thank u
