### ISSUE TITLE
Follow-up: Creation of empty UTF-8 (String) arrays will fail

### ISSUE THREAD

**Issue by cbr-bsi** [deeplearning4j/deeplearning4j#9561]
A follow-up to https://github.com/eclipse/deeplearning4j/issues/9540, as it looks like the described issue is present in 8 more of the various create methods in `Nd4j`.

Wouldn't it make sense to change the other methods as well, where `Nd4j.scalar([dataTypeAsGivenByVariableOrMethod], 0.0)` is returned in case `shape.length == 0`? I assume, these will lead to the same issue in different contexts, if the data structure is empty and the type is UTF-8.

#### Version Information

* Deeplearning4j/Nd4j version: 1.0.0-M1
* Platform information: Ubuntu 18.04.6 LTS
* CUDA version: 11.5
* NVIDIA driver version: 495.29.05

**Comment by agibsonccc** [comment]
@cbr-bsi just wanted to ack this as I was doing issue cleanup. Could you clarify what you mean a bit? I did a quick scan of Nd4j.create(..) and most of them are numerical.  Are you talking about scalar string creation? Many times in Nd4j.create(..) we require a databuffer. An emptyy ndarray isn't an ndarray with a databuffer. It usually has no data or can be zero length and so it varies a bit. I'll try to do a pass on this weekend if you can clarify a bit. Thanks!

**Comment by cbr-bsi** [comment]
On line 4279 `org.nd4j.linalg.factory.Nd4j#create(org.nd4j.linalg.api.buffer.DataType, long[], long[], char)` a fix was applied in #9540 : https://github.com/eclipse/deeplearning4j/blob/284d0c488f4a1ebc74c9fba03f2e3954acb6fc77/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java#L4279

Depending on how it's called, I assume **line 4296** `org.nd4j.linalg.factory.Nd4j#create(org.nd4j.linalg.api.buffer.DataType, long[], char)` **will have the same issue**, as the method could be called with `dataType` being UTF8: https://github.com/eclipse/deeplearning4j/blob/284d0c488f4a1ebc74c9fba03f2e3954acb6fc77/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java#L4296

The **following are most likely fine**, as they get the data type from context within `Nd4j.dataType()`, where ultimately it is loaded in `org.nd4j.linalg.api.buffer.util.DataTypeUtil#getDtypeFromContext(java.lang.String)` which, in turn, also does not consider String to be possible (it lists all numerical types loaded from a context definition):
- `org.nd4j.linalg.factory.Nd4j#create(int[], int[], char)`
- `org.nd4j.linalg.factory.Nd4j#create(long[], long[], char)`
- `org.nd4j.linalg.factory.Nd4j#create(int[], char)`
- `org.nd4j.linalg.factory.Nd4j#create(long[], char)`
- `org.nd4j.linalg.factory.Nd4j#createUninitialized(int...)`
- `org.nd4j.linalg.factory.Nd4j#ones(int...)`
- `org.nd4j.linalg.factory.Nd4j#ones(long...)`

Also the **following shoud be fine**. They could be called with Type UTF8, however, doing so will not make sense from the context, since they do initialize to a numerical value (zeros, ones...):
- `org.nd4j.linalg.factory.Nd4j#zeros(org.nd4j.linalg.api.buffer.DataType, long...)`
- `org.nd4j.linalg.factory.Nd4j#ones(org.nd4j.linalg.api.buffer.DataType, long...)`
