### ISSUE TITLE
dl4j on spark-NullPointerException

### ISSUE THREAD

**Issue by rogerlee24** [deeplearning4j/deeplearning4j#9565]
#### Issue Description

After I imported the keras model into dl4j, I wanted to run it on spark, but I encountered a problem.
The input of my model is an array containing 2048 elements。
I don't know why.
![image](https://user-images.githubusercontent.com/57137841/145221485-311a3826-1795-400d-94c6-847e1703cfc7.png)

![image](https://user-images.githubusercontent.com/57137841/145221437-186dde62-14ee-4127-aa47-0ca5c12f7515.png)
![image](https://user-images.githubusercontent.com/57137841/145221565-7d71ac8d-98d1-4a4a-9780-668bc243c419.png)
![image](https://user-images.githubusercontent.com/57137841/145221611-c2523ea7-87d5-4441-9f59-b3a8fdc2052c.png)
![image](https://user-images.githubusercontent.com/57137841/145221724-3fdad00a-82e8-44d1-bca8-6277504f23f9.png)

it is my model.
[model.zip](https://github.com/eclipse/deeplearning4j/files/7676541/model.zip)

can you help me again?Thanks!

#### Version Information
Deeplearning4j version 1.0.0-M1.1
keras version 2.7.0

**Comment by agibsonccc** [comment]
@rogerlee24 could you verify if this happens on 1.0.0-SNAPSHOT to make sure this isn't a problem we already fixed?

**Comment by rogerlee24** [comment]
@agibsonccc  yes,i didn't find a similar problem

**Comment by agibsonccc** [comment]
@rogerlee24 so this is already fixed on snapshot then? A lot of work went in to conv1d which is why I wanted to check. If so I'll close this issue and just suggest you use snapshot till next release. We're aiming for the next 2 weeks to do the last release for the year.

**Comment by agibsonccc** [comment]
@rogerlee24 just change your input to shape: batchSize,2048,1 you just had the wrong shape. Not even your keras model would expect 1 x 2048 to be valid. It would throw an error. I'm closing this after having confirmed the imported model runs fine on master.
