### ISSUE TITLE
Exception when weights array for loss function is a scalar

### ISSUE THREAD

**Issue by cyberbeat** [deeplearning4j/deeplearning4j#9582]
I stumbled upon this exception:

```
Caused by: java.lang.IllegalArgumentException: Weights array must be a row vector
	at org.nd4j.linalg.lossfunctions.impl.LossBinaryXENT.<init>(LossBinaryXENT.java:100)
	at org.nd4j.linalg.lossfunctions.impl.LossBinaryXENT.<init>(LossBinaryXENT.java:72)
...
```

with weights array being a scalar. Dl4j does the following test:

```
   public LossBinaryXENT(@JsonProperty("clipEps") double clipEps, @JsonProperty("weights") INDArray weights){
        if (weights != null && !weights.isRowVector()) {
            throw new IllegalArgumentException("Weights array must be a row vector");
        }
...
```

Shouldn't it be sufficient to test on "isRowVectorOrScalar"?

**Comment by agibsonccc** [comment]
@cyberbeat great find. Addressed this here: https://github.com/eclipse/deeplearning4j/pull/9581
Note that the samediff api (samediff.loss()... addresses this and uses different loss functions. These are mainly to be used with the deeplearning4j-nn/deeplearning4j-core api.
