### ISSUE TITLE
Simple Java Bug.

### ISSUE THREAD

**Issue by baedaron** [deeplearning4j/deeplearning4j#9585]
CURRENT MASTER.

org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner
--------------------------------------------------------------------------------------
.
.
.
    @Override
    public INDArray[] exec(CustomOp op, @NonNull OpContext context) {
        long st = profilingConfigurableHookIn(op, context);
        boolean mklOverride = false;
        try {
			DifferentialFunction differentialFunction = (DifferentialFunction) op; // *********************** ADD!!!
			String ownName = differentialFunction.getOwnName();
            if (Nd4jCpu.Environment.getInstance().isUseONEDNN()) {
                val opName = op.opName();
                val state = mklOverrides.get(op);
                if (state != null && state == true) {
                    mklOverride = true;
                    Nd4jCpu.Environment.getInstance().setUseONEDNN(true);
                }
            }

            val status = loop.execCustomOp2(null, op.opHash(), context.contextPointer());

            if (loop.lastErrorCode() != 0)
                throw new RuntimeException(loop.lastErrorMessage());

            if (status != 0) {
                // DifferentialFunction differentialFunction = (DifferentialFunction)  op; // *********************** DELETE!!!
                throw new RuntimeException("Op with name " + differentialFunction.getOwnName() + " and op type [" + op.opName() + "] execution failed");
            }
            if (context.getOutputArrays().isEmpty())
                return new INDArray[0];
            else
                return context.getOutputArrays().toArray(new INDArray[context.getOutputArrays().size()]);
.
.
.
--------------------------------------------------------------------------------------

**Comment by agibsonccc** [comment]
@baedaron thanks. Yeah just comment that out. That is already fixed here. https://github.com/eclipse/deeplearning4j/pull/9584 I'm closing this in lieu of that.
