### ISSUE TITLE
Convolutional net crashes if image is not square

### ISSUE THREAD

**Issue by joel-odlund** [deeplearning4j/deeplearning4j#959]
While experimenting with conv-nets,  a problem was encountered when the image dimensions don't match. 

The stack trace indicates, i think, that rows and columns are mixed up somewhere in the code. 

stack trace gist:  https://gist.github.com/joel-odlund/bff7d8dbfc660e34a1ac
code reproducing the issue:   https://gist.github.com/joel-odlund/f0bf176672ada09fd8ac

this was tested on version 0.4-rc3.7

**Comment by AlexDBlack** [comment]
Thanks for flagging this. You were right, height and width were switched in subsampling layer backprop code.
Fixed: https://github.com/deeplearning4j/deeplearning4j/pull/964
