### ISSUE TITLE
nOut for Bidirectional Concatenated

### ISSUE THREAD

**Issue by cyberbeat** [deeplearning4j/deeplearning4j#9593]
This is the code for `org.deeplearning4j.nn.conf.layers.recurrent.Bidirectional`

```
    public long getNOut() {
        if (this.fwd instanceof LastTimeStep) {
            return ((FeedForwardLayer) ((LastTimeStep) this.fwd).getUnderlying()).getNOut();
        } else {
            return ((FeedForwardLayer) this.fwd).getNOut();
        }
    }
```

Shouldn't it be multiplicated by 2 for Concat-Mode?

**Comment by agibsonccc** [comment]
@cyberbeat do you have some code that's causing an error here? Sorry I wasn't able to get to this till after M2. We're about to release an M2.1 and I wanted to check in to see if there's something we could do for you here.

**Comment by cyberbeat** [comment]
In concat mode you do this

```
 case CONCAT:
                ret = Nd4j.concat(1, out1, out2);
                ret = workspaceMgr.leverageTo(ArrayType.ACTIVATIONS, ret);
```

Doesn't it make sense, to have different nOut (*2) in this case?
