### ISSUE TITLE
Should this path be filePath to extract the extension for checking?

### ISSUE THREAD

**Issue by UltraRabbit** [deeplearning4j/deeplearning4j#9604]
https://github.com/eclipse/deeplearning4j/blob/3f93acc1ec943153e00538415aa4704866cc2e00/deeplearning4j/deeplearning4j-scaleout/spark/dl4j-spark/src/main/java/org/deeplearning4j/spark/util/SparkUtils.java#L594

**Comment by agibsonccc** [comment]
@UltraRabbit could you post on the community forums: https://community.konduit.ai/ and add more context to your question?
