### ISSUE TITLE
Loading a functional Keras model throws NullPointerException.

### ISSUE THREAD

**Issue by Szustarol** [deeplearning4j/deeplearning4j#9625]
#### Issue Description

- Expected behavior:
Keras model loads fine in Java/Scala using this library.
- Encountered behavior
Loading a Keras functional model with deeplearning4j is impossible, because a NullPointerException is thrown. This is the code used to load it (in Scala), and the thrown error:
```scala
object Model{
    val modelConfigPath = "../../model/model_config.json"
    val modelWeightsPath = "../../model/model_weights.h5"

    System.setProperty("org.bytedeco.javacpp.maxphysicalbytes", "4096M")
    System.setProperty("org.bytedeco.javacpp.maxbytes", "4096M")
    val model = KerasModelImport.importKerasModelAndWeights(modelConfigPath, modelWeightsPath)
    
}
````
The trace is:

> Caused by: java.lang.NullPointerException: null
>         at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.importWeights(KerasModelUtils.java:235)
>         at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:190)
>         at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:99)
>         at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:311)
>         at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:257)
>         at jobs.Model$.<clinit>(RotationGenerator.scala:28)

If I try to load the whole model (.h5 file with training data as well), I get slightly the same exception:

###### When I try to load without forcing configuration:
```scala
object Model{
    val modelPath = "../../model/best_image_v2_model.h5"
    val modelInputStream = new FileInputStream(modelPath)

    System.setProperty("org.bytedeco.javacpp.maxphysicalbytes", "4096M")
    System.setProperty("org.bytedeco.javacpp.maxbytes", "4096M")
    val model = KerasModelImport.importKerasModelAndWeights(modelInputStream, false)
}
```
I get the following error (same as above):

> Caused by: java.lang.NullPointerException: null
>         at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.importWeights(KerasModelUtils.java:235)
>         at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:190)
>         at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:99)
>         at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:311)
>         at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:150)
>         at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:50)
>         at jobs.Model$.<clinit>(RotationGenerator.scala:25)

###### When I try to load without the flag set:

```scala
object Model{
    val modelPath = "../../model/best_image_v2_model.h5"
    val modelInputStream = new FileInputStream(modelPath)

    System.setProperty("org.bytedeco.javacpp.maxphysicalbytes", "4096M")
    System.setProperty("org.bytedeco.javacpp.maxbytes", "4096M")
    val model = KerasModelImport.importKerasModelAndWeights(modelInputStream)
}
```

This is the error:
```scala
Caused by: java.lang.NullPointerException: null
        at org.deeplearning4j.nn.modelimport.keras.utils.KerasOptimizerUtils.mapOptimizer(KerasOptimizerUtils.java:116)
        at org.deeplearning4j.nn.modelimport.keras.KerasModel.importTrainingConfiguration(KerasModel.java:398)
        at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:174)
        at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:99)
        at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:311)
        at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:167)
        at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:68)
        at jobs.Model$.<clinit>(RotationGenerator.scala:25)
```

I have also tried to load this model using version 1.0.0-beta7, to get the following error:

> Caused by: org.deeplearning4j.nn.modelimport.keras.exceptions.InvalidKerasConfigurationException: Expected model class name Model (found Functional). For more information, see https://deeplearning4j.konduit.ai/keras-import/overview
>         at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:133)
>         at org.deeplearning4j.nn.modelimport.keras.KerasModel.<init>(KerasModel.java:96)
>         at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildModel(KerasModelBuilder.java:307)
>         at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:262)
>         at jobs.Model$.<clinit>(RotationGenerator.scala:25)
> 

This is the model structure as defined in python:
```python
def build_model_v2(model_image_width=64, model_image_height=128):
    """Loosely based on the U-net architecture"""
    encoder_input = keras.layers.Input(shape = ( model_image_height, model_image_width, 3,))
    conv_input = encoder_input
    conv_input = keras.layers.BatchNormalization()(conv_input)
    n_filters = [16, 16, 32, 32, 64, 64, 128, 128, 256, 256, 512, 512]
    prev_filter = n_filters[1]
    conv_layers = []
    for filter_size in n_filters:
        if filter_size != prev_filter:
            conv_input = keras.layers.MaxPooling2D((2, 2), padding='same')(conv_input)
        conv_input = keras.layers.Conv2D(filter_size, (3, 3), activation='relu', padding='same')(conv_input)
        conv_layers.append(conv_input)
        conv_input = keras.layers.BatchNormalization()(conv_input)
        prev_filter = filter_size
    conv_layers.reverse()
    conv_input = keras.layers.MaxPooling2D((2, 2), padding='same')(conv_input)

    def build_path(entry):
        nonlocal n_filters, conv_layers
        n_filters_rev = list(reversed(n_filters))
        prev_filter = n_filters_rev[0]
        for idx, filter in enumerate(n_filters_rev):
            if filter != prev_filter:
                entry = keras.layers.UpSampling2D((2, 2))(entry)
            entry = keras.layers.Conv2D(filter, (3, 3), activation='relu', padding='same')(entry)
            if idx > 1:
                entry = keras.layers.concatenate([entry, conv_layers[idx-2]])
            entry = keras.layers.BatchNormalization()(entry)
            prev_filter = filter
        entry = keras.layers.UpSampling2D((2, 2))(entry)
        entry = keras.layers.Conv2D(3, (3, 3), activation='sigmoid', padding='same')(entry)
        return entry

    left_rotation = build_path(conv_input)
    right_rotation = build_path(conv_input)
    back_rotation = build_path(conv_input)
    

    return keras.models.Model(encoder_input, [left_rotation, right_rotation, back_rotation])
```

#### Version Information

* Deeplearning4j version: Tried both 1.0.0-M1.1 and 1.0.0-M1, on 1.0.0-beta7 i get a different error - "Expected model class name Model (found Functional)"
* Platform information (OS, etc): Ubuntu 20.04 LTS

**Comment by agibsonccc** [comment]
@Szustarol could I get just a straight hdf5 model to try? That's much easier than me setting up a whole environment just to test this. Could you also tell me the keras version?

**Comment by Szustarol** [comment]
@agibsonccc sorry for the late response but I have been busy recently.
I have created a minimal example of a model that fails to load (I can't send you the .h5 file since the model is a dozen of gigabytes):
- a python script that creates the model
- build.sbt that builds scala
- and the scala file that loads the model.
Run the python script to generate the model and then sbt run to load it in scala, You should get a null pointer exception.



Tested on:
tf & keras 2.7.0
scala 2.13.8


Use this to build the model:
As for the model itself it doesn't even need two outputs to throw a null ptr exception, but this one closely resembles the model I used when it comes to the number of outputs. A functional model with just one output also throws an exception.
```python
#!/usr/bin/python3

import tensorflow.keras as keras
import tensorflow as tf

def build_simple_model():
    model_input = keras.layers.Input(shape = (32, ))
    model_dense = keras.layers.Dense(10, activation="relu")(model_input)
    model_output_1 = keras.layers.Dense(1, activation="sigmoid")(model_dense)
    model_output_2 = keras.layers.Dense(1, activation="sigmoid")(model_dense)

    return keras.models.Model(model_input, [model_output_1, model_output_2])

if __name__ == "__main__":
    model = build_simple_model()
    model.summary()
    model.compile(
            optimizer=keras.optimizers.Nadam(),
            metrics=["accuracy"],
            loss="mse"
    )
    model.save("simple_model.h5")
```

This to build the .scala:
```sbt
name := """deeplearning_test"""
organization := "org.szustarol"

version := "1.0-SNAPSHOT"

scalaVersion := "2.13.8"

val nd4jVersion = "1.0.0-M1.1"

libraryDependencies += "org.deeplearning4j" % "deeplearning4j-core" % nd4jVersion
libraryDependencies += "org.deeplearning4j" % "deeplearning4j-modelimport" % nd4jVersion
libraryDependencies += "org.nd4j" % "nd4j-native-platform" % nd4jVersion
libraryDependencies += "org.nd4j" % "nd4j-common" % nd4jVersion
```


Then this to load the model:
```scala
import org.deeplearning4j.nn.modelimport.keras.KerasModelImport
import java.lang.System
import java.io._

object Main{
  def main(args : Array[String]): Unit = {
    val modelInputStream = new FileInputStream("simple_model.h5")
    val model = KerasModelImport.importKerasModelAndWeights(modelInputStream, false)
    println("Model loaded!")
  }
}
```

**Comment by agibsonccc** [comment]
@Szustarol thanks for the reproducer. Sorry it took so long. Backlog with the builds was a bit heavy. We published our next stable release yesterday and I'll start catching up on community issues. This was actually a simple fix. Feel free to reference the PR. Snapshots will be published and you can use those.
