### ISSUE TITLE
Boolean SameDiff operations return wrong results

### ISSUE THREAD

**Issue by CompilerCrash** [deeplearning4j/deeplearning4j#9635]
#### Issue Description

Hey, this is my first issue, I hope I'm doing this right.

I noted that the SameDiff operations `math.and`, `math.or` and `math.xor` give me wrong results if their second argument has to be broadcasted. Consider the following (Scala) code:

    val sd = SameDiff.create()
  
    val x = sd.constant(Nd4j.createFromArray(Array(Array(true, false), Array(false, true))))
  
    val y1 = sd.constant(Nd4j.createFromArray(Array(Array(false, false), Array(false, false))))
    val y2 = sd.constant(Nd4j.createFromArray(Array(Array(false), Array(false))))
    val y3 = sd.constant(Nd4j.createFromArray(Array(Array(false, false))))
    val y4 = sd.constant(Nd4j.createFromArray(false, false))
    val y = y3
  
    val res = sd.math.or(x, y) // also try it with and/xor
  
    println("x =\n" + x.eval() + "\n")
    println("y =\n" + y.eval() + "\n")
    println("res =\n" + res.eval() + "\n")

Output:

    x =
    [[      true,     false], 
     [     false,      true]]

    y =
    [[     false,     false]]

    res =
    [[      true,     false], 
     [      true,      true]]

All variants of `y` should be equivalent after broadcasting, but only when `y == y1`, the result is correct. In all other cases some entries are always wrong. Therefore, I suspect that the problem is related to broadcasting. On a side note, if you cast the result to a numeric datatype (e.g. `res.castTo(DataType.UINT8)`), you can observe random numbers at some places instead of only 1s and 0s.

#### Version Information

* Deeplearning4j version: 1.0.0-M1.1
* Platform information (OS, etc): Linux Mint 20.3
* CUDA version: not used
* NVIDIA driver version: not in use

#### Additional Information

This is my logger output:

    [main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
    [main] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for linear algebra: 2
    [main] INFO org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory - Binary level Generic x86 optimization level Generic x86
    [main] INFO org.nd4j.nativeblas.Nd4jBlas - Number of threads used for OpenMP BLAS: 2
    [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CPU]; OS: [Linux]
    [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [4]; Memory: [1,9GB];
    [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
    [main] INFO org.nd4j.linalg.cpu.nativecpu.CpuBackend - Backend build information:
    GCC: "7.5.0"
    STD version: 201103L
    DEFAULT_ENGINE: samediff::ENGINE_CPU
    HAVE_FLATBUFFERS
    HAVE_OPENBLAS
    [main] INFO org.nd4j.autodiff.samediff.SameDiff - Creating new InferenceSession for thread 1

Let me know if you need more information.

#### Contributing

Sorry, I think I'm not able to do this.

**Comment by agibsonccc** [comment]
@CompilerCrash I just tried this with the latest version:
```java
    @ParameterizedTest
    @MethodSource("org.nd4j.linalg.BaseNd4jTestWithBackends#configs")
    public void testOr() {
        SameDiff sd = SameDiff.create();
        SDVariable a = sd.constant(Nd4j.createFromArray(true,false,false,true).reshape(2,2));
        SDVariable b = sd.constant(Nd4j.createFromArray(false,false).reshape(1,2));
        SDVariable result = sd.math().or(a,b);
        INDArray eval = result.eval();
        System.out.println(eval);
    }
```

This gave me:
```
[[      true,     false], 
 [     false,      true]]
```

Numpy baseline:
```python
import numpy as np
a = np.array([[True,False],[False,True]])
b = np.array([False,False])
print(np.logical_or(a,b))
```
Prints:
```
[[ True False]
 [False  True]]
```

This might be a bug in M1.1 (haven't confirmed) but the behavior looks good so maybe just try snapshots for now. I'll close this for now. Feel free to comment if something changes after you try snapshots: https://deeplearning4j.konduit.ai/multi-project/explanation/snapshots

**Comment by CompilerCrash** [comment]
Thanks for the hint regarding the snapshots. From now on I'm on 1.0.0-SNAPSHOT. Unfortunately, this did not solve the problem for me, and on closer inspection, it seems to be even stranger than I thought.

I ran the test code you gave above in a fresh Java 11 project, and the result was again wrong:

    [[      true,     false], 
     [      true,      true]]

But then I added an unrelated SDVariable definition between the definitions of `a` and `b` like this:

    SameDiff sd = SameDiff.create();
    SDVariable a = sd.constant(Nd4j.createFromArray(true, false, false, true).reshape(2, 2));
    sd.constant(42); // added statement
    SDVariable b = sd.constant(Nd4j.createFromArray(false, false).reshape(1, 2));
    SDVariable result = sd.math().or(a, b);
    INDArray eval = result.eval();
    System.out.println(eval);

And suddenly the result was correct:

    [[      true,     false], 
     [     false,      true]]

This doesn't happen with every placement and every kind of statement (only SDVariable definitions, I guess) but with quite a few. I have no idea why.

**Comment by agibsonccc** [comment]
@CompilerCrash are you using cuda? I still can't reproduce this.
Edit: Tried this on cuda as well with snapshots and I still can't reproduce this.

Beyond that...I wouldn't try to inject too much magic in to the debugging. When you create variables it just gets stored in a map.
When we go to build the execution graph we do it based on a bunch of internal dictionaries. That execution order is going to be deterministic and very well tested at this point (read: years). Unfortunately to fix this I still need to reproduce it. Is there anything else you can give me to go on for this?

Maybe give me a complete github repo to look at so I can verify it? That way I can also see any other assumptions you're trying when making the project. Sorry for the hassle I really hope I can reproduce this.

**Comment by CompilerCrash** [comment]
I'm using nd4j-native; no CUDA involved.

You are probably right that the observations about the variable ordering don't necessarily mean anything. If I had to make another wild guess, maybe some memory access in the C++ backend uses a wrong address under certain circumstances? What I can say for sure is that it happens only with boolean operations and if broadcasting is involved and that the shape and order of the inputs to the operation affect the outcome.

I created a repo with the code that triggers the bug for me: https://github.com/CompilerCrash/DL4J-Bug-Reproduction. Would be interesting to see, if anyone else can reproduce it.

I hope that helps.

**Comment by agibsonccc** [comment]
@CompilerCrash thanks a lot for that. I figured out the difference upon closer inspection. Change to:
```
   SameDiff sd = SameDiff.create();
        SDVariable a = sd.constant(Nd4j.createFromArray(true, false, false, true).reshape(2, 2));
        SDVariable b = sd.constant(Nd4j.createFromArray(false, false).reshape(2));
        SDVariable result = sd.math().or(a, b);
        INDArray eval = result.eval();
        System.out.println(eval);
```

This will give you the correct result. Notice that I changed the shape from 1,2 to 2. I'll double check the broadcasting behavior here and for now at least you have a workaround. Thanks for spending so much time on this!

**Comment by CompilerCrash** [comment]
Thank _you_ for investigating this.

Indeed, when using `reshape(2)` I get the correct result for this example. However, I added another example to the repo where this didn't help.

For now, I can easily work around this bug by either making sure all variables have their "full matrix shape" or by using 1s and 0s instead of true and false. So solving this issue is not that urgent for me.

**Comment by agibsonccc** [comment]
@CompilerCrash sure of course. I just want to make sure we get the set of broadcast shapes this happens for so I can nail down the execution path and fix that. I'm not sure if this is for specific ops yet or in the core broadcasting machinery itself (I haven't did anything than ran your code yet so I don't know quite what we're dealing with here yet)

**Comment by CompilerCrash** [comment]
Makes sense. My observations so far are: For `a` of shape (2, 2), errors may happen if `b` has shapes (1, 2), (2, 1), or (2). For shapes (2, 2), (1, 1), (1), and scalars, everything seems fine.
