### ISSUE TITLE
Error when importing a ONNX model from file

### ISSUE THREAD

**Issue by KillianB** [deeplearning4j/deeplearning4j#9642]
#### Issue Description
When using those 3 lines of code to import a ONNX model from a file in my Spring resource folder:
```Java
OnnxFrameworkImporter onnxFrameworkImporter = new OnnxFrameworkImporter();
File file = new File(getClass().getClassLoader().getResource("model_onnx.onnx").toURI());
SameDiff graph = onnxFrameworkImporter.runImport(file.getAbsolutePath(), Collections.emptyMap());
```
- expected behavior = I should have full access of my model in the `graph` variable
- encountered behavior = Error telling me nd4j-op-def.pbtxt cannot be opened because it does not exist. Seems to exist in the github repository but not in the Jar ??

#### Version Information

* Deeplearning4j version = 1.0.0-M1.1
* Platform information (OS, etc) = Microsoft Windows 10 Professionnal 64 bits - 10.0.19044 N/A build 19044
* CUDA version, if used = N/A
* NVIDIA driver version, if in use = N/A

#### Additional Information

* Exception stack trace = https://gist.github.com/KillianB/08eeb01ce358d2b81d9e6901a5120e8d#file-stacktrace-txt
* pom.xml file = https://gist.github.com/KillianB/08eeb01ce358d2b81d9e6901a5120e8d#file-pom-xml

**Comment by agibsonccc** [comment]
@KillianB  we'll have an M2 release out shortly. I'll ask you to try that to see if you still have this issue after that. In the mean time could you show me what the model is? I'd be happy to convert the model for you as well. Depending on what model it is note we have plenty of pre converted models here as well: https://github.com/KonduitAI/omnihub-zoo/tree/main/samediff

**Comment by KillianB** [comment]
@agibsonccc Thank you for your anwser ! Good news for the release. The model I tried to convert is a specific pretrained IR-50 model done in PyTorch that I converted myself into an ONNX model with `torch.onnx.export`. If you can convert it for me, I would be grateful ! One question, since it's not a format supported by GitHub, how should I send it to you?

**Comment by agibsonccc** [comment]
@KillianB go ahead and DM me on our forums at https://community.konduit.ai/ same user name. Thanks!

**Comment by agibsonccc** [comment]
Closing due to lack of follow up
