### ISSUE TITLE
Labels not saved in serialized MultiLayerNetwork

### ISSUE THREAD

**Issue by StaffanArvidsson** [deeplearning4j/deeplearning4j#9654]
#### Issue Description
When saving a `MultiLayerNetwork` using the `ModelSerializer` the `labels` field is not persisted when loaded back into memory. This requires additional meta-data to be kept with the trained models. This might not be evident for those cases where classes are standardize into one-hot-encoding and always have a one-to-one mapping from column to class "number". But consider a generic case where classes could be e.g. [-1, +1], that mapping can be conveniently saved with `model.setLabels(INDArray)` and the output from e.g. `model.predict(INDArray)` can easily be translated back into the original labels found in the training data using the output from the `model.getLabels()` method.

I might be missing the true reason for the field `labels`, if this use case is not the reason for having it. There is no javadoc for either the field, setter or getter methods, so it's very hard to tell what its purpose is.

#### Version Information
Tested both in 1.0.0-M1.1 and 1.0.0-M2 on Linux using nd4j-native and nd4j-native-platform backends.

**Comment by agibsonccc** [comment]
@StaffanArvidsson thanks for flagging. That's a fairly underused feature I believe but we can make sure that that gets saved. We really usually only focus on layer configurations and their hyper parameters + the weights not some of the properties. I can see where that'd be useful though. For now just set it in your application.

**Comment by agibsonccc** [comment]
@StaffanArvidsson this PR adds it. https://github.com/eclipse/deeplearning4j/pull/9666 Please use the dataset api for labels.
