### ISSUE TITLE
Error during DL4J runtime

### ISSUE THREAD

**Issue by thangnbn** [deeplearning4j/deeplearning4j#9665]
#### Issue Description

I was running DL4J to train on 50% of the standard CIFAR-10 dataset from [here](https://www.cs.toronto.edu/~kriz/cifar.html) when I encounter this error:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fe2a1f84b10, pid=18238, tid=18273
#
# JRE version: Java(TM) SE Runtime Environment (12.0.2+10) (build 12.0.2+10)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (12.0.2+10, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libnd4jcpu.so+0x1743b10]  sd::TadDescriptor::TadDescriptor(long long const*, int const*, int, bool)+0x420
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/khabak/tnbui/core.18238)
#
# An error report file with more information is saved as:
# /home/khabak/tnbui/hs_err_pid18238.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

The command I used to run my JAR file: `java -Xmx2g -Djava.library.path=[classpaths] -jar [file].jar [program arguments]`. I wonder if this error occurs because of memory insufficiency?

#### Version Information

* Deeplearning4j version: 1.0.0-M2
* Platform information: Ubuntu 18.04.6 LTS (Bionic Beaver)
* Hypervisor vendor: VMware
* CPU: Intel(R) Xeon(R) CPU X5690  @ 3.47GHz (4)
* Memory: 4G

#### Additional Information

Full log and `pom.xml` file: [here](https://gist.github.com/bnnthang/f3ee96a0db25ad5eb65ef2fc55ec50eb)

**Comment by agibsonccc** [comment]
@bnnthang could you please confirm if this happens with 1.0.0-M1.1 as well? I'd also be curious to see a minimal version of your training class.

Thanks for providing the crash log. It looks like it might be related to a broadcast op (I'm guessing add?)

These crashes can happen for a wide variety of reasons. Sometimes it's related to openmp and race conditions or early de allocation of buffers and may not be a bug. I can narrow it down with a b it more information. Thanks!

**Comment by thangnbn** [comment]
What do you mean by my "training class"?

If you are asking for the configuration of my training neural network, I am using the same configuration with the example [here](https://github.com/eclipse/deeplearning4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/quickstart/modeling/convolution/CIFARClassifier.java).

[Here](https://github.com/bnnthang/FederatedLearningTestbed/blob/master/CommonUtils/src/main/java/com/bnnthang/fltestbed/commonutils/clients/Cifar10TrainingWorker.java) is how I am using the library functions to initiate trainings.

I wonder if the above information answers your question. I will try to confirm if this happens on 1.0.0-M1.1.

**Comment by agibsonccc** [comment]
@bnnthang a main class that loads and trains your model. Something like:
```java
public class MyExample {
      public static void main(String...args) {
           DataSetIterator data = ...;
          ComputationGraph network = ...;
          network.fit(data);   
  }
}
```

Thanks for confirming!

**Comment by thangnbn** [comment]
So [`Cifar10TrainingWorker`](https://github.com/bnnthang/FederatedLearningTestbed/blob/master/CommonUtils/src/main/java/com/bnnthang/fltestbed/commonutils/clients/Cifar10TrainingWorker.java) is my training class. I am running training in a seperate thread. Also, [`MyCifar10Loader`](https://github.com/bnnthang/FederatedLearningTestbed/blob/master/CommonUtils/src/main/java/com/bnnthang/fltestbed/commonutils/clients/MyCifar10Loader.java) and [`MyCifar10DataSetIterator`](https://github.com/bnnthang/FederatedLearningTestbed/blob/master/CommonUtils/src/main/java/com/bnnthang/fltestbed/commonutils/clients/MyCifar10DataSetIterator.java) are how I am modifying the `DataSetIterator` for my own purpose.

**Comment by agibsonccc** [comment]
@bnnthang this is due to your close() call in your worker. Please read the docs here: https://deeplearning4j.konduit.ai/v/en-1.0.0-m1.1/multi-project/explanation/configuration/memory#memory-management-for-nd4j-dl4j-how-does-it-work

**Comment by thangnbn** [comment]
@agibsonccc  May you explain in more details what `close()` does? I guess so far from documentation is that `close()` will deallocate some memory that are previously allocated for calculations - the next time I called the `fit()` method there will be no memory allocated.  Won't the memory be allocated if I use `MultiLayerNetwork` constructor?

Please confirm if my guess is correct, thanks! Sorry I'm inexperienced.

**Comment by agibsonccc** [comment]
@bnnthang close() de allocates off heap memory. You are running in to a c/c++ crash. When java tries to use that memory it will crash the process. I see you using System.gc() as well. You can configure that based on the docs I sent you. You can also use workspaces for this if you want.

**Comment by thangnbn** [comment]
@agibsonccc The weird issue is that I repeat the `Cifar10TrainingWorker` several times - create a new thread, start the new thread, the thread finishes, and again create another new thread again - in one run. The above error never occurs immediately after the first time - in the run that created the above log, it produced the above error after about 8 threads being started and finished. If it is indeed the memory problem you were saying, shouldn't it happen right away?

**Comment by XJ8** [comment]
@bnnthang Did you fix it  eventually? I encountered the same fatal error.

**Comment by XJ8** [comment]
@bnnthang I didn't use close() or System.gc(), but still saw this error sometimes. I ran it on AWS Lambda, and yes, the error (C  [libnd4jcpu.so+0x1743b10]  sd::TadDescriptor) shows up sometimes, and sometimes it runs OK.

**Comment by agibsonccc** [comment]
@XJ8 @bnnthang was doing a bunch of things that aren't normal. If you are running in to memory issues post on the forums. I closed this because if you use the framework like the way you're supposed to in the docs (eg: the mechanisms for memory management like workspaces or periodic GC frequency) then you shouldn't have problems. If you think you have a bug feel free to open a new issue as well.

**Comment by bnnthang** [comment]
I finally fixed my problem. The problem was just I forgot to deallocate a few ``NDArray`s after I finished using them, so in long run I would run out of memory - I think later on the `malloc` call would result in error.

Anyway, I want to remind anyone who encounter the same problem is that DL4J uses "off-heap" memory. So you need to be careful and reminder to close things after use to avoid memory leak (like old time `free` after `malloc`).

**Comment by thangnbn** [comment]
@XJ8 So I just solved the issue by running on JRE 8 instead of other version. My guess is that since DL4J is built with the target is 1.8, it doesn't really run well on other versions (although they claim that older versions are backward compatible).

**Comment by agibsonccc** [comment]
@bnnthang if you have issues feel free to file an issue :) no we don't support below java 7 since M1 onwards. We added support for java 9+ modularization in M2 so I'd appreciate feedback if you have issues there as well.

**Comment by thangnbn** [comment]
@agibsonccc  Yeah previously I had run with Java 11, 12, etc. and got segfaults, then I switched to Java 8 and it currently runs well.

I wonder how I can investigate issues regarding different Java versions?

**Comment by agibsonccc** [comment]
@bnnthang please ask what might cause this next time rather than assume. Your assumptions are actually completely off base. JVM crashes have nothing to do with the java version. It's all the same c++ code no matter what version of java you're using. A JVM crash is always related to native code within the library not the java version. Ensure you file issues with crash logs so we can take a look at those. 




Crashes can be either how you're using the code (eg: you dive too much in to the internals and free memory yourself) or they could be a bug. The java version is the *last* thing that would affect something like that.



Java versions just come down to which byte code is supported. Beyond that's it's still all just java native interface. The main interface we use for generating java -> c++ is also version agnostic and wouldn't have any specialized behavior dependent on the version either.

**Comment by NagyGa1** [comment]
Regularly happening for me on M2.1, on both x86-64 and arm64 machines.
