### ISSUE TITLE
RuntimeException: Op [cbow] execution failed on CUDA

### ISSUE THREAD

**Issue by xiptos** [deeplearning4j/deeplearning4j#9667]
#### Issue Description

When training ParagraphVectors in CUDA an exception is thrown. In CPU, it trains correctly and without errors.

#### Version Information

* Deeplearning4j 1.0-M2
* Ubuntu
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

* CUDA version
* NVIDIA driver version
```
Tue Apr 12 09:58:22 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.54       Driver Version: 510.54       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN V      Off  | 00000000:00:10.0 Off |                  N/A |
| 28%   37C    P8    26W / 250W |      5MiB / 12288MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1328      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
```
#### Additional Information

https://gist.github.com/xiptos/176d49d7cb03bfd8835554ee68075ef4

#### Contributing

I'm available to help to fix the issue, if possible.

**Comment by agibsonccc** [comment]
@xiptos we're not going to fix this one. It's always going to be slower on gpu and those models were built with cpu in mind.

**Comment by xiptos** [comment]
@agibsonccc, I understand, sure! :)
However, in classification, when I'm combining doc2vec with LSTM, both will have to run in CPU, right?

**Comment by agibsonccc** [comment]
@xiptos you would generally want to train those vectors and then load them in separately.

**Comment by xiptos** [comment]
@agibsonccc, is the ParagraphVectors class thread safe? Can I share an instance by multiple threads? Or would it be better to create a different instance in each thread?

**Comment by agibsonccc** [comment]
@xiptos for just using it as an embedding it's fine. The training itself is actually multi threaded but just updates sections of the embeddings at a time.

**Comment by xiptos** [comment]
@agibsonccc, I have sets of 3000 documents to embed. I'm running on a thread ripper with 32 core. You're saying that I can have a single ParagraphVectors object and share the same object in all the threads to  inferVector? Currently I'm creating a new ParagraphVector in each thread, but I'm limmited because of the RAM to 4 threads.

**Comment by treo** [comment]
You should keep in mind that DL4J (or rather ND4J) is making use of multiple threads during computation, so you don't necessarily want 32 threads, each one with its own ParagraphVectors instance.

**Comment by xiptos** [comment]
Right!!! Thank you, @treo.
@agibsonccc, the issue about infer the ParagraphVectors embedding and classify with LSTM in different processes is that is requires some Interprocess Communication mechanism, such as sockets or RMI (or just monitoring some directory). It would be faster and easier if it would be possible to use CPU and GPU in the same process, the first for the ParagraphVectors and the second for the LSTM. I understand that the priority can be selected for the process with BACKEND_PRIORITY_?PU system variable. But is it possible to use both in the same process in different parts of the code?

I'm refering to the classification part, not the training... :)
