### ISSUE TITLE
OmpNumThreads is hardcoded to 4 in M2 Release

### ISSUE THREAD

**Issue by partarstu** [deeplearning4j/deeplearning4j#9668]
#### Issue Description

- expected behavior - NativeOpsHolder allows to set the ompNumThreads amount based on OMP_NUM_THREADS environment variable
- encountered behavior - In org.nd4j.nativeblas.NativeOpsHolder#NativeOpsHolder(), line 107 this variable is hardcoded to 4

#### Version Information

* Deeplearning4j version - M2
* Platform information (OS, etc) - Windows 10
* CUDA version, if used - N/A
* NVIDIA driver version, if in use - N/A

#### Additional Information

N/A

#### Contributing

The fix is simply removing the mentioned above line 107. The correct assignment is already done in lines 94-106

**Comment by agibsonccc** [comment]
@partarstu thanks that was a  left over debug line that has been completely removed. It was commented out before. I already have a commit prepared with a bunch of fixes and will push that within the next day or 2.

**Comment by partarstu** [comment]
No problem. This value can always be explicitly reset after backend initialization as a workaround using `NativeOpsHolder.getInstance().getDeviceNativeOps().setOmpNumThreads(threadsForOmp)`;

**Comment by quickwritereader** [comment]
this was fixed in vednn Pr. actually I removed it long ago. somehow it re-appeared ,again, which I had to remove again.
