### ISSUE TITLE
(Further) Optimize CNNs

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#967]
Based on current ND4J/DL4J: it seems there is some further room for improvement on CNNs, in terms of performance.
Running LenetMnistExample as of https://github.com/deeplearning4j/dl4j-0.4-examples/pull/54: seems like there are some significant overheads (reshaping etc with copying) that need to be eliminated.

![image](https://cloud.githubusercontent.com/assets/2360237/11841673/fd2ddb70-a452-11e5-8861-7b8fcbeb02f8.png)

![image](https://cloud.githubusercontent.com/assets/2360237/11841703/2b595b32-a453-11e5-9bdf-048305d1f6d3.png)

**Comment by agibsonccc** [comment]
Moved over to native impl now.
