### ISSUE TITLE
Memory-related JVM crash on Linux 

### ISSUE THREAD

**Issue by partarstu** [deeplearning4j/deeplearning4j#9671]
#### Issue Description
- expected behavior - when memory allocation is not possible (insufficient RAM available), an exception in JVM itself is thrown. Previously it worked this way by checking first if the allocation is possible based on the requested array's length
- encountered behavior - JVM is crashed, which makes gracious clean-up, emergency save etc. impossible

#### Version Information

* Deeplearning4j version - **M2**
* Platform information (OS, etc) - Linux (Buster 10)
* CUDA version, if used - N/A
* NVIDIA driver version, if in use - N/A

#### Additional Information

The error log is attached [here](https://gist.github.com/partarstu/fc185be49e2951b1f6cc9d268086d349)

The assumption that this crash is being caused by insufficient RAM availability has been concluded by running the model training with different batch sizes and keeping track of available physical memory. After increasing the batch size I've managed to reproduce the issue almost instantly, with smaller batch it happened after 10-15 iterations.

**Comment by quickwritereader** [comment]
@partarstu 
did you start to get such problems with the new one? Just for confirmation, was M1 working as expected?
Thanks.

**Comment by partarstu** [comment]
@quickwritereader yes - in M1 I simply got different errors/exceptions based on which component detected that another chunk of ByteArray can't be allocated inside native memory. But all of them happened inside JVM and could be intercepted. 

One more thing, I guess it's important. I use the following lines of code in order to configure memory-related options:
```
System.setProperty("org.bytedeco.javacpp.logger.debug", "false");
System.setProperty("org.bytedeco.javacpp.maxphysicalbytes", MAX_JVM_MEMORY);
if (USE_CACHING) {
      System.setProperty("org.bytedeco.javacpp.maxbytes", MAX_NATIVE_MEMORY);
   } else {
       System.setProperty("org.bytedeco.javacpp.maxbytes", "0");
}
```
Previously this logic allowed me to control the memory limits for ND4J native-backend. So lowering MAX_JVM_MEMORY having batch size unchanged would at some point cause an error or exception which makes sense. But with M2 I tried changing those values and limiting them, but JVM crash happened anyway and it seemed like those system properties were either ignored or not fully taken into account by the allocation logic. Could it be the case?

**Comment by agibsonccc** [comment]
@partarstu I thought about this a bit and generally I would recommend not trying to manually control this kind of thing yourself from the JVM. I would focus on using workspaces more or if you really need to, we have a way of automatically triggering gc on a fixed interval already.  Take a look more at this here: https://deeplearning4j.konduit.ai/v/en-1.0.0-m1.1/multi-project/explanation/configuration/memory#memory-management-for-nd4j-dl4j-how-does-it-work
https://deeplearning4j.konduit.ai/v/en-1.0.0-m1.1/multi-project/explanation/configuration/memory/workspaces


Nothing really changed in M2 from M1.1 that would cause anything new to happen here. You can see what changed here: https://deeplearning4j.konduit.ai/release-notes/1.0.0-m2 you'll basically just see java 9, samediff training changes (one that introduced the regression that's been fixed) and some scala related changed. 

Looking at this again just to be sure though I did make sure the new SDValue changes didn't affect GC too much: https://github.com/eclipse/deeplearning4j/pull/9682

What you *could* be seeing isn't so much this direct problem but more of just the GC not being triggered properly.

Generally javacpp tracks memory usage already (as do our allocators)  so an OOM crash from c++ is actually something in the kernel which could mean another issue. I'd need  more to go on if that's the real issue (and it should be a new issue with a reproducer and a more direct description of the problem)

**Comment by partarstu** [comment]
@agibsonccc this manual control was done after I read about those settings in a couple of threads. Without those settings I had some other issues. Without explicitly setting "org.bytedeco.javacpp.maxphysicalbytes" I think I saw similar issue to the one for which this ticket is created. I need to double-check that. Setting "org.bytedeco.javacpp.maxbytes" to zero was previously recommended in order to avoid some issues in Linux (there were one or two threads regarding this one on https://community.konduit.ai/ forum).

What I'm sure of is that after rolling back to M1.1 using the same source code and config, too huge batch size started causing again exceptions being thrown during allocation whereas in M2 there was simply a JVM crash. I'll try to remove those properties and re-run the model on M1.1 without them having a too huge batch size and see what happens.

**Comment by agibsonccc** [comment]
@partarstu appreciated if you could help narrow this down to something a bit more concrete!

**Comment by partarstu** [comment]
@agibsonccc I've done a couple of testing rounds. The findings:

1. **org.bytedeco.javacpp.maxphysicalbytes** must be set up in my case because by default its value is being initialized to ~ 20% of available RAM which is definitely not what I want (and I guess in any PROD environment MLOps would be willing to have this configurable)
2. If  **org.bytedeco.javacpp.maxphysicalbytes** is not approaching available RAM limits, in both **M2** and **M1.1** OOM error is thrown, an example: ```
Caused by: java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes (12460M) > maxPhysicalBytes (12288M)
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:733)
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:126)```

4. If  **org.bytedeco.javacpp.maxphysicalbytes** approaches the available RAM limits, the behavior depends on **org.bytedeco.javacpp.maxbytes** property. If this prop is not initialized, in both **M1.1** and **M2** JVM crash happens (in Windows only one error message line is written, in Linux there's a full error stack trace). If however this prop is set to **0**, in **M2** JVM still crashes but in **M1.1** the following exception is thrown:  ```
java.lang.RuntimeException: Allocation failed: [std::bad_alloc]
	at org.nd4j.nativeblas.OpaqueDataBuffer.allocateDataBuffer(OpaqueDataBuffer.java:76)
	at org.nd4j.linalg.cpu.nativecpu.buffer.BaseCpuDataBuffer.<init>(BaseCpuDataBuffer.java:284)
	at org.nd4j.linalg.cpu.nativecpu.buffer.FloatBuffer.<init>(FloatBuffer.java:64)
	at org.nd4j.linalg.cpu.nativecpu.buffer.DefaultDataBufferFactory.create(DefaultDataBufferFactory.java:293)
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1455)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:320)
	at org.nd4j.linalg.cpu.nativecpu.NDArray.<init>(NDArray.java:187)
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.createUninitializedDetached(CpuNDArrayFactory.java:233)
	at org.nd4j.linalg.factory.Nd4j.createUninitializedDetached(Nd4j.java:4428)
	at org.nd4j.linalg.factory.Nd4j.createUninitializedDetached(Nd4j.java:4435)
	at org.nd4j.autodiff.samediff.internal.memory.ArrayCacheMemoryMgr.allocate(ArrayCacheMemoryMgr.java:135)```

So the summary is the following : initializing **org.bytedeco.javacpp.maxbytes** with 0 helps avoiding JVM crash if the available RAM is lower than the limit set in **org.bytedeco.javacpp.maxphysicalbytes** property. And this is really good. But in **M2** this "feature" is either gone or modified. Anyway, what used to throw an exception in all previous releases incl. **M1.1** allowing to handle graceful termination including emergency saves etc. doesn't do it anymore in M2. 
I don't know if it's a regression or an expected behavior, but in my opinion having an exception instead of a JVM crash is of a really good use.
