### ISSUE TITLE
PyTorch importation

### ISSUE THREAD

**Issue by DangTu97** [deeplearning4j/deeplearning4j#9675]
Hi everyone,

It is true that  more and more DL models are built based on PyTorch but I can only find [examples](https://github.com/eclipse/deeplearning4j-examples/tree/master/tensorflow-keras-import-examples) for Tensorflow/Keras importation. Is it possible to import PyTorch model into Deeplearning4j? If yes, could you guys show me some instructions. 
I would really appreciate this, thank you in advance !

**Comment by agibsonccc** [comment]
@DangTu97 yes this happens via onnx. If you have a particular graph please convert it and feel free to open a separate issue. You may see how to convert it from our contrib folder here: https://github.com/eclipse/deeplearning4j/blob/master/contrib/omnihub/src/omnihub/frameworks/pytorch.py#L75

Please note the onnx convert here. If you have a specific model to convert please ask around on the forums: https://community.konduit.ai/

**Comment by DangTu97** [comment]
@agibsonccc Thank you for your recommendation, it's really helpful.
