### ISSUE TITLE
COMPILATION ERROR

### ISSUE THREAD

**Issue by baedaron** [deeplearning4j/deeplearning4j#9686]
#### Issue Description

mvn clean install -Pcpu -B -V -U -T 12 -e -pl 'org.nd4j:nd4j-native' -Dclassifiers=windows-x86_64-avx2 -Djavacpp.platform=windows-x86_64 -Djavacpp.platform.extension=-avx2 -Djavacpp.helper=openblas -Dlibnd4j.platform=windows-x86_64 -Dlibnd4j.extension=avx2 -Dlibnd4j.helper=openblas -DskipTests -DskipJavaDocs -Dmaven.javadoc.skip=true -Dmaven.test.skip=true
--------------------------------------------------------------------------------------------------------------------------------------------------
.
.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/Administrator/Downloads/DeepLearning4J/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/nativeblas/Nd4jCpu.java:[13,49] cannot find symbol
  symbol:   class Nd4jCpuHelper
  location: package org.nd4j.nativeblas
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  37.451 s (Wall Clock)
[INFO] Finished at: 2022-05-05T03:04:35+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (compile) on project nd4j-native: Compilation failure
.
.

**** ====> Perhaps, the class location should be "package org.nd4j.presets.cpu". ****

#### Version Information

DL4J Current Snapshot
Windows10 21H1
gcc.exe (Rev1, Built by MSYS2 project) 11.3.0

**Comment by agibsonccc** [comment]
@IanBoden please try again with the latest merge against master. That doesn't have any issues that I can see. I'll close this for now but feel free to ping me if you have anymore issues.
