### ISSUE TITLE
Pairwise cosine similarity

### ISSUE THREAD

**Issue by Euklios** [deeplearning4j/deeplearning4j#9695]
#### Issue Description

Please describe our issue, along with:
I'm in need of a pairwise cosine similarity similar to the pythons [sklearn implementation](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.cosine_similarity.html).
I tried using the NDMath.cosineSimilarity method, however, this produces a single value, while I need the entire matrix.

To my understanding, the sklearns pairwise implementation produces the resulting matrix by comparing all vectors using cosineSimilarity and storing the resulting value in a new matrix.
Therefore running following line for each xIndex, yIndex pairing:
```java
result.put(xIndex, yIndex, new NDMath().cosineSimilarity(x.getRow(xIndex), y.getRow(yIndex)));
```
This did hold true during my testing.
However, it was magnitudes slower than the sklearn implementation.

So to my question:
Is there an alternative method that produces the same result as the sklearn implementation?

#### Version Information

* Deeplearning4j version: 1.0.0-M2
* Nd4j-native version: 1.0.0-M2

Testet on:
* Windows 10 21H2, i7-9750H
* Windows 10 21H2, AMD Ryzen 9 3950X
* ArchLinux, Kernel Version: 5.15.38-1, Intel i9-10885H

#### Contributing

If the functionality doesn't exist, is deemed beneficial for the library, and can be done by a complete newbie to the lib, then I'd love to contribute.

**Comment by agibsonccc** [comment]
@Euklios see if this work for you: https://github.com/eclipse/deeplearning4j/blob/e746bcf7c9a21a8287fbb2bcf7ef9f5ff9cfaf88/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/ops/transforms/Transforms.java#L91 if not I'll look closer at this soon.

Post on the forums at https://community.konduit.ai next time for more visibility. Issues are assumed to be bugs.
