### ISSUE TITLE
I'm training a MLP network and got java.lang.IllegalArgumentException: Index [1] must not be >= shape[d].

### ISSUE THREAD

**Issue by wangyu0air** [deeplearning4j/deeplearning4j#970]
here is the version i used in pom.xml
<properties>
        <nd4j.version>0.4-rc3.7</nd4j.version>
        <dl4j.version>	0.4-rc3.7</dl4j.version>
        <canova.version>0.0.0.13</canova.version>
        <jackson.version>2.5.1</jackson.version>
    </properties>

here is my configuration for MLP network
MultiLayerConfiguration conf = new NeuralNetConfiguration.Builder()
                .seed(seed)
                .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
                .iterations(iterations)
                .gradientNormalization(GradientNormalization.RenormalizeL2PerLayer)
                .learningRate(1e-1f)
                .momentum(0.5)
                .momentumAfter(Collections.singletonMap(3, 0.9))
                .useDropConnect(true)
                .list(2)
                .layer(0, new DenseLayer.Builder()
                        .nIn(numRows * numColumns)
                        .nOut(1000)
                        .activation("relu")
                        .weightInit(WeightInit.XAVIER)
                        .build())
                .layer(1, new OutputLayer.Builder(LossFunction.NEGATIVELOGLIKELIHOOD)
                        .nIn(1000)
                        .nOut(outputNum)
                        .activation("softmax")
                        .weightInit(WeightInit.XAVIER)
                        .build())
                .build();

Any idea?

**Comment by agibsonccc** [comment]
Conf issue discussed in gitter. Closing.
