### ISSUE TITLE
Nd4j.shuffle

### ISSUE THREAD

**Issue by LostSummer233** [deeplearning4j/deeplearning4j#971]
This method does not give a shuffle evenly.
If we view an ndarray as a list of vectors, then a vector with small index in the original list is more likely to have a small index in the new list after the shuffle, and so does a vector with large index.

The thing is that, in this method, every time after we swap the places of two vectors, we need to renew the value of the new index in 'vectorsAlongDimension', too.

**Comment by agibsonccc** [comment]
Could you migrate this to the nd4j repo? Thanks!
