### ISSUE TITLE
Improve error handling for RecordReaderDataSetIterator

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#972]
CSVRecordReader + RecordReaderDataSetIterator: if the CSV has a malformed line, the iterator can throw an obscure exception such as: Exception in thread "main" java.lang.IllegalArgumentException: Index [1] must not be >= shape[d].
This doesn't tell the user anything about what is actually wrong.

**Comment by Ingwar** [comment]
The same thing is also true for `ImageRecordReader` + `RecordReaderDataSetIterator`: if some image is malformed, has wrong size or something, you get the same obscure exception. I think that idea to improve error handling to include some source information (file name for `ImageRecordReader`, line number for `CSVRecordreader` etc) is a great one.

**Comment by AlexDBlack** [comment]
This was added a long  time ago; validated here given recent refactoring: https://github.com/deeplearning4j/deeplearning4j/pull/3570
