### ISSUE TITLE
Bug in org.deeplearning4j.models.embeddings.loader.WordVectorSerializer

### ISSUE THREAD

**Issue by j-d-o** [deeplearning4j/deeplearning4j#9727]
#### Issue Description

Hello,

In "org.deeplearning4j.deeplearning4j-nlp" in class org.deeplearning4j.models.embeddings.loader.WordVectorSerializer I suspect a bug when when comparing my current v0.9.1 against the new v1.0.0-M2.

In method: "**protected static TokenizerFactory getTokenizerFactory(VectorsConfiguration configuration)**"  (see https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/loader/WordVectorSerializer.java in line 2609: 

`  Object preProcessor = DL4JClassLoading.createNewInstance(tokenizerFactoryClassName);`

is wrong. Instead of using the "tokenPreProcessorClassName" variable to create the instance, the "tokenizerFactoryClassName" variable is used, so a object is retrieved that is not a "TokenPreProcess" subtype and so the following setting of the token-preprocessor will never happen. It should be:

`  Object preProcessor = DL4JClassLoading.createNewInstance(tokenPreProcessorClassName);`

#### Version Information

* Seen on "org.deeplearning4j.deeplearning4j-nlp" class WordVectorSerializer ,  v1.0.0-M2, behaves correctly on  v0.9.1
* no specific platform - bug/typo in source

**Comment by agibsonccc** [comment]
@j-d-o if you want feel free to submit a pull request otherwise I'll take a look as soon as I can. Thanks!

**Comment by j-d-o** [comment]
I have no clue about your branching, so this one tries to merge into master ... sorry if this doesnt help
