### ISSUE TITLE
Compile nd4j with minifier="true"

### ISSUE THREAD

**Issue by georgiosk83** [deeplearning4j/deeplearning4j#9748]
#### Issue Description

I am trying to compile nd4j with the minified libnd4j for arm64.
Everything runs fine when compiling the libnd4j with minifier="true", and it creates the same libnd4jcpu.so file as without the minifier and a file named "minifier" which is half the size.
Then, I run the maven command to build the nd4j jars, it executes correctly, but the nd4j-native-1.0.0-beta2-android-arm64.jar file has as lib the large libnd4jcpu.so and not the minifier - it is the same whether I use the minifier="true" or not.

#### Version Information

The versions I tried this are beta2 and beta4. No CUDA, just cpu. I compile for arm64 using android-ndk-r16b.

#### Additional Information

The command for compiling the nd4j:
mvn clean install -Djavacpp.platform=android-arm64 -DskipTests -Dmaven.javadoc.skip=true -pl '!:nd4j-cuda-9.2,!:nd4j-cuda-9.2-platform,!:nd4j-tests'

The command for compiling the libnd4j:
bash buildnativeoperations.sh -platform android-arm64

after I edited the buildnativeoperations.sh to set the minifier="true"

#### Contributing

I could describe the steps to use the minifier since for now there is no documentation on it.

**Comment by agibsonccc** [comment]
@georgiosk-lerna you'll want to run it like this, below is a dockerfile for you to use if you want.
Replace the softmax;add;matmul
in the ops section with the ops you want to include. 
You can do the same with datatypes as well.

Feel free to post on the forums: https://community.konduit.ai/ if you need more help. I'm closing this since it isn't a bug.
```


FROM ubuntu:18.04
RUN apt-get update && apt-get -yq  install git  wget unzip openjdk-11-jdk curl python3
RUN    apt-get -yq  update && apt-get install -y build-essential unzip libssl-dev  && \
            curl -fsSL http://cmake.org/files/v3.19/cmake-3.19.0.tar.gz | tar xz && cd cmake-3.19.0 && \
                              ./configure --prefix=/opt/cmake && make -j2 && make install && cd .. && rm -r cmake-3.19.0

RUN    curl -fsSL https://github.com/google/protobuf/releases/download/v3.8.0/protobuf-cpp-3.8.0.tar.gz \
                                   | tar xz && \
                                   cd protobuf-3.8.0 && \
                                   ./configure --prefix=/opt/protobuf && \
                                   make -j2 && \
                                  make install && \
                                   cd .. && \
                                   rm -rf protobuf-3.8.0
RUN wget  https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz && tar xvf apache-maven-3.8.6-bin.tar.gz && mv apache-maven-3.8.6 /root/mvn
RUN cd /root && git clone https://github.com/eclipse/deeplearning4j --branch ag_importcache_graalvm
RUN cd /root/deeplearning4j && mkdir openblas_home  && cd openblas_home &&  \
                         wget https://repo1.maven.org/maven2/org/bytedeco/openblas/0.3.19-1.5.7/openblas-0.3.19-1.5.7-android-arm.jar && \
                         unzip openblas-0.3.19-1.5.7-android-arm.jar

ENV OPENBLAS_PATH=/root/deeplearning4j/openblas_home/lib/armeabi-v7a
ENV BUILD_USING_MAVEN=1
ENV PATH=/root/mvn/bin:/opt/protobuf/bin:/opt/cmake/bin:${PATH}
ENV NDK_VERSION=r21d
ENV CURRENT_TARGET=linux-arm
ENV LIBND4J_CLASSIFIER=linux-arm
ENV MODULES="-Dlibnd4j.operations='softmax;add,matmul' -Dlibnd4j.datatypes=float -Dlibnd4j.lto=ON"
RUN cd /root/deeplearning4j/libnd4j && ./pi_build.sh
```
