### ISSUE TITLE
ParagraphVectors infervector issue after upgrading to M2 version

### ISSUE THREAD

**Issue by kiransarv** [deeplearning4j/deeplearning4j#9750]
Hi All... 

I have upgraded my DL4J from beta to M2 version. After upgrading, I updated the libraries (so files) from the following links. 

https://repo1.maven.org/maven2/org/bytedeco/openblas/0.3.19-1.5.7/openblas-0.3.19-1.5.7-linux-x86.jar
https://repo1.maven.org/maven2/org/nd4j/nd4j-native/1.0.0-M2/nd4j-native-1.0.0-M2-linux-x86_64-compat.jar (as I have older GLIBC version)

But after the upgrade ParagraphVectors inferVector started failing functionally on the same word vector. There is a shape mismatch which indicates the PV is not inferring at all after upgrade.

Older version is inferred vector shape is (1, 300) whereas the new one is inferred the shape (1, 1)

Why it is happening like this ? Any other libs or packages I am missing ?

**Comment by agibsonccc** [comment]
@kiransarv ParagraphVectors hasn't changed for a while. Could you try with snapshots to see if this is still a problem? I would also appreciate a small reproducer program so I can see the issue. Without a stack trace it's going to take me time to guess what your problem is or where this could be happening.

**Comment by kiransarv** [comment]
@agibsonccc Thanks for the info.. Here is the scenario.. I have trained Paragraph Vectors using DL4J in older version.. I am reusing the PV model in both the older version and newer version. When i infer using inferVector Here is the difference in output.. 

<some_text> :: Rank: 2, DataType: FLOAT, Offset: 0, Order: c, Shape: [1,1],  Stride: [1,1] (New Version)
<som_text> ::   Rank: 2, Offset: 0 Order: c Shape: [1,100],  stride: [1,1] (Older Version)

**Comment by agibsonccc** [comment]
@kiransarv there might be some issue with the way newer models are handled and vectors. It used to be that old vectors had to be 2d but now most are 1d. Could you do what I asked and give me a reproducer? I can't just take your description and turn that in to code. You're already describing potential issue sources like an old model among other things.

**Comment by kiransarv** [comment]
@agibsonccc I have not changed my code. There is no runtime error also. There are few compilation errors and I have fixed  them. They are all due to some API changes from beta to M2. Then I ran PV inference on few test data and it started failing. Reproducer Train a PV model in beta and try to infer the vectors in M2 and you should see the shape mismatch.

**Comment by agibsonccc** [comment]
@kiransarv sorry not sure what you mean. I literally need *something* from you specifically that reproduces this problem. I want actual phsyical java code with a model that shows this issue. I am sorry if I confused you earlier but I am mentioning I need *anything* specific to you that would help reproduce this. I am not going to spend time on this otherwise. That could be your old model and some code to run it or anything.

I am not going to chase this down just based on an issue description and what you think the problem is. Then I have to debug what you think the problem is + your opinion on the problem. That usually ends up being a waste of time.

Give me a stack trace with real code + your model or something that shows the issue. How you do that is up to you. I don't need anything that's secret to your company or anything. I only want to help fix your issue. How you give that to me is up to you.

**Comment by kiransarv** [comment]
Got you.. let me in that case pull the code from repo, run it as a standalone and share the code and data with you

**Comment by agibsonccc** [comment]
Thanks for the understanding. I know it's a hassle but it will allow me to focus on just solving the problem rather than guessing where it could be.

**Comment by kiransarv** [comment]
@agibsonccc figured out the shape issue there is slight change in the setSyn0 method in InMemoryLookupTable between old vs new version which is causing the vector dimension set to 1. 

But now I am observing slowness in the inference times after upgrade... Here is the output of both old and M2 version.

Dataset used: https://www.kaggle.com/datasets/therohk/million-headlines?resource=download (select first 10k lines)

Old version (beta) output 
Time to train NN embedding model, Docs size :: 10000 :: 135804 ms
Total vocab size :: 2430 :: 100
Avg time for inference, for 500 instances is 0 ms

M2 version output
Time to train NN embedding model, Docs size :: 10000 :: 70719 ms
Total vocab size :: 2430 :: 100
Avg time for inference, for 500 instances is 27 ms

Below is the code to reproduce the issue... The libs(dylib) are copied from the below Url's 
https://repo1.maven.org/maven2/org/bytedeco/openblas/0.3.19-1.5.7/openblas-0.3.19-1.5.7-macosx-x86_64.jar
https://repo1.maven.org/maven2/org/nd4j/nd4j-native/1.0.0-M2/nd4j-native-1.0.0-M2-macosx-x86_64.jar


Code to reproduce the issue

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import org.apache.commons.io.FileUtils;
import org.deeplearning4j.models.paragraphvectors.ParagraphVectors;
import org.deeplearning4j.text.documentiterator.LabelAwareIterator;
import org.deeplearning4j.text.documentiterator.LabelledDocument;
import org.deeplearning4j.text.documentiterator.SimpleLabelAwareIterator;
import org.deeplearning4j.text.tokenization.tokenizerfactory.DefaultTokenizerFactory;

public class ParagraphVectorsM2 {
	private static final String[] MAC_OS_LIBRARIES_M2 = {"gcc_s.1", "jniopenblas", "gfortran",
			"jniopenblas_nolapack", "openblas", "gomp", "gomp.1", "stdc++", "stdc++.6", "nd4jcpu", "jnind4jcpu"};
	
	private static final String[] MAC_OS_LIBRARIES_OLD = { "gomp", "gomp.1", "stdc++", "stdc++.6", "nd4jcpu", "jnind4jcpu",
			"gcc_s", "gcc_s.1", "jniopenblas", "openblas" };
		
	
	public static void main(String[] args) throws IOException {
		// TODO Auto-generated method stub
		for (String library : MAC_OS_LIBRARIES_OLD) {
			System.loadLibrary(library);
			System.out.println("Loaded library: " + library);
		}
		System.setProperty("org.bytedeco.javacpp.loadlibraries", "false");
		
		File file = new File("/Users/kiran.sarvabhotla/Downloads/temp.txt");
		List<String> lines = FileUtils.readLines(file, "UTF-8");
		buildAndInferPV(lines);
	}

	private static void buildAndInferPV(List<String> lines) throws IOException {
		// TODO Auto-generated method stub
		long start = System.currentTimeMillis();
		List<LabelledDocument> docs = new ArrayList<LabelledDocument>();
		for(int i = 0; i < lines.size(); i++) {
			LabelledDocument labelledDocument = new LabelledDocument();
			labelledDocument.setContent(lines.get(i).toLowerCase());
			labelledDocument.setId(String.valueOf(i));
			docs.add(labelledDocument);
		}
		
		LabelAwareIterator labelAwareIterator = new SimpleLabelAwareIterator(docs);
		ParagraphVectors vocabulary = new ParagraphVectors.Builder()
				.batchSize(64)
				.epochs(50)
				.trainWordVectors(true)
				.trainSequencesRepresentation(true)
				.allowParallelTokenization(false)
				.minWordFrequency(5)
				.layerSize(100)
				.tokenizerFactory(new DefaultTokenizerFactory())
				.iterate(labelAwareIterator)
				.enableScavenger(true)
				.build();

		// 4. train/create a model
		vocabulary.fit();
		System.out.println("Time to train NN embedding model, Docs size :: " + lines.size() + " :: " + (System.currentTimeMillis() - start) + " ms");
		
		inferVector(vocabulary, lines);
	}
	
	private static void inferVector(ParagraphVectors pv, List<String> lines) {
		System.out.println("Total vocab size :: " + pv.vocab().numWords() + " :: " + pv.getLookupTable().layerSize());
		int count = 0;
		
		long start = System.currentTimeMillis();
		long time = 0;
		long infertime = 0;
		
		for(String text : lines) {
			if(count >= 500)
				break;
			
			try {
				start = System.currentTimeMillis();
				pv.inferVector(text);
				infertime = (System. currentTimeMillis() - start);
				time += infertime;
				//System.out.println(text + " :: " + arr.sumNumber() + " :: " + arr.shapeInfoToString() + " Time :: " + infertime);
			} catch(Exception e) {
				//e.printStackTrace();
				//System.err.println("Unable to infer PV for text :: " + text);
			}
			
			count++;
		}
		
		System.out.println("Avg time for inference, for " + count + " instances is " + (time/count) + " ms");
	}
}

**Comment by agibsonccc** [comment]
@kiransarv can you try the M2.1 release? (Just add a .1 on to the M2 version) if that still persists I'll investigate. Thanks!

**Comment by kiransarv** [comment]
Thanks for the reply.. If I am not wrong the change from AggregateSkipGram to SkipGramRound is the root cause... 
https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/learning/impl/elements/SkipGram.java#L375

**Comment by agibsonccc** [comment]
@kiransarv so looking at this....is there any reason you're manually copying libraries and calling System.load(..)? Javacpp already does that for you. Is something broken separately that I should be aware of? None our documentation or examples does this. Just use the nd4j-native-platform dependency or nd4j-native + openblas in maven and you should be fine.

**Comment by agibsonccc** [comment]
@kiransarv I see output like this:
```
Time to train NN embedding model, Docs size :: 1244185 :: 10889 ms
Total vocab size :: 7 :: 100
Arr shape Rank: 2, DataType: FLOAT, Offset: 0, Order: c, Shape: [1,100],  Stride: [1,1]
Arr shape Rank: 2, DataType: FLOAT, Offset: 0, Order: c, Shape: [1,100],  Stride: [1,1]
Arr shape Rank: 2, DataType: FLOAT, Offset: 0, Order: c, Shape: [1,100],  Stride: [1,1]
Arr shape Rank: 2, DataType: FLOAT, Offset: 0, Order: c, Shape: [1,100],  Stride: [1,1]
Arr shape Rank: 2, DataType: FLOAT, Offset: 0, Order: c, Shape: [1,100],  Stride: [1,1]
Arr shape Rank: 2, DataType: FLOAT, Offset: 0, Order: c, Shape: [1,100],  Stride: [1,1]
Arr shape Rank: 2, DataType: FLOAT, Offset: 0, Order: c, Shape: [1,100],  Stride: [1,1]
Arr shape Rank: 2, DataType: FLOAT, Offset: 0, Order: c, Shape: [1,100],  Stride: [1,1]
Arr shape Rank: 2, DataType: FLOAT, Offset: 0, Order: c, Shape: [1,100],  Stride: [1,1]
Arr shape Rank: 2, DataType: FLOAT, Offset: 0, Order: c, Shape: [1,100],  Stride: [1,1]
Arr shape Rank: 2, DataType: FLOAT, Offset: 0, Order: c, Shape: [1,100],  Stride: [1,1]
Arr shape Rank: 2, DataType: FLOAT, Offset: 0, Order: c, Shape: [1,100],  Stride: [1,1]
Arr shape Rank: 2, DataType: FLOAT, Offset: 0, Order: c, Shape: [1,100],  Stride: [1,1]
Avg time for inference, for 500 instances is 0 **ms**
```

Please try to upgrade to M2.1. The vectors are printing out the correct shape. I'm closing this for now. Feel free to come back if you have any issues.
