### ISSUE TITLE
LabelWeight of SameDiff dost not same as it in dl4j

### ISSUE THREAD

**Issue by SidneyLann** [deeplearning4j/deeplearning4j#9751]
I have an input data [miniBatch, sequenceLength, labelNum], and I pass the label weight [labelNum] in dl4j like:
new RnnOutputLayer.Builder(new LossMCXENT(Nd4j.create([labelNum]))))

But I must pass label weight [miniBatch, sequenceLength] in SameDiff like:
sameDiff.loss.softmaxCrossEntropy("loss", label, out, sameDiff.var([miniBatch, sequenceLength])));

Can help to change the behavior in SameDiff and let it accept label weight [labelNum] as the argument as it in dl4j?

**Comment by agibsonccc** [comment]
@SidneyLann you just specify weights as you normally would. We already have supported weights here: https://github.com/eclipse/deeplearning4j/blob/394cf869eee1f773ca0947dc0f67805e46a8eb30/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/samediff/ops/SDLoss.java#L698 Look at logLoss etc here.
