### ISSUE TITLE
Could not find artifact org.nd4j:nd4j-native:jar:windows-x86_64-avx2:1.0.0-M2.1

### ISSUE THREAD

**Issue by fgrilli** [deeplearning4j/deeplearning4j#9754]
#### Issue Description

It looks like the `nd4j-native` artifact with classifier `windows-x86_64-avx2` is no longer available as version 1.0.0-M2.1. No problem when building with previous version.

I haven't found anything in release notes about it.

#### Version Information
1.0.0-M2.1

**Comment by agibsonccc** [comment]
@fgrilli use onednn-avx2 for now. That should be faster anyways. Let me get that reuploaded. Thanks for flagging!

**Comment by fgrilli** [comment]
Cheers!

**Comment by agibsonccc** [comment]
AVX2 is now published. Thanks for flagging.
