### ISSUE TITLE
SameDiff expandDims cannot expand singleton 2D to 3D

### ISSUE THREAD

**Issue by CompilerCrash** [deeplearning4j/deeplearning4j#9765]
#### Issue Description

- expected behavior: SameDiff's `expandDims` method should add an new singleton dimension to any input `SDVariable`, e.g, if the input has shape `[1, 1]` then the output should have shape `[1, 1, 1]`.
- encountered behavior: if the input `SDVariable` has shape `[1, 1]` then the output still has shape `[1, 1]`.

The following code reproduces the error:
```
SameDiff sd = SameDiff.create();
SDVariable v1 = sd.zero(null, 1, 1);
SDVariable v2 = sd.expandDims(v1, -1);
System.out.println(v1.shape().eval()); // [1, 1]
System.out.println(v2.shape().eval()); // should be [1, 1, 1] but is [1, 1]
```

I encountered this error only in the particular case of a `[1, 1]` input shape (i.e., it works for 1D and 3D shapes and also for non-singleton 2D shapes like `[1, 2]` and `[2, 1]`) and only in SameDiff (i.e., the program above works when using `INDArray`s).

#### Version Information

* Deeplearning4j version: 1.0.0-M2.1
* Platform information (OS, etc): Linux Mint 20.3
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

**Comment by agibsonccc** [comment]
@CompilerCrash I fixed this similar to your other issue. https://github.com/deeplearning4j/deeplearning4j/pull/9767
