### ISSUE TITLE
Nd4j expandDims on scalars throws exception when passing -1 as dimension

### ISSUE THREAD

**Issue by CompilerCrash** [deeplearning4j/deeplearning4j#9766]
#### Issue Description

- expected behavior: passing `-1` as `dimension` parameter to `expandDims` adds a new singleton dimension to the input `INDArray` at index `shape.length`. In case of a 0D (scalar) input, `-1` should thus be equivalent to `0`.
- encountered behavior: in the case of 0D `INDArray`s, passing `-1` causes an `ArrayIndexOutOfBoundsException`.

The following code reproduces the error (the exception stack trace is shown below):
```
INDArray v1 = Nd4j.scalar(0); // shape is []
INDArray v2 = Nd4j.expandDims(v1, -1); // throws exception
System.out.println(Arrays.toString(v2.shape())); // shape should now be [1]
```

The exception occurs only when using `INDArray`s. When using `SDVariable`s, it works as expected.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-M2.1
* Platform information (OS, etc): Linux Mint 20.3
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

#### Additional Information

* Full log or exception stack trace:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at org.nd4j.linalg.factory.Nd4j.expandDims(Nd4j.java:406)
	at ExpandDims.main(ExpandDims.java:10)
```

**Comment by agibsonccc** [comment]
@CompilerCrash could you try using:
new NDBase().expandDims(..)?

In the most recent PR there's also Nd4j.base() now.  ExpandDims here should work: https://github.com/eclipse/deeplearning4j/blob/5e65dcade705939c834fb6b58bff9f3a979a036e/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/samediff/ops/SDBaseOps.java#L1049

I'll patch the expandDIms here to have the correct behavior.

**Comment by agibsonccc** [comment]
@CompilerCrash fixed thanks! This was due to an early termination due to some sort of tensorflow compatibility we were doing. This doesn't seem to be an issue anymore.  Also note that I removed the old expandDims logic and have it use our base class which delegates to a c++ kernel instead of 1 off java code. Thanks for flagging!

Note you can use: Nd4j.base() after this is merged instead. This uses our code generated api instead and should be the way forward for accesing various kernels. 
Similar to samediff's cnn() math() nd4j has equivalents of those.

**Comment by CompilerCrash** [comment]
@agibsonccc great, thanks for the fix and the explanation!

**Comment by agibsonccc** [comment]
@CompilerCrash https://github.com/deeplearning4j/deeplearning4j/actions once these builds are done you should be able to try it.

**Comment by CompilerCrash** [comment]
@agibsonccc yup, I can confirm that this issue and #9765 are both fixed in the latest snapshot.
