### ISSUE TITLE
Getting the last element in INDArray is not like numpy in python usin -1 index

### ISSUE THREAD

**Issue by aminechraibi** [deeplearning4j/deeplearning4j#9772]
#### Issue Description
Using python if I want the last element of array x I use -1 index for example
`x = np.array([1, 2, 3, 4])`
`x[-1] # gives 4`
But for ND4J I use -1 as index it gives different result
`INDArray x = Nd4j.create(Arrays.asList(1, 2, 3, 4));`
`x.get(NDArrayIndex.point(-1)) # gives 1`

also in expand_dims I want to use the index -1 in 
`Nd4j.expandDims(x, -1) # gives [[    1.0000,    2.0000,    3.0000,    4.0000]]`
But in python gives `[[1],[2],[3],[4]]`

My problem is in `SDVariable` in `SameDiffLambdaLayer`
I want to use `sameDiff.expandDims(x, lastDim);` but I can't get the lastDim using -1 I tried the  `shape `and `rank ` methods but they don't work
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-M1.1
* OS Windows 10

**Comment by agibsonccc** [comment]
@aminechraibi please use M2.1 or snapshots. I can't reproduce this locally. Closing.
