### ISSUE TITLE
BatchMmul issues follow-up

### ISSUE THREAD

**Issue by CompilerCrash** [deeplearning4j/deeplearning4j#9784]
#### Issue Description

I checked out the new snapshot to try out the revised `batchMmul` op and can confirm that all the issues in #9773 are fixed. However, I have some new remarks about `batchMmul` that you might want to address to improve it:
```
INDArray a = Nd4j.ones(2, 6);
INDArray b = Nd4j.ones(6, 4);
INDArray alpha = Nd4j.scalar(1f);
INDArray beta = Nd4j.scalar(0f);
```
1. All parameters of batchMmul must have floating point types. If they are not, the validation fails. But this happens rather late (especially in Nd4j, where the exception is also a bit cryptic; see below). This doesn't necessarily need to be fixed, but I wonder why the op cannot, e.g., simply use `SDValidation.validateFloatingPoint` instead of `SDValidation.validateNumerical`.
```
INDArray[] res1 = Nd4j.base.batchMmul(alpha.castTo(DataType.INT32), beta.castTo(DataType.INT32), new INDArray[]{a}, b);
System.out.println(res1[0]);
```
2. All parameters must have the same (floating point) type. As this is only validated for `alpha` and `beta`, you may mix, e.g., `FLOAT` and `DOUBLE` data types. This leads to wrong results in both Nd4j and SameDiff.
```
INDArray[] res2 = Nd4j.base.batchMmul(alpha.castTo(DataType.DOUBLE), beta.castTo(DataType.DOUBLE), new INDArray[]{a}, b);
System.out.println(res2[0]);
/*
expected:
[[    6.0000,    6.0000,    6.0000,    6.0000], 
 [    6.0000,    6.0000,    6.0000,    6.0000]]
got:
[[ 8192.0020, 8192.0020,         0,         0], 
 [ 8192.0020, 8192.0020,         0,         0]]
*/
```
3. If I understand GEMM correctly, the formula is `alpha * A * B + beta * C`. Then the `beta` parameter of `batchMmul` seems pointless to me, as you cannot specify a matrix `C` and thus `beta` has no effect at all (in my experiments, no value I passed for `beta` changed the result). You could either remove `beta` from the API or add `C` to the API to resolve this.

#### Version Information

* Deeplearning4j version: 1.0.0-SNAPSHOT
* Platform information (OS, etc): Linux Mint 20.3
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

#### Additional Information

* Exception stack trace for remark 1:
```
Op [batched_gemm] failed check for input [0], DataType: [INT32]
[main] ERROR org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner - Failed to calculate output shapes for op batched_gemm. Attempted to execute with 4 inputs, 0 outputs, 0 targs, 9 iargs, 0 bargs and 0 dargs. Inputs: [(INT,[],c), (INT,[],c), (FLOAT,[2,6],c), (FLOAT,[6,4],c)] - Please see above message (printed out from c++) for a possible cause of error.
Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: Op name batched_gemm - no output arrays were provided and calculateOutputShape failed to execute
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1513)
	at org.nd4j.linalg.factory.Nd4j.exec(Nd4j.java:6566)
	at org.nd4j.linalg.factory.ops.NDBase.batchMmul(NDBase.java:220)
	at Mmul.main(Mmul.java:32)
Caused by: java.lang.RuntimeException: Op batched_gemm with name 53b1008c-c75e-47c9-bab7-f6cfc4deaedc failed to execute. Here is the error from c++: Data types validation failed
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.calculateOutputShape(NativeOpExecutioner.java:1674)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.calculateOutputShape(NativeOpExecutioner.java:1580)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:1502)
	... 4 more
```

**Comment by agibsonccc** [comment]
@CompilerCrash actually these interfaces are all generated. I just had to convert the data type to batchMmul. Good catch! Please see: https://github.com/deeplearning4j/deeplearning4j/blob/2668876811fbebf1fafc09f954a34dfcd8c95780/contrib/codegen-tools/codegen/src/main/ops/org/nd4j/codegen/ops/SDBaseOps.kt#L2143 and data types here: https://github.com/deeplearning4j/deeplearning4j/blob/46dbd0b2035fab86f5d500508af46690b97af7c8/contrib/codegen-tools/codegen/src/main/kotlin/org/nd4j/codegen/api/DataType.kt#L25

**Comment by CompilerCrash** [comment]
I've read the term "codegen" here and there, but I didn't know what was actually being generated. Definitely makes sense given the large code base.

**Comment by agibsonccc** [comment]
@CompilerCrash you can find automatically generated definitions for ops as well: https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/resources/nd4j-op-def.pbtxt - that's generated by parsing the java and c++ code bases: https://github.com/deeplearning4j/deeplearning4j/tree/master/contrib/codegen-tools/libnd4j-gen

That's what we use for model import.
