### ISSUE TITLE
SameDiff create op ignores data type

### ISSUE THREAD

**Issue by CompilerCrash** [deeplearning4j/deeplearning4j#9786]
#### Issue Description

- expected behavior: when passing a `DataType` to `sd.create(...)`, the resulting `SDVariable` should have that type.
- encountered behavior: the `SDVariable` returned by `create` always has type `FLOAT`.

Here is an example:
```
SameDiff sd = SameDiff.create();
SDVariable var = sd.create(null, sd.constant(8), DataType.INT32);
System.out.println(var.dataType()); // should be INT32 but is FLOAT
System.out.println(var.eval());
```

Bonus question: Is the returned `SDVariable` really uninitialized? The parameter `initialize` is `false` by default but the result appears to be zero-initialized. Of course, this could simply be because the variable is created in fresh (zero-initialized) memory that has not been allocated ("polluted") by another variable before.

#### Version Information

* Deeplearning4j version: 1.0.0-SNAPSHOT
* Platform information (OS, etc): Linux Mint 20.3
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

**Comment by agibsonccc** [comment]
@CompilerCrash similar to the other issues mainly a serialization problem. Thanks for flagging!
