### ISSUE TITLE
UnsatisfiedLinkError no openblas_nolapack on ios m1 macbook

### ISSUE THREAD

**Issue by RoytenBerge** [deeplearning4j/deeplearning4j#9789]
#### Issue Description

I've been trying to run my kotlin project using gradle with the following implementations:
```
    implementation("org.deeplearning4j:deeplearning4j-core:1.0.0-M1")
    implementation("org.nd4j:nd4j-native-platform:1.0.0-M1")
```

For some reason it just keeps throwing a  `no openblas_nolapack Unsatisfied link` error. I've tried changing nd4j versions but all versions seem to have this issue for me. I've also tried running the code in a rosetta terminal but that didn't solve the issues I'm having. 

The issue seems to be related to this thread https://github.com/deeplearning4j/deeplearning4j/issues/9258 but I can't find a proper solution and the thread has been closed.

It seems like the m1 chip is not properly supported yet or I'm overseeing another solution. Any way I can fix this or is there a plan for having support for m1 chips?

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version -> 1.0.0-M1
* Platform information (OS, etc) -> Macbook pro 16" with an Apple M1 Max
* CUDA version, if used -> not used
* NVIDIA driver version, if in use -> not used

#### Additional Information

Error logs:

https://gist.github.com/RoytenBerge/c0b69d7b666cc66c0ea290b1abd6e5c2

**Comment by treo** [comment]
The M1 version means "Milestone 1" and has nothing to do with the M1 chip. 

If I remember correctly, the M1 chip is only supported starting version M2. The current release is version M2.1.

**Comment by RoytenBerge** [comment]
Thanks I'll upgrade to that version then!

**Comment by agibsonccc** [comment]
@RoytenBerge make sure to keep an eye on the openblas support for M1 as well. I was able to finish the build and run some basic tests but the upstream openblas from javacpp looks like it might not be fully working for certain routines till 1.5.8 or using snapshots: https://github.com/bytedeco/javacpp-presets/issues/1198#issuecomment-1211463789

 in that case you might need to manually override the javacpp openblas versions to the latest snapshots till javacpp can publish a 1.5.8 release and we can tag our latest stable release with that version.
