### ISSUE TITLE
Linear and reluLayer ops cannot handle null bias

### ISSUE THREAD

**Issue by CompilerCrash** [deeplearning4j/deeplearning4j#9791]
#### Issue Description

- expected behavior: according to the docs, the Nd4j and SameDiff ops `linear` and `reluLayer` should accept `null` as `bias` parameter (equivalent to passing a zero vector).
- encountered behavior: when passing `null` as `bias` to these ops, an exception is thrown.

Examples of all four cases that throw exceptions:
```
int b = 2;
int n = 4;

INDArray res1 = Nd4j.nn.linear(Nd4j.ones(b, n), Nd4j.ones(n, n), null);
System.out.println(res1);

SameDiff sd = SameDiff.create();
SDVariable res2 = sd.nn.linear(sd.one(null, b, n), sd.one(null, n, n), null);
System.out.println(res2.eval());

INDArray res3 = Nd4j.nn.reluLayer(Nd4j.ones(b, n), Nd4j.ones(n, n), null);
System.out.println(res3);

sd = SameDiff.create();
SDVariable res4 = sd.nn.reluLayer(sd.one(null, b, n), sd.one(null, n, n), null);
System.out.println(res4.eval());
```

#### Version Information

* Deeplearning4j version: 1.0.0-SNAPSHOT
* Platform information (OS, etc): Linux Mint 20.3
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

#### Additional Information

* Exception stack trace of Nd4j `linear` (`reluLayer` is similar):
```
Exception in thread "main" java.lang.IllegalArgumentException: Input 2 for op class org.nd4j.linalg.api.ops.impl.transforms.custom.XwPlusB was null!
	at org.nd4j.linalg.api.ops.DynamicCustomOp.<init>(DynamicCustomOp.java:141)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.<init>(DynamicCustomOp.java:185)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.<init>(DynamicCustomOp.java:173)
	at org.nd4j.linalg.api.ops.impl.transforms.custom.XwPlusB.<init>(XwPlusB.java:44)
	at org.nd4j.linalg.factory.ops.NDNN.linear(NDNN.java:301)
	at Layers.main(Layers.java:14)
```
* Exception stack trace of SameDiff `linear` (`reluLayer` is similar):
```
Exception in thread "main" org.nd4j.linalg.exception.ND4JIllegalStateException: Found null variable at index 2
	at org.nd4j.autodiff.samediff.SameDiff.addArgsFor(SameDiff.java:1347)
	at org.nd4j.autodiff.functions.DifferentialFunction.<init>(DifferentialFunction.java:564)
	at org.nd4j.linalg.api.ops.DynamicCustomOp.<init>(DynamicCustomOp.java:200)
	at org.nd4j.linalg.api.ops.impl.transforms.custom.XwPlusB.<init>(XwPlusB.java:40)
	at org.nd4j.autodiff.samediff.ops.SDNN.linear(SDNN.java:583)
	at Layers.main(Layers.java:16)
```

**Comment by agibsonccc** [comment]
@CompilerCrash on this one..not sure I agree with this one. It is x * w + b after all. B should be expected. Is the concrete thing you want to be having a bias optional within the layer itself?

**Comment by CompilerCrash** [comment]
@agibsonccc I (ab)used these ops to multiply a batch of vectors with the same matrix. Certainly not the standard use case. I would be fine with leaving it as it is. However, the Javadoc reads `@param bias Optional bias variable (may be null)`. So you should at least adjust the docs [here](https://github.com/deeplearning4j/deeplearning4j/blob/75e1543b85a45e1b63c33a84a73c3b5d6049433a/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/ops/NDNN.java#L294) and [here](https://github.com/deeplearning4j/deeplearning4j/blob/75e1543b85a45e1b63c33a84a73c3b5d6049433a/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/ops/NDNN.java#L472), I'd say.

**Comment by agibsonccc** [comment]
@CompilerCrash ah good catch ok! Yeah let me do that.

**Comment by CompilerCrash** [comment]
@agibsonccc I just noted that the PR #9793 that closed this issue actually only fixed the docs for `reluLayer` but not for `linear`  ([here](https://github.com/deeplearning4j/deeplearning4j/blob/74ca3775d9a01dfcd1b1058e36e33e3c1fbfa93a/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/ops/NDNN.java#L294), [here](https://github.com/deeplearning4j/deeplearning4j/blob/74ca3775d9a01dfcd1b1058e36e33e3c1fbfa93a/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/samediff/ops/SDNN.java#L576), and [here](https://github.com/deeplearning4j/deeplearning4j/blob/74ca3775d9a01dfcd1b1058e36e33e3c1fbfa93a/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/samediff/ops/SDNN.java#L593)). You may want to update them, too.
