### ISSUE TITLE
arrow's FieldVector to nd4j's INDArray

### ISSUE THREAD

**Issue by lzmchina** [deeplearning4j/deeplearning4j#9797]
#### Issue Description
I have some pyarrow vector data which is transported to java arrow flight server. 
In python arrow flight client , my code is like this:
```python
writer,reader=client.do_exchange(descriptor=pa.flight.FlightDescriptor.for_path("streamed.parquet"))
start = time()
writer.begin(schema=schema)
with writer:
    while True:
        pop=q.get()
        if pop is None:
            break
        # print("send")
        batch = pa.record_batch([pa.array(q.get())], schema)
        writer.write_batch(batch)
```
in java arrow flight server, my code is like this:
```java
VectorSchemaRoot vectorSchemaRootReceived = null;
FieldVector v = null;
try {
    while (reader.next()) {
        vectorSchemaRootReceived = reader.getRoot();
        // arb = unloader.getRecordBatch();
        rows += vectorSchemaRootReceived.getRowCount();
        v = vectorSchemaRootReceived.getVector("tensor"); 
    }
}catch (Exception e){
    e.printStackTrace();
}
```
What I want to do is transfer arrow FieldVector type to nd4j's INDArray type.

I known nd4j has some util funcs to transfer Tensor type to nd4j's INDArray type. However i do not know how to transfer arrow FieldVector type to nd4j's INArray type.

So how can i achieve my goals?Please help me,thanks!

**Comment by agibsonccc** [comment]
@lzmchina please use nd4j-arrow for serialization.  ArrowSerde should do what you need: https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-serde/nd4j-arrow/src/main/java/org/nd4j/arrow/ArrowSerde.java if arrow serde doesn't fulfull your needs open an issue with a feature request.
