### ISSUE TITLE
Getting puzzling results with Google model in 3.7

### ISSUE THREAD

**Issue by mikegwf1** [deeplearning4j/deeplearning4j#982]
I am loading the pretrained Google model and using wordsNearest to find closest 10 words, but I am getting results like the following for "analgesic".

Similar words to 'analgesic' : [Guangdong_Province, offline_advertising, lightning_strikes, Heimerdinger, Rua, Homan, Berrian, vuvuzelas, Ludacris, PKS]

When I loop through all the words in model, compute cosine similarity, and keep top 20 results, I am getting the following results:
0: analgesic - 0.9999998807907673
1: Guangdong_Province - 0.7384288210271761
2: lightning_strikes - 0.6762051145174633
3: offline_advertising - 0.6652830248058993
4: Homan - 0.6623727299804038
5: vuvuzelas - 0.6611527628170191
6: Heimerdinger - 0.6589446894757267
7: Rua - 0.6550138428766108
8: Berrian - 0.6470226294940585
9: Cumbria - 0.63485282758588
10: Ludacris - 0.6331226945676749
11: JP_Losman - 0.6291859129972873
12: Hedge_funds - 0.6270258346123097
13: PKS - 0.6266903575205128
14: pork_bellies - 0.6256552262141727
15: AlixPartners - 0.6250132843812553
16: immunities - 0.6240514969518843
17: Oldenburg - 0.6239373688996463
18: Braham - 0.6197403098391009
19: thÐ°t - 0.6179166188836616

I am loading the model as follows:
	        writeToConsole("Loading Serialized Model");
	        File gModel = new File("d:/downloads/dlj4/GoogleNews-vectors-negative300.bin.gz");
	        Word2Vec vec = (Word2Vec) WordVectorSerializer.loadGoogleModel(gModel, true);
	        writeToConsole("Finished Loading Serialized Model");

**Comment by raver119** [comment]
Bug confirmed for 3.7 
***
10:47:09.430 [main] INFO  o.s.GoogleVectors - Evaluate model....
10:47:14.735 [main] INFO  o.s.GoogleVectors - Similar words to 'analgesic' : [Guangdong_Province, lightning_strikes, offline_advertising, Heimerdinger, Homan, Rua, vuvuzelas, Berrian, Ludacris, Cumbria]
***

And looks like its already fixed at current master:
***
11:08:47.182 [main] INFO  o.s.GoogleVectors - Evaluate model....
11:09:33.597 [main] INFO  o.s.GoogleVectors - Similar words to 'analgesic' : [antispasmodic, analgesic_effects, antiemetic, granisetron, analgesics, triptan, anxiolytic, pain_relieving, anticholinergic, bronchodilator]
***
