### ISSUE TITLE
Boolean operations return wrong results

### ISSUE THREAD

**Issue by CompilerCrash** [deeplearning4j/deeplearning4j#9825]
#### Issue Description

I revisited issue #9635 and it seems to me that it is not completely fixed. Some cases work now but others still return wrong results.

- expected behavior: When an operation is applied to two `INDArray`s of different but compatible shapes, broadcasting should be applied correctly.
- encountered behavior: In some cases (only boolean ops in my observations), where broadcasting is required along one axis of one input, the resulting `INDArray` contains wrong entries (yet the shape is correct).

Example:
```
SameDiff sd = SameDiff.create();
SDVariable a = sd.constant(Nd4j.createFromArray(true, false, false, true).reshape(2, 2));
SDVariable b = sd.constant(Nd4j.createFromArray(true, true).reshape(1, 2)); // with .reshape(2, 1) or .reshape(2) it doesn't work either
SDVariable result = sd.math().and(a, b);
System.out.println(result.eval());
/*
expected result:
[[      true,     false],
 [     false,      true]]

actual result:
[[      true,     false],
 [     false,     false]]
*/
```

#### Version Information

* Deeplearning4j version: 1.0.0-SNAPSHOT
* Platform information (OS, etc): Linux Mint 20.3
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

**Comment by agibsonccc** [comment]
@CompilerCrash the bug actually wasn't what you thought it was. The broadcasting was fine. The main problem was constructor initialization. The and/or/xor pairwise ops all have a mode to compare against a scalar or a variable. The scalar was being initialized when it shouldn't be and was causing it to effectively be a no op. Thanks for flagging.

**Comment by CompilerCrash** [comment]
@agibsonccc that explanation makes even more sense. Good to have it fixed now.
