### ISSUE TITLE
Failed to execute goal on project deeplearning4j-ui. Not able to build deeplearning4j-ui

### ISSUE THREAD

**Issue by vlarobbyk** [deeplearning4j/deeplearning4j#984]
Hello!. I am trying to build deeplearning4j but I am not able to compile the deeplearning4j-ui package. All packages have correctly built by maven, however, it is not possible to build the ui package due to the following error: **The POM for org.nd4j:nd4j-jackson:jar:0.4-rc3.8-SNAPSHOT is missing, no dependency information available.**

I have cloned three times the GIT repository and followed the tutorial step by step, but the error persists.
Please, could someone provide me some advice or idea to solve my problem?
Thank you in advance!.

Below are the console messages:

[INFO] Building deeplearning4j-ui 0.4-rc3.8-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/nd4j-jackson/0.4-rc3.8-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/nd4j-jackson/0.4-rc3.8-SNAPSHOT/nd4j-jackson-0.4-rc3.8-SNAPSHOT.pom
[WARNING] The POM for org.nd4j:nd4j-jackson:jar:0.4-rc3.8-SNAPSHOT is missing, no dependency information available
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/nd4j-jackson/0.4-rc3.8-SNAPSHOT/nd4j-jackson-0.4-rc3.8-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] DeepLearning4j ..................................... SUCCESS [  0.682 s]
[INFO] dl4j-test-resources ................................ SUCCESS [ 59.570 s]
[INFO] deeplearning4j-core ................................ SUCCESS [  9.855 s]
[INFO] DeepLearning4j-scaleout-parent ..................... SUCCESS [  0.008 s]
[INFO] deeplearning4j-scaleout-api ........................ SUCCESS [  0.541 s]
[INFO] deeplearning4j-scaleout-zookeeper .................. SUCCESS [  0.507 s]
[INFO] deeplearning4j-scaleout-akka ....................... SUCCESS [  1.510 s]
[INFO] deeplearning4j-graph ............................... SUCCESS [  0.849 s]
[INFO] deeplearning4j-nlp ................................. SUCCESS [ 18.395 s]
[INFO] DeepLearning4j-AWS ................................. SUCCESS [  2.874 s]
[INFO] hadoop-yarn ........................................ SUCCESS [  0.012 s]
[INFO] cdh4 ............................................... SUCCESS [  1.580 s]
[INFO] deeplearning4j-nlp-yarn ............................ SUCCESS [  1.066 s]
[INFO] org.deeplearning4j.spark ........................... SUCCESS [  2.892 s]
[INFO] dl4j-spark ......................................... SUCCESS [ 25.393 s]
[INFO] dl4j-spark-nlp ..................................... SUCCESS [ 23.799 s]
[INFO] dl4j-spark-ml ...................................... SUCCESS [ 55.674 s]
[INFO] deeplearning4j-cli ................................. SUCCESS [  0.005 s]
[INFO] deeplearning4j-cli-api ............................. SUCCESS [  2.292 s]
[INFO] deeplearning4j-ui .................................. FAILURE [  2.267 s]
[INFO] dl4j-caffe ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by AlexDBlack** [comment]
We are recommending that people don't build from source, unless they want to contribute code. Instead, use the versions on Maven central, unless you have a very good reason not to.

Which tutorial are you referring to specifically?

At any rate, are you sure that the dependencies (nd4j and canova) built successfully? You shouldn't see that if they are.
(Speaking of, there was an issue on ND4J master that could cause issues during ND4J build, due to some CUDA refactoring work. I don't believe that has been fixed yet on master.)

**Comment by vlarobbyk** [comment]
Thank you so much for your answer. I have followed the instructions of this page (to clone and build from the sources): 

https://github.com/deeplearning4j/deeplearning4j.

Please, tell me how can I download all libraries needed to use deeplearning4j and his dependencies?

Once again, thank you!

**Comment by AlexDBlack** [comment]
Those instructions are a little out of date, we'll get that updated. Sorry for the confusion.

By far the best way to use DL4J is to use Maven (do some reading on it, if you aren't familiar with it - http://deeplearning4j.org/maven.html).

For example, if you just want to run the examples, follow this: http://deeplearning4j.org/quickstart.html
(i.e., download examples repo, import into an IDE, wait for it to download your dependencies).

You can then use the examples POM file as a starting point for your own projects.

**Comment by AlexDBlack** [comment]
Actually, on second look: those instructions are NOT out of date.
The first method ("Use Maven Central Repository") listed there is what you should be doing. Though perhaps we can clarify that a little.
