### ISSUE TITLE
IfCond and whileLoop backpropagation exception

### ISSUE THREAD

**Issue by CompilerCrash** [deeplearning4j/deeplearning4j#9844]
#### Issue Description

When training a computation graph that contains an `ifCond` or `whileLoop`, I get
```
java.lang.UnsupportedOperationException: Please extend DynamicCustomOp.doDiff to support SameDiff backprop operations. Op: org.nd4j.linalg.api.ops.impl.controlflow.compat.Merge
```
and
```
java.lang.UnsupportedOperationException: Please extend DynamicCustomOp.doDiff to support SameDiff backprop operations. Op: org.nd4j.linalg.api.ops.impl.controlflow.compat.Exit
```
respectively. Looking at the source code, it seems like none of the underlying control flow operations (`switch`, `merge`, `enter`, `exit`, `nextIteration`; see [here](https://github.com/deeplearning4j/deeplearning4j/tree/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/controlflow/compat)) implements the `doDiff` method. However, since apparently differentiation of these constructs is possible in TensorFlow (see [here](http://download.tensorflow.org/paper/white_paper_tf_control_flow_implementation_2017_11_1.pdf)), it should be possible in SameDiff, too. Maybe it is already implemented in C++ and you just need to add the Java wrapper?

(If you need code for testing, you can use [this one](https://github.com/CompilerCrash/DL4J-Bug-Reproduction/blob/master/src/main/java/ControlFlow.java).)

**Comment by agibsonccc** [comment]
@CompilerCrash that's not quite the case...training with control flow happens all the time: rnns, etc. Control flow is actually specially implemented. Those are stub ops we hand implement in the training/inference sessions. Let me see what code path is triggering that regardless though..

**Comment by agibsonccc** [comment]
@CompilerCrash confirmed. Ok let me see here...I do see ifCond + bp triggers this. The embedded use cases seem to be covered but direct use for them seems to be missing here. It should be a straightforward fix. Thanks for flagging!
