### ISSUE TITLE
dataSet.shuffle() will crash the whole project

### ISSUE THREAD

**Issue by Kanbe-Kotori** [deeplearning4j/deeplearning4j#9846]
#### Issue Description

Please describe our issue, along with:
- expected behavior: shuffle the dataset before use splitTestAndTrain()
- encountered behavior: Process finished with exit code -1073741819 (0xC0000005)
- *If I dont use shuffle(), the project works well.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-M2.1
* Platform information (OS, etc) Windows 10, Java 17.0.1
* CUDA version, if used
* NVIDIA driver version, if in use

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by Kanbe-Kotori** [comment]
"C:\Program Files\Java\jdk-17.0.1\bin\java.exe" --add-opens=java.base/java.nio=ALL-UNNAMED "-javaagent:D:\Program Files\IntelliJ IDEA Community Edition 2021.2\lib\idea_rt.jar=3235:D:\Program Files\IntelliJ IDEA Community Edition 2021.2\bin" -Dfile.encoding=UTF-8 @C:\Users\14387\AppData\Local\Temp\idea_arg_file1998443977 cn.nulladev.test.Main
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for linear algebra: 8
o.n.l.c.n.CpuNDArrayFactory - Binary level Generic x86 optimization level AVX512
o.n.n.Nd4jBlas - Number of threads used for OpenMP BLAS: 8
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [16]; Memory: [3.9GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
o.n.l.c.n.CpuBackend - Backend build information:
 GCC: "12.1.0"
STD version: 201103L
DEFAULT_ENGINE: samediff::ENGINE_CPU
HAVE_FLATBUFFERS
HAVE_OPENBLAS

Process finished with exit code -1073741819 (0xC0000005)

**Comment by agibsonccc** [comment]
@Kanbe-Kotori could you clarify a bit? There are a lot of things that could cause that. 
From what I'm seeing it is using cpu. That normally shouldn't have any issues. shuffle() might be a secondary cause of something else. 
Do you have anything like an hs_err something .log in the directory where the crash happened? If I can't reproduce it (which I can't we have tests that cover shuffle on cpu and gpu) then I can't help you.

I would need to know what's different about your case vs our tests. Thanks!

**Comment by Kanbe-Kotori** [comment]
https://gist.github.com/Kanbe-Kotori/127a0b9e6f2871d61c7940e9543b6554 @agibsonccc

**Comment by agibsonccc** [comment]
@Kanbe-Kotori still hard to reproduce... could you please set -Dorg.nd4j.noarraygc=true in the system properties when running? I wonder if there is some sort of array reference being freed. I really need self contained code to know for sure what's going on.

Could you show me what this is? n.nulladev.test.CWRUDataManager.genAnnDataSet()

I don't need or want your proprietary secrets but I do need something to understand more about what's going on. Anything you can show me about the usage of how the dataset gets created would help.

The only thing I can think of is something gets de allocated when you call shuffle.

If I can understand your use case I can suggest a workaround as well.

**Comment by Kanbe-Kotori** [comment]
@agibsonccc https://github.com/Kanbe-Kotori/deeplearning4j-examples/blob/master/dl4j-examples/src/main/java/cn/nulladev/test/CWRUDataManager.java 
method genAnnDataSet() provides a cwru bearing dataset, which failed to call shuffle().
method genAnnDataSetWithoutShuffle() provides the same function but uses vanilla shuffle() in java.util.Collections, and it succeed.

**Comment by agibsonccc** [comment]
@Kanbe-Kotori I downloaded your fork and tried running the relevant code but it looks like you're using some maven dependencies that aren't specified? It looks like you're using a text based mat parser? Could you clean that up?

**Comment by Kanbe-Kotori** [comment]
@agibsonccc That's an unofficial upgrade of a project no longer updated, I'm not sure whether it have a maven repo of this new version so I directly use the src.

**Comment by Kanbe-Kotori** [comment]
I think if the problem still cannot be reproduced, just ignore it. Anyway, I have found and provided a solution

**Comment by agibsonccc** [comment]
@Kanbe-Kotori it's up to you. I'm happy to look in to it. If there is an early de allocation or something we should still make that more obvious. Your dataset did appear to use a lot of streaming which I do believe could result in race conditions. Either way this shouldn't happen with most normal code usage. Let me know if you still want help.
