### ISSUE TITLE
Some questions on the parameters of conv1d

### ISSUE THREAD

**Issue by Kanbe-Kotori** [deeplearning4j/deeplearning4j#9848]
I want to use conv1d to do CNN on some time sequences with fixed length of 512. However, I am confused about the parameters of conv1d. And I didn't find any relevant information or sample on the Internet. The training effect is very poor now. I don't know whether it is the problem of network or parameter. The dl4j forum is only used by few people, so I have to ask questions here...
My question:
1. I see that some 2d networks use convolutionMode(ConvolutionMode.Same). What is its meaning?
2. Should the number of convolution kernels be set in nOut, or elsewhere? I don't know whether nout represents this or the length of conv result?
3. I'm not sure whether the call of padding() is successful, because I can't print the sequence size after processing for each layer?

**Comment by agibsonccc** [comment]
@Kanbe-Kotori just use setInputTYpe. No need to set nIn anything manually. nOut is the number of out channels.

**Comment by Kanbe-Kotori** [comment]
> @Kanbe-Kotori just use setInputTYpe. No need to set nIn anything manually. nOut is the number of out channels.

How can I print the length of the output of an hidden conv layer? You know, convolution without padding results in a reduction in length so I want to check it.

**Comment by agibsonccc** [comment]
@Kanbe-Kotori Try to see if model.summary() gives you what you're looking for

**Comment by Kanbe-Kotori** [comment]
@agibsonccc No, it contains no info about the length of conv result. To be specific, I want to use padding in some layers, but not in others. It's hard for me to know if I'm successful.

my print code: **System.out.println(model.summary(InputType.feedForward(2048)));**
my net structure: https://github.com/Kanbe-Kotori/deeplearning4j-examples/blob/master/dl4j-examples/src/main/java/cn/nulladev/test/NetFactory.java
result: https://gist.github.com/Kanbe-Kotori/87ac1b71d1ebf4a08af1b4b334e1c739

**Comment by agibsonccc** [comment]
@Kanbe-Kotori it tells you the in and out of each layer in the summary. Could you clarify why you think that is exactly? I already mentioned to you once the in/out channels are nIn/nOut in your configuration there.

**Comment by Kanbe-Kotori** [comment]
> @Kanbe-Kotori it tells you the in and out of each layer in the summary. Could you clarify why you think that is exactly? I already mentioned to you once the in/out channels are nIn/nOut in your configuration there.

No, I don't want to check the number of channels (the number of convolution kernels). What I want to know is how to set whether to use padding for conv1d, and also the length of the conv result, which seems not appear in model.summary(). I mean, If I use a kernel with a length greater than 1, the data will lose some length without padding, right? If the length cannot be printed in some way, how can I know whether the padding is successful?

**Comment by agibsonccc** [comment]
@Kanbe-Kotori padding isn't used unless you set it to valid.  It affects the output height/width. I would check for that. In this case, since you set same, padding isn't used even if configured. You can see the configuration here: https://github.com/deeplearning4j/deeplearning4j/blob/d77597bae3253e13a3384a168fda789f68309c1a/libnd4j/include/ops/declarable/helpers/convolutions.h#L49 
You would need to use valid or causal to see any sort of fluctuation.
Add:
```java
   Nd4j.getExecutioner().enableDebugMode(true);
        Nd4j.getExecutioner().enableVerboseMode(true);
```

You can use the above to see the inputs/output shapes of each op.

**Comment by Kanbe-Kotori** [comment]
@agibsonccc Thanks for your reply anyway, although I still don't know how to "set padding to valid", and I also don't know how to set the length of padding (Since the size of convolution kernel may be even, the left and right padding lengths are not necessarily equal). I also failed to find relevant explanations in the official documents. Hope to get a reply.

**Comment by agibsonccc** [comment]
@Kanbe-Kotori sorry I meant the convolution mode. You already had that set in your model. 

I linked you how the heights/widths are affected by the padding and the convolution mode there.  


Will elaborate more tomorrow (sorry late where I am)

**Comment by Kanbe-Kotori** [comment]
@agibsonccc So I should use ConvolutionMode.Strict, and set the length of padding in .padding(x), right?

**Comment by agibsonccc** [comment]
@Kanbe-Kotori yes if you want to use padding you need to use one of the formulas that takes it in to account.

What I linked you there were a few ways of doing convolutions. Depending on which mode you do, some take padding in to account and some don't.
Valid, Same and Casual are the below formulas:
```
f (mode  is valinDepth) {  // valinDepth
      outDepth = (inDepth - ((kD - 1) * depthDepth + 1) + 2 * paddingDepth) / strideDepth + 1;
      outHeight = (inHeight - ((kernelHeight - 1) * depthHeight + 1) + 2 * paddingHeight) / strideHeight + 1;
      outWinDepth = (inWinDepth - ((kernelWinDepth - 1) * depthWidth + 1) + 2 * paddingWinDepth) / strideDepth + 1;
    } else if (mode is same) {  // same
      outDepth = ceil(inDepth * 1. / strideDepth);
      outHeight = ceil(inHeight * 1. / strideHeight);
      outWinDepth = ceil(inWinDepth * 1. / strideDepth);

    } else if mode is causal{  // causal
      outDepth = (inDepth - 1) / strideDepth + 1;
      outHeight = (inHeight - 1) / strideHeight + 1; 
      outWinDepth = (inWinDepth - 1) / strideDepth + 1;
    }
```


I rewrote the above to be a bit more readable. You can see how the convolution mode affects the output channels (depth), height and width now.
