### ISSUE TITLE
Synchronization of loss variables between SameDiff and TrainingConfig

### ISSUE THREAD

**Issue by CompilerCrash** [deeplearning4j/deeplearning4j#9853]
#### Issue Description

This is a follow-up of issue #9684. When fitting a SameDiff graph, the reported loss (as per `ScoreListener` and `LossCurve`) is constantly zero although the learning succeeds. The workaround is to manually pass the names of the loss variables to the used `TrainingConfig` instance. It would still be nice if this wasn't necessary.

Example:
```
int batchSize = 4;
int modelDim = 8;

SameDiff sd = SameDiff.create();

SDVariable features = sd.placeHolder("features", FLOAT, batchSize, modelDim);
SDVariable labels = sd.placeHolder("labels", FLOAT, batchSize, modelDim);
SDVariable bias = sd.var("bias", new OneInitScheme('c'), FLOAT, modelDim);
SDVariable predictions = features.add("predictions", bias);
sd.loss.meanSquaredError("loss", labels, predictions, null);

TrainingConfig config = new TrainingConfig.Builder()
        .updater(new Adam(0.1))
        .dataSetFeatureMapping("features")
        .dataSetLabelMapping("labels")
        // .lossVariables(List.of("loss")) // <<< this line fixes the problem
        .build();
sd.setTrainingConfig(config);

// Task: output must be equal to input
RecordReader reader = new CollectionRecordReader(
        Collections.nCopies(batchSize, Collections.nCopies(2 * modelDim, new IntWritable(1))));
DataSetIterator iterator = new RecordReaderDataSetIterator(
        reader, batchSize, modelDim, 2 * modelDim - 1, true);

// ScoreListener will consistently report a loss of 0
History hist = sd.fit(iterator, 10, new ScoreListener(1));

// The recorded loss curve is also constantly 0
LossCurve curve = hist.lossCurve();
System.out.println("Loss curve:\n" + curve.getLossValues());

// However, the loss calculated here is > 0
Map<String, INDArray> map = sd.output(iterator, "loss");
System.out.println("Final loss: " + map.get("loss"));
```

I'm not entirely sure if this is a bug or a feature. The reason for the described behavior seems to be that the SameDiff and TrainingConfig instances store the loss variables separately (and `ScoreListener`/`LossCurve` report the losses from the latter). When the TraningConfig is assigned to the SameDiff via `setTrainingConfig()` (see [here](https://github.com/deeplearning4j/deeplearning4j/blob/a206cb6720039ac9d7b03a3e22638951482f87ad/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/samediff/SameDiff.java#L1651)), the loss variables of the TrainingConfig are copied to the SameDiff but *not* vice versa. Copying also in the opposite direction could be problematic if the user wants to use one TrainingConfig for multiple different SameDiff graphs. But you can judge this way better.

#### Version Information

* Deeplearning4j version: 1.0.0-SNAPSHOT
* Platform information (OS, etc): Linux Mint 21
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

**Comment by agibsonccc** [comment]
@CompilerCrash this is a bug.  State should be consistent across trainingconfig and loss variables. If one gets set and the other is defined then it should be updated.
Another option would be to also add some exceptions/validations when anything changes. What would you prefer to happen?

I know that state like this can be error prone to manage so I'd imagine anything silent isn't preferrable.

There's a a few states to consider:
1. Pre defined training configuration new loss variable gets added
2. Pre defined loss variables, training config gets added
3. Neither are defined 
4. One has them defined another does not.


There's also other things like training configuration having undefined variables.
I think the minimum we could do here is some validation/warnings to allow the user to make the state consistent.
What would you like to see here?

**Comment by CompilerCrash** [comment]
@agibsonccc I think the more inconsistent states can be avoided by design, the better. Therefore, I wonder if it is necessary to store two separate collections of loss variables in the first place. Maybe it is sufficient to have it only in the SameDiff instance (and maybe share the reference of this collection with the TrainingConfig)?

If for some reason this is not possible/desirable, it might also make sense to view the loss variables stored in the TrainingConfig as only those of all the loss variables that the user wants to _observe_ (this needs to be documented properly, of course). This should reduce the number of inconsistent states quite a bit because the invariant becomes "the TrainingConfig loss variables are a _subset_ of the SameDiff loss variables" instead of "the TrainingConfig loss variables are _equal_ to the SameDiff loss variables".

In general, I think it is more useful if the framework keeps the states consistent (whenever possible) than if it just emits warnings and delegates this work to the user. And I totally agree that this shouldn't happen all silently, especially if something specified by the user is overwritten. However, since restoring consistency by merging the two collections according to some rules could probably become very complicated (and hard to comprehend) in certain cases, it would also be okay to throw a validation error then and resolve only the trivial cases automatically.

To avoid the pitfall I ran into, I suppose there should either be a warning if the TrainingConfig loss variables are not set, or `null` should be interpreted as "use _all_ loss variables from the SameDiff graph".

**Comment by fcorneli** [comment]
Also stumbled upon this issue on DL4J version 1.0.0-M2.1 while trying to translate the most simple NN I can think of towards SameDiff. When can we expect a new release?

**Comment by agibsonccc** [comment]
Mostly blocked on a customer issue. I was also waiting to see if a javacpp
release would happen. That appears to be taking a while though. So I will
proceed with that after QA testing is done. Hopefully by next week.
If you want managed releases with guaranteed timelines and an SLA feel free
to reach out: https://www.konduit.ai/dl4j-consulting
