### ISSUE TITLE
word2vec TSNE blank visualization

### ISSUE THREAD

**Issue by Hambik** [deeplearning4j/deeplearning4j#986]
I am running Word2VecRawTextExample (on raw_sentences.txt) and added TSNE visualization code as follows:

        BarnesHutTsne tsne = new BarnesHutTsne.Builder()
                .setMaxIter(4)
                .stopLyingIteration(250)
                .learningRate(500)
                .useAdaGrad(false)
                .theta(0.5)
                .setMomentum(0.5)
                .normalize(true)
                .usePca(false)
                .build();
        vec.lookupTable().plotVocab(tsne);

(I set MaxIter to 4 since it is working too slow on setup (probably because of absence of supported GPU)). 
I can see the /api/coords showing some coordinates like this:

-18815.94921875,8632.708984375,been 
-17354.37109375,6028.26025390625,year 
-5956.3271484375,9430.6787109375,about 
-3004.97265625,14830.166015625,your 

However, I see blank screen when navigating to /render page. I checked the referenced assets/render.js and noticed that it contains blank variables x,y and names:

var x = [];
var y = [];
var name3 = [];

pom.xml is attached

[pom.xml.txt](https://github.com/deeplearning4j/deeplearning4j/files/72374/pom.xml.txt)

**Comment by Hambik** [comment]
Any clue on this ?

**Comment by raver119** [comment]
Fixed: https://github.com/deeplearning4j/deeplearning4j/pull/1061
