### ISSUE TITLE
Dropout changes input values

### ISSUE THREAD

**Issue by CompilerCrash** [deeplearning4j/deeplearning4j#9864]
#### Issue Description

I revisited issue #9830 and the third bug I reported there still doesn't seem to be fixed (the others are, as far as I can tell).

- expected behavior: Input values that are not dropped by the `dropout` op should remain unchanged.
- encountered behavior: The values that are not dropped are changed as if they were divided by the `probabilityValue`.

Example:
```
INDArray in = Nd4j.ones(4, 8);
INDArray res1 = Nd4j.nn.dropout(in, false, 0.2);
System.out.println("res1 =\n" + res1);   // should only contain 1s and 0s but contains 5s instead of 1s
INDArray res2 = Nd4j.nn.dropout(in, false, 0.8);
System.out.println("\nres2 =\n" + res2); // should only contain 1s and 0s but contains 1.25s instead of 1s
```
Output:
```
res1 =
[[         0,         0,         0,         0,         0,         0,         0,         0], 
 [         0,    5.0000,         0,    5.0000,         0,         0,         0,         0], 
 [    5.0000,         0,         0,         0,    5.0000,         0,         0,         0], 
 [         0,         0,         0,    5.0000,    5.0000,         0,         0,         0]]

res2 =
[[    1.2500,    1.2500,    1.2500,    1.2500,    1.2500,         0,    1.2500,    1.2500], 
 [    1.2500,    1.2500,    1.2500,    1.2500,    1.2500,    1.2500,    1.2500,    1.2500], 
 [    1.2500,    1.2500,    1.2500,    1.2500,    1.2500,    1.2500,    1.2500,         0], 
 [    1.2500,    1.2500,    1.2500,    1.2500,    1.2500,    1.2500,    1.2500,    1.2500]]
```

#### Version Information

* Deeplearning4j version: 1.0.0-SNAPSHOT
* Platform information (OS, etc): Linux Mint 21
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

**Comment by agibsonccc** [comment]
@CompilerCrash thanks. This was using the newer kernel which appeared to need some polish. I took the time to clean it up and fix this. Thanks for the report.
