### ISSUE TITLE
Training using sd.nn.linear and sd.nn.reluLayer doesn't succeed

### ISSUE THREAD

**Issue by CompilerCrash** [deeplearning4j/deeplearning4j#9869]
#### Issue Description

- expected behavior: The expressions `input.mmul(weights).add(bias)` and `sd.nn.linear(input, weights, bias)` should be equivalent.
- encountered behavior: In the code below, training will only succeed when the first variant is used: Variant 1 archives 100% accuracy, while variant 2 doesn't get better than random guessing (often even 0% accuracy).

I also added a third variant below, which uses `sd.nn.reluLayer(input, weights, bias)`. Although this is not equivalent to the other two variants (it additionally has a ReLU activation function) it should nonetheless allow learning the task with high accuracy, but it doesn't (note that the weights are initialized all positive, so the ReLU should not make a difference).

Caveat: I could only test this with M2.1 due to issue #9862, which is fixed but not yet in SNAPSHOT.

```
int batchSize = 32;
int modelDim = 10;

SameDiff sd = SameDiff.create();

SDVariable features = sd.placeHolder("features", FLOAT, batchSize, modelDim);
SDVariable labels = sd.placeHolder("labels", FLOAT, batchSize, modelDim);
SDVariable weights = sd.var("weights", new OneInitScheme('c'), FLOAT, modelDim, modelDim);
SDVariable bias = sd.zero("bias", modelDim);
// SDVariable predictions = features.mmul(weights).add("predictions", bias);         // <<< variant 1 (works)
SDVariable predictions = sd.nn.linear("predictions", features, weights, bias);       // <<< variant 2 (doesn't work)
// SDVariable predictions = sd.nn.reluLayer("predictions", features, weights, bias); // <<< variant 3 (doesn't work)
sd.loss.meanSquaredError("loss", labels, predictions, null);

TrainingConfig config = new TrainingConfig.Builder()
        .updater(new Adam(0.1))
        .dataSetFeatureMapping("features")
        .dataSetLabelMapping("labels")
        .build();
sd.setTrainingConfig(config);

// the task is to reconstruct the one-hot encoded input
DataSetIterator iterator = new ReconstructionDataSetIterator(new RandomDataSetIterator(100, new long[]{batchSize, modelDim}, new long[]{}, ONE_HOT, ZEROS));

sd.fit(iterator, 10);

Evaluation evaluation = new Evaluation();
sd.evaluate(iterator, "predictions", evaluation);
System.out.println(evaluation.stats());
```

#### Version Information

* Deeplearning4j version: 1.0.0-M2.1
* Platform information (OS, etc): Linux Mint 21
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

**Comment by agibsonccc** [comment]
@CompilerCrash  from the looks of it this appears to be fine. I added the test for all 3 cases and ensure that the predictions end up being the same.  You can take a look at the PR above.

**Comment by CompilerCrash** [comment]
@agibsonccc looking at the PR, it seems to me like the added test case does only check that variant 3 can be executed without an exception, but that's not the problem here. What I tried to describe is that in variant 2 and 3, training terminates regularly, but the network hasn't learned anything useful (while variant 1 shows that the network should be able to solve the task easily).

In my mind, there would need to be two test cases, one that uses variant 2 and one that uses variant 3, and both should include something like `assertTrue(evaluation.accuracy() > 0.9)`.

If you suspect that this issue might only exist in M2.1 and earlier and would thus be irrelevant, then I can wait for the next SNAPSHOT and report if I'm still encountering it.

**Comment by agibsonccc** [comment]
@CompilerCrash  I just published a set of snapshots. Please give it a shot. I still wasn't able to reproduce any failures here. The outputs were the same and accuracy was the same as well.

**Comment by CompilerCrash** [comment]
@agibsonccc this gives me hope that this issue might be obsolete. Unfortunately, I cannot test the new snapshot because basically every ND4J/SameDiff operation throws an `UnsatisfiedLinkError` right now. I will try again once this is fixed.

**Comment by CompilerCrash** [comment]
@agibsonccc I just tried the latest snapshot and now the training succeeds, i.e., this bug (whatever it was) has indeed been fixed.

**Comment by agibsonccc** [comment]
@CompilerCrash Thanks! (Sorry saw this but forgot to acknowledge.) A bit more to go for the release yet (overhauling attention mechanism atm + 1 more crash) but overall we should be good to go soon then we should have a much more improved samediff. Thanks for all the github issues!

**Comment by CompilerCrash** [comment]
@agibsonccc Glad to hear. You're welcome.
