### ISSUE TITLE
nd4j writeasnumpy crashed when writing a large double INDArray of shape (115240, 2400)

### ISSUE THREAD

**Issue by whogiawho** [deeplearning4j/deeplearning4j#9891]
#### Issue Description

Please describe our issue, along with:
- expected behavior
   writeAsNumpy​(arr, file) should generate a npy file 
- encountered behavior
   a npy file of size 0  is made instead

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
   1.0.0-M2.1
* Platform information (OS, etc)
  Host: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, 12 cores, 31G,  Windows 10 , 64 bit Build 22621 (10.0.22621.1105)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Additional Information
Writing an array of shape(100835, 2400) is ok.
So this may be due to the array's large size.

Wrting address 0x0 causes a violation when calling convertToNumpy
siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), writing address 0x0000000000000000

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
---------------  T H R E A D  ---------------

Current thread (0x000001f645942000):  JavaThread "main" [_thread_in_native, id=1704, stack(0x000000c2fb800000,0x000000c2fb900000)]

Stack: [0x000000c2fb800000,0x000000c2fb900000],  sp=0x000000c2fb8feda8,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [jniopenblas_nolapack.dll+0x28ddc]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.bytedeco.javacpp.Pointer.memcpy(Lorg/bytedeco/javacpp/Pointer;Lorg/bytedeco/javacpp/Pointer;J)Lorg/bytedeco/javacpp/Pointer;+0
j  org.nd4j.nativeblas.BaseNativeNDArrayFactory.convertToNumpy(Lorg/nd4j/linalg/api/ndarray/INDArray;)Lorg/bytedeco/javacpp/Pointer;+153
j  org.nd4j.linalg.factory.Nd4j.convertToNumpy(Lorg/nd4j/linalg/api/ndarray/INDArray;)Lorg/bytedeco/javacpp/Pointer;+4
j  org.nd4j.linalg.factory.Nd4j.writeAsNumpy(Lorg/nd4j/linalg/api/ndarray/INDArray;Ljava/io/OutputStream;)V+10
j  org.nd4j.linalg.factory.Nd4j.writeAsNumpy(Lorg/nd4j/linalg/api/ndarray/INDArray;Ljava/io/File;)V+9
j  com.westsword.stocks.tools.helper.TfNpzHelper.writeTrainX(Ljava/lang/String;[[D)V+16
j  com.westsword.stocks.tools.helper.TfNpzHelper.writeTrainX(III[Ljava/lang/String;[[DLjava/lang/String;)V+20
J 1330% c2 com.westsword.stocks.tools.helper.TfNpzHelper._drMakeNpy(III[Ljava/lang/String;Lcom/westsword/stocks/am/AmManager;Lcom/westsword/stocks/base/time/SdTime1;Ljava/lang/String;)V (158 bytes) @ 0x000001f655b5a488 [0x000001f655b59f80+0x0000000000000508]
j  com.westsword.stocks.tools.helper.TfNpzHelper.drMakeNpy(II[Ljava/lang/String;[ILcom/westsword/stocks/am/AmManager;Lcom/westsword/stocks/base/time/SdTime1;Ljava/lang/String;)V+27
j  com.westsword.stocks.tools.helper.TfNpzHelper.make([Ljava/lang/String;)V+269
j  com.westsword.stocks.tools.AnalyzeTools.main([Ljava/lang/String;)V+2427
v  ~StubRoutines::call_stub
siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), writing address 0x0000000000000000

* pom.xml file or similar (also in a Gist)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by whogiawho** [comment]
[hs_err_pid16496.log](https://github.com/deeplearning4j/deeplearning4j/files/10443264/hs_err_pid16496.log)

full log generated by jvm

**Comment by agibsonccc** [comment]
@whogiawho  thanks for confirming. Let me see why this is happening. I'm guessing an overflow or something. I"ll switch the right buffer to be buffered if that ended up being the issue. Thanks for the clear issue description!

**Comment by agibsonccc** [comment]
@whogiawho I figured out this is related to a numerical underflow from the array buffer size being too large. You can convert your array to float (it breaks on double) and it should work. In the mean time I'll fix the related underflow.

**Comment by whogiawho** [comment]
Thanks for quick reply and suggestion.

I will try float type and see what happens.

By the way, writing numpy array using nd4j has better performance than
other tools like numpyio.

Adam Gibson ***@***.***> 于2023年1月19日周四 18:10写道：

**Comment by whogiawho** [comment]
Using float will give 2 times buffer than double.
So it works for (float, 115240, 2400).

But if I use (float, 115240*2, 2400*2) instead of (double, 115240, 2400) ,
the same problem is still there.

Roughly checking the codes, the crash happened
at java/org/nd4j/nativeblas/BaseNativeNDArrayFactory.java's 94th line:
Pointer.memcpy(bytePointer,array.data().pointer(),(array.data().
getElementSize() * array.data().length()));

Here nd4j called javacpp's api to do the memcpy job.

If this is due to a static buffer size allocation limit of javacpp, sould
that there is not better solution for nd4j.
It is a limit of javacpp, isn't it?




Adam Gibson ***@***.***> 于2023年1月19日周四 18:10写道：

**Comment by agibsonccc** [comment]
I found an issue with memcpy. I am going to do a quick rewrite to work
around this. It's a simple fix. The original usage was just reusing the in
memory representation of a normal javacpp pointer plus writing to disk
using nio buffer channels which are very fast .

I will switch it to use a manually written copy in c++ to work around this.

**Comment by agibsonccc** [comment]
@whogiawho I am going to push a fix here. https://github.com/deeplearning4j/deeplearning4j/pull/9892

 I need to do more testing yet though.

**Comment by whogiawho** [comment]
> 

I can do cover some testing if u do not mind. 
How can I get the updated package and test cases.

**Comment by agibsonccc** [comment]
I am working on looking at strings as a last step and still need to look at
the performance. After that I can push to snapshots for you to test. The
new approach directly uses the underlying c++ to write the arrays instead.
I managed to already get it working minus strings. I might just omit that
for now if it is too complex.

**Comment by agibsonccc** [comment]
@whogiawho  I pushed the basic changes needed for larger arrays. I'm open to follow up PRs for performance or other improvements afterwards. I'm much happier with the cleaned up numpy i/o. Thanks for flagging this!

**Comment by whogiawho** [comment]
What is the max length of writeAsNumpy?  The crash still exists with
(float, 273695, 2400).



Adam Gibson ***@***.***> 于2023年1月21日周六 19:54写道：

**Comment by agibsonccc** [comment]
@whogiawho  what did you try" I didn't push this to snapshots yet so you were probably using the same code. I just pushed the fix along with some other numpy cleanup in my most recent PR. I did a snapshots build so give it a few hours and that should be up. The intent should be for there to be able to write anything.  I haven't extensively profiled every configuration I just migrated it away from java to c++. I planned on doing some QA before the release to double check more recent performance trade offs including this. Some testing would be appreciated!

**Comment by whogiawho** [comment]
Since the issue #9891 is closed, and sound that its fix code is merged into
master.
[image: image.png]
my assumption is that rebuilding *deeplearning4j-examples
<https://github.com/deeplearning4j/deeplearning4j-examples>*  with shade
plugin will give me a uber jar.
And this uber jar will include your fix, and I can verify it.
 Sounds that this assumption is not right...

Here is what I do:
1. git clone https://github.com/deeplearning4j/deeplearning4j-examples
2. delete local repo .m2
3. mvn package
4.
copy ~/sample/deeplearning4j-examples/nd4j-ndarray-examples/target/nd4j-ndarray-examples-1.0.0-SNAPSHOT-shaded.jar
to my project
5. run my codes to call writeAsNumpy(INDArray arr, File file)

I does have time to run testing. But what are the test cases? In my mind,
the test case is simple, just pass a large array to writeasnumpy.
Pls correct me if I'm wrong. And give me a large and clear picture.

Adam Gibson ***@***.***> 于2023年1月27日周五 23:21写道：

**Comment by agibsonccc** [comment]
No that is absolutely not the case. Not only do you need to change the
version to 1.0.0.SNAPSHOT but the snapshot itself online needs to be
updated . That or you build the deeplearning4j/deeplearning4j repo (notice
no -examples prefix) from source yourself.

The examples are completely decoupled from the actual project.

**Comment by whogiawho** [comment]
Ok, thanks for the clarification.

I tried <dl4j-master.version>1.0.0.SNAPSHOT</dl4j-master.version> in
nd4j-ndarray-example, but mvn reported that can not resolve dependency.

Rebuilding deeplearning4j/deeplearning4j from source also also reports:
   Execution javacpp-cppbuild-compile of goal
org.bytedeco:javacpp:1.5.8:build failed:

Waiting some time for 1.0.0.SNAPSHOT is not bad.





Adam Gibson ***@***.***> 于2023年1月28日周六 08:49写道：

> No that is absolutely not the case. Not only do you need to change the
> version to 1.0.0.SNAPSHOT but the snapshot itself online needs to be
> updated . That or you build the deeplearning4j/deeplearning4j repo (notice
> no -examples prefix) from source yourself.
>
> The examples are completely decoupled from the actual project.
>
