### ISSUE TITLE
Documentation: Explain RNN implementations and features (+ examples)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/deeplearning4j#990]
Add details on RNNs on website.

Things to explain for RNNs:
- Input shape/layout
- rnnTimeStep (and related methods)
- RnnOutputLayer
- Variable length time series
- one-to-many, many-to-one + masking
- Data import
- Using RNN layers with other layers
- Truncated BPTT
- Examples: basic details of how character example (and maybe others) work

**Comment by linkerlin** [comment]
waiting and expecting

**Comment by AlexDBlack** [comment]
@linkerlin FYI: WIP documentation is online, see links below. Still more to do, but feedback on that (or requests for anything else you'd like to see) would be appreciated. :)

https://github.com/deeplearning4j/deeplearning4j/pull/1007/files
https://github.com/deeplearning4j/deeplearning4j/blob/d45b83bcd040f55db714fcc227900d782f66d5d3/usingrnns.md
(Image links won't work in the above preview, but should be fine once merged)

**Comment by AlexDBlack** [comment]
http://deeplearning4j.org/usingrnns.html

**Comment by jpatanooga** [comment]
These docs look great btw
