### ISSUE TITLE
Add a howto / developer guide

### ISSUE THREAD

**Issue by bennythedataguy** [deeplearning4j/deeplearning4j#991]
I'm trying to add a bidirectional LSTM RNN to the codebase, but looking at codebase as a developer who has not seen it before is a bit like trying to machine learning without labels.  

Suggested changes 
* developer guide with examples, and sequence diagrams of some kind showing how all the layers, params, and so on relate to each other
* comments in source code describing what a class does, why it exists, and maybe a reference back to the developer guide

**Comment by bennythedataguy** [comment]
@AlexDBlack: 
To implement a new layer type, you need the following:
* Layer (configuration) with builder
* Layer extends BaseLayer (with fwd/bwd pass math etc)
* ParameterInitializer for the layer
* Layer factory (creates Layer object from Layer configuration object) so builder stuff gives us our config. Settings only there, no parameters or math in the layer config class

**Comment by bennythedataguy** [comment]
There are TWO Layer classes, the configuration Layer and the math logic Layer

**Comment by dperciva** [comment]
In gitter chat just now, it came up that a short description of the processing chain that instantiates a network from a network config would be useful for those wanting to implement a custom architecture--what classes need to be extended for custom work, etc. I'm making that note here instead of in a new issue, as it seems related.

**Comment by AlexDBlack** [comment]
First pass on a developer guide is here: http://deeplearning4j.org/devguide.html
Suggestions for improvement of that page are appreciated.
