### ISSUE TITLE
Importing GRU onnx model failed

### ISSUE THREAD

**Issue by ccen** [deeplearning4j/deeplearning4j#9917]
Hello all, I'm trying to import a PyTorch generated GRU onnx model into dl4j and got errors.
I will show all my processes and my speculation about the error.

**(1) Generate GRU onnx model with PyTorch**
Follow by PyTorch document [GRU](https://pytorch.org/docs/stable/generated/torch.nn.GRU.html) and [onnx](https://pytorch.org/docs/stable/onnx.html), I wrote a simple script.

```
import torch
rnn = torch.nn.GRU(10, 20, 2)
input = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
torch.onnx.export(rnn, (input, h0), "Single_GRU.onnx")
```

**(2) Import to dl4j, got import error**

```
OnnxFrameworkImporter onnxFrameworkImporter = new OnnxFrameworkImporter();
SameDiff graph = onnxFrameworkImporter.runImport(f.getAbsolutePath(), Collections.emptyMap(), true);
```
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
```

**(3) Modify onnx file, got another error**
I found IndexOutOfBoundsException occurs while accessing GRU onnx node outputs, so I wrote a python script add more outputs to GRU node, which makes an off-standard onnx file.

```
import onnx
model = onnx.load(r"Single_GRU.onnx")
graph = model.graph
node = graph.node

for i in range(len(node)):
    if node[i].op_type == "GRU":
        for j in range(2,4):
            node[i].output.insert(j, node[i].name + "_output_placeholder_" + str(j))
        print(node[i])
        print("=====")
onnx.save(model, r"Single_GRU_addoutput.onnx")
```

Then I got another error.

```
Error at [D:/a/deeplearning4j/deeplearning4j/libnd4j/include/ops/declarable/generic/nn/recurrent/gruCell.cpp:97:0]:
gruCell: Input ranks must be 2 for inputs 0 and 1 (x, hLast) - got 3, 3
Exception in thread "main" java.lang.RuntimeException: Op gruCell with name /GRU failed to execute. Here is the error from c++: Op validation failed
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.calculateOutputShape(NativeOpExecutioner.java:1486)
```

**(4) My speculation about the error**
The error message comes from [gruCell.cpp#L97](https://github.com/deeplearning4j/deeplearning4j/blob/master/libnd4j/include/ops/declarable/generic/nn/recurrent/gruCell.cpp#L97).

In dl4j [1.0.0-beta7 document](https://deeplearning4j.konduit.ai/v/en-1.0.0-beta7/operation-namespaces/rnn), I found dl4j has gru and gruCell classes, gruCell does a single time step operation, so it requires inputs rank 2.

My speculation is dl4j uses gruCell operator on onnx gru node, rather than gru operator. Which causes error in (2) and (3). One suspect is in nd4j, [onnx name of gruCell](https://github.com/deeplearning4j/deeplearning4j/blob/master/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/layers/recurrent/GRUCell.java#L63) is "GRU".

Is my assumption reasonable? Please let me know if I could provide more information. Thank you!

**Comment by agibsonccc** [comment]
@ccen  could you do *all* of what I asked in the forums?  I still need to know if you tried what I suggested and what the pytorch/onnx version is.

Also, beta7 is very old. Please use the most current docs.

**Comment by ccen** [comment]
Hello Adam, thanks for your reply!
My PyTorch is 1.13.1, dl4j version is 1.0.0-SNAPSHOT, actually nd4j-cpu-backend-common-1.0.0-20230209.002746-392.jar
For other users interested in this topic, refer to [discussion in forum](https://community.konduit.ai/t/importing-gru-onnx-model-failed/2250).

Opset version not matters in this case, I've tried all versions.
I refer to beta7 docs because only this version mentions RNN operations ;P

**Comment by agibsonccc** [comment]
@ccen  thanks for confirming! Sorry for being a bit out of sync there on the forums. Let me take a look at the op again then.

**Comment by agibsonccc** [comment]
@ccen  this needs a bit more work but the basics are there: https://github.com/deeplearning4j/deeplearning4j/pull/9918
I needed to add mapping class rather than the more simple rule based one. I double checked the cases as well as the mapping to our inputs. Note that only forward mode will be supported since that's what we already have.
That's what your GRU uses by default so it shouldn't be an issue for your use case. I made sure to throw an error for anything else.

**Comment by ccen** [comment]
Thank you! I will have a try on complicated GRU model after new SNAPSHOT version update ;D

**Comment by agibsonccc** [comment]
@ccen  I implemented basic support on the existing functionality we have.  I looked at linear_before_reset which defaults to 1 from pytorch. If you change that to false, it should be fine. We'll work on merging that today or tomorrow.

**Comment by agibsonccc** [comment]
@ccen  this is merged will publish snapshots in a bit. Feel free to check with me for testing.
