### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by linkerlin** [deeplearning4j/deeplearning4j#992]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project deeplearning4j-core: Compilation failure: Compilation failure:
[ERROR] /Users/linkerlin/gits/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/datasets/iterator/BaseDatasetIterator.java:[30,8] org.deeplearning4j.datasets.iterator.BaseDatasetIterator is not abstract and does not override abstract method getLabels() in org.nd4j.linalg.dataset.api.iterator.DataSetIterator
[ERROR] /Users/linkerlin/gits/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/datasets/iterator/ReconstructionDataSetIterator.java:[30,8] org.deeplearning4j.datasets.iterator.ReconstructionDataSetIterator is not abstract and does not override abstract method getLabels() in org.nd4j.linalg.dataset.api.iterator.DataSetIterator
[ERROR] /Users/linkerlin/gits/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/datasets/iterator/SamplingDataSetIterator.java:[28,8] org.deeplearning4j.datasets.iterator.SamplingDataSetIterator is not abstract and does not override abstract method getLabels() in org.nd4j.linalg.dataset.api.iterator.DataSetIterator
[ERROR] /Users/linkerlin/gits/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/datasets/iterator/impl/ListDataSetIterator.java:[35,8] org.deeplearning4j.datasets.iterator.impl.ListDataSetIterator is not abstract and does not override abstract method getLabels() in org.nd4j.linalg.dataset.api.iterator.DataSetIterator
[ERROR] /Users/linkerlin/gits/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/datasets/iterator/MultipleEpochsIterator.java:[29,8] org.deeplearning4j.datasets.iterator.MultipleEpochsIterator is not abstract and does not override abstract method getLabels() in org.nd4j.linalg.dataset.api.iterator.DataSetIterator
[ERROR] /Users/linkerlin/gits/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/datasets/test/TestDataSetIterator.java:[30,8] org.deeplearning4j.datasets.test.TestDataSetIterator is not abstract and does not override abstract method getLabels() in org.nd4j.linalg.dataset.api.iterator.DataSetIterator
[ERROR] /Users/linkerlin/gits/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/datasets/iterator/AsyncDataSetIterator.java:[23,8] org.deeplearning4j.datasets.iterator.AsyncDataSetIterator is not abstract and does not override abstract method getLabels() in org.nd4j.linalg.dataset.api.iterator.DataSetIterator
[ERROR] /Users/linkerlin/gits/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/datasets/canova/SequenceRecordReaderDataSetIterator.java:[23,8] org.deeplearning4j.datasets.canova.SequenceRecordReaderDataSetIterator is not abstract and does not override abstract method getLabels() in org.nd4j.linalg.dataset.api.iterator.DataSetIterator
[ERROR] /Users/linkerlin/gits/deeplearning4j/deeplearning4j-core/src/main/java/org/deeplearning4j/datasets/canova/RecordReaderDataSetIterator.java:[42,8] org.deeplearning4j.datasets.canova.RecordReaderDataSetIterator is not abstract and does not override abstract method getLabels() in org.nd4j.linalg.dataset.api.iterator.DataSetIterator

**Comment by AlexDBlack** [comment]
That's related to Canova. Make sure you are up to date on dl4j, nd4j and canova if you are trying to build from source. If you are still getting issues after that, let me know (but afaik it's all good, I built relatively recently)

**Comment by linkerlin** [comment]
I run the setup.sh every time. And it failed to build.

**Comment by linkerlin** [comment]
I found the problem, the setup.sh does not update dl4j only update nd4j and Canova.
