### ISSUE TITLE
pca_factor does not return correct factor matrix when run with native nd4j back end

### ISSUE THREAD

**Issue by dpetronijevic** [deeplearning4j/deeplearning4j#9931]
#### Issue Description
package org.nd4j.linalg.dimensionalityreduction;
class PCA
methods:
public static INDArray pca_factor(INDArray A, int nDims, boolean normalize)
public static INDArray pca_factor(INDArray A, double variance, boolean normalize)
Both methods exhibit the same behavior.  When run with CUDA nd4j backend both return the correct factor matrix, but when run with native nd4j back end, they return the transposed factor matrix. It seems that call to
Nd4j.getBlasWrapper().lapack().gesvd(A, s, null, VT);
with native back end returns V and not VT so that transpose further down in the code is not required in this case.
For example, 
INDArray factor = PCA.pca_factor(matrix, 3, false);
where matrix is:
    1    2    3
   11   12   13
   21   22   23
   31   32   33
returns with CUDA back end
- expected behavior
-0.55332	 -0.72606  0.40825	
-0.57703	 -0.01936 -0.81650	
-0.60073	  0.68735   0.40825	

While with native back end I get:
- encountered behavior
-0.55332	 -0.57703 -0.60073	
-0.72606	 -0.01936  0.68735	
0.40825	 -0.81650  0.40825	

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
   <java.version>1.17</java.version>
   <nd4j.version>1.0.0-M2.1</nd4j.version>
   <dl4j.version>1.0.0-M2.1</dl4j.version>

* Platform information (OS, etc)
   Debian Linux 12 (Bookworm)
   libblas3  version 3.11.0-2
* CUDA version, if used
   12
* NVIDIA driver version, if in use
    Driver Version: 525.89.02 

nd4j initialization output:
Mar. 12, 2023 1:27:43 P.M. org.nd4j.linalg.factory.Nd4jBackend load
INFO: Loaded [CpuBackend] backend
Mar. 12, 2023 1:27:43 P.M. org.nd4j.nativeblas.NativeOpsHolder initOps
INFO: Number of threads used for linear algebra: 6
Mar. 12, 2023 1:27:43 P.M. org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory createBlas
INFO: Binary level Generic x86 optimization level AVX/AVX2
Mar. 12, 2023 1:27:43 P.M. org.nd4j.nativeblas.Nd4jBlas <init>
INFO: Number of threads used for OpenMP BLAS: 6
Mar. 12, 2023 1:27:43 P.M. org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner printEnvironmentInformation
INFO: Backend used: [CPU]; OS: [Linux]
Mar. 12, 2023 1:27:43 P.M. org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner printEnvironmentInformation
INFO: Cores: [12]; Memory: [7.8GB];
Mar. 12, 2023 1:27:43 P.M. org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner printEnvironmentInformation
INFO: Blas vendor: [OPENBLAS]
Mar. 12, 2023 1:27:43 P.M. org.nd4j.linalg.cpu.nativecpu.CpuBackend logBackendInit
INFO: Backend build information:
 GCC: "7.5.0"
STD version: 201103L
DEFAULT_ENGINE: samediff::ENGINE_CPU
HAVE_FLATBUFFERS
HAVE_OPENBLAS

**Comment by dpetronijevic** [comment]
I forgot to report that native backend changes the input matrix while CUDA does not.
Because of that it is necessary to keep a copy of the input matrix to multiply the factor after transposing it.

**Comment by agibsonccc** [comment]
@dpetronijevic  could you please try with snapshots?  https://deeplearning4j.konduit.ai/multi-project/explanation/snapshots There were some SVD fixes recently that should affect this.

If not, could you clean this up a bit so I can run it and give you a quick fix? Thanks!

**Comment by dpetronijevic** [comment]
I tried running my small test with snapshots and got the same result as with 1.0.0-M2.1: Input matrix is changed and factor is transposed with CPU backend. CUDA backend provides correct results. I tried multiple inputs and it seems that for every n*m input matrix the first m rows are overwritten with what is returned in factor after the call. I couldn't figure out what's in the rest of the input matrix.  Here is my small test program that you can run and see the difference for yourself:

import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.dimensionalityreduction.PCA;
import org.nd4j.linalg.factory.Nd4j;

public class PcaFactorTest
{
	public static double[][] inputArray = { { 1.0, 2.0, 3.0 }, { 11.0, 12.0, 13.0 }, { 21.0, 22.0, 23.0 }, { 31.0, 32.0, 33.0 } };

	public static void main( String[] args )
	{
		INDArray inputMatrix = Nd4j.create( inputArray );
		int nColumns = inputMatrix.columns();
		System.out.println();
		System.out.println( "Test results for backend: " + Nd4j.backend.toString() );
		System.out.println();
		System.out.println( "inputMatrix before PCA.pca_factor call:" );
		System.out.println( inputMatrix.toString() );
		System.out.println();
		INDArray factor = PCA.pca_factor( inputMatrix, nColumns, false );
		System.out.println( "inputMatrix after PCA.pca_factor call:" );
		System.out.println( inputMatrix.toString() );
		System.out.println();
		System.out.println( "factor matrix as returned by PCA.pca_factor call:" );
		System.out.println( factor.toString() );
		System.out.println();
		System.out.println( "Current Backend: " + Nd4j.backend.toString() );
	}
}

**Comment by agibsonccc** [comment]
@dpetronijevic  could you please try snapshots then? That will be the main way to know if this is fixed or not. If snapshots don't work for you thank you for the reproducer I can take a look if this is till an issue using that code.

**Comment by dpetronijevic** [comment]
@agibsonccc you probably missed it in my previous comment, I did try snapshots and the problem is still there as with the  1.0.0-M2.1

**Comment by dpetronijevic** [comment]
@agibsonccc Thanks for looking into this. I don't need a quick fix, I have a workaround. I check if backend is CPU and make a copy of the input and transpose the returned factor and continue with that. So, I am not blocked.

**Comment by agibsonccc** [comment]
Ahh you're indeed correct. Sorry about that! Ok then I can implement a quick fix for this then. No reason not to fix it while we know about it though. I'll do the necessary fixes using your example as a base test to prevent regressions in the future. Thanks for highlighting!
