### ISSUE TITLE
Can DL4J load a trained NVIDIA-TSPP model (TorchScript or ONNX format)?

### ISSUE THREAD

**Issue by cqiaoYc** [deeplearning4j/deeplearning4j#9945]
Can I  load a trained model (TorchScript or ONNX format) from the NVIDIA Time Series Prediction Platform (TSPP) with DL4J?
 Is there a TSPP alternative to DL4J?

**Comment by agibsonccc** [comment]
@cqiaoYc  we should be able to run onnx based models. I would suggest trying onnx import and letting us know. If there's something we don't support open an issue. Please migrate this to the forums for discussion. Thanks!
