### ISSUE TITLE
An error is happened when compiling the Libnd4j in Windows

### ISSUE THREAD

**Issue by LotsoTeddy** [deeplearning4j/deeplearning4j#9950]
I met the following error when compiling the libnd4j dll in Windows with msys2 and cmake (version 3.26.2):

G:/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe:
 CMakeFiles/nd4jcpu.dir/objects.a(LegacyReduce3Op.cpp.obj):LegacyReduce3Op.cpp:(.text+0xcc5): undefi
ned reference to `sd::ops::LegacyReduce3Op::traceExecIfNeeded(sd::graph::Context&)'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [blas/CMakeFiles/nd4jcpu.dir/build.make:2228: blas/libnd4jcpu.dll] Error 1

![image](https://user-images.githubusercontent.com/62918515/230718720-3c06f53c-1209-4404-b81c-e0d49879fdb4.png)

How can i solve it?

**Comment by agibsonccc** [comment]
@nkfyz  pull this branch: https://github.com/deeplearning4j/deeplearning4j/pull/9951 thanks for filing the issue!
