### ISSUE TITLE
Fail to replace the libnd4jcpu.dll file for using my own custom operations

### ISSUE THREAD

**Issue by LotsoTeddy** [deeplearning4j/deeplearning4j#9952]
I successfully compile a new libnd4jcpu.dll, and I want to use the new one in my project. Hence, I replace the old dll file (in C:\Users\...\.javacpp\cache\nd4j-native-1.0.0-M2.1-windows-x86_64.jar\org\nd4j\linalg\cpu\nativecpu\bindings\windows-x86_64) by my new dll file.

However, when I execute the LeNetMNIST.java (in dl4j-examples), the new file is deleted and replaced by the old version. Maybe the following step causes this problem?

![image](https://user-images.githubusercontent.com/62918515/230750210-88ec9c3a-43cc-42e9-86a2-96a8d1b3023f.png)

How can I use my new compiled dll in my project? Need I construct & compile the nd4j project?

(BTW, the official tutorial in _https://deeplearning4j.konduit.ai/libnd4j/how-to-guides/how-to-add-operations_ indeed does not mention the replacement method)

**Comment by agibsonccc** [comment]
@nkfyz you just need to use the nd4j-native artifact and use snapshots. That's the version you need to use when building from source. That version is 1.0.0-SNAPSHOT. Pay attention to that when you're running the build.

**Comment by agibsonccc** [comment]
@nkfyz  since you can compile the project now  I'm closing this. Feel free to ask questions over on the forums as I mentioned in the other issue.
