### ISSUE TITLE
Performance problems of DL4J-examples

### ISSUE THREAD

**Issue by LotsoTeddy** [deeplearning4j/deeplearning4j#9953]
I am a beginner of DL4J project. Recently, I profile the dl4j by dl4j-examples project. I want to figure out the following two problems:

First, I train the network in org.deeplearning4j.examples.quickstart.modeling.convolution.LeNetMNIST in both Pytorch & DL4J (keep the same network layers), and I profile the two processes with /usr/bin/time toolchain. I discover that the time in DL4J is pretty longer than Pytorch. Meantime,  the time in systen kernel (systime) is even longer than user time (usrtime). What reasons cause this? Maybe there are many times syscall?

![微信截图_20230409101103](https://user-images.githubusercontent.com/62918515/230750626-1046bede-bf9d-4c28-aaed-21028f6c75fe.png)

Secondly, I profile the LenetMNIST.java by JFR (java flight recorder), the top of the flame graph shows that the CPU is mainly occupied by execCustomOp2. I want to figure out that the overhead for invoking the corresponding native methods. How can I do this?

![微信截图_20230409101220](https://user-images.githubusercontent.com/62918515/230750660-656a3e28-b5d0-40dc-b28f-32a699cf8d0d.png)

My email is fyz@mail.nankai.edu.cn, if any one can explain the above problems, i will be very appreciate.

**Comment by agibsonccc** [comment]
@nkfyz could you please post this over on the community forums https://community.konduit.ai/ ? It's easier to discuss there. The issue tracker is only for clear bugs or something we can directly resolve with an input and output. Anything requiring discussion should be discussed over on the forums. If we can figure out a concrete action like "optimize this particular op" then we can produce a proper fix. 

I'll also need a reproducer and ideally comparable pytorch and nd4j code. Thanks!
