### ISSUE TITLE
package org.nd4j.shade.guava.primitives not exists when constructing DL4J in IntelligentJ IDEA

### ISSUE THREAD

**Issue by LotsoTeddy** [deeplearning4j/deeplearning4j#9954]
when constructing DL4J in IntelligentJ IDE under Windows 10, an error was issued: package org.nd4j.shade.guava.primitives (and many other packeages) not exists

![image](https://user-images.githubusercontent.com/62918515/230801078-b2d7095f-9387-47f8-a6cd-25c9738c3743.png)

![image](https://user-images.githubusercontent.com/62918515/230800985-52d6628e-22fb-41dd-9001-55ed850fc399.png)

I have downloaded all source code by maven as follows:

![image](https://user-images.githubusercontent.com/62918515/230801007-50f65821-9ab1-48dc-ad80-7aed8e0e87e2.png)

and synced all packages in IDEA:

![image](https://user-images.githubusercontent.com/62918515/230801053-81f800c5-c808-4c1d-99b4-deb39e1ee944.png)

How can I sovle it?

**Comment by agibsonccc** [comment]
@nkfyz this isn't a bug. This is a side effect of having a shaded package. You need to exclude those. Please follow this guide. https://deeplearning4j.konduit.ai/multi-project/how-to-guides/import-in-to-your-favorite-ide#shaded-modules
