### ISSUE TITLE
package onnx and tensorflow.framework not exist when constructing DL4J in IntelliJ IDEA

### ISSUE THREAD

**Issue by LotsoTeddy** [deeplearning4j/deeplearning4j#9955]
Thank you many times for helping me @agibsonccc ! I try to maven ignore the nd4j-shaded modules, but still report the errors such as onnx and tensorflow.framework not exist. How can I solve it? The link https://deeplearning4j.konduit.ai/multi-project/how-to-guides/import-in-to-your-favorite-ide#shaded-modules does not mention this part. 

<img width="492" alt="image" src="https://user-images.githubusercontent.com/62918515/230807399-ed9ecb53-866b-4cb7-ae61-60160fc306e5.png">

Maybe i am very close to successful construction, thank you!

**Comment by agibsonccc** [comment]
@nkfyz generate those from the command line. Just run mvn clean install -DskipTests and let protoc generate the code for that. If you keep opening issues for this kind of thing I will be blocking you from the repository. This spams everyone subscribed to this repository. Please migrate to the community forums: https://community.konduit.ai/
