### ISSUE TITLE
How to construct a Computation Graph with input from 2 time series of  different sampling periods?

### ISSUE THREAD

**Issue by cqiaoYc** [deeplearning4j/deeplearning4j#9965]
How to construct a Computation Graph with input from 2 time series of  different sampling periods? For example, one is sampled daily and one is sampled weekly？

**Comment by agibsonccc** [comment]
@cqiaoYc  A multi dataset iterator should serve your use case. You would need to create 2 separate sequence iterators, combine them and then ensure your neural network has 2 inputs. From there you would combine them at some point.
I'll flesh this out on the forums if you want.

Please post issues like this on the forums in the future. Thanks!
