### ISSUE TITLE
Can't restore network configuration with GaussianDistribution from JSON

### ISSUE THREAD

**Issue by Ingwar** [deeplearning4j/deeplearning4j#998]
Hello,

I have got the following error trying to restore the network configuration with `GaussianDistribution` from JSON:
```
Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Could not resolve type id 'GaussianDistribution' into a subtype of [simple type, class org.deeplearning4j.nn.conf.distribution.Distribution]: known type ids = [Distribution, binomial, normal, uniform]
```

Version of deeplearning4j is `0.4-rc3.7`

As far as I can understand, it's caused by missing JsonSubType annotation for `GaussianDistribution` [here](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/conf/distribution/Distribution.java#L33).

**Comment by Ingwar** [comment]
Actually, is there any reason to have both `GaussianDistribution` and `NormalDistribution`? As far as I can understand from [this](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/conf/distribution/Distributions.java#L28) code, they are treated equivalently.

**Comment by AlexDBlack** [comment]
Thanks for reporting this.
I've added the json subtype annotation for GaussianDistribution, and deprecated it in favour of NormalDistribution. (Implementations of both are identical)
https://github.com/deeplearning4j/deeplearning4j/pull/1027

**Comment by Ingwar** [comment]
Thanks!
