### ISSUE TITLE
deeplearning4j-scaleout dependency within deeplearning4j-graph

### ISSUE THREAD

**Issue by fcorneli** [deeplearning4j/deeplearning4j#9987]
The `pom.xml` of `deeplearning4j-graph` still refers to `deeplearning4j-scaleout`.
Relates to:
https://github.com/deeplearning4j/deeplearning4j/commit/8a165d46f9a6575cb0cb83c486337c54f377b370
https://github.com/deeplearning4j/deeplearning4j/pull/9973

**Comment by agibsonccc** [comment]
@fcorneli  this should be fixed now thanks for flagging! https://github.com/deeplearning4j/deeplearning4j/pull/9988 Sorry about that since I still have the reference locally that never came up during my builds.
