### ISSUE TITLE
Using model predictions with multiple threads can cause results to be overwritten

### ISSUE THREAD

**Issue by visionki** [deeplearning4j/deeplearning4j#9993]
#### Issue Description

I'm trying to use [nsfw_model](https://github.com/GantMan/nsfw_model) (nsfw.299x299.h5) on java for image detection, and when I execute ComputationGraph.outputSingle under single thread, the output of the 2 images is different:
```
AnalysisResult(drawings=91.55, hentai=3.73, neutral=4.47, porn=0.23, sexy=0.02)
AnalysisResult(drawings=55.16, hentai=43.82, neutral=0.35, porn=0.65, sexy=0.02)
```

However, when I go to execute it using multiple threads, the output seems to be overwritten by:
```
AnalysisResult(drawings=91.55, hentai=3.73, neutral=4.47, porn=0.23, sexy=0.02)
AnalysisResult(drawings=91.55, hentai=3.73, neutral=4.47, porn=0.23, sexy=0.02)
```
The second detection result is overwritten by the first one.

#### Version Information

* Deeplearning4j version
`1.0.0-M2.1`

**Comment by agibsonccc** [comment]
Closing this. Use ParallelInference:
https://github.com/deeplearning4j/deeplearning4j/blob/851f4e2282782fc5a8777293ab97e3ae90d13603/platform-tests/src/test/java/org/eclipse/deeplearning4j/integration/IntegrationTestRunner.java#L640

Models are known not to be thread safe. If you want more help on how to do something please reach out on the forums: https://community.konduit.ai/

**Comment by visionki** [comment]
@agibsonccc 
Sorry, I'm not familiar with this, here is my asynchronous detection code:
```
@Slf4j
@Component
public class NsfwUtil {
    private final ComputationGraph model;
    private final NativeImageLoader loader;

    public NsfwUtil() throws IOException, UnsupportedKerasConfigurationException, InvalidKerasConfigurationException {
        model = KerasModelImport.importKerasModelAndWeights(new ClassPathResource("model/nsfw.299x299.h5").getInputStream());
        loader = new NativeImageLoader(299, 299, 3, new ColorConversionTransform(COLOR_BGR2RGB));
    }

    @Async
    public CompletableFuture<AnalysisResult> getResult(String url){
        try (InputStream inputStream = Unirest.get(url)
                .asObjectAsync(RawResponse::getContent)
                .get()
                .getBody();
             INDArray matrix = loader.asMatrix(inputStream, false);
             INDArray output = model.outputSingle(matrix.div(255))){
            return CompletableFuture.completedFuture(new AnalysisResult(output.data().asDouble()));
        }catch (Exception e){
            throw new RuntimeException();
        }
    }
}
```
I found an [example](https://github.com/deeplearning4j/deeplearning4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/advanced/features/inference/ParallelInferenceExample.java) of using ParallelInference, and with reference to the example should I change it to the following:
```
@Slf4j
@Component
public class NsfwUtil {
    private final ComputationGraph model;
    private final ParallelInference parallelInference;
    private final NativeImageLoader loader;

    public NsfwUtil() throws IOException, UnsupportedKerasConfigurationException, InvalidKerasConfigurationException {
        model = KerasModelImport.importKerasModelAndWeights(new ClassPathResource("model/nsfw.299x299.h5").getInputStream());
        // use parallelInference
        parallelInference = new ParallelInference.Builder(model)
                        .inferenceMode(InferenceMode.BATCHED)
                        .batchLimit(32)
                        .workers(2)
                        .build();
        loader = new NativeImageLoader(299, 299, 3, new ColorConversionTransform(COLOR_BGR2RGB));
    }

    @Async
    public CompletableFuture<AnalysisResult> getResult(String url){
        try (InputStream inputStream = Unirest.get(url)
                .asObjectAsync(RawResponse::getContent)
                .get()
                .getBody();
             INDArray matrix = loader.asMatrix(inputStream, false);
            // use parallelInference.output
             INDArray output = parallelInference.output(matrix.div(255))){
            return CompletableFuture.completedFuture(new AnalysisResult(output.data().asDouble()));
        }catch (Exception e){
            throw new RuntimeException();
        }
    }
}
```
I still seem to have the results overwritten even after I change it to this. How should I use the model to detect images in multiple threads?

Although the model is not thread-safe, I see that the `model.outputSingle` method does use synchronized.

**Comment by agibsonccc** [comment]
@visionki  yes that will work. The main issue is other aspects like ndarrays aren't. That's why we do a per core duplication of the model and provide a unified wrapper. Please post further clarifications to the forums https://community.konduit.ai/ . I am locking this.
